### ISSUE TITLE
Enforce UK spelling?

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#10040]
I found a list of UK/US spelling differences at https://ac.bslw.com/community/wiki/index.php/British_to_American_Spelling

Building on #10023 I could add this.  I did a test run and left out license and program (boilerplate apache license text).  It complains often "checks should be cheques" -- should it?
And then these 30 errors are left:
```
doc/man1/openssl-ca.pod:1: found 'enrollment' should use 'enrolment'
doc/man1/openssl-crl2pkcs7.pod:1: found 'enrollment' should use 'enrolment'
doc/man1/openssl-nseq.pod:1: found 'enrollment' should use 'enrolment'
doc/man1/openssl-req.pod:1: found 'organization' should use 'organisation'
doc/man1/openssl-req.pod:1: found 'organizational' should use 'organisational'
doc/man1/openssl-spkac.pod:1: found 'enrollment' should use 'enrolment'
doc/man1/openssl.pod:1: found 'behavior' should use 'behaviour'
doc/man3/BIO_s_fd.pod:1: found 'behavior' should use 'behaviour'
doc/man3/EVP_CIPHER_meth_new.pod:1: found 'optimization' should use 'optimisation'
doc/man3/EVP_PKEY_keygen.pod:1: found 'dialog' should use 'dialogue'
doc/man3/OSSL_CMP_CTX_new.pod:1: found 'enrollment' should use 'enrolment'
doc/man3/OSSL_CMP_CTX_new.pod:1: found 'behavior' should use 'behaviour'
doc/man3/OSSL_PARAM.pod:1: found 'organization' should use 'organisation'
doc/man3/OSSL_PARAM.pod:1: found 'organized' should use 'organised'
doc/man3/OSSL_STORE_LOADER.pod:1: found 'mold' should use 'mould'
doc/man3/OSSL_trace_enabled.pod:1: found 'optimization' should use 'optimisation'
doc/man3/PEM_read_bio_ex.pod:1: found 'behavior' should use 'behaviour'
doc/man3/PKCS7_verify.pod:1: found 'behavior' should use 'behaviour'
doc/man3/SSL_CTX_set_client_cert_cb.pod:1: found 'behavior' should use 'behaviour'
doc/man3/SSL_CTX_set_client_hello_cb.pod:1: found 'behavior' should use 'behaviour'
doc/man3/SSL_CTX_set_default_passwd_cb.pod:1: found 'dialog' should use 'dialogue'
doc/man3/SSL_CTX_set_record_padding_callback.pod:1: found 'behavior' should use 'behaviour'
doc/man3/SSL_CTX_set_timeout.pod:1: found 'realization' should use 'realisation'
doc/man3/SSL_CTX_set_tmp_ecdh.pod:1: found 'favor' should use 'favour'
doc/man3/UI_create_method.pod:1: found 'dialog' should use 'dialogue'
doc/man3/UI_new.pod:1: found 'dialog' should use 'dialogue'
doc/man3/X509_dup.pod:1: found 'behavior' should use 'behaviour'
doc/man3/X509_NAME_add_entry_by_txt.pod:1: found 'organization' should use 'organisation'
doc/man3/X509_STORE_add_cert.pod:1: found 'behavior' should use 'behaviour'
doc/man5/x509v3_config.pod:1: found 'organization' should use 'organisation'
doc/man7/property.pod:1: found 'favor' should use 'favour'
```

**Comment by levitte** [comment]
> It complains often "checks should be cheques" -- should it?

That sounds wrong for us.  As I understand it, a "cheque" is that signed piece of paper you pay with instead of cash, while "check" is proper spelling for the less financial meaning.  @mattcaswell might want to fill you in on that.  But yeah, if our docs start having a lot of "cheques", I'll start worrying :wink:

**Comment by richsalz** [comment]
Yeah, I think we just ignore cheque for the reasons you state. I was actually kinda surprised about how few things it found.

**Comment by richsalz** [comment]
As for "mold" vs "mould" my solution would be to use "convert" in that POD page.

**Comment by mattcaswell** [comment]
I like this idea! :-)

Yes, a "cheque" is a "signed piece of paper you pay with instead of cash", so we can ignore any complaints about that.

"Dialog" is an interesting one. The correct UK way to spell this is indeed "Dialogue" when talking about a conversation between two or more people. Of course in a software sense we often talk about a "dialog box". Since this isn't really used in commonly spoken English except in specialist IT circles I think the spelling tends to be driven by the name used in software APIs which is normally spelled "dialog" after the US spelling. I've got no reference for that so maybe its just me spelling it wrong, but "dialogue box" looks odd to me. I think the spelling in the man pages is used in the sense of "dialog box".

**Comment by richsalz** [comment]
I haven't looked yet, but here's the four places where it's found:
```
; ./util/find-doc-nits -n | grep dialog
doc/man3/EVP_PKEY_keygen.pod:1: found 'dialog' should use 'dialogue'
doc/man3/SSL_CTX_set_default_passwd_cb.pod:1: found 'dialog' should use 'dialogue'
doc/man3/UI_create_method.pod:1: found 'dialog' should use 'dialogue'
doc/man3/UI_new.pod:1: found 'dialog' should use 'dialogue'
; 
```

I will remove dialogue/dialog.

But I need #10023 to be reviewed and merged before I fix this.

The current UK/US wordlist is this:
```
'behavior' => 'behaviour',
'dialog' => 'dialogue',
'enrollment' => 'enrolment',
'favor' => 'favour',
'mold' => 'mould',
'optimization' => 'optimisation',
'organization' => 'organisation',
'organizational' => 'organisational',
'organized' => 'organised',
'realization' => 'realisation',
```

and it finds 25 non-dialog/ue errors.

**Comment by richsalz** [comment]
Since the PR was closed, I assume the OMC doesn't want to enforce this so I am closing this issue.  Someone in authority can of course re-open (but they have to explain why #10079 was closed :)
