### ISSUE TITLE
Mechanism to override a default property from the configuration file  at specific call site

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#10129]
In older OpenSSL versions that supported FIPS mode operation the various EVP and asymmetric key operations supported setting NON_FIPS_ALLOW flag which would bypass the limitations of the OpenSSL to FIPS approved or allowed operations. This was useful for applications such where the use of the non-approved crypto algorithm was not relevant for security.

We would need a similar mechanism in OpenSSL 3.0 - if the default configuration file specifies fips=yes as default property and the application using the FIPS validated OpenSSL provider wants to in general work in FIPS compliant mode but for some legacy operation that is not relevant for security needs to use some non-approved algorithm, it needs to be able to override the fips=yes default property from the config file via an API call.

It is crucial that the application does not want to affect any other OpenSSL calls - they should be fully affected by the fips=yes setting from the config file.

**Comment by mattcaswell** [comment]
@paulidale should confirm, but I believe this is already possible. It's certainly in the design to be able to do this. The default configuration file can load the fips provider and whichever other providers might be needed (default, legacy etc). The default properties can specify "fips=yes" to ensure that fips algorithms are always fetched unless an application specifies otherwise. Where an application wishes to override the default they can specify per fetch properties that include the string "-fips", e.g.

EVP_MD_fetch(NULL, "MD5", "-fips");

This has the effect of meaning that the fips property is not specified so the algorithm can be fetched from any provider that has the algorithm (including the FIPS provider).

See the section "Multilevel Queries" in the design doc:

https://www.openssl.org/docs/OpenSSL300Design.html

**Comment by levitte** [comment]
I have never really looked at this before.  I just looked through the old FOM and saw how it was done there, and weelllllllll...  I suppose we can check those flags in libcrypto at init time, and decide what default properties should be use in an implicit fetch.  If we do that, we will probably need some kind of "alternate default properties" for this use case.

@mattcaswell, @paulidale, @slontis, do pitch in, please.

**Comment by mattcaswell** [comment]
> I have never really looked at this before. I just looked through the old FOM and saw how it was done there, and weelllllllll... I suppose we can check those flags in libcrypto at init time, and decide what default properties should be use in an implicit fetch. If we do that, we will probably need some kind of "alternate default properties" for this use case.

I'm not sure what scenario you are thinking about. Which flags in particular are you referring to?

**Comment by levitte** [comment]
I refer to exactly the flag @t8m is talking about.  Did you try to `git grep NON_FIPS_ALLOW` in 1.1.1 or in the FOM source?  It shows this little tid-bit among others:

``` C
ssl/s3_enc.c:    EVP_MD_CTX_set_flags(m5, EVP_MD_CTX_FLAG_NON_FIPS_ALLOW);
```

**Comment by levitte** [comment]
BTW, those flags are still present in master, no need to go look anywhere else, unless you're curious

**Comment by mattcaswell** [comment]
Oh, right I see what you mean now. Two ways of handling this spring to mind:

1) Ignore this flag completely. It wasn't supported in 1.1.x so do we need to support it in master? You can get the same effect as this by using explicit fetch in the manner I described above

or

2) We could support it by saying "if we do an implicit fetch and that flag is set then we use the property string '-fips'" instead. That just has the effect of removing any "fips=yes" that might be in the global properties.

**Comment by levitte** [comment]
I could see us going with either choice, really.  Considering that the FOM is 1.0.2 and is then inherently incompatible with 1.1.0 or anything above that, applications that want to remain FIPS validated will have to do some amount of rewriting anyway, so one might wonder "what's another explicit fetch between rewrites?"

On the other hand, that adds *another* hurdle for upgrade work, and considering how simple it turns out to handle that flag, that might be worth the while to provide good user service?

**Comment by levitte** [comment]
Either way, it remains an internal hack that only works with *our* FIPS provider, as libcrypto isn't really supposed to know much about the providers.  If someone produces an alternative FIPS provider with another property, this flag will simply not work.

**Comment by richsalz** [comment]
I am against supporting the flag.  It only worked in 1.0.2.  The explicit fetch is the only thing we should support.

**Comment by t8m** [comment]
OK, I am sorry I did not realize there is already the negative override of properties. So this feature is already in.

**Comment by t8m** [comment]
As for the non-fips flag support - it would be convenient if it was there as it would be one less changes of applications that would be needed for 3.0 and FIPS. On the other hand I understand it would be a quite hackish thing.
As for 3rd party FIPS validated module providers - I suppose they could want to use the fips=yes property, why they wouldn't? Especially if they wanted to seamlessly replace functionality of the OpenSSL fips provider.

**Comment by t8m** [comment]
> I could see us going with either choice, really. Considering that the FOM is 1.0.2 and is then inherently incompatible with 1.1.0 or anything above that, applications that want to remain FIPS validated will have to do some amount of rewriting anyway, so one might wonder "what's another explicit fetch between rewrites?"

The applications are mostly rewritten already for 1.1.x. And, as the NON_FIPS_ALLOW flag was there (although as no-op), the application set it. Of course, conveniently, for our downstream 1.1.1 FIPS validation we made the flag to do the expected thing.

**Comment by slontis** [comment]
I would prefer this flag to be completely removed at some point..

**Comment by paulidale** [comment]
There are several ways to to allow non-FIPS algorithms:

1. Fetching with _-fips_ will disable the global _fips=yes_ for the one lookup.
1. Using a different library context which only has the default provider loaded will find non-FIPS algorithms.
1. Fetching with _fips=no_ would avoid using any FIPS algorithms for the one lookup.
1. There is a final dangerous option which is left for the reader to discover.

Matt suggested the first option  The second provides a clearer boundary between FIPS and non-FIPS (by only loading the FIPS provider in its library context).  I'd recommend either of the first two options.

The NON_FIPS_ALLOW flag should die.  The compatibility target is for 1.1.1 applications moving forwards and we've always stated that using FIPS in 3.0 will require application changes.  We don't need a fifth way to achieve the desired lookup, especially when it is a kludge.

**Comment by mattcaswell** [comment]
Nice summary @paulidale! I am intrigued by the "dangerous option"!

**Comment by levitte** [comment]
> I am intrigued by the "dangerous option"!

So am I

**Comment by richsalz** [comment]
Perhaps ```NON_FIPS_ALLOWED``` should be *removed*  This will cause compile-time errors rather than obscure run-time errors.

**Comment by levitte** [comment]
Yes!  That!  ^^

**Comment by levitte** [comment]
Oooohhhh, that could prove interestingly challenging:

https://github.com/openssl/openssl/blob/99435164ac55fda18922e278316ad76305f338ad/crypto/x509/x509_cmp.c#L215-L220

Does that mean that we want to do an explicit fetch there ourselves?  We can!  But that also sets in stone that any FIPSy provider *shall* define the property "fips=yes"

**Comment by levitte** [comment]
...  the more I think of it, the more I find that we can't get away from that in a sane away.  So the "fips=yes" property acts like a flag, then?

**Comment by mattcaswell** [comment]
> Does that mean that we want to do an explicit fetch there ourselves? We can! But that also sets in stone that any FIPSy provider shall define the property "fips=yes"

I have no problem with that.

**Comment by levitte** [comment]
See #10138

**Comment by paulidale** [comment]
I agree, let's remove the option or at least deprecate it.  Our policies require it to be deprecated for a major revision, so let's do it now in anticipation of a 4.0 removal.

The _dangerous option_ involves the `?` operator...

**Comment by richsalz** [comment]
Remove the define.  It is a security issue.

**Comment by t8m** [comment]
Removing it would break API which we said we wouldn't do. Also why is it a security issue, could you elaborate, please?

**Comment by richsalz** [comment]
We said we would *try* not to break the API.  It is a security issue because of https://github.com/openssl/openssl/issues/10129#issuecomment-540653023  Code which used to work because the flag was ignored (and there was no FIPS module), could now fail at run-time if someone wanted MD5 and used the flag.

Removing the flag means applications that use it will find out *at compile time* that their code needs to be changed. Not removing the flag means that applications will compile, but then fail at runtime because, for example, the lookup for MD5 will fail if FIPS is set.

Make sense?

**Comment by levitte** [comment]
There's really only two ways to handle it properly:

1.  put in code that "translates" any `NON_FIPS_ALLOW` flags to modern terms (i.e. do implicit fetches with "-fips").
2.  Remove the flag and force applications to do explicit fetches with  "-fips"

There really is no middle ground between the two.  Keeping the flag an ignoring would be *bad* (not just bad behaviour, but ***bad***), and since we now know the issue, it would be *willfully **bad***.

@t8m, it looks to me that you accepted variant 2 in https://github.com/openssl/openssl/issues/10129#issuecomment-539988187 ...  Was that a misunderstanding?

Either way, the two points I listed is the choice we have to make, there's no way around that.

**Comment by t8m** [comment]
I still think interpretation of this as a security issue is fairly exaggerated. However you're right that it makes more sense to remove it.

No, that was not a misunderstanding, I accept the 2.
