### ISSUE TITLE
rand_meth_st structure is wrong in 1.1.1 docs @ https://www.openssl.org/docs/man1.1.1/man3/RAND_get_rand_method.html

### ISSUE THREAD

**Issue by jacobmaynard** [openssl/openssl#10199]
The current structure def for rand_meth_st is not documented correctly online.

The code level def in 1.1.1 shows the seed function returning an int however on the documentation page, it's a void return. 

Also, the add function now takes a double as the 3rd argument however the docs still show an int.

I couldn't find a commit for an explanation as to why this was changed, so maybe a blurb describing the expected range of values in the return for the seed function would be good.

Thanks!

Jake

**Comment by mattcaswell** [comment]
The add function was introduced in commit eb952088f in January 2000 with an int as the entropy estimate value - and the docs were written at that time. It was changed a month later by commit 853f757e in order to "Allow for higher granularity of entropy estimates by using 'double' instead of 'unsigned' counters.", but the documentation wasn't updated at the same time....and no one noticed for nearly 20 years. :-)

The return type of the seed function was changed by commit b6dcdbfc which had this CHANGES entry:

> Extensive audit of libcrypto with DEBUG_UNUSED. Fix many cases where
     return value is ignored. NB. The functions RAND_add(), RAND_seed(),
     BIO_set_cipher() and some obscure PEM functions were changed so they
     can now return an error. The RAND changes required a change to the
     RAND_METHOD structure.
     [Steve Henson]

That commit was in September 2009 and neglected to update the documentation...and no one noticed for 10 years!

**Comment by jacobmaynard** [comment]
Ouch! Well... Hopefully I can make some headway here. I'm actually considering reverting the seeding change in our customized code just to get around a build error until I can find a way to implement the return value in a way that makes sense. Thanks for the prompt response!

On another note, the history for the file ended in 2015 in the git branch so it was hard to peek back further in time. Do you have any suggestions for how to better come up to speed on openssl commit history?

**Comment by mattcaswell** [comment]
I assume you are referring to rand.h which was moved into its current location in 2015. If instead of `git log` you use `git log --follow` git will give the log all the way back in history even through file renames/moves and you can go all the way back to its original import into the repo from the precursor SSLeay project back in 1998.

**Comment by jacobmaynard** [comment]
Thanks Matt! Much appreciated!

**Comment by mspncp** [comment]
> git log --follow 

Thanks for the hint!
