### ISSUE TITLE
Request over socks5 proxy fails over openssl 1.1.1d but works over 1.0.2t

### ISSUE THREAD

**Issue by gorune** [openssl/openssl#10204]
Please refer to [this stackoverflow post](https://stackoverflow.com/questions/58284829/difference-in-status-of-the-same-request-over-tor-in-python3-6-and-python3-7) for reproducibility. Here are the important bits:

Trying a request over socks5 proxy on 2 very similar environments one with python 3.6.5 and one with 3.7.4, works on the first but not the second.

Difference between the 2 environments:
cryptography              2.3.1
openssl                   1.0.2t
python                    3.6.5

cryptography              2.7
openssl                   1.1.1d
python                    3.7.4

I downgraded openssl to 1.0.2t, it downgraded cryptography to the same version as python 3.6.5 above and downgraded python to 3.7.0, and upgrading python will upgrade along openssl and cryptography. With the downgrade python 3.7 request worked fine.

I believe the issue is from openssl, so is this an intended behaviour? Or is this a bug?

**Comment by mattcaswell** [comment]
Why do you think this is an OpenSSL issue? Your SO post says that you got a 403 response from the server. 403 means:

> 
> The 403 (Forbidden) status code indicates that the server understood
>    the request but refuses to authorize it.  A server that wishes to
>    make public why the request has been forbidden can describe that
>    reason in the response payload (if any).

So this sounds like the TLS handshake was successful, but the server then didn't authorise it at the HTTP layer. You need to find out why it didn't authorise it. That *could* be due to a TLS level issue (e.g. specifying an incorrect SNI host), but it could equally be an issue at the HTTP layer.
