### ISSUE TITLE
`EC_POINT_hex2point` incorrectly decodes the point at infinity

### ISSUE THREAD

**Issue by incertia** [openssl/openssl#10258]
`EC_POINT_hex2point` incorrectly decodes the point at infinity, which is encoded as the hexstring `00`. This is because `hex2point` calls `oct2point` after converting `00` into a `BIGNUM` and calling `BN_bn2bin` on this bignum, which outputs 0 bytes whereas the decoder is expecting exactly `1` `0` byte in this case.

**Comment by romen** [comment]
So, I digged a bit into this.

This behavior has been there since `1.0.2`.

It appears `EC_POINT_hex2point()` and its callee `EC_POINT_bn2point()` have not supported decoding `00` as the point at infinity, even though `EC_POINT_point2hex()` might encode the point at infinity as `00`.

It is unclear to me how to proceed.

Maybe the fix is actually throwing an error already on `EC_POINT_point2hex()` if operating on the point at infinity.

Fixing the decoding step might open more security risks than it is worth it.

Ping @mattcaswell and @bbbrumley for feedback.

**Comment by bbbrumley** [comment]
Check 2.3.3 [here](https://www.secg.org/sec1-v2.pdf), with the caveat this is only one standard's opinion.

(I personally feel "import" or "export" of INF point is meaningless -- at the engineering view, it is a low level implementation detail.)

**Comment by romen** [comment]
> Check 2.3.3 [here](https://www.secg.org/sec1-v2.pdf), with the caveat this is only one standard's opinion.
> 
> (I personally feel "import" or "export" of INF point is meaningless -- at the engineering view, it is a low level implementation detail.)

So it seems we are conforming to 2.3.3 when encoding, but not to 2.3.4 when decoding.

**Comment by romen** [comment]
I will open a PR to address the behavior in 1.1.1 and master, but it does not fit in the cop of 1.0.2 and 1.1.0

**Comment by romen** [comment]
See #10329 for a fix
