### ISSUE TITLE
Broken link @ https://www.openssl.org/docs/man1.1.0/man3/X509_get_extension_flags.html

### ISSUE THREAD

**Issue by jacobmaynard** [openssl/openssl#10263]
There is a link "X509_check_purpose(3)" @ https://www.openssl.org/docs/man1.1.0/man3/X509_get_extension_flags.html that leads to a 404 error when clicked.

**Comment by jacobmaynard** [comment]
The same link is broken in the 1.1.1 version.

**Comment by richsalz** [comment]
yes, that manpage does not exist.  unfortunately the tooling to make the website leaves such broken links.

**Comment by levitte** [comment]
If someone writes docs for that function, it will appear! PR welcome!

**Comment by jacobmaynard** [comment]
> If someone writes docs for that function, it will appear! PR welcome!

I'm happy to help. Just not sure how.

**Comment by mattcaswell** [comment]
> I'm happy to help. Just not sure how.

The effort required here is to research the function of `X509_check_purpose` by examining the source and create an appropriate man page for it in `doc/man3`. See other pages for examples of our style.

**Comment by jacobmaynard** [comment]
@mattcaswell, I have what I think is a decent first draft. Please let me know how I can contribute, or get this reviewed.

Thanks a bunch!

Jake

**Comment by mattcaswell** [comment]
You need to create a github Pull Request so that we can review your proposed changes. See the github help pages for info on that:

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

I also recommend you read the CONTRIBUTING file for some OpenSSL specific guidance on how to make contributions:

https://github.com/openssl/openssl/blob/master/CONTRIBUTING

**Comment by DDvO** [comment]
> yes, that manpage does not exist. unfortunately the tooling to make the website leaves such broken links.

Meanwhile, `make doc-nitx` reports such issues, e.g.: "reference to non-existing X509_check_purpose(3)",
which gets flagged in the respective CI **check_docs** such that broken doc-internal links should no more happen.
