### ISSUE TITLE
libssl.so.1.1: cannot open shared object file: Permission denied

### ISSUE THREAD

**Issue by mattjma** [openssl/openssl#10270]
After openssl installed on centos 6.10 on Oracle cloud,  enter the openssl in the ssh, it shows a message as "libssl.so.1.1: cannot open shared object file: Permission denied", but it works in root.

**Comment by levitte** [comment]
Can you figure out the permissions for that file?

**Comment by mspncp** [comment]
I assume you installed openssl using the centos package manager (yum)? Or did you compile and install openssl yourself? Hopefully not the latter, because it is not a good idea to replace system libraries of your distribution with libraries built by yourself (unless you know what you are doing).

In either case, it is just a normal problem with linux file permissions. Probably the shared library file does not have the 'readable' bit set for 'others'. Try the following commands on your computer:

```
~$ which openssl
/usr/bin/openssl

~$ ldd $(which openssl)
        linux-vdso.so.1 =>  (0x00007ffff5f83000)
        libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f6f160c0000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f6f15c70000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6f158a0000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6f15680000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6f16400000)
```
Now look for the full path of `libssl.so.1.1.0` in the ldd output and do an `ls -l` to check ownership and file permissions. You should see something like `-rw-r--r-- 1 root root` at the beginning.

```
~$ ls -l /lib/x86_64-linux-gnu/libssl.so.1.1.0
-rw-r--r-- 1 root root 428384 Apr 18  2018 /lib/x86_64-linux-gnu/libssl.so.1.1.0
```

This is not an OpenSSL specific problem. Please ask a local linux expert if you need more help.

**Comment by mspncp** [comment]
> Can you figure out the permissions for that file?

You beat me be seconds again @levitte. But my reply was definitely much longer ;-).

**Comment by levitte** [comment]
I'm wondering if installing on Oracle cloud might have something to do with it...

**Comment by mspncp** [comment]
Well, maybe I shouldn’t have closes the ticket immediately. Let’s wait for a reply from @mattjma first.

**Comment by mattjma** [comment]
libssl.so.1.1 -> /usr/local/lib64/libssl.so.1.1, the last part blinks even has the 777 mod
