### ISSUE TITLE
clang linker complaining about -z option

### ISSUE THREAD

**Issue by p-steuer** [openssl/openssl#10342]
Build error:
```
make depend && make _all
make[1]: Entering directory `/home/past/Projects/openssl/openssl'
make[1]: Leaving directory `/home/past/Projects/openssl/openssl'
make[1]: Entering directory `/home/past/Projects/openssl/openssl'
clang -fPIC -pthread -m64 -Wa,--noexecstack -Qunused-arguments -Wall -O3 -L. -z defs -Wl,-znodelete -shared -Wl,-Bsymbolic   \
        -o engines/capi.so -Wl,--version-script=engines/capi.ld \
        engines/capi-dso-e_capi.o \
        -lcrypto -ldl -pthread 
clang: error: unknown argument: '-z'
clang: error: no such file or directory: 'defs'
make[1]: *** [engines/capi.so] Error 1
make[1]: Leaving directory `/home/past/Projects/openssl/openssl'
make: *** [all] Error 2
```

Steps to reproduce on x86_64 linux:
```
./config CC=clang
make
```

**Comment by kroeckx** [comment]
That should be -Wl,-z,defs

**Comment by mspncp** [comment]
Question to @openssl/omc: 

IMHO it is not optimal if issues opened by _committers_ remain in untriaged state, i.e, keep their 'issue: *' label.

How should we deal with the case when a _committer_ opens a bug report? Should the creator of the ticket set the label immediately to 'triaged: bug' instead of 'issue: bug report' (which he could do before even opening it)? Or should this be the responsibility of the first reviewer?

**Comment by mattcaswell** [comment]
> How should we deal with the case when a committer opens a bug report? 

Agreed. Committers are assumed to know what they're doing and only open a bug report if it really is a bug report. There doesn't need to be an independent triage for that. Committers should just set the "triaged" labels immediately (and remove the "issue: bug report" labels).

**Comment by levitte** [comment]
> How should we deal with the case when a _committer_ opens a bug report? Should the creator of the ticket set the label immediately to 'triaged: bug' instead of 'issue: bug report' (which he could do before even opening it)? Or should this be the responsibility of the first reviewer? 

First reviewer.  The `triage` labels can work as confirmation that the issue in question *is* indeed a bug

**Comment by levitte** [comment]
There are quite a lot of aspects to this project...  I can definitely see reason where a committer is unsure.  For example, libssl is a weak point for me, but might still make a bug report because something builds weird in a branch of mine, and it may turn out that I made a boo-boo.  Asking *me* to self-triage in such a case is too much to ask, and will just have me not report anything at all.

**Comment by mspncp** [comment]
I agree, with one little amendment: the reporter _can_ set it to the triaged state if he is sure that it is a bug, but he _doesn't have to_, in particular if he is not sure about it. In this case it should be done by the first team member who confirms the bug.

**Comment by levitte** [comment]
That sounds good

**Comment by p-steuer** [comment]
Looks like its fixed on master. Closing.
