### ISSUE TITLE
Potential Null Dereference

### ISSUE THREAD

**Issue by ManSoSec** [openssl/openssl#10347]
Return value of `BIO_get_data` and `BIO_next` are checked here:
https://github.com/openssl/openssl/blob/aec9667bd19a8ca9bdd519db3a231a95b9e92674/crypto/evp/bio_b64.c#L455-L457

While some of the checks on `ctx` and/or `next` are missed here:
https://github.com/openssl/openssl/blob/aec9667bd19a8ca9bdd519db3a231a95b9e92674/crypto/evp/bio_enc.c#L303-L305

https://github.com/openssl/openssl/blob/aec9667bd19a8ca9bdd519db3a231a95b9e92674/crypto/evp/bio_ok.c#L331-L332

https://github.com/openssl/openssl/blob/aec9667bd19a8ca9bdd519db3a231a95b9e92674/crypto/evp/bio_md.c#L142-L143

**Comment by mattcaswell** [comment]
The check on `ctx` in the first link is harmless but arguably unnecessary since it should never happen that it is NULL. Otherwise some earlier bug has happened. 

Similarly the check of `next` in the first link is harmless but arguably unnecessary because `next` is only every used in a call to `BIO_ctrl` which just fails if the passed BIO is NULL. This is true for all the cases you highlight.

Therefore this does not seem to be a bug.
