### ISSUE TITLE
Missing check on return value of s->method->ssl_new

### ISSUE THREAD

**Issue by ManSoSec** [openssl/openssl#10345]
return value of `s->method->ssl_new()` is checked here:
https://github.com/openssl/openssl/blob/aec9667bd19a8ca9bdd519db3a231a95b9e92674/ssl/ssl_lib.c#L644
https://github.com/openssl/openssl/blob/aec9667bd19a8ca9bdd519db3a231a95b9e92674/ssl/ssl_lib.c#L1590

While it is missed here:
https://github.com/openssl/openssl/blob/aec9667bd19a8ca9bdd519db3a231a95b9e92674/ssl/ssl_lib.c#L3608

I think it might lead to potential mal-functioning or NULL dereference.

Thanks

**Comment by mattcaswell** [comment]
Look like correct behaviour to me. The referenced line stores the success/fail return value in `ret` and propagates it as the result of the enclosing function, i.e. if `s->method->ssl_new()` fails then `SSL_set_ssl_method()` fails.

**Comment by mspncp** [comment]
@ManSoSec it would be better if you would post permanent links (with sha1 commit IDs in the URL),  in your reports instead of links containing branch names.

The permanent links have two advantages:

- The link will always point to the right location, and cannot become outdated when the target file is changed in the future
- GitHub will display permanent links inline as fancy code windows

**non-permanent link**

https://github.com/openssl/openssl/blob/master/ssl/ssl_lib.c#L644

**permanent link**

https://github.com/openssl/openssl/blob/aec9667bd19a8ca9bdd519db3a231a95b9e92674/ssl/ssl_lib.c#L644

**HOWTO: convert a non-permanent link to a permanent link**

To do the conversion, just follow the [non-permanent link](https://github.com/openssl/openssl/blob/master/ssl/ssl_lib.c#L644) and then press the 'y' key while you are visiting the page. The URL will change to a permanent link. (Press the '?' key to see more fancy GitHub keyboard shortcuts.)

Apropos code windows: You can select line ranges by clicking the first line and shift-clicking the last line:

https://github.com/openssl/openssl/blob/aec9667bd19a8ca9bdd519db3a231a95b9e92674/ssl/ssl_lib.c#L641-L649

**Comment by mspncp** [comment]
As a demonstration, I converted the links in your initial description to permanent links. Hope you like the result :-).

**Comment by ManSoSec** [comment]
@mspncp Thanks for the hint! I will do that for future reports.

**Comment by mspncp** [comment]
If you like this, you might also be interested in my [ghlink](https://github.com/openssl/tools/blob/master/review-tools/ghlink) script, a perl script which can be used as a shell filter to convert git grep hits into URLs:

**Markdown links**

**~/src/openssl$ git grep -n ssl_clear | ghlink --markdown**

[ssl/d1_lib.c:102:](https://github.com/openssl/openssl/blob/d7b2124a42/ssl/d1_lib.c#L102)     if (!s->method->ssl_clear(s))
[ssl/s3_lib.c:3306:](https://github.com/openssl/openssl/blob/d7b2124a42/ssl/s3_lib.c#L3306)     if (!s->method->ssl_clear(s))
[ssl/ssl_lib.c:572:](https://github.com/openssl/openssl/blob/d7b2124a42/ssl/ssl_lib.c#L572)     ssl_clear_cipher_ctx(s);
[ssl/ssl_lib.c:573:](https://github.com/openssl/openssl/blob/d7b2124a42/ssl/ssl_lib.c#L573)     ssl_clear_hash_ctx(&s->read_hash);

_...truncated..._

**Permanent links**

**~/src/openssl$ git grep -n ssl_clear | ghlink --permanent**

https://github.com/openssl/openssl/blob/d7b2124a428f9e00ed7647554b5be7153aac71f6/ssl/d1_lib.c#L102     if (!s->method->ssl_clear(s))
https://github.com/openssl/openssl/blob/d7b2124a428f9e00ed7647554b5be7153aac71f6/ssl/s3_lib.c#L3306     if (!s->method->ssl_clear(s))
https://github.com/openssl/openssl/blob/d7b2124a428f9e00ed7647554b5be7153aac71f6/ssl/ssl_lib.c#L572     ssl_clear_cipher_ctx(s);
https://github.com/openssl/openssl/blob/d7b2124a428f9e00ed7647554b5be7153aac71f6/ssl/ssl_lib.c#L573     ssl_clear_hash_ctx(&s->read_hash);

_...truncated..._

**Usage**

```
~/src/openssl$ ghlink --help
Usage:
      ghlink [<option>...] [<file>...]

    Concatenate the given file(s) to standard output, converting repository
    locations into GitHub links. If no file is given, read from stdin.

Options:
    --help
        Print a brief help message and exit.

    --man
        Print the manual page and exit.

    --markdown | -m
        Convert the locations to links in markdown syntax, with the location
        in square brackets, followed by the link in parentheses.

    --permanent | -p
        Always resolve branches to (unabbreviated) commit-ids for printing
        the link.

    --list | -l
        List only the links of all locations found, and omit the resto of th
        text. This option is useful together with the --permanent option to
        create GitHub permalinks, see EXAMPLES section below.
```

**Comment by ManSoSec** [comment]
@mspncp That's pretty cool! Thanks!
