### ISSUE TITLE
Deprecate EC_POINT_bn2point and EC_POINT_point2bn

### ISSUE THREAD

**Issue by davidben** [openssl/openssl#10366]
`EC_POINT_bn2point` and `EC_POINT_point2bn` do not make much sense. EC point serialization formats are not individual big-endian integers. #10329 is an example of the mismatch. Perhaps put them on the path for deprecation?

(@romen for thoughts)

**Comment by romen** [comment]
I have been thinking about this, I agree that `EC_POINT_bn2point` and `EC_POINT_point2bn` are good candidates for streamlining the API.

I think `EC_POINT_point2bn` can eventually just go away, while probably the functionality of `EC_POINT_bn2point` should survive internally to avoid duplicating code to convert an arbitrary long hex string into an octet buffer, but it can be implemented inside `EC_POINT_hex2point`.

I would be up to propose a PR for deprecating, but I'd like to know @openssl/omc opinion about it, because it emerged that not everyone has the same opinion about deprecating existing API.

**Comment by davidben** [comment]
`EC_POINT_bn2point` is not really suitable for `EC_POINT_hex2point` anyway. Converting a hex string to an octet buffer and converting it into a `BIGNUM` are not the same operation. The latter will chop off leading zeros.

That should probably be considered a bug in `EC_POINT_hex2point` today. It shouldn't accept `0004<x-coord><y-coord>` as a substitute for `04<x-coord><y-coord>`

**Comment by paulidale** [comment]
To be deprecated in 3.0.
