### ISSUE TITLE
Error creating SSL context (SSL_CTX_new) (INDY)

### ISSUE THREAD

**Issue by gofmanalex** [openssl/openssl#10528]
Hi all,

I use INDY components with Delphi and some stations sometimes get error when attempts creating SSL context

Indy error code 5
EIdOSSLCreatingContextError
Error creating SSL context

The error is occurring in IdSSLOpenSSL InitContext. 
    fContext := SSL_CTX_new(SSLMethod);
fContext is nil.

I use SSL23 method. TLS method doesn't work
I use 1.0.2r versions of dlls

Thank for any advice?

**Comment by mattcaswell** [comment]
Have you checked the OPENSSL error queue for any useful error messages, e.g. by using the `ERR_print_errors_fp` function.

**Comment by gofmanalex** [comment]
error:140A90F1:lib(20):func(169):reason(241)
error:140A90F1:SSL routines: SSL_CTX_new: unable to load ssl2 md5 routines


Sometimes get EIdOSSLCreatingContextError without error code

**Comment by mattcaswell** [comment]
The most likely explanation for this error is if you have attempted to build the library using the "no-md5" build time option. That option just doesn't work ("won't fix" bug) in 1.0.2 and was removed from  later versions as a result.

So, on the failing machines, how did you build the version of OpenSSL there?

**Comment by gofmanalex** [comment]
I use dlls from  openssl-1.0.2r-i386-win32
    ssleay32.dll  ver 1.0.2.18   
    libeay32.dll  ver 1.0.2.18

**Comment by mattcaswell** [comment]
> I use dlls from openssl-1.0.2r-i386-win32
ssleay32.dll ver 1.0.2.18
libeay32.dll ver 1.0.2.18

Those version numbers don't look like something the OpenSSL Project creates. Did you build the dlls from source yourself, or did you download the binaries from somewhere else? (If so - where?)

**Comment by mattcaswell** [comment]
Another theory I have for what could cause this: If you fail to call `SSL_library_init()` then I think this could happen.

**Comment by gofmanalex** [comment]
My project is written in Delphi. I just use TIdHTTP component of INDY.
The component use the dll.  I don't build or load dll manually.
The dll taken from https://indy.fulgan.com/SSL

**Comment by mattcaswell** [comment]
Has `SSL_library_init()` always been called before the first call to `SSL_CTX_new()`?

**Comment by gofmanalex** [comment]
Hi,
The saga continues. Solution still not found. 
I upgraded the INDY components what i use up to 10.5520 version and openSSL libraries to 1.0.2t version, but a problem still throw (sometimes).

Now i got error code: **336236785**
Error type: EIdOSSLCreatingContextError
Error creating SSL context
error:140A90F1:lib(20):func(169):reason(241)

I just use INDY TIdHTTP component with TIdSSLIOHandlerSocketOpenSSL and TIdMultiPartFormDataStream ad i don't know about

> Has SSL_library_init() always been called before the first call to SSL_CTX_new()?

I'm not initialize, not load and not free the dlls. The INDY component does all this work. (must do).

Interestingly, my other client has no such any problems.

**Comment by gofmanalex** [comment]
> Has SSL_library_init() always been called before the first call to SSL_CTX_new()?

I checked code of INDY. Yes.  SSL_library_init() always called.

**Comment by gofmanalex** [comment]
Server I want to connect to requires working with **SSLv3 only**

But When I trying to use **sslvSSLv3** I gеt error:
ErrorCode: 5
ErrorClassName: **EIdOSSLConnectError**
ErrorMessage: Error connecting with SSL.
**EOF was observed that violates the protocol**

When I tried to use **sslvSSLv23**, I often get an error:
Error code: 336236785
Error type: **EIdOSSLCreatingContextError**
**Error creating SSL context**
error:140A90F1:lib(20):func(169):reason(241)

**Comment by mattcaswell** [comment]
> But When I trying to use sslvSSLv3 I gеt error:
ErrorCode: 5
ErrorClassName: EIdOSSLConnectError
ErrorMessage: Error connecting with SSL.
EOF was observed that violates the protocol

Can you get a packet trace using wireshark of the failing communication?

> When I tried to use sslvSSLv23, I often get an error:
Error code: 336236785
Error type: EIdOSSLCreatingContextError
Error creating SSL context
error:140A90F1:lib(20):func(169):reason(241)

Often? Or Always? This error is the "unable to load ssl2 md5 routines" that is discussed above. If this works sometimes and doesn't work others then it rules out the possibility that the library has been built with the "no-md5" option (since it that case the code to initialise the ssl2-md5 digest is not even compiled in, so there is no possibility that it would *ever* work)...

...actually thinking about it more if you avoid this error based on the method you are using then that rules that out anyway. If "no-md5" was the problem then this should always fail with the same error no matter what.

So, my best guess is that there is a problem with the SSL_library_init(() call. Perhaps a race condition which means it is sometimes called and sometimes not???

**Comment by mattcaswell** [comment]
This issue is stale with no response to the last questions. Closing.
