### ISSUE TITLE
Missing null check after OPENSSL_zalloc

### ISSUE THREAD

**Issue by Liby99** [openssl/openssl#10525]
Here're places that null pointer check is missing after `OPENSSL_zalloc`. 

1. The pointer `exchange` is used directly in line 23 without being null checked.

https://github.com/openssl/openssl/blob/3c957bcd54d097167e53660fa100aa1ba85d63b5/crypto/evp/exchange.c#L21-L23

2. The pointer `signature` is also used directly in line 23. Similar to the first one

https://github.com/openssl/openssl/blob/3c957bcd54d097167e53660fa100aa1ba85d63b5/crypto/evp/pmeth_fn.c#L21-L23

3. In the function `OPENSSL_buf2hexstr`, the result of `OPENSSL_zalloc` is directly returned without null check. The dependents of `OPENSSL_buf2hexstr` are not checking null-pointers too.

https://github.com/openssl/openssl/blob/3c957bcd54d097167e53660fa100aa1ba85d63b5/crypto/o_str.c#L242

**Comment by mspncp** [comment]
cc @mattcaswell

**Comment by mspncp** [comment]
@Liby99 thank you for your report. Note that I edited your description and converted your code links to permalinks. There is an easy trick to do this: if you follow your original link, you can press the 'y' key and GitHub will convert branch references into permalinks (by replacing branch names by commit hashes), thus making them 'unmovable'. Also, it has the nice side effect that GitHub markdown renders these fancy permalink boxes instead of just links.

**Comment by Liby99** [comment]
I was indeed having trouble creating links. Thanks for your help!

**Comment by mspncp** [comment]
You're welcome. BTW, you can press the '?' key on any GitHub page, for example [here at pmeth_fn.c](https://github.com/openssl/openssl/blob/master/crypto/evp/pmeth_fn.c#L21-L23) and you'll see more useful keyboard shortcuts.

**Comment by mspncp** [comment]
One of my favourites is the "code tree warp" sequence: press `g c` ("goto code") to jump to the [source tree](https://github.com/openssl/openssl) and then press `t` (f"tree") to quickly jump to any file you like.

**Comment by Liby99** [comment]
You blow up my mind. Really useful tips! Thank you!

**Comment by mattcaswell** [comment]
Fix in #10526.
