### ISSUE TITLE
OpenSSL 1.1.1: no ASN1_TIME_dup

### ISSUE THREAD

**Issue by jrpascucci** [openssl/openssl#10600]
What's the reasoning behind the lack of ASN1_TIME_dup?
      A search of the man pages has been unenlightening.
      Same questions can be asked of _UTCTIME and _GENERALIZEDTIME as well.

While it appears to break the encapsulation, is casting to ASN1_INTEGER and using ASN1_INTEGER_dup safe enough for the time being?

I'm not sure if this is a lacuna in the library, or merely should have documentation as to the correct method of handling, so I'll submit this as a question.

Thanks,

JRP

**Comment by mattcaswell** [comment]
Probably because no-one needed it until now and it got missed.

Possible workarounds could be:
1) Just add the line `IMPLEMENT_ASN1_DUP_FUNCTION(ASN1_TIME)` somewhere in your code. This would give you the "dup" function you are missing. The disadvantage is that if this gets added to some future version of OpenSSL and you upgrade your application then it could cause a conflict.

or

2) Call `ASN1_item_dup()` directly, e.g.

`ASN1_item_dup(ASN1_ITEM_rptr(ASN1_TIME), object_to_dup)`

or

3) `UTCTIME `is just this:

`typedef struct asn1_string_st ASN1_UTCTIME;`

So `ASN1_STRING_dup()` should work equally well.

**Comment by richsalz** [comment]
You left out option 4: Make a PR that adds the code, doc, and a test.
