### ISSUE TITLE
 use openssl1.1.1d  report error,  undefined struct 'hmac_ctx_st'

### ISSUE THREAD

**Issue by yiyabu** [openssl/openssl#10661]
1>..\..\..\Com\src\cpk.cpp(304): error C2079: 'hctx' uses undefined struct 'hmac_ctx_st'

i find the hmac_ctx_st defined at hmac_lcl.h，but the file is not exsited in include folder.

**Comment by beldmit** [comment]
It's not a bug. The hmac_ctx_st is an internal opaque structure, so you shouldn't use it directly. Try using the functions specified in ```openssl/hmac.h```

**Comment by mspncp** [comment]
For more information, please see https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes.

**Comment by yiyabu** [comment]
> It's not a bug. The hmac_ctx_st is an internal opaque structure, so you shouldn't use it directly. Try using the functions specified in `openssl/hmac.h`

you are right
but i don't understand,  "typedef struct hmac_ctx_st HMAC_CTX" at  openssl/hmac.h  is alias, the real structure is not defined, how does it work?
i write an internal opaque structure by myself, it doesn't work。

**Comment by mattcaswell** [comment]
You don't need the contents of the struct to be defined in order to use a pointer to it. You just can't access the members or use `sizeof` on the struct. It also means you can't stack allocate it.

So, instead of:
````
HMAC_CTX ctx;
````
You have to do:
````
HMAC_CTX *ctx = HMAC_CTX_new();

/* Use the ctx */

HMAC_CTX_free(ctx);
````

**Comment by yiyabu** [comment]
> You don't need the contents of the struct to be defined in order to use a pointer to it. You just can't access the members or use `sizeof` on the struct. It also means you can't stack allocate it.
> 
> So, instead of:
> 
> ```
> HMAC_CTX ctx;
> ```
> 
> You have to do:
> 
> ```
> HMAC_CTX *ctx = HMAC_CTX_new();
> 
> /* Use the ctx */
> 
> HMAC_CTX_free(ctx);
> ```

i don't understand why the HMAC_CTX is defined?
i write an internal opaque structure by myself which is not work.

lib_Test_st.h
```
#ifndef _LIB_TEST_ST_H_
#define _LIB_TEST_ST_H_

struct BlkDataFlag 
{
	int x;
	int y;
};

#endif//_LIB_TEST_ST_H_
```
libTest.h
```
#ifndef _LIB_TEST_H_
#define _LIB_TEST_H_

typedef struct BlkDataFlag BlkData;

int add(int x,int y);
int substract(int x , int y);

#endif //_LIB_TEST_H_
```

libTest.cpp
```
#include <stdio.h>
#include "lib_Test_st.h"
#include "libTest.h"
int add(int x,int y)
{
	BlkData blk;
	blk.x = x;
	blk.y = y;
	printf("lib test!\n");
	return blk.x+blk.y;
}
int substract(int x,int y)
{
	return x - y;
}
```

when i use in the other project, it's error.
**error C2079: 'blk' uses undefined struct 'BlkDataFlag'**
main

```
#include <stdio.h>
#include "../libTest/libTest.h"

void TestMac()
{
	BlkData blk;
	blk.x  =5;
	blk.y = 8;
	printf("TestMac=%d, test ok!\n", blk.x+blk.y);
}

int main()
{
	printf("add=%d\n", add(3,5));
	return 0;
}
```

**Comment by levitte** [comment]
The difference is that with a `HMAC_CTX *`, you are passing around a pointer, and as long as that's what you do, the compiler doesn't need to know the contents of the structure it points at. In your `BlkData` example, you are not passing around a pointer, but using the structure itself. That's why you get an error.

**Comment by mspncp** [comment]
The trick is that the structure is opaque in the **public** header (which is included by the application and by the library):


https://github.com/openssl/openssl/blob/14ee781eef0e55563432f377d8911529823bee58/include/openssl/types.h#L123

Such a declaration is called a [forward declaration](https://en.wikipedia.org/wiki/Forward_declaration). It enables the compiler to use *pointers* to that struct, but not the struct itself, because it does not know the size of the struct and the layout and names of the members. The complete structure is defined elsewhere in a **private** header which is included only by the library:


https://github.com/openssl/openssl/blob/e7fb44e7c3f7a37ff83a6b69ba51a738e549bf5c/crypto/hmac/hmac_local.h#L16-L23

Since the application can't create variables of the struct type, the library needs to provide functions for creating and destroying objects on behalf of the application. In your case, it's the two functions `HMAC_CTX_new()` and `HMAC_CTX_free()`. The application receives a pointer to a new instance from `HMAC_CTX_new()`


https://github.com/openssl/openssl/blob/54a0d4ceb28d53f5b00a27fc5ca8ff8f0ddf9036/crypto/hmac/hmac.c#L133-L144

and returns it to `HMAC_CTX_free()` when it is no longer needed.

https://github.com/openssl/openssl/blob/54a0d4ceb28d53f5b00a27fc5ca8ff8f0ddf9036/crypto/hmac/hmac.c#L156-L165

In between, it passes the pointer to other API functions like `HMAC_CTX_get_md()` to obtain or modify values of the hidden members. (Those functions are called "accessors".)

https://github.com/openssl/openssl/blob/54a0d4ceb28d53f5b00a27fc5ca8ff8f0ddf9036/crypto/hmac/hmac.c#L251-L254

I hope that answers you questions.

**Comment by yiyabu** [comment]
> forward declaration

yeah,that's my need,thany you every much.
