### ISSUE TITLE
Use TPM engine for PEM files containing private key wrapped by TPM key

### ISSUE THREAD

**Issue by ironyman** [openssl/openssl#10660]
If no one objects I'd like to continue the discussion of [these patches](https://mta.openssl.org/pipermail/openssl-dev/2016-November/008841.html). 

This would be valuable to many people since this ensures the private key cannot be exfiltrated from the machine with which it's bound. This would also benefit users of other engines because they wouldn't need to specify the engine they want to use since specifying the PEM file used by that engine is enough for openssl to know which engine to use.

@levitte could you clarify why this isn't general enough so we can fix it and merge? I can help if the original author is busy.

Thanks!

**Comment by ironyman** [comment]
I'd also like to address Uri's critique in the [following message](https://mta.openssl.org/pipermail/openssl-dev/2016-November/008836.html). 

He suggests using URI to refer to the private key wrapped by TPM key instead of using PEM files. There seems to be a misunderstanding of how the private key wrapping by TPM works. The key is not stored in the TPM but in the PEM file and encrypted by a key in the TPM which is prohibitively costly for anyone to access without the TPM. So a URI would just be file path and wouldn't tell us which engine to use.

**Comment by levitte** [comment]
Let's add a bit of context...

At the time of the discussion, there were other related things going on, such as [`OSSL_STORE`](https://github.com/openssl/openssl/tree/master/crypto/stores), which is a much more generic interface to retrieve diverse objects (such as private keys) than any ENGINE function to load keys ever was. It is part of OpenSSL since 1.1.1, and integrated into the exact same function that the patch you refer to modifies. 

What needs to happen is that the [OSSL_STORE file loader](https://github.com/openssl/openssl/blob/master/crypto/store/loader_file.c) needs to be modified to recognise the "TSS KEY BLOB" or "TSS2 PRIVATE KEY" PEM types (see http://david.woodhou.se/draft-woodhouse-cert-best-practice.html#rfc.section.4.4 as well as the [TPM2 engine](https://github.com/tpm2-software/tpm2-tss-engine)) and act accordingly (whatever that means). Also, if there's still an effort for a TPM URI, a corresponding OSSL_STORE loader would be fantastic.

Also, we're currently working on a new plug-in mechanism, called "providers". You might want to look into that going forward.

**Comment by ironyman** [comment]
This feature is intended to allow existing programs that use OpenSSL to use private keys wrapped by tpm with minimal change on their part. 

For example with openssh. With this patch we could use this private key wrapped by tpm in place of any old openssh private key and it would work with no changes to openssh code (if the engine is installed). 

Can we do the same thing with ossl_store?

**Comment by levitte** [comment]
> Can we do the same thing with ossl_store?

Yes.  Or at least, I assume so.  OSSL_STORE is already integrated into the very function you want to patch, so you have the code path in place already.

**Comment by t8m** [comment]
This is something that is being already worked on by third party TPM provider. https://github.com/tpm2-software/tpm2-openssl
