### ISSUE TITLE
build fail in relase branch due to missing DEVRANDOM related defines

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#10759]
Build of 1.1.1 stable branch now fail in apps/version.c. This is regression in last 3-4 months.

Releases follows an quite long process - alpha , beta, release candidates. In those phases external developers test programs. After first official release users start to test ...
So regression after 4 releases of 1.1.1 in absolutely unexpected.

I will lest as exercise build configuration that shows failure (linux).

**Comment by mspncp** [comment]
> I will lest as exercise build configuration that shows failure (linux).

I like exercises for the reader:

    $ ./config --with-rand-seed=devrandom

And I have to admit that I'm the culprit 7b18d1a53f932391bbc599a4717d6f98a597849c  :-/

**Comment by mspncp** [comment]
The original intention of #10050 was to move the declarations to `crypto/rand/rand_local.h`. Following a suggestion of @levitte, we changed our mind and placed it into `rand_unix.c`, because we thought that this was the only place were they were needed. The CIs passed, but unfortunately, we did not consider the `--with-rand-seed` option. Sorry for the glitch and thanks for reporting it.

**Comment by mspncp** [comment]
Fix is in #10761  (1.1.1) resp. #10762 (master).
