### ISSUE TITLE
freebsd build failed on current openssl master branch

### ISSUE THREAD

**Issue by chipitsine** [openssl/openssl#10817]
on gost-engine we use freebsd within cirrus-ci

https://github.com/gost-engine/engine/runs/385094611

we build current openssl master branch.
recently it started to fail with

```
/usr/local/bin/perl "-I." -Mconfigdata "util/dofile.pl"  "-oMakefile" util/shlib_wrap.sh.in > "util/shlib_wrap.sh"
chmod a+x util/shlib_wrap.sh
pod2man --name=CA.PL --section=1 --center=OpenSSL  --release=3.0.0-dev   > doc/man/man1/CA.pl.1
pod2man: unable to format standard input
*** Error code 1

Stop.
make: stopped in /tmp/cirrus-ci-build/openssl
```

looks like error on openssl side.
also, what if enable at least some basic cirrus-ci/freebsd for openssl itself ?

**Comment by kaduk** [comment]
I can reproduce, but I have to explicitly ```make all``` (or otherwise force docs to be built), since ```build_sw``` is the default target.
The live build appears to hang waiting for input until EOF is given (at which point the "unable to format standard input" error is given); since the CI job is (presumably) run without a controlling terminal its stdin is always going to just give EOF, which explains the CI output.

It seems that ```$<``` is expanding to an empty string because IMPSRC is only defined in pattern rules, not explicit rules, and the template process produces explicit rules for each manpage.  ALLSRC (```$>```) seems like it would work okay (untested), though of course that's not portable to (e.g.) GNU make.  Perhaps we want to try a CI run with OODATE (```$?```) to see how that fares.

**Comment by richsalz** [comment]
IIRC didn't Windows nmake also have ```$<``` only work in implicit rules?

**Comment by richsalz** [comment]
Yes I recalled correctly :)  PR #10719

**Comment by kaduk** [comment]
Windows, of course, doesn't use the unix-Makefile.tmpl that the invocation here is coming from, though.

**Comment by richsalz** [comment]
My point was that maybe the same solution will work here.

**Comment by kaduk** [comment]
> the same solution

In addition to the quoting adventure, #10719 switches from ```$<``` to ```$?```, which is what I mentioned in my first comment.

**Comment by richsalz** [comment]
I was agreeing with you.  $? in explicit rules has been from version 7 unix.

**Comment by levitte** [comment]
Okie, a switch to $? it is, then... It frankly makes me a little nervous, as that may potentially be more than one file, even that *currently* doesn't happen, but if we add more dependencies to those targets in the future, we'll get nasty surprises...

**Comment by levitte** [comment]
I just had a look, and ended up replacing `$<` with the explicit file name instead.  That takes away all doubts.

**Comment by levitte** [comment]
@chipitsine, @kaduk, would you be willing to give #10849 a try?

**Comment by chipitsine** [comment]
As for enabling cirrus-ci for openssl itself, does it make sense ?
