### ISSUE TITLE
CMake build system

### ISSUE THREAD

**Issue by cristianadam** [openssl/openssl#10902]
Currently OpenSSL requires perl to build, which is not available on all platforms.

For example building on Windows using vcpkg and MinGW is not [working at the moment](https://github.com/microsoft/vcpkg/issues/9749). 

OpenSSL's forks like BoringSSL and LibreSSL can be built with CMake.

I think having a CMake build would make the lives of package manager way easier.

**Comment by richsalz** [comment]
cmake would not address the "perl is needed" issue.  look at all the .pl scripts, such as those that generate *all* the assembler code and those in util directory.  Even those two forks use perl.

**Comment by cristianadam** [comment]
Right, use perl if perl is present, if not build the generic C functions.

Compilers are getting better and better. Some of the assembly might be slower than the hand rolled assembly.

**Comment by richsalz** [comment]
> Compilers are getting better and better. Some of the assembly might be slower than the hand rolled assembly.

Nope.

And there are security issues -- AES constant time (hopefully soon to be a solved problem) and securely clearing private keys (how to stop clever compilers from optimizing out memory zeroization).

**Comment by mattcaswell** [comment]
Supporting cmake and removing perl as a dependency are two entirely different and unrelated things. The latter is unlikely to happen any time soon because of what @richsalz said. The C routines are just not a viable alternative for any serious use and are not recommended.

BTW, the linked bug report you mention above gets it wrong:

> Open SSL 1.1.x now has their own build.info files which they parse with perl, they moved away from Makefiles.

We have not "moved away from Makefiles". The build.info files are parsed to *generate* Makefiles. We can generate Makefiles in any format we want to (hence we support both unix make and Windows nmake). I'm not familiar with cmake but as I understand it, it does a very similar job.

**Comment by levitte** [comment]
Cmake does the same job. Unfortunately, Cmake is available on fewer platforms than perl is, and perl certainly *is* available on all platforms that Cmake is available on.

**Comment by petrovr** [comment]
Cristian Adam wrote:
> Currently OpenSSL requires perl to build, which is not available on all platforms.
>
> For example building on Windows using vcpkg and MinGW is not [working at the moment](https://github.com/microsoft/vcpkg/issues/9749).
>
> OpenSSL's forks like BoringSSL and LibreSSL can be built with CMake.
Hmm to use another less functional build system  :( ?

Microsoft builds are always poor  ... Perhaps in 3098 situation will 
change ...

Roumen

**Comment by cristianadam** [comment]
> Cmake does the same job. Unfortunately, Cmake is available on fewer platforms than perl is, and perl certainly _is_ available on all platforms that Cmake is available on.

Perl requires a C compiler, while CMake requires a C++11 compiler, this makes the latter available on less platforms. 

CMake is nightly tested on a variety of [platforms](https://open.cdash.org/index.php?project=CMake). 

For embedded / exotic systems that provide a cross-compiler, CMake will require the use of a  [toolchain file](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html).

Android, doesn't come with perl in their Android NDK, but it comes with a CMake toolchain file. Which makes it really easy to cross-compile projects using CMake.

With CMake you would be able to open a project in an IDE like Qt Creator, Visual Studio Code, Clion, Visual Studio. Some of them even ship CMake themselves.

There are advantages in using a popular build tool. Developers are familiar with it, documentation exists on how to fix problems. It's integrated in their workflow.

**Comment by sfhacker** [comment]
Is this 

> For example building on Windows using vcpkg and MinGW is not working at the moment.

 still happening or true?

Just downloaded the latest tarball from here: https://www.openssl.org/source/.
We use MinGW/MSYS on Windows 10.

Then, we type:
      perl Configure mingw64 .......
      make all
	
![image](https://user-images.githubusercontent.com/25817529/73466955-609cd100-4361-11ea-9756-48e34681ade6.png)

That's all folks!

![image](https://user-images.githubusercontent.com/25817529/73466972-672b4880-4361-11ea-985f-4b89a7ee6c0a.png)

Can you try the same command line above and provide screenshots showing the error messages you are getting?

Cheers.

**Comment by levitte** [comment]
> There are advantages in using a popular build tool. Developers are familiar with it, documentation exists on how to fix problems. It's integrated in their workflow.

There are platforms our stuff builds on that don't have C++11, which CMake requires to build, last I checked.  It's really a pain in the nether regions, but that's the reality we're facing.  Believe you me, if CMake was more widely available than the big three (std::unix / Linux, Windows and MacOS X), I would have pushed for using it within a bad of an eye.  Alas...

**Comment by levitte** [comment]
(g++ and clang don't port everywhere either...)

**Comment by sfhacker** [comment]
The build environment we use on Windows offers support for cmake, ninja and another one I don't recall right now.
Of course, it supports g++, gfortran, .....

![image](https://user-images.githubusercontent.com/25817529/73477490-1d4b5e00-4373-11ea-8e11-4c6ad421d5e3.png)

We build large projects from source on a regular basis using the same environment and different compilers.

Anyway, it would be useful if @cristianadam could execute the above commands and show the error messages he is getting.

Let us know if we can be of any assistance.

Have fun.

**Comment by cristianadam** [comment]
As seen at https://github.com/microsoft/vcpkg/issues/12919 OpenSSL can't compile on Windows using MinGW (not MSYS2) because it assumes MinGW64 as being `BASE_unix`. 

Having a CMake build would simply just work. 

Even though OpenSSL just needs perl and a C compiler, these two need to be in the right combination, otherwise the Makefile generated would not work.

**Comment by levitte** [comment]
We can certainly add config targets for MinGW used with CMD.  Now sure what that entails in terms of Makefile, though...

As for CMake, I will reiterate that it's not acceptable as a universal tool, because it's not quite that universal.  Of course, we *could* have parallel configuration / building systems, but believe you me, that's pretty hellish (I maintained the different building systems we had before 1.1.0, I'm not at all keen to do that again)

**Comment by sfhacker** [comment]
I don't understand why we insist on something not essential at the moment.
You can build OpenSSL from source with MinGW in two mins without installing VS nor SDK nor other tools.
Just type: configure
                make all
                make install

![image](https://user-images.githubusercontent.com/25817529/90630823-14659f80-e265-11ea-8e79-2ddfa25da7b4.png)

![image](https://user-images.githubusercontent.com/25817529/90631210-a8376b80-e265-11ea-9de1-806d73a5617b.png)


@cristianadam If you require any assistance such as setting up environments, compilation and the like, do let us know.

**Comment by cristianadam** [comment]
Qt is providing a MinGW compiler and you can build your applications with it. The Qt offline installer was (is) providing Strawberry Perl. That should be sufficient to build OpenSSL, so that's what I thought.

vcpkg is a package manager which has experimental build recipes for the standalone MinGW compiler, and it's very compelling to just have `vcpkg install my-package:x64-mingw-static/dynamic`  to build your dependencies.

In reality you need to have a Unix environment to build OpenSSL with MinGW, that's what vcpkg is trying to do, download MSYS2 to just build a library, which has a custom build system that nobody else uses.

**Comment by cristianadam** [comment]
https://github.com/janbar/openssl-cmake is a thing and I could work to get that into shape, and stop ~complaining~ suggesting it here.

**Comment by levitte** [comment]
Side note: I've pondered writing a cmake clone in perl.  The C++ classes used in current cmake aren't that complicated.
...
given time...

**Comment by cristianadam** [comment]
`Configure` could have a target system called **cmake** which would generate a `CMakeLists.txt` instead of a Makefile.

* [add_library](https://cmake.org/cmake/help/latest/command/add_library.html)(\<name\> [STATIC | SHARED ] [source1] [source2 ...])
* [add_executable](https://cmake.org/cmake/help/latest/command/add_executable.html)( \<name\> [source1] [source2 ...]) 
* [target_sources](https://cmake.org/cmake/help/latest/command/target_sources.html)(\<target\> <INTERFACE|PUBLIC|PRIVATE> [items1...])
* [target_include_directories](https://cmake.org/cmake/help/latest/command/target_include_directories.html)(\<target\> <INTERFACE|PUBLIC|PRIVATE> [items1...])
* [add_test](https://cmake.org/cmake/help/latest/command/add_test.html)(NAME \<name\> COMMAND <command> [<arg>...])

The assembly part needs some caring, but other than that it shouldn't be hard to have something working. 

It should be faster than writing a cmake clone in perl 😊

**Comment by Croydon** [comment]
Could the point "CMake isn't broadly available" please be specified? 

On which platforms OpenSSL is supporting is CMake not "official" available? (a.k.a not provided by Kitware or from the system's official package manager if existing)

If we have an answer to that question the next step would be figuring out how easy it is to get CMake there nonetheless, via e.g. compiling yourself or popular tool sets.

**Comment by eli-schwartz** [comment]
> There are platforms our stuff builds on that don't have C++11, which CMake requires to build, last I checked. It's really a pain in the nether regions, but that's the reality we're facing. Believe you me, if CMake was more widely available than the big three (std::unix / Linux, Windows and MacOS X), I would have pushed for using it within a bat of an eye. Alas...

**Comment by Croydon** [comment]
I read that, but which platforms are those _**specifically**_.

**Comment by levitte** [comment]
The one that I care about is [OpenVMS](https://vmssoftware.com/). There's an x86_64 port in the works that I understand will be a bit more up to date re Cmake et al, but that doesn't help currently existing systems.

There are others as well (there's a reason  we're sticking to C90, for example), that I'm less acquainted with.

**Comment by eli-schwartz** [comment]
https://www.openssl.org/policies/platformpolicy.html

OpenVMS, I presume, given that Linux is the primary development platform, but for secondary core development platforms, FreeBSD, Windows, and MacOS X share that distinction with VMS.

**Comment by richsalz** [comment]
I think the true answer is that the project does not know every platform that uses OpenSSL. There are many embedded devices, for example, and breaking them would be bad for the project.

**Comment by levitte** [comment]
> I think the true answer is that the project does not know every platform that uses OpenSSL. There are many embedded devices, for example, and breaking them would be bad for the project.

Yup...  that's basically the same answer, some tools that are thought to be "universal" turn out not to be.

**Comment by alexhultman** [comment]
This CMake jihad is ridiculous.

"Let's not depend on Perl and instead depend on CMake because that's MY religion and everyone should adopt MY religion".

Swapping Perl for CMake is achieving nothing at all. It's the "let's invent yet another standard to fix the 14 other standards issue that only leads to 15 standards".

The argument to drop all assembly paths just to use CMake is ridiculously preposterous.

And when you've moved to CMake then comes the BAZEL people who require the whole JVM to build.

Truth is build systems are nothing but competing religions and fanatical thinking.

No, your utopia where all code is built by CMake will never happen.

**Comment by eli-schwartz** [comment]
> I cannot speak for others, but my point was to replace scripting language requirement entirely with a standard system, preferably with one having a user interface (or at least being able to integrate with one).

I am extremely doubtful that you will ever get rid of a scripting language requirement. The scripting language requirement that is there currently is used for ***two*** things.
- the build system interpreter
- helper program used to generate asm

Porting to cmake will not mean dropping asm. If will mean you need both cmake and perl.

Porting to meson would mean you need python and perl -- or port the scripts to python too and you only need python.

I doubt it is feasible to port the scripts to cmake's rudimentary and typeless scripting language, and writing meaningful ***programs*** in *.cmake has got to be a fate nearly as bad as writing them in VimL.

So really the choice is which language to rewrite them in, or whether to continue requiring perl in addition to whichever prospective build system is under suggestion.

> It is on a Windows platform.

Meson generates VS solutions on Windows, just like cmake. I mentioned this already.

I am pretty sure Windows users who don't want a ninja dependency are going to say "oh cool, let's use the VS solution" not "well gosh I sure miss the old perl configure system's NMake files".

If you are absolutely positive that people really, really, really crave NMake instead of VS, then that need can be discussed. If meson users need an NMake backend, we can add one.

We haven't added one, because Windows users have never once expressed wanting it lol. They want VS and we provided VS.

**Comment by eli-schwartz** [comment]
@levitte I agree that cmake config files would tend to be very useful for Windows users integrating with cmake. For Linux users, I would recommend they use cmake's FindPkgConfig and `pkg_check_modules()` function which can produce sterling results based on the existing pkg-config files, but unfortunately does require installing pkg-config which windows development toolchains somehow rarely have...

(I believe Conan is much better about that though.)

FWIW meson does have some simple helpers to produce the same results as cmake's write_basic_package_version_file() and configure_package_config_file() and friends.

Inspirational source code can be seen here: https://github.com/mesonbuild/meson/blob/master/mesonbuild/modules/cmake.py

**Comment by levitte** [comment]
Frankly, I don't care much for the CMake vs Meson battle...  it's about as interesting to watch as an emacs vs vi battle.  Might be fun at first, but is tiresome in the long run.  Furthermore, considering that configuration and build systems develop over time, and sure enough borrow ideas from each other, which you end up choosing is really a matter of a wet finger in the air.

That being said, I wonder how hard it is to parse build.info files and generate CMakeLists.txts from them...  that, or the idea that @cristianadam posted [about a year ago](https://github.com/openssl/openssl/issues/10902#issuecomment-676274478).
... or the corresponding thing for Meson to make Meson fans happy, or whatever other config / build system.
I believe such hacks would be much more helpful than continuing the feature battle.

**Comment by eli-schwartz** [comment]
@levicki I'd appreciate if you stopped derailing the main discussion (replacing Configure with cmake) by talking about pre-generated assembly, which is a separate topic that is being tracked in #16188

:p

**Comment by kroeckx** [comment]
My understanding what this issue is really about is better
support for building on Windows, including support for integration
in the IDE and parallel build support. It's not clear if there is
demand for something other than supporting VSCode.

There is also mention about removing the need for perl, but adding
support for, or switching to a different build system is not enough
to remove the need for perl at this time. If you want to remove
dependencies on perl, I suggest we use a different issue for that.

I see at least the following options:
- Add VSCode support
- Add support for an other build that can generate files for
  VSCode, for instance cmake.

For both options there are 2 ways to do it:
- We maintain the files for both our current build system
  and the other system.
- Our build system is extended to generate files for the
  other system. We could update those files with "make update"
  so that they're always part of the source.

**Comment by levicki** [comment]
> My understanding what this issue is really about is **better support for building on Windows, including support for integration in the IDE and parallel build support.**

Correct.

> There is also mention about removing the need for perl, but adding support for, or switching to a different build system is not enough to remove the need for perl at this time.

That's abundantly clear, and it's why I asked what would be the best way to proceed with that.

> If you want to remove dependencies on perl, I suggest we use a different issue for that.

Fair point.

> Add support for an other build that can generate files for VSCode, for instance cmake.

If by "files for VSCode" you mean `.vcxproj` and `.sln` files which can be opened in VS IDE as well as built using `MSBuild` from the command line as part of an automated build process, then yes -- that would be very nice.

Current Windows makefiles do not allow for parallel compile (they compile one `.c` file at a time instead of passing a bunch of them to `cl.exe` along with a `/MP` switch), and even on very fast systems it takes quite a while to build OpenSSL.

Couple that with the inability to build out-of-place and suddenly building all combinations of x86 / x64 / Debug / Release (and Static / DLL if you need both) becomes quite a chore.

Therefore, any improvement for Windows builds would be most welcome so thank you very much for even considering it.

**Comment by misery** [comment]
> I see at least the following options:
> - Add VSCode support
> - Add support for an other build that can generate files for VSCode, for instance cmake. 

This should be extended with mingw without msys: https://github.com/openssl/openssl/issues/6111

**Comment by levitte** [comment]
> Couple that with the inability to build out-of-place
> I was under the impression that that worked, at least on Linux. But it seems broken both in 1.1.1 and master, I guess it's not tested enough.

Not sure what "out-of-place" is supposed to mean. If that means having a build tree outside of the source tree, that is supported indeed, and last time I checked, also tested.

**Comment by levicki** [comment]
Why people insist on talking about Meson in an issue about CMake and even claim the issue is not about CMake is really beyond me, but it is really counter-productive and rude and IMO it should stop.

> If that means having a build tree outside of the source tree, that is supported indeed, and last time I checked, also tested.

You are correct, it is supported, it's just a bit less convenient to setup than with CMake.

Frankly, my biggest issues with Windows build are speed (no parallel compile) and the inability to build multiple targets (x86 / x64 / Debug / Release) at once -- at least I couldn't find a way to do so, maybe it's possible and I missed it?

With `.vcxproj` and `.sln` files (be they generated by your current build system or CMake) both would be possible from Visual Studio or from command line using `MSBuild`.

**Comment by hwhsu1231** [comment]
> That being said, though, I've wondered how hard it would be to generate a OpenSSLConfig.cmake (for use with [find_package() in config mode](https://cmake.org/cmake/help/latest/command/find_package.html#full-signature-and-config-mode)), to be installed in an appropriate cmake module directory. If that's our responsibility or someone else's is a matter of discussion, but having a better OpenSSL version and platform specific cmake package than the complex FindOpenSSL.cmake that is currently districbuted with CMake would probably be a win for CMake users who want to use OpenSSL libraries in their own CMakeLists.txt...

@levitte 

Combined with the above quote and based on what you said in this comment: https://github.com/openssl/openssl/issues/18897#issuecomment-1198231003

Do you mean it is **POSSIBLE** to generate the following files:

- `openssl-config.cmake`
- `openssl-config-version.cmake`
- `openssl-targets.cmake`
- `openssl-targets-*.cmake`

without using CMake as the build system?

**Comment by levitte** [comment]
> Do you mean it is **POSSIBLE** to generate the following files:
> 
> * `openssl-config.cmake`
> * `openssl-config-version.cmake`
> * `openssl-targets.cmake`
> * `openssl-targets-*.cmake`
> 
> without using CMake as the build system?

Why wouldn't it? They are generated text files, all that's really needed is a good enough formula to generate them.
(another possibility could be to have a CMakeLists.txt with just enough declarations that CMake would generate a good config/target file. I've yet to explore that sort of trick...)

**Comment by ajkhoury** [comment]
Hi, I have added CMake support in https://github.com/openssl/openssl/pull/20153

Unfortunately, there was no getting around the Perl requirement due to OpenSSL's perlasm, so I devised this solution to generate a CMake script.

**Comment by gatkinso** [comment]
Hi.  Has there been any more discussion about this feature request?

I think adding CMake support would be super helpful to many.  Adding this would not impact those who want to build in the current fashion at all.

**Comment by t8m** [comment]
There is a PR #20878 which is going to provide a .cmake file to use in application builds that use CMake. However I do not see us replacing the build system with CMake any time soon. We certainly aren't going to maintain two build systems for OpenSSL. So unless we drop support for systems where perl is available but CMake isn't we aren't going to build OpenSSL using CMake. That needs to be understood.

**Comment by gatkinso** [comment]
OK. Thanks.  Certainly I would not support a _replacement_, but rather adding CMake along side of the current build like many other projects have done.

**Comment by cristianadam** [comment]
Since OpenSSL has a Makefile generator, it would be great if it there would be a CMakeFile generator. There will still be one "build system", but it could be more flexible.

On Windows generating a NMake file and running single core is absolutely ridiculous at the end of 2023!

**Comment by eli-schwartz** [comment]
If it's just about running single core then maybe a Ninja file generator is enough?

**Comment by t8m** [comment]
There could be a CMakeFile generator however as that CMakeFile would be generated as part of the Configure step during the build you would still need Perl to build OpenSSL - so I am not sure about the usefulness.

And yes, Ninja file generator would be something we would really like to have to resolve the missing parallel make problem for Windows builds.

**Comment by eli-schwartz** [comment]
Ninja would also add IDE support by enabling the trivial creation of a compile_commands.json -- many IDEs can make use of a compilation database without requiring an overly specific build system integration.

**Comment by ajkhoury** [comment]
A CMake generator is precisely what my PR (https://github.com/openssl/openssl/pull/20153) did, but the OpenSSL maintainers weren't eager to include it for reasons that I perhaps don't comprehend. The usefulness of the CMake generator in my case was the ability to use a custom compiler (that was otherwise too difficult to hack into the existing Perl build system) to cross compile for an embedded environment, and to have symbols be resolved with the CMake extension in VSCode.

**Comment by Croydon** [comment]
Just a friendly ping for everyone subscribing to this issue, but not also a similar issue about Meson build support for OpenSSL. The issue about Meson got some attention recently, including the indications of maintainers to accept contributions that add a second build system when it fulfills certain criteria. Please read https://github.com/openssl/openssl/issues/16812#issuecomment-2156989700 and all following comments.

**Comment by nhorman** [comment]
there are current community efforts here #16812  to create a secondary build system that is non-perl-requiring.  Current debate seems to be meson vs cmake

closing this as a duplicate of that
