### ISSUE TITLE
DTLS with psk: wrong psk error reporting not ideal

### ISSUE THREAD

**Issue by z-s-e** [openssl/openssl#10906]
I am not sure if this is a bug, or more of a limitation of the protocol (or UDP), so I marked this as a question for now. Anyway, when I intentionally put a wrong PSK for the client, like this:
```
$ openssl s_server -dtls1_2 -nocert -port 12345 -cipher PSK -psk 1234 &
$ openssl s_client -dtls1_2 -connect 127.0.0.1:12345 -cipher PSK -psk 1235
```
it seems both the server and client get stuck, neither reporting a clear error message (tested with OpenSSL 1.1.1d  10 Sep 2019).
It would be nice if this could be improved to behave similarly to when using regular TLS.
Thanks

**Comment by kaduk** [comment]
That just sets the key but not an identifier for it.
When it comes time to use the key, each party will just get a decryption failure ("bad record mac") but since this is DTLS will effectively assume corruption on the wire (or an attack) and ignore it.  So, the client will keep retransmitting the ClientHello+ClientKeyExchange, and the server will keep responding, but each party can't make progress because the keys don't match up.
In regular TLS the bad-record-mac is fatal, and you get the error you're looking for, but DTLS by design ignores such per-record deprotection failures.  (The packet capture is simpler if you use a pure-PSK ciphersuite like PSK-AES256-GCM-SHA384, FWIW, but conceptually the same.)

I note that it's generally wise to set a PSK identity as well as the PSK value itself, to help detect such issues, and s_server will print a diagnostic when the client identity doesn't match what was expected.

**Comment by z-s-e** [comment]
I would like to have good error reporting when the password is given incorrectly (which is usually not intentional), so for this situation the PSK identity does not really help (unless you suggest to set the PSK identity to a hash value of the PSK of sorts, which seems kind of weird to me...).

Anyway, if the protocol mandates that non-acceptable ClientHello+ClientKeyExchange's are ignored by the server, I suppose there is nothing that can be done on the OpenSSL side. Though then isn't this a protocol defect? It would make much more sense to me if instead of simply ignoring the server replied with a "I got an unacceptable Hello message from you (with checksum XX)" so the client can stop trying (if the checksum matches to what the client sent initially or something).

**Comment by richsalz** [comment]
> I would like to have good error reporting when the password is given incorrectly

The reason not to do this is that it gives attackers information.

**Comment by z-s-e** [comment]
What information? It does not seem logical to me that a (connection terminating) alert message for a DTLS handshake is substantially more problematic than for a regular TLS connection. Not trying to be rude btw, just genuinly curious.

**Comment by kaduk** [comment]
It also turns the DTLS server into a (reflection) attack vector, since the proposed alert would be sent to an address that was not verified to be under the control of the sender of the ClientHello (recall that UDP does not have the TCP three-way handshake).

**Comment by z-s-e** [comment]
Isn't that already taken care of by using HelloVerifyRequest (or something with the same purpose outside the DTLS protocol)? So that would come even before the ClientKeyExchange and subsequent alert.
