### ISSUE TITLE
App Certificate generation fails with OpenSSL Error 0x2406C06E

### ISSUE THREAD

**Issue by HemanthApte** [openssl/openssl#10969]
Hello,
In my application, i am trying to create a certificate using below code.  I get error when a function RSA_generate_key_ex( pRsaKeyPair, a_iBits, pBignum, NULL); is called. Error number is  0x2406C06E.
I am new to OpenSSL and not able to understand this error and its description.  ERR_get_error() return null value for the above issue.  

OpenSSL Version: 1.1.1d.
Linux gLibC: 2.10.1.
My Application is also integrated with Qt4.8 and Unified automation OpcUa C Stack.
The below call is called from OpcUa Stack. (Same code works with later version of gLibC compiler?)

```
PkiRsaKeyPair_Create(EVP_PKEY **a_ppKeyPair, int a_iBits)
{
        EVP_PKEY    *pKey           = NULL;
        RSA         *pRsaKeyPair    = NULL;
        BIGNUM      *pBignum        = NULL;

        pKey = EVP_PKEY_new();

        pRsaKeyPair = RSA_new();
        if(pRsaKeyPair == NULL)
                WriteToFile("Memory alloc failed... pRsaKeyPair");
        errValue = ERR_get_error();
        
        pBignum = BN_new();
        if(pBignum == NULL)
                WriteToFile("Memory alloc failed...pBigNum ");
        
	errValue = ERR_get_error();
        WriteToFile1("ErrorValue2", errValue);

        BN_set_word(pBignum, 0x10001);
        errValue = ERR_get_error();

        iRet = RSA_generate_key_ex( pRsaKeyPair, a_iBits, pBignum, NULL); // <-- Error value.
        errValue = ERR_get_error();
        
        WriteToFile((char*)ERR_reason_error_string(iRet));

        BN_free(pBignum);

        iRet = EVP_PKEY_assign_RSA ( pKey, pRsaKeyPair );
}
```

Kindly help me understand why RSA_generate_key_ex() fails and how to over come.

**Comment by levitte** [comment]
There is a `openssl errstr` command:

``` console
$ openssl errstr  0x2406C06E
error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy
```

However, your use of `ERR_reason_error_string` is incorrect, you should give it `errValue` instead of `iRet`.  But that won't necessarily tell you the whole story, as errors are registered in a stack, and `ERR_get_error()` will only pop off the top one each time.

The more human readable way of doing this is to print the whole error stack IF you have an error (`iRet` will tell you if there was an error, for example, just not *what* it is), using one of the `ERR_print_errors` functions.  In your case, since you're writing with a special function, the callback form might be the best.  So, use this as a callback:

``` C
static int Pki_ErrCallback(const char *str, size_t len, void *userdata)
{
    WriteToFile(str);
    return 1;
}
```

and then use it like this when you want to report OpenSSL errors:

``` C
    ERR_print_errors_cb(Pki_ErrCallback, NULL);
```

The manual for `ERR_print_errors_cb` in OpenSSL 1.1.1 is [here](https://www.openssl.org/docs/man1.1.1/man3/ERR_print_errors_cb.html).  That function hasn't changed in quite a while, so that manual should be valid for any current OpenSSL release

**Comment by HemanthApte** [comment]
Hi Levitte,
Thank you for your reply.
Thank you for giving details on how i can get the error description. I could use it now.
But, still i am not understanding the relation between glibc OR gcc version that we use  and the Open SSL version 1.1.1d.  

Note: My **glibc** version is **2.10.1** and **gcc version is 4.4.3**.  What is the work-around to solve above issue with these compiler and libs?  

I tried with `no-ec_nistp_64_gcc_128`,   `--with-rand-seed=os` and   `--with-rand-seed=none`. 
But its not working.  
do you have any other suggestion to get this RSA_generate_key_ex() working?

Thank you,
regards, Hemanth.

**Comment by kroeckx** [comment]
Do you have a /dev/random and /dev/urandom?

What does /proc/sys/kernel/random/entropy_avail contain?

**Comment by kroeckx** [comment]
Does the test suite pass?

Can you try to strace your application?

**Comment by HemanthApte** [comment]
@kroeckx Sorry for the late reply.
I have /dev/urandom.  But do not have /dev/random.
entropy_avail contains nothing. its empty.

**Comment by kroeckx** [comment]
We have changed things so that we're certain enough entropy is
available. The only way to wait for that on that kernel verion,
is to wait until /dev/random is readable. You will have to
create that device. We will them read 1 byte from it, and then
switch to /dev/urandom.

entropy_avail always contain some number. To see it, just do:
cat /proc/sys/kernel/random/entropy_avail

**Comment by HemanthApte** [comment]
Hi @kroeckx ,
cat /proc/sys/kernel/random/entropy_avail gives 131.  I am sorry.. earlier i used vi. :(

I will create the /dev/random device and try to read the value.  Hope it solves the issue.

Thank you for the reply. :)
