### ISSUE TITLE
BIGNUM BN_copy and BN_clear

### ISSUE THREAD

**Issue by qualitesys** [openssl/openssl#10994]
In the crypto/bn/bn_lib.c, the function BN_copy is to copy BIGNUM b to a.
~~~~~~
BIGNUM *BN_copy(BIGNUM *a, const BIGNUM *b)
{
    bn_check_top(b);

    if (a == b)
        return a;
    if (bn_wexpand(a, b->top) == NULL)
        return NULL;

    if (b->top > 0)
        memcpy(a->d, b->d, sizeof(b->d[0]) * b->top);

    a->neg = b->neg;
    a->top = b->top;
    a->flags |= b->flags & BN_FLG_FIXED_TOP;
    bn_check_top(a);
    return a;
}
~~~~~~

Since in normal compilation process  BN_FLG_FIXED_TOP=0 the a->flags remains unchanged, b->flags is never copied.
~~~~~~
a->flags|=b->flags&0;
is equivalent to
a->flags|=0;
~~~~~~
Is it done on purpose ?

The same pattern is found in BN_clear (a->flags remains unchanged)
~~~~~~
a->flags &= ~BN_FLG_FIXED_TOP;
equivalent to
a->flags &= ~0;
~~~~~~

**Comment by mattcaswell** [comment]
Yes, its done on purpose. A number of the flags are associated with the actual BIGNUM and make no sense to copy. For example BN_FLG_MALLOCED indicates whether the BIGNUM structure was allocated via a malloc call or not, and BN_FLG_SECURE whether the BIGNUM was allocated in secure memory or not.

Other flags might make sense to copy such as BN_FLG_CONSTTIME and that one was for a brief period - but we had to back that change out because it had unintended consequences that broke some things.

**Comment by qualitesys** [comment]
Thanks for your feedback. I little comment in the code would be welcome, it is not obvious.
