### ISSUE TITLE
SSL_accept() fails in server with handshake error where SSL_connect() succeeds

### ISSUE THREAD

**Issue by revraj1207** [openssl/openssl#11118]
I am using openssl (1.1.1c) in my server-client model project for data communication. When we use client authentication (use SSL_CTX_set_verify(SSL_VERIFY_PEER | SSL_VERIFY_FAIL_IF_NO_PEER_CERT in server), and client did not provide a certificate, SSL_accept() on server side fails with error “peer did not return a certificate” (but server won’t die, it  will wait for next connection).

But SSL_connect() on client side gets return code as 1 which is success.

 When an SSL handshake fails in the server, how can a  client receive SSL_Connect as success.

Please help me to find out anything am missing or is it a bug?

Thank you for your bug report. If this is your first one,
please take the time to read the following lines before posting it.

**Comment by kroeckx** [comment]
You will need to provide some more details about what the issue is. Are you saying on the client side, SSL_connect() is successful, but the server for the same connection SSL_accept() failed? What error do you get? Did you call SSL_get_error() to find out why it returned an error?

**Comment by kaduk** [comment]
[edited original post to move the useful content outside of the comment block]

**Comment by rajahks** [comment]
I'm facing the exact same issue but it happens to me only when TLSv1.3 is being used. With TLSv1.2 SSL_Connect returns -1 as expected. 

Is this because in TLSv1.3 the SSL Client authentication happens after the Handshake and so SSL_connect returns success ?? 

**If this is case, then what API should I call on the client after `SSL_connect` to know if the client authentication was successful** before trying to check the server verification using `SSL_get_verify_result`.

**Comment by kaduk** [comment]
TLS 1.3 client authentication still (can) happens during the handshake, and the post-handshake offering requires extra code so I assume you're not using it.

I don't have enough information about what API calls you're making and what they are returning, let alone what SSL_get_error() is returning, in order to give advice about how to modify your code to achieve your desired result.

**Comment by rajahks** [comment]
@kaduk  Briefly, these are the calls that are made on the client and server... 

```
      Client                                                 Server                        
===============================                  =====================================
const SSL_METHOD *meth;                          const SSL_METHOD *meth;
SSL_CTX *ssl_ctx;                                SSL_CTX *ssl_ctx;
meth = TLS_client_method();                      meth = TLS_server_method();
ssl_ctx = SSL_CTX_new( meth );                   ssl_ctx = SSL_CTX_new( meth );
...                                              ...
...                                              SSL_CTX_set_verify( ssl_ctx, SSL_VERIFY_PEER | SSL_VERIFY_FAIL_IF_NO_PEER_CERT | SSL_VERIFY_CLIENT_ONCE , NULL );
SSL_CTX_set_verify_depth( ssl_ctx, 2 );          SSL_CTX_set_verify_depth( ssl_ctx, 2 );
...                                              SSL_CTX_set_num_tickets(ssl_ctx, 0 );
...                                              ...
SSL *ssl = SSL_new(ssl_ctx );                    SSL *ssl = SSL_new( ssl_ctx );
nSSLIORetVal = SSL_connect( ssl )                nSSLIORetVal = SSL_accept( ssl );
==========================================================================================
When using TLSv1.2, SSL_connect returns -1       For both TLSv1.2 and TLSv1.3, SSL_accept
When using TLSv1.3, SSL_connect returns 1        returns -1 with Err_get_error=337100999 
                                                 (Peer did not return a certificate)

```
I use `SSL_CTX_set_max_proto_version(ssl_ctx, TLS1_2_VERSION);` to make it negotiate it to TLSv1.2.

So what is not clear to me is that with the same code why does SSL_connect behave differently for TLSv1.2 and TLSv1.3.

Can you let me know if I need to add few APIs on the client side so that it behaves the same with TLSv1.2 and TLSv1.3 ?

**Comment by mattcaswell** [comment]
The problem is due to a difference in the way TLSv1.3 works. Here is what a TLSv1.2 handshake looks like  from RFC5246:

```
      Client                                               Server

      ClientHello                  -------->
                                                      ServerHello
                                                     Certificate*
                                               ServerKeyExchange*
                                              CertificateRequest*
                                   <--------      ServerHelloDone
      Certificate*
      ClientKeyExchange
      CertificateVerify*
      [ChangeCipherSpec]
      Finished                     -------->
                                               [ChangeCipherSpec]
                                   <--------             Finished
      Application Data             <------->     Application Data

             Figure 1.  Message flow for a full handshake
```
So, the server sends a CertificateRequest. In your case the client ignores it and continues without sending a Certificate back. So it just sends ClientKeyExchange, CCS and Finished. The server then aborts the handshake without ever sending its "Finished" message and SSL_accept fails. From the client perspective the handshake is not done until it has both sent *and* received a Finished message. Because this never happens `SSL_connect` also fails.

Compare this with a TLSv1.3 handshake from RFC8446:

```
       Client                                           Server

Key  ^ ClientHello
Exch | + key_share*
     | + signature_algorithms*
     | + psk_key_exchange_modes*
     v + pre_shared_key*       -------->
                                                  ServerHello  ^ Key
                                                 + key_share*  | Exch
                                            + pre_shared_key*  v
                                        {EncryptedExtensions}  ^  Server
                                        {CertificateRequest*}  v  Params
                                               {Certificate*}  ^
                                         {CertificateVerify*}  | Auth
                                                   {Finished}  v
                               <--------  [Application Data*]
     ^ {Certificate*}
Auth | {CertificateVerify*}
     v {Finished}              -------->
       [Application Data]      <------->  [Application Data]
```

The server sends its CertificateRequest *and* its Finished message in the same flight - and trusts that the client will send the certificate as requested. The client fails to do so and just sends a finished message back. The server aborts the handshake at this point because it hasn't got the certificate it was expecting - hence SSL_accept fails. From the client perspective though it has already sent and received its Finished messages. So the client believes the handshake is "done", and so SSL_connect succeeds. It won't realise that there was a problem until such time as it attempts to read data from the server. At this point it will discover the failure alert and the SSL_read() call will fail.

**Comment by rajahks** [comment]
Thank you @mattcaswell for the detailed explanation.

From a client perspective, what can I do after SSL_connect succeeds in order to check if the server has closed down the connection? 

Is there a way I can make the SSL_connect fail, by setting some flags, in case it does not send the requested certificate from the server ?  

Basically I want my client to stop in case the server side has closed down just like with TLSv1.2. What can I do to get this behaviour ?

**Comment by mattcaswell** [comment]
> Is there a way I can make the SSL_connect fail, by setting some flags, in case it does not send the requested certificate from the server ?

No - there isn't such an option at the moment.

> From a client perspective, what can I do after SSL_connect succeeds in order to check if the server has closed down the connection?

The only thing you can do is attempt to read data from the server via SSL_read(). Unfortunately if your protocol means that the client writes first (as is often the case) and the server doesn't send anything until it's received client data then its a difficult problem to solve. If the server was expecting a certificate that it didn't get then it will abort immediately and send an alert. Calling SSL_read() will detect that an report and error. However if SSL_read() doesn't read anything (SSL_ERROR_WANT_READ) then you don't know if its because the server was successful and is waiting for the client to send it something, or whether it actually failed but the alert hasn't arrived yet.

**Comment by kaduk** [comment]
> > Is there a way I can make the SSL_connect fail, by setting some flags, in case it does not send the requested certificate from the server ?

> No - there isn't such an option at the moment.

It seems like the `client_cert_cb` ought to be able to decide to abort the connection in preference to continuing without a cert, though the current documented behavior doesn't suggest this and if you peek into the implementation to decide to return `NULL` cert and key then the resulting error message is a bit weird.

**Comment by rajahks** [comment]
> 
> 
> > Is there a way I can make the SSL_connect fail, by setting some flags, in case it does not send the requested certificate from the server ?
> 
> No - there isn't such an option at the moment.
> 
> > From a client perspective, what can I do after SSL_connect succeeds in order to check if the server has closed down the connection?
> 
> The only thing you can do is attempt to read data from the server via SSL_read(). Unfortunately if your protocol means that the client writes first (as is often the case) and the server doesn't send anything until it's received client data then its a difficult problem to solve. If the server was expecting a certificate that it didn't get then it will abort immediately and send an alert. Calling SSL_read() will detect that an report and error. However if SSL_read() doesn't read anything (SSL_ERROR_WANT_READ) then you don't know if its because the server was successful and is waiting for the client to send it something, or whether it actually failed but the alert hasn't arrived yet.

Oh that's unfortunate ... I think like ours, other apps if using client authentication would break when using TLSv1.3 because we now need to modify application logic to tackle TLS layer. It gets a bit more complicated when we have to maintain backward compatibility. 

It would be great if we have a way to detect if the Client Authentication was successful by calling another API like `SSL_get_verify_result` instead of  trying to do an SSL_read/write to detect socket closure on the other side.

**Comment by kaduk** [comment]
Well, at the protocol level, it's up to the server to decide whether the client authentication is successful.  If the server thinks the authentication was unsuccessful, your application isn't going to be able to pass any data, and calls to `SSL_read()`/`SSL_write()` will (eventually) reflect the TLS alert from the server that aborts the connection.  So I don't know that your client-side logic needs to change other than by being prepared to handle error returns properly.

**Comment by Aaru47527** [comment]
**Error with TLS Call Home connection using netopeer2-cli**

**Describe the issue:**
I am encountering an error when attempting to listen for a TLS Call Home connection using netopeer2-cli. Below is the command and the error log I receive:

**Command:**
listen --tls

**Error Log:**
cmd_listen: Waiting 60s for a TLS Call Home connection on port 4335...
nc ERROR: Communication socket unexpectedly closed.
cmd_listen: Receiving TLS Call Home on port 4335 failed.

Here are the relevant logs from the netopeer2-server:
[INF]: LN: Trying to connect via IPv4 to 172.17.167.137:4335.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: [INF]: LN: Successfully connected to 172.17.167.137:4335 over IPv4.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: Successfully connected to 172.17.167.137:4335 over IPv4.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: Session 822 (user "root", CID 56) created.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: [INF]: SR: Session 822 (user "root", CID 56) created.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: Session 823 (user "root", CID 56) created.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: [INF]: SR: Session 823 (user "root", CID 56) created.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: Session 824 (user "root", CID 56) created.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: [INF]: SR: Session 824 (user "root", CID 56) created.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: Cert verify: depth 1.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: [INF]: LN: Cert verify: depth 1.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: [INF]: LN: Cert verify: subject: /C=in/ST=ut/L=ut/O=ut/OU=ru/CN=ut/emailAddress=ut@gmail.com.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: [INF]: LN: Cert verify: issuer: /C=in/ST=ut/L=ut/O=ut/OU=ru/CN=ut/emailAddress=ut@gmail.com.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: [INF]: LN: Cert verify CTN: cert fail, cert-to-name will continue on the next cert in chain.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: [INF]: LN: Cert verify: depth 0.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: [INF]: LN: Cert verify: subject: /C=in/ST=ut/L=ut/O=ut/OU=ru/CN=ut/emailAddress=ut@gmail.com.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: [INF]: LN: Cert verify: issuer: /C=in/ST=ut/L=ut/O=ut/OU=ru/CN=ut/emailAddress=ut@gmail.com.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: [INF]: LN: Cert-to-name unsuccessful, dropping the new client.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: [ERR]: LN: Client certificate error (application verification failure).
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: [ERR]: LN: SSL accept failed (certificate verify failed).
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: Cert verify: subject: /C=in/ST=ut/L=ut/O=ut/OU=ru/CN=ut/emailAddress=ut@gmail.com.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: Cert verify: issuer: /C=in/ST=ut/L=ut/O=ut/OU=ru/CN=ut/emailAddress=ut@gmail.com.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: Cert verify CTN: cert fail, cert-to-name will continue on the next cert in chain.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: Cert verify: depth 0.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: Cert verify: subject: /C=in/ST=ut/L=ut/O=ut/OU=ru/CN=ut/emailAddress=ut@gmail.com.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: Cert verify: issuer: /C=in/ST=ut/L=ut/O=ut/OU=ru/CN=ut/emailAddress=ut@gmail.com.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: Cert-to-name unsuccessful, dropping the new client.
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: Client certificate error (application verification failure).
Aug 08 09:45:01 13266--SW--MCP7 netopeer2-server[41237]: SSL accept failed (certificate verify failed).
Aug 08 09:45:03 13266--SW--MCP7 netopeer2-server[41237]: Call Home client "default-client" endpoint "endpoint-tls" failed connection attempt limit 3 reached.
Aug 08 09:45:03 13266--SW--MCP7 netopeer2-server[41237]: [INF]: LN: Call Home client "default-client" endpoint "endpoint-tls" failed connection attempt limit 3 reached.
Aug 08 09:45:03 13266--SW--MCP7 netopeer2-server[41237]: [INF]: LN: Call Home client "default-client" endpoint "endpoint-tls" connecting...
Aug 08 09:45:03 13266--SW--MCP7 netopeer2-server[41237]: [INF]: LN: Trying to connect via IPv4 to 172.17.167.137:4335.
Aug 08 09:45:03 13266--SW--MCP7 netopeer2-server[41237]: [INF]: LN: getsockopt() error (Connection refused).
Aug 08 09:45:03 13266--SW--MCP7 netopeer2-server[41237]: Call Home client "default-client" endpoint "endpoint-tls" connecting...
Aug 08 09:45:03 13266--SW--MCP7 netopeer2-server[41237]: Trying to connect via IPv4 to 172.17.167.137:4335.


**Steps to Reproduce:**
1. Start the netopeer2-server.
2. Run `listen --tls` command from netopeer2-cli.
3. Observe the error log.

**Expected Behavior:**
The TLS Call Home connection should be established successfully.

**Actual Behavior:**
The connection fails with the error: `SSL accept failed (certificate verify failed)`.
Any help resolving this issue would be greatly appreciated.


regard
aarti

**Comment by mattcaswell** [comment]
Please create a new discussion item for this question rather than adding to a long closed old issue:

https://github.com/openssl/openssl/discussions/new?category=q-a
