### ISSUE TITLE
P and Q used after key generation

### ISSUE THREAD

**Issue by GuillermoEscobero** [openssl/openssl#11128]
I'm using OpenSSL 1.1.1d

My question is: in theory, when generating a new RSA key, P and Q primes can be discarded after the key is generated.

Does OpenSSL follow this? Specifically, I am having some problems when trying to do the initial TLS handshake, using a valid certificate and a valid private key, but only with n, d and e defined. Of course, the key is generated elsewhere. 

Thanks

**Comment by davidben** [comment]
P and Q are typically not discarded since they're used as part of the CRT optimization. OpenSSL should support RSA keys without CRT parameters (alas RSA dates to an era of cryptography where we were extremely bad at standardizing things so there are many ad hoc variations on RSA private keys), but the standard RSAPrivateKey serialization requires all the CRT parameters, so it's possible whatever you're doing involves serializing them and your key is getting messed up in the process.
https://tools.ietf.org/html/rfc8017#appendix-A.1.2

**Comment by mattcaswell** [comment]
OpenSSL can handle keys without p and q present - although performance will be impacted. I do recall a problem not that long ago where someone had a key where p/q were *present* but set to 0 - which was causing some problems!

**Comment by GuillermoEscobero** [comment]
> OpenSSL can handle keys without p and q present - although performance will be impacted. I do recall a problem not that long ago where someone had a key where p/q were _present_ but set to 0 - which was causing some problems!

That was my problem!

**Comment by mattcaswell** [comment]
> That was my problem!

Great! So can we close this issue?

**Comment by GuillermoEscobero** [comment]
> Great! So can we close this issue?
Yes! Thanks
