### ISSUE TITLE
Dates & releases missing ChangeLog web Page

### ISSUE THREAD

**Issue by raveendrapadala** [openssl/openssl#11247]
OpenSSL Team,

In changelog page (i.e.,https://www.openssl.org/news/changelog.html). i have few observations, i belive fixing them will help users.

- The date was not updated for the below item "Changes between 1.1.1a and 1.1.1b [xx XXX xxxx]"
- The 1.1.1d was released but the changes from 1.1.1b to 1.1.1c and 1.1.1c to 1.1.1d is missing
- The date was not updated for "Changes between 1.1.1 and 3.0.0 [xx XXX xxxx]". Can some one tell when it will be released atleast the approximate date. Please share the procedure to checkout latest 3.0 code.

**Comment by mattcaswell** [comment]
This is because the CHANGES file in the master branch has not been updated with the lastest releases from 1.1.1. There's not a great need for us to do that until we actually get to the point of releasing 3.0. The CHANGES file in the 1.1.1 branch is up to date:

https://www.openssl.org/news/cl111.txt

The timeline for 3.0 release is on our release strategy page:

https://www.openssl.org/policies/releasestrat.html

Skip to about 2/3 way down the page and you will see the planned alpha and beta releases and the approximate final release (early Q4 2020).

Details on checking out our code are here:

https://www.openssl.org/source/gitrepo.html

The 3.0 code is in the master branch.

**Comment by raveendrapadala** [comment]
Thanks matt.
