### ISSUE TITLE
Incorrect handling of TLS 1.2 CBC IV field

### ISSUE THREAD

**Issue by ehohenstein** [openssl/openssl#11266]
I apologize if I am mistaken about this but I believe I have found a discrepancy between the behavior of OpenSSL and the TLS 1.2 spec with regard to the encoding of a record when using a block mode cipher. While working on my own TLS library (for fun) I was using curl (version 7.58.0 on ubuntu bionic compiled with OpenSSL 1.1.1) to test and I found something that I had trouble making sense of at first. When as the server, decrypting the first encrypted TLS record sent by a curl client, being the Finished record, the IV field of the `GenericBlockCipher` struct appears to be included in the portion that is being encrypted by curl (and OpenSSL). If the record decryption doesn't start with the IV field, the Finished record does not decrypt correctly. If the record decryption starts with the IV field, the Finished message data is decrypted correctly with record type 20 and length 12 following the IV field. According to the TLS 1.2 spec, the IV field is not part of the encrypted record for CBC ciphers and the encryption should only include the payload, MAC, padding length, and padding. Here is the definition of the `GenericBlockCipher` struct from the spec:

```
struct {
    opaque IV[SecurityParameters.record_iv_length];
    block-ciphered struct {
        opaque content[TLSCompressed.length];
        opaque MAC[SecurityParameters.mac_length];
        uint8 padding[GenericBlockCipher.padding_length];
        uint8 padding_length;
    };
} GenericBlockCipher;
```

At first, I was discouraged because I thought that there must be some magic that was not in the spec or else I was misinterpreting it. However, I now suspect that the OpenSSL implementation is actually just incorrect since here is the `GenericBlockCipher` from the TLS 1.1 spec:

```
block-ciphered struct {
    opaque IV[CipherSpec.block_length];
    opaque content[TLSCompressed.length];
    opaque MAC[CipherSpec.hash_size];
    uint8 padding[GenericBlockCipher.padding_length];
    uint8 padding_length;
} GenericBlockCipher;
```

Note the difference here that the entire struct is "block-ciphered", including the IV field. This makes me think that the OpenSSL implementation for TLS 1.2 was just inherited from the TLS 1.1 implementation and this change in the spec was overlooked. This would make sense since the section in the TLS 1.2 spec regarding changes from TLS 1.1 does not mention this difference.

I'm no expert on the OpenSSL source code, but reviewing the `tls1_enc` function in `ssl/record/ssl3_record.c` seems to confirm that the IV field is written before encryption. I am assuming that `tls1_enc` is used for both TLS 1.1 and TLS 1.2. I don't see a version of `tls1_enc` that would be specific to TLS 1.2.

I have tried to duplicate this behavior using `s_client`, however, I've been unable to get `s_client` to offer the specific cipher that my library supports for the moment, which is `TLS_RSA_WITH_AES_128_CBC_SHA` (0x00, 0x2F). I'm initially implementing that cipher because it's relatively simple and because the TLS 1.2 spec explicitly states that all TLS 1.2 implementations must support this cipher.

Assuming the behavior of OpenSSL is actually wrong, I imagine it is too late to change it at this point since I assume that it would be incompatible with other (all?) TLS implementations. It also seems like CBC ciphers are now rarely used. I mostly am just trying to understand if OpenSSL is correct or not or if I am misunderstanding the TLS 1.2 spec.

**Comment by mattcaswell** [comment]
> When as the server, decrypting the first encrypted TLS record sent by a curl client, being the Finished record, the IV field of the GenericBlockCipher struct appears to be included in the portion that is being encrypted by curl (and OpenSSL).

What makes you think we encrypt the IV? This does not make sense since the IV is an input to the encryption process.

**Comment by ehohenstein** [comment]
My understanding was that the IV used to encrypt the first record is derived from the master secret and the IV in each record is used to encrypt/decrypt the following record. I was mistaken about this. I think I must have gotten this understanding from something I read that was not the TLS 1.2 spec. Indeed, the TLS 1.2 spec says this:

```
Currently, the client_write_IV and server_write_IV are only generated
for implicit nonce techniques as described in Section 3.2.1 of
[AEAD].
```

That being said, it seems that encryption must be starting with the IV rather than from the start of the Finished message + MAC + padding. Here is what I am seeing. When receiving an encrypted handshake message following a `ChangeCipherSpec` message during the initial handshake from the client (curl), the record type is handshake (22) and then length is 64. The negotiated cipher suite is `TLS_RSA_WITH_AES_128_CBC_SHA` so the encryption block length (and IV length) is 16 bytes and the MAC length is 20 bytes. When beginning decryption at offset 16 (skipping the 16 byte IV field), using the first 16 bytes of the handshake message as the IV, the Finished message does not decrypt correctly since it has random bytes where the handshake type and length should be, though the padding at the end of the final block is correct. When beginning decryption starting at the first byte of the message using the first 16 bytes of the message as the IV, the decrypted data starting at offset 16 appears to be a correctly formed Finished message with type 20 and length 12 followed by 32 (seemingly random) bytes (12 for the handshake hash and 20 for the record MAC) and then the 1-byte padding length field (with value 11), again with correct padding. I have not yet verified that the handshake hash or MAC are correct in this case but I assume thus far that they are. Is decryption supposed to start at the start of the IV? Why would decryption begin with the IV if encryption did not?

**Comment by mattcaswell** [comment]
> My understanding was that the IV used to encrypt the first record is derived from the master secret and the IV in each record is used to encrypt/decrypt the following record. 

That's how TLSv1.0 works. TLSv1.1 changed this to have an explicit IV.

> When beginning decryption at offset 16 (skipping the 16 byte IV field), using the first 16 bytes of the handshake message as the IV, the Finished message does not decrypt correctly since it has random bytes where the handshake type and length should be, though the padding at the end of the final block is correct. When beginning decryption starting at the first byte of the message using the first 16 bytes of the message as the IV, the decrypted data starting at offset 16 appears to be a correctly formed Finished message with type 20 and length 12 followed by 32 (seemingly random) bytes (12 for the handshake hash and 20 for the record MAC) and then the 1-byte padding length field (with value 11), again with correct padding.

This makes no sense. AES decrypts blocks of 16 bytes at a time. When using CBC mode you xor in an additional 16 bytes of data - which is either an IV, or the ciphertext from the previous block. In both the scenarios you describe the latter blocks should both decrypt the same way since the preceding blocks are the same.

In other words, if you're ciphertext looks like this:

IV: 16-block-IV
Ciphertext: 16-block-CT1, 16-block-CT2, 16-block-CT3 ... 16-block-CTn

Then your output from the decryption should look like this:

Plaintext: 16-block-PT1 16-block-PT2 16-block-PT3 ... 16-block-PTn (including padding)

If instead you feed this in:

IV: 16-block-IV
Ciphertext: 16-block-IV 16-block-CT1, 16-block-CT2, 16-block-CT3 ... 16-block-CTn

Then your output from the decryption should look like this:

Plaintext: 16-block-random-data 16-block-PT1 16-block-PT2 16-block-PT3 ... 16-block-PTn (including padding)

So, the two outputs should be identical except that in the latter case you get 16 bytes of random data (the "decrypted" IV) at the beginning.

The fact that you don't see that suggests there is a problem with the way you are decrypting.

**Comment by mattcaswell** [comment]
Thinking about it more, it seems likely that you are not passing the correct IV into the process somehow, i.e. doing this:

IV: 16-block-random-data
Ciphertext: 16-block-CT1, 16-block-CT2, 16-block-CT3 ... 16-block-CTn

Will result in this:
Plaintext: 16-block-random-data 16-block-PT2 16-block-PT3 ... 16-block-PTn (including padding)

But this:

IV: 16-block-random-data
Ciphertext: 16-block-IV 16-block-CT1, 16-block-CT2, 16-block-CT3 ... 16-block-CTn

Will still give you:

Plaintext: 16-block-random-data 16-block-PT1 16-block-PT2 16-block-PT3 ... 16-block-PTn (including padding)

**Comment by ehohenstein** [comment]
I very much appreciate your time spent considering and responding to my problem. Your description of how it should work (which is detailed and well written) matches my expectation. I could not, however, see how your conclusion could be correct since there are only the 3 calls to EVP_DecryptInit_ex(), EVP_DecryptUpdate(), and EVP_DecryptFinal_ex() and the parameters are all fairly straightforward.

However, when trying to come up with an easy to show example using the bytes of an encrypted record coming from curl and openssl, I managed to not only show that it works precisely as you say it should but also that your conclusion was indeed correct. I must admit I'm ashamed to say that I was passing NULL as the pointer to the IV when calling EVP_DecryptInit_ex() because the pointer to the record payload was only being initialized after that and before calling EVP_DecryptUpdate() since I had originally believed that the IV field was not yet needed at the point of calling EVP_DecryptInit_ex(). I'm guessing that the IV used in that case is some default since EVP_DecryptInit_ex() was clearly not dereferencing the NULL pointer I was giving it.

Thanks again! I am reassured that OpenSSL's handling of CBC IV fields is correct.

**Comment by mattcaswell** [comment]
Great. Glad you got it sorted.

**Comment by arielm33** [comment]
Hello, I apologize if this is not the right place to ask, but I have a question related to what was mentioned above. Apologies also because I am no expert in openssl nor in interpreting rfcS.

I can't see the explicit IV that the client should (?) send over the wire. I coded and configured a dummy aes_128_cbc engine that prints the IV, the key, and some of the first and last blocks processed; plain and cipher texts. I run the following command:

openssl s_client -tls1_2 - debug -connect www.google.com:443 -cipher AES128-SHA -servername www.google.com

In addition to looking at the output of this command, in the debug output of the engine I see the IV with which the cipher was initialized, and when checking with wireshark what I understand would be the GenericBlockCipher, I do not see that it starts with the value of that IV. Instead, I find the result of the encryption of the IV xored with the first block of the plain text. In the following records, I see that the last encrypted block is used as IV.

I would like to clarify that I am not asking about decryption; I understand that block would be discarded, what I can't find is the explicit IV.

Thank you.

**Comment by kaduk** [comment]
@arielm33  Perhaps you could post some of the wireshark output that leaves you confused?
It would be most appropriate to do so as an email to openssl-users@openssl.org, though opening a new issue would be okay as well.

**Comment by arielm33** [comment]
Thank you @kaduk 
I've added more information and details in #11866
