### ISSUE TITLE
ssl3_read_n:unexpected eof while reading while keepalive

### ISSUE THREAD

**Issue by tiiiecherle** [openssl/openssl#11381]
Hey openssl team,

I'm using archlinux with nginx-mainline and php-fpm with all packages up-to-date.

After upgrading to openssl 1.1.1.e we see the following error happening over and over again.

`nginx[11287]: 2020/03/20 23:35:38 [crit] 11287#11287: *64 SSL_read() failed (SSL: error:14095126:SSL routines:ssl3_read_n:unexpected eof while reading) while keepalive, client: x.x.x.x, server: 0.0.0.0:443`

I don't know if this is something that needs to be fixed in openssl, in nginx (or perhaps only a setting) or in the webapps used.

Unfortunately there are no other entries in the logs. I don't know if that helps in any way but I don't even use ssl3 in nginx, only tlsv1.2.

Downgrading to openssl 1.1.1.d solves the issue. I guess it is related to [this](https://github.com/openssl/openssl/commit/db943f43a60d1b5b1277e4b5317e8f288e7a0a3a).

Thanks for any help in advance.

**Comment by kroeckx** [comment]
It probably means the client is not sending a close notify like it
should. See also my comment in #11378.

**Comment by tiiiecherle** [comment]
Thanks, but what does that mean here? As stated above I don't know if this is something that needs to be fixed in openssl, in nginx (or perhaps only a setting), in the webapps used (server) or in the client software.

**Comment by kroeckx** [comment]
I don't know the details of your application, and if this is a
problem or not, and what the right thing to do about it is.

Since you talk about keep alive, I assume that the communication is
done, and are just waiting for the client to send something else or
not. It could be that the client just goes away without telling
you, and that there really isn't anything wrong.

So possible ways to fix this are:
- Fix the client to properly shut down the connection, instead of
  just closing it
- Somehow figure out that nothing is wrong, and not log the error.

**Comment by tiiiecherle** [comment]
Thanks, to be more concrete the used app is [davis](https://github.com/tchapi/davis), a carddav/caldav server and the clients are the macOS default calendar, contacts and reminders apps in the latest version.

So I can't do anything about the clients. Shall I contact the davis developer?

**Comment by itpp16** [comment]
https://forum.nginx.org/read.php?2,287377
Which includes a (dirty) workaround.
There are other entries logged as well related to this issue.

Concern: https://github.com/openssl/openssl/issues/11378
"If we do not return an error, you might be vulnerable to a truncation attack."
??

**Comment by tiiiecherle** [comment]
Thanks for the heads-up. If I get that correctly it has to be fixed in openssl (better) or in nginx and not in the webapp.

**Comment by itpp16** [comment]
I'd first like to understand what this 'truncation attack' is all about before going into the debate where or how this should be resolved.

**Comment by graxlop** [comment]
Just wanted to note here, it's not an nginx specific problem. Lots of server software that uses OpenSSL 1.1.1e is going to have the same errors come up.

I've seen it in dozens of different server software already.

**Comment by kroeckx** [comment]
> Concern: https://github.com/openssl/openssl/issues/11378
> "If we do not return an error, you might be vulnerable to a truncation attack."
> ??

One of the properties SSL/TLS provides is that you can be sure
everything has been received, and that an attacker didn't terminate
the connection. This is done by sending the close notify, to
confirm that you have sent everything. Not all protocols need this,
the protocol itself might also know when all the communication is
done, or the data that was sent over the protocol might indicate
that everything was received. As far as I know, there are cases in
HTTP 1.1 where it's not clear at the HTTP level that everything
was sent or not, but with HTTP 2 it should always be clear.

So you get that error when at the TLS layer we detect an EOF,
but the close notify was not received. This means that for TLS
something went wrong. The application called SSL_read(), but there
was neither data nor a close notify. This means the application
was still expecting data, but we can't return it, so we need to
return an error.

So in case of a peer that does not properly send you the
close notify, you can only work around this by not calling
SSL_read() when you're sure all data was received. And I strongly
suggest you fix the peer that does not send the close notify.

**Comment by tiiiecherle** [comment]
@kroeckx 
> And I strongly suggest you fix the peer that does not send the close notify.

In my case with peer you mean apple fixing the clients or fixing the caldav/carddav server?

**Comment by kroeckx** [comment]
> > And I strongly suggest you fix the peer that does not send the close notify.
> 
> In my case with peer you mean apple fixing the clients or fixing the caldav/carddav server?

As I understand it, it's apple's client that's misbehaving.

**Comment by itpp16** [comment]
>> Concern: #11378 "If we do not return an error, you might be vulnerable to a truncation attack." ??

> One of the properties SSL/TLS provides is that you can be sure everything has been received, and that an attacker didn't terminate the connection.

I've ran through the nginx code to determine what happens after each such event and found they are all 'terminated' on such EOF detection in 1.1.1e (default nginx behavior). This settles my concerns about a possible vulnerability (there isn't any).

Fixing peers is out of server control so in this case we need to patch servers or accept much larger logfiles than normal. A second patch concept can be found on the nginx forum.

**Comment by kroeckx** [comment]
> I've ran through the nginx code to determine what happens after each such event and found they are all 'terminated' on such EOF detection in 1.1.1e (default nginx behavior). This settles my concerns about a possible vulnerability (there isn't any).

I think looking at why you get the error in your log, and saying
that their is no possibility of a vulnerability is just wrong. You
can get that error message both when under attack and for
misbehaving peers. You need to look at the protocol and data
format to know that there is a vulnerability or not.

As since we're talking about nginx, and it talks HTTP 1.1, it IS
vulnerable to an attack under some conditions.

> Fixing peers is out of server control so in this case we need to patch servers or accept much larger logfiles than normal. A second patch concept can be found on the nginx forum.

Always ignoring the error is the wrong way to do it. You need to
be sure that you have actually received all the data, and only
then can you ignore it. It's my understanding that with HTTP 1.1
you can't always be sure that you have received all the data, so
that patch in the forum looks wrong, and just reintroduces a
vulnerability.

I would also recommend removing the "|| ERR_peek_error() == 0" part.
Only when you get SSL_ERROR_ZERO_RETURN did the peer shut down the
connection properly. We previously did return SSL_ERROR_SYSCALL, meaning
a "non-recoverable, fatal I/O error occurred", and nginx decided
to just ignore fatal errors if OpenSSL failed to say what the
error was. So now OpenSSL does say what the error is, and you have
a problem.

I think it's known that the HTTPS ecosystem is broken with regard
to properly terminating the connection, but that does not mean you
should just ignore the problem, you should try to fix it properly
instead.

**Comment by tgy** [comment]
i'm seeing this error on my arch linux's nginx server's logs as well.

**Comment by yourchanges** [comment]
i'm seeing this error on my prod nginx/tengine( with openssl 1.1.1e) server's logs as well.

**Comment by mattcaswell** [comment]
This should be fixed in 1.1.1f. The change that results in "unexpected eof" was reverted. Not that it has *not* been reverted in the master branch so will come back in 3.0.

See #11378 for the full discussion.
