### ISSUE TITLE
ECC Key Generation

### ISSUE THREAD

**Issue by saddy-muchu** [openssl/openssl#11533]
This question is regarding what ECC key generation actually means.
With respect to RSA private key generation, it means that we are basically generating two prime numbers.
But, wrt ECC, what are we generating?

i was trying something as below for ECC key generation:
openssl ecparam -name secp224r1 -genkey -noout -out ecc.priv.pem

**Comment by romen** [comment]
@saddy-muchu in ECC the private key is just a random scalar (smaller than the number of points on the part of curve that is safe for cryptographic use).

The keygen algorithm then multiplies a predetermined public point of that curve called generator by the random scalar to generate your public key.
Multiplying a point by a scalar just means adding that point to itself a number of times equal to the scalar.

The properties of elliptic curves define how to add 2 distinct or identical points, and have the property that the result of such addition is always a point belonging to the curve.

So, in the end, what we generate as an ECC keypair is a secret random number, and a public curve point associated to the secret scalar because it's the result of scalar times generator point.

The (assumed difficulty of the) elliptic curve discrete logarithm problem is the foundation of ECC: it postulates that, assuming the curve parameters and the generator point have been picked correctly, the complexity of correctly guessing the secret scalar knowing the public point and all curve parameters including the generator is not much less than having to test all possible secret scalar multiplying each of them by the generator until a match with the public key is found.
"not much less" here is intentionally vague: with more clever algorithms an attacker can generally halve the number of steps required to reveal the secret scalar, but choosing the curve parameters appropriately we can still end up with a cryptosystem for which we believe it is infeasible to discover the private key with knowledge of the public key in a reasonable amount of time (at least until very powerful post quantum computers are available that allow to run better algorithms to try and guess the secret scalar).

**Comment by saddy-muchu** [comment]
Thanks for the detailed information.
This was helpful.
