### ISSUE TITLE
EVP_DigestSignInit fails with "ED25519" provider key

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#11571]
OpenSSL master branch.

When a ED25519 key is created with:
EVP_PKEY_CTX_new_from_name(NULL, SN_ED25519, NULL)
then EVP_DigestSignInit(ctx, NULL, NULL, NULL, key) fails.

**Analysis**
The problem is that in do_sigver_init, if mdname is NULL, it is obtained using EVP_PKEY_get_default_digest_name:
https://github.com/openssl/openssl/blob/master/crypto/evp/m_sigver.c#L156

EVP_PKEY_get_default_digest_name returns an empty string ""
https://github.com/openssl/openssl/blob/master/crypto/evp/p_lib.c#L1029
Which is then passed to canon_mdname
canon_mdname returns the same empty string (and not NULL):
https://github.com/openssl/openssl/blob/master/crypto/evp/m_sigver.c#L33

mdname with value "" is then passed to eddsa_digest_signverify_init, which then fails with PROV_R_INVALID_DIGEST,
because it is expecting mdname to be NULL and not an empty string:
https://github.com/openssl/openssl/blob/master/providers/implementations/signature/eddsa.c#L59

**Possible Fix**
Make canon_mdname return NULL if the string is empty. 
Or make EVP_PKEY_get_default_digest_name return "UNDEF" (through the provider param OSSL_PKEY_PARAM_DEFAULT_DIGEST):
https://github.com/openssl/openssl/blob/master/crypto/evp/p_lib.c#L1012

**Comment by levitte** [comment]
It actually runs deeper than that.  For Ed keys, the undefined is not only a default digest, but a *mandatory* digest.  This cannot be assumed, but must be specified in the Ed25519 / Ed448 implementations.

Fix coming up!

**Comment by levitte** [comment]
What's weird, though, is that `test/evp_test.c` appears to do exactly what you're trying to do with Ed25519 keys, and doesn't fail.  I haven't dug very deep yet, so I hope to find out what differs...

**Comment by matbech** [comment]
I'm not sure but evp_test.c uses PEM_read_bio_PrivateKey which returns a legacy PKEY. The problem is only with keys from providers. E.g. when using EVP_PKEY_CTX_new_from_name
The issue does not happen when the EVP_PKEY is created with EVP_PKEY_CTX_new_id.

**Comment by levitte** [comment]
It turns out that as long as an EVP_PKEY has an EVP_PKEY_ASN1_METHOD attached to it, that's what's going to be used to find the default digest, regardless of if EVP_DigestSignInit() uses a provider export or not.  That's why the evp_test.c checks never fail, they simply do not exercise the provider method to get the default digest.

The fix turns out to be a bit more elaborate than I expected...

**Comment by levitte** [comment]
Fix in #11576

**Comment by hellow554** [comment]
This seems to be fixed on the master branch, is there a back to packport it to the 1.1.1 branch as well? Or if not, is there any other way to tell openssl which digest to use?

I want to be able to sign a squashfs file with rauc (https://github.com/rauc/rauc/) and it gives me this error which seems to be the same one as this issue is about.

```
Failed to create bundle: failed signing bundle: failed to create signature: error:2E066080:CMS routines:CMS_add1_signer:no default digest
140224897656640:error:2E094063:CMS routines:CMS_sign:add signer error:../openssl-1.1.1h/crypto/cms/cms_smime.c:451:
```

It gives me the error when I try to sign a bundle with a ED25519 (or ED448) certificate.

**Comment by kroeckx** [comment]
That is probably a different issue, please open a new issue.
