### ISSUE TITLE
3.0.0-alpha1: Testsuite for test_ocsp accesses folder in --openssldir

### ISSUE THREAD

**Issue by sebastianas** [openssl/openssl#11645]
I have OpenSSL 1.1.1 installed, built with --openssldir=/usr/lib/ssl.
If I configure 3.0.0-alpha1 with --openssldir=/usr/lib/ssl then the testsuite for test_ocsp fails. It seems that the test access "/usr/lib/ssl" and something in there has an influence on the test.
The openssl.cnf in there has
> MinProtocol = TLSv1.2
> CipherString = DEFAULT@SECLEVEL=2

which is non-standard.

**Comment by mattcaswell** [comment]
Hmm. So far I have been unable to reproduce this. What platform are you on?

**Comment by kroeckx** [comment]
The platform is Debian. I can repdocuce this.

**Comment by kroeckx** [comment]
Didn't really look, but I assume it then tries to look into
/usr/lib/ssl/certs/, instead of the default /usr/local/ssl/certs
which doesn't exist.

And /usr/lib/ssl/certs is a symlink for /etc/ssl/certs, containing
the root CAs.

With a normal ./config, I get things like this in the output:
40:42:73:CE:A7:7F:00:00:error:system library:file_open:No such file or directory:crypto/store/loader_file.c:849:calling stat(/usr/local/ssl/certs)

The test suite should not try to use files outside the source or
build directory.
