### ISSUE TITLE
How to disable TLS 1.3 DHE key exchange for nginx+OpenSSL?

### ISSUE THREAD

**Issue by okudayukiko** [openssl/openssl#11778]
OS: Ubuntu 20.04
How to disable TLS 1.3 DHE-RSA key exchange for nginx+OpenSSL? Only use ECDHE-RSA key exchange.
`ssl_protocols TLSv1.2 TLSv1.3;`
`#ssl_ciphers doesn't effect on TLS 1.3`
`ssl_ciphers ECDHE_RSA_AES128_GCM_SHA256;`
How to disable TLS 1.3 DHE Group for nginx?
https://tools.ietf.org/id/draft-ietf-tls-tls13-21.html#negotiated-groups

**Comment by kaduk** [comment]
This seems like an nginx question and not an OpenSSL question: you need to know what nginx configuration option will cause the openssl API like SSL_CTX_set1_groups_list() to be called.  Note that I say "API like" because there are several related APIs that would do a similar thing -- they are all in the same man page.

P.S. A better reference at this point is https://tools.ietf.org/html/rfc8446#section-4.2.7

**Comment by tspearconquest** [comment]
For those looking:

`     ssl_conf_command Ciphersuites TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256;`

This is how you configure TLSv1.3 ciphers in nginx NOTE! if you supply this entry, nginx will not respond to TLSv1.2 at all for any endpoint. See https://mailman.nginx.org/pipermail/nginx/2014-November/045738.html for more info about why not.
