### ISSUE TITLE
EVP_CIPHER_CTX_iv_noconst is too heavyin 3.0

### ISSUE THREAD

**Issue by vt-alt** [openssl/openssl#11800]
Isn't `EVP_CIPHER_CTX_iv_noconst` became too heavy in 3.0 version in comparison to 1.x? `EVP_CIPHER_CTX_iv_noconst` is used extensively in gost-engine for all basic cipher operations of modes with IVs.

Old version:
```
unsigned char *EVP_CIPHER_CTX_iv_noconst(EVP_CIPHER_CTX *ctx)
{
    return ctx->iv;
}
```
New version:
```
unsigned char *EVP_CIPHER_CTX_iv_noconst(EVP_CIPHER_CTX *ctx)
{
    int ok;
    unsigned char *v = ctx->iv;
    OSSL_PARAM params[2] = { OSSL_PARAM_END, OSSL_PARAM_END };

    params[0] =
        OSSL_PARAM_construct_octet_ptr(OSSL_CIPHER_PARAM_IV, (void **)&v,
                                       sizeof(ctx->iv));
    ok = evp_do_ciph_ctx_getparams(ctx->cipher, ctx->provctx, params);

    return ok != 0 ? v : NULL;
}
```
This may affect significantly encryption of small blocks.
Speed comparison of an old and new version. Old:
```
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
grasshopper-cbc    54905.81k    51768.32k    51011.67k    54638.59k    54692.52k    54684.33k
grasshopper-cbc    55395.85k    52204.48k    54039.81k    54633.81k    54711.64k    54733.48k
```
New:
```
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
kuznyechik-cbc    49810.94k    47844.57k    48340.82k    53941.93k    54536.87k    52012.35k
kuznyechik-cbc    47824.08k    49866.92k    53561.77k    54427.99k    54195.54k    52778.33k
```

Note ~15% slow down of `16 bytes` chink test.
@beldmit

**Comment by levitte** [comment]
We know this is going to happen.  The reason is that the structure has changed quite heavily so that things that strictly belong with the implementation stay with the implementation (i.e. is part of the implementation data).

Before 3.0, this wasn't quite the case, as some implementation data was stored in the general context like EVP_CIPHER_CTX instead of the implementation data.  This is the case for IVs.

One way to solve this is for your code to ignore the general IV data in EVP_CIPHER_CTX, and have your own IV in your data structures, such as `ossl_gost_cipher_ctx`.  That's also going to make it easier to convert the code to the provider form.

**Comment by vt-alt** [comment]
IC. Thanks!

@beldmit note that we could/should rework some ciphers to speed them up slightly.

**Comment by beldmit** [comment]
Got it...

**Comment by levitte** [comment]
I assume we can close this now.
