### ISSUE TITLE
the  #10756  cause compatible issue for certificate that parse errors in x509v3_cache_extensions

### ISSUE THREAD

**Issue by Tomasmule2015** [openssl/openssl#11819]
version: 1.1.1f
the [#10756](https://github.com/openssl/openssl/pull/10756) fix all kinds of parse errors in x509v3_cache_extensions,  this change for certificate that parse errors in x509v3_cache_extensions 
 not friendly, it will cause handshake failed. since handshake will call X509_check_purpose and X509_check_issued.

i think the x509v3_cache_extensions  is not key point of certificate, Is it necessary to influence the handshake process？

**Comment by richsalz** [comment]
Suppose there is an extension marked CRITICAL that OpenSSL doesn't know about.  It should fail.

**Comment by Tomasmule2015** [comment]
I get a compatible issue in my project. And want to check those points.

1. Does the commit is to fix a security issue or just to fix an ordinary issue?
2. I get a compatible issue, we have some older certificate that is not conform to the specifications. the BasicConstraints like this:
 
![image](https://user-images.githubusercontent.com/13390030/82117236-7663c400-97a1-11ea-92d0-cf1e40ce1416.png)
we make a invalid certificate(the pathlen should not be there). But it can run well before this commit. I think this commit maybe cause compatible issue, but release note not remind this point.
Maybe this point need to remind?
3. I can use the openssl to make this invalid certificate. Since there is no check for this function
v2i_BASIC_CONSTRAINTS:
 
![image](https://user-images.githubusercontent.com/13390030/82117328-bdea5000-97a1-11ea-9836-6b3d75c875af.png)

I think maybe this point can be change to like this:
else if (strcmp(val->name, "pathlen") == 0 && bcons->ca) {
            if (!X509V3_get_value_int(val, &bcons->pathlen))
                goto err;
 }

**Comment by chensqecc** [comment]
i meet similar issue , can you check this point ,thanks.
i am a  little confust about it ,since this change will lead ssl behavior changed, i think this should infrom users ,while releasenote is not showing this point.
@richsalz

**Comment by chensqecc** [comment]
can anybody check this point?

**Comment by t8m** [comment]
I do not think making the code to accept such truly invalid certificates would be the right thing.

**Comment by richsalz** [comment]
I cannot read the screenshot you posted, posting as plain text is much better.  Or mark it as "code" by using three backticks before and after.

You can use OpenSSL to make invalid certificates, yes.  That is useful to be a testing tool.

The PR that caused you problems (#10756) made OpenSSL check things more strictly. It was not labelled as a security fix, but there are *probably* security implications because of the better checking.

OpenSSL is pretty "loose" in what it accepts, and there are options and flags to control this. Most of that acceptance is about what extensions and their values it allows.  That is *not* the same as having an extension with an invalid value, such as ```CA:true``` and no ```pathlen``` value.

It is up to the project team to decide (I am not part of the team), but I agree that this should be closed, sorry.

**Comment by Tomasmule2015** [comment]
sorry one more question. Does the community have any plan to compatible  this point？ such as add an new api to make compatible or any other  method . because there are some invalid certificates running on the existing network.
