### ISSUE TITLE
Provider query function called many times

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#11814]
While running a test in the debugger I noticed that the provider query function was being called many times - even though `no_cache` is set to 0.

I *think* what is happening is that the algorithms that are present are caching. But algorithms that are not present result in a fresh query to the underlying provider every time. But for most providers (unless `no_cache` is set to 1) then the result is not going to change every time you query it. We really should remember whether we have previously queried a provider and not ask again if we haven't. If we've already previously asked all the available providers, and the algorithm isn't in the cache - then we don't have it and should fail.

**Comment by levitte** [comment]
What happens is that each time an implementation is fetched, the core fetching functionality will cache all the implementations in a `OSSL_ALGORITHM` array whose property definition *matches the current property query string* (merged with the default one).  The method cache stores the method, indexed with the combined algorithm named + property query string.

The next time around, the method cache is checked first, to see if there is a method for the combined name + property query string.  If there is, it should be immediately returned.  Otherwise, the same implementation foraging loop is run again, most likely *with a different property query string*, which may very well match other algorithms this time around.

I think you do need to remember the property definition strings are tied to each implementation, not to the provider as a whole.

**Comment by paulidale** [comment]
We only cache the final result don't we?
If the result is a fail, we need to query anew.

**Comment by mattcaswell** [comment]
> matches the current property query string

My debugger session maintained exactly the same property query string (i.e. none) throughout

**Comment by mattcaswell** [comment]
I don't really see the relevance of the property query string in deciding whether to call the provider's query function or not. The query string matching is all handled in core. The provider's query functions just return the same static results each time - and yet we call them over and over again. This seems wrong.

**Comment by levitte** [comment]
Do you have code to point at, or a command that you run?  I'd like to see what you see

**Comment by levitte** [comment]
I'm re-reading your original description, and am noticing details that I skimmed over earlier.  It's true that when the queried algorithm isn't supplied by any provider, the same query loop will happen every time.  I vaguely recall that this was been mentioned, but was shrugged off at the time because of other pressing matters.

It looks to me like we could maintain a simple reallocatable bitstring that records whether we've already queried a specific operation with a bit each.

BTW, I don't necessarily see a need to rush into fixing this unless someone does have some time over.  This can be saved for the beta period.

**Comment by mattcaswell** [comment]
> Do you have code to point at, or a command that you run? I'd like to see what you see

Set a breakpoint at the beginning of the default provider's query function:

https://github.com/openssl/openssl/blob/a87820e16bbbbb1f8a68ddaf3aa1159da886acca/providers/defltprov.c#L515

Then start s_server. I see the query function being called 13 times just to start s_server (across 2 different operations). I would have expected it to be called 2 times (once for each operation).

**Comment by mattcaswell** [comment]
> BTW, I don't necessarily see a need to rush into fixing this unless someone does have some time over. This can be saved for the beta period.

Agreed. It's not urgent. I just noticed the behaviour and was surprised by it, so I wanted to record the issue.

**Comment by paulidale** [comment]
> It looks to me like we could maintain a simple reallocatable per-OSSL_PROVIDER bitstring that records whether we've already queried a specific operation with a bit each.

I'm not sure how this would work.

The issue here looks to be that we don't cache negative results.  We could add them to the cache.

**Comment by levitte** [comment]
> I'm not sure how this would work.

You're thinking in terms of threads, right?  For the uni-thread case, it's actually pretty straight forward, it only takes an extra pointer in OSSL_PROVIDER and a couple of extra callbacks in the functions in `crypto/core_algorithm.c`

**Comment by paulidale** [comment]
Actually, no.  I'm wondering why a query for MD2 should imply a query for SHA3-512 has been done.

When the provider is queried, we're looking for a specific algorithm and we don't care about others.  I don't see how a bit string of queries helps.

**Comment by levitte** [comment]
> Actually, no. I'm wondering why a query for MD2 should imply a query for SHA3-512 has been done.

That's not what this is about.  What @mattcaswell actually asks is, *if the `OSSL_ALGORITHM` array that contained both was queried once already, why does it need to be queried again?*  That is a valid question, as long as that array is unchanging.

> When the provider is queried, we're looking for a specific algorithm and we don't care about others.

This is not true.  We do construct methods for *all* the stuff we find in a `OSSL_ALGORITHM` array and store them in the method store, on the fly.

> I don't see how a bit string of queries helps.

It might be that you're mixing query with query.  The query we talk about here is this downcall:

https://github.com/openssl/openssl/blob/fab8fde3fc5ee871b0f92e207343a45ad8cc36b1/include/openssl/core_numbers.h#L162-L164

**Comment by levitte** [comment]
While I was looking, I found a couple of bugs in `algorithm_do_this()`...

**Comment by levitte** [comment]
There is one detail for which I was confused earlier in this discussion: The methods are stored with their property *definition* in the method *store*, not with the property *query* they were fetched with.  They are then stored in the method *cache* as well, and that's where the property query is taken into account.

Sorry for confusing things.
