### ISSUE TITLE
armv8-a+crc does not link on master

### ISSUE THREAD

**Issue by kochtopf** [openssl/openssl#11910]
Makeing on a Raspberry pi3 (inux pi3 5.4.35-v7+ #1314 SMP Fri May 1 17:41:46 BST 2020 armv7l GNU/Linux)  with '-march=armv8-a+crc' works for Branch 1_1_1-stable but does not work on the current master.
make error:
ar: creating libcrypto.a /usr/bin/ld: libcrypto.a(libimplementations-lib-cipher_aes_gcm_hw.o): in function `armv8_aes_gcm_encrypt':
cipher_aes_gcm_hw.c:(.text+0x194): undefined reference to `aes_gcm_enc_192_kernel'...
Is this intentionally or a "new feature/bug"?

**Comment by rmartensen** [comment]
I can confirm this issue on my Raspberry Pi 3B (Linux rpi 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux)

**Comment by samuel-lee-msft** [comment]
Sorry for the noise above - it's my first time creating a PR for openssl!

Could one of you @kochtopf / @rmartensen confirm this change works for you?

**Comment by zorrorffm** [comment]
It seems you are running on 32bit kernel (armv7l GNU/Linux).  I don't think the resulting binary (even you make it successfully) can be run on your host OS which doesn't support aarch64.

Did you just want to cross-compile openssl on your 32bit OS to get binary supporting aarch64 and run it on other machine which OS supports aarch64?

In this case, because your OS is 32bit,  aes-gcm-armv8_64.pl is not used to generate aes-gcm-armv8_64.S at compile-time, so armv8 aes-gcm assembly functions like aes_gcm_enc_192_kernel implemented in aes-gcm-armv8_64.S can't be compiled into objective file.  I guess this is the reason the linker errors are reported.

**Comment by kochtopf** [comment]
Better late than never: The Pi3B+ (BCM2837 64bit CPU but crypto HW disabled) can link with  '-march=armv8-a+crc'  after 
 appending ' && AES_PMULL_CAPABLE' to line 93 and 101 in /include/crypto/aes_platform.h. It would then work on armv7l GNU/Linux (32bit) like the stable branch does. Thanks to Samuel Lee for the initial patch.
