### ISSUE TITLE
ENGINE in OPENSSL

### ISSUE THREAD

**Issue by saddy-muchu** [openssl/openssl#11999]
What is the concept of an engine in the context of OPENSSL?
What are its specific use cases?

**Comment by romen** [comment]
You can read a great deal of information about ENGINEs in the project documentation : https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/doc/man3/ENGINE_add.pod

Consider that the current development of the next major release of OpenSSL is moving that concept even further, into a new architecture based on "providers". 

You can read more about the design of the upcoming 3.0.0 release at: https://www.openssl.org/docs/OpenSSL300Design.html


In 3.0.0 ENGINEs will be deprecated in favor of providers, but there should still be at least limited support for the existing ENGINE API.

Another great source of info about differences between previous release and the upcoming 3.0.0 can be found in the wiki: https://wiki.openssl.org/index.php/OpenSSL_3.0

**Comment by saddy-muchu** [comment]
The links you shared were of great help.

Btw, how do i list the supported engines on my hardware?

**Comment by romen** [comment]
> The links you shared were of great help.
> 
> So, as far as i understand it OpenSSL has built-in support for cryptographic acceleration using the ENGINE object type. if i have a hardware device with a super fast implementation of ECDSA, then i can set the engine to that hardware device (instead of NULL), which means that the operations are now computed by the hardware device instead of the default OpenSSL software layer. Am i correct?

Yes, `ENGINE`s were originally designed exactly for supporting hw implementations, but their flexibility allowed them to be generally used as "bags" of alternative or new implementations, even in software.
E.g. the GOST engine is comprised of software implementations that enrich the capabilities of libcrypto by allowing users to dinamically load support for cryptographic algorithms mandated by the Russian government.
In other cases they have been used as research tools to, e.g., test and validate alternative implementations of already supported algorithms.


> Also, the implementations of the engines are done by specific hardware vendors and later, depending on the need, the application needs to load it dynamically?

Depending on the version, OpenSSL has historically provided a set of built-in engines, some of which are built statically into the library at compile-time and others result in "dynamic" engines that are loadable at run-time.

The details of how an application can make use of a specific set of dynamic engines depend on a few factors.
In general the recommended way is to edit the system-wide or application-specific OpenSSL config file, so that it has an "engines" section to provide all the information necessary to load the desired set of functionality.
Applications that always fully initialize libcrypto by loading the config file don't need any further change, and enabling or disabling this or that engine is completely transparent.
Unfortunately, up to 1.1.1, while applications linking against libssl are always required to fully load the config file, applications that only link against libcrypto are not strictly required to load the configuration file, so your mileage about _transparent_ ENGINE support in libcrypto-only applications might vary: some of these applications might need to either be modified to properly load the config file on init or to explicitly try to load an engine programmatically.

Beware that the upcoming 3.0 release will introduce the concept of providers, that will supersede the ENGINEs. While the ENGINE API will still be supported, it will be considered legacy, deprecated, and there might be usability issues in trying to use advanced features of the provider architecture and legacy ENGINEs at the same time.

> Btw, how do i list the supported engines on my hardware?

https://www.openssl.org/docs/man1.1.1/man1/engine.html

**Comment by romen** [comment]
> Btw, how do i list the supported engines on my hardware?

I should probably expand a little bit more about this, but the previous comment was already quite long.

Anyway: as mentioned before the [`openssl engine`](https://www.openssl.org/docs/man1.1.1/man1/engine.html) CLI tool can be used to inspect engine objects and capabilities.

On my Ubuntu 18.04.4 LTS development machine, using the distribution installation of OpenSSL, I can observe the following:

~~~bash
; openssl engine -t -c -vvvv                                                                                                                   
(rdrand) Intel RDRAND engine
 [RAND]
     [ available ]
(dynamic) Dynamic engine loading support
     [ unavailable ]
     SO_PATH: Specifies the path to the new ENGINE shared library
          (input flags): STRING
     NO_VCHECK: Specifies to continue even if version checking fails (boolean)
          (input flags): NUMERIC
     ID: Specifies an ENGINE id name for loading
          (input flags): STRING
     LIST_ADD: Whether to add a loaded ENGINE to the internal list (0=no,1=yes,2=mandatory)
          (input flags): NUMERIC
     DIR_LOAD: Specifies whether to load from 'DIR_ADD' directories (0=no,1=yes,2=mandatory)
          (input flags): NUMERIC
     DIR_ADD: Adds a directory from which ENGINEs can be loaded
          (input flags): STRING
     LOAD: Load up the ENGINE specified by other settings
          (input flags): NO_INPUT
~~~

I am using the default configuration provided by the distribution maintainers here, which is not loading any extra dynamic `ENGINE`, while the `openssl` CLI apps all try to enable all available builtin engines.

The two engines listed are two built-in static ENGINEs compiled inside my libcrypto:
- `rdrand` provides optional support for [Intel RDRAND](https://en.wikipedia.org/wiki/RDRAND)
- `dynamic` is the static engine that allows libcrypto to load dynamic engines

To check what other dynamic engines are available in my system:

~~~bash
; openssl version -a
OpenSSL 1.1.1  11 Sep 2018
built on: Tue Nov 12 16:58:35 2019 UTC
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-kxN_24/openssl-1.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
Seeding source: os-specific
; openssl version -a |grep ENGINESDIR
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
; ls /usr/lib/x86_64-linux-gnu/engines-1.1
afalg.so  capi.so  padlock.so
~~~

In the default system-wide ENGINE directory I have three engines available. For each of them we could use the `openssl engine` CLI to try to load them and get more information.

~~~bash
; openssl engine -vvvv -c -tt afalg
(afalg) AFALG engine support
 [AES-128-CBC, AES-192-CBC, AES-256-CBC]
     [ available ]
; openssl engine -vvvv -c -tt capi
140255949046208:error:260B606D:engine routines:dynamic_load:init failed:../crypto/engine/eng_dyn.c:485:
140255949046208:error:2606A074:engine routines:ENGINE_by_id:no such engine:../crypto/engine/eng_list.c:335:id=capi
; openssl engine -vvvv -c -tt padlock
140358876758464:error:260B606D:engine routines:dynamic_load:init failed:../crypto/engine/eng_dyn.c:485:
140358876758464:error:2606A074:engine routines:ENGINE_by_id:no such engine:../crypto/engine/eng_list.c:335:id=padlock
~~~

Apparently the `afalg` ENGINE is the only one that successfully loads: it is meant to support (part of) the [Linux Kernel `AF_ALG` userspace Crypto API](https://www.kernel.org/doc/html/latest/crypto/userspace-if.html) (requires Linux >= 4.1.0).

The `capi` engine should provide support for the [Microsoft CryptoAPI](https://en.wikipedia.org/wiki/Microsoft_CryptoAPI), while `padlock` should support the [VIA PadLock Instruction Set](https://en.wikipedia.org/wiki/VIA_PadLock) on supported VIA CPUs.

3rd party engines can be installed in the default location or somewhere else, depending on the openssl config file and on the use of the `OPENSSL_ENGINES` env var.

~~~sh
; OPENSSL_ENGINES=/tmp openssl engine -vvvv -c -tt afalg                                                                                                              
140552048570816:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:../crypto/dso/dso_dlfcn.c:117:filename(/tmp/afalg.so): /tmp/afalg.so: cannot open shared object file: No such file or directory        
140552048570816:error:25070067:DSO support routines:DSO_load:could not load the shared library:../crypto/dso/dso_lib.c:162:                                                                                                             
140552048570816:error:260B6084:engine routines:dynamic_load:dso not found:../crypto/engine/eng_dyn.c:414:
140552048570816:error:2606A074:engine routines:ENGINE_by_id:no such engine:../crypto/engine/eng_list.c:335:id=afalg
~~~

**Comment by saddy-muchu** [comment]
Thanks for your prompt replies.
This information was really helpful so as to connect the dots.
