### ISSUE TITLE
More bytes are generated for Key Material than needed for AEAD ciphers

### ISSUE THREAD

**Issue by maximmasiutin** [openssl/openssl#12007]
### Bug description

There is a bug that, when generating the Key Material (key_block), OpenSSL generates more data via the PRF than needed for AEAD ciphers.

Please find tls1_setup_key_block()  function in the "t1_enc.c" file.

There is the following code:

    num = EVP_CIPHER_key_length(c) + mac_secret_size + EVP_CIPHER_iv_length(c);
    num *= 2;

later it calls tls1_generate_key_block() to generate “num” of pseudo-random bytes. However, for AEAD ciphers like AES-GCM, the resulting "num" is larger than needed.

Besides that, the order of addition “EVP_CIPHER_key_length(c) + mac_secret_size + EVP_CIPHER_iv_length(c)” is misleading, because according the RFC, the MAC secret key comes first, not second. An easier to understand code would be:

    num = mac_key_length + EVP_CIPHER_key_length(c) + EVP_CIPHER_iv_length(c);

You can add a line like the following

        BIO_printf(trc_out, "key block length: %ld\n", num);

to actually see that more key bytes are generated then needed. 

If you wish to see which of the constituents lead to a decreased key block length, add the line like the following:

        BIO_printf(trc_out, "key block length: %ld (mac_secret_size: %ld, EVP_CIPHER_key_length: %ld, EVP_CIPHER_iv_length: %ld)\n", num, mac_secret_size, EVP_CIPHER_key_length(c), EVP_CIPHER_iv_length(c));

### Steps to reproduce

To reproduce this bug and see it actually, add the above "BIO_printf" line to t1_enc.c after the first entry of OSSL_TRACE_BEGIN(TLS) in tls1_setup_key_block and compile OpenSSL with tracing enabled, and run a TLS 1.2 session with AES256-GCM-SHA384.

When building OpenSSL, add the "enable-trace" parameter to "Configure". For example, for 64-bit Windows, call:

    perl Configure enable-trace enable-ssl-trace VC-WIN64A
    nmake

    set OPENSSL_TRACE=TLS
    openssl.exe s_server

On client, run the following:

openssl.exe s_client -host 127.0.0.1 -port 4433 -tls1_2 -cipher AES256-GCM-SHA384

It will start accepting TLS connections on port 4433. Connect to it with your client with any AEAD cipher suite like AES_GCM and you will see on your console trace data like this:

    TRACE[08:26:00:00]:TLS: Premaster Secret:
    TRACE[08:26:00:00]:TLS:     0000 - 03 03 24 43 41 41 46 d9-de da 55 11 b0 b9 a4 d4   ..$CAAF...U.....
    TRACE[08:26:00:00]:TLS:     0010 - cc 42 5a 21 70 aa b3 30-1f 58 4f f1 ea 1d 4f 58   .BZ!p..0.XO...OX
    TRACE[08:26:00:00]:TLS:     0020 - ab 42 8c 9c 30 62 70 e2-15 41 99 1a 39 a7 60 00   .B..0bp..A..9.`.
    [cut]
    TRACE[08:26:00:00]:TLS: key block length: 88 (mac_secret_size: 0, EVP_CIPHER_key_length: 32, EVP_CIPHER_iv_length: 12)
    TRACE[08:26:00:00]:TLS: client random
    TRACE[08:26:00:00]:TLS:     0000 - df 2d bc 93 11 f2 b2 69-2b cf f6 04 57 61 bd 35   .-.....i+...Wa.5
    TRACE[08:26:00:00]:TLS:     0010 - 97 56 0f 3b 84 97 8f 59-e7 f4 56 2d 9e 39 83 66   .V.;...Y..V-.9.f
    TRACE[08:26:00:00]:TLS: server random
    TRACE[08:26:00:00]:TLS:     0000 - c4 d8 87 ca 6d d1 53 a3-b3 e0 ba bb 4a 68 50 c7   ....m.S.....JhP.
    TRACE[08:26:00:00]:TLS:     0010 - dc 48 c9 2c 8c 20 a3 82-44 4f 57 4e 47 52 44 01   .H.,. ..DOWNGRD.
    TRACE[08:26:00:00]:TLS: master key
    TRACE[08:26:00:00]:TLS:     0000 - 4e 84 e9 a6 f4 e1 40 88-b4 ae a5 97 66 c3 98 9f   N.....@.....f...
    TRACE[08:26:00:00]:TLS:     0010 - eb 74 7b 08 a3 0c 19 f3-f7 f8 69 c2 e4 4c 62 99   .t{.......i..Lb.
    TRACE[08:26:00:00]:TLS:     0020 - 2a 72 9d aa 42 45 0a b2-c2 74 67 2f 88 87 4c bb   *r..BE...tg/..L.
    TRACE[08:26:00:00]:TLS: key block
    TRACE[08:26:00:00]:TLS:     0000 - 72 cf 69 dd 6e 64 06 ae-04 20 a5 7c 44 37 80 7e   r.i.nd... .|D7.~
    TRACE[08:26:00:00]:TLS:     0010 - b4 21 b4 d5 c9 4c 73 79-79 d4 13 16 52 57 b9 82   .!...Lsyy...RW..
    TRACE[08:26:00:00]:TLS:     0020 - be 38 71 e2 0d b3 e5 24-4a 98 0e 89 f3 e4 a9 e6   .8q....$J.......
    TRACE[08:26:00:00]:TLS:     0030 - 34 d5 fd 20 b4 d9 4c ad-63 cc 07 7f e5 b3 05 27   4.. ..L.c......'
    TRACE[08:26:00:00]:TLS:     0040 - 7f 55 15 01 99 67 c4 89-3f 1b e6 25 29 a3 ac b6   .U...g..?..%)...
    TRACE[08:26:00:00]:TLS:     0050 - 89 c8 e0 41 de 4e 78 fb-                          ...A.Nx.
    TRACE[08:26:00:00]:TLS: which = 0021, mac key:
    TRACE[08:26:00:00]:TLS: which = 0021, key:
    TRACE[08:26:00:00]:TLS:     0000 - 72 cf 69 dd 6e 64 06 ae-04 20 a5 7c 44 37 80 7e   r.i.nd... .|D7.~
    TRACE[08:26:00:00]:TLS:     0010 - b4 21 b4 d5 c9 4c 73 79-79 d4 13 16 52 57 b9 82   .!...Lsyy...RW..
    TRACE[08:26:00:00]:TLS: iv:
    TRACE[08:26:00:00]:TLS:     0000 - 7f 55 15 01                                       .U..
    TRACE[08:26:00:00]:TLS: dec 16
    TRACE[08:26:00:00]:TLS:     0000 - 14 00 00 0c 8b bb 53 28-e4 b6 62 2a c7 d9 b0 bf   ......S(..b*....
    TRACE[08:26:00:00]:TLS: which = 0022, mac key:
    TRACE[08:26:00:00]:TLS: which = 0022, key:
    TRACE[08:26:00:00]:TLS:     0000 - be 38 71 e2 0d b3 e5 24-4a 98 0e 89 f3 e4 a9 e6   .8q....$J.......
    TRACE[08:26:00:00]:TLS:     0010 - 34 d5 fd 20 b4 d9 4c ad-63 cc 07 7f e5 b3 05 27   4.. ..L.c......'
    TRACE[08:26:00:00]:TLS: iv:
    TRACE[08:26:00:00]:TLS:     0000 - 99 67 c4 89                                       .g..

You will see that the key block has more bytes the needed.

In the above example, the client IV, being 4 bytes for AEAD are "7f 55 15 01" and the server IV are "99 67 c4 89", but the key block does not end there, and the following key block bytes are unused (3f 1b e6 25 29 a3 ac b6 89 c8 e0 41 de 4e 78 fb).

Also, you may see that EVP_CIPHER_iv_length is "12" here, while only "4" (fixed IV) are actually used from the key block. This difference (12-4)*2=16 led to 16 extra bytes in the key block ((3f 1b e6 25 29 a3 ac b6 89 c8 e0 41 de 4e 78 fb).

### Proposed Solution

Fix the following line, so the key_block would be calculated correctly (also rearrange the order so the parts of the sum came in the same order as in RFC, i.e. mac_secret_size first, key_lengh second and iv_lengh third). To make it be calculated correctly, the actual number of IV bytes from the key block have to be added rather than the general "EVP_CIPHER_iv_length".

    num = EVP_CIPHER_key_length(c) + mac_secret_size + EVP_CIPHER_iv_length(c);

Also, add the following line to the trace to see the key block size.

        BIO_printf(trc_out, "key block length: %ld\n", num);

Update: 
Fixed by #13035

**Comment by jwalch** [comment]
I am trying to wrap my head around the interoperability implications here.

I see that in tls1_change_cipher_state() we have

```
341    /* TODO(size_t): convert me */
342    cl = EVP_CIPHER_key_length(c);
343    j = cl;
344    /* Was j=(exp)?5:EVP_CIPHER_key_length(c); */
345    /* If GCM/CCM mode only part of IV comes from PRF */
346    if (EVP_CIPHER_mode(c) == EVP_CIPH_GCM_MODE)
347        k = EVP_GCM_TLS_FIXED_IV_LEN;
348    else if (EVP_CIPHER_mode(c) == EVP_CIPH_CCM_MODE)
349        k = EVP_CCM_TLS_FIXED_IV_LEN;
350    else
351        k = EVP_CIPHER_iv_length(c);
352    if ((which == SSL3_CHANGE_CIPHER_CLIENT_WRITE) ||
353        (which == SSL3_CHANGE_CIPHER_SERVER_READ)) {
354        ms = &(p[0]);
355        n = i + i;
356        key = &(p[n]);
357        n += j + j;
358        iv = &(p[n]);
359        n += k + k;
360    } else {
361        n = i;
362        ms = &(p[n]);
363        n += i + j;
364        key = &(p[n]);
365        n += j + k;
366        iv = &(p[n]);
367        n += k;
368    }
```

That appears, at least to me, to be partitioning as described by 6.3 of RFC 5246:

```
   The master secret is expanded into a sequence of secure bytes, which
   is then split to a client write MAC key, a server write MAC key, a
   client write encryption key, and a server write encryption key.  Each
   of these is generated from the byte sequence in that order.  Unused
   values are empty.  Some AEAD ciphers may additionally require a
   client write IV and a server write IV (see Section 6.2.3.3).

   When keys and MAC keys are generated, the master secret is used as an
   entropy source.

   To generate the key material, compute

      key_block = PRF(SecurityParameters.master_secret,
                      "key expansion",
                      SecurityParameters.server_random +
                      SecurityParameters.client_random);

   until enough output has been generated.  Then, the key_block is
   partitioned as follows:

      client_write_MAC_key[SecurityParameters.mac_key_length]
      server_write_MAC_key[SecurityParameters.mac_key_length]
      client_write_key[SecurityParameters.enc_key_length]
      server_write_key[SecurityParameters.enc_key_length]
      client_write_IV[SecurityParameters.fixed_iv_length]
      server_write_IV[SecurityParameters.fixed_iv_length]

   Currently, the client_write_IV and server_write_IV are only generated
   for implicit nonce techniques as described in Section 3.2.1 of
   [AEAD].
```

Where I have some uncertainty is the behavior of the PRF. For simplicity, let's say each thing is 1 byte (total 6 bytes). So the current behavior would possibly have a key_block of 0x0101 0x0202 0x0303 0x0404 0x0505 0x0606. Now if we iterate the PRF fewer times (or more output is truncated) to only do a 4 byte output, shouldn't - given the same inputs to the PRF - that result in 0x0101 0x0202 0x0303 0x0404? Maybe my understanding of the PRF here is mistaken.

Now, if that understanding is correct, wouldn't that imply that for the same inputs we suddenly start using different values for the individual pieces (eg, suddenly client_write_key is 0x0101 instead of 0x0303)?

This segues into my questions about the interoperability. If the way OpenSSL is generating and subsequently partitioning the key_block is objectively wrong per the RFC, shouldn't OpenSSL have interoperability issues with RFC-compatible peers? If it doesn't, wouldn't changing this introduce such issues?

**Comment by maximmasiutin** [comment]
Hello jwalch,

This would not accept interoperability, because OpenSSL, in case of AEAD ciphers, generates more key material than it uses, the remaining key material just remains unused. I can give you more details if you wish. Just in a few words, the "_length" for some fields in AEAD is zero. OpenSSL uses the structure correctly, honoring that some fields have zero length. But when it generates the key block, when calculating the size of the block, it does not calculate those _lenghts correctly, as though they were not zero. That's why it generates more data than it uses itself. The code that I have submitted helps to easily demonstrate in the trace that more key material is generated than actually used.

Should you need specific data, just let me know.


-- 
Maxim Masiutin

**Comment by jwalch** [comment]
I understand that potions of the key block are not used directly in the case of AEAD ciphers, not just as specific to OpenSSL implementation but as a general property of the suite and how it is used in the larger protocol. My point is that from the RFC language on how the key block is constructed and partitioned and my (admittedly shaky) understanding of the PRF, it seems like the bytes corresponding to the non-mac keys & the IVs are possibly impacted by the preceding bytes (the MAC keys). Put differently, the existence of the MAC key portion of the key block has an indirect impact even in the AEAD case.

**Comment by maximmasiutin** [comment]
Hello jwalch,

Wednesday, September 23, 2020, 8:23:41 PM, you wrote:

> My point is that from the RFC language
> on how the key block is constructed and partitioned and my
> (admittedly shaky) understanding of the PRF, it seems like the bytes
> corresponding to the non-mac keys & the IVs are possibly impacted by
> the preceding bytes (the MAC keys).

There are no such bytes at all as MAC (client_write_MAC_key/server_write_MAC_key) in the key block in case of AEAD ciphers, because SecurityParameters.mac_key_length is zero. The key block starts straight with the key. And there is also no IV bytes in the key block in case of AEAD ciphers. So, in case of AEAD ciphers, the key block does only contain key bytes ("client_write_key/server_write_key"). OpenSSL handles it correctly. It just generates extra bytes in case of AEAD that it does not use anyway.



-- 
Maxim Masiutin

**Comment by jwalch** [comment]
There are a couple of things you've said that don't make much sense to me. I think that they are tangential to the main point, though.

> [...] when generating the Key Material (key_block), OpenSSL generates more data via the PRF than needed [...] You will see that the "Premaster Secret" has more bytes the needed.

You're talking about two different things here. The pre-master secret is generated long before the key_block. The length of the pre-master secret is related to the Kx. The master secret, which is derived from the pre-master secret (and some other inputs), is always 48 bytes, regardless of the length of the pre-master secret. The key_block is then derived from the master secret. The length of the pre-master secret has no bearing on the length of the key_block; if they happen to line up, it's just by coincidence.

Now, most of your discussion of the code particulars focus on the key_block generation, so I think we can just disregard your discussion of the pre-master secret entirely and try to make sense of what's before that.

> And there is also no IV bytes in the key block in case of AEAD ciphers.

That's just plain incorrect by my reading of RFC 5246. It specifically says: "Currently, the client_write_IV and server_write_IV are only generated for implicit nonce techniques as described in Section 3.2.1 of [AEAD]."

Anyway, the presence or lack thereof for the IVs in the key_block doesn't concern me, because they're at the end. That nicely segues into carrying out the math of the PRF a little more explicitly...

```
seed = "key expansion" + server_random + client_random
a0 = seed
a1 = HMAC-ALG(key=master_secret, data=a0)
a2 = HMAC-ALG(key=master_secret, data=a1)
a3 = HMAC-ALG(key=master_secret, data=a2)
a4 = ...
p1 = HMAC-ALG(key=master_secret, data=a1 + seed)
p2 = HMAC-ALG(key=master_secret, data=a2 + seed)
p3 = HMAC-ALG(key=master_secret, data=a3 + seed)
p4 = ...
key_block = p1 + p2 + p3 + p4 ...
client_write_mac_key = [first mac_len bytes of key_block]
server_write_mac_key = [next mac_len bytes of key_block]
client_write_key = [next key_len bytes of key_block]
server_write_key = [next key_len bytes of key_block]
client_write_iv = [next iv_len bytes of key_block]
server_write_iv = [next iv_len bytes of key_block]
```

(In the above, the "+" operator is concatenation, not addition.)

Hopefully it is straight-forward to see here that client_write_key necessarily depends on the value of mac_len. Even if you keep the same inputs (server_random, client_random, master_secret), changing mac_len will cause the value for client_write_key to change because it changes where you are indexing into key_block. This is why I mentioned the interoperability: it turns out that a good use case for "same inputs to key expansion" is the two sides of a TLS connection; they would have the same values for <server_random, client_random, master_secret> (or do in the working case at least). If OpenSSL were to interact with some TLS implementation that was expecting a different value for mac_len here, the two would disagree on the value for client_write_key (and all the others after) and communication would be doomed.

On the flip side, iv_len does NOT impact client_write_key in the above computation.

**Comment by maximmasiutin** [comment]
It was a mistake to mention "the pre-master secret". I meant the "key
block" there.

**Comment by maximmasiutin** [comment]
In the algorithm notation that you provided, for AEAD,  "client_write_mac_key"
is empty, "mac_len" is zero, "server_write_mac_key" is also empty,
"client_write_key"
starts at the beginning of the = key_block.

Although, in AEAD, MAC is used to generate the key_block bytes, within the
sense of the furter use of key_block bytes,"mac_len" is zero.

**Comment by maximmasiutin** [comment]
That is why it doesn't affect interoperability.

**Comment by maximmasiutin** [comment]
I meant that I have copypasted dump with premaster secret when I should
have given dump with key_block instead.

**Comment by jwalch** [comment]
In tls1_setup_key_block(), the value that you assert is incorrect is assigned to the new_mac_secret_size member. The only other place in the OpenSSL code base that this symbol is referenced is in tls1_change_cipher_state(), where it is used to index into the key_block, as shown in the code snippet further up (look for i,j,k). Therefore, if the wrong value is being used in tls_setup_key_block, it must also be getting used in tls1_change_cipher_state(). It is either right in both places or wrong in both places.

**Comment by jwalch** [comment]
I added a BIO_printf() call for mac_secret_size (the variable) in tls1_setup_key_block() and ran s_client with tracing and "AESGCM" as the cipher string:

```
TRACE[C0:BD:D9:0E:01:00:00:00]:TLS: mac_secret_size: 0
```

I'm really not convinced there's actually any problem being demonstrated in this issue. It seems like the claim is that OpenSSL is using some non-zero value for mac_secret_size in AEAD case, but that tracing experiment I conducted would suggest otherwise.

Just to be clear, I have not been trying to say that mac_secret_size shouldn't be 0 in this case. What is the correct value hasn't been my focus. The point I have been trying to make is that CHANGING the value would necessarily have interoperability implications.

**Comment by maximmasiutin** [comment]
Give me a few hours, let me make a correct trace. It is probably the IV that adds to extra key_block bytes, not the mac_secret_size. In AEAD, fixed part of the IV taken from the key block is 4 bytes, not the same amount of bytes as the block size as for modes like CBC. You have pointed out correctly that the trace that I have given is irrelevant because it gives "Premaster Secret" but not the key block.

**Comment by maximmasiutin** [comment]
Hello jwalch,

I have edited my initial message so not things became clear. See the first message at https://github.com/openssl/openssl/issues/12007 to see the things.

It turned out that that incorrect IV size, not MAC size led to incorrect sum used as a key block size.

This is the line that I have added to see all the constituents:

        BIO_printf(trc_out, "key block length: %ld (mac_secret_size: %ld, EVP_CIPHER_key_length: %ld, EVP_CIPHER_iv_length: %ld)\n", num, mac_secret_size, EVP_CIPHER_key_length(c), EVP_CIPHER_iv_length(c));

I ran openssl as server with a trace, and the client with the following command-line options: "s_client -host 127.0.0.1 -port 4433 -tls1_2 -cipher AES256-GCM-SHA384".

It will start accepting TLS connections on port 4433. Connect to it with your client with any AEAD cipher suite like AES_GCM and you will see on your console trace data like this:

My BIO_printf gave the following output:

    TRACE[08:26:00:00]:TLS: key block length: 88 (mac_secret_size: 0, EVP_CIPHER_key_length: 32, EVP_CIPHER_iv_length: 12)

You may see that EVP_CIPHER_iv_length is "12" here, while only "4" (fixed IV) are actually used from the key block according to the RFC. This difference (12-4)*2=16 led to 16 extra bytes in the key block that are not used.

Please accept my merge commit to get "BIO_printf(trc_out, "key block length" into the code so you will see that more bytes are generated, probably adding code to display other constituents of the sum.

Also please fix somehow that for AES GCM AEAD cipher just 4 bytes are added, not 12, to get the key block size.

I sincerely apologize that I thought that it is the MAC that adds extra bytes, while it turned out to be that it is the IV; but anyway my observation was correct that more bytes were added.

-- 
Maxim Masiutin

**Comment by jwalch** [comment]
I am not a gatekeeper. I can neither accept nor reject any changes you've made. I just happened to find this issue while searching for things to try better understanding how this process (key expansion from master secret) works.

**Comment by maximmasiutin** [comment]
Does my latest edit of the initial report and my latest comment make sense
to you?

**Comment by jwalch** [comment]
Yes, now it is starting to make sense to me how we could have extra bytes in the key_block without impacting interoperability. As long as the indexing / partitioning into the key_block is done correctly, the extra bytes would always be "on the end" and thus not mathematically impact the preceding values. So the key would be if we find that different values for iv_len are used during indexing v/s generation. (Unlike the mac_secret_size case, where we know same value is used in both places.)

From the snippet I posted before, here is the indexing:

```
345    /* If GCM/CCM mode only part of IV comes from PRF */
346    if (EVP_CIPHER_mode(c) == EVP_CIPH_GCM_MODE)
347        k = EVP_GCM_TLS_FIXED_IV_LEN;
348    else if (EVP_CIPHER_mode(c) == EVP_CIPH_CCM_MODE)
349        k = EVP_CCM_TLS_FIXED_IV_LEN;
350    else
351        k = EVP_CIPHER_iv_length(c);
352    if ((which == SSL3_CHANGE_CIPHER_CLIENT_WRITE) ||
353        (which == SSL3_CHANGE_CIPHER_SERVER_READ)) {
354        ms = &(p[0]);
355        n = i + i;
356        key = &(p[n]);
357        n += j + j;
358        iv = &(p[n]);
359        n += k + k;
360    } else {
361        n = i;
362        ms = &(p[n]);
363        n += i + j;
364        key = &(p[n]);
365        n += j + k;
366        iv = &(p[n]);
367        n += k;
368    }
```

So it looks like when we actually read from the key_block, the indexing is done as you describe: special-cased for AEAD (345-349). It's only in generating the key block that we always use EVP_CIPHER_iv_length() for iv_len.

So I think all that needs to be done to fix this is that instead of always adding EVP_CIPHER_iv_length() to the num local in tls1_setup_key_block(), we have some logic like 345-349 above to determine which value to add. Obviously I could open a PR myself for this, but since you found the issue and stuck with it for so long I think you should have right of first refusal.

**Comment by paulidale** [comment]
@mattcaswell, thoughts here?

**Comment by kaduk** [comment]
I am in general not very concerned about running the RNG/PRF/etc. to make a handful more random bytes than we actually use, since that's symmetric crypto and we haven't seen any data indicating a significant performance impact.
If we add in logic to sometimes generate fewer bytes, then we open up some risk that we will mistakenly generate fewer bytes than we use, which potentially causes significant loss of security properties.  So the cost/benefit analysis, given the current data, seems to argue for the status quo.  Simpler code is usually more robust.

**Comment by maximmasiutin** [comment]
@paulidale @kaduk @mattcaswell @jwalch 

I have implemented the idea of @jwalch to use existing code that was already calculating the number of bytes for IV taken from the key_block.

Please accept the pull request https://github.com/openssl/openssl/pull/12032

Here is the new dump after the fix:

    TRACE[BC:5E:00:00]:TLS: key block length: 72
    TRACE[BC:5E:00:00]:TLS: client random
    TRACE[BC:5E:00:00]:TLS:     0000 - f0 82 4c 30 a9 9a 3e 61-d7 89 d6 72 79 a8 73 de   ..L0..>a...ry.s.
    TRACE[BC:5E:00:00]:TLS:     0010 - 40 13 bd 4c 75 b3 57 78-02 06 45 1d 8d c1 bf 18   @..Lu.Wx..E.....
    TRACE[BC:5E:00:00]:TLS: server random
    TRACE[BC:5E:00:00]:TLS:     0000 - e6 9a 30 ef d9 40 30 5a-cd 3b 66 2b ff 62 3c b4   ..0..@0Z.;f+.b<.
    TRACE[BC:5E:00:00]:TLS:     0010 - 54 99 ad 34 86 05 8f 2c-44 4f 57 4e 47 52 44 01   T..4...,DOWNGRD.
    TRACE[BC:5E:00:00]:TLS: master key
    TRACE[BC:5E:00:00]:TLS:     0000 - 87 ef 9d 85 bd 95 80 fb-a3 c7 76 81 2a c2 b3 8e   ..........v.*...
    TRACE[BC:5E:00:00]:TLS:     0010 - bf 92 c6 fb f4 72 0f 22-c4 d4 f5 e6 f8 c6 b3 6f   .....r.".......o
    TRACE[BC:5E:00:00]:TLS:     0020 - c8 c3 e8 53 fd 40 35 80-0e 1a 7f f3 ac ae 27 05   ...S.@5.......'.
    TRACE[BC:5E:00:00]:TLS: key block
    TRACE[BC:5E:00:00]:TLS:     0000 - 5b 77 f6 72 ed 31 27 12-43 89 03 eb 1a fc 22 d8   [w.r.1'.C.....".
    TRACE[BC:5E:00:00]:TLS:     0010 - d2 80 3b 2c c6 77 39 02-8e 80 20 9b 47 b0 ac f7   ..;,.w9... .G...
    TRACE[BC:5E:00:00]:TLS:     0020 - 13 ca b4 9e 20 1a d6 0f-4d 76 02 54 5b 71 7f d6   .... ...Mv.T[q..
    TRACE[BC:5E:00:00]:TLS:     0030 - b6 89 d9 3e 98 04 a2 c9-6a 0f 26 20 cc d8 d8 0b   ...>....j.& ....
    TRACE[BC:5E:00:00]:TLS:     0040 - 27 02 b0 24 66 00 ca f4-                          '..$f...
    TRACE[BC:5E:00:00]:TLS: which = 0021, mac key:
    TRACE[BC:5E:00:00]:TLS: which = 0021, key:
    TRACE[BC:5E:00:00]:TLS:     0000 - 5b 77 f6 72 ed 31 27 12-43 89 03 eb 1a fc 22 d8   [w.r.1'.C.....".
    TRACE[BC:5E:00:00]:TLS:     0010 - d2 80 3b 2c c6 77 39 02-8e 80 20 9b 47 b0 ac f7   ..;,.w9... .G...
    TRACE[BC:5E:00:00]:TLS: iv:
    TRACE[BC:5E:00:00]:TLS:     0000 - 27 02 b0 24                                       '..$
    TRACE[BC:5E:00:00]:TLS: dec 16
    TRACE[BC:5E:00:00]:TLS:     0000 - 14 00 00 0c ab 30 eb e0-22 fe 73 9f 8e df cc ac   .....0..".s.....
    TRACE[BC:5E:00:00]:TLS: which = 0022, mac key:
    TRACE[BC:5E:00:00]:TLS: which = 0022, key:
    TRACE[BC:5E:00:00]:TLS:     0000 - 13 ca b4 9e 20 1a d6 0f-4d 76 02 54 5b 71 7f d6   .... ...Mv.T[q..
    TRACE[BC:5E:00:00]:TLS:     0010 - b6 89 d9 3e 98 04 a2 c9-6a 0f 26 20 cc d8 d8 0b   ...>....j.& ....
    TRACE[BC:5E:00:00]:TLS: iv:
    TRACE[BC:5E:00:00]:TLS:     0000 - 66 00 ca f4                                       f...


As you see, the key block length is 72 bytes here, not 88 as before for TLS 1.2 AES256-GCM-SHA384. And the key block ends with the last IV ("66 00 ca f4"). No extra bytes present in the dump, and the connection still works.

@kaduk - you were right that you have pointed attention to the probability of make a bug, but since we have used existing code that was in one copy and made a function of it and called it from the old place and from the new one, this will save us from the probable error that you have envisaged. Also, if fewer bytes are generated, the connection will not start and this will be immediately noticed. Key generation is a very sensitive issue and should be taken with great care. Extra bytes should not be tolerated because such lax approach leads to reduced code quality and finally to eventual key leaks.

**Comment by maximmasiutin** [comment]
Fixed in https://github.com/openssl/openssl/pull/12032
