### ISSUE TITLE
Choosing the appropriate hashbang line for installed perl scripts

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#1202]
This continues the discussion started in #1199...  that discussion seems off-topic there.

The topic here is, then, what to do with hashbang lines in installed perl scripts (`CA.pl`, `tsget`, ...)

I see two options:

1.   make those line to always be `#! /usr/bin/env perl`, regardless of what the user says when configuring
2.   make those lines *default* to `#! /usr/bin/env perl`, but use whatever was given to configuration through the environment variable `PERL`, *if* it's defined then.

I'd like some opinions on this.

**Comment by dot-asm** [comment]
As mentioned in #1199, my major argument is that we should recognize difference between compile- and execution-time environments. While second option is appealing in sense that it grants certain freedom to package producer, it doesn't actually allow to tell apart the said environments. Concern is that while trying to push the build through compilation, "packeteer" might face the dilemma yet remain unaware of it. Maybe one should introduce separate option for overriding `#!` in installed scripts? Though personally I'd be as content with first option, i.e. unconditional `#!/usr/bin/env perl`.

**Comment by levitte** [comment]
I experimented a bit and came to the same conclusion, option 1 is my favorite as well. Glad we agree, I'll implement as soon as I have a chance (which might not be before Monday)

**Comment by kroeckx** [comment]
In Debian we have a perl policy.  It currently says:
```
All packaged perl programs must start with #!/usr/bin/perl and may append such flags as are required. 
```
It's also what I currently get.  Will this change something for me?

**Comment by dot-asm** [comment]
> Will this change something for me?

Yes, it totally would. I mean if we go for the 1st option, *unconditional* `#!/usr/bin/env perl`. While current setup serves well cases when there always is only one perl and especially at standard location (like in your, @kroeckx, case), it's formally error-prone. As already mentioned, maybe additional option, say HASHBANGPERL environment variable or --hashbang-perl option would be appropriate. It can be complemented with kind of heuristic approach, such as if `$config{hashbangperl}` is not defined, and if `$config{perl}` is /usr/bin/perl, then use it as `#!` interpreter, otherwise default to `#!/usr/bin/env perl`. This way it would keep working for @kroeckx without any additional tweaks.

**Comment by mattcaswell** [comment]
@levitte, and this one too. Are we planning to make a change for 1.1.0?

**Comment by levitte** [comment]
Looking at this again now

**Comment by levitte** [comment]
Have a look at #1282

**Comment by levitte** [comment]
Closing, as the issue is fixed
