### ISSUE TITLE
About BN_R_NO_INVERSE issue

### ISSUE THREAD

**Issue by joymcg** [openssl/openssl#12129]
Hi，
    It seems this function BIGNUM *BN_mod_inverse(BIGNUM *in） missed some logic int following line.
https://github.com/openssl/openssl/blob/ffb6c86663f8d1048b8bac4023c0e41d3ec5891d/crypto/bn/bn_gcd.c#L49
   When int_bn_mod_inverse go into the following logic, https://github.com/openssl/openssl/blob/ffb6c86663f8d1048b8bac4023c0e41d3ec5891d/crypto/bn/bn_gcd.c#L49
 *pnoinv = 0  always execute, if errors happen, this *pnoinv is always 0, even though BN_R_NO_INVERSE error set.
So maybe we should pass pnoinv to 
static BIGNUM *BN_mod_inverse_no_branch(BIGNUM *in, const BIGNUM *a, const BIGNUM *n,BN_CTX *ctx)  
   function and Set pnoinv to 1 at
https://github.com/openssl/openssl/blob/ffb6c86663f8d1048b8bac4023c0e41d3ec5891d/crypto/bn/bn_gcd.c#L507

**Comment by romen** [comment]
The only public function there is `BN_mod_inverse()` (even though it is unfortunate that some static functions in there start with uppercase `BN_`).

https://github.com/openssl/openssl/blob/ffb6c86663f8d1048b8bac4023c0e41d3ec5891d/crypto/bn/bn_gcd.c#L18-L27

`int_bn_mod_inverse()` can end up calling `BN_mod_inverse_no_branch()` :

https://github.com/openssl/openssl/blob/ffb6c86663f8d1048b8bac4023c0e41d3ec5891d/crypto/bn/bn_gcd.c#L44-L50

`BN_mod_inverse_no_branch()` does not care about `*pnoinv`, but does detect the case in which no inverse exists, and correctly raises `BN_R_NO_INVERSE`:

https://github.com/openssl/openssl/blob/ffb6c86663f8d1048b8bac4023c0e41d3ec5891d/crypto/bn/bn_gcd.c#L506-L509


I get that it is a bit confusing because the way implementations are nested appears asymmetric and convoluted, but as far as the logic goes (in the public or internal use) there isn't an error.

Still, it would be interesting to refactor this code to improve readability, and a PR about it would be very welcome!

**Comment by romen** [comment]
See #12142 for a proposed refactor

**Comment by joymcg** [comment]
Hi, 
    Thanks for the PR and refractor the code. That makes the logic clear now.

**Comment by alex** [comment]
Hi all. In addition to making this code easier to read, I believe it also fixed a bug that would lead to an error being returned when setting up RSA blinding if the randomly chosen modulo did not have an inverse: https://github.com/pyca/cryptography/issues/5521

Does my analysis look right to you?

**Comment by kaduk** [comment]
@romen may be best-placed to answer @alex 's question.  I am not sure that I should try to invest the time to understand #12129 myself...

**Comment by davidben** [comment]
I haven't looked at the change carefully itself, but to answer the immediate question: a randomly-chosen blinding factor having no inverse has about the same probability as randomly guessing the RSA private key[*]. If you hit that case, your key has worse problems. :-) Additionally, if the blinding factor has no inverse, you're not going to correctly perform the RSA private key operation. So, even if it were likely, you'd need to add a loop to the blinding factor selection to mitigate it and I don't see a loop in this commit. (Which is fine because, again, this will never happen for RSA keys that aren't totally broken.)

[*] Having no inverse means you have a common factor with the modulus. Compute a gcd, and out pops a factorization. You'll manage to find such a value with roughly 2^-1023 probability for an RSA-2048 key.

**Comment by romen** [comment]
In theory #12169 does not change the error reporting logic, so errors are raised in the same conditions.
What changes is from which function the error is added to the stack though, so maybe that can have an effect on the missing cleanup of the error stack by the framework around libcrypto?

Would that make sense @alex?
