### ISSUE TITLE
It's not possible to unload a provider once its been used

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#12157]
Once you've load a provider and used it, its not possible to then unload it again. At least this is true for the default provider, and I assume others. See this test program:

````
#include <stdio.h>
#include <openssl/provider.h>
#include <openssl/evp.h>

void print_availability(const char *label)
{
    printf("%s\n", label);
    printf("Default provider is %s\n\n",
           OSSL_PROVIDER_available(NULL, "default") ? "loaded" : "not loaded");
}

int main(void)
{
    OSSL_PROVIDER *defltprov = NULL;
    OSSL_PROVIDER *nullprov = OSSL_PROVIDER_load(NULL, "null");
    EVP_MD *sha256;

    if (nullprov == NULL)
        printf("Failed to load null provider\n");

    print_availability("Before start");
    defltprov = OSSL_PROVIDER_load(NULL, "default");

    sha256 = EVP_MD_fetch(NULL, "SHA2-256", NULL);
    if (sha256 == NULL)
        printf("Failed to fetch SHA256\n");
    EVP_MD_free(sha256);

    print_availability("After load");
    if (!OSSL_PROVIDER_unload(defltprov))
        printf("Unload failure\n");

    print_availability("After unload");

    OSSL_PROVIDER_unload(nullprov);

    return 0;
}
````

That produces this output:
````
$ ./defltprov 
Before start
Default provider is not loaded

After load
Default provider is loaded

After unload
Default provider is loaded
````

I expected the final line to say "Default provider in not loaded"

**Comment by levitte** [comment]
Essentially, this is caused by the reference count we have in a provider.  Every constructed method holds such a reference, and hence, the provider reference count increases.
The availability function is very simple, it simply tells you if the provider is initialized (i.e. it's init function has been called, and its teardown function hasn't).  The teardown function is only called when the provider's reference count gets down to 1 (only the provider store has a reference to the provider structure at this point).

Now, one might think that when you free `sha256`, that should be it!  We don't know of any more methods, so the refcount should be low enough that the teardown function gets called and the availability function should return false.  And while simple intuition agrees with this, what's not apparent is that methods for all other algorithms of the same type (in this case, digests) that are available in the same provider get created as well, so if you expect your `EVP_MD_fetch()` to increase the refcount by 1, chances are (and this is definitely true for the default provider) that it has increased by quite a bit more.

So then the question is, should we have two refcounts, one that's exclusively about the times a particular provider has been loaded, which the other is entirely about the method store having any method or not, and check both to find out if a provider is 1) "available", and 2) possible to unload?

(the knowledged reader is probably reminded of the ENGINE structure vs function refcount...  I don't mean to imply that we should do the same for providers, 'cause it comes with its own pains, but there is definitely a lesson to be learned)

**Comment by romen** [comment]
@levitte isn't that a symptom of something that is not properly cleaned up? 

Where are the user-invisible objects that have the accounted references to the provider stored?
If it is in the provider itself or in the default libctx I fail to see why all those references are not cleared once we ask the libctx to unload said engine!

What am I missing?

And if this is a feature and not a bug, how can we make this behavior easy to understand for external developers? 
Should we also think of potential limitations for external applications deriving from this behavior and have prominent disclaimers about them in the documentation that explains this?

**Comment by levitte** [comment]
> @levitte isn't that a symptom of something that is not properly cleaned up?

Not really.  Unless the provider says otherwise, we build a cache of methods of all implementations that we get passed.  Everytime we call the `query_operation` function, we get back an array of `OSSL_ALGORITHM`, each one of them is used to create a method in libcrypto.  The method store is a slot in the library context, pointing at method store structure, which you find in `crypto/evp/evp_fetch.c`.  Destruction of that store happens when the library context that holds it gets destructed, and that's when those methods get ultimately freed.
This is by design, and I believe you can find that written in the design document (have you read it?).

> And if this is a feature and not a bug, how can we make this behavior easy to understand for external developers?

Like I said above...  basically by decoupling the "availability" of the provider from the amount of methods tied to it.

**Comment by romen** [comment]
@levitte It was a good opportunity to read [it](https://www.openssl.org/docs/OpenSSL300Design.html) again! ;)

I am not sure I find the part that describes this:

> Destruction of that store happens when the library context that holds it gets destructed, and that's when those methods get ultimately freed.

On the other hand, I found things that in my interpretation would suggest that calling `OSSL_PROVIDER_unload(defltprov)` should indeed make sure the provider is unloaded:

> The Core has the following characteristics:
> 
> - It enables Provider discovery, loading, initialisation and unloading
> - It enables property-based algorithm queries
> - It implements caching of algorithm queries and implementation details
> - It operates within a library context that contains data such as global properties, search cache and dispatch tables.

> Providers can be loaded at any point in time. Unload at any point in time can be requested. It is up to the application to ensure that a provider is not currently being used or referenced when it is unloaded. If an attempt is made to use an implementation that is no longer available then an error will be returned.

> `OSSL_FUNC_TEARDOWN`, which _[is one of two mandatory callbacks exposed by a provider and]_ is used when the provider is unloaded.

> The algorithm query cache can be flushed to remove:
> - All queries returning a specific algorithm implementation
> - **All algorithm implementations from a specific provider**
> - All algorithm implementations

----

From the excerpts above, as an external user, I would expect _Core_ to act on the request of unloading the specified provider, having the capability of flushing the stores in the `libctx` that hold references to the specified provider, and call the `OSSL_FUNC_TEARDOWN` callback if the user made sure that the provider is not currently being used or referenced by objects in his responsibility and that this was the last reference to the specified provider in any `libctx`.

In Matt's code I think all the conditions are satisfied, yet the teardown does not happen and the provider appears to be still available.

----

- Would flushing the algorithm query cache in the `libctx` from which the user is asking to unload the provider remove the references that are preventing the teardown?
- Is there some reason I am missing that prevents Core from flushing anything related to the specified provider in the specified `libctx`?
   - If for some valid reason we don't want to flush that store upon `OSSL_PROVIDER_unload()`, should it return some special value to signal that the user needs to trigger the flush of the algorithm query cache for the specified provider in the relative `libctx`?
   - What should the user call to achieve that?
- Is something else stored in the `libctx` that should be flushed if the user wants to make sure the provider is indeed unloaded?

**Comment by paulidale** [comment]
We should definitely not have two references counts like engines.  The double counting in engine is simply confusing.  It is also broken in several ways.

I'd like the unload to flush the cache and prevent it being repopulated -- i.e. the provider will cease being used eventually and dlclosed(2) at that point.  That or we get rid of the unload call entirely.  Want to unload a provider?  Destroy the library contexts referencing it.
