### ISSUE TITLE
OpenSSL s_client not working

### ISSUE THREAD

**Issue by saddy-muchu** [openssl/openssl#12204]
Hello,

i was trying to fetch some info from a known server via the s_client command line utility.
But, i end up in the following error:

openssl s_client -connect www.linkedin.com:443 
139645522540352:error:2008F002:BIO routines:BIO_lookup_ex:system lib:../openssl-1.1.1d/crypto/bio/b_addr.c:724:Temporary failure in name resolution
connect:errno=11

I'm using openssl version 1.1.1d

Any info on this?

**Comment by DDvO** [comment]
Well, @saddy-muchu, the error message says it all:
your system was not able to resolve the name, which in your case is www.linkedin.com.
This likely is because your network is down or your DNS server is not reachable.
There is little what OpenSSL can do about it.

When I disable my network access, I get the same response.
Other tools will then give basically the same result, for example:
```
wget https://www.linkedin.com
--2020-06-20 22:30:26--  https://www.linkedin.com/
Resolving www.linkedin.com (www.linkedin.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘www.linkedin.com’
```
