### ISSUE TITLE
Several OCSP_REQ_CTX-related functions impossible to use from C++ in 3.0.0

### ISSUE THREAD

**Issue by jwalch** [openssl/openssl#12234]
Sometime in 3.0.0 development, several functions (eg, OCSP_REQ_CTX_free) were moved outside of the ifdef __cplusplus / extern "C" business.

There is a comment in ocsp.h saying that these "functions are used only internally" that I find a bit perplexing. How can one possibly say that for certain? Those functions were in a public header (ocsp.h), many (if not all) are documented in the man pages (even in current master), and many (if not all) appear in libcrypto.num and are as a consequence exposed symbols from the library perspective.

The upshot of them now being outside of the extern block is that C clients code can continue to use these symbols / functions as they always had while C++ clients will fail at link time.

It's unclear what exactly the intent was here, but surely a different API for C v/s C++ clients was not the desired outcome. I would also note that if the symbols are to ultimately be removed, I would expect some intermediate deprecation step, as they were formally exposed (and still are, for C code).

**Comment by levitte** [comment]
> There is a comment in ocsp.h saying that these "functions are used only internally" that I find a bit perplexing. How can one possibly say that for certain?

One can't, but that was the intent.  Remember that before 1.1.0, *almost everything* was declared publicly, even things that were only intended for internal use.  We still have traces of that time, and this is obviously such a case.

> It's unclear what exactly the intent was here, but surely a different API for C v/s C++ clients was not the desired outcome. I would also note that if the symbols are to ultimately be removed, I would expect some intermediate deprecation step, as they were formally exposed (and still are, for C code).

I agree with this

**Comment by mattcaswell** [comment]
> There is a comment in ocsp.h saying that these "functions are used only internally" that I find a bit perplexing.

Actually I'm not sure about that either. Seems to have been introduced in #10667. I don't recall picking up on this during the review of that PR. Perhaps @DDvO can shed some light on the background here.

**Comment by DDvO** [comment]
> > There is a comment in ocsp.h saying that these "functions are used only internally" that I find a bit perplexing. How can one possibly say that for certain?
> 
> One can't, but that was the intent. Remember that before 1.1.0, _almost everything_ was declared publicly, even things that were only intended for internal use. We still have traces of that time, and this is obviously such a case.

Correct. I should better have written: these functions are *meant to be* used only internally.

> > It's unclear what exactly the intent was here, but surely a different API for C v/s C++ clients was not the desired outcome. I would also note that if the symbols are to ultimately be removed, I would expect some intermediate deprecation step, as they were formally exposed (and still are, for C code).
> 
> I agree with this

Me too. 
Not including them in `extern "C" blocks was by mistake.
Yet in this way we prevent at least C++ users from using them externally :stuck_out_tongue_winking_eye: 


> Actually I'm not sure about that either. Seems to have been introduced in #10667.

Yes.

> I don't recall picking up on this during the review of that PR.

I just went through the comments there and did not find a comment from you on this specific topic,
only one that referred to functions that I had attempted to move to `http.h`
which I reverted due to your comment that this would break the API:
https://github.com/openssl/openssl/pull/10667#discussion_r367332257

> Perhaps @DDvO can shed some light on the background here.

The background was that the pre-existing OCSP-centric API of the (until that time very limited) HTTP functionality was horrible, hard to read, and hard to use. 
So I would have have revised it completely but did not dare to do, in order to keep backward compatibility as far as possible.
Part of my thoughts are still reflected as comments in ocsp.h.

I agree with @jwalch that those 'internal' function should better be deprecated for external use and should be made non-public later.

**Comment by levitte** [comment]
> I agree with @jwalch that those 'internal' function should better be deprecated for external use and should be made non-public later.

Deprecate?  Why?  If this is *new stuff* in master, then just move them.

**Comment by mattcaswell** [comment]
> Deprecate? Why? If this is new stuff in master, then just move them.

It isn't new stuff - these functions exist in released versions.

**Comment by DDvO** [comment]
> Deprecate? Why? If this is _new stuff_ in master, then just move them.

Those are not new functions, but old stuff that should at least be renamed, along with the type `OSCP_REQ_CTX` to `HTTP_CTX`. I shrunk back from doing so, for backward compatibility.
Maybe a few of them should still be exported, under their new names.

**Comment by jwalch** [comment]
Yeah, the only thing that's new to 3.0.0 is the manner in which the functions are declared (ie, outside of extern C blocks) and annotated in the source. At least some (if not all) of those functions go back to at least 1.0.2. Interestingly, the man page documentation for them, while not present in 1.0.2 as far as I can tell, was added in either 1.1.0 or 1.1.1. (That would suggest that whomever added that documentation didn't understand the purported original intent for them to be private.)

If the ultimate solution here is to walk these symbols through the deprecation process, I would request that the relevant man pages include pointers to what clients are supposed to use instead. I have found pages like https://www.openssl.org/docs/manmaster/man3/RSA_generate_key_ex.html to be helpful as I go through the exercise of preparing a legacy codebase for an update to 3.0.0.

**Comment by DDvO** [comment]
> Yeah, the only thing that's new to 3.0.0 is the manner in which the functions are declared (ie, outside of extern C blocks) and annotated in the source. At least some (if not all) of those functions go back to at least 1.0.2. Interestingly, the man page documentation for them, while not present in 1.0.2 as far as I can tell, was added in either 1.1.0 or 1.1.1. (That would suggest that whomever added that documentation didn't understand the purported original intent for them to be private.)

I did not say that the original intent was for them to be private ;-)
And from the fact that an exported OpenSSL function is not documented one cannot deduce that the function is meant to be private - typically the reason is that its author failed to document it.

> If the ultimate solution here is to walk these symbols through the deprecation process, I would request that the relevant man pages include pointers to what clients are supposed to use instead. I have found pages like https://www.openssl.org/docs/manmaster/man3/RSA_generate_key_ex.html to be helpful as I go through the exercise of preparing a legacy codebase for an update to 3.0.0.

Yeah, we should somehow determine with of the functions in `ocsp.h` marked as 'internal' can&should be renamed, and which of them to deprecate. And would be good to document those that are not (yet) documented, namely (with current names):
OCSP_REQ_CTX_new
OCSP_REQ_CTX_http 
OCSP_REQ_CTX_i2d 
OCSP_REQ_CTX_nbio 
OCSP_REQ_CTX_nbio_d2
OCSP_REQ_CTX_get0_mem_bio

**Comment by DDvO** [comment]
This issue, which has been neglected for quite a while, happens to getting fixed by #13742.
