### ISSUE TITLE
what's the difference between     SSL_CTX_set_options(cctx, SSL_OP_NO_TLSv1_3);  and SSL_CTX_set_min_proto_version

### ISSUE THREAD

**Issue by joymcg** [openssl/openssl#12240]
Hi,
    I am confused about    SSL_CTX_set_options(cctx, SSL_OP_NO_TLSv1_3)  and SSL_CTX_set_min_proto_version.  In the document , it said that SSL_OP_NO_TLSv1_3s options are deprecated.  But how to use SSL_CTX_set_min_proto_version and  SSL_CTX_set_max_proto_version  to disable one version in the middle of two version?  Now openssl only support version range?

**Comment by kroeckx** [comment]
Disabling a single version in the middle of 2 others might not
work as you expect. I think that if it's a client, and you
disable a version, and a higher version is enabled, it will
disable all lower versions too, so that no version in the middle
is disabled.

I also fail to see the usecase of disabling a version in the
middle.

**Comment by mattcaswell** [comment]
> I am confused about SSL_CTX_set_options(cctx, SSL_OP_NO_TLSv1_3) and SSL_CTX_set_min_proto_version. In the document , it said that SSL_OP_NO_TLSv1_3s options are deprecated. But how to use SSL_CTX_set_min_proto_version and SSL_CTX_set_max_proto_version to disable one version in the middle of two version? Now openssl only support version range?

Don't try to disable one version in the middle of the range. The old way is deprecated precisely to avoid that scenario which is considered bad practice.

**Comment by joymcg** [comment]
Hi guys,
Thanks a lot for the detail explain.
