### ISSUE TITLE
Crash in X509_NAME_cmp (openssl 1.1.1)

### ISSUE THREAD

**Issue by ArtsviKarayan** [openssl/openssl#12316]
The OpenSSL version is 1.1.1g now (but noticed the issue after migrating from 1.0.1 to 1.1.1).
It is our custom build for ARM architecture.

The crash is in X509_NAME_cmp function from "openssl/crypto/x509/x509_cmp.c".

The issue is not a NULL check. We have brought the null check patch from master branch ([Prevent crash in X509_NAME_cmp() etc. when cert has no issuer](https://github.com/openssl/openssl/pull/11386/commits/c6226f98b4fb3d9b114060a3ff485a069cb5f03c)) to 1.1.1g for testing purposes.

```
int X509_NAME_cmp(const X509_NAME *a, const X509_NAME *b)
```

One of the arguments (b) is garbage (not NULL).

The crash happens when callback for "SSL_VERIFY_PEER" is called.
The trace is the following:
- verification callback -> "X509_STORE_get_by_subject" -> "X509_OBJECT_retrieve_by_subject"

**Comment by DDvO** [comment]
I fear that more information is needed for tackling this issue.
Can't you use, e.g., Eclipse to trace where the garbage comes from?

I may even just be due to an inconsistent build, which can happen, e.g., after switching between branches using `git checkout`.
I advise using `make clean; make ...` before any further investigation.

**Comment by ArtsviKarayan** [comment]
Thank you for the response!
Indeed, I also imagine that the issue is very hard to tackle.
About the clean build: It is fully cleaned 100 %.

For more traces, I will try to get more. 

The garbage comes from the store object seems, is there any idea why can it happen?
Something uninitialized or the memory may be corrupted in librcypto/our side?

We use the OpenSSL libraries from our app and it is quite complicated setup on an ARM device, but please note that we did not have the crash before 1.1.1. We did some migration on our side for 1.0.1 to 1.1.1.
We have tried to debug the memory using memory debuggers  (e.g. dmalloc) but unfortunately, it is not reproducible with them :( . Can it be a timing/synchronization issue?

Could you advise where we can add traces to localize the issue?

**Comment by DDvO** [comment]
I also have been experiencing such issues from time to time.
Good that you are sure it's not simply a build inconsistency.

Usually this is due to a premature `free()`, which leads to memory being overwritten when new memory is allocated and filled.
I suggest setting a breakpoint to some place (before the corruption likely was brought in)
and keeping an eye on the data structure, e.g., certificate, that eventually contains/refers to corrupted data.

**Comment by DDvO** [comment]
@ArtsviKarayan, here is an idea how you might find out with little analysis effort if my suspicion on the reason of the crash is the right one in your case: 
disable the underlying `free()` function (e.g., by commenting out `free(str);` in `crypto/mem.c` or by replacing `free_impl` by a no-nop function)
and re-run to see if the corruption/crash is gone.

**Comment by ArtsviKarayan** [comment]
Thank you very much for your ideas. We will do more experiments and debug to come back with more info.

**Comment by ArtsviKarayan** [comment]
The crash is disappeared after some porting staff in our software. Closing now it. Thank you for your support.
