### ISSUE TITLE
Is there any issues if I enable TLS padding extension by default?

### ISSUE THREAD

**Issue by joymcg** [openssl/openssl#12351]
Hi,
   I find that TLS padding extension(rfc7685) is used to fix some bugs in some implements . And openssl have 
  SSL_CTX_set_options(ctx, SSL_OP_TLSEXT_PADDING) to enable it.
   I want to know:
1.  is there any issue that I enable this extension by default?

2. which TLS implements has such bug that need padding extension? 

Thanks in advance.

**Comment by mattcaswell** [comment]
> is there any issue that I enable this extension by default?

Not particularly. It artificially increases the size of the ClientHello if it would otherwise fall in the problematic range (256 - 511 bytes). Generally speaking you don't want to send more data than you have to for performance reasons, but I think it is unlikely to have much of a discernible effect in most cases. I have no data to say how prevalent the affected implementations are these days. I don't recall seeing a report of a problem recently - and we don't set this option by default, so you might want to try running without it and see if it is actually a problem.

 > which TLS implements has such bug that need padding extension?

I don't recall what specific implementations had the problem. I think it was some middleware boxes (load balancers or similar).

**Comment by joymcg** [comment]
thanks a lot for the reply

**Comment by kaduk** [comment]
FWIW, the originally discovered culprit was F5 (see links from https://mailarchive.ietf.org/arch/msg/tls/EsIs-iLVlRsSshD9ZNhqZVsGXfU/) but they don't have a "monopoly" on it (see, e.g., https://mailarchive.ietf.org/arch/msg/tls/9MBtOpmP-SOPyQT3qNN_TYb5eu0/)
