### ISSUE TITLE
MinProtocol can only be used for TLS or DTLS, not both.

### ISSUE THREAD

**Issue by treibholz** [openssl/openssl#12394]
In openssl 1.1.1, only one value can be set to MinProtocol (https://www.openssl.org/docs/man1.1.1/man3/SSL_CONF_cmd.html)

If MinProtocol is set to "TLSv1.2", it is not possible for an application to use "DTLSv1.2".
To restrict the used protocol versions to the currently support ones >=1.2, you have to use the deprecated "Protocol" command:

```
# MinProtocol = TLSv1.2
Protocol = -SSLv3, -TLSv1, -TLSv1.1, TLSv1.2, TLSv1.3, -DTLSv1, DTLSv1.2
```

It should be possible, to set a minimal version for TLS and DTLS.

This issue (and possible solutions) have already been discussed on the openssl-users mailinglist: https://www.mail-archive.com/openssl-users@openssl.org/msg88405.html

**Comment by vdukhovni** [comment]
Thanks for opening the issue.  Before we get to implementation pull requests, any thoughts about whether my [proposed solution](https://www.mail-archive.com/openssl-users@openssl.org/msg88408.html) of two new "CONF" parameters for DTLS min/max protocol is the way forward?

**Comment by vdukhovni** [comment]
@mattcaswell Any feedback on my proposed way forward? Can you think of anyone else we should encourage to comment?

**Comment by mattcaswell** [comment]
> @mattcaswell Any feedback on my proposed way forward? 

Your proposal seems the best route ahead.

**Comment by vdukhovni** [comment]
> > @mattcaswell Any feedback on my proposed way forward?
> 
> Your proposal seems the best route ahead.

I started an implementation, and discovered that a small change of plan may be in order.  Specifically, while TLS version bounds would still apply only to TLS-based contexts and DTLS bounds only to DTLS-based contexts, it turns out much simpler to use a single configuration option name for both&mdash;`MxxProtocol` in config files and `mxx-protocol` in command-line options&mdash;and just specify the config file setting or command-line option twice, with an appropriate value for each protocol:
```
MinProtocol = TLSv1.2
MinProtocol = DTLSv1.2
```
With a modest documentation change, and a simple filter than applies the bound only to contexts of the right type this is by far the least disruptive implementation strategy, and in retrospect I think also makes for a reasonable interface.

Any objections?

**Comment by vdukhovni** [comment]
On closer inspection, the requisite code was written (by me, of all people) back in 2015, but needs better docs and a couple of minor tweaks to be more forgiving when the bounds and SSL_CTX protocol don't match up.

@treibholz Please reply to the [openssl-users post](https://mta.openssl.org/pipermail/openssl-users/2020-July/012744.html) when you get a chance.

**Comment by vdukhovni** [comment]
Unless the underlying problem is not what we expected, #12472 should address this issue.
