### ISSUE TITLE
why Declare these function inner?but just for test.

### ISSUE THREAD

**Issue by stardrift1** [openssl/openssl#12403]
@mattcaswell 
https://github.com/openssl/openssl/blob/168c595b14ff034ec40642ec1cb5d2c77ce82e0e/crypto/cmp/cmp_local.h#L899

**Comment by mattcaswell** [comment]
Good question.

@DDvO this function only ever seems to be called from the tests. Should it be removed from libcrypto?

**Comment by stardrift1** [comment]
@mattcaswell@DDvO It seems there are many such lnner function,these function DELCARE as outter API in branch :https://github.com/mpeylo/cmpossl

**Comment by DDvO** [comment]
@stardrift1, I'm not sure what you mean by an "inner" functions and what your issue with `ossl_cmp_msg_load()` is.

If you mean functions such as declared in `crypto/cmp/cmp_local.h` (and for most part documented in `doc/internal/man3/`),
these are functions used internally across the CMP code files in `crypto/cmp/*.c` and/or in unit tests and were not considered worth exporting.

The function `ossl_cmp_msg_load()` is indeed just used in unit tests.
If desired, we could export it (i.e., make in public in `cmp.h`)
or remove it from libcrypto because it is essentially just a user-friendly and rather straightforward wrapper around the exported function `d2i_OSSL_CMP_MSG_bio()`.

**Comment by DDvO** [comment]
I meanwhile realized that `ossl_cmp_msg_load()` is implemented redundantly as part of `read_PKIMESSAGE()` in `apps/cmp.c`, 
so it really should be exported and called from there.
I've just done this, as well as a related improvement, in #12421.
