### ISSUE TITLE
Fork-hooks for providers?

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#12406]
Should providers be able to register pre/post fork handlers, analogous to the init/unload?  (See OPENSSL_fork_prepare ec) Or should providers register functions themselves?  One subtlety of the latter is the fork handlers need to be told when a library is unloaded.

This came to mind with the fork/drbg issues, and #12405 more generally.

**Comment by mspncp** [comment]
In the course of discussing CVE-2019-1549 (which was caused by the fact that the advertised drbg fork handler was not used) we had a controversial discussion whether libcrypto should install fork handlers by default. The outcome was that it should happen only if the application requests it. As a consequence, fork-safety was established without using a pthread_atfork handler (commit 1b0fe00e2704b5e20334a16d3c9099d1ba2ef1be).

**Comment by richsalz** [comment]
Thanks for the history reminder.  Since the "provider" architecture is explicitly to allow "anyone" to write crypto code, I think OpenSSL has to provide something in the fork-handler area.

**Comment by richsalz** [comment]
Since the fork-handling routines are now deprecated, closing this.
