### ISSUE TITLE
EVP_MAC & EVP_KDF algorithm NID (and name)

### ISSUE THREAD

**Issue by ozppupbg** [openssl/openssl#12420]
Hello!

While playing with the EVP_MAC and EVP_KDF API, I noticed, that there only exists ``EVP_MAC_number``/``EVP_KDF_number`` and ``EVP_MAC_names_do_all``/``EVP_KDF_names_do_all``, but no way to get the NID or a simple single name for the algorithm.

At least a function to get the NID of the algorithm would be great (it can also be used to get a single name via the ``OBJ_nid2*`` functions).

Thank you!

**Comment by levitte** [comment]
Constant, pre-defined numbers (which is what NIDs are; NID stands for Numeric ID) are not possible with the new structure with providers, as providers can potentially bring new MACs or KDFs that we know nothing about.  The number returned by `EVP_{TYPE}_number` are the closest thing, but are *dynamically allocated* numeric identities and are likely not to be the same from one program run to another.

Because of the more dynamic nature of what's coming, the use of NIDs is considered legacy, and since EVP_MAC and EVP_KDF are new interfaces, we've chosen to have those work as interfaces for provider backends only.  The constant, pre-defined NIDs simply have no place there.

As for names, there actually exists an internal function that will return the "first" name (it's not defined which of several names will come first, but fortunately, most of our MACs and KDFs only have a single name).  That's the closest we can currently have to a "single name".

But, what you just said does strike a chord...  it should be possible to let providers associate an OID with their implementations (if there is one), and adapt at least some of the OBJ functionality to work with the more dynamic numbers.

**Comment by paulidale** [comment]
We have EVP_MAC_name() and EVP_KDF_name().
As mentioned, NID isn't meaningful in the provider world.

Is this sufficient?
