### ISSUE TITLE
Potential dangers of renegotiation 

### ISSUE THREAD

**Issue by Mengliuxx** [openssl/openssl#12504]
By default, OpenSSL supports renegotiation. If the renegotiation callback function client_hello_cb is set to process renegotiation requests, is there any security risk (for example, DDoS)?  Although I don't know what DDoS is.

and
Whether OpenSSL has any dangerous vulnerability in relationship renegotiation .

**Comment by kaduk** [comment]
I'm afraid I don't really understand the questions being asked here.

First off, are you asking about a specific version?  My responses will assume the master branch otherwise.

> By default, OpenSSL supports renegotiation.

Yes, to the extent that renegotiation is defined (i.e., not TLS 1.3).  We do require (by default) the "renegotiation_info" extension from RFC 5746 that closes the main renegotiation vulnerability that was present historically.

> If the renegotiation callback function client_hello_cb is set to process renegotiation requests

I don't think it's fair to call the client_hello_cb a "renegotiation callback function", and I don't know what it would mean for it to be "set to process renegotiation requests" -- it processes all incoming ClientHellos, whether initial or rengotiating.

> Whether OpenSSL has any dangerous vulnerability in relationship renegotiation 

Known dangerous vulnerabilities have been mitigated in the default configuration, but renegotiation is still inherently problematic, especially when it is (ab)used as a way to require client authentication that was not required in the initial handshake.  It was removed from TLS 1.3 for reasons including it being overloaded as both parameter renegotiation and (re)authentication, and there being provably ambiguous state skew between peers as to whether the client was authenticated for any specific higher-level protocol request.

**Comment by Mengliuxx** [comment]
THS
