### ISSUE TITLE
Memory Leak in SSL_do_handshake

### ISSUE THREAD

**Issue by colinmai123** [openssl/openssl#12520]
Hi All, 

Through running valgrind, I have discovered a memory leak in SSL_do_handshake on OpenSSL 1.1.1g. 
Here is the backtrace:

![image](https://user-images.githubusercontent.com/67295883/88320181-0d815680-ccd2-11ea-9ecc-814043921bb0.png)

Has this issue been fixed in more recent openssl versions? Please let me know if any more information is needed from me. 

Thank you

**Comment by mattcaswell** [comment]
Do you have simple reproducer code where this occurs that you can share with us? Not all memory leaks coming from OpenSSL are necessarily due to an OpenSSL problem (for example if you forget to call SSL_free() then you will see this issue). A simple reproducer would help enormously in tracking down where the issue is.

**Comment by colinmai123** [comment]
Our code is massive, so it would be a hassle to attach it all here. If no one else has seen this issue, I will just assume that we forgot to call SSL_free() somewhere in our code. Thank you for all the help!
