### ISSUE TITLE
OSSL_DESERIALIZER_from_bio not working with file bio

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#12541]
OSSL_DESERIALIZER_from_bio fails for file bios (e.g. bio created with BIO_new_file).

The reason is here:
deserializer_lib.c
function deser_process
```
        if (loc == 0) {
            if (BIO_reset(bio) <= 0)
                goto end;
        } else {
```

BIO_reset returns 0 for a file bio. From the documentation:
https://www.openssl.org/docs/man1.0.2/man3/BIO_reset.html
```
BIO_reset() normally returns 1 for success and 0 or -1 for failure. File
BIOs are an exception, they return 0 for success and -1 for failure.
```

The solution, while not very elegant, is to ignore the result of BIO_reset like this is done in other places:
(void)BIO_reset(bio);

**Comment by levitte** [comment]
I've found that BIO_reset() is not very usable in many cases, so it's probably better to switch to pure BIO_tell() / BIO_seek() use. BIO_s_mem can easily be modified to support that (since we use that internally).

A point here is that it should be possible to have more than object in the same file, especially PEM, so OSSL_DESERIALIZER_from_bio() needs to be able to deal with that. 

I have a PR coming up soon that deals with this and more.

**Comment by matbech** [comment]
Thank you. Please also see the new issue: https://github.com/openssl/openssl/issues/12568
