### ISSUE TITLE
Segmentation fault in SSL_export_keying material

### ISSUE THREAD

**Issue by rogull** [openssl/openssl#12588]
Hi,

There is a segmentation fault when SSL_export_keying_material is called before any messages of the handshake were received.

Here is a short program that causes the segmentation fault with openssl 1.1.1:

```
#include <openssl/evp.h>
#include <openssl/ssl.h>

int main(int argc, char ** argv) {
    const size_t len = 128;
    const char label[] = "EXPERIMENTAL";
    unsigned char key1[len];
    int r;
    
    SSL * ssl = SSL_new(ctx);

    // Non blocking BIOs to interrupt the handshake
    BIO * in = BIO_new(BIO_s_mem());
    BIO * out = BIO_new(BIO_s_mem());
    SSL_set_bio(ssl, in, out);

    SSL_set_accept_state(ssl);
    
    r = SSL_do_handshake(ssl);
    // r <= 0 because the handshake is interrupted
    // SSL_get_error returns SSL_ERROR_WANT_READ
    
    // Segfault below.
    r = SSL_export_keying_material(ssl, key1, len, label, sizeof(label), NULL, 0, 0);
    return 0;
}
```

When SSL_set_connect_state is called instead of SSL_set_accept_state it works fine except if SSL_do_handshake is not called, in which case it causes a segfault anyway.

**Comment by kaduk** [comment]
Can you say a bit more about why you think this is not programmer error?  A server ("accept state") SSL that has not received any messages does not have enough information to be able to compute any exported key material (i.e., a ClientHello), so calling the exporter API at this time will never succeed.

**Comment by t8m** [comment]
@kaduk I agree that this is programmer error. On the other hand segfaulting instead of returning a regular error in such case is really bad API contract. It is very much different from other programming errors such as calling something with invalid or NULL pointer or other similar stuff where it can be easily identified and handled on the caller side.

@paulidale Why did you mark it as question? I do not see any question here. Either we accept that this is bug and fix it (my preference) or we should just close wontfix or notabug this.

**Comment by mattcaswell** [comment]
I relabelled it as a bug.
