### ISSUE TITLE
how about  the schedule of adding FIPS_drbg_health_check&FIPS_drbg_set_check_interval?

### ISSUE THREAD

**Issue by stardrift1** [openssl/openssl#12593]
I See there:https://www.openssl.org/docs/OpenSSL300Design.html
will these two API to de added?
![image](https://user-images.githubusercontent.com/42114820/89513914-c3d35880-d807-11ea-82ce-404f11ebbc5e.png)

**Comment by mattcaswell** [comment]
I don't think we're planning on adding those two API calls. #11752 adds an ability to run the self-test KATs for the whole module (i.e. not just the DRBG) on demand via the function `OSSL_PROVIDER_self_test`.

**Comment by stardrift1** [comment]
> I don't think we're planning on adding those two API calls. #11752 adds an ability to run the self-test KATs for the whole module (i.e. not just the DRBG) on demand via the function `OSSL_PROVIDER_self_test`.
SO Can the 3.0 design document be modified?and SELF_TEST_post() can use to test on demand?
i see some Comments on the above of this function:
/* This API is triggered either on loading of the FIPS module or on demand */

**Comment by stardrift1** [comment]
> #11752 adds an ability to run the self-test KATs for the whole module (i.e. not just the DRBG) on demand via the function `OSSL_PROVIDER_self_test`.
SELF_TEST_post() can use to test on demand?
i see some Comments on the above of this function:
/* This API is triggered either on loading of the FIPS module or on demand */

**Comment by paulidale** [comment]
@mattcaswell is correct.  We're not supporting these two calls.  In what way should the design documentation be updated.  I don't remember these two being mentioned.

The global self test on demand is runnable and, due to changes in the FIPS policies, they should be far faster than perviously.  They always run the DRBG KATs.  A pull request that adds selectable granularity to the FIPS on demand self tests would likely be considered for inclusion.

FIPS doesn't mandate rerunning the DRBG KATs regularity, so this won't be supported.

**Comment by stardrift1** [comment]
> In what way should the design documentation be updated. I don't remember these two being mentioned.

you can see the URL i methioned above,it's from the OpenSSL 3.0 Alpha4 Release's design document.

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by paulidale** [comment]
Closing, this isn't relevant anymore.
