### ISSUE TITLE
Certificates with explicit ECC curve encodings are allowed in verification chain

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#12600]
Certificates with explicit ECC curve encodings are allowed in verification chain but they should be rejected according to the RFC 5480, section 2.1.1.

We should reject them at least with the X509_V_FLAG_X509_STRICT.

**Comment by sidhpurwala-huzaifa** [comment]
I think this issue is on the verge of being a security flaw. See:
https://blog.trendmicro.com/trendlabs-security-intelligence/an-in-depth-technical-analysis-of-curveball-cve-2020-0601/

A similar issue in MS Crypto API allows malware to be installed via signature bypass.

**Comment by t8m** [comment]
The crucial difference here is that although OpenSSL also uses hash to compare certificates, the hash computation does not cover just the public key but the whole certificate which includes the ECC curve parameters. This means a forged certificate with explicit ECC curve parameters does not match a legitimate root EC cert.

So no, this is IMO not a security flaw.

**Comment by davidben** [comment]
While it's possible that OpenSSL implements it without issues, explicit EC parameters are nonetheless still error-prone and not a great idea. FWIW, BoringSSL has not allowed explicit EC encodings in public keys[*] (and thus X.509 certificates) since December 2015 and it seems to have been fine. Most other implementations I've seen correctly reject it. I think OpenSSL should follow suit.

[*] We sadly, do still support the explicit EC encoding in private keys because sadly older OpenSSL (prior to 86f300d38540ead85543aee0cb30c32145931744) used the non-compliant encoding by default. It's possible that can be retired now too, since most other implementations reject them there too. I haven't tried. Getting it out of public keys appears to be quite safe though.

**Comment by t8m** [comment]
Duplicate of #12139
