### ISSUE TITLE
Memory leak of BIGNUM related to EVP_PKEY_CTX_set_rsa_keygen_pubexp() changes in 3.0.0

### ISSUE THREAD

**Issue by jwalch** [openssl/openssl#12635]
I started seeing complaints of a BIGNUM leak while running a testcase involving RSA key generation under ASAN against 3.0.0-alpha6.

EVP_PKEY_CTX_set_rsa_keygen_pubexp() no longer appears to take custody of the BIGNUM passed onto it. Presumably this is an artifact of the transition to the provider model. (I imagine doing copies before passing data off to the providers is quite typical and makes good sense from the internal POV.)

A few key points:

1. The documentation still states, "The pubexp pointer is used internally by this function so it should not be modified or freed after the call." As far as I can tell that does not square with the new behavior.
 
2. Changing memory custody semantics for pre-existing APIs is probably leaving a land mine for applications, particularly when those semantics were in fact explicitly defined (see 1). It will be very easy for existing applications to begin leaking memory after updating libraries.
 
3. It seems quite plausible to me that this isn't the only EVP_PKEY_CTX_set_* API with such an impact. I'm not explicitly aware of any others, so perhaps the bug is unique. However, the circumstances seem somewhat generic, and hence my concern.

**Comment by t8m** [comment]
Due to the existing semantics we would basically need to release the BIGNUM once we copy it into the provider. 

The question is - could there be existing applications than would be "surprised" by the immediate release of the BIGNUM and expecting that although they cannot modify the BIGNUM anymore after that call with the existing contract that they expect to be able to use it in a read-only way? I hope we can ignore this corner case.

**Comment by davidben** [comment]
The current behavior is especially goofy. Looks like in the "legacy" case, it behaves as in 1.1.1, taking ownership, while the provider case, it copies. That means a caller needs to either predict which path will be used, or risk either a leak or a UAF.

There aren't any perfect answers here, but I think releasing the object is the way to go. That's what we've done in BoringSSL in other cases where we've had to retain compatibility with a `set0`-like function but have since changed the internal representation. Sadly, in some edge cases, callers may be relying on the object to still be around, despite having relinquished ownership of it. I think this is, strictly speaking, incompatible with the notion of relinquishing ownership, but folks do it. It's fairly rare and you can usually fix the caller, but not a great situation.

Another option is to have the `EVP_PKEY_CTX` own a placeholder `BIGNUM` object, retained solely for callers' benefit. And then either have one of these for each property, or one per type and only retain the `BIGNUM` for the most recent API called. (On grounds that, if you relinquish ownership *and* mutate the parent object, you *really* don't have grounds to assume the object is alive.) But this is very hacky, so we've usually opted to just fix the few affected callers. (Usually a matter of bumping a refcount or reordering some lines.)

This is the nuisance with non-copying `get0` and `set0` API. :-( They avoid the copy, which is nice, but they implicitly constrain the implementation.

**Comment by t8m** [comment]
So the safest way would be to have the copy of all the BIGNUMs in the library context AND deprecate the APIs which require the copy so we could eventually drop them in a future API breaking release. Not sure if we need to do it or that we can just say that even read-only use after set0 is a misuse of the API. Unfortunately we do not have the BoringSSL advantage of having only known callers - there might be simply just anything out there and use-after-free bugs can be quite ugly.

**Comment by mattcaswell** [comment]
>have the copy of all the BIGNUMs in the library context AND deprecate the APIs

Why in the library context? Why not take a copy in the EVP_PKEY_CTX?

**Comment by t8m** [comment]
By the library context I've meant the EVP_PKEY_CTX in the library. I'm sorry for not being clear.
