### ISSUE TITLE
Custom EC Point Formats option

### ISSUE THREAD

**Issue by zedd3v** [openssl/openssl#12644]
Would it be possible to add an option to change the supply custom ec point format list?
Current defaults are https://github.com/openssl/openssl/blob/e4162f86d7fd92058e5558bd81ce9dbc615fec3f/ssl/t1_lib.c#L197,
but I would only like to use TLSEXT_ECPOINTFORMAT_uncompressed

**Comment by mattcaswell** [comment]
It wouldn't be too hard to do. As far as I can tell all the underlying code to achieve this exists - it just that (for some reason) its never been exposed via an API call. Whether the underlying code actually *works* is another question since its almost certainly not being exercised in any test given the lack of API.

So, the  implementation work consists of creating a function to manipulate `s->ext.ecpointformats` and `s->ext.ecpointformats_len`, as well as the equivalent SSL_CTX fields. Probably also a test would need to be written in `test/sslapitest.c`.

Unfortunately, this feature request is unlikely to receive much attention from the main committer team since I consider it quite niche and all current focus is on the 3.0 release. However if someone wanted to contribute a PR for this then it would be considered. I've added the "help wanted" label accordingly.

Note that this would not be eligible for backport to 1.1.1 since it is a new feature and the 3.0 feature freeze is hopefully later this month, so its  unlikely to appear in any release until 3.1/4.0 (whatever the next release after 3.0 is going to be).

**Comment by davidben** [comment]
Point format negotiation has been more-or-less removed at this point, so changing the default in OpenSSL may also make sense.
https://tools.ietf.org/html/rfc8422#section-5.1.2

**Comment by kaduk** [comment]
And in terms of US government consumers (e.g., those that care about FIPS 140 validation), the use of (only) uncompressed point format is going to be required by the CNSA profile for (D)TLS 1.2: https://tools.ietf.org/html/draft-cooley-cnsa-dtls-tls-profile ("as required by [RFC8422] and [RFC8446]")
I'd be +1 to changing the default

**Comment by dcooper16** [comment]
> And in terms of US government consumers (e.g., those that care about FIPS 140 validation), the use of (only) uncompressed point format is going to be required by the CNSA profile for (D)TLS 1.2: https://tools.ietf.org/html/draft-cooley-cnsa-dtls-tls-profile

Changing the default to conform to RFC 8446 seems like a good idea. However, for most U.S. government consumers (i.e., those not operating National Security Systems), CNSA does not apply. A more relevant reference for TLS would be NIST [Special Publication 800-52 Rev. 2](https://doi.org/10.6028/NIST.SP.800-52r2), _Guidelines for the Selection, Configuration, and Use of Transport Layer Security (TLS) Implementations_.

**Comment by zedd3v** [comment]
> > And in terms of US government consumers (e.g., those that care about FIPS 140 validation), the use of (only) uncompressed point format is going to be required by the CNSA profile for (D)TLS 1.2: https://tools.ietf.org/html/draft-cooley-cnsa-dtls-tls-profile
> 
> Changing the default to conform to RFC 8422 seems like a good idea. However, for most U.S. government consumers (i.e., those not operating National Security Systems), CNSA does not apply. A more relevant reference for TLS would be NIST [Special Publication 800-52 Rev. 2](https://doi.org/10.6028/NIST.SP.800-52r2), _Guidelines for the Selection, Configuration, and Use of Transport Layer Security (TLS) Implementations_.

"The use of compression may enable attackers to perform attacks using compression-based side
channels (e.g., [60], [11]). To defend against these attacks, the null compression method shall be
enabled, and all other compression methods shall be disabled. "

This suggests that the default should indeed be changed but I would also like to see an option for manually choosing them.

**Comment by dcooper16** [comment]
> This suggests that the default should indeed be changed but I would also like to see an option for manually choosing them.

That text is referring to compression of the TLS session data (see compression_methods in https://tools.ietf.org/html/rfc5246#section-7.4.1.2).

This discussion is about the EC Point Formats extension, which is discussed in Sections 3.4.2.4 and 4.4.2.4 in [SP 800-52 Rev. 2](https://doi.org/10.6028/NIST.SP.800-52r2).
