### ISSUE TITLE
DSA signature Generation

### ISSUE THREAD

**Issue by varunsood189** [openssl/openssl#12710]
Hi, I am varun.
I am working for DSA signature generation,

In the function 
```
int DSA_sign(int type, const unsigned char *dgst, int dlen,
             unsigned char *sig, unsigned int *siglen, DSA *dsa)

```
I am passing input as hash message and getting signature as output.

As per my understanding DSA has 2 signature when i referred online,
[](https://www.includehelp.com/cryptography/digital-signature-algorithm-dsa.aspx)
DSA generates 2 signatures r and s,

I tried to extract the r and s signatures from the sig generated above using below code:

```

	string p_string = "F30C68CCBCDA9A3C271A2A2F8427D683C6E79E5B121DEDEC0F1C3AE5DA7D42A6EE327D013383BAF6F2CECE5E6DC1CD63243BA40D457BACABD80E6CB21A5490590A4B8BC79ECF2DBEA75AAFF275507CE1D75BEE802E86E298C2F8B00787A53A68A625C357E08DADCFCD456F194A87769D3D9118B0F1A50D2D7F84291F055494EB";
	string q_string = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009E60337C7B003F2F4C3B4D94B1CC52649ACADA4B";
	string g_string = "9A2C52479BE6FF23A4E8BEC64C18F2A00E1C868D1C58BE6F722D5947698C1121CD8971416F8EE191E8C3F25CCFEA38D83236B873B31B5887CECC03A2AB894BB34266686770A7FF53321A4F599865EEEA8E7E114397A50C1DB5CABB8606E58DE445FBE26700C682F316B312E76E5EC2D79CACCDC1656990B29A967F8CC92FD9A8";
	string public_key_string = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011284B0AAF67437B9D2FD5597ED7DD98808F6560";
	string r_string = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000033CCCC7E5C4DE525FD5F269932708171CFB05DD7";
	string s_string = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000068DDBA97CE00DE5BD55F86A9866A13E5C1B805AA";
	string h_string = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001A888E9E6B18849DF8F49E65FC2603782989238A";
	string private_key_string = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011284B0AAF67437B9D2FD5597ED7DD98808F6560";
	
	static BN_CTX *ctx = BN_CTX_new();
	BN_hex2bn(&p, p_string.c_str());
	BN_hex2bn(&q, q_string.c_str());
	BN_hex2bn(&g, g_string.c_str());
	BN_hex2bn(&public_key, public_key_string.c_str());
	BN_hex2bn(&private_key, private_key_string.c_str());
	BN_hex2bn(&r, r_string.c_str());
	BN_hex2bn(&s, s_string.c_str());
	BN_hex2bn(&h, h_string.c_str());	
	
	//signature generation

	DSA *dsa = DSA_new();
	DSA_set0_pqg(dsa, p, q, g);
	DSA_set0_key(dsa, public_key, private_key);
	
	unsigned int siglen;
	unsigned char *signature = (unsigned char *)malloc(DSA_size(dsa));	

	if (DSA_sign(NULL, (const unsigned char*)h_string.c_str(), h_string.size(), signature, &siglen, dsa))
		cout << "signature is generated."<<endl;
	else
		cout << "signature is not generated." << endl;
	cout << "signature length is  " << siglen << endl;	
	cout << "signature is ";
	for (int i = 0; i < siglen; i++)
	{
		cout <<setw(2) << setfill('0') <<hex<< (int)signature[i];
	}
	cout << endl;
	DSA_SIG *sig = d2i_DSA_SIG(NULL, (const unsigned char**)&signature, siglen);
	/*BIGNUM* r_gen=NULL, *s_gen = NULL;
	r_gen = BN_new(); s_gen = BN_new();*/
	const BIGNUM *r_gen, *s_gen;
	DSA_SIG_get0(sig,&r_gen, &s_gen);
	
	cout << "compare the r " << BN_cmp(r, r_gen) <<endl;
	cout << "compare the s " << BN_cmp(s, s_gen) << endl;
	cout << endl << " r= ";
	BN_print_fp(stdout, r);
	cout << endl << " s= ";
	BN_print_fp(stdout, s);
	cout << endl << " r_gen= ";
	BN_print_fp(stdout, r_gen);
	cout << endl << " s_gen = ";
	BN_print_fp(stdout, s_gen);
	cout << endl;

```

output:

signature is generated.
signature length is  47
signature is 302d02150081f37999df65af6c728ad0be312465d4449d6b580214031efd03b27367057db6cb545f4026793a9a0600
compare the r ffffffff
compare the s 1

 r= 33CCCC7E5C4DE525FD5F269932708171CFB05DD7
 s= 68DDBA97CE00DE5BD55F86A9866A13E5C1B805AA
 r_gen= 81F37999DF65AF6C728AD0BE312465D4449D6B58
 s_gen = 31EFD03B27367057DB6CB545F4026793A9A0600

Signatures are not matching.

Is there some mistake in above code.
Thanks,
Varun

**Comment by romen** [comment]
There are a few things to notice:
- the `DSA_*` API has been discouraged for a long time now, if you are writing code beyond mere experimentation and learning, avoid using this API, in favor of `EVP_PKEY_*`
-  signing generates a single signature (which is composed of a pair of integers in the case of DSA) and not to two signatures
- DSA signatures generated in this way are non-deterministic: signing the same exact message with the same exact key SHOULD deliver a different signature `(r, s) ` every time (because one of the first steps of traditional DSA signing is to generate a new random nonce)
- when calling `DSA_sign` you are passing a hexstring representation of the digest, not the digest in binary form

**Comment by varunsood189** [comment]
Ok romen. Thanks for reply.
I understand:
- I need to look into usage via EVP_PKEY_* .
- Signing generates a single signature and not two signatures.
- Every time I use DSA signature. It is going to generate a different signature. 
- DSA_sign is expecting input in format of binary.

Follow up question:
- Is there an reference to the usage via EVP_PKEY_*.
- Is there a way to get the values of `(r , s)` from the single signature?
- I see that the traditional algorithm is not used in the DSA signature implementation.
          `* We will blind this to protect against side channel attacks`  in the method:
`static DSA_SIG *dsa_do_sign(const unsigned char *dgst, int dlen, DSA *dsa)`
Blinding is used during implementation. Where can I refer the blinding concept ?

Thanks & Regards,
Varun

**Comment by romen** [comment]
- Reference to the recommended API for signatures: https://www.openssl.org/docs/man1.1.1/man3/EVP_DigestSign.html
- notice in particular that his API takes care of the message digest part, so the input is the data to be signed, not its digest. 
- if you really need to go parse the internals of a signature, one way is using the API you found, in the EVP API the signature will generally be a binary blob but then you can parse it with the DSA_SIG functions. One really needs a very good reason (like an ill-defined protocol) to access the individual r and s values, as a standard DSA signature is their concatenation according to rules mandated by the DSA spec and the verify functions should expect that as input as well, so there shouldn't be use cases to extract them individually (other than for human inspection).
- about blinding and other side-channel countermeasures I can't point to a single source, Wikipedia is often a good free starting point with references to books and articles to deepen your understanding of the matter from a theory point of view; an alternative is to dig inside the source code as often the countermeasures are annotated with comments that explain what is going on and might have references to ARTICLES. To go even deeper you might want to check the git history of the code to check when some countermeasure was added in the code and retrieve the relevant PR: in the PR usually you will find a discussion about the countermeasure with more references.

As a bonus answer, as a general trend traditional (even with all the side-channel countermeasures, but compatible with the first specification and non-deterministic behavior) DSA usage in the industry is on the decline (if not actively discouraged) because of the ever increasing key and signature size, and various pitfalls and caveats in implementing and using it securely.

Its cousin ECDSA is way more popular, as it maintains many of the DSA strengths and concepts, with extra benefits such as reduced sizes and better performance for the same level of security.
EdDSA is yet another variation of very similar concepts, and it features similar characteristics to ECDSA with extra perks that some users or use cases might prefer.

DSA is definitely worth as a study topic, and it's a stepping stone to be able to understand ECDSA and related stuff without having to master EC mathematics, but if you are building something new for production I would invite you to check what is the current state of the art and find a very compelling reason to use DSA instead of ECDSA/EdDSA or RSA.

**Comment by varunsood189** [comment]
Thanks for explaining. 
The above comment has increased my understanding of the concept related to the DSA.
I will look into the blinding(countermeasure) and link mentioned for EVP. Thanks again.
I am closing this issue since the question has been been answered.
