### ISSUE TITLE
Generating SSL session PEM certificate 

### ISSUE THREAD

**Issue by saddy-muchu** [openssl/openssl#12776]
I have the below RSA based SSL session certificate.

-----BEGIN SSL SESSION PARAMETERS-----
MIIEBgIBAQICAwMEAsAwBCCK2XwVpjj8tXh02Vrg86ZINo9UJOVKoc2DiqKourom
eAQwN7W3ndfldvYJDdiYF56+draGy/Vr6V05TCweG1p/7QZv5TTA+M1Mh9NL6Wt8
1gF8oQYCBFzOzsOiBAICHCCjggORMIIDjTCCAnWgAwIBAgIITHNIniLz7WwwDQYJ
KoZIhvcNAQELBQAwLzEtMCsGA1UEAwwkU2VjdXJlIEJvb3QgVG9vbGluZyBHZW5l
cmF0ZWQgSXNzdWVyMB4XDTE2MTIxOTE1MDAzNFoXDTI2MTIxNzE1MDAzNFowNDEy
MDAGA1UEAwwpU2VjdXJlIEJvb3QgVG9vbGluZyBHZW5lcmF0ZWQgQ2VydGlmaWNh
dGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC/qn2XSb0mnJTQ0Uoh
aNb7Kq8Zb0SPk64fZElr7uQdv5u9CQftDEP2X0mWmAk7x1m8FNms1uNqap7w0ObN
FfG92rKMegzdIi3nAXeSGhQcZreZmwChVAfZ/lbrtwcthnI+F2390yod543/dLCY
BHf2ZP9hep77JEawiHfAJxvP+vZ5EXrBJtkFIdjZn5Cn083YyHHsdsOa1ie0yY5G
HWZzIEEb/s2gJmqDdkqndoO+UEWU0y6GyJu3NP+i88MwBnPOpvAHw9aKD4EvHjg+
D9BlBlY3a0e/ypuGe3EZYABg01LOMA03+VNwJ2tVQnmXLTNPQFQBvYEmvkAG8hYV
ZcKJAgMBAAGjgacwgaQwCQYDVR0TBAIwADALBgNVHQ8EBAMCB4AwHQYDVR0OBBYE
FPfA/KLK4gkbRgT0TQ8rtnYrSwwDMB8GA1UdIwQYMBaAFCRpJYob3hpCoTwNC3zw
s/BOBYB7MC4GA1UdEQQnMCWBI2V4YW1wbGVAZXhhbXBsZTtVUkk6aHR0cDovL2V4
YW1wbGUvMBoGA1UdEgQTMBGBD2V4YW1wbGVAZXhhbXBsZTANBgkqhkiG9w0BAQsF
AAOCAQEAWGrfZwHr7Lj6KpXQMhpwn7+yECkZA7R5ZT+vb1xdldWWy+1IY3GfiMd0
0Rmt29ydTkSutxI9XhSZ0TpwsoJKuXkSBKPlGP8tRcWtWr0PvwAl5vnsLM+3uFrQ
UQ3MEczDKATHe9s4fUSYhzaM6FXtNAtE6VQ7iBAGwuhJhNfgbp9t/4G9xe7r82q9
RoAxmUrRejq6uzvsrYWZEOqaE+KWO1Q51i6dwCbHK+5KTt392ScqFH4SIS8Iymoq
5zjSDSC8e+qcOGqmpMXIlfFjG8em1+ttFu9OPHEBO1v+YFdVfrPSsOJckRNPRB5+
OixyllK5+XSSjVjXZVoy1zWIEn21tqQCBAA=
-----END SSL SESSION PARAMETERS-----

I want to generate the same for ECC.
What is the significance of this certificate actually?
Are there any OpenSSL commands to generate such a certificate?

**Comment by mattcaswell** [comment]
This is *not* a certificate. It is session data. It contains the following information:

````
$ openssl sess_id -in sess.pem -noout -text
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 8AD97C15A638FCB57874D95AE0F3A648368F5424E54AA1CD838AA2A8BABA2678
    Session-ID-ctx: 
    Master-Key: 37B5B79DD7E576F6090DD898179EBE76B686CBF56BE95D394C2C1E1B5A7FED066FE534C0F8CD4C87D34BE96B7CD6017C
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1557057219
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
````

So  this is a TLSv1.2 session file.

When a TLSv1.2 client connects to a TLSv1.2 server a TLS connection is established and a session is associated with it. The session contains information such as the master key. There is also a unique session id associated with the session data (unless session tickets are being used, but that's more complicated). A client can subsequent "resume" a previous session in a new TLS connection. It passes the session id in the CllientHello. The server looks up the session  in its session cache and, assuming its found it, the resumption attempt succeeds. The previous session data is reused. The means an abbreviated TLS handshake can occur which is faster, and doesn't have to go through all the steps of (for example) checking the server certificate.

The actual file format is OpenSSL specific. Such session files can be generated by the OpenSSL s_client command. For example, first start a server:

````
$ openssl s_server -cert mycert.pem -key mykey.pem
````

And then start a client to connect to that server and write out the session data:

````
$ openssl s_client -sess_out sess.pem -no_tls1_3
````

Gracefully close the s_client session by typing "Q" and then enter. Assuming you keep the server running for the whole time (so that its session cache remains intact), the client can then subsequently reconnect using the session data:

````
$ openssl s_client -sess_in sess.pem -no_tls1_3
````

If it successfully resumed the new connection will tell you in the s_client output. There should be a line which looks like this:

````
Reused, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
````
The "Reused" says the session was successfully resumed (otherwise it says "New").

Sessions in TLSv1.2 are always associated with the original ciphersuite that was negotiated. In your case it is "ECDHE-RSA-AES256-GCM-SHA384". So the certificate used in the original session was RSA. If you want that to be an EC certificate (ECDSA) then you need to configure the server to support an EC cert and ensure an ECDSA based ciphersuite is negotiated.

**Comment by saddy-muchu** [comment]
Really nice explanation.
Thanks a lot for your time.
I was successfully able to generate a session file based on ECDSA
