### ISSUE TITLE
Inconsistency in set_flags API's

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#12804]
There are a couple of dozen "set_flags" API's and they're not consistent -- does setting flags "or" in the new bits, or just "set" the bits that are set?

Trying to fix a minor one, https://github.com/openssl/openssl/pull/12715, led to an interesting discussion. OpenSSL is not consistent, as @t-j-h points out in his comprehensive survey at https://github.com/openssl/openssl/pull/12715#issuecomment-688258245

One possible migration strategy is use "addin_flags" as a migration, and deprecate the existing "add_flags" API's. Or some other name, consistency is more important than the actual name :)

**Comment by levitte** [comment]
It seems like the set-is-or model  is predominant among older APIs, while the set-is-set model is predominant among newer, roughly speaking. The set-is-or model can be seen as more caller friendly, because it makes it easier to modify certain flags while leaving other alone, when the set-is-set model requires the caller to do the bit math.
I have a slight preference for the set-is-or model.

**Comment by nhorman** [comment]
based on the comments in the PR, it seems like theres nothing more to do here

Marking as inactive, to be closed at the end of 3.4 dev, barring further input

**Comment by richsalz** [comment]
It is what it is, my issue, no action, so I'll just close it.
