### ISSUE TITLE
Perl test harness does not keep stdout/stderr output order

### ISSUE THREAD

**Issue by ekasper** [openssl/openssl#1290]
Our tests are pretty inconsistent about writing to stdout vs stderr. With VERBOSE=yes, our (Perl's?) test harness does not apparently merge stdout and stderr in-order. For example, if a standalone test does

fprintf(stderr, "foo");
fprintf(stdout, "bar");
fprintf(stderr, "baz");

then under the harness, we appear to sometimes get

foo
baz
bar

**Comment by levitte** [comment]
It's Test::Harness, an unfortunately, it depends on the version.  Later versions are just wrappers around TAP::Harness, which does have an option **merge** to do exactly what you ask for, but that option isn't available through the Test::Harness wrapper.

Thinking of it, it's possible we *could* switch to use TAP::Harness directly and thereby avoid this kind off issue...  It does exist since perl 5.10.1, which is only one edit away from our requirements, 5.10.0.  I wonder how many would be affected by a requirement upgrade...  and also, what was supported in earlier TAP::Harness versions.

**Comment by levitte** [comment]
I think this is a post 1.1.0 issue.  Do you agree?

**Comment by richsalz** [comment]
Ping @levitte close?

**Comment by levitte** [comment]
Actually, it turned out that this wasn't a Test::Harness issue, but a buffering issue.  stderr is unbuffered while stdout is buffered, which means we might get this kind of effect if we don't flush stdout.

This has been compensated for in the C test framework, so this can be closed.
