### ISSUE TITLE
What is -rev option in s_client?

### ISSUE THREAD

**Issue by saddy-muchu** [openssl/openssl#12912]
The man page says:
-rev
    Simple test server which just reverses the text received from the client and sends it back to the server.

I'm little unclear as to why do we need to reverse the text?
What is the main use-case of using -rev?

**Comment by mattcaswell** [comment]
The title says s_client, but your text talks about s_server. I assume you're talking about s_server since s_client doesn't have such an option.

s_server is a test tool. When testing a client, it could be a useful thing to have a server which always echo's back what it sends - just to test that sending and receiving data is working as expected. I'm not sure that we would bother adding such a feature these days, but I think that option has been around for a long time. Presumably some developer in the dim and distant past decided it was useful enough to add it. We typically don't remove such options unless we really need to in order to avoid breaking people that are using them.

**Comment by saddy-muchu** [comment]
Didn't really understand the statement "a server which always echo's back what it sends".
So, it just echoes back the requests made by the client to the client?

**Comment by saddy-muchu** [comment]
So, even the -www option echoes back the message to the client?
How does -rev differ from -www?

**Comment by mattcaswell** [comment]
> "a server which always echo's back what it sends".

I of course meant, "a server which always echo's back what it receives".

> So, it just echoes back the requests made by the client to the client?

Yes, although of course it also reverses that text.

> So, even the -www option echoes back the message to the client.
How does -rev differ from -www?

-www expects an HTTP request, and responds with information about the connection and server. -rev, just echoes back exactly what the client sends to it (reversed). It doesn't need to be well formed HTTP.

**Comment by saddy-muchu** [comment]
Thanks a lot for the clarification :)
