### ISSUE TITLE
Pattern for OSSL_EXCHANGE_PARAM_KDF_UKM

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#12985]
There is a TODO relating to the usage of OSSL_EXCHANGE_PARAM_KDF_UKM in core_names.h. Its unclear to me from the TODO description whether an API change should be considered. Raising it as an issue here to get an answer. Putting against beta 1 milestone for now.

Reference is:

https://github.com/openssl/openssl/blob/a48309cb5c58be8fa310608124925d4729664cf8/include/openssl/core_names.h#L408-L419

**Comment by t8m** [comment]
So there are a few options on how to solve this (and the other parameters which are similar (they are strings on set and ptr on get).

1. to make them strings on get we would have to cache the values in the EVP_PKEY_CTX in the core
2. to make them ptr on set would not be hard but the ptr types are frowned upon because they are harder to handle right and users will be inevitably confused when using them directly (not through the helper functions)
3. leave it as is and just remove the TODO

Some further considerations - 1. is ugly as we make the existing EVP_PKEY_CTX structure more bloated with the cached data. 2. is ugly because absolute majority of set parameters are of the string type. And 3. might not be that big deal because getting (not setting) those parameters from apps would be actually fairly uncommon and we have the helper functions. So only provider writers are affected if they want to support the getting at all - they do not necessarily have to.

So my opinion is to go with 3. Do we need an explicit OTC decision?

**Comment by t8m** [comment]
@openssl/otc any opinions?

**Comment by levitte** [comment]
Re the "difficult" with PTR, could it work by contrasting UTF8_STRING vs UTF8_PTR just like `char *` vs `char**`?  After all, the latter isn't a mysterious concept, and things like `char **` is fairly common as an output argument to functions, and UTF8_PTR can be understood in exactly the same manner.

**Comment by t8m** [comment]
Sure, the _hard ptr handling_ is definitely just a matter of opinion and probably not that relevant. But the 2. has its own issue with the inconsistency with the rest of the settable parameters. So in the end status quo with removing the TODO is my preferred choice as the option 1. is IMO truly ugly unless it was done in some general way like having a lhash of cached parameters or something.

**Comment by t8m** [comment]
OTC does not have objections to the approach in the PR.
