### ISSUE TITLE
Meaning of HMAC flags

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#12992]
There is a TODO in the HMAC code which talks about formalising the meaning of the flags parameter. Since this forms part of the public API do we need to do something before beta 1?

Reference

https://github.com/openssl/openssl/blob/a48309cb5c58be8fa310608124925d4729664cf8/providers/implementations/macs/hmac_prov.c#L265-L267

**Comment by mattcaswell** [comment]
@levitte - checking the logs it seems you added this TODO. What  sort of thing did you have in mind?

**Comment by paulidale** [comment]
I'd like to see _flags_ arguments broken up into individual params.

**Comment by richsalz** [comment]
Breaking flags into individual params seems like a bad idea.  If you're not keeping the existing public API, this adds 2*(num of flags) to a new API.  And breaking out some flags doesn't make sense (look at ```AES_CBC_HMAC_SHA_FLAGS``` for example).  And then why only HMAC, it should be all ```XXX_set_flags``` routines.

I think this is a great deal of work for little to no real benefit.  Are you *sure* this has to happen for 3.0, @paulidale, @levitte, @mattcaswell ?

**Comment by t-j-h** [comment]
We communicate items using PARAMS - we should not be pushing around "binary" flags when we have gone to the effort of providing a simple string based interface for interacting with all the other sorts of things.

**Comment by richsalz** [comment]
You can communicate flags as an unsigned int.  I wasn't saying don't use PARAMS.

**Comment by levitte** [comment]
Personally, I think that a passed number or a set of passed strings doesn't really matter from a *technical* point of view.  It all comes down to what the provider understands either way, and the application has to adapt according to the providers it uses.

The problem is mainly human.  What's the easiest for a human to remember, the sum of individual bits in decimal, or a set of comprehensive names?  Furthermore, a set of flags names is much easier to document with the gettable and settable query functions than something that just says "gimme a number".

**Comment by richsalz** [comment]
Humans aren't going to remember bits expressed as decimal, they are going to look at source code.  Developers might need to know to use "/x" or equiv to print something in hex. :)

Developers, however, would now need more complicated code by creating a parameter for each flag.  That can be a nuisance and/or error-prone (allocated worst-case, forgot the END marker).

And none of the three points I raised in https://github.com/openssl/openssl/issues/12992#issuecomment-709173209 have been discussed here.

**Comment by slontis** [comment]
For MAC there is only one flag field that needs fixing which is used inside HMAC (other MAC's are already using individual keys for different flags already). This only has a few setter values (noinit and oneshot) so it is not too bad..
KDF is already not using flags also.

For Ciphers and digests I need to figure out what actual flags are needed to be passed back..
The flags passed back here are just constant flags that should be cached as flags in EVP_MD (since that is what the API requires). Note: that EVP_MD does not cache currently.

Of all the various cipher flags it looks like only a few are required currently (as far as i can see)
i.e..
  EVP_CIPH_FLAG_AEAD_CIPHER
  EVP_CIPH_FLAG_TLS1_1_MULTIBLOCK

For digests
  EVP_MD_FLAG_DIGALGID_ABSENT
  EVP_MD_FLAG_XOF

**Comment by levitte** [comment]
> Humans aren't going to remember bits expressed as decimal, they are going to look at source code.

Hmmm, it was actually unclear to me if these flags ever reached as far as being settable with ctrl functions, and thereby being accessible with `openssl` sub-command options like `-pkeyopt`.  If they are, I find it incredibly dismissive to basically tell users "read the source".

**Comment by richsalz** [comment]
I agree that if the commandline requires users to enter raw (hex) numbers, that's wrong.  I am not sure that it does.

**Comment by slontis** [comment]
So for digests where we pass hardwired_flags via macros to a default function

````
IMPLEMENT_digest_functions(name, ctx, blk_sz, digest_sz, hardwired_flags, init, update, final)
````
This then uses a default function
````
int digest_default_get_params(OSSL_PARAM params[], size_t blksz, size_t paramsz,
                                                    unsigned long flags)
{
    p = OSSL_PARAM_locate(params, OSSL_DIGEST_PARAM_FLAGS);
    if (p != NULL && !OSSL_PARAM_set_ulong(p, flags)) {
        ERR_raise(ERR_LIB_PROV, PROV_R_FAILED_TO_SET_PARAMETER);
        return 0;
    }
    return 1;
}
````
This would become either (1)
````
int digest_default_get_params(OSSL_PARAM params[], size_t blksz, size_t paramsz,
                                                    unsigned long flags)
{
    p = OSSL_PARAM_locate(params, OSSL_DIGEST_PARAM_XOF);
    if (p != NULL && !OSSL_PARAM_set_int(p, flags & EVP_CIPH_FLAG_XOF)) {
        ERR_raise(ERR_LIB_PROV, PROV_R_FAILED_TO_SET_PARAMETER);
        return 0;
    }
    ....
    return 1;
}
````
OR (2)
````
int digest_default_get_params(OSSL_PARAM params[], size_t blksz, size_t paramsz,
                                                    int xof, int diaglid_absent, ...)
{
    p = OSSL_PARAM_locate(params, OSSL_DIGEST_PARAM_XOF);
    if (p != NULL && !OSSL_PARAM_set_int(p, xof)) {
        ERR_raise(ERR_LIB_PROV, PROV_R_FAILED_TO_SET_PARAMETER);
        return 0;
    }
    ....
    return 1;
}
````
With (2) every time a new param is needed the function and macros() needs to change -  so this seems not very nice.

**Comment by kaduk** [comment]
It seems like in the general case having the different knobs be discoverable as gettable/settable params is preferred to having a single "flags" param but leaving knowledge of which parameters are/aren't supported ambiguous.
