### ISSUE TITLE
SSKDF controls

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#12993]
There is a TODO in the SSKDF code questioning the need for all the various settings. Since this is part of the public API, do we need to do something for beta 1?

Reference
https://github.com/openssl/openssl/blob/a48309cb5c58be8fa310608124925d4729664cf8/providers/implementations/kdfs/sskdf.c#L374-L378

**Comment by slontis** [comment]
My advice would be to remove the TODO.

This code follows the standard. See https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Cr2.pdf

i.e it supports:
H(x) = hash(x) 
H(x) = HMAC-hash(salt, x)
H(x) = KMAC#(salt, x, H_outputBits, “KDF”)

AND the standard spefically talks about the salt length..

*  This  Recommendation  places  no  restriction  on  the  length  of  a  chosen  salt  other  than  the  requirement that its byte length be greater than zero but no greater than the length of a single input block to  the  hash  function, hash, used  to  implement  HMAC-hash.  That  freedom  of  choice  is  somewhat  illusory,  however,  since  the  HMAC  algorithm  will  convert  an  input  salt  value  (as  needed)  into  a  string  of  the  indicated  hash-dependent  length.A  shorter salt  (used  by  H  as  an HMAC key) will be padded by appending an all-zero bit string to obtain a string of the indicatedlength (the length of a single input block for the hash function, hash); a longer salt will be hashed to produce a shorter string (of bit length H_outputBits), which will then be padded (by appending an  all-zero  bit  string)  to  obtain  a  string  of  the  indicated  length (see [FIPS  198]  for additional information).
