### ISSUE TITLE
Add support for keccak256

### ISSUE THREAD

**Issue by fare** [openssl/openssl#13033]
Ethereum and after it many cryptographic applications use the original pre-NIST variant of SHA3-256, these days named keccak256, where the delimiter byte is 0x1 rather than 0x6.

Could you add this variant (and possibly the 224, 384 and 512 bit variants) to your SHA3 support?

See for instance this implementation:
https://github.com/coruus/keccak-tiny

See also test vectors at
https://github.com/fare/gerbil-crypto/blob/master/t/keccak-test.ss

**Comment by slontis** [comment]
It might be a while before this is added - due to trying to get 3.0 to beta stage..

It looks like the padding change is the only difference, and in that case it should not be too hard to add.

i.e in sha3_prov.c add a new macro and duplicate .. change the macro to use 1 instead of 6
See IMPLEMENT_SHA3_functions(224)

Add the function(s) in defltprov.c

**Comment by paulidale** [comment]
OTC: this doesn't conform to our policy about being a standard before inclusion.  In this case, an exception vote has taken place and this can be included.  The reason being that it is in use, we have the implementation and that it just needs to be exposed.

**Comment by paulidale** [comment]
Support has been merged in master.
