### ISSUE TITLE
Whether DTLS can be used without a private key

### ISSUE THREAD

**Issue by zhanghenghw** [openssl/openssl#13109]
We have encounted a project in which out client program should do bidirectional tls handshake with server.
 We have a custom private key signature method，But we can't use private key file!!!
how to build DTLS connection and use our signature method whithout private key？

**Comment by kaduk** [comment]
The normal way to do this sort of thing used to be to write an "ENGINE" that encapsulated operations using the private key.  In some sense it still is, since that's the only way to do it with the currently supported 1.1.1 release series, but that mechanism will soon be deprecated in favor of the "provider" concept to be introduced in the forthcoming OpenSSL 3.0 release.
There are some links with more background at a previous answer to a similar question, at https://github.com/openssl/openssl/issues/11999#issuecomment-636387461
