### ISSUE TITLE
TODO(OpenSSL1.2) should be updated

### ISSUE THREAD

**Issue by Jakuje** [openssl/openssl#13161]
Throughout the code, there are still couple of `TODO(OpenSSL1.2)`, which is somehow outdated as it looks like there will be no 1.2. Not sure how these are urgent, but they should get updated to new targets if not fixed just now.

https://github.com/openssl/openssl/blob/5b70206cb316024c6dc30ce54f585ce5cf001a56/ssl/t1_lib.c#L2059

https://github.com/openssl/openssl/blob/5b70206cb316024c6dc30ce54f585ce5cf001a56/ssl/s3_lib.c#L3514

**Comment by kaduk** [comment]
Thanks for raising the issue; this does seem like something that will need to at least be triaged before 3.0 beta 1.

The first one might require a bit of looking at the history, as the TODO specifically in this location is not clear -- it might just be saying that we shouldn't generate a ClientHello with those values, but I'm not sure yet.
The second one I'm sure @mattcaswell will love, after all the time we spent with `SSL_get_servername()` -- this one is saying that we should make `SSL_set_tlsext_host_name()` calls on a server SSL explicit errors instead of silently masking them.

**Comment by mattcaswell** [comment]
> The first one might require a bit of looking at the history, as the TODO specifically in this location is not clear -- it might just be saying that we shouldn't generate a ClientHello with those values, but I'm not sure yet.

I think its saying that, strictly speaking according to the TLSv1.3 spec, we shouldn't generate a ClientHello which uses DSA etc under any circumstances. However what is actually implemented is a check to see what the minimum TLS version we support is - if its below TLSv1.3 then we allow their use. This strictly speaking means we end up with a ClientHello that *can* be used for TLSv1.3 but contains values prohibited by the TLSv1.3 spec. A strict reading of the spec disallows this (or it did in some draft, I haven't checked what the final text says).

**Comment by kaduk** [comment]
>  A strict reading of the spec disallows this (or it did in some draft, I haven't checked what the final text says).

Still does:

```
   -  In TLS 1.2, the extension contained hash/signature pairs.  The
      pairs are encoded in two octets, so SignatureScheme values have
      been allocated to align with TLS 1.2's encoding.  Some legacy
      pairs are left unallocated.  These algorithms are deprecated as of
      TLS 1.3.  They MUST NOT be offered or negotiated by any
      implementation.  In particular, MD5 [SLOTH], SHA-224, and DSA
      MUST NOT be used.
```
