### ISSUE TITLE
How to compile and generate legacy.so

### ISSUE THREAD

**Issue by 1185129439** [openssl/openssl#13163]
Compared with OpenSSL 1.1.1f ，OpenSSL3.0.0  has a new dynamic library ——legacy.so in providers。How to compile and generate this legacy.so。thanks

**Comment by 1185129439** [comment]
How to configure and where is the configuration file？ thanks！！

**Comment by mspncp** [comment]
Please take a look at the [INSTALL.md](https://github.com/openssl/openssl/blob/master/INSTALL.md) file, it contains a detailed description. Also, the [openssl-users](https://mta.openssl.org/mailman/listinfo/openssl-users) mailing list might be a better place to ask such general questions about using OpenSSL, because you reach a much wider audience.

**Comment by mspncp** [comment]
The [OpenSSL 3.0.0 Wiki Page](https://wiki.openssl.org/index.php/OpenSSL_3.0) might also be helpful.
