### ISSUE TITLE
Early data rejected because of ticket_lifetime

### ISSUE THREAD

**Issue by william-zk** [openssl/openssl#13182]
OpenSSL version:

Openssl1.1.1 and later

problem description:
try this:
```
step1: openssl s_client -connect 127.0.0.1:443 -tls1_3 -sess_out s.lo
step2: Change the client time to a few seconds ago
step3: openssl s_client -connect 127.0.0.1:443 -tls1_3 -sess_in s.lo  -early_data ./httpget.txt
```
phenomena:
server will reject the early data because of ticket_lifetime check, code are show below:
```
 if (id == 0
                    && sess->timeout >= (long)agesec
                    && agems / (uint32_t)1000 == agesec
                    && ticket_age <= agems + 1000  /* this check will fail */
                    && ticket_age + TICKET_AGE_ALLOWANCE >= agems + 1000) {
     s->ext.early_data_ok = 1;
 }   
```

The reason of this problem: When client want to send early data by session ticket, then it will calculate ticket_age and write into session ticket `ticket_lifetime` field. And when server receive it, sever will calculate agems to do a judgement. But we change client time, this judgement would fail.

Maybe it seems not like a openssl problem, but for a client, such as mobile phone, which would often have time adjustment, then it will cause 0-rtt data rejected(but success session resumption). Actually this problem often occurs in our production environment, and it is very difficult to investigate.

I found that the RFC does not require client to recalculate `ticket_lifetime`, so why not just use `ext.tick_lifetime_hint` to check ticket lifetime? Are there any special considerations in this？By the way, I'd like to make a pr help to fix it. ;-)

**Comment by mattcaswell** [comment]
> I found that the RFC does not require client to recalculate ticket_lifetime, so why not just use ext.tick_lifetime_hint to check ticket lifetime? Are there any special considerations in this？By the way, I'd like to make a pr help to fix it. ;-)

The client must accurately calculate the ticket_lifetime, because the server MUST validate it when early_data is in use:

> For PSKs provisioned via NewSessionTicket, a server MUST validate
   that the ticket age for the selected PSK identity (computed by
   subtracting ticket_age_add from PskIdentity.obfuscated_ticket_age
   modulo 2^32) is within a small tolerance of the time since the ticket
   was issued (see Section 8).  If it is not, the server SHOULD proceed
   with the handshake but reject 0-RTT, and SHOULD NOT take any other
   action that assumes that this ClientHello is fresh.

This requirement is there for security reasons, i.e. as a defence against replay attacks.

Therefore if a client wants to take advantage of early_data then the TLSv1.3 spec places a requirement on it that it can accurately calculate the ticket age.

**Comment by t8m** [comment]
Also @william-zk  as the early data should be completely optional thing why would the occasional rejection of it when the client's time fluctuates be a problem?

**Comment by william-zk** [comment]
Oh, I got it, thanks for answering
