### ISSUE TITLE
Inheritance of SNI SSL_CTX's behavior to SSL object

### ISSUE THREAD

**Issue by anupamam13** [openssl/openssl#13208]
I am using openssl-1.1.1d.

I have a default SSL_CTX and a SNI SSL_CTX. 
For both the SSL_CTX I am setting different "ecdh_curve_name" and "ciphersuites" using SSL_CTX_set1_groups_list() and SSL_CTX_set_ciphersuites(). I am also setting client_hello_cb on the default SSL_CTX using SSL_CTX_set_client_hello_cb().

Then i create SSL connection object using the default SSL_CTX. When i get the client_hello_cb for the SSL connection when the request comes with a servername, i change SSL to use the SNI SSL_CTX by setting SSL_set_SSL_CTX(). 

Now i expect the SSL object to have SNI SSL_CTX's setting of "ecdh_curve_name" and "ciphersuites". However i see only the "ciphersuites" to have taken effect but not the "ecdh_curve_name". I had to set it explicitly using SSL_set1_groups_list. Is this correct behavior? Can someone explain why this is needed and how to decide whether it has to be explicitly set for SSL object?
I am also interested in knowing for - ciphers, ssl/tls version and alpn

**Comment by kaduk** [comment]
This is something that is unfortunately not very uniform across the different configuration settings.  Basically, for some of the settings, the configuration is copied from the `SSL_CTX` to the `SSL` during `SSL_new()`, and so the configuration on the SNI `SSL_CTX` will not take effect (unless there is specific logic in `SSL_set_SSL_CTX()` to adjust to that case, but this is only done for the `sid_ctx`).  This is what happens for the supported groups list, at https://github.com/openssl/openssl/blob/47b422c90aec6e3d1de38110d67e17133d086051/ssl/ssl_lib.c#L782-L790
So it is necessary to inspect the implementation of both `SSL_new()` and `SSL_set_SSL_CTX()` (an unfortunate abstraction barrier violation!) in order to answer what will happen for the ciphers, TLS versions, and ALPN settings.

As it happens, the version and ALPN are copied just like the supported groups (so you will need to set them on the SSL directly when you change to the SNI SSL_CTX) but the ciphers are not (so they should be inherited from the SNI SSL_CTX, unless specifically set on the SSL in question at some other point).

**Comment by anupamam13** [comment]
Thanks for your reply.
