### ISSUE TITLE
ECCN for openssl

### ISSUE THREAD

**Issue by akshayrb9** [openssl/openssl#13222]
Hi, For documentation purpose and project release process we need the Export control classification number(ECCN) for Openssl if it applies. Can you please let me know the ECCN ?

**Comment by paulidale** [comment]
OpenSSL does not have one that I'm aware of.

If you distribute OpenSSL as part of your product then it is your responsibility to ensure that you comply with any laws or
regulations that may be in force for your particular region. Since we are not lawyers we cannot advise you on this. I recommend that you consult with a suitably qualified lawyer to answer this question.
