### ISSUE TITLE
SHA-512 patent / IPR issues with SIMD code

### ISSUE THREAD

**Issue by bbbrumley** [openssl/openssl#13244]
Hey Folks,

Looking at commit c4558efbf3a44a1b5e68dce46347dd3888db4760 I see a lot of overlap with [this Intel patent](https://patents.google.com/patent/US20130332742A1).

Is there a CLA / other Intel-specific agreement in place, to alleviate IPR / patent concerns with this code?

**Comment by bbbrumley** [comment]
People are asking. This is from the supercop mailing list

> OpenSSL vectorizes block expansion across multiple blocks, but unfortunately that's covered by U.S. patent 8856546 until 2032, so the new implementation avoids it. (I'm not sure what this patent means for OpenSSL and applications using OpenSSL.) 

So it would be great to have a statement from the project regarding this. Especially since I know first hand you are sticklers for CLAs, which I hope precludes the project from any such IPR worries concerning the commit in question.

**Comment by bbbrumley** [comment]
@mattcaswell you handle the CLAs right?

**Comment by mattcaswell** [comment]
> @mattcaswell you handle the CLAs right?

I receive CLAs and file in them in the right place to make it possible for people to make submissions. Unfortunately that doesn't make me competent to comment on this patent issue, or the legal interpretation of our CLAs :-)

I'll stick to facts that are public.

The corporate CLA text says this about patents:

> 3. Grant of Patent License. Subject to the terms and conditions of this Agreement, You
hereby grant to the Foundation and to recipients of software distributed by the Foundation
a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable (except as
stated in this section) patent license to make, have made, use, offer to sell, sell, import,
and otherwise transfer the Work, where such license applies only to those patent claims
licensable by You that are necessarily infringed by Your Contribution(s) alone or by
combination of Your Contribution(s) with the Work to which such Contribution(s) were
submitted. If any entity institutes patent litigation against You or any other entity
(including a cross-claim or counterclaim in a lawsuit) alleging that your Contribution, or
the Work to which you have contributed, constitutes direct or contributory patent
infringement, then any patent licenses granted to that entity under this Agreement for that
Contribution or Work shall terminate as of the date such litigation is filed.
> 4. You represent that You are legally entitled to grant the above license. You represent
further that each employee of the Corporation designated on Schedule A below (or in a
subsequent written modification to that Schedule) is authorized to submit Contributions
on behalf of the Corporation.

Details of who we have CLA agreements with are not made public, except to say that it is a matter of policy that *all* contributions made since 1.1.0 was released must have a CLA in place unless such contribution is considered trivial.

**Comment by kroeckx** [comment]
We have a CLA with Intel. But we only started using CLAs recently,
so it's unlikely to be covered by a CLA.

Even if there was a CLA in place, it's not clear that Intel
contributed that code or not, the commit doesn't mention anything
about it, nor can I find a record of them submitting it to us.

The commit says it's written in November 2012, commited in
February 2013. Both dates are between the filing date and the
publishing date. It's my understanding that the filing date is the
relevant date, so we can't claim prior art.

**Comment by t8m** [comment]
@dot-asm could perhaps shed some light on the origin of the patch.

**Comment by richsalz** [comment]
I am not commenting on the specifics, but I want to mention that OpenSSL is part of the Open Invention Network, https://openinventionnetwork.com/directory-community/, for two reasons:
- OpenSSL is considered part of the base Linux OS
- OpenSSL Software Foundation is member number 2116 

That might help should a defense be needed.

**Comment by dot-asm** [comment]
> @dot-asm could perhaps shed some light on the origin of the patch.

What is the question more specifically? Did I write it myself? Yes. Did Intel know that I was doing it? Trick question. What is "Intel" more specifically? Legal department? Or engineers who I talk to in case I can't achieve the expected performance? But since "defense" was mentioned, I suppose it's former. In which case the answer would have to be "I have no idea."

BTW, I think you're misreading the patent, I don't see that it's about the module in question. Well, unless it's claimed that patent grants Intel exclusive right to use SIMD instructions in **any** implementation.

**Comment by bbbrumley** [comment]
Hey Andy,

Thanks for the reply.

> What is the question more specifically?

Did Intel commission you or the project to make this contribution? In my simple engineering brain, that would dismiss any doubt. Ofc neither you nor the project are obligated to answer that.

> BTW, I think you're misreading the patent, I don't see that it's about the module in question.

By my reading, part of the patent claims cover preparing the message schedule in parallel with SIMD. I believe you're doing some of that in this code change.

I really am not intending to argue patent details and certainly not point fingers. I am simply looking for the shortest path to dismiss these IPR concerns in the OpenSSL codebase.

**Comment by richsalz** [comment]
Please do NOT discuss patent issues publically.  If it turns out that OpenSSL is infringing then everyone who might have looked at this issue could be liable for triple damages.

STOP.  Close this.

**Comment by bbbrumley** [comment]
Well, this didn't go anywhere.

From an outside perspective, a little disappointing. I expected more from the project management.
