### ISSUE TITLE
RSA_PKCS1_PSS_PADDING for signature verification

### ISSUE THREAD

**Issue by saddy-muchu** [openssl/openssl#13300]
I've observed that we don't have this padding supported during signature verification.
Function is rsa_ossl_public_decrypt() in rsa_ossl.c.

May i know why it isn't included?
is it going to be included in the future?

Reason for asking: i could trigger a invalid padding error from PKCS7_verify() function when RSA_PKCS1_PSS_PADDING is used.
Logs are:
140297930185984:error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding:../openssl-1.1.1d/crypto/rsa/rsa_pk1.c:67:
140297930185984:error:04067072:rsa routines:rsa_ossl_public_decrypt:padding check failed:../openssl-1.1.1d/crypto/rsa/rsa_ossl.c:588:
140297930185984:error:21071069:PKCS7 routines:PKCS7_signatureVerify:signature failure:../openssl-1.1.1d/crypto/pkcs7/pk7_doit.c:1041:
140297930185984:error:21075069:PKCS7 routines:PKCS7_verify:signature failure:../openssl-1.1.1d/crypto/pkcs7/pk7_smime.c:353:

**Comment by mattcaswell** [comment]
The PKCS7 code is not PSS aware - it just assumes RSA_PKCS1_PADDING is used.

We *do* support PSS more generally in libcrypto but you won't see that support in the rsa_ossl_public_decrypt() function. It is implemented at a higher level (i.e. in EVP). See here:

https://github.com/openssl/openssl/blob/25fa346e906c4f487727cfebd5a40740709e677b/crypto/rsa/rsa_pmeth.c#L260-L270

> May i know why it isn't included?

Because no one has done the work to implement PKCS7 PSS support

> is it going to be included in the future?

There are no current plans to add it, although if someone contributed the necessary code in the form of a PR it would be considered.
