### ISSUE TITLE
Signature Verification using EVP_Verify* functions

### ISSUE THREAD

**Issue by saddy-muchu** [openssl/openssl#13345]
I have a PKCS7 signature with me that is signed using PSS padding.
Now i want to verify this signature using the EVP interface.

I have seen both EVP_Verify* and EVP_DigestVerify* interfaces.
I'm currently using OpenSSL 1.1.1d.
Which interface is supported in this OpenSSL version?
Which one should be used?

**Comment by mattcaswell** [comment]
As per the discussion in #13300, we don't support PSS mode using the PKCS7 APIs. Your question suggests you want to do it "manually", i.e. not going via the PKCS7 APIs.

To do that you need to use the macro `EVP_PKEY_CTX_set_rsa_padding()` to set the padding mode to `RSA_PKCS1_PSS_PADDING`.  Potentially you may need to set saltlen and MGF1 MD using `EVP_PKEY_CTX_set_rsa_pss_saltlen()` and `EVP_PKEY_CTX_set_rsa_mgf1_md()` respectively. See the documentation on these macros here:

https://www.openssl.org/docs/man1.1.1/man3/EVP_PKEY_CTX_ctrl.html

You will note that above macros operate on an `EVP_PKEY_CTX` object. The older verify functions `EVP_Verify*` do not give you the opportunity to influence the underlying `EVP_PKEY_CTX`. By contract the `EVP_DigestVerifyInit` function enables you to get a reference to the `EVP_PKEY_CTX` so that you can set things like the padding mode. See the documentation here:

https://www.openssl.org/docs/man1.1.1/man3/EVP_DigestVerifyInit.html

Note that `EVP_DigestVerify*` performs the combined operation of digesting the input, and then verifying the signature associated with the digested data. This is the normal way of doing things but sometimes you need more control over the digesting process (or not do it at all in some cases). There is also the lower level `EVP_PKEY_verify` function which just does a low level verification operation. It assumes that any input data has been pre-digested as required. See the documentation here:

https://www.openssl.org/docs/man1.1.1/man3/EVP_PKEY_verify.html

**Comment by saddy-muchu** [comment]
Thanks for the detailed explanation.
i have seen that via the  "openssl cms" cmd line interface, we provide the padding via the "keyopt" option. Does this mean, we can using RSA-PSS padding via CMS api's?

On the other hand, "openssl pkcs7" cmd line interface doesn't have any such utility.

**Comment by saddy-muchu** [comment]
Commands used:

openssl genrsa -out rootCAkey.pem 4096

openssl req -x509 -new -nodes -key rootCAkey.pem -sha256 -days 1024 -out rootCAcert.pem

openssl cms -in testdata -sign -inkey rootCAkey.pem -signer rootCAcert.pem -keyopt rsa_padding_mode:pss -out cmsig

i could clearly see a "rsassaPss" object in the "cmsig" structure
