### ISSUE TITLE
The memory alloc for variable rsa are not freed in function get_test_pkey in file test/enginetest.c

### ISSUE THREAD

**Issue by ycdxsb** [openssl/openssl#13420]
The memory alloc for variable `rsa` are not freed in function get_test_pkey(before https://github.com/openssl/openssl/blob/master/test/enginetest.c#L243 and https://github.com/openssl/openssl/blob/master/test/enginetest.c#L246) . It is a piece of test code, but add a memory free before return will be better.
```
221 static EVP_PKEY *get_test_pkey(void)
222 {
223    static unsigned char n[] =
224        "\x00\xAA\x36\xAB\xCE\x88\xAC\xFD\xFF\x55\x52\x3C\x7F\xC4\x52\x3F"
225        "\x90\xEF\xA0\x0D\xF3\x77\x4A\x25\x9F\x2E\x62\xB4\xC5\xD9\x9C\xB5"
226        "\xAD\xB3\x00\xA0\x28\x5E\x53\x01\x93\x0E\x0C\x70\xFB\x68\x76\x93"
227        "\x9C\xE6\x16\xCE\x62\x4A\x11\xE0\x08\x6D\x34\x1E\xBC\xAC\xA0\xA1"
228        "\xF5";
229    static unsigned char e[] = "\x11";
230
231    RSA *rsa = RSA_new();
232    EVP_PKEY *pk = EVP_PKEY_new();
233
234    if (rsa == NULL || pk == NULL || !EVP_PKEY_assign_RSA(pk, rsa)) {
235        RSA_free(rsa);
236        EVP_PKEY_free(pk);
237        return NULL;
238    }
239
240    if (!RSA_set0_key(rsa, BN_bin2bn(n, sizeof(n)-1, NULL),
241                      BN_bin2bn(e, sizeof(e)-1, NULL), NULL)) {
242        EVP_PKEY_free(pk);
+          RSA_free(rsa);
243        return NULL;
244    }
+      RSA_free(rsa);
245   
246    return pk;
}
```

**Comment by mattcaswell** [comment]
This is incorrect - the original code looks right to me. As soon as the `EVP_PKEY_assign_RSA` call successfully returns, the RSA object is "owned" by the EVP_PKEY. Freeing the EVP_PKEY also frees the RSA object. Your suggested modifications would actually introduce a double free.

Strictly speaking it would probably be better if the `RSA_set0_key` call occurred *before* the `EVP_PKEY_assign_RSA` call since it assumes that the RSA object reference is still valid even after it has been assigned.
