### ISSUE TITLE
About the relationship and difference between openssl and gnutls.

### ISSUE THREAD

**Issue by hongyi-zhao** [openssl/openssl#13457]
Hi,

On Ubuntu 20.04, when I try to install [pycurl](https://github.com/pycurl/pycurl), it seems that it relies on one of the following libraries: openssl and gnutls. For my case, installation of the following packages can meet the required dependency:
```
sudo apt-get install libcurl4 libcurl4-openssl-dev
or
sudo apt-get install libcurl4 libcurl4-gnutls-dev
```
OTOH, I also noticed that openssl and gnutls are conflict with the other, i.e., I only need and can install one of them. So, I want to know what's the relationship and difference between them. Any hints will be highly appreciated.

Regards,
HY

**Comment by paulidale** [comment]
They are both different cryptographic toolkits.  As for which is more suitable for your use, it might be best to ask the pycurl or curl developers.

**Comment by kroeckx** [comment]
There are multiple copies of libcurl in Ubuntu, and they can all be installed at the same time. Those are libcurl4, libcurl3-gnutls, libcurl3-nss. You normally don't install them, you install something else that depends on them.

But if you want to build/link against libcurl, you need the development versions so that you know against which one to builld. Those are libcurl4-openssl-dev, libcurl4-gnutls-dev and libcurl4-nss-dev. You can only install 1 of those.

Which one to use depends on various factors, including the license of openssl, gnutls and nss.

**Comment by hongyi-zhao** [comment]
Thanks a lot for your clarification.
