### ISSUE TITLE
bio_new_from_core_bio not available for external providers

### ISSUE THREAD

**Issue by gotthardp** [openssl/openssl#13464]
In an external provider I am trying to implement the OSSL_OP_ENCODER, mainly the OSSL_FUNC_encoder_encode() function, which gives me the provider-side key and a OSSL_CORE_BIO pointer.
However, the PEM_ASN1_write_bio() function I use for encoding expects a pointer to BIO as an argument. Following the example of internal providers, I thought I will use the `bio_new_from_core_bio()` to get BIO from the OSSL_CORE_BIO, but this function is not available externally.
I don't see any other way to get BIO from OSSL_CORE_BIO and also I don't see any way to write ASN.1 using the OSSL_CORE_BIO pointer. Or am I missing something?

**Comment by mattcaswell** [comment]
> I don't see any other way to get BIO from OSSL_CORE_BIO and also I don't see any way to write ASN.1 using the OSSL_CORE_BIO pointer. Or am I missing something?

No, you're not missing anything.

The original intent was that provider authors would use the various BIO related "upcalls" available to them from core (see the "Core functions" section in the `provider-base` man page...although it looks like that section needs a bit of an update, because it misses a few BIO upcalls).

When we came to write our own providers we realised we needed to be able to pass a real BIO object around and `bio_new_from_core_bio()` was written to create one and wrap the upcalls - but it was only ever intended for our own internal use.

However I can see why third party provider authors would want to do exactly the same thing so it might make sense to make it available publicly. PR's welcome!

Of course the workaround is just to copy providers/common/bio_prov.c into your own provider for now, since it should be pretty much self contained.

**Comment by gotthardp** [comment]
Now I wonder what is the purpose of the bio_prov.c wrapper? It captures the "upcall" functions, makes new BIO* from them, but then take the SSL_CORE_BIO* from the OSSL_FUNC_encoder_encode(), which is also BIO* essentially and makes the first BIO called with the second BIO* as an argument.
The #11758 talks about a possible conflict when the provider is linked against a different version of libcrypto than the version of libcrypto that loaded the provider. But-- aren't the "upcalls" captured during initialization and the OSSL_CORE_BIO passed via the OSSL_FUNC_encoder_encode based on the identical BIO functions? Both come from the caller. Could these two be ever different?

**Comment by mattcaswell** [comment]
Consider the scenario where the application is linked against a different version of libcrypto to the version used by the provider. Further consider the possibility that in each of those versions of libcrypto the BIO structure is different (e.g. a different size, with fields moved around). In that scenario the application's version of BIO_read (for example) works differently and assumes a different BIO structure than the provider's version of the same function. So they really are different functions (albeit with the same name).

Seen from the provider side perspective the OSSL_CORE_BIO object is a handle on the application side BIO structure. While a plain BIO object is a handle on the provider side BIO structure. The provider cannot call the versions of the BIO functions that know about the OSSL_CORE_BIO structure layout - because it isn't linked against that version of libcrypto. The only way it can do that is to call the upcalls.

**Comment by mattcaswell** [comment]
This is now being tracked by #14409. Closing this one.
