### ISSUE TITLE
SSL_select_next_proto may return an insecure address

### ISSUE THREAD

**Issue by dylc5190** [openssl/openssl#13521]
https://github.com/openssl/openssl/blob/2d840893e78253bcce428603fdbcda159bdebe08/ssl/ssl_lib.c#L2917

I got problem on this when using Perl's SSL module Net::SSLeay. In the NPN callback, result will eventually point to a soon-to-be-freed address and then my program got crashed. I'm wondering why not set result to NULL if nothing is negotiated?

![圖片](https://user-images.githubusercontent.com/16539810/100314388-7adf2400-2ff1-11eb-84dc-1e0bdc9b1c32.png)
https://github.com/radiator-software/p5-net-ssleay/blob/8c9187507af9039e3bf68e74ca04cd20f95591fd/SSLeay.xs#L1191

**Comment by mattcaswell** [comment]
That might be a reasonable thing to do - but the current behaviour is not unreasonable and is well documented:

https://www.openssl.org/docs/man1.1.1/man3/SSL_select_next_proto.html

> If no match is found, the first item in client, client_len is returned in out, outlen. 

This API has been around for many years so changing its behaviour now is really not an option since apps may be relying on this documented behaviour.

**Comment by dylc5190** [comment]
OK. I got your point. Thanks.
