### ISSUE TITLE
Buffer length from a BIO

### ISSUE THREAD

**Issue by saddy-muchu** [openssl/openssl#13613]
Currently, i have a filled BIO pointer 'p'
i would like to know if there is any BIO function that would return the buffer length (say 'buf_len') from this BIO pointer which can later be used in the BIO_read() function.

Ex: BIO_read(p, data , buf_len);

**Comment by mattcaswell** [comment]
It's a little unclear what exactly you are asking, since your question assumes that all BIOs have a buffer. This is not the case. However, some certainly do.

Probably what you want is the `BIO_pending` macro. The documentation says this about it:

> BIO_pending(), BIO_ctrl_pending(), BIO_wpending() and BIO_ctrl_wpending()
return the number of pending characters in the BIOs read and write buffers.
Not all BIOs support these calls. BIO_ctrl_pending() and BIO_ctrl_wpending()
return a size_t type and are functions, BIO_pending() and BIO_wpending() are
macros which call BIO_ctrl().

https://www.openssl.org/docs/man1.1.1/man3/BIO_pending.html

**Comment by saddy-muchu** [comment]
OK
Thank you
