### ISSUE TITLE
OSSL_DECODER segfaults if passed a pkcs8 (x509) public key.

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#13610]
When trying to load the key it has no domain parameters. So when it tries to cache the key it attempts to get the size
And this will then do a NULL access since dsa->params is NULL.
This sees like a general problem that may exist across multiple key types.

Here is a minimal test case to reproduce the issue..

````
#ifndef OPENSSL_NO_DSA
static int dsa_private_decode_failure(void)
{
    static const unsigned char dsa_der_pkcs8_public_key[] = {
        0x30, 0x12, /* SEQ */
            0x30, 0x09, /* SEQ */
                  0x06, 0x07, /* ALG OID */
                             0x2a, 0x86, 0x48, 0xce, 0x38, 0x04, 0x03,
            0x03, 0x05, /* BITSTRING: public key */
                  0x00, 0x02, 0x01, 0x00, 0x23,
    };
    int ret = 0;
    EVP_PKEY *pkey = NULL;
    OSSL_DECODER_CTX *dctx;
    const unsigned char *pder = dsa_der_pkcs8_public_key;
    size_t len = sizeof(dsa_der_pkcs8_public_key);

    ret = TEST_ptr(dctx = OSSL_DECODER_CTX_new_by_EVP_PKEY(&pkey, "DER", "pkcs8", "DSA", EVP_PKEY_KEYPAIR, NULL, NULL))
          && TEST_true(OSSL_DECODER_from_data(dctx, &pder, &len)) /* TIME TO SEGFAULT */
          && TEST_ptr_null(pkey);

    OSSL_DECODER_CTX_free(dctx);
    EVP_PKEY_free(pkey);
    return ret;
}
#endif /* OPENSSL_NO_DSA */

 int setup_tests(void)
 {
  ...
  ...
 #ifndef OPENSSL_NO_DSA
        ADD_TEST(dsa_private_decode_failure);
````

This is the reason for the fuzz test failure in PR https://github.com/openssl/openssl/pull/13591

**Comment by slontis** [comment]
NOTE: this only segfaults for a selection of EVP_PKEY_KEYPAIR...
EVP_PKEY_PUBLIC & EVP_PKEY_PARAMETERS both pass as expected.

**Comment by slontis** [comment]
Callstack is

````
#1  0x00005555557045ee in DSA_bits (dsa=0x5555559cb0c0) at crypto/dsa/dsa_lib.c:338
#2  0x00005555556a4c8e in dsa_get_params (key=0x5555559cb0c0, params=0x7fffffffc790)
    at providers/implementations/keymgmt/dsa_kmgmt.c:281
#3  0x00005555555ef71b in evp_keymgmt_get_params (keymgmt=0x5555559ce650, keydata=0x5555559cb0c0,
    params=0x7fffffffc790) at crypto/evp/keymgmt_meth.c:371
#4  0x00005555555edefb in evp_keymgmt_util_cache_keyinfo (pk=0x5555559cf830) at crypto/evp/keymgmt_lib.c:225
#5  0x00005555555ed894 in evp_keymgmt_util_assign_pkey (pkey=0x5555559cf830, keymgmt=0x5555559ce650,
    keydata=0x5555559cb0c0) at crypto/evp/keymgmt_lib.c:62
#6  0x00005555555ed8ec in evp_keymgmt_util_make_pkey (keymgmt=0x5555559ce650, keydata=0x5555559cb0c0)
    at crypto/evp/keymgmt_lib.c:73
#7  0x00005555555dda82 in decoder_construct_EVP_PKEY (decoder_inst=0x5555559ccb90, params=0x7fffffffcb10,
    construct_data=0x5555559cd290) at crypto/encode_decode/decoder_pkey.c:166
(gdb) down
#6  0x00005555555ed8ec in evp_keymgmt_util_make_pkey (keymgmt=0x5555559ce650, keydata=0x5555559cb0c0)
    at crypto/evp/keymgmt_lib.c:73
(gdb) up
#7  0x00005555555dda82 in decoder_construct_EVP_PKEY (decoder_inst=0x5555559ccb90, params=0x7fffffffcb10,
    construct_data=0x5555559cd290) at crypto/encode_decode/decoder_pkey.c:166
#8  0x00005555555dbfd0 in decoder_process (params=0x7fffffffcb10, arg=0x7fffffffcc70)
    at crypto/encode_decode/decoder_lib.c:536
````

**Comment by slontis** [comment]
````
(gdb) p *dsa
$1 = {pad = 0, version = 0, params = {p = 0x0, q = 0x0, g = 0x0, j = 0x0, seed = 0x0, seedlen = 0, pcounter = -1,
    nid = 0, gindex = -1, h = 0, flags = 3, mdname = 0x0, mdprops = 0x0}, pub_key = 0x5555559cf960, priv_key = 0x0,
  flags = 1, method_mont_p = 0x0, references = 1, ex_data = {ctx = 0x0, sk = 0x0},
  meth = 0x55555595d940 <openssl_dsa_meth>, engine = 0x0, lock = 0x5555559cf3e0, libctx = 0x0, dirty_cnt = 2}
````

**Comment by slontis** [comment]
I am unsure about where this should be checked.. dsa_get_params()?

**Comment by levitte** [comment]
So, uhmmmm, this is how [RFC 5208](https://tools.ietf.org/html/rfc5208#section-5) defines PrivateKeyInfo:

```
      PrivateKeyInfo ::= SEQUENCE {
        version                   Version,
        privateKeyAlgorithm       PrivateKeyAlgorithmIdentifier,
        privateKey                PrivateKey,
        attributes           [0]  IMPLICIT Attributes OPTIONAL }

      Version ::= INTEGER

      PrivateKeyAlgorithmIdentifier ::= AlgorithmIdentifier

      PrivateKey ::= OCTET STRING

      Attributes ::= SET OF Attribute
```

However, PKCS#8 isn't what you have there, but rather a SubjectPublicKeyInfo (which is not the same thing), defined like this in [RFC 5280](https://tools.ietf.org/html/rfc5280#section-4.1):

```

   SubjectPublicKeyInfo  ::=  SEQUENCE  {
        algorithm            AlgorithmIdentifier,
        subjectPublicKey     BIT STRING  }
```

If you use the structure name "SubjectPublicKeyInfo" instead of "pkcs8", you're probably going to get better results.

That being said, an actual crash is still not a good thing.  I suppose there is a NULL dereference somewhere that we're not catching.

**Comment by slontis** [comment]
callstack and data listed above show you what is going on.
It does look like it actually 'thinks' it is pkcs8 from what it loads since it does the asn1 decode part..

**Comment by slontis** [comment]
I guess it tries to load the private key part which fails and then it tries the public key part..

**Comment by levitte** [comment]
I get worried that `decoder_construct_EVP_PKEY()` is called...  I wonder what kind of params it got, cause I can't imagine how it could extract anything from your DER, as that's not a PKCS#8 at all.
It could be interesting to see what you get with `enable-trace` and `OPENSSL_TRACE=DECODER`...

**Comment by slontis** [comment]
TRACE[40:47:5E:96:44:7F:00:00]:DECODER: (ctx 0x560f1fcc1e70) Looking for DSA decoders with selection 135
TRACE[40:47:5E:96:44:7F:00:00]:DECODER:     input type: DER, input structure: pkcs8
TRACE[40:47:5E:96:44:7F:00:00]:DECODER: (ctx 0x560f1fcc1e70) Added decoder instance 0x560f1fd1bea0 (decoder 0x560f1fcc3860) with:
TRACE[40:47:5E:96:44:7F:00:00]:DECODER:     input type: DER, input structure: pkcs8
TRACE[40:47:5E:96:44:7F:00:00]:DECODER: (ctx 0x560f1fcc1e70) Added decoder instance 0x560f1fcc0ef0 (decoder 0x560f1fcc3860) with:
TRACE[40:47:5E:96:44:7F:00:00]:DECODER:     input type: DER, input structure: pkcs8
TRACE[40:47:5E:96:44:7F:00:00]:DECODER: (ctx 0x560f1fcc1e70) Got 2 decoders
Segmentation fault (core dumped)

**Comment by levitte** [comment]
Cool, thanks.  At least, this wasn't caused by some rogue implementation getting mixed into the pot...

**Comment by levitte** [comment]
Ok, found it...  `decoder_der2key.c` is a bit too flexible when there is an extractor function...  then it will basically go back to guessing mode regardless of if an input structure is given or not, so it successfully decodes your DER data with d2i_PUBKEY_ex(), and passes the result to the decoding callback, but then, something somewhere expects parameters that are simply not there.  It really should not have come that far at all.

However, it's true that the problem is manyfold...  should a DSA public key always have key parameters with it, or is it fine to have *just* the public key?  It's possible that there are parts of our code that do expects key parameters to be present in all DSA keys.

**Comment by levitte** [comment]
Is the DER data from a live cert somewhere, or did you make it up all on your own?

**Comment by levitte** [comment]
I've just looked at the legacy code (dsa_ameth.c), and indeed, it's possible to have a DSA structure without parameters, so it does indeed look like `dsa_get_params()` needs to check that.  In 1.1.1, this same key would cause a crash when `EVP_PKEY_bits()` is called.  But since we are caching those values in master, that same crash happens earlier.  One could say that the problem lies in `DSA_bits()` because it doesn't check if the `p` parameter is present (which for example `DSA_security_bits()` does!)...

**Comment by levitte** [comment]
#13611 fixes the crashes, at least as far as I've tested.

The decoder issues I discovered (and you probably will as well) are worthy of another raised issue.

**Comment by slontis** [comment]
> Is the DER data from a live cert somewhere, or did you make it up all on your own?

It was from the fuzz asn1 test data
