### ISSUE TITLE
OSSL_DECODER_CTX_new_by_EVP_PKEY OSSL_ENCODED_CTX_new_by_EVP_PKEY

### ISSUE THREAD

**Issue by t-j-h** [openssl/openssl#13622]
These API names aren't following the consistent pattern. 
Using _new_by is not the right approach. We have _new_from when constructing something.
e.g. EVP_PKEY_CTX_new_from_pkey

The APIs should be renamed to following that pattern.

And yes there is another use of new_by in EC_KEY_new_by_curve_name but that isn't the same sort of thing.

In English usage terms all the new_by should be new_from IMHO - but certainly the newly added APIs should be following the main naming convention already in use.

**Comment by levitte** [comment]
For starters, I agree that "by" wasn't the best choice.

Function like `EVP_PKEY_CTX_new_from_pkey` have "from" in them because they do something (create something new) from existing data (some input parameter, like a pkey), and while one could arguably have `OSSL_ENCODER_CTX_new_from_pkey`, the same kind of thinking doesn't quite fit for decoder variant, since it doesn't create the DECODER_CTX from existing pkey data.
The name choices for these two functions was made to strongly associate with the *type* of the intended input / output.

**Comment by t8m** [comment]
Should the names be OSSL_DECODER_CTX_new_for_pkey and OSSL_ENCODER_CTX_new_from_pkey then?

**Comment by t-j-h** [comment]
OTC: If we keep combined function then use _for_; but prefer to move into two functions then use _setup_for_ for the new function.
