### ISSUE TITLE
Retrieving peer_chain from SSL_SESSION

### ISSUE THREAD

**Issue by GuyLewin** [openssl/openssl#13673]
We're developing to a software that exposes a `SSL_SESSION` struct to our code.
Even though the function `SSL_SESSION_get0_peer` exists, there's no way to get `peer_chain` (and not the individual certificate) out of this structure.
Is this intended? Can I create a PR to introduce a `SSL_SESSION_get0_peer_chain` function?

Thanks!

**Comment by kaduk** [comment]
Roughly speaking, the `SSL_SESSION` is supposed to contain the information that you need in order to resume a TLS connection, and not much else.  That the peer end-entity certificate itself is available is something of an exception to that rule already (it's there because it's the most robust way to store the identity of the authenticated peer, which becomes very important when you are a TLS server that is resuming connections created by clients that used client-certificate authentication.  Given that the intent is to store the authenticated identity and not to allow for future re-verification of the certificate itself, in my opinion adding the entire peer chain to the `SSL_SESSION` would be tough to sell.  There's already pressure to keep the size of the `SSL_SESSION` down (session tickets are basically just ASN.1-encoded `SSL_SESSION` objects, among other things), and adding the full chain would increase the size by a significant amount.
@mattcaswell does that sound right to you?

**Comment by GuyLewin** [comment]
@kaduk thanks for your reply!
The entire peer is already a part of `SSL_SESSION`, my suggestion is simply to include a function to export it.
This is a snippet from the most recent `ssl_local.h`:
https://github.com/openssl/openssl/blob/ea7808143d6880db0cb9eb9cf6694c23958d32b0/ssl/ssl_local.h#L590

**Comment by kaduk** [comment]
That would be misleading, though, since the API would only work on initial handshakes and not resumptions.  Note that the `SSL_SESSION_ASN1` contains only the peer and not the chain:
https://github.com/openssl/openssl/blob/ea7808143d6880db0cb9eb9cf6694c23958d32b0/ssl/ssl_asn1.c#L27

We generally don't add APIs in the `SSL_SESSION` namespace that are ineffectual on resumed sessions.

**Comment by GuyLewin** [comment]
@kaduk makes sense to me, we can close this suggestion

**Comment by kaduk** [comment]
Closing per submitter feedback.
Thanks for raising the topic; I will file a separate issue (#13745) to propose moving the `peer_chain` field from the `SSL_SESSION` to the `SSL` itself...
