### ISSUE TITLE
openssl1.1.1g: How to enable certificate based TLS1.3 authentication 

### ISSUE THREAD

**Issue by pankajjnumca05** [openssl/openssl#13689]
I am using openssl1.1.1g to setup TLS1.3 connection.

By default openssl1.1.1g seems to be using PSK based authentication. Is there a way to enforce certificate based authentication instead ?

I have already tried compiling with -D OPENSSL_NO_PSK option.. hoping it would disable the default PSK authentication and then fallback would be the certificate based auth. But it didn’t help. 

Some compile time solution would be preferred.

**Comment by kaduk** [comment]
(The issue title as written is a bit odd; certificate-based authentication is enabled by default.  The body text does clarify that the interest is in excluding PSK, rather than including certificate.)

So, the TLS 1.3 "PSK" mechanism is used for both the so-called "external" PSK that is what we would traditionally think of as a PSK ciphersuite (a symmetric key known to both parties out of band), and for "resumption" PSK from session tickets.  Anything that would disable external PSK at compile-time would also disable TLS 1.3 resumption entirely.  It's not clear just from your description here whether that would be tolerable.

Second, there is perhaps some level of difference between how TLS clients and servers interact with the PSK.  In either case, you will definitely not use an "external" PSK if you do not configure one!  For clients, you would also need to configure a session ticket in order to use the (PSK) TLS 1.3 resumption flow.  Servers, on the other hand, will issue (and accept) TLS 1.3 session tickets without any additional configuration.  Even setting `SSL_OP_NO_TICKET` on the server `SSL` merely forces the use of a stateful cache, but still sends the protocol elements that will be used as a PSK by the client during resumption.

**Comment by pankajjnumca05** [comment]
Thanks a lot. 

I am new to openssl. Apology for the confusion. It is sorted now. 
Actually everything after Server Hello is encrypted in TLS 1.3 and that is why I was unable to see certificate exchange on Wireshark.

Couple of more clarifications:
1) I am in need to strictly use only TLS 1.3 (and nothing else). Is there is way to enforce this using 1) compile time flag OR 2) APIs
2) Why does "Client Hello" carries a "psk_key_exchange_modes" even when there is no  “pre_shared_key” extension present ? Is it really needed, if not how can be remove it ?
 
![image](https://user-images.githubusercontent.com/66313109/102786569-bb01ae80-43c5-11eb-86e4-8e60991b693e.png)
 
Regards
Pankaj

**Comment by mattcaswell** [comment]
> I am in need to strictly use only TLS 1.3 (and nothing else). Is there is way to enforce this using 1) compile time flag OR 2) APIs

Yes, you can use (for example) `SSL_CTX_set_min_proto_version` to set the minimum permitted TLS version to TLSv1.3.

> Why does "Client Hello" carries a "psk_key_exchange_modes" even when there is no “pre_shared_key” extension present ? Is it really needed, if not how can be remove it ?

Strictly speaking it does not need to be there if there is no PSK, but OpenSSL sends it regardless. You can't suppress that behaviour. Its harmless. Just ignore it.

**Comment by kaduk** [comment]
> > I am in need to strictly use only TLS 1.3 (and nothing else). Is there is way to enforce this using 1) compile time flag OR 2) APIs
> 
> Yes, you can use (for example) `SSL_CTX_set_min_proto_version` to set the minimum permitted TLS version to TLSv1.3.

IIRC you can also do this at compile time by passing `no-tls1 no-tls1_1 no-tls1_2` to Configure (at least, until TLS 1.4 exists and is implemented).

**Comment by pankajjnumca05** [comment]
Thanks. Your answers were really helpful.

One other query I have is on "TLS version" info in headers.  TLS 1.3 packets have version mentioned as "TLS 1.0" and "TLS 1.2" in "Client Hello" messages. See the attachment as following.

![image](https://user-images.githubusercontent.com/66313109/103234020-a0e74380-4964-11eb-9287-b88699673ab0.png)
 
Doesn't this look inconsistent ? Shouldn't it be TLS 1.3 ? 

I don't have any problem because of it, just wanted a clarification note if you can add.

**Comment by richsalz** [comment]
TLS 1.3 handshake looks like TLS 1.2 because of middleboxes on the Internet that were coded badly.

Look at the extensions in the handshake to determine which version is being used.

**Comment by kaduk** [comment]
Some further discussion of these issues is given in https://tools.ietf.org/html/rfc8446#appendix-D (but the gory details would be in the archives of the IETF TLS WG mailing list).

**Comment by pankajjnumca05** [comment]
Thanks.

One more query, by default openssl client negotiates using following TLS 1.3 cipher suites.

TLS_AES_128_GCM_SHA256
TLS_AES_256_GCM_SHA384
TLS_CHACHA20_POLY1305_SHA256

Is there a way to add TLS_AES_128_CCM_SHA256 & TLS_AES_128_CCM_8_SHA256 also to the above list or is it something not implemented yet ?

**Comment by kaduk** [comment]
See https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_ciphersuites.html
I was about to add a note that the CCM_8 variant might need a reduced SECLEVEL to be usable, though apparently that's currently not the case.  (Arguably it should be the case, since the 64-bit authentication tag does reduce the provided level of security.)
