### ISSUE TITLE
Reading PEM files doesn't take PEM type into account

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#13709]
When I use "openssl x509 -in file.pem", and that file is a PEM file with "BEGIN CERTIFICATE", it first seems to be trying to parse it as type PUBKEY, than an X509_SIG, PKCS8_PRIV_KEY_INFO, X509_AUX, X509, X509_CRL, ... It seems to have lost it's type information, and tries to parse a format until it doesn't get a parse error.

I haven't looked at the code, but I think that if it gets back the wrong type, or can't parse it as any type, it just gives some general error instead of the parsing error.

I've also seen that if the file is a DER file, and you tell to read it as a PEM file, it's happy to read it, instead of giving an error that it can't read it as PEM.

**Comment by levitte** [comment]
Hmmm...  the decoder implementation should pass some info back to libcrypto, described in https://github.com/openssl/openssl/blob/master/doc/man7/provider-object.pod.  It's quite possible that we're missing some, or that the central code in libcrypto doesn't *quite* deal with it the way it should.  I dunno and am not going to dive into it now now now, seeing that I'm taking a well needed break starting Monday.

**Comment by levitte** [comment]
I look at this with fresh eyes, and yeah, information is indeed dropped.

It should all be handled in this function:

https://github.com/openssl/openssl/blob/50ccc176da8644be079eccc4523c261e34f7b293/providers/implementations/encode_decode/decode_pem2der.c#L113-L213

As you can see, it does decode the *data type* [OSSL_PARAM_OBJECT_DATA_TYPE] if it's a pkey through, but doesn't declare an object type [OSSL_PARAM_OBJECT_TYPE] (which should at the very least be set to `OSSL_OBJECT_PKEY` for a pkey).

It could be made intelligent enough to detect all sort of PEM files and set the object type appropriately as well.  However, object types are not part of the DER->whatever information that libcrypto takes into when selecting the next decoder or keymgmt to try, and for a moment, I was thinking that "dang, we'll need another bit of information". That turns out not to be true, because we already have the concept of structures (OSSL_OBJECT_PARAM_DATA_STRUCTURE), and that happens to match the other sort of stuff that we can get from PEM files.
All we need is to come up with structure names.  A proposal is to map to the the ASN.1 names (I already started that with SubjectPublicKeyInfo)

`CERTIFICATE`
-> OSSL_PARAM_OBJECT_DATA_TYPE = **OSSL_OBJECT_CERT**
-> OSSL_PARAM_OBJECT_DATA_STRUCTURE = **"Certicate"**

`CERTIFICATE REQUEST`
-> OSSL_PARAM_OBJECT_DATA_TYPE = **OSSL_OBJECT_CSR** (we'll have to add that one)
-> OSSL_PARAM_OBJECT_DATA_STRUCTURE = **"CertificationRequest"**

`X509 CRL`
-> OSSL_PARAM_OBJECT_DATA_TYPE = **OSSL_OBJECT_CRL**
-> OSSL_PARAM_OBJECT_DATA_STRUCTURE = **"CertificateList"**

...

**Comment by levitte** [comment]
Note that our DER decoder implementations only handle keys, so the other object types will fail when going through those.  That's because we have no support for those other object types in providers.  However, this OSSL_STORE function is designed to handle the missing pieces:

https://github.com/openssl/openssl/blob/50ccc176da8644be079eccc4523c261e34f7b293/crypto/store/store_result.c#L103

So basically, for whatever the provider side decoders can't handle, the OSSL_STORE libcrypto functionality tries to save the day.  All it needs is to get a DER blob and enough other data to make sense of what it gets (if not, it tries stuff until it finds a match, which is precisely the effect that @kroeckx saw).

**Comment by mattcaswell** [comment]
Fix in #14191
