### ISSUE TITLE
Should OpenSSL provide a root store?

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#13743]
This is being discussed in #7871, and is sort of hijacking that discussion.

**Comment by noloader** [comment]
I think that would make a good addition for folks who use Mozilla's [cacert.pem](https://curl.se/ca/cacert.pem) or Google's [roots.pem](https://pki.goog/roots.pem).

Keep in mind not all folks use the CA Zoo. Use cases still include loading the CA required to validate an EE certificate, and nothing more. For example, a connection to openssl.org should still validate using only the Let's Encrypt R3 ca.

**Comment by kroeckx** [comment]
The question is not really clear to me. One way to interprete that
question is that CAs can ask us to include their CA in our root
store. I don't think we should be evaluating root CAs. There are
already plenty of root stores available.

So the question could be if we should ship a converted root store,
for instance Mozilla's root store converted. I don't think we
should be doing that either, people should use the root store
directly.

What we might want to do is ship something that can convert the
root stores to a format we understand. But those scripts already
exist, they just need to be modified.

If we want to convert them to "TRUSTED CERTIFICATE", one problem
is going to be that OpenSSL is going to be the only one that
understands them. So we might need to place that into a different
directory/file so that other programs still keep working.

This all seems to be out of scope of what OpenSSL should provide.

**Comment by richsalz** [comment]
I have the following reasons for being against a trust store.

- Maintaining one is nearly a full-time job.  Look at the Mozilla process [1] and the just-announced Chrome Root Program [2].  Think about how to handle controversial issues, such as the Dark Matter CA [3] and the Kazakhstan CA [4]. You can't make the policy "accept anyone who asks" without pointing out very clearly to people that CA's like those would be accepted.

- In my opinion, the team does not have the necessary skills. They can be obtained, of course. There's a vast body of knowledge; start by reading all the links on [1] and perhaps the CA/Browser forum filings.

- The team already has problems with getting releases out; this will be a distraction from the project's main deliverable. This  is probably obvious from the first two, but is worth calling out: what will the project give up by taking on this responsibility?

- The code to implement this is not complete, as shown by comments such as [5].  There are conflicting views on some points such as KeyUsage extensions [6].

- None of the major browsers (Chrome, Safari, Firefox, Edge) would give up their root program for OpenSSL's. The question is then, who is this for? Without a well-defined answer for that question, it seems hard to justify the effort of doing this work, as described in the points above.

- The OpenSSL release cycle, in both timing and policy, does not match up with the needs of a root program update. If a new CA is added, all supported releases must get the update. In order to get downstream users to take the update, the trust store changes must be marked as HIGH, and probably must be separated from any other fixes that are already scheduled. Since OpenSSL is bundled in many Linux release, for example, the project must figure out how to affect changes in those platforms. Browsers, which are mostly installed directly by end users, seem to achieve 90% penetration within one or two weeks. (I don't have a reference for that, but perhaps some of them will speak up here to confirm or correct me.)

There's a trust store comparison that might be useful [7], especially if someone wants to provide tools to convert things into something OpenSSL could consume.

[1] https://wiki.mozilla.org/CA
[2] https://www.chromium.org/Home/chromium-security/root-ca-policy
[3] https://groups.google.com/g/mozilla.dev.security.policy/c/nnLVNfqgz7g/m/tGD1qWIiCAAJ
[4] https://venturebeat.com/2019/08/21/google-and-mozilla-block-kazakhstan-root-ca-certificate-from-chrome-and-firefox/
[5] https://github.com/openssl/openssl/issues/7871#issuecomment-751521378
[6] https://github.com/openssl/openssl/issues/7871#issuecomment-751460021
[7] https://github.com/nabla-c0d3/trust_stores_observatory

**Comment by nbougalis** [comment]
I completely agree with @richsalz here, with one small quibble: maintaining a root store isn’t _nearly_ a full-time job; it’s a full time job and then some.

In my opinion, it’s simply not tenable for the OpenSSL team, which frankly has bigger and more important fish to fry, to do this.

**Comment by tiran** [comment]
Hi,

as maintainer of Python stdlib OpenSSL bindings (ssl module) I also totally agree with @richsalz. I also like to point out that vendors of Linux distributions are unlikely to switch to OpenSSL's trust store. Distributions have established procedures and tooling for root stores.

Instead of shipping a trust store, I would rather improve OpenSSL's bindings to existing trust stores on BSD, Linux, macOS, and Windows. This would improve user experience without adding the burden of maintaining a root store.

* OpenSSL cannot use the native trust store on Windows and macOS. It would be fantastic if OpenSSL could integrate with native trust store on both OS. I'm aware that an implementation would be far from trivial. For example Windows downloads and updates CA certificates on demand. OpenSSL would have to use APIs that trigger an update. This also means that certificate validation may block. On macOS some APIs are not compatible with ``fork()`` that is not immediately followed by ``execve()``.

* BSD and Linux distributions have their root store in different locations. There is currently no *Linux Standard Base* or *freedesktop.org* standard for a trust store location. Debian/Ubuntu-based Linux distributions don't install a trust store by default. This is less of an issue for software that uses the system's OpenSSL libraries. But it causes problems for software that contains a statically linked OpenSSL or alternative TLS libraries like Golang and Rust. I believe that a standard location would help. A couple of months ago, I opened [RHBZ#1895619](https://bugzilla.redhat.com/show_bug.cgi?id=1895619) to improve the situation on future CentOS, Fedora, and RHEL. My project https://github.com/tiran/distro-truststore lists trust store location and other information for most common platforms.

**Comment by kroeckx** [comment]
At least in Debian, applications that need a trust store need to either ship it itself, or Depend on it. For instance tools like wget, libcurl, apt, git and so on Depend on or Recommend ca-certificates. ca-certificates is the Mozilla trust store converted to normal .pem files, so without the trust settings. And so Debian has a script to convert Mozilla's certdata.txt to .pem files. It should actually not be that hard to modify it to also output trusted certificates.

**Comment by tiran** [comment]
> At least in Debian, applications that need a trust store need to either ship it itself, or Depend on it. For instance tools like wget, libcurl, apt, git and so on Depend on or Recommend ca-certificates

Off-topic: Debian's Python package is missing this dependency. I have reported the problem in May, but it hasn't been fixed yet. https://bugs.launchpad.net/ubuntu/+source/python3.6/+bug/1879310

> And so Debian has a script to convert Mozilla's certdata.txt to .pem files. It should actually not be that hard to modify it to also output trusted certificates.

Fedora-based distributions (CentOS, RHEL) are very similar. Fedora uses ``p11-kit-trust`` to build various trust stores from PKCS#11 providers (e.g. Mozilla's ``libnssckbi.so``), PEM files, and ``p11-kit-object-v1`` files. Fedora has been shipping trusted certificates store at ``/etc/pki/tls/certs/ca-bundle.trust.crt`` for a while. I would appreciate if distributions could agree on a common file name and path for a trusted bundle.

**Comment by kroeckx** [comment]
OpenSSL seems to use $OPENSSLDIR/cert.pem and $OPENSSLDIR/certs/ by default for cafile and capath. But it's currently unclear to me where that comes from. Maybe it can be useful that OpenSSL starts to look into 2 directories by default.

**Comment by richsalz** [comment]
No, OpenSSL should not provide a trust store; leave it to folks with a "real" root program. Closing this.
