### ISSUE TITLE
OpenSSL 1.1.i and "Can't locate FindBin.pm in @INC"

### ISSUE THREAD

**Issue by noloader** [openssl/openssl#13761]
It looks like a new Perl dependency was introduced with OpenSSL 1.1.1i. It is causing trouble.

```bash
openssl-1.1.1i$ ./Configure
Can't locate FindBin.pm in @INC (you may need to install the FindBin module) (@INC contains: /usr/local/lib64/perl5/5.32 /usr/local/share/perl5/5.32 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at ./Configure line 15.
BEGIN failed--compilation aborted at ./Configure line 15.
```

It looks like this is not an isolated incident:

* https://www.gitmemory.com/issue/sfackler/rust-openssl/1292/642923521
* https://github.com/cloudflare/wrangler/issues/761
* https://www.cnblogs.com/fah936861121/p/10562731.html
* https://blog.csdn.net/hezhanran/article/details/105972007
* ...

**Comment by kaduk** [comment]
Configure is identical in 1.1.1h and 1.1.1i.
There were changes to it between 1.1.1g and 1.1.1h, but not until line 200-something (your quoted snippet seems to be complaining about line 15).

The linked references largely do not seem to be specific to 1.1.1i, either.

FindBin has been used by OpenSSL since 1.1.0h (note .0, not .1), so I'm confused why you say "new Perl dependency [...] wiht OpenSSL 1.1.1i".


I do note that we did have a different issue with finding perl modules recently, see #13679 , but that seems to have been an issue with the context in which the library call was being made, not the import itself, so it doesn't seem to be terribly relevant to the scenario you describe.

Regardless, I think we need more information about your system and what it is supposedly a regression from, in order to do anything useful here.

**Comment by levitte** [comment]
I see that you have a locally built perl.  In the perl source, you should find `dist/FindBin/lib/FindBin.pm`, and probably `lib/FindBin.pm` when you've built perl.  If you do `find /usr/local -name FindBin.pm`, do you get its location?  If not, there's your problem.

`FindBin.pm` is a core perl module, and we do assume a full perl installation, including its core modules.  (this is the reason we require rpm based dists to install `perl-core` rather than `perl`, and Debian based installation to install `perl` and not just `perl-base`).  If you've made some kind of minimalized perl installation, then we can't help you.

**Comment by yesnik** [comment]
@noloader Thank you for creating this issue. I got the same issue at Fedora v.33 when I tried to execute this command:

```bash
[root@localhost openssl-1.1.1i]# ./config no-async shared --prefix=/usr/local/ssl --openssldir=/usr/local/ssl -Wl,-rpath,/usr/local/ssl/lib
```

Installing `perl` helped me to fix this error:

```bash
dnf install perl
```

**Comment by bendem** [comment]
Why do we need perl to build openssl again?

**Comment by t8m** [comment]
> Why do we need perl to build openssl again?

Perl was always needed.

**Comment by t8m** [comment]
I do not think this is a real bug. Most probably the perl installation on the reporter's machine was somehow botched (perhaps core perl modules were not installed or so).
Closing as there was no response from the original reporter to the @levitte question.

**Comment by droosifer** [comment]
Installing Perl worked for me. Thank you.

**Comment by PsiACE** [comment]
> ```shell
> dnf install perl
> ```

Here's a more lightweight option:

 ```shell
 dnf install perl-FindBin
```

**Comment by buahaha** [comment]
Answer to install `dnf install perl` is still valid

**Comment by ondrej-ivanko** [comment]
> > ```shell
> > dnf install perl
> > ```
> 
> Here's a more lightweight option:
> 
> ```shell
> dnf install perl-FindBin
> ```

The first part cmd worked for me, the second didnt. I was still missing some dependencies.

**Comment by whg517** [comment]
> ```shell
> dnf install perl-FindBin
> ```

zhe second lightweight way is work on rockylinux 9.3 with old openssl 1.1.0

**Comment by buahaha** [comment]
Perl is not a trouble. We need __Common Language__

**Comment by ChocolateLoverRaj** [comment]
Why wasn't perl automatically installed on Fedora if it's a dependency?

**Comment by SteveLauC** [comment]
> > ```shell
> > dnf install perl
> > ```
> 
> Here's a more lightweight option:
> 
> ```shell
> dnf install perl-FindBin
> ```

Same here, the second option does not work for me.

**Comment by piotr-dobrogost** [comment]
@PsiACE 

> Here's a more lightweight option:

Thanks for sharing as it's always good to know what's specifically required. However as `perl-FindBin` is a module in Perl it's useless without Perl so it's hardly "lightweight option", no?

**Comment by piotr-dobrogost** [comment]
@ondrej-ivanko 

> The first part cmd worked for me, the second didnt. I was still missing some dependencies.

The second one probably worked fine in the sense it fixed the error `Can't locate FindBin.pm in @INC` which is what OP asked for. The fact you needed other dependencies is irrelevant here.

**Comment by piotr-dobrogost** [comment]
> Why wasn't perl automatically installed on Fedora if it's a dependency?

Because dependencies for software installed through package manager are runtime dependencies not build dependencies. You don't need Perl to **use** OpenSSL.

**Comment by piotr-dobrogost** [comment]
> Perl is not a trouble. We need **Common Language**

We have one for a long time already and it's called Python.
It would be sensible to change Perl helper scripts for Python scripts in projects where they are used which would enhance usability by avoiding many problems with Perl as a dependency.
