### ISSUE TITLE
insufficient locking in EVP_PKEY

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#13818]
@kroeckx pointed out in https://github.com/openssl/openssl/pull/13788#discussion_r554175917:  EVP_PKEY now has an operation_cache and cache it didn't have in 1.1.1. We seem to be using at least the operation_cache without a lock, and it looks to me like it should use a lock. The cache is probably fine.

If OpenSSL wants EVP_PKEY to continue be thread-safe, and I think you do, then this probably needs to be fixed.

**Comment by davidben** [comment]
One thing we've found useful is to run our tests with TSan on CI and then write tests that fire off some threads and do things which are supposed to be thread-safe. TSan seems pretty good at catching locking errors when you do that. Tests we've found handy:

* Ref-counting logic works concurrently
* RAND_bytes works concurrently
* Run a bunch of different RSA operations concurrently (sign, verify, getters)
* Library init functions can be run concurrently
* A bunch of threads sharing an SSL_CTX, that concurrently:
  * Make some fresh handshakes
  * Resume the same session
  * Resume different sessions
* A bunch of threads concurrently hitting the session cache size limits

We don't have a dedicated EVP_PKEY one yet because thus far our EVP_PKEY hasn't had interesting state, but if yours does now, that seems worthwhile. I expect the SSL_CTX one would also cover EVP_PKEY, but a more narrow test may be more reliable.
https://boringssl.googlesource.com/boringssl/+/571c3e78bf2aa479c3abdecbd238d6b5381cc788/ssl/ssl_test.cc#4619
https://boringssl.googlesource.com/boringssl/+/571c3e78bf2aa479c3abdecbd238d6b5381cc788/crypto/rsa_extra/rsa_test.cc#1054

**Comment by kaduk** [comment]
> One thing we've found useful is to run our tests with TSan on CI and then write tests that fire off some threads and do things which are supposed to be thread-safe.

This is something I've been intending to do "eventually" for a while.  Thanks for the list of useful tests and pointers!

**Comment by mattcaswell** [comment]
I actually have a test that fires off multiple threads and does some "work" in PR #13660. It doesn't cover all the cases that @davidben lists - but it could definitely be extended to do so.
