### ISSUE TITLE
Fix typo on crypto/ocsp/v3_ocsp.c 

### ISSUE THREAD

**Issue by qualitesys** [openssl/openssl#13820]
The include declarations are erronous only in this file. Is it possible to fix it ?

Replace
    ```
    # include <stdio.h>
    ```
By
    ```
    #include <stdio.h>
    ```

Thanks

**Comment by mspncp** [comment]
With 'erroneous' you only mean that the indentation is wrong, correct?

**Comment by mspncp** [comment]
See #13822

**Comment by qualitesys** [comment]
Yes, the indentation was wrong. Thanks for the fix

**Comment by mspncp** [comment]
Side note: The wrong indentation was caused by the removal of a surrounding `#ifndef OPENSSL_NO_OCSP`, which happened in commit 6ef869d7d0a9d2e7ea7908c0b5aab1cb451e00fa. (It took me a while to find [the location](https://github.com/openssl/openssl/commit/6ef869d7d0a9d2e7ea7908c0b5aab1cb451e00fa#diff-69e9df1517f6e51180d22d7c9548fa3a8cef34b541fe0259d67bdf0d5cc5d02fL60-L61), because the file was moved in the same commit).
