### ISSUE TITLE
EVP_RAND_CTX_new documentation

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#13912]
`EVP_RAND_CTX_new` needs to note that the parent random should have locking enabled before any child is created.  A parent must be lockable if it has more than one child.  Not doing so is an error.

Refer: https://github.com/openssl/openssl/pull/13660#discussion_r560847550

**Comment by paulidale** [comment]
Having the code check that the parent can be locked and return an error if not is not correct.
E.g. a parent with a single child doesn't require locking.

**Comment by mattcaswell** [comment]
> A parent must be lockable if it has more than one child

Presumably this is only the case if the children can be accessed concurrently.

**Comment by paulidale** [comment]
> Presumably this is only the case if the children can be accessed concurrently.

Yes.

**Comment by kaduk** [comment]
Is there also a risk of concurrent access for direct output from the parent and use by the child?

**Comment by paulidale** [comment]
I'm not sure I understand the question.

**Comment by kaduk** [comment]
It may not be a sensical question, so that's understandable, and sorry for being confusing.  (I haven't gotten to look at the guts of EVP_RAND_CTX.)

But basically, we have a setup where we have a chain or tree of RNGs, with the output of one ("parent") used as input to another ("child").  At some point, certainly in the child, the output of an RNG is used directly by the application.  If the output of a parent RNG is used directly by the application, then we need to consider the case of concurrent access from the application making direct requests to the parent and the child making requests to the parent.  If we have something in place that prevents the output of the parent from being exposed directly to the application, then there's no issue -- I just don't know because I haven't had a chance to look.

**Comment by paulidale** [comment]
So long as the parent has had locking enabled, it's all good.  For the built in trio of DRBG's locking is set up properly but if you are setting up your own chains, it will be up to your application to enable it.
