### ISSUE TITLE
Support for key exchange using Curve448 (Goldilocks)

### ISSUE THREAD

**Issue by yoavnir** [openssl/openssl#1398]
I think it would be great if OpenSSL supported Curve448 as well as Curve25519.

This is a continuation of issue #309.

**Comment by richsalz** [comment]
Yes, but not in the upcoming release.

**Comment by haraldj** [comment]
Hello,

is there any progress on this issue? What is the estimated time schedule for Curve448 support?

Kind regards
Harald

**Comment by richsalz** [comment]
No progress.  No schedule.  No commitment.  Our focus for the next release, as stated in our blog, is TLS 1.3.  Other stuff will of course also happen, but I'm not aware of anyone working on this.

**Comment by haraldj** [comment]
Thanks for the information, if there are any news I guess you will
update this thread?

**Comment by TerraX-net** [comment]
Please ship this along with TLS 1.3, also browser vendors are interested in it. Maybe you set this curve in the first place of the curve list because it's very secure but has also very good performance. (["The ~224-bit security level of curve448 is a trade-off between performance and paranoia."](https://tools.ietf.org/html/rfc7748#section-6.2))

**Comment by richsalz** [comment]
Not that X25519 is a SHOULD and 448 isn't even that.  So this is not at all requires for TLS 1.3.  If you want it, a PR to implement it will help otherwise my guess (and it's only my personal view) is that this will not happen.

**Comment by TerraX-net** [comment]
I thought the "security scene" distrust the NIST curves and wanted to move to an alternative. The only thing that yet happened is a curve (x25519) which has equal security as AES-128, [which is not really a transitional solution to post quantum security](https://www.keylength.com/en/3/). The same says Ivan Ristics book "Bulletproof SSL and TLS" (No. 8 in Table 1.2 on page 17). So it was all about nothing and only a distraction to create a feeling that something would be improved in this area? DHE is deprecated, plain RSA will no longer be possible and everything relies on that old intransparent NIST curves or on that alternative very short curve -- and it's not even possible to use custom curves with web browsers etc.
The only thing that was improved this year is performance. Everything is about performance. curve448 (or other better long curves) is/are completely worthless and were a waste of time of their creators, if nobody wants to implement them. I am not a crypto developer. I don't even know someone who could make a patch for you.
The only thing I can do is to draw attention on the small things. On the other hand there are corporations like Google who wants aggressively eliminate secp521r1 on the internet: Removed from Chrome, Googlebot, Gmail - because of them, you can't even deploy a dual certificate postfix with ECDSA P-521 and RSA with ECDHE P-521. The only thing I archived here is that postfix will support multiple curves propably in version 3.2. I don't like that some people decise that my complete digital life will be exposed in 40 years a a quantum computer more easy because there were people who only thought about performance.
Please think about that aggressive process to gain move performance and to outbrake currently more secure alternatives.

**Comment by richsalz** [comment]
The team has finite resources and capabilities, and OpenSSL is doing what just about everyone else is doing as well.  You don't like that it's not a priority, well you can change that by writing code.

**Comment by richsalz** [comment]
Thanks.  Write code.

**Comment by vdukhovni** [comment]
I see no connection between DLP in F_p^n for composite n and EECDH with Curve25519.   This seems to be relevant for pairing-based crypto, but the connection to EECDH (e.g. in TLS) is rather non-obvious, and likely not there...

**Comment by snhenson** [comment]
The biggest blocker for this is a low level algorithm implementation of X448 similar to the X25519 one which is in crypto/ec/curve25519.c If someone can write or locate a usable implementation (e.g. can be put under the OpenSSL license and has a similar API) then adding TLS support is relatively straight forward.

**Comment by bitwiseshiftleft** [comment]
@snhenson Is the MIT license acceptable?  You can pull in X448 from https://sourceforge.net/p/ed448goldilocks/code/ci/x448/tree/, or that and many other functions (with greater performance and arch-specific code) from the master branch.

**Comment by kroeckx** [comment]
We require a CLA (Contributer License Agreement) from the author.

**Comment by TerraX-net** [comment]
@bitwiseshiftleft Would it be possible that you made that CLA? 
https://www.openssl.org/policies/cla.html
( https://www.openssl.org/policies/openssl_icla.pdf )

**Comment by bitwiseshiftleft** [comment]
Probably, but it’ll take time.  It’s going through Rambus legal.  I’m also on vacation this week, which is delaying things.

**Comment by bitwiseshiftleft** [comment]
OK, it's almost through legal (but need CCLA not ICLA).  Should I just sign the CLA saying that the repo is contributed as of the current version (0.9.3 or whatever) and then you can pull whatever files you need?

**Comment by kaduk** [comment]
The wording is perhaps not as clear as it could be, but CCLA is in addition to ICLA, not in replacement of.

**Comment by richsalz** [comment]
I think the wording, https://www.openssl.org/policies/cla.html is now clear.  If you have suggestions on how to improve it, we'd love to know.

I don't know if we need/want the Goldilocks code, @snhenson is best equipped to comment.  But there is definitely no rush :)

**Comment by mattcaswell** [comment]
> I don't know if we need/want the Goldilocks code, @snhenson is best equipped to comment. But there is definitely no rush :)

I think we definitely *do* want it!!

**Comment by kroeckx** [comment]
@bitwiseshiftleft: Any update on this?

**Comment by snhenson** [comment]
As far as I'm concerned if/when we have suitable low level algorithm code I'll work on adding the glue for EVP and TLS. It should hopefully be very similar to the X25519/Ed25519 code.

**Comment by bitwiseshiftleft** [comment]
Sorry to delay.  I lost track of who between me and Rambus legal was responsible for the next stage of the procedure.  Looks like it was me all along.  I've sent in the contribution to OpenSSL legal, so once they check that I did it right, it should be fine.

**Comment by maqp** [comment]
Great to see this moving forward. @bitwiseshiftleft Any word from the legal yet?

**Comment by mattcaswell** [comment]
@maqp, all legal issues have been resolved. I am working on a patch at the moment.

**Comment by mattcaswell** [comment]
See #4829 for my patch so far.

**Comment by r-love** [comment]
Should this be working for TLS at HEAD?

**Comment by mattcaswell** [comment]
No. In master we have internal support for the curve448 primitives. PR #5419 is seeking to introduce support for X448 at the EVP layer. As noted in that PR once it has been pushed, another PR is required to add TLS support.

**Comment by mattcaswell** [comment]
We now have TLS support for this in master. Closing.
