### ISSUE TITLE
OSS-Fuzz issue #30037: Out-of-bounds read in kdf_sshkdf_set_ctx_params

### ISSUE THREAD

**Issue by guidovranken** [openssl/openssl#14027]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=30037

I pass the `OSSL_KDF_PARAM_SSHKDF_TYPE` parameter as a buffer of size 1: https://github.com/guidovranken/cryptofuzz/blob/f3bebc46e83f4a411cce95f9ca1cb5caadf146c9/modules/openssl/module.cpp#L2809-L2810

The buffer is not NULL-terminated because I'm specifying the size (1).

Unless I'm misunderstanding the documentation, the string does not have to be NULL-terminated if the size is specified:

```
OSSL_PARAM_construct_utf8_string() is a function that constructs a UTF8 string OSSL_PARAM structure.
A parameter with name key, storage buf and size bsize is created.
If bsize is zero, the string length is determined using strlen(3) + 1 for the null termination byte.
Generally pass zero for bsize instead of calling strlen(3) yourself.
```

(It seems a bit redundant to me to 1) specify the size and 2) have NULL-termination)

But `kdf_sshkdf_set_ctx_params` then treats it as a NULL-terminated string: https://github.com/openssl/openssl/blob/e947a0642db111bb34547b5f7d48e13163492ca5/providers/implementations/kdfs/sshkdf.c#L162

leading to out-of-bounds read.

**Comment by levitte** [comment]
You're right that the spec of OSSL_PARAM only says that *data_size* must indicate the number of bytes passed with *data*.
A C string is by it's nature strlen()+1 because of the NUL byte, but there's nothing in the spec that obligates that.  However, since we've been dealing with C strings, that's where we got.

But you're right that the OSSL_PARAM spec does allow a single byte UTF8 STRING
(oh boy, there are a lot of places where we assume NUL termination and don't even look at *data_size*...)

**Comment by levitte** [comment]
We might have to decide if we want mandatory NUL termination for UTF8 strings...  @openssl/otc, opinions?

**Comment by richsalz** [comment]
Single-byte UTF8 string is tricky, since it will likely get confused with 8bit codeset; I suggest NUL termination.

**Comment by levitte** [comment]
In this case, the accepted letters are "A" through "F". I challenge you to find a different character code than single byte 65 through 70 for them.

**Comment by paulidale** [comment]
IBM has such an encoding.

**Comment by levitte** [comment]
> IBM has such an encoding.

Really?  I mean, apart from EBCDIC...  After all, it's called a *UTF8* string, that comes with expectations.

But the issue here isn't about encoding, discussing that is actually a bit of derailing.
The base issue here is, do we accept that UTF8_STRING may not be NUL (not NULL) terminated, and therefore the *data_size* becomes significant, or do we want to make NUL termination mandatory?  That has nothing to do with encoding, and everything about finding the size of the string.

(side note: it's perfectly possible to support both a size and NUL termination...  all you have to do is look at `p->data[p->data_size - 1]` and count one less if that byte happens to be `'\0'`)

**Comment by richsalz** [comment]
I'm sorry, I wasn't clear.  In this case, sure, a single byte works.  But UTF8 chars can be multibyte even tho it represents one character. And various encodings also use the high bit. I think that's likely to cause problems.  Just nul-terminate everything, if only for compatibility with C strings.

**Comment by levitte** [comment]
UTF8 multibyte is *inconsequential*, it will be the same problem whether we determine the string length by looking for the NUL byte or rely on the passed size.

**Comment by paulidale** [comment]
From a user perspective, it is consequential: a string containing a single character might not be one byte long.

**Comment by levitte** [comment]
We're running in circles

**Comment by paulidale** [comment]
Yep, I suggest we mandate both a '\0' terminator and the length.  The helper functions will calculate the length for you.

The only alternative that seems reasonable to me is to not specify the length and for the receiver to compute it.

**Comment by levitte** [comment]
> The only alternative that seems reasonable to me is to not specify the length and for the receiver to compute it.

That would make OSSL_PARAM inconsistent.  *data_size* is meant to *always* have the size of the contents that *data* points at (indirectly for `_PTR` data types).

**Comment by levitte** [comment]
Meanwhile, #14035 is one possible fix for this issue

**Comment by t8m** [comment]
Should the callee be responsible to check for consistency? Or can it just depend on the caller to always DTRT and do both NUL termination and set the size right (including the NUL)?

In case the NUL is optional we would have to fix all the callees to never depend on the NUL. That makes the code much less efficient.

Another option would be to make the one character case special but otherwise make the NUL termination mandatory.

**Comment by richsalz** [comment]
I guess you still don't understand my point.  Making the NUL not required is more likely to be error-prone.  People will mix things up. Just nul-terminate.

**Comment by t8m** [comment]
Should the callees always verify that the NUL is there?

**Comment by richsalz** [comment]
>Should the callees always verify that the NUL is there?

Maybe in an NDEBUG build.

C strings are nul-terminated.  Stop.

**Comment by guidovranken** [comment]
I've fixed this in my fuzzer.
