### ISSUE TITLE
Excess import/export operations

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#14159]
#14126 notes that import/export between key managers is happening even when the key managers are the same.  This should be addressed.

This is most noticeable when running with the no-cached-fetch option but it will also occur if the fetch cache is flushed.

**Comment by levitte** [comment]
I did have a thought about methods being able to show "kinship" with each other, but that turned out to be a complex idea when I talked about it, so we ditched it.

I fail to see an operation cache flush as an issue. When the cache is flushed, there's nothing left to compare with. Or are you thinking of selective/partial flushing? Is that something for 3.0?

**Comment by paulidale** [comment]
_**fetch**_ cache.  If that is flushed, the next fetch will return a different object and the import/export issues appear.

**Comment by levitte** [comment]
We should probably rethink what we consider to be "the same", in terms of methods (like EVP_KEYMGMT).  It's true that we may find ourselves having multiple copies of the same method at times, and our current comparison of direct EVP_KEYMGMT pointers becomes flawed in that situation.

So, another thought we might want to consider is trusting that dlopen() and similar will try very hard not to load a .so / .dll into memory more than once, meaning that its code sections can be seen as fairly unique and constant.  So, instead of comparing `keymgmt1` against `keymgmt2`, we might want to consider comparing `keymgmt1->free` against `keymgmt2->free`.

In current code, it could look as simple as this:

``` diff
diff --git a/crypto/evp/keymgmt_lib.c b/crypto/evp/keymgmt_lib.c
index 0c643b3b49..2730caf10b 100644
--- a/crypto/evp/keymgmt_lib.c
+++ b/crypto/evp/keymgmt_lib.c
@@ -217,7 +217,7 @@ size_t evp_keymgmt_util_find_operation_cache_index(EVP_PKEY *pk,
     size_t i, end = OSSL_NELEM(pk->operation_cache);
 
     for (i = 0; i < end && pk->operation_cache[i].keymgmt != NULL; i++) {
-        if (keymgmt == pk->operation_cache[i].keymgmt)
+        if (keymgmt->free == pk->operation_cache[i].keymgmt->free)
             break;
     }
 
```

**Comment by levitte** [comment]
(I picked `keymgmt->free`, because it's singularly required to be present by `keymgmt_from_dispatch()`)

**Comment by mattcaswell** [comment]
This seems dubious to me. It is entirely possible that different key managers have a common free function. In fact we already have this in our code:

https://github.com/openssl/openssl/blob/13888e797c5a3193e91d71e5f5a196a2d68d266f/providers/implementations/keymgmt/ecx_kmgmt.c#L749-L777

**Comment by paulidale** [comment]
Checking all of the function pointers might work better, what we really want is some kind of UID.

**Comment by levitte** [comment]
We could have something else that must be a unique address...  could be a function that does nothing, but just sits for the sake of uniqueness.

What I'd like to avoid is to push the whole UID concept on provider authors other than that.  We've already had fantasy discussions on UID coordination between providers that consider each other "kin"...  let's avoid that rabbit hole for now, yeah?

**Comment by mattcaswell** [comment]
We already have a `name_id`...won't the combination of `keymgmt->name_id` and `keymgmt->prov` be sufficient to check equality?

**Comment by paulidale** [comment]
We already allocate a numeric ID for each thing a provider presents.  Couldn't that, along with the library context, act as the UUID?

**Comment by mattcaswell** [comment]
> We already allocate a numeric ID for each thing a provider presents. Couldn't that, along with the library context, act as the UUID?

Isn't that what I just said :-)....except I said name_id and prov. Technically a name_id is only unique within the scope of a libctx. But since we will also need to check the prov and the prov ptr will always be unique even for the same provider in different libctxs, it is sufficient just to check the name_id and prov.

**Comment by paulidale** [comment]
Yeah it is.  I should refresh and read after an interruption :)

**Comment by levitte** [comment]
Yes!  I'm on board for the name_id + prov check.
