### ISSUE TITLE
Order of algorithms search

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#14198]
In 3.0 we can have an implementation provided by on of a native providers, by engine and by the 3rd-party provider at the same time. 

We should establish a unified order of selecting the implementation and use it consistently in all the places we directly  look for a presence of the algorithm.

**Comment by paulidale** [comment]
Within the providers, there order is deliberately undefined.  Property queries should be used to pick a specific provider.

The question of engine vs provider is interesting.

The concept of priority of algorithms is something for post 3.0.

**Comment by beldmit** [comment]
Current code works this way:
https://github.com/openssl/openssl/blob/62829f9f26bf248f29be9604870bbe46f946927a/crypto/cms/cms_lib.c#L411-L424

https://github.com/openssl/openssl/blob/62829f9f26bf248f29be9604870bbe46f946927a/apps/speed.c#L1498-L1512

@levitte says the order should be reverted (see https://github.com/openssl/openssl/pull/14182#issuecomment-779046452).

I anyway think we should get an unified code (helper functions) to ensure the order and avoid code duplication.

**Comment by beldmit** [comment]
> Within the providers, there order is deliberately undefined. Property queries should be used to pick a specific provider.

Can we explicitly request "Use RSA from the provider XXX"? If yes, it solves the problem.

**Comment by paulidale** [comment]
Passing `"provider=XXX"` as the property query will force the source.

**Comment by levitte** [comment]
> Can we explicitly request "Use RSA from the provider XXX"? If yes, it solves the problem.

You can fetch a provider side algorithm based on properties.  Exactly what properties are available to query depends on the provider.  We *could* have apps choose to only fetch (i.e. not use functions like `EVP_get_digestbyname()` at all) if there is a property query string, even an empty one.

**Comment by levitte** [comment]
Looking more closely at this issue, I'm having misgivings about what the proper order is.

When looking at `apps/dgst.c`, I was previously thinking that since an engine must be explicitly loaded (via `-engine`), that signals an explicit desire to use that engine's implementations, so it would be natural to use `EVP_get_digestbyname()` first and `EVP_MD_fetch()` as a fallback.

However, if both providers and engines are loaded due to configuration in the config file, there's no indication from the user what's preferred, making the order harder to determine from user input.

So, if I can have a raise of hands; if there's no way to say what the user prefers, do we:

-   Try fetching first, then fall back on legacy methods?, or
-   Try legacy methods first, then fall back on fetching?

It might be a good idea to have a look at the code for functions like `EVP_DigestInit_ex()` to see what priorities have been made there and if that can give an indication of what we should do.

**Comment by t8m** [comment]
My preference would be to fetch first and only if not found, fallback on legacy. And yes, I understand this will break some legacy use-cases as basically you won't be able to override provider implementation with engine implementation. But IMO this should be acceptable. Another possibility would be to look if we have any engine set up (by option or configuration) and in that case prefer the legacy, but that makes the behavior much less dependable.

**Comment by paulidale** [comment]
I'd favour fetch then fallback too.

However, should we honour an engine based default (e.g. via `ENGINE_set_default_digests`)?  I think we ought to.  Which would be default -> fetch -> fallback.

**Comment by levitte** [comment]
> default -> fetch -> fallback.

Considering that "default" from ENGINEs is baked into "fallback", oh boy there's some dissection to do.  We might want to consider a libcrypto function that does this for us, uniformly...  that or allow EVP_XXX_fetch() to return legacy algorithms, but only if libctx and propq are NULL...  [duck, run]

**Comment by t8m** [comment]
> > default -> fetch -> fallback.
> 
> Considering that "default" from ENGINEs is baked into "fallback", oh boy there's some dissection to do. We might want to consider a libcrypto function that does this for us, uniformly... that or allow EVP_XXX_fetch() to return legacy algorithms, but only if libctx and propq are NULL... [duck, run]

Well... with the change to allow EVP_xxx_free() on the non-fetched algorithms it would actually be possible. :rofl:

**Comment by levitte** [comment]
Yup.

**Comment by beldmit** [comment]
Oh, and we get an universal API fetch - hash/cipher/etc - free? It's the API of my dream!

**Comment by t-j-h** [comment]
Whatever we do, the order should be deterministic and defined.

I'm much less concerned about where Engine fits into things as Engine is legacy and is going away or if we have different orders of processing compared to previous handling for engines in order to get something considered "logical" with providers. 

We should be able to specify which algorithms come from which providers using configuration - that is where we need to end up - and that is a journey. We should not be thinking "applications can do this themselves" as although they can, the concept of providers is to allow the end user of an application to be able to control which providers are used for which algorithms - and that means controlling things in configuration and not by having applications all having to add mechanisms to achieve that explicitly.

In terms of order of processing, fetch from providers then fall back to legacy and engines hanging off legacy seems to me to be the right approach for now. I do not thing we should be adjusting where engine kicks in at all. 

Having EVP fetch being able to return any algorithm implementation whether it is provider based, or legacy (and hence engine) does not seem unreasonable. And I don't think we would need to have that limited to libctx==NULL or propq==NULL either.

It would also ease things significantly for contexts where you want to add an implementation for a subset of things and not have to implement everything (as per other discussions where it is "everything" or "nothing" per publickey type). 

We should just be able to view things as "implementations" and not have applications having to make a distinction between what sort of implementation of something it is (provider, legacy, engine).

**Comment by paulidale** [comment]
> It would also ease things significantly for contexts where you want to add an implementation for a subset of things and not have to implement everything (as per other discussions where it is "everything" or "nothing" per publickey type).

It's off topic here but EC  has some issues in this regards :(

**Comment by levitte** [comment]
Question answered, we all seem to agree to fetch first, and have `EVP_get_{cipher,digest}xxx` as a fallback.  Therefore closed

**Comment by t8m** [comment]
Reopening to fix after #14898 is merged.
