### ISSUE TITLE
Regression in d2i_PrivateKey_bio for GOST engine keys

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#14263]
The failing test basically looks like

https://github.com/gost-engine/engine/blob/fde4a66ddaaf97ee103d02b400fb7f1b79320ac9/test_sign.c#L151-L155

The d2i_PrivateKey_bio does not produce a valid result

**Comment by Sadique11** [comment]
The failing test basically looks like

https://et20slam.net/crichd/

**Comment by beldmit** [comment]
The regression was introduced after alpha12

**Comment by levitte** [comment]
Ah yup, `i2d_PrivateKey_ex()` now *only* tries using OSSL_DECODER, and therefore never goes the legacy route.

@slontis?

**Comment by beldmit** [comment]
BTW, may be it makes sense including the basic tests for the GOST engine into the CI matrix?

**Comment by levitte** [comment]
> BTW, may be it makes sense including the basic tests for the GOST engine into the CI matrix?

Yes, truly.  This actually goes for the lot of the external tests, we currently have *none* of them.  Please raise an issue

**Comment by levitte** [comment]
The issue here revolves around `d2i_AutoPrivateKey_ex()`, and something to be noted is that when it couldn't figure out any type-specific DER, it fell back on trying to unpack it as a PKCS#8 structure, and call `EVP_PKCS82PKEY_ex()` on it, which I believe still handles legacy / engine keys correctly.

So it seems like that fallback needs to be re-instated, and that should resolve the matter.

(one might also ponder having a fallback decoder implementation in libcrypto, which does some magic to handle legacy keys, but that's a bit more complex)

**Comment by beldmit** [comment]
#14265

**Comment by slontis** [comment]
Not sure why this PR mentions i2d - it is d2i that got modified recently.
