### ISSUE TITLE
Provider side encoders and decoders need to stop using EVP_PKEY

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#14306]
The encoders and decoders were implemented with a use of EVP_PKEY, where they counted on the functions they used to only handle legacy EVP_PKEYs, just to extract the lower level keys with EVP_PKEY_get1_XXX().

As more and more functions that handle EVP_PKEYs are expanded to handle a provider side internal key, the encoders and decoders find themselves in an endless recursion, which has been parried by making special internal functions that stick with legacy only EVP_PKEYs.  This situation is not future proof.

The encoders and decoders therefore need to be refactored to use the diverse lower level functionality, thereby handling RSA, DSA, EC_KEY etc pointers directly rather than going via EVP_PKEY.

There's some early refactoring work in #13994 (which was abandoned in favor of #14281).

-----

Related to #14302 and #14304.

**Comment by h-vetinari** [comment]
I was wondering about this... Over several topics, the message that has emerged consistently was always: "just use EVP". Now, if someone wants to turn their code (assuming they've followed that recommendation) into a provider, they'll have to rewrite it with lower-level APIs?

Not that I understand the design very well, but are there really no other ways to break this circularity other than asking provider authors to use different APIs?

**Comment by t8m** [comment]
You have to understand that internally our providers must use _something_ to implement the actual functionality. But! They cannot use high level libcrypto API calls because this is when the circularity happens.
And actually when third party providers are implemented they should not use high level API OpenSSL calls either as that can lead to exactly the same circularity. Of course they might avoid it by using a separate libctx and somehow ensuring their provider is not loaded into that libctx but that requires extra care. But in OpenSSL providers we do not have this option.

**Comment by levitte** [comment]
Providers know about their own key structures, that's the basic principle.  EVP has no clue what the internal structures are for the keys.
So, *our* providers should know about the structure that *we* have support for.  While types like `RSA`, `DSA`, `DH` and `EC_KEY` are removed from public view, they are very much the foundation upon which *our* providers rest.  *Other* providers are assumed to have their own structures for whatever key types they choose to support.

**Comment by h-vetinari** [comment]
OK, thanks for the explanation

**Comment by mattcaswell** [comment]
PR #14314 fixes this so closing.
