### ISSUE TITLE
Resolve or remove TODO 3.0 in providers/.../gmac_prov.c

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#14359]
There is a following TODO in function gmac_final():
```
    if (!EVP_EncryptFinal_ex(macctx->ctx, out, &hlen))
        return 0;
    
    /* TODO(3.0) Use params */
    hlen = gmac_size();
    if (!EVP_CIPHER_CTX_ctrl(macctx->ctx, EVP_CTRL_AEAD_GET_TAG,
                             hlen, out))
        return 0;

    *outl = hlen;
    return 1;
```

**Comment by paulidale** [comment]
I'd suggest remove the comment.  It makes no sense to me.

**Comment by levitte** [comment]
That functions has a *lot* if dubious things:

- `hlen` receives a value from `EVP_EncryptFinal_ex()`, but that value is dropped in favor of `gmac_size()`...
- The ctrl call uses `hlen` as the size of `out`, rather than `outsize`
- There are *no* checks between those sizes, and especially, no check that any other size was less or equal to `outsize`.
