### ISSUE TITLE
TLS extension about TLSEXT_TYPE_renegotiate

### ISSUE THREAD

**Issue by ayang05** [openssl/openssl#14439]
using the TLS extension TLSEXT_TYPE_renegotiate, client don't transmit the extended fields for renegotiation by default ,It does not comply with the ANSSI. If this extended field is added to the client, what effect will it have?

**Comment by kaduk** [comment]
I don't think I understand the question being asked very well.
I note that the normal operation mode for the RFC 5746 renegotiation indication extension is that in an initial (full) handshake, the client includes the extension with empty body, to indicate support for the mechanism (it can alternately use the `TLS_EMPTY_RENEGOTIATION_INFO_SCSV` signaling cipher suite value instead of the empty extension).  Only in a renegotiation handshake are the `client_verify_data` transmitted in the extension body.

If you think that OpenSSL is not compliant with the relevant standard (I assume you refer to RFC 5746), please be more specific about what behavior you think is incorrect.
