### ISSUE TITLE
RFC 7919 FFDHE groups are now treated as DHX instead of DH in an EVP_PKEY

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#14444]
The RFC7919 FFDHE groups are all safe primes. That RFC specifies the groups
in terms of p, q and g (where q = (p-1)/2, because they are safe). However, in
1.1.1, calling the function DH_new_by_nid() and specifying the nid for one of
these primes got you back a DH object with only p and g defined. The q value
was always NULL. In 3.0 we also provide the q value.

This makes a difference when we "assign" such a DH object to an EVP_PKEY. During
the assign we check whether the q value is present or not. If not the key type
for the EVP_PKEY is EVP_PKEY_DH. If it is then the key type is EVP_PKEY_DHX.

This means that creating an RFC7919 DH object in 3.0 and assigning it to an
EVP_PKEY results in an EVP_PKEY with a different type to what you get with 1.1.1

The same applies even if you construct a DH object for these groups "manually",
i.e. by creating the DH object by DH_new(), and setting only the p and g values
via DH_set0_pqg(). In this case the DH_set0_pqg() is sufficiently clever that it
recognises that you have set a named group and automatically fills in the q
value.

This is a change in behaviour from 3.0. Probably this is ok - but if so it at least deserves a CHANGES entry (I couldn't find one for this).

**Comment by t8m** [comment]
I am not quite sure this is OK. IMO we should not use the DHX type for parameters with safe prime p. @slontis ?

**Comment by slontis** [comment]
1.1.1 was not doing compliant generation/validation that requires the use of the 'q' value.

DH is a real pain. Safe primes have a q value that is known.
Part of the reason for moving to using named groups is that the q value is known. 
Using DHX because there is a 'q' sounds like the real issue..

So we can either
(1) Not set the 'q' and then in places where we actually need the q value retrieve the q if it has a nid. (e..g ossl_ffc_validate_public_key(), generate_key() - there may be other places.)
(2) Be a bit smarter when we do the q check to determine if it is a DHX key? (Where is that check??)
(3) Document what it does now.

q is required for both validation and

**Comment by beldmit** [comment]
@slontis, your previous comment looks like unfinished

**Comment by t8m** [comment]
IMO 3 is wrong. The q value is needed only for full validation of the key. For generation, in case of the known safe prime groups, the only relevant thing is the q size.

**Comment by mattcaswell** [comment]
> (2) Be a bit smarter when we do the q check to determine if it is a DHX key? (Where is that check??)

It's here:
https://github.com/openssl/openssl/blob/a2c911c2d069b5c6f9e2a8f20764de83a82b1c99/crypto/evp/p_lib.c#L859-L867

We could somehow change that check to determine whether a safe prime is being used and only assign DHX if it isn't. Although that is also a change in behaviour (previously in 1.1.1 any DH group with a q present will be treated as DHX).

> I am not quite sure this is OK. IMO we should not use the DHX type for parameters with safe prime p.

Why not? This seems ok to me.

**Comment by t8m** [comment]
> Why not? This seems ok to me.

Because the DHX type was meant for the X9.42 which does not use safe prime p and small g but instead generate the p, q, g via the algorithm that DSA uses as well.

So the q value for the safe prime groups is really misleading.

This is important for group validation because for the DH type group the validation should be to just test that the p is a safe prime but for the DHX type you need to have the seed and do the generation computation with the known seed.

In practice of course testing that p is safe prime would be too expensive to perform so we have those known safe prime groups that we can use & simply match when validating.

**Comment by mattcaswell** [comment]
> Because the DHX type was meant for the X9.42 which does not use safe prime p and small g but instead generate the p, q, g via the algorithm that DSA uses as well.

As I understand it PKCS 3 doesn't specify safe primes either. It's just that OpenSSL always has used safe primes for PKCS3 DH to prevent small sub-group attacks. But there's nothing stopping you from using it with non safe primes and in fact libssl does not validate that parameters received are safe primes. IIUC, this is safe because the DH keys are ephemeral, so a small sub-group attack can't be applied.

> In practice of course testing that p is safe prime would be too expensive to perform so we have those known safe prime groups that we can use & simply match when validating.

But historically it was common place to receive arbitrary DH params in SSL/TLS without any knowledge of whether they were safe primes or not.

**Comment by t8m** [comment]
> As I understand it PKCS 3 doesn't specify safe primes either. It's just that OpenSSL always has used safe primes for PKCS3 DH to prevent small sub-group attacks.

But that is not an argument to treat the safe prime groups as DHX keys. Actually the other way around - this is an argument that DHX keys can be treated as DH keys and it is less bad to do that rather than to treat a safe prime key as DHX key which is supposed to be generated and validated differently.

**Comment by slontis** [comment]
EVP_PKEY_set1_DH() has been modified so that by default..

named safe prime groups and the safe prime generator use DH.
fips186-X and RFC5114 named groups use DHX.

Named groups can be assigned to either DH or DHX keys.
fips186-X is restricted for use by DHX keys.
The safe prime generator is restricted for use by DH keys.
