### ISSUE TITLE
Handshake records larger than max_fragment_length in DTLS 1.2?

### ISSUE THREAD

**Issue by tazle** [openssl/openssl#14495]
We are trying to get a DTLS client to restrict the network packets sent by either end of the connection because the network in question drops with UDP packets over 1400 bytes or so. The server-side also talks to clients on other networks that don't have this issue, so we'd like to make the choice on the client.

To accomplish this, we attempted to `SSL_CTX_set_tlsext_max_fragment_length(ctx, TLSEXT_max_fragment_length_1024);`  to force both ends to send at most 1024 byte records, which should keep the packet size under control. This succeeded in forcing both sides to send smaller UDP packets, so now the DTLS handshake no longer fails because some packets get dropped.

However, it still doesn't succeed. Instead we are now seeing Record Overflow alert from the client.

After reading [RFC 6066 section 4](https://tools.ietf.org/html/rfc6066#section-4), it's not quite clear to us if this should happen during the handshake. The specification certainly talks about restricted buffer size as one of the motivations for using the extension, but it also talks about fragmentation support in handshake, which made us think that handshake records larger than max_fragment_length would not be an issue.

Is this a bug in OpenSSL, or are we trying to make max_fragment_length do something it wasn't supposed to do?

**Comment by mattcaswell** [comment]
This sounds like a bug.

Are client and server both using OpenSSL?

> Instead we are now seeing Record Overflow alert from the client.

Do you mean a record overflow alert is sent by the client, or a record overflow is received by the client? If it is sent by the client do you have any OpenSSL error log information detailing the problem further? Or if it is sent by the server do you have any error information on the server detailing to problem?

Which OpenSSL version are you using?

Can you get a packet capture of a failing connection?

**Comment by tazle** [comment]
> Are client and server both using OpenSSL?

Only the client is OpenSSL. The server is, I believe, Scandium.

> 
> > Instead we are now seeing Record Overflow alert from the client.
> 
> Do you mean a record overflow alert is sent by the client, or a record overflow is received by the client? If it is sent by the client do you have any OpenSSL error log information detailing the problem further? 

Record overflow alert is sent by the client. Here is a screenshot from Wireshark showing the client receiving fragmented records from the server and responding with record overflow alert:

![dtls-fragmentation](https://user-images.githubusercontent.com/681203/110777884-52aac680-826a-11eb-90dd-53262b158c45.png)

> Which OpenSSL version are you using?

We have tested with 1.1.1g and 1.1.1h.

> Can you get a packet capture of a failing connection?

We should be able to make a packet capture available later, or perhaps an executable test.

**Comment by tazle** [comment]
I can't seem to attach pcap files here.

**Comment by mattcaswell** [comment]
zip file?

**Comment by mattcaswell** [comment]
Also, it would be very useful to see the error message generated by the client when it sends the alert.

**Comment by tazle** [comment]
I believe this is the error message (using OpenSSL 1.1.1h in case it matters): "error:14101092:SSL routines:dtls1_process_record:data length too long"

Here is the zipped pcap (I believe this test used OpenSSL 1.1.1g, in case it matters): 
[dump_dtls_data_length_too_long.zip](https://github.com/openssl/openssl/files/6122794/dump_dtls_data_length_too_long.zip)

**Comment by mattcaswell** [comment]
This appears to be due to a bug in the server side implementation - potentially because of a misunderstanding about the RFC that specifies this behaviour.

There are in fact 2 different contexts in which the word "fragment" is used in TLS/DTLS - which is quite unfortunate. In TLS it is used in RFC 5246 (TLSv1.2) in section 6.2.1:

````
6.2.1.  Fragmentation

   The record layer fragments information blocks into TLSPlaintext
   records carrying data in chunks of 2^14 bytes or less.  Client
   message boundaries are not preserved in the record layer (i.e.,
   multiple client messages of the same ContentType MAY be coalesced
   into a single TLSPlaintext record, or a single message MAY be
   fragmented across several records).

      struct {
          uint8 major;
          uint8 minor;
      } ProtocolVersion;

      enum {
          change_cipher_spec(20), alert(21), handshake(22),
          application_data(23), (255)
      } ContentType;

      struct {
          ContentType type;
          ProtocolVersion version;
          uint16 length;
          opaque fragment[TLSPlaintext.length];
      } TLSPlaintext;
````
So, in this context, it is talking about fragmenting information from some higher layer across records. A TLS record consists of its type, protocol version, fragment length and the fragment data.

DTLS 1.2 is specified in RFC 6347 - and basically refers to the TLS RFC to say "its like that, but with these differences". Unfortunately the DTLS RFC also talks about fragments in an entirely different context:

````
4.2.3.  Handshake Message Fragmentation and Reassembly

   As noted in Section 4.1.1, each DTLS message MUST fit within a single
   transport layer datagram.  However, handshake messages are
   potentially bigger than the maximum record size.  Therefore, DTLS
   provides a mechanism for fragmenting a handshake message over a
   number of records, each of which can be transmitted separately, thus
   avoiding IP fragmentation.

   When transmitting the handshake message, the sender divides the
   message into a series of N contiguous data ranges.  These ranges MUST
   NOT be larger than the maximum handshake fragment size and MUST
   jointly contain the entire handshake message.  The ranges SHOULD NOT
   overlap.  The sender then creates N handshake messages, all with the
   same message_seq value as the original handshake message.  Each new
   message is labeled with the fragment_offset (the number of bytes
   contained in previous fragments) and the fragment_length (the length
   of this fragment).  The length field in all messages is the same as
   the length field of the original message.  An unfragmented message is
   a degenerate case with fragment_offset=0 and fragment_length=length.
````

In this context we are talking about handshake messages *only* (so not application data) and how those handshake messages are broken up. Those handshake messages are ultimately then sent in records.

The max_fragment_length extension is specified in RFC 6066. It is intended for use in both TLS and DTLS, and its use of the word fragment is very clearly related to the first of the above contexts, i.e. record layer fragments:

````
   The negotiated length limits the input that the record layer may
   process without fragmentation (that is, the maximum value of
   TLSPlaintext.length; see [RFC5246], Section 6.2.1). 
````

In the pcap file that you sent me I can see that both client and server agree on a max fragment length of 1024. I then see that the server has sent the following record:

![DTLSCapture](https://user-images.githubusercontent.com/7422273/110788641-c8ad2e80-8266-11eb-9300-e8308fe51769.png)

From this it is clear to see that the *handshake* fragment length is 1024 but the *record* fragment length is 1036. Since the max_fragment_length applies to the record fragment length this is too long and hence the client fails with the record overflow alert.

Probably your next step is to raise this with Scandium.

**Comment by tazle** [comment]
Thank you for the thorough analysis!
