### ISSUE TITLE
OpenSSL 1.1.1j - AES_cbc_encrypt cannot decrypt memory overlap

### ISSUE THREAD

**Issue by renwang0946** [openssl/openssl#14490]
AES_cbc_encrypt in OpenSSL 1.1.1j (Windows default compilation option) can't decrypt memory overlap? For example, AES_ cbc_ encrypt(pSrcData+16, pSrcData, nSrcSize-16, &aes, iv, AES_DECRYPT), so I don't have to apply for more than temporary memory. The previous version of OpenSSL 1.0.2h had no problems.

**Comment by paulidale** [comment]
Where is it documented that this is possible?

How is this possible without allocating temporary memory?  (the answer is that it isn't).

In order to encrypt, CBC requires the ciphertext of the previous block.  When the destination overlaps but lags the source, the encryption would be best done backwards but CBC mode does not permit this.  The worst case would be having to maintain a cache of all bar one block.
