### ISSUE TITLE
RSA signature is invalid if Parameters omitted for DigestInfo::digestAlgorithm.parameters

### ISSUE THREAD

**Issue by microshine** [openssl/openssl#14539]
I've got two RSA PKCS1 v1.5 signatures. BouncyCastle verifies them successfully. But OpenSSL returns false for a signature where algorithm identifier parameters omitted.

https://github.com/openssl/openssl/blob/8020d79b4033400d0ef659a361c05b6902944042/crypto/rsa/rsa_sign.c#L425-L429
As I can see from the source code OpenSSL encodes computed data digest and compares it with decrypted signature. That's why encoded data has `Null` parameters, but decrypted doesn't.

Decripted signature: `MDEwDQYJYIZIAWUDBAIBBQAEIBNRk05odUAkFkvUI9130m39UwewnTYlDalQ7Tz5duXF`
```
SEQUENCE (2 elem)
  SEQUENCE (1 elem)
    OBJECT IDENTIFIER 2.16.840.1.101.3.4.2.1 sha-256 (NIST Algorithm)
  OCTET STRING (32 byte) 1351934E68754024164BD423DD77D26DFD5307B09D36250DA950ED3CF976E5C5
```

Decripted signature: `MDEwDQYJYIZIAWUDBAIBBQAEIBNRk05odUAkFkvUI9130m39UwewnTYlDalQ7Tz5duXF`
```
SEQUENCE (2 elem)
  SEQUENCE (2 elem)
    OBJECT IDENTIFIER 2.16.840.1.101.3.4.2.1 sha-256 (NIST Algorithm)
    NULL
  OCTET STRING (32 byte) 1351934E68754024164BD423DD77D26DFD5307B09D36250DA950ED3CF976E5C5
```

### Incoming data for testing
**Data(HEX):** `4d65737361676520746f207369676e`
**Public Key:**
```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnA9e7rbX5VnoRSu/PXkW
cHitjac5Vv9sO0BcJqDGG13RLQXeiaLlyOYr88qzJ1hCOOifal++zA5AsU3dL7b0
Scb4Q1JdHXK0crgDJNTxEZOaKDWaIAJwNMuvPYmIX3tSG/nIrOlNiv2zut3NiNfv
A//l5kwzQDYhpDkdFSa7CK4Pp/p3+Wv2dkJiyxJDQmSiOKFHvSNW4OKFoI5Xk4Gj
YXVNGrXaqKIGbgHl3RH7wxgUOFWt5ZN+Y6mfa1IqBh04Qwnq/bDgq+626bx3u/uv
zuR7P6GLMv96PIEGVq+ESzpGFxEjOtRoHf4NRUASxBn5XBhZg59XoStTfiJwqDLf
vQIDAQAB
-----END PUBLIC KEY-----
```
**Signature 1 (HEX):**
```
7e494f2bcfd319a97b2a4b41d9245bf5497567e8075cebe46b4fa4a11a03257a555266e9aed5e85566c4386ebf5da1bd9162bac1b96ae6445f45fead88d5ee5cc1d25e2bf671703082fb17c56bd87866ead3f4a5b5096c857d704c13dccef8f27e22bda4dd3b9889f38dbd1894b1618dc7c781ade2356c72b99b6f175561bd2ef9832cbe2f5933cd5b043104083e6d78431351c015f398f845a5a2a1ada37ce5b411eebd9e47a809a84c990592b4189be83cecf47b715d1a0766cd3b0f5131fda88a013321752c7d41e76fd9d3db8c7cf1a9928cfdfe8ba26dfba30fbef3dfde11429b2e607e32bc17016e3303defe2a34c8c43469bfedd8eedf459d76c6e19c
```

**Signature 2 (HEX):**
```
5853ccac1b74b90bda0771e60e93cd21c3887d35ef96aa5ef2356629c9f286d956322b2e25ba9771c9aa73eda5ae690ac58309bf34c7583c5c16de0b2845600042f4ecd190e03060449bb6f7231ddf28d159e078433dbf7a23426de6f41d5eb65c87d98c4d6f239d4104ed35402fa38eb3de6955dbe95c0fdeba9d2fef9423704033d8514174206a2952b7b2b8fc1e2d95ea12912c96d7130fed7385deb0a9a32840db1e6f933386fbd0458350905359ba6053de7e4d43d7a79f066c7be42a701c797e463cc317a430da0c382235433ef8c8ce8ff083d6b1ec70ca86837c54fba543ba0be23997310fe98aaf020ff4f815646291a81588e31dd5d54fa80fb4a1
```

**Comment by davidben** [comment]
The one without NULL is invalid. RFC8017 is pretty clear on this. The verification algorithm is expressed in terms of encoding the expected output, EM', and then comparing it with the actual output, EM. (It does later say decoding it is a valid implementation strategy, but you would need to produce the same output as the reference algorithm, so that doesn't change things. Decoding it is also a more dangerous method, as, done laxly, it can admit attacks like [this one](https://www.imperialviolet.org/2014/09/26/pkcs1.html).)
https://tools.ietf.org/html/rfc8017#section-8.2.2

That means there is one and only one input that is valid. The one that is valid is the one with the NULL, as noted in the appendix here:
https://tools.ietf.org/html/rfc8017#appendix-A.2.4

Where did the other signature come from? Whatever software is producing it should be fixed.

**Comment by microshine** [comment]
@davidben Thank you for the answer. I think that issue can be closed
