### ISSUE TITLE
3.0.0-alpha14-dev can't read DER from stdin

### ISSUE THREAD

**Issue by dcooper16** [openssl/openssl#14559]
#14407 seems to have fixed the problem of reading input from stdin only if the input is PEM encoded. However, 3.0.0-alpha14-dev still cannot handle reading input from stdin if the input is DER encoded.

An (non-realistic) example of the problem is the following:
```
openssl x509 -in ./demos/bio/root.pem -outform DER | openssl x509 -inform DER -text -noout
```
This works with OpenSSL 1.1.1 and earlier, but with 3.0.0-alpha14-dev the result is:
```
Could not read certificate from <stdin>
809B26CAB07F0000:error:0680008E:asn1 encoding routines:asn1_d2i_read_bio:not enough data:crypto/asn1/a_d2i_fp.c:198:
Unable to load certificate
```
Similarly, the following works with OpenSSL 1.1.1 and earlier, but not with 3.0.0-alpha14-dev:
```
openssl x509 -in ./demos/bio/root.pem -pubkey -noout | openssl pkey -pubin -outform DER | openssl pkey -pubin -inform DER -text_pub
```
With OpenSSL 3.0.0-alpha14-dev the result is:
```
Could not read key of Public Key from <stdin>
809B0DAF9B7F0000:error:0680008E:asn1 encoding routines:asn1_d2i_read_bio:not enough data:crypto/asn1/a_d2i_fp.c:198:
```
The error is created by the third call to OpenSSL. The second call, which receives a PEM-encoded public key as input, works correctly with OpenSSL 3.0.0-alpha14-dev.

**Comment by slontis** [comment]
Just looking at a trace - I have a suspicion about what is causing this..
The decoder is doing a lot of stuff..
I think it tries using BIO_gets (for the PEM) and then later tries using BIO_get.
And then probably gets confused since it is using the readbuffer BIO. I will have to debug into it to figure out what to do.

It seems a bit crazy trying all these different decoders when the app has asked for DER input for a cert.
