### ISSUE TITLE
bn_mod_sub_fixed_top puts bignum in weird state

### ISSUE THREAD

**Issue by guidovranken** [openssl/openssl#14767]
I know `bn_mod_sub_fixed_top` is not a public API function but I'm testing it with my fuzzer.

```
#include <openssl/bn.h>

int bn_mod_sub_fixed_top(BIGNUM *r, const BIGNUM *a, const BIGNUM *b, const BIGNUM *m);

int main(void)
{
    BIGNUM* res = BN_new();
    BIGNUM* a = BN_new();
    BIGNUM* b = BN_new();
    BIGNUM* c = BN_new();

    BN_dec2bn(&res, "0");
    BN_dec2bn(&a, "0");
    BN_dec2bn(&b, "9");
    BN_dec2bn(&c, "9");
    
    bn_mod_sub_fixed_top(res, a, b, c);
    
    printf("%s\n", BN_bn2hex(res));
    return 0;
}
```

This prints nothing (only a newline) whereas if you remove the call to `bn_mod_sub_fixed_top`, it prints 0 (as expected).

I have not experienced this behavior with any other bignum function.

Is this something you'd like to address, or shall I work around it in my fuzzer?

**Comment by davidben** [comment]
I suspect this is, for now, working as intended. This is one of the bandaids applied in lieu of fixing #6640 more robustly.

What's happening is the `fixed_top` functions break `BIGNUM`'s internal invariants by making non-minimal `BIGNUM`s. That means you can't rely on random functions to work. The symptom here is `BN_bn2hex` calls `BN_is_zero`, which only gives the right answer for minimal `BIGNUM`s. (For now, the non-minimal values are only maintained internally and OpenSSL needs to take care to only call functions which are tolerate non-minimal values.)

That said, this arrangement isn't great and leaves some values (e.g. `EC_KEY_get0_private_key` leaky because they're exposed outside the public API. I wrote out a roadmap in #6640 and indeed the first step is to make all functions tolerate non-minimal values. That means "fixing" this "bug" would actually make progress towards #6640. So I'll defer to OpenSSL folks whether to keep this ticket open or not.

But regardless of the state of this ticket, I think you need to avoid that function in your fuzzer. It's not public API and there's no guarantee that `BIGNUM` functions will behave correctly with them.

**Comment by paulidale** [comment]
I suspect we'll fix this as part of the overall BN refactoring.  As for when that is, definitely after 3.0.

**Comment by guidovranken** [comment]
Thanks. I'll remove the call to bn_mod_sub_fixed_top in my fuzzer.

@davidben FYI I'm also calling a bunch of private BoringSSL functions: https://github.com/guidovranken/cryptofuzz/blob/5a41fd9293b818a8094ca9c9a0b491f9eb5e2b76/modules/openssl/bn_ops.cpp#L10-L15

I'll keep calling these for as long these functions continue to behave as expected.

**Comment by davidben** [comment]
> FYI I'm also calling a bunch of private BoringSSL functions

Ack. Those shouldn't break any internal invariants (our BIGNUMs tolerant non-minimal values), but I had left them private just to avoid increasing the API surface unnecessarily. (Especially at the time, we were still toying with how to do the constant time BIGNUM stuff and I wasn't sure yet if I had the right strategy.)

Ah well. Too many fires to put out in the world, so, I guess I will make a sad face at you, forget about it, and we'll deal with it when/if it causes a problem. :-)

**Comment by guidovranken** [comment]
I'm only trying to help and make BoringSSL better.. I'd rather deal with a false positive than miss a legitimate computation bug.

**Comment by davidben** [comment]
Oh certainly. It's much appreciated too! Sorry, that probably came off wrong. I meant the sad face mostly in jest.

And, yeah, that it's just a fuzzer is part of why I don't want to worry about it until/unless it causes a problem by us changing the internal function. The Right Answer(TM) would be for us to expose APIs for functions that are worth fuzzing, or maybe we come up with a different project/fuzzing-infra split. But that sounds like a lot of work, and time spent on that is probably better spent on more pressing issues.
