### ISSUE TITLE
Trouble reading legacy PKCS#12 files produced with OpenSSL 1.1.1

### ISSUE THREAD

**Issue by Akretsch** [openssl/openssl#14790]
tested with 86522324d2a398ad3ed2f648a66b62b0a6176258 :
```
../openssl pkcs12 -in store.p12 -info
```
results in:
> Enter Import Password:
> MAC: sha1, Iteration 2048
> MAC length: 20, salt length: 8
> PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 2048
> Error outputting keys and certificates
> 80323002737F0000:error:0308010C:digital envelope > routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:330:Global default library context, Algorithm (RC2-40-CBC : 62), Properties ()

If *store.p12* was written with version 1.1.1f

The man page for the pkcs12 command recommends the   *-legacy* option for such problems.

But 
```
../openssl pkcs12 -legacy -in store.p12 -info
```
results in 
> openssl pkcs12: unable to load provider legacy

The legacy provider is not loaded by default.

**Comment by Akretsch** [comment]
The error message is confusing. It need some additional reading to understand it.

**Comment by DDvO** [comment]
In other words, user guidance on loading legacy PKCS12 stores is poor.

**Comment by DDvO** [comment]
A related issue reported to me by @Akretsch is:
After successfully producing a PKCS#12 file that can be handled directly by OpenSSL 3.0-alpha (using AES etc. instead of RC2) cannot be loaded with Java 8 because the algorithms are too new for that -

So with PKCS#12 there is both a backward and a forward compatibility issue :frowning_face:

**Comment by t8m** [comment]
Then use -legacy. I do not think we should be changing the defaults back.

**Comment by DDvO** [comment]
I think his point was that guidance how to properly use `-legacy` for such cases is weak.

**Comment by t8m** [comment]
OK, any PR improving the guidance is certainly welcome.

**Comment by DDvO** [comment]
`openssl-pkcs12.pod.in` reads as if using `-legacy` is sufficient, e.g.,
```
apps/openssl pkcs12 -in test/certs/v3-certs-RC2.p12 -passin pass:v3-certs -info -legacy
```
but this gives me
```
pkcs12: unable to load provider legacy
00E15AA10C7F0000:error:12800067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:118:filename(/usr/local/lib64/ossl-modules/legacy.so): /usr/local/lib64/ossl-modules/legacy.so: cannot open shared object file: No such file or directory
00E15AA10C7F0000:error:12800067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:162:
00E15AA10C7F0000:error:078C0105:common libcrypto routines:provider_init:init fail:crypto/provider_core.c:580:name=legacy
```
It turns out that in addition `-provider-path providers` 
or `OPENSSL_MODULES=providers`
is needed in case OpenSSL 3.0(-alpha) is not installed system-wide.

**Comment by DDvO** [comment]
Doc fix is in #14891.

**Comment by stone14z** [comment]
In C, the function PKCS12_parse now fails since upgrading to OpenSSL 3.0.5.   I executed the command
export NODE_OPTIONS=--openssl-legacy-provider
but it did not help.  I am running under Redhat linux 8.6-x86_64.  How do I get this to work again???

**Comment by stone14z** [comment]
Found the solution, added the call
OSSL_PROVIDER_load(NULL, "legacy");
before the pkcs12_parse function call and now everything works.

**Comment by nareshganugu** [comment]
Hi @stone14z, 
Can you please provide your full command how it looks? When I try to execute the same I'm getting the below error
My command looks like: openssl OSSL_PROVIDER_load(NULL, "legacy"); pkcs12 -in converted.pfx -nocerts -out deploy.certname.new.key
Output: Invalid command 'OSSL_PROVIDER_load(NULL,'; type "help" for a list.
My actual command is openssl pkcs12 -in converted.pfx -nocerts -out deploy.certname.new.key, and since you mentioned use OSSL_PROVIDER_load(NULL, "legacy"); before pkcs12, I had added accordingly. Appreciate your response.

**Comment by stone14z** [comment]
I was running openssl 3.0 configure to allow the openssl 1.1.1 API.  The
pkcs12 file had been built using RC2.  In my C code, I could get it to work
by including the line OSSL_PROVIDER_load(NULL, "legacy") otherwise I would
get a failure.  I ended up removing the OSSL line, extracted the
certificates from the pkcs12 file and repackaged them into a new pkcs12
file using AES.  I then had the tech writers add a notification to the end
user that deprecated ciphers are no longer supported.

Have you verified that you can extract the certificates from the pkcs12
file from the command line?  That is the first step in figuring out what is
going on.

**Comment by DDvO** [comment]
@nareshganugu you tried combining the API-level C function call `OSSL_PROVIDER_load(NULL, "legacy")` 
with the CLI-level command invocation `openssl pkcs12 -in converted.pfx -nocerts -out deploy.certname.new.key`, which makes little sense.
Instead, you need to add to your command the `-legacy` option
(and possibly a hint where the legacy provider lib can be found, such as `-provider-path path/to/providers`).

**Comment by stone14z** [comment]
As I responded, I used the -legacy option on the pkcs12  cli to dump the
certificates in the pkcs12 file.  I then repackaged the certificates using
the cli so that the file no longer used deprecated ciphers.  After that,
the OSSL C API was no longer needed.

Tom

*"It is insane to me that cryptocurrencies are still a thing."*
*    -- Bruce Schneier  20 April 2022*

**Comment by nareshganugu** [comment]
I already tried running command by adding -legacy at the end of the command and I get below error. 
Command: openssl pkcs12 -in converted.pfx -nocerts -out deploy.certname.new.key - legacy
Error: pkcs12: unable to load provider legacy
Hint: use -provider-path option or OPENSSL_MODULES environment variable.

If my command is openssl pkcs12 -in converted.pfx -nocerts -out deploy.certname.new.key -legacy, what should I tweak to successfully extract certificate. The same command worked few months before and now its not working.

**Comment by t8m** [comment]
> @DDvO @stone14z I already tried running command by adding -legacy at the end of the command and I get below error. Command: openssl pkcs12 -in converted.pfx -nocerts -out deploy.certname.new.key - legacy Error: pkcs12: unable to load provider legacy Hint: use -provider-path option or OPENSSL_MODULES environment variable.
> 
> If my command is openssl pkcs12 -in converted.pfx -nocerts -out deploy.certname.new.key -legacy, what should I tweak to successfully extract certificate. The same command worked few months before and now its not working.

It is reported straight in the error message - apparently the legacy provider cannot be loaded because it is not installed at the place the openssl library expects it to be installed.

**Comment by nareshganugu** [comment]
I have installed Openssl Version: OpenSSL 1.1.1w  11 Sep 2023 and using version my same old commands worked without using -legacy at the end of the command.

**Comment by stone14z** [comment]
Using the -legacy option should only be required when using OpenSSL 3.x.
Glad you got it working though.

Tom

*"It is insane to me that cryptocurrencies are still a thing."*
*    -- Bruce Schneier  20 April 2022*
