### ISSUE TITLE
multi threading safety in v1.1.0

### ISSUE THREAD

**Issue by wolftobias** [openssl/openssl#1499]
We change right now our code to use the new version 1.1.0 and as fare as we understood the thread lock functions have been set to deprecated, therefore we compiled with no deprecated option. We removed the previous implementation of the threading functions from our code now. 
Our product is written in java and the code is wrapped in a dll which calls the openssl api.

Now we got a java.lang.IllegalMonitorStateException in our code during runtime when we execute a certificate verify callback given here in the ssl context:

```
SSL_CTX_set_cert_verify_callback(ctx, cert_verify_callback, NULL);
```
```
int cert_verify_callback(X509_STORE_CTX* x509_store_ctx, void* arg) {
	LOG_ENTER("cert_verify_callback(%p,%p)", x509_store_ctx, arg);

	if(gk_check_params_failed("cert_verify_callback", 1, x509_store_ctx)) {
		return -1;
	}

	/* Get the correct index to the SSLobject stored into X509_STORE_CTX. */
	SSL* ssl = (SSL*) X509_STORE_CTX_get_ex_data(x509_store_ctx, SSL_get_ex_data_X509_STORE_CTX_idx());
	int result = 0;
	APP_DATA* app_data = gk_SSL_get_app_data(ssl);

	if(app_data->vccc != NULL) {
		const char* authMethod = gk_SSL_get_current_cipher(ssl);
		SSL_SESSION* session = SSL_get_session(ssl);
		STACK_OF(X509*) cert_chain = X509_STORE_CTX_get0_untrusted(x509_store_ctx);
		LOG_TRACE("calling callback verifyCertificateChain(session=%p,certChain=%p,authMethod=%s)", session, cert_chain, authMethod);
		int cert_chain_size = gk_sk_X509_num(cert_chain);
		result = app_data->vccc(session, cert_chain, cert_chain_size, authMethod);
	}

	LOG_EXIT("cert_verify_callback(%p) => %d", x509_store_ctx, result);
	return result;
}
```
The error comes not consistently always at the same place, therefore we think it could have something to do with multi threading, our product is a multi threading backend server. Please provide some hints how the multi threading is implemented now in the new version 1.1.0 to give us the chance to trap down the error.

**Comment by mattcaswell** [comment]
Multi-threading now uses native platform threading calls rather than the old style callbacks. Currently we support pthreads and win-threads. If you are on a platform that we don't recognise for some reason you could end up with "no-threads", which means no multi-threaded support. From your description it sounds like you are on Windows so you should just get native win-threads support by default. The windows threading implementation, if you want to look at it, is in crypto/threads_win.c.

**Comment by mattcaswell** [comment]
My guess is you may need to do some work to associate a JVM thread with a native thread.

**Comment by wolftobias** [comment]
I'm compiling with mingw under linux for Windows 64 bit, is there a known issue with this configuration? As I mentioned earlier with v1.0.2 same code is working. We changed only what was necessary to support   opaque api.

**Comment by wolftobias** [comment]
I tried now with VS compiled openssl libraries and I get the saem error. How can I verify that I running with treading support? In old implementation we`ve initialized threading support explicitly, now with new version we do nothing there! Is there a way to initialize this now?

our old way:
```
void gk_initialize() {
	LOG_ENTER("gk_initialize()", NULL);

	int rc = gk_thread_setup();

	if(rc != 1) {
		gk_throwOpenSSLNativeException("gk_thread_setup failed!");
	}

	SSL_library_init();
	OpenSSL_add_all_algorithms();
	SSL_load_error_strings();
	ERR_load_crypto_strings();

	gk_init_dh_params();

	LOG_EXIT("gk_initialize()", NULL);
}
```

our new way:
```
void gk_initialize() {
	LOG_ENTER("gk_initialize()", NULL);

	OPENSSL_init_ssl(0, NULL);
	OPENSSL_init_crypto(0, NULL);

	gk_init_dh_params();

	LOG_EXIT("gk_initialize()", NULL);
}
```

**Comment by wolftobias** [comment]
Just right now I experienced an access violation at this point:
```
 	kernel32.dll!SwitchToFiber()	Unbekannt
	libcrypto-1_1-x64.dll!async_start_func() Zeile 166	C
```

Is the behavior for handshake changed to some asynchronously job mechanism?

**Comment by mattcaswell** [comment]
Async support has been added but it is off by default. You have to explicitly request it by setting the mode to `SSL_MODE_ASYNC` using `SSL_CTX_set_mode()` or `SSL_set_mode()`. Do you have more of a backtrace that the above. I'm assuming you haven't set that mode, so it would be interesting to see how it got into the above call....however if you are having multi-thread issues then it could be that some other issue is causing some corruption, leading to this cod path being taken.

**Comment by wolftobias** [comment]
Your are right assuming, we are not setting this on purpose, but with your hint we found the reason, there was a constant with the same value defined!

```
// BEAST attack mitigation (1/n-1 record splitting for CBC cipher suites
// with TLSv1 and SSLv3).
GematikOpenSSL.provider().setMode(ssl, OpenSSLConstants.SSL_MODE_CBC_RECORD_SPLITTING);
```
I`m going to close this issue, but let me ask one last question, we took this code from android project without deeper knowledge about the reason, do you know about this BEAST attack? Is there a way to avoid this in new openssl 1.1?

**Comment by mattcaswell** [comment]
Interesting. After a bit of digging I discovered that SSL_MODE_CBC_RECORD_SPLITTING is a BoringSSL specific mode (@agl, @davidben), so this now represents a potential incompatibility between the two forks. Added in this commit:
https://boringssl.googlesource.com/boringssl/+/d493d5289dd834b65232899c2cd8fe83baddfd44

BEAST mitigation is on by default, unless you enable SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS (which is also enabled if you use SSL_OP_ALL).

**Comment by richsalz** [comment]
So we should reserve a value like SSL_MODE_unused which maps to thier record-splitting constant.

**Comment by mattcaswell** [comment]
Too late...we already used it: SSL_MODE_ASYNC

**Comment by richsalz** [comment]
But we can work with them to get a new number and avoid future conflicts.

**Comment by davidben** [comment]
Oh, definitely don't burn numbers on our behalf! I think you all should just close this WontFix. As far as OpenSSL is concerned, this no different from the consumer randomly doing `SSL_set_mode(ssl, 0xf00000);` which is obviously not supported.

@wolftobias, it sounds like you're using OpenSSL and not BoringSSL, so you shouldn't setting or defining that constant anyway. If you copied it from Android, it uses BoringSSL and previously used a heavily patched OpenSSL, so it's never been using the same library as you anyway.

If you were using BoringSSL, we don't promise a stable ABI and consider it fair game to renumber things, so you shouldn't have been making a assumptions on the numbers anyway. (For instance, perhaps we'd like to renumber to avoid colliding with OpenSSL...) In Android's Conscrypt project, we generate the Java constants files at build time precisely so this sort of thing can't happen.

(BoringSSL has a different record-splitting thing because OpenSSL's 0/n splitting has some compatibility issues. I believe, at least at the time, there were servers which broke on empty records. I think they treated it as EOF. This is likely why `SSL_OP_ALL` includes `SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS`. Browsers instead implemented 1/n-1 splitting which is much more compatible. But this is tangential to this bug.)

**Comment by richsalz** [comment]
well okay then.  :)
