### ISSUE TITLE
openssl 1.1.1d on debian Buster stuck cannot enabling custom cipher

### ISSUE THREAD

**Issue by antokxvi** [openssl/openssl#15024]
now, i'm on project about implementation of GIFT lightweight block for cipher suite custom OpenSSL. I've done implementing that algorithm with following step that given from https://wiki.openssl.org/index.php/How_to_Integrate_a_Symmetric_Cipher#Create_the_Cipher then, I installing the OpenSSL custom with command:

1. sudo ./config --prefix=/opt/openssl-gift --openssldir=/opt/openssl-gift enable-gift128
2. sudo make depend
3. sudo make clean
4. sudo make
5. sudo make install

aftar finished, i open the directory /opt/openssl-gift, then i check the list of ciphers with "openssl enc -ciphers" but i didn't find my custom cipher that is called gift128. anyone can solve about this? Thank a lot

**Comment by kaduk** [comment]
Presumably your `PATH` setting is finding `/usr/bin/openssl` instead of `/opt/openssl-gift/bin/openssl`, so you are not actually using your new code.
You will probably also need to add a file in  `/etc/ld.so.conf.d/` and run `ldconfig -a` to tell the runtime linker about the new shared libraries you installed.

(Also, IIRC it is enough to specify just `--prefix` and `--openssldir` is not needed when set to the same value, but the documentation is going to be more accurate for that point.)
