### ISSUE TITLE
The fipsmodule.cnf to be installed cannot be created by openssl fipsinstall in cross-compiled builds

### ISSUE THREAD

**Issue by tomiii00** [openssl/openssl#15166]
#13684 broke cross-compiled builds by making `install_fips` automatic.

Our project cross-compiles OpenSSL for ARM on x86_64 as part of a larger distribution. Other open-source components of this distribution have dependencies on OpenSSL. As such, we depend on the `install` target working properly so we can build OpenSSL and install the artifacts into a staging directory which we then specify on the "configure" command lines when we subsequently build those other components. Prior to #13684 the install target completed successfully (and `providers/fips.so` was getting installed into the correct location). Now the install target in our cross-compile builds fails with:

`make[2]: *** No rule to make target 'providers/fipsmodule.cnf', needed by 'install_fips'.  Stop.`

This aborts installation and prevents the copying of `fips.so` into our staging directory.

We use this command line to configure OpenSSL:

`./Configure linux-generic32 -DL_ENDIAN -DOPENSSL_NO_COMP shared --prefix=/usr --openssldir=/conf/openssl enable-fips no-zlib no-comp no-tests`

It appears that `no-tests` prevents the creation of the `providers/fipsmodule.cnf` Makefile target (which we can't actually build anyway when cross-compiling). Since `providers/fipsmodule.cnf` is now a prerequisite for installing `fips.so` into our staging directory, that module is missing from our final product.

**Comment by mspncp** [comment]
Thank you @tomiii00 for your report. I agree that it's a bug, but from your description it seems that #13684 is not the actual problem, it just triggered it:  the `no-tests` and `enable-fips` configure options are currently not compatible. The main question is whether this is by design or just a bug:

- If `providers/fipsmodule.cnf` depends on `enable-tests` (because of the CAVS testsuite?) then `enable-fips` should require `enable-tests`.
- If `providers/fipsmodule.cnf` does not depend on `enable-tests`, then it's a bug in the make rules and dependency needs to be removed in the makefile template.

I'm not familiar enough with every detail of the FIPS project to give you an answer without some investigation, but maybe @t8m or @slontis can give more insight.

**Comment by rsbeckerca** [comment]
> 
> 
> Thank you @tomiii00 for your report. I agree that it's a bug, but from your description it seems that #13684 is not the actual problem, it just triggered it: the `no-tests` and `enable-fips` configure options are currently not compatible. The main question is whether this is by design or just a bug:
> 
>     * If `providers/fipsmodule.cnf` depends on `enable-tests` (because of the CAVS testsuite?) then `enable-fips` should require `enable-tests`.
> 
>     * If `providers/fipsmodule.cnf` does not depend on `enable-tests`, then it's a bug in the make rules and dependency needs to be removed in the makefile template.
> 
> 
> I'm not familiar enough with every detail of the FIPS project to give you an answer without some investigation, but maybe @t8m or @slontis can give more insight.

Should not `provider/fipsmodule.cnf` depend on both `enable-tests` and `enable-fips` rather than only one of them?

**Comment by mspncp** [comment]
> Should not provider/fipsmodule.cnf depend on both enable-tests and enable-fips rather than only one of them?

@rsbeckerca it's not quite like that: targets don't depend on configure options, configure options influence which dependency rules are stated when the Makefile is created from the template at configuration time.

The main change of #13684 was that the `install_fips` target gets part of the `install` target if fips is enabled, and it's a no-op (just showing a warning) when fips is disabled ("what you configured is what gets installed"):

https://github.com/openssl/openssl/blob/a07b0bfb99169d23d2801b8aee210d98a0d12cac/Configurations/unix-Makefile.tmpl#L529

https://github.com/openssl/openssl/blob/a07b0bfb99169d23d2801b8aee210d98a0d12cac/Configurations/unix-Makefile.tmpl#L598
  
It's the `install_fips` target which requires `provider/fipsmodule.cnf` (when fips is enabled), because the `fips.so` shared library is not a valid FIPS module without the checksums.

**Comment by mspncp** [comment]
> Since providers/fipsmodule.cnf is now a prerequisite for installing fips.so

In view of my previous post: yes, this dependency is by design.

**Comment by tomiii00** [comment]
> > Since providers/fipsmodule.cnf is now a prerequisite for installing fips.so
> 
> In view of my previous post: yes, this dependency is by design.

I accept that it is by design. However, it's not clear to me how it will ever be possible for this design to support cross-compile environments where by definition you are building on one machine and executing on another. Furthermore, this design seems at odds with this blurb from README-FIPS.md:

```
The FIPS module must have the self tests run, and the FIPS module config file
output generated on every machine that it is to be used on. You must not copy
the FIPS module config file output data from one machine to another.
```

I would think it's a common use case to build on a central build server and then distribute the artifacts elsewhere. Attempting to also generate fipsmodule.cnf as part of that process goes contrary to the intent of that paragraph.

**Comment by slontis** [comment]
@t-j-h Do you have an opinion on this ?

**Comment by t-j-h** [comment]
The current wording and approach is a unnecessarily limiting and incomplete. 

The user should be able to construct the configuration file in any manner than they wish on the target platform (i.e. we should not be requiring the existence of the openssl application and the ability to run a command line tool). What is necessary is that the mac has been calculated and stored - and that can be performed (the calculation) on any platform and that the self tests have been run on the target prior to first usage.

I would tend to create the configuration file as part of the build process without the self-tests-have-run indicator on the build platform. Updating the self-tests have run status is a separate exercise and the user should be able to perform that in any manner they wish - i.e. edit the file themselves manually etc - provided they are asserting that they have (somehow) run the self tests.

i.e. we should be decoupling this somewhat 

The security policy document will have to provide the list of steps the installer of the module has to follow and they will necessarily have to allow for handling platforms where the installer won't be running command line applications.

Remember that we have target platforms for the fips release where there is no command line and no shell available so it has to be possible to "install" and run on those platforms and what is there presently does not handle that context.

**Comment by t8m** [comment]
Now the question is what tool should we use to compute the module hmac on cross-compiled builds. Or even all builds if we decide that the file should not contain the self-test-have-run indicator. Which is IMO better option for uniformity and also to allow proper build-once deploy many times. As by the FIPS requirements every deployment is required to run the self-tests at least once.

**Comment by slontis** [comment]
Having the self tests always run on load on these targets seems like a reasonable thing to do (the tests are not slow).
fipsinstall could also be run twice to generate 2 config files on the build system. The targets still need to run the self tests at least once though before using a config file that skips the self tests.

**Comment by paulidale** [comment]
The checksum generator needs to be approved I believe.

**Comment by t8m** [comment]
> The checksum generator needs to be approved I believe.
AFAIK no. The build process (and the module checksum is part of it) is outside of things that FIPS considers.

**Comment by levitte** [comment]
There are several flaws with the current approach in producing providers/fipsmodule.cnf.  To begin with, only hooking that in the tests is flawed, considering that we depend on it for installation.  That's a bug.

**Comment by t8m** [comment]
IMO we need a different fipsmodule.cnf for the tests - that can be generated the way it is generated now - and another fipsmodule.cnf for the make install_fips target. That cannot be generated by openssl fipsinstall and should not contain the self-tests-has-been-run indicator.

**Comment by levitte** [comment]
Er...  why?

**Comment by t8m** [comment]
Well if we do not care about the _self-tests-has-been-run indicator_ for the tests' fipsmodule.cnf then we can still have just one.

**Comment by levitte** [comment]
Meanwhile, I have a proposed fix in #15174

**Comment by levitte** [comment]
> I would tend to create the configuration file as part of the build process without the self-tests-have-run indicator on the build platform.

Isn't this essentially the same as not having a fipsmodule.cnf, or if we must have it, an empty one?
Maybe my memory is foggy on what has changed, but wasn't if the case that if there was no integrity check data, the self tests would automatically be run when the FIPS provider is loaded?

**Comment by levitte** [comment]
Never mind what I wrote...  my memory *is* foggy

**Comment by t8m** [comment]
No, there are two things - the module checksum and the _selftests run_ indicator in form of install-mac and install-status. 

The module checksum is always required and normally needs to be created as part of build process. Of course things are a little bit blurred with _source level validations_ because the build process is done by the user, but let's disregard it for now. This checksum verifies that the binary of the fips module has not been accidentally changed after the build.

The _selftests run_ indicator is just an optimization thing to be able to skip running the selftests on every fips.so load. This indicator indicates that the selftests were run at the deployed system at least once. It is absolutely required that the indicator is created on the actually deployed system and not on the build system in case they are different.

**Comment by t8m** [comment]
We could use hmac_sha256_hex from Digest::SHA for example to compute the module checksum during build.

**Comment by paulidale** [comment]
An aside: could we see how long the power up tests take to run?  We might be able to avoid the optimisation entirely.

**Comment by levitte** [comment]
So in summary, are we talking about producing a fipsmodule.cnf without the self-test-run indicator (i.e. only the integrity check) with simple means like Digest::SHA, and then essentially make an extended variant of the configuration file that has the self-test-run indicator added?

Would it then be sensible to modify `openssl fipsinstall` to grab the already existing fipsmodule.cnf, run the tests and just add the self-test-run indicator, instead of re-creating it all from scratch?

**Comment by t8m** [comment]
> Would it then be sensible to modify `openssl fipsinstall` to grab the already existing fipsmodule.cnf, run the tests and just add the self-test-run indicator, instead of re-creating it all from scratch?

It would make sense to me. If it wrote the file from scratch it should not modify the existing module checksum. I.e., it should actually verify the existing checksum is correct before overwriting.

**Comment by t8m** [comment]
> An aside: could we see how long the power up tests take to run? We might be able to avoid the optimisation entirely.

On my machine it takes about 12.7 ms.

**Comment by tomiii00** [comment]
It takes roughly 1.8 seconds to run the self-tests in my 32-bit ARM environment. The optimization is absolutely necessary.

**Comment by t8m** [comment]
OTC: we can use perl or some `quick hack HMAC-SHA256` compiled on the build system for the build host.
