### ISSUE TITLE
Filtering openssl list output by provider

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#15196]
When I call 
`openssl list -provider-path `pwd`/providers/ -provider legacy -propquery "provider=legacy" -digest-algorithms -kdf-algorithms -mac-algorithms -cipher-algorithms -key-exchange-algorithms -kem-algorithms -signature-algorithms -asymcipher-algorithms -public-key-algorithms` 
it lists all the algorithms including definitely not legacy, such as Ed448. 

Is it an intended behavior?

**Comment by paulidale** [comment]
List doesn't fetch the algorithms, so ignoring the propquery is expected.

It's seems more than a little counterintuitive to operate this way.  Adding a fetch/free to each of the collect functions would enforce the use of the propquery.

**Comment by beldmit** [comment]
Well... It tries to fetch the algorithms at least for _some_ purposes, I've added it myself :)

**Comment by paulidale** [comment]
I think the question was more about why the `-propquery "provider=legacy"` option didn't achieve anything.

**Comment by levitte** [comment]
Because property queries don't cause provider loading.

**Comment by beldmit** [comment]
I expected that provider parameters specify the (extra) set of loaded providers and propquery specifies which algorithms/implementations are listed.

**Comment by beldmit** [comment]
BTW, is there any option to list exactly all the features provided by a particular provider?

**Comment by paulidale** [comment]
> But, what did you expect?

As somebody who didn't know the deep internals of the code, I'd have expected only the legacy provider algorithms to be listed.

I know how this works, I know why it does what it does.  That doesn't mean it's the "right" thing to do 😃

**Comment by levitte** [comment]
Like I said, we could simply forego our internal legacy implementations. They should really not be necessary any more, like at all.

**Comment by levitte** [comment]
... or not líst them, at least drop that code, unless they're engine implementations

**Comment by beldmit** [comment]
OK, I wonder, what algorithms/implementations are FIPS compatible and expect I can do it using the `list` command.

**Comment by paulidale** [comment]
I don't have a problem dropping the legacy implementations.  I think they should, at least, be renamed to avoid confusion with the legacy provider -- us developers have confused the two on occasion and users who aren't aware of the distinction will find it harder.  We don't need to rename all the internal stuff, just the user visible parts.  What about _compatibility_ instead of _legacy_ for them?

Then we could add a _-no-compatibility_ or _-compatibility_ option to `list` to print them (which depends upon if they are shown by default or not).  We should still list engine implementation regardless (because they need _-engine_ or configuration file to load).

We should also try fetching the implementation as a filter (perhaps only if _-propquery_ is specified).

**Comment by t8m** [comment]
> Like I said, we could simply drop our internal legacy implementations. They should really not be necessary any more, like at all.

What about some operations that combine external legacy implementation and internal one? Like a decoding an external engine based key encrypted in PKCS#8 with an algorithm that is internal to OpenSSL? I do not even know if we currently support this though.

**Comment by t8m** [comment]
So IMO it would be safer to just not list the legacy implementations instead of cutting them out completely.

**Comment by susanbaouch** [comment]
nice
