### ISSUE TITLE
Is the download, cloning of the huge fuzz/corpora necessary?  

### ISSUE THREAD

**Issue by WinserverSupport** [openssl/openssl#15272]
Is the download, cloning of the huge fuzz/corpora necessary?   Its downloads for a long time and I don't believe its something required for production builds?   Is it?  I am just rebuild from source, the *.DLL and *.,EXE images.

**Comment by paulidale** [comment]
Are you going to do a `make test` before you use this in production?
* if you are then you need the fuzzing;
* if you aren't you probably need to reconsider that decision.

**Comment by levitte** [comment]
The fuzz testing is skipped if the fuzz/corpora subdirectories aren't present.  So even with `make test`, they aren't strictly necessary.
And of course, if you're not going to run `make test` at all, they really aren't.

We do not include the fuzz/corpora data in our official tarballs.  This is by design.

**Comment by WinserverSupport** [comment]
Ok, not a problem.  I was impatient as it taking a long time to download/svn clone. Never noticed it before. Researched the fuzz purpose as it was still downloading and saw GitHub limited truncated data folders.  I didn't think it would something important  if we are just recompiling production images.  Anyway, its working!!  Thanks

**Comment by WinserverSupport** [comment]
> Are you going to do a `make test` before you use this in production?
> 
> * if you are then you need the fuzzing;
> * if you aren't you probably need to reconsider that decision.

As short as I can make this,  since early openssl v1.0. never had to do a test on what I believe is release "stable" code, ready for production builds in distributions.   If there is an expectation that we need to run a series of test. well, then it wasn't ready for prime time.  We already third party developers using it ahead of its and we don't change until ready.  We are in update mode now.  I don't know what the "fuzz" is all about, but this is new to me.  Is the suggestion the v1.1.11k "stable" release is not stable?

Thanks

**Comment by levitte** [comment]
> Is the suggestion the v1.1.11k "stable" release is not stable?

1.  "Stable" doesn't mean "absolutely free of bugs", it means that the interfaces will not change, and that all bugs that have been found (by the OpenSSL teams of by others) have been corrected.
2.  OpenSSL can be built on far more platforms than we have access to, and some bugs may only become apparent on those.  We do test quite a bit, and have at least Linux, Windows and MacOS covered through github actions.

Fuzzing is a tool to find obscure bugs such as corner cases, due to "surprising" input etc.

So whether you run the test suite or not is *your* judgement call.  Is the platform you have covered well enough by the tests that we do?  Do you trust our testing infrastructure and the tests we run?  If you do, then I see no reason for you to run `make test`.
We can't make that judgement call for you.

**Comment by WinserverSupport** [comment]
@levitte, 

"Stable" to me has always meant a product is ready as an official (public) release, "Ready to Ship"  where the internal test suites and fuzz testing would no longer be necessary, nor expected of the product end-users.   

Of course, it does not  mean  "free of bugs"   but it should be free of fuzz/test suite related issues.  A release marked as "Stable" is generally not  considered Alpha, Beta nor Gamma.,   

If you believe Fuzz testing is a MUST or even a SHOULD requirement before any OpenSSL stable release usage, then imo, this tells me 1.1.1k  is not ready and I should revert to the previous version.

**Comment by paulidale** [comment]
The project cannot test your build with your compiler on your hardware running your operating system.

We do do testing and believe that the release is stable.  However, your environment will be different to any we can test on.   Prudence would suggest testing but as @levitte mentioned, it's your call.

As for reverting, again your call.  The previous release went through the same testing by us.

**Comment by WinserverSupport** [comment]
That idea of implementation testing is where we have confidence -- its Windows! I require 100% Win32/64 API C stable, sound server/client application development code.   If it was IoT, RasPI, etc, I get it,  but this is solid 100% 32/64 bit Windows.  I've been testing the 64bit version for 2 years now and now pending release.   Sort of like Herd Immunity.  I can see the testing requirements with the different *nix OSes by shear volume.   I don't recall seeing the Fuzz cloning with 1.1.1.g, our last version, nor If I was watching, but I did notice now. More curious.

Let me say,  I have no problem with this.   I _can_ imagine the management behind a long time legacy, well established open source product - worldwide, complex and hard.    If it doesn't already, it would help with a "Test-after-building-and-before-Releasing.cmd" batch file!    I can easily add it to our script when rebuilding a new openssl.    

My openssl plans is to move to v3.0. I see it is at Alpha.   I definitely plan to look into it soon.

Have a good day.
