### ISSUE TITLE
Building for Android with clang fails: "-mandroid" unknown argument

### ISSUE THREAD

**Issue by Stevolk** [openssl/openssl#1531]
OpenSSL sets `-mandroid` flag when compiling for Android, which breaks building with clang, as clang does not recognize this argument.

Starting with clang 3.4 unknown compiler flags were treated as an error. This caused problems on OS X (-> Xcode 5.1) with packages failing to compile.
For some time the behavior could be disabled with `-Wno-error=unused-command-line-argument-hard-error-in-future`, but this option has been removed (don't know the exact version). 

**Problematic OpenSSL source code:**
file: `Configurations/10-main.conf`
lines: [876](https://github.com/openssl/openssl/blob/OpenSSL_1_1_0/Configurations/10-main.conf#L876) and [916](https://github.com/openssl/openssl/blob/OpenSSL_1_1_0/Configurations/10-main.conf#L916)
```
OpenSSL 1.1.0
Android NDK r12b
Android clang version 3.8.256229  (based on LLVM 3.8.256229)
Compilation target: armv7-a
```

**Comment by yan12125** [comment]
I have the same problem, and I'm using a dirty patch for that: https://github.com/yan12125/python3-android/blob/cpython-hg/mk/openssl/fix-cflags.patch

**Comment by dot-asm** [comment]
Well, so far gcc was supported and I can confirm that targets are operational as long as you follow instructions in Configurations/10-main.cf. If clang support is desired, then one should formulate problem like that, i.e. clang support is desired.

As for providing ad-hoc patches for 10-main.cf it's not the way to go. Composing separate .cf add-on file with embedded instructions is. I mean Configure reads all files in Configurations directory, not just 10-main.cf, so if you want a custom target just drop additional file of own design.

**Comment by Stevolk** [comment]
> Well, so far gcc was supported and I can confirm that targets are operational as long as you follow instructions in Configurations/10-main.cf. If clang support is desired, then one should formulate problem like that, i.e. clang support is desired.

Yes, there are no problems using GCC.

Why I am concerned about clang support (and have opened this issue) is that GCC is going to be deprecated in Android NDK in the future.
See https://android.googlesource.com/platform/ndk.git/+/master/CHANGELOG.md
> GCC is no longer supported. It will not be removed from the NDK just yet, but is no longer receiving backports. It cannot be removed until after libc++ has become stable enough to be the default, as some parts of gnustl are still incompatible with Clang. It will likely be removed after that point.

**Comment by yan12125** [comment]
@dot-asm Did you mean adding new targets like "android-arm-clang", "android64-aarch64-clang" and so on? Or does 10-main.conf allow using different cflags for different compilers?

**Comment by dot-asm** [comment]
> I am concerned about clang support

And one should have opened with this. It not uncommon that we have different configurations for same OS and different compilers, so that in general case  you-can't-do-that-so-just-don't is very natural reaction. Well, in some cases replacing compiler works, if they are option-compatible, but this obviously is not such case, is it? :-) In other words one shouldn't complain about current android config targets not working with flag-incompatible compiler, but about lack of clang support... It will be looked into, meanwhile adhere to gcc.

**Comment by dot-asm** [comment]
> Did you mean adding new targets like "android-arm-clang", "android64-aarch64-clang" and so on?

Yes, there hardly is another option. As just mentioned it's flag-incompatible with gcc, and having user fill in option by passing appropriate flag (though command line or environment variable) is not exactly desirable, because it can result in attempt to pass platform-x-specific flags to platform-y build. And once again, [custom] targets can be added without patching existing file[s], but adding a new one. And target doesn't have to be created from scratch, you can `inherit_from` and override just specific bits, even if it's placed in separate file...

> Or does 10-main.conf allow using different cflags for different compilers?

It's kind of a trick question. You can pass additional compiler flags on Configure command line, but naturally they have to be meaningful and correct for given target. There also is suggestion for Configure to use CFLAGS to override those denoted by 'release' and 'debug' tags in configs. But in either case there still is and will be a set of base flags in targets that so to say define it. As for different compilers, see previous comment.

**Comment by yan12125** [comment]
Thanks for explanation. I'll try.

**Comment by xsacha** [comment]
On 1.1.0b, I get this error in addition to the error in OP:
***** Unsupported options: no-canonical-prefixes

**Comment by yan12125** [comment]
Finally I can run tests on Android for my clang build. I guess this indicates everything is fine?
```
$ PERL=$(which perl) make test
make depend && make _tests
make[1]: Entering directory '/data/data/com.termux/files/home/openssl'
make[1]: Leaving directory '/data/data/com.termux/files/home/openssl'
make[1]: Entering directory '/data/data/com.termux/files/home/openssl'
( cd test; \
  SRCTOP=../. \
  BLDTOP=../. \
  PERL="/data/data/com.termux/files/usr/bin/perl" \
  EXE_EXT= \
  OPENSSL_ENGINES=.././engines \
    /data/data/com.termux/files/usr/bin/perl .././test/run_tests.pl  )
../test/recipes/01-test_abort.t ............ ok   
../test/recipes/01-test_sanity.t ........... ok   
../test/recipes/01-test_symbol_presence.t .. ok   
../test/recipes/02-test_ordinals.t ......... ok   
../test/recipes/05-test_bf.t ............... ok   
../test/recipes/05-test_cast.t ............. ok   
../test/recipes/05-test_des.t .............. ok   
../test/recipes/05-test_hmac.t ............. ok   
../test/recipes/05-test_idea.t ............. ok   
../test/recipes/05-test_md2.t .............. skipped: md2 is not supported by this OpenSSL build
../test/recipes/05-test_md4.t .............. ok   
../test/recipes/05-test_md5.t .............. ok   
../test/recipes/05-test_mdc2.t ............. ok   
../test/recipes/05-test_rand.t ............. ok   
../test/recipes/05-test_rc2.t .............. ok   
../test/recipes/05-test_rc4.t .............. ok   
../test/recipes/05-test_rc5.t .............. skipped: rc5 is not supported by this OpenSSL build
../test/recipes/05-test_rmd.t .............. ok   
../test/recipes/05-test_sha1.t ............. ok   
../test/recipes/05-test_sha256.t ........... ok   
../test/recipes/05-test_sha512.t ........... ok   
../test/recipes/05-test_wp.t ............... ok   
../test/recipes/10-test_bn.t ............... ok   
../test/recipes/10-test_exp.t .............. ok   
../test/recipes/15-test_dh.t ............... ok   
../test/recipes/15-test_dsa.t .............. ok   
../test/recipes/15-test_ec.t ............... ok   
../test/recipes/15-test_ecdh.t ............. ok   
../test/recipes/15-test_ecdsa.t ............ ok   
../test/recipes/15-test_rsa.t .............. ok   
../test/recipes/20-test_enc.t .............. ok       
../test/recipes/20-test_passwd.t ........... ok     
../test/recipes/25-test_crl.t .............. ok   
../test/recipes/25-test_d2i.t .............. ok     
../test/recipes/25-test_pkcs7.t ............ ok   
../test/recipes/25-test_req.t .............. ok   
../test/recipes/25-test_sid.t .............. ok   
../test/recipes/25-test_verify.t ........... ok       
../test/recipes/25-test_x509.t ............. ok   
../test/recipes/30-test_afalg.t ............ skipped: test_afalg not supported for this build
../test/recipes/30-test_engine.t ........... ok   
../test/recipes/30-test_evp.t .............. ok   
../test/recipes/30-test_evp_extra.t ........ ok   
../test/recipes/30-test_pbelu.t ............ ok   
../test/recipes/40-test_rehash.t ........... ok   
../test/recipes/70-test_asyncio.t .......... ok   
../test/recipes/70-test_bad_dtls.t ......... ok   
../test/recipes/70-test_clienthello.t ...... ok   
../test/recipes/70-test_packet.t ........... ok   
../test/recipes/70-test_sslcbcpadding.t .... ok   
../test/recipes/70-test_sslcertstatus.t .... ok   
../test/recipes/70-test_sslextension.t ..... ok   
../test/recipes/70-test_sslrecords.t ....... ok   
../test/recipes/70-test_sslsessiontick.t ... ok    
../test/recipes/70-test_sslskewith0p.t ..... ok   
../test/recipes/70-test_sslvertol.t ........ ok   
../test/recipes/70-test_tlsextms.t ......... ok   
../test/recipes/70-test_verify_extra.t ..... ok   
../test/recipes/70-test_wpacket.t .......... skipped: Only supported in no-shared builds
../test/recipes/80-test_ca.t ............... Use of uninitialized value in -x at /data/data/com.termux/files/usr/lib/perl5/5.24.0/aarch64-linux/Cwd.pm line 197.
../test/recipes/80-test_ca.t ............... ok   
../test/recipes/80-test_cipherlist.t ....... ok   
../test/recipes/80-test_cms.t .............. ok   
../test/recipes/80-test_ct.t ............... ok   
../test/recipes/80-test_dane.t ............. ok   
../test/recipes/80-test_dtls.t ............. ok   
../test/recipes/80-test_dtlsv1listen.t ..... ok   
../test/recipes/80-test_ocsp.t ............. ok     
../test/recipes/80-test_pkcs12.t ........... Can't exec "locale": No such file or directory at ../test/recipes/80-test_pkcs12.t line 48.
../test/recipes/80-test_pkcs12.t ........... ok   
../test/recipes/80-test_ssl_new.t .......... ok     
../test/recipes/80-test_ssl_old.t .......... ok   
../test/recipes/80-test_ssl_test_ctx.t ..... ok   
../test/recipes/80-test_tsa.t .............. ok     
../test/recipes/80-test_x509aux.t .......... ok   
../test/recipes/90-test_async.t ............ ok   
../test/recipes/90-test_bio_enc.t .......... ok   
../test/recipes/90-test_bioprint.t ......... ok   
../test/recipes/90-test_constant_time.t .... ok   
../test/recipes/90-test_fuzz.t ............. ok     
../test/recipes/90-test_gmdiff.t ........... ok   
../test/recipes/90-test_heartbeat.t ........ skipped: heartbeats is not supported by this OpenSSL build
../test/recipes/90-test_ige.t .............. ok   
../test/recipes/90-test_memleak.t .......... ok   
../test/recipes/90-test_p5_crpt2.t ......... ok   
../test/recipes/90-test_secmem.t ........... ok   
../test/recipes/90-test_srp.t .............. ok   
../test/recipes/90-test_sslapi.t ........... ok   
../test/recipes/90-test_threads.t .......... ok   
../test/recipes/90-test_v3name.t ........... ok   
All tests successful.
Files=88, Tests=488, 763 wallclock secs ( 5.53 usr  0.43 sys + 470.11 cusr 57.18 csys = 533.25 CPU)
Result: PASS
make[1]: Leaving directory '/data/data/com.termux/files/home/openssl'
```

**Comment by richsalz** [comment]
yes.  have fun :)

**Comment by xsacha** [comment]
So, this is still broken. Any ideas of a workaround or fix on the horizon?
All android* configure options will give gcc:-mandroid

**Comment by xsacha** [comment]
Can we have this issue re-opened or should I make it again? It was never resolved.
The only workaround for now is to use linux-generic32/64 target instead of android.

**Comment by petrovr** [comment]
Sacha wrote:
> Can we have this issue re-opened or should I make it again? It was never resolved.
> The only workaround for now is to use linux-generic32/64 target instead of android.
>
This issue is closed but problem not rejected - see #2229 "Build for 
Android with Clang"

**Comment by epicstar** [comment]
Was this abandoned? Looks it because #2229 is closed. If so, there should be an official workaround documented somewhere since GCC is no longer supported as of NDK16 until someone fixes OpenSSL. https://developer.android.com/ndk/downloads/revision_history.html

If it's becoming a pain for the configure script to support multiple different architectures and platforms, the team should consider something like CMake.

**Comment by yan12125** [comment]
FYI: This is fixed since version 1.1.1-pre3 (#5613, #5589)

**Comment by epicstar** [comment]
@yan12125, is there any way to backport the fix to the LTS versions (and perhaps an official patch file workaround)? We have a dependency on the LTS versions of OpenSSL for our software, and talking to the team that actually makes the software, bumping up to the non-LTS versions AND a beta version carries a lot of risk and work. We cross-compile our software with multiple other platforms (iOS, Windows, Linux, Mac), and your suggested fix makes our Android build the odd man out with what the lead quotes is a "whacko" version of OpenSSL. 

I'm currently trying to compile 1.0.2o with clang btw.

**Comment by xsacha** [comment]
@epicstar we are stuck on android NDK r15c for this exact reason.
There's honestly nothing to gain from going to r16/r17 yet.

**Comment by epicstar** [comment]
@richsalz, I've had no issues updating my cross-platform build scripts to the latest NDK version with the following libs:

* Iconv
* ICU4C
* ogg
* opus
* boost
* speex

However, the only reason why I don't really have to work hard at doing this is because I've been using the official Android standalone toolchain (which requires python): https://developer.android.com/ndk/guides/standalone_toolchain.html 

Essentially, this copies the needed files from the ndk-bundle into a standard location so that you won't have to work with the incredibly horrendous ndk-bundle folder directly. All the header files, sysroot folders, and runtimes are then put into a standard location so that you can easily pick and choose STL's, Android Sysroot versions, etc. without having to change the shell script for every NDK upgrade.

Using the standalone toolchain, I got OpenSSL to build with linux-generic32 and linux-generic64 but haven't had the chance to test out the binaries yet.

That being said, I can definitely help with converting your android-configure shell script to use the standalone toolchain, but I'll have to do that on my free time after work :(

**Comment by eighthave** [comment]
As of NDK r19, the "standalone toolchain" is now considered moot: https://developer.android.com/ndk/guides/standalone_toolchain  #8992 looks like the way forward for better clang support.

**Comment by eighthave** [comment]
Actually, I just discovered, using NDK r20, its easy to build with _clang_:
```console
$ export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
$ ./Configure android-arm -D__ANDROID_API__=16
$ make
```

**Comment by xsacha** [comment]
Surely there's more to set up than just PATH? Include locations?

**Comment by eighthave** [comment]
the NDK compilers now find their sysroot automatically, so no need for include locations for openssl, since it only uses headers and libs that are part of the NDK sysroot.

**Comment by xsacha** [comment]
Oh that is awesome. Thanks for the news.

**Comment by ejparz** [comment]
> @yan12125, is there any way to backport the fix to the LTS versions (and perhaps an official patch file workaround until then)? We have a dependency on the LTS versions of OpenSSL for our software, and talking to the team that actually makes the software, bumping up to the non-LTS versions AND a beta version carries a lot of risk and work. We cross-compile our software with multiple other platforms (iOS, Windows, Linux, Mac), and your suggested fix makes our Android build the odd man out with what the lead quotes is a "whacko" version of OpenSSL.
> 
> I'm currently trying to compile 1.0.2o with clang btw.

@epicstar We're you able to get a version of OpenSSL 1.0.2 to compile with clang for android?

If so, can you please share patch/steps to do so?

My team is currently in the following predicament:
For security reasons, we need to update our embedded linux system to use a newer version of Android (Which no longer supports gcc compiler).

However, we still need to use OpenSSL 1.0.2 in order to stay FIPS compliant (The current OpenSSL FIPS module is only compatible with OpenSSL 1.0.1 and 1.0.2), and the new OpenSSL FIPS module (Which will be compatible with new OpenSSL 3.0) will not be ready until perhaps early 2021 (https://www.openssl.org/blog/blog/2019/11/07/3.0-update/)

Any recommendations/advice on how to build OpenSSL 1.0.2 using clang would be much appreciated.

Thanks!

**Comment by ejparz** [comment]
@xsacha Yes, we can still cross compile using gcc, but for consistency, we would prefer to compile all user space apps using clang

**Comment by epicstar** [comment]
@ejparz , I was able to eventually get OpenSSL 1.0.2 compiling with clang. It was borderline impossible but was able to do it. Give me some time to figure out what I did. First thing that comes to my mind though was that I ended up using the generic linux32 and generic linux64 triplets for the arm builds.

My build scripts are different than most on the internet because I ended up using standard toolchain (python script in the NDK). It significantly simplified all the args used for compiling. However, take note now that NDK r20 deprecated the standalone toolchain because everything in the NDK is setup correctly.

I'll give you more detailed info later.
