### ISSUE TITLE
x509_pubkey_decode() does not consider algorithms provided by providers.

### ISSUE THREAD

**Issue by anhu** [openssl/openssl#15393]
`x509_pubkey_ex_d2i)()` calls x509_pubkey_decode() but it is legacy (even says so in the comments...se below) so if the algorithm is not associated with a NID, it fails. Of course, this can happen if the algorithm is provided via a provider. 

```
/*
 * Attempt to decode a public key.
 * Returns 1 on success, 0 for a decode failure and -1 for a fatal
 * error e.g. malloc failure.
 *
 * This function is #legacy.
 */
static int x509_pubkey_decode(EVP_PKEY **ppkey, const X509_PUBKEY *key)

```

**Comment by levitte** [comment]
> so if the algorithm is not associated with a NID, it fails. Of course, this can happen if the algorithm is provided via a provider.

Yes?  This is by design, and is reflected in this code:

https://github.com/openssl/openssl/blob/cc9f9b98997ce3aca276dc6dbbe6d98efab4e65d/crypto/x509/x_pubkey.c#L137-L168

In other words, we *try* to use it first, and if that fails (non-fatally), we then try with provider friendly code.

It seems we missed something, though.  This is currently investigated...

**Comment by mattcaswell** [comment]
This seems related to #15327.

**Comment by levitte** [comment]
Yes, thanks for the reminder

**Comment by anhu** [comment]
@levitte said:
> ... we try to use it first, and if that fails (non-fatally), we then try with provider friendly code.

No, according to what I'm seeing, if there is no ameth, libcrypto will not look for decoders in the  providers.

**Comment by mattcaswell** [comment]
I'm working on fixes in this area...watch this space...

**Comment by anhu** [comment]
@mattcaswell  : Thanks for letting me know.  I'll keep my eyes peeled!  :+1:
