### ISSUE TITLE
Checkdocs CI looks like has a internal failure that is not marked as an error.

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#15449]
It looks like the CI loop is reporting that checkdocs is successful currently..
If you look at the output from docnits - it does not look so good.

Complex regular subexpression recursion limit (65534) exceeded at ./util/find-doc-nits line 1004.
This seems to be related to the rather large migration_guide.pod.

**Comment by levitte** [comment]
So, it seems that this particular error doesn't cause an exception (no `die` at least), that's why it's undetected.  From debugging printing I just did, it appears we still get a list of links, only surprisingly small.

I'm currently running doc-nits with added regexp debugging enabled around that code section to find out what's really going on.
It may be as simple as having to run this regexp in a while loop and manually push $1 to @lists...

**Comment by levitte** [comment]
Fix in #15450

**Comment by romen** [comment]
This was already reported in #15407: I marked that as duplicate even if it predates this issue, just because most of the relevant discussion happened here.
