### ISSUE TITLE
Strange GCC complains building master

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#15497]
Many of them, mostly about the tests, looking this way:

```
${LDCMD:-gcc} -pthread -m64 -Wa,--noexecstack -Wall -O3 -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wa,--noexecstack -Wa,--generate-missing-build-notes=yes -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  -Wl,-z,relro -Wl,--as-needed -Wl,-z,now \
	-o test/ffc_internal_test \
	test/ffc_internal_test-bin-ffc_internal_test.o \
	test/libtestutil.a libcrypto.a -lz -ldl -pthread 
In function 'CRYPTO_free',
    inlined from 'BN_RECP_CTX_free' at crypto/bn/bn_recp.c:42:9,
    inlined from 'BN_RECP_CTX_free' at crypto/bn/bn_recp.c:35:6,
    inlined from 'BN_mod_exp_recp' at crypto/bn/bn_exp.c:290:5:
crypto/mem.c:252:5: warning: attempt to free a non-heap object 'recp' [-Wfree-nonheap-object]
  252 |     free(str);
      |     ^
```

gcc version 10.3.1 20210422 (Red Hat 10.3.1-1) (GCC)

**Comment by levitte** [comment]
It's because it's a "trick" to be able to "free" stack allocated variables (i.e. their contents)...  there's a flag in the `BN_RECP_CTX` to indicate if the recp structure was malloced or not, but GCC doesn't know how to process it:

https://github.com/openssl/openssl/blob/91f2b15f2ecd9dd92b6ed2563b10c1a126db2643/crypto/bn/bn_recp.c#L41-L42

End result, GCC flags a potential fuck-up, and for good reason.  This is an ugly "convenience hack"

**Comment by beldmit** [comment]
Thanks!

**Comment by t8m** [comment]
This kind of trick is used at many places in OpenSSL code so unfortunately this warning is useless when building OpenSSL.

**Comment by Mulling** [comment]
`-Wfree-nonheap-object` only triggers this warning in `BN_mod_exp_recp` even though this "trick" is used in several places. Couldn't this be solved by just adding `BN_RECP_CTX_free_static`?
