### ISSUE TITLE
How to solve the Error Configuring Openssl error on Kali WSL?

### ISSUE THREAD

**Issue by MrUndead13** [openssl/openssl#15623]
Good afternoon,
Whenever I try to use Openssl on my Kali Linux (used with Windows Linux Subsystem), I get the following error:

Error configuring OpenSSL
14096613411322780475:error:2507006C:DSO support routines:DSO_load:functionality not supported:dso/dso_lib.c:224:
14096613411322780475:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf/conf_mod.c:274:module=ssl_conf, path=ssl_conf
14096613411322780475:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf/conf_mod.c:214:module=ssl_conf
failed to load configuration

Would anyone understand what's wrong and have a fix for that please ?

Thanks in advance.

**Comment by mattcaswell** [comment]
What version of OpenSSL is this?

> Whenever I try to use Openssl

When you say "use OpenSSL" what do you mean? Is this the command line application you are trying or an application using the library?

**Comment by MrUndead13** [comment]
This is the thing, I can't even check the version, since when I type any command line with openssl, I get this error.

This is command line application. Like "openssl ...." with different flags.

**Comment by mattcaswell** [comment]
Locate where the openssl binary is:

````
$ which openssl
/usr/local/bin/openssl
````

Then please report the results from running this:
````
$ ldd /path/to/openssl
````

**Comment by mattcaswell** [comment]
Also you might try this:

````
$ OPENSSL_CONF=doesnotexist.cnf openssl version
````

**Comment by MrUndead13** [comment]
I remember trying to find the path and I was able to find two different paths following two different methods.
Doing the one you showed give me this : "/usr/local/bin/openssl"

However trying this "ldd /path/to/openssl", I get this: "ldd: /path/to/openssl: No such file or directory"

Finally, the last one gives me this : "WARNING: can't open config file: doesnotexist.cnf
LibreSSL 2.1.6"

**Comment by mattcaswell** [comment]
> ldd: /path/to/openssl: No such file or directory

I meant for you to replace "/path/to/openssl" with the actual path that "which openssl" returned, e.g. "ldd /usr/local/bin/openssl" :-)

But never mind. This gives me what I needed:

> LibreSSL 2.1.6

This is not OpenSSL at all. It is LibreSSL.

Most likely your config file has an "ssl_conf = what-ever" section in it. But invoking the LibreSSL command line doesn't know how to handle it because (unlike OpenSSL) it doesn't initialise the ssl_conf module by default. At least I don't think it does (I don't really know LibreSSL).

If you do this:

````
$ OPENSSL_CONF=doesnotexist.cnf openssl version -d
````
It should tell you the location of OPENSSLDIR. In that directory you will hopefully find the openssl config file "openssl.cnf".

Commenting out the line in that config file that starts "ssl_conf = ..." should hopefully solve the problem. However if there are any applications that are *using* that "ssl_conf" line then it might impact/break them.

An alternative solution is to take a local copy of the global config file and comment out the line in your local copy. Then set an environment variable "OPENSSL_CONF" to point to your local copy of the config file. That way it will only impact applications started explicitly by you.

**Comment by MrUndead13** [comment]
Oh my bad.....

So I copied the config file (with cp) and put in another directory. I modified it (with nano).
However for the variable I'm not sure, should I only do "OPENSSL_CONF=openssl.cnf" ?

Should I call openssl command line after that of is there another one for libressl ?

**Comment by mattcaswell** [comment]
To set the variable:

````
$ export OPENSSL_CONF=/full/path/to/openssl.cnf
````

Replacing "/full/path/to/openssl.cnf" with the actual full path to the file!
After that just use the openssl command line. There isn't a separate command for libressl. LibreSSL provides an alternative implementation of the OpenSSL command - but its called the same thing.

**Comment by MrUndead13** [comment]
It worked like a charm ! Thank you so much for that and for your patience (I'm a big nooby ^^).
Have a nice evening !

**Comment by mattcaswell** [comment]
Great. Glad it worked. Closing this.
