### ISSUE TITLE
What can I do if the DTLS cannot detect the status of the peer link ? One of them  restarts after the handshake is finish.

### ISSUE THREAD

**Issue by yangyangtiantianlonglong** [openssl/openssl#15651]
I can't set up a heartbeat mechanism because the peer is a third party. For example,  After the client and server finish, the client restarts due to some reason. The client initiates a handshake again, but the server is still in the finish state. 
  I didn't find a way to deal with it in rfc6347. Should the app on the server parse the client hello no-cookie, release the SSL, and start over?
  I look forward to hearing from you.  Thanks.

**Comment by mattcaswell** [comment]
> Should the app on the server parse the client hello no-cookie, release the SSL, and start over?

It *could* although that gives an avenue for a denial of service attack, or possibly a truncation attack. A client hello with no cookie is totally unverified and could come from anyone, so an attacker could send spurious client hellos in order to induce the dropping of the connection, or to stop processing at a given point before the "real" client has finished.

An alternative might be to just timeout the connection if you've not received application data after a given period.

**Comment by yangyangtiantianlonglong** [comment]
OK, thank you for your detailed answer. Timeout disconnection may affect the customer's experience, I'll see in https://github.com/tlswg/dtls13-spec/issues/248 if I can get some help.
