### ISSUE TITLE
Why the deprecated API is still being used in default provider implemention?

### ISSUE THREAD

**Issue by lgynju** [openssl/openssl#15891]
we want to build a 3rd-party provider by referring default provider, As we know, the deprecated API will be removed sooner or later, but in the latest branch, we found it is still being used in the default provider, for example `RSA_size()`, so if we don't want to use the deprecated API, which provider can we refer to now?

**Comment by levitte** [comment]
> the deprecated API will be removed sooner or later,

... removed *from public view*.  That doesn't mean that they stop existing internally.

**Comment by levitte** [comment]
OpenSSL's providers aren't the best example of how to do things right, because of the fairly unusual entanglement with functions offered directly by libcrypto (albeit deprecared for the most part).  You may have better luck looking at other 3rd party providers.  A few that I know are listed in https://github.com/provider-corner/provider-corner/README.md

At some point, when the deprecated functions are removed from public view, I expect that we will shuffle around some source to make it cleaner.

**Comment by mattcaswell** [comment]
> for example RSA_size(), so if we don't want to use the deprecated API, which provider can we refer to now?

As @levitte says these APIs will eventually be removed from the public API so application's cannot call them directly. However they remain as our low level interface to the RSA algorithm. Therefore OpenSSL's own default provider will continue to call them even after they have gone from public view.
