### ISSUE TITLE
decode sm2 pem private key error

### ISSUE THREAD

**Issue by zhenyuwei** [openssl/openssl#16000]
when use `openssl ec -in test/certs/sm2-root.key -text` decode sm2 private key, i find p_lib.c code:
```
int EVP_PKEY_set_params(EVP_PKEY *pkey, OSSL_PARAM params[])
{
    if (pkey != NULL) {
        if (evp_pkey_is_provided(pkey)) {
            pkey->dirty_cnt++;
            return evp_keymgmt_set_params(pkey->keymgmt, pkey->keydata, params);
        }
```
I'm not find EVP_KEYMGMT about sm2, OpenSSL-1.1.1 have sm2_pmeth.c file, but 3.0 remove it, please fix it.

 ```shell
error:030000A3:digital envelope routines:EVP_PKEY_set_params:invalid key:crypto/evp/p_lib.c:2312
```

**Comment by levitte** [comment]
OpenSSL 3.0 makes a bigger difference between EC and SM2 keys, i.e. SM2 keys are no longer EC key aliases, but a separate key type.  This was necessary, because despite of their *structural* similarity, the *methods* to generate them and to calculate signatures with them differs from how normal EC keys are used.

I would recommend using `openssl pkey` rather than `openssl ec` anyway, because of better generality.
