### ISSUE TITLE
CMP: KUR operation fails if the old and the new certificates are different

### ISSUE THREAD

**Issue by gotthardp** [openssl/openssl#16041]
The https://github.com/openssl/openssl/commit/66be663b64e05fb5524edd051b85fb919f59e054 introduced the following check used during CMP KUR:

https://github.com/openssl/openssl/blob/0007ff257c95f5cd046799e492436f41caf4ecb2/apps/lib/cmp_mock_srv.c#L230-L235

It compares a serialNumber of `cid = OSSL_CRMF_MSG_get0_regCtrl_oldCertID(crm)`, which is the **old** (to be updated) certificate
with `serial = X509_get0_serialNumber(ctx->certOut)` of the **updated** (new) certificate.
The check fails if the serial numbers are different, which feels wrong-- the serial numbers should be different, right? (Or did I miunderstood something?) The mock server should rather ensure the serial number of the old and the new certificate are not equal, i.e. the condition should be IMO reversed.

This is not detected by the tests because the tests seem to use a single certificate only, both the old and the new certificate used to test KUR are identical (`test/recipes/80-test_cmp_http_data/Mock/signer_only.crt`) and thus have the same serial number, so the test passes.

**Comment by DDvO** [comment]
Thanks @gotthardp for your feedback on the CMP mock/test server.
I very much appreciate this in particular because it is the first issue raised here regarding CMP semantics.

You are right that the behavior of the mock server appears pretty strange regarding the checks on the `oldCertID` in `kur` messages.
This is because for the HTTP-based OpenSSL-internal CMP test cases the mock server old deals, as you noticed, with a single certificate.
For this reason, the short-circuit comparison given in `cmp_mock_srv.c` is sufficient but at least would have deserved an explaining comment and documentation.

In order to make the mock server more generally useful, I've extended it in #16050 by giving the option to specify an independent reference certificate to be used for the checks done for `kur`and `rr` messages.

On this occasion I've also corrected the verbosity option handling of the CMP server (and also of the HTTP server) in #16051.

**Comment by DDvO** [comment]
@gotthardp, finally the fix for this issue has been approved and merged.
Unfortunately the fix did not make it into 3.0, and neither into 3.0.1,
yet it will become part of OpenSSL 3.1.

**Comment by gotthardp** [comment]
@DDvO, thank you very much!

**Comment by ayushiays** [comment]
I see the fix is still not available in 3.1.1 version. Can someone confirm in which release this change is expected?

**Comment by t8m** [comment]
This is going to be fixed in 3.2.0 release.

**Comment by DDvO** [comment]
> I see the fix is still not available in 3.1.1 version.

What I had written in early Jan 2020 about version 3.1 became obsolete 
after it became clear that OpenSSL 3.1 is about FIPS only. 
Everything else goes into 3.2+.

**Comment by ayushiays** [comment]
Thanks  @t8m @DDvO 

Any tentative date for 3.2.0 release?
