### ISSUE TITLE
EVP_get_default_properties

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#16245]
Do we need this function to find out what's going on fetching?

**Comment by t8m** [comment]
IMO this might be useful function but it is clearly Post 3.0 feature.

**Comment by beldmit** [comment]
For me it looks like a missing accessor :)

**Comment by t8m** [comment]
Then it might be added in 3.0.1 even. But IMO not for 3.0.0.

**Comment by selvanair** [comment]
Any plans of adding this?

**Comment by paulidale** [comment]
We didn't include it because it is the calling application that sets the default properties and thus should know what it set.

**Comment by selvanair** [comment]
It could be loaded from the config file as well, isn't it? is there an easy way to know what was set that way?

**Comment by paulidale** [comment]
Yes it could come from config.

My question is what is the use case?  Using it to fetch an algorithm isn't one since it does that already.  Overriding, augmenting or replacing part of the default is also possible already.  I guess it could be printed.

**Comment by selvanair** [comment]
I'm not saying its a missing _accessor_. It's useful information, and it looks not hard for the library to make it available for its consumers.

My use case is replacing the default when necessary and then reverting back to what the user specified in the config file.

Also, in existing applications with API calls where the default propq may get used under the wraps, a clear idea of what is in the default is useful for application authors. If only to print a proper error message in some cases.

One could say an application should use a custom config file and control what is in it. But there are many applications that loads default config file and changing that is not easy.

By "augmenting", do you mean to add an explicit propq in function calls so that it will get merged with the default? Doing that without knowing what one is "augmenting" is like working in the dark.

That said, one of the many things that I didn't know was that when default propq is merged with the one set explicitly in the function call, the latter overrides the former for matching names. E.g., with "provider=foo" in defaults, setting "?provider=foo" in a function call ignores the default and takes the latter. I expected the stronger directive of the two (the default in this case) to prevail. The docs are less than clear on the merging rules. Had to read the source to figure this out.

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by beldmit** [comment]
I'd consider this feature useful

**Comment by nhorman** [comment]
@beldmit Are you willing/able to put together a PR for this?  If so, i'll happily mark it as a community issue for you.  I just don't think we're going to dedicate openssl resources to addressing this in the foreseeable future

**Comment by Phani-Sreenivasa-Prasad** [comment]
@nhorman @beldmit Any update on this issue?
We also have similar situation.  we are setting the default_properties flag as below in the conf file to enable FIPS mode.
**default_properties = ?fips=yes** ( this enables fallback from fips to default provider).

Then again  using EVP_default_properties_is_fips_enabled() is returning false. So having an API such as [EVP_get_default_properties] would be much useful.

**Comment by simo5** [comment]
it should be EVP_CTX_get_properties(libctx), and should return the default properties set in openssl.cnf for the default context if no properties were set by the application.

**Comment by selvanair** [comment]
> @beldmit Are you willing/able to put together a PR for this? If so, i'll happily mark it as a community issue for you. I just don't think we're going to dedicate openssl resources to addressing this in the foreseeable future

Why wouldn't you? I would consider this an essential feature for applications that load user-defined  provider libraries and config files.

**Comment by simo5** [comment]
For the uses case I am interested in it may suffice to have a new call that creates a libctx inheriting all the configs from a parent context (usually the default context).
This is because there is a real use case for libraries wanting to do some changes to the context that should not propagate to the main application or other libraries, but they want to start from the same conditions and configurations of the application provided context (or the default one) so that applications can control defaults.

This kind of inheritance is very important in complex integrations, where you may have several layers of indirection between application and libraries used, and several distinct uses of openssl by different libraries.

**Comment by mattcaswell** [comment]
This looks straight forward to add if anyone has the inclination. We have an internal function for this already - so it looks to me like a simple matter of putting a public API wrapper around it:

https://github.com/openssl/openssl/blob/e8498dc6455fc36f70dc3a0ca1ef82b34c088a90/crypto/evp/evp_fetch.c#L558-L582

Mostly I suppose the effort is writing some documentation and putting some kind of test in place.

**Comment by beldmit** [comment]
Implemented via #25434, closing
