### ISSUE TITLE
OpenSSL 3.0.0-beta2 incorrectly building libs into the 'lib64' folder.

### ISSUE THREAD

**Issue by dbcbt** [openssl/openssl#16244]
Building OpenSSL 3.0.0-beta2 on Ubuntu 20.04 64-bit / gcc-10 is now writing the libs to 'lib64' whereas OpenSSL 3.0.0-beta1 wrote them to 'lib' as with OpenSSL 1.1.1i.

Attached is the output from perl configdata.pm --dump

As a result if I then try to build with libCurl it fails to find the OpenSSL libraries and causes undefines.
I've worked around this issue temporarily by creating a symbolic link from lib64 to lib.

[dump_output.txt](https://github.com/openssl/openssl/files/6945023/dump_output.txt)

**Comment by t8m** [comment]
This is caused by 74b7f339aa58af57c0e71b7efca66e6f2db5ae2e

But I do not think completely reverting it would be a good idea either. Perhaps we could somehow detect that the system is using a multilib layout in the Red Hat/Fedora way vs. the Debian way?

Or we could add a way how to easily override adding the multilib postfix? I.e., add no-multilib configure option?

**Comment by t8m** [comment]
As a workaround, you can use --libdir to specify the libdir explicitly.

**Comment by dbcbt** [comment]
Thanks @t8m for the quick response and workaround.

**Comment by t8m** [comment]
Maybe the workaround is good enough and we just document it?

**Comment by mattcaswell** [comment]
OTC: This should be treated as a documentation problem. There should be a CHANGES entry for the new behaviour.

**Comment by t8m** [comment]
Doc fix in #16281
