### ISSUE TITLE
i2d_x509 now fails in 3.0.0

### ISSUE THREAD

**Issue by kgold2** [openssl/openssl#16257]
I have an application where I create a partial x509 certificate.  It gets sent to an HSM, which adds the public key and signs it. 

I do essentially this to build the X509 structure::

    X509_new
    X509_set_version
    X509_set_issuer_name
    X509_get_notBefore
    X509_get_notAfter
    X509_set_subject_name
    X509_EXTENSION_create_by_OBJ
    i2d_x509 

This worked in 1.0.1, 1.0.2, 1.1.1, but fails in 3.0.0.

In debugging, even this simple test case now fails.

    X509_new
    i2d_x509 

I tried including everything except the signature, omitting just

    X509_sign

and it also failed.

I also tried replacing i2d_x509 with i2d_re_X509_tbs and it also failed.

It could be user error, but this has been working for many years.

**Comment by t8m** [comment]
I am afraid with the current 3.0 codebase there are not many options
how to workaround this problem apart from either signing the certificate with a
bogus key - if the HSM is able to re-sign such certificate.

Another (more complicated) option would be to define your own ASN.1
X509 structure where the signature would be optional and thus the
stricter encoder that is now in 3.0 codebase would allow encoding the
incomplete certificate.

**Comment by kgold2** [comment]
The HSM follows ISO-11889 and cannot be changed.  It adds the public key after checking the attributes, and then signs it.
I don't understand the 'revert ... on 1.1.1'.  1.1.1k and previous all worked.  The regression is on 3.0.0.

**Comment by davidben** [comment]
Is ISO-11889 the same document as document 1A [here](https://trustedcomputinggroup.org/resource/tpm-library-specification/)? I can find references to "partialCertificate", but no clear definition as to what a partial certificate is.

The TBSCertificate structure defined in RFC5280 does not mark the SPKI as OPTIONAL, so simply omitting it does not produce the same structure. Is the expectation to omit it, or to insert some empty placeholder instead?

In order to support this non-certificate structure, I think the bare minimum is that someone has even written down what it is.

**Comment by davidben** [comment]
Aha, found it in part 3, 18.8.1. Looks like this is an entirely different structure that not only omits the public key, but also the version. And if makes the signature algorithm optional. I think this should be a separate API, for serializing a "TPM Partial Certificate", which is a related but different animal from "X.509 Certificate".

**Comment by davidben** [comment]
Here's some sample code for how to use OpenSSL's ASN.1 template APIs to transcript the non-certificate structure in the TPM spec. This should work both before and after the bugfix. You also can call `i2d_X509_NAME`, etc., and assemble it using your favorite DER encoder.

```
#include <openssl/asn1.h>
#include <openssl/asn1t.h>
#include <openssl/x509.h>
#include <stdio.h>
#include <string.h>
#include <time.h>

typedef struct {
  ASN1_TIME *notBefore;
  ASN1_TIME *notAfter;
} TPM_PARTIAL_CERT_VALIDITY;

typedef struct {
  X509_ALGOR *algorithm;
  X509_NAME *issuer;
  TPM_PARTIAL_CERT_VALIDITY *validity;
  X509_NAME *subject;
  STACK_OF(X509_EXTENSION) *extensions;
} TPM_PARTIAL_CERT;

ASN1_SEQUENCE(TPM_PARTIAL_CERT_VALIDITY) = {
  ASN1_SIMPLE(TPM_PARTIAL_CERT_VALIDITY, notBefore, ASN1_TIME),
  ASN1_SIMPLE(TPM_PARTIAL_CERT_VALIDITY, notAfter, ASN1_TIME),
} ASN1_SEQUENCE_END(TPM_PARTIAL_CERT_VALIDITY)

// Note, per 18.8.1, the signature algorithm is optional while the extension
// list is required.
ASN1_SEQUENCE(TPM_PARTIAL_CERT) = {
  ASN1_OPT(TPM_PARTIAL_CERT, algorithm, X509_ALGOR),
  ASN1_SIMPLE(TPM_PARTIAL_CERT, issuer, X509_NAME),
  ASN1_SIMPLE(TPM_PARTIAL_CERT, validity, TPM_PARTIAL_CERT_VALIDITY),
  ASN1_SIMPLE(TPM_PARTIAL_CERT, subject, X509_NAME),
  ASN1_EXP_SEQUENCE_OF(TPM_PARTIAL_CERT, extensions, X509_EXTENSION, 3),
} ASN1_SEQUENCE_END(TPM_PARTIAL_CERT)

IMPLEMENT_ASN1_FUNCTIONS(TPM_PARTIAL_CERT)

int main() {
  // Fill in some placeholder values, just to demonstrate this works. Missing
  // error-handling and whatnot.
  TPM_PARTIAL_CERT *cert = TPM_PARTIAL_CERT_new();
  X509_NAME_add_entry_by_NID(cert->issuer, NID_commonName, MBSTRING_UTF8, "A",
                             1, -1, 0);
  time_t now = time(NULL);
  ASN1_TIME_adj(cert->validity->notBefore, now, 0, -24 * 60 * 60);
  ASN1_TIME_adj(cert->validity->notAfter, now, 0, 24 * 60 * 60);
  X509_NAME_add_entry_by_NID(cert->subject, NID_commonName, MBSTRING_UTF8, "B",
                             1, -1, 0);

  unsigned char *der = NULL;
  int der_len = i2d_TPM_PARTIAL_CERT(cert, &der);
  fwrite(der, der_len, 1, stdout);

  TPM_PARTIAL_CERT_free(cert);
  OPENSSL_free(der);
  return 0;
}
```

**Comment by t8m** [comment]
OTC: there is a proper way how to do this presented above. The i2d should not create invalid encodings. We are not going to revert this change.

**Comment by kgold2** [comment]
> Here's some sample code for how to use OpenSSL's ASN.1 template APIs to transcript the non-certificate structure in the TPM spec. This should work both before and after the bugfix. You also can call `i2d_X509_NAME`, etc., and assemble it using your favorite DER encoder.

t.c:24: warning: no previous prototype for 'TPM_PARTIAL_CERT_VALIDITY_it'
t.c:34: warning: no previous prototype for 'TPM_PARTIAL_CERT_it'
t.c:36: warning: no previous prototype for 'd2i_TPM_PARTIAL_CERT'
t.c:36: warning: no previous prototype for 'i2d_TPM_PARTIAL_CERT'
t.c:36: warning: no previous prototype for 'TPM_PARTIAL_CERT_new'
t.c:36: warning: no previous prototype for 'TPM_PARTIAL_CERT_free'

Was this code complete?
What does "assemble it using your favorite DER encoder" mean?

**Comment by davidben** [comment]
> t.c:24: warning: no previous prototype for 'TPM_PARTIAL_CERT_VALIDITY_it'

Perhaps you're building with more warnings then whatever my GCC had on by default. Try adding `DECLARE_ASN1_ITEM(TPM_PARTIAL_CERT_VALIDITY)`  and `DECLARE_ASN1_FUNCTIONS(TPM_PARTIAL_CERT)`. Normally these various bits would be split between header and source file, but I skipped all that for brevity. I also haven't checked if this is something that was changed in 3.0.0.

The important bit is that this is a different ASN.1 type and, from the beginning, your code should have reflected that. OpenSSL's X.509 encoder isn't magic. It's just encoding stuff according to DER. That omitting fields worked in `d2i_X509` was just a bug.

> What does "assemble it using your favorite DER encoder" mean?

Certificates use an encoding called DER. If you're unfamiliar with it, you can read about it here:
https://letsencrypt.org/docs/a-warm-welcome-to-asn1-and-der/

If you have a preferred DER encoder on hand, you can also just ask OpenSSL to encode the various fields, concatenate them and wrap it in a SEQUENCE. (E.g. the library I work on has this imperative encoding library, since I don't like the macro tables business.) But using OpenSSL's macros works just fine. I believe those are public API.
