### ISSUE TITLE
Revert refusal of encoding ASN.1 structures with non-optional items missing on 1.1.1

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#16266]
The refusal to encode ASN.1 structures with non-optional items missing breaks some valid applications that worked fine before. See for example #16257

We should revert it at least on the 1.1.1 branch. (I.e., revert commits merged from #16027 )

**Comment by kgold2** [comment]
Referring to #16257, this worked on 1.1.1k (and all the way back to 1.0.2).  It is only a regression on 3.0.0.  I hope it can be fixed on 3.0.0, because it breaks my application.

**Comment by t8m** [comment]
It was changed for a reason so I am not sure it will be reverted on 3.0.0. However the change is also present in 1.1.1 git branch where it should be IMO reverted before any further 1.1.1 release as the change is apparently too disruptive.

**Comment by kgold2** [comment]
I suggested, on the other issue, to add a new API rather than break an existing one.  IMHO, that's a general statement.
I surely believe it should be reverted on 1.1.1.  The naming convention says that all 1.x releases are API/ABI compatible.  While it's undesirable in 3.x, the change should be forbidden in 1.x.  I.e., it's not a bug fix or a new feature.

**Comment by davidben** [comment]
It is definitely a bugfix. Whether it's compatible enough for 1.1.x is another question, but omitting optional items produces an unparsable, sometimes even ambiguous, structure.

For a long-term, supported answer, looking at where these partialCertificate structures come from, this isn't a certificate in the first place. Even the TPM specification defines it as a separate structure. See https://github.com/openssl/openssl/issues/16257#issuecomment-895368215. So you're right that it should be a new API, but it's the TPM stuff that should go through the new API, and `i2d_X509` remains for its stated use: certificates.

Indeed had the "embed" optimization been applied to `X509_CINF.key`, like it was applied to many other fields, I think the TPM stuff would have broken too. It's relying on some internal implementation details of the `X509` object that don't match RFC5280.

**Comment by kgold2** [comment]
It certainly was not unparsable.  It was quite useful.  I know the TPM spec - I'm the editor.  ;-)

If 3.x can create a new d2i_x509-ignoring-missing-files, I can deal with that.  

Should I do a feature request?

**Comment by davidben** [comment]
It's unparsable as an X.509 Certificate or TBSCertificate, which is what `i2d_X509` is intended to produce. And, in general, it is even ambiguous because ASN.1 only requires that tags disambiguate omitted fields when they're OPTIONAL or DEFAULT.

The TPM spec, while not quite correctly written (it should have defined an actual ASN.1 structure), does correctly describe it as a distinct structure from X.509's Certificate or TBSCertificate. This should be reflected in code: don't rely on bugs in `i2d_X509`, but serialize your own structure. See https://github.com/openssl/openssl/issues/16257#issuecomment-895448370 for an example. This doesn't require new features from OpenSSL because OpenSSL already gives you the tools to define your own structures.

An `i2d_X509_ignore_missing` would also not be right because it presumes "missing" is even a possible state for an `X509` object. Indeed observe how `X509_CINF.signature` is now not a pointer, but directly embedded in the structure. This is counter to the TPM specification, which believes the signature algorithm is optional. Using your own structure would let you capture what the TPM specification says.

**Comment by romen** [comment]
For the record, as the disucssion is spread across separate issues, in https://github.com/openssl/openssl/issues/16257#issuecomment-895448370 @davidben suggests a workaround that would allow applicaitons depending on the previous buggy behavior to achieve the same goal without "abusing" the x509 API.

**Comment by mattcaswell** [comment]
An OTC vote has started on this topic:

topic: Revert the commits merged from PR #16027 in 1.1.1

**Comment by t8m** [comment]
> An OTC vote has started on this topic:
> 
> topic: Revert the commits merged from PR #16027 in 1.1.1

The vote is now closed and it was accepted. So this revert should happen. I'll prepare a PR.

**Comment by t8m** [comment]
The revert happened.
