### ISSUE TITLE
Fill in public key info from private key info?

### ISSUE THREAD

**Issue by nikic** [openssl/openssl#16267]
When creating a DH key using EVP_PKEY_fromdata using the FFC_P, FFC_G and PRIV_KEY parameters, this will result in a key that only contains the private key information, but not the public key information. Is there some way to generate the public key from the private key using the EVP_PKEY API?

We currently have some code that manually computes the public key using BN_mod_exp_mont, which seems extremely dangerous to me, but I couldn't find a suitable API for this purpose.

**Comment by t8m** [comment]
Hmm, this looks like a serious deficiency of the new API when compared to the deprecated low level DH calls. The DH_generate_key() allowed computing just the public key when a private key was already present in the DH structure.

We could use that functionality with EVP_PKEY_gen() however the DH provider implementation does not allow skipping the parameter generation. This looks like a major defect and IMO it can be easily fixable before the release. But giving this is kind of new functionality in the provider(s) I think we need to discuss it within OTC first.

**Comment by beldmit** [comment]
Do we have this problem only for DH?

**Comment by nikic** [comment]
I think the API problem (compute public key from private key) is a general one, but DH might be the only case where the low-level API provided a way to do so. I think most other key generation functions would always generate a full keypair, even if a private key was already present. At least that's the case for DSA_generate_key and EC_KEY_generate_key.

**Comment by romen** [comment]
This problem was discussed back when OTC decided to change the convention for EVP_PKEY objects and consider valid also keys which only include the private components.

From that discussion, I will remark that, from a security perspective, it is paramount that, if public components are to be derived from the private ones, they must be generated when they key is first initialized, not on demand when an operation needs them.

**Comment by t8m** [comment]
OTC: this is missing feature which we are not going to add in 3.0. We will consider this Post 3.0.

**Comment by baentsch** [comment]
> Do we have this problem only for DH?

No, this issue also exists for quantum-safe/post-quantum crypto: [One cannot re-create public from private keys for all algorithms there](https://github.com/PQClean/PQClean/issues/415#issuecomment-910377682).

> when OTC decided to change the convention for EVP_PKEY objects and consider valid also keys which only include the private components

Is this decision/position firm? It seems to contradict this statement from https://www.openssl.org/docs/manmaster/man3/EVP_PKEY_eq.html: 

> Since OpenSSL private keys contain public key components too the function EVP_PKEY_eq() can also be used to determine if a private key matches a public key

Reason for asking: When implementing a QSC/PQC decoder (decoding a private key) in an external provider, due to the PQ math limitation stated above, a full key pair cannot be re-generated and subsequent key equality tests "become a challenge"...

Thus, and in light of the apparent OTC decision, would it be reasonable to ask for the adaptation of the above statement in `EVP_PKEY_eq` documentation and probably for a change to the corresponding logic here: https://github.com/openssl/openssl/blob/8b6a7da304d4fdd0de38ddd6037d8a02491e3e4e/crypto/evp/p_lib.c#L344-L346 which seems to equate EVP_PKEY equality with public key material equality (?). This would eliminate the need for "special" key matching code in the [oqsprovider](https://github.com/open-quantum-safe/oqs-provider).

**Comment by levitte** [comment]
> > when OTC decided to change the convention for EVP_PKEY objects and consider valid also keys which only include the private components
> 
> Is this decision/position firm? It seems to contradict this statement from https://www.openssl.org/docs/manmaster/man3/EVP_PKEY_eq.html:
> 
> > Since OpenSSL private keys contain public key components too the function EVP_PKEY_eq() can also be used to determine if a private key matches a public key

...

> Thus, and in light of the apparent OTC decision, would it be reasonable to ask for the adaptation of the above statement in `EVP_PKEY_eq` documentation and probably for a change to the corresponding logic here:
> 
> https://github.com/openssl/openssl/blob/8b6a7da304d4fdd0de38ddd6037d8a02491e3e4e/crypto/evp/p_lib.c#L344-L346
> which seems to equate EVP_PKEY equality with public key material equality (?). This would eliminate the need for "special" key matching code in the [oqsprovider](https://github.com/open-quantum-safe/oqs-provider).

This is a reasonable idea, and is quite easy, just change `SELECT_PARAMETERS | OSSL_KEYMGMT_SELECT_PUBLIC_KEY` to `SELECT_PARAMETERS | OSSL_KEYMGMT_SELECT_KEYPAIR`.  The documentation will have to be altered, though, since the "explanation" is no longer valid as written (this holds true either way).

**Comment by baentsch** [comment]
> This is a reasonable idea, and is quite easy, just change SELECT_PARAMETERS | OSSL_KEYMGMT_SELECT_PUBLIC_KEY to SELECT_PARAMETERS | OSSL_KEYMGMT_SELECT_KEYPAIR. The documentation will have to be altered, though, since the "explanation" is no longer valid as written (this holds true either way).

Thanks for taking this up with #16704. The proposed change above makes me wonder though whether I understood the selection bits correctly: Wouldn't setting `OSSL_KEYMGMT_SELECT_KEYPAIR` mean that both public _and_ private key must be compared and matched (in the provider's key management `match` function)? Am I wrong in this understanding? My original assumption/proposal was to simply drop `OSSL_KEYMGMT_SELECT_PUBLIC_KEY` from `SELECT_PARAMETERS | OSSL_KEYMGMT_SELECT_PUBLIC_KEY` (and adapt the documentation, of course).

**Comment by levitte** [comment]
The way selectors have been specified (and implemented *mostly*) is a set of bits of what's *desired*, but leaving it to the backend implementations to decide what's *reasonable*.

This comment says a little more about that (and it's possible that it should be uncommented):

https://github.com/openssl/openssl/blob/398ae8231650c4bd8ddff0e5efd38233c23b1ca0/doc/man7/provider-keymgmt.pod#L203-L208

**Comment by levitte** [comment]
Could we discuss EVP_PKEY_eq() in #16704, please?

**Comment by nhorman** [comment]
it is unclear to me what the path forward in this issue is.  The initial comment suggests that there is a desire to have an api to compute a DH public key from the private key, but @romen comment strongly suggests that doing so is a security concern, implying that such an api not be provided.

@nikic @romen @t8m any comment here?  Trying to decide if this  should be categorized for a future minor release, or marked as done/not planned

**Comment by baentsch** [comment]
> if this should be categorized for a future minor release, or marked as done/not planned

FWIW, I'd vote for the latter if the topic is not re-labelled to explicitly refer to DH keys as I do not see this as technically possible for _all_ (incl. provided) key types and I think this comment by @romen goes in the same direction:

> From that discussion, I will remark that, from a security perspective, it is paramount that, if public components are to be derived from the private ones, they must be generated when they key is first initialized, not on demand when an operation needs them.

**Comment by nhorman** [comment]
ack, marking as inactive, to be closed at the end of 3.4 dev

**Comment by baentsch** [comment]
Tagging @nhorman as to whether it's intentional that this has not been closed? Tagging @t8m as a reference to the discussion around "do keys always (need/have to) contain a public part?"

**Comment by nhorman** [comment]
No, it should be closed, just hadn't gotten to it
