### ISSUE TITLE
Are RSA keys with p/q but without CRT parameters valid?

### ISSUE THREAD

**Issue by nikic** [openssl/openssl#16271]
When creating an RSA key using the fromdata API, if the RSA primes are set, then it's also necessary to set the CRT exponents and coefficients: https://github.com/openssl/openssl/blob/2f61bc17d42bce0d5958cabc971f4f1343353fb3/crypto/rsa/rsa_lib.c#L755-L759

However, the RSA check_key implementation explicitly allows setting p/q without CRT parameters -- it only requires that if some CRT parameters are set, then all are set, e.g. in https://github.com/openssl/openssl/blob/1c0eede9827b0962f1d752fa4ab5d436fa039da4/crypto/rsa/rsa_sp800_56b_check.c#L29-L34 This matches what the low-level API did with the RSA_set0_factors / RSA_set0_crt_params split.

I just want to double check what the intention here is. Does the key checking code only allow this for compatibility with legacy keys constructed with low level APIs, while keys from high level APIs should now always have either both or neither?

**Comment by t8m** [comment]
IMO this is OK. We aim for some compatibility with legacy. Perhaps the check could be stricter as CRT will be used only when both factors and crt params are set but I do not see any harm keeping things as is.

**Comment by davidben** [comment]
CRT requires all the coefficients, so just having p and q isn't especially useful. I suppose, given d, p, and q, you can compute the other CRT parameters, but I see no reason to encourage the proliferation of even more variations on what an RSA private key is. RFC8017 only specifies two formulations:
https://datatracker.ietf.org/doc/html/rfc8017#section-3.2

(Although an (n, d) pair isn't great because, without e, you can't fault-check the computation. So upgrading that to (n, e, d) is probably prudent.)

I'm curious what's the scenario you've got where you have p and q but not the other CRT coefficients available.

**Comment by nikic** [comment]
I don't have any actual use case for this -- we were just exposing an API that allowed this, so tests picked up the different behavior when switching to the high-level API. I fixed the tests by adding the missing dp/dq/qinv parameters :) Just wanted to double check that the different validity requirements for the low and high level APIs are intentional. I think your reasoning here makes sense, so I'll go ahead and close this issue.
