### ISSUE TITLE
How to verify EVP_PKEY using non-deprecated APIs

### ISSUE THREAD

**Issue by maheshkumar01** [openssl/openssl#16306]
I have below code to verify EVP_PKEY generated using "EVP_RSA_gen(bits)". Some of the APIs in below function are deprecated in 3.0.0. 
"How can I achieve similar functionality using new (non-deprecated) APIs?" A sample code would be of great help.

```
bool VerifyPKey(EVP_PKEY &key) {
  BN_CTX *ctx;
  BIGNUM *r;

  auto rsa = EVP_PKEY_get0_RSA(&key);
  if (rsa) {
    auto p = RSA_get0_p(rsa);
    auto q = RSA_get0_q(rsa);
    auto iqmp = RSA_get0_iqmp(rsa);
    if (BN_cmp(p, q) >= 0) {
      BN_mod_mul(r, q, iqmp, p, ctx);
    } else {
      BN_mod_mul(r, p, iqmp, q, ctx);
    }
  }

  return BN_is_one(r) == 1; 
}

```

**Comment by mattcaswell** [comment]
The simplest thing to do is to just call `EVP_PKEY_check` which performs a whole set of tests to validate the key, instead of the custom ones that you have here:

https://www.openssl.org/docs/manmaster/man3/EVP_PKEY_check.html

If you really want to replicate exactly what you had in the old code then you can call `EVP_PKEY_get_bn_param()` to get hold of the `p`, `q` and `iqmp` values:
https://www.openssl.org/docs/manmaster/man3/EVP_PKEY_get_bn_param.html

The second parameter to `EVP_PKEY_get_bn_param` should be `OSSL_PKEY_PARAM_RSA_FACTOR1` (for `p`), `OSSL_PKEY_PARAM_RSA_FACTOR2` (for `q`) and `OSSL_PKEY_PARAM_RSA_COEFFICIENT1` (for `iqmp`)

**Comment by maheshkumar01** [comment]
```EVP_PKEY_check``` expects ```EVP_PKEY_CTX``` as parameter. I have ```EVP_PKEY```, how can I get ```EVP_PKEY_CTX``` from this?

**Comment by mattcaswell** [comment]
Use `EVP_PKEY_CTX_new_from_pkey()`:

https://www.openssl.org/docs/manmaster/man3/EVP_PKEY_CTX_new_from_pkey.html

**Comment by maheshkumar01** [comment]
Closing issue. Thanks for helping.
