### ISSUE TITLE
Possible AES-CBC decryption regression between 1.1.1 and 3.0

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#16351]
Original description/reproducer: https://bugzilla.redhat.com/show_bug.cgi?id=1992648#c17

The normal process of CBC encryption/Decryption with appending MAC gives different results in 3.0 and 1.1.1
I don't see any obvious error, though the apr-related stuff can make things more difficult to understand

**Comment by paulidale** [comment]
I do not have access permissions to see the reproducer.

**Comment by beldmit** [comment]
@paulidale I've fixed the permissions, please recheck

**Comment by paulidale** [comment]
Thanks, the reproducer can be downloaded without login in.

**Comment by beldmit** [comment]
@paulidale did you have a chance to look at it?

**Comment by paulidale** [comment]
Not yet.

**Comment by beldmit** [comment]
I confirm the behavior change :(

**Comment by beldmit** [comment]
If I add the call to EVP_CTX_set_padding(ctx,0) I get the real content (and unreal length).

Looks like an important problem to me. The necessity of removing padding is not mentioned anywhere, and it's the 2nd time i see it as a regression.

**Comment by beldmit** [comment]
Reduced example:

```
#include <openssl/evp.h>

#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

struct databuf {
    unsigned char *value;
    int length;
};

unsigned char ekey[32];
const EVP_CIPHER *aes = NULL;


int SEAL_BUFFER(struct databuf *plain, struct databuf *cipher)
{
    int blksz = EVP_CIPHER_block_size(aes);
    int err = EFAULT;
    EVP_CIPHER_CTX *ctx;
    uint8_t rbuf[blksz];
    int outlen, totlen;
    int ret;

    ctx = EVP_CIPHER_CTX_new();

    memset(rbuf, 2, blksz);

    /* add space for IV and padding */
    cipher->length = (plain->length / blksz + 2) * blksz;
    cipher->value = malloc(cipher->length);
    if (!cipher->value) {
        err = ENOMEM;
        goto done;
    }

    ret = EVP_EncryptInit_ex(ctx, aes, NULL, ekey, NULL);
    if (ret == 0) goto done;
    totlen = 0;

    outlen = cipher->length;
    ret = EVP_EncryptUpdate(ctx, cipher->value, &outlen, rbuf, sizeof(rbuf));
    if (ret == 0) goto done;
    totlen += outlen;

    outlen = cipher->length - totlen;
    ret = EVP_EncryptUpdate(ctx, &cipher->value[totlen], &outlen,
                            plain->value, plain->length);
    if (ret == 0) goto done;
    totlen += outlen;

    outlen = cipher->length - totlen;
    ret = EVP_EncryptFinal_ex(ctx, &cipher->value[totlen], &outlen);
    if (ret == 0) goto done;
    totlen += outlen;

    err = 0;

done:
    EVP_CIPHER_CTX_free(ctx);
    return err;
}
int UNSEAL_BUFFER(struct databuf *cipher, struct databuf *plain)
{
    int err = EFAULT;
    EVP_CIPHER_CTX *ctx = NULL;
    int blksz = EVP_CIPHER_block_size(aes);
    int outlen, totlen;
    int ret, i;

    ctx = EVP_CIPHER_CTX_new();
    if (getenv("NOPAD"))
        EVP_CIPHER_CTX_set_padding(ctx, 0);

    if (plain->length == 0) {
        plain->length = cipher->length;
        plain->value = malloc(plain->length);
        if (!plain->value) {
            err = ENOMEM;
            goto done;
        }
    }

    ret = EVP_DecryptInit_ex(ctx, aes, NULL, ekey, NULL);
    if (ret == 0) goto done;

    totlen = 0;
    outlen = plain->length;
    printf("Before update, totlen: %d, outlen: %d\n", totlen, outlen);
    ret = EVP_DecryptUpdate(ctx, plain->value, &outlen,
                            cipher->value, cipher->length);
    if (ret == 0) goto done;
    printf("After  update, totlen: %d, outlen: %d\n", totlen, outlen);

    totlen += outlen;
    outlen = plain->length - totlen;
    printf("Before final, totlen: %d, outlen: %d\n", totlen, outlen);
    ret = EVP_DecryptFinal_ex(ctx, plain->value, &outlen);
    if (ret == 0) goto done;

    totlen += outlen;
    printf("After  final, totlen: %d, outlen: %d\n", totlen, outlen);
    /* now remove the confounder */
    totlen -= blksz;
    memmove(plain->value, plain->value + blksz, totlen);

    plain->length = totlen;
    err = 0;

done:
    EVP_CIPHER_CTX_free(ctx);
    return err;
}

int
main() {
    int rc;
    char *plain = "Hello World";
    struct databuf plainbuf = { 0 };
    struct databuf cipherbuf = { 0 };
    struct databuf unsealbuf = { 0 };

    memset(ekey, 1, 32);
    aes = EVP_aes_128_cbc();

    plainbuf.value  = strdup(plain);
    plainbuf.length = strlen(plain);

    printf("value: (%d) %s\n", plainbuf.length, plainbuf.value);

    printf("Sealing buffer\n");
    rc = SEAL_BUFFER(&plainbuf, &cipherbuf);
    if (rc != 0) {
        printf("Sealing failed\n");
    }
    printf("cipherbuf: (%d) %s)\n", cipherbuf.length, cipherbuf.value);

    printf("unsealing buffer\n");
    rc = UNSEAL_BUFFER(&cipherbuf, &unsealbuf);
    if (rc != 0) {
            printf("Unsealing failed\n");
    }

    printf("cipherbuf: (%d) %s)\n", cipherbuf.length, cipherbuf.value);
    unsealbuf.value[unsealbuf.length] = '\0';
    printf("value: (%d) '%s'\n", unsealbuf.length, unsealbuf.value);

    return 0;
}

```

This code behaves differently for 3.0.0 and 1.1.1

**Comment by paulidale** [comment]
This line in `UNSEAL_BUFFER()` is the problem:
```c
memmove(plain->value, plain->value + blksz, totlen);
```
It's overwriting the correct result with the garbage.  Removing it and both versions work the same.

Now, there is still a behaviour change from 1.1.1: in 1.1.1 the plaintext is stored twice.  Once at `plain->value` and a second time at `plain->value + blksz` which means the `memmove(3)` works :astonished:

**Comment by beldmit** [comment]
The example is from a long-existing production code, AFAIK

**Comment by mattcaswell** [comment]
OTC: Requires further investigation to determine whether or not this is relying on an implementation quirk that is now no longer there, or if there is really a bug.

**Comment by beldmit** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1979100 is the other AES-CBC related issue fixed by switching off the padding. I am not sure these issues are related but they _may_ be related

**Comment by t8m** [comment]
@beldmit @paulidale the problem with the reproducer is not the memmove() but the fact that the call to EVP_DecryptFinal_ex() overwrites the previously written decrypted data. It should be in fact `EVP_DecryptFinal_ex(ctx, plain->value + totlen, &outlen);`

With this simple change the code works as expected. Yes, the code works by chance on 1.1.1, but that is only due to the way how the unpadding is done there and it absolutely cannot be something that applications can depend on.

I am not even sure this is worth a Changes note as the reproducer code is obviously buggy.

**Comment by beldmit** [comment]
@t8m is it my bug or the bug of the original reproducer?

**Comment by t8m** [comment]
The original reproducer does the same incorrect thing.

**Comment by mattcaswell** [comment]
Right, @t8m beat me to it. I've been looking at this code too, and came to exactly the same conclusion. This works in 1.1.1 purely by accident. There is a clear bug in the reproducer (as described by @t8m) which when fixed solves the issue.

There are two behaviour changes between 1.1.1 and master than explain the things described in this issue. Neither of these changes are bugs, and no well behaving application should by impacted by them.

In the EVP_DecryptUpdate() call the first block (16 bytes) is decrypted and placed at the start of the `plain->value` buffer, and `outlen` is updated to say that 16 bytes of data is available for reading. The application has no business expecting that more than 16 bytes has been output. As it turns out, due to a 1.1.1 implementation quirk for this cipher, it uses the output buffer as temporary storage and it just so happens that the next block has also been decrypted too and could be read by the application. But since that requires reading more than the 16 bytes of data advertised by the returned `outlen` value, the application has absolutely no business relying on that.

So this is the first behaviour change (1) 1.1.1 used some bytes in the output buffer as temporary storage. No application should be relying on the state of those bytes.

The second behaviour change is when doing "no-padding". In 1.1.1 the final block is held back until the `EVP_DecryptFinal_ex` call. In 3.0 all the data is written out as part of the `EVP_DecryptUpdate` call. Therefore the data is in the place expected by this application and it works. This is all fully within the scope of how the API is supposed to work. The application should not be relying on it.

**Comment by mattcaswell** [comment]
As a separate issue, the fact that this reproducer is using a "NULL" IV is deeply suspicious. If this is present in the real application there could be security impacts.

**Comment by t8m** [comment]
> As a separate issue, the fact that this reproducer is using a "NULL" IV is deeply suspicious. If this is present in the real application there could be security impacts.

They use the first block to be encrypted as the IV, so IMHO this is no issue.

**Comment by beldmit** [comment]
> > As a separate issue, the fact that this reproducer is using a "NULL" IV is deeply suspicious. If this is present in the real application there could be security impacts.
> 
> They use the first block to be encrypted as the IV, so IMHO this is no issue.

I agree with Matt and I'd like to forbid this behaviour, but it's definitely post-3.0.

**Comment by mattcaswell** [comment]
> They use the first block to be encrypted as the IV, so IMHO this is no issue.

It always encrypts to the same value if the key is reused. Its not random.

**Comment by t8m** [comment]
> > They use the first block to be encrypted as the IV, so IMHO this is no issue.
> 
> It always encrypts to the same value if the key is reused. Its not random.

In the real reproducer they use random bytes instead of `memset(rbuf, 2, blksz);`

**Comment by mattcaswell** [comment]
> In the real reproducer they use random bytes instead of memset(rbuf, 2, blksz);

Ah. That's good enough (assuming secure random bytes).

**Comment by richsalz** [comment]
They don't need secure, they just need unique IV, right?

**Comment by mattcaswell** [comment]
> They don't need secure, they just need unique IV, right?

Yes.

**Comment by beldmit** [comment]
@t8m, @mattcaswell - many thanks! Brilliant work!
