### ISSUE TITLE
Size of libssl.a compiled in different machine is not same, which one should use?

### ISSUE THREAD

**Issue by okayabc** [openssl/openssl#16397]
My service link .a of openssl, not .so. I found a problem if i compile openssl in machine A and machine B seperately, the size of libssl.a and libcrypto.a is not same. If my service running in machine A, which .a should use, from A or B?

**Comment by t8m** [comment]
This is too generic question to answer. Also the reasons for the varying sizes can be multiple and not all of them really relevant.

**Comment by rsbeckerca** [comment]
> 
> 
> This is too generic question to answer. Also the reasons for the varying sizes can be multiple and not all of them really relevant.

A practical example: cross compiling any of the NonStop builds will almost certainly be different in size than building on platform because of differences in the text regions of the ELF files - compiler identification, etc., even if the generated object code is identical.

Compiling with symbols puts path names that may be different from one machine to another - or even on the same machine in different directories.

So multiple potential reasons for EOF being different. EOF is not considered a valid identifier for significant differences in an ELF-format file from an audit standpoint (or shouldn't be although I have seen it). Neither is timestamp for that matter, if this is the underlying concern.

**Comment by okayabc** [comment]
Ok, thanks!
