### ISSUE TITLE
multilib should honour ./bin as well as ./lib

### ISSUE THREAD

**Issue by rsbeckerca** [openssl/openssl#16460]
When building OpenSSL 3.0 with `multilib`, the bin directory will be built using the settings appropriate for the build - for example 32 vs. 64 bit memory model. When multiple builds of `bin/openssl` are installed on the same system, the last install references the library being used. This may not be entirely correct or understandable by users trying to set up their execution environment. A `./bin/openssl` object, when built with a 32-bit model, will not run with a 64-bit libssl.so, so the `LIB` path (in NonStop's case, `_RLD_LIB_PATH`) needs to be set up correctly. This may not be consistent with the applications built with other OpenSSL libraries. The behaviour for this is likely to be platform-specific and likely applies to Windows and NonStop but possibly not Linux that can repoint its DLL name after installation.

I am uncertain whether this needs to be solved prior to 3.0.0a.

**Comment by levitte** [comment]
The way it works on Linux is that the value `LD_LIBRARY_PATH` is a path (multiple directories separated by colons), which are searched through until a suitable variant of the requested library is found.

Just as an example, I have a multilib installation of OpenSSL 1.1.1l on my laptop, which means that I have these packages installed: `libssl1.1:amd64`, `libssl1.1:i386`.  Those are the Debian packages to get the OpenSSL libraries, and this is among the files those packages deliver:

``` console
find /usr/lib -name libcrypto.so.1.1 -ls 2>/dev/null
  1968051   2832 -rw-r--r--   1 root     root      2896704 aug 25 00:19 /usr/lib/i386-linux-gnu/libcrypto.so.1.1
  2233496   3008 -rw-r--r--   1 root     root      3076960 aug 25 00:19 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
```

My `/etc/ld.so.conf`, which lists the default directories to search for libraries, includes both `/usr/lib/i386-linux-gnu` and `/usr/lib/x86_64-linux-gnu`.

However, there is only one `/usr/bin/openssl`, which is an x86_64 build:

``` console
$ file /usr/bin/openssl
/usr/bin/openssl: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=5d75d33f61656514ce6bc0afa5522dba0ab2c404, for GNU/Linux 3.2.0, stripped
```

So, just for demonstration purposes, I did an strace with an explicit `LD_LIBRARY_PATH`:

``` console
$ LD_LIBRARY_PATH=/usr/lib/i386-linux-gnu:/usr/lib/i686-linux-gnu:/usr/lib/x86_64-linux-gnu strace /usr/bin/openssl version
...
openat(AT_FDCWD, "/usr/lib/i386-linux-gnu/libcrypto.so.1.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0\3\0\1\0\0\0\0`\5\0004\0\0\0"..., 832) = 832
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\t\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=3076960, ...}) = 0
mmap(NULL, 3096464, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f3c29f0d000
mprotect(0x7f3c29f93000, 2326528, PROT_NONE) = 0
mmap(0x7f3c29f93000, 1732608, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x86000) = 0x7f3c29f93000
mmap(0x7f3c2a13a000, 589824, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x22d000) = 0x7f3c2a13a000
mmap(0x7f3c2a1cb000, 204800, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2bd000) = 0x7f3c2a1cb000
mmap(0x7f3c2a1fd000, 16272, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f3c2a1fd000
close(3)                                = 0
```

So as you can see, it found both variants of `libcrypto.so.1.1`, but skipped over the first one, presumably because the ELF headers showed that there was a platform mismatch, while the second one got mapped to memory.

What I've described is what our multilib is modeled around.

So, is NonStop very different in this regard?  I was expecting that a variable called `_RLD_LIB_PATH` would be equally able to hold multiple directories (just like `PATH`), and that the shared library loader would be able to search for a requested library through all those directory a pick the one that's suitable...

I've re-triaged this as a question...  might possibly become a feature.

**Comment by rsbeckerca** [comment]
In the case of the NonStop (and I think Windows loader), the first library name match wins. There is no provision for attribute detection, so the run will crash.

**Comment by t8m** [comment]
In that case the multilib concept is very much different on these platforms and perhaps something like just using proper prefix instead of multilib is the way to go?

**Comment by rsbeckerca** [comment]
> 
> 
> In that case the multilib concept is very much different on these platforms and perhaps something like just using proper prefix instead of multilib is the way to go?

What about introducing a `multibin` concept that parallels `multilib`? This would conceptually add `BINDIR` to the `Makefile` instead of hard-coding `./bin`.

The alternative is to pull out `multilib` from `50-nonstop.conf`, which would result in breaking assumptions made by `curl` on where our 64-bit libraries are - the thing that started all this for us.

**Comment by t8m** [comment]
> What about introducing a `multibin` concept that parallels `multilib`? This would conceptually add `BINDIR` to the `Makefile` instead of hard-coding `./bin`.

IMO, why not, however this definitely looks like a new feature -> post 3.0.

**Comment by rsbeckerca** [comment]
> 
> 
> > What about introducing a `multibin` concept that parallels `multilib`? This would conceptually add `BINDIR` to the `Makefile` instead of hard-coding `./bin`.
> 
> IMO, why not, however this definitely looks like a new feature -> post 3.0.

Makes sense. I don't mind doing what I can for it. I think I've got enough of an understanding of the template code.

**Comment by rsbeckerca** [comment]
@t8m Candidate implementation now has a PR.

**Comment by rsbeckerca** [comment]
Hoping this can make it into 3.1
