### ISSUE TITLE
No ChaCha20-Poly1305-draft edition support

### ISSUE THREAD

**Issue by dynos01** [openssl/openssl#1655]
Only ARM devices can take full advantages of ChaCha20, but they only support ChaCha20-Poly1305-draft (0xcc13、0xcc14). Hope you can add this in a further release.

**Comment by Darkudorus** [comment]
You should use a newer Android. A draft isn't a standard and should therefore not be included in OpenSSL. The changes between draft and the final standard have been made with intention.

**Comment by lukastribus** [comment]
Agreed, everyone using the draft should upgrade to the standard.

Untrue is "just upgrade". Only Android 7 supports the new standard, Android 5 and 6 (accounting for about 60% of the currently used Android handhelds [1]) just support the draft. That is the reason why Google still supports the draft on their infrastructure and will continue to do so.

So most of the currently used devices do not support the new standard, don't have AES-NI HW support (so they could efficiently use AES-GCM) and likely won't ever get an upgrade to Android 7.

Current/next ARM generations will have AESNI HW support anyway, so they won't need Chacha20 at all.

I guess the embedded sector still benefits from ChaCha20.

I'm not trying to argue that we should include this, I'm just saying what the facts regarding the Android/handheld devices are.


[1] https://developer.android.com/about/dashboards/index.html

**Comment by davidben** [comment]
Android 5 and 6 do not support either the draft or the (then nonexistent) standard version of ChaCha20-Poly1305. The draft versions were intentionally excluded from the system Android BoringSSL to avoid this situation:
https://android.googlesource.com/platform/external/boringssl/+/fc104df40ab7812f749993809b873c139da3d959

**Comment by lukastribus** [comment]
This change you are mentioning is not even in Android 7.
Android [5..7] all support the draft (with 7 supporting the standard).

Android 5:
https://www.ssllabs.com/ssltest/viewClient.html?name=Android&version=5.0.0&key=88

Android 6:
https://www.ssllabs.com/ssltest/viewClient.html?name=Android&version=6.0&key=129

Android 7:
https://www.ssllabs.com/ssltest/viewClient.html?name=Android&version=7.0&key=139

**Comment by davidben** [comment]
Interesting. I'm not sure what software those ClientHellos were based on, but that doesn't look like a ClientHello from the system image. Perhaps that's whatever snapshot of WebView happened to be current at the time, which doesn't matter. Starting Android 5.0, WebView is a separate updatable app and doesn't use the system image SSL stack.

**Comment by lukastribus** [comment]
I digged some more into this:
those hellos are from the builtin browser (not Chrome) and likely depend on the ROM vendor (Samsung and Cyanogenmod in my case). It is neither webview nor system ssl based as it seems (meaning we have 3 different ssl libraries with different patchlevels and features; great!).

Checking the behavior of actual APPs like gmail and youtube, they either are system based (no draft support either) or webview based.

Still not sure why current webview supports both draft and the standard or how a patch from 2015 made it into a 2014 Android release, but in any case my point above only applies to broken third party apps that apparently ship their own lib (although I'm not sure why both Samsung and Cyanogenmod would decide to ship their browser with their own outdated ssl lib).

**Comment by davidben** [comment]
> those hellos are from the builtin browser (not Chrome)

The ClientHello looks like various snapshots of something Chromium-based. I believe back when there was still a built-in browser maintained in Android proper, it was not using the Chromium OpenSSL/BoringSSL and rather the system OpenSSL/BoringSSL (which does not produce a ClientHello like that). This is probably ROM vendors doing funny things.

> Still not sure why current webview supports both draft and the standard

WebView these days is Chromium-based which supports both. We just haven't gotten around to removing the draft version yet. Probably will do that sometime next year. Regardless, we've supported the standard one for quite some time now.

> how a patch from 2015 made it into a 2014 Android release

As of Android 5.0, WebView is a separate app that is updatable.


Anyway, the important point is there is no need for OpenSSL to implement the draft version. We intentionally excluded it from the base image because those tend to last much longer, whereas other things get updated reasonably. OpenSSL should stick to the standard one, and this bug should stay closed.

**Comment by lukastribus** [comment]
Agreed.
