### ISSUE TITLE
1.1.1g to 3.0 problem with PEM_read_bio_PrivateKey()

### ISSUE THREAD

**Issue by jfield1005** [openssl/openssl#16619]
I am migrating from 1.1.1k to 3.0. Both of which I built myself.
I am having a problem with the following code.
It works when using 1.1.1k but with 3.0 the PEM_read_bio_PrivateKey
returns 0.  

...

gcax509 = NULL;
gcaKey = NULL;

bioC = BIO_new_mem_buf((char *)cert_data, cert_data_size);
gcax509 = PEM_read_bio_X509(bioC, NULL, 0, NULL);

pfixup( ); //Put pasword into pws

bioK = BIO_new_mem_buf((char *)key_data, key_data_size);
gcaKey = PEM_read_bio_PrivateKey(bioK, NULL, NULL, pws); //NOT Working

...

Any help orsuggestions are appreciated.

**Comment by mattcaswell** [comment]
Since you are passing a password I assume the private key is encrypted. What is it encrypted with? Possibly it is using legacy encryption.

I'd suggest dumping out the OpenSSL error stack (for example with `ERR_print_errors_fp()`) which might give you a clue what the problem is. You may need to load the legacy provider for access to legacy ciphers.

**Comment by jfield1005** [comment]
Encryption was issue. was using -des genrsa option. changes to -aes256 and it is now working. 
Thank You
