### ISSUE TITLE
Decrypting multiple files with same key pair

### ISSUE THREAD

**Issue by GreatScotch** [openssl/openssl#16665]
Hi, 

I have a request to decrypt multiple files and I thought why not use /*.crypt in my command but it doesn't work and instead, however decrypting specific files works fine.

Does anyone know the correct parameters or syntax I need to use to be able to bulk decrypt files?

Thanks

**Comment by paulidale** [comment]
Since you said nothing about what system you are using, it's kind of difficult to help.

However, you'll need something along these lines:
```sh
for file in /*.crypt
do
   command $file
done
```

**Comment by GreatScotch** [comment]
Hi,

Sorry, I'm running openssl on windows 10.

So I will have to attempt to write a Powershell script?

Thanks

Chi

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by levitte** [comment]
The openssl app expects exact file names.  It doesn't try to expand globs, as that's expected to be the shell's job (Unix shells do this, so the app would get the resulting files as separate command line arguments).

However, your attempt wouldn't even work on Unix, because `-in` and `-out` expect one value each, not multiple.  Therefore, you will have to do the suggested loop around the openssl call.

You might find this helpful: https://ss64.com/nt/forfiles.html

If I should venture a guess, this might be a suitable command for you:

```
forfiles /p e:\ /m *.crypt /c "openssl.exe cms -decrypt -inkey C:/key.pem -recip C:/cert.pem -inform DER -in @path -out" E:/@fname.xml"
```

I haven't tested this, at all.  I'll leave that to you, with the guidance of https://ss64.com/

**Comment by GreatScotch** [comment]
Hi,

Thanks for the reply! much appreciated. I'll check out the link

Chi

**Comment by t8m** [comment]
Is there anything missing here? The response to your question simply is - openssl does not support decryption of multiple files in one openssl tool invocation.

**Comment by GreatScotch** [comment]
No thanks for the info
