### ISSUE TITLE
Signature calls: How to determine available capacity in sig buffer and what exactly is sigsize?

### ISSUE THREAD

**Issue by selvanair** [openssl/openssl#16673]
PS: Looks like the second call  with *siglen = 0 may be an error in my provider implementation, so read this as a question about what is sigsize and can *siglen on input be assumed to contain the capacity of sig when its not NULL?

In a custom provider with signature ops implemented, one gets calls to

```int foo_signature_digest_sign(unsigned char *sig, size_t *siglen, size_t sigsize, .....)```
and
```int foo_signature_sign(unsigned char *sig, size_t *siglen, size_t sigsize, ....)```

When `sig` is not NULL, in the first call above, I generally see `sigsize = (size_t) -1`, indicating no maximum (?) and `*siglen == EVP_PKEY_size(..)`. ~But in the latter case  I get `*siglen = 0`.~

~This may be just a side effect of how those calls arise in my application -- I always get `foo_signature_digest_sign()` call with `sig=NULL` for a fresh TLS handshake, to which I respond with `*siglen = 256` (for example) and then in the next call that value is preserved.~

~Whereas, I see calls to `foo_signature_sign` reusing the context only if there is a reset in the application, leading to a re-issue of the sign request, with the digest already available. In that case OpenSSL calls it with `sig != NULL`, but `*siglen` is zero.
All this appears fine, as `*siglen` is not documented to be meant as an input, its for returning the signature size.~ 

The question is how can one determine the max capacity of `sig` buffer? Just assume that it can fit at least whatever size was requested when called with `sig == NULL`? From the docs I got the mistaken impression that the `sigsize` indicates the capacity of `sig` buffer, but not so...? What exactly is `sigsize`?

**Comment by slontis** [comment]
EVP_PKEY_sign() calls this:
````
    ret = ctx->op.sig.signature->sign(ctx->op.sig.algctx, sig, siglen, SIZE_MAX, tbs, tbslen);
````
So sigsize just seems to be a hardwired max bound..

Have a look at the existing ones inside providers/implementations/signature..
They are returned when sig == NULL and represent the max capacity.
DSA uses DSA_size()  (it needs a q value to figure out the size since the value is put inside a DER blob.)
RSA uses RSA_size() which requires a value for rsa->n.

**Comment by selvanair** [comment]
Okay, so it looks like sigsize can be ignored for all practical purposes and *siglen on entry is the capacity of sig when not null, to be set to the actual length of the signature on return.

**Comment by mattcaswell** [comment]
At the moment the public facing APIs don't provide the ability to pass through the `sigsize` value. We just assume that the provided buffer is big enough.For backwards compatibility reasons we have not fixed that. However we wanted to still pass a `sigsize` through to the providers with the thinking that we would like to fix the public API at some point. Providers should confirm that that the `sigsize` is sufficient for the signature - even though at the moment it always will be. At some point in the future we might expose this to end applications so that they can explicitly say how big the sig buffer is.
