### ISSUE TITLE
Can we work with HMAC-SHA1/MD5 authentication using hex stream instead of string directly ? Does OPENSSL support it ?

### ISSUE THREAD

**Issue by A-Choudhury026** [openssl/openssl#16687]
echo 'helloworld' | openssl dgst -sha1 -hex -hmac samplestring
SHA1(stdin)= ca944c068070b8dc8403277da8d5ef09ce785181

(using http://string-functions.com/string-hex.aspx)
helloworld --> 68656c6c6f776f726c64 
samplestring --> 73616d706c65737472696e67

echo '68656c6c6f776f726c64' | openssl dgst -sha1 -hex -hmac 73616d706c65737472696e67
SHA1(stdin)= 84211ab305c404e8a8a5eb45aea688f5e2127b8a

As both are not matching is there any procedure which we need to follow to work with hex stream.

**Comment by mattcaswell** [comment]
Strangely I get a slightly different result to you for the same command. Not sure why:

````
$ echo 'helloworld' | openssl dgst -sha1 -hex -hmac samplestring
SHA1(stdin)= 208158712658bc2955bbc0736dce94ea48c8e53c
````

The "echo" command adds a newline to the end of the string - which also gets hashed. So to only calculate the string itself without the newline you need to add a "-n" option to echo:

````
$ echo -n 'helloworld' | openssl dgst -sha1 -hex -hmac samplestring
SHA1(stdin)= 7cade991c2a6ac071f6ffa69b77f3a71d2cc2244
````
You can do the equivalent in hex like this:

````
$ echo 68656c6c6f776f726c64 | xxd -r -p | openssl dgst -sha1 -hex -mac hmac -macopt hexkey:73616d706c65737472696e67
SHA1(stdin)= 7cade991c2a6ac071f6ffa69b77f3a71d2cc2244
````

**Comment by A-Choudhury026** [comment]
@mattcaswell Thank you for your response.

`echo -n 'helloworld' | openssl dgst -sha1 -hex -hmac samplestring
SHA1(stdin)= 2727f3615b95322e47c7d13fe741c4f8adbd3a57`

It shows differently in my executable. (https://slproweb.com/products/Win32OpenSSL.html), further its not able to recognize  xxd as input parameter.

`echo -n '68656c6c6f776f726c64' | xxd -r -p | openssl dgst -sha1 -hex -mac hmac  hexkey:73616d706c65737472696e67
'xxd' is not recognized as an internal or external command,
operable program or batch file.`

Do we have any external source code where openssl works with hex stream ?

**Comment by levitte** [comment]
xxd on Windows

https://sourceforge.net/projects/xxd-for-windows/

**Comment by mattcaswell** [comment]
Ahh! This is Windows! That makes a difference. I'm not sure if the "-n" parameter works on Windows (I suspect not). You will need some Windows method of doing the equivalent of xxd (and @levitte's pointer looks like a good starting place). But this is outside of OpenSSL itself.

> Strangely I get a slightly different result to you for the same command.

The fact that this is Windows explains this difference. The line endings are different and hence you will get a different hash. 

This page has some suggestions for how to strip line endings from echo on Windows (i.e. instead of "-n"). I don't currently have access to windows to test this out:

https://stackoverflow.com/questions/7105433/windows-batch-echo-without-new-line
