### ISSUE TITLE
Hardware offload usage roadmap in providers age

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#16868]
In pre-3.0 age it was possible to load the engine providing, say, RSA_METHOD in the configuration file and specify its usage via `default_algorithms=RSA` in the configuration. This approach does not work for the EVP-based apps in OpenSSL 3.0 version (e.g. openssh with ibmca engine) - the provider-based implementation is used. 

What should be done to ensure using the hardware offload? I assume that 

- the engine should be turned into a provider, 
- the provider should be loaded via config, 
- and default properties should be smth like `provider=?myprov`

Is it a suitable roadmap?

Will the engine-based approach still work for the applications using deprecated RSA* API?

**Comment by mattcaswell** [comment]
> There is no requirement for third-party providers to set provider=name or any such property in their methods, isn't it?

It's a convention, but not a requirement.

> If so how can application author be sure that ?provider=myprov will work?

Prop query strings may be written by application authors (if they are embedded in an application), or by end users (for example in a config file). In either case the person writing the prop query string is expected to know the properties available for the providers they are using. It is assumed that the provider authors will document that.

> Also, what if all that an application is given is the filename of the shared object for the provider --- in that case would provider=path-to-myprov.so get translated to the internal name of the provider, even if that were to work...

You can specify the full name to the .so instead of the "short" name when *loading* the provider. The name used in any prop query string will still be the short name, and it is expected that the documentation accompanying the provider will specify the property values that it defines.

> If an application wants to allow user to specify multiple providers to load, it appears we may also have to ask the user to state what propquery to use. Is that the design intent... Constructing an appropriate propquery in an application without user input and/or intimate knowledge of the provider looks like near to impossible. Is there an API to find what properties are set by a provider on its methods?

Generally I expect the user to be specifying the providers they want in their config file along with the global property query if appropriate. It may be that a given application may have a dependency on a specific provider, in which case it may choose to load that provider itself. In that case the application author is expected to know the properties available within the provider it depends on. There is no API to discover the properties dynamically at run time. That could be a future enhancement but was not an objective for 3.0.

> What if there are multiple providers where one is preferred for RSA, other accelerates AES etc? Add to that an HSM provider which doesn't want to be used for anything but operations on keys it hold. In that case one needs a propquery like ?provider=default for the HSM, but how to combine that with, say, ?provider=my_fast_aes and ?provider=myrsaprov..

It was a deliberate design decision in 3.0 to keep property queries simple for this release. It would be nice to be able to do priority orderings, e.g. prefer provider A first, if that's not available use provider B, and only if neither of those are available use provider C. It would also be nice to be able to do things like "prefer provider A if using curve XYZ, otherwise use provider B". However none of that is currently available. We expect future versions to have more complex capabilities in this area, but we deliberately decided not to do it yet in the interests of getting 3.0 out of the door.

> If there is a design document that explains how provider selection using propquery is supposed to happen in various circumstances such as these, that would help.

There is a man page for properties, but it probably doesn't answer all the questions you are asking:
https://www.openssl.org/docs/man3.0/man7/property.html

**Comment by beldmit** [comment]
Closing this.
