### ISSUE TITLE
Different version TLS in record layer and handshake layer

### ISSUE THREAD

**Issue by pavelnt** [openssl/openssl#1689]
I use OpenSSL 1.0.2g. Application is able to receive incoming connections and initiate outbound connection. Application sends ClientHello message during create outbound connection. In this time I see that versions of TLS are different in record layer and handshake layer.

```
Secure Sockets Layer
TLSv1.2 Record Layer: Handshake Protocol: Client Hello
    Content Type: Handshake (22)
    Version: TLS 1.0 (0x0301)
    Length: 122
    Handshake Protocol: Client Hello
        Handshake Type: Client Hello (1)
        Length: 108
        Version: TLS 1.2 (0x0303)
```

The following flags are used to set in global context.

`SSL_CTX_set_options(ctx, SSL_OP_NO_SSLv2 | SSL_OP_NO_SSLv3 | SSL_OP_NO_TLSv1 | SSL_OP_NO_TLSv1_1);`

I'd like to see the same version of TLS in record and handshake layers.

**Comment by mattcaswell** [comment]
This is expected behaviour. It is the Handshake layer version number that is important. In fact any TLS1.2 compliant server MUST accept any value {03,XX} as the record layer version number for ClientHello as per RFC5246. See https://tools.ietf.org/html/rfc5246#appendix-E for a discussion of this complex issue.

**Comment by pavelnt** [comment]
Thanks for answer.
So, does it happen inside openssl library?

**Comment by mattcaswell** [comment]
Yes. You cannot control this (nor should you need to).

**Comment by pavelnt** [comment]
How about browsers? They are able to set the same version of TLS in record and handshake layers.

**Comment by mattcaswell** [comment]
It is *valid* to do it. It is also valid not to do it - and OpenSSL doesn't.

**Comment by pavelnt** [comment]
In my case I don't use something special, only what OpenSSL provides.
So, as I understand it's not possible. :)

**Comment by mattcaswell** [comment]
Correct.

**Comment by dionmonstavicius** [comment]
It isn't a security vulnerability because all the hello is sent in the clear anyway.  But the perception is that this is using TLS 1.0 is a problem in a political sense---you are using TLS 1.0 because you write TLS 1.0 in your header and thus this product cannot be sold to US government.

**Comment by davidben** [comment]
The record layer version is entirely vestigial. It doesn't mean anything and historically needed to be set to 0x0301 (TLS 1.0) for compatibility reasons:

>   legacy_record_version:  MUST be set to 0x0303 for all records
>      generated by a TLS 1.3 implementation other than an initial
>      ClientHello (i.e., one not generated after a HelloRetryRequest),
>      where it MAY also be 0x0301 for compatibility purposes.  This
>      field is deprecated and MUST be ignored for all purposes.
>      Previous versions of TLS would use other values in this field
>      under some circumstances.

https://www.rfc-editor.org/rfc/rfc8446#page-79

If your tool determines the TLS version based on the record-layer version, it's simply outputting things wrong.

**Comment by dionmonstavicius** [comment]
@davidben  Tool is wireshark.  Wireshark is industry standard.  I'm telling y'all, not arguing, that I am about to drop openssl over this issue because I cannot risk 100M in revenue.  I know it is a vestigial but nobody else does.  Wireshark reports my software uses TSL1.0 over this issue alone and I cannot risk someone refusing my software on this basis.

**Comment by dionmonstavicius** [comment]
@davidben Issue logged with Wireshark.  https://gitlab.com/wireshark/wireshark/-/issues/19515.  I think it is unlikely they will resolve this issue in my favor since they are simply reporting the information in the header written by openssl.  In my opinion, the best option is for openssl to offer me the ability to set this header to 1.3 to avoid this issue.

**Comment by davidben** [comment]
That would, in fact, be in violation of the TLS 1.3 protocol. See the text I cited above. The value for the legacy version is 0x0303 ("TLS 1.2"), or 0x0301 ("TLS 1.0") in the ClientHello.

From the Wireshark ticket, it sounds like this simply stems from a misunderstanding of not only the spec but also Wireshark's output.

**Comment by dionmonstavicius** [comment]
@davidben  Agreed.

**Comment by HuanGMZzz** [comment]
I also encountered the same problem today. Some services do not accept TLS1.0 Record Layer version ...
