### ISSUE TITLE
sm4 cbc decrypt fail to get the original text

### ISSUE THREAD

**Issue by xiaonan-INTC** [openssl/openssl#16939]
In OpenSSL 3.0.0, SM4 CBC mode, a plaintext encrypt then decrypt, fail to get the plaintext.
Test code:
https://github.com/jinghe-INTC/intel-sgx-ssl/tree/master/Linux/sgx/test_app/enclave/tests/evp_smx.c
in int ecall_sm4_cbc(void), step 8 will return false:
// 8. Compare original and decrypted text
if (memcmp(plainText, decryptedText, sizeof(plainText)) != 0) {
    printf("Error: original and decrypted text is different\n");
    ret = -8;
    break;
}

Dump plaintext, encryptedText and decryptedText,
[sm4_cbc.txt](https://github.com/openssl/openssl/files/7440280/sm4_cbc.txt)
[sm4_cbc_dec.txt](https://github.com/openssl/openssl/files/7440281/sm4_cbc_dec.txt)
[sm4_cbc_enc.txt](https://github.com/openssl/openssl/files/7440282/sm4_cbc_enc.txt)

**Comment by ShundaZhang** [comment]
I think it is because of padding, NOT a bug of OpenSSL.

You can try to add 
int pad = 0; EVP_CIPHER_CTX_set_padding(evp_ctx, pad); after EVP_EncryptInit_ex.

Or just change the encrypt/decrypt buffer from 16 to 32:
unsigned char pEncrypt[32] = {};
unsigned char pDecrypt[32] = {};

Some more details of padding:
The plaintext is 16 bytes (00000000: aaaa aaaa bbbb bbbb cccc cccc dddd dddd), after PKCS7 padding, there will be one more block (0x10*16) to be ecrypted.
The complete Ciphertext is:
00000000: 78eb b11c c40b 0a48 312a aeb2 0402 44cb  -> first block       aaaa....
00000010: 417c 7fd5 8fb4 6cb1 c5a5 61ed dabe 7ea6    -> second block 101010....

**Comment by xiaonan-INTC** [comment]
Thanks Shunda for explaining, I have submitted a patch of SMx sample project for OpenSSL and close it.
