### ISSUE TITLE
Is it support NuttX?

### ISSUE THREAD

**Issue by PierrePeng** [openssl/openssl#16946]
I wanna if it's support for NuttX? If yes, is there any tutorials about that?

**Comment by paulidale** [comment]
It's not specifically supported.

**Comment by PierrePeng** [comment]
Hi @paulidale, thanks for your reply.

Another question: If I want to cross-compile for the Cortex-M33 chip on Linux, which target should I set?

I am trying to compile using with the command "../Configure linux-armv4 --prefix=/home/pierre/git/openssl/build/install --openssldir=/home/pierre/git/openssl/build/install -static", and "make CC=arm-none-eabi-gcc -j16".  Then I got the error as the following pictures shown.

![image](https://user-images.githubusercontent.com/23045104/140030741-e35aec79-dbb3-4152-908e-434d10f81bee.png)

**Comment by PierrePeng** [comment]
If I use the parameter -no-threads, then I got this error. 
![image](https://user-images.githubusercontent.com/23045104/140037592-661a4b38-7008-4410-ae1d-6a1f72d791b8.png)

**Comment by paulidale** [comment]
I'd suggest setting the CC one the configure line rather than for the build.  We do a CI build for ARM v4.  It's in `.github/workflows/cross-compiles.yml`: https://github.com/openssl/openssl/blob/6450ea27ffdc22194f27e90796ce5538af2d81e2/.github/workflows/cross-compiles.yml#L40-L43

Beyond this, I'm at a loss.  I've little recent experience with any similar platform.

**Comment by PierrePeng** [comment]
Anyway, thanks @paulidale. I will have a try.
