### ISSUE TITLE
3.0.0: dgst crash

### ISSUE THREAD

**Issue by sdaoden** [openssl/openssl#16961]
Hello.  Now on github, just for you :)
On "OpenSSL 3.0.0 7 sep 2021 (Library: OpenSSL 3.0.0 7 sep 2021)" (AlpineLinux edge package) as well as custom compiled on GNU/Linux (i have not looked what happens)

```
$ openssl dgst -mac siphash -macopt key:0123456789abcdef ANY_FILE_HERE
Segmentation fault
```

I am sure it is misuse, but crashing is surely not wanted.

**Comment by sdaoden** [comment]
Wow that was fast :)  Somehow i did not get a notification, nothing in my mail logs either..
But thanks for fixing!

**Comment by sdaoden** [comment]
P.S.: you are doing all the things now, closing the issue etc?!
P.P.S.: now got notification, likely misconfiguration on my side at first.
Ciao!

**Comment by mspncp** [comment]
Thank you @sdaoden for reporting this issue. It looks like @paulidale pushed a fix to his repository but did not create a pull request yet. But don't worry, it will happen. And since commit https://github.com/paulidale/openssl/commit/c4f4e728b0d4aecff77088fdde94d8ad28d945dc contains a note that it fixes this issue. So it will be autoclosed when the pull request gets merged.

**Comment by paulidale** [comment]
Oops, I meant to.
