### ISSUE TITLE
PPC vector register break

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#16995]
Reported by @evanmiller as a [comment on the commit](https://github.com/openssl/openssl/commit/77112270593c4c51631e9138174f6657096399e9#commitcomment-59655332):

> [This commit](https://github.com/openssl/openssl/commit/77112270593c4c51631e9138174f6657096399e9) generates broken PPC code, such as
> 
> ```
> vsel 0,0,0,0
> ```
> 
> It appears that `vsr2vr1` is being passed a full register name e.g. `"v7"` but the logic is expecting only the integer portion e.g. `"7"`.
> 
> Downstream bug report: https://trac.macports.org/ticket/63847

**Comment by evanmiller** [comment]
Just to clarify, the flavor in question is `osx32`. Reproduce with

```
perl5 crypto/aes/asm/aesp8-ppc.pl "osx32" | grep vsel
```

**Comment by t8m** [comment]
@martin-schwenke Could you please help?

**Comment by martin-schwenke** [comment]
Oh great!  Hopefully the last of the PPC platforms broken with that handful of commits...  :smiley: 

I've pushed potential fix to https://github.com/martin-schwenke/openssl/tree/fix-osx.

I used the following script to test that it only changes output on OS X platforms:

```
#!/bin/sh

set -e

dir="$1"
mkdir -p "$dir"

flavours="aix32 aix64 linux32 linux64 linux64le linux64v2 osx32 osx64"
scripts=$(git grep -l ppc-xlate)

for f in $flavours ; do
	for s in $scripts ; do
		# Do not run scripts for 64-bit flavours against 32-bit flavours
		case "$f" in
		*32*)
			case "$s" in
			*64*)
				continue
			esac
		esac
		b=$(basename "$s")
		out="${dir}/${b}-${f}.out"
		perl "$s" "$f" "$out"
	done
done
```
Run with `master` branch with argument (say) `before` and then on this branch with argument (say) `after`.  Then `diff -qru before after` shows only changes for OS X flavours.  Dropping the `q` from the `diff` command appears to show useful changes for the OS X flavours.

@evanmiller Can you please verify that my branch fixes the build on `osx32`?

I'm no longer at IBM, so:
* Perhaps @amitay can please take a look from a `linux64le` perspective and confirm that I'm not doing anything stupid.
* If this turns into a PR then this will be under personal rather than corporate CLA - I'll try to remember to note that in the PR if we get to that point.  :wink:

**Comment by t8m** [comment]
The fix looks good to me - I did not verify it though.

**Comment by martin-schwenke** [comment]
> I do not know PPC assembly, but the comment over the original function (line 153) makes it sound like the function will change the prefix from `vs` to `v`.

The comment is a little confusing but, at the time, I couldn't figure out a way to keep it both useful and short.  It is really referring to the 2 different ways that registers are numbered in the ISA.  I blame the confusion on whoever decided the vector registers should be numbered in 2 different ways.

**Comment by evanmiller** [comment]
@martin-schwenke Thanks for the clarification.

The generated assembly now builds successfully with the patch. Will report back when the complete build and test suite are finished.

**Comment by evanmiller** [comment]
Builds and test suite passes locally 👍

**Comment by paulidale** [comment]
Our CIs do a `linux64le` cross compile build.  We've no other PPC builds otherwise.
