### ISSUE TITLE
SSL_connect() fails with SSL_R_UNEXPECTED_EOF_WHILE_READING

### ISSUE THREAD

**Issue by Snuff-Daddy** [openssl/openssl#17004]
I upgraded from 1.1.1h to 3.0.0 and immediately ran into this problem.  When initiating TLS with a FTP server, SSL_connect() fails with SSL_R_UNEXPECTED_EOF_WHILE_READING

I've tried SSL_OP_IGNORE_UNEXPECTED_EOF.  I've tried ignoring the error.  I've tried both.  Nothing works.

Here is the conversation with the server:

```
220 Microsoft FTP Service
>AUTH TLS
234 AUTH command ok. Expecting TLS Negotiation.
>SSL negotiation failed, code 1: SSL module internal error.
error:0A000126:SSL routines::unexpected eof while reading
```

Platform is Win64.  FTP server is Microsoft IIS7.  With SSL_OP_IGNORE_UNEXPECTED_EOF there is no error but the connection is dropped.

Anyone else seeing this?

**Comment by mattcaswell** [comment]
> With SSL_OP_IGNORE_UNEXPECTED_EOF there is no error but the connection is dropped.

This much at least is expected behaviour. If you receive the error `SSL_R_UNEXPECTED_EOF_WHILE_READING` it means that the peer closed the connection abruptly (i.e. without sending a graceful close_notify alert). In 1.1.1 and earlier this error is incorrectly reported as `SSL_ERROR_SYSCALL` with a 0 `errno`. That behaviour is weird but fixing it in the stable 1.1.1 release destabilised existing applications so we reverted that fix - in order to reintroduce at a 3.0 (a major version upgrade). All `SSL_OP_IGNORE_UNEXPECTED_EOF` does is cause OpenSSL to treat an unexpected EOF as if a close_notify had been received. The result is the same - the connection is closed.

Is it possible to get logs from the server in this case? It seems like the server is rejecting the connection for some reason. There might be logs on the server that give some clue as to why.

**Comment by Snuff-Daddy** [comment]
I don't think that's the issue.  There shouldn't be any error in the first place.  It worked perfectly on 1.1.1h, and it works when I revert to that version.  The client is not closing the connection.  I'm afraid the log doesn't provide any useful information.

```
#Software: Microsoft Internet Information Services 7.0
#Version: 1.0
#Date: 2021-11-10 14:27:19
#Fields: date time c-ip cs-username s-ip s-port cs-method cs-uri-stem sc-status sc-win32-status sc-substatus sc-bytes cs-bytes x-session x-fullpath x-debug
2021-11-10 14:27:19 XX.XX.XX.XX - XX.XX.XX.XX  21 ControlChannelOpened - - 0 0 0 0 81a89720-5e6e-411f-84d1-0eece6992783 - -
2021-11-10 14:27:19 XX.XX.XX.XX - XX.XX.XX.XX  21 AUTH TLS 234 0 0 22 10 81a89720-5e6e-411f-84d1-0eece6992783 - -
2021-11-10 14:27:19 XX.XX.XX.XX - XX.XX.XX.XX  21 ControlChannelClosed - - 2148074289 0 49 517 81a89720-5e6e-411f-84d1-0eece6992783 - -
```

If you have the means I can give you the server information so that you can test it yourself.

**Comment by mattcaswell** [comment]
> If you have the means I can give you the server information so that you can test it yourself.

Please do

**Comment by Snuff-Daddy** [comment]
Server is gammadyne.com port 21.  No need for credentials because it's never getting past the AUTH TLS command.

**Comment by mattcaswell** [comment]
The problem is that the server is intolerant of clients that do not support SHA-1. SHA-1 is considered broken and its use is deprecated. For this reason OpenSSL 3 no longer offers SHA-1 based signature algorithms in its ClientHello. Since the server apparently requires these signature algorithms to be present it is aborting the connection.

OpenSSL can be configured to support SHA-1 anyway. Using the OpenSSL 3 command line, the following fails:

````
$ openssl s_client -connect gammadyne.com:21 -starttls ftp
CONNECTED(00000003)
40F715F8147F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:ssl/record/rec_layer_s3.c:308:
````

But the following succeeds:

````
$ openssl s_client -connect gammadyne.com:21 -starttls ftp -cipher DEFAULT@SECLEVEL=0
...
220 Microsoft FTP Service
````
The difference is that in the latter we deliberately lower the default OpenSSL security level from 1 to 0. At level 0, SHA-1 is allowed.

**Comment by Snuff-Daddy** [comment]
Eureka!  You are a real ninja, I would have never figured that out.

In my case, I just needed to call SSL_CTX_set_security_level(ctx, 0) after creating the context.

Hope this helps others.
