### ISSUE TITLE
Does OpenSSL-1.1.1x provide the TLS SNI(Server Name Indication) extension by default  in ClientHello?

### ISSUE THREAD

**Issue by ravinjhajharia** [openssl/openssl#17071]
Does OpenSSL-1.1.1x provide the TLS SNI support by default so that it can be used by the client and server application? If not, How a client application can enable TLS SNI support? 
Would be great if someone can also point how to disable it from the server-side if the client doesn't implement the TLS SNI?

**Comment by ravinjhajharia** [comment]
@mattcaswell Would appreciate it if you can through some light on this?

**Comment by mattcaswell** [comment]
> Does OpenSSL-1.1.1x provide the TLS SNI support by default so that it can be used by the client and server application? If not, How a client application can enable TLS SNI support?

OpenSSL s_client application sends SNI by default. However other applications need to call `SSL_set_tlsext_host_name` in order to set the host name to be passed in SNI.

https://www.openssl.org/docs/man1.1.1/man3/SSL_set_tlsext_host_name.html

> Would be great if someone can also point how to disable it from the server-side if the client doesn't implement the TLS SNI?

Server applications don't do anything with SNI by default. You have to explicitly write them to handle it, e.g. by using `SSL_CTX_set_tlsext_servername_callback` or `SSL_CTX_set_client_hello_cb` to set the correct certificate in the SSL object based on the SNI data that was received.

https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_tlsext_servername_callback.html
https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_client_hello_cb.html

**Comment by ravinjhajharia** [comment]
@mattcaswell Thanks for the details. Really appreciate your quick response.
Could you throw some light on why some server accepts the connection even though they had SNI enabled with the older openssl s_client like 1.0.2? Is it left up to the server that he can choose either to accept or to abort the connect with a fatal error if the **server_name** is not provided in Client Hello? Just like the below case with google.com

**1.0.2:**
![image](https://user-images.githubusercontent.com/6805694/142639732-f4f1befd-7ced-4c9d-846c-ae9cf65c814c.png)

**1.1.1:**
![image](https://user-images.githubusercontent.com/6805694/142639992-875ea6e6-c506-4aeb-a447-dc8331f9d9e4.png)

Could see the first one didn't send the **server_name** extension but still it's allowed to make the connection?

**Comment by mattcaswell** [comment]
SNI is not mandatory and was defined some years after the original TLS1.0 spec. So for many years it was quite normal for clients not to send SNI data. In more recent years it has become standard practice to always send SNI. In previous years servers tended to be tolerant of clients that had no SNI for this reason. If, SNI was present then they would select the correct certificate/key for the host, and if not the server would fallback to some default certificate/key. Depending on the hostname that the client thought it was connecting to the default certificate may or may not match the hostname in the default certificate (and therefore it may or may not work).

More recently servers have often been less tolerant of missing SNI data. Very often there just is no default certificate that would make sense if the SNI is missing (e.g. in the case where cloud providers front 100s of websites behind a single server). In such cases the server may just choose to fail immediately rather than try and send back a default certificate.

**Comment by mattcaswell** [comment]
> SNI is not mandatory

I should clarify that this is the case in TLSv1.2 and earlier. In TLSv1.3 its says that "clients SHOULD send this extension" (but not MUST).
