### ISSUE TITLE
crypto/aes/aes-586.o  Illegal subtraction 

### ISSUE THREAD

**Issue by teschulz** [openssl/openssl#1715]
I am trying to build openssl-1.1.0b on a Solaris 10 i386 box.

The configure command is:

./Configure shared --prefix=/opt/verylocal enable-rc5 enable-mdc2
  zlib-dynamic  -R/opt/verylocal/lib solaris-x86-gcc

The Compiler is gcc version 4.7.2. Perl is v5.20.1.

The error is:

gcc  -I. -Icrypto/include -Iinclude -DZLIB -DZLIB_SHARED -DDSO_DLFCN
-DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE
-DOPENSSL_PIC -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2
-DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM
-DSHA512_ASM -DRC4_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM
-DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM
-DOPENSSLDIR="\"/opt/verylocal/ssl\""
-DENGINESDIR="\"/opt/verylocal/lib/engines-1.1\"" -Wall -DL_ENDIAN
-DOPENSSL_NO_INLINE_ASM -O3 -fomit-frame-pointer -pthread -DFILIO_H 
-R/opt/verylocal/lib -fPIC -MMD -MF crypto/aes/aes-586.d.tmp
-MT crypto/aes/aes-586.o -c -o crypto/aes/aes-586.o crypto/aes/aes-586.s
Assembler: aes-586.s
        "crypto/aes/aes-586.s", line 1003 : Illegal subtraction in ...
        "OPENSSL_ia32cap_P - .L004pic_point"
**\* Error code 1

**Comment by teschulz** [comment]
Building the 64 bit version using target solaris64-x86_64-gcc works. But what we need is the 32 bit version. So I will have to stick with version 1.0.2* until this is fixed.

**Comment by dot-asm** [comment]
> So I will have to stick with version 1.0.2* until this is fixed.

But generated code for that particular module is identical for 1.0.2 and 1.1.0. Well, there is `private_` prefix added to names, but that's the only difference, code is otherwise identical... Can you really confirm that 1.0.2 works and 1.1.0 doesn't? With same compiler and everything? Anyway, key question is also what is your assembler and its version. You can see which assembler is invoked by copying-n-pasting command line and adding -v. Then you can run assembler separately and ask for version number. For reference I can't reproduce the problem with recent GNU assembler. I suppose your gcc is using /usr/ccs/as... But still how is it possible that 1.0.2 works while 1.1.0 doesn't. If you actually can confirm it. And if you can, could you compare the two files?

**Comment by teschulz** [comment]
I built 1.0.2j using target solaris-x86-cc which was removed in 1.1.0b. Target solaris-x86-cc invokes Sun C 5.11 SunOS_i386 2010/08/13 which probably includes it's own assembler. For 1.1.0b I switched to target solaris-x86-gcc. Re-trying 1.0.2j with that target does fail with the same error.

The as command generated by gcc is:
/usr/ccs/bin/as -V -Qy -s -xarch=generic -o crypto/aes/aes-586.o crypto/aes/aes-586.s

And the version displayed is:
as: SunOS 5.10 119961-07 Patch 05/05/2010

I will try to capture what the Sun cc compiler is doing with this file in 1.0.2j.

**Comment by teschulz** [comment]
Not quite the same error in 1.0.2j with target solaris-x86-gcc. It dies on x86cpuid.s instead. Illegal subtraction at line 158.

It looks like 1.0.2j with target solaris-x86-cc does not use assembly code at all. It must be doing everything with strait C code.

**Comment by dot-asm** [comment]
> It looks like 1.0.2j with target solaris-x86-cc does not use assembly code at all.

Right. And original reason ought to be the failure we are discussing here. Note that rationale behind removing this target in 1.1.x was two-fold: a) it *erroneously* turned out binary incompatible with solaris-x86-gcc; b) lack of assembler support is considered incompatible with contemporary standards of security. In other words you should feel discouraged to use solaris-x86-cc even in 1.0.2.

Anyway, what can be done about the problem. What works/is known to work is GNU assembler. gcc compiler package available for latest Solaris from vendor repositories is pre-configured to use GNU assembler and that's what we test and aim to support. On the other hand supporting out-dated OS is not exactly best way to spend our resources, especially if there seem to be a way to solve the problem by other means. In other words I'd suggest to configure your gcc installation to use GNU assembler. Unfortunately I don't have any wise words on how to do that, i.e. bootstrap compiler with GNU assembler support. Though it might be possible to pass compiler option as it is (I don't know if there is one for Solaris, but there used to be one on IRIX), in which case you'd only have to compile binutils alone. If additional compiler flag is all it takes, you can simply pass additional one at config/Configure command line.

**Comment by teschulz** [comment]
I can not find a compiler option specify the assembler. The man page suggests -mgas but gcc does not accept it.

To see if gas would work, at each assembler failure I used gcc -v to get the assembler command line and then ran gas by hand to get an object file. This went  well until I hit:

 crypto/chacha/chacha-x86.s:484: Error: no such instruction:
   `pshufb (%eax),%xmm6

There were 16 failures similar to that one.
Along the line I noticed that every Sun as failure involved OPENSSL_ia32cap_P -  something.

Just in case this is useful, here are the errors seen so far:

Assembler: aes-586.s
        "crypto/aes/aes-586.s", line 1003 : Illegal subtraction in ...
        "OPENSSL_ia32cap_P - .L004pic_point"


Assembler: crypto/aes/asm/aesni-x86.s
        "crypto/aes/aesni-x86.s", line 2857 : Illegal subtraction in ...
        "OPENSSL_ia32cap_P - .Lkey_const"


Assembler: crypto/bn/asm/bn-586.s
        "crypto/bn/bn-586.s", line 11 : Illegal subtraction in ...
        "OPENSSL_ia32cap_P - .L000PIC_me_up"


Assembler: crypto/bn/asm/x86-gf2m.s
        "crypto/bn/x86-gf2m.s", line 246 : Illegal subtraction in ...
        "OPENSSL_ia32cap_P - .L000PIC_me_up"


Assembler: crypto/bn/asm/x86-mont.s
        "crypto/bn/x86-mont.s", line 63 : Illegal subtraction in ...
        "OPENSSL_ia32cap_P - .L003PIC_me_up"


Assembler: chacha-x86.s
        "crypto/chacha/chacha-x86.s", line 18 : Illegal subtraction in ...
        "OPENSSL_ia32cap_P - .Lpic_point"


crypto/chacha/chacha-x86.s:484: Error: no such instruction:
   `pshufb (%eax),%xmm6

**Comment by dot-asm** [comment]
> I can not find a compiler option specify the assembler. The man page suggests -mgas but gcc does not accept it.

But it should be possible to bootstrap gcc with gas... But as already mentioned, I don't have any advice on how to do that. Though there might be another possibility. Customarily gcc driver *looks* for assembler prior it calls /usr/ccs/bin/as. This means that it might be possible to solve the problem without recompiling by gcc by strategically placing GNU assembler binary. If you `touch a.s` and `truss -t access gcc -c a.s` you should get the idea...

> crypto/chacha/chacha-x86.s:484: Error: no such instruction:
> `pshufb (%eax),%xmm6

Oh! Well, your compiler seems relatively fresh, 4.7.2, which ought to mean that you update stuff yourself. All it takes is to update even GNU assembler. However, formally speaking it's actually a bug, since we do support SSSE3 instructions with non-SSSE3-capable assemblers, at least partially.  https://github.com/openssl/openssl/pull/1873 addresses this problem. Unfortunately you can't verify it without making gcc use GNU assembler. This is because chacha20-x86.pl queries GNU assembler version. If you can't make your gcc work with GNU assembler, then you'd have to configure with additional no-sse2 option [which disables all vector code, which, depending on your processor, might be bad from security viewpoint].

**Comment by teschulz** [comment]
I now  have the latest gas, version 2.27.  Running gas by hand on each failure does assemble everything but then when make tries to link the shared libraries there are undefined symbols. The symbols print out as a bunch of spaces.

Using truss on gcc did not show any attempt to locate gas, it went directly to /usr/ccs/bin/as.  I tried moving /usr/ccs/bin/as out of the way and putting gas in as /usr/ccs/bin/as. That did not work as gcc puts -xarch=generic on the as command line, which gas does not like.

So it looks like I will have to rebuild gcc to use gas. That will take awhile. I  wonder if programs  and libraries built with gcc using gas will be compatible with programs and libraries built with Solaris C or gcc using Solaris as.

I wonder what is OPENSSL_ia32cap_P and why can gas subtract things from it while as can not.

**Comment by dot-asm** [comment]
> I wonder if programs and libraries built with gcc using gas will be compatible with programs and libraries built with Solaris C or gcc using Solaris as.

They totally are. Well, it wasn't actually verified on venerable Solaris 10 on i386, but there is no reason to believe that it (at least shared libs) wouldn't work.

> I wonder what is OPENSSL_ia32cap_P

It's processor capability vector that is used to choose most optimal code for current processor at run-time. I mean there is a number of code paths for different algorithms, optimized for a number of different processors, x86 in this case, to choose from, and OPENSSL_ia32cap_P is one giving directions.

> and why can gas subtract things from it while as can not.

I'd say that it's not about ability, but rather will. In sense that /usr/ccs/as effectively refuses to perform that kind of operation and generate specific kind of relocation, even though it is actually defined in ELF and is supported by Solaris linker. I probably should also point out that it's not that it's impossible to make it work with /usr/ccs/as, but rather that it's too much work and potentially disruptive changes. Modules in question are used with multiple operating systems, Windows, MacOS X, Android, Linux, all flavours of BSD, and work fine... Yes, people like you might feel outside, but as long as there is way around it, gcc with GNU assembler in this case, we will keep pushing for it.

**Comment by teschulz** [comment]
With gcc rebuilt to use /opt/local/bin/gas, I can build openssl-1.1.0b and make test passes.

Interesting that the 64 bit version built OK using the Solaris as.

How are you detecting the version of gas in your patch shown in change #1873? I put the new gas in /opt/local/bin and left the Solaris version alone in /usr/sfw/bin.

**Comment by dot-asm** [comment]
> With gcc rebuilt to use /opt/local/bin/gas, I can build openssl-1.1.0b and make test passes.

Great. Could you do two things:

- write couple of words on how to compile gcc with gas for public reference (is it sufficient to have GNU assembler on $PATH during configuration or does one have to pass special flag to configure);
- review https://github.com/openssl/openssl/pull/1911 and confirm that you can compile master branch without `-DOPENSSL_NO_INLINE_ASM`;

**Comment by dot-asm** [comment]
> How are you detecting the version of gas in your patch shown in change #1873?

`gcc -Wa,-v -c -o /dev/null -x assembler /dev/null` is invoked to snatch assembler version. This means it doesn't matter where does assembler resides, what matters is where does gcc finds it.

**Comment by teschulz** [comment]
> write couple of words on how to compile gcc with gas for public reference (is it sufficient to have GNU
> assembler on $PATH during configuration or does one have to pass special flag to configure);

I configured gcc to use gas by adding the following to the configure command line:
--with-gnu-as --with-as=location-of-gas

I found documentation on how to do that in INSTALL/specific.html in the gcc source. Running ./configure --help does not show these options although running  ./gcc/configrue --help does show them. When configuring gcc, the main configure and then make run the other configure programs.

It may be that putting gas in the correct directory relative to the location of the gcc installation would allow configure to find gas by itself, but I had specified /opt/local/gcc/gcc-4.7.2/5.10 as the location
to install gcc and put gas into /opt/local/bin/gas. So I used --with-as=/opt/local/bin/gas on the
configure command line. The documentation does not say what defaults may be applied.

**Comment by teschulz** [comment]
> review #1911 and confirm that you can compile master branch without -DOPENSSL_NO_INLINE_ASM;

I got git and built master. It built OK and make test passes. I then moved the new gas out of the way and installed a link to the older Solaris gas and built again. This also builds OK and make test also passes. I did verify that the sizes of the libraries are different with the new gas libcrypto.so size 2452480 and the old gas libcrypto.so size 2434192.

**Comment by dot-asm** [comment]
Thanks, appreciated very much! I consider this issue as resolved. If you, @teschulz, won't close it, I'll do it tomorrow (as I'm signing off for today).

**Comment by teschulz** [comment]
I think it's good. Given the way you detect the gas version, you can probably detect that something other than gas, such as Solaris as, is being used. Your call as  to if you think that would be a good idea.

**Comment by vladak** [comment]
For reference, the bug (or rather enhancement) that tracks the issue in the Studio assembler has a synopsis that reads _treat undefined subtraction operand in leal instruction as relocation entry_. The question is if this will be ever fixed.

**Comment by orcl-jlana** [comment]
workaround, which unfortunately has an impact on speed, is building the library with `no-asm` option
