### ISSUE TITLE
s_client -proxy option broken in master

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#17247]
The s_client `-proxy` option no longer works in master:

````
$ openssl s_client -proxy localhost:8888 -connect localhost:4433 -trace
Connecting to 127.0.0.1
CONNECTED(00000003)
s_client: HTTP CONNECT failed, bad HTTP version HTT
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 70 bytes and written 65 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
This TLS version forbids renegotiation.
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
````
This has regressed since OpenSSL 3.0 where it works fine. It was broken by commit 2ff286c2 in PR #15847.

**Comment by mattcaswell** [comment]
Ping @DDvO.

**Comment by DDvO** [comment]
I had a fix for this issue already in one of my open pipelines.
Extracted it to #17250.

**Comment by DDvO** [comment]
Would be good if we had tests also for the HTTP(S) proxy functionality
such that issues like this one would have been caught right away.

Yet this appears awkward to do because some client, proxy, and server stub needs to be set up using sockets and in part with TLS.
Maybe someone who has experience with the TLS tests can provide this.
