### ISSUE TITLE
Multithread SSL connection

### ISSUE THREAD

**Issue by srshashi** [openssl/openssl#17377]
I'm trying to create multithread ssl connection where read/write happen on different thread but getting SSL_Error_Syscall at random times. 
Openssl version 1.1.1c. 

According to openSSL FAQ(https://www.openssl.org/docs/faq.html#PROG), using ssl connection object on multithread is not thread safe but in the next line it says for version 1.1.0 nothing needs to do? 

Please, let me know if we can read/write on different thread or not?

**Comment by t-j-h** [comment]
In general, you cannot share an SSL connection between threads. 

The FAQ is about registering callbacks for locking handling for things like the SSL_CTX which can be shared.
Prior to 1.1.0 you had to provide and register the callbacks yourself, in 1.1.0 and later the callbacks are automatically provided and automatically registered.

**Comment by srshashi** [comment]
Thanks @t-j-h for FAQ clarification. But if we don't share objects like SSL_CTX between multiple SSL connections, do we still need to set locking function for versions prior to 1.1.0? 

"In general, you cannot share an SSL connection between threads."  
Why openssl do not allow read/write on different threads? Is there any SSL protocol limitation? 

Also, i tried creating non-blocking socket and take locks on SSL_read and SSL_write(seperate thread) but still getting SSL_ERROR_SYSCALL. What are the reasons when openssl give SSL_ERROR_SYSCALL? How can we debug it?

**Comment by mattcaswell** [comment]
> But if we don't share objects like SSL_CTX between multiple SSL connections, do we still need to set locking function for versions prior to 1.1.0?

If you are calling OpenSSL from multiple threads then you need to provide the locking callbacks for OpenSSL 1.0.2 or earlier - regardless of whether objects are shared between threads.

> Why openssl do not allow read/write on different threads?

If an OpenSSL object was shared between multiple threads then we would have to use extensive locking to ensure correct operation. Since locking can add significant performance penalties we try to avoid this where possible.

> Also, i tried creating non-blocking socket and take locks on SSL_read and SSL_write(seperate thread) but still getting SSL_ERROR_SYSCALL. What are the reasons when openssl give SSL_ERROR_SYSCALL? How can we debug it?

From the man page:

````
=item SSL_ERROR_SYSCALL

Some non-recoverable, fatal I/O error occurred. The OpenSSL error queue may
contain more information on the error. For socket I/O on Unix systems, consult
B<errno> for details. If this error occurs then no further I/O operations should
be performed on the connection and SSL_shutdown() must not be called.

This value can also be returned for other errors, check the error queue for
details.
````
So, check `errno` to see if that gives you any clues. This error can also occur in 1.1.1 and earlier with `errno` set to 0 to indicate that the remote peer has disconnected abruptly without cleanly shutting down the connection.

**Comment by srshashi** [comment]
@mattcaswell thanks for answering questions. 

I checked the `errno` , it is set to 0, looks like connection closed by peer.
