### ISSUE TITLE
Error extracting keyentry aliases from PFX

### ISSUE THREAD

**Issue by longnguk** [openssl/openssl#17414]
keytool and IBM Key Management tools would fail to read A PKCS12 keystore generated by openssl v3.0.1. The exact same commands using openssl v1.1.1 would generate PKCS12 keystore that can be accessed by the tools without issues.

Steps to reproduce:
1. Generate a self-signed certificate (or use a CA signed certificate)
```
openssl req -newkey rsa:2048 -nodes -keyout tlskey.pem -subj "/CN=localhost" -x509 -days 3650 -out tls.pem
```
2. Create a PKCS12 keystore
```
openssl pkcs12 -export -in .\tls.pem -inkey .\tlskey.pem -out tls.p12

```
3. Use either keytool or ikeyman (IBM Key Management) to access the keystore
```
keytool -list -keystore tls.p12 -storetype pkcs12
keytool error (likely untranslated): java.io.IOException: Error extracting keyentry aliases from PFX
```

**Comment by t8m** [comment]
This is most likely due to different default algorithms used for encrypting the PKCS12 file. Use the -legacy option.

**Comment by longnguk** [comment]
Thank you for the update. Unfortunately, the -legacy option doesn't seem to work with a pre-compiled 3.0.1 Windows 64. (Windows 10).
```
pkcs12 -export -in .\tls.pem -inkey .\tlskey.pem -out tls.p12 -legacy
pkcs12: unable to load provider legacy
Hint: use -provider-path option or OPENSSL_MODULES environment variable.
48340000:error:12800067:DSO support routines:win32_load:could not load the shared library:crypto\dso\dso_win32.c:108:filename(C:\Program Files\OpenSSL\lib\ossl-modules\legacy.dll)
48340000:error:12800067:DSO support routines:DSO_load:could not load the shared library:crypto\dso\dso_lib.c:152:
48340000:error:078C0105:common libcrypto routines:provider_init:init fail:crypto\provider_core.c:907:name=legacy
```

**Comment by paulidale** [comment]
Is this related to #17426 ?

**Comment by t8m** [comment]
> Is this related to #17426 ?

I suppose so.

**Comment by t8m** [comment]
> pkcs12: unable to load provider legacy
> Hint: use -provider-path option or OPENSSL_MODULES environment variable.

Do you have the legacy provider installed at path where the OpenSSL expects it? Or you need to set the OPENSSL_MODULES environment variable to the path where the legacy.dll is placed.

**Comment by longnguk** [comment]
@t8m : I am using the ready-built openssl v3.0.1 for Windows (https://slproweb.com/products/Win32OpenSSL.html) that doesn't appear to have the legacy.dll included. Do you happen to have a ready-built v3.0.1 for Windows that I could try?

**Comment by longnguk** [comment]
> Is this related to #17426 ?

I may have mistaken, but the #17426 implies the use of openssl v1.1.1k whereas this is specific to the latest version 3.0.1. In other words, the error "Error extracting keyentry aliases from PFX" causes by version 3.0.1

**Comment by paulidale** [comment]
The OpenSSL project doesn't distribute binaries for any platform, just the source.
I don't know how to extract files from one of our Windows CI builds or even if it is possible.

**Comment by xlouk** [comment]
> ... this is specific to the latest version 3.0.1. In other words, the error "Error extracting keyentry aliases from PFX" causes by version 3.0.1

Had the same issue, but could solve it. I obtained my 3.0.1 64 Windows package from http://wiki.overbyte.eu/wiki/index.php/ICS_Download.
The Pack contains legacy-x64.dll. Rename it to legacy.dll, otherwise it is not found.

This batch sample will produce a PFX file. You need to replace Your... und My... with your individual settings:

setlocal enabledelayedexpansion
Set "OpenSslPath=<YourDrive:\YourPath>\openssl-3.0.1-win64"
REM Set OPENSSL_MODULES to the path of the pack
Set "OPENSSL_MODULES=!OpenSslPath!"
Set OpenSSL=!OpenSslPath!\openssl.exe"

echo = Create Key
"!OpenSSL!" genrsa -out server.key 4096

echo = Create certificate request
"!OpenSSL!" req -config "YourPathTo\openssl.cnf" -new -key server.key -out server.csr -sha256 -subj "/C=YourCountryShortCut/ST=YourState/L=YourTown/O=YourCompany/OU=SC/CN=YourFQDN/emailAddress=YourEmail" 

echo = Verify certificate request
"!OpenSSL!" req -text -noout -verify -in .\server.csr

echo = Generate self signed certificate with e.g. 365 due days applied in certificate. 
"!OpenSSL!" x509 -req -days 365 -in server.csr -signkey server.key -out server.crt 

echo = Now export the certificate and private key to create a PFX file
""!OpenSSL!"" pkcs12 -export -in server.crt -inkey server.key -name MyAlias -out server_cert-and-key.pfx -legacy -passout pass:MyPassword

That will succesfully output a PFX File with openSSL 3.0.1.
