### ISSUE TITLE
How can I distinguish  2-way TLS(mutual TLS) from one-way(single-way TLS by Wiresahrk app?

### ISSUE THREAD

**Issue by uzeyiryenilmez** [openssl/openssl#17438]
During the TLS session test using Wireshark, I can see the server sends its certification but I can not see the Client sends its own certification to the server. Why?

**Comment by mspncp** [comment]
I guess with "mutual TLS" you mean a TLS handshake with mutual authentication. If you have specific questions about dissecting and/or decrypting TLS traffic using Wireshark, I'd recommend asking your questions on the Wireshark mailiing list, ideally with a sample capture file, this will maximize the probability for a helpful reply. But before asking your questions you might want to consult the [Wireshark TLS Wiki](https://wiki.wireshark.org/TLS). Because IMHO your current question appears a little bit unspecific to me: you wonder about the missing client certificate but don't mention whether you encountered a **CertificateRequest** in the capture of your alleged [Client-authenticated TLS handshake](https://en.wikipedia.org/wiki/Transport_Layer_Security#Client-authenticated_TLS_handshake). So maybe you should try to obtain a deeper understanding of the TLS handshake first (from e.g. Wikipedia and/or RFC) and analyze the problem in more detail yourself, before asking on the mailing list. I'm sure you'll learn a lot more about TLS like this.

**Comment by bernd-edlinger** [comment]
You can force the client certificate this way:
`openssl s_server -Verify -1`

**Comment by uzeyiryenilmez** [comment]
> I guess with "mutual TLS" you mean a TLS handshake with mutual authentication. If you have specific questions about dissecting and/or decrypting TLS traffic using Wireshark, I'd recommend asking your questions on the Wireshark mailing list, ideally with a sample capture file, this will maximize the probability for a helpful reply. But before asking your questions you might want to consult the [Wireshark TLS Wiki](https://wiki.wireshark.org/TLS). Also, IMHO your current question appears a little bit unspecific to me: you wonder about the missing client certificate but don't mention whether you encountered a **CertificateRequest** in the capture of your alleged [Client-authenticated TLS handshake](https://en.wikipedia.org/wiki/Transport_Layer_Security#Client-authenticated_TLS_handshake). So maybe you should try to obtain a deeper understanding of the TLS handshake first (from e.g. Wikipedia and/or RFC) and analyze the problem in more detail yourself, before asking on the mailing list. I'm sure you'll learn a lot more about TLS like this.
The question is specific,and you already answered my question that " need client cert request parameter" the thing is what makes you think that " I should understand deeper" maybe I don't want to understand deep for now, I want to focus on other thing. If a person wants he can Learn anything. Should I tell you that you should study customer support soft skills.
