### ISSUE TITLE
pkcs12 passout no longer works with empty password

### ISSUE THREAD

**Issue by vwillyams** [openssl/openssl#1747]
This command "openssl pkcs12 -in $1 -out ${TMP_OUT} -passin pass:"$2" -passout pass: 2>&1" executes without issue in 1.0.2h however in 1.0.2j this fails with an "Error outputting keys and certificates".

**Comment by funbsd** [comment]
Is it possible make it work without password right now?

**Comment by levitte** [comment]
With 1.0.2h, have you checked that you actually get some sensible output?

It turns out that what has happened between 1.0.2h and 1.0.2j is that we got a tiny bit better at checking errors, and this is a consequence...  in 1.0.2h, no error was displayed, but I suspect that the resulting output was crap, or at least missing a private key...

To sum it up, a zero length output password has never been allowed, it's just that the `openssl pkcs12` command didn't catch and display the error before 1.0.2j.

**Comment by funbsd** [comment]
@levitte 
Is it possbile to create a private key without password?
I do not want a private key with password.
But I have to when run command below: 
openssl genrsa -aes256 -out cert.key 2048

**Comment by levitte** [comment]
`-nodes`

**Comment by funbsd** [comment]
thanks.
openssl genrsa without -aes256 works.
openssl req -nodes works as well.
