### ISSUE TITLE
Empty statement in x509_trust.c

### ISSUE THREAD

**Issue by rillig** [openssl/openssl#17525]
[x509_trust.c](https://github.com/openssl/openssl/blob/57645339ab645fe5abffe14fc005b5402ce03b84/crypto/x509/x509_trust.c#L169) says:
~~~c
goto err;;
~~~

While the extra semicolon is harmless, it nevertheless smells. I only noticed it because I made the same mistake in my own code. I then searched the whole NetBSD/src tree for other instances and found some of them in the OpenSSL source.

**Comment by tmorganPDC** [comment]
Outlook not looking good. Magic 8ball.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Roland Illig ***@***.***>
Sent: Saturday, January 15, 2022 5:44:38 PM
To: openssl/openssl ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [openssl/openssl] Empty statement in x509_trust.c (Issue #17525)


x509_trust.c<https://github.com/openssl/openssl/blob/57645339ab645fe5abffe14fc005b5402ce03b84/crypto/x509/x509_trust.c#L169> says:

goto err;;

While the extra semicolon is harmless, it nevertheless smells. I only noticed it because I made the same mistake in my own code. I then searched the whole NetBSD/src tree for other instances and found some of them in the OpenSSL source.
