### ISSUE TITLE
Export PEM to PFX without creating password?

### ISSUE THREAD

**Issue by maroonbells** [openssl/openssl#17563]
Has v3 changed .pfx files so they no longer can be created without a password as opposed to password=empty-string?

I'm trying to create a no-password cert.pfx that I can use in the AdiIRC IRC client, to login to an IRC server using SASL, without being prompted for the password every time I get disconnected, including when I'm not at the keyboard.

AdiIRC needs the cert to be in pfx format, so after creating a self-signed cert.pem containing both the public RSA cert and the private RSA key, I need to export this to .pfx format. In OpenSSL v1.1.1L I can press <ENTER> at the password prompts from:

openssl pkcs12 -in cert.pem -inkey cert.pem -export -out cert.pfx

... and AdiIRC lets me use cert.pfx to login to the server without any password prompt. In OpenSSL v3.01, the exact same command generates a cert.pfx which is different enough that the IRC client thinks it needs to ask for a password, and it fails when I just press <ENTER> - I guess because no-password-used is not the same as password=empty-string.

If v3.01 creates a .pfx using a short password, I can input that at the password prompt each time I login to the site, but I don't want to do that every time. It doesn't help to use -noenc because v3.01 says it ignores that for the -export switch.

**Comment by tomato42** [comment]
If you enter empty password (just press enter on the prompt), then openssl 3.0 will create a PKCS#12 file both with 3.0.0 and 1.1.1. The difference between them are the encryption options used, 1.1.1 defaults to the ancient pbeWithSHA1And40BitRC2-CBC and pbeWithSHA1And3-KeyTripleDES-CBC while 3.0.0 defaults to AES-256-CBC.
The difference is that AES-256-CBC uses PBKDF2 for key derivation, not the PKCS#12 KDF, the difference being that the PKCS#12 KDF uses NULL terminated UCS-2 strings, while PBKDF2 uses non-NULL terminated UTF-8 strings.

So I'd guess that the issue is with AdiIRC handling of empty passwords for modern PKCS#12 files rather than bad 3.0.0 behaviour.
You should be able to verify this by using 1.1.1 export like so: `openssl pkcs12 -in localhost.crt -inkey localhost.key -export -keypbe aes-256-cbc -certpbe aes-256-cbc -out cert.pfx`

**Comment by t8m** [comment]
You can also use the `-legacy` option with 3.0 to produce the files with the same algorithms as 1.1.1.

**Comment by maroonbells** [comment]
ok I was able to have 1.1.1 reproduce the unwanted 3.0 behavior using tomato42's command in 1.1.1
However, when i tried to use -legacy to make 3.0  create a pfx without any password,  it generates an error message wanting to load a legacy provider. I'm using one of the precompiled binaries - is this failing because they did not compile it to include legacy support?

**Comment by t8m** [comment]
> I'm using one of the precompiled binaries - is this failing because they did not compile it to include legacy support?

Unfortunately we do not build and ship the precompiled binaries so we cannot help with that. However either there is no legacy provider module at all, or it is not installed at a place where it is looked for.

**Comment by mohdwaseem** [comment]
-legacy option works with me (Library: OpenSSL 3.2.3 3 Sep 2024)
