### ISSUE TITLE
CRL update looks impossible in X509_STORE

### ISSUE THREAD

**Issue by OlegPekar** [openssl/openssl#17639]
Imagine we have a long lasting X509_STORE instance with lifetime of several months. We have a CA certificate in this store that has CRL location configuration. The application downloads the next CRL from that location within configured interval (e.g. one a week) or some time before the time when the current CRL is going to be expired. 

When first CRL file arrives, the application adds it to the store using `int X509_STORE_add_crl(X509_STORE *ctx, X509_CRL *x);`

However when the next CRL file is downloaded - there's no API to replace the existing CRL. If we just add it again - we will have two CRL with the same issuer name and the first of them will always be taken. 

I see three ways to overcome this problem:

1. Add function `X509_STORE_remove_crls(X509_STORE *ctx, X509_NAME* issuer) `- remove all CRLs with the given issuer name. Then we can remove the old CRL and add the new one.
2. Add function `X509_STORE_replace_crl(X509_STORE *ctx, X509_CRL *x)` - remove all CRLs with the given issuer name and add the new one
3. Change the function `X509_STORE_add_crl() `above to always replace the CRL with the same issuer name so a single CRL per issuer is kept (anyway only the first will be used in certificate validation)

I implemented option 3 in my application and can contribute it. What is the suggested way to fix from the maintainers? 

Thanks
Oleg

**Comment by t8m** [comment]
If there is really no functional use of the current semantics of X509_STORE_add_crl(), i.e. there is currently no way how to use the second CRL that is added by the second call, then implementing 3. would be OK, IMO. Otherwise I suppose the 2. is preferable to 1. so you do not have to have a window when the CRL is removed and no replacement being in the store which might require extra locking in the application.

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of the 3.4 dev cycle, barring further input
