### ISSUE TITLE
Unexpected fragmentation with large writes and max_fragment_length=4096

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#17656]
Using current master (eafd3e9d07e9).

When using `openssl s_server -rev` to make openssl send large records, I've noticed that every line size sent to server is handled as expected, when I send 11111 bytes, I get 11111 bytes back. Similarly, when I negotiate max_fragment_length extension, the server will answer with packets fragmented in a way the client sent it. Negotiate 4096 byte records, send two 4096 byte and one 512 byte records, receive three records back, two 4096 byte long and one 512 byte long.

That is with the exception of negotiation of 4096 byte max_fragment_length and 16KiB long application data line, then server replies with 5 records, four 3584 byte long and one 2048 byte long.

This does not happen without max_fragment_lenght, or with smaller fragment sizes like 2048, 1024 or 512.
It also happens with ciphers with different overhead, like TLS_RSA_WITH_AES_128_CBC_SHA, or TLS_RSA_WITH_AES_128_CBC_SHA256.
But not with TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_RSA_WITH_AES_128_GCM_SHA256 or TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256

Reproducer:
```
openssl req -x509 -newkey rsa -keyout localhost.key -out localhost.crt -subj /CN=localhost -nodes -batch
openssl s_server -key /tmp/localhost.key -cert /tmp/localhost.crt -rev -cipher @SECLEVEL=0:ALL -quiet
```
in another console:
```
git clone https://github.com/tomato42/tlsfuzzer
pushd tlsfuzzer
# won't be needed after https://github.com/tlsfuzzer/tlsfuzzer/pull/762 gets merged
git checkout length-testing
git clone https://github.com/tlsfuzzer/tlslite-ng .tlslite-ng
ln -s .tlslite-ng/tlslite tlslite
git clone https://github.com/tlsfuzzer/python-ecdsa .python-ecdsa
ln -s .python-ecdsa/src/ecdsa ecdsa
PYTHONPATH=. python scripts/test-lengths.py --size-limit 4096 -n 0 "length: $((1024*16))"
```
Use `-C TLS_RSA_WITH_AES_128_CBC_SHA` or `-C TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256` to test different ciphers (place before the name of the test, i.e. "length...")
Run without `"length: $((1024*16))"` to test all lengths.

**Comment by mattcaswell** [comment]
Even more curiously if I add `-trace` onto the end of the s_server command line the test suddenly starts to pass!

**Comment by mattcaswell** [comment]
The reproducer seems to run 3 tests 2 of which pass and 1 of which fails. Is it possible to get it to only run the 1 failing test?

**Comment by mattcaswell** [comment]
It's a feature! Sort of.

This is actually due to the multiblock performance enhancement. This kicks in if you are sending more than a set amount of data and encrypt-then-mac is not being used, and the cipher supports it. In such a case some ciphers can actually create the whole TLS records themselves and can encrypt 4 or 8 records worth of data all in one go.

In this case, sending 16KiB data with 4096 max_fragment_length the code is detecting that it can do 4 records in one go via multiblock. The fragment size to send is actually reduced slightly for the period that multiblock has kicked in due to this code:

https://github.com/openssl/openssl/blob/eafd3e9d07e99583a1439bb027e4d6af43e2df27/ssl/record/rec_layer_s3.c#L448-L450

So when multiblock is operational we are actually using a fragment size of 4096 - 512 = 3584. So the 4 records you see of 3584 bytes have been encrypted using the multiblock code. Finally there is 2048 bytes remaining and it is sent in a fifth and final record.

I actually doubt that multiblock should be kicking in, in the case that max_fragment_length has been negotiated. Multiblock is optimised for full length records. I doubt we see the performance benefit for smaller fragment lengths, and it is probably a bug that it is kicking in for these smaller fragments.

**Comment by mattcaswell** [comment]
> Not sure if it's a bug though, looking at benchmark speeds at my 4-core 8-thread i7-8650U @ 1.9GHz I'm getting:

Thanks. Looks like we're best to keep that behaviour then.
