### ISSUE TITLE
Windows build of 1.0.2j issues with CPU/platform settings

### ISSUE THREAD

**Issue by levicki** [openssl/openssl#1766]
While I was building 32-bit build of 1.0.2j on Windows using latest ActiveState perl and VS2013 Update 5, I have noticed the following issues:
1. `no-sse2` option seems to be ignored in perl/VS build -- there is a warning about unknown option printed. Furthermore, compiled DLLs still contain SSE2 code, and they crash on Pentium III machines. Reason is that VS 2013 C++ compiler defaults to `/arch:SSE2`. Therefore, If `no-sse2` option is specified, the configure script should add the compiler switch `/arch:SSE`. Also, if `386` option is specified (which is also reported as unknown by configure), then the configure script should add the compiler switch `/arch:IA32`, and change the `#undef I386_ONLY` in opensslconf.h.
2. Specifying `no-hw` option together with `enable-static-engine` leads to unresolved externals during DLL linking phase. It is not obvious how to fix this, at least to me.
3. There is no way to specify target platform during configuration -- i.e. -D_WIN32_WINNT=0x501 if you want a Windows XP build. The default OS and subsystem version written in DLL PE  optional header is 6.0, while for XP it should be 5.1 which means that the `LFLAGS` should be set to `/subsystem:console,5.1`. Finally, as far as I know, DLL projects in Visual Studio always specify the subsystem as `windows`, not `console` so perhaps `MLFLAGS` should be set accordingly.

Regards,
Igor Levicki

**Comment by dot-asm** [comment]
> no-sse2 option seems to be ignored in perl/VS build -- there is a warning about unknown option printed

The warning [at ms\do_nasm step] can be safely ignored. However, there seem to be misunderstanding about no-sse2. It doesn't control compiler ability to generate SSE2 code, it controls only assembly code generation. I.e. if you specify no-sse2 no SSE2 (or post-SSE2) code will be generated when *assembly* modules are generated. Same applies to 386 option, i.e. it affects only generation of assembly modules. Compiler has to be controlled separately...

> the configure script should add the compiler switch /arch:*

Well, one would be able to argue in favour only if *all* compilers supported it. Well, one can argue that all *contemporary* compilers support it, and that I don't really have a case. But trouble is that we make no specific claims about compiler version :-( But it's not impossible to solve this particular problem. All you need to do is to pass additional compiler flag at configure stage, e.g. `perl Configure VC-WIN32 -arch:SSE`. Note that you don't actually have to specify no-sse2, because SSE2 capability is detected at run-time and post-SSE code assembly paths won't be executed and won't crash your application.

> There is no way to specify target platform during configuration -- i.e. -D_WIN32_WINNT=0x501 if you want a Windows XP build. ... /subsystem:console,5.1.

There seem to be misconception. _WIN32_WINNT macro only controls what is exposed through system headers, it has no effect on linker options. And it should be noted that default for 1.0.2 is actually more conservative than 0x501.

> The default OS and subsystem version written in DLL PE optional header is 6.0, while for XP it should be 5.1

Default for your compiler, yes. In non-Windows case it would be possible to resolve the problem by passing an additional flag at config time. While on Windows you have an option set `LINK` environment variable to change the default, e.g. `set LINK=/subsystem:console,5.1`.

On related note. One can argue that configuration should recognize even /flags (currently it recognized only -flags) and should even recognize /link to pass additional linker-specific flags (currently it recognized Unix-centric -l and -Wl). But it would be hardly appropriate to do that in maintenance branch such as 1.0.2.

**Comment by levicki** [comment]
To be clear, I was talking only about Windows build using Microsoft compiler. I understand that OSS community doesn't have much interest in putting additional effort into supporting that particular combination, but if you have already implemented build system for that, then it might be prudent to at least document what that build does (or doessn't) and how.

For example, how was I supposed to know that no-sse2 option affects only assembler code? Yes, I could have checked that 100+ KB configure script to see what it (un)defines, then grep all *.c and *.asm files to see what code is affected.

The first step already requires one to be familiar with GNU build system which most Windows developers aren't, and the second step requires considerable not-your-own-code reading skill, including in this case assembler, which might have as well been written in AT&T syntax and which even I who is proficient in x86 assembly might not be able to parse easily.

Furthermore, for me (and I am sure for many other non-native English speakers), ````no-sse2```` option in configure implies that no SSE2 code whatsoever will be generated either by compiler or assembler or by a neural network running a perl script which translates haiku directly into x86 opcodes if that ever happens to become a part of build process.

As for the compiler and options, all relevant compilers have some sort of ````/arch```` switch. All Microsoft compilers define _MSC_VER and it is trivial to check which one is used and set switches accordingly. In other words, it is a rather poor excuse not to have the full control of the compiler output at least for the compilers from 2005 onwards just because the old ones might not support it -- if someone still needs to compile using old and unsupported compiler versions such as gcc 2.95 or VC6 I am sure they will have a lot more things to change than just a single switch anyway.

As for _WIN32_WINNT there is no confusion -- macro is defined to prevent you from accidentaly using a newer OS feature in the code (not only new API but also different version of some system structure layout). Linker version specified in ````/subsystem```` is related to executable loading. I am aware that I can change that myself as well, but my point was that the build system should have build targets which target certain platforms (Windows hardly counts as a single platform), and not rely on compiler/linker defaults.

**Comment by dot-asm** [comment]
> For example, how was I supposed to know that no-sse2 option affects only assembler code?

Correct, *we* can't expect you to know the history behind it(*), but at the same it's not exactly appropriate for *you* to imagine what it does, and complain about provided explanation, arguing that we are not interested in supporting Windows. We are, we just support it in a way that allows us to optimize the way we do it. By sharing as much as possible, be it code, C or assembly, build and configuration infrastructure... It's not unreasonable compromise.

> As for the compiler and options, all relevant compilers have some sort of /arch switch.

So pass one. This kind of discussion was taken several times and it's impossible to get it right. I for one find it inappropriate to rely on compilers defaults that compile explicitly for processor compiler is running on for the moment of compilation, and usually argue for specifying kind of a *least* common denominator in configuration line, but I'm usually voted down. And it's not a problem. Nor should it be for you. We can't cover all possibilities...

> my point was that the build system should have build targets which target certain platforms (Windows hardly counts as a single platform), and not rely on compiler/linker defaults.

There is time and place for this kind of discussion. Ideal time is beta period prior a release, and place is openssl-dev list. Also keep in mind that it's not unreasonable to be reluctant(**) to make changes to branches that are not in active development stage, such as 1.0.2. Especially if there is a way to work around the problem.

(*) no-sse2 originates from time when you could find yourself in situation when OS running on by-then-hottest-news P4 processor doesn't support P4 register extensions;

(**) wording is chosen to indicate that it's not like that changes are impossible, only that they are not taken lightly;

**Comment by levicki** [comment]
Thanks for the explanation.

If it is not possible to change default compiler options then how about at least updating the INSTALL.W32 with the relevant information we discussed here?

I propose including clarification that ````no-sse2```` is not necessary because of auto-detection, that it does not disable compiler and C runtime SSE2 code, and that passing ````perl Configure VC-WIN32 -arch:SSE```` (or ````-arch:IA32````) is the way to make sure code will work on older CPUs.

As for the linker, how do you propose to pass ,5.1 part of the subsystem option without having to edit generated makefile? You said to use ````set LINK=/subsystem:console,5.1```` but that will set the executable type to console for every component built, and if I am not mistaken OpenSSL DLLs should be ````/subsystem:windows``` because they do not require console in order to work.

**Comment by dot-asm** [comment]
As for no-sse2. There actually is whole story in INSTALL file, so that we effectively can expect you to know it. As for /arch flag. Apparently it was recently changed. Up to VS2013 lack of /arch flag actually meant "don't use processor extensions", while pasts t

**Comment by dot-asm** [comment]
Oh! Wrong click. So I start over.

As for no-sse2. There actually is whole story in INSTALL file, so that we effectively can expect you to know it.

As for /arch flag. Apparently it was recently (in terms of this project lifetime) changed. Up to VS2012 lack of /arch flag actually meant "don't use processor extensions", while past that no /arch flags means "use SSE2" by default. In other words up to recently everything worked as expected, i.e. *default* configuration would actually produce desired outcome.

As for `set LINK=/subsystem:console,5.1` and it's suitability for DLL. Why not just try it and see that it's actually ignored when you link DLL? I mean it *is* ignored, so that build comes out just fine.

**Comment by dot-asm** [comment]
As for closing-re-opening. As already said, I accidentally clicked wring button. However, the issue can as well be closed. I've submitted https://github.com/openssl/openssl/pull/1971 for review, and that's all that need and can be done in 1.0.2 context.

**Comment by dot-asm** [comment]
> As for set LINK=/subsystem:console,5.1 and it's suitability for DLL. Why not just try it and see that it's actually ignored when you link DLL? I mean it is ignored, so that build comes out just fine.

This is a bit wrong. It's not actually that it's ignored by linker, but it's ignored when dll is loaded to application. In fact we have been linking our dlls with /subsystem:console like forever and nobody complained so far. Then one should also recognize that with LINK environment variable set and command line passed one will take precedence. And if one is "incomplete", i.e. without version specifier, they will be *merged*.

Closing this. Problem that didn't get attention should be reported separately.
