### ISSUE TITLE
SNI extension parsing does not follow RFC 6066

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#1771]
There are few issues with the way OpenSSL handles the SNI extension, as described in [RFC 6066](https://tools.ietf.org/html/rfc6066).
1. The library does not sanity check the host_name names before passing them to application (e.g. s_server prints names with ANSI escape codes on the command line)
2. SNI extension with multiple items of different types are rejected by server with a decode_error alert
3. In case client offers session resumption to the server, SNI extension is completely ignored (even malformed extension does not generate an alert)

I have tested current 1.0.1, 1.0.2 and master branches (9d9e0535366b4e5cfb2eb4d74be6b3d546b98fe8, 45f4761fdbb7b47a92ee5ed94e5485fb6218f3f5, 2df7f11fad886cf54c98a17e95932d9b5987f488), all present the same behaviour.

---

Reproducer:

```
openssl req -x509 -newkey rsa -keyout localhost.key -out localhost.crt -subj /CN=localhost -nodes -batch
openssl req -x509 -newkey rsa -keyout example.key -out example.crt -subj /CN=example.com -nodes -batch
openssl s_server -key localhost.key -cert localhost.crt -www -servername example.com -cert2 example.crt -key2 example.key -servername_fatal
```

In another console:

```
git clone https://github.com/tomato42/tlsfuzzer.git
pushd tlsfuzzer
git checkout sni-tests
git clone https://github.com/tomato42/tlslite-ng.git .tlslite-ng
ln -s .tlslite-ng/tlslite tlslite
git clone https://github.com/warner/python-ecdsa.git .python-ecdsa
ln -s .python-ecdsa/ecdsa ecdsa
PYTHONPATH=. python scripts/test-invalid-server-name-extension.py --sni example.com
PYTHONPATH=. python scripts/test-invalid-server-name-extension-resumption.py --sni example.com
```

**Comment by kaduk** [comment]
OpenSSL also effects the configuration changes (cert, etc.) that are triggered by SNI somewhat late in ClientHello processing, in particular after doing session resumption.  This is pretty related to your (3), and I would like to fix it by moving SNI (callback) processing earlier, quite possibly to be even before version negotiation is fully done, since potentially a single server could serve both a legacy endpoint and a modern endpoint and wish to reject older TLS versions on certain names.  (This does only work for TLS versions due to the lack of extensions in SSL, of course.)

**Comment by davidben** [comment]
(1) sounds like needless complexity. It'd be a bunch of extra string processing (in C, no less!) which, ultimately, will be redundant with any processing the application would be doing anyway.

The SNI extension point has badly ossified at this point, so (2) is intentional. This was also discussed on the TLSWG list:
https://git.openssl.org/gitweb/?p=openssl.git;a=blob;f=ssl/t1_lib.c;h=87ebbf3625900cf46b656df4d4426d4d9b0f08f8;hb=HEAD#l1860
https://www.ietf.org/mail-archive/web/tls/current/msg19425.html

(3) is worth fixing, yeah. OpenSSL's SNI processing happens in the wrong order. In BoringSSL, we use an "early callback" which lets the consumer inspect the ClientHello and make whatever changes they like before any processing has happened.
https://commondatastorage.googleapis.com/chromium-boringssl-docs/ssl.h.html#SSL_CTX_set_select_certificate_cb

**Comment by tomato42** [comment]
> (1) sounds like needless complexity. It'd be a bunch of extra string processing (in C, no less!) 
> which, ultimately, will be redundant with any processing the application would be doing anyway.

thing is, that the API promises domain names, but will provide arbitrary byte strings - that's ugly, if not dangerous

> The SNI extension point has badly ossified at this point, so (2) is intentional.

on the mailing list there were few people saying that they do use the extended format too. And it has ossified _because_ OpenSSL is the dominant server implementation and it got it wrong.

> RFC 4366 defined the
> syntax inextensibility and OpenSSL 1.0.x parses it as
> such.

that simply is not true, the RFC 4366 syntax is extensible, RFC 6066 made it less so (prohibit different items of same type)

**Comment by davidben** [comment]
RFC 3546 didn't define how to skip over an unknown name type. Although it tried to be extensible, it failed. RFC 4366 continued this mistake. RFC 6066 fixed this in 2011 by adding:

> The data structure associated with the host_name NameType
> is a variable-length vector that begins with a 16-bit length.  For
> backward compatibility, all future data structures associated with
> new NameTypes MUST begin with a 16-bit length field.  TLS MAY treat
> provided server names as opaque data and pass the names and types to
> the application.

But by then it was too late and OpenSSL (and likely others) had long since implemented the inextensible version. If we need a new name type, define a new extension. This is really how it should have been from the beginning. It's unfortunate we have these wasted few bytes, but so it goes.

**Comment by davidben** [comment]
Oh, it seems that last sentence in the quote even justifies (1) formally. (Though I think it is justified regardless. Consumer <-> library interfaces are not the purview of these documents.) OpenSSL doesn't really interpret SNI at all. OpenSSL's API actually has `SSL_get_servername` take a `type` parameter and it gives a `SSL_get_servername_type` function. (Of course, this is pointless since it was never extensible, but nevermind that.)

**Comment by richsalz** [comment]
We should fix item (3); (1) and (2) are not important enough to fix.

**Comment by tomato42** [comment]
The API returns `char*`, which means the application _can't_ correctly process server_name extension with nulls in it.

**Comment by davidben** [comment]
(Zero bytes in the name should be properly rejected. OpenSSL believes SNI is a C-style string with no NULs but otherwise leaves the application to deal with the rest.)

**Comment by tomato42** [comment]
well, it behaves exactly the same in "SNI name with NULL" and "SNI name with BEL" cases, in neither case does it send the correct illegal_parameter alert

**Comment by richsalz** [comment]
guys, let's move to more important things :)

**Comment by richsalz** [comment]
Agreed. Still not a priority in my opinion.

**Comment by richsalz** [comment]
We are not going to do anything about this.

**Comment by tomato42** [comment]
wouldn't this be a good issues for someone to get into openssl development?

**Comment by richsalz** [comment]
The TLS WG has said it's "always and only a hostname"

**Comment by tomato42** [comment]
well, if that hostname is printed in terminal with no checking what so ever, it can result in something [more interesting](https://www.proteansec.com/linux/blast-past-executing-code-terminal-emulators-via-escape-sequences/) than just a sound being played

**Comment by richsalz** [comment]
apps should always verify content that comes from a remote source :)

If you want to discuss a PR for the kinds of checks you'd like to see, perhaps openssl-dev mailing list...

**Comment by tomato42** [comment]
I'm talking about `s_server` :)

**Comment by richsalz** [comment]
oi :)

**Comment by richsalz** [comment]
See #4193

**Comment by richsalz** [comment]
Okay, with #4193 being merged, that's all we're going to do on this issue.

For real this time :)

**Comment by tomato42** [comment]
@richsalz thanks!

**Comment by richsalz** [comment]
The fix was easy.  Getting me to understand it -- what you did -- was the harder part :)  Thank you!
