### ISSUE TITLE
The PKCS12_parse API should support mac-less PKCS12 files

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#17720]
Currently the PKCS12_parse() fails if it is called on mac-less PKCS12 files. Given the KDF used with the MAC algorithm in PKCS12 is not FIPS compliant it would be desirable to allow mac-less PKCS12 files.

The PR would need to include some tests for PKCS12_parse API as there are currently none.

**Comment by davidben** [comment]
I don't think MAC-less PKCS#12 files exist. Or rather, MAC-less password-based PKCS#12 files don't exist. Only the public key mode, which I've never seen implemented. See https://datatracker.ietf.org/doc/html/rfc7292#section-3.1

While the macData field is OPTIONAL at the ASN.1 schema, this only is because the same structure is used in password integrity mode and public-key integrity mode. Per section 3.1, those are your options and if you pick password integrity mode, you've got to have the MAC.
