### ISSUE TITLE
Issue while using methods from crypto.h file

### ISSUE THREAD

**Issue by rohitnits123** [openssl/openssl#17753]
Hi,
In the Openssl version 3.0.1 a new method 
int OPENSSL_buf2hexstr_ex(char *str, size_t str_n, size_t *strlen,
                          const unsigned char *buf, size_t buflen,
                          const char sep);
has been declared in the crypto.h file at line 127. The problem in this function is the third input parameter where the variable name is **strlen**
As its a reserved keyword in C++ when I include the file crypto.h in my project it gives build error.
Can you please look into it and modify the parameter name.

**Comment by paulidale** [comment]
Any thoughts about this comment on the fixing PR:

> FWIW: not that I object to the change itself, but strlen is certainly not a reserved keyword in C++. If at all, I would suspect a collision with some preprocessor define which pollutes the global namespace. And I would ask the reporter of https://github.com/openssl/openssl/issues/17753 about the exact error message to find out whether it’s really the C++ compiler and its library which is causing the problem or some misplaced define in some (third party) header file.

**Comment by mspncp** [comment]
> Any thoughts about this comment on the fixing PR

Sorry @paulidale, I should have asked my question here in the issue and not in the pull request. 

@rohitnits123 just for my interest: could you please share some more details about the compiler error message you encountered? Because as I wrote in https://github.com/openssl/openssl/pull/17764#issuecomment-1053560361, I believe that your explanation of the error cause is not correct.
