### ISSUE TITLE
RipeMD160 Hash returns Segfault after Upgrading to OpenSSL 3.0

### ISSUE THREAD

**Issue by r3dapple** [openssl/openssl#17775]
I have the following function. I have marked in the comment where the segfault occurs. 

```
std::vector<std::byte> hash(std::vector<std::byte> message){
  unsigned char md_value[EVP_MAX_MD_SIZE];
  unsigned int md_len;
  
  char* buffer = reinterpret_cast<char*>(message.data());
  
  EVP_MD_CTX* mdctx = EVP_MD_CTX_new();
  
  const EVP_MD* md_hash = EVP_ripemd160();
  EVP_DigestInit(mdctx, md_hash); // This returns zero. Before upgrading to OpenSSL 3.0 this worked
  EVP_DigestUpdate(mdctx, buffer, message.size()); // SEGFAULT HERE
  EVP_DigestFinal_ex(mdctx, md_value, &md_len);
  EVP_MD_CTX_free(mdctx);
  
  std::string str(reinterpret_cast<char*>(md_value), md_len);
  std::vector<std::byte> retvec(md_len);
  std::transform(str.begin(), str.end(), retvec.begin(), [] (char c) { return std::byte(c); });
  return retvec;
}
```

**Comment by mspncp** [comment]
The RipeMD160 algorithm has been moved to the legacy provider in 3.0, it is not contained in the default provider. 

See https://www.openssl.org/docs/manmaster/man7/migration_guide.html#Legacy-Algorithms for more information.

**Comment by r3dapple** [comment]
Thanks! Do you know why ripemd160 has been moved to legacy? Has there been a problem with collisions?

**Comment by mspncp** [comment]
Incidentally, there was a question and some discussion only some days ago (#17722) why SHA1 was allowed to remain in the default provider but RipeMD160 was moved to the legacy provider, which is a bit inconvenient because it is still widely used for cryptocurrencies. Regardles of whether this was a wrong choice or not, the OpenSSL release policy allows such changes only in major versions, so the next chance to revise this decision would be in version 4.0.
