### ISSUE TITLE
Can RAND_bytes guarantee  uniqueness?

### ISSUE THREAD

**Issue by okayabc** [openssl/openssl#17780]
For example, i use the following code segment to generate 8 digit random, after i run 5000 0000 serveral times, the every random is not duplicate, does it mean this can be used to gurantee uniqueness?

    ```
    time_t tSeed = time(0);
    void* pISeed = &tSeed;
    unsigned char szBuf[8];
    RAND_seed(pISeed, sizeof(tSeed));
    RAND_priv_bytes(szBuf, 8);
    ```

**Comment by t8m** [comment]
There is no uniqueness guarantee as those numbers should be indistinguishable from a true RNG.

The probability of generating the same 8 bytes twice is 1/2^64. Of course the probability raises if you generate multiple 8 byte numbers and you seek for uniqueness across the whole set.

**Comment by okayabc** [comment]
If i want to gurantee uniqueness using 16 bytes or more, how should i do?

**Comment by t8m** [comment]
I might not fully understand your question. However if you want to guarantee uniqueness across some set of randomly generated 8 byte numbers you have to store all the previously generated numbers and match the newly generated number with all the previously generated ones and if it matches, just generate another number.

**Comment by t8m** [comment]
Another option is instead of using the RAND_priv_bytes(), is to simply use some block cipher with 64bit block size (such as 3DES) in the ECB mode. Use a random key with the cipher and encrypt a sequence of incrementing numbers 0, 1, 2, 3,...... This will give you 64bit pseudo random numbers that are guaranteed to be unique.

**Comment by okayabc** [comment]
What's difference between RAND_bytes and RAND_priv_bytes?
Thanks, due to service restart or other factor, the former random set may lose. I mean does it exist other algorithm not restrict to openssl to guarantee uniquenss in distributed nodes?

**Comment by t8m** [comment]
Use the suggestion above to use the 64bit block cipher in the ECB mode. You'll have to distribute the encryption key across the nodes and give each of the node some number that will be part of the 64 bit number sequence encrypted by the block cipher. (Example: 32bit node number, 32bit sequence number will give you 2^32 random unique numbers for each node.) You have to save the last sequence number used by the node and start with that number+1 if the node is restarted. Of course this can never be perfect for example if the node crashes failing to save the number. Unfortunately there is not much you can do else

And of course if you need to have these numbers indistinguishable from random numbers for an attacker you have to keep the encryption key private.

Another option would be to just use random 128bit numbers - in which case the probability of a collision is sufficiently low that there is no point in checking for uniqueness. However it again depends on how many such numbers you need to generate as due to the birthday paradox you'll start getting collisions after 2^64 128 bit numbers are generated.

**Comment by okayabc** [comment]
Ok, thanks!
