### ISSUE TITLE
openssl_get_publickey always notice not exist or null

### ISSUE THREAD

**Issue by cxpyear** [openssl/openssl#1791]
error:0906D06C:PEM routines:PEM_read_bio:no start line"\u4e0d\u5339\u914d\u6216\u4e3a\u7a7a\uff01"

**Comment by levitte** [comment]
That's because you're feeding `PEM_read_bio` a file that isn't in PEM format.

That being said, `openssl_get_publickey` isn't one of our routines, so this ticket isn't clearly about issues *in* OpenSSL.  I suggest you talk with those that wrote the program / library you're using, or if `openssl_get_publickey` is something you wrote, the mailing list openssl-users@openssl.org may be a more suitable place to ask.

Closing this ticket.
