### ISSUE TITLE
1.1.0b test falure on Solaris 8

### ISSUE THREAD

**Issue by teschulz** [openssl/openssl#1800]
I built 1.1.0b on a Solaris 8 Sparc box. The configure command is:

./Configure shared --prefix=/opt/verylocal enable-rc5 enable-mdc2 zlib-dynamic  -I/opt/verylocal/include -R/opt/verylocal/lib solaris-sparcv9-cc

The C compiler is Forte Developer 7 C 5.4 and Perl is v5.22.2.

Some of the tests fail. If I access the same build form a Solaris 10 machine (nfs mount) and run make test  there, all the tests pass. So I assume that the build itself is good. Going back to the Solaris 8 machine, make test again fails. Attached (I hope) is the test error messages.

[openssl-1.1.0b.bug.test.sol8.txt](https://github.com/openssl/openssl/files/559065/openssl-1.1.0b.bug.test.sol8.txt)

**Comment by teschulz** [comment]
[openssl-1.1.0b.bug.test.d.txt](https://github.com/openssl/openssl/files/569668/openssl-1.1.0b.bug.test.d.txt)

The same error log but with the line endings changed to dos line endings.

Is there some way to run individual tests  with more detailed output?

**Comment by levitte** [comment]
> Is there some way to run individual tests with more detailed output?

```
make test TESTS='test_sslcertstatus test_sslrecords test_sslsessiontick test_sslskewith0p test_sslvertol test_tlsextms' V=1
```

**Comment by teschulz** [comment]
When the tests are run one at a time with V=1, only tests test_sslsessiontick, test_sslvertol and test_tlsextms fail. Test test_sslvertol only fails sometimes and the other two fail differently each time they are run. I will attach two logs of test_sslsessiontick, the first failing sub tests 1 and 2 and the second failing 1 and 3 with sub test 1 failing at a different place in the log. I wonder if there is some kind of race condition happening. Let me know if there is some further information I can provide.

[l1.txt](https://github.com/openssl/openssl/files/571905/l1.txt)

[l2.txt](https://github.com/openssl/openssl/files/571907/l2.txt)

**Comment by teschulz** [comment]
Oops, I misread the output of diff. It looks like sub test 1 fails the same way both times.

**Comment by dot-asm** [comment]
One should recognize that tests in questions rely on dynamically loaded engine. Presumably that's where one should start looking for problem. Does `util/opensslwrap.sh engine ossltest` work? On side note you should also recognize that our options to test this are very limited, i.e. non-existent, so that if you can't identify the root cause, we won't be able to help.

**Comment by teschulz** [comment]
> Does util/opensslwrap.sh engine ossltest work? 

That returns:
(ossltest) OpenSSL Test engine support

I assume that this is a success message.

> On side note you should also recognize that our options to test this are very limited, i.e.
> non-existent, so that if you can't identify the root cause, we won't be able to help.

I was afraid of that.
Given the erratic nature of the failures, I am thinking that perhaps when the test reaches the point where it thinks that everything is ready to send some input to a test, things are not yet quite ready. What I would like to try is to insert a small delay just before such input is sent. But I can't find my way around the test system to find such a place. If you think that I am not completely wrong here, could you give me a pointer on how or where to insert a delay.

**Comment by mattcaswell** [comment]
All the tests that are failing are TLSProxy based tests. TLSProxy basically starts an s_client process and an s_server process, and then sits in between, proxying messages between the two. Tests are performed by modifying messages and watching what happens. `clientstart()` in `util/TLSProxy/Proxy.pm`, does the job of sending and receiving of packets. If you wanted to insert an artificial delay, that's probably where you'd do it.

**Comment by dot-asm** [comment]
Looking at first failure in l1.txt and comparing it to successful log. It looks like it means that close_notify alert was not observed by proxy. So that in the context it's a bit misleading, as it says "not ok - Handshake" while handshake was actually perfectly fine. As for why close_notify wasn't observed. Is it possible that kernel drops data after close? I mean client sends alert and closes socket without giving it much thought. If kernel drops data from closed socket (maybe after minuscule timeout), then we would observe the kind of failure we are observing...

**Comment by dot-asm** [comment]
Wasn't there some other system where this didn't really work, i.e. intermittent failures all over TLSProxy-based tests?

**Comment by mattcaswell** [comment]
Yeah, TLSProxy is a bit flaky. Its disabled in Win32. Some less common platforms do have problems sometimes. Often it has been to do with IPv6 issues.

**Comment by dot-asm** [comment]
In other words it appears that failure to perform tests in question does not actually say that build is unsuccessful, it's just that TLSProxy is not up to the job. As for why it works on Solaris 10 machine. What are these two systems hardware-wise? I'd guess that Solaris 8 machine is single-processor UltraSPARC, while Solaris 10 is multi-processor. And I wouldn't be surprised if it turns out that TLSproxy tests on slow single-processor machine suffers from some kind of "anti-race" condition.

**Comment by teschulz** [comment]
I thought it might be a hardware capability issue, so I ran the test on several machines. I tried 3  different Solaris 8 machines and two different Solaris 10 machines. The fastest Solaris 8 machine  and the fastest Solaris 10 machine have identical hardware and are multi-cpu. In every case the test had failures on Solaris 8 and no failures on Solaris 10. Still some sort of race condition seems likely as there are fewer failures when the tests are run with V=1 and fewer still when run one at a time.

**Comment by dot-asm** [comment]
> The fastest Solaris 8 machine and the fastest Solaris 10 machine have identical hardware and are multi-cpu.

In other words the *only* thing that is common for failures is Solaris 8. As for possible experiments, I have no suggestions. It seems that TLSProxy needs some "face lift" (since it's known to fail even in other contexts) and it's probably makes lesser sense to spend efforts trying to find workaround here and now.

**Comment by teschulz** [comment]
> In other words the only thing that is common for failures is Solaris 8

Yes. Perl is the same on both 8 and 10. I built Perl on 8 and installed it on both 8 and 10.
I think that I will assume that openssl 1.1.0 is built OK and will work fine with Sendmail, Bind, SSH and such. If you ever do a face lift, I will see if this problem goes away.
