### ISSUE TITLE
Value of label to be provided for RSA-OAEP algorithm

### ISSUE THREAD

**Issue by Hussain1811** [openssl/openssl#18102]
Hello,
I basically had the below questions:

1)What is the value of "label" attribute to be provided for RSA-OAEP algorithm? I couldn't find much info from https://www.rfc-editor.org/rfc/rfc8017#section-7.1. Is there any maxima and minima for the same?

2)Should the same "label" string be used during both encryption & decryption?

**Comment by t8m** [comment]
To be compliant with RFC8017 you have to actually always use an empty string as the label.

Otherwise the algorithm allows just anything that is within the limits for input for the hash function used for hashing the label. And yes, of course the label always have to be identical when encrypting and decrypting the same data, otherwise the decryption fails.

**Comment by Hussain1811** [comment]
Hello @t8m 
Thanks for the clarification.
