### ISSUE TITLE
provider: key loading from files & loaded key - provider affinity

### ISSUE THREAD

**Issue by bastiengi** [openssl/openssl#18174]
Hi,

I'm implementing a provider for asymmetric operations. The asymmetric cryptographic computations are offloaded on hardware.
The provider is currently composed of a EC key mgment, ECDH and ECDSA part and runs with the 'speed' app.

To validate the implementation further I want to use 'pkeyutl' and 'digest' applications of OpenSSL with my provider. While trying that, I noticed that keys loaded from files are linked to the default provider. When an ECDH operation is called on the key, my provider is ignored. If I understand correctly, this is because my provider doesn't have a DECODER that decodes a key into my key format.
The provider will be used in the context of OpenSSL SSL connections. There some keys and certificates are encoded. I want to be sure that my provider will be the one that handles all ECDH, ECDSA operations and not the default implementation during SSL.

Is there a way for me to re-use the OpenSSL decoder for keys in files and export this OpenSSL key object into my key object? Implementing my own PEM/DER decoder is quite heavy and error prone.

Best Regards,
Bastien

**Comment by mattcaswell** [comment]
Your key manager needs to support the import function:

````
 int OSSL_FUNC_keymgmt_import(int selection, void *keydata, const OSSL_PARAM params[]);
````

See:

https://www.openssl.org/docs/man3.0/man7/provider-keymgmt.html

Also see the following for common import parameter names:

https://www.openssl.org/docs/man3.0/man7/EVP_KEYMGMT-EC.html

With that you should be able to decode keys using the DECODER from the default or base providers and then use the ECDH/ECDSA operations from your custom provider. OpenSSL will automatically import the key into your provider after it has read it from the PEM file. If using the DECODER implementations from default then you will obviously have both your provider and the default provider loaded at the same time. Since the default provider also implements ECDH/ECDSA you need to configure things to prefer your custom provider over default, e.g. by setting a global default property string of something like "?provider=myprovider". The "?" *prefers* that property to be true but will ignore it if its not possible. Alternatively you could just not load default at all and use the decoder implementations in the base provider.

**Comment by bastiengi** [comment]
Thanks for the confirmation that it should work this way! I found some issues in my import function. Now it works as expected with the base provider. Thanks

**Comment by paulidale** [comment]
closing because answered
