### ISSUE TITLE
openssl 3.0.2 cmp -cmd ir doesn't work with ed25519 key

### ISSUE THREAD

**Issue by mickae1** [openssl/openssl#18184]
I would like to know if it's normal that with the key type ed25519, I got:

CMP:apps/cmp.c:1400:CMP warning: -cert and -key not used for protection since -secret is given
CMP:apps/cmp.c:1958:CMP info: will contact http://192.168.1.1:80/cmp_path
CMP error: invalid digest
CMP error: error creating certreq

It's working with the key type rsa . I don't get the message: CMP error: invalid digest

**Comment by DDvO** [comment]
> @DDvO perhaps this is somehow related to how the digest algorithm is implicit in ed25519?

Yes - I found that this happens whenever the `-newkey` argument, 
which is used (among others) for the POPO self-signature of the request, 
is of type ed25519 or ed448.

The location of the error is:
```
eddsa_digest_signverify_init:providers/implementations/signature/eddsa_sig.c:99:error: invalid digest
ossl_cmp_certreq_new:crypto/cmp/cmp_msg.c:452:CMP error: error creating certreq
```

If the `mdname` parameter of `eddsa_digest_signverify_init(()` is NULL, this works fine,
but here by default `"SHA2-256"` gets passed in.

Does `eddsa_digest_signverify_init()` really need to be that picky here?
Couldn't it simply ignore the (in this case needless) `mdname` parameter?

**Comment by t8m** [comment]
> Does `eddsa_digest_signverify_init()` really need to be that picky here?
> Couldn't it simply ignore the (in this case needless) `mdname` parameter?

I am not sure this is a good idea as the hash algorithm is a security parameter and simply ignoring it may be a serious error in some cases. Couldn't the calling code recognize the algorithm?

**Comment by DDvO** [comment]
Yes, this should be doable, but will require detecting the special cases ed25519 and ed448, plus in the future possibly more such ones.
So would be good not to do this at application level (such as CMP), but somewhere more internal/general,
i.e., within `ASN1_item_sign_ex()` or some signing function called by it.
Where do you suggest to do it?

**Comment by t8m** [comment]
There is a `EVP_PKEY_get_default_digest_name()` which returns `UNDEF` if no digest should be used with the PKEY. IMO that should be invoked from the place that sets up the signature algorithms.

**Comment by DDvO** [comment]
> There is a `EVP_PKEY_get_default_digest_name()` which returns `UNDEF` if no digest should be used with the PKEY.

Good hint - so I'll use that.

BTW, interesting that this function (at least according to its doc) returns `SHA256` for all other (i.e., non-Edwards) key types.
although it would be preferable to select a digest algorithm depending with a strength that corresponds to the strength of the key, as recommended, e.g., in https://datatracker.ietf.org/doc/html/rfc5480#section-4.
Is there an OpenSSL function implementing something like that?

> IMO that should be invoked from the place that sets up the signature algorithms.

I'm not sure where best to do this.
It turns out if done within `do_sigver_init()` of `crypto/evp/m_sigver.c`, some tests fail:
```
15-test_rsapss.t                 (Wstat: 1024 Tests: 9 Failed: 4)
20-test_dgst.t                   (Wstat: 1536 Tests: 10 Failed: 6)
30-test_evp_extra.t              (Wstat: 256 Tests: 3 Failed: 1)
30-test_evp.t                    (Wstat: 256 Tests: 72 Failed: 1)
```
So in #18195 fixing this issue I've done it in `ASN1_item_sign_ex()`.

**Comment by DDvO** [comment]
> CMP:apps/cmp.c:1400:CMP warning: -cert and -key not used for protection since -secret is given

@mickae1, looks like your `openssl cmp` invocation provides `-cert` and `-key` options, but they are ignored if you also provide a `-secret` option.

**Comment by mickae1** [comment]
@DDvO  

I agree with you,

This is working:
openssl cmp -cmd ir -server 192.168.1.1:80 -path cmp_path -srvcert certificatCmpCaServer.pem -ref 005 -secret pass:test_pwd -key keyClient -certout cert_cmp.tmp -subject /CN=005

But when I removed -key argument I have the error:
error: missing -newkey (or -key) to be certified and no -csr given

And if I remove only -srvcert I have the warning: 
 apps/cmp.c:1400:CMP warning: -cert and -key not used for protection since -secret is given
apps/cmp.c:1563:CMP warning: missing -recipient, -srvcert, -issuer, -oldcert or -cert; recipient will be set to "NULL-DN"


Michael,

**Comment by mickae1** [comment]
I don't want the private key to be updated, that's why there is no newkey argument.
I think, it's important to give my key to be certified by the cmp server.

**Comment by DDvO** [comment]
> I don't want the private key to be updated, that's why there is no newkey argument.
> I think, it's important to give my key to be certified by the cmp server.

The name of the `-newkey` option may be a bit confusing.
It does no mean that the key is fresh, but it is the key to be certified in the requested new certificate.
It is perfectly valid to provide a key (value) that has been used before (e.g,, when just extending the validity of a certification, updating a cert without changing the public key certified).

I you do not provide a `-newkey` option, the value of the `-key` option will be used as a fallback.
Yet the general role of the `-key` and `-cert` option is different: they provide credentials used by the CMP client to authenticate itself. 
If you provide a `-secret`, this is an alternative way of providing client credentials, and this will take precedence for the client authentication. In this sense, I meant yesterday that the `-cert` and `-key` are ignored, but in fact, even in this case the `-key` value is taken as the default/fallback key to be certified.
Maybe we should drop this default mechanism (of taking the `-key` value as fallback for the `-newkey` value) because it is more confusing than helpful.

**Comment by mickae1** [comment]
I'm using the secret argument only for the initial request . 
Because at the beginning the CMP server doesn't know if it can trust the device that issue the initial request. 

Thanks, for the precision, I will use newkey argument:

openssl cmp -cmd ir -server 192.168.1.1:80 -path cmp_path -srvcert certificatCmpCaServer.pem -ref 005 -secret pass:test_pwd -newkey keyClient -certout cert_cmp.tmp -subject /CN=005

**Comment by mickae1** [comment]
@DDvO about this command:
openssl cmp -cmd ir -server 192.168.1.1:80 -path cmp_path -srvcert certificatCmpCaServer.pem -ref 005 -secret pass:test_secret -newkey keyClient.pem -certout cert_cmp.tmp -subject /CN=005

I tried this command when the file keyClient.pem doesn't exist, and it doesn't work.
I don't understand why, because at this step we don't have a private key and a certificate. This goal for this command is to get a private key with the certificate.
