### ISSUE TITLE
SSL_get_peer_certificate() fails for TLS_DH_anon_WITH_AES_256_CBC_SHA256

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#18191]
I am testing a client server communication using the cipher suite: TLS_DH_anon_WITH_AES_256_CBC_SHA256.
The SSL_get_peer_certificate() fails (returns NULL) for this cipher suite.
If I change the cipher suite to some other (like TLS_DHE_RSA_WITH_AES_256_GCM_SHA384), SSL_get_peer_certificate() returns a valid certificate.
Can someone let me know what could be wrong?
Does TLS_DH_anon_WITH_AES_256_CBC_SHA256 require any specific type of certificate?

Thanks in advance.

Regards,
Amal

**Comment by mattcaswell** [comment]
This is expected behaviour. The "anon" bit means that it does not *use* a certificate. By using this ciphersuite you do not get any authentication guarantees about the peer, i.e. they are anonymous.

**Comment by amaljesudas** [comment]
Thanks @t8m 
If possible can you also direct me to some openssl documentation on the same, so that I can keep that as reference?

**Comment by mattcaswell** [comment]
Certificate verification is done when a certificate is received. In the event of an "anon" ciphersuite no certificate message is ever sent, so we don't attempt verification. In that case the `SSL_CTX_set_verify` setting is irrelevant.

The documentation for `SSL_get_peer_certificate` is here:

https://www.openssl.org/docs/man3.0/man3/SSL_get_peer_certificate.html

It doesn't really explicitly spell out the behaviour with "anon" ciphersuites but does say:

> If the peer did not present a certificate, NULL is returned.

Since anon ciphersuites don't send a certificate it is implied that NULL will be returned in this case.

**Comment by amaljesudas** [comment]
Thanks @mattcaswell
