### ISSUE TITLE
How to enable the extension in Client Hello: Application_Layer_PROTOCOL_negotiation, status_Request, renegotiation_info

### ISSUE THREAD

**Issue by wuchuwei** [openssl/openssl#18207]
Openssl version: 1.1.1 N
How to use Application_Layer_PROTOCOL_negotiation, status_Request, renegotiation_info in the Client Hello phaseSigned_certificate_timestamp,padding extension?
I am using Nginx /1.20.1 (OpenSSL 1.1.1n) as a reverse proxy.The background server has a WAF firewall.TLS fingerprint recognition (JA3). I tried to recompile and configure Nginx and OpenSSL so that the Nginx proxy requests TLS fingerprints the same as normal browsers.
Now I need to disable OpenSSL Cipher Suite: TLS_EMPTY_RENEGOTIATION_INFO_SCSV (0x00FF) and Enable openSSL TLS extension:Application_Layer_PROTOCOL_negotiation, status_Request, renegotiation_info in the Client Hello phaseSigned_certificate_timestamp,padding

**Comment by kaduk** [comment]
I believe you will need to patch Nginx in order to achieve these goals.

Look for APIs like:
- `SSL_CTX_set_alpn_protos`
- `SSL_CTX_set_tlsext_status_type`
- `SSL_CTX_enable_ct`
- `SSL_CTX_set_options(.,SSL_OP_TLSEXT_PADDING)`

OpenSSL as a client only uses the renegotiation info SCSV, and does not currently provide an option to use the "renegotiation_info" extension in the ClientHello to indicate support for the functionality.
