### ISSUE TITLE
TLS_DH_RSA_WITH_AES_128_CBC_SHA256

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#18239]
I need to set the cipher suite TLS_DH_RSA_WITH_AES_128_CBC_SHA256.
But when I call SSL_CTX_set_cipher_list passing DH-RSA-AES128-SHA256, the function fails.
I ran the command **openssl ciphers -v DH-RSA-AES128-SHA256** and it gives the below error:
Error in cipher list
7520:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl\ssl_lib.c:2571:

Is my openssl not supporting the above cipher suite? Can I enable the same through some configuration?

Thanks in advance.

**Comment by mattcaswell** [comment]
The ciphersuite you want is called `DHE-RSA-AES128-SHA256` (note the extra `E` after `DH`)

**Comment by amaljesudas** [comment]
But @mattcaswell, aren't DHE-RSA-AES128-SHA256 and DH-RSA-AES128-SHA256 two separate cipher suites?
I can see TLS_DH_RSA_WITH_AES_128_CBC_SHA256 mapped as DH-RSA-AES128-SHA256 in the below openssl man page also:
[](https://www.openssl.org/docs/man1.1.1/man1/ciphers.html)

**Comment by mattcaswell** [comment]
> But @mattcaswell, aren't DHE-RSA-AES128-SHA256 and DH-RSA-AES128-SHA256 two separate cipher suites?

They are - but no one uses `DH-RSA-AES128-SHA256` and support for it was removed from OpenSSL in 2015 (bc71f91064). Seems like the ciphers page reference you found should be cleaned up. You almost certainly do not want to use `DH-RSA-AES128-SHA256` - it requires a special DH certificate to use it which are very difficult to come by (I'm not aware of CAs that issue these) - and so consequently this ciphersuite never saw widespread usage.

The last OpenSSL version that supported this was 1.0.2 (which is no longer publicly supported) - and even in that version it was not compiled by default - due to it being considered "weak".

This is why I point you to `DHE-RSA-AES128-SHA256`. This *is* supported and used in practice.

**Comment by amaljesudas** [comment]
Thanks @mattcaswell 
We are using openssl 1.1.1l version.
I now understand that current versions of openssl do not support DH-RSA-AES128-SHA256.
To confirm, there is no way to enable DH-RSA-AES128-SHA256 in the latest versions of openssl - correct?
Or is there a work around like setting some flag when compiling just like we use enable-weak-ssl-ciphers for 3DES?

**Comment by mattcaswell** [comment]
> To confirm, there is no way to enable DH-RSA-AES128-SHA256 in the latest versions of openssl - correct?

Correct.

> Or is there a work around like setting some flag when compiling just like we use enable-weak-ssl-ciphers for 3DES?

No. This ciphersuite does not even exist in the weak-ssl-ciphers set and support for it was completely removed from the codebase.

**Comment by amaljesudas** [comment]
Thanks @mattcaswell 
One last confirmation before I close - Same applies to the DH-DSS set as well right?

**Comment by mattcaswell** [comment]
Correct.

**Comment by amaljesudas** [comment]
Thanks a ton for the help @mattcaswell
