### ISSUE TITLE
Documentation of X509_INFO missing?

### ISSUE THREAD

**Issue by pataxis** [openssl/openssl#18342]
I'm compiling openssl 1.1.1 and use that and curl in C-code.

I have looked at this [curl example](https://curl.se/libcurl/c/cacertinmem.html) and try to understand the callback function which adds certificates using openssl library.
Searching the online documentation for library functions https://www.openssl.org/docs/man1.1.1/man3/ I can't find any reference of functions including `X509_INFO`.

But checking in my local openssl 1.1.1 source code I can find functions like `PEM_X509_INFO_read` and `PEM_X509_INFO_read_bio` in `include/openssl/pem.h`. The same file on GitHub master [include/openssl/pem.h](https://github.com/openssl/openssl/blob/master/include/openssl/pem.h#L420) has these functions too.

Searching the 3.0 pages https://www.openssl.org/docs/man3.0/man3/ for `X509_INFO` I can find two functions, one of them is
[PEM_X509_INFO_read_ex](https://www.openssl.org/docs/man3.0/man3/PEM_X509_INFO_read_ex.html) which according to the 3.0 migrating instructions https://www.openssl.org/docs/man3.0/man7/migration_guide.html is the replacement function for  [PEM_X509_INFO_read(3)](https://www.openssl.org/docs/man3.0/man3/PEM_X509_INFO_read.html) when using a library context, but this is a dead link to man3.0 pages. Changing the URL to 1.1.1 also gives a dead link, see these below:

- https://www.openssl.org/docs/man3.0/man3/PEM_X509_INFO_read.html
- https://www.openssl.org/docs/man1.1.1/man3/PEM_X509_INFO_read.html

## Questions

- Is there documentation missing for `X509_INFO` functions like `PEM_X509_INFO_read` in both 1.1.1 and 3.0?
- Are the `X509_INFO` structs and functions not public/recommended to use?

**Comment by mattcaswell** [comment]
> Is there documentation missing for X509_INFO functions like PEM_X509_INFO_read in both 1.1.1 and 3.0?

Yes the documentation is missing.  As you note `PEM_X509_INFO_read_ex` and `PEM_X509_INFO_read_bio_ex` *are* documented. The versions without the "ex" are basically the same but they use the default libctx and cannot supply a custom property query (which is irrelevant in 1.1.1 since those concepts don't exist there).

It seems like it would be a simple matter to extend the existing man page with documentation for the older, non "ex", versions of these functions. It's a shame we didn't think to do so when adding the "ex" documentation in 3.0.

> Are the X509_INFO structs and functions not public/recommended to use?

These are fine for use. Missing documentation should not be interpreted as meaning we don't recommend its use. Functions that we do not recommend for use are explicitly marked as deprecated in the headers (and compilers that support it will report deprecation warnings if they are used). Unfortunately there are still a significant number of older functions that are missing documentation.

Marking this issue as "help wanted" - since it seems that adding the missing documentation for these 2 functions should be straight forward. PRs welcome.

**Comment by pataxis** [comment]
@mattcaswell  Thanks, all my questions have been answered.
