### ISSUE TITLE
Static randomization parameters in FIPS self-tests.

### ISSUE THREAD

**Issue by arubadean** [openssl/openssl#18414]
In FIPS 140-3 IG 10.3.A, there is no longer an explicit allowance for pairwise consistency tests (PCT) for algorithms like DSA/ECDSA which have variable output for their same inputs, in their self-tests.. Randomization parameters are required to be fixed.

Can this be accomplished in the FIPS provider self-test by setting a TEST-RAND instance as the parent of the the random source for the context being used in the self-test? Is there another technique that would better achieve this?

**Comment by paulidale** [comment]
Set the TEST-RAND as the random source rather than as the parent of the random source but that's what it was designed for.  You might need to call `RAND_set_DRBG_type` to do this.  I guess you could use a custom RAND_METHOD to achieve the same thing.

Have you looked into seed parameters for these algorithms?  It is an easier path.  q.v. [DSA](https://www.openssl.org/docs/man3.0/man7/EVP_PKEY-FFC.html) and [ECDSA](https://www.openssl.org/docs/man3.0/man7/EVP_PKEY-EC.html).

**Comment by beldmit** [comment]
We use a different approach providing a known K value for signatures in FIPS KAT mode. 

https://src.osci.redhat.com/rpms/openssl/blob/rhel-9-main/f/0060-FIPS-KAT-signature-tests.patch

If this approach is OK for upstream, I can submit a corresponding PR

**Comment by t8m** [comment]
@beldmit that url seems to be internal one.

**Comment by beldmit** [comment]
Removed it from the previous my comment.

Sorry, will provide the relevant public URL later. BTW, the approach still is relevant.
