### ISSUE TITLE
Android NDK r24 `__ANDROID_API__` macro redefined

### ISSUE THREAD

**Issue by wongsyrone** [openssl/openssl#18561]
Environment:
Host: Archlinux x64
Android NDK r24

Issue:
I got `__ANDROID_API__` macro redefined warning when compiling for android-arm target with command:

```
./Configure android-arm -D__ANDROID_API__=23 no-shared && make
```

The error message from Android NDK clang:

```
armv7a-linux-androideabi23-clang  -Iproviders/common/include/prov -I. -Icrypto -Iinclude -Iproviders/implementations/include -Iproviders/common/include  -DAES_ASM -DBSAES_ASM -DOPENSSL_CPUID_OBJ -fPIC -pthread -Wa,--noexecstack -Qunused-arguments -Wall -O3 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-3\"" -DMODULESDIR="\"/usr/local/lib/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DNDEBUG -D__ANDROID_API__=23 -MMD -MF providers/common/der/libdefault-lib-der_sm2_key.d.tmp -MT providers/common/der/libdefault-lib-der_sm2_key.o -c -o providers/common/der/libdefault-lib-der_sm2_key.o providers/common/der/der_sm2_key.c
In file included from <built-in>:373:
<command line>:11:9: warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
#define __ANDROID_API__ 23
        ^
<built-in>:366:9: note: previous definition is here
#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
        ^
1 warning generated.
armv7a-linux-androideabi23-clang  -Iproviders/common/include/prov -I. -Icrypto -Iinclude -Iproviders/implementations/include -Iproviders/common/include  -DAES_ASM -DBSAES_ASM -DOPENSSL_CPUID_OBJ -fPIC -pthread -Wa,--noexecstack -Qunused-arguments -Wall -O3 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-3\"" -DMODULESDIR="\"/usr/local/lib/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DNDEBUG -D__ANDROID_API__=23 -MMD -MF providers/common/der/libdefault-lib-der_sm2_sig.d.tmp -MT providers/common/der/libdefault-lib-der_sm2_sig.o -c -o providers/common/der/libdefault-lib-der_sm2_sig.o providers/common/der/der_sm2_sig.c
In file included from <built-in>:373:
<command line>:11:9: warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
#define __ANDROID_API__ 23
        ^
<built-in>:366:9: note: previous definition is here
#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
        ^
1 warning generated.
```

Based on feedback from official NDK maintainers (https://github.com/android/ndk/issues/1538), clang defines `__ANDROID_API__` automatically.

My temporary workaround is:

```diff
diff --git a/Configurations/15-android.conf b/Configurations/15-android.conf
index 41ad9223e0..993f1c9483 100644
--- a/Configurations/15-android.conf
+++ b/Configurations/15-android.conf
@@ -64,9 +64,9 @@
             } else {
                 $api = "*";
 
-                # see if user passed -D__ANDROID_API__=N
+                # see if user passed -D__ANDROID_MIN_SDK_VERSION__=N
                 foreach (@{$useradd{CPPDEFINES}}, @{$user{CPPFLAGS}}) {
-                    if (m|__ANDROID_API__=([0-9]+)|) {
+                    if (m|__ANDROID_MIN_SDK_VERSION__=([0-9]+)|) {
                         $api = $1;
                         last;
                     }
@@ -151,7 +151,7 @@
                     die "no $incroot"          if (!-d $incroot);
                     die "no $incroot/$triarch" if (!-d "$incroot/$triarch");
                     $incroot =~ s|^$ndk/||;
-                    $cppflags  = "-D__ANDROID_API__=$api";
+                    $cppflags  = "-D__ANDROID_MIN_SDK_VERSION__=$api";
                     $cppflags .= " -isystem \$($ndk_var)/$incroot/$triarch";
                     $cppflags .= " -isystem \$($ndk_var)/$incroot";
                 }

```

and use the command below to 'workaround' the issue:

```
./Configure android-arm -D__ANDROID_MIN_SDK_VERSION__=23 no-shared && make
```

PS: Sorry, I don't know how to detect clang or gcc in Perl, and cannot come up with a backward compatible fix.

**Comment by xtkoba** [comment]
It should be clarified that this is just a warning, not an error unless `-Werror` is specified. A workaround that I take is to pass `-U__ANDROID_API__` as a configuration argument along with `-D__ANDROID_API__=n`.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of 3.4 dev barring further input

**Comment by petrovr** [comment]
На 9.06.24 г. в 2:18 ч., Neil Horman написа:
> marking as inactive, will be closed at the end of 3.4 dev barring further input
> 

This is real issue. It is result of OpenSSL build regression.

What OpenSSL team needed to know more?

It you like to resolve such things REMOVE Android support or IMPROVE it.

Roumen

**Comment by tom-cosgrove-arm** [comment]
> What OpenSSL team needed to know more?

You can see at https://www.openssl.org/policies/general-supplemental/platforms.html that Android is a community-supported platform, i.e. not one that the core OpenSSL team have experience with. Generally such community-supported platforms need a nominated community maintainer to avoid exactly such issues as this. (Presumably Android support was added before this policy was introduced.)

> It you like to resolve such things REMOVE Android support

That has happened for unsupported platforms

> or IMPROVE it

It might be a cliché, but: pull requests to improve this are welcome. Note that there does appear to be a workaround.

> REMOVE ... IMPROVE

Please don't shout

**Comment by nhorman** [comment]
@petrovr I'm sorry, I'm not trying to suggest this isnt a real problem.  By marking It inactive I am however pointing out that no one has touched this bug in over a year, and valid bug or not, it seems that it would be favorable to close this for the benefit of having a more manageable backlog for me to organize and work through.

I'm glad you spoke up though, as that was part of this exercise - to identify those bugs that have people paying attention to them, vs those that go unnoticed.  As you responded, you are putting this bug in the former category, which is great.

So what to do about it now?  As @tom-cosgrove-arm points out, android is an unadopted platform, and as such the core openssl team isn't going to invest time in fixing this at the moment.  That means the only way forward here is to mark this as a community issue with the help wanted label and hope someone picks this up.  

Seeing at that hasnt happened since this bug has opened, I'm not hopeful, but maybe your speaking up is an indication of interest?  If you're willing to take in the task of fixing this, I'm happy to assign you to it and mark it as a community issues, removing it's inactive status.

What do you say?

**Comment by petrovr** [comment]
It is clear to OpenSSL team lack build capability on most OS-es except Linux. One member know VMS.

Is not better to keep issues open? Note default filters! Opened issues is expected to be found unlike closed.
Also to close an issue we should know decision. How to understand "inactive". Is this solution? If yes then this means to me only one thing - ignore Android community. 
Note that we use spare time(!) to share our knowledge. 

----

Work-around should address issue if build is with NDK >= 22 or 23(?). With other words to parse either __ANDROID_API__ or __ANDROID_MIN_SDK_VERSION__ depending from NDK version.
If this is yet another work-around  user could use CPPFLAGS to define required minimum supported Android API version.

----
Remark: due to many other reasons I prefer to use NDK 21.

**Comment by nhorman** [comment]
We have plenty of capacity for those platforms which the project supports.  Please note our CI routinely builds for all the current primary and secondary platforms listed [here](https://github.com/openssl/private/issues/477)

Community platforms are further supported by the gracious efforts of those dedicated community members who volunteer their time to regularly test on those platforms and submit bugfixes.

Note that Android is listed above as an unadopted platform - this means that the core openssl development team does not support that platform, nor has there been a volunteer from the android user base to do so.  As such there is no effort made within the core openssl developer group to maintain it, above reviewing whatever PR's are submitted to fix whatever issues may exist there.  i would request that you not interpret our lack of input on an unsupported platform as an inability to build on anything other than linux.

In answer to your direct questions:
1) No, it is absolutely not better to leave issues open.  We have 2000+ issues laying about now, many of which are exactly like this that go without any update for multiple years ,until someone suggests closure.  Leaving these issues open creates significant noise in our issue list, negatively impacting our ability to identify, plan and schedule work for issues that do affect our supported platforms.  As someone who is responsible for such scheduling, its self evident to me what the choice is here.  If an issue for any platform is being regularly worked on, and moving toward resolution, I'm happy to leave it open.  But if its just going to sit inert, its more valuable to have it not exist to provide better visibility to those issues which are relevant to us.  Changing this behavior is however, quite straightforward: at @tom-cosgrove-arm notes, volunteer to be a community maintainer.

2) The inactive flag means exactly that, that an issue is inactive.  I've been using it in the following cases:
     - An issue is vestigial (i.e. the problem is or seems resolved, but the issue remains open)
     - An issue references a release no longer in support
     - An issue is unresponsive (like this one, it has gone without comment for a long period, my rule of thumb being 12 months or more)

Regardless of the reason, the label indicates the same thing (based on my comment), that the issue will be closed at the end of the 3.4 dev cycle, unless someone wants to pick the issue up and drive it to closure themselves.

so that all said, there are a few options here:
1) You (or someone) can volunteer to be the android maintainer, and issues like these can be assigned to you to handle on whatever schedule you are able - if you are amenable to this, please open a PR to update the above web page to list yourself as the community maintainer (and thank you).
2) We can mark this issue as community support, assign it to you (or someone in the community), and they can drive it to closure.
3) We can recognize that issue is not going to get any further input, close it, and understand that, like all projects, sometimes reviewing issues in archives requires searching closed issues, weather or not they were ever truly resolved.

Note I am unwilling to accept any variant of "issues should remain open until completed".  That simply doesn't work from a planning standpoint for the reasons stated above.

That all said, are you volunteering as a community maintainer for android? or are you willing to take on this specific issue as a community support task?

**Comment by beldmit** [comment]
@nhorman this comment is worth a separate communication, in blog and at openssl-users@

**Comment by nhorman** [comment]
ACK, can do @beldmit
