### ISSUE TITLE
AES CMAC verification

### ISSUE THREAD

**Issue by swanandb2** [openssl/openssl#18572]
I was looking for AES_CMAC_128 generation and verification algorithm.
I did refer sample, https://gist.github.com/ecerulm/90653daf2b808aea0837 and it was able to generate MAC successfully.

However, as per my understanding this MAC will be appended to some message and symmetric key is use to separate MAC and org message, in this way receiver can authenticate sender.
I still couldn't get any sample to verify message at receiver side? Can you please help me with same?

I am new to cryptography and not fully aware of MAC concept trying to evaluate it. 
Thank you for your support!

[@paulidale: edit to fix link]

**Comment by swanandb2** [comment]
Any update on above?

**Comment by paulidale** [comment]
It's not clear what you are asking for.

MACs are not magically appended to a message, your code needs to do that.  The opposite at the receiving end.

I suggest you find some introductory cryptography reading or videos and research further.  Using cryptyography without understanding the its application only leads to pain.

**Comment by kaduk** [comment]
I wholeheartedly endorse what Pauli said.
But for MACs in particular, there will not necessarily always be a separate "verify MAC" API (in the way that "encrypt"/"decrypt" APIs are paired), since the parties creating and verifying the MAC both have the same inputs available, and the verification procedure is summarized as "create your own MAC and check if it matches the one you got from the other party".  (N.B. there are several subtleties that color that summary, including the need to known/verify the provenance of all inputs and often the need to use a constant-time comparison function, which can be relevant to producing a secure system overall.  You really do want to do the introductory reading/watching that Pauli suggested.)

**Comment by swanandb2** [comment]
Thanks for support. I did confirm same MAC generation algorithm is available and input also, verify should need to check generated MAC.
