### ISSUE TITLE
error:0A000126:SSL routines::unexpected eof while reading in php

### ISSUE THREAD

**Issue by msalik42** [openssl/openssl#18574]
I have built a website in PHP using the YII2 framework. When I use file_get_contents($requestUrl, false, stream_context_create($arrContextOptions)) then i am getting error saying error:0A000126:SSL routines::unexpected eof while reading I have also tried to enable the legacy provider by editing the openssl.cnf file, but got no success. Reference: https://gist.github.com/rdh27785/97210d439a280063bd768006450c435d

[Here is the screenshot](https://i.stack.imgur.com/45QV6.png)

Server: Nginx (nginx/1.18.0) 
OS: Ubuntu 22.04 LTS 
PHP: 7.4.29 
Openssl: 1.1.1d

**Comment by beldmit** [comment]
It has nothing to do with legacy provider. SSL_OP_IGNORE_UNEXPECTED_EOF is the corresponding flag to ignore this error, see https://www.openssl.org/docs/man3.0/man3/SSL_CTX_set_options.html for more information

**Comment by jessuppi** [comment]
This error is popping up all over GitHub and StackOverflow, I don't know why this issue is marked "resolved"... it seems there is a bug in OpenSSL that requires upgrading and/or downgrading packages, and/or rebooting.

Ref: https://github.com/curl/curl/issues/5138
Ref: https://stackoverflow.com/questions/72627218/openssl-error-messages-error0a000126ssl-routinesunexpected-eof-while-readin
Ref: https://stackoverflow.com/questions/60888230/openssl-ssl-error-ssl-routines-ssl3-read-n-unexpected-eof-while-readin

...among several other threads.

It seems to happen in both 1.1.1d and 1.1.1e, possibly other versions.

**Comment by t8m** [comment]
Not rumors but facts:

1.1.1f reverted the behavior the error is reported. The error is really an error of the peer.

3.0.x requires the application to set the SSL_OP_IGNORE_UNEXPECTED_EOF to ignore the error.

**Comment by SalihSyr** [comment]
Can anyone show me how to set the SSL_OP_IGNORE_UNEXPECTED_EOF to the ssl.h ?

**Comment by t8m** [comment]
You're editing an OpenSSL header file, not modifying the application calling the OpenSSL. Anyway, this should be done by the application developer, not by user.

**Comment by SalihSyr** [comment]
Oh I got it. Well when I downgraded it to an older version of openssl it still didn't work.

Do you know a version where it deffinetly won't make problems?

**Comment by t8m** [comment]
Use the latest 1.1.1 release (1.1.1q).
