### ISSUE TITLE
TLS1.3 session reuse

### ISSUE THREAD

**Issue by jay900323** [openssl/openssl#18792]
Hello, I encountered a problem when I used session reuse for the client in the tls1.3 protocol. I set the callback function through the SSL_CTX_sess_set_new_cb function, and saved the SSL_session after the handshake. 
On the next SSL handshake, set the session to the saved session address using SSL_set_session funciton, but I found that session reuse can only take effect for the first time, and there is no pre_shared_key information in the clienthello of the subsequent handshake, But in tls1.2, all connection session reuse will take effect.
The sample code is as follows
````
SSL_SESSION *ssl_session = NULL;
static int ssl_new_session_cb(SSL *s, SSL_SESSION *sess)
{
   if(ssl_session == NULL){
     SSL_SESSION_up_ref(sess);
     ssl_session = sess;
   }
}

int main() {

      ctx = SSL_CTX_new(SSLv23_method());
      ...
      SSL_CTX_sess_set_new_cb(ctx, ssl_new_session_cb);
      
      ...
      
      SSL *ssl1 = SSL_new(ctx)
      SSL_do_handshake(ssl1)
      ...
      
      SSL *ssl2 = SSL_new(ctx)
      SSL_set_session(ssl2, ssl_session)
      SSL_do_handshake(ssl2)
      ...
      
      SSL *ssl3 = SSL_new(ctx)
      SSL_set_session(ssl3, ssl_session)
      SSL_do_handshake(ssl3)

}

````

**Comment by kaduk** [comment]
Can you confirm that you are cleanly `SSL_shutdown()`ing the connections between resumption attempts?
In some situations an unclean connection shutdown will cause the session object to be invalidated (though I didn't think in this one, and especially not differentiating between TLS 1.2 and TLS 1.3).
TLS 1.3 does strongly encourage single-use of resumption tickets, but I did not think our client implementation enforced that by default (which would be required in order to explain your observation about "no pre_shared_key information").  That said, the single-use-ticket behavior is different when early data is enabled -- can you also confirm whether early data is enabled on either/both the client and server?

**Comment by leirenbaobao** [comment]
I have meet some problem.quite different with tlsv1.2. you must call ssl_read && [SSL_CTX_sess_set_new_cb()](https://www.openssl.org/docs/manmaster/man3/SSL_CTX_sess_set_new_cb.html) will be called.in the callback func.you can save session.Don't forget call ssl_read or callback.

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of the 3.4 dev cycle barring further input

**Comment by MINGHAOLl** [comment]
Hi, I also encountered this issue with code setup similar to the above example.

I was using OpenSSL 3.0 and the issue occurred only when using TLS1.3.

After adding a session remove callback with `SSL_CTX_sess_set_remove_cb`, I noticed the callback is triggered after the second handshake.

I did some investigation and it seems to be caused by `SSL_CTX_remove_session()` in [statem_lib.c](https://github.com/openssl/openssl/blob/e113a92e290b31aaeab9a3f24b2cd6011c5ee670/ssl/statem/statem_lib.c#L1476)

Is this behavior intended, and would it be possible to add a check to make it respect the `SSL_SESS_CACHE_NO_AUTO_CLEAR` flag?

Thanks

**Comment by davidben** [comment]
That looks to be an implementation of https://www.rfc-editor.org/rfc/rfc8446#appendix-C.4
