### ISSUE TITLE
Leaks or use-after-frees in TS_VERIFY_CTX accessors

### ISSUE THREAD

**Issue by botovq** [openssl/openssl#18854]
The `TS_VERIFY_CTX` accessors return the value passed in. This is a bit strange.

https://github.com/openssl/openssl/blob/cbb1cda67f61b34c89fb49c8e2267ec6217bc33f/crypto/ts/ts_verify_ctx.c#L51-L77

One possible explanation is that the appropriate freeing of already present struct members were missed. This is the interpretation taken in #16347 for `TS_VERIFY_CTX_set_imprint()`.

Or perhaps the idea of https://github.com/openssl/openssl/commit/ca4a494cb7437a7af155361b0084de8329c0bf25 was that they should return the old value of the relevant `ctx` member so that the caller can free them? However, that doesn't make sense with the error checking that was added with their use in ts.c.

Either way, the current behavior means that whatever was set on the `ctx` is likely leaked if an application calls one of these setters a second time.

As already mentioned, this was changed for `TS_VERIFY_CTX_set_imprint()` in #16347 (without treating the other functions the same way). This was a dangerous change since it makes the API behavior inconsistent and, worse, it causes a use after free or a double free for callers who would previously take care of freeing the old pointer themselves to avoid a leak.

This problem would arise for example in [ruby/openssl][1] if someone were to add an `X509_STORE_free(store)` at the top of `TS_VERIFY_CTX_set_store()` similar to #16347 .

Presumably the only way to fix this without breaking existing consumers is to deprecate the existing API and to add `set0` or `set1` versions of these setters that don't have these issues.

[1]: https://github.com/ruby/openssl/blob/b31446464e1e9f8bd0c58e92f9e74a9c7663b0e0/ext/openssl/ossl_ts.c#L831-L839

**Comment by erbsland-dev** [comment]
I searched for usages of these functions in public GitHub repositories. From the usages found, it seems people expect that the return value indicates whether the value has been successfully set. While most of these functions do not have manual pages, the function `TS_VERIFY_CTX_set_certs` does:

```
RETURN VALUES
       TS_VERIFY_CTX_set_certs() returns the stack of X509 certificates the user passes in via parameter certs.
```

I recommend adding documentation pages to the existing functions, clearly stating that the returned value is the one passed in. This clarification would help prevent misunderstandings about the return value being a status indicator.

Regarding adding `OPENSSL_free` to these functions:
- If data in a context is released using `OPENSSL_free`, the context is still in use, but the pointer to this data isn't set to NULL, I consider this as bad programming practice.
- Without documentation on how these functions should be used, it's hard to fault users for misuse.
- Deprecating the existing methods and replacing them with well-defined ones seems reasonable, especially since they are rarely used.

## Proposed Changes

@t8m I would create a pull request with the following changes:

- Create a new set of all `TS_VERIFY_CTX_set_*` functions named `TS_VERIFY_CTX_set1_*`.
- Change the return type to `int`, returning 1 on success and 0 on failure, consistent with the rest of the API.
- Free any previously allocated data before assigning new data.
- Write documentation for all new methods.
- Deprecate all old methods.

## Collected Usages

https://github.com/openssl/openssl/blob/2f0b4974dfbd9bc71e1164e0742fc7fdb2b2b70e/apps/ts.c#L923
```c
        if (data != NULL) {
            f |= TS_VFY_DATA;
            if (TS_VERIFY_CTX_set_data(ctx, BIO_new_file(data, "rb")) == NULL)
                goto err;
        } else if (digest != NULL) {
```

https://github.com/Ptival/pirate/blob/b4d9f71674331f6b73c0645e1b2995aa9d8142fe/demos/time_demo/src/ts_crypto.c#L539
```c
    if (TS_VERIFY_CTX_set_data(ctx, data) == NULL) {
        goto end;
    }
    data = NULL;         /* Freed by TS_VERIFY_CTX_free */
```

https://github.com/andronat/dcmtk/blob/5e874fa8c1675df9f6fb3ed1fa0934e8665cb74b/dcmsign/libsrc/sitstamp.cc#L58
```c
#define TS_VERIFY_CTX_set_data(x,y) ((x)->data = (y))
```

https://github.com/open-eid/libdigidocpp/blob/41bba271a3f16afacbe35171b7e0546a28c84087/src/crypto/TS.cpp#L252
```cpp
        TS_VERIFY_CTX_set_flags(ctx.get(), TS_VFY_IMPRINT|TS_VFY_VERSION|TS_VFY_SIGNATURE);
        TS_VERIFY_CTX_set_imprint(ctx.get(),
            (unsigned char*)OPENSSL_memdup(digest.data(), digest.size()), long(digest.size()));
        TS_VERIFY_CTX_set_store(ctx.get(), store.release());
        if(TS_RESP_verify_token(ctx.get(), d.get()) != 1)
        {
            unsigned long err = ERR_get_error();
```

https://github.com/openssl/openssl/blob/2f0b4974dfbd9bc71e1164e0742fc7fdb2b2b70e/apps/ts.c#L961
```c
    if (untrusted != NULL) {
        certs = load_certs_multifile(untrusted, NULL, "extra untrusted certs",
                                     vpm);
        if (certs == NULL || TS_VERIFY_CTX_set_certs(ctx, certs) == NULL)
            goto err;
    }
    ret = 1;
```

**Comment by t8m** [comment]
I am actually not sure it is worth it touching this particular issue. But if you want to, your plan seems OK except for naming the new functions. They should be named `TS_VERIFY_CTX_set0_*` not set1. `set1` is used in case the callee doesn't take ownership of the passed-in reference.

**Comment by erbsland-dev** [comment]
@t8m I agree, it’s a subtle point, but I believe it’s better to fix it before these functions see actual use. Thank you for pointing out the correct `set0` naming convention. I will start working on a PR.

**Comment by erbsland-dev** [comment]
@t8m I assumed deprecation for the 3.4.0 release and split the documentation into two files to avoid distracting the reader with the deprecated function calls.

**Comment by t8m** [comment]
> @t8m I assumed deprecation for the 3.4.0 release and split the documentation into two files to avoid distracting the reader with the deprecated function calls.

I am not sure it makes sense to split the docs. But it is up to you.
