### ISSUE TITLE
openssl 1.1.1q Opensuse Tumbleweed

### ISSUE THREAD

**Issue by GastonMelo** [openssl/openssl#18971]
Hi to all, Im trying to CROSS-COMPILE u-boot to use sunxi liche pi. Im using Linux Opensuse Tumbleeed and also using openssl 1.1.1q version. When I perform make CROSS_COMPILE=arm-linux-gnueabihf- (i had the export on bashrc) this error came up:
![Screenshot_20220809_195611](https://user-images.githubusercontent.com/42498839/183776002-4398f7d1-38fd-483c-adfc-37054127822d.png)
I read on other thread about this error but don't know how to fixed.
Thanks
Gastón

**Comment by tom-cosgrove-arm** [comment]
As per https://github.com/openssl/openssl/blob/master/SUPPORT.md, how you configured is even more important than how you invoked `make`.

Can you include the output of `perl configdata.pm --dump` and `cc --version`?

**Comment by mattcaswell** [comment]
You say you are using OpenSSL 1.1.1q, and your screenshot says "in expansion of macro 'RSA_get0_n'"....but `RSA_get0_n` is not a macro in 1.1.1q it is a *function*. There is no such macro defined in any OpenSSL version.

This looks like some compatibility macro is incorrectly being defined somewhere so that the code will work with versions of OpenSSL that don't have that function - but it is not required for 1.1.1q.

Searching for the code file that is failing I find this:

https://github.com/u-boot/u-boot/blob/3dd4e916324efc825a7ee8e412f5cf1ded839021/tools/sunxi_toc0.c#L37-L41
````
#if defined(LIBRESSL_VERSION_NUMBER)
#define RSA_get0_n(key) (key)->n
#define RSA_get0_e(key) (key)->e
#define RSA_get0_d(key) (key)->d
#endif
````
So, indeed, compatibility macros are being defined if `LIBRESSL_VERSION_NUMBER` is defined. But that macro is something that comes from LibreSSL (a fork of OpenSSL) not OpenSSL itself. This looks to me like your environment is screwed somehow and it is somehow partially configured for use with LibreSSL and partially for use with OpenSSL.

In any case this doesn't look like a problem with OpenSSL itself. You should probably direct your questions to the u-boot developers.

**Comment by GastonMelo** [comment]
thanks for your help. I uninstall Libressl and the error is gone now. Thanks!!!

**Comment by mattcaswell** [comment]
Great. Closing this.
