### ISSUE TITLE
NIST and FIPS compliant in openssl 

### ISSUE THREAD

**Issue by sheikfaaruk** [openssl/openssl#18984]
I am using a 64 bit arm architecture based soc from NXP (QorIQ LS1046A) which includes cryptography hardware accelerator(NXP CAAM) in build. My requirement is to develop a ssl based application using OpenSSL, currently i am using OpenSSL v1.1.1d. I need to offload all crypto functions into hardware accelerator(NXP CAAM), offload is done now through OpenSSL 1.1.1d.

I was able to generate a random number from the generator using hardware accelerator(NXP CAAM) in QorIQ LS1046 soc.
NXP CAAM provide a complete implementation of SP800-90A using SHA-256 in random number generator.

My question is, if cryptography hardware accelerator provides a FIPS & NIST Compliant means. To achieve FIPS & NIST Compliant is OpenSSL 1.1.1d is enough or need to upgrade for OpenSSL 3.0?

**Comment by mattcaswell** [comment]
> My question is, if cryptography hardware accelerator provides a FIPS & NIST Compliant means. To achieve FIPS & NIST Compliant is OpenSSL 1.1.1d is enough or need to upgrade for OpenSSL 3.0?

It's not clear from your question what you are after. FIPS is a large set of standards covering many different crypto algorithms and primitives.

SP800-90A is one specific standard relating to DRBGs.

Any particular product may be compliant with one or more standards - meaning that its implementation follows the requirements of those standards. Any vendor can claim compliance with the standards. Those claims are not necessarily checked by anyone external to the vendor.

NIST also run a cryptographic module validation program. This validates and provides a certificate from NIST that a module conforms to FIPS 140-2 (or FIPS 140-3). Those standards themselves require that any cryptographic algorithm the module implements conforms to many other FIPS standards in order to be able to claim compliance and achieve validation.

OpenSSL 3.0 provides a FIPS module that is compliant with FIPS 140-2 and is currently undergoing validation. There is no FIPS module available directly from the OpenSSL project for 1.1.1.

I do not know the specifics of the product you are using and whether it has a FIPS 140-2/3 validation.

So you really need to understand what crypto algorithms do you need to use and do they need to be simply compliant with a standard, or do they to be FIPS 140-2 or FIPS 140-3 validated? What algorithms does the module you are already using implement and are they FIPS 140-2 or FIPS 140-3 validated?

**Comment by sheikfaaruk** [comment]
Thank you for your reply

**Comment by paulidale** [comment]
You should ask a FIPS labs what your status is.  They are the experts, each situation is different and there are many subtleties involved.

The security policy for the hardware you are using should also be available, it will list all the validated algorithms.  If you use anything outside of those, you won't be compliant.
