### ISSUE TITLE
Cyptographic library | Expressions illustrating different cipher naming conventions mixed

### ISSUE THREAD

**Issue by Ricky-Tigg** [openssl/openssl#19012]
_release:_ openssl-3.0.5

Hello. Expressions illustrating different cipher naming conventions may be mixed in command output. It may not be an indication of an issue but a coherent outcome. In case it is not, reporting. Illustration:
```
$ openssl ciphers -tls1_3 | sed 's/:/\n/g' | grep -i chacha | head -2
TLS_CHACHA20_POLY1305_SHA256
ECDHE-ECDSA-CHACHA20-POLY1305
```
Differing conventions are illustrated respectively by the presence of _ and _-_.

**Comment by mattcaswell** [comment]
The difference is deliberate:

````
ECDHE-ECDSA-CHACHA20-POLY1305
````

The above is an "old" style ciphersuite name used in protocol versions prior to TLSv1.3. Historically OpenSSL ciphersuites have had their own naming scheme different to the standard IETF ciphersuite name. This is quite confusing for a lot of users, but changing the names would probably cause lots of disruption and backwards compat issues.

````
TLS_CHACHA20_POLY1305_SHA256
````

This is a TLSv1.3 ciphersuite. When we added these new ciphersuites we decided to adopt the standard IETF naming. Since they were being newly added there were no backwards compat issues.

There is a slightly different peculiarity here but I'm not sure I would go so far as to say it is a bug. In your original command you had this:

````
$ openssl ciphers -tls1_3
````
This actually returns ciphersuites that are not suitable for use in TLSv1.3. To actually restrict the output to only those ciphersuites suitable for use in TLSv1.3 you additionally need the `-s` param:

````
$ openssl ciphers -tls1_3 -s
````
That behaviour seems a bit unexpected.

**Comment by Ricky-Tigg** [comment]
That was much helpful. The amount of suitable ciphers is probably not common knowledge. I was myself surprised
```
$ openssl ciphers -tls1_3 | sed 's/:/\n/g' | wc -l
61
$ openssl ciphers -tls1_3 -s | sed 's/:/\n/g' | wc -l
4
$ openssl ciphers -tls1_3 -s | sed 's/:/\n/g' | column
TLS_AES_256_GCM_SHA384			TLS_AES_128_GCM_SHA256
TLS_CHACHA20_POLY1305_SHA256		TLS_AES_128_CCM_SHA256
```

**Comment by mattcaswell** [comment]
Prior to TLSv1.3 the ciphersuite specified a lot more things such as the signature algorithm and the key exchange algorithm. With just a few choices with each different type of algorithm it doesn't take much for all the different combinations to multiply up to a lot of ciphersuites being needed. From TLSv1.3 the signature algorithm and key exchange algorithm is not specified by the ciphersuite anymore (these are instead negotiated via a different mechanism) and so you need a lot less ciphersuites.

**Comment by Ricky-Tigg** [comment]
The fifth, 0x13,0x05 | TLS_AES_128_CCM_8_SHA256, not being recommended.
