### ISSUE TITLE
Openssl fails to connect to SMTP server TLS enabled- with 1.1.1o in IBM AIX

### ISSUE THREAD

**Issue by sunnysaurabh93** [openssl/openssl#19011]
While executing the below command using latest openssl 1.1.1O :
openssl s_client -connect <mail.example.com:25> -starttls smtp

Getting the below error :
error:1421C105:SSL routines:set_client_ciphersuite:wrong cipher returned

Tried adding -qstaticinline in CFLAGS while building the openssl libs but still getting the same error.

**Comment by mattcaswell** [comment]
> error:1421C105:SSL routines:set_client_ciphersuite:wrong cipher returned

This indicates a "should not happen" protocol level error. It can happen for a number of different reasons, but all come down to the server selected a ciphersuite that we weren't expecting or did not think was allowed in this context.

If you can get a pcap trace of the handshake that might help to diagnose further.

**Comment by sunnysaurabh93** [comment]
[](url)

**Comment by sunnysaurabh93** [comment]
[ssl.zip](https://github.com/openssl/openssl/files/9413603/ssl.zip)

Hi captured the pcap trace using tcpdump on AIX machine where I am running the above openssl command.. 
In the pcap file, 10.90.4.23 is the AIX machine ip and 40.97.121.18 is the ip of the office365 server.. As requested by you, can you check the pcap file and troubleshoot the issue. thanks

**Comment by mattcaswell** [comment]
Hmm...that is odd. It looks like the client is misbehaving for some reason. It appears to offer a set of ciphersuites to the server. The server is picking one of those offered, but the client is then complaining about it saying the server should not have selected it.

Please can you tell me how you compiled OpenSSL? In particular what Configure line did you use?

Are you able to build a debug version of OpenSSL. Are you comfortable running this in a debugger? I am interested to know what happens when it hits the `set_client_ciphersuite` function in ssl/statem/statem_clnt.c

**Comment by t8m** [comment]
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.
