### ISSUE TITLE
wiki.openssl.org is offline

### ISSUE THREAD

**Issue by RobertCElliott** [openssl/openssl#19060]
wiki.openssl.org currently returns this:

```
<?php // For broken web servers: ><pre>

// If you are reading this in your web browser, your server is probably
// not configured correctly to run PHP applications!
//
// See the README, INSTALL, and UPGRADE files for basic setup instructions
// and pointers to the online documentation.
//
// https://www.mediawiki.org/wiki/Special:MyLanguage/MediaWiki
//
// -------------------------------------------------

```

**Comment by levitte** [comment]
Thanks for the heads up.  I'm on it.

**Comment by levitte** [comment]
Fixed!

The causes of this failure appears to be an incomplete upgrade of mediawiki when the operating system was upgraded

- [ ] WIth newer mediawiki versions, it appears that you *must* set `$wgServer` in LocalSettings.php
- [ ] There was some confusion with the mysql server upgrade, so the mysql server couldn't start properly
- [ ] Probably because of that, the mediawiki maintenance update hadn't run, so the database hadn't migrated to the new version
