### ISSUE TITLE
'openssl ciphers -ciphersuites' | Queried algorithm list not honoured

### ISSUE THREAD

**Issue by Ricky-Tigg** [openssl/openssl#19104]
_release:_ openssl-3.0.5
_reference:_ (outputs truncated)
```
$ openssl help ciphers
 -ciphersuites val   Configure the TLSv1.3 ciphersuites to use
$ man openssl-ciphers
 -ciphersuites val
  Sets the list of TLSv1.3 ciphersuites. This list will be combined with
  any TLSv1.2 and below ciphersuites that have been configured.
```
Hello. "_Configure the TLSv1.3 ciphersuites to use_" and "_Sets the list of TLSv1.3 ciphersuites_", which are self-explicitly formulated sentences, are actually not reflecting their meanings as "_This list will be combined with any TLSv1.2 and below ciphersuites that have been configured._" demonstrates it. Such combination of contradictory meanings within the usage brings inevitably to the project at least confusion if not also incoherence.

When executing `openssl ciphers -ciphersuites TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384`, in which query is dully limited to specified algorithms, `TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384` alone is then expected as output, not as part of a non-queried output as it is actually the case.

**Comment by mattcaswell** [comment]
How would you formulate it better?

**Comment by Ricky-Tigg** [comment]
Well,thanks for asking me, though that's a bit fast. Remember the nature of the present report. I made the assumption that it may be a issue towards documentation, and made it while being on **user**'s side not developer's side. That tells all about the context if needed.

Here are the unknowns i could easily notice:
- whether a **triage** is needed for the present report; At the time i am writing, it still cannot be determined from developers' comments, whether the **command output** i presented as potential issue, was determined or could be determined as such by one of them.
- the effect that function attempted to achieve in first place. at least the author of the function would know that for sure.

**Comment by Ricky-Tigg** [comment]
Well, thanks for asking me, though that's a bit fast. Remember the nature of the present report. I made the assumption that it may be a issue towards documentation, and made it while being on **user**'s side not developer's side. That tells all about the context if needed.

Here are the unknowns i could easily notice:
- whether a **triage** is needed for the present report; At the time i am writing, it still cannot be determined from developers' comments, whether the **command output** i presented as potential issue, was determined or could be determined as such by one of them.
- the effect that function attempted to achieve in first place. At least the author of this function would know that for sure.

**Comment by mattcaswell** [comment]
What you have observed is the correct expected behaviour. The `openssl ciphers` command gives you the list of ciphersuites that will be used for a given configuration. Configuration of ciphersuites is formed from two parts:
1) The configured list of TLSv1.3 ciphersuites to be used
2) The configured list of TLSv1.2 (and below) ciphersuites to be used

If you only configure one part you will get the default list for the other part. So for example if you only configure the TLSv1.3 ciphersuites then you will get the configured list of TLSv1.3 ciphersuites combined with the default list of TLSv1.2 (and below) ciphersuites. Similarly if only configure the TLSv1.2 (and below) ciphersuites you will get the default list of TLSv1.3 ciphersuites combined with the configured list of TLSv1.2 (and below) ciphersuites.

The current functionality was the result of a lot of debate about how TLSv1.3 ciphersuites should be integrated into libssl. The current way it works was considered the "least worst" option. It's less than ideal but for technical reasons it needs to work this way. It may be non-obvious to a new user so I'd be happy to consider better ways of describing this in our docs.

**Comment by Ricky-Tigg** [comment]
Strange how things may take a sudden turn. I found myself a bit pretentious to have been able to suppose for a moment that i could be a pertinent judge of a matter, whose highly complex nature i realize it fully now, somehow lately, was beyond my intelligence. If i learned a lesson, and i may have, i would hope that it is to became humble,

_ps._: As i understand it, the term "_Configuration_" must be referring to a task applying to ciphers in the installed OpenSSL library, which is in my Linux distribution installed by default, as those _configurations_ did not require my intervention. I wouldn't know even how ciphers may be configured and what it meant by such operation. Time to close, i must have already wasted your time.
