### ISSUE TITLE
OpenSSL 1.1.0 client can send Certificate message on renegotiation although not requested

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#1920]
As seen in https://bugzilla.redhat.com/show_bug.cgi?id=1393579 the openssl 1.1.0 client can send Certificate message although not requested with CertificateRequest on renegotiation. This is regression from 1.0.x.

In the handshake attached to the above Fedora bug you can see that the server requests a renegotiation where it sends CertificateRequest on which the client properly reacts with the Certificate message. Then the server immediately requests another renegotiation but this time without the CertificateRequest - the client in 1.1.0 incorrectly responds with Certificate message and the server (1.0.1) responds with fatal unexpected message alert.

**Comment by davidben** [comment]
Looks like this is because `s->s3->tmp.cert_req` (not to be confused with `s->s3->tmp.cert_request` :-) ) isn't reset to zero anymore. In 1.0.2, this line ended up resetting things.
https://git.openssl.org/gitweb/?p=openssl.git;a=blob;f=ssl/s3_clnt.c;h=218534734dd7e7467a14d1d0914207a77343e218;hb=refs/heads/OpenSSL_1_0_2-stable#l2073

(The state was always reached and then skipped afterwards.)

**Comment by seraphxs** [comment]
kk

**Comment by seraphxs** [comment]
opl

**Comment by t8m** [comment]
Unfortunately I do not know where is the most appropriate place to put the reset of the cert_req in the new state machine code.

**Comment by mattcaswell** [comment]
See fixes in #1982 and #1983
