### ISSUE TITLE
JA3 Fingerprint match with OpenSSL.

### ISSUE THREAD

**Issue by JeanPaulUltra** [openssl/openssl#19458]
Hello Developers,
i would like to ask. is there any way to send empty renegotiation_info extensions instead of TLS_EMPTY_RENEGOTIATION_INFO_SCSV Cipher even if we need to modify source of Openssl. and also is there any possibilities to serialize the extensions or extensions bytes on my own choice ? Please suggest me. Because i want to match JA3.

**Comment by sameer-here** [comment]
Per [the RFC](https://www.ietf.org/rfc/rfc5746.txt#3.3:~:text=However%2C%20some%20SSLv3,cannot%20be%20negotiated.) this workaround (sending TLS_EMPTY_RENEGOTIATION_INFO_SCSV ) is for TLS1.0 and SSLv3.

> However, some SSLv3 and
   TLS 1.0 implementations incorrectly fail the handshake in such a
   case.  This means that clients that offer the "renegotiation_info"
   extension may encounter handshake failures.  In order to enhance
   compatibility with such servers, this document defines a second
   signaling mechanism via a special Signaling Cipher Suite Value (SCSV)
   "TLS_EMPTY_RENEGOTIATION_INFO_SCSV", with code point {0x00, 0xFF}.
   This SCSV is not a true cipher suite (it does not correspond to any
   valid set of algorithms) and cannot be negotiated.

I think this cipher should not be send if the client has disabled SSLv3 and TLS 1.0.  @mattcaswell what do you think of that idea?

**Comment by mattcaswell** [comment]
The section you quote in the RFC is describing the original motivation for why you can signal this in two different ways (either via the SCSV or via an extension). However the RFC itself does not restrict usage of the SCSV to any particular protocol version. At the time of implementation OpenSSL chose the SCSV route and hasn't changed since (presumably since it worked in all protocol versions including SSLv3). These days SSLv3 support is disabled by default. It would be plausible to not send the SCSV if SSLv3 support is disabled. Instead the empty extension would need to be sent. Currently OpenSSL does not support that so it would have to be implemented. That's unlikely to be seen as a priority by the dev team, but if someone wanted to supply a PR to do it then it would be looked at.

**Comment by sameer-here** [comment]
Thanks Matt, I'll look into sending the empty extension.
