### ISSUE TITLE
Semantics of OSSL_FUNC_keymgmt_has/wrong PEM_read_bio_PrivateKey_ex selector logic

### ISSUE THREAD

**Issue by baentsch** [openssl/openssl#19498]
This is the documentation on the provider method [OSSL_FUNC_keymgmt_has](https://www.openssl.org/docs/man3.0/man7/provider-keymgmt.html):

> OSSL_FUNC_keymgmt_has() should check whether the given keydata contains the subsets of data indicated by the selector. A combination of several selector bits must consider all those subsets, not just one. An implementation is, however, free to consider an empty subset of data to still be a valid subset. 

Question: If the flags "OSSL_KEYMGMT_SELECT_PUBLIC_KEY | OSSL_KEYMGMT_SELECT_PRIVATE_KEY" are set, but the provider only has one component for the given EVP_PKEY, say the private key _but not_ the public key, is the provider function expected to return True ("empty subset OSSL_KEYMGMT_SELECT_PUBLIC_KEY" ) or False ("A combination of several selector bits must consider all those subsets")?

Reason for asking: The function [PEM_read_bio_PrivateKey_ex](https://github.com/openssl/openssl/blob/e251e7ba1ce85d11f3c342b3ae1326a35b7d0b4a/crypto/pem/pem_pkey.c#L292-L298) returns an error when trying to read a PKCS#8 structure that only contains a private key component because it requests presence of public _and_ private key ("EVP_PKEY_KEYPAIR"). Or is this an error, i.e., wouldn't it be more logical if `PEM_read_bio_PrivateKey_ex` were checking `EVP_PKEY_KEY_PARAMETERS | OSSL_KEYMGMT_SELECT_PRIVATE_KEY` rather than `EVP_PKEY_KEYPAIR`?

**Comment by t8m** [comment]
The answer to the question is the has function should return False.

And yeah, this looks like an error in PEM_read_bio_PrivateKey_ex() as it should check only for EVP_PKEY_KEY_PARAMETERS | OSSL_KEYMGMT_SELECT_PRIVATE_KEY.

**Comment by baentsch** [comment]
Thanks for the quick response. Will create suitable PR.

**Comment by levitte** [comment]
I'm don't quite agree with what @t8m said.

The selector when reading isn't a precise instrument, it's more of an indication what the key could potentially be used for (according to the general school of thought that the public key can be used to encrypt or verify a signature, and that the private key can be used for decryption and signing).

This is kinda blury, because keys can generally contain whatever parts.
For example, a PKCS#1 RSA private key also contains the purely public parts, so EVP_PKEY_KEYPAIR makes perfect sense for that.
Another example, an EC key may contain just the private part, but it's often assumed that if there is no public part present, it can still be easily be generated on the fly when needed (for encryption / verification), so EVP_PKEY_KEYPAIR is fitting there as well, in spirit at least.

With `OSSL_FUNC_keymgmt_has()`, it makes sense to be more precise, i.e. to return true/false values that reflect the contents of the key...  although, I'm not sure what to expect for EC keys, considering the possibility to automatically generate the public part; could it be seen as the public key always being there?

In the end, what a key can be used for is most safely determined when attempting something like EVP_DigestSignInit() with it, 'cause that's the only place where the provider can see how the key is actually going to get used.

So as you can see, the exact interpretation of selector is left to the provider.  Because there's quite a variety of what's considered valid, it's difficult to assert to much precision in libcrypto.

**Comment by baentsch** [comment]
>  it's difficult to assert to much precision in libcrypto

That I can whole-heartedly agree with: A very similar issue occurs with the `OSSL_FUNC_keymgmt_match_fn`: The `oqsprovider` just cannot always properly decide whether two keys (i.e., when only passed pure private and pure public EVP_PKEYs) match and has to leave possible mismatches to "later" logic (i.e., actual key uses that might fail if the two key parts were indeed not matching). Of course it would be possible to "operate" the two keys within the `match` function to find out whether they match but that feels "overkill" (and inefficient): Please let me know if you feel strongly about this (and the function `match` must do everything it can to ascertain key pair correctness).

In this case of `has`, though, things IMO seem more clear: Changing the provider's logic to return `True` when asked for public and private key component(s) "feels wrong": This occurs when parsing a private key file where I'm changing the provider implementation in line with a standardization proposal where the PKCS#8 file is to only contain private key components: With this change, the provider now returns `False` (as it factually does not have both key components) to the current `PEM_read_bio_PrivateKey_ex` selector request. Thus I really think the OpenSSL selector logic in `PEM_read_bio_PrivateKey_ex` should be changed to not check for public key components. 

My intention was to add this change to the completion of https://github.com/openssl/openssl/pull/19312 and corresponding additional tests for https://github.com/openssl/openssl/issues/19369: I will not do that if you disagree with this change. What about you assign the "bug" label to this issue if you'd agree the selector in `PEM_read_bio_PrivateKey_ex` should be changed?

**Comment by t8m** [comment]
I do not think there is any dispute on OSSL_FUNC_keymgmt_has semantics. The current semantics is correct. And no, we do not compute the public key in EC keys on demand, instead we do it on import so there cannot be any EC key without public key. But that is IMO irrelevant to the OSSL_FUNC_keymgmt_has semantics.

**Comment by t8m** [comment]
Please look at #19505 for the proposed fix of the PEM functions.
