### ISSUE TITLE
zlib-compressed certificates aren't interoperable

### ISSUE THREAD

**Issue by t184256** [openssl/openssl#19520]
I'm testing newly merged certificate compression feature,
and I suspect that zlib-compressed data comes out malformed and non-interoperable.
OpenSSL is master, configured with `no-shared enable-brotli enable-zstd enable-zlib`.

I've tested it against:
1. gnutls client against openssl server
2. my implementation of RFC8879 in [tlslite](https://github.com/tlsfuzzer/tlslite-ng/pull/484)/[tlsfuzzer](https://github.com/tlsfuzzer/tlsfuzzer/pull/802)

Rough steps to reproduce:
```
wireshark &
./apps/openssl s_server -www -key server/key.pem -cert server/cert.pem -verify 1 -CAfile ca/cert.pem -cert_comp &
SSLKEYLOGFILE=keylogfile build/src/gnutls-cli localhost:4433 --x509cert client/cert.pem --x509key client/key.pem --x509ca ca/cert.pem --compress-cert=zlib -d9
```
openssl prints `804BB240F37F0000:error:0A000412:SSL routines:ssl3_read_bytes:ssl/tls alert bad certificate:ssl/record/rec_layer_s3.c:783:SSL alert number 42`
gnutls prints
```
...
|<3>| ASSERT: ../../lib/buffers.c[get_last_packet]:1176
|<3>| ASSERT: ../../lib/handshake.c[_gnutls_recv_handshake]:1600
|<3>| ASSERT: ../../lib/buffers.c[_gnutls_handshake_io_recv_int]:1428
|<3>| ASSERT: ../../lib/compress.c[_gnutls_decompress]:231
|<3>| ASSERT: ../../lib/tls13/certificate.c[decompress_certificate]:641
|<3>| ASSERT: ../../lib/tls13/certificate.c[_gnutls13_recv_certificate]:84
|<5>| REC: Sending Alert[2|42] - Certificate is bad
|<5>| REC[0x1a11bc0]: Preparing Packet Alert(21) with length: 2 and min pad: 0
|<9>| ENC[0x1a11bc0]: cipher: AES-256-GCM, MAC: AEAD, Epoch: 1
|<5>| REC[0x1a11bc0]: Sent Packet[1] Alert(21) in epoch 1 and length: 24
|<3>| ASSERT: ../../lib/handshake-tls13.c[_gnutls13_handshake_client]:124
*** Fatal error: Decompression of the TLS record packet has failed.
...
```

Moreover, if I select `Compressed Certificate Message` from `Server Hello` in wireshark,
export it and try to uncompress it with python's zlib, that fails:
``` python
import zlib
data = \
b"\x78\x9c\x62\x60\x60\x53\x65\x60\xe6\x37\x68\x62\xe6\x36\x68\x62" \
b"\xfc\xbc\x80\x99\x89\x91\x09\x88\x0c\x78\xd9\x38\xb5\xda\x3c\xda" \
b"\xbe\xf3\x32\x32\x72\xb3\x32\x18\x88\x1a\x0a\x1b\x08\xb2\x31\x87" \
b"\xb2\x70\xf1\x70\xb9\x56\x24\xe6\x16\xe4\xa4\x2a\x38\x3b\x1a\xc8" \
b"\x89\xf3\x1a\x19\x19\x1a\x18\x19\x18\x9a\x18\x1b\x1a\x5b\x46\x01" \
b"\xb9\xc6\x48\x5c\x03\x11\x43\x21\x03\x01\x90\x36\x66\x1e\xce\x9c" \
b"\xfc\xe4\xc4\x9c\x8c\xfc\xe2\x12\xa0\x3d\x4a\xc8\xe6\x33\xb2\x32" \
b"\x30\x37\x31\xf2\x33\x00\xc5\xb9\x98\x9a\x18\x19\x19\xf6\xda\x5f" \
b"\x72\xfd\x70\xa7\x62\xfe\xb9\xe7\x9f\xda\xf4\xa5\xa3\x76\x1b\x1c" \
b"\xbe\x5a\x2d\x96\x53\x1d\xce\x7c\xf4\x57\x1b\x23\x67\x64\xcd\x8d" \
b"\x25\x65\x65\x45\x2d\xae\x99\x21\xfb\x26\x4c\xcc\x5e\xb1\xab\xbd" \
b"\xe0\x5e\xc2\x04\xa9\x57\x87\xe2\xf2\xe6\x4f\x55\x37\xf4\xce\xb3" \
b"\xdf\x9f\xe8\xb6\xc0\xe0\xf0\xa9\x5d\x11\xd3\xa3\xcf\x2d\xfe\x37" \
b"\x7f\xcf\xf4\x1f\xde\x33\xdc\xbb\x55\x93\x9d\xe7\x5e\x92\x98\xa4" \
b"\x2b\x31\x35\xde\x85\xdb\x4e\x42\x71\xa3\x82\x93\x98\xf1\x5e\xab" \
b"\x43\x3d\xf7\xdf\xdf\x99\xbf\x8f\xe5\xf7\x61\xf1\xd5\x6d\xad\x0f" \
b"\x8f\x58\xa9\xcd\xf7\xfc\x3c\xe1\xc2\x04\xe9\x7b\x56\x8f\xd6\x37" \
b"\xa7\x34\x2e\x97\xbe\x64\x6b\xba\x44\x93\x49\x69\x41\xb2\xc2\x86" \
b"\x97\x36\x93\x6c\x3e\xd8\x73\x76\xb6\xf7\x26\x88\x07\x4f\x28\xb6" \
b"\x63\x99\xe5\xc9\xbc\xe9\xb0\xff\x85\xd5\x4f\x3c\x3e\x5a\x71\x5f" \
b"\xfd\xc3\xc2\xd3\x7f\x85\x43\xd7\xc6\xe6\xdf\xf5\x0d\xd3\xfe\xd6" \
b"\xdc\xf1\x8b\x53\x69\x31\xf1\xda\xb1\xda\xc4\x36\x26\x4f\x7e\xba" \
b"\x49\x80\xc3\xfc\xba\x5b\x7d\x3a\xbb\xed\xb2\xbf\x29\x05\x34\xc4" \
b"\x1d\x6e\x4b\x34\xd0\xec\x33\xe9\x08\x52\x9a\x6c\xbc\x40\x34\xad" \
b"\xfc\xd8\xb4\x07\xbf\x25\x42\x33\xd5\x55\x99\x98\x19\x19\x18\x17" \
b"\xa7\x1b\xa4\x1a\xf0\x01\xc3\x4e\x96\x9f\x91\xf1\x3f\x0b\x0b\x33" \
b"\x13\xf3\x0a\x03\x61\x10\x5f\x95\x85\xc7\x80\x8b\x8d\x43\x9b\x8d" \
b"\x91\x95\x95\x9d\x99\xd1\x40\x16\x24\xc8\xc7\x22\xc6\x22\x32\x47" \
b"\x6e\x95\x7d\xc1\xff\x33\x7b\xfa\x82\x32\x66\x96\xf5\x88\x2a\xf8" \
b"\x24\x24\x3c\x33\x90\x07\x49\x2b\xb3\x48\x18\x88\x35\x88\xdc\xe8" \
b"\xba\xb6\x80\xe1\xfd\xd1\x99\x4b\x1f\xa5\xf9\x9c\xe8\x4d\xae\x09" \
b"\xa9\x3d\xbf\x08\x2d\xaa\x99\x41\x31\x50\x15\xd0\x75\x6f\xd9\x35" \
b"\xc5\xa7\xe7\x66\x5b\x71\x33\xd7\x5d\x58\x28\x1c\x76\xe5\x7f\xa8" \
b"\xd4\xe2\x65\x33\xbf\x0a\x19\xd8\xef\x91\xdb\xbc\x58\x76\xe5\x19" \
b"\x95\xbd\x4f\xf3\x8f\x6b\x3a\x1a\xe6\xab\xa7\xeb\x95\x1f\x17\x88" \
b"\x70\xd4\x3a\xbc\xa0\xf0\xe9\x92\x4f\x59\x2c\x3b\xc3\x6f\xeb\xdd" \
b"\x58\xf6\xf3\xe4\xe1\xbf\x8b\x04\x94\xfe\x1c\x0b\xbf\x7c\xaa\x54" \
b"\xfe\xdc\xb5\xb4\x4c\x19\xc6\xf5\x3b\xd6\xb0\xaf\x99\x1b\x5a\x7b" \
b"\x96\xd9\x95\x53\x9b\x29\x7d\x65\xe1\xf2\x7f\x0e\xdf\x1f\x2b\x58" \
b"\xe6\x65\xb7\x8a\x75\x9e\x58\x14\xa9\xe5\xb4\x7d\xeb\xef\xb5\xb7" \
b"\x63\xa6\x2d\xcc\x4f\x58\xb1\xc2\x47\xba\xd9\xbd\xc2\x2f\xde\xfa" \
b"\xcb\xc4\x95\xdd\x53\xd5\x2d\x0f\x94\x64\xfe\x75\x8d\x99\x12\x1e" \
b"\x58\xed\x62\xda\x5a\x91\xd5\x32\x55\x6d\xfd\xe9\x49\x9d\xd6\x66" \
b"\x0b\x35\x3a\xfb\x27\x5c\x5c\x2c\x52\x31\xe9\x89\xd0\xd6\x5f\xcd" \
b"\x09\x4f\x3d\xc5\xdd\x37\xc9\x9c\xe5\x5c\xf4\x2f\xc5\x7f\x76\x8e" \
b"\xeb\xea\x2d\xd3\xdf\xaa\xaf\x33\xb1\xbb\xcc\x15\x9a\x57\xbe\xf1" \
b"\x6e\x5a\xfe\x36\x0f\xfd\xe4\xfa\x43\x8a\x3f\xee\xc7\x55\x7f\xd4" \
b"\xaa\xcf\xf6\x8d\x8f\xe7\xfa\x26\x68\x71\xc9\xc2\x7f\xc1\x29\xcf" \
b"\x1d\xae\x5b\xff\xf8\x6f\x3b\xc5\xc0\xc0\xc0\xcc\x03\xcc\x13\x1c" \
b"\xc0\x34\xf9\x01\x9a\x27\x18\x89\xcf\x13\x86\xe6\xf0\x4c\x60\x00" \
b"\xcc\x13\xc6\x46\x48\x5c\x5c\xda\x08\x65\x8a\x65\x1d\xe7\x7d\x2c" \
b"\x97\x6e\x77\x63\xcf\x5f\xfc\x81\x67\xd2\xc2\xbc\x49\x1a\xce\x4f" \
b"\xd5\xfb\xb4\x32\x33\xb6\x67\x18\x4d\x6f\xeb\x91\x69\x9e\xf7\xca" \
b"\x77\x53\xde\xd2\xc8\x25\x1d\x5e\x4c\xb3\x17\x96\x27\x3a\x3e\xbb" \
b"\xce\x7a\x7a\xe3\xab\xd9\x6a\x3f\x42\xd8\x8e\x32\xe5\xaf\x3b\xf4" \
b"\xea\x4c\x56\x6d\xde\xfb\xf2\x4c\x4d\xa3\xce\x46\x23\x31\x91\x15" \
b"\xaa\xdb\xa6\x25\xcc\x11\x28\x6f\xac\x4b\xb2\x4d\x9f\xbc\xae\x58" \
b"\xe5\x40\x95\x01\x5b\x66\x56\xd5\xc3\xc3\xfe\x26\xb7\xf5\x65\x3d" \
b"\xd5\xb9\x39\xa7\xef\xcd\x48\xe7\x8e\xfd\x6c\x63\x31\x7f\x12\x8b" \
b"\xe1\x31\xfd\x88\xf2\x4b\x92\xeb\x66\xcd\xc8\xdd\xb9\x79\x73\xe8" \
b"\xa2\x90\x82\x65\xd7\xbb\x2a\xec\x6f\xbf\xb0\xd6\x7c\xe0\x9f\xb1" \
b"\xf0\xa4\xe2\x47\xd6\x06\xbf\xba\xa7\x95\x05\xf2\xba\xaa\x99\xc6" \
b"\xbc\x6b\x2b\x3b\xb9\xd9\x1f\xfd\x0e\xb2\x33\x3d\xfa\xd8\x48\xac" \
b"\x3b\xd2\xb5\xe7\x64\x6a\x4c\xf2\x81\x1d\x9b\x03\x12\xfc\x13\x5f" \
b"\x78\xab\x65\x9f\x5b\xf4\x46\x5b\xdf\x50\xf0\x88\x59\x4e\x3d\xc3" \
b"\xe9\x57\x1f\xf8\x9d\xbd\x2b\x0e\xb3\xb3\xa6\x0a\xf8\xeb\x3c\x8b" \
b"\x6b\x3f\x97\xfe\x80\x81\xef\xf1\xec\x0f\x97\xfc\xac\xb8\xa2\xf9" \
b"\x1b\x5c\x65\xfd\xa5\x03\x21\x99\x22\xd9\x20\xd1\x80\x1f\x94\xa0" \
b"\x85\x41\x99\x82\xd5\x80\x19\x48\xa1\xe6\x12\x46\x36\xa4\x0c\x81" \
b"\x35\xbd\x93\x93\x21\x84\x9d\x27\xef\x15\x12\xd9\x1d\x7e\x4a\xc5" \
b"\x78\x52\x9c\xcf\x96\x0b\x1c\xe7\xbf\xbf\x2f\x67\xd7\xab\x29\x5d" \
b"\xb4\x2b\xf3\xc7\xb2\xbc\x1d\x7a\xce\xcc\x5f\x36\x7b\x38\x86\xf5" \
b"\x54\x59\x7b\xa5\x9e\xe1\xf3\xbd\x69\x95\xb0\xe9\x9a\x9f\xd2\xe1" \
b"\xf0\x13\x8e\x97\xb8\x7e\xf9\x7b\xc8\x2e\x38\x73\xf6\xdd\xc4\xd8" \
b"\x84\x7b\xe9\x56\xdc\xa5\x02\x6e\x87\xaa\x13\xa6\x3b\xbc\xe1\x6b" \
b"\x48\x7f\xca\xfd\x74\x2e\xc3\x56\xfe\x04\xf6\x39\xb5\xdd\x87\x52" \
b"\xbf\x36\xda\x70\x2b\x5c\x5c\xc3\xaf\xe6\xad\x16\xfa\x2c\xd8\x3c" \
b"\x87\xc3\x99\xab\x2f\xf9\xed\xed\xc3\xdb\xee\x16\xec\x66\xf5\xcc" \
b"\x5c\xa8\xbb\xf6\x93\x60\xee\xe3\x46\x87\x0b\x09\x8b\x9a\x9b\xde" \
b"\xd9\x85\x85\x2e\x79\x1a\xfe\xaa\x98\x6b\x49\xa6\x5d\x22\xff\xf3" \
b"\xe4\x58\x9b\x65\x57\x2f\xfe\x15\x9b\x1d\xba\xf7\x53\xf2\xdc\x85" \
b"\xb3\x7f\xbd\x4b\x4a\x6f\xd8\xcf\x76\x77\x5f\xa7\xf3\xe4\x9b\xba" \
b"\xfd\x45\x13\x45\x72\x0c\xd7\x7a\x4e\xbf\xa7\x97\xbf\xe9\xac\x85" \
b"\x74\x87\x75\xed\x84\xef\x5a\x41\xb3\xd3\x66\xcc\x0d\xda\xaa\xe5" \
b"\xb1\xbf\xef\xc6\xdf\x33\xcb\xdf\x72\x9e\x9c\xbe\x6f\x15\xab\x47" \
b"\xfc\xaf\x0e\xdb\x3b\xbb\xc4\xb2\x26\x6c\x0e\x2a\x3c\xa6\x1c\x51" \
b"\x70\x96\x93\x81\x01\x00\x00\x00\xff\xff"
zlib.decompress(data)
```
```
zlib.error: Error -5 while decompressing data: incomplete or truncated stream
```

Note that without a `-comp_cert` on the server, compression isn't used at all,
I'm not sure this is intended.

If you'd like me to provide a more complete self-contained reproducer,
please specify what implementation would you prefer me to reproduce against.

**Comment by beldmit** [comment]
@tmshort could you please look?

**Comment by tmshort** [comment]
I'll take a look when I get a chance.
Is it only with ZLIB? What about Brotli and Zstd?

**Comment by tmshort** [comment]
>Note that without a -comp_cert on the server, compression isn't used at all,
I'm not sure this is intended.

That's intentional, you have to explicitly tell it to compress the certificate on the server-side (so it can be tested as "enabled", but with no compressed certificates).

**Comment by t184256** [comment]
> Is it only with ZLIB? What about Brotli and Zstd?

Yes, the other two decompressed fine in my testing.

>> Note that without a `-comp_cert` on the server, compression isn't used at all, I'm not sure this is intended.
>
> That's intentional, you have to explicitly tell it to compress the certificate on the server-side (so it can be tested as "enabled", but with no compressed certificates).

`--help` [said](https://github.com/openssl/openssl/blob/d8eb0e1988aba5d86aa6570357853cad0ab3f532/apps/s_server.c#L847) it's "*pre*-compress", `SSL_CONF_cmd` [said](https://github.com/openssl/openssl/blob/d8eb0e1988aba5d86aa6570357853cad0ab3f532/doc/man3/SSL_CONF_cmd.pod?plain=1#L556) compression is on by default and `s_client` lacked a matching option, so I was left under the impression it *pre*compresses server certs. Like, performs an optimization, not acts as a knob for everything RFC8879.

**Comment by tmshort** [comment]
There's a few things going on here. The API went through several iterations during review. It was decided to simplify and always have the server-side pre-compress the certificates, rather than enable automatic compression, which is what the client does.

This was done for performance, to avoid repetitively compressing a certificate on-the-fly when it's not necessary. This is possible on the server-side only, since the context value is 0. This allows an application to call the pre-compression APIs and store the pre-compressed certificate in an SSL_CTX or other data store.
For the client-side, since the context value is given to it by the server, the compression has to be done on demand during the handshake.

That being said, we have to distinguish between the options that are available to enable/disable certificate compression via the extension, and the actual use of a compressed certificate.

The _negotiation_ of the certificate compression option is enabled by default. The `SSL_OP_NO_TX_CERTIFICATE_COMPRESSION` and `SSL_OP_NO_RX_CERTIFICATE_COMPRESSION` options (and their corresponding configuration file commands) can be used to enable and disable this negotiation.

In actuality, this is not a negotiation, the extension is just a notification from one peer to the other indicating what types of certificate compression it supports.

Now, just because certificate compression is supported by the peer, it doesn't mean it has to be used! For example, if the compressed certificate actually expands, sending this larger certificate makes no sense. Or maybe one side doesn't support a compression algorithm the peer does.

So, the `-comp_cert` option on the server is used to invoke the APIs to pre-compress the certificates in `s_server`.

This extra knob allows testing with `s_server`, in that you are able to control whether or not to actually have the server send a compressed certificate based on the "negotiation".

For instance, if I want to test if my client's state machine can handle the non-compressed Certificate message even though my client sent the extension.

(I worked on this PR for 3 years, so I can elaborate on it quite a bit.)

**Comment by tmshort** [comment]
In response specifically to this:

> Like, performs an optimization, not acts as a knob for everything RFC8879.

To sent compressed certificates from the server, the certificates must always be pre-compressed; it's not considered an optimization (even though it is). This was to actually _simplify_ the user API, since there was originally a complicated callback mechanism and multiple means of compressing the certificate.

Given a CDN for example, which might store and transport certificates around its network already compressed, it just needs to assign the compressed blob to the SSL/SSL_CTX via the `SSL_set1_compressed_cert()` (or SSL_CTX version) API after loading the non-compressed certificate and key.

A simpler website would instead load the certificate and key, then call `SSL_CTX_compress_certs()` to automatically compress the certificates (this is basically what `-comp_cert` does).

**Comment by tmshort** [comment]
> > Is it only with ZLIB? What about Brotli and Zstd?
> 
> Yes, the other two decompressed fine in my testing.

Thank you, this is helpful.

**Comment by beldmit** [comment]
I summarized several more useful features in #19532

**Comment by tmshort** [comment]
Looks as though I have to add a zlib oneshot function that terminates/completes the compression properly.

@t184256 could you try this branch? https://github.com/tmshort/openssl/tree/fix-zlib

**Comment by t184256** [comment]
@tmshort, thumbs up. Tried that one, zlib-compressed data is now decompressable.
