### ISSUE TITLE
Do not parse SANs of irrelevant types

### ISSUE THREAD

**Issue by DemiMarie** [openssl/openssl#19563]
This would have prevented both CVE-2022-3786 and CVE-2022-3602.

**Comment by dcooper16** [comment]
Hi @DemiMarie,

Could you please explain more what you mean by "irrelevant"? I looked at CVE-2022-3786 and CVE-2022-3602, and the descriptions say they are both about name constraint checking on email addresses. I am guessing this means that exploiting the vulnerability requires a CA certificate include a nameConstraints extension that imposes constraints on an email address and a certificate later in the path to have an email address in the subjectAltName. If that is the case, then certificate validation is required to check whether the email address in the SAN satisfies the name constraint, even if the application validating the certificates doesn't care about email addresses.

So, if your suggestion is that OpenSSL shouldn't parse the email address (because only the DNS name is relevant), even if a name constraint is imposed on email addresses, then this would be inconsistent with RFC 5280:

>    If a name constraints extension that is marked as critical
>    imposes constraints on a particular name form, and an instance of
>    that name form appears in the subject field or subjectAltName
>    extension of a subsequent certificate, then the application MUST
>    either process the constraint or reject the certificate.

**Comment by DemiMarie** [comment]
> So, if your suggestion is that OpenSSL shouldn't parse the email address (because only the DNS name is relevant), even if a name constraint is imposed on email addresses, then this would be inconsistent with RFC 5280:
> 
> > If a name constraints extension that is marked as critical
> > imposes constraints on a particular name form, and an instance of
> > that name form appears in the subject field or subjectAltName
> > extension of a subsequent certificate, then the application MUST
> > either process the constraint or reject the certificate.

What do other implementations, such as rustls, do?  From my perspective, the security impact of ignoring this is zero, and the increased attack surface is significant.

**Comment by briansmith** [comment]
> What do other implementations, such as rustls, do? From my perspective, the security impact of ignoring this is zero, and the increased attack surface is significant.

I implemented the name constraint checking in `webpki` that is used by Rustls. It doesn't parse or check email address constraints, but that was done more for expediency than anything else. I did implement the email address parsing & constraint verification in the similar mozilla::pkix C++ library.

It's difficult for a general-purpose X.509 library to get away from doing so, especially since the spec requires *all* constraints to be enforced during validation. Building and validating the certificate is a separate step from validating the certificate is valid for any particular name, as successfully filtering out "irrelevant" name types requires knowing what name type you're going to validate for.

**Comment by DemiMarie** [comment]
> It's difficult for a general-purpose X.509 library to get away from doing so, especially since the spec requires _all_ constraints to be enforced during validation. Building and validating the certificate is a separate step from validating the certificate is valid for any particular name, as successfully filtering out "irrelevant" name types requires knowing what name type you're going to validate for.

In the TLS context, one does have this information, but using it might be a layering violation.  That said, is there a reason that punycode decoding is necessarily part of this?  I would that domains in certificates would need to be punycode-encoded already.  Also, punycode could be handled with WPACKET (which does bounds checks) and should certainly be fuzzed.

**Comment by thesamesam** [comment]
@paulidale is working on WPACKET usage at https://github.com/openssl/openssl/pull/19591.

Fuzzing was brought up by @hanno at https://twitter.com/hanno/status/1587775675397726209 with a libfuzzer example.

**Comment by nhorman** [comment]
I'm not seeing a clear direction on this issue at the moment, Is it still being discussed?  I'm going to mark this as inactive, please update if there is further discussion here, otherwise it will be closed when 3.4 is released.
