### ISSUE TITLE
Upgraded openssl 3.0.2 to 3.0.7 but version command still show library for 3.0.2

### ISSUE THREAD

**Issue by Lee-Jung-Hoon** [openssl/openssl#19575]
I had just installed manual upgrade (3.0.2 -> 3.0.7) on Ubuntu 22.04

Unzipped the tar.gz file and executed the command
./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl shared
'make' and 'make test'
-> show results is 'PASS' 
'make install'
'ldconfig -v' 

but openssl version command still show library for 3.0.2
"OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)"

How can I make sure processes using the library are using the correct version library

**Comment by t8m** [comment]
You're using openssl packages distributed by your OS vendor. It is not recommended to replace the system openssl library with a library built by yourself. The vendor is supposed to provide packages updated with any security fixes relevant for the OS.

**Comment by ElectroLutz** [comment]
@Lee-Jung-Hoon Ubuntu released the fix yesterday

The version via command stayed the same
`$ openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)`

But you can check if the patch is installed via
`$ apt list --installed | grep openssl`

it should show "3.0.2-0ubuntu1.7" for openssl, which is the fix for the latest vulnerabilities.

**Comment by Lee-Jung-Hoon** [comment]
@t8m @ElectroLutz
I appreciate you for your kind help and advice.
