### ISSUE TITLE
Undefined Behaviour in `crypto/bn/rsaz_exp_x2.c`

### ISSUE THREAD

**Issue by manxorist** [openssl/openssl#19584]
The supposed fix from <https://github.com/openssl/openssl/pull/19394> (<https://github.com/openssl/openssl/commit/8511520842b744d1794ea794c032ce5f78cd874b>) is incomplete.

The problem was correctly diagnosed in that accessing misaligned data is Undefined Behaviour in C.

*See C17 §6.3.2.3 Pointer p.7*:
> A pointer to an object type may be converted to a pointer to a different object type. If the resulting pointer is not correctly aligned for the referenced type, the behavior is undefined. [...]

This applies regardless of guarantees of the targeted architecture.

However, the *fix* does not work for various reasons:
 1. GCC only documents `__attributed__((aligned(#))` on a `typedef` to be able to reduce the natural alignement requirements from GCC 9 onwards.
    See GCC 9 <https://gcc.gnu.org/onlinedocs/gcc-9.5.0/gcc/Common-Type-Attributes.html#Common-Type-Attributes>:
    > When used on a struct, or struct member, the aligned attribute can only increase the alignment; in order to decrease it, the packed attribute must be specified as well. When used as part of a typedef, the aligned attribute can both increase and decrease alignment, and specifying the packed attribute generates a warning.

    and GCC 8 <https://gcc.gnu.org/onlinedocs/gcc-8.5.0/gcc/Common-Type-Attributes.html#Common-Type-Attributes>:
    > The aligned attribute can only increase alignment. Alignment can be decreased by specifying the packed attribute. See below.

    Thus, if OpenSSL can still target GCC earlier than GCC 9, the attribute cannot be assumed to do anything and thus cannot be assumed to solve the problem.
    Also, it would need to be researched how compilers other than GCC which also define `__GNUC__` (i.e. Clang or icc/icx) handle this particular case.
 2. For MSVC, `__declspec(align(#))` has the same restrictions as for GCC <= 8.
    See <https://learn.microsoft.com/en-us/cpp/cpp/align-cpp?view=msvc-170>:
    > __declspec(align(#)) can only increase alignment restrictions.
 3. For any other compilers, the problem was not addressed at all.

Additionally, this is not just a mere problem of silencing a CI issue. Compilers are known to optimize based on alignment guarantees of the C standard and **will miscompile** (in relation to developer intent) such code (example: <https://godbolt.org/z/zs1hb1rdh>).

However, that's not all. Even if the pointer was properly aligned (which it is not in the general case), it would still be Undefined Behaviour due to type punning.

*See C17 §6.5 Expressions p.5*:
> An object shall have its stored value accessed only by an lvalue expression that has one of the following types:
>  -  a type compatible with the effective type of the object,
>  -  a qualified version of a type compatible with the effective type of the object,
>  -  a type that is the signed or unsigned type corresponding to the effective type of the object,
>  -  a type that is the signed or unsigned type corresponding to a qualified version of the effective type of the object,
>  -  an aggregate or union type that includes one of the aforementioned types among its members (including, recursively, a member of a subaggregate or contained union), or
>  -  a character type.

The proper way to portably issue mis-aligned or wrong-type loads and stores in C is to use helper functions based on memcpy, like:
```C
uint64_t load8(const void * p) {
    uint64_t result = 0;
    memcpy(&result, p, 8);
    return result;
}

void store8(void * p, uint64_t value) {
    memcpy(p, &value, 8);
}
```

*Related Question*: What is OpenSSL's policy on issueing security notices for Undefined Behaviour? I did read <https://www.openssl.org/policies/general/security-policy.html>, but it does not talk about Undefined Behaviour at all.

**Comment by paulidale** [comment]
I would expect most instances of undefined behaviour to be bugs not security issues.
It would depend on the undefined behaviour being exploitable.  If it were, it would be a security issue.

**Comment by bernd-edlinger** [comment]
This is a non-issue,  as we only alias BN_ULONG with a more aligned type of the same fundamental type "long",
that is similar like for instance, aliasing "long" with "unsigned long" is allowed.
But it has a potential to cause real damage, as we are not able to do proper testing of even very simple "fixes" in this
specific module.
Regarding the and GCC 8 documentation of the aligned attribute, that is simply a documentation issue.
All versions of gcc do respect this attribute at leaset with regard to the UBSAN code generation.

**Comment by manxorist** [comment]
> This is a non-issue,

***Absolutely not!***

> as we only alias BN_ULONG with a more aligned type of the same fundamental type "long",

You unaligned-alias to an uint8_t that is aliased to a BN_ULONG.

> that is similar like for instance, aliasing "long" with "unsigned long" is allowed.

No, that is not similar. The memory locations you alias uint64_t to are not locations where objects of type BN_ULONG exist, simply due to the fact that you modified the alignment. They merely overlap with them, which has no semantic meaning in C (other than for character types).

> But it has a potential to cause real damage,

So now it is an issue?
I am actually confused by your first claiming "*This is a non-issue*" and then "*has potential to cause real damage*".

> as we are not able to do proper testing of even very simple "fixes" in this specific module.

That's concerning. Why would OpenSSL ship code that it cannot test?

> Regarding the and GCC 8 documentation of the aligned attribute, that is simply a documentation issue.
> All versions of gcc do respect this attribute at leaset with regard to the UBSAN code generation.

Don't you think it is actively very dangerous to rely on undocumented compiler features in a security and safety related library?

https://github.com/bernd-edlinger/openssl/commit/8dfd00fb794b115b6065d94b6dd68b8cb0dbec9f does not fix the issue. It is only partially a concern of strict-aliasing (due to overlapping the unaligned uint64_t), and instead more of alignment. It does not address the issue at all for !\_\_GNUC\_\_.
Addressing also the overlapping is of course the correct thing to do, and a memcpy-based solution does both.

https://github.com/openssl/openssl/pull/19597 looks good to me, as it uses the portable abstraction that works with every compiler (and handles both, the alignment and aliasing/overlapping issues), instead of incompletely relying on compiler-specific language extensions for some compilers and ignoring the problem for others.

**Comment by bernd-edlinger** [comment]
Hmm, are you a lawyer?

BTW: I am a GCC maintainer myself, so I think I can tell how GCC works,
and since it is not developed by lawyers, errors are possible both
in the implementation and in the documentation.
The only thing we can do aginst it, is using proper tests.

> You unaligned-alias to an uint8_t that is aliased to a BN_ULONG.

The data flow is starting with `BN_ULONG *` here:
https://github.com/openssl/openssl/blob/f5a10d5cc19215ab22be55b4a2ee1e41bd38fb14/crypto/bn/rsaz_exp_x2.c#L142
to here:
https://github.com/openssl/openssl/blob/f5a10d5cc19215ab22be55b4a2ee1e41bd38fb14/crypto/bn/rsaz_exp_x2.c#L213
then cast to `uint8_t *`
https://github.com/openssl/openssl/blob/f5a10d5cc19215ab22be55b4a2ee1e41bd38fb14/crypto/bn/rsaz_exp_x2.c#L559
and back to `uint64_t_align1 *`
https://github.com/openssl/openssl/blob/f5a10d5cc19215ab22be55b4a2ee1e41bd38fb14/crypto/bn/rsaz_exp_x2.c#L562

So, originally a `long *` , and later a `long *` with an alignment attribute that is not defined by the standard.
The `uint8_t *` can alias anything, but that is irrelevant, as the`uint8_t *` is not dereferenced.
The point is, the aligned attribute does not give the compiler a guarantee that is will be mis-aligned or not.
Strict aliasing rules do never use knowledge from data flow analysis, no matter how obvious the data flow
may be,

**Comment by manxorist** [comment]
> Hmm, are you a lawyer?
> BTW: I am a GCC maintainer myself

Maybe I care about cross-compiler correctness and you do not?

GCC-specific knowledge is completely irrelevant here, as you absolutely need to prove that every compiler that also defines \_\_GNUC\_\_ also follows undocumented GCC behaviour.

> > You unaligned-alias to an uint8_t that is aliased to a BN_ULONG.
> 
> The data flow is starting with `BN_ULONG *` here:
[...]
> So, originally a `long *` , and later a `long *` with an alignment attribute that is not defined by the standard.

***WRONG!!!*** It's originally long * and later align(1) long * with a different offset, so thus originally actually ***NOT*** long * but somewhere inside a long *. That's very much not the same.

> The point is, the aligned attribute does not give the compiler a guarantee that is will be mis-aligned or not.

True, but what's the point of that statement? The accesses ***ARE*** mis-aligned as they very clearly add+6 or +7 to an uint8_t *.

> Strict aliasing rules do never use knowledge from data flow analysis, no matter how obvious the data flow may be,

GCC-specific, thus irrelevant.

I actually do not care if your change might have been "correct" ***for GCC*** because you implicitly relied on undocumented implementation details in earlier GCC. For every other compiler, it's still just very obviously very wrong.

**Comment by bernd-edlinger** [comment]
Sorry, you simply can't use any compiler you want to use here, this is a C code module just interfacing with an
assembler module.  The assembler modules must adhere to the ABI contract with the compiler, and so on.
Strictly speaking even if You use `memcpy` to access something that overlaps two adjacent `long` values,
this code relies on completely implementation dependent properties like byte-order and therefore it will
immediately break when you use a cross-compiler for a big-endian architecture.
So when you don't have any knowledge of the compiler you want io use, this code is and will always
be undefined behaviour, according to the C standard.
I mean, of course by the letter of the standard this is undefined behaviour as long as we don't rewrite it to
extract each byte of the BN_ULONG using shift operations like 
```C
b0 = (uint8_t)(*in);
b1 = (uint8_t)(*in >> 8);
b2 = (uint8_t)(*in >> 16);
```
But that is probably not at all desirable for the performance, and would be even more difficult to do it right,
since the original Author of this code does not seem to be around any more.

**Comment by manxorist** [comment]
> Sorry, you simply can't use any compiler you want to use here, this is a C code module just interfacing with an assembler module. The assembler modules must adhere to the ABI contract with the compiler, and so on.

Then specify which compilers the code is compatible with. Your previous change strongly suggests "all of them", because you explicitly (and wrongly so) handled cases for all of them.

And even then, you are still assuming that all compilers that are compatible with GCC also did have a crystal ball to imagine a non-existent documentation for earlier GCC in the past. Sure, dream on. You are arguing in favour of disgustingly dangerous and obviously brittle code in OpenSSL, a library that should be very security and safety conscious. And for absolutely no reason; a better and portable way to implement the code in question that does not rely on undocumented compiler-specific language extensions does exist.

> Strictly speaking even if You use `memcpy` to access something that overlaps two adjacent `long` values, this code relies on completely implementation dependent properties like byte-order and therefore it will immediately break when you use a cross-compiler for a big-endian architecture.

So the code should guard against that, which it kind of does as it references AVX512 which is only available on x86/amd64 and thus only little-endian. That assumption is thus fair, even though the C code itself might still compile, as it will probably not link successfully later on.

> So when you don't have any knowledge of the compiler you want io use, this code is and will always be undefined behaviour, according to the C standard. I mean, of course by the letter of the standard this is undefined behaviour as long as we don't rewrite it to extract each byte of the BN_ULONG using shift operations like
> 
> ```c
> b0 = (uint8_t)(*in);
> b1 = (uint8_t)(*in >> 8);
> b2 = (uint8_t)(*in >> 16);
> ```

If you want to go there, fine: While the endianness is not specified by the standard, the bit layout of unsigned types actually is. So, no, you are again wrong here. If the code is only suitable for little-endian 8-bits-per-byte (which it is), memcpy is totally fine.

> But that is probably not at all desirable for the performance, and would be even more difficult to do it right, since the original Author of this code does not seem to be around any more.

How is performance of any relevance for incorrect code?

**Comment by manxorist** [comment]
> You can also define load/store functions without using memcpy, which I generally prefer:

Yeah, that also works.

> ```c
> uint32_t load32(const uint32_t *p)
> {
>   const unsigned char *a = (const unsigned char *)p;
>   return a[0] | (a[1] << 8) | (a[2] << 16) | (a[3] << 24);
> }
> ```

However, I strongly suggest calling this particular function load32le (or similar), as it is an explicit little-endian load, independent of architecture endianness, and it should not take an uint32_t * argument, as that would suggest the memory would be aligned.

So, something like:
```c
uint32_t load32le(const void * p) {
    const unsigned char * a = (const unsigned char *)p;
    return a[0] | (a[1] << 8) | (a[2] << 16) | (a[3] << 24);
}
```

**Comment by hlandau** [comment]
@manxorist Sounds good.

**Comment by davidben** [comment]
I think I agree with @manxorist that the code is a strict aliasing violation. (Though I might suggest a less combative tone.) Compilers have to reason about more local data flow, but the actual text of the strict aliasing rule is a global property:

> An object shall have its stored value accessed only by an lvalue expression that has one of the following types:
> * a type compatible with the effective type of the object,
> * a qualified version of a type compatible with the effective type of the object,
> * a type that is the signed or unsigned type corresponding to the effective type of the object,
> * a type that is the signed or unsigned type corresponding to a qualified version of the effective type of the object,
> * an aggregate or union type that includes one of the aforementioned types among its members (including, recursively, a member of a subaggregate or contained union), or
> * a character type.

That is, the abstract machine knows the "effective type" of every object in memory. And then you can only access those objects through pointers that sufficiently match the effective type (or is a character type). That translates into aliasing assumptions made by the compiler, but code needs to follow the stricter thing.

(Personally, I think this rule is terrible and a failure of the language specification to meet reality. If someone were to actually build a StrictAliasingSanitizer, I'd expect to find zero non-trivial C programs actually honor strict aliasing. But those are the rules of the game we play right now, so we have to try. ☹️)

It is a _little_ weird because one might hope the vendor-specific `__attribute__((aligned(1)))` counts as compatible (unclear), and the text doesn't specifically say anything about overlap. But it's kind of a weird interpretation to allow overlap.

> Strictly speaking even if You use memcpy to access something that overlaps two adjacent long values, this code relies on completely implementation dependent properties like byte-order and therefore it will immediately break when you use a cross-compiler for a big-endian architecture.

It's implementation-defined, but not undefined. That particular file only runs on little-endian machines, so I think `memcpy` is fine here.

> How is performance of any relevance for incorrect code?

Performance is generally relevant for performance-sensitive code...

Yes, code that exhibits UB is incorrect and should be fixed. However, there is a wide gap between UB and actually miscompiled in practice by _today's_ compilers. It is highly unlikely that existing benchmarks with today's compilers were miscompiled. (As @bernd-edlinger notes, the compiler may have a hard time deducing this UB.) That doesn't mean we shouldn't fix it, but it means those benchmarks are a valid baseline for this code's performance.

If the fix generates poor code in practice, we'll have regressed performance. That doesn't mean we shouldn't fix it, but that we should look for a well-defined fix that also meets the performance goals. For example, see below for a compiler where the byte-by-byte version is _not_ ideal.

Now, I would hope that any compiler worth its salt is able to optimize `memcpy` away, so _hopefully_ the fix is fine. But that should still be confirmed. (After all, this code is performance-sensitive enough that OpenSSL chose to accept optimizations that only run on very very new hardware!)

> as that would suggest the memory would be aligned

Not only would suggest, but would require it. IIRC, it is UB in C to construct a misaligned pointer. (Not just use, it's UB as early as casting, unlike strict aliasing which cares about use.)

FWIW, load/store helper functions we use in BoringSSL. We have a suite of internal `CRYPTO_{load,store}_u{N}_{be,le}` functions that we use when, to borrow terms from Rust, transmuting memory. This comes up surprisingly often, so they're definitely worth the abstraction. Also it's just far more readable. Except...

> You can also define load/store functions without using memcpy, which I generally prefer:

I used `memcpy` for BoringSSL's. We do have the luxury of only supporting standard little-endian, two's complement platforms, but sadly the byte-by-byte strategy is a little problematic in practice: MSVC is really bad at compiling it. See the godbolt output here:
https://godbolt.org/z/xEP7xWrhz

This is really irritating because byte-by-byte would be a nice way to be endian-independent. ☹️ That said, your example isn't quite right...

> `a[0] | (a[1] << 8) | (a[2] << 16) | (a[3] << 24);`

Be careful! This is actually UB and doesn't even work at all for `load64`. You're relying on integer promotion for `a[3] << 24` to act on `int` rather than `unsigned char`, and then on the fact that `int` is 32-bit. But even that doesn't work because `int` is signed and it is UB to left-shift into the sign bit. (This language is terrible.) Happily, UBSan catches that one.

```
% cat broken-load32.c
#include <stdint.h>

uint32_t broken_load32le(const void *p) {
  const unsigned char *a = (const unsigned char *)p;
  return a[0] | (a[1] << 8) | (a[2] << 16) | (a[3] << 24);
}

int main() {
  unsigned char buf[4] = {0xff, 0xff, 0xff, 0xff};
  broken_load32le(buf);
}
% clang -fsanitize=undefined broken-load32.c  
% ./a.out 
broken-load32.c:5:52: runtime error: left shift of 255 by 24 places cannot be represented in type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior broken-load32.c:5:52 in 
```

You need to cast each element to `uint32_t` first.

**Comment by manxorist** [comment]
> That said, your example isn't quite right...
> 
> > `a[0] | (a[1] << 8) | (a[2] << 16) | (a[3] << 24);`
> 
> Be careful! This is actually UB and doesn't even work at all for `load64`. You're relying on integer promotion for `a[3] << 24` to act on `int` rather than `unsigned char`, and then on the fact that `int` is 32-bit. But even that doesn't work because `int` is signed and it is UB to left-shift into the sign bit.
[..]
> You need to cast each element to `uint32_t` first.

Oops, sorry for missing that. You are absolutely right of course.
