### ISSUE TITLE
ossl_ecx_key_op not able to access in openssl3.0 Engine

### ISSUE THREAD

**Issue by naghaabirami** [openssl/openssl#19580]
From QAT Engine we are accessing OpenSSL's default implementation incase of synchronous request. From openssl 3.0 in ossl_ecx_key_op function always below condition is satisfied and hence key generation is failing.

```
openssl/crypto/ec/ecx_backend.c:
        if (p == NULL || id == EVP_PKEY_NONE || plen != KEYLENID(id)) {
            ERR_raise(ERR_LIB_EC, EC_R_INVALID_ENCODING);
            return 0;
        }
```

**Comment by mattcaswell** [comment]
Your question doesn't really give us enough context to work on. I don't understand what you are trying to do here.  Please expand your question to give us some more background.

**Comment by naghaabirami** [comment]
We have compiled qat engine against openssl3.0 and trying to run ecx operation in sync mode.
In sync mode we trying to call "pkey_ecx_keygen" openssl API for key generation.
Inside pkey_ecx_keygen function "ossl_ecx_key_op" API is called.
In ossl_ecx_key_op function, always "if (op != KEY_OP_KEYGEN)" conditions is true and entering inside and failing at below if condition.

"if (p == NULL || id == EVP_PKEY_NONE || plen != KEYLENID(id))".

Debugged and checked always input parameter 'p' is NULL.

**Comment by slontis** [comment]
@mattcaswell I dont understand this code, but this call is either wrong, or the way the call is handled is not right?
````
static int pkey_ecx_keygen(EVP_PKEY_CTX *ctx, EVP_PKEY *pkey)
{
    ECX_KEY *ecx = ossl_ecx_key_op(NULL, NULL, 0, ctx->pmeth->pkey_id,
                                   KEY_OP_PUBLIC, NULL, NULL);
    ....
}
````

i.e. This call will hit the point shown above..

**Comment by ShuaiYuan21** [comment]
Hi @slontis and @mattcaswell 

The parameter _ecx_key_op_t_ in **ossl_ecx_key_op()** may not be correct in OpenSSL 3, it should be _KEY_OP_KEYGEN_ instead of _KEY_OP_PUBLIC_, because this function is used for key generation and it is also _KEY_OP_KEYGEN_ in openssl1.1.1. This issue can be solved after the change. I have submitted a PR for this #20680, please review it. Thanks!

KEY_OP_KEYGEN
https://github.com/openssl/openssl/blob/836080a89a1f5e45dac4e0df76b9270587f65d5b/crypto/ec/ecx_meth.c#L714
```C
static int pkey_ecx_keygen(EVP_PKEY_CTX *ctx, EVP_PKEY *pkey)
{
    ECX_KEY *ecx = ossl_ecx_key_op(NULL, NULL, 0, ctx->pmeth->pkey_id,
                                   KEY_OP_PUBLIC, NULL, NULL);

    ....
}
```
