### ISSUE TITLE
VC++ Run-Time Library conflict between OpenSSL 1.1.0 and zlib 1.2.8 with "no-shared" and "zlib" options

### ISSUE THREAD

**Issue by 23W** [openssl/openssl#1960]
Zlib library in static variant (project zlibstat.vcxproj) for VC++ (Windows x86 and x64) platform is compiled with /MD (/MDd) flag: 
> Causes your application to use the multithread- and **DLL-specific version** of the run-time library. 

But OpenSSL 1.1.0 in static variant (using "zlib" and "no-shared" options) use /MT for its libs:
> Causes your application to use the multithread, **static version** of the run-time library.

In such situations linker builds libs with error "Run-Time Library conflict"

P.S.: Small addition, as MS recommends all static projects have to use the **dynamic DLL VC++ CRT**. Because it's good solution for bug fixing in CRT without recompiling whole project which depends from it.

**Comment by 23W** [comment]
For example, curl project uses dynamic VC++ CRT in static build mode and support additional for switch to static CRT (RTLIBCFG=static). Main reason why they use dynamic CRT is:
> The CRT DLLs are updated by Microsoft Update for security and stability.

Please read **Static linking of Microsoft's C RunTime (CRT)** section in [BUILD.WINDOWS.txt](https://github.com/curl/curl/blob/master/winbuild/BUILD.WINDOWS.txt)

**Comment by dot-asm** [comment]
Well, linking statically does have advantage: you don't have to rely on or provide the VC redistributable. But it should be noted that OpenSSL static libraries themselves can be linked with *either* option. In other words it's decided when application is linked. So that if developer who chooses to use OpenSSL static libraries decides to link hist application with /MD, it's not actually a problem. And I'd argue that any static library should let user decide. It's achieved by compiling code that goes to library with /MT /Zl. Magic is not /Zl, bit combination. For example library code compiled with /MD /Zl still can be linked only with dynamic VC++ CRT, while code compiled with /MT /Zl can be linked with *either*.

**Comment by 23W** [comment]
I disagree with you, OpenSSL library is not independent module, but only component for many other apps. In Windows Platform most of them use VC++ CRT in dynamic linkage, so using static library with static CRT linkage does not have any advantages.
Only `OpenSSL.exe` application may have some advantage from using static CRT and this is very questionable advantage

**Comment by dot-asm** [comment]
What is outcome of OpenSSL "static" build? It's pair of .lib files and openssl.exe. Once again, .lib files [that are meant to be component for other applications, as absolutely correctly noted] *can* be linked with *either* option. If you want to compile and link *your* application code with /MD and link with OpenSSL static .lib-raries, you can do that. If you want to compile and link *your* application with /MT, you can do that too. It's developer's choice. If concern is that such arrangement threatens security by inhibiting you from using update-able VC CRT DLLs in case you choose to compile and link your application with /MD, then it's ungrounded concern. If you choose to link your application with /MD, OpenSSL object code that comes from static .lib-raries will use very same CRT DLL too. Because the "decision" is taken the moment you link your application, not when object code for OpenSSL .lib-raries is compiled.

As for openssl.exe itself being linked with static CRT. It's conscious choice that makes binary seamlessly movable between systems. Naturally because it doesn't contain references to components that are not guaranteed to present on arbitrary chosen system. As for possible security implications for openssl.exe itself. We make no guarantees about its suitability as Internet-facing application, which allows us to prioritize binary "mobility". openssl.exe is sometimes referred to as swiss-army-knife application. Would you appreciate if your ability to use your Swiss Army knife was conditional?

**Comment by 23W** [comment]
Ok, may be I did not understand the documentation for building static openssl libs with dynamic VC++ CRT. How to do this?
Now after `perl Configure VC-WIN32 no-asm no-gost no-shared zlib --with-zlib-include=%zlibInclude_path% --with-zlib-lib=%zlibLib% --prefix=%MY_PATH%`, I received the `makefile` with build options like `LIB_CFLAGS=/Zi /Fdossl_static **/MT** /Zl `.
How to force it to the **/MD** ?

**Comment by dot-asm** [comment]
What I was saying all along is that we don't/refuse to enforce anything in static OpenSSL libs. Once again, it's choice *you* make when you link *your* application, by means specific to *your* environment. For this reason there can't be documentation for "building static OpenSSL libraries with dynamic VC++ CRT". OpenSSL build configured with `no-shared` is *agnostic* to application link flags.

If question is how to modify generated makefile so that openssl.exe, *our* application, is linked with dynamic VC CRT, then you can modify BIN_CFLAGS.

**Comment by 23W** [comment]
Ok, I'll try to ask simple question.
I use `libcrypto.lib` and `libssl.lib` (OpenSSL library) in my application. I use it together with `zlibstat.lib` (Zlib library) and `libcurl.lib` (CURL library). All of them are built in static form (`lib` file without `dll` module). And all of them uses VC++ CRT (of course as and main application) in dynamic form (should be built with /MD flag).
So, How to build `libcrypto.lib` and `libssl.lib` libraries in static form and with dynamic VC++ CRT (/MD flag)?

**Comment by dot-asm** [comment]
Unfortunately I can't think of wording that doesn't start with "as already said" or "once again"... So as already said, once again. Configure with no-shared and *just link* with your application (why haven't you tried?). To work around problem with linking openssl.exe itself (as I understand that's what original problem was) adjust BIN_CFLAGS in generated makefile. Since I argue that it would be more appropriate if zlib was compiled in similar way that permits linking with either flag, I'm reluctant to change current default way (static) openssl.exe is linked.

**Comment by 23W** [comment]
@dot-asm 
> Configure with no-shared and just link with your application (why haven't you tried?). 

It works. But, this configuration build the libs with static CRT and I want dynamic. :)

>  To work around problem with linking openssl.exe itself (as I understand that's what original problem was) adjust BIN_CFLAGS in generated makefile.

I to do the same, fixing the `makefile` file after `Configure` manually. But my project is built in automatic mode (night building), and of course 'hand work' is not good solution.

> I'm **reluctant to change** current default way (static) openssl.exe is linked.

I ask you to add new flag for processing which type of CRT should be used at compiling time: /MD(d) or /MT(d). Then such errors will be avoided. Customer can decide themselves what is it wants.  The "Default" way can stays as now. This is my proposition. 

Thank you again.

**Comment by dot-asm** [comment]
> >    Configure with no-shared and just link with your application (why haven't you tried?).
>
> It works. But, this configuration build the libs with static CRT and I want dynamic. :)

**ONCE AGAIN**, **AS ALREADY SAID**, `cl /MT yourapp.c libcrypto.lib` -> static CRT, `cl /MD yourapp.c libcrypto.lib` -> dynamic CRT. This is **WITH SAME LIBCRYPTO.LIB** [naturally provided that it's configured with no-shared]. You get dynamic if you do it right.

> 'hand work' is not good solution.

`nmake libcrypto.lib libssl.lib` and/or `set _CL_=/MD`.

**Comment by 23W** [comment]
> set _CL_=/MD
Thank you

**Comment by 23W** [comment]
After the last your comment I finally rechecked my building scripts (from night builds) and found error in them! Mixing CRT types was in them.
Greater thank you and I am sorry for your time that you lost with me :(
