### ISSUE TITLE
Upgrade to 1.1.1s issue

### ISSUE THREAD

**Issue by conmank3** [openssl/openssl#19659]
Hello, 

I apologize if this is my ignorance for I am fairly new to all things Linux and openssl. 
I recently upgraded openssl 1.1.1k to 1.1.1s on Rocky Linux 8.6 and now cannot sudo. 
I am receiving the following errors: 
sudo: error in /etc/sudo.conf, line 19 while loading plugin "sudoers_policy"
sudo: unable to load /usr/libexec/sudo/sudoers.so: /lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b
sudo: fatal error, unable to load plugins

Any advice would be appreciated. 

Thank you!

**Comment by t8m** [comment]
You usually cannot replace the system OpenSSL libraries that are shipped by the OS vendor with your own build of upstream packages because OS vendors usually patch multiple things in the system packages. Instead you have to rely on the OS vendor to provide up-to-date packages in regards to any security fixes needed. Many vendors also apply security fixes on top of older OpenSSL releases so the older version number of the OS package does not necessarily mean it is vulnerable.

The fix is to reinstall the openssl package as shipped by the OS.

**Comment by conmank3** [comment]
Much appreciated on the reply I went ahead and rolled it back. Thank you again!

**Comment by GuppyGhost** [comment]
The problem is that PCI compliance requires openssl >= 1.1.1p.

So, rolling back to openssl 1.1.1.k isn't an option (if you're site does credit card processing).

**Comment by zztaki** [comment]
> Much appreciated on the reply I went ahead and rolled it back. Thank you again!

Hello, can I ask how you solved it? Thank you very much!
