### ISSUE TITLE
Inconsistent behaviour of BN_add_word()

### ISSUE THREAD

**Issue by ttc0419** [openssl/openssl#19745]
I used ```BN_add_word()``` to increment a 12 bytes memory, however, the result is not consistent.

**Code:**
```c
#include <stdio.h>
#include <string.h>
#include <openssl/evp.h>

static void increment_nonce(unsigned char *const restrict nonce)
{
	BIGNUM *bn_nonce = BN_bin2bn(nonce, 12, NULL);
	BN_add_word(bn_nonce, 2);
	BN_bn2bin(bn_nonce, nonce);
	puts(BN_bn2dec(bn_nonce));
	BN_free(bn_nonce);
}

int main(int argc, const char *argv[])
{
	unsigned char nonce[12];
	memset(nonce, 0, 12);

	for (int i = 0; i < 4; ++i) {
		increment_nonce(nonce);

		for (size_t j = 0; j < 12; ++j)
			printf("%u ", nonce[j]);
		putchar('\n');
		putchar('\n');
	}

	return 0;
}
```

**Output:**
```
2
2 0 0 0 0 0 0 0 0 0 0 0 

618970019642690137449562114
2 0 0 0 0 0 0 0 0 0 0 2 

618970019642690137449562116
2 0 0 0 0 0 0 0 0 0 0 4 

618970019642690137449562118
2 0 0 0 0 0 0 0 0 0 0 6 
```

**Questions:**
Why the function increment the last byte of the memory from the second iteration onwards?
How to do it properly?
Is the function the same as [sodium_increment](https://github.com/jedisct1/libsodium/blob/6e8468d8750aecf91593f28a9d373bb9a5fe326e/src/libsodium/sodium/utils.c#L269)?

**Comment by t8m** [comment]
The BN_bin2bn and BN_bn2bin expect big endian representation of the big number in the memory. And, BN_bn2bin outputs the minimum number of bytes needed to represent the number. So in the first cycle the BN_bin2bn sees 12 byte zero bignum value however BN_bn2bin it outputs just the first byte with the value 2 because that is the shortest representation. However in the second cycle the BN_bn2bin now sees 12 byte bignum value with the value of 0x020000000000000000000000 which is then incremented by 2 to make 0x020000000000000000000002.

If you need little endian value in the nonce with a fixed size use BN_lebin2bn and BN_bn2lebinpad.

**Comment by t8m** [comment]
And of course this is not particularly efficient because the bin2bn conversion routines allocate memory for the new bignum if used with NULL bn parameter.

**Comment by davidben** [comment]
If you're just trying to do a counter-based fixed-width nonce, however, `BIGNUM` is probably not the thing to use in the first place. Think about whether it's actually possible to overflow beyond, say, a `uint64_t` in whatever protocol you're using.

**Comment by ttc0419** [comment]
Thanks for the suggestions.
