### ISSUE TITLE
EVP_PKEY_decrypt (RSA) does not check output buffer size properly

### ISSUE THREAD

**Issue by Hlipa** [openssl/openssl#19790]
When I tried to use EVP_PKEY_decrypt() and use original buffer size as a outlen I got following error:

`stderr| 00000001:error:1C80008E:Provider routines:rsa_decrypt:bad length:../../openssl-3.0.5/providers/implementations/asymciphers/rsa_enc.c:225:`

I see problem here on condition 222:
```
198      size_t len = RSA_size(prsactx->rsa);
...
222          if (outsize < len) {
223              ERR_raise(ERR_LIB_PROV, PROV_R_BAD_LENGTH);
224              return 0;
225          }
```

It does not care about real size of decrypted data and expect that output size always will be modulo size which is not true.

**Comment by t8m** [comment]
The code is correct. We cannot know how big the decrypted size would be and it can be up to RSA_size() (depending on the padding).

**Comment by Hlipa** [comment]
From my point of view it is not expected behavior. At least some PKCS11 implementation returns modulo size, when out buffer is NULL and somebody ask for the length. But when out buffer is passed then implementation tries decrypt and if buffer is not big enough, it returns exact size.

**Comment by t8m** [comment]
> From my point of view it is not expected behavior.

Could be and we can possibly improve the manual page to make it clear what the current behavior is.

However I do not think we can change the implementation as that would not allow decrypting in place. It would also possibly provide a timing side channel so that is another reason why this would be a bad idea.

The current API contract definitely allows for proper usage and I do not see any serious deficiencies with it.

**Comment by Hlipa** [comment]
Improving manual page would be perfect. Thanks
