### ISSUE TITLE
ec sign and verify example on manual page

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#19829]
Manual page ECDSA_SIG_new describes low-level elliptic curve digital signature algorithm (ECDSA) functions. Low-level are depecated in 3.0.

Issues:
 - examples are based on deprecated ECDSA_sign and ECDSA_verify;
 - search engine usually point to these pages.

What about to mark these samples as "historic" and first to refer to more up do date examples?

**Comment by petrovr** [comment]
P.S. Reference to EVP_Digest{Sign|Verify}Init is "hidden", i.e. is easy reader to miss this part. So may be is better to remove esamples.

**Comment by mattcaswell** [comment]
Rather than deleting the examples I'd prefer to split the man page into two, i.e. one to document the ECDSA_SIG_* functions which are not deprecated, and one to document the remaining deprecated functions. Hopefully then it should be clear that all the functions, including the examples, on the second page are deprecated.
