### ISSUE TITLE
[question]TLS netconf callhome established, and send a lot of configurations, then TLSv1.2 Encrypted Alert

### ISSUE THREAD

**Issue by adamzyg** [openssl/openssl#19894]
version: openssl-1.1.1k
Hi,
I encountered a strange problem. After the TLS netconf callhome connection was successful and a lot of configuration data was sent, the callhome client suddenly reported an Encrypted Alert, and then the callhome disconnected. According to the TLSv1.2 protocol, after the handshake is successful, the two parties will negotiate a symmetric encryption algorithm to send data. Why does the Encrypted Alert suddenly appear?
The attachment is the pcap package I captured, can you help me analyze it?
[test1.zip](https://github.com/openssl/openssl/files/10216181/test1.zip)

**Comment by mattcaswell** [comment]
I can only comment on TLS itself - I am not familiar with netconf callhome.

There's not much that can be said about the Encrypted alert because it's encrypted! It could be a fatal alert of some form, or it could also be an orderly shutdown via a "close_notify" alert. It is interesting that I see a couple of cases in the pcap of an alert going the other way (i.e. server to client) - but presumably these are warning alerts only because communication continues after these alerts are sent.

In order to understand what this alert is better you would need to see if either the server or the client provides any logs about this alert. Alternatively you could use something like wireshark's capability to decrypt TLS traffic when given the appropriate secrets to decrypt the encrypted alert and find out what it is.

https://wiki.wireshark.org/TLS

**Comment by Jr-produciones1000** [comment]
saludos https://youtu.be/jyP80scCDBo

**Comment by Jr-produciones1000** [comment]
[suscribete ](https://youtu.be/jyP80scCDBo)``

**Comment by Jr-produciones1000** [comment]
> [suscribete ](https://youtu.be/jyP80scCDBo)
