### ISSUE TITLE
SSL_ERROR_NO_CYPHER_OVERLAP in Firefox

### ISSUE THREAD

**Issue by noelmario7** [openssl/openssl#2006]
**Issue**:
We are facing the SSL_ERROR_NO_CYPHER_OVERLAP issue in Firefox, due to which our application is inaccessible. Please refer the below screenshot.

![image](https://cloud.githubusercontent.com/assets/11534701/20615899/d41b9e46-b303-11e6-8b40-2db3e034f5c7.png)

**Technical Details**:
WebServer : Webmin 1.8
ssl_cipher_list=ALL:!SHA1:!RC4:!LOW:!MEDIUM:!SSLv2:!SSLv3:+HIGH
Operating System: CentOS 6.8
Firefox verision: 50
OpenSSL details:
Arch        : x86_64
Version     : 1.0.1e
Release     : 48.el6_8.3

**Analysis**:
1. The application is inaccessible when the above mentioned SSL cipher list is implemented
2. If one enables SSLv3, then the application is accessible
3. This suggests either the WebServer or OpenSSL is unable to support the given cipher list

**Queries**:
1. Does one need to upgrade OpenSSL to latest?(We  tried to do it, but found that latest OpenSSL 1.1.0 is unavailable for CentOS 6.8)
2. Are we missing something in the configuration?

**Comment by mattcaswell** [comment]
A default Firefox ClientHello sends the following ciphers:
````
        {0xC0, 0x2B} TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        {0xC0, 0x2F} TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        {0xCC, 0xA9} TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        {0xCC, 0xA8} TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        {0xC0, 0x2C} TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        {0xC0, 0x30} TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        {0xC0, 0x0A} TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
        {0xC0, 0x09} TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
        {0xC0, 0x13} TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
        {0xC0, 0x14} TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
        {0x00, 0x33} TLS_DHE_RSA_WITH_AES_128_CBC_SHA
        {0x00, 0x39} TLS_DHE_RSA_WITH_AES_256_CBC_SHA
        {0x00, 0x2F} TLS_RSA_WITH_AES_128_CBC_SHA
        {0x00, 0x35} TLS_RSA_WITH_AES_256_CBC_SHA
        {0x00, 0x0A} SSL_RSA_WITH_3DES_EDE_CBC_SHA
````

Your cipher list is:
````
ALL:!SHA1:!RC4:!LOW:!MEDIUM:!SSLv2:!SSLv3:+HIGH
````
This probably isn't doing what you think it is doing. In particular the "!SSLv3" does not disable the SSLv3 protocol. It disables all ciphersuites which are defined to work in SSLv3. All of those ciphersuites also work in TLSv1.0, TLSv1.1 and TLSv1.2. The "!SHA1" term does effectively the same thing since all of those ciphersuites also use SHA1. That effectively means you only allow ciphersuites defined for TLSv1.2. OpenSSL 1.0.1 does not support CHACHA20 based ciphersuites. You will further restrict your choice of ciphersuites based on the certificate type you have. Assuming it is an RSA cert, then that means the remaining overlapping ciphersuites are these:

````
        {0xC0, 0x2F} TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        {0xC0, 0x30} TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
````

In OpenSSL 1.0.1 you must explicitly configure ECDHE based ciphersuites by making a call to `SSL_CTX_set_tmp_ecdh()` (in OpenSSL 1.1.0 this is not necessary). If you haven't explicitly configured them then ECDHE will also not be available to you and you will get the "no cipher overlap" problem.

As well as the above problems your cipher list is insecure. You have used "ALL" (which obviously switches everything on) but have not taken care to remove all insecure ciphers. Specifically all the NULL authentication ciphers are still switched on. You can review the effect of your ciphersuite selection using the command `openssl ciphers -v ALL:!SHA1:!RC4:!LOW:!MEDIUM:!SSLv2:!SSLv3:+HIGH` (this will still show all the ECDHE/DHE ciphersuites which your application must configure explicitly to really get.)

**Comment by vdukhovni** [comment]
> ALL:!SHA1:!RC4:!LOW:!MEDIUM:!SSLv2:!SSLv3:+HIGH

Also the "+HIGH" looks like a blunder.  This moves "HIGH" ciphers to the *end* of the list.  If you had any non-HIGH ciphers they'd be preferred over the HIGH ones.  Since you don't disable EXPORT ciphers, only LOW and MEDIUM, if your 1.0.1 build supports EXPORT ciphers, then those are preferred over HIGH!  Many builds now have EXPORT disabled, so perhaps "+HIGH" is a NOOP, but still you should delete that bit from the cipherlist.

A much better cipherlist for your apparent intent is:

   DEFAULT:!SSLv2:!RC4:!EXPORT:!LOW:!MEDIUM:!SHA1

although that final "!SHA1" could lead to significant interoperability issues with any legacy clients.  As mentioned by @mattcaswell , the SSLv3 protocol is disabled by other means, not via the cipherstring.

**Comment by noelmario7** [comment]
Thanks @mattcaswell and @vdukhovni  for your detailed inputs. Truly appreciate your help.
As per your solution, we have explicitly disabled the protocols via different configuration mechanism, and the application is now accessible.

The webserver automatically derived a new cipher list given below. The intent is to disable weak ciphers such as RC4.

`EECDH+AES:EDH+AES:-SHA1:EECDH+AES256:EDH+AES256:AES256-SHA:!aNULL:!eNULL:!EXP:!LOW:!MD5:!RC4:!MEDIUM`

Hope the above is correct.
