### ISSUE TITLE
Potentially incomplete checks for EVP_CIPHER_asn1_to_param

### ISSUE THREAD

**Issue by nielsdos** [openssl/openssl#20116]
Hello.

I'm working on a static analysis tool to detect missing and incorrect error checking. It works by inferring an error specification for error-returning functions and later it verifies whether checks adhere to the specification.

The following 2 pieces of code check for an error return value of `EVP_CIPHER_asn1_to_param`:
https://github.com/openssl/openssl/blob/61222b95ff20f6a7bb20668e43b657561efdb922/crypto/evp/p5_crpt2.c#L162
https://github.com/openssl/openssl/blob/c3aed7e4e6f1960eaa43ecbea2178b82481887af/crypto/pkcs7/pk7_doit.c#L592

The documentation of EVP_CIPHER_asn1_to_param says however:
> EVP_CIPHER_asn1_to_param() return greater than zero for success and zero or a negative number on failure.

So it seems to me that `EVP_CIPHER_asn1_to_param` can also return 0 on failure. This is not handled by the above 2 checks. This is what my tool reported to me.

All other users of EVP_CIPHER_asn1_to_param do check using `<= 0` instead of `< 0` though.

I was wondering whether this is a real bug. If it is I could create a PR that changes the checks to `<= 0`.

Thanks in advance!

**Comment by mattcaswell** [comment]
Yes. This does look like a bug. A PR would be very welcome.

**Comment by nielsdos** [comment]
Thank you for confirming.

I'm not very familiar with OpenSSL's codebase.
If I fix it in pk7_doit.c, all tests still pass.
However, if I fix it in p5_crpt2.c, tests start failing, for example:

```
80-test_pkcs12.t ........................ 
        # INFO:  @ test/helpers/pkcs12.c:426
        # Adding key
        # ERROR: (ptr) 'bag != NULL' failed @ test/helpers/pkcs12.c:439
        # 0x0
        # 4017FEAF857F0000:error:0300007A:digital envelope routines:evp_cipher_asn1_to_param_ex:cipher parameter error:crypto/evp/evp_lib.c:236:
        # 4017FEAF857F0000:error:0300007A:digital envelope routines:PKCS5_v2_PBE_keyivgen_ex:cipher parameter error:crypto/evp/p5_crpt2.c:163:
        # 4017FEAF857F0000:error:11800067:PKCS12 routines:PKCS12_item_i2d_encrypt_ex:encrypt error:crypto/pkcs12/p12_decr.c:191:
        # 4017FEAF857F0000:error:11800067:PKCS12 routines:PKCS8_set0_pbe_ex:encrypt error:crypto/pkcs12/p12_p8e.c:80:
        # OPENSSL_TEST_RAND_ORDER=1674493616
        not ok 5 - iteration 5
```

I'm guessing it is related to the ERR_raise which is in p5_crpt2.c but not in pk7_doit.c.
Should this ERR_raise only be done if the return value <0, or am I making a mistake here?
Thanks in advance

**Comment by mattcaswell** [comment]
There appears to be another bug here. `EVP_CIPHER_asn1_to_param` calls `evp_cipher_asn1_to_param_ex` internally. That function returns greater than 0 for success, or <= 0 for failure (as per `EVP_CIPHER_asn1_to_param`). However it calls `EVP_CIPHER_get_asn1_iv` in some circumstances and the return value from that function is just propagated. However `EVP_CIPHER_get_asn1_iv` returns <0 on failure or the length of the IV otherwise (and 0 is a valid IV length). This is then misinterpreted by `evp_cipher_asn1_to_param_ex` which treats it as an error (calls `ERR_raise`).

The call to `EVP_CIPHER_asn1_to_param` in p5_crpt2.c seems to treat a 0 return as a success (even though an err has been raised) and then goes on to do the right thing. This is why the test cases work - but it is definitely wrong because there is now a spurious error on the error stack.

Probably `evp_cipher_asn1_to_param_ex` should be checking the return value from `EVP_CIPHER_get_asn1_iv` and, if it is 0, it should return a positive value back up the call chain to indicate a success.

**Comment by nielsdos** [comment]
Thanks for clarifying, by hadling the EVP_CIPHER_get_asn1_iv case it works now.

**Comment by bernd-edlinger** [comment]
> Thank you for confirming.
> 
> I'm not very familiar with OpenSSL's codebase. If I fix it in pk7_doit.c, all tests still pass. However, if I fix it in p5_crpt2.c, tests start failing, for example:
> 
> ```
> 80-test_pkcs12.t ........................ 
>         # INFO:  @ test/helpers/pkcs12.c:426
>         # Adding key
>         # ERROR: (ptr) 'bag != NULL' failed @ test/helpers/pkcs12.c:439
>         # 0x0
>         # 4017FEAF857F0000:error:0300007A:digital envelope routines:evp_cipher_asn1_to_param_ex:cipher parameter error:crypto/evp/evp_lib.c:236:
>         # 4017FEAF857F0000:error:0300007A:digital envelope routines:PKCS5_v2_PBE_keyivgen_ex:cipher parameter error:crypto/evp/p5_crpt2.c:163:
>         # 4017FEAF857F0000:error:11800067:PKCS12 routines:PKCS12_item_i2d_encrypt_ex:encrypt error:crypto/pkcs12/p12_decr.c:191:
>         # 4017FEAF857F0000:error:11800067:PKCS12 routines:PKCS8_set0_pbe_ex:encrypt error:crypto/pkcs12/p12_p8e.c:80:
>         # OPENSSL_TEST_RAND_ORDER=1674493616
>         not ok 5 - iteration 5
> ```
> 
> I'm guessing it is related to the ERR_raise which is in p5_crpt2.c but not in pk7_doit.c. Should this ERR_raise only be done if the return value <0, or am I making a mistake here? Thanks in advance

The original failure here was only due to the RC4 cipher which does not need any IV.
But the fix to ignore missing IV on any other cipher is probably wrong.

See #31676
