### ISSUE TITLE
PSK mode without DHE never reached

### ISSUE THREAD

**Issue by geovandro** [openssl/openssl#20129]
I have been testing openssl in PSK mode (psk_client_callback and psk_server_callback) and wanted to avoid to perform DH since I use a fresh new PSK key for each session. 
Even though I have the flag SSL_OP_ALLOW_NO_DHE_KEX set in my ctx options, the server is still performing the DH key generation. 

After some inspection, I noticed that the client sends both TLSEXT_KEX_MODE_KE_DHE and TLSEXT_KEX_MODE_KE even when the SSL_OP_ALLOW_NO_DHE_KEX flag is set (see line below):
https://github.com/openssl/openssl/blob/e95d6e1eec2f080713aa91c12e411cea4cffee65/ssl/statem/extensions_clnt.c#L585 

Isn't it the case that line below (on the server side) should be like
if (s->hit && (s->ext.psk_kex_mode & TLSEXT_KEX_MODE_FLAG_KE) != 0)
in order to skip DHE:
https://github.com/openssl/openssl/blob/e95d6e1eec2f080713aa91c12e411cea4cffee65/ssl/statem/extensions_srvr.c#L586

**Comment by t8m** [comment]
@mattcaswell can probably explain

**Comment by nhorman** [comment]
@mattcaswell , can you comment here please?

**Comment by nhorman** [comment]
@mattcaswell ping

**Comment by nhorman** [comment]
@mattcaswell ping

**Comment by mattcaswell** [comment]
Sorry - somehow I missed all the numerous previous pings on this!!

The option `SSL_OP_ALLOW_NO_DHE_KEX` has the effect of **allowing** key exchange without DH but it does not cause a preference for this. So, for example, if a server sets `SSL_OP_ALLOW_NO_DHE_KEX` and a client only sends `TLSEXT_KEX_MODE_KE` (but not `TLSEXT_KEX_MODE_KE_DHE`) then the key exchange will succeed. On the client side setting this option causes `TLSEXT_KEX_MODE_KE` to be sent as an allowed key exchange mode but does not cause any preference for it. This was a deliberate design decision made at the time TLSv1.3 was first implemented. The purpose of the option is to allow an OpenSSL endpoint to interoperate with an endpoint that does not support `TLSEXT_KEX_MODE_KE_DHE`. An OpenSSL client talking to an OpenSSL server would always use `TLSEXT_KEX_MODE_KE_DHE` in preference, regardless of `SSL_OP_ALLOW_NO_DHE_KEX`.

Since the original TLSv1.3 implementation we have subsequently added a new option in OpenSSL 3.3: `SSL_OP_PREFER_NO_DHE_KEX`. This is ignored on the client, but causes a server to prefer `TLSEXT_KEX_MODE_KE` over `TLSEXT_KEX_MODE_KE_DHE`. It must always be used in conjuction with `SSL_OP_ALLOW_NO_DHE_KEX`.

See the docs here:

https://www.openssl.org/docs/man3.3/man3/SSL_CTX_set_options.html

**Comment by geovandro** [comment]
Thanks for the clarification and for letting me know about the new SSL_OP_PREFER_NO_DHE_KEX option. I'm closing the issue.
