### ISSUE TITLE
solaris-sparcv9-cc no-asm: BN_sqr() bug

### ISSUE THREAD

**Issue by c-bb** [openssl/openssl#2012]
On the `solaris-sparcv9-cc` platform, when configuring the build with `no-asm`, the openssl test suite fails its `BN_sqr()` tests in `test/bntest.c`.

This happens in 1.0.2j but not 1.0.1u.

To reproduce:

```
$ ./Configure solaris-sparcv9-cc no-shared no-asm
$ make build_libs build_engines build_tests
$ test/bntest
```

(`no-shared` just to keep it simpler.)

This is with `CC` pointing at the native Solaris compiler (`cc -V` gives `cc: Sun C 5.12 SunOS_sparc Patch 148917-07 2013/10/18`).

The failure is:

```
test BN_sqr
print "test BN_sqr\n"
-FFFFF2F2F2 * -FFFFF2F2F2 - FFFFE5E5E4AA54166CC4
23A3A3A3A00FF * 23A3A3A3A00FF - 4F6275888BBF65523FF8CFE01
-800000000000000 * -800000000000000 - 400000000000000000000000000000
-393939FF2F2F00FFFF * -393939FF2F2F00FFFF - CCA889E83C992C26855D68B5FA2A1FE0001
B4340E0E0E0000FFFFFF * B4340E0E0E0000FFFFFF - 7ED93E597A2B3BB5F0DEB3B3E3E4E3FFFE000001
300E60000FF0000FFFF0000 * 300E60000FF0000FFFF0000 - 90564CEA9FBCA3A02C3FF35FDFE02FFFE000100000000
FFFFF3FFFFFFFBDFFB0B0B0FF * FFFFF3FFFFFFFBDFFB0B0B0FF - 110FFE5000D8FF6BE2629C5BB4BB8362C55FD4E8F5478FF9E01
Square test failed!
1
```

Using `git bisect`, I tracked it down to the following commit:

```
commit 49446ea62f34ed2986e7bd89431928e09bfb8709
Author: Andy Polyakov <appro@openssl.org>
Date:   Mon Jan 5 15:20:54 2015 +0100

    Fix for CVE-2014-3570 (with minor bn_asm.c revamp).

    Reviewed-by: Emilia Kasper <emilia@openssl.org>
    (cherry picked from commit 56df92efb6893abe323307939425957ce878c8f0)

 crypto/bn/asm/mips.pl      | 611 ++++++++++++++++++++++++++++---------------------------------------------------------------------------------------------------
 crypto/bn/asm/x86_64-gcc.c | 101 ++++++++++-----------
 crypto/bn/bn_asm.c         | 241 +++++++++++++++++++++++++-------------------------
 crypto/bn/bntest.c         | 102 +++++++++++++++++-----
 4 files changed, 379 insertions(+), 676 deletions(-)
```

I tried reverting that commit in 1.0.2j to double-check that it's the culprit, but that's not trivial as there are conflicts due to subsequent code formatting changes.

However, when starting with 1.0.2j and checking out `crypto/bn/bn_asm.c` and `crypto/bn/bntest.c` from the parent revision (`f33ab61`) of the bisected commit (`49446ea`), the entire test suite succeeds.

The test suite also succeeds when building without `no-asm`.

**Comment by dot-asm** [comment]
Trouble is that we don't have access to SPARC Solaris system so that I don't have possibility to reproduce the problem. It should be noted however that I can *not* reproduce the problem on SPARC Linux. Since the code and config for the two are shared it suggests that it's a compiler bug. Try this. With build completed, open top-most Makefile in text editor, locate -xO5 flag in CFLAG line, drop the optimization level to say -xO1 and save the changes. Then `rm crypto/bn/bn_asm.o` and re-run make and the test.

**Comment by c-bb** [comment]
Thanks for the quick response, @dot-asm.

I tried what you suggested, and it turns out you're right: with `-xO1`, the entire test suite passes. Very interesting! I'll try to narrow this down some more.

**Comment by c-bb** [comment]
@dot-asm: so the immediate workaround on my end is probably to drop the `no-asm` flag. Clearly, it has the added benefit of making openssl faster!

Before I go that way, I would appreciate some advice. Are there any known downsides to dropping `no-asm`? In particular, has the assembly code been known to break on certain CPUs, or does it consistently have all the right CPUID checks to ensure it does not feed the CPU any instructions it cannot understand? (The openssl I'm building will end up running on a variety of different SPARC Solaris computers, although none of them are super-ancient.)

**Comment by richsalz** [comment]
Sadly, some of the crypto is not constant-time.

**Comment by c-bb** [comment]
It turns out that `-xO3` works. But `-xO4` fails. This is with Sun compiler version 12.3.

I'm also told that with `-xO5`, it fails with 12.4 but is fixed in 12.5.

So it looks like a bug in a some optimizer pass that's effective in `-xO4` and above, and which is fixed in Sun Studio version 12.5 and above.

**Comment by dot-asm** [comment]
> Are there any known downsides to dropping no-asm?

It's unusual formulation in sense that you customarily *add* it, not omit. And most common reason for adding it is trouble-shooting, not production build. Absolute majority of assembly packs, SPARCv9 included, are designed to detect current processor capabilities and execute only code suitable for current processor. One can even add "most suitable", because if there are two code paths that can be executed, fastest one is chosen. So that same binary effectively adapts to current processor to provide optimal performance. And as @richsalz implied, omitting assembly support is likely to be bad for security. It's even argued that disabling assembly support is plain incompatible with security by todays standards, especially on contemporary processors.

As for compiler bugs. Even though we occasionally implemented workarounds for compiler bugs in source code in the past, we resist the temptation, increasingly with the time. I see no reason to seek workaround in this case.

It appears to me that case can be closed...

**Comment by c-bb** [comment]
Thanks a lot for the explanation @dot-asm, that's exactly what I'd hoped.

The only remaining doubt that I have here is whether this is really a compiler bug, or whether it could be the openssl code relying on undefined behaviour which most compilers handle in the "expected" way, but which `-xO4` and above take advantage of.

**Comment by dot-asm** [comment]
If it isn't a compiler bug, then how come it's fixed in later compiler release? :-) Well, it is a valid concern, but trouble is that drawing definitive conclusion is prohibitively expensive for us. Because from *our* side it would involve examining a lot of machine code to spot what compiler did "right" and if it was justified. In other words we can't really answer this question, compiler vendor is in much better position to do so. And since we can't really answer the question, we settle for indirect indications of compiler bug that served us well over the years, namely dropping optimization level that makes problem disappear, and problem being limited to particular release(s).

Above means that I did have another look at macros modified in referred commit and I don't see that they rely on "expected" behaviour.

**Comment by c-bb** [comment]
Thanks for your help, I really appreciate it.
