### ISSUE TITLE
 -DOPENSSLDIR="\"/xxx/ssl\"" -DENGINESDIR="\"/xxx/lib/engines-1.1\"

### ISSUE THREAD

**Issue by jinfeihan57** [openssl/openssl#20185]
When I cross-compiled openssl, I noticed that two macros appeared in the compilation option, 
-DOPENSSLDIR=""/xxx/ssl "" 
-ENGINE SDIR=""/xxx/lib/engines-1.1\“
”xxx“ is the installation directory I set, but my running environment does not have this directory. This directory only appears in the compilation environment. I don't know how the paths specified by these two macros will affect openssl. Does anyone know what happened?

**Comment by levitte** [comment]
That's a tricky one, and this is one place where we don't treat cross compilation particularly well, unfortunately.

To borrow the terminology from [GNU autoconf](https://www.gnu.org/software/autoconf/manual/autoconf-2.68/html_node/Specifying-Target-Triplets.html), the specified paths are normally expressed in build system terms, not host system terms.  We do have some configuration options to change those defaults, but since the also affect where `make install` tries to install the files, and we can't know if the installation is going to be performed on the build system or on the host system, it's a bit difficult to juggle what's used how.
It would be simple to say "just have the same file system setup on both the build and the host system", but that's not quite realistic in some cases...

There's no clear answer for the moment.  I'm not quite sure how other build systems make the difference for this sort of thing, maybe we can take inspiration that allows us to adapt our configuration options to deal with this discrepancy.

Sorry that I can't give you a clearer answer at this time.

**Comment by t8m** [comment]
Please note that the _installation should go into a different path than where the files are deployed_ is handled by the `DESTDIR` variable.

I.e. you configure the prefix of the build to point to the place where the files should be deployed on the target system but then you use `make install DESTDIR=/xxx` on the build system. This will install the files into /xxx/deployment-prefix/ssl etc. but the OPENSSLDIR and ENGINESDIR will use /deployment-prefix/ssl etc.

**Comment by t8m** [comment]
Yeah, it works if the crosscompilation is from POSIX (or posix-like) system to another one but once the difference between build and target systems are much larger, this probably won't work good enough.

**Comment by vszakats** [comment]
With cross-compilation, there is a known and unfixed bug where an `OPENSSLDIR` value with an absolute Windows path is rejected because the verification logic expects a absolute path conforming the host platform. On a cross-build run on Linux `C:/MyDir` is not absolute, thus rejected.

It means that the insecure `C:\Program Files\` default cannot be customized in cross-builds. Not without patching `./Configure` at least.

`make install DESTDIR=` will only fix the copy destination, not the `OPENSSLDIR` path embedded into the binaries.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
