### ISSUE TITLE
DSA_sign hangs with invalid parameters

### ISSUE THREAD

**Issue by guidovranken** [openssl/openssl#20268]
This hangs:

```c
#include <openssl/dsa.h>
#include <openssl/bn.h>
#include <openssl/err.h>
#include <string.h>

#define CF_CHECK_NE(expr, res) if ( (expr) == (res) ) { goto end; }

int main(int argc, char *argv[])
{
    DSA *dsa;
    BIGNUM *p, *q, *g, *priv_key, *pub_key;
    unsigned char *signature;
    const unsigned char msg[] = {0x00};
    unsigned int signature_len;

    p = BN_new();
    g = BN_new();
    q = BN_new();
    priv_key = BN_new();
    pub_key = BN_new();

    BN_dec2bn(&p, "26959946667150639794667015087019640346410327083120074548994958668279");
    BN_dec2bn(&q, "1");
    BN_dec2bn(&g, "11031159150393236145358169167399899033873710076688195872983140529812576");
    BN_dec2bn(&pub_key, "0");
    BN_dec2bn(&priv_key, "44072239980705620047479035580457605556085320000");

    dsa = DSA_new();
    CF_CHECK_NE(DSA_set0_pqg(dsa, p, q, g), 0);
    CF_CHECK_NE(DSA_set0_key(dsa, pub_key, priv_key), 0);

    signature = malloc(DSA_size(dsa));

    DSA_sign(0, msg, sizeof(msg), signature, &signature_len, dsa);

end:
    DSA_free(dsa);
    free(signature);

    return 0;
}
```

If I instruct my fuzzer to not call `DSA_sign` if these constraints are violated:

- P > Q
- Q > priv
- priv != 0

Then no hang occurs (as far as I can tell now).

So adding these checks in DSA_sign will presumably resolve the issue.

BoringSSL does not hang except when priv == 0. @davidben 

I can't test LibreSSL right now because the build is broken on Linux. @botovq

**Comment by davidben** [comment]
> BoringSSL does not hang except when priv == 0. @davidben

Hmm, I'm not able to repro this. To make sure I'm trying the right thing, this is if I use the test program, but replacing the `priv_key` line with `BN_dec2bn(&priv_key, "0");`?

**Comment by davidben** [comment]
Oh, it's not doing anything because we reject any q values that aren't exactly 160-, 224-, or 256-bit, as of https://boringssl-review.googlesource.com/c/boringssl/+/42504

If I adjust q to be in size and then put g in bounds, I can repro. Looking...

**Comment by davidben** [comment]
Fixes for BoringSSL:
* https://boringssl-review.googlesource.com/c/boringssl/+/57226
* https://boringssl-review.googlesource.com/c/boringssl/+/57227
* https://boringssl-review.googlesource.com/c/boringssl/+/57228

This reminded me that @hannob had reported something similar way back, but it slipped through, so that series also fixes that report. On the BoringSSL side, I think there were a few things going on:

First, we allowed the private key to be zero on import. Even though the "domain parameters" are valid, we still need to do this check because, as you found, zero private key + zero hash will never converge. So that series fixes that in our DSA and ECDSA implementations.

Second, there's deeper problem with how the DSA was specificied. DSA and ECDSA have important preconditions in what FIPS 186-4 and 186-5 calls "domain parameters". When those preconditions aren't met, all assumptions in the algorithms go out the window, including whether the retry loop converges. Unfortunately, the 186 documents were catastrophic failures in how to define cryptography, particularly in DSA. By [failing to pick parameters](https://www.imperialviolet.org/2022/03/15/pickingparameters.html), they force every system integrate this tricky notion of "domain parameter" in their system.

This notion empirically did not get through to folks. X.509 encodes DSA domain parameters by coefficients, and has a mode where it does the same for ECDSA. OpenSSL's APIs treat domain parameters as just one of many things you can parse or manually configure. This was all incorrect. As a result, it is very easy for untrusted domain parameters flow into a system. And thus we have this infinite loop, and previously OpenSSL had CVE-2022-0778.

The _right_ way to do this would have been to do everything a la ECDSA named curves: named, well-known DSA parameters, with no mechanism for arbitrary domain parameters at all. But that's not what happened, and the specification made it very hard to do this.

While priv == 0 isn't a loop from invalid domain parameters, there are other infinite loop cases BoringSSL which are. As @botovq suggests, there's no real reason to retry indefinitely. (Really there's no real reason to retry at all. For valid groups, needing to retry even once happens with negligible probability.) So while the root cause is, IMO, elsewhere, it's too late to fix the root cause, so we're going to cap the loop in (EC)DSA.

**Comment by guidovranken** [comment]
Now that the patches have been merged, I have confirmed that there are no more issues with DSA in BoringSSL.

**Comment by guidovranken** [comment]
OpenSSL also has an OOB write if you pass negative values

```c
#include <openssl/dsa.h>
#include <openssl/bn.h>
#include <openssl/err.h>
#include <string.h>

#define CF_CHECK_NE(expr, res) if ( (expr) == (res) ) { goto end; }

int main(int argc, char *argv[])
{
    DSA *dsa;
    BIGNUM *p, *q, *g, *priv_key, *pub_key;
    unsigned char *signature;
    const unsigned char msg[] = {0x00};
    unsigned int signature_len;

    p = BN_new();
    g = BN_new();
    q = BN_new();
    priv_key = BN_new();
    pub_key = BN_new();

    BN_dec2bn(&p, "800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000200000063000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000500000000000000000000000000000000000000000001905755000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000400600000000000000000000000000000000050000065550000000000000000000000000000000000000000000500000000000000001000000000000000000000000100000000000000000000000000000000800800000000000000000000000050600000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000483505847");
    BN_dec2bn(&q, "-522604916991225250052420120174356177703444321269");
    BN_dec2bn(&g, "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
    BN_dec2bn(&pub_key, "0");
    BN_dec2bn(&priv_key, "-220364184181605486093120234785300259603054497414");

    dsa = DSA_new();
    CF_CHECK_NE(DSA_set0_pqg(dsa, p, q, g), 0);
    CF_CHECK_NE(DSA_set0_key(dsa, pub_key, priv_key), 0);

    signature = malloc(DSA_size(dsa));

    DSA_sign(0, msg, sizeof(msg), signature, &signature_len, dsa);

end:
    DSA_free(dsa);
    free(signature);

    return 0;
}
```

```
=================================================================
==2446909==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000151 at pc 0x55ec977b7788 bp 0x7fff610984d0 sp 0x7fff610984c8
WRITE of size 1 at 0x602000000151 thread T0
    #0 0x55ec977b7787 in put_value /home/jhg/ossl-dsa/openssl/crypto/packet.c:217:15
    #1 0x55ec977b7787 in WPACKET_put_bytes__ /home/jhg/ossl-dsa/openssl/crypto/packet.c:412:17
    #2 0x55ec977a9895 in ossl_encode_der_length /home/jhg/ossl-dsa/openssl/crypto/asn1_dsa.c:52:14
    #3 0x55ec977a9895 in ossl_encode_der_dsa_sig /home/jhg/ossl-dsa/openssl/crypto/asn1_dsa.c:136:17
    #4 0x55ec9778fc8e in i2d_DSA_SIG /home/jhg/ossl-dsa/openssl/crypto/dsa/dsa_sign.c:98:10
    #5 0x55ec97790507 in ossl_dsa_sign_int /home/jhg/ossl-dsa/openssl/crypto/dsa/dsa_sign.c:170:15
    #6 0x55ec977906bb in DSA_sign /home/jhg/ossl-dsa/openssl/crypto/dsa/dsa_sign.c:178:12
    #7 0x55ec977780f8 in main /home/jhg/ossl-dsa/cryptofuzz/p.c:34:5
    #8 0x7fd99098e082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
    #9 0x55ec976b90ad in _start (/home/jhg/ossl-dsa/cryptofuzz/a.out+0x2be0ad) (BuildId: b84b983a46a281da9a25cae6d6b922eab3a1d554)

0x602000000151 is located 0 bytes to the right of 1-byte region [0x602000000150,0x602000000151)
allocated by thread T0 here:
    #0 0x55ec9773dc6e in __interceptor_malloc (/home/jhg/ossl-dsa/cryptofuzz/a.out+0x342c6e) (BuildId: b84b983a46a281da9a25cae6d6b922eab3a1d554)
    #1 0x55ec977780db in main /home/jhg/ossl-dsa/cryptofuzz/p.c:32:17
    #2 0x7fd99098e082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
```

@slontis

**Comment by slontis** [comment]
A couple of things are going on here:
(1) You are allocating a buffer based on DSA_size(). Which correctly returns an error of 0 since q is negative.
(2) DSA_sign() just gets passed the allocated buffer and assumes it is big enough, ideally it would have passed in the size also, but it doesnt.

So I think the problem really here is that you ignore the error from (1). Ideally (2) Should not have been done this way.

**Comment by guidovranken** [comment]
According to https://www.openssl.org/docs/man3.1/man3/DSA_size.html DSA_size() does not return an error code except when `dsa` does not contain key parameters, then it returns -1. It doesn't say that 0 is an error.

I think it would be better to return from DSA_sign if inputs are negative. But if that is not an option I'll work around it in my fuzzer.

**Comment by slontis** [comment]
if q is negative then it returns 0. Allocating a zero size buffer and passing it to a function that doesnt know how big the buffer is (it assumes it is big enough) doesnt sound like a good idea.
It could check for negative values in dsa_sign() just not sure if it should.

**Comment by slontis** [comment]
@openssl/otc opinions?

**Comment by paulidale** [comment]
`DSA_set0_key` seems like the place to catch negatives IMO.
`DSA_set0_pqg` should check as well.

**Comment by davidben** [comment]
That OpenSSL's functions often don't explicitly know the size isn't great, but that's not the caller's. Those are existing flaws in those OpenSSL APIs. The best a caller can do is act by the documentation, which says the buffer is sized by `DSA_size`.

If `DSA_size` doesn't return anything useful under some condition, then it is likewise a bug for `DSA_sign` to write to the buffer in that condition. Writing past `DSA_size` bytes is failing to meet its API contract. So `DSA_sign` should check for negative q here.

**Comment by davidben** [comment]
> `DSA_set0_key` seems like the place to catch negatives IMO.
> `DSA_set0_pqg` should check as well.

No, that's not viable and will introduce memory errors in all kinds of existing applications. In principle, yes, construction is the right place to do that. In practice, OpenSSL 1.1.0 designed its setters wrong such that you cannot do this anymore.

There are two problems. First, we have the issues discussed in #5158, which prevent you from checking most invariants. They also, incidentally, are the cause of significant threading contention in the `RSA` object.

Second, we have compatibility and the fact that these functions are `set0`. These functions only take ownership on success, which turns out to be rather tricky to combine with fallibility. I've seen a lot of callers of these APIs and they almost universally, either implicitly or explicitly, assume the functions never fail. Explicitly by way of not checking or crashing, and implicitly by way of getting the ownership wrong. (While the functions are technically fallible today, they only fail on NULL, which is usually a programmer error, not an invalid value. Checking for negatives doesn't fall as neatly in that category.)
