### ISSUE TITLE
after openssl 1.1.1t, can't login with correct password

### ISSUE THREAD

**Issue by mookseven** [openssl/openssl#20261]
Today i update openssl 1.1.1t, But i can't login with correct password

what happen to server (centos)

do you have any ideas?

thank you

**Comment by t8m** [comment]
If you manually replaced the system openssl library instead of updating it from centos rpm, then you most probably broke your system installation and the SSH or PAM modules are broken.

Unfortunately I cannot help you with reverting that but probably reinstalling the openssl-libs package from centos  via rpm should help.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
