### ISSUE TITLE
Bug in Bio_Printf

### ISSUE THREAD

**Issue by GillesT78** [openssl/openssl#20330]
Hello

If i call
        out = BIO_new_file("test.txt", "w");
	BIO_printf(out, "TEST%s","zz");
There is no problem, in the result file, there is : TESTzz

But if I call
	out = BIO_new_file("test.txt", "w");
	BIO_printf(out, "TEST%s","\r\n");

In the result file, I got : TESTCRCRLF instead of TESTCRLF
![image](https://user-images.githubusercontent.com/49693366/219852306-07c3e389-b242-44d9-8fd4-65b22ade449d.png)

Can you check, I don't undertstand why there is this problem
I haven't this problem with previous version of OpenSSL (0.9 or 1.0 or 1.1)
I do the test with OpenSSL 3.0.4

Regards
Gilles

**Comment by mattcaswell** [comment]
What platform are you seeing this on? My assumption is that printing the LF is being converted to CRLF automatically somewhere (perhaps because the file is open in "w" mode not "wb"). Not sure why the behaviour would have changed between OpenSSL versions though.

**Comment by GillesT78** [comment]
Hello
I am working on Windows
You are rigth, if I use "wb", I haven't the problem anymore
The default mode has certainly change in openssl

Regards
Gilles

**Comment by mattcaswell** [comment]
Ok...so this looks like "not a bug" to me. `BIO_printf` is behaving as it should, and the additional CRLF is due to the file mode being used. Why this didn't happen in older versions of OpenSSL remains a bit of a mystery which I haven't investigated - but the current behaviour looks to me like I would expect.
