### ISSUE TITLE
Huge size difference between 1.1.1 and 3.0.X

### ISSUE THREAD

**Issue by liyi77** [openssl/openssl#20345]
After upgrading to 3.0, the size of compiled binary will increase by >+50%,
This is really a huge change... affecting backwards compatibility.

I've tried adding more no-x from https://github.com/openssl/openssl/blob/master/INSTALL.md,
clipping the default provider, clipping object_dat and object_mac but with little effect,
there is still about 30% growth.
I am not very familiar with the structure of openssl, is there more effective ways to reduce the size? Thanks.

config list as: https://github.com/kraxel/edk2/blob/6fb6b61b93be4170de0ed12ae782b82c3c43a139/CryptoPkg/Library/OpensslLib/process_files.pl#L151-L211

**Comment by slontis** [comment]
OpenSSL 3.0 added a lot of code in order to support the providers - so it is going to be bigger.. The old code is still there so that engines still work also/
Apart from applying lots of no (e.g no-cmp), I am not sure you can do much else currently.
I can see a tool that can compare files that might help? https://github.com/google/bloaty
It may be possible that we need more config options to strip some of this stuff out..

**Comment by xtkoba** [comment]
See also: #13219

**Comment by liyi77** [comment]
> 



> OpenSSL 3.0 added a lot of code in order to support the providers - so it is going to be bigger.. The old code is still there so that engines still work also/ Apart from applying lots of no (e.g no-cmp), I am not sure you can do much else currently. I can see a tool that can compare files that might help? https://github.com/google/bloaty It may be possible that we need more config options to strip some of this stuff out..

Thanks! It is useful. At least I known where to start if I have to trim the openssl library myself.

**Comment by liyi77** [comment]
> See also: #13219

Glad to see the community is already discussing this issue, thanks

**Comment by nhorman** [comment]
marking as inactive, will be closed at the completion of 3.4 dev without further input
