### ISSUE TITLE
Context duplication is often unsupportable with hardware tokens

### ISSUE THREAD

**Issue by simo5** [openssl/openssl#20364]
OpenSSL 3.0 default behavior for some operations, like signatures, is to duplicate the operation context, then proceed to complete the signature operation on the duplicated context or fail if the duplication fails.

In the pkcs11-provider I work around this behavior by effectively transferring the context to the duplicate and simply rendering the original context unusable.

This is not ideal, and I would like to raise this as an API problem.

Ideally OpenSSL would *try* to make a duplicate, and on failure continue the operation on the original context but not fail the whole operation.

I can easily send a patch to do that in places like this:
https://github.com/openssl/openssl/blob/2c1ec72a7abb29f2d91eda6f93942670f1cbdb9e/crypto/evp/m_sigver.c#LL477

However I guess there is a reason why OpenSSL does something as odd as this by default?
My guess is it has to do with some space optimization for TLS handshakes, but I do not know for sure.

I know not all operations depend on context duplication to be completed successfully, because my workaround does work with all command line operations so far (but I do not have TLS tests yet).

This is something of a big deal for any provider that want to expose hardware (or remote) crypto engines, like TPM, HSMs, Smartcards, etc... and natively implement digest/sign APIs.

One option is to revert to software digesting + only raw signatures at the end, but that is not ideal and not all hw will necessarily offer raw signature APIs.

Plus FIPS compliance requires digesting to be done on the token, so it would break that part for users that want to be compliant.

One compromise could be to advertise at context creation time the need to have a duplicate later on, or perhaps the other way around, query some new context param to check if it supports context duplication for the specific algorithm selected ?

If the provider knows in advance that context duplication will be requested, it could change behavior only in those cases if it knows the HW context can't be duplicated.
Otherwise if OpenSSL queries the HW it could decide to take fallback paths, unclear to me what would be the best way.

I am seeking guidance here, and am willing to provide patches.

**Comment by mattcaswell** [comment]
Interesting. I was not aware of this "feature".

> However I guess there is a reason why OpenSSL does something as odd as this by default?
My guess is it has to do with some space optimization for TLS handshakes, but I do not know for sure.

No, the reasons behind it are documented in the man page:

> The call to EVP_DigestSignFinal() internally finalizes a copy of the digest
context. This means that calls to EVP_DigestSignUpdate() and
EVP_DigestSignFinal() can be called later to digest and sign additional data.

It seems this behaviour has been there since forever (at lest it exists for EVP_SignFinal in 0.9.8 which is as far back as I checked). At some point there was an attempt to add an option to disable it:

> =item EVP_MD_CTX_FLAG_FINALISE
> 
> Some functions such as EVP_DigestSign only finalise copies of internal
contexts so additional data can be included after the finalisation call.
This is inefficient if this functionality is not required, and can be
disabled with this flag.

But this is a non-default option, and requires the caller to explicitly set it which, I guess, hardly anyone does.

It doesn't seem unreasonable to me to fall back to not duplicating the context if the duplication operation fails. This wouldn't exactly be a compatibility break because, presumably, applications that rely on this are already using providers that support it.

It would have to be a documented restriction of any provider that it doesn't support this "continue signing more data" capability which may make it incompatible with some applications that use this. Probably this couldn't be classed as a "bug fix" though, so master only. We'd also have to update the man pages for the various sign/verfiy functions to explain that some providers may not support this. Perhaps there needs to be some param/API you can query to find out if it is supported or not?

**Comment by beldmit** [comment]
I'd consider this behavior change to 3.1.

**Comment by beldmit** [comment]
EVP_PKEY_CTX_dup seems to be relatively new - AFAIR, EVP_PKEY_CTX appeared in 1.0 series together with pluggable asymmetric algorithms. The problem I see here is that even when digest context is usually more easily duplicated than the EVP_PKEY context...

**Comment by simo5** [comment]
> Perhaps there needs to be some param/API you can query to find out if it is supported or not?

Yes, I poporsed this above, if you can tell me what to do here, I can implement it in the pkcs11-provider and document.
Meanwhile I am going to propose a code fix and will follow up with a path for docs if we agree the fix is sound.

**Comment by beldmit** [comment]
Do we have anything to do here?

**Comment by simo5** [comment]
The main PR was done, I think we can close if no more needs to be added.
