### ISSUE TITLE
What is the reason for this code?

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#20414]
https://github.com/openssl/openssl/blob/d0a3b9d1eb1fc510ec3447b44803bbf5520a0c47/providers/implementations/rands/drbg.c#L661-L663

Why the parent DRBG reseeding is to enforce reseeding all the childs?

**Comment by neverpanic** [comment]
Also, isn't this a performance hog as soon as one of the DRBGs is used with prediction resistance?

If I use `EVP_RAND_generate(RAND_get0_public(), ..., prediction_resistance=1, ...)`, that will cause `ossl_prov_drbg_reseed()` to be called with `prediction_resistance` set to 1. `ossl_prov_drbg_reseed()` will invoke `get_entropy()`, which will call `ossl_drbg_get_seed()`, all with prediction resistance enabled. As I understand things, this will cause all DRBGs on the chain to the top to reseed.

The piece of code quoted in the 1st comment will then cause all other DRBGs to reseed from their parents, which means a single EVP_RAND_generate() with prediction resistance will cause all DRBGs to reseed. In other words, a single EVP_RAND_generate() with prediction resistance will cause all DRBGs to be slow.

What am I missing?

**Comment by paulidale** [comment]
It's useful.  We could technically live without it.  @mspncp introduced this in 1.1.1 I believe, he might be able to supply the reasoning behind this.

_"all other DRBGs"_ is a misnomer, it should be _"the other DRBG"_.  With the setup OpenSSL has by default (primary, public and private), using prediction resistance will cause one unneeded reseed (if you use the public DRBG with prediction resistance, the private DRBG will reseed when next used).  The performance cost won't be huge in reality.

If you are setting up lots of your own DRBGs and using prediction resistance, things might be different.  I'd suggest picking their seed sources carefully or not using prediction resistance.

**Comment by neverpanic** [comment]
> _"all other DRBGs"_ is a misnomer, it should be _"the other DRBG"_. With the setup OpenSSL has by default (primary, public and private), using prediction resistance will cause one unneeded reseed (if you use the public DRBG with prediction resistance, the private DRBG will reseed when next used). The performance cost won't be huge in reality.

I had the impression that the public and private DRBGs existed per thread, while the primary DRBG exists once, so it's not just "the other DRBG" if you create threads. Let's assume some application creates 100 threads to handle various different SSL_CTXs, and then creates one additional thread where is uses prediction resistance with the public DRBG. Wouldn't those 100 threads then all re-seed?

> If you are setting up lots of your own DRBGs and using prediction resistance, things might be different. I'd suggest picking their seed sources carefully or not using prediction resistance.

This is not obvious from the documentation, and I doubt anyone will know unless they've actually read the code or strace'd a process with many DRBG instances.

**Comment by mspncp** [comment]
The original design of the OpenSSL 1.1.1 DRBG was a major improvement compared to the singleton locked RNG we had in 1.1.0 and before:  every thread has a dedicated thread-local DRBG  (later it was split into two, a private and a public DRBG) which would provide a lock-free **generate** operation. The child (per-thread) DRBGs **reseed** on a regular base (after some data or time threshold was met), using a **generate** operation to optain fresh random input from the parent (singleton) DRBG.

**The original implementation, however, was different in one important way:**  a reseeding of the child DRBG did not automatically trigger a reseeding of the parent DRBG, even if  `prediction_resistance` was required for the child. So it was possible to have a single thread using `prediction_resistance` without affecting the others too much.

> I had the impression that the public and private DRBGs existed per thread, while the primary DRBG exists once

Exactl, and the primary DRBG is the only one who gets 'true' fresh randomness from the operating system, so the line which @beldmit quoted simply ensures that fresh randomness from the operating system propagates downwards as soon as possibe.

https://github.com/openssl/openssl/blob/d0a3b9d1eb1fc510ec3447b44803bbf5520a0c47/providers/implementations/rands/drbg.c#L661-L663

The behaviour changed in commit eb238134e0a0fb5ac5c8239ade1dfe77a815aba5 where @kroeckx introduced the concept of propagating the `prediction_restance` requests upwards to the parent:

```patch
@@ -435,7 +437,9 @@ int RAND_DRBG_reseed(RAND_DRBG *drbg,
     drbg->state = DRBG_ERROR;
     if (drbg->get_entropy != NULL)
         entropylen = drbg->get_entropy(drbg, &entropy, drbg->strength,
-                                   drbg->min_entropylen, drbg->max_entropylen);
+                                       drbg->min_entropylen,
+                                       drbg->max_entropylen,
+                                       prediction_resistance);
```

I was strongly opposed to this change, because I believed that the NIST standard does not mandate it, but I was overruled. Maybe I was wrong at the time, or maybe the requirements have become stricter, I don't know. I still dislike this change. You can read the discussion in https://github.com/openssl/openssl/pull/5402#issuecomment-369513189 ff.

A consequence of this change is that a single thread can trigger an avalanche of reseedings if it overuses the `prediction_resistance` flag, just as @neverpanic describes in https://github.com/openssl/openssl/issues/20414#issuecomment-1450324003.

> Also, isn't this a performance hog as soon as one of the DRBGs is used with prediction resistance?

You are absolutely right.

**Comment by rsbeckerca** [comment]
I am somewhat concerned, with #20394, that this may be bypassing the hardware RNG in some circumstances. The `get_hardware_random_value()` method does not appear to be invoked even when `--with-rand-seed=rdcpu` is used.

**Comment by beldmit** [comment]
@mspncp we were told by our labthat we need to reseed because of the DRBG chaining and SP 800-90C, and that introduces an endless reseed loop. Now we are trying to get rid of this loop with reasonable modifications.

**Comment by mspncp** [comment]
@beldmit I'm not sure I completely understand what you mean with "we need to reseed": 

Are you saying that all your thread-local DRBGs are configured to request prediction resitance on every generate call? Then I understand why you get an infinite loop. If that's the case, the chaining to the primary DRBG is not only completely pointless, but becomes a real bottleneck. I'd suggested that you dump the  primary DRBG and have all thread-local DRBGs reseed using entropy directly from the operating system instead.

**Comment by mspncp** [comment]
> I am somewhat concerned, with #20394, that this may be bypassing the hardware RNG in some circumstances. The `get_hardware_random_value()` method does not appear to be invoked even when `--with-rand-seed=rdcpu` is used.

Sorry, I don't see how these two issues are related?

**Comment by rsbeckerca** [comment]
> > I am somewhat concerned, with #20394, that this may be bypassing the hardware RNG in some circumstances. The `get_hardware_random_value()` method does not appear to be invoked even when `--with-rand-seed=rdcpu` is used.
> 
> Sorry, I don't see how these two issues are related?

I'm just looking for possible causes of why the x86 RNG is not being used on the NonStop platform.

**Comment by beldmit** [comment]
> Are you saying that all your thread-local DRBGs are configured to request prediction resistance on every generate call?! Then I understand why you get an infinite loop. If that's the case, the chaining to the primary DRBG is not only completely pointless, but becomes a real bottleneck. I'd suggested that you dump the primary DRBG and have all thread-local DRBGs reseed using entropy directly from the operating system instead.

No. If we are reseeding the private/public DRBG, we have to reseed the primary first.

**Comment by mspncp** [comment]
> I'm just looking for possible causes of why the x86 RNG is not being used on the NonStop platform.

This issue is just about chaining of DRBGs, i.e., how one DRBG reseeds from another. Your problem concerns the reseeding of the primary DRBG from the operating system, and the answer to your question lies probably hidden somewhere in [rand_unix.c](https://github.com/openssl/openssl/blob/master/providers/implementations/rands/seeding/rand_unix.c).

**Comment by mspncp** [comment]
> No. If we are reseeding the private/public DRBG, we have to reseed the primary first.

That's exactly what `EVP_RAND_generate()` does when you call it with `prediction_resistance = 1`:

- reseed the primary DRBG
- reseed the thread-local private/public DRBG
- generate random data

**Comment by paulidale** [comment]
Oops, I'd forgotten about the per-thread DRBGs.  Yes, there could be a lot of reseeding.

Prediction resistance has to propagate up to the primary, it's a NIST mandate.
I'm not aware of any of our code (outside of tests) setting prediction resistance but an application could do this via the EVP_RAND API.

Given that we do not rely on what is supplied via `RAND_add()`, we could drop the reseed after the parent reseeds.

**Comment by rsbeckerca** [comment]
> Oops, I'd forgotten about the per-thread DRBGs. Yes, there could be a lot of reseeding.
> 
> Prediction resistance has to propagate up to the primary, it's a NIST mandate. I'm not aware of any of our code (outside of tests) setting prediction resistance but an application could do this via the EVP_RAND API.
> 
> Given that we do not rely on what is supplied via `RAND_add()`, we could drop the reseed after the parent reseeds.

In this situation, git is not built with threads - it will soon, but I have not gotten to that particular enhancement on NonStop, and we would have to deal with that when we come to it - git does not do that right now, so it may be an issue there. The only `RAND_` call used by git (checked the object) is `RAND_bytes`.

**Comment by rsbeckerca** [comment]
> > I'm just looking for possible causes of why the x86 RNG is not being used on the NonStop platform.
> 
> This issue is just about chaining of DRBGs, i.e., how one DRBG reseeds from another. Your problem concerns the reseeding of the primary DRBG from the operating system, and the answer to your question lies probably hidden somewhere in [rand_unix.c](https://github.com/openssl/openssl/blob/master/providers/implementations/rands/seeding/rand_unix.c).

I have gone into `rand_unix.c` (seen above in the ifdef/elif/endif block). There is no explicit reference to NonStop compiler defines in that code - I am guessing there needs to be, but I do not get the specific change required.

**Comment by mspncp** [comment]
@beldmit told me (privately) that he patched OpenSSL such that both thread-local DRBG instances reseed with prediction resistance enabled (when the threshold has been reached). Mixing calls to those two DRBGs introduces the same negative side-effects, namely that after the first reseeding the reseed counters will be out-of-sync, so you get a full reseeding on every generate call.

```C
    for(;;) {
        RAND_bytes(...);
        RAND_priv_bytes(...)
    }
```
IMHO I would enforce prediction resistance only when reseeding the private instance, not the public one, since the former is intended for long-term secrets, while the other is for arbitrary randomness (e.g. nonces). That was the whole point of having two instances in the first place.

**Comment by beldmit** [comment]
It's a public patch :)

And reseeding is required by NIST after some amount of operations (65536?). Chain reseeding is also a NIST requirement.

**Comment by neverpanic** [comment]
> It's a public patch :)

https://gitlab.com/redhat/centos-stream/rpms/openssl/-/blob/c9s/0076-FIPS-140-3-DRBG.patch, so save everybody some time.

> And reseeding is required by NIST after some amount of operations (65536?).

AFAIK, NIST would be fine with a much larger number of draws before it requires a reseed (something in the range of 2^48), and does not require reseeding after a certain amount of time at all.

> Chain reseeding is also a NIST requirement.

Correct, we've been told by our certification lab that chaining DRBGs is only ok under SP 800-90C if a reseed of the child DRBG reseeds the parent DRBG before using its output as seed, and if that parent DRBG is also used to directly generate random numbers (i.e., is accessible to the user), we also need to reseed it *after* obtaining the seed for the child DRBG, plus this operation must be under a lock so that no user can obtain any information about the state of the DRBG when it was used to seed the child DRBG.

This obviously brings us to the question whether we shouldn't just completely drop DRBG chaining and always seed every DRBG from the kernel instead, since that's more or less what's happening (with a few DRBGs doing some mixing in between).

Note that in the interpretation of our lab, the OpenSSL primary DRBG is also chained to the kernel DRBG, which is why we re-purpose the unused getrandom(GRND_RANDOM) flag to trigger this same reseed dance for the kernel DRBG.

**Comment by beldmit** [comment]
@neverpanic just 2c - I'm not sure GRND_RANDOM is upstream flag.

**Comment by neverpanic** [comment]
> @neverpanic just 2c - I'm not sure GRND_RANDOM is upstream flag.

It used to be. It is now unused.

**Comment by mspncp** [comment]
> This obviously brings us to the question whether we shouldn't just completely drop DRBG chaining and always seed every DRBG from the kernel instead, since that's more or less what's happening (with a few DRBGs doing some mixing in between).

That was also my spontaneous suggestion to @beldmit.

**Comment by mspncp** [comment]
> It's a public patch :)

The _private_ adjective only referred to our discussion, not to the patch 😉

**Comment by kroeckx** [comment]
> This obviously brings us to the question whether we shouldn't just completely drop DRBG chaining and always seed every DRBG from the kernel instead, since that's more or less what's happening (with a few DRBGs doing some mixing in between).

Maybe not from the kernel, but what is set up as source of what is now the primary DRBG.

**Comment by paulidale** [comment]
> Correct, we've been told by our certification lab that chaining DRBGs is only ok under SP 800-90C if a reseed of the child DRBG reseeds the parent DRBG before using its output as seed, and if that parent DRBG is also used to directly generate random numbers (i.e., is accessible to the user), we also need to reseed it _after_ obtaining the seed for the child DRBG, plus this operation must be under a lock so that no user can obtain any information about the state of the DRBG when it was used to seed the child DRBG.

I'd be pushing back, if necessary ask for NIST's take on it (as a last resort).  This interpretation is crazy IMO.  It makes chained DRBGs pointless.  Nowhere else is there any discussion of locking, so that's silly too, again IMO.

**Comment by neverpanic** [comment]
> I'd be pushing back, if necessary ask for NIST's take on it (as a last resort). This interpretation is crazy IMO. It makes chained DRBGs pointless. Nowhere else is there any discussion of locking, so that's silly too, again IMO.

Following up on this, see FIPS 140-3 IG section D.K, comment 5. Emphasis mine:

There are additional considerations when the stateful conditioning component is a DRBG. For every request to GetEntropy from the entropy source, at least $n_{in}$ bits must be provided to the stateful conditioning component (where $n_{in}$ is defined for the conditioning component and provides $h_{in}$ bits of entropy). If the conditioning component is a DRBG, the conditioning component **shall have prediction resistance enabled, or shall be reseeded** before requesting an output using at least $n_{in}$ bits from the noise source or the previous conditioning component. A stateful conditioning component shall not output any bits without obtaining at least $n_{in}$ bits from the primary noise source or the previous conditioning component. A DRBG is not a bijective conditioning function. The length of the output of the DRBG shall be at most equal to the security strength of the DRBG. **If the DRBG is used in other contexts** than as a conditioning component for the entropy source, **the DRBG shall be reseeded both before and after bits are requested in the other context**. This may occur when one DRBG instance has been instantiated to serve multiple applications such as within an operating system.

**Comment by paulidale** [comment]
This IG doesn't apply to the OpenSSL FIPS provider because there is no claim of an entropy source that is compliant to SP 800-90B.

It could probably be argued that use for a single application doesn't require a reseed on each generate call (at least for the public and private DRBGs): there is no restriction on the number of bits that can be requested in the other context case.  Likewise, it's not specified to be per generate.

This is crazy nonetheless...
