### ISSUE TITLE
OBJ_create: lock is unlocked without ever having been acquired

### ISSUE THREAD

**Issue by alex** [openssl/openssl#20613]
https://github.com/openssl/openssl/blob/openssl-3.1/crypto/objects/obj_dat.c#L742-L752

These two `goto err;` will invoke `ossl_obj_unlock`, even though they
haven't called `ossl_obj_write_lock`.

At least with pthreads, this is undefined behavior.

**Comment by mattcaswell** [comment]
Hmm. This seems to have been fixed in master some while ago via #17417 (which covered a whole bunch of different issues). But that only went to master and was not cherry-picked to 3.1. There was a 3.0 backport in #17443, but it was 3.0 specific and did not include the fix for OBJ_create (because it wasn't relevant there). So 3.1 never got that set of fixes. So I think we need a 3.1 backport of #17417 to cover all the fixes there.

**Comment by mattcaswell** [comment]
The situation is even more complicated actually. It seems that at the time of the merge of #17417 the 3.1 branch did not contain the new thread safe OBJ_create implementation. That was backported later as part of the mass backports of code from master to 3.1 - but the backport of the subsequent fix was somehow missed.

**Comment by t8m** [comment]
The only fix from #17417 that is missing in 3.1 are actually the obj_dat.c fixes - so yeah, not just the unlocks without lock but also the leak of tmpoid on error.

**Comment by mattcaswell** [comment]
Fix in #20615
