### ISSUE TITLE
libcrypto conflict (3.0 vs 1.1)

### ISSUE THREAD

**Issue by Haag-se** [openssl/openssl#20666]
I recently upgraded Ubuntu to 22.04 resulting in OpenSSL 3.0.2 being installed.

```
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
```

This created problems for my C++ apps. When compiling c++ code that are using OpenSSL, I get an error stating that there is a potential conflict between libcrypto.so.1.1 and libcrypto.so.3

```
 /usr/bin/ld: warning: libcrypto.so.1.1, needed by /lib/x86_64-linux-gnu/libpq.so.5, may conflict with libcrypto.so.3
```

Any ideas how to solve this?

**Comment by paulidale** [comment]
This is an Ubuntu packing issues.  Suggest you ask them for assistance.

**Comment by levitte** [comment]
It's not a packaging issue per se...  I just checked on a 22.04 system (last update in the beginning of february this year):

``` console
$ # ldd /lib/x86_64-linux-gnu/libpq.so.5
...
        libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007f2b22c1b000)
        libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007f2b227d9000)
...
```

Also, `apt` shows me that libpq5 has been built against OpenSSL 3 for quite a while (since alpha 1‽):

```
# apt show libpq5
Package: libpq5
Version: 14.7-0ubuntu0.22.04.1
...
Depends: libc6 (>= 2.33), libgssapi-krb5-2 (>= 1.17), libldap-2.5-0 (>= 2.5.4), libssl3 (>= 3.0.0~~alpha1)
...
```

So I suspect that, for some reason or another, the system where libpq5 depends on OpenSSL 1.1.1 is not quite up to date in this respect.  Could the usual `apt update; apt upgrade` dance help?  Does it help to do `apt full-upgrade`?
