### ISSUE TITLE
Reject invalid versions in X509_REQ_set_version

### ISSUE THREAD

**Issue by alex** [openssl/openssl#20663]
RFC 2986 only defines a single version for CSRs: v1(0). However, many people accidentally use an X.509 version (e.g. v3(2)). This results in a proliferation of CSRs that are invalid.

OpenSSL should reject invalid values in X509_REQ_set_version, and thus avoid encoding them in new applications.

**Comment by t8m** [comment]
I am afraid that rejecting could be seen as API breakage (i.e., what if someone uses OpenSSL to test creating such broken CSR to see if it is properly rejected on read) so that would mean waiting for 4.0 at the earliest.

**Comment by alex** [comment]
The documentation states:
> Similarly X509_REQ_get_version(), X509_REQ_set_version(), X509_CRL_get_version() and X509_CRL_set_version() get and set the version number of certificate requests and CRLs. They use constants X509_REQ_VERSION_1, X509_CRL_VERSION_1, and X509_CRL_VERSION_2.

Which can reasonably be read to indicate that specifying other values isn't supported.

It is documented that these functions can fail:

> X509_set_version(), X509_REQ_set_version() and X509_CRL_set_version() return 1 for success and 0 for failure.

**Comment by raviteja-b** [comment]
its always suggested to set version to 1 using X509_REQ_set_version() ?
I have set CSR version to 1 using X509_REQ_set_version() and noticed this issue https://github.com/openssl/openssl/issues/23963

**Comment by davidben** [comment]
It is suggested to not call `X509_REQ_set_version` at all. See my reply to your bug.

**Comment by davidben** [comment]
OpenSSL folks: this issue was mis-triaged last year. It says "triaged: feature", but this is really a spec compliance bug in OpenSSL, in the same vein as https://github.com/openssl/openssl/pull/23483#issuecomment-1941238361 (cc @job). @t8m, can you please correct this?

BoringSSL considered this a bug and fixed this back in 2022. We will not produce CSRs with the wrong version. We were forced to still accept one non-compliant version number, "v3"(2), as a direct consequence of this very bug in OpenSSL. OpenSSL's non-compliant CSR implementation resulted in applications putting the wrong version number into their CSRs and now there are non-compliant values in the ecosystem, e.g. certbot prior to https://github.com/certbot/certbot/pull/9334. The mixup that @raviteja-b ran into is also a direct consequence of this OpenSSL bug.

Spec compliance failures like these in OpenSSL are a big part of why interoperability is so difficult in X.509, and why the protocol has eroded so badly over time. This OpenSSL bug needs to be fixed to stop the bleeding.

**Comment by t8m** [comment]
I do not agree that adding such rejection of invalid versions would be a _bug fix_. I do not think such addition needs to wait for 4.0 version but it should not be done on stable release branches.

**Comment by job** [comment]
It seems sensible to protect users against accidentally setting the wrong version in CSRs, I put forward a draft proposal, see #23965.

Given the function signature (the function being able to return an error), and there not being any other versions standardized other than `X509_REQ_VERSION_1`, this patch seems fairly non-intrusive.

**Comment by SoraKohaku** [comment]
If CSR update resolve solution of update good. but sometimes need test system to make it's stable.

**Comment by t8m** [comment]
This was fixed by https://github.com/openssl/openssl/pull/23965
