### ISSUE TITLE
OpenSSL symbols conflict while linking with application

### ISSUE THREAD

**Issue by AshishDurgapal** [openssl/openssl#20766]
We  have created a static library having OpenSSL(version 3.1.0) statically linked and we have another application which is using OpenSSL 1.1.1f, so when we link our library with application then OpenSSL symbols from library and application conflicts with each other.

Is there any option to hide the OpenSSL symbols from library ?

**Comment by t8m** [comment]
Which platform are you making your library on? I do not know if other platforms support this but with glibc based ones you can use the symbol map file to export only specified symbols to a shared library. Of course that assumes that your library is a shared library, i.e. you do not try to make your library a static one. Because in that case there is IMO no way to avoid such conflicts.

**Comment by paulidale** [comment]
Is your library shared?  If so, it should be possible to exclude OpenSSL's symbols.

Can you use a shared OpenSSL library?

**Comment by AshishDurgapal** [comment]
No, I can't use shared OpenSSL lib and have to create static library .

**Comment by paulidale** [comment]
I know of no way to achieve what you're after.

You might be able to figure out something using objcopy or similar to rename the symbols but it's a bit of a dodgy kludge.

**Comment by t8m** [comment]
Yeah, some libraries support adding prefixes to all extern symbols through fancy macros but I do not think we want to do such mess ever.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
