### ISSUE TITLE
Getting continuously debug BIO messages 

### ISSUE THREAD

**Issue by suprita52** [openssl/openssl#20763]
Hi,

Openssl Version : OpenSSL 1.0.2zg-fips  7 Feb 2023

 Iam getting BIO messages and many socket related messages only when I am performing remote logging (tcp) using openssl. We are using rsyslog application for local and remote logging. Remote logging using TLS with openssl. These debug messages are logged when any operation we do eg, like logger command(logger "hello") etc.

'''
BIO[0x7fd9ff202fe0]: ctrl(102) - socket
BIO[0x7fd9ff202fe0]: ctrl return 0
BIO[0x7fd9ff202fe0]: write(11,259) - socket fd=11
BIO[0x7fd9ff202fe0]: write return 259
BIO[0x7fd9ff202fe0]: read(11,7) - socket fd=11
BIO[0x77bf60]: ctrl(102) - socket
BIO[0x77bf60]: ctrl return 0
BIO[0x77bf60]: write(10,259) - socket fd=10
BIO[0x77bf60]: write return 259
BIO[0x77bf60]: read(10,7) - socket fd=10
BIO[0x77bf60]: read return 7
BIO[0x77bf60]: ctrl(6) - socket
BIO[0x77bf60]: ctrl return 0
BIO[0x77bf60]: read(10,85) - socket fd=10
BIO[0x77bf60]: read return 85
BIO[0x77bf60]: read(10,5) - socket fd=10
BIO[0x77bf60]: read return 5
BIO[0x77bf60]: read(10,827) - socket fd=10
BIO[0x77bf60]: read return 827
BIO[0x77bf60]: read(10,5) - socket fd=10
BIO[0x77bf60]: read return 5
BIO[0x77bf60]: read(10,401) - socket fd=10
BIO[0x77bf60]: read return 401
BIO[0x77bf60]: read(10,5) - socket fd=10
BIO[0x77bf60]: read return 5
BIO[0x77bf60]: read(10,127) - socket fd=10
BIO[0x77bf60]: read return 127
BIO[0x77bf60]: read(10,5) - socket fd=10
BIO[0x77bf60]: read return 5
BIO[0x77bf60]: read(10,4) - socket fd=10
'''

The code we found in the  bio_cb.c(openssl source code):
code snippet below : 

'''
        switch (cmd)
                {
        case BIO_CB_FREE:
                BIO_snprintf(p,p_maxlen,"Free - %s\n",bio->method->name);
                break;
        case BIO_CB_READ:
                if (bio->method->type & BIO_TYPE_DESCRIPTOR)
                        BIO_snprintf(p,p_maxlen,"read(%d,%d) - %s fd=%d\n",
                                 bio->num,argi,bio->method->name,bio->num);
                else
                        BIO_snprintf(p,p_maxlen,"read(%d,%d) - %s\n",
                                 bio->num,argi,bio->method->name);
                break;
        case BIO_CB_WRITE:
                if (bio->method->type & BIO_TYPE_DESCRIPTOR)
                        BIO_snprintf(p,p_maxlen,"write(%d,%d) - %s fd=%d\n",
                                 bio->num,argi,bio->method->name,bio->num);
                else
                        BIO_snprintf(p,p_maxlen,"read(%d,%d) - %s\n",
                                 bio->num,argi,bio->method->name);
                break;
        case BIO_CB_WRITE:
                if (bio->method->type & BIO_TYPE_DESCRIPTOR)
                        BIO_snprintf(p,p_maxlen,"write(%d,%d) - %s fd=%d\n",
                                 bio->num,argi,bio->method->name,bio->num);
                else
                        BIO_snprintf(p,p_maxlen,"write(%d,%d) - %s\n",
                                 bio->num,argi,bio->method->name);
                break;
        case BIO_CB_PUTS:
                BIO_snprintf(p,p_maxlen,"puts() - %s\n",bio->method->name);
                BIO_snprintf(p,p_maxlen,"puts() - %s\n",bio->method->name);
                break;
        case BIO_CB_GETS:
                BIO_snprintf(p,p_maxlen,"gets(%d) - %s\n",argi,bio->method->name);
                break;
        case BIO_CB_CTRL:
                BIO_snprintf(p,p_maxlen,"ctrl(%d) - %s\n",argi,bio->method->name);
                break;
        case BIO_CB_RETURN|BIO_CB_READ:
                BIO_snprintf(p,p_maxlen,"read return %ld\n",ret);
                break;
        case BIO_CB_RETURN|BIO_CB_WRITE:
                BIO_snprintf(p,p_maxlen,"write return %ld\n",ret);
                break;
        case BIO_CB_RETURN|BIO_CB_GETS:
                BIO_snprintf(p,p_maxlen,"gets return %ld\n",ret);
                break;
        case BIO_CB_RETURN|BIO_CB_PUTS:
                BIO_snprintf(p,p_maxlen,"puts return %ld\n",ret);
                break;
        case BIO_CB_RETURN|BIO_CB_CTRL:
                BIO_snprintf(p,p_maxlen,"ctrl return %ld\n",ret);
                break;
        default:
                BIO_snprintf(p,p_maxlen,"bio callback - unknown type (%d)\n",cmd);
                break;
                }
'''

We are getting the exact same message like  BIO[0x7fd9ff202fe0]: read(11,7) - socket fd=11 which is matching the code  BIO_snprintf(p,p_maxlen,"read(%d,%d) - %s fd=%d\n",
                                 bio->num,argi,bio->method->name,bio->num);

Can you please guide us on what is the reason we are getting these messages and how to disable these debug messages.

Thanks,
Suprita

**Comment by paulidale** [comment]
1.0.2 is out of public support.  Please raise this as an issue on your private OpenSSL GitHub instance.

**Comment by murugeshg** [comment]
Here is the root cause analysis and a possible fix:

BIO_debug_callback_ex() is defined in both openssl and rsyslog.

Location of the above function:
In openssl: src/crypto/bio/bio_cb.c
In rsyslog: runtime/nsd_ossl.c

Library to which these function goes:
In openssl: libcrypto.so
In rsyslog: lmnsd_ossl.so

The function defined in openssl uses "stderr".

If there is any facility filter configured then it results in "stderr" pointing to the device which is configured against that filter.

If remote logging with TLS enabled then "stderr" points to the TCP socket which is established with remote server.

shell> ss -aeip | grep rsyslog
u_dgr UNCONN 0 0 /dev/log 6767 * 0 users:(("rsyslogd",pid=2222,fd=3)) <-> ino:6768 dev:0/1
u_dgr UNCONN 0 0 * 5855 * 6767 users:(("rsyslogd",pid=2222,fd=1)) <->
tcp ESTAB 0 0 10.52.1.28:57736 10.52.2.4:6514 users:(("rsyslogd",pid=2222,fd=2)) ino:6919 sk:39 <->
shell>

From the above command output stderr (fd=2) pointing to TCP socket, due to which anything written on "stderr" is sent over TCP socket.
BIO_debug_callback_ex() defined in openssl module, writes debug information before establishing TLS handshake, which causes
the debug information sent on TCP socket to the remote server.

Here is the sample of debug information sent as a TCP payload:

BIO[0xf6f2fe80]: ctrl(102) - socket
BIO[0xf6f2fe80]: ctrl return 0

The remote server does validate the packet and results in below message logged and disconnects the TCP session.

Jan 24 22:09:10 raspberrypi rsyslogd: SSL_ERROR_SSL Error in 'osslHandshakeCheck Server': 'error:00000001:lib(0):func(0):reason(1)(1)' with ret=-1 [v8.2102.0]
Jan 24 22:09:10 raspberrypi rsyslogd: OpenSSL Error Stack: error:1408F10B:SSL routines:ssl3_get_record:wrong version number [v8.2102.0]
Jan 24 22:09:10 raspberrypi rsyslogd: netstream session 0xb4d05e60 from 10.1.1.1 will be closed due to error [v8.2102.0 try https://www.rsyslog.com/e/2089 ]
Jan 24 22:09:10 raspberrypi rsyslogd: SSL_ERROR_SSL Error in 'osslEndSess': 'error:00000001:lib(0):func(0):reason(1)(1)' with ret=-1 [v8.2102.0]
Jan 24 22:09:10 raspberrypi rsyslogd: OpenSSL Error Stack: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init [v8.2102.0]
Jan 24 22:09:10 raspberrypi rsyslogd: nsd_ossl:TLS session terminated with remote syslog server. [v8.2102.0]

Renaming of BIO_debug_callback_ex() defined in rsyslog and registering the renamed function as a call back fixes this issue.

This is one of the solution.

Another solution is to create a facility filter for "syslog" and log to a local file on the client side.

**Comment by t8m** [comment]
I do not think there is anything to fix in OpenSSL here.
