### ISSUE TITLE
Confirming FIPs is installed on OpenSSL 3.0

### ISSUE THREAD

**Issue by JordanDalton** [openssl/openssl#20774]
I'm trying to get OpenSSL 3.0 installed with FIPs enabled.

I did the `./config enable-fips` along with `make` and `make install`

I read [here](https://wiki.openssl.org/index.php/OpenSSL_3.0#Completing_the_installation_of_the_FIPS_Module) that you need the `fipsinstall` command ran to complete the instllation:  

`root@ubuntu-s-1vcpu-1gb-nyc1-01:~/openssl-3.0.8# openssl fipsinstall -module providers/fips.so -out ~/fipsmodule.cnf -provider_name fipsINSTALL PASSED`

Afterwards, when I check the version I see there's no mention of FIPs.

```
root@ubuntu-s-1vcpu-1gb-nyc1-01:~# openssl version -a
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)
built on: Wed Apr 19 18:08:28 2023 UTC
platform: linux-x86_64
options:  bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/lib64/engines-3"
MODULESDIR: "/usr/local/lib64/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_ia32cap=0xfef83203078bffff:0x400004219c01a9
```

When I test against MD5 I get the error as expected:

```
root@ubuntu-s-1vcpu-1gb-nyc1-01:~/EPCSCP# openssl md5 test.txt 
Error setting digest
C0D185178E7F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (MD5 : 102), Properties ()
C0D185178E7F0000:error:03000086:digital envelope routines:evp_md_init_internal:initialization error:crypto/evp/digest.c:254:
```

I get success when testing sha256:

```
root@ubuntu-s-1vcpu-1gb-nyc1-01:~/EPCSCP# openssl sha256 test.txt 
SHA2-256(test.txt)= f2ca1bb6c7e907d06dafe4687e579fce76b37e4e93b7605022da52e6ccc26fd2
```

Forgive me as I'm new to this. Shouldn't `openssl version -a` include some sort of output that indicated FIPs mode is enabled? If not, is there something specific I need to do?

**Comment by paulidale** [comment]
Have a look at the OpenSSL `list` command: `./util/wrap.pl -fips apps/openssl list -provider fips -providers`

`version` isn't mentioning FIPS because the library is build identically with or without FIPS support.  It's the separate FIPS provider that makes things FIPS approved.

I'll also not that 3.0.8 is not FIPS validated.  Only the 3.0.0 FIPS provider has a certificate.  You should build OpenSSL 3.0.0 to get it's FIPS provider and then run the 3.0.8 library using the 3.0.0 FIPS provider.

Which means `openssl version` should print 3.0.8 and openssl list (as above) should show 3.0.0 for the FIPS provider.

**Comment by JordanDalton** [comment]
Thanks, @paulidale.

I went and installed 3.0.0, went through the steps:

```
root@ubuntu-s-4vcpu-8gb-nyc1-01:~/openssl-3.0.0# ./util/wrap.pl -fips apps/openssl list -provider fips -providers
Providers:
  base
    name: OpenSSL Base Provider
    version: 3.0.0
    status: active
  fips
    name: OpenSSL FIPS Provider
    version: 3.0.0
    status: active
```

Unless I'm missing something it looks like I'm good to go.

**Comment by mattcaswell** [comment]
> Unless I'm missing something it looks like I'm good to go.

This tells you that you have a correctly built OpenSSL version that is capable of loading and using the FIPS provider. Such a version of OpenSSL is equally capable of using the default provider (which is not FIPS validated). In order to actually *use* FIPS crypto in your applications they have to be configured correctly. Refer to the man page for details:

https://www.openssl.org/docs/man3.0/man7/fips_module.html

**Comment by JordanDalton** [comment]
@mattcaswell In my case all I'm needing FIPs for is creating private & public keys, signing a file, then validating the signature. These are the steps I did to go through that process. Am I doing this right?

```
# Create a private key for a clinic

./util/wrap.pl -fips apps/openssl genpkey -algorithm RSA -outform PEM -out ~/EPCSCP/clinics_3.pem -pkeyopt rsa_keygen_bits:2048 -provider fips

# output: writing RSA key

# Create public key for the clinic
./util/wrap.pl -fips apps/openssl rsa -in ~/EPCSCP/clinics_3.pem -pubout -outform PEM -out ~/EPCSCP/clinics_3_public.pem -provider fips

# Digitally sign file which represents the order:
 ./util/wrap.pl -fips apps/openssl dgst -sign ~/EPCSCP/clinics_3.pem -out ~/EPCSCP/clinics_3_orders_262766472.bin -sha256 ~/EPCSCP/262766472.txt

# This creates: clinics_3_orders_262766472.bin 

# We now validate the digital signature
./util/wrap.pl -fips apps/openssl dgst -verify ~/EPCSCP/clinics_3_public.pem -signature ~/EPCSCP/clinics_3_orders_262766472.bin -sha256 ~/EPCSCP/262766472.txt

# Output: Verified OK
```

**Comment by mattcaswell** [comment]
> ./util/wrap.pl -fips 

This is actually not correct usage for what you want to do. That script is really an internal testing script not intended for end application usage. It uses the FIPS installation in the current build directory and a test fips config file - but doesn't use the *installed* openssl version. You need to correctly install OpenSSl (e.g. "make install"), and then ensure that you are using the fipsmodule.cnf file you generated at the "fipsinstall" stage. Refer to the README-FIPS.md file in the sources.

**Comment by JordanDalton** [comment]
@mattcaswell I've gone through the readme, but everything I have now I think is correct (alway room for error). Is there any special command I need to run? I've ran just about everything I can find from the readme files.

**Comment by mattcaswell** [comment]
Does the command `openssl list -provider fips -provider base -providers` (i.e. similar to above but without using the wrap.pl script) list the fips and base providers as expected?

Your commands for creating the private/public keys should not use the wrap.pl script - does it appear to work without that? The dgst commands that you use should also include the "-provider fips" options. All of those commands should also use "-provider base" as well.

**Comment by JordanDalton** [comment]
Without the warp I does show the FIPs provider. All other commands work without the wrap :)

Thank you all so much for your help.

**Comment by jfathman** [comment]
@paulidale 
> I'll also not that 3.0.8 is not FIPS validated. Only the 3.0.0 FIPS provider has a certificate. You should build OpenSSL 3.0.0 to get it's FIPS provider and then run the 3.0.8 library using the 3.0.0 FIPS provider.

Is that correct?  This makes me think 3.0.8 is FIPS validated, not 3.0.0:

**Comment by t8m** [comment]
Yes, currently (by mistake) only the 3.0.8 is listed as validated. This will be corrected as 3.0.0 should be still considered validated as well.

**Comment by jfathman** [comment]
Thanks @t8m.  Just to clarify, I can build the FIPS module using either 3.0.0 or 3.0.8 and the result will be FIPS approved?  I do not need to limit my build to one or the other?

**Comment by t8m** [comment]
Strictly speaking you should use only 3.0.8 for new deployments now. But as I said this is being handled and both 3.0.0 and 3.0.8 should be OK.

**Comment by paulidale** [comment]
3.0.8 became validated _after_ my earlier comment about 3.0.0 being the only one.  Apologises for any confusion.

3.0.9 is also under validation but isn't certified yet -- the only relevant change is for aarch64 using AES XTS mode.

**Comment by jfathman** [comment]
@paulidale Thank you.

If I understand the terrain correctly, my plan is to build the 3.0.8 FIPS provider and use it with whatever OpenSSL 3.x version is the latest in Debian 12 bookworm (currently 3.0.9).  That way, I benefit from recent OpenSSL security updates combined with a perhaps older but compatible clearly certified FIPS module that I can point to during any customer review or security audit.

As newer versions of the OpenSSL 3.x FIPS module achieve certification, I can update my integration to use those, but with the expectation there will likely always be a lag between OpenSSL versions and the FIPS module versions, due to the lengthy interval required to traverse the certification process.

I would like to take this opportunity to thank the OpenSSL developers for their contributions, and particularly those who work to support FIPS, which can be unsung, but is a great help to so many of us.

**Comment by paulidale** [comment]
@jfathman, pretty much spot on as to what we'd recommend.
