### ISSUE TITLE
Missing deterministic ECDSA signatures support

### ISSUE THREAD

**Issue by RJPercival** [openssl/openssl#2078]
OpenSSL does not currently appear to implement [RFC6979 - Deterministic Usage of the Digital Signature Algorithm (DSA) and Elliptic Curve Digital Signature Algorithm (ECDSA)](https://tools.ietf.org/html/rfc6979). Determinstic ECDSA signatures are required by [RFC6962-bis](https://tools.ietf.org/html/draft-ietf-trans-rfc6962-bis-21#section-12.4), the next Certificate Transparency standard.

**Comment by ofek** [comment]
Any progress?

**Comment by richsalz** [comment]
No.  Most folks are working on TLS 1.3, or other things.

**Comment by erdtman** [comment]
Any news on this? I´m trying to implement this in nodejs but have now understood that it might not even be possible. If not implemented Do we think this will be a priority any time soon or should I try to find another way forward?

**Comment by richsalz** [comment]
There *is* Ed25519, which is similar but not the same.
Perhaps those who need it can come together and create a PR with an implementation?

**Comment by YuGits** [comment]
The paper "[A Note on Fault Attacks Against Deterministic Signature Schemes (Short Paper)](https://link.springer.com/chapter/10.1007/978-3-319-44524-3_11)" says that using deterministic ECDSA as described in RFC6979 could make it vulnerable to fault attacks which could be used to recover the private key when using deterministic ECDSA. So are you sure you want to have this implemented?

**Comment by ofek** [comment]
@YuGits Yes.

**Comment by YuGits** [comment]
@ofek But why would you want something that could make ECDSA vulnerable to attacks that require the nonce to stay the same for many operations? Knowing that the current approach in OpenSSL with the SHA512(private_key + H(message) + random) already prevents predictable nonces when you have a predictable random number generator

**Comment by richsalz** [comment]
OpenSSL doesn’t define any of the standards here, we just implement them.
We should do EdDSA and we will.

**Comment by vdukhovni** [comment]
A current discussion on the OARC dns-operations list brought this issue to my attention.  In the context of DNSSEC it would be quite useful to have a deterministic signature scheme, so that the same RRsets signed with the same keys produced the same signatures.  I don't think that fault attacks are a meaningful consideration for DNS signing (datacentre machines running only DNS software).  It will be a long time before EdDSA is interoperable in DNSSEC, but ECDSA is supported now.  So this could a very useful 1.1.1 feature, if small enough to implement and review before 1.1.1 ships (yes it is now quite late in the release cycle...)

**Comment by briansmith** [comment]
> A current discussion on the OARC dns-operations list brought this issue to my attention. In the context of DNSSEC it would be quite useful to have a deterministic signature scheme, so that the same RRsets signed with the same keys produced the same signatures.

Please see https://www.ietf.org/mail-archive/web/trans/current/msg02882.html, Subject "[Trans] The RFC6979 requirement in RFC6962-bis is bad" by myself, for another working group. More generally RFC6979 is bad and meaningless to mandate in a standard, and I think the debate in that thread probably translates to your DNS use cases and many other cases where people think mandating deterministic signatures is a good idea.

See also https://bitcoin.stackexchange.com/questions/36127/problems-with-deterministic-ecdsa-based-on-rfc6979-in-bitcoin#comment42214_36142 regarding the considerable performance cost.

**Comment by ofek** [comment]
I agree this should not be the default behavior, but it most definitely should be an option.

**Comment by vdukhovni** [comment]
Firstly, the choice of deterministic signatures is not what's important here, if RFC6979 is somehow worse than other schemes, feel free to suggest a better [deterministic] scheme.  As to the points raised in the trans-WG post:

1. I'm not proposing a change in default behaviour. Rather, I'd like to see an option to get deterministic signatures.
2. A small performance hit is not consequential for off-line DNS signing, where what's far more important is reproducible results when a zone is signed on multiple master servers: https://lists.dns-oarc.net/pipermail/dns-operations/2018-June/017683.html

Without deterministic signatures, Peter Koch of DENIC is sticking with 1024-bit RSA, where-as P-256 is otherwise attractive for many reasons.  So there is a good case for the functionality with some suitable deterministic scheme.

**Comment by jamuir** [comment]
PR #18809 was recently merged, so I think this issue can be resolved/closed.
