### ISSUE TITLE
Macro definitions are really scary

### ISSUE THREAD

**Issue by colory7** [openssl/openssl#20835]

**Comment by hlandau** [comment]
Can you elaborate, or provide specific examples of what you find concerning?

**Comment by bharsaklemukesh975** [comment]
Can you provide any examples? I would like to work on this.

**Comment by levitte** [comment]
I agree, macro defs can be quite...  involved, shall we say, and difficult to follow (let alone debug).
On the other hand, block copying the swathes of resulting code would be just as scary, in my opinion.

I respond this way, because this looks much more like a general discussion topic than about some specific piece of OpenSSL code.

**Comment by colory7** [comment]
Yes, that's what I want to express

> I agree, macro defs can be quite... involved, shall we say, and difficult to follow (let alone debug). On the other hand, block copying the swathes of resulting code would be just as scary, in my opinion.
> 
> I respond this way, because this looks much more like a general discussion topic than about some specific piece of OpenSSL code.

**Comment by colory7** [comment]
> I agree, macro defs can be quite... involved, shall we say, and difficult to follow (let alone debug). On the other hand, block copying the swathes of resulting code would be just as scary, in my opinion.
> 
> I respond this way, because this looks much more like a general discussion topic than about some specific piece of OpenSSL code.

Yes, that's what I want to express
