### ISSUE TITLE
OSSL_sleep() on unix maps to usleep(3) which does not handle large values

### ISSUE THREAD

**Issue by MartinHusemann** [openssl/openssl#21009]
I ran into this by looking at why test/sanitytest fails for me.
Turns out the test tries to sleep for 1 second calling OSSL_sleep(1000).

But the unix implementation of OSSL_sleep() in most parts of the #ifdef cascade maps to `usleep(millis1000).

This has two problems:

  - usleep() has been removed from Posix, applications are recommended to use nanosleep() instead
  - usleep() does not work for times >= 1 second at least on some systems, see e.g. [usleep(3)](https://man.netbsd.org/usleep.3)

**Comment by paulidale** [comment]
Suggest we consider using OSSL_TIME and a custom sleep function.

**Comment by mattcaswell** [comment]
We should probably loop if millis >= 1000, so that we do multiple invocations of the sleep functions which are all less than 1 second.

> Suggest we consider using OSSL_TIME and a custom sleep function.

Converting it to use OSSL_TIME internally wouldn't be a bad idea for master - but I guess the "custom sleep function" is still the same sleep code that we are currently using - but converted to use OSSL_TIME instead.

I'd call this a bug if this is causing tests to fail on real systems.

The conversion to use nanosleep instead probably is more of a feature. At least until we encounter real systems that don't have usleep. We'd somehow need to detect the existence of nanosleep()  (perhaps by checking the claimed POSIX support level??).

**Comment by t8m** [comment]
This is already fixed.
