### ISSUE TITLE
Slow response when using the store X509_LOOKUP method

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#21067]
This comment:

https://github.com/openssl/openssl/pull/20952#issuecomment-1564232273

suggests that the store X509 lookup method is considerably slower than the directory X509 lookup method when looking at the same source directory (at least when used with an empty store). We should investigate why that is the case and see if there are any opportunities for optimisation.

**Comment by t8m** [comment]
For reference - this is the part that is responsible for this duplicate directory store addition:
https://github.com/openssl/openssl/blob/master/crypto/x509/x509_d2.c#L30-L33

I assume the slowness is because when going through the store lookup method, providers' OSSL_STORE implementation are involved which is inherently much slower than the simple directory lookup in by_dir lookup method.

**Comment by t8m** [comment]
This needs to be discussed within OTC along with #21068. One possibility how to "fix" this is to basically accept the change as is in master branch, i.e. do nothing about #21068 except documenting the change properly.

**Comment by arapov** [comment]
Investigate: 3sp
