### ISSUE TITLE
Build dependency problem

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#21112]
In #20935 a workaround to avoid weird build errors was introduced via b4a123100720c959b018529f15818fd5fde8a323
Ideally, this commit should be reverted and the build dependency got to work.

Even more ideally, the other generated files should depend on the scripts that build them as well.

Assigning to @levitte as the most likely to be able to fix this oddity in reasonable time.

**Comment by levitte** [comment]
Yup

**Comment by levitte** [comment]
I just tried this on one of our Macs, and yeah, this is caused by a combination of slight name conflict (we have a `config.pm` in `uitl/perl/OpenSSL`, and perl comes with `Config.pm`, and Macs file searches are case-independent), and the fact that the `DEPEND` statement combined with the `GENERATE` statement has a more involved meaning than just adding a dependency.  As a matter of fact, the `DEPEND` statement in that scenario behaves more like a `USE` statement...

So, without the DEPEND statement (the one that b4a123100720c959b018529f15818fd5fde8a323 removes), the produced rule for `include/internal/param_names.h` becomes:

```
include/internal/param_names.h: ../master/include/internal/param_names.h.in  configdata.pm
	$(PERL) "-I." -Mconfigdata "../master/util/dofile.pl" "-oMakefile" ../master/include/internal/param_names.h.in > $@
```

With that DEPEND line, the result is this instead:

```
include/internal/param_names.h: ../openssl/include/internal/param_names.h.in ../openssl/util/perl/OpenSSL/paramnames.pm configdata.pm ../openssl/util/perl/OpenSSL/paramnames.pm
	$(PERL) "-I." "-I../openssl/util/perl/OpenSSL" -Mconfigdata -Mparamnames "../openssl/util/dofile.pl" "-oMakefile" ../openssl/include/internal/param_names.h.in > $@
```

The specific item that causes the problem is `"-I../openssl/util/perl/OpenSSL"`, 'cause that's where our `config.pm` lives (it's usually loaded as `OpenSSL::config`, which is safe).

There are different ways this could be fixed...  some are ugly/hackish but means that `build.info` files may remain unchanged.  There are also a couple of possibilities that are more elegant, and probably future-proof, but will require some `build.info` changes...  but on the other hand, I hope to make `DEPEND` less involved, and thereby less confusing.  I much prefer the latter, to be honest.

**Comment by paulidale** [comment]
Fixing the case issue would be my call here: ossl-config e.g.
Windows builds produce a quite different error sadly.

**Comment by levitte** [comment]
> Fixing the case issue would be my call here: ossl-config e.g.

Yeah, but that only fixes that symptom, the deeper confusion with how `DEPEND` works isn't fixed, so renaming that file only work until we find another file name conflict.

I haven't looked at Windows yet, thanks for pointing it out

**Comment by paulidale** [comment]
We can avoid future name conflicts indefinitely without any pain.
If a developer picks a conflicting name, the CIs will pick it up and we ask for the change.

**Comment by levitte** [comment]
The Windows error is essentially the same, it's just that the Windows variant tries to load something that the Macos variant doesn't.  However, the commonality is that the loaded `util/perl/OpenSSL/Config.pm` (note the case).

`IPC::Cmd`'s failure to load `Win32` is a mystery, considering that when we do use `OpenSSL::config` properly (which we do from `Configure`), it works perfectly

**Comment by levitte** [comment]
Ah, I may have figured out a sort of hackish way that's still elegant

**Comment by levitte** [comment]
See #21117

**Comment by gvanem** [comment]
I'm getting this error when nmake is trying to generate `include/openssl/core_names.h`:
```
F:\MinGW32\src\inet\Crypto\OpenSSL> nmake
  "f:/util/StrawberryPerl/perl/bin/perl.exe" "-I." -Mconfigdata "util\dofile.pl" "-omakefile" "crypto\params_idx.c.in" > crypto\params_idx.c
"my" variable $trieref masks earlier declaration in same scope at F:/MinGW32/src/inet/Crypto/OpenSSL/util/perl/OpenSSL/paramnames.pm line 640.
syntax error at F:/MinGW32/src/inet/Crypto/OpenSSL/util/perl/OpenSSL/paramnames.pm line 582, near "$cursor{"
Global symbol "$cursor" requires explicit package name at F:/MinGW32/src/inet/Crypto/OpenSSL/util/perl/OpenSSL/paramnames.pm line 584.
Global symbol "%trie" requires explicit package name at F:/MinGW32/src/inet/Crypto/OpenSSL/util/perl/OpenSSL/paramnames.pm line 588.
syntax error at F:/MinGW32/src/inet/Crypto/OpenSSL/util/perl/OpenSSL/paramnames.pm line 589, near "}"
syntax error at F:/MinGW32/src/inet/Crypto/OpenSSL/util/perl/OpenSSL/paramnames.pm line 636, near "}"
syntax error at F:/MinGW32/src/inet/Crypto/OpenSSL/util/perl/OpenSSL/paramnames.pm line 662, near "}"
syntax error at F:/MinGW32/src/inet/Crypto/OpenSSL/util/perl/OpenSSL/paramnames.pm line 673, near "}"
Compilation failed in require at crypto\params_idx.c.in line 12.
BEGIN failed--compilation aborted at crypto\params_idx.c.in line 12.
NMAKE : fatal error U1077: '"f:/util/StrawberryPerl/perl/bin/perl.exe" "-I." -Mconfigdata "util\dofile.pl" "-omakefile" "crypto\params_idx.c
.in" > crypto\params_idx.c' : return code '0x1'
Stop.
```

What??!!

**Comment by gvanem** [comment]
@tom-cosgrove-arm From `master`:
```
perl.exe -I. -I./util/perl -I./crypto/perlasm -I./crypto/bn/asm -I./crypto/des/asm Configure ^
VC-WIN64A-ONECORE no-makedepend enable-tls1_3 enable-md2 enable-asm enable-quic enable-brotli ^
enable-zlib enable-zstd enable-crypto-mdebug enable-trace no-ec_nistp_64_gcc_128 enable-asan ^
enable-aria enable-rc5 enable-heartbeats
```

Followed by `nmake` which gives the error above. From Strawberry's `perl.exe -v`
```
This is perl 5, version 18, subversion 4 (v5.18.4) built for MSWin32-x86-multi-thread-64int
```
