### ISSUE TITLE
openssl3.0 universal libs crash in our app on mac

### ISSUE THREAD

**Issue by aniljadaun** [openssl/openssl#21246]
I created x86_64 and arm64 dylib binaries for mac. 
This generated symlink libcrypto.dylib which points to libcrypto.3.dylib
also libssl.3.dylib . 
Originally our app used libcrypto.dylib , libssl.dylib . So i deleted symbolic link and renamed  libcrypto.3.dylib as libcrypto.dylib and 
libssl.3.dylib as libssl.dylib  . Now when i try to run my app on mac , i get instant crash.

console  logs :
dlopen(/Applications/sample app/sample.app/Contents/Frameworks/samplelib.framework/sample, 265): Library not loaded: /Users/anils/openssl/x86_64/dll/release/lib/libssl.3.dylib

Though i have not given any reference of this lib in my code . i am not sure where am i getting this error from. why is it try to find reference from originally created dylib and not name change dylib. ?

Does libcrypto internally references and load libssl.3.dylib ?
Is direct name changing not allowed ?
How do i make sure to use libcrypto.dylib and libssl.dylib name for the openssl libs with out the number reference ?

**Comment by paulidale** [comment]
Suggestion: don't change the names.

OpenSSL doesn't load either, this happens from your application (probably via a dynamic linker).

**Comment by levitte** [comment]
When you link your program with dynamic libraries, the "real name" (libssl.3.dylib, for example) is stored in the program image, so when the program is activated, it knows what file to look for.

Because you've removed (renamed) the file that has the "real name", your program can't start.

The symlink is a convenience, so the programmer doesn't have to remember the version of the default library installation.
