### ISSUE TITLE
Avoid bad behavior with empty OPENSSL_CONF

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#21258]
For example (and this might not be the only case):
```
diff --git a/crypto/conf/conf_mod.c b/crypto/conf/conf_mod.c
index 17bbbf7a27..62af600f36 100644
--- a/crypto/conf/conf_mod.c
+++ b/crypto/conf/conf_mod.c
@@ -628,7 +628,8 @@ char *CONF_get1_default_config_file(void)
     char *file, *sep = "";
     size_t size;
 
-    if ((file = ossl_safe_getenv("OPENSSL_CONF")) != NULL)
+    if ((file = ossl_safe_getenv("OPENSSL_CONF")) != NULL
+           && *file != '\0')
         return OPENSSL_strdup(file);
 
     t = X509_get_default_cert_area();
```

**Comment by mspncp** [comment]
Thanks for the report, Rich. It might be better to fix it inside `ossl_safe_getenv()` generically instead of sprinkling workarounds at the call sites, do you agree?

**Comment by mspncp** [comment]
I also slightly tend towards bug fix, not feature request, because it that's the behavior a human would expect.

**Comment by richsalz** [comment]
I reported it as a bug.  It should be backported, we're running into it and the behavior is, as you say, not expected.  I don't know if `safe_getenv` is the place to do it, because that treats all empty assignments as unset; think about it, such as the impact on the `ia32cap` variable.  But if you're comfortable, okay.

**Comment by mspncp** [comment]
Thanks for the heads-up about `OPENSSL_ia32cap` (and friends): it seems indeed to make a difference whther the variable is set to an empty string

https://github.com/openssl/openssl/blob/a02571a02473889d13fe7996e0d2d052328f3199/crypto/cpuid.c#L106-L109

or whether it is unset

https://github.com/openssl/openssl/blob/a02571a02473889d13fe7996e0d2d052328f3199/crypto/cpuid.c#L146-L148

because in the former case the empty string is converted naively to a zero integer. So changing `safe_getenv()` to consistently treat empty environment variables as unset seems to break this use case  (what's your opinion about it @bernd-edlinger, do we need to care about the first case, or can we treat an empty `OPENSSL_ia32cap` variable as an unset one?)

On the other hand, I feel extremely uncomfortable about treating environment variables differently depending on their name.
[Using roughly your own words](https://github.com/openssl/openssl/pull/15653#issuecomment-1604198863),

> it would be bad if *one part* of OpenSSL did treat empty environment variables as unset while the other part did not.

MayI turn the question around @richsalz? Isn't it standard Posix semantics that `getenv` distinguishes between an unset variable and variable set to an empty string, where in general only the unset variable guarantees that you get the default value? So why can't you just unset the variable in your use case instead of requesting a change of semantics for a specific environment variable?

_I would like to hear what other project members (@t8m? @hlandau?) think about making an exception for `OPENSSL_CONF` and possibly `OPENSSL_CONF_INCLUDE`?_

**Comment by t8m** [comment]
IMO this definitely should NOT be done in ossl_safe_getenv().

**Comment by t8m** [comment]
Also I'm not even sure this should be done anywhere. Empty environment variables are a distinct thing from unset ones and people could already depend on the existing behavior.

**Comment by richsalz** [comment]
`OPENSSL_CONF` is special, because an empty value can mean "read the directory" as a config file, which fails on some platforms, not others. It  can also just hang (we've seen it) on some platforms, not others.  I think not having standard behavior for at least that env var is a bug.  Look at the `conf_mod.c` file and see how it's used.

**Comment by t8m** [comment]
Then that's a bug, but the fix should be different.

**Comment by richsalz** [comment]
I don't agree with that reasoning: It is relying on undocumented platform-specific behavior. If you want to preserve that, then close this as "not a bug"

**Comment by t8m** [comment]
We do not want random platform-specific behavior. On the other hand the #21282 delivers non-random behavior that basically keeps backwards compatibility with what most platforms already do.
