### ISSUE TITLE
RSA_generate_key API 1.0.2q and 3.0.8

### ISSUE THREAD

**Issue by nagu1137** [openssl/openssl#21345]
Hi Is RSA_generate_key() method is deprecated in 1.0.2q version or not.
it is confusing from the rsa.h file.
![Capture](https://github.com/openssl/openssl/assets/98408015/a560d35e-a780-40e4-ab87-3cbdb24150d2)

Also is it allowed and correct to use the deprecated functions?
i see that we are using the above method in 1.0.2q in our application

I see the same function is marked as deprecated in 3.0.8 library.

**Comment by t8m** [comment]
The function is deprecated since 0.9.8 version. The annotations in 1.0.2 were not fully complete - i.e. there the usage would not show a deprecation warning.

In 3.0 all the low-level RSA functions were deprecated, so not just RSA_generate_key but also the RSA_generate_key_ex which was not deprecated in 1.0.2.

You can of course use deprecated functions but there are some consequences. These functions can be removed in future major versions (i.e., 4.0) and also using deprecated low-level crypto functions such as this one implies that the application will not be FIPS compliant.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
