### ISSUE TITLE
Assertion failure in the QUIC TXP

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#21369]
Running the test added in #21368 results in the following assertion failure:

````
ssl/quic/quic_txp.c:2218: OpenSSL internal error: Assertion failed: h.bytes_appended > 0
````

**Comment by hlandau** [comment]
As I suspected, this is due to a mismatch in the criteria for the functions to determine if a packet should be generated (pending) and the functions to actually generate a packet. A packet with a zero-length payload is not allowed in QUIC. We expect our pending function to be completely accurate here.

The specific problem is that congestion control is limiting the size of the packet generated to 24 bytes (which is fine) which leads to a maximum payload size of 3 bytes. The TXP wants to generate an ACK frame, but there is not enough room to encode one.

Fix might be a bit awkward; thinking about it.

**Comment by kroeckx** [comment]
Doesn't QUIC have a 1200 minimum packet size?

**Comment by hlandau** [comment]
> Doesn't QUIC have a 1200 minimum packet size?

To be specific, QUIC requires that a network path be able to support a maximum UDP datagram payload size of 1200 bytes. A QUIC datagram can contain multiple QUIC packets in the same datagram, so a single QUIC packet may need to be constructed to a budget of less than 1200 bytes if a packet has already been placed in the datagram, partially consuming the 1200 byte budget for that datagram. A budget of less than 1200 bytes could also occur due to limits imposed by the congestion controller.
