### ISSUE TITLE
what is the last version?

### ISSUE THREAD

**Issue by fatemehajikarami** [openssl/openssl#2152]
Hi
Is the last version of myssl 1.1.0? (according to https://www.openssl.org/source/)
So why in readme (https://github.com/openssl/openssl/readme) it said that the version is 1.1.1?
I am so confused!
When I want to see my version, after typing "myssl version" comment, I got this:
OpenSSL 1.1.1-dev  xx XXX xxxx

I don't know my openssl version and other than that I want to have version 1.0.2, what should I do?

**Comment by mattcaswell** [comment]
> Is the last version of myssl 1.1.0? (according to https://www.openssl.org/source/)

Not sure what "myssl" is, But the latest version of "openssl" is 1.1.0

> So why in readme (https://github.com/openssl/openssl/readme) it said that the version is 1.1.1?
> I am so confused!

Well the above link is a 404 for me. Probably you were looking at this:

https://github.com/openssl/openssl/blob/master/README

This references version 1.1.1-dev. That's because that link is for the unreleased development version of OpenSSL. The link for the latest released version of the README on github is here:

https://github.com/openssl/openssl/blob/91eaf079b7430cb4ebb7f3ccabe74aa383b27c4e/README



>When I want to see my version, after typing "myssl version" comment, I got this:
> OpenSSL 1.1.1-dev xx XXX xxxx

Again, I don't know what "myssl" is. The above version information indicates you are using the development version of OpenSSL which has not been released and should not be used for production purposes.

> I don't know my openssl version and other than that I want to have version 1.0.2, what should I do?

The 1.0.2 version is available as a download from here:
https://www.openssl.org/source/

**Comment by fatemehajikarami** [comment]
I wrote myssl instead of openssl!! :| sorry for this

**Comment by fatemehajikarami** [comment]
How can I remove the 1.1.1 version?
