### ISSUE TITLE
Pkey methods PRF and HKDF only use the provider API

### ISSUE THREAD

**Issue by ShuaiYuan21** [openssl/openssl#21622]
In OpenSSL 3.0, the function tls1_PRF() will just fetch the default provider to do KDF, but there is no judgment for the scene using the engine API. Is it possible to add support for engine API? (HKDF also has the same issue)

For example, first judge whether it is a legacy case, if yes, call the engine API, otherwise call the provider API.

OpenSSL 3.0: 
https://github.com/openssl/openssl/blob/5c56cef501c5344a0e1c1061b356e74c24ca1cef/ssl/t1_enc.c#L48-L72
OpenSSL 1.1.1: 
https://github.com/openssl/openssl/blob/fe824ce0c5d51e7e7cf36c31db6c49c1c0c04a25/ssl/t1_enc.c#L41-L50

**Comment by paulidale** [comment]
I'm not entire sure what you are asking about here.  The second code segment should still work, it's deprecated and won't be removed until at least 4.x but it should still work.  HKDF isn't supported via the PKEY interface and never will be.

The project has been pretty clear since 3.0 was released: there will not be any further enhancements to the engine APIs.  They are deprecated and providers are the replacement.
