### ISSUE TITLE
Documentation of thread safety

### ISSUE THREAD

**Issue by triska** [openssl/openssl#2165]
Regarding **thread safety** of OpenSSL, we find the following statements in the official documentation:

The documentation on OpenSSL [**threads**](https://www.openssl.org/docs/man1.0.2/crypto/threads.html) states (at least for version&nbsp;1.0.2):

<pre>
<b>OpenSSL can safely be used in multi-threaded applications</b> provided that at least two 
callback functions are set, locking_function and threadid_func.
</pre>

The [ChangeLog](https://www.openssl.org/news/cl110.txt) of version 1.1.0 states:

<pre>
  *) OpenSSL now uses a new threading API. <b>It is no longer necessary to
     set locking callbacks to use OpenSSL in a multi-threaded environment.</b> There
     are two supported threading models: pthreads and windows threads. It is
     also possible to configure OpenSSL at compile time for "no-threads". The
     old threading API should no longer be used. The functions have been
     replaced with "no-op" compatibility macros.
     [Alessandro Ghedini, Matt Caswell]
</pre>

Contradicting or hedging these statements, the following statements are made by OpenSSL core developers in&nbsp;#2147 :

-  "the objects cannot be used concurrently in multiple threads"
- "*any* modification of openssl data structures is not safe"
- "OpenSSL has never supported concurrent use of its data objects."
- "the documentation is wrong, or misleading or incomplete"
- "The safety for use in multi-threaded applications means that there is not (unlocked) global state in the library that could be modified by concurrent calls from different threads, such as a global error queue or a static counter for the next free index into an array. "

Please correct and update the library **documentation** so that it is clear and accurately documented:

- what *is* regarded safe
- what is *not* regarded safe.

In particular, the following use case warrants attention (for example): Is it *safe* to *create* an SSL&nbsp;context, and then use the exact same context to *negotiate* concurrent connections in multiple&nbsp;threads?

**Comment by richsalz** [comment]
To address the last question:  OpenSSL does not guarantee that any of its objects can be used concurrently by multiple threads.  Therefore, the answer is no; you'll have to lock it.

**Comment by davidben** [comment]
Hrm? An `SSL_CTX` may be used on multiple threads _provided it is not reconfigured_. (Even without threads, reconfiguring an `SSL_CTX` after calling `SSL_new` will behave weirdly in places.) Observe that the session cache is locked and everything. Also observe that an `RSA` object goes through a lot of trouble to work around `RSA_new` + setters (a better API pattern would be functions like `RSA_new_private` and `RSA_new_public` which take all their parameters in a single shot and then remove all `RSA_set*` functions) with `BN_MONT_set_locked` so that two threads may concurrently perform operations. This is, in part, so that two `SSL`s on different threads may sign with that shared key in the `SSL_CTX`.

The API typically considers "logically immutable" _use_ of an object to be safe across threads (otherwise there would be little point in even thread-safe refcounts, much less `CRYPTO_THREAD_*_lock`), but "logically mutable" _reconfiguring_ an object to not be. Of course, the key bits here are "typically" and the scare quotes, so better documentation is probably worthwhile.

**Comment by richsalz** [comment]
@davidben You are right -- I went too far.  We need to consider what are implementation details, and what guarantees we can/should provide.  I consider your comment about ssl_ctx/ssl_new to be buggy behavior, for example -- else why refcount :)

**Comment by vdukhovni** [comment]
@richsalz Not sure what buggy ssl_ctx/ssl_new behaviour you have in mind Rich?  The ref count is there so that the SSL_CTX can be automatically freed when the last associated SSL object is freed:

```
    ctx = SSL_CTX_new(...);
    /* create one or more SSL handles */
    ssl = SSL_new(ctx, ...);

   /* Free the context, no more handles will be created with it */
    SSL_CTX_free(ctx);
    
  /* Continue using already created SSL handles, destruction of the last one will trigger deallocation of the SSL_CTX */
```

**Comment by richsalz** [comment]
Not me, @davidben

**Comment by davidben** [comment]
I'm actually not sure what you meant either. :-)

My claim was:
* A thread may not reconfigure an `SSL_CTX` while another thread is accessing it.
* Even stronger, if there is an `SSL` attached to the `SSL_CTX`, reconfiguring the `SSL_CTX` should probably be undefined (except when documented otherwise). This is how BoringSSL is documented to behave. This is because some fields are copied from `SSL_CTX` to `SSL` while others are referenced directly off of `SSL_CTX`. Reconfiguring the `SSL_CTX` will behave differently depending on this. If you look at the set of APIs there are, it's not clear either interpretation makes particular sense as universal. I think it's best to just say you don't get to do that. Less combinatorial explosion of cases to test.

But this is somewhat tangential to the thread-safety point.

**Comment by kaduk** [comment]
> Contradicting or hedging these statements, [...]

There is no contradiction; the former statements are about being thread-safe in the way that strerror_r() is thread-safe and strerror() is not.  (It does not mean anything about concurrent access to given data structures from multiple threads.)  That is, it was common in really old C libraries to structure things so that having multiple concurrent threads of execution would cause the library to completely fall over.  Given that it's 2017, it might be less confusing to not mention anything at all about that sort of thread-safety, as no one should be assuming that C libraries only support single-threaded execution anymore.

It would also be really helpful if you could point to where you would be looking for the documentation you want to see -- a particular manual page, for example.  Otherwise we have to guess, which is likely to leave you unhappy.

**Comment by triska** [comment]
> It would also be really helpful if you could point to where you would be looking for the documentation you want to see -- a particular manual page, for example.

Please first write down what is actually meant by "thread-safe" in the context (and other data&nbsp;structures) of OpenSSL. For example, is it generally true that multiple threads can safely use the same object as long as no functions are called that *modify* certain aspects of these objects? If so, how do we know which of the provided interface functions satisfy this property, i.e., what are the criteria for these aspects? For example, are these *always* distinguished by their *name*, or is their name generally an indication of such properties with a few exceptions, or is their name no indication whatsoever about these properties?

Depending on how general such safety properties are within OpenSSL, certain places of the manual will be more suitable than others. This can range from modification of several man pages describing individual functions to a general clarification in the ChangeLog of the next release, for example. It also depends on which parts can be most generally covered. For example, if it essentially boils down to "`ERR_get_error()` is thread&nbsp;safe, everything else is unsafe", then the best place to document it would be different than if the converse were&nbsp;true.

**Comment by richsalz** [comment]
Please see https://www.openssl.org/blog/blog/2017/02/21/threads/

This is all we are going to document for now.

**Comment by triska** [comment]
In my opinion, a blog post (and in particular this one) does *not* adequately address this issue.

Please consider reopening this issue until it is fully resolved in the library&nbsp;**documentation**.

**Comment by C8LUKA** [comment]
@richsalz sorry to disturb you，I read the https://www.openssl.org/blog/blog/2017/02/21/threads/，but I still confused，if I follow the suggestion，mean multi-thread safe for openssl API call or something(I noticed that you mention the ssl object is not thread safe)

**Comment by richsalz** [comment]
I am sorry, but I don't understand your question.  Two different threads cannot use an OpenSSL object at the same time.

**Comment by triska** [comment]
@richsalz: When you say "Two different threads cannot use an OpenSSL object at the same time.", then this is different from what @davidben said in https://github.com/openssl/openssl/issues/2165#issuecomment-270007943, and which you agreed to in https://github.com/openssl/openssl/issues/2165#issuecomment-270009469.

To users of this library, whether or not two different threads can use an OpenSSL object at the same time is an elementary design&nbsp;parameter that can have profound effects on their program architectures and on the correctness and efficiency of their programs. 

To me, it is surprising to see so widely diverging opinions expressed about such a foundational usage question regarding this library. I would greatly appreciate clarification about these questions.

**Comment by t8m** [comment]
I think @richsalz meant a SSL object where in the #2165 comments the SSL_CTX is talked about.

**Comment by C8LUKA** [comment]
thanks to reply me
before version 1.1.0，we setup the function as：
CRYPTO_set_locking_callback 
CRYPTO_set_id_callback
to make thread safe,but two different threads cannot use an OpenSSL object at the same time.
that`s why I confused, and try to find out: 
after following the suggestion，the "multi-thread safe" is set for openssl API call or ssl object.

**Comment by C8LUKA** [comment]
@t8m that`s anthoer question I want to ask for advice: 
the ssl connection created by the SSL_CTX is not thread safe, and we try to lock it between two thread.
we should lock just ssl connection or we must lock SSL_CTX at same time(ssl connection is the member of SSL_CTX, SSL_CTX may mgr the member status)

**Comment by t8m** [comment]
As davidben writes above - if SSL_CTX is not being reconfigured (i.e. read access only) (which it should not be with living SSL objects created from it anyway) there should be no need to lock it.

**Comment by richsalz** [comment]
OpenSSL now uses the local platform thread mechanisms.  You don't need to set the locking callback any more, it will use pthreads or Windows mutexes.  

The requirements to lock things, to use them safetly at the same time with multiple threads, and the documentation (sadly) *has not changed.*

Realistically, I do not expect the project (I'm not a member) to work on this any time soon.

**Comment by andreffrosa** [comment]
From this discussion I could not understand if how we could create a multi-threaded TLS server, i.e., upon accepting a TCP connection launch a new thread to handle that connection. How do I integrate SSL into this with thready safety?

**Comment by mattcaswell** [comment]
> From this discussion I could not understand if how we could create a multi-threaded TLS server, i.e., upon accepting a TCP connection launch a new thread to handle that connection. How do I integrate SSL into this with thready safety?

Create an SSL_CTX before you start. Once created don't modify it. Yes, upon accepting a TCP connection you can launch a new thread to handle that connection. Create an SSL object for that connection (based on the SSL_CTX you created at the start). Make sure that the SSL object is only ever accessed by one thread.

**Comment by andreffrosa** [comment]
> 
> 
> > From this discussion I could not understand if how we could create a multi-threaded TLS server, i.e., upon accepting a TCP connection launch a new thread to handle that connection. How do I integrate SSL into this with thready safety?
> 
> Create an SSL_CTX before you start. Once created don't modify it. Yes, upon accepting a TCP connection you can launch a new thread to handle that connection. Create an SSL object for that connection (based on the SSL_CTX you created at the start). Make sure that the SSL object is only ever accessed by one thread.

Than you! Should I create the SSL object inside the thread or prior to launching it?

**Comment by mattcaswell** [comment]
> Than you! Should I create the SSL object inside the thread or prior to launching it? (or it does not matter?)

Either is fine. It makes no difference as long as you make sure that the SSL object is only ever accessed by one thread at a time.

**Comment by udiakasnuke** [comment]
I'll just scratch on this thread again, I am migrating to 1.1.1 from 1.0.2, after reading a lot of threads i am still a bit confused. I will just write what i inferred from my reading - 
With 1.1.1 there is now no need for the application to setup the static and dynamic callbacks which we used to do for 1.0.2 .
eg - for static callbacks - 
```
CRYPTO_set_id_callback(thread_id)
CRYPTO_set_locking_callback(locking_function)
```

for dynamic callbacks - 
```
CRYPTO_set_dynlock_create_callback(dyn_create_function);
CRYPTO_set_dynlock_lock_callback(dyn_lock_function);
CRYPTO_set_dynlock_destroy_callback(dyn_destroy_function);
```
Can i now safely assume that i can remove all these functions(obviously i had to, since its not supported in 1.1.1) and all the things that application implemented for these functions, i meant all the functions(dyn_create_function, dyn_lock_function, dyn_destroy_function etc) n all and can still assume that OpenSSL would work just fine since platform dependent threading implementation has been handled by openssl itself internally and that applications don't need to do anything about it.

Also what does it actually mean by new threading API, i hope it meant platform dependent threading which openssl implemented internally.

Everything said, does application need to do anything extra on all these front or i can just remove everything and be care fre about it ?? Thanks!! Best Luck!!

**Comment by mattcaswell** [comment]
> With 1.1.1 there is now no need for the application to setup the static and dynamic callbacks which we used to do for 1.0.2 .

Correct

> Can i now safely assume that i can remove all these functions(obviously i had to, since its not supported in 1.1.1) and all the things that application implemented for these functions, i meant all the functions(dyn_create_function, dyn_lock_function, dyn_destroy_function etc) n all and can still assume that OpenSSL would work just fine since platform dependent threading implementation has been handled by openssl itself internally and that applications don't need to do anything about it.

Yes.

> Also what does it actually mean by new threading API, i hope it meant platform dependent threading which openssl implemented internally.

Yes. OpenSSL will automatically either use pthreads or windows thread support automatically based on the platform it is running on.

> Everything said, does application need to do anything extra on all these front or i can just remove everything and be care fre about it ??

Applications still need to be careful about how they use the APIs - you can't be completely care free!! For example you can't share most OpenSSL data structures between threads. So - it is thread safe to call `SSL_read` from two different threads as long as each thread is using a different SSL object. But it is *not* thread safe to call `SSL_read` from two different threads using the *same* SSL object.

**Comment by t8m** [comment]
There is some fairly incomplete manual page openssl-threads(7) in master now. Not sure it can be considered good enough to close this.

**Comment by richsalz** [comment]
This issue has become a place to ask/answer random threads questions. I think, given #13788, it should be closed.

**Comment by t8m** [comment]
Yep, anything missing in the manual in regards to the thread safety, can be ideally reported as new PRs, or issues :grin:
