### ISSUE TITLE
PEM_read_bio_X509 return NULL in centos

### ISSUE THREAD

**Issue by OliviaSnail** [openssl/openssl#21650]
I tried openssl in centos and ubuntu using same code, it works well in ubuntun  but not in centos.
In centos, the function PEM_read_bio_X509 return NULL, 
and using ERR_error_string get "Error reading certificate: error:00000000:lib(0):func(0):reason(0)"
I have tried 2 versions: 1.1.1 and 3.0.9, both not work.

The code is below:

    X509_STORE* caStore = X509_STORE_new();
    if (caStore == nullptr) {
        return nullptr;
    }
    BIO* bio = BIO_new_mem_buf(pca_crt, -1);
    if (bio == nullptr) {
        //std::cerr << "Failed to create BIO" << std::endl;
        DEBUG("Failed to create BIO");
        X509_STORE_free(caStore);
        return nullptr;
    }
    X509* caCert = PEM_read_bio_X509(bio, NULL, 0, NULL);
    if (caCert == NULL) {
        unsigned long err = ERR_get_error();
        char *errStr = ERR_error_string(err, NULL);
        fprintf(stderr, "Error reading certificate: %s\n", errStr);
        DEBUG("Failed to read CA certificate from PEM");
        BIO_free(bio);
        X509_STORE_free(caStore);
        return nullptr;
   }

The log is below:
Error reading certificate: error:00000000:lib(0):func(0):reason(0)
verify-ssl  - Failed to read CA certificate from PEM

The script to generate certificate is below:

echo $serial
st=$[ $(date '+%s') / 86400 ]
et=$[ ${st} + 365 ]

if [ ! -f "server.key" ] ; then
    echo "create CA key and CA crt file: server.key, server.crt"
    openssl genrsa -out server.key 2048
    openssl req -new -x509 -days 3650 -key server.key -out server.crt 
fi

echo "create client key: ${client_name}.key"
openssl genrsa -out ${client_name}.key 2048

echo "create client csr: ${client_name}.csr"
openssl req -new -key ${client_name}.key -out ${client_name}.csr  

echo "create client crt: ${client_name}.crt"
openssl x509 -req -in ${client_name}.csr -out ${client_name}.crt -days 3650 \
    -CAcreateserial -CA server.crt -CAkey server.key \
    -CAserial serial

**Comment by mattcaswell** [comment]
Can you share what the contents of the `pca_crt` buffer actually look like?

**Comment by nhorman** [comment]
It looks like PEM_read_bio is failing internally on centos, as that would return NULL with an empty error, such as you are seeing. That in turn might be caused by PEM_read_bio_ex, which fails without pushing to the error stack for a few reasons like a failure to extract the Certificate CN or header.

Are you ok modifying the library to debug?  in PEM_read_bio_ex you could amend the failure case to push a custom error (or just fprintf for debugging) to announce that the library failed in the calls to get_name or get_header_and_data.  That would help narrow down the cause

**Comment by nhorman** [comment]
marking as inactive, will be closed at the end of the 3.4 dev cycle barring further input

**Comment by WinserverSupport** [comment]
> Can you share what the contents of the `pca_crt` buffer actually look like?

I am having serious issues with OpenSSL PEM_read_bio_X509 or PEM_read_x509 across different platforms.  No problems on a local machine, but on an AWS instance running code and accessing files:

local folder file - success
shared mapped folder access -  hung or lucky to see error 67.

I have exhausted many C/C++ coding workarounds and with the helped of GPT4,  we are concluding, this is leaning towards a serious overlooked problem in those functions - They should NEVER hang an application  - regardless of OS or network environment.  

1) Using fopen() appears to work across the board when compiling and linking applink.c
2) using BIO_new_file() hangs on AWS Windows instances when references a shared mapped folder.  Not local.

When is PEM_read_*_X509() blaming the consumer? It has no internal fault checks.

**Comment by WinserverSupport** [comment]
> marking as inactive, will be closed at the end of the 3.4 dev cycle barring further input

I am just getting involved and updating to 3.4, I can't say my observations are 3.4 specific, but I have exhausted how to eliminate HANGs and ABORTS using PEM_read_*_X509 depending on the OS, the network environment.  Opening local files appear to be ok (when linking in applink.c) but when the source is a mapped folder/file, it hangs the application.   The behavior is not consistent with LAN vs WAN file paths. 

My question is, why isn't PEM_read_*_X509() 100% protected against against faults related to WAN I/O?

This is becoming a show stopper hence why I am commenting.  Keep it open please.

**Comment by Sashan** [comment]
I think part of the problem is that it's hard to tell a difference between file corruption (permanent error) and temporal introduced by network when we read file from remote share. I think it is a network here to blame. The network which
provides a file needs to decide if call to `fread()` needs to be kept blocked or interrupted. If it gets interrupted then
the `fread()` returns less data than caller is asking for. If caller reads from file less data than it expects, then caller (OpenSSL here) thinks file is corrupted it makes no sense to continue and bails with error. This is exactly what happens on many places.  Snippet below comes from `PEM_read_bio_ex()`:
```
 982     *data = PEM_MALLOC(len, flags);
 983     if (*header == NULL || *data == NULL)
 984         goto out_free;
 985     if (headerlen != 0 && BIO_read(headerB, *header, headerlen) != headerlen)
 986         goto out_free;
 987     (*header)[headerlen] = '\0';
 988     if (BIO_read(dataB, *data, len) != len)
```
at line 985  we ask BIO  read `headerlen` of data to continue parsing the pem file.
If we are reading from file the `BIO_read()` calls to `fread()`. If `fread()` returns less
than expected then it is an error. Because headerlen value comes from the same file
it says: next chunk of data is _n_ bytes long. However if `fread()` is not able to read _n_
bytes, then file must be corrupted.

If the file comes from network share mounted to your system then yes, `fread()` may
block indefinitely or return prematurely (depending on what network thinks is the best
course of action). All this is out of hands of library.

**Comment by WinserverSupport** [comment]
Isolating rapid testing code, I was able to zoom in on the problem not as a lock or fault but very long network delays (40-60 seconds) when using BIO_new_file() for PEM_read_bio_X509().  No problem with using fopen() and no problem with custom BIO methods for RPC client/server file I/O.   To avoid the delays, the solution was to read the data into a BIO mem buffer for PEM_read_bio_X509 to read/parse.

I agree. Its out of the hands of the library.   

Thanks

**Comment by davidben** [comment]
Windows? You might be running into https://github.com/openssl/openssl/pull/25716, a perf regression on 3.x.

**Comment by petrovr** [comment]
На 21.11.24 г. в 20:24 ч., David Benjamin написа:
> Windows? You might be running into https://github.com/openssl/openssl/pull/25716, a perf regression on 3.x.
> 

a) read operation may return less bytes - applicable on any OS. Depend 
from many things. Work-around is so called "atomic io" code.
Remark: operation could be terminated by signal.

b) windows - because of end of line conversion in "text mode" function 
may return less bytes read.
Remark \r\n is counted as one \n.

Regards,
Roumen Petrov

**Comment by WinserverSupport** [comment]
> Windows? You might be running into #25716, a perf regression on 3.x.

Looking at #25716, yes, its interesting to see this is a Raw vs Cooked file I/O problem. 

Retesting with BIO_new_file(szFileName, "rb")  worked.  No Delays.

This tells me the issue is how library is reading in the data  under cooked mode.

Tracing the code, I see areas that are questionable in  crypto\pem\pem_lib.c, i.e. comparing with "\n".  This is why it works in raw (binary) mode. 

The reader needs to take into account the known EOL environments:

- DOS (\r\n)
- Mac (\n) and
- *nix (\r).

I believe VMS falls under *nix.   

I now think this is a library issue.   The reader is not generic enough for all known EOL environments.  

Thanks for the follow up.
