### ISSUE TITLE
Compiling EVP_aes_128_ctr

### ISSUE THREAD

**Issue by liorbiu** [openssl/openssl#2175]
I'm trying to compile one of my files that include `<openssl/evp.h>`
When I'm trying to compile the code : 
```
EVP_CIPHER* cipher;
cipher = EVP_aes_128_ctr();
```
I got the following error: `‘EVP_aes_128_ctr’ was not declared in this scope`.
I noticed in `<openssl/evp.h>` that this function is under a pre-compiled header `#ifndef OPENSSL_NO_AES`

In my code I never defined `OPENSSL_NO_AES`.

The problem exist in the new version of OpenSSL - 1.1.0, in the previous version of OpenSSL I didn't had such problem.

**Comment by richsalz** [comment]
This is on Windows?  How do you configure and build?

**Comment by liorbiu** [comment]
I'm using CentOS 7.3.
The build was done via CentOS package manager `yum install openssl-devel.i686`.
I installed it again, and now I'm getting the another error:
`error: invalid use of incomplete type ‘HMAC_CTX {aka struct hmac_ctx_st}`

**Comment by dot-asm** [comment]
As for EVP_aes_128_ctr(). I'd recommend to use EVP_get_cipherbyname. The idea is that application should rather query crypto capabilities at run-time, rather than at compile/link time.

As for last error. It can't be helped without context. I mean it's impossible to provide any advice based on referred error line *alone*. However, it appears to be 101-kind of error, and chances are that C programmer next to you would be able to provide the hint...

**Comment by liorbiu** [comment]
@dot-asm  thanks for your reply.

The error occured to me at the line:
`return EVP_MD_size(hmac->md);`
While `hmac` is defined as `HMAC_CTX *hmac`

I looked at OpenSSL [documentation](https://www.openssl.org/docs/man1.1.0/crypto/EVP_DigestInit.html) and I'm sending the correct parameter (`md` is defined inside `hmac` as `const EVP_MD*` )

**Comment by richsalz** [comment]
The "invalid use of incomplete type" message is because the HMAC type is now opaque.  You have to use an accessor, ```HMAC_CTX_get_md``` to get the digest field.  Or, do what @dot-asm suggested.
