### ISSUE TITLE
QUIC address requirements

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#21949]
The SSL_set1_initial_peer_addr() documentation currently says:
`Where a QUIC connection object is provided with a write BIO which supports the BIO_CTRL_DGRAM_GET_PEER control (for example, BIO_s_dgram), the initial destination peer address can be detected automatically; if BIO_CTRL_DGRAM_GET_PEER returns a valid (non-AF_UNSPEC) peer address and no valid peer address has yet been set, this will be set automatically as the initial peer address. This behaviour can be overridden by calling SSL_set1_initial_peer_addr() with a valid peer address explicitly.`

This seems to imply that OpenSSL requires this address, and I see no good reason why QUIC/UDP would require OpenSSL to know the address while it does not for TLS/TCP. It should be possible to use QUIC/UDP without OpenSSL knowing about this information.

**Comment by hlandau** [comment]
QUIC supports connection migration which means it has to be L4-address aware. In future we will support this behind the scenes automatically.

While we do not support migration yet APIs need to be designed with this in mind to avoid the need for changes down the line.

There are also RFC recommendations which require considering L4 addresses even if migration is not supported. For example, RFC 9000 s. 9.6 says: "If a client receives packets from a new server address when the client has not initiated a migration to that address, the client SHOULD discard those packets."

Having said all this, we will support "unaddressed" network BIOs in 3.2, such as `BIO_dgram_pair` with no caps set. This is done in order to support existing applications with only minimal changes, and is exemplified by the DDD demos which have now merged in their final form and can be found in doc/designs/ddd.

However, such applications, which use our QUIC implementation without our QUIC implementation knowing about any L4 addresses, will not be able to automatically take advantage of connection migration (or multipathing, or so on) in the future.

It is also possible to use `BIO_dgram_pair` etc. in addressed mode with L4 address awareness, in which case migration can still be supported.

**Comment by kroeckx** [comment]
I'm not saying that we don't need to have support OpenSSL knowing about the addresses. I'm saying it should still be possible to use it without. As far as I can see, there is nothing in QUIC that requires us to know it, but there are various optional things where it will be useful to know it. It will be easier to adopt to QUIC if it's possible to not have to tell OpenSSL about the addresses.

That being said, I'm not sure the current APIs will be sufficient. I assume there will be software that want to create a new socket for a new address, and we might need some kind of callback for that.

**Comment by hlandau** [comment]
>I'm saying it should still be possible to use it without.

As mentioned above, this is already possible.

>That being said, I'm not sure the current APIs will be sufficient. I assume there will be software that want to create a new socket for a new address, and we might need some kind of callback for that.

The plan is to support migration, etc. on a single socket using `sendmmsg`/`recvmmsg`, which allows source/destination addresses to be specified. So it should just work. Please see the API docs for BIO_sendmmsg(3) &mdash; this is the interface which QUIC always uses to access the network.

**Comment by mattcaswell** [comment]
Closing since this is marked as resolved.
