### ISSUE TITLE
OSSL_STORE error reporting masked on EOF

### ISSUE THREAD

**Issue by simo5** [openssl/openssl#21968]
When a provider returns an error from a load operation, openssl masks it away and does not report it from OSSL_STORE_error() if the provider also reports EOF.

This happens in https://github.com/openssl/openssl/blob/e664ef78b92532bf94c7976b181d88c4abf83074/crypto/store/store_lib.c#L438

I see no way to let openssl report a fatal error happening on load() that results in no entries or only 1 entry being available and therefore requiring the provider to return EOF on request after the first _load().

The original issue comes from https://github.com/latchset/pkcs11-provider/issues/274

**Comment by levitte** [comment]
The whole problem is actually the condition introducing the line you quote:

https://github.com/openssl/openssl/blob/e664ef78b92532bf94c7976b181d88c4abf83074/crypto/store/store_lib.c#L437-L438

And yeah, that doesn't look right.  It does look intentional, though, so I wonder why it was done this way in the first place...

**Comment by levitte** [comment]
I traced back to that modification.  It goes all the way back to the initial adaptation to provider support, in 34b80d0622924d112b145fd36bfaad18616f2546.  No real explanation for that particular check, so I'll have a go at removing it and...  see what happens.

**Comment by levitte** [comment]
Yup.  Fix in #21976, please have a go with it, and comment there
