### ISSUE TITLE
building with configuration VC-WIN64A fails

### ISSUE THREAD

**Issue by jamuir** [openssl/openssl#22371]
I tried to build `master` (eaee1765) using the configuration `VC-WIN64A` on two different x86_64 windows machines and both builds failed.

I used a bat file containing the following lines:

```
REM doit.bat > log.txt 2>&1
perl Configure VC-WIN64A --prefix="C:\Users\tvavra\source\repos\james\tmp\beforespace afterspace"
nmake
nmake test
nmake install
```

The first `nmake` step fails with the following error:

```
	cmd /C ""link" /nologo /debug /dll  /nologo /debug @C:\Users\tvavra\AppData\Local\Temp\2\nmB0A4.tmp /implib:libcrypto.lib || (DEL /Q libcrypto-3-x64.* libcrypto.lib & EXIT 1)"
crypto\aes\libcrypto-shlib-aes_cfb.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64'
Could Not Find C:\Users\tvavra\source\repos\james\openssl\libcrypto-3-x64.*
NMAKE : fatal error U1077: 'cmd /C ""link" /nologo /debug /dll  /nologo /debug @C:\Users\tvavra\AppData\Local\Temp\2\nmB0A4.tmp /implib:libcrypto.lib || (DEL /Q libcrypto-3-x64.* libcrypto.lib & EXIT 1)"' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX86\x86\nmake.exe" /                   _tests' : return code '0x2'
Stop.
```

Then both `nmake test` and `nmake install` fail with the same error.

**Comment by jamuir** [comment]
I should note that if I call `Configure` without `VC-WIN64A` (so that the script selects its own build-config), then the build completes successfully.

**Comment by mattcaswell** [comment]
> fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64'

This normally occurs because of a discrepancy between the toolchain being used and the architecture that you are attempting to build for, i.e. using the x86 VC toolchain but attempting to build for VC-WIN64A (i.e. x86_64).

If you run the compiler (`cl.exe`) by itself with no arguments it should tell you what architecture it is targeting.

See:

https://github.com/openssl/openssl/blob/eaee1765a49c6a8ba728e3e2d18bb67bff8aaa55/NOTES-WINDOWS.md?plain=1#L65-L73
