### ISSUE TITLE
quic fuzzer hang

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#22412]
The fuzzer from #22368 combined with #22410 and #22411, hangs with 
[hang2.gz](https://github.com/openssl/openssl/files/12935634/hang2.gz)

**Comment by kroeckx** [comment]
If you fix this, can I suggest that you run the fuzzer for a minute or so. I've found both those hangs in a few seconds. Use libfuzzer, and add -timeout=5 to the command line, so it gives you a nice file instead of just hanging for a very long time.

**Comment by mattcaswell** [comment]
This hang is caused because we receive a very large token in a retry packet. Later we try to create a PING frame but, because the token is so large, we fail to insert the PING or anything else into the datagram. Since we have failed to generate a PING, but the ping deadline has expired we immediately try to create another PING - and so on in an infinite loop.

**Comment by mattcaswell** [comment]
> If you fix this, can I suggest that you run the fuzzer for a minute or so. I've found both those hangs in a few seconds. Use libfuzzer, and add -timeout=5 to the command line, so it gives you a nice file instead of just hanging for a very long time.

I did that and immediately ran into #22427

**Comment by t8m** [comment]
The original hang was fixed.
