### ISSUE TITLE
Change Blake2b to use OSSL_PARAM_DIGEST_SIZE as settable instead of OSSL_PARAM_DIGEST_XOFLEN

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#22488]
This needs to go in before 3.2.0 beta1.

**Comment by kkumar45** [comment]
@t8m Is there a reason why this is not a part of 3.5.0 LTS version? I am using the 3.5.0 version of OpenSSL and I couldn't find the fix there. Can you please provide any information regarding this?

**Comment by mattcaswell** [comment]
> @t8m Is there a reason why this is not a part of 3.5.0 LTS version? I am using the 3.5.0 version of OpenSSL and I couldn't find the fix there. Can you please provide any information regarding this?

This PR *is* included in 3.5 (see https://github.com/openssl/openssl/commit/6a0ae393dd554eb718e5148696e8f437d4faae5b). The code looks a little different in 3.5 since it was subsequently refactored but looking at the code, the essence of the fix still seems to be there:

https://github.com/openssl/openssl/blob/8f646cfb761f94e5fbb431c7cb800600364ba35a/providers/implementations/digests/blake2_prov.c#L71-L82
