### ISSUE TITLE
quic-client fuzzer OOM

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#22568]
[oom-478d500a9936bfd8184313e669f1dc8a281a97d0.gz](https://github.com/openssl/openssl/files/13216049/oom-478d500a9936bfd8184313e669f1dc8a281a97d0.gz)

**Comment by mattcaswell** [comment]
Fix in #22579

**Comment by mattcaswell** [comment]
> Out of curiosity, why was this causing OOM?

The function `ch_tx` loops indefinitely until we have stopped creating packets to send. Because of this bug we were creating a packet for a pn_space where we wouldn't otherwise be creating a packet. Due to other conditions at the time we were unable to create an ack frame for the pn_space that we actually wanted to create one for - which is fine, but it meant that we did not clear the flag in `txp->want_ack`. Since we created a packet `ch_tx` went around the loop again. The flag was still set, so we created another packet - and so on infinitely. Each time we send a packet we consume a bit more memory - so eventually OOM occurs. This would have otherwise timed out eventually.
