### ISSUE TITLE
Evaluate potential use of abidiff and libabigail symbol scanning tools

### ISSUE THREAD

**Issue by hlandau** [openssl/openssl#22571]
Following on from PR #22478.
May provide a further tool for #22330.

From @thesamesam:

> Might be worth looking at `abidiff` and the other tools from libabigail at some point.

**Comment by nhorman** [comment]
I like this idea, but I'm not quite sure how we would go about implementing it.  libabigail builds a xml representation of the abi that a given library presents, but doesn't really include data about symbols that a given DSO _requires_.  I can't see anything in the abidw docs that explicitly lets you build a file defining what symbols you need, or am I missing something here?

**Comment by t8m** [comment]
Yeah, this is a completely separate thing to your symbol scanning script with a different purpose.

It still could be useful although we are catching api/abi breaks on reviews pretty well nowadays.

**Comment by nhorman** [comment]
ah, we just want to add a check to compare changes to our own abi?  Yeah, that makes sense

**Comment by nhorman** [comment]
https://github.com/openssl/openssl/pull/22589

**Comment by thesamesam** [comment]
The libabigail maintainers (who are very interested in hearing if you have any feature requests/bug reports) wanted me to mention that abidiff can also now "follow the dependencies" of a binary and include those deps in the comparison. See --follow-dependencies at https://sourceware.org/libabigail/manual/abidiff.html.

Thanks for implementing this so quickly after just a throwaway comment! :)

**Comment by nhorman** [comment]
@thesamesam @t8m recently proposed this [change](https://github.com/openssl/openssl/pull/22689) in our ci to print out the xml diff of an abi comparison on failure.  That might be a nice feature to add to abidiff directly, just to save some extra work in the ci yaml.

Thanks for bringing it to the libabigail maintainers attention!

**Comment by nhorman** [comment]
@thesamesam regarding the dependency following operation, I'm reading the man page, and could you clarify the granularity of the comparison?  For example, if we run abidw --follow-dependenires on libcrypto.so, and we build libcrypto with zlib support, is the comparison done on all exported symbols of the dependency or only the symbols that libcrypto references?  

I ask because, in our use case, we use abidw as a gate to detect abi changes in the libraries we ship, it matters if zlib changes a function we reference, but it matters less, if zilb adds a function that we don't reference

**Comment by sftcd** [comment]
Hi - I'm seeing CI build fails due to this. I'm in a linux dev environment and wondering if there's a tool (in my environment) to regenerate ``libssl-abi.xml`` for an upcoming PR which adds new APIs. For the moment I've manually added lines to that file (we'll see how that goes:-), but I guess there may be a better way to do things.
Ta,
S.
