### ISSUE TITLE
compile error in crypto/threads_pthread.c under RedHat 4 (Nahant Update 7)

### ISSUE THREAD

**Issue by skydeepsky** [openssl/openssl#2261]
I download openssl-OpenSSL_1_1_0-stable from github,and then upload to my fresh install RedHat 4(U7) x86_64 ,when I compile ,it aborted with the bellow error info:

> In file included from crypto/threads_pthread.c:10:0:
crypto/threads_pthread.c: In function 'CRYPTO_THREAD_lock_new':
crypto/threads_pthread.c:16:49: error: 'pthread_rwlock_t' undeclared (first use in this function)
     CRYPTO_RWLOCK *lock = OPENSSL_zalloc(sizeof(pthread_rwlock_t));
                                                 ^
include/openssl/crypto.h:128:23: note: in definition of macro 'OPENSSL_zalloc'
         CRYPTO_zalloc(num, OPENSSL_FILE, OPENSSL_LINE)
                       ^
crypto/threads_pthread.c:16:49: note: each undeclared identifier is reported only once for each function it appears in
     CRYPTO_RWLOCK *lock = OPENSSL_zalloc(sizeof(pthread_rwlock_t));
                                                 ^
include/openssl/crypto.h:128:23: note: in definition of macro 'OPENSSL_zalloc'
         CRYPTO_zalloc(num, OPENSSL_FILE, OPENSSL_LINE)
                       ^
crypto/threads_pthread.c:20:5: warning: implicit declaration of function 'pthread_rwlock_init' [-Wimplicit-function-declaration]
     if (pthread_rwlock_init(lock, NULL) != 0) {
     ^
crypto/threads_pthread.c: In function 'CRYPTO_THREAD_read_lock':
crypto/threads_pthread.c:30:5: warning: implicit declaration of function 'pthread_rwlock_rdlock' [-Wimplicit-function-declaration]
     if (pthread_rwlock_rdlock(lock) != 0)
     ^
crypto/threads_pthread.c: In function 'CRYPTO_THREAD_write_lock':
crypto/threads_pthread.c:38:5: warning: implicit declaration of function 'pthread_rwlock_wrlock' [-Wimplicit-function-declaration]
     if (pthread_rwlock_wrlock(lock) != 0)
     ^
crypto/threads_pthread.c: In function 'CRYPTO_THREAD_unlock':
crypto/threads_pthread.c:46:5: warning: implicit declaration of function 'pthread_rwlock_unlock' [-Wimplicit-function-declaration]
     if (pthread_rwlock_unlock(lock) != 0)
     ^
crypto/threads_pthread.c: In function 'CRYPTO_THREAD_lock_free':
crypto/threads_pthread.c:57:5: warning: implicit declaration of function 'pthread_rwlock_destroy' [-Wimplicit-function-declaration]
     pthread_rwlock_destroy(lock);
     ^
make[1]: *** [Makefile:5014: crypto/threads_pthread.o] Error 1
make[1]: Leaving directory '/openssl-OpenSSL_1_1_0-stable'
make: *** [Makefile:128: all] Error 2

My OS is Red Hat Enterprise Linux AS release 4 (Nahant Update 7),it is Linux 2.6.9.
Following is my compile step :

> unzip openssl-OpenSSL_1_1_0-stable.zip
cd openssl-OpenSSL_1_1_0-stable
chmod 755 *
./config
make

How to correct this error?
THANKS for any help that can be given!

**Comment by mattcaswell** [comment]
Hmmmm. That is very strange. Those symbols are defined in "pthread.h" which is transitively included from   "openssl/crypto.h" which is included at the top of the "crypto/threads_pthread.c" file. One of two possibilities come to mind:

1) Your system does not define those symbols
2) For some reason those symbols are not being included even though they should be brought in by crypto.h

To rule out 2 (which looking at the code I don't see how it could happen), please add the following lines to the very top of "crypto/threads_pthread.c", and then try to compile again:
````
#include <sys/types.h>
#include <pthread.h>
````

If the above still fails with similar compile issues, then it looks like your problem is (1)...which kind of means your out of luck. OpenSSL 1.1.0 depends on those symbols being present. You could still compile using the "no-threads" option to "config", i.e.

````
./config no-threads
make
````
But that gives you a very hobbled version of OpenSSL. It might be useful to you depending on what you want to do with it. If your application is only ever going to be single threaded, or you only want to use the command line tools then it should work.

**Comment by levitte** [comment]
Hmmm...  looking at `/usr/include/pthread.h` on my machine, it looks like the declaration of things rwlock requires certain features to be enabled.  From what I can tell, one of these are needed before including pthread.h:

``` C
# define _POSIX_C_SOURCE 200112L

/* It's possible that 500 works as well */
# define _XOPEN_SOURCE 600
```

**Comment by levitte** [comment]
... it's also possible that RedHat 4 is to old

**Comment by dot-asm** [comment]
> it's also possible that RedHat 4 is too old

Yes. The problem can be worked around by adding -D_GNU_SOURCE at *config-time*, e.g. `./config -D_GNU_SOURCE`. Since it's an old system, workaround is only plausible approach.

**Comment by levitte** [comment]
I think that concludes this issue.
