### ISSUE TITLE
quic-client fuzzer: Assertion failed: ossl_quic_txfc_consume_credit(&stream->txfc, stream->txp_txfc_new_credit_consumed)

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#22706]
I'm getting:
ssl/quic/quic_txp.c:2944: OpenSSL internal error: Assertion failed: ossl_quic_txfc_consume_credit(&stream->txfc, stream->txp_txfc_new_credit_consumed)
From this file: 
[crash-cd68035706010ad1a4031e3005af1cce0f581010.gz](https://github.com/openssl/openssl/files/13327578/crash-cd68035706010ad1a4031e3005af1cce0f581010.gz)

**Comment by mattcaswell** [comment]
In this case we have two streams, both with data to send and each with plenty of stream level flow control credit. However the connection level credit is only 26 bytes.

We consider the first stream and determine that we can only send 26 bytes due to the remaining connection level credit.
We then consider the second stream and also determine that we can only send 26 bytes due to the connection level credit.

Finally, because we sent data for two streams each consuming 26 bytes of credit, we try to consume 52 bytes of credit....but we only have 26, so we get the assertion failure.

Fix in #22718.
