### ISSUE TITLE
update coding style (discuss/vote) for unused arguments

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2282]
quoting https://github.com/openssl/openssl/pull/2270#issuecomment-274941918:

It would probably be appropriate to mention this in coding style... I'd also argue that last sentence in chapter 6 could be relaxed to permit ```_unused``` suffix or ```unused_``` prefix in function implementation. Though there is bunch of cases where additional pre-/suffix doesn't formally conflict with the last sentence of the chapter 6. Cases when static methods get implemented and don't require all the arguments...

**Comment by dot-asm** [comment]
Or in other words. Last paragraph of Chapter 6: Functions currently reads

> In function prototypes, include parameter names with their data types.
Although this is not required by the C language, it is preferred in OpenSSL
because it is a simple way to add valuable information for the reader.
The name in the prototype declaration should match the name in the function
definition.

And suggestion is to add something in following spirit. Unused arguments may have `_unused` suffix in definition [which is likely to be more common in methods and callback implementations]. Unused arguments should be "short-circuited" early in function body by casting them to `(void)`.

**Comment by richsalz** [comment]
moved to https://github.com/openssl/web/issues/48
