### ISSUE TITLE
1.0.2j build failure on ia64

### ISSUE THREAD

**Issue by asarubbo** [openssl/openssl#2286]
I have a build failure for 1.0.2j on ia64.

gcc version 4.9.4 (Gentoo 4.9.4 p1.0, pie-0.6.4) 
glibc-2.23
kernel-3.14

log attached.
[openssl-ia64.txt](https://github.com/openssl/openssl/files/730250/openssl-ia64.txt)

**Comment by dot-asm** [comment]
Error output looks like as if .S-file wasn't pre-processed... Well, it's not a mystery that it refers to lines in .S-file, that's because there is line number info in .s-file. But there shouldn't be any `getrw` things or non-general registers in .s-file. And it does work for me with stone-age compiler... Could you attach generated md5-ia64.s? Also try to omit line number info. To do that `cd crypto/md5`, open Makefile in text editor, locate md5-ia64.s rule, add -P flag to `$(CC)` line. Finally `rm md5-ia64.s` and re-run make.

**Comment by asarubbo** [comment]
I hope is what you looking for..

[md5-ia64.s.txt](https://github.com/openssl/openssl/files/731877/md5-ia64.s.txt)

**Comment by dot-asm** [comment]
As you can see yourself it's not actually pre-processed. There are `#define` directives and references to defined macros, such as `GETLW(W_,Y_,offset)` at line 456. Properly pre-processesed file starts like this:
```
# 1 "crypto/md5/asm/md5-ia64.S"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<command-line>" 2
# 1 "crypto/md5/asm/md5-ia64.S"
# 250 "crypto/md5/asm/md5-ia64.S"
 .text
# 272 "crypto/md5/asm/md5-ia64.S"
 .type md5_block_asm_data_order, @function
 .global md5_block_asm_data_order
 .align 32
 .proc md5_block_asm_data_order
```
Question of course is how come it's not pre-processed. Apparently -g3 is responsible for this. At least if I pass -g3 -E, I also get file that starts with bunch of `#define` directives, and references to macros. In other words drop -g3. Does it work then?

**Comment by asarubbo** [comment]
The hint you gave permitted me to do more tests.

-O2 -pipe -mtune=itanium2 -ggdb -> FINE
-O2 -pipe -mtune=itanium2 -ggdb1 -> FINE
-O2 -pipe -mtune=itanium2 -ggdb2 -> FINE
-O2 -pipe -mtune=itanium2 -ggdb3 -> FAILURE
-O2 -pipe -mtune=itanium2 -ggdb2 -g2  -> FINE
-O2 -pipe -mtune=itanium2 -g2 -> FINE
-O2 -pipe -mtune=itanium2 -g3 -> FAILURE

In short the failure exist when the debug level between one of -g/-ggdb is 3

**Comment by richsalz** [comment]
so this appears to be a compiler bug that you have to work around by disabling some flags.

**Comment by jduerstock** [comment]
Was this ever filed as a gcc bug?

**Comment by trofi** [comment]
For posterity: it was caused by ia64-specific makefile rule in openssl-1.0 branch: https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/crypto/md5/Makefile#L51

```
md5-ia64.s: asm/md5-ia64.S
	$(CC) $(CFLAGS) -E asm/md5-ia64.S | \
$(PERL) -ne 's/;\s+/;\n/g; print;' > $@
```

Here `$(CC) $(CFLAGS)` calls preprocessor with `-ggdb3`. In this mode `gcc` (6 and 7) on purpose does not make macros go away in the final output. My guess it's done to emit more precise debug info that can refer to `cpp` objects in `gdb` session.

I've seen a similar bug in `guile` recently: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=25803

openssl-1.1 seems to fix it in a radical way by removing ia64-specific assembly entirely which means it's not an issue anymore. Users of openssl-1.0 branch would somehow neeed to filter out -g* flags around that makefile rule.
