### ISSUE TITLE
Provider activation can fail if HAVE_ATOMICS defined

### ISSUE THREAD

**Issue by Futaura** [openssl/openssl#22933]
Note that the following code, which I think is new for 3.2.0:

https://github.com/openssl/openssl/blob/4ff5137ff5fb896e0273d274110517e3c7adb8cf/crypto/provider_core.c#L449-L455

This can cause the following to fail as no lock was allocated, if `CRYPTO_atomic_add` should need to fall back to using it:

https://github.com/openssl/openssl/blob/4ff5137ff5fb896e0273d274110517e3c7adb8cf/crypto/provider_core.c#L1196

Probably the lock should be allocated and freed in all cases?

**Comment by nhorman** [comment]
Unilaterally allocating the lock would certainly fix the problem, but the only case I could see this occurring is if BROKEN_CLANG_ATOMICS was defined.  It might be better to refactor the CRYPTO_THREAD_atomic api to just not check atomic_is_lock_free for those opertions if we are building for OS/X 10.7 or 10.8.  Doing so would save the extra allocation, which will almost never be used

**Comment by nhorman** [comment]
I don't think it has changed at all.  In both branches HAVE_ATOMICS indicates weather or not a given platform supports atomic operations, which is used internally to that api to determine if a separate mutex is needed to preform atomic operations.  the only change between 3.1.4 and master is that the refcnt api was updated to internally allocate a lock, rather than requiring the caller to allocate one.

Its use to determine the need to allocate a lock for atomic operatiions was really just a shorthand way to save the allocation if a builder could predict it wasn't needed.

The solution that was implemented in the master branch was to remove HAVE_ATOMICS and allocate the lock all the time because it was being used for an api (CRYPTO_THREAD_atomic_add) which always assumed the lock was allocated.

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev barring further input

**Comment by Futaura** [comment]
I'm happy with the fix that was made - is working fine here

**Comment by t8m** [comment]
Closing the issue then.
