### ISSUE TITLE
Trying to install tunnelkit with cocoapods

### ISSUE THREAD

**Issue by deviouskh** [openssl/openssl#23001]
Very new to vpn integration and xcode... any help and advice is greatly appreciated

Command line tools are up to date, thats the main answer to my question but does not resolve my issue.

<img width="1366" alt="Screenshot 2023-12-10 at 10 47 05 PM" src="https://github.com/openssl/openssl/assets/151959972/301a2319-8e78-413f-89a7-9a82313b4061">

**Comment by tom-cosgrove-arm** [comment]
There's a number of things here:

First, there's no indication of what the error actually is - it says "Problem during make - Please check /Users /
Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.11.11-fb93d/bin/Catalyst14.0-x86_64.sdk/build-openss1-1.1.11.10g" but you haven't posted that.

Second, that's an image, which makes referring to lines such as that one a lot of work, and frankly I don't think anyone is really going to have the patience to do that if an issue is raised with just a screenshot like that (which is pretty much the least effort anyone can make when raising an issue).

Thirdly, things like this are better raised as discussions - there's no indication that this is actually an _issue_ with OpenSSL.

So then we move on to "Trying to install tunnelkit with cocoapods" - I don't know what tunnelkit is, but the OpenSSL project provides a library that is used by other components upstream: this is best raised with tunnelkit or cocoapods.

Because also, the version in the logs, `OpenSSL-Apple (1.1.1l.11)` isn't an OpenSSL version. But [all OpenSSL 1.1.1 versions are out of support since September 2023 anyway](https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/).

I think this issue is best closed so that you can ask in a more appropriate place, but I'll wait for a second opinion

**Comment by mspncp** [comment]
So did you check build-openssl1.1.1l.log, as requested by the build tool?

Would you mind posting it's contents? (You may remove personal content like parts of the path if you wish.)

*Disclaimer*: this is very likely a downstream problem and OpenSSL 1.1.1 is out of support.
