### ISSUE TITLE
Enable ZLIB without TLS compression

### ISSUE THREAD

**Issue by sebastianas** [openssl/openssl#23058]
TLSv1.2 and less makes compression available at protocol level. This leads to problems such as the CRIME attack and therefore I had the openssl compiled with no-zlib.
No I would like to compile openssl with zlib due to compressed certificates but I would still like not to allow zlib at TLS level. My understanding is that this is currently not possible. The define OPENSSL_NO_COMP in ssl/ covers the instances of compression at TLS level but "no-comp" can't be used at configure time because this also disables all compression including for certificates.

Is this correct? If so, would it be possible to introduce another define so that it is possible to use zlib compression certificates while disabling zlib compression at TLS protocol level?

**Comment by t8m** [comment]
This could be a valid feature. On the other hand TLS compression is disabled in TLS connections by default and you won't get it negotiated unless you call SSL_COMP_add_compression_method() in your application.

**Comment by sebastianas** [comment]
On 2023-12-15 03:27:50 [-0800], Tomáš Mráz wrote:
> This could be a valid feature. On the other hand TLS compression is
> disabled in TLS connections by default and you won't get it negotiated
> unless you call SSL_COMP_add_compression_method() in your application.

I was under the impression that this is enabled by default if available.
However, if this is not the case then it would work me to enable zlib
and allow the individual application use if it is safe to do so.

Thank you.

Sebastian

**Comment by t8m** [comment]
No, TLS compression is never enabled by default. @mattcaswell please correct me if I am wrong.

**Comment by mattcaswell** [comment]
From OpenSSL 1.1.0 and above TLS compression was disabled by default, i.e. the TLS runtime option `SSL_OP_NO_COMPRESSION` is set by default. To enable it you have to explicitly clear that option on your `SSL_CTX`/`SSL`.

From OpenSSL 3.2.0 and above the default security level has changed to 2. TLS compression is disallowed at security level 2 and above. Therefore in OpenSSL 3.2.0 and above, in order to enable TLS compression you would have to clear the option mentioned above *and* reduce the security level to 1 or lower.

We could probably do with improving out documentation on the second point because its not really mentioned anywhere.

**Comment by mattcaswell** [comment]
> you won't get it negotiated unless you call SSL_COMP_add_compression_method() in your application.

Note that this is *not* necessary. The compression methods will be loaded by default and used if the runtime options and security level allow.

**Comment by mattcaswell** [comment]
> We could probably do with improving out documentation on the second point because its not really mentioned anywhere.

#23104

**Comment by t8m** [comment]
@sebastianas given the above can we close this RFE?

**Comment by sebastianas** [comment]
On 2023-12-20 05:10:42 [-0800], Tomáš Mráz wrote:
> @sebastianas given the above can we close this RFE?

Yes, thank you.

Sebastian
