### ISSUE TITLE
support Via padlock

### ISSUE THREAD

**Issue by s3boun3t** [openssl/openssl#2311]
Hi, could you add support for VIA PADLOCK 64 bits module.
i'm on ubuntu 16.10 with openssl 1.0.2g and the command "openssl engine" don't show via padlock support

it's show "(dynamic) dynamic engine loading support"

I have via nano 64 bits

**Comment by levitte** [comment]
It's a dynamic engine, so you must say that you want it.  Try this:

```
$ openssl engine padlock
```

**Comment by s3boun3t** [comment]
I have error

```
139830909517528:error:260B606D:engine routines:DYNAMIC LOAD:init failed:eng dyn.c:545
139830909517528:error:2606A074:engine routines:ENGINE by id:no such engine:eng list.c:390:id=padlock
```

**Comment by s3boun3t** [comment]
hi, any news ?
I am on xubuntu 18.10 64 bits now, there has been no progress since.
The via padlock works in 32 bits but not in 64 bits.

I have make a conf file in /etc/ssl/openssl.cnf with this in the end:
openssl_conf = openssl_def
    
    [ openssl_def ]
    engines = openssl_engines
    
    [ openssl_engines ]
    padlock = padlock_engine
    
    [ padlock_engine ]
    engine_id = padlock
    dynamic_path = /usr/lib/x86_64-linux-gnu/engines-1.1/padlock.so
    default_algorithms = ALL

and now i have this error

openssl engine padlock
140546670662720:error:260B606D:engine routines:dynamic_load:init failed:../crypto/engine/eng_dyn.c:485:
140546670662720:error:2606A074:engine routines:ENGINE_by_id:no such engine:../crypto/engine/eng_list.c:335:id=padlock

thanks

**Comment by kroeckx** [comment]
Padlock is not compiled by default. The top of the file says:
/*
 * VIA PadLock AES is available *ONLY* on some x86 CPUs. Not only that it
 * doesn't exist elsewhere, but it even can't be compiled on other platforms!
 */

The bind_engine() function just returns that it's not available.
The reason is that PADLOCK_ASM is not defined, it should probably
be defined if either the e_padlock-x86_64.s or e_padlock-x86.s is
generated.

The padlock_bind_fn() is inside an #   ifdef DYNAMIC_ENGINE
I think that should say #   ifndef OPENSSL_NO_DYNAMIC_ENGINE

After fixing that, I get:
(padlock) VIA PadLock (no-RNG, no-ACE)

**Comment by levitte** [comment]
#8220 make it compile properly, and worked.  Confirmed on my laptop (x86_64)
