### ISSUE TITLE
Add DTLS functionality to TLS::Proxy perl module

### ISSUE THREAD

**Issue by fwh-dc** [openssl/openssl#23199]
For DTLS 1.3 I want to add tests for the downgrade protection mechanism as is tested on tls1.3 in ```70-test_tls13downgrade.t```. This test uses `-no_tls1_2` and `-no_tls1_3` as arguments to change the list of supported protocols.

I am missing the same handles to do it for dtls. I tried by using `-dtls -no_tls1_2` but the program returns a failure: those args cannot be used together.

So my question is: is there a way to achieve this functionality with the current master?

If not:
What do you consider the best way to add such functionality? The way that `-no_tls1_2` works is not obvious to me from the source code.

**Comment by mattcaswell** [comment]
There are multiple aspects to consider in this question.

> as is tested on tls1.3 in 70-test_tls13downgrade.t

The first thing to realise about this test is that it is based on TLSProxy which is implemented here:

https://github.com/openssl/openssl/tree/master/util/perl/TLSProxy

TLSProxy is written in perl and works by becoming a "man-in-the-middle" between a client and a server. The idea is to be able to insert things which would otherwise be invalid. The client and server are based on s_client and s_server and therefore implement fully standards compliant (D)TLS. It's not possible for them to emit invalid protocol messages. TLSProxy sits in the middle and modifies messages according to whatever test we are trying to implement. Obviously (D)TLS has in built protections against man-in-the-middle attacks, so for this to work we have to disable those protections. We do this via the ossltest engine:

https://github.com/openssl/openssl/blob/master/engines/e_ossltest.c

This overrides the implementation of certain crypto algorithms such that MACs always produce the same output no matter what the input, and ciphers are no-ops (i.e. so that data is transmitted in plaintext).

None of this currently works with DTLS. For example at the very least this file would have to be adapted to work with DTLS:

https://github.com/openssl/openssl/blob/master/util/perl/TLSProxy/Record.pm

Probably there are other changes that would be required too - but I'm not sure what would be needed.

So, getting this test to work with DTLS is much bigger than just getting s_client/s_server to accept the -no_dtls1_2 etc flags.

> The way that -no_tls1_2 works is not obvious to me from the source code.

It's all implemented here:

https://github.com/openssl/openssl/blob/8b9cf1bc2c3085b6e9493a057209ffd0bddf48a6/ssl/ssl_conf.c#L704-L836

In theory it should be as simple as adding new entries to the `ssl_conf_cmds` and `ssl_cmd_switches` arrays.

Note that the same effect can be achieved using the `-min_protocol` and `-max_protocol` command line arguments (also implemented in the same file).

You will probably also need to make changes here:

https://github.com/openssl/openssl/blob/8b9cf1bc2c3085b6e9493a057209ffd0bddf48a6/ssl/ssl_conf.c#L279-L288

and here:

https://github.com/openssl/openssl/blob/8b9cf1bc2c3085b6e9493a057209ffd0bddf48a6/ssl/ssl_conf.c#L313-L321

**Comment by fwh-dc** [comment]
> Note that the same effect can be achieved using the -min_protocol and -max_protocol command line arguments (also implemented in the same file).

With `-no_tls1_2` you create a version hole which is also tested by the test suite and that can't be achieved max and min.

> TLSProxy sits in the middle and modifies messages according to whatever test we are trying to implement.

Aha ok thanks for the explanation. Ok I see there is more work to be done here.

I think I will work on some other issues for dtls 1.3 first (NewSessionTickets are not working properly) which also blocks this test execution.

I was thinking to add this test functionality TLS::proxy and -no_dtls directly to master. Do you have some suggestions to relevant dtls tests that could be created or refactored to use this functionality?

**Comment by mattcaswell** [comment]
There are numerous TLSProxy based tests (grep TLSProxy in test/recipes). Many of these would benefit from additionally testing DTLS. Some particular ones that leap out at me as being especially relevant are sslrecords, sslversions, sslvertol....but really any of them.

**Comment by t8m** [comment]
> With `-no_tls1_2` you create a version hole which is also tested by the test suite and that can't be achieved max and min.

If I remember correctly it is NOT possible to create a version hole. Using just this option will disable all versions except for TLS-1.3. In combination with `-no_tls1_3` it will disable TLS>=1.2.

**Comment by fwh-dc** [comment]
Aha, thats interesting.

From the documentation it just looked like it was possible to achieve a version hole.
https://github.com/openssl/openssl/blob/3348713ad390372ba5a0a0f98b46b2f637475e47/doc/man3/SSL_CONF_cmd.pod?plain=1#L269-L275
Should there be a warning when using s_client and s_server that the arguments are deprecated?

For future notice there's no point in adding the `-no_dtls1_0` and `-no_dtls1_2` now because the tls equivalents are deprecated and 
> Note that the same effect can be achieved using the -min_protocol and -max_protocol command line arguments (also implemented in the same file).

So I guess to do similar testing (test_tls13downgrade.t, 70-test_sslrecords.t, etc.) with dtls as for tls there needs to be added support in TLSProxy and perhabs in e_ossltest. I can have a look at that later.
