### ISSUE TITLE
evp_fetch.c: Superfluous check for name_id

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#23226]
Recently was activated in 3.0 branch a new functionality. Dunno way is added new fucntionality to this branch.
Question is about condition. Current code look like:
```
if (name_id == 0)
	reise error
else
	get method id
	if (name_id != 0) // <===  method id ?
		cache by method id(?) and etc
```

**Comment by t8m** [comment]
I assume you're referring to this PR: https://github.com/openssl/openssl/pull/23110/files

This is not a _new functionality_, this is a bug fix as without this fetching "something:anything" produces asserts instead of just failing. This bug fix prevents the assert.

And yeah, the `if (name_id != 0)` should probably be rather `if (meth_id != 0)` but that was preexisting in the code.
