### ISSUE TITLE
Missing exports for QLOG

### ISSUE THREAD

**Issue by gvanem** [openssl/openssl#23518]
Building from `git master` today and with this new QLOG feature (`perl Configure enable-unstable-qlog ...`),
showed some issues when linking `libssl*.dll`; None of these functions gets exported from `libcrypto*.dll`:
  * `ossl_safe_getenv()` in `crypto/getenv.c`.
  * `ossl_ctype_check()` in `crypto/ctype.c`.
  * `ossl_isdigit()` in `crypto/ctype.c`.

I assume these function should **not** be duplicated in `libssl*.dll`. But taken from `libcrypto*.dll`, no?
So these ought to be added to `util/libcrypto.num` somehow. Little idea how to conditionally add to the `.def`-file. 
Some trickery in `mkdef.pl` I assume.

Besides compiling `ssl/quic/qlog.c` with `clang-cl` caused this error:
```c
ssl/quic/qlog.c(325,62): error: call to undeclared function 'getpid'; ISO C99 and later do not support implicit function declarations
      [-Wimplicit-function-declaration]
  325 |                         ossl_json_u64(&qlog->json, (uint64_t)getpid());
      |                                                              ^
```

But this I see was addressed in #23517. [Here](https://github.com/openssl/openssl/pull/23517/files#diff-40206579bd6a0db04314d49907a7db16668065a8e609e32c01d1f81c09fa8450R322).

**Comment by hlandau** [comment]
@gvanem I'm unsure why you're experiencing these linker errors as those files are supposed to be duplicated in the build of libssl, as per `ssl/quic/build.info`:

```
IF[{- !$disabled{qlog} -}]
  SOURCE[$LIBSSL]=json_enc.c qlog.c
  SHARED_SOURCE[$LIBSSL]=../../crypto/getenv.c ../../crypto/ctype.c
ENDIF
```

@levitte &mdash; any ideas?

**Comment by gvanem** [comment]
>  as those files are supposed to be duplicated in the build of libssl

So I assumed wrong. But why this code-bloat? 
I'll do a *make realclean* and retry.

**Comment by hlandau** [comment]
@gvanem It is not ideal. The underlying issue here is that we have non-public APIs in libcrypto we would like to use in libssl. However, we've generally tried to follow the principle that we don't export non-public symbols from libcrypto, and libssl doesn't have "privileged" access to libcrypto internals. So occasionally we have to just duplicate some little things.

Things haven't gotten out of hand so far in terms of when we have to do this. It's something we might have to find a better solution if it starts happening more often.

**Comment by gvanem** [comment]
Seems a rebuild fixed this (adding `ctype.c` + `getenv.c`). Hence closing.
