### ISSUE TITLE
AEAD parameters appear to be broken, at least for CMS PWRI

### ISSUE THREAD

**Issue by corrideat** [openssl/openssl#23634]
When encrypting data or decrypting CMS data using a PasswordRecipientInfo field (PWRI), it looks like AEAD (i.e., GCM, which is the only implemented mode) doesn't work.

```
$ echo data | openssl cms -aes-256-gcm -encrypt -pwri_password password
804B1E5F227F0000:error:0300007A:digital envelope routines:evp_cipher_param_to_asn1_ex:cipher parameter error:crypto/evp/evp_lib.c:169:
804B1E5F227F0000:error:17000066:CMS routines:CMS_add0_recipient_password:cipher parameter initialisation error:crypto/cms/cms_pwri.c:118:
```

The same happens when decrypting data:

```
$ openssl cms -decrypt -pwri_password password -inform der < encrypted.p7
Error decrypting CMS using password
800B884F2F7F0000:error:0300007A:digital envelope routines:evp_cipher_asn1_to_param_ex:cipher parameter error:crypto/evp/evp_lib.c:245:
800B884F2F7F0000:error:17000066:CMS routines:ossl_cms_RecipientInfo_pwri_crypt:cipher parameter initialisation error:crypto/cms/cms_pwri.c:363:

```

On the other hand, `EncryptedData_encrypt` seems to be fine,

```
$ echo data | openssl cms -EncryptedData_encrypt -aes-256-gcm -secretkey 0000000000000000000000000000000000000000000000000000000000000000 | openssl cms -EncryptedData_decrypt -secretkey 0000000000000000000000000000000000000000000000000000000000000000
data
```

This is the base64-encoded version of `encrypted.p7`.

```
MIH1BgkqhkiG9w0BBwOggecwgeQCAQMxgZujgZgCAQCgMgYJKoZIhvcNAQUMMCUEEHDwwdIFlT6u
ZSxg4kkfNOsCAxAAADAMBggqhkiG9w0CCQUAMC0GCyqGSIb3DQEJEAMJMB4GCWCGSAFlAwQBLjAR
BAwGIGu8MlGalWYQhfcCARAEMNbttD/b2UMx7vLX0PIXQPtdUg8NwRxSfmrJh14xbg06cA4KVTGb
HhDsVIiYgZpegTBBBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDPCOatAEQk+L9qlHAAIBEIAU
/B0dzWybqPq4tD9jRjz6d+fxh5w=
```

**Comment by t8m** [comment]
AEAD ciphers are not supported for EncryptedData.

Duplicate of #21414

**Comment by lapo-luchini** [comment]
`man openss-cms` strongly implies it is supported, though…

```
   Encryption and decryption options

       -cipher
           The encryption algorithm to use. For example triple DES (168 bits) - -des3 or 256 bit AES  -
           -aes256.  Any  standard  algorithm name (as used by the EVP_get_cipherbyname() function) can
           also be used preceded by a dash, for example -aes-128-cbc. See openssl-enc(1) for a list  of
           ciphers supported by your version of OpenSSL.

           Currently the AES variants with GCM mode are the only supported AEAD algorithms.
```

**Comment by bukka** [comment]
@t8m Just came accross this and this part is actually a bug

```
openssl cms -aes-256-gcm -encrypt -pwri_password password
```

It has nothing to do with using EncryptedData but it's more about encrypting the password which uses the same algorithm. I just did a bit of debugging and it's because `CMS_add0_recipient_password` calls `EVP_CIPHER_param_to_asn1(ctx, encalg->parameter)` which then calls `evp_cipher_param_to_asn1_ex`. The problem is that in this path evp_cipher_aead_asn1_params won't get set.

**Comment by bukka** [comment]
So I spent a bit more time than I wanted on this. I initially thought that it could be a good idea to support AEAD ciphers for password encryption which I made sort of work for encryption in https://github.com/bukka/openssl/commit/5cd4d73f445e745a40cb3805821e867c7e58efb7 but it just was messy because I could not save tag anywhere so the decryption did not work because it doesn't allow zero length tag so I would have to either remove that limitation (not a good idea) or store tag somewhere. But there's no spec for this so I would have to come up with my own format (e.g. prefixing the tag to the encrypted password). I also checked BouncyCastle and it doesn't allow AEAD for it. There's really no point to have authenticated tag because it is already a tag for the envelope which covers this. So I just rejected that idea.

Instead I came up with a cleaner solution that allow explicitly setting the password encryption cipher (introducing `-kekcipher` option). This is implemented in https://github.com/openssl/openssl/pull/26871 . So the above example with that would look like:
```
openssl cms -aes-256-gcm -kekcipher aes-256-cbc -encrypt -pwri_password password
```

**Comment by flawrist** [comment]
Guys, forgive me, but I am bursting with curiosity.

I have OpenSSL 3.5.0 8 Apr 2025 on Windows 7 x64 and use the following command to encrypt data symmetrically:

``` console
$ openssl enc -chacha20 -iter 600000 -base64 -in plain.txt -out encrypted.txt
```

I chose ChaCha20 over AES because there is confusion about AES encryption modes (the disadvantages of CBC, CTR, OFB and others are being trumpeted on every corner today). And I am reluctant to specify `-md sha256` for compatibility with past and future OpenSSL versions, because ChaCha20 is tightly linked to SHA256 and that's not going to change.

My question is, if `openssl cms` could be the solution since it allows us to use AES-GCM. I have seen the command above and it works, but it requires specifying the secret key in HEX, and I'd like to type a plain password in the terminal or pass it as is.

``` console
$ echo data | openssl cms -EncryptedData_encrypt -aes-256-gcm -secretkey 0000000000000000000000000000000000000000000000000000000000000000 | openssl cms -EncryptedData_decrypt -secretkey 0000000000000000000000000000000000000000000000000000000000000000
```

**Comment by flawrist** [comment]
Err… Hello?
