### ISSUE TITLE
base64 decoding using EVP_DecodeBlock returns wrong result: one byte (0x10) too much

### ISSUE THREAD

**Issue by matthiasklein** [openssl/openssl#23863]
When decoding `vzxgPuegSjRksLnCAu/LElxWRonjVkCoArWzZqliiSEtmlbaCfZaGkrSweWJKQkgQsyrBUpSusAcPcGDfFhWOx==`    I get the following back `BF3C603EE7A04A3464B0B9C202EFCB125C564689E35640A802B5B366A96289212D9A56DA09F65A1A4AD2C1E58929092042CCAB054A52BAC01C3DC1837C58563B1000`.

I understand the zero byte at the end, but I don't understand the penultimate byte (`0x10`). Other Base64 decoders such as https://cryptii.com/pipes/base64-to-hex do not output `0x10` at the end.

Is this a bug?
Or is there an explanation for the `0x10` at the end?

I use version `OpenSSL 3.0.11 19 Sep 2023` from Debian bullseye.

```
#include <openssl/opensslv.h>
#include <openssl/evp.h>

#include <stdio.h>
#include <string.h>

int main()
{
    char * encoded = "vzxgPuegSjRksLnCAu/LElxWRonjVkCoArWzZqliiSEtmlbaCfZaGkrSweWJKQkgQsyrBUpSusAcPcGDfFhWOx==";
    int approxDecodedLength = strlen(encoded) / 4 * 3;
    unsigned char buffer[approxDecodedLength];

    printf("%s\n", OPENSSL_VERSION_TEXT);
    int decodedLength = EVP_DecodeBlock(buffer, (unsigned char *) encoded, strlen(encoded));

    for(int i=0; i<decodedLength; i++)
    {
        printf("%02X", buffer[i]);
    }
    printf("\n");

    return 0;
}
```
![cryptii](https://github.com/openssl/openssl/assets/6062141/4f63012e-8e9b-404b-8ff6-a2e7c76c91e3)

**Comment by nhorman** [comment]
I believe its because the base64 decoded is not quite RFC 3548 compliant.  It was initially written in 1998 prior to even RFC 1421 being ratified.  As the documentation here notes:
https://www.openssl.org/docs/man1.1.1/man3/EVP_DecodeBlock.html
The output from EVP_DecodeBlock is always a multiple of 3 bytes, which is achieved by treating the pad characters as part of the message
Where the decoder at https://cryptii.com/pipes/base64-to-hex detects the end processing characters '=' and strips their translations from the output buffer, openssl leaves them in place

**Comment by mattcaswell** [comment]
You should instead use the `EVP_DecodeInit`, `EVP_DecodeUpdate` and `EVP_DecodeFinal` functions to decode the data.

**Comment by mattcaswell** [comment]
Yeah `EVP_DecodeBlock` is intended as a low level primitive, not really as an end user one-shot thing. Documentation could be a lot better in that regards. It would also be good if we did provide a simple one-shot function instead which does the right thing.
