### ISSUE TITLE
CI regression from the new hashtable support

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#24272]
2 CI on-push jobs have regressed.

[run-checker (enable-asan enable-ubsan no-shared no-asm -DOPENSSL_SMALL_FOOTPRINT)](https://github.com/openssl/openssl/actions/runs/8832138209/job/24248845522#logs)

```
# ../../fuzz/corpora/hashtable/750489b928c4012a6c4352fdefd92c33d5ca600d
fuzz/hashtable.c:145:14: runtime error: load of misaligned address 0x602000000111 for type 'uint16_t' (aka 'unsigned short'), which requires 2 byte alignment
0x602000000111: note: pointer points here
 00 00 00  ce ce ce ce ce ce c4 ce  3f 3f 28 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00
              ^ 
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior fuzz/hashtable.c:145:14 in 
../../util/wrap.pl ../../fuzz/hashtable-test ../../fuzz/corpora/hashtable => 1
not ok 2 - Fuzzing hashtable
# ------------------------------------------------------------------------------
#   Failed test 'Fuzzing hashtable'
#   at ../../test/recipes/fuzz.pl line 22.
```

[cross-compilation (hppa-linux-gnu, libc6-dev-hppa-cross, -static linux-generic32, no, -test_inclu...](https://github.com/openssl/openssl/actions/runs/8832138216/job/24248851454#logs)

```
../../util/wrap.pl ../../test/lhash_test => 139
not ok 1 - running lhash_test
# ------------------------------------------------------------------------------
#   Failed test 'running lhash_test'
#   at /home/runner/work/openssl/openssl/util/perl/OpenSSL/Test/Simple.pm line 77.
# Looks like you failed 1 test of 1.02-test_lhash.t ......................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
```

**Comment by t8m** [comment]
@nhorman Unfortunately the hppa cross-compile job is still not fixed:

https://github.com/openssl/openssl/actions/runs/8893580037/job/24420072833

**Comment by nhorman** [comment]
will look at it, need to get a local reproducer setup

**Comment by nhorman** [comment]
Notes:
So....this is troubling
while looking for the root cause of this issue, I found that it was occuring in the test_hashtable_multithread test.  Its really odd, because it appears we're getting random memory corruption during the test

Whats more odd is that hppa is built without thread support, so its all single threaded, which eliminates race conditions as a possible source of the problem.

Whats more odd is that, in this single threaded environment

Whats more  odd is that if I reduce the optimization level to -O1, the problem abates

further reading shows that pa-risc has no hardware support for atomics, all atomic operations are by default implemented with the sync library, or optionally by libatomic.  When using the latter several build errors are produced, so for now we appear stuck with the former

I'm starting to wonder if perhaps we're seeing a issue with atomic operations on an old arch that isn't as well maintained anymore

**Comment by t8m** [comment]
Hmm... I am wondering if we should just have much more simple fallback for atomics on no-thread builds? Of course another option is to just declare this platform unsupported and remove it from CI.

**Comment by nhorman** [comment]
Possibly.  I'd like to better understand the issue before we make a decision, but yeah, I think both of those options are on the table.  It's also feasible that this is a compiler issue.  One of the options for hppas compiler is -mnoindex-loads, which eliminates the use of indexed addressing mode in loads/stores to which this problem seems related to.  Will let you know
