### ISSUE TITLE
openssl_fopen() causes segmentation fault (access violation) under some conditions on Windows

### ISSUE THREAD

**Issue by michael-o** [openssl/openssl#24416]
This has been verified with OpenSSL 3.0.11, but seems to happen with any OpenSSL version on Windows.
The actual, lengthly report comes from https://lists.apache.org/thread/m1dbj3w1x1oqftqsbj7jbnvkm2073x1o
The code in question is here: https://github.com/apache/tomcat-native/blob/4eaa5c93c632f1ea80e889b5458d5b95f57b59a2/native/src/sslcontext.c#L711 where the first argument is not `NULL` while the second one is `NULL`. 

Issue: Upon calling this function (`SSL_add_file_cert_subjects_to_stack()`) OpenSSL causes a "EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000001e5288f772e, pid=17588, tid=0x0000000000003aec". The reason is that the `NULL` pointer is passed along and reaches `openssl_fopen()`. While `fopen()` on Windows and POSIX-like properly sets `errno` on `NULL` pointer. The problem is the Windows code:https://github.com/openssl/openssl/blob/a6afe2b29a7b77956ef888653849f8cc38e39106/crypto/o_fopen.c#L41-L42

`strlen()` crashes upon a `NULL` pointer.

From my PoV:
* The behavior is inconsistent across platforms
* The higher level functions do not tell whether `NULL` pointer are valid input or not

Maybe the easiest way would be a `NULL` check and pass along to `fopen()` where it can set the `errno` properly.

**Comment by t8m** [comment]
I do not think that calling fopen with NULL pathname is actually valid. Yes, it might not crash for some implementations but it is not an explicitly documented behavior.

I believe we should check this in SSL_add_file_cert_subjects_to_stack() and fail if the second argument is NULL.

**Comment by michael-o** [comment]
> I do not think that calling fopen with NULL pathname is actually valid. Yes, it might not crash for some implementations but it is not an explicitly documented behavior.

At least both Windows and FreeBSD gave me a reasonable errno, but true if it is not documented do not rely on it.

**Comment by michael-o** [comment]
> OpenSSL doesn't set `errno` anywhere else for errors. It has it's own error mechanism. Why should this case be different?

I was solely referring to `fopen()` on those two platforms and its behavior with a `NULL` argument. No OpenSSL code involved.

**Comment by ChristopherSchultz** [comment]
Note that the behavior on the UNIX-like systems I've tried is that calling `openssl_fopen(NULL, "r")` results in a `NULL` return value with `errno` set to `EFAULT` while Windows uses `EINVAL`. This is not because of OpenSSL's behavior, but that of the underlying calls to `fopen`.

OpenSSL's call to `strlen` does not check for `NULL` filenames and thus causes a `SIGSEGV`. So the behavior is different across platforms -- more than just the differing underlying error codes used by `fopen`.

Yes, the calling code should be checking for `NULL`. In this case, the calling-code is actually OpenSSL itself via the `SSL_add_file_cert_subjects_to_stack`, `BIO_read_filename` and so on.

**Comment by Chriz76** [comment]
I did only a little bit of programming with open ssl  long time ago but now stumbled over this issue. So I apologize if my question is stupid.

I looked at the code and SSL_add_file_cert_subjects_to_stack expects a non null file pointer. This should be checked by the calling code. Like it is done in https://github.com/openssl/openssl/blob/f692ceeedcd104407b7672c67d62d6f86f8ac182/apps/s_client.c#L1904.

I checked other methods that expect a valid file pointer and they don't check the pointer, too. So could this issue be closed without changing any code because the fix should be implemented in the tomcat code?

**Comment by michael-o** [comment]
> I did only a little bit of programming with open ssl long time ago but now stumbled over this issue. So I apologize if my question is stupid.
> 
> I looked at the code and SSL_add_file_cert_subjects_to_stack expects a non null file pointer. This should be checked by the calling code. Like it is done in
> 
> https://github.com/openssl/openssl/blob/f692ceeedcd104407b7672c67d62d6f86f8ac182/apps/s_client.c#L1904
> .
> 
> I checked other methods that expect a valid file pointer and they don't check the pointer, too. So could this issue be closed without changing any code because the fix should be implemented in the tomcat code?

i don't think so. If other APIs do accept null pointers for the same type why shouldn't this one. It should be consistent and documented. Though, I have added the fixed into the code anymore.

**Comment by Chriz76** [comment]
I checked some other places where the api expects a non null pointer. Openssl expects the caller to give a non null pointer and doesn't  check it.

See [SSL_CTX_use_certificate_file](https://github.com/openssl/openssl/blob/a753547eefc9739f341824a0cb0642afe7a06fcc/ssl/ssl_rsa.c#L296) or [SSL_load_client_CA_file_ex](https://github.com/openssl/openssl/blob/a753547eefc9739f341824a0cb0642afe7a06fcc/ssl/ssl_cert.c#L738).

I suggest to close this issue. Maybe add an information to the documentation that required parameters may not be null.

**Comment by ChristopherSchultz** [comment]
I understand the consistency argument, and if the project chose to close this bug without making any changes I would understand that, too.

On the other hand, what is the argument *against* performing checks against input from client code? I don't think the "performance" argument holds any water. With OpenSSL – specifically – being such a foundational library for so many environments, I would think that safety would be a high priority.

**Comment by Chriz76** [comment]
I actually looked at this issue because I wanted to create some code to fix it. But now it looks like this would mean to change a lot of places to be consistent or to change the documentation for the same amount of places. I am curious what the openssl staff thinks? 

And maybe changing all the places to do a null check and return an error may even break existing non windows implementations that then might get another kind of error then now.

**Comment by zimirza** [comment]
I tried to add checks if file is `NULL`. I am not sure if the error is actually correct or not, in `ERR_raise` function.
