### ISSUE TITLE
[rt.openssl.org #4285] SSL_CTX_load_verify_locations() fails without error with invalid files

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2474]
Migrated from [rt.openssl.org#4285](https://rt.openssl.org/Ticket/Display.html?id=4285) (status was 'new')

Requestors:
* tss@iki.fi

From tss@iki.fi on 2016-02-01 20:56:28:
```
If loaded file isn't valid, SSL_CTX_load_verify_locations() returns 0,
but ERR_get_error() reports 0.

Debian unstable
Version: 1.0.2f-2

Example:

// create "empty-file" by e.g. touching it (or containing whatever garbage)
#include <openssl/ssl.h>
#include <openssl/err.h>

int main(void)
{
SSL_CTX *ssl_ctx;

SSL_library_init();
SSL_load_error_strings();

ssl_ctx = SSL_CTX_new(SSLv23_server_method());
if (!SSL_CTX_load_verify_locations(ssl_ctx, "empty-file", NULL)) {
printf("error = %lu\n", ERR_get_error());
}
return 0;
}

```

**Comment by pauli-oracle** [comment]
The issue here is in the `X509_load_cert_crl_file` function in `crypto/x509/by_file.c`.  The call to `PEM_X509_INFO_read_bio` is seeing nothing in the file and returning an empty stack of X509_INFO without raising an error.  At the end of the function, the count is returned -- thus the zero return with no error code.

It's possible to add a check at the end (before the _return count_) to raise an error:
```
    if (count == 0)
        X509err(X509_F_X509_LOAD_CERT_CRL_FILE, X509_R_EMPTY_FILE);
```

An alternative would be to update the function documentation in `doc/man3/X509_LOOKUP_hash_dir.pod` to clarify that a zero return without an error is possible:

> Functions return the number of objects loaded from file, which can be zero, or 0 in case of error.  It is necessary to call ERR_get_error(3) to distinguish the zero return cases. 

It isn't clear which alternative is more desirable here.  The former changes the behavour of the function, the latter gets into trouble if errors have been raised elsewhere but not checked for.

**Comment by levitte** [comment]
A curiousity is that if the input argument `file` is NULL, it will return 1 (!)

**Comment by pauli-oracle** [comment]
I missed that!

Both `X509_load_cert_file` and `X509_load_crl_file` both return 1 on NULL, they should return either 0 or error depending on which fix is deemed better.  Or should the NULL checks be removed entirely?

**Comment by levitte** [comment]
Frankly, I'm not sure why they check NULL at all...  Or well, I understand for 1.0.2, but not for 1.1.0 and on.

**Comment by mattcaswell** [comment]
This linked PR was merged so closing.
