### ISSUE TITLE
GPG key to verify the OpenSSL Archive is no longer found

### ISSUE THREAD

**Issue by a-burik** [openssl/openssl#24800]
Hi! 

Previously we had a mechanism to verify the openSSL archives we download from the source page (https://www.openssl.org/source/). The key is mentioned on this page, and titled the OpenSSL OMC key with fingerprint [EFC0 A467 D613 CB83 C7ED 6D30 D894 E2CE 8B3D 79F5](https://keys.openpgp.org/search?q=openssl-omc%40openssl.org)

As you can see, following this link returns a 404 which prevents us from verifying the archives we download.

**Comment by levitte** [comment]
That's...  infuriating.  That key has been *revoked*, which means that it can't be used to make new signatures, but can still be used to check old signatures, so still has a level of validity.

It seems that for revoked keys, keys.openpgp.org drops all UIDs, i.e. makes them not searchable by email address any more.  However, search by fingerprint still works: https://keys.openpgp.org/search?q=EFC0+A467+D613+CB83+C7ED+6D30+D894+E2CE+8B3D+79F5

**Comment by nhorman** [comment]
This sounds like its an idiosyncrasy of keys.openpgp.org in how it does key revocation.  Is there anything to be done here?

**Comment by asingh3-atlassian** [comment]
@levitte The OpenSSL 3.1.2 binary has a fingerprint.txt file which has a list of keys. I'm using those keys in my script to validate the integrity of the downloaded OpenSSL. On checking, I found that one of those keys `EFC0 A467 D613 CB83 C7ED 6D30 D894 E2CE 8B3D 79F5` is not available. Surprisingly, this key matches with the one you mentioned in your comment earlier.
https://keys.openpgp.org/search?q=EFC0+A467+D613+CB83+C7ED+6D30+D894+E2CE+8B3D+79F5

Because of this, my installation script is failing. Can I get your inputs on this? Thanks.

**Comment by levitte** [comment]
So it looks like after a time, keys.openpgp.org *removes* revoked keys.  How irritating.

I'll note, though, that OpenSSL 3.1.x is out of public support, and that the latest in that series was 3.1.8, with a tarball signed with our new release PGP key.  I'd urge you to upgrade to at least that, or to a newer minor version.

**Comment by levitte** [comment]
I've just now submitted a PR for the library web pages, where we make keys we've used available as a downloadable pubkeys.asc.  That files includes the missing (revoked, but still usable for verification) public key.  I hope that's going to be a good enough solution.

**Comment by asingh3-atlassian** [comment]
Thanks @levitte. Waiting for your PR to get merged. 🤞

**Comment by asingh3-atlassian** [comment]
Hi @levitte, just checking — was your PR merged?

**Comment by levitte** [comment]
Yes.  There's some text on the topic on https://openssl-library.org/source/, but long story short, here's a direct link to the public keys we publish: https://openssl-library.org/source/pubkeys.asc .

**Comment by levitte** [comment]
Note that more keys may be added to that file, so do reimport it a little now and then.

**Comment by asingh3-atlassian** [comment]
Hi @levitte , not sure if I'm missing something, but the key `[EFC0A467D613CB83C7ED6D30D894E2CE8B3D79F5](https://keys.openpgp.org/search?q=EFC0+A467+D613+CB83+C7ED+6D30+D894+E2CE+8B3D+79F5)` still seems to be missing, and that's why I am not able to verify the shasum of [OpenSSL 3.1.2](https://www.openssl.org/source/old/3.1.2/openssl-3.1.2.tar.gz) using [public key](https://www.openssl.org/source/old/3.1.2/openssl-3.1.2.tar.gz.asc).

To reproduce the issue,

```
# Download OPENSSL artifacts
curl -fsSLO --compressed --retry 5 --retry-all-errors "https://www.openssl.org/source/old/3.1.2/openssl-3.1.2.tar.gz"
curl -fsSLO --compressed --retry 5 --retry-all-errors "https://www.openssl.org/source/old/3.1.2/openssl-3.1.2.tar.gz.asc"

# Check shasum
gpg --batch --verify "openssl-3.1.2.tar.gz.asc" "openssl-3.1.2.tar.gz"
```


I get this error,
```
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: Signature made Tue Aug  1 13:36:58 2023 UTC
gpg:                using RSA key EFC0A467D613CB83C7ED6D30D894E2CE8B3D79F5
gpg: Can't check signature: No public key
```

I even tried using the [public key](https://openssl-library.org/source/pubkeys.asc) provided by you, but I get `verify signatures failed: Unexpected error`.

**Comment by levitte** [comment]
Did you import pubkeys.asc?  In other words, did you do this?

``` console
$ gpg --import pubkeys.asc
```

It might tell you that it can't check signature because of other keys missing, but that's no matter, you can try to receive them from key servers separately if you wish.
