### ISSUE TITLE
Stack smashing error in BIO_int_ctrl() on a 64-bit machine

### ISSUE THREAD

**Issue by cutefluffypuppy** [openssl/openssl#24875]
The function `BIO_int_ctrl`  gives a GCC "Stack Smashing" error on a 64-bit machine.
```
long BIO_int_ctrl(BIO *b, int cmd, long larg, int iarg)
{
    int i;

    i = iarg;
    return BIO_ctrl(b, cmd, larg, (char *)&i);
}
```
The problem is that `BIO_int_ctrl` passes a pointer to a 32-bit integer (`i`) to `BIO_ctrl`, but the latter returns a 64-bit value.

The solution is to pass `0` instead, as the value stuffed in '`i`' is not returned by `BIO_int_ctrl`.
```
long BIO_int_ctrl(BIO *b, int cmd, long larg, int iarg)
{
    return BIO_ctrl(b, cmd, larg, 0);
}
```

**Comment by nhorman** [comment]
But it doesn't pass a 32 bit integer, it passes a pointer to a 32 bit integer, ((char *)&I) which on a 64 but platform, is 8 bytes, so that should be fine.

That's not to say there's not a problem here though.  If something in the BIO_ctrl path dereferences that pointer as a uint64_t or some such, that would be an issue.

Do you have the stack trace of the error you can share here?

**Comment by cutefluffypuppy** [comment]
The problem isn't the passing of a parameter, the problem is what is returned in the parameter.

Something in the `BIO_CTRL` execution dereferences the pointer. Not 'as' `uint64`, because it is a pointer, but as `(unint64 *)`. So a 64-bit quantity will be written into `i`, which is a 32-bit quantity.

In detail, yes the pointer (`&i`) is 64 bits, but this is not the point. A pointer is being passed in order to return information. This is a normal C pattern. So let's call `(&i)` '`p`'. Then we are passing '`p`' to `BIO_ctrl`. At some point, `BIO_ctrl` is going to dereference '`p`', say `*p = x`. Here `x` is a 64-bit quantity. Now '`p`' points to '`i`', so the information, viz '`x`', will be written to '`i`'. But '`i`' is only 32 bits, so there's going to be 32 further bits left over. These overflow bits are going to corrupt the stack.

Unfortunately, when there is a Stack Smashing error, the program terminates without a traceback.

**Comment by tom-cosgrove-arm** [comment]
Without a stack trace (and even a reproducer - I don't see any description of what was actually being done) it's going to be almost impossible to figure out which callback is doing this.

Replacing a pointer in the call to `BIO_ctrl ()` with `0` is definitely wrong. Replacing it with `NULL` would be okay as long as all callbacks respect `NULL` here. But since we know we already have a callback with a bug handling `parg`, assuming all the rest are okay would likely be a mistake.

There's not really much else to be done. On a little-endian system, a hacky solution would be to replace the `int` with a `uint64_t` initialised to 0, so that correct callers would set the 32 least significant bits, but that still leaves sign extension as an issue, and big endian systems wouldn't be dealt with.

Of course, the value from `parg` isn't used, so maybe this doesn't matter.

And this code is very old, and no idea why it doesn't just take the address of `iarg` on the stack. Overall, not great code, and not surprising there a bugs in it. But we need more information to be able to track down the issue.

**Comment by nhorman** [comment]
at a minimum, if you can print out the values for cmd, larg and the contents of b, that would provide a clue as to whats going on here.  I'd suggest running your sample app under gdb with the following commands:
```
gdb <application>
set env LD_LIBRARY_PATH=<path to your openssl lib>
break BIO_int_ctrl
commands 1
print *b
print cmd
print larg
continue
^D
```
That will tell us what the bio in use is, and the value of the parameters immediately prior to the stack smashing occuring, which will give us a clue where to look

**Comment by cutefluffypuppy** [comment]
Please try out the following code for yourself. 
```
#include <stdio.h>
#include "openssl/bio.h"
int main()
{
	BIO *bio = BIO_new(BIO_s_mem());
	BIO_write(bio, "message", 7);
	int len = BIO_int_ctrl(bio, BIO_CTRL_INFO, 0, 0);
	printf("len %d\n", len);
	BIO_free(bio);
	return 0;
}
```
When I compile and run this on Ubuntu 22:
```
$ gcc -g -Wall -Iopenssl-openssl-3.3.1/include -c -o biotest.o biotest.c
$ gcc -o biotest biotest.o openssl-openssl-3.3.1/libcrypto.a
$ ./biotest
*** stack smashing detected ***: terminated
Aborted (core dumped)
```

**Comment by nhorman** [comment]
Thank you that helps.

The problem is occuring because the BIO_CTRL_INFO command, when called on a BIO_s_mem object assumes expects that the pointer value points to an object of type char * (i.e. a 64 bit pointer on 64 bit systems), but you are passing a 32 bit integer, leading to the stack overflow.  so now we know the root cause.

That said, calling BIO_int_ctrl for this bio type is an api misuse.   BIO_CTRL_INFO should only be passed vi BIO_ctrl, or preferably via the macros that wrap these calls (see BIO_get_mem_data).

From the docs:
https://www.openssl.org/docs/man3.2/man3/BIO_int_ctrl.html

Nominally, direct calls to BIO_ctrl and BIO_int_ctrl shouldn't be made, but rather the macro-wrapped variants should be used to avoid this kind of type mismatching.

Seems like this should be marked as resolved/not a bug
