### ISSUE TITLE
DTLS1.2 server sends fatal alert when receives second ClientHello with invalid cookie after sending the first HelloVerifyRequest

### ISSUE THREAD

**Issue by longparty** [openssl/openssl#25051]
According to RFC6347:
**4.2.1 Denial-of-Service Countermeasures**
If a server receives a ClientHello with an invalid cookie, it SHOULD treat it the same as a ClientHello with no cookie. This avoids race/deadlock conditions if the client somehow gets a bad cookie (e.g., because the server changes its cookie signing key).

But in openssl1.1.1, when the server receives a second ClientHello with an invalid cookie, it will send a HANDSHAKE_FAILURE alert instead of sending a HelleVerifyRequest again
https://github.com/openssl/openssl/blob/b372b1f76450acdfed1e2301a39810146e28b02c/ssl/statem/statem_srvr.c#L1698-L1710
Is this a bug that openssl is not consistent with rfc6347?

**Comment by mattcaswell** [comment]
It's not really a bug since it's only a SHOULD in the RFC. We also handle this as expected in the case where the application is using `DTLSv1_listen`:

https://github.com/openssl/openssl/blob/871c534d39efecc2087da0fd24ff72e2712031a4/ssl/d1_lib.c#L626-L649

Although I would classify this as "not a bug" we might consider some future community PR to change this behaviour.
