### ISSUE TITLE
Potential file descriptor leak in RAND_write_file

### ISSUE THREAD

**Issue by nielsdos** [openssl/openssl#25064]
Hello. I'm working on a static analysis tool to detect incomplete error handling code.

My tool reported the following:

In the following code, `fd` is assigned the return value of `open`, and in case `open` succeeded, it tries to call `fdopen`.
https://github.com/openssl/openssl/blob/871c534d39efecc2087da0fd24ff72e2712031a4/crypto/rand/randfile.c#L210-L212

In theory, `open` could succeed while `fdopen` could fail.
The following fallback code checks if `fdopen` has failed:

https://github.com/openssl/openssl/blob/871c534d39efecc2087da0fd24ff72e2712031a4/crypto/rand/randfile.c#L237-L238

In that case that `out == NULL`, the file descriptor `fd` is never closed. I.e. there's a `close(fd);` call missing in that error handling block.

I understand this is quite an unlikely/theoretical bug.
I could also be wrong because my results are based on static analysis even though I manually read the code as well.

Thanks in advance

**Comment by coolshrid** [comment]
This does not seem to be a file descriptor leak. Based on the man page for [fdopen](https://linux.die.net/man/3/fdopen). It states that 

"*...The file descriptor is not dup'ed, and will be closed when the stream created by fdopen() is closed. ...*"

**Comment by nielsdos** [comment]
The point is that if `fdopen` fails (e.g. on ENOMEM), then the file descriptor does leak.

**Comment by coolshrid** [comment]
You are right `nielsdos` (I overlooked that). I added a check after the `fdopen` and raise an exception.

**Comment by paulidale** [comment]
The fix is incorrect: the file mode is critical here and `fopen(3)` doesn't let you set the mode like `open(2)` does.

If you do want to submit a fix for this, please raise a pull request so we can run it through our review processes.

**Comment by IDisposable** [comment]
#25080 doesn't actually `close()` the `fd` so it does not _actually_ fix _this_ issue. Additionally it changes the flow so we don't even attempt the subsequent attempt to use openssl_fopen in write+binary mode.

**Comment by coolshrid** [comment]
I created a new pull request #25081, since #25080 was having some white space issues.

From: Marc Brooks ***@***.***>
Date: Thursday, August 15, 2024 at 12:45
To: openssl/openssl ***@***.***>
Cc: shridhar ***@***.***>, Comment ***@***.***>
Subject: Re: [openssl/openssl] Potential file descriptor leak in RAND_write_file (Issue #25064)

#25080<https://github.com/openssl/openssl/pull/25080> doesn't actually close() the fd so it does not actually fix this issue. Additionally it changes the flow so we don't even attempt the subsequent attempt to use openssl_fopen in write+binary mode.
