### ISSUE TITLE
FRAGMENTED_CLIENT_HELLO failure on DTLS IPv6 connections.

### ISSUE THREAD

**Issue by Splediferous** [openssl/openssl#25380]
SSL Version: 3.3.2. But is also evident in all 3.3.x versions.
OS: Windows 10

Demonstrated on localhost connections.

Only affects IPv6 DTLS connections.
Version 3.2.1 behaves as expected with a successful DTLS connection established for both IPv6 and IPv4 addresses.

When selecting an IPv6 address for DTLS, the connection attempt fails with the Error "FRAGMENTED_CLIENT_HELLO" at DTLSv1_Listen. 
Selecting an IPv4 address with identical parameters successfully connects.  
Limiting the number  of encryption algorithms (reduce the Client Hello size) also results in a successful connection.

Wireshark exports:
[export_3.2.1_IPv6.txt](https://github.com/user-attachments/files/16870368/export_3.2.1_IPv6.txt)
[export_3.3.2_IPv6_Fail.txt](https://github.com/user-attachments/files/16870371/export_3.3.2_IPv6_Fail.txt)
[export_3.3.2_IPv6_pass.txt](https://github.com/user-attachments/files/16870373/export_3.3.2_IPv6_pass.txt)

**Comment by mattcaswell** [comment]
This is expected behaviour and  just means that the a ClientHello has become fragmented because it has exceeded the MTU size. DTLSv1_listen will report this error on the second (or subsequent) fragment of such  a ClientHello. This is actually a non-fatal error and DTLSv1_listen returns 0 in this case (which the man page indicates as non-fatal). The man page says this:

> A return value of 0 indicates a non-fatal error. This could (for
example) be because of nonblocking IO, or some invalid message having been
received from a peer. Errors may be placed on the OpenSSL error queue with
further information if appropriate. Typically user code is expected to retry the
call to DTLSv1_listen() in the event of a non-fatal error.

**Comment by Splediferous** [comment]
Thanks for the prompt reply.

Can confirm this is not a fatal error. 
Continuing by calling  **_DTLSv1_listen_** repeatedly (on a non-blocking connection) until non zero results in a successful connection or error.
