### ISSUE TITLE
possible memory leak on EVP_DigestInit_ex() - FreeBSD

### ISSUE THREAD

**Issue by devnull-hub-lab** [openssl/openssl#25456]
Hey guys,

I think there is a memory leak on EVP_DigestInit_ex()

When compiled with -fsanitize=address flag, EVP_DigestInit_ex always return false.
Without -fsanitize=address flag, it works perfectly.

```c
#include <stdio.h>
#include <openssl/evp.h>
#include <string.h>

int main() {
    const char *message = "My Message to be hashed";
    unsigned char digest[EVP_MAX_MD_SIZE];
    unsigned int digest_len;

    EVP_MD_CTX *mdctx;
    if ((mdctx = EVP_MD_CTX_new()) == NULL)
    {
        fprintf(stderr, "Error EVP_MD_CTX_new \n");
        return 1;
    }

    if (EVP_DigestInit_ex(mdctx, EVP_sha256(), NULL) != 1)
    {
        fprintf(stderr, "Error \n");
        EVP_MD_CTX_free(mdctx);
        abort();
        return 1;
    }

    //.....I ignored EVP_DigestUpdate(), EVP_DigestFinal_ex(), since the error occurred in EVP_DigestInit_ex above.

    EVP_MD_CTX_free(mdctx);

    return 0;
}
``` 

$ cc ex2.c -o ex2 -lssl -lcrypto -g -O0 -fno-inline -fsanitize=address 

Tested on FreeBSD (14.0 and 14.1)
OpenSSL 3.0.13
Tested on CLANG 18.1.5 and CLANG 16.0.6

On Linux (tested on debian/ubuntu), it seems it works.

**Comment by botovq** [comment]
As pointed out in https://github.com/libressl/portable/issues/1098 this is because ASAN on FreeBSD (and NetBSD) intercepts `SHA256_Init()` with incompatible signature since that is intended to replace the function of the same name in libmd [which returns nothing][1].

This is a toolchain issue that needs to be solved by FreeBSD and NetBSD and can therefore probably be closed here. I reported this to FreeBSD: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=281685

[1]: https://man.freebsd.org/cgi/man.cgi?query=SHA256_Init&apropos=0&sektion=0&manpath=FreeBSD+14.1-RELEASE+and+Ports&arch=default&format=html

**Comment by t8m** [comment]
Thank you @botovq. Closing this then.
