### ISSUE TITLE
OPENSSL_3.2.0' not found (required by openssl)

### ISSUE THREAD

**Issue by Burny4600** [openssl/openssl#25462]
Update from OpenSSL 3.0.14 4 Jun 2024 (Library: OpenSSL 3.0.14 4 Jun 2024) on OpenSSL 3.3.2 under Debian the update completes incorrectly.

Raspberry Debian Version:
Linux 6.6.47+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.47-1+rpt1 (2024-09-02) aarch64

Openssl Version Check
openssl: /lib/aarch64-linux-gnu/libssl.so.3: version OPENSSL_3.2.0' not found (required by openssl) openssl: /lib/aarch64-linux-gnu/libcrypto.so.3: version OPENSSL_3.3.0' not found (required by openssl)
openssl: /lib/aarch64-linux-gnu/libcrypto.so.3: version `OPENSSL_3.2.0' not found (required by openssl)

**Comment by nhorman** [comment]
are you building openssl yourself or just installing updated debian packages?  the latter is something you need to contact debian about

**Comment by Burny4600** [comment]
I install OpenSSL myself.

Installation steps:
sudo su
cd /home/Admin
wget https://github.com/openssl/openssl/releases/download/openssl-3.3.2/openssl-3.3.2.tar.gz -O openssl-3.3.2.tar.gz
tar -xvzf openssl-3.3.2.tar.gz
cd openssl-3.3.2
./config --prefix=/usr zlib-dynamic --openssldir=/etc/ssl shared
make test
make install


Raspberry Pi OS Bookworm Full Desktop
Linux 6.6.47+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.47-1+rpt1                                                                                                     (2024-09-02) aarch64

**Comment by tom-cosgrove-arm** [comment]
So can I check: this is now working?

Note that in general we don't recommend changing the system version of OpenSSL, since various system components can depend on a specific version - it's usually better to upgrade with system tools (e.g. `apt`, `yum`, etc).

If you need a specific version of OpenSSL for a particular piece of software, it's best install it in a separate location, and point the specific software at it

**Comment by Burny4600** [comment]
Thanks for the info.
