### ISSUE TITLE
OpenSSL Initialization Failure Due to Manually Mapped DLLs Not Recognized by GetModuleHandleExA

### ISSUE THREAD

**Issue by pinwhell** [openssl/openssl#25569]
Say we stop using `LoadLibraryA` instead we create its equivalent for security purposes, the module we map windows wont be aware of it, for OpenSSL modules, when we map it, and attempt to initialize OpenSSL, its failing to robustly initialize on that Context, the reason exaclty becouse of `ossl_init_load_crypto_nodelete`, who returns false inside Crypto Initialize routine, becouse of the fact that WinApi `GetModuleHandleExA` is not aware of the manually mapped modules, how to approach this problem? notice that appart from that, when redirecting to another legit module, and forcing the function to return true, everything initialize as expected and OpenSSL works as normal (Sanity Tested Extensively).
Version 1.1.1w
to reproduce the issue simply use any dll manual mapper and simply call `OPENSSL_init_crypto`

**Comment by tom-cosgrove-arm** [comment]
Is this an issue in OpenSSL, or should it be a discussion?

**Comment by nhorman** [comment]
I think thats to be determined.  Currently whats being attempted I don't think can be done.  The question to answer is, should it be possible?  i.e. is this a feature request?

**Comment by tom-cosgrove-arm** [comment]
> The question to answer is, should it be possible?

`LoadLibraryA` is a fundamental operating system API. Replacing these is almost certainly going to cause problems in some use-cases.

> Say we stop using `LoadLibraryA` instead we create its equivalent for security purposes

Without knowing how the "equivalent" is created, and what "security purposes" means, this is a very vague requirement.

> `GetModuleHandleExA` is not aware of the manually mapped modules

Since `GetModuleHandleExA` is a fundamental operating system API that works with `LoadLibraryA`, it's clear that the "equivalent to LoadLibraryA" API isn't really equivalent.

It may be that what the OP wants ("securing" `LoadLibraryA` for an unspecified meaning of "securing") could be achieved by hooking `LoadLibraryA` and only allowing whitelisted requests through.

**Comment by nhorman** [comment]
@tom-cosgrove-arm are you suggesting that LoadLibraryA is a weak symbol that the author can override and call the underlying function after passing a whitelist test?  That would make sense

**Comment by pinwhell** [comment]
not exaclty guys, let me explain why it precisely fails!, that call to GetModuleHandleEx was to pin the current OpenSSL module so it cant be unloaded, as you can see this action fails becouse the Module is not mapped by the OS, instead by us!, so the os is not aware of such module thus the reason why GetModuleHandleEx fails!, i was experimenting did a patch to that single thing, and OpenSSL succesfully initialized, worked, and was extensively tested, and passed all tests

**Comment by pinwhell** [comment]
when i said, "Replaced" LoadLibraryA, i was refering mimicing its action, meaning manually loading the DLL instead of calling LoadLibraryA directly

**Comment by nhorman** [comment]
You're still not being particularly clear in what you are trying to do.  Its clear that the call to GetModuleHandleEx pins libcrypto.so so that it can't be unloaded.

From that we can conclude that the ability to pin a library is a requirement for openssl on windows.

Whats unclear is exactly how you are mimicing the loading of libcrypto.  If you are not calling LoadLibraryA, what are you doing?  Are you just opening the file, memory mapping it, and resolving symbols on your own?

If so, OpenSSL was never meant to be loaded in that fashion.  Its always been assumed that the library is loaded by the operating systems, using API's that inform the OS of that operation. Thats not a bug, its a design choice.

You can continue to explore this approach, and if you have a proposed change, please feel free to post it, and we will gladly review it, but I expect your use case is not one openssl will likely choose to support natively

**Comment by pinwhell** [comment]
> You're still not being particularly clear in what you are trying to do.  Its clear that the call to GetModuleHandleEx pins libcrypto.so so that it can't be unloaded.
> 
> 
> 
> From that we can conclude that the ability to pin a library is a requirement for openssl on windows.
> 
> 
> 
> Whats unclear is exactly how you are mimicing the loading of libcrypto.  If you are not calling LoadLibraryA, what are you doing?  Are you just opening the file, memory mapping it, and resolving symbols on your own?
> 
> 
> 
> If so, OpenSSL was never meant to be loaded in that fashion.  Its always been assumed that the library is loaded by the operating systems, using API's that inform the OS of that operation. Thats not a bug, its a design choice.
> 
> 
> 
> You can continue to explore this approach, and if you have a proposed change, please feel free to post it, and we will gladly review it, but I expect your use case is not one openssl will likely choose to support natively

I am mapping the library, solving its imports, handling relocations, handling TLS, which is enough to make everything works, as you see for security reasons I am not mapping it in the OS records of loaded libs, otherwise simply call LoadLib in the first place and problem solved, maybe there could be a option to control pinning mechanism manually so users can selectively decide if pinning or not, to avoid this type of problems, I guess it definitely an edge case probably beyond scope of OpenSSL, but could be cool to support that bare metal like environment

**Comment by pinwhell** [comment]
> You can compile OpenSSL with "no-pinshared" to turn off pinning.

If this is such an option I do believe it would be the ideal solution, I wasn't aware of it, Just to be clear for anyone who might get the same problem, on the 1.1.1w just handling this issue, OpenSSL seems to behave properly when manually mapped, Thanks guys ...
