### ISSUE TITLE
Appending data to ECDSA signature occasionally does not cause verification to fail

### ISSUE THREAD

**Issue by iomartin** [openssl/openssl#25589]
When I ECDSA-sign something and then append garbage data to the signature and try to verify, this sometimes fails, and sometimes passes. For example consider the following commands:

```bash
dd if=/dev/zero bs=1M count=1 of=/tmp/input
openssl ecparam -name prime256v1 -genkey -noout -out /tmp/key.priv
openssl ec -in /tmp/key.priv -pubout -out /tmp/key.pub
openssl dgst -sha1 -sign /tmp/key.priv -out /tmp/sig_file /tmp/input
openssl asn1parse -in /tmp/sig_file -inform der
echo -n 'aa' >> /tmp/sig_file
openssl dgst -sha1 -verify /tmp/key.pub -signature /tmp/sig_file /tmp/input
```

I noticed that it only passes when both r&s signatures are 33 bytes each. If either or both are 32 bytes, then verify fails (as it should).

This was confirmed with 3.0.2 (shipped with Ubuntu 22.04) as well as 3.5.0-dev (self-compiled on FreeBSD 14.0, hash 12d14de641c299ec080edc521f7080acc44e366f).

**Comment by t8m** [comment]
This is an artifact of how the `openssl dgst` app handles the signature file. It reads only EVP_PKEY_get_size(sigkey) bytes from the signature file. That value is the maximum size of a signature the given pkey can produce.

I do not think changing this in stable branches would be a good idea because some users might actually depend on this (mis?)feature.

I have no problem changing the behavior on the master branch though.

**Comment by iomartin** [comment]
Thanks @t8m, your explanation makes sense. Is there an an alternative (via the CLI) that is guaranteed to always fail? I'm trying to build a test like this in my CI

**Comment by t8m** [comment]
`openssl pkeyutl -rawin ...` should work correctly for your use case.

**Comment by iomartin** [comment]
Thanks @t8m, using `openssl pkeyutl -rawin` works for me!
