### ISSUE TITLE
openssl

### ISSUE THREAD

**Issue by dwan87** [openssl/openssl#25828]
yl@yl-virtual-machine:~/sensor$ openssl version -a
openssl: /lib/x86_64-linux-gnu/libssl.so.3: version `OPENSSL_3.2.0' not found (required by openssl)
openssl: /lib/x86_64-linux-gnu/libcrypto.so.3: version `OPENSSL_3.0.9' not found (required by openssl)
openssl: /lib/x86_64-linux-gnu/libcrypto.so.3: version `OPENSSL_3.3.0' not found (required by openssl)
openssl: /lib/x86_64-linux-gnu/libcrypto.so.3: version `OPENSSL_3.2.0' not found (required by openssl)

```[tasklist]
### Tasks
```

**Comment by dwan87** [comment]
how to fix it

**Comment by tom-cosgrove-arm** [comment]
This seems to be more a question about how to get OpenSSL installed rather than an issue with OpenSSL itself, and as such should be opened as a discussion rather than an issue.

In order for us to help you, we really need a bit more than some error messages: what system are you on, and what exactly have you done to get to this point?

**Comment by dwan87** [comment]
Thanks for your reply. I added export OPENSSL=/usr/local/openssl/bin export PATH=$OPENSSL:$PATH:$HOME/bin to /etc/profile and sourced /etc/profile. However, when checking the version as shown in the title, it prompted that the relevant library could not be found. The above is the process of my problem (before this, I had an old version of openssl in my ubuntu, but I did not uninstall it but directly downloaded the new openssl 3.3.2). Then I added "export LD_LIBRARY_PATH=/usr/local/openssl/lib64" souce ~/.bashrc to ~/.bashrc to solve this problem.
