### ISSUE TITLE
Add provider signature template code

### ISSUE THREAD

**Issue by baentsch** [openssl/openssl#25894]
Following up on https://github.com/openssl/openssl/pull/25640 this issue is to suggest adding template code for signature provider implementation to simplify integration of different PQ signature algorithms.

Code for this may be used from https://github.com/openssl/openssl/pull/25882 to ease that PR's integration and further speed up the development of an ML-DSA integration in parallel.

Tagging @slontis for willingness to split out that part of #25882 to implement this issue and thus kick-start the ML-DSA integration in parallel?

**Comment by slontis** [comment]
Cant say I am overly motivated by the whole template idea, quite a bit of what was done for the kem case seemed to be tracing related (which I find fairly pointless). gdb works just fine when you are inside OpenSSL, especially if you are doing test driven development. I could write base code for ML-DSA though, since it should be very similar to the existing code for SLH-DSA.

**Comment by baentsch** [comment]
> since it should be very similar to the existing code for SLH-DSA

That's what I'd think too, so Thanks for the offer, @slontis ! I'd be fine closing/withdrawing this issue/proposal then unless someone else thinks it'd have other value.

**Comment by baentsch** [comment]
> I'm with @slontis here. I haven't found the templates to be very useful for KEM or key management.

OK. The more I think about it, they've been intended as a crutch to allow people without _any_ provider experience to get going. But the two of you don't fit that bill. Given how far down the road you already are and how much of that code can be (re)used in ML-DSA, let's close the issue.
