### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [openssl/openssl#259]
The function "[siglongjmp](http://pubs.opengroup.org/onlinepubs/9699919799/functions/siglongjmp.html "non-local goto")" does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers#SIG30-C.Callonlyasynchronous-safefunctionswithinsignalhandlers-NoncompliantCodeExample%28longjmp%28%29%29 "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for your function "[common_handler](https://github.com/openssl/openssl/blob/7aa0b022460e1a7bfdf5c70e8cd084d916bac012/crypto/sparcv9cap.c#L113 "Reconsider signal handling implementation?")".

**Comment by jillest** [comment]
As long as that code needs to probe instructions that may fault and returning from the signal handler causes the faulting instruction to be retried, calling some sort of longjmp from the signal handler is hard to avoid (alternatives would be to fork a process and have it terminate on a fault (slow and more likely to cause annoying logs) or overwrite the faulting instruction with nops in the signal handler).

Per POSIX, calling `longjmp()` from a signal handler is not always undefined, though. Via issue http://austingroupbugs.net/view.php?id=516 this was clarified. The code could be fixed by setting the signal handler with the `siglongjmp()` inside the `if (sigsetjmp` blocks only. This is because `sigsetjmp()` is not async-signal safe, in practice because it is not atomic. This can really only cause trouble if an unexpected `SIGBUS` or `SIGILL` occurs or if someone sends one from outside. The latter could be detected via `si_code` in an `SA_SIGINFO` handler.

Also, the application should avoid calling `OPENSSL_cpuid_setup()` while multiple threads exist, since the signal dispositions are a process-wide resource (not per thread).

**Comment by richsalz** [comment]
There is nothing to do here, because the code in question is only built on specific architectures where it is known to work.  Closing this.
