### ISSUE TITLE
Need a way to supress prefixing local directories to OPENSSLDIR for mobile clients

### ISSUE THREAD

**Issue by noloader** [openssl/openssl#2592]
I've been testing ways to work with a mobile platform's sandbox or walled garden. In this arrangement, OpenSSL proper is not installed on the mobile client. Rather, a program is linked with the ssl and crypto libraries, and everything is relative to an install directory like `/var/mobile/Applications/A4D17A73-84D7-4628-9E32-AEFEA5EE6153`. The last part is a UUID, and its not known in advance.

The test below were carried out on Mac OS X 10.9 for an iOS target. Things seem to go fairly well, except for the `-DOPENSSLDIR="\"/usr/local/NSHomeDirectory()""`.

Attempting to twiddle `--prefix` results in `Directory given with --prefix MUST be absolute`.

Please provide a way to suppress prefixing local directories to OPENSSLDIR for mobile clients. Or maybe, provide a means to use a function call like `NSHomeDirectory()` as the OPENSSLDIR.

-----

```
export CC=clang
export CROSS_TOP=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/
export CROSS_SDK=iPhoneOS.sdk

./Configure ios-cross --openssldir="NSHomeDirectory()"
...

$ make
perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" crypto/include/internal/bn_conf.h.in > crypto/include/internal/
bn_conf.h
perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" crypto/include/internal/dso_conf.h.in > crypto/include/internal
/dso_conf.h
perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.
h
make depend && make _all
make[1]: Entering directory '/Users/jwalton/openssl'
make[1]: Leaving directory '/Users/jwalton/openssl'
make[1]: Entering directory '/Users/jwalton/openssl'
( trap "rm -f crypto/aes/aes-armv4.s.*" INT 0; \
  CC="clang" perl crypto/aes/asm/aes-armv4.pl ios32 crypto/aes/aes-armv4.s.S; \
  clang  -I. -Icrypto/include -Iinclude -Icrypto -DDSO_DLFCN -DHAVE_DLFCN_H -DND
EBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_BN_ASM
_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSA
ES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/
NSHomeDirectory()\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -O3 -D_REENTR
ANT -arch armv7 -mios-version-min=6.0.0 -isysroot /Applications/Xcode.app/Conten
ts/Developer/Platforms/iPhoneOS.platform/Developer//SDKs/iPhoneOS.sdk -fno-commo
n  -E crypto/aes/aes-armv4.s.S | \
  perl -ne '/^#(line)?\s*[0-9]+/ or print' > crypto/aes/aes-armv4.s.i && \
  mv -f crypto/aes/aes-armv4.s.i crypto/aes/aes-armv4.s )
...
```

**Comment by dot-asm** [comment]
Well, you can't really expect `NSHomeDirectory()` to work, right? At least not without it being explicitly *programmed* to be recognized as instruction to do something specific at run time. And this implies that we work out convention for how to present the instruction. I mean what if you wanted catalog to be named literally `NSHomeDirectory()`? But at any case, one can wonder if OpenSSL is actually right place to do this. It would probably be more appropriate to let application do that kind of stuff, e.g. by allowing application to override OpenSSL internal file I/O operations or at least file open operation. In fact there already is kind of precedent for that, Windows-specific Applink thing. Though it's quite bad example, because it's meant as last-resort aid thing for legacy applications in specific position, it's not recommended for new applications to rely on. But either way I'd insist that it should rather be something for application to take control and decide over. Note that it's actually possible to take over libc calls and "emulate" any file system layout you wish, see https://github.com/openssl/openssl/blob/OpenSSL-fips-2_0-dev/iOS/fopen.m for an example, but that would affect whole application, not just OpenSSL libs. And it probably would be rejected by the AppStore vetting procedure, so it's not really the answer. But it also illuminates following practical problem specific to iOS. You refer to NSHomeDirectory(), but can you call it from C? I mean don't you have to call it from Objective C? It's not a problem to link together object modules compiled by Objective C and C, but we, OpenSSL that is, don't really want to go there, not at lib level. In other words this is another argument for giving control to the application. BTW, If fopen is the only call that needs to be overridden, then one should recall that there is only one place it's made, crypto/o_fopen.c. This also means that it would be right spot at least to experiment to figure out what would be the right thing to do...

**Comment by richsalz** [comment]
Maybe just overriding ```getenv``` is enough?  Or maybe just have a call to "gethomedir" or something?

**Comment by dot-asm** [comment]
> Maybe just overriding getenv is enough?

You mean that when OpenSSL asks for OPENSSL_CONF it will return something that would be relative to NSHomeDirectory()? Yes, that would work, but only for config file, while you might be interested to pick more files from per-application directory. But still note that intercepting at libc level it likely to be rejected by AppStore.

>  Or maybe just have a call to "gethomedir" or something?

But it still implies that there would be code that would make some substitutions in to-be-opened filename. For example if you say that prefix is $HOME, where $HOME is not expanded at config time[!], but passed down as literal, then there ought to be code that searches for $HOME and replaces it with corresponding environment value. And what I'm saying is that we are probably better off if it's left to application. So that application developer can make it as flexible as it suits the application/environment...

**Comment by dot-asm** [comment]
Or maybe you refer specifically to the "practical problem". Well, yes, there might be ready-to-use C-callables... I don't know. Idea is that if application does it, then I don't even need to know :-)

**Comment by oneton** [comment]
Since **dot-asm** requested my opinion here, I had a look at this. My personal contribution to the [build script](https://github.com/x2on/OpenSSL-for-iPhone) and investigation of the iOS32 asm issue is quite out of balance compared to my experience with using the library. I did some initial work on an app I had/have in mind, but so far it only reads/processes certificates. (Priorities....)

So far, I haven't run into this problem, since I never touched a function that reads files from OPENSSLDIR. Checking my build, it actually contains a fixed reference to my build directory, which will never work on the iPhone. This is the case for all (default) builds created with the script, so I'm assuming other users also didn't run into this problem.

The first thing that comes to my mind is a relative path, but it's so obvious that I suppose there is an equally obvious reason not to use/mention it.

**Comment by noloader** [comment]
> oneton> The first thing that comes to my mind is a relative path, but it's so obvious that I suppose there is an equally obvious reason not to use/mention it.

I'd like to disable it all together, but there does not seem to be interest in it: [CONF-less OpenSSL configuration](https://mta.openssl.org/pipermail/openssl-users/2016-November/004855.html).

If I can't disable it, then I'd like to move it into the app's sand box (*q.v.*).

> dot-asm> Well, you can't really expect NSHomeDirectory() to work, right? 

Yes. This is the first baby step to see what breaks.

I would not be surprised if Apple got aggressive about their filesystem policies and banned OpenSSL-based apps because of the potential out-of-sandbox accesses. The decision would likely drive folks to Apple's `SecureTransport`, so it could make a good policy decision if they wanted it.

**Comment by dot-asm** [comment]
> The first thing that comes to my mind is a relative path

And the question is relative to what? To *current* working directory. And what is current working directory for iOS application? Or rather do they all start in unique per-app directory? And prohibited to change it? I don't have experience with applications that are suitable for submission to iOS App Store, but I know that openssl binaries launched under debugger (but they still get "deployed" and appear as icons on home screen) initially end up in /. That's why first thing above mentioned fopen.m does is change directory to app-specific one. In general case assuming something about current working directory or changing it in *library* such as OpenSSL is inappropriate. And I don't see that it would be appropriate in iOS. In other words relative path is no-go.

**Comment by dot-asm** [comment]
> I would not be surprised if Apple got aggressive about their filesystem policies and banned OpenSSL-based apps because of the potential out-of-sandbox accesses.

So that you wouldn't be able to dynamically link with /usr/lib/libsomething.dylib? I mean application has to access a whole bunch of files outside sandbox, so why would they get angry about out-of-sandbox access? Of course they can make a white list and get cranky about violations, or see where does the call originate from, application itself or system-provided shared library. All this despite the fact that there already is mechanism in place, access control one. Or well, who said that they have to behave rationally...

**Comment by mattcaswell** [comment]
There doesn't seem to be any action required here. Closing.
