### ISSUE TITLE
CMS_get1_{certs,crls}() behavior change and inconsistency with CMS_get0_signers() in OpenSSL 3.4

### ISSUE THREAD

**Issue by botovq** [openssl/openssl#26079]
Before #18916 was merged, CMS_get1_{certs,crls}() would return NULL in the following cases:

1. The content type isn't signed or enveloped data (authenticated or not)
2. The optional CertificateChoices or RevocationInfoChoices ASN.1 field is absent
3. There are no X.509 Certificates or CertificateLists in said choices (other information may still be there, but inaccessible)
4. An allocation error occurred

The caller can exclude 1 by checking the type beforehand. However, options 2-4 were indistinguishable. Depending on the context, and on how strict one wants to be, the distinction between 2 and 3 doesn't matter. In the RPKI the distinction is relevant since the commonly chosen approach is to be as strict as possible (mainly limited by the leniency and brokenness of various ASN.1 parsers).

Now the API change allows distinguishing between 4 on the one hand and 2 and 3 on the other. This is an improvement. Except: it subtly changed behavior and broke a best-effort check for excluding 2 and 3 that resulted in (easy to fix) real-world breakage.

Another problematic aspect is that the API is now inconsistent with `CMS_get0_signers()` which returns NULL on error or on empty set of signerInfos, which is not an error since RFC 5652 states in section 5.1 that:

      signerInfos is a collection of per-signer information.  There MAY
      be any number of elements in the collection, including zero.

Thus, I'd be inclined to describe the old "suboptimal" behavior as broken and the new behavior as perhaps slightly less broken and inconsistent.

Another fun bit about `CMS_get0_signers()` is that the get0 is a hint at having to use `sk_X509_free()` as opposed to `sk_X509_pop_free()`, a trap which the documentation is silent about.

It is of course up to OpenSSL to decide how to proceed. I think the API in both the form it had prior to #18916, and in its current form, is unsalvageable and would therefore suggest deprecation. As a consequence, I would also suggest reverting the change and developing a replacement API that has no backward compatibility issues. This might also be a chance to accommodate support for attribute certificates in CMS...

**Comment by t8m** [comment]
**OTC: Should the behavior change in 3.4.0 be reverted?**

**Comment by DDvO** [comment]
As I wrote [here](https://github.com/openssl/openssl/pull/18916#issuecomment-2504758878), for any API function,
it should not and cannot be the job of the caller to try and find out in advance or thereafter all error conditions that the function execution may suffer from. In particular since the internals of the function is allowed to change over time without notice.
This would work out only in case all its possible error conditions were documented and would be guaranteed not to change.
Yet this would place needless restrictions on the function implementers
and would be too much of a burden for all involved: with its implementation, documentation, and use.

In my view the type signature of the function `CMS_get1_crls()` and the like is okay (alternatives would have been a little awkward), but for sure its behavior in case of an empty set of crls was not great -
likely this was not by design, but by accident. Its suboptimal behavior [got documented](https://github.com/openssl/openssl/commit/e33ffaca12c) after the fact.

IMO, the new semantics is the best one can do here without changing the type signature of the function.
The only problem is that it is not fully backward compatible with the original suboptimal behavior.

And right, something should be done also on `CMS_get0_signers()`.
Among others, as discussed [here](https://github.com/openssl/openssl/pull/18916#issuecomment-2506211735), its documentation does not correctly describe its suboptimal behavior on an empty set of signers:
> CMS_get0_signers() returns all signers or NULL if an error occurred.

because in general (at least during construction of a CMS message, and maybe for unsigned messages) it can legitimately be empty. So this case should not be seen as an error at the level of this function.

**Comment by botovq** [comment]
In-band error signalling rarely works well in C and it gets really hairy when absence is an acceptable outcome. As mentioned, here you even have two forms of absence a caller might care about distinguishing.

> it should not and cannot be the job of the caller

Yes, I agree. Hence my use of scare quotes around the word you seem to be fond of using, as that has the connotation of being somewhere in the vicinity of good.

> alternatives would have been a little awkward

Hard to respond to since you don't say what alternatives you have considered. Something like
```C
int CMS_get1_crls_ex(CMS_ContentInfo *cms, STACK_OF(X509_CRL) **crls);
```
would certainly work to signal errors via the return value and on success allow caller who care to distinguish 2 and 3 by returning NULL or an empty stack in crls. Those who don't care can just walk the stack as usual. If you're doing this right, callers can just do `sk_X509_CRL_pop_free(crls, X509_CRL_free);` on error or once they're done with `crls`. Similarly for certs and signers.

And yes, I agree there is room for improvement in the documentation. I even pointed it out.

**Comment by DDvO** [comment]
> I would also suggest reverting the change and developing a replacement API that has no backward compatibility issues. 

I support this, i.e., 
* reverting the changes regarding empty sets of crls/certs for backward compatibility, 
* fixing the documentation of `CMS_get0_signers()`, and
* deprecating those functions while adding new ones with an improved API.

**Comment by botovq** [comment]
Thank you.

**Comment by t8m** [comment]
**OTC: We will revert the behavior change of the CMS_get1_certs/crls() functions in master and 3.4 branches. We will add an internal call for replacement in 3.4 and a new public API call in 3.5.**

**Comment by DDvO** [comment]
Something like
> 
> ```c
> int CMS_get1_crls_ex(CMS_ContentInfo *cms, STACK_OF(X509_CRL) **crls);
> ```
> 
> would certainly work to signal errors

Just beware that such a more complicated API can be more awkward an error-prone than expected.
In particular, an output parameter like`crls` is tricky w.r.t. who is responsible to free the result.
In case of error, make sure that `*crls` does not contain a pointer to some leftover preliminary result,
to prevent mem leaks because callers would not assume to be responsible for freeing it on error.
Instead, on error it should be NULL, to prevent double-free by callers who wrongly assume to be responsible.

**Comment by DDvO** [comment]
@t8m I just noticed that #[fceeac4](https://github.com/t8m/openssl/commit/fceeac461aef41b40bc8aa417ec4adf8cd9e9527) already handles that problem correctly.

Yet there is an independent (already pre-existing) double-free case with `ossl_cms_get1_crls_ex()`.
