### ISSUE TITLE
OpenSSL accepts a certificate whose validity is not in the range of its CA certificate's without any warning

### ISSUE THREAD

**Issue by chenchuAtXidian** [openssl/openssl#2622]
Summary: As for a certificate, its validity should be in the range of its CA certificate's in logic. For example, if a CA certificate's validity is from Aug 15 10:28:44 2016 GMT to Aug 15 10:28:44 2017 GMT, the validity of a certificate which is issued by this CA should not be from Aug  1 12:12:12 2008 GMT to Nov  3 12:12:12 2018 GMT or from Sep  3 12:12:12 2016 GMT to Nov  3 12:12:12 2018 GMT. OpenSSL should reject such certificates or give warnings in logic, instead of depending on CRL or OCSP.
   
   Versions of OpenSSL: 1.0.1u, 1.0.2j, and 1.1.0b
   Operating System: [Ubuntu v1604-LTS x64]
   
   Steps to reproduce:  
							openssl verify -CAfile ca.pem 3.pem 
							openssl verify -CAfile ca.pem 4.pem 
   
   Actual results: 3.pem: OK, 4.pem: OK
   Expected results: OpenSSL should reject such certificates or give warnings.
   
   The attachement contains ca.pem and 3.pem and 4.pem.
   
   Please rename the file "test cases.txt" as "test cases.zip" and extract it.

	    ca.pem:
			Not Before: Aug 15 10:28:44 2016 GMT
                        Not After : Aug 15 10:28:44 2017 GMT
   
		3.pem:
			Not Before: Aug  1 12:12:12 2008 GMT
                        Not After : Nov  3 12:12:12 2018 GMT
						
		4.pem 
			Not Before: Sep  3 12:12:12 2016 GMT
                        Not After : Nov  3 12:12:12 2018 GMT

[test cases.txt](https://github.com/openssl/openssl/files/772973/test.cases.txt)

**Comment by dcooper16** [comment]
You seem to believe that there is a requirement for each certificate in a certification path to have a validity period that falls entirely within the validity period of the certificate that precedes it in the path. However, there is no such requirement, nor should there be, and so OpenSSL should neither reject nor issue a warning if it encounters such a situation.

Perhaps you think of all PKIs as being strictly hierarchical, so that the subject of a CA certificate is always "subordinate" to the issuer of the certificate, and you assume that CA certificates are never renewed (renewal is when a new certificate is issued with new validity dates, but with the same subject public key). However, not all PKIs are like that.

Consider the scenario below. Suppose that Organization 2 sets up a root CA and creates a self-signed certificate for that CA with validity dates from January 2010 to January 2030 and it then issues a certificate from that root to a subordinate CA with validity dates from February 2010 to February 2020.

Now suppose that sometime in 2017 Organization 1 wants its users to be able to accept certificates issued by Organization 2. So it issues a cross-certificate from its root to Organization 2's root, and it sets the validity period in this certificate to be February 2017 to August 2018.

Now, if OpenSSL were to validate the certification path from Organization 1's root CA to Organization 2's root CA to Organization 2's issuing CA to an end entity in organization 2, the second certificate in the certification path would be valid from February 2010 to February 2020 whereas its CA certificate would be valid from February 2017 to August 2018. According to you, OpenSSL should reject this certification path or at least give a warning, but the certification path is valid, and there is no  reason that OpenSSL should reject or flag it as being improper.
```
     +----------------------+              +----------------------+     
     |   Organization 1     |----------->  |   Organization 2     |
     |       Root CA        |              |       Root CA        |
     +----------------------+              +----------------------+
                                                       |
                                                       |
                                                      \ /
                                           +----------------------+     
                                           |   Organization 2     |
                                           |       Issuing CA     |
                                           +----------------------+
                                                       |
                                                       |
                                                      \ /
                                           +----------------------+     
                                           |      End-entity      |
                                           +----------------------+
```
