### ISSUE TITLE
Unable to compile Pure-FTPd with OpenSSL 1.0.2x

### ISSUE THREAD

**Issue by nik6018** [openssl/openssl#2646]
I am trying to compile Pure-FTPd with OpenSSL 1.0.2x.

Though the compiling finishes without any error, but it does not work. When I try to start or restart from the command line, I get the following error:
**Starting pure-ftpd: /usr/local/apps/pureftpd/sbin/pure-ftpd: symbol lookup error: /usr/local/apps/pureftpd/sbin/pure-ftpd: undefined symbol: DH_get_2048_256
[ OK ]**

I am unable to debug or make sense even after googling for hours.

In case if something is wrong with my configure command you can check it below :

```
LDFLAGS="-L$PPS_PATH/lib" CPPFLAGS="-I$PPS_PATH/include" LD_LIBRARY_PATH="$PPS_PATH/lib" ./configure 
--prefix=$PATH_PUREFTPD \
--with-puredb \
--with-ftpwho \
--with-quotas \
--with-altlog \
--with-tls && make && make install >> $LOG 2>&1
```

Also you can check my openssl configure command below :

```
LDFLAGS="-L$PPS_PATH/lib" CPPFLAGS="-I$PPS_PATH/include" ./config
--prefix=$PPS_PATH  \
--openssldir=$PPS_PATH/etc/openssl shared && make && make install >> $LOG 2>&1
```

**Comment by dot-asm** [comment]
It looks like compiled application doesn't find shared libraries it's linked with, i.e. it appears to be problem with *run-time* library path. This is not OpenSSL problem, because there are several ways to arrange it, and the choice is left to application developer. Because we are simply not in position to dictate one. This forum is hardly right place to discuss available methods and their pros and cons in specific situations. This is also very generic problem, so that I'm not sure if even openssl-users would be right forum... Anyway, closing.
