### ISSUE TITLE
curl: (60) SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by sjackman** [openssl/openssl#2833]
I'm able to reproduce this issue with openssl on Linux and Mac, but not with DarwinSSL on Mac.

### Steps to reproduce
with either Homebrew or Linuxbrew
```
❯❯❯ brew install curl --with-openssl
❯❯❯ /usr/local/opt/curl/bin/curl https://www.erlang.org/
curl: (60) SSL certificate problem: unable to get local issuer certificate
❯❯❯ /usr/bin/curl https://www.erlang.org/ | head -n1
<!DOCTYPE html>
```

### Versions
openssl 1.0.2k
curl 7.53.1
https://curl.haxx.se/ca/cacert-2017-01-18.pem

Originally reported at https://github.com/Linuxbrew/brew/issues/275

**Comment by richsalz** [comment]
Gogle the error message.  This is a local configuration issue, not having the server's CA certificate in the trust store.  You'll have to get the Darwin CA list, or similar, and install it in the openssl directory.

**Comment by sjackman** [comment]
I have Googled the error message. The accepted answer on Stack Overflow is to download `cacert.pem` from https://curl.haxx.se/ca/cacert.pem, which I've done (see above). Try for yourself:
```
❯❯❯ curl -O https://curl.haxx.se/ca/cacert-2017-01-18.pem
❯❯❯ curl --cacert cacert-2017-01-18.pem https://www.erlang.org/
curl: (60) SSL certificate problem: unable to get local issuer certificate
```

**Comment by levitte** [comment]
For these kinds of questions, openssl-users@openssl.org is the mailing list to go to. 
See https://www.openssl.org/community/mailing lists . html for links to the subscription pages.

**Comment by sjackman** [comment]
I'm not a fan of mailing lists. Having to subscribe to post a question, then unsubscribe once it's answered, is rather inconvenient. Perhaps a https://github.com/openssl/openssl-users/issues repository could be created for this purpose?

**Comment by richsalz** [comment]
And then everyone else has to follow and reply appropriately, putting the burden on the community.  There are places that gateway, including nabble.

**Comment by sjackman** [comment]
I suspect that `https://www.erlang.org/` is somehow misconfigured or that `https://curl.haxx.se/ca/cacert-2017-01-18.pem` doesn't include the CA that signed it, which to me seems odd, but I know relatively little about SSL. The signing authorities (from DarwinSSL) are
```
* Connected to www.erlang.org (31.172.186.60) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: www.erlang.org
* Server certificate: Symantec Class 3 Secure Server CA - G4
* Server certificate: VeriSign Class 3 Public Primary Certification Authority - G5
```

In any case, I've discovered that the secure URL https://www.erlang.org/download/otp_doc_man_19.2.tar.gz (the source of the original bug report https://github.com/Linuxbrew/brew/issues/275) redirects to the insecure URL http://erlang.org/download/otp_doc_man_19.2.tar.gz so I've modified Linuxbrew/core to use that insecure URL instead.

Resolved by https://github.com/Linuxbrew/homebrew-core/pull/1919

**Comment by levitte** [comment]
To cut this short, you have misunderstood what a CA cert is and does.  There is no way in the world that the CA cert from haxx.se would verify the server cert for www.erlang.org, that's not how this works.

However, a quick run of `openssl s_client -connect www.erlang.org:443` shows this line:

```
issuer=/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./OU=http://certs.godaddy.com/repository//CN=Go Daddy Secure Certificate Authority - G2
```

Have a look in http://certs.godaddy.com/repository/

**Comment by sjackman** [comment]
Is there a better source of CA certificates than https://curl.haxx.se ? Surely you don't have to download certificates for each individual hosting provider. Of the 4,047 formula in https://github.com/Linuxbrew/homebrew-core, this issue affects only, namely https://curl.haxx.se , which is why I suspect that it is somehow misconfigured.

**Comment by levitte** [comment]
Ok!  I didn't know haxx.se had a bundle of all sorts of CA certs.  My bad.

I just did this (`CAoath .` to avoid the central CA certs repository on my machine):

```
openssl s_client -connect www.erlang.org:443 -verify 255 -CApath .
```

And among everything else, it told me this:

```
    Verify return code: 19 (self signed certificate in certificate chain)
```

If I do this instead (cacert.pem is the same download you made):

```
: ; openssl s_client -connect www.erlang.org:443 -verify 255 -CAfile cacert.pem
```

which gave me this:

```
    Verify return code: 0 (ok)
```

Can you repeat that?  If you get the same results as I, the issue isn't with OpenSSL, and this is most probably a curl usage problem.  You should ask the curl folks (I suspect curl doesn't like self-signed certs in a cert chain received from the server.  It *is* kind of a no-no)

**Comment by sjackman** [comment]
```
❯❯❯ openssl s_client -connect www.erlang.org:443 -verify 255 -CAfile cacert-2017-01-18.pem </dev/null 2>&1 | tail -n3
    Verify return code: 0 (ok)
---
DONE
```

In your opinion is this `curl` bug or a bug with the configuration of `https://www.erlang.org/` ?

**Comment by adnanali011** [comment]
What we do with .pem file. I have download it and also make changes in php.ini.  Where i add this certificate??

**Comment by richsalz** [comment]
@adnanali011, please don't re-use issues for other topics.  This does not seem to be an openssl issue -- we don't have a php.ini, nor does curl.  I suggest you post on the appropriate forum.

**Comment by petrbela** [comment]
In my case, upgrading openssl (to 1.0.2n) solved the problem.

**Comment by DavidSantia** [comment]
I actually walked down the path of trying to update my curl curl-ca-bundle.crt to work with a GoDaddy cert on my sandbox server.  There were a few articles on the internet that explored the --cacert option to curl, but this turned out to be the wrong path for the actual issue.

It turns out my sandbox needed to also include the intermediate cert from GoDaddy along with the one for my domain.  This fix works without any mods to curl, etc:

See article here:
* https://www.godaddy.com/help/what-is-an-intermediate-certificate-868

Also explained here how to server the fullchain, not the cert by itself:
* https://www.npmjs.com/package/ssl-root-cas

What you do is add the intermediate cert to your test server.  Then curl works without any mods.

**Comment by DavidSantia** [comment]
I actually walked down the path of trying to update my curl curl-ca-bundle.crt to work with a GoDaddy cert on my sandbox server.  There were a few articles on the internet that explored the --cacert option to curl, but this turned out to be the wrong path for the actual issue.

It turns out my sandbox server needed to also include the intermediate cert from GoDaddy along with the one for my domain.  When you fix it on the server it, works without any mods to curl, etc:

See article here:
* https://www.godaddy.com/help/what-is-an-intermediate-certificate-868

Also explained here how to serve the fullchain, not the cert by itself:
* https://www.npmjs.com/package/ssl-root-cas

What you do is add the intermediate cert to your test server.  Then curl works without any mods.

The reason this may seem to be a curl related issue is that my browser (Chrome) did not detect any issues when my server was missing the intermediate cert.  It said the site was secure (apparently it can find the intermediate cert on its own).  But technically my server should have provided the full chain.

**Comment by kaduk** [comment]
Modern browsers super-aggressively cache intermediate certificates that they've seen, in order to provide a better user experience for users talking to misconfigured sites/servers.  That doesn't make those servers any less misconfigured; it just masks the issue for the people who complain the most loudly to the browser vendors.

**Comment by kroeckx** [comment]
In theory most of the cases can also be solved using AIA chasing.
Supporting that does not look like something OpenSSL should be
doing, but maybe curl could do it.

**Comment by xyanlucasx** [comment]
Registering here, maybe I can help someone. I had this same problem and this, besides disturbing my "curl", also broke a fultter application that consumed this site(nodejs over nginx server in VM).

In my case the problem was with my certificate, I wasn't using the fullchain, the godaddy certificate was missing. Initially I had a .pfx file (Azure). I performed the following steps to get my necessary files

```
openssl pkcs12 -in <filename.pfx> -nocerts -nodes | sed -ne '/-BEGIN PRIVATE KEY-/,/-END PRIVATE KEY-/p' > <clientcert.key>
openssl pkcs12 -in <filename.pfx> -clcerts -nokeys | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > <clientcert.cer>
openssl pkcs12 -in <filename.pfx> -cacerts -nokeys -chain | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > <cacerts.cer>
```

After that I put my clientcert.cer content right in front of the cacerts.cer content so it looks something like this >>

-----BEGIN CERTIFICATE-----
.......
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
............
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
..............
-----END CERTIFICATE-----

then just put it to my nginx server to read this cert file concatenated in ssl_certificate and the key file generated earlier being read in ssl_certificate_key
