### ISSUE TITLE
ElGamal cryptographic primitive

### ISSUE THREAD

**Issue by Lyla-Fischer** [openssl/openssl#2842]
I'm working with someone who is interested in using the ElGamal algorithm in a project to play around with what might be possible with homomorphic encryption (especially in a cloud computing environment, where storage providers might not be trusted), and there don't seem to be many supported, open-source libraries for it. I was wondering if there might be some interest from openSSL in adding that primitive to this library?

**Comment by richsalz** [comment]
It is highly doubtful that we would get around to doing this in the near future.  A pull request with implementation, docs, test is going to be the quickest way for this to happen.

**Comment by Lyla-Fischer** [comment]
In other open source projects that I have worked on, they appreciated getting a heads up for sizeable pull requests so that the need for review would not take them by surprise. Are there similar needs here?

**Comment by mattcaswell** [comment]
It is not necessary, but bear in mind that OpenSSL gets a lot of pull requests and you will compete for reviewer attention. To be accepted you must get two approvals from OpenSSL committers. For a large request it might be wise to create a "WIP" pull request to show what it's looking like and getting any initial feedback before investing too much time and effort in completing it. You should review the coding style document (https://www.openssl.org/policies/codingstyle.html) and read the CONTRIBUTING file (https://github.com/openssl/openssl/blob/master/CONTRIBUTING).

For a new licbrypto algorithm you will need to integrate it into the EVP API to be acceptable. As @richsalz already pointed out it will also require tests and full documentation. It should target the master branch (we do not backport features to stable branches).

**Comment by Lyla-Fischer** [comment]
I was just looking at this again, and spent some time poking around the codebase, and I was wondering if anybody might be willing to provide a short tour of the EVP API. I was having some trouble finding documentation and/or reconstructing it from the codebase proper.

**Comment by FdaSilvaYY** [comment]
Please take a look at the two last added algorithms : 
SM3: a0c3e4fa9089f571ff4b406cb914d0a504847b10
ARIA : d42d0a4dc7925e3ea398821028a254c94665d733

HTH, ;)

**Comment by mattcaswell** [comment]
ElGamal is a public key encryption algorithm. Therefore you're probably going to be mainly interested in the EVP_PKEY set of APIs, and in particular the encrypt/decrypt stuff, i.e.

https://www.openssl.org/docs/manmaster/man3/EVP_PKEY_encrypt.html
https://www.openssl.org/docs/manmaster/man3/EVP_PKEY_decrypt.html

The only other public key encryption algorithm that we have is RSA, so I suggest you look at how that is implemented from an EVP perspective. ElGamal should be simpler than RSA, because RSA also does sign/verify and has various padding variants. You will have to implement a new EVP_PKEY_METHOD structure and add it to the set of standard methods here:

https://github.com/openssl/openssl/blob/master/crypto/evp/pmeth_lib.c#L25

The RSA implementation of that structure is here:

https://github.com/openssl/openssl/blob/master/crypto/rsa/rsa_pmeth.c#L734

You will also have to implement an EVP_PKEY_ASN1_METHOD structure for the serialisation/deserialisation of public/private keys. For RSA's implementation of that, see here:

https://github.com/openssl/openssl/blob/master/crypto/rsa/rsa_ameth.c#L992

That structure needs to be added to the set of standard ASN.1 EVP_PKEY_ASN1_METHODs here:

https://github.com/openssl/openssl/blob/master/crypto/asn1/standard_methods.h#L15

Finally you will have to create a new EVP_PKEY_assign_ElGamal() macro. Here is the definition of EVP_PKEY_assign_RSA():

https://github.com/openssl/openssl/blob/master/include/openssl/evp.h#L401

**Comment by paulidale** [comment]
Also look at [how to integrate a symmetric cipher](https://wiki.openssl.org/index.php/How_to_Integrate_a_Symmetric_Cipher) on the wiki.  This is improved upon notes I wrote when I added ARIA.  Having something similar for a public key algorithm would be great.
