### ISSUE TITLE
Adding name constraint extension to cert using app fails

### ISSUE THREAD

**Issue by grooverdan** [openssl/openssl#2852]
<pre>
$ cat extension.conf
[ca_nameconstraint]
nameConstraints=critical,permitted;DNS:.ibm.com
nameConstraints=critical,permitted;email:.ibm.com
$ LD_LIBRARY_PATH=. ./apps/openssl x509  -extfile extension.conf  -extensions ca_nameconstraint  -in /tmp/IBMInternalRootCA.crt -out /tmp/IBMInternalRootCA_out.crt -addtrust serverAuth -addreject clientAuth           
$ LD_LIBRARY_PATH=. ./apps/openssl x509   -in  /tmp/IBMInternalRootCA_out.crt -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 0 (0x0)
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C = US, O = International Business Machines Corporation, CN = IBM Internal Root CA
        Validity
            Not Before: May 31 04:00:00 2011 GMT
            Not After : Jan  2 03:59:59 2035 GMT
        Subject: C = US, O = International Business Machines Corporation, CN = IBM Internal Root CA
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:d4:28:6b:a4:f5:39:ab:8b:8d:d1:dd:26:ae:4b:
                    b8:18:f6:b4:3d:0d:7b:d1:c2:49:67:6d:6f:b7:4e:
..
                    be:01:3b:c5:eb:75:d6:b6:55:0a:35:88:36:6c:f0:
                    0f:1b
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            Netscape Comment:
                .0Generated by the Security Server for z/OS (RACF)
            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Subject Key Identifier:
                F9:DE:18:E5:9E:30:13:69:51:A7:FD:79:85:48:8C:7C:0E:6F:D8:E3
    Signature Algorithm: sha1WithRSAEncryption
         85:7d:3c:a8:6f:cc:06:20:e1:a1:f7:2f:e0:68:87:f6:8b:21:
         d8:29:44:95:04:db:3b:f1:ff:fc:6b:50:50:1d:0e:13:24:10:
..
         15:2e:3c:3f:91:b4:ef:6c:f1:ac:84:c1:5a:a9:df:e1:d8:d0:
         50:6a:86:52
Trusted Uses:
  TLS Web Server Authentication
Rejected Uses:
  TLS Web Client Authentication
</pre>

**Comment by jon-oracle** [comment]
I can confirm that this is the current behaviour. It's a little confusing given that the usage _should_ allow for this to work. Currently the certificate is not re-encoded unless it is going to be signed or self-signed. This is understandable in a way because if the extensions change then the certificate signature is no longer valid.

There may be circumstances where this is still desirable, e.g. when creating a template certificate to be signed later, so I've made some changes on a branch to allow this:

https://github.com/jon-oracle/openssl/commit/9acd1df641b6e80482c980ddb0d270b37195629c

**Comment by levitte** [comment]
The template, that would be a csr, no?

**Comment by jon-oracle** [comment]
Yes a CSR would be a more standardised way to generate certs. I sometimes find when I'm generating test certs that getting the cert to 'look right' by adding/modifying fields and extensions then signing it after is quicker & easier.

**Comment by levitte** [comment]
Sorry, I had forgotten the "mini CA" capabilities.  What's lacking in @grooverdan's attempt is a key to sign the resulting certificate with.  Have a look at the option `-signkey` for this purpose.

Otherwise, "a template certificate to be signed later" *is-a* CSR.  There's no way around that (unless you roll your own software for it, of course)

**Comment by grooverdan** [comment]
i'm happy to accept i'm using it wrong, especially if the workaround is hard.

**Comment by levitte** [comment]
Well, unless I'm entirely off base, the workaround is `-signkey` (i.e. you must sign the resulting new certificate), and should therefore be quite easy (provided you have a key to sign with, of course).

A side note: as you must have noticed, the trust settings got added successfully.  The reason is that they are attached to the certificate file, but not part of the certificate *itself*.  Extensions, on the other hand, must be part of the certificate itself, which is the reason you must also sign the new certificate.

**Comment by levitte** [comment]
I think this ticket is ready for a close.  If you find new issues with what you're trying to do, please feel free to file a new issue...

**Comment by grooverdan** [comment]
thank you @jon-oracle @levitte
