### ISSUE TITLE
errors when I run nmake test

### ISSUE THREAD

**Issue by HmidiSlim** [openssl/openssl#2874]
I'm using windows 10 professional and I'm trying to download Openssl.
I downloaded perl from [www.activestate.com](activeState) and I downloaded visualStudio buildtool 2015.
I run VS2015 x64 Native Tools Command Prompt and I followed the instructions on the INSTALL.
When I run nmake test I got many errors:
[logfile](http://pastebin.com/5BbitQNJ).
Can anyone help me to fix it?

**Comment by levitte** [comment]
It especially worries me that `test_sanity` failed.  Could you answer me this?

1.  What was your exact configuration command?
2.  What is the output when you do `nmake test TESTS=test_sanity V=1`

**Comment by dot-asm** [comment]
It looks like reporter would fail to execute *any* compiled program, and in such case it's not OpenSSL problem, but environment-specific. Possible reason for failure is that one needs to install even corresponding Microsoft C++ 2015 Redistributable...

Since there was no response for over 2 weeks, I'm closing this.
