### ISSUE TITLE
SSL_get_version will return a version before handshake.

### ISSUE THREAD

**Issue by Lukasa** [openssl/openssl#2893]
Spotted originally when working with Python, as [Python issue 29781](https://bugs.python.org/issue29781).

`SSL_get_version` is documented as follows: 

```
NAME
       SSL_get_version - get the protocol version of a connection.

SYNOPSIS
        #include <openssl/ssl.h>

        const char *SSL_get_version(const SSL *ssl);

DESCRIPTION
       SSL_get_version() returns the name of the protocol used for the
       connection ssl.

RETURN VALUES
       The following strings can be returned:

       SSLv2
           The connection uses the SSLv2 protocol.

       SSLv3
           The connection uses the SSLv3 protocol.

       TLSv1
           The connection uses the TLSv1.0 protocol.

       TLSv1.1
           The connection uses the TLSv1.1 protocol.

       TLSv1.2
           The connection uses the TLSv1.2 protocol.

       unknown
           This indicates that no version has been set (no connection
           established).
```

Note that the man page says that "unknown" will be returned when no connection is established. However, this is not the actual behaviour. For example, consider the following test code:

```c
#include <stdio.h>
#include <openssl/bio.h>
#include <openssl/ssl.h>

void init_openssl(void) { 
    SSL_library_init();
    SSL_load_error_strings();
    ERR_load_BIO_strings();
    OpenSSL_add_all_algorithms();
}

SSL_CTX *create_context() {
    const SSL_METHOD *method;
    SSL_CTX *ctx;

    method = SSLv23_server_method();

    ctx = SSL_CTX_new(method);
    if (!ctx) {
	printf("Unable to create context!\n");
	exit(1);
    }

    return ctx;
}

int main(int argc, char **argv) {
    SSL_CTX *ctx;
    SSL *ssl;
    BIO *in_bio;
    BIO *out_bio;
    const char *version;

    init_openssl();
    ctx = create_context();
    ssl = SSL_new(ctx);
    in_bio = BIO_new(BIO_s_mem());
    out_bio = BIO_new(BIO_s_mem());

    if ((in_bio == NULL) || (out_bio == NULL)) {
        printf("Unable to allocate BIOs\n");
        exit(2);
    }

    SSL_set_bio(ssl, in_bio, out_bio);
    SSL_set_connect_state(ssl);

    version = SSL_get_version(ssl);
    printf("Version: %s\n", version);

    SSL_free(ssl);
    SSL_CTX_free(ctx);
    return 0;
}
```

This test code prints `Version: TLSv1.2`. This is despite the fact that no connection is established, and that as a result there is no TLS version in use right now.

I've reproduced this bug against OpenSSL 1.0.2, but I have no reason to believe it was not present in earlier versions, or in later ones.

**Comment by NicsTr** [comment]
I tried to find out what's going on. I don't know if that helps but here is what I found : 

The SSL_CTX structure (ctx) holds (among other things) :
1. the function `int ssl3_new(SSL *s);` in the field `ctx->method->ssl_new` ;
2. the function `void tls1_clear(SSL *s);` in the field `ctx->method->ssl_clear` ;
3. a constant `TLS_ANY_VERSION (65536)` in the field `ctx->method->version`.


When you initialize the SSL structure with `ssl = SSL_new(ctx);` in your main program the function (1.) is called.

Then at the end of this function (1.) the function (2.) is called.

This function (2.) is responsible for setting the SSL structure field `ssl->version`  with the constant `TLS_MAX_VERSION` when the field (3.) is `TLS_ANY_VERSION`. In your case it sets the version to `TLS1_2_VERSION`.

 
I don't know if it's truly a bug or if it's done this way on purpose, because the function `tls1_clear` does nothing else more than calling `ssl3_clear` (which sets the version field to `SSL3_VERSION`) and changing the value of the version.

**Comment by Lukasa** [comment]
@NicsTr Good investigation.

For my part, either there is a bug or a documentation issue. The documentation says that when no connection is established the return value should be `"unknown"`. That does not match the actual behaviour. I'm fine if the OpenSSL team want to say that the documentation is in error, I have no particular horse in this race (it's really simple for me to work around this in my own code by just keeping a boolean that tracks connection state). But one way or another either the docs or the code should change.
