### ISSUE TITLE
FIPS iOS library invalid architecture

### ISSUE THREAD

**Issue by jostster** [openssl/openssl#2927]
I have updated my iOS scripts to build for all archs now using the latest fips-2.0.14 and openssl-1.1.0e.

Before I was using 1.0.2h I believe and fips-2.0.12 and didn't have armv7s support added (https://gist.github.com/jostster/ebbc6925c668b632d8b185293080256c/5418296d9bfba9b0c8b0b4acc5b83477e4e72a06).
 I needed to add it so I upgrade and adjusted my script accordingly https://gist.github.com/jostster/ebbc6925c668b632d8b185293080256c

This works great, however I now get an error when building my application in xcode.
```
Undefined symbols for architecture armv7:

  "_FIPS_text_start", referenced from:

      _FINGERPRINT_premain in fips_premain.o

  "_FIPS_signature", referenced from:

      _FINGERPRINT_premain in fips_premain.o

      +[VTFipsInfo getEmbeddedFingerprint] in VTFipsInfo.o

  "_FIPS_incore_fingerprint", referenced from:

      _FINGERPRINT_premain in fips_premain.o

      +[VTFipsInfo getExpectedFingerprint] in VTFipsInfo.o

ld: symbol(s) not found for architecture armv7
```
VTFipsInfo.o is my objective-c files that get if FIPS is enabled and gets the hashes to display to the end user. If I try this on our buildkite server it replaces armv7 with x86_64. However running lipo -info on my libssl and libcrypt.a returns

```
Architectures in the fat file: libssl.a are: armv7 i386 armv7s x86_64 arm64 
Architectures in the fat file: libcrypto.a are: armv7 i386 armv7s x86_64 arm64 
```
My valid architectures in xcode are armv7, armv7s and armv64. Before I upgraded my openssl and added armv7s support, this wasn't an issue.

I have also moved the fips-ecp back down to 2.0.12 but get the same results. Moving openssl to anything below 1.1.0 prevents armv7s from compiling as it throws a random make error.

*Test Case*
Using the script above to compile the libcrypto.a and libssl.a you can then use the fips-pi.tar.gz sample application located at http://openssl.com/fips/2.0/platforms/ios/ to test. This encounters the same error.

**Comment by jostster** [comment]
I see FIPS is taken out on master, is this temporary? What is the latest stable version that supports FIPS?

**Comment by richsalz** [comment]
FIPS support was removed in 1.1.0; 1.0.2 is the latest (and only supported) version. We will be working on FIPS, but it will be a future release.

**Comment by jostster** [comment]
@richsalz thanks for the follow up. What is the latest version of 1.0.2 that supports armv7, armv7s, arm64? I tried 1.0.2k and was getting random make errors on armv7s. If I can get this working I would love to clean up that script and make it public with a readme to help anyone else needing FIPS for iOS for all ARMs

**Comment by richsalz** [comment]
So is this all that's needed to close the issue, and answer to your question?  Have you looked at the 1.0.2 log?

**Comment by jostster** [comment]
@richsalz I looked at the 1.0.2 latest and it doesn't have support for armv7s. So it seems at this time our app will not have FIPS support.

Is there an ETA on when FIPS support will be added back?

**Comment by richsalz** [comment]
No ETA.  The team is focused on TLS 1.3 right now.

**Comment by dot-asm** [comment]
> I tried 1.0.2k and was getting random make errors on armv7s.

Really? I.e. every time you try it would fail at *different* places producing seemingly "unprovoked" error messages? This doesn't sound like something a working computer would do... :-) :-) :-)

But on serious note. As for armv7s. In normal case, a.k.a. Linux, it wouldn't be a problem to link together FIPS module targeting armvN with application targeting armvN+1. But Apple of course has to be special and it's indeed appears to be impossible to link module targeting armv7 with armv7s application. There is nothing we can do about without somebody stepping up and sponsoring additional validation specifically for armv7s. Otherwise you're stuck with armv7. But question is if your application actually does have to be armv7s? As far as I recall armv7s simply adds couple of floating-point instructions, and if your application doesn't benefit from them, it can as well target armv7. Just in case, OpenSSL does not benefit from them, i.e. there is no performance benefit in compiling OpenSSL specifically for armv7s.

As for arm64. FIPS module does have support for it, there is ios64-cross target. No, 1.0.2 itself doesn't have corresponding line, but it ought to be trivial and surely doable. At the very least the party who sponsored ios64-cross validation surely does it...

**Comment by jostster** [comment]
@dot-asm sorry, it seemed random as i was building using the -j flag. When running a single threaded build it was erroring on invalid CPU type.

I previously built for armv7, arm64 and i386, however on armv7s devices, it would crash when using the openssl library on `EVP_EncryptUpdate` & `EVP_DecryptUpdate`.

**Comment by dot-asm** [comment]
> on armv7s devices, it would crash when using the openssl library on EVP_EncryptUpdate & EVP_DecryptUpdate.

Present evidence, such as stack back-traces.... And once again, why isn't armv7 is option?

**Comment by dot-asm** [comment]
I'm inclined to close this, because original question is kind of answered. Namely that there is nothing we can do *here* about armv7s support in *FIPS* context. Other issues can be handled separately.

**Comment by jostster** [comment]
Thats fine. I will create another issue when I have some time to provide the stack traces for the armv7

**Comment by jostster** [comment]
@dot-asm I see there have been some fips updates. Does that mean that fips is now back in and working?

**Comment by richsalz** [comment]
I am not sure what "fips updates" you mean.  FIPS is not possible in anything other than 1.0.2, and there have been no changes to that.
