### ISSUE TITLE
ARMV7 alignment crash in 1.1.0e

### ISSUE THREAD

**Issue by zTristan** [openssl/openssl#3031]
Getting this crash on older iOS devices that run ARMv7 and ARMv7s.

```
(lldb) bt
warning: could not load any Objective-C class information. This will significantly reduce the quality of type information available.
* thread #34: tid = 0x65c00, 0x01bc059c Chef Showdown Debug`bsaes_cbc_encrypt + 732, stop reason = EXC_BAD_ACCESS (code=EXC_ARM_DA_ALIGN, address=0x1f31c574)
    frame #0: 0x01bc059c Chef Showdown Debug`bsaes_cbc_encrypt + 732
    frame #1: 0x01c98ac6 Chef Showdown Debug`tls1_enc + 1130
    frame #2: 0x01c97e56 Chef Showdown Debug`ssl3_get_record + 732
    frame #3: 0x01c9701e Chef Showdown Debug`ssl3_read_bytes + 342
    frame #4: 0x01c9c07a Chef Showdown Debug`ssl3_read_internal + 124
    frame #5: 0x0101a4ea Chef Showdown Debug`lws_ssl_capable_read + 32
    frame #6: 0x01014d9c Chef Showdown Debug`lws_service_fd_tsi + 1012
    frame #7: 0x0101b7f8 Chef Showdown Debug`lws_plat_service_tsi + 318
  * frame #8: 0x0100723c Chef Showdown Debug`cocos2d::network::WsThreadHelper::onSubThreadLoop(this=0x1bbb53a0) + 638 at WebSocket.cpp:412
    frame #9: 0x01006f6e Chef Showdown Debug`cocos2d::network::WsThreadHelper::wsThreadEntryFunc(this=0x1bbb53a0) + 62 at WebSocket.cpp:448
    frame #10: 0x0100e3c6 Chef Showdown Debug`void* std::__1::__thread_proxy<std::__1::tuple<void (cocos2d::network::WsThreadHelper::*)(), cocos2d::network::WsThreadHelper*> >(void*) [inlined] decltype(__f=0x1bbb53e0, __a0=0x1bbb53e8)).*fp(std::__1::forward<>(fp1))) std::__1::__invoke<void (cocos2d::network::WsThreadHelper::*)(), cocos2d::network::WsThreadHelper*, void>(void (cocos2d::network::WsThreadHelper::*&&)(), cocos2d::network::WsThreadHelper*&&) + 74 at __functional_base:383
    frame #11: 0x0100e37c Chef Showdown Debug`void* std::__1::__thread_proxy<std::__1::tuple<void (cocos2d::network::WsThreadHelper::*)(), cocos2d::network::WsThreadHelper*> >(void*) [inlined] void std::__1::__thread_execute<void (cocos2d::network::WsThreadHelper::*)(), cocos2d::network::WsThreadHelper*, 1ul>(__t=0x1bbb53e0)(), cocos2d::network::WsThreadHelper*>&, std::__1::__tuple_indices<1ul>) + 20 at thread:347
    frame #12: 0x0100e368 Chef Showdown Debug`void* std::__1::__thread_proxy<std::__1::tuple<void (cocos2d::network::WsThreadHelper::*)(), cocos2d::network::WsThreadHelper*> >(__vp=0x1bbb53e0) + 228 at thread:357
    frame #13: 0x2423f85a libsystem_pthread.dylib`_pthread_body + 138
    frame #14: 0x2423f7ce libsystem_pthread.dylib`_pthread_start + 110
    frame #15: 0x2423d724 libsystem_pthread.dylib`thread_start + 8
(lldb) 
```

OpenSSL 1.1.0e library was built with https://github.com/x2on/OpenSSL-for-iPhone using default settings.

I was told to look for a way to force `STRICT_ALIGNMENT` but that didn't seem to help.

Has anyone encountered this before?

**Comment by dot-asm** [comment]
Well, bsaes_cbc_ecnrypt is assembly subroutine, and it's not affected by `STRICT_ALIGNMENT` macro. Instruction at offset 732 from beginning of bsaes_cbc_ecncrypt refers to stack. The subroutine in question is written under assumption that upon entry to a subroutine stack pointer is aligned at 64 bits. This is common ABI requirement, which makes it simpler to handle floating-point local variables and arguments. Customarily maintaining stack alignment is so to say cooperative exercise when each subroutine assumes that stack is aligned upon entry and maintains it at same alignment when it calls next subroutine. So that crash means either of three things: a) compiler is buggy and fails to maintain alignment in some subroutine in back-trace; b) stack was incorrectly seeded by kernel or at entry point to the binary; c) Apple adheres to modified ABI with relaxed stack alignment requirement. In either case, it's trivial to test work-around. Open crypto/aes/asm/bsaes-armv7.pl in text editor, search for `,:64` and remove it. There is only *one* occurrence...

**Comment by zTristan** [comment]
Hey that worked perfectly. thanks @dot-asm.

I have another fix of adding `no-asm` to remove the assembly all together in the armv7 architecture. I was worried about possible performance and security issues that might cause.

I'll use your solution.

**Comment by dot-asm** [comment]
#3032 merged, this case is closed.
