### ISSUE TITLE
clean up BIO_printf formatting strings.

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#3060]
See the comments in #3044  We should get rid of OSSLzu, etc., and just use our own platform-neutral formatting.

**Comment by dot-asm** [comment]
> See the comments in #3044 We should get rid of OSSLzu

??? Where does it say that? It says that we should implement 'z' in BIO_printf (so that BIO_printf calls can be used without OSSLzu), and that we should be able to omit PRIu64 (because it's used only with BIO_printf). It also says that OSSLzu is effectively mis-defined in some cases, but it doesn't actually spell that we can get rid of OSSLzu. Well, one can say that it's *implied*... But if we aim for that, we also have to recognize that in such case we would have to convert all [f]printf calls with OSSLzu to BIO_printf calls...

**Comment by bernd-edlinger** [comment]
Hmm, PRIu64 is used as argument in BIO_printf calls, but BIO_printf implements
simply l=long ll=LLONG, you should simply use %llu if it is a LLONG
which is not necessarily int64_t ?

**Comment by dot-asm** [comment]
> Hmm, PRIu64 is used as argument in BIO_printf calls

Exactly. See #3083.

**Comment by dot-asm** [comment]
And after #3094 this can be closed...
