### ISSUE TITLE
SSL_do_handshake does not flush the write bio

### ISSUE THREAD

**Issue by daurnimator** [openssl/openssl#322]
At no point does `SSL_do_handshake` call `BIO_flush`.

This means that you can't have a bio that buffers up data until a flush is received.
Likewise, if the BIO delays writes (e.g. due to [Nagle's algorithm](https://en.wikipedia.org/wiki/Nagle%27s_algorithm)) in the hope that more data could be sent in the same packet, it will always timeout. This makes `BIO_flush` practically useless during a handshake.

(originally found while researching https://github.com/wahern/cqueues/issues/79#issuecomment-118752195)

**Comment by daurnimator** [comment]
Note that in this example program, `"FLUSH"` is never printed:

```c
#include <openssl/ssl.h>
#include <openssl/err.h>
#include <openssl/bio.h>

static int bio_create(BIO *bio) {
	printf("BIO CREATE\n");
	bio->init = 1;
	bio->shutdown = 0;
	bio->num = 0;
	bio->ptr = NULL;
	return 1;
}

static int bio_write(BIO *bio, const char *src, int len) {
	BIO_clear_retry_flags(bio);
	printf("WRITING %ld\n", len);
	return len;
}

static long bio_ctrl(BIO *bio, int cmd, long udata_i, void *udata_p) {
	switch (cmd) {
	case BIO_CTRL_FLUSH:
		printf("FLUSH\n");
	default:
		printf("CTRL cmd=%d\n", cmd);
	}
	return 0;
}

static BIO_METHOD bio_methods = {
	BIO_TYPE_SOURCE_SINK,
	"testing",
	bio_write,
	NULL,
	NULL,
	NULL,
	bio_ctrl,
	bio_create,
	NULL,
	NULL,
};

int main() {
	SSL_CTX *ssl_ctx;
	SSL *ssl;
	BIO *bio;

	SSL_load_error_strings();
	SSL_library_init();


	if (!(ssl_ctx = SSL_CTX_new((SSL_METHOD *)SSLv23_method()))) return 1;
	if (!(ssl = SSL_new(ssl_ctx))) return 1;
	SSL_CTX_free(ssl_ctx);
	if (!(bio = BIO_new(&bio_methods))) return 1;
	SSL_set_bio(ssl, bio, bio);
	SSL_set_connect_state(ssl);
	int rval = SSL_do_handshake(ssl);
	if (rval <= 0) {
		puts(ERR_error_string(ERR_peek_last_error(), NULL));
		return 1;
	}
	return 0;
}
```
```
$ gcc issue#322.c -l ssl -l crypto && ./a.out 
BIO CREATE
WRITING 318
error:2006F079:BIO routines:BIO_read:unsupported method
```

**Comment by daurnimator** [comment]
bump?

**Comment by mattcaswell** [comment]
It isn't entirely true to say that flush is never called during SSL_do_handshake(). Actually what happens is writes are buffered internally until we're at a point in the handshake where we can't write any more without input from the peer. At that point everything we have written to the buffer so far is written to the BIO in one go, and then a flush is issued immediately afterwards. The only place in the handshake where this is not the case is the initial ClientHello message written by the client. As this is just a single message we haven't put in place the buffering yet, and we just do this as a simple write, and no flush is performed. This is why your test code above does not see a flush: because it is only looking at the initial message in the handshake and does not do a full handshake.

There really aren't going to be any benefits to you of adding your own buffering at the BIO layer during the handshake because, as I said above, we already do that buffering for you. When we do a write, we really mean you need to do a write because we can't make any further progress until we have heard back from the peer.

Furthermore, adding a flush after the initial ClientHello is a non-trivial change (at least in the stable branches) because we have to cope with the instance where we are performing non-blocking IO. The flush call could potentially come back with a retry response and therefore we need to be able to restart the IO from that point at some later time. That is doable, but would require some changes to the OpenSSL state machine. The change is simpler in the forthcoming 1.1.0 due to the fact we have rewritten the state machine code - but as I said above I am dubious of the benefits.

**Comment by daurnimator** [comment]
> what happens is writes are buffered internally until we're at a point in the handshake where we can't write any more without input from the peer. At that point everything we have written to the buffer so far is written to the BIO in one go, and then a flush is issued immediately afterwards.

I didn't see that in my testing. => the whole thing just called write() and waited.

**Comment by mattcaswell** [comment]
How did you test? I just tested the same thing and did see the flushes (with the exception of the inital client write as noted above).

**Comment by daurnimator** [comment]
> How did you test? 

Originally, inside of a larger application. 
But now working from the example above. See https://gist.github.com/daurnimator/1f5eb0268aaeac2aacbc171415f19ed4 for current results.
Note that `flush` is never called; and `do_handshake` is already saying for the application to wait for data to arrive on the socket.

**Comment by mattcaswell** [comment]
But your test does NOT test a full handshake! You are ONLY doing the client side and there is no server. The client issues its initial ClientHello and (you're right) it does not flush for that one message as I said above. It then sits there awaiting a response from the server which it's never going to get because you don't have a server.

**Comment by daurnimator** [comment]
> But your test does NOT test a full handshake! You are ONLY doing the client side and there is no server. The client issues its initial ClientHello and (you're right) it does not flush for that one message as I said above. It then sits there awaiting a response from the server which it's never going to get because you don't have a server.

The server side is unnecessary => I was going to have a bio that buffered things in `bio_write` and only actually `write()` to the system socket on `flush`. But `flush` is never called.

**Comment by mattcaswell** [comment]
As I said above the benefits of doing so during the handshake are zero. We already do the buffering for you. We only issue a write when you really need to write because we can't make any further progress without input from the peer.

**Comment by daurnimator** [comment]
> As I said above the benefits of doing so during the handshake are zero. We already do the buffering for you. We only issue a write when you really need to write because we can't make any further progress without input from the peer.

In my case I can either do it for the whole life of the connection... or not at all.
To do otherwise would involve making the underlying bio know about the state of the SSL object that is using it.

**Comment by mattcaswell** [comment]
Ok. I'll give that some thought.

**Comment by mattcaswell** [comment]
Commit 464175692 in master addresses this issue. This will appear in OpenSSL 1.1.0. It is my opinion that the changes required to 1.0.2 to enable this are too significant (because it would mean changing the state machine). Therefore this will not be addressed in that branch. Closing this ticket.

**Comment by daurnimator** [comment]
Great, thanks :)
