### ISSUE TITLE
Test infrastructure items

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#3341]
This is intended to be a place to keep the current items needing review/improvement in the test infrastructure.  The wiki might be a better place.

~Reformat the failure messages.  This is highlighted in #3155 and consists of several items.~
* ~The messages are very short and fairly cryptic.  A new more readable style/layout should be adopted.  Failure messages are not expected, so making them verbose doesn't hurt.~
* ~The messages output the comparison that failed `3 < 2` rather than the condition that holds `3 >= 2`  This warrants further consideration.~
* ~The hex and string outputs don't line up and are difficult to determine where the difference is.  They should line up (probably on alternating lines if they are too long) and there should be an indication as to where the first difference is (all differences).~

* ~Clean up the hex and string outputs as in the side note in #3465~

~Add support for bignum comparisons.~
* ~TEST_BN_eq, TEST_BN_ne to compare bignums directly.~
* ~TEST_BN_eq_int, TEST_BN_ne_int to compare bignums to small integers directly.~
* ~Should this include API support for BNs in BIO_printf as well?~

~Execute tests in random order to prevent dependencies between tests and to stress the library differently.~

~Remove all traces of the TEST_check macro.~

~Remove prints from the tests and use test infrastructure instead.~  ~We'll want a new call that is like TEST_info but without the file and line information.~

~Unify memory, bignum and string outputs (i.e. like the TEST_xxx outputs but for single values).~

I'm sure there are plenty of other items.

**Comment by pauli-oracle** [comment]
BN support in BIO_printf isn't desirable -- we'd lose the attribute(printf, ...) tag that checks arguments.

**Comment by pauli-oracle** [comment]
An initial attempt at test output reformatting is in #3357.

**Comment by pauli-oracle** [comment]
Test order randomisation is in #3393.

**Comment by dot-asm** [comment]
Let's consider output with corrupt bntests.txt:
```
# ERROR: 
# unexpected value

# ERROR: (BIGNUM) expected == actual @ ../openssl/test/bntest.c:149
#    0:  '0AE2CA2CE7ADDAEE2E2B7752E286B2BB6A58B51CFBED5C924F00398E59EC36FE'
#   64:  '6341CD83DA43A33A12410F45F6228079C4AEB3912BE87E2E81FA1799151BFA0F'
#  128:  'EA29873097475B2C3EFA312145D0BF7E51B2A7C9BC961A4F4DCF0C883FF90B91'
#  192:- '9B87C21099FBA40257645BE31F95A3A278'
#  192:+ '9B87C21099FBA40257645BE31F95A3A277'
#                                          ^

# INFO: 
# Failed ModMul test at 7728
```
Once again, `ERROR: expected == actual` can't be interpreted in any other way than "observed equality is the reason for the error". It's easy to "fix" by adding one word, "failed". I suppose it would be appropriate to add quotes around condition. Secondly, without looking at bntests.txt can you tell which value is expected? Now go and look. [On side note (because it's not directly related and should be addressed elsewhere) take a note on what's on line number 7728.]

Looking at test_test output:
```
# ERROR: (BIGNUM) b < c @ ../openssl/test/test_test.c:339
#    0:- '01'
#    0:+ '-13F3B7EF'
#         ^ ^^^^^^^
```
Space in line of carets is inappropriate. I mean the fact that 1 is observed in same position in string representation is not exactly relevant information in the context. Ideally, just like with ectest, it would be more appropriate to "favour" least significant part. For example given FFFF and FFFFFFFF it should emphasize left-most FFFF.

**Comment by dot-asm** [comment]
As pointed out elsewhere, I fail to see why does it have to be self-purpose. Consider again ModMul failure report mentioned above. In case of failure you'd be more interested to see numerical difference between expected and observed values. [Because it might be small, or might have specific bit pattern.] For example, originally it was done by emitting expression itself minus observed result in format suitable for copy-n-pasting to bc, so that you could examine difference if deemed interesting. Now, I'm not suggesting to put it back, but this underpins following argument. It should not be inappropriate for test program to generate custom error output that would emphasize details specific to underlying functionality. Generic framework can't cover all the nuances. Test program should be valued by its ability to efficiently orient and locate the root of the problem, not its usage of framework.

**Comment by levitte** [comment]
Re explicit "failed", see #3423

**Comment by levitte** [comment]
> Looking at test_test output:
> ```
> # ERROR: (BIGNUM) b < c @ ../openssl/test/test_test.c:339
> #    0:- '01'
> #    0:+ '-13F3B7EF'
> #         ^ ^^^^^^^
> ```
> Space in line of carets is inappropriate. I mean the fact that 1 is observed in same position in string representation is not exactly relevant information in the context. Ideally, just like with ectest, it would be more appropriate to "favour" least significant part. For example given FFFF and FFFFFFFF it should emphasize left-most FFFF.

I agree here.  The comparison should show the number like this:

```
       01
-13F3B7EF
```

However, I see a problem when comparing a small number to a huge number, for example `01` against `0AE2CA2CE7ADDAEE2E2B7752E286B2BB6A58B51CFBED5C924F00398E59EC36FE6341CD83DA43A33A12410F45F6228079C4AEB3912BE87E2E81FA1799151BFA0FEA29873097475B2C3EFA312145D0BF7E51B2A7C9BC961A4F4DCF0C883FF90B919B87C21099FBA40257645BE31F95A3A277`.  How would you display that?

**Comment by levitte** [comment]
> Let's consider output with corrupt bntests.txt:
> ```
> # ERROR: 
> # unexpected value
> 
> # ERROR: (BIGNUM) expected == actual @ ../openssl/test/bntest.c:149
> #    0:  '0AE2CA2CE7ADDAEE2E2B7752E286B2BB6A58B51CFBED5C924F00398E59EC36FE'
> #   64:  '6341CD83DA43A33A12410F45F6228079C4AEB3912BE87E2E81FA1799151BFA0F'
> #  128:  'EA29873097475B2C3EFA312145D0BF7E51B2A7C9BC961A4F4DCF0C883FF90B91'
> #  192:- '9B87C21099FBA40257645BE31F95A3A278'
> #  192:+ '9B87C21099FBA40257645BE31F95A3A277'
> #                                          ^
> 
> # INFO: 
> # Failed ModMul test at 7728
> ```
> [...] Secondly, without looking at bntests.txt can you tell which value is expected? Now go and look. [On side note (because it's not directly related and should be addressed elsewhere) take a note on what's on line number 7728.]

You're misrepresenting the output, here's the *actual* output (freshly updated master):

```
    # ERROR:  @ ../master/test/bntest.c:148
    # unexpected A * B (mod M) value

    # ERROR: (BIGNUM) expected == actual @ ../master/test/bntest.c:149
    #    0:  '0AE2CA2CE7ADDAEE2E2B7752E286B2BB6A58B51CFBED5C924F00398E59EC36FE'
    #   64:  '6341CD83DA43A33A12410F45F6228079C4AEB3912BE87E2E81FA1799151BFA0F'
    #  128:  'EA29873097475B2C3EFA312145D0BF7E51B2A7C9BC961A4F4DCF0C883FF90B91'
    #  192:- '9B87C21099FBA40257645BE31F95A3A278'
    #  192:+ '9B87C21099FBA40257645BE31F95A3A277'
    #                                          ^
```

"unexpected A * B (mod M) value" tells me quite clearly what's unexpected.
It's possible, though, that the `TEST_error` call should be made after the `TEST_bn_eq` call...

**Comment by levitte** [comment]
(previous comment updated, I was assuming the @dot-asm was from an absolutely current master)

**Comment by dot-asm** [comment]
??? All this was for absolutely current master, 03d8e9cb43da5c524e5890a5a51e2c77f1fbd789 to be specific. I don't see no "unexpected A * B (mod M) value" and you didn't answer the question. Which one you *would* think is expected? One with 7 at the end or 8? +- notation kind of implies kind of original value denoted with -, and kind of new one with +. Would you consider expected to be kind of new or original? It's also about left- vs. right-hand sides of presented expression. In other cases (those I looked at) left-hand goes as -...

**Comment by levitte** [comment]
Err, I frankly don't understand. If you get an error line saying `A == B` with similar dump, is it the same mystery? 
Should we add a couple of diff-like lines saying what's what? You know:

```
# --- expected
# +++ value
```

**Comment by dot-asm** [comment]
> I frankly don't understand.

My bad, I confused myself. I apologize for the noise about this particular thing. Sorry.

**Comment by levitte** [comment]
Okie, good, one less thing to worry about.

**Comment by pauli-oracle** [comment]
Right justifying bignum output seems like a good idea to me, I'd already been thinking about how to do it.  I was trying to avoid using internal APIs, hence the string output.  Improved formatting will need to work with the raw words `bn_get_words` and `bn_get_top` should be enough.

Anyway, some questions about the output format:

Where should the sign go?

```
sign inline     sign left       inline & +      left & +
     -01        -      01             -01        -      01
13F3B7EF         13F3B7EF       +13F3B7EF        +13F3B7EF
```

I'm leaning towards left justifying the sign and including the `+` but this gets awkward if one number is very long (multi-line) and the other is short.


Should left side spaces be zero filled? (I suspect not).  What about high zeros in the top word? (I think yes).

**Comment by pauli-oracle** [comment]
> Should we add a couple of diff-like lines saying what's what? You know:
> ```
> # --- expected
> # +++ value
> ```
> 

I toyed with this idea but I put both on one line which looked confused.  Using two lines as above seems like a good suggestion.

**Comment by dot-asm** [comment]
> I was trying to avoid using internal APIs, hence the string output. Improved formatting will need to work with the raw words bn_get_words and bn_get_top should be enough.

BN_bn2bin and BN_num_bytes (or BN_num_bits if you want to get rid of rightmost 0).

> I'm leaning towards left justifying the sign

I'd prefer first suggestion, because left-justified sign runs risk of being mixed up with +- denoting differences. But this is not strong opinion, since we're more likely to observe unsigned values. I'd probably feel stronger about explicitly denoting positive values with +. I mean I wouldn't be in favour.

> Should left side spaces be zero filled? (I suspect not).

I'd say not as well.

> What about high zeros in the top word? (I think yes).

I don't follow. What word? We can't make assumptions about word size. But just like with ectest, it would be meaningful to do something like this:
```
                                                               123
- 6341CD83DA43A33A12410F45F6228079C4AEB3912BE87E2E81FA1799151BFA0F
+ 6341CD83DA43A33A12410F45F6228079C4AEB3912BE87E2E81FA1799151BFA0E
                                                                 ^
```
Though this calls for question how to number offsets. I mean this notation invites zero at bottom. I mean something like
```
32:                                                                123
 0: - 6341CD83DA43A33A12410F45F6228079C4AEB3912BE87E2E81FA1799151BFA0F
 0: + 6341CD83DA43A33A12410F45F6228079C4AEB3912BE87E2E81FA1799151BFA0E
                                                                     ^
```
Kind of ugly, huh? Or maybe if one uses bit count it would be more clear? ...

**Comment by dot-asm** [comment]
Or maybe
```
                                                                123 : 256
 - 6341CD83DA43A33A12410F45F6228079C4AEB3912BE87E2E81FA1799151BFA0F : 0
 + 6341CD83DA43A33A12410F45F6228079C4AEB3912BE87E2E81FA1799151BFA0E : 0
                                                                  ^
```

**Comment by pauli-oracle** [comment]
> I don't follow. What word?

Using your example, displaying the top word's leading zeros would result in something like:

```
                                                          00000123
- 6341CD83DA43A33A12410F45F6228079C4AEB3912BE87E2E81FA1799151BFA0F
+ 6341CD83DA43A33A12410F45F6228079C4AEB3912BE87E2E81FA1799151BFA0E
                                                                 ^
```

I don't think they are necessary.


I'm thinking about separating the hex digits on BN_BYTES boundaries or would fixed 8 byte boundaries like the memory compare be better?

I like the look of the offset numbering on the right.  It looks good with a byte count too:

```
                                                                   123 : 32
 - 6341CD83DA43A33A 12410F45F6228079 C4AEB3912BE87E2E 81FA1799151BFA0F : 0
 + 6341CD83DA43A33A 12410F45F6228079 C4AEB3912BE87E2E 81FA1799151BFA0E : 0
                                                                    ^^
```

**Comment by levitte** [comment]
Quite frankly, if you don't *know* already what that decreasing offset numbering to right is, will people understand it intuitively?  Will a new OpenSSL developer coming in next year understand it?

**Comment by dot-asm** [comment]
> > What word?

> 00000123

I.e. 32-bit word. No, I'd also say it's unnecessary. It *could* make sense if least significant part wasn't "favoured" as discussed above. Or in other words bignum decomposition like above is informative enough without padding zeros on most significant side.

> I'm thinking about separating the hex digits on BN_BYTES boundaries or would fixed 8 byte boundaries like the memory compare be better?

Nibbles are fine by me, because they are the digits in the context. I mean just like if you were to compare decimal string presentation, say 5001 (as five thousand and one) and 5002, you wouldn't insist on marking digits by pairs. It's kind of same here. Though @levitte suggested to mark bytes. Is this digit argument sensible to you, Richard? Though if by-byte markup is easier to implement, it would work too... So whatever...

**Comment by dot-asm** [comment]
> Quite frankly, if you don't know already what that decreasing offset numbering to right is, will people understand it intuitively?

That's why I suggested to number by *bits* on the right side. At least numbering by ascending bytes on left side is actually more confusing. I mean offset from which byte? Most significant one? So that above example that starts with 123 would be numbered how? With 0 and 2? Does it really make sense? How easy would it be to access how long is the number? In words? bytes? bits?

> Will a new OpenSSL developer coming in next year understand it?

Ah! I know how to play this one :-) "I'm biased, so I'll let someone else answer your question" ;-) :-) @richsalz?

**Comment by dot-asm** [comment]
> by bits

Rationale basically is to exploit the fact that key-lengths in PKI algorithms are customarily expressed in bits. And observing such big offsets should trigger association with bits. I mean associations and intuition kind of fly together...

**Comment by levitte** [comment]
Bits or bytes doesn't matter for me, it's the decreasing offset that gets me, it's totally contrary to dumps we've all seen for eons.  Mind you, I *do* understand your reasoning, but then I've *followed* your reasoning for some time...  for someone new, it might not be very clear.  For a moment there, I was seriously considering if we should just not print the offset at all...  but I can see the downside.

So, errr, @richsalz, wanna play the arbitror?  ;-)

**Comment by richsalz** [comment]
I go with @dot-asm because he'll bump into this more than the rest of us, I expect.

**Comment by pauli-oracle** [comment]
I can add a header line indicating the right most column is bit offset.

```
                                                                    offset
                                                                123 : 256
 - 6341CD83DA43A33A12410F45F6228079C4AEB3912BE87E2E81FA1799151BFA0F : 0
 + 6341CD83DA43A33A12410F45F6228079C4AEB3912BE87E2E81FA1799151BFA0E : 0
                                                                  ^
```

It will be a squeeze to find suitable text but I'll think of something.

**Comment by dot-asm** [comment]
> I go with @dot-asm because he'll bump into this more than the rest of us, I expect.

This is not helpful response. Question was not about what do you think would be appreciated more by any particular team member, but if suggested presentation is intuitive enough for a fresh eye. And once again, my suggestions are not based on personal *preferences* (personally I'd prefer old-style straight line with operation minus result in bc format, because it's more versatile), but rather on projection of experience to make orientation in future problem report with this new way to present failure results meaningful/efficient for everybody, including[!] reporter.

**Comment by dot-asm** [comment]
> intuitive enough

Note that when I suggested bit offsets, I simply threw in offsets on the right side without mentioning units *at all*. Yet, response was "looks good with a byte count *too*". "Too" is clear indication that @pauli-oracle had no problem recognizing units.

**Comment by dot-asm** [comment]
Disregard last comment, as I did mentioned bits in post prior to one suggesting right-hand indexing. Sorry about noise :-(

**Comment by richsalz** [comment]
Nobody can predict the future, I still think Andy's suggestions are reasonable.

**Comment by levitte** [comment]
Okie ☺️

**Comment by pauli-oracle** [comment]
I done a PR for a first go at the reformatting in #3465.
I've displayed the offset in bytes but don't mind changing to bits if that's agreed upon.

**Comment by pauli-oracle** [comment]
The offset can be bit, nibble or byte -- it is just a matter of adding a scale factor to the output.

I'm highlighting by nibble (digit).

**Comment by pauli-oracle** [comment]
#3514 and #3515 clean up the string and memory output in light of the comments in #3465

**Comment by paulidale** [comment]
#3655 for the unification of the output of strings, bignums and memory dumps.

**Comment by paulidale** [comment]
Everything here has been done (will be once #3838 is closed).
