### ISSUE TITLE
openssl-1.0.2k dgst incorrectly treats "-engine" parameter for X9.31 padding

### ISSUE THREAD

**Issue by mouse07410** [openssl/openssl#3356]
When the keys are in files on a disk, everything's fine:
```
$ openssl dgst -keyform DER -sign rsa2048priv.der -sha256 -sigopt rsa_padding_mode:x931 -out t256.dat.sig t256.dat
$ openssl dgst -keyform DER -sha256 -verify rsa2048pub.der -sigopt rsa_padding_mode:x931 -signature t256.dat.sig t256.dat
Verified OK
$
```

However, when the key is on a hardware token, `dgst` command (according to OpenSC PKCS11SPY log given [here](https://github.com/OpenSC/libp11/issues/158)) tries to offload the padding processing to the token (i.e., when it invokes the "executors" it probably passes the engine ptr when it should pass NULL).

Here's the bad output from `openssl dgst`:
```
$ openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:manufacturer=piv_II;object=SIGN%20key;type=private" -sha256 -sigopt rsa_padding_mode:x931 -out t256.dat.sig t256.dat
engine "pkcs11" set.
Enter PKCS#11 token PIN for PIV Card Holder pin (PIV_II):
Enter PKCS#11 key PIN for SIGN key:
Error Signing Data
140736466609160:error:80009091:Vendor defined:PKCS11_rsa_encrypt:Operation not initialized:p11_rsa.c:120:
$ 
```

In case of RSASSA-PSS padding `openssl dgst` works correctly:
```
$ openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:manufacturer=piv_II;object=SIGN%20key;type=private" -sha256 -sigopt rsa_padding_mode:pss -out t256.dat.sig t256.dat
engine "pkcs11" set.
Enter PKCS#11 token PIN for PIV Card Holder pin (PIV_II):
Enter PKCS#11 key PIN for SIGN key:
$ openssl dgst -engine pkcs11 -keyform engine -verify "pkcs11:manufacturer=piv_II;object=SIGN%20pubkey;type=public" -sha256 -sigopt rsa_padding_mode:pss -signature t256.dat.sig t256.dat
engine "pkcs11" set.
Verified OK
$ 
```

**Comment by bernd-edlinger** [comment]
I think the rsa_priv_enc method is simply expected to handle RSA_PKCS1_PADDING
RSA_X931_PADDING and RSA_NO_PADDING
while the rsa_priv_dec is expected to handle RSA_PKCS1_PADDING
RSA_PKCS1_OAEP_PADDING (with SHA1), RSA_SSLV23_PADDING
and RSA_NO_PADDING just as the normal functions in rsa_eay.c
However if the replacement function from you engine fail to do that correctly,
then some padding modes will not work, it is just by chance that RSAPSS
and OAEP (if useing the EVP methods) work because they done are implemented
in rsa_pmeth.c and use RSA_NO_PADDING.
There are public helper methods so that implementing that in the engine
should be no big effort.

**Comment by richsalz** [comment]
Reported against 1.0.2, so not a just-1.1.1 issue, so removing that milestone.

**Comment by t8m** [comment]
The engines are deprecated in master. As this is basically a RFE against engines, this is not going to be implemented. Closing.
