### ISSUE TITLE
No way to select toolset with recent Visual Studio versions

### ISSUE THREAD

**Issue by sergey-shambir** [openssl/openssl#3376]
Since Visual Studio 2012 WinXP support turned off for default toolset, but can be enabled with MSBuild by using e.g. `v140_xp` toolset instead of `v140`.
As far as I know `nmake` doesn't allow to select toolset, but there is workaround shown in this Python2 script:

```py
import os

def replace_text_in_file(params, path):
    """
    Replaces `needle` text to `replacement` in given utf8 file
    """
    lines = []
    with open(path, 'r') as infile:
        for line in infile:
            for needle, replacement in params.iteritems():
                line = line.replace(needle, replacement)
            lines.append(line)
    with open(path, 'w') as outfile:
        for line in lines:
            outfile.write(line)

def fix_makefile(makefile_path):
    """
    Will force XP support.
    """
    params = {
        '/MD': '/MD -D_USING_V110_SDK71_ -D_WIN32_WINNT=0x501',
        '/subsystem:console': '/subsystem:console,5.01',
        'MKLIB=lib /nologo': 'MKLIB=lib /nologo /subsystem:console,5.01',
    }
    replace_text_in_file(params, os.path.join(SOURCES_DIR, makefile_path))

fix_makefile(r'ms\ntdll.mak')
```

OpenSSL Configure/Build scripts have no option to enable WinXP support within Visual Studio, that's very inconvient.

**Comment by dot-asm** [comment]
??? Does MKLIB look at /subsystem? /subsystem is something that it written to .exe or .dll, and lib doesn't produce either. Anyway, answer to the above question so far was `set LINK=/subsystem:console,5.01`. Can you actually confirm what it's insufficient? [Recall that you can pass additional compiler flags as extra config arguments.]

**Comment by dot-asm** [comment]
If questions remain unanswered, this will be closed.

**Comment by sergey-shambir** [comment]
Just overriding subsystem is unsafe if newer versions of OpenSSL will use WinAPI system calls that are not available on WinXP. Macros `_USING_V110_SDK71` and `_WIN32_WINNT` will cause compiler error in that case.

Howerver, right now setting LINK environment variable is enough.

**Comment by dot-asm** [comment]
> Just overriding subsystem is unsafe

That's why I said that additional flags can be passed as extra config arguments. I.e. you set LINK variable *and* pass required -D flags. Yes, it kind of sucks, because you have to ensure that LINK is set every time you "come back" to execute nmake. However, now, with confirmation that it's sufficient, it would be possible to arrange something in Configure. I actually had PR that would recognize MSVC-specific flags including /link. It kind of stalled because of certain ambiguity, but when get back to it, I'll keep even this /subsystem thing in mind... Thanks.
