### ISSUE TITLE
Crash due OPENSSL_assert(s->d1->mtu >= dtls1_min_mtu(s));

### ISSUE THREAD

**Issue by ibc** [openssl/openssl#346]
Debian 7.6 **openssl** package 1.0.1e-2+deb7u12.

We disable automatic MTU detection:
```c
#define RTPPAYLOADSIZE 1350
// [...]
SSL_CTX_set_options(ssl_ctx, SSL_OP_NO_QUERY_MTU);
```

Then we check whether `ssl->d1->mtu` is not 0 and set our own MTU value:
```c
BIO_write(read_bio, buffer, size);

if (!ssl->d1->mtu) {
  // No mtu set, trying to set it again.
  SSL_set_mtu(ssl, RTPPAYLOADSIZE);
  BIO_ctrl(write_bio, BIO_CTRL_DGRAM_SET_MTU, RTPPAYLOADSIZE, NULL);

  if (!ssl->d1->mtu)
    // Still not set => error
    return -1;
}

SSL_read(ssl, buffer, size);
```

In some cases it happens that an assert in ssl/d1_both.c is not satisfied and the app crashes:

```c
int dtls1_do_write(SSL *s, int type)
{
    int ret;
    unsigned int curr_mtu;
    int retry = 1;
    unsigned int len, frag_off, mac_size, blocksize, used_len;

    if (!dtls1_query_mtu(s))
        return -1;

    OPENSSL_assert(s->d1->mtu >= dtls1_min_mtu(s)); /* should have something
                                                     * reasonable now */
```

We have confirmed that within the `dtls1_do_write` function the value of `s->d1->mtu` is indeed 0, but our code above is supposed to avoid that. How can it happen?

**Comment by mattcaswell** [comment]
OpenSSL 1.0.1j and below is buggy with regards to MTU handling. Quite a lot of fixes in this area have gone in from 1.0.1k and later (and more general DTLS fixes after that). One fix in particular resolved a bug where SSL_OP_NO_QUERY_MTU was not always being respected (see commit 8aaeec9f9a4). Other fixes resolved problems with reachable asserts. I would recommend using the latest openssl version from the OpenSSL website rather than using the debian provided package as I suspect that these defect fixes have not been backported to debian.

**Comment by ibc** [comment]
Ok, will try with the trunk version.

**Comment by oeichenwei** [comment]
I tested with openssl 1.0.2d, it should use "DTLS_set_link_mtu(ssl, mtu)" instead of SSL_set_mtu
