### ISSUE TITLE
Invalid outl returned by EVP_DecryptUpdate

### ISSUE THREAD

**Issue by lumag** [openssl/openssl#3516]
In some cases `EVP_DecryptUpdate()` will fail to return proper length output to output buffer. For example see the following code, which demostrates that the buffer gets filled, but outl is returned as zero. Tested on Linux x86_64, gcc 6.3.0, both 1.0.2 and 1.1.0 branches.

```c
#include <openssl/evp.h>
#include <stdio.h>
#include <string.h>

void dump_head(unsigned char *buf, size_t len)
{
	unsigned end, i;
	for (end = len; end > 0; end--)
		if (buf[end-1] != 0)
			break;
	printf("buf = {");
	for (i = 0; i < end; i++)
		printf(" %02hhx,", buf[i]);
	printf(" }\n");
}

int main(void)
{
	unsigned char key[] = "0123456789abcdef";
	unsigned char iv[] = "1234567887654321";
	unsigned char indata[32] = "0123456789abcdeffedcba9876543210";
	unsigned char buf[32 + EVP_MAX_BLOCK_LENGTH];
	unsigned pos;
	int cipher_len;
	EVP_CIPHER_CTX *ctx;

	ctx = EVP_CIPHER_CTX_new();
	EVP_DecryptInit_ex(ctx, EVP_aes_128_ecb(), NULL, key, iv);
	pos = 0;
	while (pos < sizeof(indata)) {
		int seg = sizeof(indata) - pos;

		if (seg > 5)
			seg = 5;
		memset(buf, 0, sizeof(buf));
		EVP_DecryptUpdate(ctx, buf, &cipher_len, indata + pos, seg);
		pos += seg;
		printf("Got %d\n", cipher_len);
		dump_head(buf, sizeof(buf));
	}
	printf("Final!\n");
	memset(buf, 0, sizeof(buf));
	EVP_DecryptFinal_ex(ctx, buf, &cipher_len);
	printf("Got %d\n", cipher_len);
	dump_head(buf, sizeof(buf));

	return 0;
}
```

Output on my system:
```
Got 0
buf = { }
Got 0
buf = { }
Got 0
buf = { }
Got 16
buf = { 45, 59, 03, f1, b9, 34, 93, c2, c1, fa, 16, 90, ed, 21, 5b, f7, }
Got 0
buf = { }
Got 0
buf = { }
Got 0
buf = { db, 80, e9, 1f, 08, 0f, c1, e0, 8c, fd, fb, fc, f9, ed, 85, 2e, }
Final!
Got 0
buf = { }
```

**Comment by lumag** [comment]
Just to point that out, the trouble I'm observing, is an `outl` being incorrect (after seventh call to `EVP_DecryptUpdate()`).

**Comment by mattcaswell** [comment]
This is due to a bug in your code. By default the EVP routines will apply padding. See the NOTES section of the man page:

https://www.openssl.org/docs/man1.1.0/crypto/EVP_DecryptInit.html

In this case in the EVP_DecryptFinal_ex() the padding check is failing (because you are just decrypting "dummy" data). Therefore the `EVP_DecryptFinal_ex()` call is returning with an error code, which you are not checking for. To fix it you can either switch padding off by calling `EVP_CIPHER_CTX_set_padding(ctx, 0)` after the `EVP_DecryptInit_ex()` call, or you can change your dummy data to be "real" encrypted and properly padded data. You should also change your code to properly check for error conditions, and in the event of a failure check the OpenSSL error queue for more diagnostic information.
