### ISSUE TITLE
AES vulnerable to timing attacks

### ISSUE THREAD

**Issue by ghost** [openssl/openssl#353]
http://cr.yp.to/antiforgery/cachetiming-20050414.pdf demonstrates that table lookups are vulnerable to timing attacks and yet that's exactly what https://github.com/openssl/openssl/blob/master/crypto/aes/aes_x86core.c is doing.

**Comment by x64architecture** [comment]
See https://github.com/openssl/openssl/blob/master/crypto/aes/aes_x86core.c#L29

**Comment by dot-asm** [comment]
There are two essential words that are missing in original message, namely "would" and "if executed", i.e. that's what aes_x86core.c *would* be doing *if executed*. But the fact is that it's *not* executed in supported cases. The issue is discussed in great detail in https://securityblog.redhat.com/2014/07/02/its-all-a-question-of-time-aes-timing-attacks-on-openssl/.

**Comment by richsalz** [comment]
From the link Andy posted:  "In short answer, no"  Closing this issue.
