### ISSUE TITLE
How to set a CFLAG which separate by space 

### ISSUE THREAD

**Issue by kaichieh** [openssl/openssl#3543]
I've try to add CFLAG like -isysroot /Developer/SDKs/MacOSX10.6.sdk and -arch x86_64, so the instruction is something like the following
```
./config -isysroot /Developer/SDKs/MacOSX10.6.sdk -arch x86_64
```
But the config can't parse /Developer/SDKs/MacOSX10.6.sdk and  x86_64 because they are regarded as another option.
I'd like to know how to set this kind of CFLAG via openssl config.

**Comment by dot-asm** [comment]
Well, it's not like arbitrary option would work with whatever config makes out from current uname information. And specific platform flags have to match configuration parameters. And platform flags are customarily part of config line. For example -arch x86_64 is first flag in darwin64-x64_64-cc. The fact that you ask the question ought to mean that you end up using some other config line. And in such case I can tell that it wouldn't work, or at least we wouldn't support such configuration. Once again, question itself suggests that something unwanted/unexpected/wrong is going on. Quoting INSTALL
```
       $ ./config [[ options ]]
     ...
     This guesses at your operating system (and compiler, if necessary) and
     configures OpenSSL based on this guess. Run ./config -t to see
     if it guessed correctly. If you want to use a different compiler, you
     are cross-compiling for another platform, or the ./config guess was
     wrong for other reasons, go to step 1b. Otherwise go to step 2.
```
But for completeness sake in order to pass "two-word" option, use %20 instead of space, e.g. -foo%20bar.

**Comment by kaichieh** [comment]
%20 is what I need. Thanks for your reply.
