### ISSUE TITLE
err_cleanup deletes err_thread_local even if not initialized

### ISSUE THREAD

**Issue by heftig** [openssl/openssl#3584]
I've been debugging a crash in colord-sane which led me to libcrypto (https://bugs.archlinux.org/task/54205).

`OPENSSL_cleanup`, which is called `atexit`, runs `err_cleanup` which cleans up `err_thread_local` even if the latter has never been initialized and is still `0`.

Pthread key `0` is valid and belongs to glib (specifically GSlice's `private_thread_memory`). Glib is still running in other threads while the main thread is exiting.

Glib's worker thread races with the main thread and, if unlucky, attempts to use the thread-local after libcrypto has destroyed, resulting in a noisy SIGABRT.

libcrypto should not delete a `pthread_key_t` it never created.

Probably fallout from https://github.com/openssl/openssl/pull/3035.

OpenSSL 1.1.0f
glib 2.52.2
glibc 2.25

**Comment by richsalz** [comment]
Does this patch fix it?
```
; g diff
diff --git a/crypto/err/err.c b/crypto/err/err.c
index f866f2f..c55f849 100644
--- a/crypto/err/err.c
+++ b/crypto/err/err.c
@@ -122,6 +122,7 @@ static ERR_STRING_DATA ERR_str_reasons[] = {
 #endif

 static CRYPTO_ONCE err_init = CRYPTO_ONCE_STATIC_INIT;
+static int set_err_thread_local;
 static CRYPTO_THREAD_LOCAL err_thread_local;

 static CRYPTO_ONCE err_string_init = CRYPTO_ONCE_STATIC_INIT;
@@ -260,7 +261,8 @@ DEFINE_RUN_ONCE_STATIC(do_err_strings_init)

 void err_cleanup(void)
 {
-    CRYPTO_THREAD_cleanup_local(&err_thread_local);
+    if (set_err_thread_local != 0)
+        CRYPTO_THREAD_cleanup_local(&err_thread_local);
     CRYPTO_THREAD_lock_free(err_string_lock);
     err_string_lock = NULL;
 }
@@ -639,6 +641,7 @@ void ERR_remove_state(unsigned long pid)

 DEFINE_RUN_ONCE_STATIC(err_do_init)
 {
+    set_err_thread_local = 1;
     return CRYPTO_THREAD_init_local(&err_thread_local, NULL);
 }

```

**Comment by heftig** [comment]
That indeed seems to fix it; thanks.

**Comment by Mekk** [comment]
I feel that the patch is fixing wrong problem. 

It seems to me that the real problem is that macro DEFINE_RUN_ONCE_STATIC is invalid if used more than once in singe file. See: https://github.com/openssl/openssl/blob/master/include/internal/thread_once.h#L58  – the macro relocates actual code to static function named ```init```, then calls this function. 

If the macro is used twice in single .c file, then single compilation unit contains two static functions named init, and two calls to this function from static initializer. Usually this means that linker throws one away and calls another twice.

Now take a look at
    https://github.com/openssl/openssl/blob/master/crypto/err/err.c
My bet is that  do_err_strings_init gets called twice (leaking a bit), and err_do_init - never. 

Not sure what are consequences of uninitialized err_thread_local (apart from openssl cleanup calling pthread_key_delete on value 0, which accidentally happen to be value of uninitialized err_thread_local) but probably there are some.

To fix the problem either macro DEFINE_RUN_ONCE_STATIC should be rewritten to work if called more than once, or err.c split into two files.



PS I just spend a day of debugging tracking mysterious exit error in my code, which finally turned out to be caused by openssl calling pthread_key_delete on key zero which belonged to my library.

**Comment by Mekk** [comment]
As I can't reopen this issue, I raised https://github.com/openssl/openssl/issues/8384
