### ISSUE TITLE
Thread safety and using gmtime/localtime.

### ISSUE THREAD

**Issue by thatGuy-** [openssl/openssl#3604]
At work we’ve noticed that in parts of the codebase (currently using **v1.0.2l** but have noticed it since **v1.0.1**) the functions `gmtime` and `localtime` are being used on platforms that don’t guarantee thread safety using them within a multi-threaded application.

For example in `OPENSSL_gmtime()` in **crypto/o_time.c** it is deliberately deciding to use `gmtime` on macOS instead of the thread safe `gmtime_r` (even when `OPENSSL_THREADS` is set by passing in the threads option to the configure script). 

There are a few other spots that do similar things, where they are deliberately being used on linux/mac platforms instead of their thread safe counterparts `gmtime_r` and `localtime_r`. 

Some other examples:

- `gmtime` being used in function `TS_RESP_set_genTime_with_precision()` in **crypto/ts/ts_rsp_sign.c**
- `localtime` and `gmtime` being used in function `kssl_check_authent()` in **ssl/kssl.c**
- `localtime` being used in function `print_leak_doall_arg()` in **crypto/mem_dbg.c**

I’m just wondering if this is something that may need to be patched, or is it being done deliberately for a reason that I haven’t noticed? 

Thanks

**Comment by richsalz** [comment]
It was not a conscious design decision.  Much of OpenSSL isn’t thread-safe.  Much of it can be.

**Comment by kroeckx** [comment]
If it's easy to make things thread safe we should probably do it.
The only concern I have is that some of those functions might not
be portable to all platforms.

**Comment by thatGuy-** [comment]
I put in a pull request for this at #3609. 

It should be portable. `gmtime_r` and `localtime_r` are now only called on platforms that support it. All calls to `gmtime` have been updated to call `OPENSSL_gmtime()` instead, which will call the appropriate version depending on the platform. The function was also updated to now allow macOS to use `gmtime_r`.

For calls to `localtime`, since systems that support `gmtime_r` also support `localtime_r`, similar platform logic was used to determine whether it is allowed to call the thread safe "_r" variant of the function or not.

**Comment by noloader** [comment]
> It should be portable. gmtime_r and localtime_r are now only called on platforms that support it. ...

Windows should use `gmtime_s` and `localtime_s`. See, for example, [gmtime_s, _gmtime32_s, _gmtime64_s](https://msdn.microsoft.com/en-us/library/3stkd9be.aspx) on MSDN. They first appeared in Visual Studio 2005, so the guard for using them should be:

```
#if _MSC_VER >= 1400
    ...
#endif
```

**Comment by dot-asm** [comment]
> Windows should use whatever_s.

I'd say "*could* use". I mean there is nothing extraordinary magic about gmtime_s. And since it's effectively equivalent option, one can wonder if extra #if case would be justified. I mean would it actually make code easier to maintain?

Speaking of easier to maintain. Here is radical idea. Is it really complicated conversion from time_t to struct tm? It's probably more lines than all those #ifs (including those for VMS account in master), but is it actually *that* complicated [to refuse to consider to implement one]?

**Comment by noloader** [comment]
@dot-asm,

Good points.

> I mean would it actually make code easier to maintain?

Believe it or not, this often helps some folks the most by getting them through an audit more quickly. The non-safe function will trigger a finding, and it starts a process. Each organization is different regarding how painful the process is.

I'm guessing about 95% of the folks won't care, and 5% of the folks will buy you beer for life.

**Comment by dot-asm** [comment]
What's non-safe about gmtime on Windows? The only essential difference is how they signal failure, which you have to pay attention to in either case. [BTW, as far as thread safety goes Windows gmtime is thread-safe, because it allocates per-tread storage.] Implied question also was how would 5% feel about not using any gmtime variant?

**Comment by levitte** [comment]
This seems to be fixed by now.  Closing.  If I'm wrong, feel free to re-open
