### ISSUE TITLE
"read R BLOCK" error on s_client when TLS1.3 is enabled

### ISSUE THREAD

**Issue by yctung** [openssl/openssl#3649]
Hi,

I just compile the latest (master) code in my Mac. I try to make few small test about TLS1.3.
The handshake seems working perfectly but I keep getting a "read R BLOCK" in my s_client

Here is the code to reproduce the error: 
**in the server side:** openssl s_server -key key.pem -cert cert.pem -accept 44330 -WWW -state
**in the client side:** s_client -state -connect localhost:44330 -tls1_3
#
**Dumped messages in the client:**
SSL handshake has read 1482 bytes and written 276 bytes
Verification error: self signed certificate
New, TLSv1.3, Cipher is TLS13-AES-256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS13-AES-256-GCM-SHA384
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 948BFDC4B03D5DC5EA39AF527D81D93F2BFE8B63150E38E031E5E0BB76BD8A9E7910DE7FFBABE42CEC95AE30C09BC638
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1497050202
    Timeout   : 7200 (sec)
    Verify return code: 18 (self signed certificate)
    Extended master secret: no
SSL_connect:SSL negotiation finished successfully
SSL_connect:SSL negotiation finished successfully
SSL_connect:SSLv3/TLS read server session ticket
read R BLOCK

Does any know how to fix it? Would it be a bug in the new TLS1.3 code? (I would not have this problem if I use TLS1.2)

Yu-Chih

**Comment by mattcaswell** [comment]
This is normal expected behaviour. The "read R BLOCK" message can occur even with TLSv1.2 and is an information message which effectively means "s_client attempted to read some application data but libssl was not able to return any". For example, in TLSv1.2 this could occur if a TLS record is split over 2 TCP packets. The arrival of the first packet will cause s_client to attempt to read application data, but because a full TLS record has not yet arrived, the read will not return any data and you will get "read R BLOCK".

In the TLSv1.3 case, what is happening is that after the handshake is complete an additional protocol message is being sent by the server (i.e. not application data). The arrival of the protocol message is causing s_client to think that application data might be available so it tries to read it. Because it is a protocol message and not application data nothing is returned and so you get "read R BLOCK". TLSv1.3 has made changes to the way sessions work. Sessions are established by a post-handshake protocol message. This is what you are seeing. It is perfectly harmless and normal and can be ignored.

**Comment by yctung** [comment]
Hi Mattcaswell, 

Thank you for replying it. However, I don't get the idea why it should be considered not an "error". In the TLSv1.3 case, the client then should either 1) don't read at that time or 2) read, but the SSL_read told him there is nothing to read instead of the error, right? Do you mean that "read R Block" is not an error message but one of this flag to told client there is nothing to read.

Yu-Chih

**Comment by kroeckx** [comment]
I think what Matt is saying is that it's a debug message. And
maybe we should just not display it?

**Comment by yctung** [comment]
Hi Kroeckx,

That surprise me a lot. Does that mean I can ignore all the "read block" error in my code when I use openssl? (my old project using openssl 1.0.2k will exist when it receives any of these error messages, i.e., return value of SSL_read() < 0).

Yu-Chih

**Comment by mattcaswell** [comment]
> I think what Matt is saying is that it's a debug message. And maybe we should just not display it?

Well, it's informational. s_client is typically used for diagnostic and debug purposes, so I look on it as an intentional feature.

> And maybe we should just not display it?

This behaviour is long standing. The TLSv1.3 code makes it more obvious because it typically happens most times a client connects to a server. I don't see any need to remove it.

**Comment by mattcaswell** [comment]
> That surprise me a lot. Does that mean I can ignore all the "read block" error in my code when I use openssl? (my old project using openssl 1.0.2k will exit when it receives any of these error messages, i.e., return value of SSL_read() < 0).

Exiting on SSL_read() < 0 is incorrect behaviour. A -ve return value is not necessarily a fatal error. See https://www.openssl.org/docs/man1.0.2/ssl/SSL_read.html and https://www.openssl.org/docs/man1.0.2/ssl/SSL_get_error.html

**Comment by yctung** [comment]
Hi Matt,

Thank you for the explanation. It is very clear to me. I felt so lucky that my old project never have this issue when using OpenSSL 1.0.2k. I am going to modify it then.

Yu-Chih
