### ISSUE TITLE
NPN is not supported at TLS 1.3 anymore?

### ISSUE THREAD

**Issue by yctung** [openssl/openssl#3665]
Hi,

I am updating OpenSSL of my project from 1.0.2 to 1.1.1 (mainly to upgrade TLS1.2 to TLS1.3). I just notice that when the TLS1.3 is enabled npn is not working anymore. 

For example: 
`openssl s_server -nextprotoneg "h2" + openssl s_client -nextprotoneg "h2" -tls1_2`
is fine

but 
`openssl s_server -nextprotoneg "h2" + openssl s_client -nextprotoneg "h2" -tls1_3`
is not ok

The client/server never get the callback being called. After tracing few codes, I notice in the ssl/statem/extension.c, the npn context is defined as: 
```
#ifndef OPENSSL_NO_NEXTPROTONEG
    {
        TLSEXT_TYPE_next_proto_neg,
        SSL_EXT_CLIENT_HELLO | SSL_EXT_TLS1_2_SERVER_HELLO
        | SSL_EXT_TLS1_2_AND_BELOW_ONLY,
        init_npn, tls_parse_ctos_npn, tls_parse_stoc_npn,
        tls_construct_stoc_next_proto_neg, tls_construct_ctos_npn, NULL
    },
#else
```
which makes the npn extension be "filtered out" during the `should_add_extension()` call because of the set `SSL_EXT_TLS1_2_AND_BELOW_ONLY` mask.

I know people are moving from npn to alpn. My project was supporting both and I see many websites doing so. So I am wondering if npn in openssl 1.3 is officially not supported anymore? or it is just not implemented yet?

**Comment by InfoHunter** [comment]
From my understandings, NPN requires an extra `EncryptedExtensions` message prior to `Finished` msg to tell the server what protocol is selected at last. Per [TLS 1.3 pec](https://tlswg.github.io/tls13-spec/), it doesn't state such a message should be presented among messages from client side. And it seems no other specifications/RFCs make this an additional stuff to TLS 1.3. Draft of [NPN](https://tools.ietf.org/html/draft-agl-tls-nextprotoneg-04) states this for TLS 1.2 as:

> A new handshake message type ("encrypted_extensions(TBD)") is
   defined.  If the server included a "next_protocol_negotiation"
   extension in its "ServerHello" message, the client MUST send a
   "EncryptedExtensions" message after its "ChangeCipherSpec" and before
   its "Finished" message.

Since no specifications there (as you know NPN is outdated and never standardized), so I don't think it should be put in any TLS 1.3 implementation.

Anyway, I think there should be an explicit prompt in `s_client`'s output to state it's invalid to use `-nextprotoneg` along with `-tls1_3`

**Comment by mattcaswell** [comment]
> I know people are moving from npn to alpn. My project was supporting both and I see many websites doing so. So I am wondering if npn in openssl 1.3 is officially not supported anymore? or it is just not implemented yet?

As @InfoHunter says, NPN is not well defined for TLSv1.3 so it is not possible to implement it.

**Comment by yctung** [comment]
Got it! Thank you for the reply!

**Comment by hellt** [comment]
@InfoHunter Does OpenSSL have any plans to drop NPN support for TLS 1.2?

**Comment by mattcaswell** [comment]
> Does OpenSSL have any plans to drop NPN support for TLS 1.2?

No, there are no such plans.
