### ISSUE TITLE
Is checking error queue for returning error done correctly in SSL_CTX_use_certificate_chain_file ?

### ISSUE THREAD

**Issue by akhilbaai** [openssl/openssl#3690]
I see the code in ssl/ssl_rsa.c ( use_certificate_chain_file() )

`err = ERR_peek_last_error();
if (ERR_GET_LIB(err) == ERR_LIB_PEM
   && ERR_GET_REASON(err) == PEM_R_NO_START_LINE)
            ERR_clear_error();
        else
            ret = 0;  `

So if there is no error in the queue, as per documentation ERR_peek_last_error() returns 0.
This fails this function. 
I'm seeing, for some reason one executable linked to openssl lib succeeds loading certitificate by passing this if condition and another executable fails since last error is 0.

**Comment by mattcaswell** [comment]
SSL_CTX_use_certificate_chain_file() keeps looping over the BIO trying to read certificates from it until PEM_read_bio_X509() returns NULL (indicating an error has occurred). If the error that terminated the loop is PEM_R_NO_START_LINE then this is expected - it just means the BIO has no more data to provide. Any other error is a *real* error and should be propagated back to the caller. So I think this function is doing the right thing.

What is perhaps more surprising is if ERR_peek_last_error() returns 0. This means that PEM_read_bio_X509() has failed (because to get here we know it returned NULL), but there is no error on the error queue. So, if there is any bug here, it is that PEM_read_bio_X509() failed without populating the error queue.

**Comment by richsalz** [comment]
does it just break, return NULL on EOF?

**Comment by akhilbaai** [comment]
Is the error queue global or local to a thread ? But even an ERR_print_errors() somewhere can clear the queue.

**Comment by mattcaswell** [comment]
The error queue is local.

> But even an ERR_print_errors() somewhere can clear the queue.

I'm not sure what your point is.

**Comment by akhilbaai** [comment]
Thanks for your response..
Im just trying to figure out why it fails in one executable..
So kept traces in openssl for debugging..

EXE1 ( loads certiticate )
 -> PEM_bytes_read_bio returns NULL
 -> ERR_peek_last_error called from, file=crypto/err/err.c, line=420
 ->Trying to get errors from queue, get_error_values called from file=crypto/err/err.c, line=445
 -> err = 151441516, GET_LIB = 9, GET_REASON = 108

EXE2( fails to load certitificate )
 -> PEM_bytes_read_bio returns NULL
 -> err = 0, GET_LIB = 0, GET_REASON = 0

It is strange that EXE2 doesn't give traces that it has executed the code in ERR_peek_last_error..
Could you please tell me what could be the issue in the second case.. and from where it could get this error 0..

**Comment by mattcaswell** [comment]
Which version of OpenSSL are you using? Looking at the code in master I can see that if a PEM file contains a start and end line but with no data between them, then that will fail without an error in the queue. I can also see a situation where a malloc failure can end up without an error going on the queue. Other OpenSSL versions may be different.

**Comment by akhilbaai** [comment]
I'm using OpenSSL 1.1.0e

**Comment by kaduk** [comment]
Did you clarify whether the two executables exhibiting different behavior are trying to load the same certificate file or different ones?  If the latter, you should probably tell us more about the structure of the two files.

**Comment by akhilbaai** [comment]
I tried loading the same as well as two different certificates. In both cases the same result was observed. One certificate is a self signed certificate with embedded private key in it. The other one is having embedded private key, certificate and CA certificate in a single file. Both certificates are PEM encoded. 
The executable which fails is a multi process one and the one succeeds spawns only single process.

**Comment by akhilbaai** [comment]
Adding a bit more detailed trace..

**EXE1 (loads certificate)**
- PEM_bytes_read_bio called
- PEM_read_bio called
- BIO fgets reads, len=0 : 
- ERR_get_state called, state = 80c0f20
- err-clear_data() called from, file=crypto/err/err.c , line=369
- BIO_gets, returns 0
- BIO_gets, error logged, PEM_R_NO_START_LINE
- Error in PEM_read_bio
- ERR_get_state called, state = 80c0f20
- Trying to get errors from queue, get_error_values called from file=crypto/err/err.c, line=446
- ERR_get_state called, state = 80c0f20
- err-clear_data() called from, file=crypto/err/err.c , line=710
- PEM_bytes_read_bio returns NULL
- ERR_peek_last_error called from, file=crypto/err/err.c, line=421
- ERR_get_state called, state = 80c0f20
- Trying to get errors from queue, get_error_values called from file=crypto/err/err.c, line=446
- err = 906d06c, GET_LIB = 9, GET_REASON = 108
- ERR_print_errors_fp called
- ERR_print_errors_cb called
- ERR_get_error_line_data called from, file=crypto/err/err.c, line=399
- ERR_get_state called, state = 80c0f20
- Trying to get errors from queue, get_error_values called from file=crypto/err/err.c, line=446
- 0:error:0906D06C:PEM routines:PEM_read_bio:no start line:crypto/pem/pem_lib.c:693:Expecting: CERTIFICATE

**EXE2 (fails loading certificate)**

- PEM_bytes_read_bio called
- PEM_read_bio called
- BIO fgets reads, len=0 : 
- ERR_get_state called, state = a6d0748
- err-clear_data() called from, file=crypto/err/err.c , line=369
- BIO_gets, returns 0
- BIO_gets, error logged, PEM_R_NO_START_LINE
- Error in PEM_read_bio
- ERR_get_state called, state = a6d0748
- Trying to get errors from queue, get_error_values called from file=crypto/err/err.c, line=446
- ERR_get_state called, state = a6d0748
- err-clear_data() called from, file=crypto/err/err.c , line=710
- PEM_bytes_read_bio returns NULL
- err = 0, GET_LIB = 0, GET_REASON = 0
- some other error
- ERR_print_errors_fp called
- ERR_print_errors_cb called
- ERR_get_error_line_data called from, file=crypto/err/err.c, line=399
- ERR_get_state called, state = a6d0748
- Trying to get errors from queue, get_error_values called from file=crypto/err/err.c, line=446
- 0:error:0906D06C:PEM routines:PEM_read_bio:no start line:crypto/pem/pem_lib.c:693:Expecting: CERTIFICATE

The strange thing is that, EXE2 while checking the error queue retuns 0 and just after when printing the error queue before clearing it actually gives the exact error as expected..
As I pointed out earlier,
_ERR_peek_last_error called from, file=crypto/err/err.c, line=421_
Above trace is missing in EXE2 and I've no idea how it gets the error 0..

Any help on identifying what is going wrong is highly appreciated..

**Comment by mattcaswell** [comment]
It would be helpful to know what ERR_peek_last_error() reports immediate after the PEM_R_NO_START_LINE gets logged, and at intermediate points between then and when it is finally checked in SSL_CTX_use_certificate_chain_file(). It would be useful to know at what point does it apparently "forget" that it has already logged PEM_R_NO_START_LINE.

Does this problem happen consistently every time? Or is it intermittent?

**Comment by akhilbaai** [comment]
Please tell me where PEM_read_bio_X509() is defined or which function eventually gets invoked. I'm keeping more traces in PEM_read_bio() where this error is getting logged. I can see inside PEM_read_bio(), after logging the error, ERR_peek_last_error() returns correct errors.. I'll add more traces inside PEM_read_bio_X509() and will post the traces..

> Does this problem happen consistently every time? Or is it intermittent?

This happens all the time with EXE2.

**Comment by levitte** [comment]
> Please tell me where PEM_read_bio_X509() is defined

[here](https://github.com/openssl/openssl/blob/master/crypto/pem/pem_x509.c#L18)

Nope, not a joke.  You will find all the necessary macros in `include/openssl/pem.h`

**Comment by mattcaswell** [comment]
PEM_read_bio_X509() is implemented in crypto/pem/pem_x509.c by a complicated series of macros. Ultimately though it is a thin wrapper around PEM_ASN1_read_bio(). That calls PEM_bytes_read_bio(), which calls pem_bytes_read_bio_flags() which calls PEM_read_bio_ex().

**Comment by akhilbaai** [comment]
Kept a lot of tracing in the code..

- BIO_gets, error logged, PEM_R_NO_START_LINE
 - ERR_peek_last_error called from, file=crypto/err/err.c, line=421
 - ERR_get_state called, state = 94728e0
 - Trying to get errors from queue, get_error_values called from file=crypto/err/err.c, line=446
 - Just after logging error, err = 906d06c, GET_LIB = 9, GET_REASON = 108
 - Error in PEM_read_bio
 - ERR_peek_last_error called from, file=crypto/err/err.c, line=421
 - ERR_get_state called, state = 94728e0
 - Trying to get errors from queue, get_error_values called from file=crypto/err/err.c, line=446
 - PEM_read_bio return time, err = 906d06c, GET_LIB = 9, GET_REASON = 108
 - ERR_get_state called, state = 94728e0
 - Trying to get errors from queue, get_error_values called from file=crypto/err/err.c, line=446
 - ERR_get_state called, state = 94728e0
 - err-clear_data() called from, file=crypto/err/err.c , line=710
 - ERR_peek_last_error called from, file=crypto/err/err.c, line=421
 - ERR_get_state called, state = 94728e0
 - Trying to get errors from queue, get_error_values called from file=crypto/err/err.c, line=446
 - PEM_bytes_read_bio returning 0, err = 906d06c, GET_LIB = 9, GET_REASON = 108
 - PEM_ASN1_bytes_read_bio returns NULL
 - ERR_peek_last_error called from, file=crypto/err/err.c, line=421
 - ERR_get_state called, state = 94728e0
 - Trying to get errors from queue, get_error_values called from file=crypto/err/err.c, line=446
 - PEM_ASN1_read_bio after return time, err = 906d06c, GET_LIB = 9, GET_REASON = 108
 - err = 0, GET_LIB = 0, GET_REASON = 0
 - some other error
 - ERR_print_errors_fp called
 - ERR_print_errors_cb called
 - ERR_get_error_line_data called from, file=crypto/err/err.c, line=399
 - ERR_get_state called, state = a6d0748
 - Trying to get errors from queue, get_error_values called from file=crypto/err/err.c, line=446
 - 0:error:0906D06C:PEM routines:PEM_read_bio:no start line:crypto/pem/pem_lib.c:693:Expecting: CERTIFICATE

Still getting same issue in EXE2.
I'm linking ssl.so and crypto.so to EXE2. My observation is when all the functions in crypto calls ERR_peek_last_error(), it returns correct value. Here SSL_CTX_*() calls it several places and gets 0.
I even tried with gdb to understand the flow and see while SSL_CTX_*() calls, it doesn't hit a break point inside ERR_peek_last_error(). 

I saw the same issue was raised in few places but didn't get any satisfying answer..
http://openssl.6102.n7.nabble.com/SSL-CTX-use-certificate-chain-file-can-return-zero-on-success-td55043.html
http://openssl.6102.n7.nabble.com/openssl-0-9-8n-and-openssl-fips-1-2-ERR-peek-last-error-failure-td19317.html

**Comment by mattcaswell** [comment]
Not specific to 1.1.1 so removing that milestone.

**Comment by t8m** [comment]
Is this still an issue with current 1.1.1 releases?

**Comment by datto-nathan-lutterman** [comment]
I'm not sure if I'm insane or not, but I think I've just come across this.  I'm _not_ well versed in working with the library directly, but I was affected as a user of Barrier, the network KVM tool: https://github.com/debauchee/barrier/.  I'm linking against `OpenSSL 1.1.1k`.  

I'm dumping the error stack via `ERR_print_errors_fp(stderr);` before and after attempting to slurp up the PEM-format X509 certificate.  I've ensured that there was nothing wrong with the file by reading it in and dumping it in multiple ways, into different formats, etc.  

I eventually get to the same error that's been repeated above:

```
140712754767040:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: CERTIFICATE
```

I get that same error, every single time.

I did a little bit more tracing myself and noticed that `PEM_read_bio_X509()` is a function that is essentially generated by macros. After following the crumbs, I eventually found myself staring down the macro which generated the declaration and definition:

Declaration: [include/openssl/pem.h#L197-L198](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1k/include/openssl/pem.h#L197-L198):  

```C
#  define DECLARE_PEM_read_bio(name, type) \
        type *PEM_read_bio_##name(BIO *bp, type **x, pem_password_cb *cb, void *u);
```

Definition: [include/openssl/pem.h#L108-L112](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1k/include/openssl/pem.h#L108-L112)

```C
# define IMPLEMENT_PEM_read_bio(name, type, str, asn1) \
type *PEM_read_bio_##name(BIO *bp, type **x, pem_password_cb *cb, void *u)\
{ \
return PEM_ASN1_read_bio((d2i_of_void *)d2i_##asn1, str,bp,(void **)x,cb,u); \
}
```

So when we call `PEM_read_bio_X509()`, we're _actually_ calling `PEM_ASN1_read_bio()`.

The definition of that function can be found here: https://github.com/openssl/openssl/blob/OpenSSL_1_1_1k/crypto/pem/pem_oth.c#L20-L36

After all the macros run their series of transformations, then the expression:  
    `X509* cert = PEM_read_bio_X509(bp, NULL, 0, NULL);`

becomes:  
    `X509* cert = (X509*)PEM_ASN1_read_bio((d2i_of_void *)d2i_X509, "CERTIFICATE", bio, NULL, NULL, NULL);`

The function `PEM_ASN1_read_bio()` calls [`PEM_bytes_read_bio()`](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1k/crypto/pem/pem_lib.c#L275-L280) which is a wrapper for [`pem_bytes_read_bio_flags()`](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1k/crypto/pem/pem_lib.c#L232-L273). Inside the latter, I can see in that function we have this logic here, checking for flags:

```C
    if (!PEM_read_bio_ex(bp, &nm, &header, &data, &len, flags)) {
        if (ERR_GET_REASON(ERR_peek_error()) == PEM_R_NO_START_LINE)
            ERR_add_error_data(2, "Expecting: ", name);
        return 0;
```

So there's our error, the expression `ERR_add_error_data(2, "Expecting: ", name);`.  `name` is "CERTIFICATE" there, making "Expecting: CERTIFICATE" appear as the error message.  

I did a _buuunch_ more debugging and stepping through things and I think I've found my own issue.  Eventually, `check_pem()` gets called in a `do...while()` loop: [crypto/pem/pem_lib.c#L252](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1k/crypto/pem/pem_lib.c#L252).  Inside of `check_pem()`, there's a series of string comparisons done against the `name` var from above ("CERTIFICATE") and the name that's obtained from the header file (I think).

So _heeeere's_ the kicker, in my case.  This first comparison is done:

```C
    /* Make PEM_STRING_EVP_PKEY match any private key */

            if (strcmp(name, PEM_STRING_EVP_PKEY) == 0) {
                int slen;
                const EVP_PKEY_ASN1_METHOD *ameth;
                if (strcmp(nm, PEM_STRING_PKCS8) == 0)
                    <span class="pl-k">return</span> <span class="pl-c1">1</span>;
```

`name` is compared to `PEM_STRING_EVP_PKEY` first.  The key that I'm ultimately trying to check against is titled `"PRIVATE KEY"`.  Since the original call to `PEM_read_bio_X509()` always ends up choosing "CERTIFICATE" as the name, my private key will never work! It's a PKCS8 key!  :facepalm::facepalm::facepalm:  

So ultimately, my solution is to either use a key with a "CERTIFICATE" header, or to change the `PEM_read_bio_X509()` call for reading in a PKCS8 key.

I hope my walkthrough of debugging this myself helps someone else out some day, or maybe leads to some kind of improvement or clarification down the line.

Thanks @akhilbaai for sticking with it, originally!

**Comment by t8m** [comment]
Closing as this was reported against 1.1.0e and there was no response.
