### ISSUE TITLE
more const

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#3742]
We could make more things const -- in particular API parameters.
There's been discussion on whether not adding const to an API breaks ABI, but for now let's just record the issue as something we want to address.

**Comment by levitte** [comment]
I agree with you (except I'd say that *only* API parameters can be safely consitified).
Some care must be taken, though...  there are some types that can't be constified as things currently stand, even as input parameters, because they cache things in the structure on the fly.  `X509` is one of them.

**Comment by mattcaswell** [comment]
Moving this to post-1.1.1 milestone.

**Comment by DDvO** [comment]
https://github.com/openssl/openssl/pull/7646/commits/168824237fd33e634b9e3f021b8404ea758e5871 provides some more const, mostly on  `*_dup()` and `*i2d_*()` and related functions.

**Comment by DDvO** [comment]
PR #8029 provides some more const, mostly on  `*_dup()` and `*i2d_*()` and related functions.

**Comment by t8m** [comment]
This is too broad issue. Closing. If there is anything that can be easily constified without an API break, feel free to open a concrete issue or even better a PR.
