### ISSUE TITLE
compilation fails with no-ui

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#3806]
crypto\store\loader_file.c(56): error C2065: 'UI_INPUT_FLAG_DEFAULT_PWD': undeclared identifier

I do assume the #if !defined(OPENSSL_NO_UI) checks in https://github.com/openssl/openssl/blob/master/crypto/store/loader_file.c are missing.

**Comment by levitte** [comment]
Hmmm...  Using UI is an integral part of OSSL_STORE, so that would mean that turning off UI would turn off OSSL_STORE, which is unfortunate.

However, this has me thinking that both UI and OSSL_STORE are really composed of two things each, 1) a core API for which one can build methods, and 2) one or more method that implements the functionality (a console method for UI, a file loading method for OSSL_STORE.
So I'm what I'm wondering is if it's really interesting to disable the core libraries (and why), or are the methods the real thing one might want to disable?

What say you, @matbech?

**Comment by levitte** [comment]
In the lack of an answer, I think I'll opt for making UI non-disablable.  However, I'll make the default built-in method `UI_OpenSSL` disablable, with the assumption that this is important to be able to do on small devices for the same reason `no-stdio` may be a good idea.

As a side effect, this also simplifies other routines, like `PEM_def_callback` and `EVP_read_pw_*`, as they currently make more assumptions about the default UI they use than they should.

I hope this option will be satisfactory.

**Comment by matbech** [comment]
That sounds like a good idea. An option like no-ui-console would then exclude UI_OpenSSL and set the default ui method to UI_null. On Windows, this would remove imports for ReadConsoleW and co., which was one of the reasons no-ui was originally used.

**Comment by levitte** [comment]
Cool, I'm glad we're on the same page :-)

**Comment by richsalz** [comment]
This sounds like a bug.  Can you open an issue for it?

**Comment by akryeem-INTC** [comment]
Issue opened:
https://github.com/openssl/openssl/issues/5465
