### ISSUE TITLE
Build with Bazel

### ISSUE THREAD

**Issue by qzmfranklin** [openssl/openssl#3840]
Hi,

Newbie here.

I have checked the CONTRIBUTING file. Did not find any relevant section on the issue I am bringing up. Would be happy to comply if there are other rules regarding opening issues.

I want to build openssl with the Bazel build system (https://bazel.build/) on at least trusty/xenial-x86_64 systems. I know that the only build system supported by openssl, at least thus far, has been the perl config scripts plus the generated Makefiles. Could anyone provide information on whether building with Bazel is desirable or not?

To illustrate the point, I have created a branch that adds the Bazel support here:
https://github.com/qzmfranklin/openssl/tree/bazel

On that branch, assuming you are on a Ubuntu 16 x86_64 machine with bazel installed (default toolchain configuration), you should be able to build the crypto and ssl libraries via:
```
bazel build :crypto :ssl
```

Note that the branch I supplied above only works for `linux-x86_64` so far. But it should be easy to port it to other platforms given a working example on the `linux-x86_64` platform.

Open to feedback. Thanks in advance!

Thanks,
Zhongming

**Comment by levitte** [comment]
I'm not sure what level you want to bring this to.  Do you want to replace the whole configuration and build file generation stuff, or do you simply want to be able to generate a `BUILD` instead of a `Makefile`?

Generating a `BUILD` would actually be quite easy, all you need is a `Configurations/BUILD.tmpl` that does what you want.  It does require embedded perl as it currently stands.  With that, configuration can be done like this:

```
BUILDFILE=BUILD ./config
```

If you want to replace all of Configure, the Configurations/ stuff, the test recipes and all that, I'm afraid we'll give you a more difficult time, 'cause that would require bazel to be as widely spread as Perl.  I'll just mention VMS as a measuring point...  if bazel can run on VMS, I'll be the first to be amazed.

**Comment by richsalz** [comment]
I think it's pretty clear that we're not going to do a replacement.  A bazel BUILD file might be a curiosity, but I don't see the point.  At any rate, I think we can close this issue.

**Comment by qzmfranklin** [comment]
Hi,

Thanks for the input.

I think the existing Configure and Configurations/ stuff is awesome. I have no intention for this `BUILD` thing to be a replacement. Only wanted to provide people who want to build openssl with Bazel a working sample `BUILD` to start with. Initially the BUILD file may only be on one or two platforms. But the list of supported platforms could be expanded with community effort.

@levitte : There is a pretty steep learning curve for people who do not know the openssl perl scripts deeply enough to Bazelise openssl using the existing perl scripts. And the perl scripts and templates for the `BUILD` file need to be carefully maintained and expanded to support other platforms. The sample BUILD file I provided is an approach that only requires parsing the build log (via `./config && make build_libs`) and is fully automated apart from the generation of the build log itself. The same approach could be very well extended to any platform that openssl already builds on.

Last, I am aware that Bazel supports a very limited set of platforms compared to that of openssl. Not advocating for adding full support outright. It could be a long term effort whose inception might be one or two commonly used platforms.

In any case, thanks a lot for the input and discussion.

**Comment by rpwoodbu** [comment]
I'd like to ask you to take another look at supporting Bazel. It would be helpful to Bazel-based projects that depend on openssl. There's no desire to replace your existing build system, but simply to teach it a new trick.

Bazel is highly desirable for being hermetic and deterministic. Therefore dependencies are best built from source instead of depending on pre-built libraries. But, of course, Bazel has to know _how_ to build dependencies, which is a significant hurdle to adoption.

Bazel has some great facilities for referring to external projects. It is therefore useful for the upstream project to offer their own BUILD file. For most upstream projects, this would be a notable maintenance burden, since they aren't switching to Bazel themselves, and would have to maintain it in parallel. But openssl is in a better position due to the fact that your Makefiles are generated by your own scripts in a templated fashion (as @levitte points out). It would definitely be a boon to the Bazel community for this fundamental library to have a provision for a BUILD file.

If the facility for generating a BUILD file were included upstream, Bazel-based projects could simply generate that manually and "bolt it on" like so:

    new_git_repository(
        name = "openssl",
        remote = "https://github.com/openssl/openssl",
        commit = "$COMMIT_ID",
        build_file = "$PATH_TO_BUILD_FILE",
    )

They would then simply refer to `openssl` as a "dep" in any build rule that uses it. That's it. The downloading, authentication, and build all happen automatically. They can build with different compiler flags, or different compilers, or even do multi-platform cross-compilation, all without fiddling with the openssl build or any other dependency. That's pretty powerful.

More advanced projects could get around the manual step of generating your BUILD file and committing into their source tree with a little clever Skylark coding (see example [here](https://stackoverflow.com/questions/38358504/can-i-generate-a-build-file-in-bazel)). This would make updating openssl as easy as changing the commit ID.

Note: I am the author of [Mosh for Chrome](https://github.com/rpwoodbu/mosh-chrome), which uses Bazel and openssl, and would definitely enjoy this level of integration.

**Comment by levitte** [comment]
> They would then simply refer to openssl as a "dep" in any build rule that uses it. That's it. The downloading, authentication, and build all happen automatically. They can build with different compiler flags, or different compilers, or even do multi-platform cross-compilation, all without fiddling with the openssl build or any other dependency. That's pretty powerful.

In all of this, where and when would configuration happen?  Depending on the exact platform, things like global C flags differ, so some file with variables would need to be generated before bazel comes into play, right?  I'm not sure how that would happen in the flow you talk about.

**Comment by levitte** [comment]
At this point, I think it's clear that this isn't something that's going to be done or even initiated by the @openssl team for now, for a very simple reason: we lack bazel competence.  I've skimmed through the bazel docs, and I have more questions that answers, and frankly don't think my time should be spent too much more on this.

So tell you what, if someone wants to make an attempt at doing a BUILD generator and whatever's needed to smoothly integrate OpenSSL in other bazel based projects, by all means!  I'd say that the best way to publish something like that for general consumption would be on [our wiki](https://wiki.openssl.org).
If I can assist with the template itself (and perl), I'm available by email...  I know those parts inside and out.

**Comment by rpwoodbu** [comment]
@levitte That's totally fair. I wouldn't expect you to take this on yourself. I was just hoping you'd embrace a contribution, and it sounds like you would. Getting it on the wiki seems like a reasonable compromise; I hope that's sufficiently discoverable.

@qzmfranklin Since you were able to make a proof-of-concept Bazel config, do you think you could take on the task of seeing if it could be generated using their shell scripts? Ahead of that, perhaps your existing work could be published on their wiki. But I think, for continuing maintenance purposes, for the meat of it to be constructed from their scripts.

@levitte Re your question about configuration: My thinking is that the configuration would happen just as it does today, and the BUILD files that are generated would reflect that configuration. However, it would be possible at build-time for the user to alter the flags (e.g., to build with symbols, TSAN, etc.), overriding the configuration. (I say this without having looked at how openssl is configured.)

**Comment by qzmfranklin** [comment]
@rpwoodbu Thanks. What you said is exactly what I was hoping to do but was unable to clarify earlier. I will post the existing work to wiki to help form the basis. And I will try to understand the perl scripts to start building a genuine Bazel BUILD file generator with the help of experts such as @levitte and maybe more.

@levitte Thanks very much for all your nice input and the attitude of embracing a contribution. Very much appreciated. Agree with rpwoodbu in every aspect, i.e., a) the existing perl scripts will be used to form the basis for any Bazel generator that is to be conceived, b) it is not going to fall on any single person but more likely to be a team effort of people with different expertise, and c) I would be happy to volunteer to add at least the initial sample to the openssl wiki.

**Comment by levitte** [comment]
Cool.  Keep me in the loop, I'm interested to see how this evolves.

**Comment by rpwoodbu** [comment]
Would it be appropriate to reopen this bug and assign to @levitte?

**Comment by richsalz** [comment]
No becuase the end result is not currently planned to be in the release, but rather a page on the wiki.

**Comment by qzmfranklin** [comment]
Just a quick note, I just sent an email to wiki-support@openssl.org requesting a wiki account. Would appreciate it if that could be processed quickly.

**Comment by mpictor** [comment]
@qzmfranklin did you ever get a wiki account or create a page? A quick wiki search for `bazel` didn't turn anything up.

**Comment by mikelikespie** [comment]
@qzmfranklin Not sure if this is useful to you, but appears there's a branch of boringssl w/ a  bazel build file. https://github.com/google/boringssl/tree/master-with-bazel Seems to work out of the box for me, even as an external project

**Comment by ccbrown** [comment]
In case anyone comes across this hoping for a Bazel build, I just put together a quick one that works fine for Linux and macOS:

BUILD:

```python
config_setting(
    name = "darwin",
    values = {
        "cpu": "darwin_x86_64",
    },
)

cc_library(
    name = "crypto",
    hdrs = glob(["include/openssl/*.h"]) + ["include/openssl/opensslconf.h"],
    srcs = ["libcrypto.a"],
    includes = ["include"],
    linkopts = select({
        ":darwin": [],
        "//conditions:default": ["-lpthread", "-ldl"],
    }),
    visibility = ["//visibility:public"],
)

cc_library(
    name = "ssl",
    deps = [":crypto"],
    hdrs = glob(["include/openssl/*.h"]) + ["include/openssl/opensslconf.h"],
    srcs = ["libssl.a"],
    includes = ["include"],
    visibility = ["//visibility:public"],
)

genrule(
    name = "openssl-build",
    srcs = glob(["**/*"], exclude=["bazel-*"]),
    outs = [
        "libcrypto.a",
        "libssl.a",
        "include/openssl/opensslconf.h",
    ],
    cmd = """
        OPENSSL_ROOT=$$(dirname $(location config))
        pushd $$OPENSSL_ROOT 
            ./config
            make
        popd
        cp $$OPENSSL_ROOT/libcrypto.a $(location libcrypto.a)
        cp $$OPENSSL_ROOT/libssl.a $(location libssl.a)
        cp $$OPENSSL_ROOT/include/openssl/opensslconf.h $(location include/openssl/opensslconf.h)
    """,
)
```

WORKSPACE (If you're wanting to add this as an external dependency to your project.):

```python
new_http_archive(
    name = "openssl",
    url = "https://github.com/openssl/openssl/archive/OpenSSL_1_1_0h.tar.gz",
    sha256 = "f56dd7d81ce8d3e395f83285bd700a1098ed5a4cb0a81ce9522e41e6db7e0389",
    strip_prefix = "openssl-OpenSSL_1_1_0h",
    build_file = "third-party/openssl/BUILD",
)
```

Obviously it'd be much better if it used Bazel to compile instead of the OpenSSL build system, but it works as a stop-gap.

**Comment by levitte** [comment]
That could be added to our [wiki](https://wiki.openssl.org/)

**Comment by terrisgit** [comment]
I was able to get this working but when trying to use it to build with https://github.com/eclipse/paho.mqtt.c, I ran into errors with using brackets instead of quotes in the openssl include files such as <openssl/ssl.h> . It's far easier to install openssh on OSX or libssl-dev on Linux.

**Comment by eaigner** [comment]
@ccbrown and how would you invoke this build? If I run `@openssl//:crypto` it builds nothing. Where is the dependency to `build-openssl`?

**Comment by eaigner** [comment]
For anyone interested, I fixed the dependency by adding

    data = [":openssl-build"],

to the `crypto` cc_library target.

**Comment by jsharpe** [comment]
Dropbox have just open sourced their python bazel build tools which includes perl scripts to generate the BUILD files:
https://github.com/dropbox/dbx_build_tools/tree/master/thirdparty/openssl

**Comment by dev-guy** [comment]
We are closing in on a better solution. https://github.com/bazelbuild/rules_foreign_cc/issues/337#issuecomment-582500380

**Comment by terrisgit** [comment]
We finally got it working with rules_foreign_cc which is much more maintainable. https://github.com/bazelbuild/rules_foreign_cc/issues/337

**Comment by 372046933** [comment]
> In case anyone comes across this hoping for a Bazel build, I just put together a quick one that works fine for Linux and macOS:
> 
> BUILD:
> 
> ```python
> config_setting(
>     name = "darwin",
>     values = {
>         "cpu": "darwin_x86_64",
>     },
> )
> 
> cc_library(
>     name = "crypto",
>     hdrs = glob(["include/openssl/*.h"]) + ["include/openssl/opensslconf.h"],
>     srcs = ["libcrypto.a"],
>     includes = ["include"],
>     linkopts = select({
>         ":darwin": [],
>         "//conditions:default": ["-lpthread", "-ldl"],
>     }),
>     visibility = ["//visibility:public"],
> )
> 
> cc_library(
>     name = "ssl",
>     deps = [":crypto"],
>     hdrs = glob(["include/openssl/*.h"]) + ["include/openssl/opensslconf.h"],
>     srcs = ["libssl.a"],
>     includes = ["include"],
>     visibility = ["//visibility:public"],
> )
> 
> genrule(
>     name = "openssl-build",
>     srcs = glob(["**/*"], exclude=["bazel-*"]),
>     outs = [
>         "libcrypto.a",
>         "libssl.a",
>         "include/openssl/opensslconf.h",
>     ],
>     cmd = """
>         OPENSSL_ROOT=$$(dirname $(location config))
>         pushd $$OPENSSL_ROOT 
>             ./config
>             make
>         popd
>         cp $$OPENSSL_ROOT/libcrypto.a $(location libcrypto.a)
>         cp $$OPENSSL_ROOT/libssl.a $(location libssl.a)
>         cp $$OPENSSL_ROOT/include/openssl/opensslconf.h $(location include/openssl/opensslconf.h)
>     """,
> )
> ```
> 
> WORKSPACE (If you're wanting to add this as an external dependency to your project.):
> 
> ```python
> new_http_archive(
>     name = "openssl",
>     url = "https://github.com/openssl/openssl/archive/OpenSSL_1_1_0h.tar.gz",
>     sha256 = "f56dd7d81ce8d3e395f83285bd700a1098ed5a4cb0a81ce9522e41e6db7e0389",
>     strip_prefix = "openssl-OpenSSL_1_1_0h",
>     build_file = "third-party/openssl/BUILD",
> )
> ```
> 
> Obviously it'd be much better if it used Bazel to compile instead of the OpenSSL build system, but it works as a stop-gap.


Got 
```
Error in genrule: rule openssl-build has file libcrypto.a as both an input and an output
```
