### ISSUE TITLE
SSL error with sign-file

### ISSUE THREAD

**Issue by farika** [openssl/openssl#3876]
Good evening,
I try to sign my nvidia drivers so that they work with secureboot.
I created my X509 keys following the redhat guide: https://access.redhat.com/documentat...es-for-secure- Boot.html. I used the example configuration file for X509.
My key is well enrolled in my UEFI.

To facilitate my task I then use the following very interesting script:
https://github.com/aneesh-neelam/UEF...-signtool-sign

The files are well signed but i have some weird errors :
At main.c:319:
- SSL error:0200B015:system library:fread:Is a directory: crypto/bio/bss_file.c:154
- SSL error:20082002:BIO routines:file_read:system lib: crypto/bio/bss_file.c:155
At main.c:365:
- SSL error:0200B015:system library:fread:Is a directory: crypto/bio/bss_file.c:154
- SSL error:20082002:BIO routines:file_read:system lib: crypto/bio/bss_file.c:155
sign-file: /lib/modules/4.11.8-200.fc25.x86_64/: Is a directory

What is bio ? 

These errors are not blocking file signature but i try to understand.

Thanks for your help

**Comment by richsalz** [comment]
I understand your frustration.  This is not an OpenSSL issue, but rather the documentation of the tools that tell you how to use OpenSSL to generate and/or sign keys.  BIO is the basic-I/O abstraction that OpenSSL uses.  I suggest you figure out exactly which program is failing, and contact that support list or repo.

My guess, knowing nothing other than the error mesages, is that you are giving a directory rather than a filename for your contents.

Good luck.  I'm closing this.
