### ISSUE TITLE
OpenSSL 1.1.0f - SSL routines:ssl3_get_record:decryption failed or bad record mac

### ISSUE THREAD

**Issue by alvosec** [openssl/openssl#3916]
I'm keep getting that error, even though that I've tried to check 'every' little detail in order to make sure that it is not some kind of misconfiguration. 

Here is my full question: https://serverfault.com/questions/859987/im-getting-error-ssl3-get-recorddecryption-failed-or-bad-record-mac

So based on what I have done so far and error is keep coming I'm afraid that this issue is related to OpenSSL bug.

**Comment by alvosec** [comment]
I'm sorry to bother you, but we are still having issue on our production server and consequently many of our users are experiencing this trouble.

Could anybody help us regarding this issue?

**Comment by mattcaswell** [comment]
Errors like this "SSL routines:ssl3_get_record:length too short:../ssl/record/.." and "SSL routines:SSL3_GET_RECORD:block cipher pad is wrong" are indicative of a fairly low level problem. These should just not happen in normal operation. Did you compile OpenSSL yourself or are you using the stock OS provided version? If you compiled it yourself what config options did you use, and did you run the self-tests?

**Comment by alvosec** [comment]
No it was pre-compiled so it came with OS. I have tried many things but still no success, so I had in my mind that maybe this can be u bug in openssl.

Do you have any other idea of what can I try more in order to fix this issue?

**Comment by mattcaswell** [comment]
My suggestion would be to try compiling OpenSSL yourself and use that instead. That way we can know for sure what config options were used, and run the tests to make sure everything is working as expected.

**Comment by alvosec** [comment]
Will compiling OpenSSL require removing existing OpenSSL from OS, and is there any risk of doing that in a way that it can effect other services on the server? Thank you

**Comment by mattcaswell** [comment]
No, you can have multiple versions of OpenSSL installed at the same time in different locations. There is no need to remove the OS version (and in fact I would recommend against doing that). The main risk in having multiple instances is that an application picks up the wrong version of OpenSSL. Typically though if you have a custom OpenSSL installation it is in a separate location that the rest of the system doesn't know about. You have to explicitly tell the application to load its libraries from there (e.g. using LD_LIBRARY_PATH).

**Comment by alvosec** [comment]
Is there anything that can be done in order to solve this issue, before we start compiling OpenSSL from scratch. We are still seeing the same error;

`SSL Library Error: error:140940F4:SSL routines:ssl3_read_bytes:unexpected message`

After so many tries we are unable to make working properly. Any ideas? Thanks

**Comment by mattcaswell** [comment]
Your problem is unlikely to be with the SSL options given above. It appears to be something quite fundamental. You could try running an openssl s_server instance on your server and see if you can successfully connect to that. That might at least prove whether the openssl installation itself is sound or not.

One other thought - all the error messages you are seeing could be explained if the network stream is somehow being corrupted between the client and openssl. Are there any middleboxes or any other configuration that could do that?

**Comment by alvosec** [comment]
If I run:

`openssl s_server -accept 7569 -cert /etc/letsencrypt/live/als-0001/cert.pem -CAfile /etc/letsencrypt/live/als-0001/chain.pem -key /etc/letsencrypt/live/als-0001/privkey.pem`

and try to connect: `openssl s_client -connect localhost:7569`

everything it seems to work just fine.

Yes I'm running firewall and IDS (pfsense) in front of our server.

**Comment by alvosec** [comment]
One more question, if I compile new OpenSSL by running:

`curl https://www.openssl.org/source/openssl-1.0.2l.tar.gz | tar xz && cd openssl-1.0.1g && sudo ./config && sudo make && sudo make install`

and then: `ln -s /usr/local/ssl/bin/openssl /usr/bin/openssl`

how can I go back to original OpenSSL which is part of OS (in my case OpenSSL-1.1.0f)?

Can I use this one (1.0.2l) on `Ubuntu 14.04.5 LTS`?

**Comment by richsalz** [comment]
If you are using the vendor-supplied version, you should try contacting your vendor.

**Comment by dot-asm** [comment]
What I find amazing is how far can it go without asking most obvious questions. It was said "it's vendor-supplied", but who is vendor? Ubuntu 14 was mentioned, but at the same time it was asserted that we are looking at OpenSSL 1.1.0f... But Ubuntu 14 comes with 1.0.1f... [In the context it should be noted that anything below 1.0.2 is sole vendor's responsibility. In sense that they are responsible to tracking bugs and backporting fixes if such would be required. This means that if we are in fact talking about Ubuntu 14 and 1.0.1f, you will end up contacting your vendor no matter what happens here.]

Next obvious question which cipher is it that is failing? Can one reproduce failure with s_client -cipher same-cipher? Against localhost and from outside?

What is processor?

**Comment by alvosec** [comment]
My bad, now it's clear to me. As for using -cipher it fails on any chosen cipher, like:

Remotely: `openssl s_client -debug -connect server:443 -cipher AES256+EDH`

Error: `SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac:s3_pkt.c:535:`

From localhost:

`openssl s_client -debug -connect localhost:443 -cipher AES256+EDH`

```
3073194560:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:../ssl/record/ssl3_record.c:469:
write to 0x8c02ee8 [0x8c0c5eb] (31 bytes => -1 (0xFFFFFFFF))
```
Processor: `model name	: Intel(R) Xeon(R) CPU           X3430  @ 2.40GHz`

**Comment by dot-asm** [comment]
Does reply mean that we are talking about Ubuntu 14 and bundled 1.0.1f? Something might be clear to you, but I'm still in the dark of wild guesses. But in either case. Once again, anything below 1.0.2 is vendors' responsibility. Though processor is old enough, there are no processor-specific fixes that would be essential. Secondly, since openssl s_client always works against openssl s_server, and apparently never against application, one has to draw conclusion that problem ought to be with interfacing of the application with openssl shared libraries. And here comes second boundary of responsibility, we can't possibly trouble-shoot it for you, you're pretty much on your own. Apache 2.4.27 was mentioned. But Ubuntu 14 comes with 2.4.7 (16 with 2.4.18). So that one can as well ask where does 2.4.27 binary come from, how was it (or more specifically mod_ssl) compiled... But once again, these are questions you should ask in first hand yourself...

**Comment by alvosec** [comment]
Yeah you were right, I had to downgrade my Apache to 2.4.7 and now everything works just fine. Thank you very much for your help.

**Comment by dot-asm** [comment]
It's not like there are irreconcilable incompatibilities between Apache 2.4.27 and OpenSSL 1.0.1f but they have to be built "right". And that's what Linux vendors do, or have to do to call themselves ones. However, definition of "right" falls beyond this forum. Which means that this case is resolved as non-OpenSSL problem. Cheers.
