### ISSUE TITLE
Server tries to call SSL_clear() return "SSL clear internal error" after client sent unknown CA.

### ISSUE THREAD

**Issue by wiki-vv** [openssl/openssl#3945]
Using the openssl-1.0.2j, after client returns unknown CA alert, server tries to call SSL_clear() and returns internal error.
   
1. The reason may exist in below code:

- s3_srvr.c: ssl3_accept()
```
 case SSL3_ST_SR_CLNT_HELLO_C:
        s->shutdown = 0;
        ret = ssl3_get_client_hello(s);
        if (ret <= 0)
            goto end;
        s->renegotiate = 2;
        s->state = SSL3_ST_SW_SRVR_HELLO_A;
        break;
```
After receive the client hello, set the renegotiate value to 2.
And send the server hello to to client.

- ssl_lib.c: SSL_clear()
```
    if (s->renegotiate) {
        SSLerr(SSL_F_SSL_CLEAR, ERR_R_INTERNAL_ERROR);
        return 0;
    }
```
Server receives client unknow CA alert and tries to call SSL_clear().
Check the s->renegotiate and return internal error. 

2. PCAP trace:
![image](https://user-images.githubusercontent.com/13937077/28252957-43b201c2-6a52-11e7-95d4-52c1c2d43943.png)

3. Suggest fix:
Remove s->renegotiate check in SSL_clear.

4. Other reference:
https://boringssl-review.googlesource.com/c/4823/

Thanks,
Wiki

**Comment by davidben** [comment]
Re point 4, note the commit message in that change mentions the `SSL_clear` calls in the handshake state machine which are "since gone". That is referring to https://boringssl-review.googlesource.com/c/2436/, not a change in OpenSSL. (I don't know off-hand if OpenSSL still calls `SSL_clear` within the handshake.)

I believe we also since noticed some code that removing those `SSL_clear`s broke, though I think that code and the in-handshake `SSL_clear` calls were clearly in error and we ultimately opted to fixing that code. But it does mean that OpenSSL may not be able to follow the same path without backwards compatibility woes.

**Comment by wiki-vv** [comment]
@davidben Thanks for your clarifying.
