### ISSUE TITLE
CVE-2014-3571 fix cripples reading DTLS handshake packet unless read_ahead is not 0

### ISSUE THREAD

**Issue by mcgitty** [openssl/openssl#397]
Branch OpenSSL_1_0_0-stable: https://github.com/openssl/openssl/commit/bf6fa208b5c081c041f267c4c0352c686fa8d8a5

The 2 lines added to s3_pkt.c prevents the reading of the packet body after the DTLS header. The call stack looks like this (using openssl-1.0.0s):

>	ssleay32.dll!ssl3_read_n(ssl_st * s=0x01bcdaf8, int n=0x0000000d, int max=0x00004150, int extend=0x00000000)  Line 141	C
 	ssleay32.dll!dtls1_get_record(ssl_st * s=0x01bcdaf8)  Line 590 + 0x1a bytes	C
 	ssleay32.dll!dtls1_read_bytes(ssl_st * s=0x01bcdaf8, int type=0x00000016, unsigned char * buf=0x01e1fc28, int len=0x0000000c, int peek=0x00000000)  Line 823 + 0x9 bytes	C
 	ssleay32.dll!dtls1_get_message_fragment(ssl_st * s=0x01bcdaf8, int st1=0x00002111, int stn=0x00002112, long max=0x00004000, int * ok=0x01e1fd30)  Line 856 + 0x19 bytes	C
 	ssleay32.dll!dtls1_get_message(ssl_st * s=0x01bcdaf8, int st1=0x00002111, int stn=0x00002112, int mt=0x00000001, long max=0x00004000, int * ok=0x01e1fd30)  Line 480 + 0x19 bytes	C
 	ssleay32.dll!ssl3_get_client_hello(ssl_st * s=0x01bcdaf8)  Line 838 + 0x24 bytes	C
 	ssleay32.dll!dtls1_accept(ssl_st * s=0x01bcdaf8)  Line 269 + 0x9 bytes	C
 	ssleay32.dll!SSL_accept(ssl_st * s=0x01bcdaf8)  Line 927 + 0xf bytes	C

Function dtls1_get_record(SSL *) in d1_pkt.c makes 2 calls to ssl3_read_n(), one in line 590 to read the DTLS header to get the size of the body:

    n = ssl3_read_n(s, DTLS1_RT_HEADER_LENGTH, s->s3->rbuf.len, 0);

When s->read_ahead is 0, it will only read the header into s3->rbuf, and after the head is consumed, s3->rbuf.left is 0.

The 2nd call is in d1_pkt.c line 651 to read the body (the last parameter 'extend' is 1):

    n = ssl3_read_n(s, i, i, 1); /* extend = 1 */

In line 146 of s3_pkt.c, variable 'left' will get 0. Then line 186 and 187 for CVE-2014-3571 will return an empty packet body:

        if (left == 0 && extend)
            return 0;

You may avoid this if you set s->read_ahead to 1, but that contradicts the "NOTES" section of

  https://www.openssl.org/docs/man1.0.1/ssl/SSL_CTX_set_read_ahead.html

**Comment by mattcaswell** [comment]
This is a known bug in OpenSSL 1.0.0. See https://rt.openssl.org/Ticket/Display.html?id=3657 (username=guest/password=guest). This has been fixed in OpenSSL 1.0.1+ but 1.0.0 and 0.9.8 are nearing End Of Life (at the end of this year) and are currently only receiving security fixes (see https://www.openssl.org/policies/releasestrat.html). As this is not a security fix it does not qualify.

The documentation that you refer to is the 1.0.1 specific version and the NOTES are correct for that version where this bug has been corrected (the documentation was written specifically in response to this bug).

The workaround for 1.0.0 and 0.9.8 is to explicitly set read_ahead to 1.

Closing this issue.

Matt
