### ISSUE TITLE
 sensible default for RANDFILE for windows users

### ISSUE THREAD

**Issue by MetaMemoryT** [openssl/openssl#410]
It would be nice if RANDFILE was a sensible default for windows users so they wouldn't run into this error:

http://stackoverflow.com/questions/12507277/how-to-fix-unable-to-write-random-state-in-openssl

How about use %APPDATA%\Local\Temp on windows, it is already used by .ssh,

Is there any security considerations?  Should openssl explain where it is writing the random file?

**Comment by levitte** [comment]
Is that a location that exists in all Windows versions?  Is it a per user location?

Since %APPDATA% is the typical Windows / cmd syntax for environment variables and OpenSSL leans towards a more Unixly style, I'm going to assume that something like `${APPDATA}/Local/Temp` should work just as well, no?  Also, isn't there some other env var that denotes this location, such as, oh I dunno, %TEMP%?

Sorry if these are silly questions...  I'm much more Unix than Windows savvy.

**Comment by MetaMemoryT** [comment]
It exists in all relevant windows versions:

see this for usage:

http://stackoverflow.com/questions/3964124/how-to-get-the-appdata-folder-in-c

we won't need to use platform specific enviroment variable syntax, can just access this functionality directly from the win32 c api.

**Comment by mattcaswell** [comment]
Ping @levitte

**Comment by levitte** [comment]
The smartest would really be to make the std config file into a template, so the final result can adapt to the platform at hand.  That would simplify matters for VMS as well...  (it's currently handled with `VMS/VMSify-conf.pl` on VMS)

**Comment by levitte** [comment]
I'd like to hear opinions on my last comment.  Sorry if that was unclear...

**Comment by mattcaswell** [comment]
Seems like a good idea to me.

**Comment by levitte** [comment]
I'll see what I can do

**Comment by mattcaswell** [comment]
Fixed in commit 13c03c8d6. Closing.
