### ISSUE TITLE
"get_last_rtl_error" not defined

### ISSUE THREAD

**Issue by fractalb** [openssl/openssl#4120]
related to issue #4029.
"get_last_rtl_error" function is not defined but it is called inside "crypto/bio/b_sock.c" file

**Comment by richsalz** [comment]
Ping @levitte , @kroeckx who worked on this?

**Comment by mattcaswell** [comment]
Ping @levitte.

**Comment by mattcaswell** [comment]
Ping @levitte

**Comment by levitte** [comment]
The code was added in 27f172d9a3f3ec9901439b4823c95788598fa367, and refers to [rt-2275](https://rt.openssl.org/Ticket/Display.html?id=2275) (login as user "guest" with same password to view).  The commit is exactly the patch that was originally provided, so it seems the original patch was equally incomplete.

I have no idea what to do with this.  We could reverse the commit in question, or someone will have to write `get_last_rtl_error`, or maybe we should just use `errno` directly.  That last option actually seems reasonable, because the only reason for `get_last_rtl_error` would be to provide for Windows, but since Windows doesn't seem to have `fcntl` (please correct me if I'm wrong), the section of code where `get_last_rtl_error` is used doesn't seem to be for Windows.  I'll try a PR that does exactly that.

**Comment by levitte** [comment]
I had a last minute change of heart, and am implementing `get_last_rtl_error`.  However, I'm only implementing an `errno` based variant.  Someone else will have to provide a Windows implementation if need be (hopefully never)

**Comment by levitte** [comment]
@fractalb, if you're still around, it'd be nice if you could try out #6088

**Comment by fractalb** [comment]
I have been using that workaround for some time now.
It works. Thanks.
