### ISSUE TITLE
sys/time.h is guarded inconsistently

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#4271]
I had a quick look and `sys/time.h` isn't guarded consistently:

- `!defined(_WIN32)`
- `!defined(OPENSSL_SYS_VXWORKS) && !defined(OPENSSL_SYS_WIN32)`
- `defined(__unix) || defined(__unix__)`
- `!defined(OPENSSL_SYS_WINDOWS)`
- `defined(OPENSSL_SYS_UNIX)`

There are additional cases where the build system is doing the guarding (haiku.h, sparcv9cap.c).

A bit of a mess.

**Comment by levitte** [comment]
Actually, these ones are plain wrong:

* `defined(__unix) || defined(__unix__)`
* `defined(OPENSSL_SYS_UNIX)`

They should be changed to be similar to the others, i.e. exclude Windows only.

It's actually only pure pure luck that the VMS builds didn't bail out for the lack of definition of `struct timeval` in those files, and the luck comes like this in VMS' `sys/socket.h`:

``` C
/*         
**  <sys/socket.h> is a header defined by XPG4 V2.  That specification
**  puts struct timeval, the FD* macros and select in <sys/time.h>.  
**  We define select here for compatibility with DEC C V4, unless
**  the program is in XPG4 V2 mode.
*/         
#if !defined __TIMEVAL && !defined _XOPEN_SOURCE_EXTENDED
#   define __TIMEVAL 1
#   if !defined _DECC_V4_SOURCE
        struct timeval {
           __time_t tv_sec;         /* seconds since Jan. 1, 1970 */
           long     tv_usec;        /* microseconds */
    };
#   else
        struct timeval {
           long     tv_sec;         /* seconds since Jan. 1, 1970 */
           long     tv_usec;        /* microseconds */
        };
#   endif
#endif
```

**Comment by dot-asm** [comment]
> haiku.h

Just in case for reference. Note that you won't find explicit `#include <haiku.h>` anywhere. It's included first-most through command line in Configuration/50-haiku.conf. It's a kludge that works around header position sensitivity on Haiku. Basically choice was between #ifdef spaghetti and this `-include \$(SRCDIR)/os-dep/haiku.h` and latter was found least invasive.

> A bit of a mess

Effectively unavoidable since we are supporting that many platforms. As already mentioned elsewhere, we should keep in mind that it would be more than appropriate to switch to own OS-neutral time type. This wouldn't make libcrypto code completely free of mess (because we would still have to convert the said OS-neutral time to OS-specific), but it would make it easier to use from application (and libssl). But it can't be done in minor release. [Well, it can if it's done with parallel interfaces. At least one should be able to do it between libcrypto and libssl. It might be worth considering. Specifically in minor release...]

**Comment by paulidale** [comment]
The _bit of mess_ comment was aimed at the hodgepodge of different guards not what has to be done.

I'd be happy with a consistent guard (perhaps in an internal header) but our own time type might be a better fix.

**Comment by paulidale** [comment]
How do folks feel about an internal/timeval.h header which contains the preprocessor magic done consistently and the timeval source from e_os.h ?  Am I breaking things too fine?

**Comment by levitte** [comment]
I would think that internal/time.h should suffice

**Comment by dot-asm** [comment]
> internal/time.h

On related note in https://github.com/openssl/openssl/pull/4246#issuecomment-325015970 I argue that this kind of naming would be acceptable only under certain circumstances. And conditions are not really met here. Indeed, time.h is mentioned in C language standard and is not specified to define timeval.

**Comment by levitte** [comment]
Thing is, if we create a header file for *one* structure, we're setting a precedent which is kinda silly...  and which will obviously include something that mimics sys/time.h anyway.

Ah, or are you saying we should make it internal/sys/time.h?  Or perhaps internal/sys-time.h...  I would prefer the latter, actually.

**Comment by dot-asm** [comment]
> How do folks feel about an internal/timeval.h header

Note that there is kind of irreconcilable conflict. Normally headers are viewed to be position-insensitive, and I bet that this is your intention even here :-) But trouble is that timeval declaration can't be made position-insensitive on Windows, because timeval is defined in winsock[2].h, which in turn position-sensitive [in relation to windows.h]. This means that there ought to be some kind of *rule* for positioning internal/timeval.h. But in such case wouldn't we better off if there was only one position-sensitive header? And in such case timeval should probably be in this one? (Currently it's e_os.h, and no, I haven't formed my opinion about sockets.h).

**Comment by dot-asm** [comment]
> Thing is, if we create a header file for one structure, we're setting a precedent which is kinda silly...

I absolutely agree, and it's kind of discussed later. I mean the part that e_os.h is too big, has to be broken to pieces, *but* it would be a mistake to break it into too many. So that in a sense suggestion is not only to instantiate and follow "internal/standard-looking.h should include corresponding standard header and not go beyond what it entails" rule, but even to use it as *deterrent* for creating too many internal "portability" headers.

**Comment by levitte** [comment]
It sounds more and more like the "over-relianse on e_os.h" wasn't such an over-relianse after all...  at least in the Windows case, as we need to include windows.h or winsock[2].h+windows.h more or less everywhere anyway...

I could easily go for keeping the "over-relianse on e_os.h" for the sake of Windows, and move everything away but the inclusion of those Windows headers, having the rest in internal header files that are geared for all other platforms (guarded with anti-Windows checks).  I find this solution disgusting, but it seems more and more that this would be the smoothest way to go.

**Comment by dot-asm** [comment]
> It sounds more and more like the "over-relianse on e_os.h" wasn't such an over-relianse after all...

Yes, it was. It had to be included for things that are not least OS-specific, blake2 and des being couple of latest examples. Once again, it should be "used in "exceptional" situations to resolve *real* system dependencies." Nor is it directly appropriate to use it in apps, which should set an example of how to use public headers alone. [Yes, it means that *some* of the apps/\*.c would have to include winsock[2].h and windows.h, but it would be more appropriate if they do it themselves, without relying on e_os.h.]

> I could easily go for keeping the "over-relianse on e_os.h" for the sake of Windows, ...

I wouldn't be surprised if I soon find myself arguing that splitting internal/sockets.h was a mistake. As just said, we are better off if we have only *one* position-sensitive header [and so far it was e_os.h]... Yet, it doesn't mean that there is *no* over-reliance on e_os.h. Because there really *is*.

**Comment by paulidale** [comment]
I suggested the new file name based on your earlier comment @dot-asm 
It seems like a local type definition might be better than a tiny header file.

At the least I'll clean up the guards so they are consistent.

**Comment by dot-asm** [comment]
> I suggested the new file name based on your earlier comment @dot-asm

Well, it's like that thing you can't really define, but point it out when you see it. I mean the comment was rather invitation for discussion than call for immediate action. And it shouldn't come as surprise that some responses to immediate actions can feel contradicting initial comment. We seem to agree that it's a mess, but we don't have ready answer how to solve it (and probably can't come up with one using *this* communication platform), so it will take several tries and possibly errors...

**Comment by paulidale** [comment]
Agreed.  I might just clean the guards.  There isn't a compelling reason to pull them all together header.

Is:
```
#if !defined(_WIN32) && !defined(OPENSSL_SYS_VXWORKS) && !defined(OPENSSL_SYS_WIN32) && !defined(OPENSSL_SYS_WINDOWS)
```
The correct guard?  Can I drop any of the Windows checks?  I'm not a Windows person and am fairly clueless as to how things work in the forbidden land :)

**Comment by levitte** [comment]
`OPENSSL_SYS_WINDOWS` is defined in `e_os2.h` for any Windows version, so as long as that header file is included, you can drop all other Windows guards.

`OPENSSL_SYS_WIN32` and `OPENSSL_SYS_VXWORKS` are defined in `opensslconf.h`, so as long as that header file is included, you can drop all other guards (but then, you won't detect Win64 correctly).

`_WIN32` is defined by the compiler...  I think also on 64-bit?  @dot-asm can confirm.

For minimal dependency, I'd make sure to include `opensslconf.h` and have this guard:

``` C
#if !defined(_WIN32) && !defined(OPENSSL_SYS_VXWORKS)
```

**Comment by dot-asm** [comment]
> _WIN32 is defined by the compiler... I think also on 64-bit? @dot-asm can confirm.

Yes, _WIN32 is defined by *all* compilers targeting Windows, 32- or 64-bit, "real" or embedded. Do note that "all compilers" and not "Microsoft compilers", it's not a coincidence. Then in addition to that you get _WIN64 if compiler targets 64-bit Windows.

> OPENSSL_SYS_VXWORKS

Actually VxWorks compilers also pre-define a macro, __vxworks. And in case we find a platform that doesn't bother to distinguish itself with pre-define, I'd argue that we would be better off [in long run] defining one of own choice at command line through Configurations/\*.cf.

**Comment by levitte** [comment]
> I'd argue that we would be better off [in long run] defining one of own choice at command line through Configurations/*.cf.

So, appropriate `sys_id` entry that becomes the macro `OPENSSL_SYS_$target{sys_id}`.  This macro is stored in `opensslconf.h`, not on the command line, we can surely live with that, right?

**Comment by paulidale** [comment]
PR in #4312

**Comment by dot-asm** [comment]
>>    I'd argue that we would be better off [in long run] defining one of own choice at command line through Configurations/*.cf.

First of all, quote is truncated, and full quote has an if clause: "[*if*] we find a platform that doesn't bother to distinguish itself with pre-define." And it's a big "if", as I haven't seen such platform, so it would be rather rare *exception*. Now, with this in mind, what is more appropriate/fair/elegant? To treat all curent platforms *as if* they were that one rare exception? Or let that one exception be an exception?

> So, appropriate sys_id entry that becomes the macro OPENSSL_SYS_$target{sys_id}. This macro is stored in opensslconf.h, not on the command line, we can surely live with that, right?

I'd say no. Beside the exception argument above, this particular approach has contradiction. Our API aims to provide OS-*neutral* interface. This formally means that public headers should not bear any reference to OS. [Ideally they shouldn't even be compiler-specific, but they definitely shouldn't be OS-specific, as all OS specifics should really be private matter of libcrypto/libssl.] And ... opensslconf.h is a public header. In fact, I'd even suggest to take it one step further saying that in long run we should aim for ... removal of opensslconf.h. Or at least purging its portions. Let's consider first entry for example. #ifndef OPENSSL_NO_ARIA. Does *application* actually have to know this? Wouldn't it be more appropriate if application probed for its availability at run time? Can it do it *now*? Yes! Instead of linking to EVP_aria_\* it could simply EVP_get_cipherby\*. ... Does application need to know about NON_EMPTY_TRANSLATION_UNIT? BN_LLONG and stuff?

**Comment by t-j-h** [comment]
Ideally there should be *no* difference at all between the public header files use for any release of OpenSSL on a cross-platform basis - i.e. nothing in the public header files for a release should vary across a platform (outside of 'include' differences) - and that does mean a 32-bit and a 64-bit set of headers on the same platform should be able to be identical. That is what I think the aim should be.
