### ISSUE TITLE
Unable to decode negative serial number

### ISSUE THREAD

**Issue by hsheth2** [openssl/openssl#4320]
OpenSSL 1.1.0f is unable to decode a certificate:
```
$ openssl x509 -inform pem -in '1914312.crt' -noout -text
unable to load certificate
140735234723840:error:0D0E20DD:asn1 encoding routines:c2i_ibuf:illegal padding:crypto/asn1/a_int.c:187:
140735234723840:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:609:Field=serialNumber, Type=X509_CINF
140735234723840:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:609:Field=cert_info, Type=X509
140735234723840:error:0906700D:PEM routines:PEM_ASN1_read_bio:ASN1 lib:crypto/pem/pem_oth.c:33:
```

Older versions of OpenSSL were able to handle this certificate correctly:
```
$ /usr/bin/openssl version
OpenSSL 0.9.8zh 14 Jan 2016
$ /usr/bin/openssl x509 -inform pem -in '1914312.crt' -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
             (Negative)2a:2a:ba:c2:cd:b1:6a:74:80:3a:2f:b8:88:24:42
        Signature Algorithm: sha1WithRSAEncryption
[...]
```

For reference, the certificate in question can be found online: https://crt.sh/?id=1914312.

**Comment by richsalz** [comment]
That certificate is not encoded properly.  Negative numbers aren't allowed so that if a number has the high-bit on, it must be preceeded by a leading zero byte so that it is not taken as a negative number.

Not sure what we should do here.

**Comment by hsheth2** [comment]
Yes, [RFC5280](http://www.ietf.org/rfc/rfc5280.txt) states that "The serial number MUST be a positive integer assigned by the CA to each certificate" in section 4.1.2.2. However, "Certificate users SHOULD be prepared to gracefully handle such certificates."

Maybe OpenSSL should try to handle this situation more gracefully, as was done in previous versions. If giving a decoding error is sufficient, then perhaps the error message should more clearly identify the cause of the error.

**Comment by snhenson** [comment]
The cause isn't just that the serial number is negative: OpenSSL will tolerate that as required by RFC5280 et al. The problem is that the ASN.1 Integer has an invalid encoding: there is illegal extra padding. OpenSSL used to tolerate this but doesn't any more. If you click on zlint in the link you get a similar error.

**Comment by hsheth2** [comment]
Interesting. Thank you for clarifying.

**Comment by Anthony-Mai** [comment]
I was reading @snhenson 's comment on illegal extra padding but initially could not understand what it was. Then I finally realized. The serial number in question is 16 bytes in big endian:
    FF D5 D5 45 3D 32 4E 95 8B 7F C5 D0 47 77 DB BE
There are a total of 128 bits, but the crt.sh web site says the value only has 118 bits. Here is what the leading bits look like:
      F   F        D    5  ...
 11111111 11010101 ..
A leading bit of 1 would indicate a 2's complement negative number. Note the first byte is all 1's. Removing the leading 8 bits of 1's would not change the value. Like wise padding more bytes of all 1 bits on the left would not change the value either. Same as FF and FFFFFFFF and FFFFFFFFFFFFFFFF are all representing -1. Thus the leading whole byte of all 1's is not necessary. Therefore it is considered illegal because we have to follow the minimum bytes representation rule.

Just to share what I discovered.

**Comment by yangyangtiantianlonglong** [comment]
hi, @snhenson 
my  error is 

> OpenSSL> version
OpenSSL 1.1.1a  20 Nov2018
OpenSSL> x509 -in enodeb.cer -inform DER -text -noout
unable to load certificate
139974830417728:error:0D0E20DD:asn1 encoding routines:c2i_ibuf:illegal padding:crypto/asn1/a_int.c:187:
139974830417728:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:627:Field=serialNumber, Type=X509_CINF
139974830417728:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:627:Field=cert_info, Type=X509
error in x509

 **asRFC5280 4.1.2.2，**
  Note: Non-conforming CAs may issue certificates with serial numbers
  that are negative or zero.  Certificate users SHOULD be prepared to
  gracefully handle such certificates.
1. My current version is OpenSSL1.1.1a, I will delete the following code.  and I want to be compatible with OpenSSL 0.9.8 version，It has no checksum for negative serial number. 
 **in file            a_int.c
        function   c2i_ibuf  
        line           186**
   `    if (pad && (neg == (p[1] & 0x80))) {
        ASN1err(ASN1_F_C2I_IBUF, ASN1_R_ILLEGAL_PADDING);
        return 0;
    }`
2.  According to your understanding, what behavior will this modification affect?

**Comment by yangyangtiantianlonglong** [comment]
@richsalz  hi，https://github.com/openssl/openssl/issues/4320#issuecomment-516754721
 Can you help with the above question?

**Comment by levitte** [comment]
The issue is still the same, that the serial number is not only a negative number, but a badly formed negative number.
