### ISSUE TITLE
Why am I asked to overwrite a MakeFile when compiling?

### ISSUE THREAD

**Issue by adamskiii** [openssl/openssl#438]
Hi!
When I try to compile openssl on Linux it stops at this point:

make[2]: Leaving directory `/home/Clients/openssl/openssl-1.0.2d/crypto/asn1'
making depend in crypto/pem...
make[2]: Entering directory `/home/Clients/openssl/openssl-1.0.2d/crypto/pem'
../../util/domd ../.. -MD gcc -- -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -D_GNU_SOURCE -D_REENTRANT -D_POSIX_C_SOURCE=199506 -DBN_DEBUG -DREF_CHECK -DCONF_DEBUG -DCRYPTO_MDEBUG -m64 -DL_ENDIAN -g -Wall -I.. -I../.. -I../modes -I../asn1 -I../evp -I../../include  -DOPENSSL_NO_DEPRECATED -DOPENSSL_NO_EC_NISTP_64_GCC_128 -DOPENSSL_NO_GMP -DOPENSSL_NO_IDEA -DOPENSSL_NO_JPAKE -DOPENSSL_NO_LIBUNBOUND -DOPENSSL_NO_MD2 -DOPENSSL_NO_RC5 -DOPENSSL_NO_RFC3779 -DOPENSSL_NO_SCTP -DOPENSSL_NO_SSL_TRACE -DOPENSSL_NO_SSL2 -DOPENSSL_NO_SSL3 -DOPENSSL_NO_STORE -DOPENSSL_NO_UNIT_TEST -- pem_sign.c pem_seal.c pem_info.c pem_lib.c pem_all.c pem_err.c pem_x509.c pem_xaux.c pem_oth.c pem_pk8.c pem_pkey.c pvkfmt.c
mv: try to overwrite `Makefile', overriding mode 0444 (r--r--r--)?

Does anyone know why it is asking me to overwrite this MakeFile ?

Thank you

**Comment by mattcaswell** [comment]
It looks like you are running `make depend`. The purpose of this is to update all of your Makefiles with updated dependencies based on config/Configure options that you have chosen. It copies your original Makefile to Makefile.save, creates an updated version Makefile.new, and finally mv's Makefile.new to Makefile, overwriting the original. In your case it seems you have set the Makefile to be read only which is why it is asking you if you want to overwrite it.
