### ISSUE TITLE
Setting s_client EHLO hostname

### ISSUE THREAD

**Issue by szepeviktor** [openssl/openssl#4422]
Seems like it is `openssl s_clinet -name $EHLO` but was designated `-smtphost $EHLO`

https://github.com/openssl/openssl/blob/master/apps/s_client.c#L669-L670

```c
{"name", OPT_SMTPHOST, 's',
"Hostname to use for \"-starttls lmtp\" or \"-starttls smtp\""},
```

Is it a typo?

**Comment by szepeviktor** [comment]
Was https://rt.openssl.org/Ticket/Display.html?id=2642#txn-48176

**Comment by mattcaswell** [comment]
I'm not sure I understand your point? What is the typo?

**Comment by szepeviktor** [comment]
`"name"`
I think it should be `smtphost`

**Comment by szepeviktor** [comment]
BTW it is not available in v1.0.2l

**Comment by InfoHunter** [comment]
Seems should be `smtphost`

**Comment by levitte** [comment]
Because we already have `-xmpphost` and that's documented, it would make sense to have `-smtphost` in the SMTP case (and because `-name` is undocumented, a rename would make a bit of sense).

On the other hand, it's absolutely ridiculous to have different options for what is conceptually the same thing regardless of protocol...  so if you ask me, `-name` makes more sense, and should be used with all protocols that can or must declare a host of some kind.  `-xmpphost` could be made a synonym...

**Comment by szepeviktor** [comment]
`-smtphost` is in the [commit above](https://github.com/openssl/openssl/commit/90899ae82e14ecbfbeac6fc47757470f9a0a9b80#diff-cc77fc65ccc025a6a3ca1cb7a4e844a6R73).
That is why I think `-name` is a typo.

**Comment by levitte** [comment]
That commit isn't part of our repo, so I assume it's part of a PR

**Comment by szepeviktor** [comment]
@richsalz Could you update us on the status of https://github.com/openssl/openssl/commit/90899ae82e14ecbfbeac6fc47757470f9a0a9b80#diff-cc77fc65ccc025a6a3ca1cb7a4e844a6 ? I am not able to find its origin.

**Comment by richsalz** [comment]
looks to be commit 9576545a in master.

**Comment by szepeviktor** [comment]
Thank you.
It looks like `OPT_SMTPHOST` is `-name` on the command line.

**Comment by richsalz** [comment]
Okay, the -name option is now implemented with that above commit.  Closing this issue.

**Comment by szepeviktor** [comment]
Thank you for fixing it.
