### ISSUE TITLE
Stack issues

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#4426]
There are a number of points raised in #4386 which shouldn't be swept under the carpet:

- Remove the argument checking at the start of many functions (`st == NULL` **and** `st->num < 0`)
- Setting the minimum allocation size `min_nodes` to something larger than _4_
- ~Postponing the allocation of `st->data` until something is added or an explicit reserve is issued.~
- Replacing the entire data structure with something more efficient.

**Comment by levitte** [comment]
> - Remove the argument checking at the stat of many functions (`st == NULL` **and** `st->num < 0`)

That's a change in behavior that's not acceptable before 1.2.0.

The rest should be fine to implement any time in 1.1.x

**Comment by dot-asm** [comment]
> That's a change in behavior that's not acceptable before 1.2.0.

Why? Is it reasonable to assume that there is code that *relies* on NULL being recognized as *legitimate* value for sk?

**Comment by levitte** [comment]
While that question may seem valid, the truth is that we don't know and therefore can't assume.  Looking through `crypto/stack/stack.c`, it's obvious that the functions were consistently made to allow that.  That makes it a legitimate value.
We might not agree with that implementation, but that's how it is now, and it's been like that since forever...  so yeah, I think it's reasonable to think that someone may rely on this behavior.

BTW, [`DEFINE_STACK_OF`](https://github.com/openssl/openssl/blob/master/doc/man3/DEFINE_STACK_OF.pod) hints at this behavior in the documentation of `sk_TYPE_num`

**Comment by paulidale** [comment]
Lazy allocation is happening in #4379

**Comment by paulidale** [comment]
I agree about the NULL checks.  The `st->num < 0` checks could go now since the stack functions don't produce this and the structure is opaque.  I still think it better to remove them both at the same time, i.e. 1.2 at the earliest.

**Comment by mattcaswell** [comment]
Given the last comment on this Issue. Is the milestone for this issue correct? Should it actually be 1.2 @paulidale?

**Comment by paulidale** [comment]
The `st->num < 0` checks have gone it appears.  The NULL checks are API changing so 1.2

**Comment by nhorman** [comment]
@paulidale this still an issue?

**Comment by nhorman** [comment]
Marking as inactive, to be closed at the end of 3.4 dev, barring further input

**Comment by paulidale** [comment]
There is stuff we could do to clean up our stack.
We might be better replacing the stack with more appropriate data structures.

Given nothing much has happened for six years, this might as well be closed.
