### ISSUE TITLE
TLSv1.3 early data and server name callback

### ISSUE THREAD

**Issue by tatsuhiro-t** [openssl/openssl#4496]
While debugging TLSv1.3 early data with picotls client, and OpenSSL s_server, I found that OpenSSL refuses early data if server name callback is not set in server side.

The location where early data is rejected is https://github.com/openssl/openssl/blob/2e8b5d75afaff7c9b75917b750f997dc82336fac/ssl/statem/extensions.c#L878

Since the default value of ret is SSL_TLSEXT_ERR_NOACK, and there is no code to handle the case when servername callback is not set, early data is rejected if servername callback is missing.

It looks like just changing default value of ret to SSL_TLSEXT_ERR_OK fixes this issue.

**Comment by kaduk** [comment]
Can you clarify what language in the draft specification supports your interpretation that this behavior should be allowed?  In section 4.6.1 of https://tools.ietf.org/html/draft-ietf-tls-tls13-21 we see that:

> Any ticket MUST only be resumed with a cipher suite that has the same
   KDF hash algorithm as that used to establish the original connection,
   and only if the client provides the same SNI value as in the original
   connection, as described in Section 3 of [RFC6066].

I claim that in the current OpenSSL architecture/API contract for SNI callback, the responsibility for ensuring this consistency lies in the application's callback, and so if there is no such callback OpenSSL can conclude that the required check is not being performed.  In that case, OpenSSL is correct to reject early data (and resumption entirely!) when no SNI callback is set.

**Comment by kaduk** [comment]
If there's no SNI in either connection, we can detect that entirely internally in the library, sure.  (I don't think we currently do anything like that, and expect the default SSL_TLSEXT_ERR_NOACK return value to apply.)
But we'd need to check ```s->session->ext.hostname``` for NULLness in ```init_server_name()``` and cache that for comparison in ```final-server_name()```, so I don't see that as a reason to change the default return value.

**Comment by mattcaswell** [comment]
Actually the bug seems to be that if the client sends SNI in the ClientHello establishing the initial session *and* server does not have callback set then it will always refuse early data. However if the client does not send SNI in the ClientHello establishing the session then it works.

**Comment by mattcaswell** [comment]
Possible fix (but needs a test):
````
diff --git a/ssl/statem/extensions.c b/ssl/statem/extensions.c
index f6a200fa18..5bfe2aad63 100644
--- a/ssl/statem/extensions.c
+++ b/ssl/statem/extensions.c
@@ -826,13 +826,17 @@ static int final_server_name(SSL *s, unsigned int context, int sent,
     int altmp = SSL_AD_UNRECOGNIZED_NAME;
     int was_ticket = (SSL_get_options(s) & SSL_OP_NO_TICKET) == 0;
 
-    if (s->ctx != NULL && s->ctx->ext.servername_cb != 0)
+    if (s->ctx != NULL && s->ctx->ext.servername_cb != 0) {
         ret = s->ctx->ext.servername_cb(s, &altmp,
                                         s->ctx->ext.servername_arg);
-    else if (s->session_ctx != NULL
-             && s->session_ctx->ext.servername_cb != 0)
+    } else if (s->session_ctx != NULL
+             && s->session_ctx->ext.servername_cb != 0) {
         ret = s->session_ctx->ext.servername_cb(s, &altmp,
                                        s->session_ctx->ext.servername_arg);
+    } else if (!sent) {
+        OPENSSL_free(s->session->ext.hostname);
+        s->session->ext.hostname = NULL;
+    }
 
     /*
      * If we're expecting to send a ticket, and tickets were previously enabled,
````

**Comment by kaduk** [comment]
That seems like a correct patch to include, though I'm not sure offhand whether it is an actual complete fix for any observable behavior.

**Comment by tatsuhiro-t** [comment]
Thanks.  I'm not aware that servername_cb still has such an important role.  I'll close my PR.
From the manual, the role of servername_cb is superseded by ClientHello callback.  Can I expect such migration happens in this code as well before 1.1.1 release?

I'm not sure it is really an application's responsibility to check the equality of SNI between the original connection and resumed handshake.  If I understand correctly, it requires an application to cache the association of original connection identifier and SNI in its own storage.  It is a bit huge burden just for 0-RTT.  Is there any possibility to include original SNI in a ticket, and check the equality in OpenSSL library?  It is much easier for an application perspective.  And it is actually what picotols does.  That changes ticket construction, but it is TLSv1.3 only, and there is no compatibility concern, no?

**Comment by kaduk** [comment]
I probably was not writing as clearly as could have yesterday, and may even have misunderstood some things.  However, I did write:

> In that case, OpenSSL is correct to reject early data (and resumption entirely!) when no SNI callback is set.

In particular, the TLS 1.3 spec does not place different requirements on SNI handling for "regular" resumption vs accepting early data, so it would be good to know whether @tatsuhiro-t is specifically seeing early-data rejection but successful resumption, or if resumption is also failing.

I'm not sure why I said that the SNI callback is responsible for checking consistency between the original connection and the resumption; that's something that we can (and do) do within the library, via ```s->session->ext.hostname```.

I still don't think that having final_server_name() default to returning SSL_TLSEXT_ERR_OK is correct, but adjusing the SSL_TLSEXT_ERR_NOACK handling (such as by clearing ```s->session->ext.hostname``` if SNI is not accepted) to allow the early data may be okay.

Anyway, sorry for saying crazy things and sending you down the wrong path.

**Comment by tatsuhiro-t** [comment]
Thank you for clarification. Without SNI callback in place in server, resumption still works in TLSv1.3.  Sending early data fails in client side.  Note that s_server does not set SNI callback by default.
Error writing early data

139691362264320:error:142120E7:SSL routines:tls_construct_ctos_early_data:inconsistent early data sni:ssl/statem/extensions_clnt.c:719:
139691362264320:error:141E7044:SSL routines:tls_construct_client_hello:internal error:ssl/statem/statem_clnt.c:1149:

**Comment by mattcaswell** [comment]
Fix in #4519

**Comment by tatsuhiro-t** [comment]
It looks like the issue still persists.  It might not be the same as the original.

```
$ openssl s_server -cert server.crt -key server.key -early_data -max_early_data 16384 -debug
Using default temp DH parameters
ACCEPT
read from 0x563cf11c7670 [0x563cf11ccc83] (5 bytes => 0 (0x0))
Error reading early data
shutting down SSL
CONNECTION CLOSED
ACCEPT
```

```
$ openssl s_client -connect localhost:4433 -sess_out session.txt -servername localhost -early_data a -sess_in session.txt
CONNECTED(00000003)
Error writing early data
140126441481472:error:142120E7:SSL routines:tls_construct_ctos_early_data:inconsistent early data sni:ssl/statem/extensions_clnt.c:719:
140126441481472:error:141E7044:SSL routines:tls_construct_client_hello:internal error:ssl/statem/statem_clnt.c:1149:
```

**Comment by mattcaswell** [comment]
Ok, I'll take a look.

**Comment by mattcaswell** [comment]
Hmmm. This seems to be working as designed - although the "internal error" bit in the error message is misleading. The problem is the use of the explicit "-servername localhost" flag. Actually, usually, there is no reason to use that flag in master. In master (not in 1.1.0), s_client will send SNI by default. It will set it to the host specified in the "-connect" flag *unless* it is asked to reuse a session (via -sess_in), in which case it will use the SNI associated with that session. If there is no SNI in the session (usually because the server didn't echo it back), then no SNI will be sent. You only need to explicitly use the "-servername" flag if you want to set it to something different to the default.

What is happening in this case is that you are creating a session initially - but s_server is not set up for SNI so it does not echo it back. Therefore the session you have created has no SNI associated with it. Normally s_client would then not send any SNI in that instance, however because you have used the explicit "-servername" flag it is forced to send it anyway. However you have *also* asked it to send early_data using that session. It is a condition of sending early_data that the SNI in the session, and the SNI in the ClientHello must match. They don't in this case, so s_client aborts.

**Comment by tatsuhiro-t** [comment]
Thanks for detailed explanation, and it explains everything I experienced.  I think this issue can be closed.

**Comment by kaduk** [comment]
davidben pointed out that the s_client behavior here doesn't really make sense.
That is, given that the server is permitted to not know anything about the session that s_client is attempting to resume, the extensions we send in the ClientHello must include everything that we would want if a full handshake was going to happen.  So, it probably makes more sense for s_client to ignore the ```-sess_in``` when considering what extensions to send (including SNI) than to try to duplicate it.  If the user asks for different settings than when the session was created, then it should be expected that the resumption would/could fail, of course, but in general it does not seem like the session input should be the source for anything in the ClientHello other than the session ID, since the client cannot expect a guarantee of resumption.
