### ISSUE TITLE
Annotate assembly files to indicate they do not require non-executable stacks

### ISSUE THREAD

**Issue by alex** [openssl/openssl#4575]
GCC/the linux ecosystem requires an annotation in `.S` files to indicate that they do not require an executable stack, otherwise GCC/as doesn't emit the right metadata for them to be noexec. Currently none of the assembly files (well, perl scripts which generate assembly files) in OpenSSL contain this annotation:

https://wiki.ubuntu.com/SecurityTeam/Roadmap/ExecutableStacks documents it.

As far as I can tell, all the linux distros work around this by providing the `-Wa,--noexecstack` incantation, but people who compile their own OpenSSL do not get these protections.

If OpenSSL included these annotations in its assembly files `.so`s produced would be automatically nostackexec.

**Comment by dot-asm** [comment]
> Currently none of the assembly files (well, perl scripts which generate assembly files) in OpenSSL contain this annotation

And the reason for that is obviously fact that OpenSSL assembly modules are not actually Linux-centric.  Beside Linux they compile on Solaris, BSD, MacOS X, Windows (though Windows don't actually belong in the list because of different calling convention)... As for -Wa,--noexecstack note that it's added by ./config script as result of probe if assembler supports it, so I suppose question is rather about cases when users don't use ./config. Is this it? I'd guess that one can argue that it would be appropriate to perform the probe in ./Configure instead...

**Comment by levitte** [comment]
#4674 is the PR that makes the change...  it does need a rebase, but otherwise I'd say it's good to go.

**Comment by dot-asm** [comment]
Addressed in #6174, that is replacement for #4674.
