### ISSUE TITLE
How to build only libcrypto.a (and not libssl.a)?

### ISSUE THREAD

**Issue by snap9** [openssl/openssl#4597]
There used to be a `make build_crypto` AFAIK.

But on OpenSSL 1.1, `build_crypto` seems to be gone.

What is the solution?

**Comment by kaduk** [comment]
Just "make libcrypto.so" (or libcrypto.a) directly -- the new build system produces a single global makefile that knows how to build everything.

**Comment by snap9** [comment]
@kaduk 

`make libcrypto.a` did not work:

    In file included from crypto/aes/aes_cbc.c:10:
    include/openssl/aes.h:13:11: fatal error: 'openssl/opensslconf.h' file not found

Just `make` however works just fine. The problem is I waste time building libssl.a

Any ideas?

**Comment by richsalz** [comment]
Sorry, no.  Perhaps post to the openssl-users mailing list; see https://mta.openssl.org for details.

**Comment by kaduk** [comment]
> openssl/openssl.conf.h not found

Hmm, that feels like a bug (missing dependencies on generated headers).  Once you manually make the three-ish generated headers, the build should work okay.
So,

```
make include/openssl/opensslconf.h
make crypto/include/internal/bn_conf.h
make crypto/include/internal/dso_conf.h
make libcrypto.a
```

**Comment by kaduk** [comment]
@levitte any idea why this stopped/isn't working?

```
# Empty DEPEND "indices" means the dependencies are expected to be built
# unconditionally before anything else.
DEPEND[]=include/openssl/opensslconf.h crypto/include/internal/bn_conf.h \
         crypto/include/internal/dso_conf.h
```

**Comment by levitte** [comment]
They are collected in the Makefile variable `GENERATED_MANDATORY`, which is used as dependencies for the target `build_generated`, so in essence, you need to do this when you're starting fresh:

```
make build_generated libcrypto.a
```

As soon as enough has been made, that work-around isn't needed any more, because dependency generation will have registered exactly which object files depend on those header files, and they will be regenerated as needed.

The reason we have this situation is a catch 22.  We *could* make all object files in `crypto/` and `ssl/` depend on those header files explicitely...  the trouble is that if any of them changes, *everything* gets rebuilt, not just the fewer particular files that do depend on them (I mean, imagine changing the BN conf...).  The other method is to generate dependencies first, but since we do that automatically as part of the build, it's a moot point.  So we have the workaround with `build_generated`...

**Comment by kaduk** [comment]
Ah, silly me only tried ```make generated``` and didn't look for ```make build_generated```

**Comment by kaduk** [comment]
Perhaps we should pick out a list of "public" top-level targets like libfoo.a/so and put explicit dependencies on ```build_generated``` in the makefile template?

**Comment by snap9** [comment]
For openssl-1.1.0f, 

    make include/openssl/opensslconf.h
    make crypto/include/internal/bn_conf.h
    make crypto/include/internal/dso_conf.h
    make libcrypto.a

works fine. Are you saying that for openssl-1.1.0f you would recommend

    make build_generated libcrypto.a
    make libcrypto.a

instead? Thanks.

**Comment by kaduk** [comment]
Yes, ```make build_generated && make libcrypto.a``` is the pretty way to spell the above, that I had forgotten existed.

**Comment by levitte** [comment]
@snap9: Well, since `build_generated` depends on `include/openssl/opensslconf.h`, `crypto/include/internal/bn_conf.h` and `crypto/include/internal/dso_conf.h`, either works.  `build_generated` is simply a comfortable shortcut that will always work, even if the list of globally generated header files changes.

Side note: it's not necessary to do an extra `make libcrypto.a` ;-)

**Comment by levitte** [comment]
@kaduk, [we already have a list of "public" targets in INSTALL](https://github.com/openssl/openssl/blob/master/INSTALL#L879-L926).  The `build_` targets are more of the internal sort, targetted at developers that "know their thing", and with the option of changing over time.

**Comment by snap9** [comment]
This works, thanks! You are geniuses.

**Comment by snap9** [comment]
@levitte @kaduk What is the correct way to run the tests for only libcrypto.a? Is it `make test build_generated libcrypto.a` or just `make test libcrypto.a`?

**Comment by levitte** [comment]
There is no such separation. The test target depends on all programs being built, and they in turn depend on both libraries, collectively. We simply haven't thought of dividing it per library...

**Comment by skys215** [comment]
Is it same for Windows(not mingw/cygwin/msys)?

**Comment by kaduk** [comment]
Yes
