### ISSUE TITLE
File::Glob::glob() deprecated (1.1.0)

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#4636]
Running `make test` in the 1.1.0 branch results in this warning appearing:

`File::Glob::glob() will disappear in perl 5.30. Use File::Glob::bsd_glob() instead. at .././test/run_tests.pl line 45.`

It doesn't stop the tests from running but should probably be fixed. This doesn't seem to be an issue in master.

Ping @levitte

**Comment by levitte** [comment]
#4040 and #4069 fixed it on master.  I did cherry pick #4040 to 1.1.0, but reverted rather than cherry picking #4069 as well, because the latter was too invasive for 1.1.0, or so was my thinking then.

Care to have a look at #4069 and give it a second opinion re feasibility for 1.1.0?  I think that I was scared to move perl modules around there like I did in master...

**Comment by levitte** [comment]
Ping?

**Comment by mattcaswell** [comment]
#4069 does seem quite invasive - but isn't it more than what we need here? Surely just the commit that introduces our own Glob wrapper is enough?

**Comment by levitte** [comment]
Sure, we can skip moving perl modules, but then there are a few questions to answer:

-  where to place OpenSSL::Glob?
-  dealing with fixes backported from master (cherry picking with different paths is...  tricky)

Also, some scripts will then have to deal with one more include directory instead of just dealing with the one and only.

This only touches internal stuff anyway...

(so suffice to say, I've changed my mind re invasiveness)

**Comment by kaduk** [comment]
Right, it is invasive in a specific and controlled way, if that is not an oxymoron to even say.
(I only skimmed #4069 but do not consider the invasiveness a blocker to backporting.)

**Comment by levitte** [comment]
It occurs to me that now, it's probably easier to simply make new 1.1.0 specific PRs...

**Comment by levitte** [comment]
#4666 does the basics, #4667 does the location consolidation.  Please have a look

**Comment by levitte** [comment]
I think this just got resolved.
