### ISSUE TITLE
can't build with active state perl 5.14

### ISSUE THREAD

**Issue by JimmySnails** [openssl/openssl#4683]
Due to the change in util\copy-if-different.pl and util\copy.pl it's not possible anymore to build openssl with active state perl 5.14. I didn't verify newer versions of perl though. 

Culplrit is the qq that was added.

`foreach (glob qq("$arg"))`

It's a problem for me to change the perl version on some of my older machines...  Would you consider removing the qq? currently i'm adjusting the buildscripts for my older computers.

**Comment by dot-asm** [comment]
Hmmm... I recall testing it when it went to 1.0.2 (and I customarily test with 5.10), and seeing that it works... But apparently I could have been testing wrong thing. It's not clear when behaviour changed, but in 5.10 (and I guess even in yours 5.14) qq("$arg") works as expected only if there is white space in $arg. If there are no white spaces, then it does something else. And I must have checked it only with pathnames with white spaces, because that what proposed modification was allegedly solving. In later Perl versions qq("$arg") works as expected even without white spaces... Go figure...

**Comment by mattcaswell** [comment]
Also see #4680

**Comment by dot-asm** [comment]
On certain level it can be (and arguably should be) viewed as problem to address, because we do specify that 5.10 is minimum requirement, and it doesn't work with it. Could you try to replace `qq("$arg")` with `($arg =~ /\s/ ? qq("$arg") : $arg)`?

**Comment by JimmySnails** [comment]
Yes, the related issue is exactly the same problem that i am describing here. I didn't look at closed issues, that#s why i overlooked that. 

Thanks for analyzing this. You're right, about qq() and i don't use paths with blanks in it. 

Your regex is working, i was rather thinking on 
`foreach (glob "\"$arg\"")`
to get rid of qq() at all, but that's also a solution.

**Comment by dot-asm** [comment]
I don't quite follow, `qq("$arg")` is supposed to be equivalent of `"\"$arg\""`, so how would it help? Does it actually help?

**Comment by JimmySnails** [comment]
Sry, i got you wrong... i thought the problem's with qq() and not glob(). I just tried it and it doesn't work if you add the quotes, so your solution is perfectly fine.

Should i close the ticket?

**Comment by dot-asm** [comment]
It's appropriate to keep in open till fix is committed... I can take care of both...

**Comment by dot-asm** [comment]
Since copy-if-different.pl was mentioned, it ought to be 1.0.2. The problem was addressed in #4696.
