### ISSUE TITLE
Memory-behavioral change in X509_NAME_set in OpenSSL 1.1.0g

### ISSUE THREAD

**Issue by alex** [openssl/openssl#4710]
Specifically: https://github.com/openssl/openssl/commit/4ea5f53d7c6364d3d91539258d8aeb6e9a2e4c93

When used with aliasing, like:

```c
X509_NAME *subject1;
// ...
X509_NAME *subject2 = subject1;
X509_NAME_set(&subject1, subject2);
```

the behavior changes from OpenSSL 1.1.0f to g.

In (f) the `subject2` continues to point to valid memory; in (g) `subject2` now points to freed memory.

This leads to a use-after-free in pyOpenSSL: https://github.com/pyca/cryptography/issues/4015

**Comment by vdukhovni** [comment]
You are not supposed to alias the pointer in the manner in your example.  The original code assumed that in calls of `X509_NAME_set(dst, src)` that if (*dst == src) there was only only a single reference involved, and the call was a NOP. So in the original implementation calling `X509_NAME_free()` on both `subject1` and `subject2` would cause a double free!

You are right that the new implementation which always clones the name (better I think) should not free the old name if that happens to be the source, but even then we end up with some callers exposed to a new memory leak, if they expected to not have the object duplicated.  On the other hand the counter-intuitive previous code can lead to a double free.

So it is not clear what the right answer is.  The function is not documented, so can't use that to determine what it should do. So it is not clear how to proceed.

**Comment by alex** [comment]
We do not call free on both `subject1` and `subject2` in pyOpenSSL, so we did not have a double free.

We don't use `X509_NAME_set` directly, we use it via `X509_set_subject_name` and `X509_set_issuer_name`.

**Comment by vdukhovni** [comment]
The safe behaviour of just use-case in one application is unfortunately not a sufficient basis for a stable API. The real issue here is that functions of the form `foo(&X, Y)` where foo allocates a copy of Y to put into X, *and* frees any previous data stored in X are fundamentally ambiguous when `&X` is an alias of Y.  When is the programmer expecting to end up with two objects and when with just one.  That is, should we construct a copy of Y to put into X, or check whether X==Y and do nothing?  It seems unlikely that the appliation is calling us via `foo(&X, X)`, so there's some expectation that X and Y are separate objects, so why would they not be separate deallocated?

Can you provide a more complete context for your example, with the `X509_set_subject_name()` and `X509_set_issuer_name`()?

My take is that such interfaces SHOULD NOT handle deallocation of previous data for you, they either read or write your pointer, but not both.  If you want old data in X freed, do so explicitly before calling `foo`.  But OpenSSL has many functions that combine both.  This makes the semantics complicated.  The function in question is not documented, so any use of it is already in a state of sin.  I'd like to hear from other team members about what should be done here, but first please explain your use case and motivation in more detail...

**Comment by alex** [comment]
The complete context is that it can happen with pyOpenSSL's API, see the linked bug. If the determination is that the previous behaviour with aliasing will not be restored, we'll work around it there. I filed this primarily out of concern for other callers, who may not realize they are impacted, but not have a use-after-free.

**Comment by mattcaswell** [comment]
I see another problem with the original implementation:

````
 int X509_NAME_set(X509_NAME **xn, X509_NAME *name)
 {
    X509_NAME *in;

    if (!xn || !name)
        return (0);

    if (*xn != name) {
````
Here it is not clear that *xn will always be initialised, e.g. this seems quite reasonable:

````
X509_NAME *xn;

X509_NAME_set(&xn, name);
````

But will actually result in an uninitialised read. Probably harmless but might cause sanitisers to complain.

My feeling is that we should probably not revert to the old way of doing things because of this and the other problems outlined by @vdukhovni above. I'm inclined to close this as a "won't fix".

Any other opinions?

**Comment by richsalz** [comment]
I don't think your example is reasonable, the docs say it is setting a name.  It's like claiming that this is reasonable:
```
char *p, q[10];
strncpy(q, p, 10);
```
If you pass an uninitialized pointer, you're going to get unexpected results and the code is broken.

**Comment by mattcaswell** [comment]
Err? No? That's completely different! It's more like this:

````
char *p = "msg", q[10];
strncpy(q, p, 10);
````
And then getting an unitialised read because the q buffer is unitialised.

My example would work perfectly fine in our current implementation (just not in the old original implementation). There is no reason to expect that X509_NAME_set() would read *anything* from the first parameter

**Comment by mattcaswell** [comment]
Ah. I'm wrong. Even in the current implementation we do an X509_NAME_free(*xn). :-(

**Comment by levitte** [comment]
We did `X509_NAME_free(*xn)` previously as well, as can be seen in #4326.  The difference is that we previously checked if `*xn != name` before reassigning.  It would be easy to put back that check, question is if it should return 0 or 1.

**Comment by levitte** [comment]
Looking at this issue again, it seems that this code would trip:

```
X509_set_subject_name(x, X509_get_subject_name(x));
```

Now, that's a silly call sequence, but imagine that the two calls are some distance apart, and there is a decision point where the subject would simply be put back.

So there's a certain fragility, where the result of one function can't be used liberally with others.  This may actually be the reason why there was the `*xn != name` check in the code before the change.
