### ISSUE TITLE
What does "_st" (for opaque types) stand for in your codebase?

### ISSUE THREAD

**Issue by snap9** [openssl/openssl#4750]
Out of curiosity, when you write (in OpenSSL 1.1)

    typedef struct evp_cipher_st EVP_CIPHER;

for opaque types, what does the "_st" stand for? I'm guessing "structure type", but who knows.

**Comment by levitte** [comment]
Yup. `_st` is very common in structure names. Not our invention...

**Comment by snap9** [comment]
Also, I guess you're assuming that I do not define my own `struct evp_cipher_st` in my own codebase. This could lead to serious disasters, right?

**Comment by levitte** [comment]
Yes. Doing so would be downright abusive...

**Comment by richsalz** [comment]
It would not break openssl, which doesn't use your codebase.  It would be inconvient to your code if you wanted to use EVP_CIPHER and your type, but things would probably still work since none of the OpenSSL code exposes the structure to your code.

C has no namespacing, so type names are global, unfortunately.
