### ISSUE TITLE
EVP_CIPHER_meth_get_XXX functions

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#4781]
Many of EVP_CIPHER_meth_get_XXX functions documented in `doc/man3/EVP_CIPHER_meth_new.pod` don't exist.

In the _RETURN VALUES_ section these are mentioned but they aren't described anywhere and they don't exist in the code base:

- `EVP_CIPHER_meth_get_input_blocksize`,
- `EVP_CIPHER_meth_get_result_size`,
- `EVP_CIPHER_meth_get_app_datasize`,
- `EVP_CIPHER_meth_get_flags`,
- `EVP_CIPHER_meth_get_update`,
- `EVP_CIPHER_meth_get_final` and
- `EVP_CIPHER_meth_get_copy`

The first question, is should these functions exist or should these references be removed?

Additionally, `EVP_CIPHER_meth_get_do_cipher`, `EVP_CIPHER_meth_get_get_asn1_params` and `EVP_CIPHER_meth_get_set_asn1_params` are mentioned in the _NAME_ and _SYNOPSIS_ sections, are implemented but don't get a description.

**Comment by levitte** [comment]
I just found out...  it's an unfortunate copy'n'paste error.  If you look in `doc/man3/EVP_MD_meth_new.pod`, you'll see where they came from.

Both these manuals were written more or less at the same time, together with the functionality, and there are a lot of similarities, that's why this ended up happening.

I'll do some cleaning.

**Comment by levitte** [comment]
It looks like those two manuals are incomplete in more ways :-/

**Comment by paulidale** [comment]
Thanks for the cleaning.
