### ISSUE TITLE
Checks to see if one certificate issued the second

### ISSUE THREAD

**Issue by algv** [openssl/openssl#4786]
Problem with verify certificate chain. I think in  [X509_check_issued](https://github.com/openssl/openssl/blob/master/crypto/x509v3/v3_purp.c#L758) -> [X509_check_akid](https://github.com/openssl/openssl/blob/master/crypto/x509v3/v3_purp.c#L780) not realy need check all fields in akid.

Now openssl check:

- key ids (if present)
- issuer name (if present)
- serial number (if present)

In [RFC 5280](https://www.ietf.org/rfc/rfc5280.txt):

> ```
> AuthorityKeyIdentifier ::= SEQUENCE {
>     keyIdentifier             [0] KeyIdentifier            OPTIONAL,
>     authorityCertIssuer       [1] GeneralNames             OPTIONAL,
>     authorityCertSerialNumber [2] CertificateSerialNumber  OPTIONAL }
>     -- authorityCertIssuer and authorityCertSerialNumber MUST both
>     -- be present or both be absent
> ```

But openssl no chekc it. Maybe need write:
```c++
if (akid->serial && akid->issuer &&
        ASN1_INTEGER_cmp(X509_get_serialNumber(issuer), akid->serial))
       //
      //
```

And I cannot find information, that CA need add all field and then aplications check all akid field for chain verification. Сorrect me if I'm wrong.

**Comment by bernd-edlinger** [comment]
A cert with only serial number in AKID is itself invalid.
OpenSSL does not generate this, but might silently accept it, right?

**Comment by mattcaswell** [comment]
Not a 1.1.1 specific issue so removing that milestone.

**Comment by DDvO** [comment]
The `AuthorityKeyIdentifier` (AKID) extension of an X.509v3 cert 'just' helps to uniquely identify the cert of its issuer. If it is not present the chain building algorithm may have more possibilities to check because the issuer Distinguished Name (DN) may be not unique. This may lead to inefficiency because the cert path validation needs to try more than one candidate issuer cert. It may also lead to incompleteness (and thus to false rejection) in case the chain building stops after not trying all possibilities. So the issuer matching should be as strong/narrow as possible, yet non-unique matching does not incur a security risk.

Actually an RFC 52080 compliant cert that includes the AKID extension MUST have the `keyIdentifier` sub-field included (except for self-signed certs, where it would equal the SubjectKeyIdentifier and where the issuer does not need to be matched anyway), and when present it uniquely identifies the cert such that the `authorityCertIssuer` and `authorityCertSerialNumber` field are irrelevant. In this case `X509_check_akid()` ignores both of them, which is fine.

In the rare (and for non-self-signed certs already non-compliant!) case that the `keyIdentifier` sub-field is not included the values of the `authorityCertSerialNumber` and `authorityCertIssuer` sub-fields are compared (in this order) as far as present. If just one of the two is present (which is non-compliant as already observed by others above) this is just a disadvantage as I described in the paragraph before.

Indeed `X509_check_akid()` could reject a cert where the AKID extension is present but only one of its `authorityCertSerialNumber` and `authorityCertIssuer` sub-fields is included, but there are higher chances for efficient and complete chain building if it makes use of all indentifying information available. 

So I'd say it is good that `X509_check_akid()` behaves gracefully in the non-compliant (but anyway very rare) situation that just either the `authorityCertIssuer` or the `authorityCertSerialNumber` sub-fields of the AKID are included.

**Comment by t8m** [comment]
I do not think there is anything to fix here given the @DDvO 's explanation above. Closing. Please reopen if you disagree.
