### ISSUE TITLE
test/bntest: missing "goto err;" when the tests fail

### ISSUE THREAD

**Issue by FlyerEye** [openssl/openssl#4808]
File: test/bntest.c
Function: file_lshift
Lines: 1090~1092

The execution flow does not jump to the end of function file_lshift() even if getBN() or BN_new() returns a NULL pointer, which may result in NULL dereference bugs on subsequent uses of "a", "lshif" and "ret". I guess it misses a "goto err;" just after line 1092.

For your convenience, I copy and paste related codes as follows:

1085 static int file_lshift(STANZA *s)
1086 {
1087     BIGNUM *a = NULL, *lshift = NULL, *ret = NULL;
1088     int n = 0, st = 0;
1089 
1090     if (!TEST_ptr(a = getBN(s, "A"))
1091             || !TEST_ptr(lshift = getBN(s, "LShift"))
1092             || !TEST_ptr(ret = BN_new()))
1093 
1094     if (!TEST_true(BN_lshift(ret, a, n))
1095             || !equalBN("A << N", lshift, ret)
1096             || !TEST_true(BN_rshift(ret, lshift, n))
1097             || !equalBN("A >> N", a, ret))
1098         goto err;
1099 
1100     st = 1;
1101 err:
1102     BN_free(a);
1103     BN_free(lshift);
1104     BN_free(ret);
1105     return st;
1106 }

Thanks,
Pan Bian

**Comment by mattcaswell** [comment]
It's worse than that. The missing "goto err" means that the lshift tests don't get run at all because the second "if" becomes the body of the first "if". Putting back the "goto err" reveals that the test is broken. This happened during commit 30bea14, where we converted these tests to the new test framework. PR #4809 fixes it.
