### ISSUE TITLE
OpenSSL for Windows Universal API (OneCore)

### ISSUE THREAD

**Issue by specio** [openssl/openssl#4853]
I could not find any reference, to openSSL support for Universal Windows Driver.
Are there plans to add configuration (VS-CORE) which can be run on new Microsoft UWD design, to be precise - includes openSSL linked to OneCore  API. Microsoft is forcing usage of this API, which mean direct linking to system libraries are forbidden (i.e. kernel32.dll, it should be passed via new API).
All new drivers and (possibly) applications need to pass through APIValidator which warns about calls unsupported by Universal API. Such OpenSSL configuration should pass without warnings scan performed by tool made by Microsoft, specified in given article:
https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/getting-started-with-universal-drivers
If passes verification, OpenSSL would support every windows platform, beginning from Win10-IoT Core to Regular Win10 OS's.

**Comment by mattcaswell** [comment]
AFAIK no one is currently looking at this.

**Comment by levitte** [comment]
That being said, patches / PRs welcome!

**Comment by dot-asm** [comment]
There seem to be certain misunderstanding. The question is about *drivers*, but OpenSSL never aimed for *drivers*, only applications. And I find it hard to imagine that it would be even feasible to aim for drivers.

**Comment by specio** [comment]
From new Microsoft perspective all drivers and applications will use new unified Windows API, wrapped inside OneCore.dll, OneCoreUAP.dll, OneCore_downlevel.dll etc, included to new WSDK. 
https://msdn.microsoft.com/en-us/library/windows/desktop/mt683763(v=vs.85).aspx
It's more about API not if it's a driver or not, just drivers got first shot, no matter if it's UWD or UWP, it seems that every app will come to Windows Store, should pass ApiValidation, and link only by Umbrella libraries. I'm working on PoC right now, most of the Win API is covered by new libraries, so mainly they are changes within build configuration.

**Comment by dot-asm** [comment]
> From new Microsoft perspective all drivers and applications will use new unified Windows API

Ah! Typical of Microsoft to extend the meaning of the term, "driver" in this case, to cover something beyond what used to be quite specific term. Also it's not onecore.dll, but onecore.lib. Anyway, aiming for onecore would also mean dealing with dependencies from VCRT. I have actually suggested to set for minimization/elimination of the said dependency, but met either no support for or rejection of the idea from the team. Well, it's actually lesser problem with static build, because resulting binary would include copy of VCRT, which should result in onecore-able external references. However, OpenSSL is rather viewed as "DLL" to custom application, and including VCRT copy into DLL is error-prone...

**Comment by dot-asm** [comment]
> it's actually lesser problem with static build, because resulting binary would include copy of VCRT, which should result in onecore-able external references.

Well, even if external references are onecore-able, it, static copy of VCRT, seems to be leaving references to kernel32.lib anyway... As for IoT, dynamically linked hello-world application seems to work, i.e. there is dynamic VCRT at least on my unit...

**Comment by MouriNaruto** [comment]
I commited some work about this in https://github.com/openssl/openssl/pull/7729 .

Mouri

**Comment by t8m** [comment]
Fixed on master by #8917
