### ISSUE TITLE
1.0.2n (and 1.0.2m) source tarballs include three binaries

### ISSUE THREAD

**Issue by brucestephens** [openssl/openssl#4863]
`test/ssltest_old`, `test/v3ext`, `test/x509aux`. Presumably a `clean` target didn't remove them or something.

**Comment by Kramax** [comment]
I noticed this too but in addition when I looked into the state of the distributed source tar ball I realized that it does not look like a "make dclean" is ever done before creating it. This seems surprising because if you look at the distributed Makefiles they have make depend things in them for .o files and generated files that "make dclean" removes such as apps/CA.pl and tools/c_rehash. What is the policy on this? Is there a good reason to distribute a quasi-configured set of source?

**Comment by richsalz** [comment]
People make mistakes.  Sorry for the inconvenience.
In this case, it was probably a combination of switching branches, the git ignore file, and not using "git clean -df"

**Comment by Kramax** [comment]
I understand it may have just been an oversight and no big deal. I just was more worried that there may have been a larger issue at work here that would require a repackaging or something because a more critical step might have been missed. It is easy to just run "make dclean" after unpacking--no worries.

**Comment by dot-asm** [comment]
So is it going to be fixed, @richsalz? BTW, according to commit message the files were added as result of cherry-pick. Now, this kind of thing can *not* happen as result of successful cherry-pick. I thought that we were to submit separate request if cherry-pick didn't work...

**Comment by richsalz** [comment]
I think there are differing definitions of "cherry-pick worked."  Me, for example, if I can resolve the conflict trivially...  So a PR to remove those three files from the 1.0.2 branch should do it, right?

**Comment by levitte** [comment]
Escept they aren't in the 1.0.2 branch.  They just happened to be in the build tree that the 1.0.2 release was made from.

**Comment by levitte** [comment]
Darn.  Sorry, turns out I'm wrong, they really are in the branch.  D'oh

**Comment by dot-asm** [comment]
> I think there are differing definitions of "cherry-pick worked."

Then maybe we should work on common one.

> So a PR to remove those three files from the 1.0.2 branch should do it, right?

There actually were 17 "alien" files added, and 14 were removed.

**Comment by levitte** [comment]
These 3 binaries now gone...
