### ISSUE TITLE
openssl fips not building correctly on MINGW64 Windows

### ISSUE THREAD

**Issue by scotthain** [openssl/openssl#4882]
It looks like this has been fixed in openssl master by this commit: https://github.com/openssl/openssl/commit/41bee3e8fb749504f21f78dbf3eca85e5b84820b#diff-2245023265ae4cf87d02c8b6ba991139

What is the appropriate way to get this merged into an openssl-fips release?

Thanks in advance!

**Comment by richsalz** [comment]
Sorry, but it won't happen by the OpenSSL project.

**Comment by scotthain** [comment]
@richsalz I understand - Do you have any guidance on where would be the correct place to post this? I couldn't find any documentation on the openssl website or any other places. (I thought this might be correct place since the openssl-fips branches are located in this repo)

**Comment by richsalz** [comment]
The issue is that you cannot change a single line of code without resubmitting the validation.  We're not going to re-open the existing validation; we currently are only the "owners" of 1747. The other two are owned by a private consultant who has not yet turned them over to the project.

We *are* interested in doing FIPS work, but our focus is going to be on a new certification rather than maintaining the old ones. And as I said, we don't have the rights to them anyway. Hopefully that will change.
