### ISSUE TITLE
X509_cmp_time() can return undocumented values

### ISSUE THREAD

**Issue by MarcT512** [openssl/openssl#4954]
The documentation for X509_cmp_time() states it returns -1 (for earlier than or equal to), 0 (error) or +1 (otherwise).

[https://www.openssl.org/docs/manmaster/man3/X509_cmp_time.html](https://www.openssl.org/docs/manmaster/man3/X509_cmp_time.html)

However, in 1.0.2n and 1.1.0g the function can end up returning the value of strcmp(buff1, buff2) which could be other values.

I've been debugging an issue where it was returning -2 and the application code was explicitly checking for -1.

Could the documentation be updated to state it returns < 0 (for earlier or equal to), 0 (error) or > 0 (otherwise) ?

Thanks, Marc

**Comment by ekasper** [comment]
Uh, good catch.

You're looking at the docs for master, and in master this is true :) Here's what happened. This used to be undocumented. I cleaned up the code, and then I documented it (80770da39ebba0101079477611b7ce2f426653c5). I didn't notice that the old code used to return other values.

I'm going to put together a pull that fixes this for other branches too, because that seems like the path of least confusion. There is no value in returning -2.

**Comment by ekasper** [comment]
https://github.com/openssl/openssl/pull/4955

**Comment by MarcT512** [comment]
Great - Thanks!

**Comment by DDvO** [comment]
It looks like this issue has been solved long ago by #4955 and can be closed.
