### ISSUE TITLE
Improve memory use ; remove internal copies of ASN1_{ENUMERATED,INTEGER}

### ISSUE THREAD

**Issue by FdaSilvaYY** [openssl/openssl#4960]
See https://github.com/openssl/openssl/pull/4790#discussion_r153045366

---
It is just for the records.

**Comment by t8m** [comment]
Copying the comment here to make this issue a little bit more descriptive:

The issue exists in all OpenSSL versions, including 1.0.2. A certificate with 100k of path length constraint currently takes several seconds to feed into openssl x509 -text. And note this scales quadratically, so 5MB will take more than an hour. Whether that's important enough to backport I'll leave up to you. It's just a pretty-printing function, but, then again, folks like crt.sh do like to serve the OpenSSL pretty-print format.

Note how each of the callers of this function already start with ASN1_{ENUMERATED,INTEGER}_to_BN which produces a copy within the BIGNUM. Those callers, in turn, loop over every extension producing these temporary buffers when perhaps they could stream the hex into the BIO. There's even an extra temporary copy for CHARSET_EBCDIC. And, of course, there's the fundamental crypto/asn1 inefficiency where the ASN1_INTEGER itself contains a copy of its contents rather than aliasing into the serialized certificate. Unlike everything else here, that one actually impacts real-world performance in our experience.

**Comment by FdaSilvaYY** [comment]
Title updated.

**Comment by FdaSilvaYY** [comment]
issue relies here :
https://github.com/openssl/openssl/blob/1c0eede9827b0962f1d752fa4ab5d436fa039da4/include/openssl/types.h#L45-L46
and here 
https://github.com/openssl/openssl/blob/1c0eede9827b0962f1d752fa4ab5d436fa039da4/include/openssl/asn1.h.in#L159-L163

IMHO, possible solution(s) could be : 
- a new `asn1_integer_st` reimplementation for `ASN1_INTEGER`, separated of `ASN1_STRING`
- a kind of shared-memory buffer introduced into `asn1_string_st` 
-  ...

**Comment by nhorman** [comment]
@t8m is this still something that needs addressing?

**Comment by t8m** [comment]
@nhorman IMO not important enough to spend limited resources on it. Closing.
