### ISSUE TITLE
MINGW-W64: missing symbols for builds with 'shared' flag on Windows

### ISSUE THREAD

**Issue by sav-ix** [openssl/openssl#4990]
Hello, everyone,

For OpenSSL builds using mingw-w64 with **shared** configuration flag, `libcrypto.dll.a` and `libssl.dll.a` import libraries are missing some symbols, available for builds with **no-shared** configuration flag. This leads to issues, like reported in [QTBUG-62692](https://bugreports.qt.io/browse/QTBUG-62692) (in the part of Shared build errors only).

And since
**static** libraries `libcrypto.a` and `libssl.a` from OpenSSL **shared** installation folder
presumably contains the same set of symbols, as
**shared** libraries `libcrypto.dll.a` and `libssl.dll.a` from OpenSSL **shared** installation folder,
it is possible to compare their contents with
**static** libraries `libcrypto.a` and `libssl.a` from OpenSSL **static** installation folder:
![openssl_mingw-w64_shared_vs_static_libcrypto a_1](https://cloud.githubusercontent.com/assets/3617101/25426419/bdf62c62-2a77-11e7-8db0-90525670c631.jpg)
![openssl_mingw-w64_shared_vs_static_libcrypto a_2](https://cloud.githubusercontent.com/assets/3617101/25426415/b75e43d0-2a77-11e7-8dac-f709bf176e65.jpg)

Reproduced for:
* builds using mingw-w64 with Shared layout,

not reproduced for:
* builds using mingw-w64 with Static layout,
* builds using <ICC on Windows|MSVC>.

Environment:
* Windows 10 x64,
* mingw-w64 x86_64 7.2.0,
* ICC 2018 Update 1,
* MSVC 2017 15.5.0,
* Windows SDK 10.0.16299.15,
* MSYS2 20161025,
* OpenSSL-1.1.0g, OpenSSL-1.1.1-dev (f47270e10b7ec18e5719bb2260a7d6460af387ac).

P.S. the above also raises question, why OpenSSL test suite missed this issue?

Best,

Alexander

**Comment by levitte** [comment]
Regarding QTBUG-62692, it's very clearly a question of ordering on the linking command line, and lies entirely on the QT team, not on us.  All the comments in that bug report tell you how to get past the issue.

Regarding the difference in shared vs static library content...  those are private symbols, not to be consumed by library users.  Those can be hidden away in shared libraries but not in static libraries, that's why you see a difference.

**Comment by sav-ix** [comment]
> Regarding QTBUG-62692, it's very clearly a question of ordering on the linking command line

It turned out, that changing libraries ordering has no effect on this issue. AIUI, Qt Developers tested **shared** Qt builds using mingw-w64 with **no-shared** OpenSSL binaries, and such test case was unable to catch **static** Qt build errors.
But when I tested **shared** Qt builds using mingw-w64 with **shared** OpenSSL binaries, got "missing symbols" error.
And when tested **static** Qt builds using mingw-w64 with **no-shared** OpenSSL binaries, got "symbols export" error.
Both errors were [mistakenly] reported on Qt bugtracker as the same issue, and only recently it turned out that they are different.
As I mentioned in Description, [this issue](https://github.com/openssl/openssl/issues/4990) relate to "missing symbols" error only.

> Regarding the difference in shared vs static library content... those are private symbols, not to be consumed by library users. Those can be hidden away in shared libraries but not in static libraries, that's why you see a difference.

Starting from this place things have become more complicated than they seemed before. Thus have to add more details concerning inconsistencies in OpenSSL builds on Windows.
The contents of OpenSSL-1.1.0g installation folders for builds using:
* mingw-w64 with **shared** configuration:
```
lib\libcrypto.a        <==== (static library, missing private symbols)
lib\libcrypto.dll.a    <==== (import library, missing private symbols)
lib\libssl.a           <==== (static library, missing private symbols)
lib\libssl.dll.a       <==== (import library, missing private symbols)
```

* mingw-w64 with **no-shared** configuration:
```
lib\libcrypto.a        <==== (static library, contains private symbols)
lib\libssl.a           <==== (static library, contains private symbols)
```

* MSVC with **shared** configuration:
```
lib\libcrypto.lib      <==== (import library, contains private symbols)
lib\libssl.lib         <==== (import library, contains private symbols)
```

* MSVC with **no-shared** configuration:
```
lib\libcrypto.lib      <==== (static library, contains private symbols)
lib\libssl.lib         <==== (static library, contains private symbols)
```

This explains, why Qt "missing symbols" build error reproduced for builds using mingw-w64 only, but not MSVC.

Hence few questions:
* why OpenSSL binaries, built using MSVC, contains private symbols for both **shared** and **no-shared** configurations, and built using mingw-w64 contains private symbols for **no-shared** configuration only?
* why **shared** OpenSSL installations, built using mingw-w64, contains both static and import libraries, and built using MSVC contain import libraries only?

**Comment by levitte** [comment]
Ok, so this is confusing... are you saying that you found something *other* than what was reported in [QTBUG-62692](https://bugreports.qt.io/browse/QTBUG-62692)?  'cause the big issue there that does generate all those missing symbols (and the majority of those reported there are *public*, i.e. present in import libraries) *is* the order of the libraries on the command line...  they have `c:\libOPENSSL-1.1.0f\GCC64RH\lib\libcrypto.a c:\libOPENSSL-1.1.0f\GCC64RH\lib\libssl.a` when it should be `c:\libOPENSSL-1.1.0f\GCC64RH\lib\libssl.a c:\libOPENSSL-1.1.0f\GCC64RH\lib\libcrypto.a`.

Now, the enumeration you make there says that `lib\libssl.lib` and `lib/libcrypto.lib` when configured with MSVC and **shared** have them include private symbols...  that's clearly wrong.  Likewise, the mingw libcrypto.a and libssl.a should contain private symbols.  I'll have to investigate that.

**Comment by sav-ix** [comment]
Everything I found concerning [presumable] OpenSSL flaws is described in this issue. Though thank you for trying to help with [QTBUG-62692](https://bugreports.qt.io/browse/QTBUG-62692). Concerning your suggestion, I can add:
* changing order in linking command line from `-llibcrypto -llibssl` to `-llibssl -llibcrypto` solved Qt **shared** build errors with **shared** OpenSSL binaries using mingw-w64; finally I got something, that two more people told me before you; though odd, that **shared** Qt builds using MSVC do not depend on the order in linking command line (i.e. use of `-llibcrypto -llibssl` key for such builds doesn't reproduce error),
* changing order in linking command line from `-llibcrypto -llibssl` to `-llibssl -llibcrypto` didn't solve Qt **static** build errors with **no-shared** OpenSSL binaries using mingw-w64; though it's not OpenSSL bug,
* using **shared** OpenSSL binaries, built using MSVC, fixed both Qt **shared** and **static** build errors using mingw-w64; though this is could be considered as a workaround, but not a solution.

I was wrong when told, that OpenSSL **shared** binaries, built using MSVC, contains private symbols. Already corrected previous post. Sorry for the noise.

Since everything above seems to be an expected behavior, I assume this issue could be closed. 

The only opened questions left, why **shared** OpenSSL installations, built using mingw-w64, contains both static and import libraries, and built using MSVC contain import libraries only? And is it possible to introduce <`static`|`no-static`> flags similar to <`shared`|`no-shared`>, to allow explicitly disable static binaries build for shared OpenSSL builds?

**Comment by levitte** [comment]
> The only opened questions left, why **shared** OpenSSL installations, built using mingw-w64, contains both static and import libraries

Because, just as on Unix, we offer both.  That gives people the choice of what they prefer to use, from one build.  gcc (or is it ld?) on (and cygwin) understand to translate `-llibcrypto` appropriately to `libcrypto.dll.a` or `libcrypto.a` depending on what other flags you use.

We can't offer the same thing with Native Windows, 'cause there is no such distinction between import and static libraries in that environment.

> And is it possible to introduce <`static`|`no-static`> flags similar to <`shared`|`no-shared`>, to allow explicitly disable static binaries build for shared OpenSSL builds?

We have `-static` (I'm not sure why it wasn't made a regular Configure option...)

**Comment by sav-ix** [comment]
Indeed. But still its implementation slightly differs from `shared` flag:
* forced use of `no-thread` key (and where is "a choice for the people" here),
* it is missing in `my @disablables = {...}` list in `Configure` script.

Does this worth to be reported as a separate issue and discussed by OpenSSL Community?

**Comment by levitte** [comment]
I don't remember the reasoning there...  the goal with `-static` was to produce a `openssl` binary with *no* references to shared libraries whatsoever, so you would just copy that binary over where you like and it just works.

The reason it wasn't made a regular disablable option is that it's really just a compiler flag passed on the configuration command line, we just take note of it and disable certain features as a consequence, to make sure it fulfills its intended promise.  Otherwise, people had to go through this hoop to get the result they wanted from `-static`:

```
./config -static no-shared no-dso no-pic no-threads ...
```

I cannot say why threads are disabled by default with `-static`, but on the other hand, it's perfectly possible to re-enable it, like this (ordering is important, arguments are processed left to right):

```
./config -static enable-threads ...
```

**Comment by sav-ix** [comment]
It's all not easy, and it seems better to leave `Configure` script as is. As for OpenSSL static binaries in shared builds, they could be deleted manually from installation folder.
Thank you for your time!

**Comment by dot-asm** [comment]
> I cannot say why threads are disabled by default with -static

For starters one has to recognize that build configured with -static is apps/openssl-centric. In other words intention wasn't that it would be `make install`-ed, but rather that you'd simply take apps/openssl to another system [without having to bother with what *exact* kind of system is it(*)]. And since apps/openssl does not use any threading, it makes no sense to enable it. Secondly and actually more importantly, libthread is more system-specific than one would normally expect from statically linked binary, i.e. you wouldn't be as free copying apps/openssl around. In fact it's not even given that statically linked libpthread works at all. For example if I configure with -static enable-threads on my x86_64 Linux computer, apps/openssl and test programs crash with SEGV early in startup code... Windows of course is another matter, because threading support is there unconditionally(**).

(*) For example I for one customarily use it to produce binaries that can be executed on say Raspbian as well as ... Android.

(**) As curious fact, how do Windows handle ctrl-c in console application? Kernel actually force-creates a thread in application context to execute the handler.

**Comment by dot-asm** [comment]
> We can't offer the same thing with Native Windows, 'cause there is no such distinction between import and static libraries in that environment.

As you mentioned, mingw linker is "magic" in sense that it translates -lcrypto to a *search*, by default first libcrypto.dll.a followed by [attention!] crypto.dll.a, only then by libcrypto.a, still followed by crypto.lib, libcrypto.dll, crypto.dll and crypto.lib. MSVC linker is not even least magic and you have to explicitly name library down to extension, e.g. libcrypto.lib. It means that we could as well provide static library under different name, e.g. libcrypto.a.lib. [Just in case, filename extension is magic, it has to end with .lib, so one can't call it libcrypto.a.] So it's not actually so that we can't offer it, but it would be surely raise some brows and it would be counter-intuitive. But we could put it together during build for testing purposes...

**Comment by dot-asm** [comment]
Last note from OP sounds like issue could be closed... Or is it wrong perception?

**Comment by levitte** [comment]
I agree with your impression, so closing
