### ISSUE TITLE
Compiling and met with error "storage size of 'ctx' isn't known"

### ISSUE THREAD

**Issue by daver12345** [openssl/openssl#5009]
Hello. I was compiling a package and was met with the error "storage size of 'ctx' isn't known"
This is all that appeared as the error:
 HMAC_CTX ctx;

If somebody could help, that would help a lot.

**Comment by kaduk** [comment]
Many data types were made into opaque structures for the 1.1.0 release, and may no longer be allocated on the stack by application code; HMAC_CTX is one such type.  The application will need to switch to using HMAC_CTX_new() and HMAC_CTX_free(), with a pointer variable, in order to be compatible with the latest OpenSSL release branch.

**Comment by richsalz** [comment]
https://www.openssl.org/docs/faq.html#PROG2

**Comment by mattcaswell** [comment]
I'm not sure of the relevance of that FAQ entry to this issue - but since this question does come up from time to time we really should have an FAQ entry for it.

Anyway, most likely the package you are trying to compile only support OpenSSL 1.0.2 and not 1.1.0. Please try that OpenSSL version and encourage the package maintainer to upgrade!

**Comment by richsalz** [comment]
Perhaps the FAQ can have additional text, but that is *exactly* the error.

**Comment by mattcaswell** [comment]
Oh...my mistake, for some reason I was reading the FAQ entry below.
