### ISSUE TITLE
Please follow semantic versioning

### ISSUE THREAD

**Issue by probonopd** [openssl/openssl#5042]
OpenSSL is a central piece of infrastructure on virtually every Linux system. As such, applications linking to it should have the assurance that new OpenSSL versions don't break applications compiled against older OpenSSL versions.

According to https://semver.org/,

-  **MAJOR** version when you make incompatible API changes,
-  **MINOR** version when you add functionality in a _backwards-compatible_ manner, and
-  **PATCH** version when you make backwards-compatible bug fixes.

So OpenSSL should have added "functionality in a backwards-compatible manner" going from 1.0 to 1.1. However, applications compiled against OpenSSL 1.0 seem to break when OpenSSL is updated to 1.1.

There are two ways to address this:
1. Ensure that all applications compiled against OpenSSL 1.0 continue to run when OpenSSL is updated to 1.1; or
2. Rename OpenSSL 1.1 to 2.0 in order to make clear that you made incompatible API changes; advise users to install 1.x in addition to 2.x if they want to continue to run applications compiled against 1.x

If application developers (such as Firefox and Chrome) cannot rely on backward compatibility in OpenSSL, they are effectively forced to ship privately bundled versions, leading to duplication and locking them out from system-wide security patches.
 
References:

- https://github.com/probonopd/AppImages/commit/6c7473d8cdaaa2572248dcc53d7f617a577ade6b
- http://stackoverflow.com/questions/32644157/forcing-a-binary-to-use-a-specific-newer-version-of-a-shared-library-so
- https://abi-laboratory.pro/tracker/timeline/openssl/

**Comment by probonopd** [comment]
Even though OpenSSL may not have been using semantic versioning so far, it is _now_ the time to start embracing it. The project is just now going from 1.0 to 1.1 - so this is the last possible chance to fix this before 1.1 find its way into LTS distributions. At which point the mess will not be easily reversible anymore.

**Comment by levitte** [comment]
Actually, our versioning scheme *is* semantic as defined by http://semver.org, semantically speaking.  The only actual difference is our version number *syntax*.

Very simply put, we have a static `1.` at the beginning of the version number, so our versioning becomes `1.{MAJOR}.{MINOR}{PATCHletter}`.  We have set our shared library SONAME to match, i.e. for OpenSSL 1.0.x, the shared library SONAME should be `lib{crypto,ssl}.so.1.0.0` (yes, that was a bit overboard), while for OpenSSL 1.1.x, the SONAME is `lib{crypto,ssl}.so.1.1`, which is different, i.e. a shared library bump (remember that the numbers in SONAMEs have *nothing* to do with package versions per se).

We haven't quite decided what we will do with that starting `1.` and what `2.` would actually mean.  Someone (possibly me) has floated the idea that it should be made to mean a complete rewrite (which is much stronger than just some API incompatibility), but there's no conclusion yet...

The thing is that you're a bit late in the game, calling for a rename of 1.1 to 2.0.  1.1.0 was released in August 2016, that's 1½ year ago.  Rethinking the versioning *now* would be irresponsible.  I'd say that what we currently call 1.2.0 (major number 2) could be the next target for rethinking...

**Comment by richsalz** [comment]
So we should close this issue?

**Comment by probonopd** [comment]
Part of the power of http://semver.org is that it is not only _some_ semantic versioning scheme, but _one_ scheme that _many_ projects agree on and follow, making it _easy_ to recognize what each number in a version means.

If you decide to use _your own_ semantic versioning scheme, then maybe insiders in the project will have the same advantages as with http://semver.org but outsiders to the project will mis-interpret the meaning of the numbers and may draw the wrong conclusions.

So I would hope to see at least a discussion/consideration of http://semver.org for the next major release that will come up at some point (e.g., to make what you had planned to become 1.2.0 a http://semver.org like 2.0.0, and drop the letters).

**Comment by levitte** [comment]
@richsalz, if we close it, we will forget.  I labeled it so we can remember to reconsider this at the appropriate time, so I think it should be kept open.

**Comment by probonopd** [comment]
Looking at the [Qt sourcecode](https://github.com/qt/qtbase/blob/50deb8cf70f61e21fb0c35182341477af11adbc1/src/network/ssl/qsslsocket_openssl_symbols.cpp#L745-L765), I see this comment:

>  // (...) OpenSSL is a well-known case of binary-compatibility breakage. To
// avoid such problems, many system integrators and Linux distributions change
// the soname of the binary, letting the full version number be the soname. So
// we'll find libssl.so.0.9.7, libssl.so.0.9.8, etc. in the system. For that
// reason, we will search a few common paths (see findAllLibSsl() above) in hopes
// we find one that works.

A clear naming scheme following  http://semver.org combined with a corresponding use of SONAME/SHLIB_VERSION_NUMBER should improve the situation, shouldn't it?

**Comment by levitte** [comment]
It's true that we've be uncareful and caused breakage where we shouldn't have.  However, a different *version syntax* will not make any difference at all.

But then, [let's look at actual facts](https://abi-laboratory.pro/tracker/timeline/openssl/).  As you can see for yourself, there are a number of times during the life of the `1.0.0` SONAME where we removed symbols.  Some of them are really private and should not have been an issue, but there have been a couple of instances, as I understand it, where actual public symbols were changed.
This is within the lifetime of one and the same SONAME, and within what are MINOR updates of our version numbers.  Do you truly think that if we had followed semver *version syntax*, the outcome would have been different?

So while I can really see why Qt say what they do, and that they have good reason to.  But I think that your conclusion that this had something to do *version syntax* is somehow missing the point...

**Comment by levitte** [comment]
Mind you, 1.1.0 is our attempt to start over.  We've harmonised several platforms that were previously going in very different directions (would you believe that the Windows shared libraries were called `libeay32.dll` and `ssleay32.dll` for the longest time?  That stopped with 1.1.0)

**Comment by probonopd** [comment]
Probably a clear numbering scheme in which OpenSSL sets the version numbers, distributions don't try to outsmart OpenSSL, and subsequently Qt wouldn't have to try to outsmart distributions would, if nothing else, make things _simpler_. In other words, if OpenSSL will bump the major version number each time symbols are removed or other breakage occurs, if everyone uses the same version numbers, and everyone can trust that everyone uses the same version numbers, everyone's life should be easier, shouldn't it? (I also wonder whether one could, instead of _removing_ symbols, replace them with a no-op and a text message printed to the terminal...)

**Comment by levitte** [comment]
> (I also wonder whether one could, instead of removing symbols, replace them with a no-op and a text message printed to the terminal... so that at least applications would continue to run)

That's completely irrelevant for a shared library bump...  which is the only time public symbols should ever be removed.

Either way, I've put this on hold for them time when we get near 1.2.0.  There's no point changing our numbering scheme before then.  No discussion going on now will change that.

**Comment by nickthetait** [comment]
I support adopting this change as soon as possible. Deciding on a release's name earlier will reduce confusion later.

**Comment by Croydon** [comment]
OpenSSL will follow semantic versioning. Thanks!

https://www.openssl.org/blog/blog/2018/11/28/version/

**Comment by mattcaswell** [comment]
That blog post says explicitly that we are NOT doing that:

"We are not at this stage directly adopting semantic versioning because it would mean changing our current LTS policies and practices."

I'm closing this issue because we considered it in some depth and at length, but decided not to.

**Comment by probonopd** [comment]
> changing our current LTS policies and practices

Yes, I guess this is what I was asking for.

Oh well.

**Comment by levitte** [comment]
You should read https://semver.org/

Semantic versioning is more than a version number layout, it's also a strict set of rules for when each number changes. Some of these rules differ ever so slightly from our practice, so we may be close to semantic versioning, but that's also all.

If it only looks like a duck but doesn't quite swim like a duck, it's not a duck...

**Comment by probonopd** [comment]
But then, why not make it a _real_ duck? (I mean, instead of "we are not doing it because our policy is to not do it" - real reasons?)

**Comment by Croydon** [comment]
I'm assuming that I don't need to read about semver, but rather about `OpenSSL practices`. Maybe the article should have contained two sentences or a few bullets points explaining the differences as I'm pretty sure that I'm not the only one mislead by it.

The only statement indicating a difference is 
> We are not at this stage directly adopting semantic versioning because it would mean changing our current LTS policies and practices.

which is directly followed by
> The current 1.1.1 and 1.0.2 versioning scheme will remain unchanged.

which can be easily interpreted that `We are not at this stage directly adopting semantic versioning` simply means that for current release strings it won't be changed.

**Comment by levitte** [comment]
> The only statement indicating a difference is 
> > We are not at this stage directly adopting semantic versioning because it would mean changing our current LTS policies and practices.

> which is directly followed by
> > The current 1.1.1 and 1.0.2 versioning scheme will remain unchanged.
> 
> which can be easily interpreted that `We are not at this stage directly adopting semantic versioning` simply means that for current release strings it won't be changed.

The 1.1.1 series will continue to be 1.1.1 followed by a letter for patch updates.
The 1.0.2 series will continue to be 1.0.2 followed by a letter for patch updates.

However, the next *major* release will be 3.0.0 and will have a MAJOR.MINOR.PATCH version, where the PATCH level number will be used in place of the patch letters.

Our major deviation from semantic versioning is that we allow the addition of new public functions in a PATCH update.  Remember the setter and getter functions that were missing in 1.1.0?  They got added in patch updates.  This is something that semantic versioning does *not* allow.  I justify it by making a difference between adding functions that were omitted where they shouldn't (the omission is a bug) have and adding functions that are actually new features.  The former is acceptable for a patch update according to our policy, the latter is not.  So in summary, semantic versioning is problematic for us because semantic versioning views *all* added functions as new features, we do not necessarely do so.

**Comment by levitte** [comment]
As soon as #7724 goes through, the master branch will have shifted to the new version scheme.

**Comment by probonopd** [comment]
@mattcaswell 

> I'm closing this issue because we considered it in some depth and at length, but decided not to.

Can you give rationale behind this decision?

Users are running into practical issues every day due to this. Example:
https://github.com/antony-jr/QTalarm-AppImage/issues/1

**Comment by kroeckx** [comment]
The major reason we can not adopt semantic versioning is because
we support more than 1 version of the software, and we might need
to add new features to older versions of the software. Adding such
a feature to older software under semantic versioning will require
that the minor number gets changed, but that minor number might
already exist. So we will change the patch number instead in that
case.

In the past we have needed to add new functions to old versions
many times. If you look at the util/libcrypto.num and
util/libssl.num files in the OpenSSL_1_1_0-stable branch, and look
at all the lines that don't have 1_1_0, but things like 1_1_0d,
you'll see that we had to add many functions.

**Comment by mattcaswell** [comment]
Note also that the new versioning scheme we are adopting for our next version (3.0) is very similar in a lot of ways to semantic versioning, but doesn't quite meet the official definition due to the issue @kroeckx described above. See:

https://www.openssl.org/blog/blog/2018/11/28/version/

**Comment by claell** [comment]
> However, the next major release will be 3.0.0 and will have a MAJOR.MINOR.PATCH version, where the PATCH level number will be used in place of the patch letters.

Nice!

> Our major deviation from semantic versioning is that we allow the addition of new public functions in a PATCH update. Remember the setter and getter functions that were missing in 1.1.0? They got added in patch updates. This is something that semantic versioning does not allow. I justify it by making a difference between adding functions that were omitted where they shouldn't (the omission is a bug) have and adding functions that are actually new features. The former is acceptable for a patch update according to our policy, the latter is not. So in summary, semantic versioning is problematic for us because semantic versioning views all added functions as new features, we do not necessarely do so.

Can you elaborate why it is important for you to make this destinction between new features and "bug fix features"? I mean, you could stick with your policy to not add new features in what you call "patches" while using semantic versioning to indicate that new functions got introduced with your bug fix. Does that make sense?

Also, if it does not, you are probably not the only project having this problem with semantic versioning. So you might want to open an issue there so that they are aware of this problem. Maybe they can find a standardized solution for it. Because I think the biggest issue here is to not comply with the standard which causes confusion. And if the standard does not fit you, maybe it needs to be changed.

**Comment by levitte** [comment]
> I mean, you could stick with your policy to not add new features in what you call "patches" while using semantic versioning to indicate that new functions got introduced with your bug fix. Does that make sense?

There are times when we have needed to add new public functions as part of a patch, but that's not enough to make it a minor release (i.e. new feature release).  When we released 1.1.0, we had forgotten to add a number of accessor functions for the types that are now opaque, and we added them in so called "letter updates" (which corresponds in spirit to "patch" releases).  If you follow strict semantic versioning, this is forbidden.

I see no point bothering the semver folks.  They have made a set of rules that are consistent within their realm of thinking, and they *do* note among their tutorials and stuff that there are many projects that are close to semver, but not quite...  and in the end, that's quite all right, really.

The main thing is that:

- for PATCH releases, there should be no new public features and no *changed* public functions.  Semver says that new public functions are new features, we say that it depends...  I think we've concluded that whole new APIs (i.e. *set* of functions) constitute new features.  This is still upwardly compatible, both API and ABI wise, so in spirit, semver agrees with us (even if not strictly).
- for MINOR releases, there can be new public features.  There, semver agrees with us, even when read strictly.
- for MAJOR releases, anything goes (even though doesn't have to be breaking).  Again, semver agrees with us there.

So in essence, we are close enough to semver to be happy.

**Comment by claell** [comment]
I prefer to have things rather standardized, maybe semver can be changed if they agree with you in spirit.

Also after reading https://github.com/openssl/openssl/issues/5042#issuecomment-494534534 which I now notice to be probably a bit different from the problem you describe, I created an issue at semver about this: https://github.com/semver/semver/issues/532

**Comment by wizzwizz4** [comment]
> There are times when we have needed to add new public functions as part of a patch, but that's not enough to make it a minor release (i.e. new feature release). When we released 1.1.0, we had forgotten to add a number of accessor functions for the types that are now opaque, and we added them in so called "letter updates" (which corresponds in spirit to "patch" releases). If you follow strict semantic versioning, this is forbidden.

Is it forbidden, though? It's a bug fix, where the bug happened to be "failure to export certain functions". Them not having been written is irrelevant to the reality: they should've been there, and weren't. This is a bug fix, and therefore should use the patch number. Yes, it's technically changing the symbol table, but SemVer doesn't mention symbol tables. Bug fixes nearly always change behaviour, but if the previous behaviour was useless, flawed or violated interfaces, that's fine.

You defined (a category of) interfaces that opaque types should possess, then fixed the bug that "not all opaque types had this interface". That's a patch number increment, because it's a bug fix that didn't introduce new features (the functions were meant to be there all along to implement the feature (you thought) you were including), doesn't break existing, correctly-working code and would, in fact, cause correct code that didn't work before to begin working.

That's not against SemVer.

**Comment by levitte** [comment]
> 7. Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API.

Ref: https://semver.org/#spec-item-7

But seriously, I don't understand the need to quibble over details. We have chosen something that's close enough, even though not exactly "right" according to a strict reading of the rules. But frankly, I find the difference too small to spend a lot of time and energy on. If you think we do follow semver, that's absolutely fine, but it's not like we're seeking some kind of branding... 

This issue is closed.

**Comment by jeme** [comment]
Just to add i caution note to your version scheme.

You mention that you guarantee API/ABI compatibility between the same MAJOR versions, yet you allow the additions of new functions in a PATCH release of a older version.

I don't know if you have thought that through, but if not ill hit on it here...

Say you release have an interface that has the following functions in the releases as outlined here:
----
v1.0.0
 - FuncA
 - FuncB

v1.1.0
 - FuncA
 - FuncB
 - FuncC

v1.2.0
 - FuncA
 - FuncB
 - FuncC
 - FuncD
----

In order to maintain your promise, the only thing you can add to v1.0.1 is FuncC, if you add FuncD or another even a FuncE, you are breaking backwards compatibility of you v1.1.0 as that does not have that function.

I just wanted raise that, if your only ever backporting features from one version ahead, you should be fine on the promises.

**Comment by kroeckx** [comment]
We would most likely add a FuncE either to all, and release
v1.0.1, v1.1.1 and v1.2.1. Or maybe only add it to v1.1 and v1.2
because it doesn't affect v1.0.

We also use symbol versioning (on platforms that support it).
The symbol version would be v1.0.1 in all v1.* releases.

This actually works properly if you upgrade from v1.0.1 to v1.1.1
or v1.2.1. If you try to upgrade to v1.2.0, it would clearly
break, but why would you want to do that?

**Comment by jeme** [comment]
@kroeckx I dont think you ar understandung what I am pointing out, I don’c care what you do an how you manage versions. I only pointed out that if you do what you do, you are violating your own version scheme.

At least from how it is put forth in this thread, so you probably want to correct the scheme then.

**Comment by levitte** [comment]
> In order to maintain your promise, the only thing you can add to v1.0.1 is FuncC, if you add FuncD or another even a FuncE, you are breaking backwards compatibility of your v1.1.0 as that does not have that function.

If we add a new function that we deem a bug fix (i.e one of those missing accessory functions I mentioned), and therefore a patch level change, we do apply that same patch to all version series (within the same major version) we support. In other words, to go from your example, if we would release FuncBbis in 1.0.1, we would have to release 1.1.1 and 1.2.1 with that same function added (and with the same transfer vector location on platforms where that's still applicable).

Does that make more sense to you?

**Comment by jeme** [comment]
@levitte I understand what it is your doing, and to the extend your doing it you are breaking your promise with our version scheme.

If i where to be really harsh on the way it's formulated in https://www.openssl.org/blog/blog/2018/11/28/version/
> API/ABI` compatibility will only be guaranteed for the same MAJOR version number.

It could even be read as you guarantee compatibility going from 1.3.0 to 1.0.0 as you don't touch order of versions at all. I obviously ignored that and just figured you mean "Backwards API/ABI` compatibility will only be guaranteed for the same MAJOR version number." (which makes a lot more sense)...

But your still breaking the promise as your not staying backwards compatibly within the Major version when you consider is the natural order of version numbers.

As i stated to @kroeckx , I don't care what you do and why, I only wanted to point out that what you promise people in your version scheme, is not what you deliver. As such you should go over the scheme again and clarify it. - And I was fairly certain that it was a angle you overlooked as you wrote the scheme, as such you "backwards" compatibility is based on a combination of the natural order of the version number, e.g. 1.2.1 is greater than 1.1.1 and 1.2.0, but ALSO the date that it was released.

----

Does it make sense for me that you do that?...

Not at all, as a Software Architect, Developer and Package Consumer, I can't see any reason at all to ever not upgrade to the latest minor version if backwards compatibility is promised, and ESPECIALLY within something as the OpenSSL package as that is security related (I would even put great effort in staying with the latest major for such packages). Anything else would be ludicrous to me. **BUT I am not here to discuss that**

**Comment by claell** [comment]
@kroeckx 
> If you try to upgrade to v1.2.0, it would clearly
break, but why would you want to do that?

I guess that incompatibility is what @jeme was pointing out. I am not sure why one would upgrade to v1.2.0. At least you claim that it should be compatible in your blog.

**Comment by levitte** [comment]
@jeme, understood. Thank you for the thorough input.

**Comment by probonopd** [comment]
This is still causing trouble 4 years later.

Running 20.04.4 LTS (Focal Fossa) and wanting to use [this](https://www.egenix.com/products/python/PyRun/#Download) software that requires libssl1.0, but apparently all that Ubuntu nowadays provides in main is libssl1.1.

There should really be a policy that wherever essential system packages like this get updated in binary breaking ways, then t least the 3 versions before it should still be shipped in distributions so as not to break existing software. Unfortunately all Linux distributions seem to care for is the software _inside_ the distribution, not the software users want to run _on top of_ the distribution ("sideloading").

Stuff like this is really a pain!


```
sudo apt-get install libssl1.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libssl1.1 is already the newest version (1.1.1f-1ubuntu2.12).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

sudo apt-get install libssl1.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libssl1.0-dev' for regex 'libssl1.0'
Note, selecting 'libssl1.0.0' for regex 'libssl1.0'
Note, selecting 'libssl1.0.2' for regex 'libssl1.0'
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

$ sudo apt install libssl1.0.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libssl1.0.0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libssl1.0.0' has no installation candidate
```

**Comment by probonopd** [comment]
Let's hope that 1.2.x.will either
* Be compatible in such ways that software compiled for 1.1.x can still run with 1.2.x, or
* Be called 2.0.x (because it breaks existing software _again_)

**Comment by tmshort** [comment]
@probonopd lease see: https://www.openssl.org/blog/blog/2018/11/28/version/
There won't be a 1.2 nor 2.0.
2.0 was used by the FIPS Object Module (and LibreSSL)
OpenSSL's current release is 3.0; and is now based on semantic versioning as of that version. 3.0 is the current LTS release, the prior LTS release (1.0.2) will be out of support in ~17 months.

**Comment by tmshort** [comment]
My mistake... 1.1.1 is the prior LTS release, and will be out of support in ~17 months.

**Comment by probonopd** [comment]
> OpenSSL's current release is 3.0; and is now based on semantic versioning as of that version. 

:+1: :+1: :+1: 

Now, will distributions (read: Ubuntu main) still carry 1.0 and 1.1 once 3.0 is released? I strongly hope so!

**Comment by tom-cosgrove-arm** [comment]
@probonopd OpenSSL 3.0 was released last year, and 3.0.3 will be released next week. Have a read of https://www.openssl.org/source/

**Comment by mattcaswell** [comment]
> and is now based on semantic versioning as of that version

"based on" is an important caveat. As per the blog post that @tmshort links to:

> This more closely aligns with the expectations of users who are familiar with semantic versioning. We are not at this stage directly adopting semantic versioning because it would mean changing our current LTS policies and practices.

**Comment by tmshort** [comment]
> Now, will distributions (read: Ubuntu main) still carry 1.0 and 1.1 once 3.0 is released? I strongly hope so!

So, I installed Ubuntu 22.04 over 21.10... and... it installs OpenSSL 3.0, but removes OpenSSL 1.1... However, grub still depends on 1.1. Which ends up breaking `apt` because grub can't complete its updates. You can still install the 21.10 or earlier (e.g. focal) version of OpenSSL 1.1 onto 22.04.

It is "ok" for a (Unix-like) system to have multiple versions of OpenSSL installed, the shared objects are versioned, as are their names. The only complications come when building applications. You really can only have one set of header files, and one set of non-versioned symlinks to versioned shared objects (e.g. libcryto.so -> libcrypto.so.3 and libssl.so -> libssl.so.3 symlinks).
