### ISSUE TITLE
Extra space in openssl CLI output for notAfter/enddate

### ISSUE THREAD

**Issue by nikolaiderzhak** [openssl/openssl#5107]
I am getting extra space in enddate output of this command:

```
$ export IP=google.com;  nc -z -w 3 $IP 443 && (echo | openssl s_client -connect $IP:443 2>/dev/null | openssl x509 -noout -enddate)
Connection to google.com port 443 [tcp/https] succeeded!
notAfter=Apr  4 09:40:00 2018 GMT
```

Note two spaces between Apr and 4 in notAfter= line.

That is the case for both versions I have on laptop and on linux server:

```
$ openssl version
LibreSSL 2.2.7
$ openssl version
OpenSSL 1.0.1f 6 Jan 2014
```

https://stackoverflow.com/questions/48328163/extra-space-in-openssl-cli-output-for-notafter-enddate

LibreSSL has the same issue: https://github.com/libressl-portable/portable/issues/382

**Comment by kaduk** [comment]
This is intentional behavior from ASN1_TIME_print(), to use a fixed number of characters for the day representation.  If the day number is less than 10, it still takes up two columns, with the first one being filled as a space.  This is friendly to automated tooling parsers even if it is a little jarring for the human eye.  I don't think it's appropriate to change ASN1_TIME_print()'s behavior because it is used in more places than just this.
