### ISSUE TITLE
Removal of Whirlpool hash algorithm

### ISSUE THREAD

**Issue by hannob** [openssl/openssl#5118]
OpenSSL contains code for the Whirlpool hash algorithm.

I'm not aware of any real world use of that hash alg. It had some popularity around the time MD5+SHA1 got broken, but I think it never gained any traction.

For complexity reduction of the OpenSSL code I recommend removing whirlpool with the next API change.

**Comment by mbroz** [comment]
FYI, Whirlpool is one of the hash functions used for TrueCrypt PBKDF2 and we use OpenSSL (or libgcrypt) as a backend for cryptsetup (that can open these containers).

Removal of Whirlpool means that users are no longe able to open these containers.
Whirlpool variant is not common, but I would definitely like to have backward compatible way to open it.

Please do not remove algorithms from a generic crypto library just because you do not know who use them. Thanks.

**Comment by mspncp** [comment]
A compromise would be to add whirlpool and other (outdated, unsafe, ...) algorithms to the disabled-by-default list of algorithms in the next major release.

**Comment by mbroz** [comment]
If it can be enabled in runtime by some legacy switch, it is ok for me, we can call it.
But if it is jus a compile-time switch, it is almost the same as removal - I guess distributions will stick with defaults.

Anyway, just want to mention that there are some users of legacy algorithms ;-) Thanks.

**Comment by richsalz** [comment]
You are free to take the code and put it into your project. The question is whether it should be globally enabled and supported by openssl, given that the team has finite resources.

**Comment by mattcaswell** [comment]
I see no reason to remove it at this stage.

**Comment by t8m** [comment]
Also there should be a proper deprecation followed, so I do not think it should be done earlier than in 4.0.0.

**Comment by kroeckx** [comment]
It's been moved to the legacy provider

**Comment by GNUtoo** [comment]
> Please do not remove algorithms from a generic crypto library just because you do not know who use them. Thanks.

I've a real world example of a completely broken hash function.

I maintain a free software library (libsamsung-ipc) that implements a modem protocol found in various Samsung smartphones, which is also responsible of storing data on behalf of the modem. For that, using md5 (with special initialization data) is required by the modem firmware. And here a hash function doesn't give end users any security benefits at all. And writing a modem firmware to "fix" that would takes order of magnitude more resources than what we have.

I guess that there are many more not very well known examples like that were hashes are not used for security but we still need them for interoperability.

**Comment by mirage335** [comment]
Hey! Why is whirlpool hash unsafe? Just because it is fast? Use more iterations?

Whirlpool is already used in both quantum-resistant communications authenticated encryption and in disk encryption functions of 'coreoracle' software. This cannot be changed easily, without either greatly increasing the attack surface, or having physical access, or other means, all of which present serious added security risks in expected use cases. Examples:
https://github.com/mirage335/coreoracle/blob/main/fragKey#L18738
https://github.com/mirage335/coreoracle/blob/main/commKey#L17839

This is the second time I've noticed open issues to remove useful cryptographic primitives that must require a negligible amount of code to implement. Even if it is insecure, there are at least read-only use cases, as has been pointed out for the Truecrypt example. Recovering data from Truecrypt volumes years to decades later, as just another example, is not an uncommon scenario, it happens frequently.

**At this rate, I'll be promoting widespread adoption of an OpenSSL fork of my own. Please close this insanely absurd issue immediately.**

**Comment by paulidale** [comment]
The project currently has no intention of removing anything from OpenSSL.
Older weaker algorithms are moved to the legacy provider to discourage their use but that is very different from removal.

**Comment by mirage335** [comment]
Ok, but why is this issue still open then? Shouldn't the issue be closed?

**Comment by t8m** [comment]
I am closing this as Whirlpool should not be and is not going to be removed any time soon.
