### ISSUE TITLE
openssl doesn't download intermediate certificate

### ISSUE THREAD

**Issue by magicode** [openssl/openssl#5168]
i open issues in nodejs https://github.com/nodejs/node/issues/16336 maybe need to fix  it in openssl

this site  https://incomplete-chain.badssl.com/ configured without intermediate certificate.

In Google Chrome it work well. because Google Chrome does download the intermediate certificate. Now, the problem is, that since Chrome is by far the most popular browser, website owners configure their website to work in Chrome.
 
error with openssl  (unable to verify the first certificate)
`$ openssl s_client -servername incomplete-chain.badssl.com -connect incomplete-chain.badssl.com:443`

output 
```
...
Verify return code: 21 (unable to verify the first certificate)
```

in .net framework is work well.
example: https://dotnetfiddle.net/Th5M0c (c#)

in curl (base openssl) have error:
curl "https://incomplete-chain.badssl.com/"
>curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

All errors occur because there is no  intermediate certificate.

I download certificate from website incomplete-chain.badssl.com
`$ echo -n | openssl s_client -servername incomplete-chain.badssl.com  -connect incomplete-chain.badssl.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > incomplete-chain.badssl.com.crt`

I see the details
`$ openssl x509 -in incomplete-chain.badssl.com.crt -text -noout`

```
Certificate:
...
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, O=DigiCert Inc, CN=DigiCert SHA2 Secure Server CA
        Validity
...
            Authority Information Access: 
                OCSP - URI:http://ocsp.digicert.com
                CA Issuers - URI:http://cacerts.digicert.com/DigiCertSHA2SecureServerCA.crt

            X509v3 Basic Constraints: critical
....
```

in first certificate have link to intermediate certificate.
` CA Issuers - URI:http://cacerts.digicert.com/DigiCertSHA2SecureServerCA.crt`

I guess. Google Chrome. or .net framework. download this intermediate certificate. and check it.
openssl no download it.

today all major browser download intermediate certificate. chrome, edge , filefox ,explorer.

i checked it with wireshark.

in chrome or edge in windows fetch from link with  this headers
```
GET /DigiCertSHA2SecureServerCA.crt HTTP/1.1
Connection: Keep-Alive
Accept: */*
User-Agent: Microsoft-CryptoAPI/10.0
Host: cacerts.digicert.com
```

in chrome on linux
```
GET /DigiCertSHA2SecureServerCA.crt HTTP/1.1
Host: cacerts.digicert.com
Connection: keep-alive
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36
Accept-Encoding: gzip, deflate
```
this is url http://cacerts.digicert.com/DigiCertSHA2SecureServerCA.crt

**Comment by richsalz** [comment]
Thank you for all the detail.  This is not an OpenSSL issue.  OpenSSL does not provide a list of certs that it trusts (a trust store), that is up to the application to do so.

**Comment by magicode** [comment]
@richsalz  Your answer is not related to what I wrote.
I'm talking about the certificate verification process.
It does not include automatic completion of intermediate certificates from the URL found on the first certificate.

**Comment by richsalz** [comment]
It is up to the application to have all the certs it wants to trust, and to put them into the trust store that it is asking OpenSSL to use in validation.  OpenSSL will not go out and fetch intermediates as part of doing chain validation.

**Comment by magicode** [comment]
if root ca cert have in the trust store
Why would not openssl automatically fix the chain ?

**Comment by richsalz** [comment]
Because OpenSSL does not do any network activity "automatically" because of security concerns.  It is up to the application.

**Comment by kroeckx** [comment]
I think the point is that the server doesn't send the intermediate certificates, and so with the certificates the server sends you can't validate the server. As far as I know, browsers have 2 workarounds for this issue:
- Caching intermediate certificates
- AIA chasing: downloading the intermediates based on the what the other certificates say is the intermediate.

But OpenSSL currently doesn't do any of those things. It's currently up to the application to do those things. OpenSSL currently doesn't validate the chain, it's up to the application to call a function in OpenSSL to validate it.

That doesn't mean that OpenSSL can't be changed, but it would be part of larger changes, where OpenSSL would do all those things on behalf of the application so that all applications don't need to write that code.

**Comment by kroeckx** [comment]
I guess we do have an SSL_CTX_set_verify() ...

**Comment by richlv** [comment]
What about `openssl s_client`, it being "the application", should it handle the intermediate certificates?

**Comment by levitte** [comment]
Openssl commands are fairly simple tools, not designed to be full fledged http solutions. There are plenty of others that are more feature complete, such as curl, links,...

So s_client currently requires all applicable certificates to exist in a local store. Like is already said above, that could change, but it's not our top priority.

**Comment by CodeLife2012** [comment]
Maybe should add more doc for this.

**Comment by Amegatron** [comment]
Hi! Sorry if this is necro-posting, but since the problem is really common, I would like to share my suggestions.

On one hand I agree that OpenSSL should not auto-request intermediate certificates - it is beyond direct responsibility to validate the cert. But on the other hand, it's still OpenSSL's scope to know about root CA's. In other words, it's still OpenSSL who somehow accesses CA-storage, so it could validate the certificate.

Though I'm not really aware of OpenSSL internals, to me the problem here is that the resolution of a parent certificate is tightly coupled to filesystem-storage. In other words, it's not possible to have different certificate resolution mechanisms. But OpenSSL could abstract from this process. Filesystem could be only one of such exact mechanisms. Other mechanisms can either ship with OpenSSL itself, or be externally supplied as arguments, provided they implement an established interface.
