### ISSUE TITLE
How can I use "printf" in libcrypto.so

### ISSUE THREAD

**Issue by mrpre** [openssl/openssl#5171]
I found ```printf``` couldn't run well if it exists in libcrypto.so(no output in shell while using ```printf```), What is the cause?

**Comment by richsalz** [comment]
This is not an openssl issue.  OpenSSL does nothing with stdout, so printf should work normally. Maybe your application is doing something unusual?  Maybe you need to fflush as well?  Can you post more details, otherwise we should just close this.

*On a separate matter* can you please email me rsalz at openssl.org?  We are trying to reach you about your previous contributions to openssl.

Thank you.
