### ISSUE TITLE
How to use openssl with a third party webserver

### ISSUE THREAD

**Issue by xyuan240** [openssl/openssl#5220]
Hi, I am trying to enable ssl for moongoose webserver (a third party webserver framework), and I have successfully compiled openssl configured as VC-WIN64A(MSVC2008 ) with the your support (Thanks a lot!). 

The files and libs I included from openssl are:

libssl.lib
libcrypto.lib
headers under
openssl-root\include\openssl

However, there are still compiling error  such as:

%%%
undefined struct/union 'ssl_st'
undefined struct/union 'ssl_ctx_st'
%%%

I can see ssl_st is defined in ssl_locl.h under ssl/, which I have not included in my project. I wonder if there are some steps/guidance about integrating openssl in a self-contained project? Thanks in advance.

Regards

**Comment by mspncp** [comment]
Hello,

the header `ssl_locl.h` is not intended for private use. The contents of the structures are hidden and you need to use setter and getter functions to access them. This is an essential difference between OpenSSL 1.0.2 and 1.1.0.

It might be better to ask this type of question on the `openssl-users` mailing list. That way, you will reach a lot of programmers out there which use OpenSSL for their software and projects. So it is more likely that you get a helpful answer there. 

You can subscribe to the list here: https://mta.openssl.org/mailman/listinfo/openssl-users

Also, you can search the [OpenSSL Wiki](https://wiki.openssl.org) for answers.

**Comment by mspncp** [comment]
If you are new to OpenSSL and are just trying to compile it and use it together with other software, it is probably better to [download a stable release](https://www.openssl.org/source) instead of pulling a brand new developer copy from master. Note that 1.0.2 and 1.1.0 are incompatible due to the hiding of the structures, as mentioned before. If you use third party libraries, it is possible that they require version 1.0.2 and are not ready for version 1.1.0 yet.

**Comment by xyuan240** [comment]
thanks for the info
