### ISSUE TITLE
OPENSSL 1.1.1 -async performance

### ISSUE THREAD

**Issue by duadbsgh** [openssl/openssl#5241]
Hi 
I would like to know about openssl 1.1.1 performance.

openssl1.0.1m async + qat and When openssl 1.1.x async + qat is compared to per top, use cpu 55% both,
but, sha256_block_data_order used openssl 1.1.x more CPU resources.

result.
openssl 1.1.x async
14.46% libcrypto.so.1.1 [.] sha256_block_data_order
5.80% libc-2.23.so [.] _int_malloc
5.53% libcrypto.so.1.1 [.] AES_encrypt
4.48% libc-2.23.so [.] _int_free
3.95% libc-2.23.so [.] malloc
2.44% libc-2.23.so [.] __memset_sse2
1.77% ssl_proxy [.] ai_ip_cmp
1.56% libcrypto.so.1.1 [.] AES_decrypt

openssl 1.0.1m async
1.04% [kernel] [k] _raw_spin_lock
1.00% [kernel] [k] pdriver_packet_mirroring
0.95% [kernel] [k] update_cfs_shares
0.93% [unknown] [.] 0x00007f58e78415e9
0.91% [kernel] [k] _raw_spin_lock_irqsave
0.90% [unknown] [.] 0x00000000004e8e61
0.85% [kernel] [k] ixgbe_xmit_frame_ring

Do you know any of the above results?

Kind Regards,

**Comment by richsalz** [comment]
I assume you mean 1.1.0, but that is only on g not m.  1.0.1 is outdated, out of support, and doesn't have async or QaT support.

**Comment by levitte** [comment]
*ahem* there was an earlier version that had another type of async support than what we ended up doing for 1.1.0.  That one had its starting point in 1.0.1c.  QaT, as I recall, was an engine that worked as the live test case back then.

I know, because I developed that async support.

Now, @richsalz is entirely correct that it's out of support.  And quite frankly, while what I developed did work, the result is a bit fragile as I recall it.  The async support we put in 1.1.0 is much more flexible an robust, and it's quite possible that this comes at a performance prise (I haven't made any analysis, so I can't really tell).  That is to say, it's not entirely fair to compare the two purely on a performance basis.

**Comment by stevelinsell** [comment]
I think this question is very specific to the Intel Quickassist(QAT) Engine and the elements it offloads rather than the general OpenSSL async mechanism. For instance the amount of sha256 operations in the above profiles would depend on whether PRF operations are being offloaded to the engine.
The question has also been raised as part of another issue in the QAT Engine github repo here:
https://github.com/intel/QAT_Engine/issues/52
I think that is a more appropriate forum and propose that this issue here be closed.

**Comment by mattcaswell** [comment]
Closing this as per @stevelinsell's suggestion.

**Comment by leyao-daily** [comment]
Hi, @duadbsgh I want to use openssl async mode with QAT card. But I only can use this in command "openssl -engine qat -async_jobs 32 ...". How can I config openssl to use the async jobs by default. Thanks
