### ISSUE TITLE
Compile PHP 7.2.2 with openssl on macOS

### ISSUE THREAD

**Issue by xxalfa** [openssl/openssl#5263]
macOS 10.13.2
```
$ openssl version
LibreSSL 2.2.7
```
When I try to compile PHP 7.2.2 with openssl, I get these errors.
```
configure: error: Cannot find OpenSSL's <evp.h>
```
The following command solves the first problem.
```
$ cd /usr/local/include 
$ ln -s ../opt/openssl/include/openssl
```
Now I get this error.
```
Undefined symbols for architecture x86_64:
  "_X509_get_signature_nid", referenced from:
      _zif_openssl_x509_parse in openssl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/cli/php] Error 1
```
Then I do not understand why LibreSSL is installed. I would like to use openssl and did it with brew install openssl.

My wish is simply to use the latest version of PHP with openssl, so I'm in the right place.

**Comment by levitte** [comment]
Hmmm, I was sloppy in the previous issue.  This seems to be an issue with building PHP, and I'm sorry, this isn't quite the right place for that...

But, knowing a little about GNU's configuration style, I can suggest that you try the option `--with-openssl=/opt/openssl` (or whatever the path actually is) when you configure PHP.

I *am* closing this again, because as far as I can tell, *this is not an issue in building OpenSSL*
Please don't reopen another issue with this same content again.

**Comment by xxalfa** [comment]
Even now I can not understand why the problem is already closed again - how about if you would wait for a response. Thank you for pointing out, I will test it. If something is closed, that means to me, I can not answer anymore, that's why I created it again.

I would like to delete my two problems, but I can not find an option - why is not it possible?

**Comment by richsalz** [comment]
You got an answer.  This is an issue about how to configure and build PHP.  Go to one of those forums and say "i have libressl one the system, but I want to download and use openssl when building php; how do i do that?"

This is what Richard wrote; I just made it more clear.
