### ISSUE TITLE
SSL_get_shared_ciphers returns client ciphers not shared ciphers

### ISSUE THREAD

**Issue by noxxi** [openssl/openssl#5317]
Contrary to what the name suggests `SSL_get_shared_ciphers` returns the same ciphers as `SSL_get_client_ciphers`, i.e. the contents of `ssl->session->ciphers`.  The `ciphers` member of  `ssl_session_st`  is documented as follows:

      STACK_OF(SSL_CIPHER) *ciphers; /* shared ciphers? */

The question mark behind "shared ciphers" is there since at least 0.9.8 - and rightly so. Because this member contains at least in the current versions not the shared ciphers but all ciphers offered by the client. 

Given that `SSL_get_shared_ciphers` is used for example in apps/s_server.c the output from this app is misleading since it claims that the client provided ciphers are actually the shared ciphers. For example when using `s_server` with a restricted cipher set and connecting with a client offering a larger cipher set the output looks like this:

       $ openssl s_server -cipher 'AES128-SHA' -cert ...
       ....
       Shared ciphers:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:...AES128-SHA:...
       ...
       CIPHER is AES128-SHA

**Comment by mattcaswell** [comment]
This bug looks like its been present since the beginning of time. `SSL_get_shared_ciphers()` exists right back at the time of the original SSLeay import and the "shared ciphers?" comment exists then. Back then there was a comment in front of the `SSL_get_shared_ciphers()` function which said "works well for SSLv2, not so good for SSLv3". This comment only got removed when we removed SSLv2 support. Going back to a version that supported SSLv2 I see that SSL_get_shared_ciphers() *does* return the shared ciphers for SSLv2, but it never has (AFAICT) for SSLv3 and above.

So the question is what to do about it? Should we fix it? With such a long standing bug there is a risk that this will actually break applications which are coded to expect different behaviour. The intent of the function is clear though.

No matter what we should definitely fix that comment!!

**Comment by levitte** [comment]
Making it change behavior is possible... For openssl 1.2...

**Comment by richsalz** [comment]
For this release?  I disagree.  When we do fix it, we should probably add a new API (it will be hard to come up with a good name) and then remove this function, so in rel+2 we can bring back the "real" name.

**Comment by t8m** [comment]
I am with Matt here - the name clearly says what the function should return and it does not. For listing the client ciphers there is the SSL_get_client_ciphers(). And the SSL_get_shared_ciphers() is not even documented. Which of course does not mean that nobody can call it but depending on undocumented behavior when there is more appropriate function that is even documented is asking for breakage.

**Comment by mattcaswell** [comment]
I do think we should fix this now. But unless there is more support for that view from @openssl/committers it appears we won't get a consensus for that. If there are no more comments on this PR I'll change the milestone to 1.2.0 in a few days.

**Comment by vdukhovni** [comment]
I support changing the implementation.  Here are the OpenBSD docs FWIW:
https://man.openbsd.org/SSL_get_shared_ciphers.3

**Comment by t-j-h** [comment]
@mattcaswell it should be fixed

**Comment by mattcaswell** [comment]
I will create a PR for this. I'll make sure I give people an opportunity to object to it before merging.

**Comment by mattcaswell** [comment]
I created PRs #6113, #6114 and #6115 for this. If anyone objects to their inclusion please flag it in those PRs.
