### ISSUE TITLE
UNICODE

### ISSUE THREAD

**Issue by rrip** [openssl/openssl#5382]
Somehow UNICODE is now the default for VC builds.
I don't see a way of un-selecting it, as the VC-noCE-common configuration has no option.

**Comment by levitte** [comment]
*Now*?  It's been like that for ages, it's just as default in 1.0.2 and has before then as well as far as I remember.  So, errr, what do you mean with "now"?  Compared to when?

**Comment by rrip** [comment]
You are correct. I found it in 1.0.2 builds as well.

**Comment by dot-asm** [comment]
Just in case, in the context UNICODE affects the way OpenSSL library communicates with underlying Windows OS interface. But has no effect on OpenSSL interface observed by application code using the library. So why would one have it as option? *Earlier* it was an opt-in[!] option for VC-WIN32 target, but that was rather because *native* interface for Win9x was non-UNICODE. Now native interfaces on all *supported* Windows OSes are UNICODE, and there is no [need for] option even for VC-WIN32.
