### ISSUE TITLE
Segmentation fault in _bsaes_key_convert on X64 Linux - version  1.0.2k-fips

### ISSUE THREAD

**Issue by jimmyOIS** [openssl/openssl#5384]
Problem experienced on x64 Centos 7

OpenSSL 1.0.2k-fips  26 Jan 2017
built on: reproducible build, date unspecified
platform: linux-x86_64
options:  bn(64,64) md2(int) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DKRB5_MIT -m64 -DL_ENDIAN -Wall -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -Wa,--noexecstack -DPURIFY -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/etc/pki/tls"
engines:  dynamic 

Using function SSL_CTX_use_PrivateKey_file we get a seg fault in some programs. Problem appears to be alignment problem as described below:

File: crypto/aes/bsaes-x86_64.s

In the function	bsaes_cbc_encrypt

If rsp is not aligned on 16 byte boundary - when space is reserved on the stack for use by _bsaes_cbc_encrypt then seg fault occurs. 

	movl	%eax,%edx
	shlq	$7,%rax
	subq	$96,%rax
	subq	%rax,%rsp

	movq	%rsp,%rax
	movq	%r15,%rcx
	movl	%edx,%r10d
	call	_bsaes_key_convert

in the function _bsaes_key_convert

seg fault when rax is used as destination

	movdqa	%xmm7,(%rax)

Issue still exists in openssl-1.1.1-pre1.

**Comment by dot-asm** [comment]
> If rsp is not aligned on 16 byte boundary

Thing is that rsp is *required* to be aligned on 16-byte boundary by ABI specification. Which means that if it's found to be misaligned, then it should be viewed as ABI violation, and then the question would be who is to be held responsible. Trouble is that stack alignment is a "collective" effort, in sense that it's each subroutine's responsibility to maintain it. Which in turn means that if there is one subroutine in the call chain that misbehaves, it will ruin things for all successors in the call chain. Now, bsaes_cbc_encrypt preserves stack alignment, and _bsaes_key_convert is formally entitled to expect alignment suitable for movdqa. In other words it ought to be one of subroutines in backtrace that failed/didn't care to preserve compliant stack alignment. Since callers are compiler-generated, I'd consider a compiler bug...
