### ISSUE TITLE
Support bracketed equal-preference groups in SSL[_CTX]_set_cipher_list

### ISSUE THREAD

**Issue by rcombs** [openssl/openssl#541]
BoringSSL implemented this in https://boringssl.googlesource.com/boringssl/+/858a88daf27975f67d9f63e18f95645be2886bfb
This allows a server consumer to specify multiple cipher suites at the same level of preference, so the server can enable `SSL_OP_CIPHER_SERVER_PREFERENCE`, but also take the client's preferences into account when selecting one of several ciphers that are all equally preferred.
The upshot, as described in that BoringSSL commit message, is that the server can prefer AES-GCM and ChaCha20 equally. Android devices without hardware AES support put ChaCha20 first in their suite preference list, so with this feature, the server could select AES-GCM for clients with hardware support and ChaCha20 for ones without it, which optimizes performance for both cases.

**Comment by shigeki** [comment]
I also would like to have this feature. Firefox will prioritize ChaCha20/Poly1305 ciphers over AES-GCM for ARM builds like Chrome in https://bugzilla.mozilla.org/show_bug.cgi?id=1126830 . 
With the equal-preference group, we can make the most use of client performance for both AES-NI and ARM devices, not giving up using server preference of ciphers.

**Comment by richsalz** [comment]
I wanted it too, but we ran out of time. :(

**Comment by zh99998** [comment]
+1 for this request

**Comment by blblack** [comment]
@richsalz: I haven't tested the commit above thoroughly (or added new testsuite tests, either) yet, so there's a little more yet to go here.  Is there any chance this can still make 1.1.0 or is it far too late for something like this?  It's kind of a big pragmatic issue with using the new chacha20-poly1305 stuff in the real world (where only the client knows whether chapoly or aes-gcm is the better perf choice among AEADs).

**Comment by richsalz** [comment]
For a variety of reasons, it is not going to be in 1.1.

**Comment by blblack** [comment]
Planning a better overall mechanism maybe?  The one in BoringSSL is fairly limited in that it doesn't allowing nesting of ordered sets within un-ordered preferences, etc.  It **would** be nice to do something more-general in terms of expressiveness, but probably a lot more invasive as well.

**Comment by richsalz** [comment]
I think the whole CIPHER syntax needs to be reviewed, especially with TLS 1.3 requirements.

**Comment by MichalStaruch** [comment]
@blblack We shouldn't fixate on any specific algorithms here, so I think OpenSSL should rather incorporate changes made for BoringSSL by @agl - syntax extension introduced in BoringSSL ([AES256|CHACHA20]) looks reasonable to me. And grouping ciphers is nice, flexible approach that can be still useful in future, when we move to different algorithms.

@richsalz Please consider incorporating this feature in 1.1 line. We have CHACHA20 now, and this change would allow to deploy configurations that are good for both desktop and mobile worlds. You can find good summary why we need it in [this article](https://www.zeitgeist.se/2014/08/23/optimize-aes-and-chacha20-usage-with-boringssl/). I wouldn't wait with this for TLSv1.3.

**Comment by richsalz** [comment]
Unfortunately, we didn't get to it for 1.1.0 and since it's a feature, not a bug-fix, it will have to wait for the next release.  Yes this is a pain.

**Comment by MichalStaruch** [comment]
@richsalz I didn't expect new syntax to come in 1.1.0a as bugfix - but adding it to master, and releasing in not so distant future as 1.1.1 looks both worthwhile and possible.

**Comment by richsalz** [comment]
Agreed.  But the syntax is still TBD.  E.g., TLS 1.3 might have additional requirements/desires.

**Comment by lukastribus** [comment]
You guys are actively working on TLS 1.3 right now; I assume you are not expecting any additional changes in TLS 1.3 which would further block this important enhancement?

**Comment by richsalz** [comment]
One possibility is that the cipher strings for TLS 1.3 are not specifiable, except perhaps via set-flags type of API.

**Comment by lukastribus** [comment]
Hardcoding the preference of single cipher suites like NSS, is that what you are saying?

**Comment by richsalz** [comment]
There are three ciphers and so maybe just do client preference.  I'm not committing to anything, just pointing out that we might not have/need to specify ciphers for tLS 1.3. In particular, having TLS 1.3 merged into the old cipher syntax is... ugly.

**Comment by rcombs** [comment]
For some context, in 1.3, BoringSSL prefers ChaCha if AES hardware is unavailable, and otherwise just goes with the client preference.
It's probably reasonable to still want a way to _blacklist_ cipher suites in 1.3 in case of some future vulnerability being discovered (I'm not sure what BoringSSL does here), but I'm not sure if the ordering mechanism still makes sense in the absence of legacy ciphers.
One thing that might make sense for both legacy and 1.3 is to provide a "callback" API, where the consumer provides a function pointer that takes a client's preferred list and returns its choice, with the default callback having sane behavior (ChaCha if either client prefers it or no AES hardware, then AES AEAD suites, then legacy in the string order). That should be pretty simple and future-proof. Thoughts?

**Comment by davidben** [comment]
BoringSSL does not currently have APIs to blacklist TLS 1.3 cipher suites or whatever else, as Rich is suggesting. But, yes, we do prefer ChaCha if the server lacks AES hardware. (This is unlikely for a typical web server deployment, but may come up in use cases like WebRTC.) Adding such APIs would be easy enough, but the need hasn't come up.

**Comment by rcombs** [comment]
(You'd be surprised; my use-case often involves armv7 NAS devices, and that'll probably grow a bit with IoT stuff until armv8 takes over)

**Comment by richsalz** [comment]
I am *not suggesting anything.*  I am saying *we might not do this.*  That is all.

**Comment by rcombs** [comment]
I'm not super attached to this specific syntax/API concept, but having _some_ way to give ChaCha20 to 1.2 clients without AES hardware is pretty significant for perf, whether it's via this, or a callback, or a flag for a hardcoded check, or something else.

**Comment by richsalz** [comment]
If the server picks the clients first cipher, that does it.

**Comment by lukastribus** [comment]
By not setting SSL_OP_CIPHER_SERVER_PREFERENCE, giving up server preference for TLS 1.[0-2].

**Comment by richsalz** [comment]
Or by doing it in the code directly for *only 1.3*

**Comment by lukastribus** [comment]
I don't think giving up server preference in any TLS version is a good idea.

Just because we have a small number of cipher suites in TLS 1.3 right now doesn't mean there will never be any need for server side preference.

Google is deploying post quantum test suites in their Chrome canary builds [1] right now, and I don't see that the current TLS 1.3 suites will stay as-is in the coming years. We are gonna need an option to negotiate what works best, for both server and client.

I think suite negotiation and its flexibility is gonna stay a crucial element, even in TLS 1.3.


[1] https://github.com/ssllabs/ssllabs-scan/issues/384

**Comment by blblack** [comment]
I'm not exactly sure where all the related conversations stand, maybe this isn't the most-appropriate forum, but I thought I'd add a $0.02 here about server/client cipher lists/selections and TLSv1.3:

Even with just the 3 ciphers TLSv1.3 has today, server operators are going to have performance and/or security-evaluation reasons to differ from each other in their ciphersuite preferences.  I think I could construct a legitimate argument from such preferences for any of the possible 6 orderings  of the 3 initial ciphers, depending on your evaluation of AES batch-attack risks, AES-GCM-vs-ChaPoly security, the performance of client and/or the server, your particular site's user-agent mix, the types of CPUs your servers use, etc.

We want to have these server preferences while also, sometimes, allowing for clients to make a performance choice in their own list when it makes sense for the server operator (equal-pref groupings).  These arguments are further bolstered by the fact that the future is an unknown.  We don't yet know what other ciphers will be added to TLSv1.3, and we don't yet know which current ciphers may fall or be weakened by some new analysis in the coming years.

The only adequate alternate proposal I've seen to equal-pref grouping is to use callbacks so that the server code (e.g. haproxy, nginx, etc) can do its own custom magic evaluation of client-v-server preferences.  While this **does** provide the necessary level of flexibility, I think it would be a shame to foist this down on all of the N (N is quite large) OpenSSL-using server codebases to each implement these features via callbacks in divergent ways and possibly with overly-complex configuration mechanisms to expose that full generality to the administrator.

Equal-pref grouping is much simpler.  It can be documented easily, it does the Right Thing, administrators aren't going to be baffled by it, and server implementations get it for free as part of cipher pref string parsing.

**Comment by richsalz** [comment]
Where it stands right now is: we don't have plans to implement it.  The Google "cipher equivalence" thing is a cute hack but has limitations as described elsewhere (can't use @STRENGTH? I forget) and it adds to a cumbersome syntax.

**Comment by MichalStaruch** [comment]
@richsalz Having grouping with limitations sounds much better than not having it at all, TBH. And it's already implemented in BoringSSL, so it should be pretty compatible and easy to port.

**Comment by kaduk** [comment]
```SSL_OP_PRIORITIZE_CHACHA``` landed in #4436 but that pull request also got some discussion about what the optimal path is going forward.  I've opened #5050 for the more general question, without presuming a specific solution, and will close this one in favor of 5050 -- please feel free to add proposals and discussion there!
