### ISSUE TITLE
PPC64 Link problems on AIX

### ISSUE THREAD

**Issue by noloader** [openssl/openssl#5456]
Link issue on GCC119. Too much output to paste on GitHub and Pastebin.

[failed-link.zip](https://github.com/openssl/openssl/files/1755342/failed-link.zip)

**Comment by dot-asm** [comment]
Output from make -jN is not exactly helpful as it's impossible to navigate among multi-line outputs from different programs. Submit output from make without -j argument. You claim an error, but the only *error* message there is is "interrupted system call", as if ^C was pressed. And if it was something else, then it still sounds rather as external problem that we can't be held responsible for. If you are alarmed by duplicate symbol warnings, you have to keep in mind that those are *warnings*. And since vendor or any of AIX users didn't claim that this poses a problem, it's assumed benign. After all, `make test` does pass. If you claim it's a problem, then present a test case. [On related note it's not unlike that majority of AIX users prefer vendor compiler, and there are no warnings if you use xlc.]
