### ISSUE TITLE
PPC64 Link problems on Linux

### ISSUE THREAD

**Issue by noloader** [openssl/openssl#5457]
Link issue on GCC112. Too much output to paste on GitHub and Pastebin.

[failed-link.zip](https://github.com/openssl/openssl/files/1755385/failed-link.zip)

**Comment by dot-asm** [comment]
Output from make -jN is not exactly helpful as it interleaves errors and it's impossible to attribute them to specific command. So I'd suggest to submit logs from make without -j. But in this case it's possible to tell what's the problem, because all errors point in same direction, assembly modules. One can also see that commands generating them are *not* suitable to gcc112. Specifically perlasm_scheme, it should be linux64le for gcc112. Output suggests that you've executed `./Configure linux-ppc64` manually. When you do so, you become accountable for choosing correct target, and correct target for gcc112 is linux-ppc64le. I'd suggest to stick with ./config.

**Comment by noloader** [comment]
> Output suggests that you've executed ./Configure linux-ppc64 manually.

Yes. That's because configure detected again. It detected 32-bit platform, not a 64-bit one.

For the love of Christ can you please fix that broken fucking configure program.

**Comment by dot-asm** [comment]
> It detected 32-bit platform, not a 64-bit one.

There is no 32-bit option on ppc64le platform, and gcc112 *is* detected as linux-ppc64le by ./config. As for the rest, get less emotional, collect your thoughts, and make suggestion :-)

**Comment by levitte** [comment]
> There is no 32-bit option on ppc64le platform

.... but @noloader isn't talking about ppc64*le*

Now, @noloader, have you possibly set the environment variable `KERNEL_BITS`?  If you have and the value is 32, then you have effectly *told* `./config` that you do want 32-bit platform.

**Comment by levitte** [comment]
> Now, @noloader, have you possibly set the environment variable `KERNEL_BITS`?

Never mind that question...  I misread the code.  It's true that `./config` defaults to 32-bit, i.e. `linux-ppc`...  Setting `KERNEL_BITS=64` makes it choose `linux-ppc64` instead.

**Comment by levitte** [comment]
(and mind you, I agree that it seems weird to default to a 32-bit build on a 64-bit platform.  It's not intuitive)

**Comment by dot-asm** [comment]
> .... but @noloader isn't talking about ppc64le

Yes, he does. gcc112 is ppc64le system and assertion that it was detected as 32-bit is unsubstantiated. What is more likely to happen is that he got angry with big-endian system [where 32-bit would indeed be offered as default] and copy-n-pasted config command between two systems...

**Comment by dot-asm** [comment]
> (and mind you, I agree that it seems weird to default to a 32-bit build on a 64-bit platform. It's not intuitive)

One can blame OpenSSL for being overly conservative, nothing wrong with that, blaming that is. I only suggest to put emotions aside.
