### ISSUE TITLE
Portable edition?

### ISSUE THREAD

**Issue by arc95** [openssl/openssl#5479]
Hi! Is there a portable version of OpenSSL which doesn't require installation? Thanks.

**Comment by richsalz** [comment]
The project only distributes source.  See https://wiki.openssl.org/index.php/Binaries for third-party packages.

**Comment by C0nw0nk** [comment]
@pedroalbanese 

I grabbed direct-dl's since your redirect page from sourceforge annoyed me. Hope you or others find it useful.

https://deac-ams.dl.sourceforge.net/project/openssl-for-windows/OpenSSL-1.1.1h_win32%28static%29%5BNo-GOST%5D.zip
https://kumisystems.dl.sourceforge.net/project/openssl-for-windows/OpenSSL-1.1.1h_win32(static)[No-GOST].zip
https://deac-fra.dl.sourceforge.net/project/openssl-for-windows/OpenSSL-1.1.1h_win32(static)[No-GOST].zip
https://netcologne.dl.sourceforge.net/project/openssl-for-windows/OpenSSL-1.1.1h_win32(static)[No-GOST].zip
https://altushost-swe.dl.sourceforge.net/project/openssl-for-windows/OpenSSL-1.1.1h_win32(static)[No-GOST].zip
https://netix.dl.sourceforge.net/project/openssl-for-windows/OpenSSL-1.1.1h_win32(static)[No-GOST].zip
https://deac-riga.dl.sourceforge.net/project/openssl-for-windows/OpenSSL-1.1.1h_win32(static)[No-GOST].zip
https://pilotfiber.dl.sourceforge.net/project/openssl-for-windows/OpenSSL-1.1.1h_win32(static)[No-GOST].zip
https://cfhcable.dl.sourceforge.net/project/openssl-for-windows/OpenSSL-1.1.1h_win32(static)[No-GOST].zip
https://versaweb.dl.sourceforge.net/project/openssl-for-windows/OpenSSL-1.1.1h_win32(static)[No-GOST].zip
https://phoenixnap.dl.sourceforge.net/project/openssl-for-windows/OpenSSL-1.1.1h_win32(static)[No-GOST].zip
https://jaist.dl.sourceforge.net/project/openssl-for-windows/OpenSSL-1.1.1h_win32(static)[No-GOST].zip
https://ufpr.dl.sourceforge.net/project/openssl-for-windows/OpenSSL-1.1.1h_win32(static)[No-GOST].zip

Usage for other projects you submit.
`https://deac-ams.dl.sourceforge.net/project/ PROJECT_NAME / FILE_NAME`

Grab other locations to start as subdomain `https:// LOCATION .dl.sourceforge.net/project/ PROJECT_NAME / FILE_NAME`
https://sourceforge.net/settings/mirror_choices?projectname=openssl-for-windows&filename=OpenSSL-1.1.1h_win32(static)[No-GOST].zip&selected=autoselect

**Comment by pedroalbanese** [comment]
Caution! Do not click on the links above.

**Comment by pedroalbanese** [comment]
@C0nw0nk I didn't understand what you meant, but I agree with you 100%.
