### ISSUE TITLE
symbol lookup error: openssl: undefined symbol: i2d_DHxparams

### ISSUE THREAD

**Issue by modfiles** [openssl/openssl#5480]
Hi, I have compiled version 1.0.2n in rasperry and everything went well and no error or whatsoever.
But everytime i run 
`openssl version`
it always shows
`symbol lookup error: openssl: undefined symbol: i2d_DHxparams`
and all updates that requier or need updates and https qurries seems broken

**Comment by levitte** [comment]
`i2d_DHxparams` doesn't exist in 1.0.2, so it seems that the `openssl` command is a later version.  What did you do exactly?

**Comment by mspncp** [comment]
Richard, it seems like i2dDHxparams does exist in 1.0.2, see [libeay.num](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/util/libeay.num#L4319). The annotations say it was introduced in 79e75e04ea9.

**Comment by levitte** [comment]
Yup, sorry, my bad, I temporarly had 0.9.8j checked out in my 1.0.2 workspace.  D'oh

**Comment by modfiles** [comment]
i just did what install file said
./config --prefix=/user
make
make test
make install

make test passed and no error before i proceed to make install

**Comment by mspncp** [comment]
My guess is that you have different versions of `libcrypto.so` on your computer and that the one that is loaded does not match your `openssl` binary. You can find whether this is the case using the commands below:

```
$ which openssl
/usr/bin/openssl

$ ldd /usr/bin/openssl
        linux-vdso.so.1 (0x00007ffe679a8000)
        libssl.so.1.0.0 => /usr/lib64/libssl.so.1.0.0 (0x00007fc5dc217000)
        libcrypto.so.1.0.0 => /usr/lib64/libcrypto.so.1.0.0 (0x00007fc5dbdd9000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fc5dba2a000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fc5db826000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fc5db60f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc5dc486000)
```

**Comment by modfiles** [comment]
thanks for the reaponse. this is the result of ldd but i have no idea if its the correct version needed by 1.0.2n
please do note that im running it on raspberry jessie lite
```
pi@raspberrypi:~ $ ldd /usr/bin/openssl
        /usr/lib/arm-linux-gnueabihf/libarmmem.so (0xb6f0d000)
        libssl.so.1.0.0 => /usr/lib/arm-linux-gnueabihf/libssl.so.1.0.0 (0xb6eab000)
        libcrypto.so.1.0.0 => /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0 (0xb6d3d000)
        libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xb6d2a000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6be9000)
        /lib/ld-linux-armhf.so.3 (0x7f617000)
```

**Comment by mspncp** [comment]
You can use the following `find` command to list all library instances with their md5 hash
```
$ find /usr/lib* -name 'libcrypto.so*' -type f -exec md5sum {} +
940dce214a0925cba74db1807cbbeded  /usr/lib32/libcrypto.so.1.0.0
e7c73ca6abf33cab5922f2ca88621ea2  /usr/lib64/debug/usr/lib64/libcrypto.so.1.0.0.debug
7ee2ddcd28e50514f57cec4e66826817  /usr/lib64/debug/usr/lib32/libcrypto.so.1.0.0.debug
b59636f9e7f1b8021a1d943afc754614  /usr/lib64/libcrypto.so.1.0.0
```

Now compare them with your source tree (edit the path below) and you will know which one is yours.
```
$ find /home/msp/src/openssl-1.0.2/ -name 'libcrypto.so*' -type f -exec md5sum {} +
5ab327a5251da2c43387623b703ca0e6  /home/msp/src/openssl-1.0.2/libcrypto.so.1.0.0
```

**Comment by mspncp** [comment]
The example above does not show a match, because my development version is installed in `/home/msp/install/openssl-1.0.2` instead of `/usr/lib*`. But there it is, indeed:
```
$ find /home/msp/install/openssl-1.0.2  -name 'libcrypto.so*' -type f -exec md5sum {} +
5ab327a5251da2c43387623b703ca0e6  /home/msp/install/openssl-1.0.2/lib/libcrypto.so.1.0.0
```

**Comment by modfiles** [comment]
im wondering if its normal to have 2 libcrypto directory?
```
$ find /usr/lib/ -name 'libcrypto.so*' -type f -exec md5sum {} +
21cbc392ee75e8584e898b09c0d0dca5  /usr/lib/libcrypto.so.1.0.0
bb164168bb28797bb69e6bfa05cea967  /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
```

**Comment by mspncp** [comment]
My guess: The first of the two is the library you built and installed manually, the second one is the one that was preinstalled with your linux distribution. Just check the library dates  (replace `md5sum` by `ls -l` in the find command).

The interesting questions in the first place are:

1. Which version of OpenSSL is preinstalled on your Raspberry Pi?
2. Do you _really_ need to build your own OpenSSL copy replace the preinstalled one? Why?

Maybe 2. was not your real intention. If not, then it's maybe better to find out how you can update the preinstalled OpenSSL installation using the package manager of your distribution.

If you really intend to do it, then you will probably have to take care that you are using the same toolchain (`arm-linux-gnueabihf`) and that the shared libraries are installed into the proper location.

For question like this, it is actually much better to post them to the [openssl-users](https://mta.openssl.org/mailman/listinfo/openssl-users) mailing list. If you are lucky, there will be other OpenSSL users that already solved your problem or know how to fix it.

Closing, because this is not an OpenSSL issue.
