### ISSUE TITLE
BN_mask_bits's error case doesn't make sense and is architecture-dependent

### ISSUE THREAD

**Issue by davidben** [openssl/openssl#5537]
`BN_mask_bits`'s documentation says:
> An error occurs if `a` already is shorter than `n` bits.

However the implementation only checks words, not bits:
https://github.com/openssl/openssl/blob/72983c0eab750dfc1b6298c516df7afb1a73ba54/crypto/bn/bn_lib.c#L650-L651

This means it is inaccurate and in an architecture-dependent way. However, it also does not make much sense to have this as an error case. Indeed, looking through Debian code search, these are the callers which actually check the return value:
1. https://sources.debian.org/src/u-boot/2018.01+dfsg1-2/lib/rsa/rsa-sign.c/?hl=537#L537
2. https://sources.debian.org/src/bobcat/4.08.02-2/bigint/maskbits.cc/?hl=5#L5
3. https://github.com/openssl/openssl/blob/72983c0eab750dfc1b6298c516df7afb1a73ba54/crypto/dsa/dsa_gen.c#L202
4. https://github.com/openssl/openssl/blob/72983c0eab750dfc1b6298c516df7afb1a73ba54/crypto/dsa/dsa_gen.c#L476

1, 3, and 4 would do the wrong thing were that behavior ever triggered. (Though it seems unlikely to trigger in each of these cases.) 2 is just a thin wrapper over OpenSSL, though I would be surprised if it too were expecting this behavior.

Rather, I suspect this was just a typo from SSLeay which got memorialized in dd8dec69b825c9fdafc26a200961702d850496b5. If one changes the branch to say `return 1`, it makes much more sense.

(Fortunately, `BN_mask_bits` also does not allocate, so one may as well pretend it returns `void`.)

**Comment by davidben** [comment]
> Though it seems unlikely to trigger in each of these cases.

(Well, 1 doesn't appear to ever work for large exponents, but RSA public exponents aren't supposed to get that big...)

**Comment by mattcaswell** [comment]
I'm not sure we can just declare that the documented behaviour would make more sense if it did something else. We have plenty of APIs that don't make a lot of sense, but we're stuck with them :-). Shouldn't we just fix things so that it returns an error as per the documentation, and in a non-architecture dependent way?

**Comment by davidben** [comment]
I mean, it's also possible that existing code relies on the current "buggy" behavior in that it actually wants the natural behavior, but doesn't notice because the architecture-specific approximation of the documented behavior makes triggering it low-probability. The return value appears to be a disaster however you slice it.

**Comment by mattcaswell** [comment]
Good point. Which leaves us with 3 options I think:

1) Change the behaviour to return 1. Pros: Makes the most sense from what you might expect the function to do, Cons: Goes against the long standing documented behaviour; could break stuff relying on that documented behaviour (although that behaviour doesn't work in many cases...so maybe not?)

2) "Fix" the behaviour to return 0 in a non-architecture specific way: 1. Pros: Fixes things so that the implemented behaviour matches the documented behaviour 2. Cons: Could break stuff expecting the "natural" behaviour that has never triggered the lower probability documented behaviour.

3) Leave it as is and document the issue (Possibly fixing it with (1) for 1.2.0).

**Comment by richsalz** [comment]
I vote for option 3 -- fix it by documenting.  If we want, add a new API that has the "right" return values.  What's needed for 1.1.1?

**Comment by mattcaswell** [comment]
Not a 1.1.1 specific issue so removing that milestone.

**Comment by erbsland-dev** [comment]
@t8m I analyzed the current HEAD and found that this issue still persists.

I can create a PR to address this situation.

If I understand the problem correctly, here is my proposed solution for the PR:
- Add a note/warning to the documentation of the original function, indicating that the error condition depends on the platform's word size and that the return value of the function can safely be ignored.
- Since the `BN_num_bits` function is available, users can perform a precise check of the number of bits before calling the `BN_mask_bits` function if necessary.
- Providing a new function for a precise error check seems unnecessary. The precise check isn't typically needed in most cases when the function is called.

**Comment by t8m** [comment]
> @t8m I analyzed the current HEAD and found that this issue still persists.
> 
> I can create a PR to address this situation.
> 
> If I understand the problem correctly, here is my proposed solution for the PR:
> 
>     * Add a note/warning to the documentation of the original function, indicating that the error condition depends on the platform's word size and that the return value of the function can safely be ignored.
> 
>     * Since the `BN_num_bits` function is available, users can perform a precise check of the number of bits before calling the `BN_mask_bits` function if necessary.
> 
>     * Providing a new function for a precise error check seems unnecessary. The precise check isn't typically needed in most cases when the function is called.

Yes, this is a good proposal.
