### ISSUE TITLE
ENHANCEMENT: Allow handshake and application data across memory spaces.

### ISSUE THREAD

**Issue by FGasper** [openssl/openssl#5552]
I have an application where I’d like to:

1) Negotiate a WebSocket connection (requires HTTP and SHA1 logic) over TLS
2) exec() to a separate binary
3) resume the WebSocket over TLS

Based on [a recent openssl-users thread](https://mta.openssl.org/pipermail/openssl-users/2018-March/007659.html), this doesn’t appear to be possible currently with OpenSSL because the renegotiation after exec() would need to happen over the same encrypted channel that was established prior to the exec().

Would it be feasible to implement? Or what am I missing?

**Comment by mattcaswell** [comment]
Your terminology is a little confusing. *Resumption* of sessions across memory spaces is already possible - but what you describe is not resumption.

Session resumption is the process of initiating a new connection (with an associated abbreviated handshake) that reuses some of the cryptographic and other parameters from an earlier connection.

From the sound of it you would like to do the handshake in one binary and  the application data transfer in another? Is that correct? You also mention renegotiation which is something else again...did you really mean renegotiation?

**Comment by FGasper** [comment]
> From the sound of it you would like to do the handshake in one binary and the application data transfer in another?
^^ Yes, this is what I would like to do.

I’m sorry for my imprecise terminology before; I’m not really sure what the underlying TLS mechanics to make this possible would look like.

**Comment by mattcaswell** [comment]
In order to do this we would need to serialise (some of?) the state in the SSL object, with an associated de-serialisation on the other side (in much the same way as we can do now with the SSL_SESSION object). The application would have to handle the transfer of the underlying transport. This is a significant piece of work and very definitely non-trivial - although technically feasible.

It's not clear to me how much of the SSL object state we would need to transfer and how much we could get away without. There would be problems around the parent SSL_CTX (would we serialise that too, or associate the SSL object with a new SSL_CTX at it's destination? Probably the latter). Any callbacks etc registered in the SSL would probably be lost so it would be up to the application to handle that if it needed them.

It sounds like an interesting feature, but unlikely to get any dev team attention in the foreseeable future. PRs might be considered that add this.

**Comment by richsalz** [comment]
I really think the honest thing to do is close this.  As a work-around you can do the handshake, get a session ticket, and then pass that to the other process to open the connection and resume that way.  Or look at the QUIC-style export stuff.

**Comment by FGasper** [comment]
The underlying transport (i.e., the TCP socket) is no biggie; I’m just not sure of what specifically needs to be preserved/serialized for TLS.

I initially thought (going by various guides to the handshake mechanism that I’ve found) that I could just send a new ClientHello, and everything would “just work” (or the equivalent for server-side), but as you observe, the new handshake does still need some context from before.

I’d work on it if I felt like I understood more of the protocol mechanics, but from where I am now I sense that it would be a bit too much stabbing-in-the-dark.

**Comment by richsalz** [comment]
The more that I think about this, the more strongly I believe that we will not expose the SSL state so that it can be exposed and shared across different processes.  This also runs into maintainability issues, imagine the parent has static-linked with one version of the library and the child is a different one.

What needs to be preserved and serialized is the TLS session.  Anything else we're not going to do.  We just spent a great deal of effort making things opaque and this would be a step backwards.

I am closing this.
