### ISSUE TITLE
Don't OPENSSL_CLEANSE stack variables

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#5585]
We spend too much time in openssl_cleanse.  I think we should not call it on stack-local variables, only heap data.

**Comment by levitte** [comment]
... 'cause when on the stack, it can't be sensitive data?

**Comment by richsalz** [comment]
@dot-asm can talk to this point with tech details, but stack data is kind of silly to protect against.

**Comment by dot-asm** [comment]
> @dot-asm can talk to this point with tech details, but stack data is kind of silly to protect against.

??? I feel that you're putting words in my mouth. I am [saying](https://github.com/openssl/openssl/issues/5559#issuecomment-371881202) that reason for why we cleanse is somewhat "schizophrenic", but I'm not  putting *any* weight on what's more important to cleanse, stack or heap. I can subscribe to assertion that cleansing stack is more expensive(*), but it doesn't mean that I'd consider it any more "silly" than cleansing the heap. One can argue that stack is more dynamic and secret material is swiftly overwritten, but one can as well argue that secret material is more readily available to inadvertent picking up on the stack. Indeed, all application code needs to do is to call own over-optimized subroutine right after libcrypto one. While in order for such subroutine to accidentally pick data from heap it would need a pointer and more or less conscious out-of-bound indexing...

(*) because it's excessive, each subroutine does over and over, when it would be more than sufficient if only last one did, e.g. one on the boundary to application code; because calls are often chained when they could be coalesced;

**Comment by dot-asm** [comment]
Though if you think about it, one can probably say following. De-facto[!] we don't really care about **shreds** of secret key material. Indeed, we are not even in position to trace register holding 32 bits of say AES key schedule being spilled on stack. So why would we care about any other **intermediate** vector? The difference between the two is that we have a pointer to the latter and can call OPENSSL_cleanse on it. Otherwise it's too just a **shred** that is not usable by its own. Or in other words one can probably say that intermediate data that is **not directly usable** outside current process boundary, doesn't have to be cleansed that scrupulously. But even so, it's not actually stack vs. heap. Yes, we are more likely to keep intermediate data on stack than in heap, but you can't really formulate it "no cleansing on stack".

**Comment by levitte** [comment]
So one could conclude that "Don't OPENSSL_cleanse intermediate values" might be a more appropriate title, is that it?

**Comment by mspncp** [comment]
Which is obviously a false strategy when it comes to the intermediate values of a Diffie-Hellman key exchange. Intermediate values are just as precious as the final results.

**Comment by richsalz** [comment]
Sorry for mis-remembering, @dot-asm.

**Comment by dot-asm** [comment]
> obviously a false strategy

Trouble here is that there is nothing actually obvious here. Starting with threat model. I mean what is it that we are trying to protect against? We do have *complete* trust to *all* code that is executed in current process context. It's argued that some code might *inadvertently* leak some information across the boundary. Or in other words we are trying to protect against *benign* code. And right there we have a logical contradiction. And I'd say that since we can't actually formulate the objective, we can't determine what is actually the right thing to do. We just do *something* and claim that it helps. And natural side effect is that we can't tell what we can stop doing [when we find it excessive]. It's kind of a trap...

Is there *anything* one ca do? Every little bit helps. Optimize by [coalescing](https://github.com/openssl/openssl/pull/5427#discussion_r172442197) OPENSSL_cleanse calls. Search for cases of double-cleansing... And why not consider option of trusting compiler to not optimize away memset [and at the same time to inline it]? As for last part. I know it's controversial, but it's only controversial if you formulate it as "is there any *one* thing I can do that would work with *any* compiler". But what if it's established fact that specific compiler at hand does not optimize away memsets? Wouldn't it be appropriate to provide an option to override **a chosen subset of OPENSSL_cleanse calls**? What would be the benefit? As long as call is inlined compiler would be in position to determine minimal amount of instructions (including vector ones;-), hopefully with no branches [and of course no subroutine call overhead]. Thing is that calls to OPENSSL_cleanse do have overhead (of call itself and very likely mispredicted branch overhead, because length is changing all the time) and this overhead can be comparable to operation itself. Because it's often called on short inputs.

**Comment by bernd-edlinger** [comment]
I don't know if that is relevant, but NIST SP 800-56Br1 states for instance in paragraph 5.5.3:

"A  routine  that  implements  a  key-derivation  procedure  specified  in  [SP  800-135] 
shall destroy any local copies of sensitive input values, as well as any other locally stored values used 
or  produced  during  its  execution  (including  any  local  copies  of  portions  of  the  derived  keying 
material).  Their  destruction shall occur  prior  to  or  during  any  exit  from  the  routine
– whether exiting early because of an error or exiting normally, with the output of keying material."

**Comment by paulidale** [comment]
I'd consider that relevant.  Sensitive values should be zeroed as a matter of course.
I don't mind the suggestion by @dot-asm that these can be coalesced but that will require more work figuring out and be moire error prone.

**Comment by paulidale** [comment]
I've added the won't fix label.  I don't see a consensus leaning towards leaving secrets on the stack.
