### ISSUE TITLE
run-checker broken

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#5609]
The main `config -d --strict-warnings` build in run-checker is failing (which I think means none of the rest of the builds run??).

`git bisect` reckons the culprit is something in #5534.

Ping @levitte.

**Comment by kaduk** [comment]
Looks like ```BIN_CFLAGS``` are not getting ```$config{cflags}``` but our override to pass ```-Qunused-arguments``` for clang is adding to ```$config{cflags}``` and not ```$target{cflags}```

**Comment by levitte** [comment]
The issue is actually that `-Qunused-arguments` gets added to `$config{cflags}` *before* the devteam warnings, which means there's a `-Wall -Wextra` getting added after it...  Fix coming up

**Comment by levitte** [comment]
Argh, red herring...  `-Qunused-arguments` is about things passed on the command line, not about C code.  From `man clang`:

```
       -Qunused-arguments
              Do not emit any warnings for unused driver arguments.
```

I believe the actual reason is this, in `linux-x86_64-clang`:

``` perl
        CFLAGS           => add("-Wextra"),
```

Since that's a default user flag (ending up in `$config{CFLAGS}`), which ends up in `$(CFLAGS)` in Makefile, it gets added last in `BIN_CFLAGS`.

Now, quite frankly, I wonder why we have `-Wextra` in the default user flags...  I suspect it's an oldie from before we had `--strict-warnings`...  It should be removed, really...

**Comment by levitte** [comment]
#5612 contains the fix.

It surprises me a little bit that this wasn't caught by Travis...  Ah, of course, we only use clang on Darwin, which doesn't come with the same flags...
