### ISSUE TITLE
how i get opnesl.ld file each library version?

### ISSUE THREAD

**Issue by KyoungJoonKim** [openssl/openssl#5642]
i am compiling openssl library.
i want add .gnu.version_d information.
so i did find openssl.ld file(example : https://gist.github.com/Scottmitch/71a89d98b3af272aab6ae6bfed122c5a) but i not found openssl.ld file.
how i get openssl.ld file each library version?

**Comment by kaduk** [comment]
What version of OpenSSL are you compiling, and where do you get your sources from?

The normal place we hear about openssl.ld files is when the Debian packaging's build system is used; in that case, you might be better served by ```apt-get source openssl``` and making your modifications there, rather than trying to start from unmodified upstream OpenSSL (which is what this github repository is for).

**Comment by mattcaswell** [comment]
Does not appear to be an OpenSSL problem. Closing this.
