### ISSUE TITLE
x25519-x86_64.pl ends before asm file is written due to wrong close statement

### ISSUE THREAD

**Issue by rainerjung** [openssl/openssl#5656]
When building OpenSSL 1.1.1-pre2 I noticed a problem on RHEL 6 and RHEL 7: the make rule for crypto/ec/x25519-x86_64.s:

crypto/ec/x25519-x86_64.s: crypto/ec/asm/x25519-x86_64.pl
        CC="$(CC)" $(PERL) crypto/ec/asm/x25519-x86_64.pl $(PERLASM_SCHEME) $@

runs and next the .s file should have been compiled to a .o file. But instead the compilation fails because the .s file was not yet written, when the compilation started. The reason is, that crypto/ec/asm/x25519-x86_64.pl creates the output .s file by calling x86_64-xlate.pl in a pipe. When x25519-x86_64.pl has finished writing to the pipe it closes STDOUT and exits. Make then immediately runs the next rule although the original child process x86_64-xlate.pl is still working on generating the .s file.

The time gap between the exit of x25519-x86_64.pl and the existence of the final .s file is not big, I saw about 200ms.

I expect the same problem to be possible for other asm generators, but I observed it only for x25519-x86_64.pl. I think x25519-x86_64.pl and other generators should wait for their child processes to finish.

I unfortunately do not have a patch available currently.

i worked around the issue by injecting fixed sleep commands into the Makefile, but that is of course neither robust nor nice.

Regards,

Rainer

**Comment by rainerjung** [comment]
Found the root cause: In general perl guarantess, that a close for an file descriptor that refers to a pipe waits for the child process to terminate. What is special about the one script x25519-x86_64.pl is a bug in that it uses "close $STDOUT" instead of "close STDOUT". Note the additional and wrong dollar sign.

So the trivial patch would be:

--- crypto/ec/asm/x25519-x86_64.pl.orig 2018-03-17 23:02:18.802468000 +0100
+++ crypto/ec/asm/x25519-x86_64.pl      2018-03-17 23:02:28.498560000 +0100
@@ -815,4 +815,4 @@

 $code =~ s/\`([^\`]*)\`/eval $1/gem;
 print $code;
-close $STDOUT;
+close STDOUT;

I checked all perl files and did not find the same problem in any other file.

What would be nice though is trying to switch to "use strict" mode and declare variables. That way "$STDOUT" would have been immediately found.

Regards,

Rainer

**Comment by levitte** [comment]
This has been fixed since then, the fix will be part of 1.1.1-pre3

**Comment by rainerjung** [comment]
Another perl script which closes another descriptor ("OUTPUT") than it actually opens ("STDOUT") is ms/uplink-x86.pl:

--- ./ms/uplink-x86.pl.orig     2017-08-04 20:38:33.000000000 +0200
+++ ./ms/uplink-x86.pl  2018-03-17 23:09:23.566500000 +0100
@@ -41,4 +41,4 @@
 }
 &asm_finish();

-close OUTPUT;
+close STDOUT;

All other files look OK.

**Comment by levitte** [comment]
Ah, that one hasn't been noticed, let alone fixed, yet. Thanks!

**Comment by dot-asm** [comment]
I suppose that reason for why it went unnoticed so far is because x86 scripts don't pipe the output to another program. So that there is only one program, the script itself, to synchronize on. And since output will be naturally flushed upon normal exit, you don't actually have to explicitly close STDOUT. Once again, this is unlike x86_64 scripts that pipe output to x86_64-xlate. This is not a suggestion to leave it as is, just an explanation how it went unnoticed so far [and could go for eternity].

As fun fact about original failure to compile x25519-x86_64.pl. When compilation fails, and you examine the generated x25519-x86_64.s it looks perfectly sane and complete. It's just that in the heat of making, without proper synchronization, compiler races x86_64-xlate and manages to snatch incomplete file. But it becomes complete for you to look at and wonder what's wrong, because you are not as fast as compiler...
