### ISSUE TITLE
openssl crypto_malloc_init() not declare

### ISSUE THREAD

**Issue by Mandhata121** [openssl/openssl#5684]
Hi,

I am facing the below issues.
openssl_lib.cpp:44:73: error: ‘CRYPTO_malloc_init’ was not declared in this scope
 void OpenSSLLib::SSL_CRYPTO_malloc_init() noexcept { CRYPTO_malloc_init(); }

Please give some information on the above issue.

Thanks&Regards
Debi

**Comment by levitte** [comment]
I assume the OpenSSLLIB library was used with OpenSSL 1.0.x, and now you've switched to 1.1.0.  With that version, a lot of things became opaque and/or automatic.  Library initialization is one of those things, it happens pretty much automatically.

If you do find yourself in situations where you want to be in detailed control, there are [OPENSSL_init_crypto](https://www.openssl.org/docs/man1.1.0/crypto/OPENSSL_init_crypto.html) and [OPENSL_init_ssl](https://www.openssl.org/docs/man1.1.0/crypto/OPENSSL_init_ssl.html), but quite frankly, you shouldn't need to unless you have extraordinary needs.

**Comment by hlsantos** [comment]
Hi Levitte.  You helped me earlier with getting the 32/64 images separated. :)   I am one of the developers who have been using OpenSSL since early 2000s.  So naturally, we are going to try to recompile existing internal tools and ssl examples to make sure we got an handle of whats going on with these changes.

I did a search for the missing CRYPTO_malloc_init(_) and came across the issue.   What I found is that CRYPTO_malloc_init() defaulting to setting the malloc, realloc, free functions.

What should of been done here was make it a NOOP since it was moved internally or replaced with OPENSSL_malloc_init().
