### ISSUE TITLE
1.1.0g: test cases in ssl_old are failing on HP-UX

### ISSUE THREAD

**Issue by makr** [openssl/openssl#5691]
A `make test TESTS=test_ssl_old V=1` on HP-UX 11i v3 leads to failing test cases 2-20 and 2-21:
```
15:10:56 4294967296:error:0200F016:system library:getsockopt:Invalid argument:crypto/bio/b_sock2.c:166:
15:10:56 4294967296:error:2008B086:BIO routines:BIO_listen:getting socktype:crypto/bio/b_sock2.c:167:
15:10:56 4294967296:error:20087002:BIO routines:BIO_lookup:system lib:crypto/bio/b_addr.c:693:service not supported for socket type
15:10:56 Doing handshakes=1 bytes=256
15:10:56 TLSv1.2, cipher (NONE) (NONE)
15:10:56 ../../util/shlib_wrap.sh ../../test/ssltest_old -s_key keyU.ss -s_cert certU.ss -c_key keyU.ss -c_cert certU.ss -ipv4 => 1
15:10:56     not ok 20 - test TLS via IPv4
15:10:56     
15:10:56     #   Failed test 'test TLS via IPv4'
15:10:56     #   at ../test/recipes/80-test_ssl_old.t line 411.
15:10:56 4294967296:error:0200F016:system library:getsockopt:Invalid argument:crypto/bio/b_sock2.c:166:
15:10:56 4294967296:error:2008B086:BIO routines:BIO_listen:getting socktype:crypto/bio/b_sock2.c:167:
15:10:56 4294967296:error:20087002:BIO routines:BIO_lookup:system lib:crypto/bio/b_addr.c:693:service not supported for socket type
15:10:56 Doing handshakes=1 bytes=256
15:10:56 TLSv1.2, cipher (NONE) (NONE)
15:10:56 ../../util/shlib_wrap.sh ../../test/ssltest_old -s_key keyU.ss -s_cert certU.ss -c_key keyU.ss -c_cert certU.ss -ipv6 => 1
15:10:56     not ok 21 - test TLS via IPv6
15:10:56     
15:10:56     #   Failed test 'test TLS via IPv6'
15:10:56     #   at ../test/recipes/80-test_ssl_old.t line 418.
15:10:56     # Looks like you failed 2 tests of 21.
15:10:56 not ok 2 - standard SSL tests
```
I am just logging this now and will analyze tomorrow...

**Comment by makr** [comment]
Hm. Is it possible to disable these tests, from command line or environment variable?

Background: After skimming through `man getsockopt` and `man xopen_networking` on HP-UX 11i v3 I decided to try to build OpenSSL 1.1.0g using the documented "method B". I added `-D_XOPEN_SOURCE -D_XOPEN_SOURCE_EXTENDED -D_HPUX_ALT_XOPEN_SOCKET_API` to the compiler flags. This fixes these particular test cases but breaks quite a number of other test cases. So it looks as if this might be solved already in new code and it might indeed be specific to the ssl_old test module.

**Comment by makr** [comment]
Hm. Looks as if I have to remove `80-test_ssl_old.t` before calling `make test` or is there another way?

**Comment by makr** [comment]
I am closing this issue again. I will live with the incomplete test suite on HP-UX. What I do now is disabling these two test cases (`sed` is my friend, here) while still keeping all the rest.
For a couple of hours I have been searching for a way to compile it correctly, but it always breaks one way or the other. The order of the includes and the defines in ssltest_old.c is the most likely reason for the failure. Although I didn't go into the debugger to confirm this. My best guess is that the library build chooses the BSD sockets and - due to a `#define _XOPEN_SOURCE_EXTENDED 1` - the ssltest_old build the X/Open implementation. On HP-UX there are these two implementations available. The BSD type sockets are sort of default. Which one is chosen at compile time depends on a combination of the effective macros mentioned in a previous comment. As an example, there are 5 definitions of getsocktopt() in sys/socket.h with only subtle differences, e. g. `int *optlen` versus `socklen_t *optlen` etc.
Not defining _XOPEN_SOURCE_EXTENDED in ssltest_old.c didn't change the situation, however.

**Comment by dot-asm** [comment]
But ssltest_old doesn't create socket by itself, socket are created by BIO, and in such case BIO simply has to be consistent with itself. In other words I find it hard to imagine that it would be some kind of flag mismatch when compiling library and ssltest_old...

> As an example, there are 5 definitions of getsocktopt() in sys/socket.h with only subtle differences, e. g. int *optlen versus socklen_t *optlen etc.

If there is some inconsistency, then compiler ought to issue warning. We don't seem to have any warning flags in hpux targets (not even for gcc for some reason), but can you add some and see? Then those different flags should linking to different symbols, so that it would still be question of self-consistency of any given compile unit...

**Comment by makr** [comment]
I added a +w to the cflags and am now sitting on 145k lines of build.log ... it seems to be "remarks" mostly, but there are a number of "warnings", too. No warnings, however, on compiling ssltest_old.c. But what escaped me so far, is that the other ssl-tests are not executed because "Unable to start up Proxy for tests". I simply just looked for failed tests. So reopening again and start digging ...

**Comment by makr** [comment]
There are some warnings when compiling the test code, but nothing in the ssl tests. The BIO stuff, does have some warnings, however:
```
"crypto/bio/b_addr.c", line 69: warning #4232-D: conversion from "const struct sockaddr *" to a more strictly aligned type "const struct sockaddr_in *" may cause misaligned access
          ap->s_in = *(const struct sockaddr_in *)sa;
                      ^

"crypto/bio/b_addr.c", line 74: warning #4232-D: conversion from "const struct sockaddr *" to a more strictly aligned type "const struct sockaddr_in6 *" may cause misaligned access
          ap->s_in6 = *(const struct sockaddr_in6 *)sa;
                       ^

"crypto/bio/b_addr.c", line 410: warning #4232-D: conversion from "struct sockaddr *const" to a more strictly aligned type "BIO_ADDR *" may cause misaligned access
          return (BIO_ADDR *)bai->bai_addr;
                 ^

"crypto/bio/b_addr.c", line 74, procedure BIO_ADDR_make: warning #20207-D: Out of bound access (In expression "*(struct sockaddr_in6*)sa", variable "sa" [crypto/bio/b_addr.c:66] (type: struct sockaddr* ) has 16 
bytes, reading byte range [0 .. 27].)

"crypto/bio/b_addr.c", line 80, procedure BIO_ADDR_make: warning #20207-D: Out of bound access (In expression "*(struct sockaddr_un*)sa", variable "sa" [crypto/bio/b_addr.c:66] (type: struct sockaddr* ) has 16 b
ytes, reading byte range [0 .. 93].)

"crypto/bio/b_sock.c", line 104: warning #2167-D: argument of type "socklen_t *" is incompatible with parameter of type "int *"
      i = getsockopt(sock, SOL_SOCKET, SO_ERROR, (void *)&j, &size);
                                                             ^

"crypto/bio/b_sock.c", line 359: warning #2167-D: argument of type "socklen_t *" is incompatible with parameter of type "int *"
                                &addr_len);
                                ^

"crypto/bio/b_sock2.c", line 164: warning #2167-D: argument of type "socklen_t *" is incompatible with parameter of type "int *"
      if (getsockopt(sock, SOL_SOCKET, SO_TYPE, &socktype, &socktype_len) != 0
                                                           ^

"crypto/bio/b_sock2.c", line 243: warning #2167-D: argument of type "socklen_t *" is incompatible with parameter of type "int *"
                             BIO_ADDR_sockaddr_noconst(addr), &len);
                                                              ^

"crypto/bio/bss_dgram.c", line 312: warning #2167-D: argument of type "socklen_t *" is incompatible with parameter of type "int *"
                         BIO_ADDR_sockaddr_noconst(&peer), &len);
                                                           ^

```
... and line 164 in b_sock2.c among these warnings.

**Comment by makr** [comment]
As socklen_t is used, I take it that X/Open implementation of the sockets is targeted. So the relevant part of the manual is a follows:
```
    Method A) Strict Compliance Method
      An X/Open conforming application is one that has all its parts
      compiled and built according to X/Open specifications.  For such
      conforming applications, this compilation method would be appropriate.

      Compilation

      UNIX 03
      Applications should ensure that the feature test macro _XOPEN_SOURCE
      is defined with the value 600.  To ensure portability, applications
      should define the macro either on the compilation command line, or at
      the beginning of each source module prior to the inclusion of any
      headers.

      For example, to compile a 64 bit object using HP ANSI Compiler:

           c99 +DD64 -D_XOPEN_SOURCE=600 -c main.c -o main.o

           c99 +DD64 -D_XOPEN_SOURCE=600 -c routines.c -o routines.o

      UNIX 95
      Applications should ensure that the feature test macros _XOPEN_SOURCE
      and _XOPEN_SOURCE_EXTENDED are defined.  To ensure portability,
      applications should define the macros either on the compilation
      command line, or at the beginning of each source module prior to the
      inclusion of any headers.

      For example, to compile a 64 bit object using HP ANSI Compiler:

           c89 +DD64 -D_XOPEN_SOURCE -D_XOPEN_SOURCE_EXTENDED -c main.c -o
           main.o

           c89 +DD64 -D_XOPEN_SOURCE -D_XOPEN_SOURCE_EXTENDED -c routines.c
           -o routines.o

      Linkage
      Link the program objects with Xnet library.

      For example:

           ld main.o routines.o -lxnet -lc -o prog

      Note if the C library is also specified in the link line, the Xnet
      library has to be specified before the C library.  Otherwise, X/Open
      Sockets calls would have been resolved to BSD Sockets functions in the
      C library instead of X/Open Sockets functions in the Xnet library.
```
... I'll find a fitting place for this setup and will give it a try. But its meeting time now and weekend later, so it has to wait until next week.

**Comment by dot-asm** [comment]
> argument of type "socklen_t *" is incompatible with parameter of type "int *"

This is deadly in big-endian sizeof(size_t) != sizeof(int) case, such as HP-UX +DD64, and would totally explain reported failure in getsockopt. Key question is how does it happen, getsockopt should end up being declared with `socklen_t *` for last argument. Unfortunately I'm not in position to figure it out, but I bet that if you get rid of this warning it should work. For reference, I've been [struggling](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/crypto/bio/b_sock.c#L812) with the ambiguity myself, but figured that it shouldn't be a problem with contemporary systems. On out-dated system I have access to, consistent declaration is observed with `_XOPEN_SOURCE_EXTENDED`, but in my case [of gcc, no vendor compiler] it gets defined somewhere without me doing anything...

[Just in case for reference. Where does size_t above come from. On HP-UX socklen_t is customarily size_t.]

**Comment by dot-asm** [comment]
> I've been struggling with the ambiguity

And it's kind of coming back, the head ache that is. What HP does wrong is that they provide symbols with incompatible prototypes (like mentioned above) under same names. They are in different libraries, but since you don't have control over which library application is linked with, there is always a risk that you hit wrong one. Unless you do some controversial stuff like in 1.0.2 with union with size_t and int. Well, it works out in 32-bit, it's disaster only on 64-bit. And one can make shared library consistent with itself, but shared is not the only option we [try to] support.

Stuff in 1.0.2 is pretty old, and one can wonder how does it look now. The HP-UX system I have access to is quite out-dated, so it might be not representative, but here is what I see there. libc exports getsockopt that expects `int *` and _xpg_getsockopt that expects `size_t *`, while libxnet exports getsockopt what expects `size_t *`. This actually means that given the presented warning you should be able to resolve the problem by simply adding -lxnet. And as far as I can see if you specify -D_XOPEN_SOURCE -D_XOPEN_SOURCE_EXTENDED -D_HPUX_ALT_XOPEN_SOCKET_API, then it will start using _xpg symbols, but then you don't have to link with -lxnet.

**Comment by makr** [comment]
Right, because they define a set of wrapper functions for this case. They call it "Method B", because it should provide some sort of forward compatibility (whatever that means). This method fixes the ssltest_old cases and executes all newer socket using test cases, but quite a number of them do fail then. I'll check this and report back here next week.

**Comment by dot-asm** [comment]
To clarify. "what I see [on HP-UX system I have access to]" and "you should be able to resolve" actually means that I managed to reproduce the problem and resolve conundrum by adding either -lxnet or macro definitions. And "resolve conundrum" means that I can confirm that **whole** 'make test' passes(*), it's **not** like if test_ssl_old works, then something else breaks. And I find it hard to imagine a reason for why your experience would be different(**). Is it possible that you didn't 'make clean' between tries?

(*) Well, test_pkcs12 fails, but that's because shell involved in launching apps/openssl seems to mangle utf-8 string passed as argument from perl. If I execute the command manually, it does work. If it fails even for you, i.e. on more up-to-date system, then it might be appropriate to suppress the test on HP-UX.

(**) Though let's keep in mind that I don't have access to vendor compiler, only gcc, and as already mentioned _XOPEN_SOURCE _XOPEN_SOURCE_EXTENDED get defined somehow without me doing anything.

**Comment by dot-asm** [comment]
Basically the question is whether or not you can confirm that configuring with additional -D_XOPEN_SOURCE -D_XOPEN_SOURCE_EXTENDED -D_HPUX_ALT_XOPEN_SOCKET_API does the trick.

**Comment by makr** [comment]
I see, will have a look after the Easter holidays...

**Comment by makr** [comment]
Here we go ...
- I added the three flags to the shared_cflag
- the above mentioned warnings in b_sock.c, b_sock2.c and bss_dgram.c are gone
- the warnings in b_addr.c do persist
- the tests build without warnings and the ssl_old test succeeds
- the following tests are failing now (they were among the skipped tests previously):
```
Test Summary Report
-------------------
../test/recipes/70-test_sslcbcpadding.t  (Wstat: 256 Tests: 5 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
../test/recipes/70-test_sslcertstatus.t  (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
../test/recipes/70-test_sslextension.t   (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
../test/recipes/70-test_sslrecords.t     (Wstat: 1280 Tests: 11 Failed: 5)
  Failed tests:  1-3, 5, 7
  Non-zero exit status: 5
../test/recipes/70-test_sslsessiontick.t (Wstat: 1024 Tests: 10 Failed: 4)
  Failed tests:  1-3, 6
  Non-zero exit status: 4
../test/recipes/70-test_sslvertol.t      (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
../test/recipes/70-test_tlsextms.t       (Wstat: 1280 Tests: 9 Failed: 5)
  Failed tests:  1-4, 6
  Non-zero exit status: 5
Files=95, Tests=543, 490 wallclock secs ( 0.73 usr  0.29 sys + 454.07 cusr 28.49 csys = 483.58 CPU)
Result: FAIL
*** Error exit code 1
```

**Comment by dot-asm** [comment]
`make test TESTS=test_sslcbcpadding V=1`

**Comment by dot-asm** [comment]
> the warnings in b_addr.c do persist

This is expected. The only way to resolve them would be to replace assignments with memcpy. But let's figure out configuration issues first.

**Comment by makr** [comment]
The output is quite large, I'll redirect it into a log file and attach it ...

**Comment by makr** [comment]
The log as text file: 
[test-sslcbcpadding.txt](https://github.com/openssl/openssl/files/1871614/test-sslcbcpadding.txt)

**Comment by dot-asm** [comment]
Got it. It even reproducible on 1.1.1-pre3. But not pre4. Though pre4 fails some *other* 70-tests. What all 70-tests have in common is that they use TLSProxy thing. There were some changes lately (which ought to be explanation for why sslcbcpadding started working in pre4. I'll have a closer look, but for now I'd say that this is sufficient information to move forward with #5742 by adding the macros to config...

**Comment by dot-asm** [comment]
Well, I don't see any warning that would be worthy to address. Some of code that triggers warning is intentional (we have static conditions that always false on some platforms or always true on others, conscious choice), some warnings are false positives (for example some of potential null dereference warnings after if (!ptr)), some warnings are already addressed in master...

Then there is a bunch or remarks. Some overlap with warnings in VC-WIN64 builds and trouble there is that not all of them can be resolved without breaking binary compatibility. In other words they are consciously ignored for now, with intention to revisit them when time is right. (But it's not that bad as it sounds, because we run sanitizers and fuzzing, which work as indication that warnings don't cause harm in practical situations). Another bunch of remarks is also result of conscious choice, choice of how command line options are handled in apps/*... Another bunch of remarks is about padding in structures. Yeah, it can be meaningful to rearrange some structures, but it's kind of a too big overhaul. Another bunch is about unused subroutine parameters. Some are false positives...

On related note, our normal workflow is to work in first hand on master and backport stuff to lower branches. If applicable or deemed appropriate. So that formally speaking we'd appreciate build log for master branch more. And as already mentioned elsewhere, I'd actually suggest to aim for 1.1.1. I mean it sounds like you are in process of migration from 1.0.2 (otherwise socket-related errors would be reported earlier), and since it's not over-night process, you probably can aim straight for 1.1.1.

**Comment by dot-asm** [comment]
I'm closing this. Real issues with fatal prototype mismatch are addressed. There will be some [possibly intermittent] errors in 1.1.0 in 70 range. It's suggested to ignore them and consider moving on to 1.1.1.

**Comment by makr** [comment]
I see, thanks for your help!
