### ISSUE TITLE
dump in BN_from_montgomery_word

### ISSUE THREAD

**Issue by DarovskikhAndrei** [openssl/openssl#5785]
openssl_1_1_0-stable
file: bn_mont.c
method: static int BN_from_montgomery_word(BIGNUM *ret, BIGNUM *r, BN_MONT_CTX *mont)

If r value has r->top great then mont->N.top, we can recive max value less then r->top and dump in 
    /* clear the top words of T */
    i = max - r->top;
    if (i)
        memset(&rp[r->top], 0, sizeof(*rp) * i); -<<<< if i less 0 will dump

Here should be 
    /* clear the top words of T */
    i = max - r->top;
    if (i > 0)
        memset(&rp[r->top], 0, sizeof(*rp) * i); <----- i great 0. Correct. No dump
    else if (i < 0)
        return  0; <--- return error. No dump

May be here required other checks fo r and mont.N values?

**Comment by bernd-edlinger** [comment]
Yes, although `BN_from_montgomery_word` is an internal function, I think it is a valid concern.
This can happen if r > N^2, which is may happen if
`BN_mod_mul_montgomery` is called with a > N and b > N

**Comment by DarovskikhAndrei** [comment]
ок

**Comment by dot-asm** [comment]
> it is a valid concern.

Well, it's a tricky question. Of course if you abstract from the context *completely*, i.e. assume that application if entitled to exercise BN_mod_mul_montgomery with arbitrary inputs, then yes, one can argue that it would be a valid concern. However, question also is how would it be different from feeding data of one type to subroutine that expects data of another? Thing is that you are expected to pass not just any inputs to the subroutine in question, but output from BN_to_montgomery. Which does meet the implied boundary condition. Now, let's refine the question as what should you expect to happen if you feed data of one type to subroutine that expects data of another, a.k.a. make a programming mistake? Well, some would probably have different opinion, but I'd say that you should expect crash. I'd even go as far as saying that you should even *appreciate* the crash. Because it exposes programming mistake (by leaving vital hint that is hopefully closest to the mistake), instead of masking it with silent return 0. Now, let's imagine it wasn't a programming mistake, but result of data corruption. Even so you should appreciate crash as soon as possible, because you might be facing taking inadequate security decisions.

**Comment by dot-asm** [comment]
As for exposing programming mistake and crashing as close as possible to its origin. I'd say that it would be appropriate to add soft asserts to BN_mod_mul_montgomery that would check for boundary condition. So that debug build would crash as close as possible to the origin.

**Comment by bernd-edlinger** [comment]
I don't think a memset that wipes out everything, possibly even the entire call stack
is a really user friendly failure mode.
While dereferencing a null pointer is of course something completely different.

**Comment by dot-asm** [comment]
I'd say that user friendliness is not an issue with programming mistakes. As already said, crash should be *appreciated* and rather sooner than later (because later might be too late). And if it takes memset, then be it. From practical viewpoint it's unlike to reach stack, because there is more than likely inaccessible page on the way.

But let's say that we conclude that in this case the programming error should be masked. I'd still say that ensuring boundary condition in beginning of BN_mod_mul_montgomery would be the right spot to mask the error. Because if we are looking at data corruption, then we at least minimize chances of further corruption.

**Comment by bernd-edlinger** [comment]
Fixed.
