### ISSUE TITLE
Cannot configure GOST sigalgs

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#5810]
I have been unable to get GOST ciphersuites to work in TLSv1.2 because there are no GOST sigalgs entries. There does seem to be some GOST sigalg support in the code but I can't figure out how to activate it - so either I'm doing something wrong or it's broken. Forcing TLSv1.1 means sigalgs aren't sent and GOST works.

**Comment by mattcaswell** [comment]
Ping @beldmit for your thoughts.

**Comment by beldmit** [comment]
I am not sure that it was really tested because Russian GOST TLS was more or less ctrange mix of TLS 1.0, 1.1 and 1.2 when I was implementing it, and there were no 3rd-party implementations pretending to be TLS 1.2. 

I added GOST sigalgs to sigalg_lookup_tbl list though the struct of that list seems to be changed since I looked into it...

**Comment by mattcaswell** [comment]
So @beldmit what should we do about this issue? I currently have it against the 1.1.1 milestone. Should I push it out to post-1.1.1?

**Comment by mattcaswell** [comment]
#5809 is fixed in the latest master branch (as well as the latest 1.1.0 branch). It's preferable to test master I think.

**Comment by beldmit** [comment]
Could you please take a look at #6168?

**Comment by mattcaswell** [comment]
#6168 got merged so this can be closed.
