### ISSUE TITLE
capi engine: function not supported

### ISSUE THREAD

**Issue by frankero** [openssl/openssl#5847]
when use capi-engine to load window certificate (server needs to verify client's certificate), 
it always aborted with error "capi_rsa_priv_enc:function not supported:engines\e_capi.c:814". 
the openssl version is 1.1.1pre3. 
can this issue be solved ?

**Comment by levitte** [comment]
It could possibly be solved if you tell exactly what you're trying to do.  I assume this is in an application you've built?  Or is it with the `openssl` command?  Worst case scenario, can you put together a small example program that exhibits this behaviour?

What I *suspect* is that you're using RSA_private_encrypt() to sign something.  We would encourage you to try RSA_sign instead, or to be more future proof, try the EVP API.

**Comment by frankero** [comment]
Didn't find any use of APIs like RSA_private_encrypt() in the source code.
just used SSL_CTX_set_client_cert_engine() to make it use capi engine.

Tried again by write a simple example. this issue can't be reproduced again.
so this is not an openssl issue and probably caused by other part of the code.
This issue can be closed and thanks for your advice, @levitte

**Comment by levitte** [comment]
Ok then.  Thanks!

**Comment by olszomal** [comment]
I reproduced the same error „capi_rsa_priv_enc:function not supported” with openssl-1.1.1
I also tested this with  openssl-1.1.1a, 1.1.1b and the current master branch.

### Steps to reproduce the bug
I am trying to connect from an stunnel client using the CAPI engine to the openssl s_server
```
$ openssl s_server -accept 4433 -cert server.pem -CAfile CACerts.pem -Verify 1 
```
Stunnel configuration:
```
engine = capi
[client]
client = yes
accept = 8080
connect = 192.168.1.201:4433
engineId = capi
```

Everything works well if at least one of the peers uses openssl older then 1.1.1 or TLSv1.1 is required.

I would like to reproduce this problem using s_client but s_client doesn’t work with the CAPI engine option.
https://stackoverflow.com/questions/54418779/openssl-capi-can-find-ca-cert-in-windows-cert-store-wont-validate-server-ce 

Stunnel error logs:
```
2019.02.28 16:01:15 LOG7[1]: TLS alert (write): fatal: internal error
2019.02.28 16:01:15 LOG3[1]: error queue: ssl\statem\statem_lib.c:299: error:141F0006:SSL routines:tls_construct_cert_verify:EVP lib
2019.02.28 16:01:15 LOG3[1]: SSL_connect: engines\e_capi.c:814: error:8006F074:lib(128):capi_rsa_priv_enc:function not supported
```
and the received s_server alert:
```
ERROR
140412234445056:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:ssl/record/rec_layer_s3.c:1576:SSL alert number 80
shutting down SSL
```

### My initial analysis

I managed to get the following backtrace:
```
Address    Stack      Procedure / arguments                 Called from                   Frame
00B0F540   5A204FB7   capi._ERR_put_error                   capi.5A204FB2
00B0F558   57394D43   libcrypt.RSA_private_encrypt          libcrypt.57394D3E
00B0F580   5735946D   Includes libcrypt.57394D43            libcrypt.5735946B
00B0F5A0   5735499A   libcrypt.EVP_PKEY_sign                libcrypt.57354995             00B0F654
00B0F618   573547C7   libcrypt.EVP_DigestSignFinal          libcrypt.573547C2             00B0F654
00B0F62C   57244570   libssl-1._EVP_DigestSign              libssl-1.5724456B
00B0F718   57238FC2   Includes libssl-1.57244570            libssl-1.57238FC0
00B0F758   57238BE8   libssl-1.write_state_machine          libssl-1.57238BE3
00B0F770   5723836B   libssl-1.state_machine                libssl-1.57238366
00B0F77C   572202B9   Includes libssl-1.5723836B            libssl-1.572202B7             00B0F840
00B0F7A0   5721FB1A   libssl-1.SSL_do_handshake             libssl-1.5721FB15             00B0F840
00B0F7AC   00CA97D4   stunnel._SSL_connect                  stunnel.00CA97CF              00B0F840
00B0F7C0   00CA844F   stunnel.ssl_start                     stunnel.00CA844A              00B0F840
00B0F7DC   00CA813B   stunnel.client_try                    stunnel.00CA8136              00B0F840
00B0F844   00CA8000   stunnel.client_run                    stunnel.00CA7FFB              00B0F840
```

The pkey_rsa_sign() callback calls RSA_private_encrypt because RSA_PKCS1_PSS_PADDING is used.
Missing support for PSS padding mode in CAPI engine was discussed in #7341
