### ISSUE TITLE
Cannot open include file:“openssl/opensslconf.h”: No such file or directory

### ISSUE THREAD

**Issue by vishnuaggarwal** [openssl/openssl#6040]
i am using openssl openssl-1.1.1-pre5, while compiling the windows project , its provide the error Cannot open include file:“openssl/opensslconf.h”: No such file or directory.

i did't not found the file, how can i create this file, so that i am able to compile the project

**Comment by mspncp** [comment]
The file `./include/openssl/opensslconf.h` is created automatically during the build process from `./include/openssl/opensslconf.h.in`. Have you read the INSTALL and the NOTES.WIN files?  There you find all the information needed for building OpenSSL.

**Comment by mspncp** [comment]
@vishnuaggarwal, I hope my previous answer was helpful for you. If you have more questions about building and using OpenSSL, I recommend that you register on the [openssl-users](https://mta.openssl.org/mailman/listinfo/openssl-users) mailing list and post your questions there. On the mailing list you will reach not only the OpenSSL developers but also a lot of other friendly and helpful OpenSSL users, which can help you and answer your questions.

Closing this issue, because it's not an OpenSSL bug.

**Comment by kkelley1** [comment]
I had the same problem when trying to build OpenSSL_1_1_1b and I had to install the Text::Template perl module to get things to work.
