### ISSUE TITLE
Building for iOS with -fembed-bitcode flag is causing an error

### ISSUE THREAD

**Issue by Zagoruyko** [openssl/openssl#6082]
I’m trying to build OpenSSL 1.1.0f for iOS with bitcode enabled, using -fembed-bitcode flag. I got an error: 

ld: -bundle and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together

In the Makefile.shared I found string: SHAREDFLAGS="$(CFLAGS) `echo $(SHARED_LDFLAGS) | sed s/dynamiclib/bundle/`"; \

Is that causing the conflict? How can I fix it and build with bitcode enabled?

**Comment by dot-asm** [comment]
The issue was discussed in #5513, but with no apparent resolution, originator closed it without answering questions. I suppose that suggested no-engine config-time option worked and considered sufficient. As additional alternative to what was discussed in #5513 one can add disable => [ "engine" ] to ios configs to enforce no-engine, so that user doesn't have to keep it in mind. Rationale would be that bundled engines has no use on ios to begin with, and OpenSSL's way to load engines is not exactly ios-friendly (because engine location is determined at compile time, but application will never be installed there.)

**Comment by Zagoruyko** [comment]
Thank you for your answer. I was able to build for iOS with -fembed-bitcode and no-engine flags. But it's still a workaround, the problem is I have to choose which option I need more. I can meet Apple requirement and sacrifice the hardware acceleration or do the opposite. It's a hard decision and really would be nice to have both options in same time. I see you've added this to the 1.1.1  milestone, does it mean it possibly be implemented in 1.1.1 release?

**Comment by dot-asm** [comment]
> I can meet Apple requirement and sacrifice the hardware acceleration or do the opposite.

What acceleration? None of bundled engines give an edge and out engine loading code is not exactly iOS-friendly, because of disconnect between search path determined at config time and fact that application is installed in sandbox directory that can't be predicted in advance. As per #6106 no-engine is default for iOS targets.
