### ISSUE TITLE
Unnecessary code complecity?

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#6090]
I just tumbled on a piece of code that seems unnecessarily complex:

https://github.com/openssl/openssl/blob/master/crypto/cryptlib.c#L38-L44

Why can't we have a simple line like this?

``` C
        vec = strtoul(env + off, NULL, 0);
```

**Comment by dot-asm** [comment]
Not really. Intention is to collect 64-bit value. strtoul is a poor-man fallback in case sscanf fails, it will truncate value to 32 bits on 32-bit platforms (and Windows), but it's considered more appropriate than doing something else [in case sscanf fails].

**Comment by levitte** [comment]
So then the question is how far back `strtoull` is implemented on Windows...

**Comment by t8m** [comment]
strtoull(): POSIX.1-2001, POSIX.1-2008, C99

**Comment by dot-asm** [comment]
> strtoull(): POSIX.1-2001, POSIX.1-2008, C99

The question was rather rhetorical. Point was rather that one can ask same question about POSIX and Windows. And next point is what would you do given an answer, whichever it is. #if this-n-that-but-not-apple-because-it-has-to-be-special? Or whichever special cases you can run into [a year later]? Or just probe sscanf at run-time and fallback to strtoul, combo that has very high chances to work on *both* contemporary and legacy platforms?

**Comment by levitte** [comment]
Ok, I'm convinced
