### ISSUE TITLE
BSD standard integer types

### ISSUE THREAD

**Issue by dlegaultbbry** [openssl/openssl#6097]
openssl should avoid using BSD specific standard integer types and use the C standard ones instead.

u_intX_t -> uintX_t

These cause compilation errors on systems that don't have these defined. I found about this while enabling cryptodev on 1.1.0 on QNX.

crypto/rand/rand_unix.c:    u_int32_t rnd = 0, i;
crypto/engine/eng_cryptodev.c:static u_int32_t cryptodev_asymfeat = 0;
crypto/engine/eng_cryptodev.c:    u_int8_t *pd;
apps/s_client.c:typedef unsigned int u_int;
apps/s_socket.c:typedef unsigned int u_int;
apps/s_server.c:typedef unsigned int u_int;
engines/afalg/e_afalg.c:    u_int64_t eval = 0;

I can take care of this as soon as CLAs clear with legal.

**Comment by levitte** [comment]
For the typedefs in apps/s_client.c, apps/s_socket.c and apps/s_server.c, they are there for good reason, read the comment just above them.

For engines/afalg/e_afalg.c, I agree.
For crypto/rand/rand_unix.c, this is in a OpenBSD section, and arc4random() has the return type u_int32_t, so...
For crypto/engine/eng_cryptodev.c, that's BSD-only code, so...

It seems like the amount of reasonable changes turns out to be very small (only e_afalg.c).  You might as well make that a trivial PR if you're still inclined.

**Comment by mattcaswell** [comment]
Interestingly most of this isn't an issue in 1.1.1/master. Aside from the ones in apps (which shouldn't be a problem because of the conditional compilation around them), the only remaining instance of the above I could find was in e_afalg - which just looks like a typo to me (probably it was always intended to be `uint64_t`).

**Comment by richsalz** [comment]
Ping @mattcaswell for review of #6187.

**Comment by richsalz** [comment]
As discussed in #6187, all other instances are fixed except for one file that isn't compiled on the platform in question.  Closing this issue.
