### ISSUE TITLE
Preprocessor "include guard" indentation

### ISSUE THREAD

**Issue by davxy** [openssl/openssl#6129]
As can be read in the "codingstyle" directives:

> Pre-processor directives use one space for indents:

    #if
    # define
    #else
    # define
    #endif

Anyway this rule a bit overkill if applied to the (ubiquitous) header files include guards.

    #ifndef HEADER_FOO
    # define HEADER_FOO
    ...
    # define USEFUL_MACRO 1
    # define USEFUL_MACRO 2
    ...
    # ifndef BAR
    #  define ANOTHER_MACRO 
    # endif
    ...
    #endif

Because every header file should begin (at least from a design perspective) with the "classic" include guard, **the rule generates header wiles where all the macro are indented**...

Again, to improve code design I would suggest to ignore the rule for include guards, thus getting to the other (more widespread and IMHO more clean) form:

    #ifndef HEADER_FOO
    #define HEADER_FOO
    ...
    #define USEFUL_MACRO 1
    #define USEFUL_MACRO 2
    ...
    #ifndef BAR
    # define ANOTHER_MACRO 
    #endif
    ...
    #endif

Actually the suggestion still respect the "1 space indentation" reported by the *guidelines* for everything except for the "include guard".

Furthermore looks like the `#ifndef __cplusplus` (fortunately) ignores the indentation rule and I've found some other *violations* around that are encoded like the second form I've proposed.

(This would be a long-term work... where old header files are slowly adjusted)

**Comment by richsalz** [comment]
You might read Pike's style guide on header files.

**Comment by davxy** [comment]
Read. In particular I've Read this: https://www.lysator.liu.se/c/pikestyle.html

Looks like the golden rule is: "header files should never include other header files and that the include test should be done by the *includer* and not the *included*" (in order to speed up the parser). Understood the Pike's pov but.. openssl akaik doesn't use that paradigm right?

**Comment by richsalz** [comment]
WE don’t follow his guideline, but if we’re going to overhaul things we should look at it.

**Comment by mspncp** [comment]
> Looks like the golden rule is: "header files should never include other header files and that the include test should be done by the _includer_ and not the _included_" (in order to speed up the parser).

**Note:** this advice about using outer include guards (around the include statements) instead of inner include guards (inside the header file) for efficiency reasons is outdated and makes the include statements really clumsy.

For modern compilers (e.g., gcc, clang, msvc) there is a much better alternative: they understand the `#pragma once` directive which instructs the compiler that the header file does not need to be included more than once. Those pragma directives were added (in addition to the classical include guards) a while ago during the reorganization of the header files (#9333).

_(@davxy I'm aware that this issue is old, but it popped up in my timeline since it was closed seven hours ago and caught my interest.)_
