### ISSUE TITLE
how to get members from struct evp_cipher_ctx_st 

### ISSUE THREAD

**Issue by nixiejun** [openssl/openssl#6194]
Description:
Since I had some pieces of code that worked well with openssl 1.0.2, however after I update openssl to 1.1.0. I find some struct such as evp_cipher_ctx_st are made into opaque. And I can not get the members value as I did since evp_cipher_ctx_st is currently a incomplete type.

For example in my previous code:

` if(!ctx->encrypt)
        {
            if(ctx->final_used)
            {
                memcpy(out_buf, ctx->final, block_length);
                out_buf += block_length;
                fixed = 1;
            }
            else
            {
                fixed = 0;
            }
        }
`

and also like 

`if(!ctx->encrypt)
        {
            if(block_length > 1 && !ctx->buf_len)
            {
                out_length -= block_length;
                ctx->final_used = 1;
                memcpy(ctx->final, &out_buf[out_length], block_length);
            }
            else
            {
                ctx->final_used = 0;
            }
            if(fixed)
            {
                out_length += block_length;
            }
        }
`

And my question is, by calling which function can I get the members in evp_cipher_ctx_st?
I know there should exist some functions can be used, but I can not know their usage easily from the function name.  Can anyone please help me with it? Thanks in advance.

**Comment by nixiejun** [comment]
@mattcaswell please help to take a look. Thanks.

**Comment by mattcaswell** [comment]
> And my question is, by calling which function can I get the members in evp_cipher_ctx_st?

You can get the value of `ctx->encrypt` by calling `EVP_CIPHER_CTX_encrypting()`.

For the others you cannot get these members via the API. Nor do I think we would want to expose them. These contain the internal state of the cipher operation and are really not intended for application use.

Why do you need them?

**Comment by nixiejun** [comment]
Since we have a project use RampartC which depends on openssl. Now our openssl has upgraded from 1.1.0 so I have to rebuild the RampartC. 

And in https://svn.apache.org/repos/asf/axis/axis2/c/rampart/branches/02032010/src/omxmlsec/openssl/  
crypt.c, it still use ctx in this way.

So I need to rewrite the code to pass compiling.

**Comment by mattcaswell** [comment]
This code is nuts!

It appears to be implementing a custom padding scheme. Normally when you encrypt/decrypt, the final block contains padding so that the final byte of the block is a number indicating the number of padding bytes. Each padding byte must have the same value as the final padding byte. So, for example, if your block length is 16 bytes and you have 4 padding bytes, then you will end up with 12 bytes of payload content data, followed by 4 bytes each set to the value "4":

````
XX XX XX XX XX XX XX XX XX XX XX XX 04 04 04 04
````
The custom padding scheme appears to be a variation on this such that the final byte is still the number of padding bytes, but the rest of the padding bytes are just random data.

Normally, when padding is enabled, the EVP_CIPHER_CTX is used to keep track of the final block of data. So each time you call EVP_DecryptUpdate (or equivalently EVP_CipherUpdate), the final block you provide is stashed away for later use and not immediately returned in the output buffer. This is so that when EVP_DecryptFinal (or equivalently EVP_CipherFinal) is called we can do the padding check and strip off any padding bytes.

The code you have pointed me attempts to implement this by first switching off padding support:

````
    EVP_CIPHER_CTX_set_padding(&ctx, 0);
````
Switching off padding support has the effect of skipping all of the logic for stashing away the final block during the Update calls.

The code then attempts to replicate the OpenSSL padding behaviour by *reimplementing* the internal OpenSSL logic for stashing the final block that was previously skipped because padding was switched off (its a copy and paste of OpenSSL code with just some minor tweaks).

When the EVP_CipherFinal call is done at the end, OpenSSL again skips all of its padding logic because padding was switched off. The code then reimplements the OpenSSL padding logic, but changed to cope with the custom padding scheme.

This is completely the WRONG way to do this!!! It assumes all sorts of things about how the OpenSSL padding logic works and is very brittle. You should not be attempting to replicate the OpenSSL logic by stashing the block in the EVP_CIPHER_CTX. The EVP_CIPHER_CTX is for OpenSSL internal data - it is not a convenient place for applications to stash data!

The correct way to do this is to simply switch off padding support (as the code does now) and then just call EVP_CipherUpdate() as required. All of the block stashing logic should be stripped.

When encrypting one final EVP_CipherUpdate() call should be made to add the custom padding and to make the total length up to a multiple of a block size. When decrypting the output buffer will contain all of the payload bytes AND the padding bytes. Just strip them off of the end of the output buffer before the function returns.

**Comment by nixiejun** [comment]
Thank you @mattcaswell.  Close this issue.

**Comment by effywu** [comment]
Hi @nixiejun , sorry for tagging you after 3 years of this issue. I'm facing the same situation that needs to upgrade the rampartc to be compatiable with OpenSSl 3.0 ... just wonder how was your upgrade go and if it's possible to share the piece of code that you replaced for the final_used logics?
