### ISSUE TITLE
X509 app srl file path detection detects first "." rather than last causing problems with some CA file paths

### ISSUE THREAD

**Issue by athena-metis** [openssl/openssl#6203]
The x509 app when determining the filename for the SRL file makes the assumption that the period "." character is only used for the file extension. If the CA file is specified as a path that contains a period or the CA file name itself contains a period other than as a file extension separator then this causes unexpected end user behaviour.

strrchr is expected to be used rather than strchr on:
https://github.com/openssl/openssl/blob/2d1b5717b9fd3ed54b663334e18c006d34776328/apps/x509.c#L919

Examples CA files/paths that cause issues:
/home/ca.root/certs/ca.crt  (looks for an srl of /home/ca.srl)
ca.root.crt (looks for an srl of ca.srl)

Expected behaviour would be that the last period is used to remove the extension from the CA certificate filename and substitute it with .srl

**Comment by beldmit** [comment]
#6580

**Comment by richsalz** [comment]
This is not a just-in-1.1.1 issue, so removing that milestone.

**Comment by mspncp** [comment]
This issue has been fixed by #6566 for all `CAFile`s which have a file extension. The only case which still breaks is the rather exotic case where the `CAFile` does not have an extension but one of the path components contains a dot. So #6566 is a good-enough fix to close this issue, just like #6489 has already been closed. 

@beldmit, closing this issue is not meant to discourage you from pursuing your improvement #6580 :-).
