### ISSUE TITLE
Need to test GOST-based cipersuites

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#6210]
As GOST ciphersuites are a part of main tree, we need to test them on regular basis.

**Comment by beldmit** [comment]
There are 2 main possibilities to organize such testing:

1. A GOST engine (https://github.com/gost-engine/engine) can be used.
2. GOST algorithms can be made 1st-class citizens along with RSA/EC/SM.

The set of tests may include either self-compatibility or compatibility with 3rd-party implementations.

The main problem related to including GOST algorithms in the main tree is current absence of GOST-related people among OpenSSL committers. The 2nd problem is we in Russia have a relatively fast development of standards that sometimes is faster than development of OpenSSL itself (and sometimes is slower).

**Comment by mattcaswell** [comment]
I think initially any test should attempt to load the GOST engine. If it fails to load then this should not be counted as a test failure and the rest of the tests are skipped. Otherwise we carry on with the rest of the test.

Initially we should focus on self-compatibility. Although we do have the "external" tests, mostly we only worry about self-compatibility for everything else we have.

We can look at making the GOST algorithms 1st class citizens - but that can be done on a separate (possibly longer) timeline to getting some tests together.

**Comment by lumag** [comment]
I'd suggest to add non-engine implementation of GOST algorithms to libcrypto. Then certified engine would be able to override default implementation, while default user would still be able to use non-certified GOST algo implementation.

**Comment by paulidale** [comment]
Is this relevant anymore?
GOST is an engine.  It will be a provider.  It won't be part of libcrypto.

**Comment by beldmit** [comment]
In the ideal world it's worth testing the GOST TLS ciphersuites not only in self-compatibility mode (as it done now). But for now it can be closed, and the separate issue should be raised against the GOST engine itself.
