### ISSUE TITLE
IDEA Ciphersuites in TLS 1.2

### ISSUE THREAD

**Issue by ic0ns** [openssl/openssl#6247]
During our research on TLS-Attacker we discovered that Openssl 1.0.2o allows the IDEA ciphersuite to be negotiated for TLS 1.2. The client accepts an IDEA cipher suite selection from a server and the server is also willing to select this cipher suite themselfs. The RFC 5246 deprecated the IDEA cipher suite:
 ```
Removed IDEA and DES cipher suites.  They are now deprecated and
 will be documented in a separate document   
```
We do not think that this is a _direct_ security issue, but this additionally creates an interoperability issue with potential other clients since such handshakes probably result in a failed handshake. 

Best regards
Robert Merget (@ic0ns), Simon Friedberger (@Apromixately) and Juraj Somorovsky (@jurajsomorovsky)

**Comment by kaduk** [comment]
As of OpenSSL 1.1.0, IDEA, DES, and several other things are not available at the default security level.
Making this change in the 1.0.2 series would be a compatibility-breaking behavior change and seems unlikely to be done in the absence of an exploitable critical flaw.  As such, I don't think there's anything to do other than close this issue (since it is already addressed in the latest releases), but feel free to continue the conversation if you disagree with this assessment.
