### ISSUE TITLE
"openssl ciphers UNSUPPORTED" no longer fails with OpenSSL 1.1.1-pre6

### ISSUE THREAD

**Issue by tiran** [openssl/openssl#6296]
``SSL_CTX_set_cipher_list()`` no longer fails, when called with an invalid or unsupported cipher suite list. For example ``openssl ciphers INVALID`` no longer fails. Instead it returns TLS 1.3 cipher suites. Even a combination of ``SSL_CTX_set_max_proto_version(ctx, TLS1_2_VERSION)`` and ``SSL_CTX_set_cipher_list(ctx, "INVALID")`` doesn't fail for me. The problem is likely caused by https://github.com/openssl/openssl/pull/5392 . 

## OpenSSL 1.1.1

```
$ openssl ciphers INVALID
TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256
$ openssl version
OpenSSL 1.1.1-pre6 (beta) 1 May 2018
```

## OpenSSL 1.1.0
```
$ openssl ciphers INVALID
Error in cipher list
140552924768064:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl/ssl_lib.c:2193:
$ openssl version
OpenSSL 1.1.0h-fips  27 Mar 2018
```

**Comment by tiran** [comment]
On CPython master, a connection test with 1.1.1-pre6 and settings

```
client_context.maximum_version = ssl.TLSVersion.TLSv1_2
server_context.maximum_version = ssl.TLSVersion.TLSv1_2
client_context.set_ciphers("3DES")
```

fails with error ``[SSL: UNEXPECTED_MESSAGE] unexpected message``.

**Comment by mattcaswell** [comment]
Yes, this is deliberate. It's the result of a compromise on the least bad option for integrating TLSv1.3 ciphersuites into OpenSSL. We tried a couple of different ways until we settled on this approach. Now TLSv1.3 ciphersuites are configured separately to TLSv1.2 ciphersuites and below. This makes a lot of sense because they really are quite different: you can't use TLSv1.3 ciphersuites in TLSv1.2, and you can't use TLSv1.2 ciphersuites in TLSv1.3. There is a separate "-ciphersuites" option to the "ciphers" command if you want to change the default TLSv1.3 ciphersuite list:

````
openssl ciphers -ciphersuites "" INVALID
Error in cipher list
140116936156096:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl/ssl_lib.c:2533:
````

> fails with error [SSL: UNEXPECTED_MESSAGE] unexpected message.

That looks like a different problem (probably because 3DES is not enabled unless you compile with enable-ssl-weak-ciphers). The fact it fails is probably right. The error is wrong. That should probably be in a different issue though.

**Comment by mattcaswell** [comment]
It looks like the client bails with:
140000263410624:error:141A90B5:SSL routines:ssl_cipher_list_to_bytes:no ciphers available:ssl/statem/statem_clnt.c:3727:No ciphers enabled for max supported SSL/TLS version

That will be because 3DES isn't available and TLSv1.3 has been disabled, so there are no other ciphersuites available. The client also sends an internal error alert to the server. The server then complains because it thinks it shouldn't receive anything other than a ClientHello as the first message.

Actually I'm not sure what is correct there, i.e. whether it is ok to send an alert as the first message (in which case the server is wrong for complaining), or whether it isn't ok and the client is wrong for sending it.

**Comment by tiran** [comment]
CPython contains some tests for older ciphers. So far we did something like

```
context.maximum_version = ssl.TLSVersion.TLSv1_2
try:
    context.set_ciphers("3DES")
except ssl.SSLError:
    self.skipTest("no DES cipher available")
```

I assumed that ``SSL_CTX_set_cipher_list()`` would know about the maximum protocol version from ``SSL_CTX_set_max_proto_version()`` and detect that no ciphers are available.

If that's not the case, then I have to convince our release managers to get a new feature into stable versions. In general that's against Python release policy.

**Comment by mattcaswell** [comment]
> I assumed that `SSL_CTX_set_cipher_list()` would know about the maximum protocol version from `SSL_CTX_set_max_proto_version()` and detect that no ciphers are available.

No, that's not the case. Since the various config options can be set at different times and in different orders, both on the SSL_CTX and on the SSL, we don't know whether the cipher list is ok until we attempt to form a connection (i.e. the last possible moment). There is a change of behaviour here between 1.1.0 and 1.1.1. In 1.1.0, we would happily let you attempt to make a connection even though there are no suitable ciphers available for your maximum protocol and let the server complain about no suitable ciphersuites. In 1.1.1 we detect this condition early and bail out before the ClientHello is sent.

**Comment by tmshort** [comment]
> we don't know whether the cipher list is ok until we attempt to form a connection (i.e. the last possible moment).

Would it make sense for there to be an API that would allow applications to check if the ciphers are valid before attempting the connection? Some kind of "cipher validation" function? Since this functionality was effectively removed?

**Comment by tmshort** [comment]
Yeah, we figured out the disabling TLSv1.3 ciphers "workaround". Thanks for the other pointer.

**Comment by mattcaswell** [comment]
Based on the above discussion, I think this should be closed.
