### ISSUE TITLE
openssl-1.1.0 on windows - SSL_get_error() internally reset the value being returned by WSAGetLastError()

### ISSUE THREAD

**Issue by vmurashev** [openssl/openssl#6299]
#### openssl-1.1.0 on windows - SSL_get_error() internally reset the value being returned by WSAGetLastError()
I revealed this fact during my experiment when I built Python2.7 with OpenSSL-1.1.0 and tested.
Top problem is failing test - [test_ftplib.py](https://github.com/python/cpython/blob/2.7/Lib/test/test_ftplib.py)
After debug I found out that ssl related logic looks like:
- call SSL_read
- call SSL_get_error
- when result of SSL_get_error is SSL_ERROR_SYSCALL ask for WSAGetLastError
- WSAGetLastError returns 0

Debugger shows that WSAGetLastError() is reset exactly by the winapi call of TlsGetValue()
```
SSL_get_error()
  -> ERR_peek_error()
    -> get_error_values()
      -> CRYPTO_THREAD_get_local()
        -> TlsGetValue()  /* WSAGetLastError is reset here */
```
As result after call of SSL_get_error() it is impossible to check low level socket error.
With openssl-1.0.0 the situation was different.

**Comment by davidben** [comment]
It's an OpenSSL bug. As you note, libssl's calling convention requires that nothing in `SSL_get_error` modify `errno` or `GetLastError`. The problem is, unlike most functions, `TlsGetValue` clears the last error on success, so that you can distinguish successful or failing `NULL` returns. This interferes with `SSL_get_error`.
https://msdn.microsoft.com/en-us/library/windows/desktop/ms686812(v=vs.85).aspx

The fix is to sample `GetLastError` before `TlsGetValue` and then restore it afterwards. (`TlsGetValue` promises never to fail if the index was allocated via `TlsAlloc`, so there's no particular need to route error-handling in here.)
https://github.com/google/boringssl/blob/master/crypto/thread_win.c#L193-L209
https://github.com/google/boringssl/blob/master/crypto/err/err_test.cc#L224-L237

**Comment by zaher** [comment]
Same problem with 1.1.1g, SSL_get_error reset error for WSAGetLastError 
When read socket have timeout.
