### ISSUE TITLE
Significant slow down caused by a7b0b69: ECC: unify generic ec2 and ecp scalar multiplication, deprecate ec2_mult.c

### ISSUE THREAD

**Issue by vanc** [openssl/openssl#6396]
Checked out OpenSSL_1_1_1_pre7, and run "Configure -static linux-x86_64 && make", and then ran evp_test, found significant slow down.

With pre6:

$ time build/test/evp_test test/recipes/30-test_evp_data/evppkey.txt >/dev/null 2>&1
real	0m0.811s
user	0m0.799s
sys	0m0.008s

With pre7:

$ time build/test/evp_test test/recipes/30-test_evp_data/evppkey.txt >/dev/null 2>&1
real	0m3.864s
user	0m3.859s
sys	0m0.005s

Bisecting the commits, found it was caused by:

commit a7b0b69c6e9fa172aeb1ac0ede5ef306315dd80c (HEAD)
Author: Billy Brumley <bbrumley@gmail.com>
Date:   Tue Apr 24 06:01:53 2018

    ECC: unify generic ec2 and ecp scalar multiplication, deprecate ec2_mult.c
    
    Reviewed-by: Richard Levitte <levitte@openssl.org>
    Reviewed-by: Andy Polyakov <appro@openssl.org>
    Reviewed-by: Rich Salz <rsalz@openssl.org>
    (Merged from https://github.com/openssl/openssl/pull/6070)

The slow down mostly happened in this test:
    # Starting "ECDH KATs (from NIST SP800-56A co-factor ECDH KATs" tests at line 5908

**Comment by bbbrumley** [comment]
> The slow down mostly happened in this test:

Try `no-ec2m` at build time.

**Comment by vanc** [comment]
no-ec2m surely solved the issue as expected. The option basically hides all the changes from a7b0b69.

Do we have any side effect by disabling EC2M?

**Comment by vanc** [comment]
Tried with "openssl speed" for various ECDH benchmarks, revision a7b0b69 caused huge regression, except x25519 and p256 which all have dedicated ASM packs.

For example: ecdhp224.

-pre7:
                             op      op/s
 224 bits ecdh (nistp224)   0.0005s   **2050.1**

1.1.0g:
                              op      op/s
 224 bit ecdh (nistp224)   0.0001s  **10528.2**

**Comment by vanc** [comment]
@dot-asm

**Comment by bbbrumley** [comment]
> Do we have any side effect by disabling EC2M?

Yea, speeding up the regression testing significantly ;)

@mattcaswell now is the time to choose from https://github.com/openssl/openssl/pull/6070

> 1. Eventually remove support entirely. If so, this is a step in that direction.
> 2. Enhance support. If so, you need projective coordinates for performance, which is easy to add.

or now 3: make no-ec2m default.

I support (3), because it will be a slow bleed showing just how little ec2m usage there is out there.

(For example, https://github.com/openssl/openssl/commit/3a6a4a93518fbb3d96632bfdcb538d340f29c56b fix was almost 2 years in the wild https://github.com/openssl/openssl/commit/f54be179aa4cbbd944728771d7d59ed588158a12 before I filed that PR; not because it was affecting me, just kicking the tires.)

> caused huge regression

@vanc in this case, `openssl speed` is not representative of a typical app, in the sense that it uses precomputation. Our experiments show the patch, in practice, is about 50-60% slower. That's the price you pay for security. It can be improved, ofc. (Both in security and performance.)

**Comment by mattcaswell** [comment]
> Enhance support. If so, you need projective coordinates for performance, which is easy to add.

How easy? Is this something you can help us with?

> make no-ec2m default.

That would probably be counted as a breaking change which we're not supposed to do in 1.1.1. It could be done in 1.2.0, but that doesn't help now.

**Comment by mattcaswell** [comment]
> BTW, the SM2 test failed in the evppkey tests, since pre6.

@vanc, the output is a bit confusing. The test is to ensure that an operation fails and that it does so in the right way - which it does, so the test actually passes. However a side effect is that you see spurious error messages on the screen in the process. We should probably clean that up at some point.

**Comment by t8m** [comment]
I am confused, how could a7b0b69 cause regression of speed for prime field curves when this commit does not touch prime curve code at all?

**Comment by mattcaswell** [comment]
> I am confused, how could a7b0b69 cause regression of speed for prime field curves when this commit does not touch prime curve code at all?

The speed issue is for binary curves which the above commit does touch.

**Comment by bbbrumley** [comment]
> cause regression of speed for prime field curves when this commit does not touch prime curve code at all

@t8m you're right, the P-224 diff is actually caused by https://github.com/openssl/openssl/pull/6116. (And if you want fast + secure P-224, pass `enable-ec_nistp_64_gcc_128`, so I'm gonna argue any slowdown is irrelevant.)

> The speed issue is for binary curves which the above commit does touch.

@mattcaswell it is _much_ more prominent for binary curves, yes

> How easy? Is this something you can help us with?

My team is slammed at the moment. Maybe Aug time frame? Anyway it's basically copy / paste / cleanup of this: https://github.com/openssl/openssl/issues/2386

**Comment by t8m** [comment]
Well, there are still some big endian systems out there...

**Comment by bbbrumley** [comment]
> Well, there are still some big endian systems out there...

... that can now enjoy better side-channel security :)

**Comment by dot-asm** [comment]
> Our experiments show the patch, in practice, is about 50-60% slower.

One has to keep in mind that percents work differently in different directions. I mean <100% *improvement* is always <2x difference, while <100% regression can as well be 5x difference. Anyway, it's just to accept the cost. Most popular algorithms are unaffected, and that's what matters. Slower test can be annoying, but is not viewed critical.

**Comment by mattcaswell** [comment]
> My team is slammed at the moment. Maybe Aug time frame? Anyway it's basically copy / paste / cleanup of this: #2386

See #6418.

**Comment by mattcaswell** [comment]
#6690 got merged which should help *significantly* with binary curves. It doesn't entirely get us back to where we were with performance prior to the various SCA mitigations going in - but I'll take a slower secure implementation over a fast insecure one. Closing this.
