### ISSUE TITLE
Simplify bn_from_montgomery to do the minimum work necessary

### ISSUE THREAD

**Issue by briansmith** [openssl/openssl#6399]
Apologies in advance if I am misunderstanding things.

I read this comment in https://github.com/openssl/openssl/blob/83cf7abf8e9abbd4d0b68c63dc1cb43374aafe63/crypto/bn/asm/x86_64-mont5.pl#L2136-L2141

If I understand the comment `bn_from_montgomery` writes outside where its argument points. In particular, it assumes that the argument points into a larger buffer, and it zeroes that entire larger buffer. 

If so, this makes `bn_from_montgomery` less useful than it could be. In particular, it would be great if we could use `bn_from_montgomery` to accelerate `BN_from_montgomery()` in general.

I also find this to be difficult to understand from a security review standpoint. I would prefer that all zeroing in RSA exponentiation be done via `OPENSSL_cleanse`/`OPENSSL_free`. It seems like there is already an `OPENSSL_cleanse()` at https://github.com/openssl/openssl/blob/166f0082e7ce53ed608d8519526b99893ca7925e/crypto/bn/bn_exp.c#L1109 so the zeroing being done in `bn_from_montgomery` may be redundant now? That is, maybe the optimized zeroing code is actually slowing things down now?

Also, that comment indicates that bn_from_montgomery does some extra copying to ensure its arguments don't create false sharing. Since `bn_from_montgomery` is only called once during an exponentiation, maybe we should just do the simplest thing that works, and avoid the re-alignment adjustment?

**Comment by dot-asm** [comment]
> If I understand the comment bn_from_montgomery writes outside where its argument points.

No. It says "alias ... modulo 4096", i.e. goal is to avoid overlap of 12 least significant bits of stack frame's address and 12 least significant bits of external arguments' address. It doesn't mean that it modify external buffers in *non-prescribed* way, only that manipulating stack frame doesn't interfere with *prescribed* access to external buffers.  There is something called memory disambiguator, which is responsible for canceling loads that were speculatively moved ahead of stores. I mean if programming order is "store to X" followed by "load from Y", and "load from Y" is speculatively executed prior store, then if X and Y are same, processor would have to cancel speculative load and re-execute it after store. However it looks only at 12 least significant bits, so that X and X+4096 count as same address. Aligning stack frame in specific manner relative to external buffers allows to avoid this false positives.

> In particular, it assumes that the argument points into a larger buffer, and it zeroes that entire larger buffer.

No, it's not about argument pointing into a larger [external] buffer, but stack frame. Yes, bn_from_montgomery does allocate larger stack frame than it actually uses. And it does cleanse more stack than it actually used. But there is nothing that prohibits it to do that. It allocated *a* stack frame and it cleansed it. But how this larger-than-needed stack frame is allocated? And how much is cleansed? It's allocated using exactly same algorithm as other subroutines, so that it overlaps ... *previously* allocated stack frames. And it cleanses as much as other subroutines used. This way previously called subroutines can be let off the hook cleansing their stack frames. I mean customarily subroutine developer have to assume that caller doesn't even know how to cleanse subroutine's stack frame and hence subroutines will be bound to cleanse it on per-call basis. But if you know that caller calls specific subroutine at the end, you can use the opportunity to cleanse stack only once. That's what bn_from_montgomery does [besides performing prescribed calculations]. In other words one shouldn't look at stack handling from bn_from_mongomery's perspective alone, but even from others'. Yes, this means that bn_from_montgomery is not meant to be called "standalone" but only in specific sequence, equivalent to one observed in bn_exp.c.

**Comment by dot-asm** [comment]
Just in case it wasn't clear. As far as cleansing goes, bn_from_montgomery cleans up after its "fellow" assembly subroutines, and only does things that can't be done in high-level language [such as C]. It doesn't have any side effects that would be observable from high-level language. In other words it doesn't actually steps on caller's toes as original message implied. Of course standing suggestion is to take alloca from assembly domain, so that cleansing *becomes* caller's business...

**Comment by dot-asm** [comment]
> this means that bn_from_montgomery is not meant to be called "standalone" but only in specific sequence

"Not meant" doesn't mean "can't". If called "standalone" it will produce expected result. But it will do that with *non-observable* side effect of allocating larger stack frame [and cleansing it] than minimally required.
