### ISSUE TITLE
__bn_sqr8x_reduction or a generalized bn_from_montgomery equivalent should be available to C code

### ISSUE THREAD

**Issue by briansmith** [openssl/openssl#6400]
An alternative to using BN_mod to reduce an input in ℤ/nℤ to an element in ℤ/pℤ and and element in ℤ/qℤ is descibed in in the section "Intrinsically BPA-Protected CRT-RSA Implementation — Smooth CRT-RSA" in https://eprint.iacr.org/2007/039.pdf. I have implemented this reduction method in *ring* and BoringSSL has implemented it too.

Basically, we do the reduction using `BN_from_montgomery_word` followed by `BN_to_montgomery()`. (In fact, there is a way to eliminate the call to `BN_to_montgomery()` that is described in the paper and implemented in *ring*.)

`__bn_sqr8x_reduction` in the x86_64 assembly module implements (AFAICT) exactly the reduction that is needed (I'm assuming it isn't optimized explicitly for the squaring case; if so, then it would need to be tweaked) in a side-channel-free and high-performance way.

It would be nice if this optimized implementation could be made available for use outside of the assembly module by C/Rust code.

Alternatively, maybe `bn_from_montgomery` could be generalized to accept a double-sized input argument?

@dot-asm WDYT?

**Comment by briansmith** [comment]
Such a function could possibly also be used to resolve #6367, by having `BN_generate_dsa_nonce()` generate random bytes that are 2X the length of the modulus and then using this function to do the reduction. (I have implemented something like this in another project.)

**Comment by davidben** [comment]
Some notes:

The paper's version involves precomputing R^3, but that's only needed to take the result straight into Montgomery form in preparation for exponentation (what Brian describes as eliminating the call to `BN_to_montgomery()` above). But that optimization is tricky in OpenSSL anyway because of the RSAZ code, which uses a different radix, making R different. I could imagine instead precomputing an appropriate value to take it into whatever the to-be-selected modular exponentiation implementation needs, but we haven't bothered with that in BoringSSL. It's an awful lot of work to shave one multiplication + reduction when you're doing a thousand of them anyway. :-)

Also this requires the input fit in the Montgomery reduction bounds for the modulus. So it doesn't easily work for unbalanced RSA keys where p and q are vastly different sizes (rare), or for multi-prime RSA (which OpenSSL supports these days). So you'd either need to deny CRT to those cases, accept a leaky reduction and lean on blinding (do you all turn that on by default these days? I forget), or try to generalize it.

I think it can be generalized by fiddling with the Montgomery reduction algorithm, likely at the cost of extra factors of R^-1 to clear, but I haven't thought about this very hard since we don't support multi-prime and we just deny CRT to unbalanced keys.

**Comment by briansmith** [comment]
> It's an awful lot of work to shave one multiplication + reduction

I believe it saves 2 * (1 multiplication + 1 reduction) since it has to be done for each of p and q. Also we only do ~450 modular multiplications IIUC. So I guess it'd be about 1% savings.

**Comment by briansmith** [comment]
Besides the 1% savings, there's also a security analysis benefit because doing this on x86_64, especially with Broadwell+) hardware eliminates a huge chunk of code from the TCB from consideration (if/when the rest of the Smooth CRT RSA implementations are implemented).

**Comment by briansmith** [comment]
> I believe it saves 2 * (1 multiplication + 1 reduction)

2 * (1 multiplication + 1 to_mont + 1 from_mont) and maybe one or two other Montgomery conversions.

**Comment by davidben** [comment]
Don't we also need 1024 x (square + reduction) per prime? Presumably squares are cheaper than multiplications, but 1024 is also a pretty big number.

(I'm certainly happy to be proven wrong that the optimization isn't very useful! That's makes an easy-ish place speed things up. Though I would suggest OpenSSL not bother with the R^3 version to start with because it is a bit more work to thread through the rest of the code.)

**Comment by briansmith** [comment]
> Don't we also need 1024 x (square + reduction) per prime? Presumably squares are cheaper than multiplications, but 1024 is also a pretty big number.

Oh, yeah! My bad!

Seriously though, I don't think even a ~1% improvement would matter too much but I do think it would be great to minimize the amount of code (potentially) executed during the RSA computation.
