### ISSUE TITLE
Max message size for CertificateVerify too small

### ISSUE THREAD

**Issue by christianpaquin** [openssl/openssl#6433]
I'm experimenting with the integration of post-quantum cryptography into TLS 1.3 using OpenSSL. I got the post-quantum key exchange to work (*), and I'm now working on the authentication.

I ran into an issue while integrating a PQ signature algorithm with a large signature size. The code fails in ossl_statem_client_max_message_size's TLS_ST_CR_CERT_VRFY state (in statem_clnt.c) because the CertificateVerify message, containing the large signature, exceeds SSL3_RT_MAX_PLAIN_LENGTH.

Why is the CertificateVerify's size limited to SSL3_RT_MAX_PLAIN_LENGTH (2^14), while TLS 1.3 specifies the message as:

  struct {
    SignatureScheme algorithm;
    opaque signature<0..2^16-1>;
  } CertificateVerify;

requiring a max size of 2^16 + 2?

(*) for the curious, see: https://github.com/open-quantum-safe/openssl/tree/OQS-master

**Comment by mattcaswell** [comment]
The max message sizes are just there as a sanity check to ensure that the peer isn't sending us unreasonably large amounts of data (which could be a potential DoS). The maximum's there do not necessarily represent the maximum values allowed by the spec, but rather the maximum that OpenSSL is prepared to accept. Since we don't currently support any signature algorithms in TLS that issue such large signatures it seems reasonable to set a lower limit - and that limit happens to be the maximum amount of data that would fit into a single record. Arguably we could set this a lot lower.

Presumably you've already had to amend OpenSSL's source code to add support for your experimental sig alg? There should be no adverse impacts to you also amending the max allowed certificate verify size.

**Comment by christianpaquin** [comment]
Yes, I'm indeed modifying the source; I'll increase the maximum value in our fork. Thanks for the info.
