### ISSUE TITLE
Openssl does not install

### ISSUE THREAD

**Issue by purplehorse** [openssl/openssl#6506]
I follow exactly this guide:
  
  $ git clone --depth 1 https://github.com/openssl/openssl
  $ cd openssl
  $ ./config enable-tls1_3 --prefix=/home/delia/openssl
  $ make
  $ make install

And I get this output:

```
delia@delia-VirtualBox:~/openssl$ make install
make depend && make _all
make[1]: Entering directory '/home/delia/openssl'
make[1]: Leaving directory '/home/delia/openssl'
make[1]: Entering directory '/home/delia/openssl'
make[1]: Leaving directory '/home/delia/openssl'
*** Installing development files
install ./include/openssl/aes.h -> /home/delia/openssl/include/openssl/aes.h
cp: './include/openssl/aes.h' and '/home/delia/openssl/include/openssl/aes.h' are the same file
Makefile:309: fallo en las instrucciones para el objetivo 'install_dev'
make: *** [install_dev] Error 1
delia@delia-VirtualBox:~/openssl$ 

```

I don't seem to get any warning in the "make" but I can copy the code if it is necessary. I don't know why the installation is not working...

**Comment by mattcaswell** [comment]
You cloned the source code from github into the "openssl" directory of your home dir, i.e. "/home/delia/openssl". But when you ran "config" you specified the install location as "--prefix=/home/delia/openssl". So the source and install location are the same place! When you run "make install" it falls over because the files are already there. Specify a different location to install to than where your source is.

**Comment by purplehorse** [comment]
That was it! thank you!

**Comment by mattcaswell** [comment]
Great! Closing.

**Comment by mosquitotrip** [comment]
heeh, ty :D
