### ISSUE TITLE
EC_POINTs_mul and ECDSA_do_sign with NID_secp384r1 is slower in 1.1.1

### ISSUE THREAD

**Issue by kamulos** [openssl/openssl#6512]
I am not sure if this is a mistake on my part or a side effect of a security improvement:

For the NID_secp384r1 curve EC_POINTs_mul (without p and m values) and ECDSA sign takes double the time in my benchmarks compared to 1.1.0 compiled with the same parameters.

**Comment by mattcaswell** [comment]
There has been various work to improve side-channel attack resistance in the EC code. It's most like a side effect of that. Ping @bbbrumley, @romen for comment.

**Comment by romen** [comment]
I'll have to run some tests and profiling for a full answer, probably in the next days, but yes this sounds really likely to be a side-effect of implementing some of the recent SCA mitigations, so until further notice I would consider this as a "slower but safer" case.

Also, if the slow-down is measured through `openssl speed`, as @bbbrumley mentioned in https://github.com/openssl/openssl/issues/6396#issuecomment-394511377 , we should remember that `speed` is not representative of a typical app (given that `speed` uses precomputation, while most applications using the EVP interface do not).

Anyhow, I'll run more detailed tests/comparative profiling to give a more complete answer.

Also, I wouldn't mark this as a duplicate of #6396 because in that issue there is a bit of confusion between reported slowdown on binary curves while the datapoints refer to prime curves.

**Comment by mattcaswell** [comment]
@romen - any further update on this?

**Comment by romen** [comment]
@mattcaswell not yet, I've been swamped working on https://github.com/openssl/openssl/pull/6418#issuecomment-400977255, which, if all goes well, should anyway improve the performance anyway which I guess would allow to close this issue.

**Comment by davidben** [comment]
When we did our own side channel hardening, we found that merely [stack-allocating](https://boringssl.googlesource.com/boringssl/+/master/crypto/fipsmodule/ec/felem.c) all the temporary field elements inside the [low-level point operations](https://boringssl.googlesource.com/boringssl/+/master/crypto/fipsmodule/ec/simple.c#215) (we cap curve sizes at P-521, which fits comfortably on the stack) and avoiding `BIGNUM` gave enough of a speed boost to more than cover the loss of the variable-time multiply. (Our work started by fixing the underlying field operations and then went up.)

Although our constant-time multiply is [windowed](https://boringssl.googlesource.com/boringssl/+/master/crypto/fipsmodule/ec/simple_mul.c) with a constant-time table lookup, while it looks like the new OpenSSL one effectively uses a 1-bit window, so that probably helps.

**Comment by davidben** [comment]
(#6418 only helps curves over binary fields, right? secp384r1 is a prime field.)

**Comment by romen** [comment]
@davidben you are right that specific change won't affect prime curves directly: I updated my previous comment accordingly!

**Comment by romen** [comment]
@mattcaswell @kamulos I can confirm that indeed the SCA changes are introducing the slowdown: I am using my own "alternative `speed`" tool for benchmarking as it allows me to run stuff through the EVP interface and specify a fixed number of operations rather than a fixed time window (which is nicer for profiling comparison):
```
/opt/openssl-111-pre3/bin/harness  -evp_pkey_keygen EVP_PKEY_EC:secp384r1
Running 100 times 384 bit EVP_PKEY_EC:secp384r1 evp_pkey_keygen... 192155357 cycles
/opt/openssl-master/bin/harness  -evp_pkey_keygen EVP_PKEY_EC:secp384r1
Running 100 times 384 bit EVP_PKEY_EC:secp384r1 evp_pkey_keygen... 353382204 cycles
```
[Here](https://imgur.com/a/PL84iuV) you can see the profiling graphs and visually appreciate why it clearly is a case of "safer but slower".
There is some commentary on the imgur post.

**Comment by mattcaswell** [comment]
Thank @romen. I think this issue should be closed on the basis that this is an expected side effect.
