### ISSUE TITLE
Support personalization string in SM2 signatures

### ISSUE THREAD

**Issue by randombit** [openssl/openssl#6534]
Some discussion on adding this in closed PR #6443

I started working on this but ran into a snag. SM2 personalization works by hashing the personalization string along with other values (like info on the curve) into a string `ZA`. Then `e = H(ZA || msg)` is taken as the message representative that is signed. But the current signature pmeth just gets the hash, and we can't go from `ZA` and `H(msg)` to ``H(ZA || msg)``.

I see some maybe promising callbacks in `EVP_PKEY_METHOD`: `signctx_init`, `signctx`, `verifyctx_init`, and `verifyctx`  look like they expose the EVP_MD_CTX. If that works, then perfect - the init functions can compute ZA, add it to the MD ctx, and then the rest of the message is added after. But it seems these functions are used for HMAC, Poly1305, etc - I didn't find any users for public key signatures. So I wanted to ask for advice before I go too deep into something that won't work.

**Comment by randombit** [comment]
@mattcaswell You probably ran into something similar for Ed25519 which also hashes the message with a prefix, any hints?

**Comment by mattcaswell** [comment]
Well, we've only exposed PureEdDSA via EVP (not the pre-hash variant) - and that only supports one shot signing (i.e. no EVP_DigestSignUpdate) with a NULL digest (effectively PureEdDSA does its own hashing), so I don't think its really comparable.

I think `signctx_init` and friends should do what we need it to do here. I don't think they're intended to be specific to MACs.

**Comment by randombit** [comment]
Ah yeah a somewhat different situation then. I'll try with `signctx_init`.

**Comment by randombit** [comment]
I spent some time on this and I don't think `signctx_init` will work. The problem is this function is called when `EVP_DigestVerifyInit` or `EVP_DigestSignInit` are invoked. But until that function returns, there is no `EVP_PKEY_CTX` on which one can call `EVP_PKEY_ctx_ctrl_str` to set the identifier.

I also saw `EVP_PKEY_CTRL_DIGESTINIT` which is invoked during `EVP_DigestInit_ex` , which looked like another approach that might work, but it has the same problem, at the point it is used no `EVP_PKEY_CTX` exists and so the identifier cannot be known at the point that ctrl is invoked.

I'll keep working on this, there must be some way to make it work, but right now I don't see it.

**Comment by randombit** [comment]
One thing I guess could work, would be placing the identifier on the `EVP_PKEY` instead of `EVP_PKEY_CTX`. So, roughly:

```
EVP_PKEY *pkey = load_a_pkey_from_somewhere();
EVP_PKEY_set_context(pkey, "user@example.com");
EVP_DigestSignInit(..., pkey);
```

This way, the identifier string is available at initialization time, in which case I think `signctx_init` can use it.

@matcaswell Does some approach like this seem ok?

**Comment by mattcaswell** [comment]
I'm not especially keen on that approach because it moves operation specific data into the EVP_PKEY, i.e. potentially you have to update the EVP_PKEY every time you use it, which isn't really the idea behind an EVP_PKEY. Operation specific data should really go in the EVP_PKEY_CTX.

Here's an idea: how about calling EVP_DigestSignInit() twice? So you call it once and get a handle on the EVP_PKEY_CTX. If you don't care about the personalisation string you can just go ahead and use it. If you do want personalisation then you set the string on the EVP_PKEY_CTX, and then call EVP_DigestSignInit() again to re-initialise. It's a bit nasty - but I think that might work?

Another possibility is to create a new version of EVP_DigestSignInit(), which allows you to pass in your own EVP_PKEY_CTX.
