### ISSUE TITLE
Invalid Certificate versions are accepted

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#6599]
In this report:

https://cryptosource.de/docs/Report_CPT_findings.pdf

It is stated that OpenSSL will accept invalid Certificate versions:

"A number of tested implementations accept X.509 certificates which indicate the value “5” in their X.509
version field, even though currently the highest version is 3. Implementations with this behavior may
exhibit security vulnerabilities in the future if newer versions of the X.509 standard with noncompatible
processing rules are issued."

It is not clear to me that this is actually a defect at all. Potentially this was done on purpose for inter-operability reasons. It also seems unlikely to me that, given numerous implementations behave in this way, incompatible processing rules will ever be specified for some future version number.

However, I'm raising it here to see what others think about it.

**Comment by richsalz** [comment]
I think we should reject versions other than 0,1,2 (those are the values, not the version).  It's a bugfix.

**Comment by ericroman920** [comment]
I agree that versions other than v1, v2, v3 should be rejected.

While it may not be be a security issue (at least currently), being lax is harmful per https://www.ietf.org/id/draft-thomson-postel-was-wrong-03.txt.

The problem is more nuanced than made out by that paper which includes only results for what I presume was a test using v6 (INTEGER 5).

Broadly speaking, certificate verification implementations have been buggy/lax with how version specific constraints are enforced. For instance some will allow extensions to be present and applied even for v1 or v2 certificates. And some will accept undefined version numbers as equivalent to v3. Etc.

Because the symbolic version number is off-by-one from its INTEGER representation, an easily made historic mistake when generating certificates was to encode v3 certificates as INTEGER 3 rather than INTEGER 2, in effect making it a v4 certificate. Some implementations recognize this problem and have a compatibility hack scoped to it.

I investigated handling of "v4" certificates for Chromium in https://bugs.chromium.org/p/chromium/issues/detail?id=522220, and found that mis-encodings of version numbers is not currently a problem for certificates in the public Web PKI. It has been a problem seen in self-issued certificates and client certs. However given the diversity of ways implementations handle this, users can't realistically rely on such invalid certificates to be accepted cross platform, making it a bad practice.

For instance:

* NSS accepts invalid version numbers
* OpenSSL accepts invalid version numbers
* Windows's CryptoAPI accepts invalid version numbers
* macOS's security framework REJECTS invalid version numbers
* ...however on iOS invalid versions numbers appear to be accepted
* Mozilla pkix REJECTS invalid version numbers, however special cases v4 (3)

The Google Chrome Web Browser currently REJECTS certificates with invalid version numbers across platforms. To my knowledge this has not resulted in notable compatibility problems, making this a plausible solution for Web PKI focused applications.

Similarly, the Firefox web browser currently rejects certificates with an invalid version number, however made an explicit allowance for v4 certificates (https://bugzilla.mozilla.org/show_bug.cgi?id=1047177).

Cheers.

**Comment by kroeckx** [comment]
RFC5280 says: `Implementations SHOULD be prepared to accept any version certificate.`

So I'm closing this as not a bug.

**Comment by DDvO** [comment]
It may make sense to produce a warning if the version of an X.509 certificate is not one of v1, v2, or v3,
but the OpenSSL crypto lib so far is is not well equipped to issue warnings
and its users likely would not be prepared to handle them suitably.
