### ISSUE TITLE
OpenSSL violates RFC 5246, section 7.4.4 certificate_authorities size

### ISSUE THREAD

**Issue by michael-o** [openssl/openssl#6609]
We have stumbled upon this rather obscure issue when we investigated a mutual auth issue in company-internal CAs:
 
At our company a global CA certstore is maintained, for Java's JSSE (cacerts) as well as Schannel.  This truststore public CAs maintained by Microsoft/Oracle as well as our company's ones. The files (JKS, PEM) are about one megabyte large.

We tried to perform mutual auth from Java side (1.8.0_172) on the server and failed with:

    main, handling exception: java.lang.RuntimeException: Field length overflow, the field length (72207) should be less than 65536
    %% Invalidated:  [Session-1, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]
    main, SEND TLSv1.2 ALERT:  fatal, description = internal_error
    main, WRITE: TLSv1.2 Alert, length = 2
    main, called closeSocket()
    main, IOException in getSession():  javax.net.ssl.SSLException: java.lang.RuntimeException: Field length overflow, the field length (72207) should be less than 65536

After a bit of investigation we came to the conclusion that 

      struct {
          ClientCertificateType certificate_types<1..2^8-1>;
          SignatureAndHashAlgorithm
            supported_signature_algorithms<2^16-1>;
          DistinguishedName certificate_authorities<0..2^16-1>;
      } CertificateRequest;

is violated in terms of DN size and Java terminated the handshake. So we wanted to try with OpenSSL via mod_ssl on Apache Web Server: `Apache/2.4.33 (FreeBSD) OpenSSL/1.0.2o`. Both have been installed from ports.
Converted the JKS file in question to PEM format:

    $ grep -c "BEGIN CERTIFICATE" cert.pem
    669

and hooked that into HTTPd:

    SSLCACertificateFile /tmp/cert.pem
    SSLVerifyClient require
    SSLVerifyDepth 5

We then tried OpenSSL from command line with:

    echo -ne 'GET /~osipovmi/tls-auth/phpinfo.php HTTP/1.1\r\nHost: hostname\r\n\r\n'  | openssl s_client -connect hostname:443 -CAfile /etc/ssl/cert.pem -ign_eof -prexit -msg

in midair we see:

    <<< TLS 1.2 Handshake [length 10fcf], CertificateRequest
        0d 01 0f cb 03 01 02 40 00 1e 06 01 06 02 06 03
        05 01 05 02 05 03 04 01 04 02 04 03 03 01 03 02
        03 03 02 01 02 02 02 03 0f a5 00 13 30 11 31 0f
        30 0d 06 03 55 04 03 13 06 44 2d 52 20 43 41 00
        1b 30 19 31 17 30 15 06 03 55 04 03 13 0e 41 42
        ...
        20 4c 31 42 00 79 30 77 31 0b 30 09 06 03 55 04
        06 13 02 44 45 31 0f 30 0d 06 03 55 04 08 0c 06
        42 61 79 65 72 6e 31 11 30 0f 06 03 55 04 07 0c
        08 4d 75 65 6e 63 68 65 6e 31 10 30 0e 06 03 55
        04 0a 0c 07 53 69 65 6d 65 6e 73 31 11 30 0f 06
        03 55 04 05 13 08 5a 30 30 33 52 48 35 53 31 1f
        30 1d 06 03 55 04 03 0c 16 4d 6f 62 69 6c 69 74
        79 20 53 54 43 20 50 50 4b 49 20 4c 69 76 65
    >>> ??? [length 0005]
        15 03 03 00 1a
    >>> TLS 1.2 Alert [length 0002], fatal decode_error
        02 32

`0x10fcf` = 69 583. This is more that the allowed `2^16-1`. I can see huge encrypted handshake messages in Wireshark. Using Firefox (ESR 52.8.0 on Windows 7) as a TLS client gives me:

    SSL hat eine nicht wohlgeformte Handshake-Nachricht "Zertifikat-Anfrage" empfangen. Fehlercode: SSL_ERROR_RX_MALFORMED_CERT_REQUEST

So Firefox does check on the max length as does OpenSSL with `s_client`.

I consider this as a bug in the server-side of OpenSSL not checking the size of the encoded DN buffer going out to the client. Can you confirm? Do you need more data from me? I can send pcaps or full logs privately.

**Comment by michael-o** [comment]
@bagder have you stumbled upon this in a similar fashion? This can be, of course, reproduced with curl:

    <= Recv SSL data, 5 bytes (0x5)
    0000: .....
    == Info: TLSv1.2 (IN), TLS handshake, Request CERT (13):
    <= Recv SSL data, 69583 bytes (0x10fcf)
    0000: .......@....................................0.1.0...U....D-R CA.
    0040: .0.1.0...U....ABLE Root CA 1..0.1.0...U....SI1.0...U....ACNLB.'0
    ...
    10e80: G0E..U...>CPS CONTAINS IMPORTANT LIMITATIONS OF WARRANTIES AND L
    10ec0: IABILITY1907..U...0www.entrust.net/CPS is incorporated by refere
    10f00: nce1.0...U....(c) 2008 Entrust, Inc.1.0,..U...%Entrust Certifica
    10f40: tion Authority - L1B.y0w1.0...U....DE1.0...U....Bayern1.0...U...
    10f80: .Muenchen1.0...U....Siemens1.0...U....Z003RH5S1.0...U....Mobilit
    10fc0: y STC PPKI Live
    => Send SSL data, 5 bytes (0x5)
    0000: .....
    == Info: TLSv1.2 (OUT), TLS alert, Server hello (2):
    => Send SSL data, 2 bytes (0x2)
    0000: .2
    == Info: OpenSSL SSL_read: error:1408709F:SSL routines:ssl3_get_certificate_request:length mismatch, errno 0
    == Info: Closing connection 0
    curl: (56) OpenSSL SSL_read: error:1408709F:SSL routines:ssl3_get_certificate_request:length mismatch, errno 0

**Comment by richsalz** [comment]
OpenSSL is liberal in what it accepts.  It is hard to see that this is a bug, but more like a configuration error.

**Comment by michael-o** [comment]
So you are telling that is intentionally does not adhere to the RFC with the upper limit of `certificate_authorities<0..2^16-1>` although other clients will reject it?

This isn't about accepting, this is return/write from OpenSSL server code.

**Comment by davidben** [comment]
The length listed in the original report, 0x10fcf, is not the length of the certificate_authorities list. It's the length of the overall message. That one is not bounded by 2^16-1. Rather, the certificate_authorities list is. There, it is not syntactically possible to express a certificate_authorities list larger than 2^16-1. That syntax in TLS also specifies the number of bytes in the byte length, so certificate_authorities has a two byte length. You need to reconsider your design if you're trying to send 1MB of certificate names.

Finally, however, I think this is solidly an OpenSSL bug. OpenSSL's encoder is trying to encode a large length into two bytes that doesn't fit and, rather than noticing the error, it just truncates the length to fit. (Here it's reporting a length of 0x0fa5.) The receiver is then rightfully complaining it is not a valid CertificateRequest. This comes from everything being serialized with pointer arithmetic and macros like `s2n` and `l2n3`. This has been fixed on the master branch, but it looks like both 1.0.2 and 1.1.0 still use the macros.

In the likely case, it produces something unparseable. If adversarially misconfigured, one can imagine worse consequences on other messages (here, the problematic field is last, so it's fine) under a threat model that allows some attacker-supplied configuration. In so far as one can frame this as OpenSSL being "liberal in what it accepts", this is another demonstration of how [problematic](https://tools.ietf.org/html/draft-thomson-postel-was-wrong-03) the idea can be. Postel's Law has no place in a security library.

**Comment by richsalz** [comment]
I agree, I misunderstood the original report.

**Comment by richsalz** [comment]
ping @mattcaswell (who's away for a couple of days)

**Comment by michael-o** [comment]
@davidben 

> The length listed in the original report, 0x10fcf, is not the length of the certificate_authorities list. It's the length of the overall message. That one is not bounded by 2^16-1. Rather, the certificate_authorities list is. 

So how do I determine  the size of the `certificate_authorities`? I doubt that someone else in the message has a huge impact on the size.

> You need to reconsider your design if you're trying to send 1MB of certificate names.

This is way out of my control. The company is too large (350 000 employees). Of course, I will raise this, but I don't want to maintain my own CA store and sync periodicly.

> "liberal in what [configuration?] it accepts"

I am aware of this principal and expect OpenSSL to be conversative in what it sends.

@richsalz Thanks for reconsidering.

@markt-asf This might be interesting for you and tcnative.

**Comment by davidben** [comment]
> This is way out of my control. The company is too large (350 000 employees). Of course, I will raise this, but I don't want to maintain my own CA store and sync periodicly.

Alas, this detail of the protocol is outside of everyone's control at this point. It's a two byte length in TLS 1.0 through 1.3, which means you can't fit a length bigger than 2^16. Any OpenSSL fix here would amount to failing the connection on the server, rather than the client, so it still wouldn't work for you. (Silently truncating the CA list is, of course, not reasonable.) A fix would entail adding a new version or extension to TLS and then getting it into all clients and servers.

I've definitely seen servers that send humongous CertificateRequests, but they've always been mistakes. You are supposed to advertise the CAs that you'd accept certificates from. That means you don't want the global trust store for the Web PKI; those CAs presumably aren't issuing certificates for your employees. Indeed you wouldn't want to accept arbitrary ones for security reasons.

Rather, it's more likely that some internal CA at your company is issuing these, or perhaps you've partnered with some CA to manage this for you. You would then only need to include that root in CertificateRequest, not the entire trust store.

**Comment by michael-o** [comment]
@davidben 

> Alas, this detail of the protocol is outside of everyone's control at this point. It's a two byte length in TLS 1.0 through 1.3, which means you can't fit a length bigger than 2^16. Any OpenSSL fix here would amount to failing the connection on the server, rather than the client, so it still wouldn't work for you. (Silently truncating the CA list is, of course, not reasonable.) A fix would entail adding a new version or extension to TLS and then getting it into all clients and servers.

I don't expect anymore to derive from the RFC at all. In fact, I expect the opposite, OpenSSL to fail from the server if it sees that the DN list exceeds a two-byte length.

> I've definitely seen servers that send humongous CertificateRequests, but they've always been mistakes. You are supposed to advertise the CAs that you'd accept certificates from. That means you don't want the global trust store for the Web PKI; those CAs presumably aren't issuing certificates for your employees. Indeed you wouldn't want to accept arbitrary ones for security reasons.
> Rather, it's more likely that some internal CA at your company is issuing these, or perhaps you've partnered with some CA to manage this for you. You would then only need to include that root in CertificateRequest, not the entire trust store.

While I need to strip down the CA, granted, and raise it with our contractor, Atos, I still claim that OpenSSL operates outside of the spec.

**Comment by mattcaswell** [comment]
> I still claim that OpenSSL operates outside of the spec.

Agreed (for 1.1.0 and 1.0.2)

Fix in #6628 and #6629. It would be helpful if you could validate this patch.

The `s2n` and family macros are a nightmare, so I find it very unsurprising that we get it wrong here. The two patches in #6628 and #6629 just fix up the immediate issue. There is already a long term solution in 1.1.1 which is to use the WPACKET for constructing these packets instead - and this is the reason that 1.1.1 (aka master) is unaffected by this bug.

**Comment by michael-o** [comment]
@mattcaswell Great, thanks for the patch. Will compile from master tomorrow and test with `openssl s_server`.

**Comment by mattcaswell** [comment]
Patch was merged, so I'm closing this.
