### ISSUE TITLE
Possible violation of RFC5280

### ISSUE THREAD

**Issue by doru91** [openssl/openssl#6610]
According to RFC5280, otherName field of Subject Alternative Name should be a encapuslated inside an ASN1 SEQUENCE:

SubjectAltName ::= GeneralNames

   GeneralNames ::= SEQUENCE SIZE (1..MAX) OF GeneralName

   GeneralName ::= CHOICE {
        otherName                       [0]     OtherName,
        rfc822Name                      [1]     IA5String,
        dNSName                         [2]     IA5String,
        x400Address                     [3]     ORAddress,
        directoryName                   [4]     Name,
        ediPartyName                    [5]     EDIPartyName,
        uniformResourceIdentifier       [6]     IA5String,
        iPAddress                       [7]     OCTET STRING,
        registeredID                    [8]     OBJECT IDENTIFIER }

   OtherName ::= SEQUENCE {
        type-id    OBJECT IDENTIFIER,
        value      [0] EXPLICIT ANY DEFINED BY type-id }

However, this is not the case when using OpenSSL 1.1.0g, the otherName field follows immediately after 0xA0 byte: A0 2E 06 0A 2B 06 01 04 01 82  37 14 02 03 A0 20 0C 1E 74 65 73 74 40 6B 65 72  62 65 72 6F 73 65 2D 64 6F 6D 61 69 6E 2E 69 6E  74 65 72 6E 61 6C (this is the encapsulation for the universalPrincipalName below):

![san](https://user-images.githubusercontent.com/9597450/42033850-e2b50c06-7ae6-11e8-8a07-bae4014024e6.png)

**Steps to reproduce this:**

- install  OpenSSL 1.1.0g
- use the the configuration file from https://gist.github.com/doru91/253c08435c85217161d02168c15dc2ad
- openssl command for generating a self-signed certificate with SAN fields:
openssl req -x509 -config example-com.conf -new -sha256 -newkey rsa:2048 -nodes -keyout example-com.key.pem -days 365 -out example-com.req.pem
- analyze example-com.req.pem SAN fields using https://lapo.it/asn1js/ 

**or you can directly download the certificate in pem format from:**
https://gist.github.com/doru91/9bebf3a2bf5f04f30a4fa00dc07364d9

**Comment by dcooper16** [comment]
While it may seem odd, the encoding is actually correct. In RFC 5280 GeneralName is defined in the module in Appendix A.2, and that module specifies the use of IMPLICIT tagging. This means that there is not an explicit SEQUENCE (30) tag following the A0 tag (you just know from the ASN.1 that what follows the A1 tag is a SEQUENCE). This is in contrast to the value field within OtherName (test@kerberose-domain.internal), where the tag for UTF8String (0C) follows the A0 tag, since EXPLICIT tagging is specified for that particular field.

You will notice the same thing if you look at other choices within GeneralName. If you look at the DNS names encoded in the subjectAltName extension, the 82 tag (corresponding to [2]) is not followed by a tag for IA5String (22). It is not needed since the ASN.1 indicates that what follows the 82 tag is an IA5String. However, if the module specified EXPLICIT encoding, then there would be a 16 tag after the 82 tag.

**Comment by richsalz** [comment]
Thanks for the nice explanation, @dcooper16.  Maybe we should put that into the FAQ?  Closing this.

**Comment by richsalz** [comment]
Thanks for the nice explanation, @dcooper16.  Created https://github.com/openssl/web/pull/64 to make this a FAQ. Closing this.
