### ISSUE TITLE
CVE-2012-4929/30  OpenSSL -- TLS 1.1, 1.2 denial of service vulnerability.

### ISSUE THREAD

**Issue by kbrahmaa** [openssl/openssl#6612]
Dear OpenSSL,

We are facing CVE-2012-4929 vulnerability on SSL 1.0.2m version as below:-
================================================================  
   nmap -sV --script ssl-enum-ciphers -p 8443 <host>
|     compressors:
|       DEFLATE
|       NULL
 
Above use of "DEFLATE" means using the DEFLATE/Zlib algorithm. Nessus is indicating the server supports DEFLATE (1) and this makes the server vulnerable.
================================================================
Can you please share relevant patch to resolve above vulnerability.   

Sincerely, 
Brahma

**Comment by istenrot** [comment]
The CRIME vulnerability should be mitigated by disabling TLS compression on the server configuration. It's good that OpenSSL still has option to use TLS compression as some users may need it for backwards compatibility in their applications. But normally OpenSSL can be build with `no-comp` configuration option. For HTTPS servers TLS compression should be always disabled as suggested. For legacy servers that don't have a TLS compression switch in configuration and rebuilding OpenSSL is not on option then simple server environment variable `export OPENSSL_NO_DEFAULT_ZLIB=1` should do the trick.

**Comment by kbrahmaa** [comment]
Thanks for the info.

 as you confirmed ..  how can disable TLS compression,  you mean to disable Zlib on Makefile ??

**Comment by tmshort** [comment]
Either:

1. Run './config no-comp` before building the library, or
1. Use the SSL_OP_NO_COMPRESSION option in the `SSL_CTX_set_options()` or `SSL_set_options()` APIs

This is really about server configuration; you should look at how to configure no compression in the server.

Since this is really an inquiry that is more appropriate for the openssl-users@openssl.org (or other apache?) mailing list, I'm going to suggest this issue be closed

**Comment by t8m** [comment]
Closing. The question has been answered.
