### ISSUE TITLE
msys2: libcrypto.a exports DllMain

### ISSUE THREAD

**Issue by Optiligence** [openssl/openssl#6727]
the [build script](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-openssl/PKGBUILD)

Either the existence of `libcrypto.a` in addition to the import library `libcrypto.dll.a` isn’t correct or it doesn’t build correctly. 

related issue https://github.com/Alexpux/MINGW-packages/issues/4080

**Comment by mspncp** [comment]
Hi @Optiligence,

I'm a little in doubt whether your libcrypto.a is really a static library or rather a misplaced copy of the import library for the dll, since you have configured a 'shared' build and also DllMain is guarded by `#if defined(_WINDLL)` in [crypto/cryptlib.c:750](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/crypto/cryptlib.c#L750). Are you still able to build openssl using your build script after commenting out all patches and the sed command? And if this the case, do you still get the .a file with the DllMain symbol?

- If the answer 'yes' holds for both questions, please provide the raw configure and build commands together with a complete build log.
- Otherwise, the problem is probably caused by a bug in your build script and not by OpenSSL, in which case you will have to figure it out by yourself.

HTH,
Matthias

**Comment by mspncp** [comment]
> misplaced copy of the import library for the dll

Well, it can't be an import library, because DllMain is not exported. So maybe it's a static library which was accidentally built with _WINDLL defined?

**Comment by mspncp** [comment]
It seems to be like I expected: the object files are comiled with _WINDLL defined...

```
gcc -I. -I.. -I../include -I/mingw64/include -D_WINDLL -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_MT -DDSO_WIN32 -DL_ENDIAN -O3 -Wall -DWIN32_LEAN_AND_MEAN -DUNICODE -D_UNICODE -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM   -c -o cryptlib.o cryptlib.c

```

...and then a static library is created from the object files.

```
ar  r ../libcrypto.a cryptlib.o mem.o mem_dbg.o cversion.o ex_data.o cpt_err.o ebcdic.o uid.o o_time.o o_str.o o_dir.o o_fips.o o_init.o fips_ers.o x86_64cpuid.o
D:\msys64\mingw64\bin\ar.exe: creating ../libcrypto.a
```

This explains why DllMain is in there although it shouldn't be. But it doesn't explain how and when things started to go wrong. The log doesn't tell me how `libssl.dll.a` gets built. All I can see is

```
if [ -n "libcrypto.dll.a libssl.dll.a" ]; then \
	(cd ..; make libcrypto.dll.a); \
fi
```
Also, I don't see any linker options `-shared` or `--out-implib` anywhere. Since I have no experience with the peculiarities of mingw builds, somebody else would have to look into it.

@levitte?, @dot-asm, any ideas?

**Comment by dot-asm** [comment]
Looks like a bug. Basically dllmain should be in separate file and be passed to linker when dll is linked. It indeed doesn't belong in libcrypto.a(*). But it's not in separate file, not in 1.0.2 that is. I can look into it, but not right away...

(*) libcrypto.a in mingw *is* static library, at least in sense that it's collection of actual object files, and not import stubs as in libcrypto.dll.a.

**Comment by mspncp** [comment]
Ad (*): But why is libcrypto.a built in the first place although a 'shared' build was configured? Wouldn't one expect to see only libcrypto.dll and libcrypto.dll.a?

**Comment by dot-asm** [comment]
> But why is libcrypto.a built in the first place although a 'shared' build was configured?

For same reason libcrypto.a is built on Unix even in shared build. I suppose because we can? At some point I said "we project too much of our Unix experience to Windows." So here you see it :-) On mingw it's not actually a problem, because library search algorithm permits presence of both libcrypto.dll.a and libcrypto.a in same location. By "library search algorithm" I mean you type -lfoo and what happens. mingw linker searches for libfoo.dll.a, foo.dll.a, libfoo.a, foo.lib, libfoo.dll, foo.dll. As curious fact note last two entries. Unlike Microsoft linker, mingw linker can link straight with dlls without export library...

**Comment by levitte** [comment]
In 1.0.2, we don't have the concept of C modules for shared libraries only, do we? So even if we place dllmain in a separate file, using it only for a shared library will be a matter of deeper surgery...
