### ISSUE TITLE
Need a check?

### ISSUE THREAD

**Issue by Bugcheckers** [openssl/openssl#6800]
Hi,

I reported this to the mailing list but no reply. That's why I report it here:

I have seen message_len has checked here:
https://github.com/openssl/openssl/blob/master/crypto/ec/curve448/eddsa.c#L164
https://github.com/openssl/openssl/blob/master/crypto/ec/curve448/eddsa.c#L205

(message_len > 0 && !EVP_DigestUpdate(hashctx, message, message_len)

But it has not checked here:

https://github.com/openssl/openssl/blob/master/crypto/ec/curve448/eddsa.c#L275

!EVP_DigestUpdate(hashctx, message, message_len)

Is there anything missing?

Thanks!

**Comment by Bugcheckers** [comment]
Can you please check these locations as well:

Zlen https://github.com/openssl/openssl/blob/master/crypto/dh/dh_kdf.c#L121
Zlen https://github.com/openssl/openssl/blob/master/crypto/ec/ecdh_kdf.c#L43
sinfolen https://github.com/openssl/openssl/blob/master/crypto/ec/ecdh_kdf.c#L47
inlen  https://github.com/openssl/openssl/blob/master/crypto/ec/curve448/eddsa.c#L31
count https://github.com/openssl/openssl/blob/master/crypto/evp/digest.c#L274
saltlen https://github.com/openssl/openssl/blob/master/crypto/pem/pvkfmt.c#L662
passlen https://github.com/openssl/openssl/blob/master/crypto/pem/pvkfmt.c#L663
seedlen https://github.com/openssl/openssl/blob/master/crypto/rsa/rsa_oaep.c#L271
hLen https://github.com/openssl/openssl/blob/master/crypto/rsa/rsa_pss.c#L213
hLen https://github.com/openssl/openssl/blob/master/crypto/rsa/rsa_pss.c#L115
msg_len https://github.com/openssl/openssl/blob/master/crypto/sm2/sm2_sign.c#L49

**Comment by richsalz** [comment]
Perhaps the better fix is for EVP_DigestUpdate to ignore zero-length data?  Comments, @openssl/committers ?

**Comment by levitte** [comment]
Doesn't that already happen?

https://github.com/openssl/openssl/blob/201b305a2409d9eb13b5e4bfbd4967e04e155a60/crypto/include/internal/md32_common.h#L135

**Comment by richsalz** [comment]
Only for some hashing that includes it (md4, md5, ripe, etc).  Not for sha-3 and 448, for example.

**Comment by paulidale** [comment]
I'd vote for hoisting the zero length check up into `EVP_DisgestUpdate` and removing it from the include.

**Comment by dot-asm** [comment]
> [check for length happens] Only for some hashing that includes it (md4, md5, ripe, etc). Not for sha-3 and 448, for example.

Even though there is no explicit check for zero length, sha-3 (as well as others) do work with zero length. It's just that zero length passes several *implicit* checks that result in no-op. As additional insurance one can add additional round to evp_test that would exercise fragmented input. I mean in addition to just passing whole thing, it can break input into several pieces and pass even a zero-length...

**Comment by dot-asm** [comment]
> do work with zero length. It's just that zero length passes several implicit checks that result in no-op.

Generally speaking less conditions is better. Because branch prediction logic is limited resource. So that if a *should-never-happen* value [of zero length in this case] is checked implicitly (like in SHA3 and elsewhere), it's actually overall favourable to let it be and not check explicitly. Because you won't risk unnecessary mispredicted  branch penalties when processing *real-life* values. This of course is not always-true rule. Specifically in OpenSSL context one can make a case for explicit check arguing that you can skip an *indirect* call, which an expensive affair, and its cost is increasing. But it still would have to be for cases when "magic" value is among commonly observed. And *here* we're talking about *should-never-happen* value, so if it's nevertheless observed (in specifically crafted program), there is no point to optimize for it.
