### ISSUE TITLE
ocsp proxy support feature request

### ISSUE THREAD

**Issue by plaintextcity** [openssl/openssl#6965]
Proxy support in s_client is a welcome addition and helpful for troubleshooting.  In order to troubleshoot connection issues (walking through Ivan Ristic's OpenSSL Cookbook "Testing with OpenSSL") it would be helpful to have the equivalent -proxy support from s_client in ocsp.

**Comment by DanielOatAWS** [comment]
Ping. Can you please confirm that 'ocsp' module cannot work behind a proxy, and if so, maybe see about prioritising this feature request (if possible at all)?

**Comment by t8m** [comment]
@DDvO is this somehow handled already in your http client improvements in the current master?

**Comment by DDvO** [comment]
So far I was not aware of this FR; thanks @t8m for pointing me to it.

I've added proxy support to the OpenSSL crypto lib already 1.5 years ago in PR #10667 (commit 29f178bddfdbd11218fbcba0b8060297696968e3).
This was driven by supporting HTTP proxies for CMP, but since then it would be straightforward to make use of this also for the `openssl ocsp` CLI app.

Yet I wonder if this FR makes sense for the `s_client` app - does this use (classical) OCSP at all, where an HTTP proxy can be of interest?
For `s_client` I can see only the optional use of OCSP stapling (i.e., the TLS cert status extension), 
which reuses the (TCP, HTTP or whatever) connection itself for which TLS is being set up.

**Comment by DDvO** [comment]
I just added explicit HTTP(S) proxy support to the `ocsp` and `s_server` apps in #15245.
Is that what was actually desired in this FR?

**Comment by DDvO** [comment]
@plaintextcity, @ounsworth, @THausherr, @DanielOatAWS, and @drwetter, did #15245 solve the issue for you?

**Comment by drwetter** [comment]
To me it seems so. Thanks!

**Comment by THausherr** [comment]
I can't comment, I'm not sure why I bookmarked this. Most likely I had to troubleshoot some https connection at work years ago.

**Comment by DDvO** [comment]
> I can't comment, I'm not sure why I bookmarked this. Most likely I had to troubleshoot some https connection at work years ago.

Thanks anyway for letting us know.

**Comment by ounsworth** [comment]
@DDvO Neat, I had forgotten about this thread. 

If I remember correctly, at the time I was fuzz testing an OCSP server and I was looking for an easy way to capture valid OCSP requests in a proxy like Burp or OWASP ZAP so that I could then inject broken ASN.1.

I would be happy to test this, but I've never done openssl dev before, so I'll need instructions for getting the nightly build or building your dev branch.

**Comment by DDvO** [comment]
> @DDvO Neat, I had forgotten about this thread.
> 
> If I remember correctly, at the time I was fuzz testing an OCSP server and I was looking for an easy way to capture valid OCSP requests in a proxy like Burp or OWASP ZAP so that I could then inject broken ASN.1.

Interesting use case.
So apparently you were using the OCSP client portion of the `ocsp` app.
For this the `-proxy` option should have helped.

> I would be happy to test this, but I've never done openssl dev before, so I'll need instructions for getting the nightly build or building your dev branch.

Thanks @ounsworth for offering to test this.
According to what we just wrote above, I'm confident that the fix would have helped,
so I don't see the need for testing with your use case.
If you still wanna try it out, you could take yesterday's alpha release from https://www.openssl.org/source/,
which can be built as usual.

**Comment by t8m** [comment]
I am closing this. A new issue can be opened if there is still anything missing with the proxy support in ocsp.
