### ISSUE TITLE
Consider using Facebook's "infer" static analysis tool

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#6968]
From a mail message
```
Yes, infer can run on OpenSSL. It should be easy to run Infer (see http://fbinfer.com/docs/getting-started.html). For OpenSSL all that's needed is `infer -- make -j`.

I just ran infer on 1.1.0d and got lots of results using infer's latest master.
It seems that the quality of the results may have gone down since OpenSSL 1.0.2 and infer from that time, as we now get 222 reports. We monitor the quality of the analysis, but with respect to 1.0.2, which is quite old now...

I quickly looked at just two examples (report #0 and #4); they are both unintended reports.
```

**Comment by dot-asm** [comment]
I'm not impressed. Majority, >2/3 of reports are DEAD_STORE and most common reason is last `*ptr++`. More specifically `++` is viewed problematic because *pointer* is not used anymore. The post-increment is also customarily part of macro, so that in order to address this, one would have to have two macros, one that leaves pointer post-incremented and one that doesn't. It would be excessive and doesn't help readability.

Majority of MEMORY_LEAK reports is because it fails to recognize for example EVP_MD_CTX_free as resource freeing. This is counter-productive, one has to work too hard look for real ones. There seem to be couple in test/\*... Then there is some hairy stuff in o_names.c:236, maybe false positive... Oh! There seem to be real leak in ssl3_final_finish_mac(), multiple logical errors...

**Comment by t8m** [comment]
I do not think we are going to start using random static analyzers regularly as that would require huge investment in the initial work and it would require having a db for waiving false positives. Closing.
