### ISSUE TITLE
iOS build fails when using -fembed-bitcode option

### ISSUE THREAD

**Issue by seifeet** [openssl/openssl#6971]
I'm trying to compile OpenSSL 1.1.1-pre8 for ios-cross, ios64-cross, iphoneos-cross  target with bitcode embedded.

The specific error I'm seeing is: "clang: error: -Wa, is not supported 
with -fembed-bitcode"

**Comment by dot-asm** [comment]
See #6997. On related note 1.1.1 defines ios targets that are more convenient to use as they don't require any additional environment variables, ios-xcrun, ios64-xcrun, iossimulator-xcrun.

**Comment by seifeet** [comment]
@dot-asm does iossimulator-xcrun build for i386 or x86_64?

**Comment by dot-asm** [comment]
You should keep in mind that I (and none of us to my knowledge) am *not* an iOS expect. I for one write only "console" applications for iOS and execute them under debugger from command line. It suffices to ensure that low-level implementations produce correct results, leaving interactions with real-life application to its developer. However, I've never used simulator, so that it's not actually supported to same extent as real hardware. It's just that there is no reason to believe that it wouldn't. As which I would guess that it would just have to be "right" for current Xcode...

**Comment by seifeet** [comment]
Thanks @dot-asm it seems like there should be a separate target for iossimulator x86_64.
Something like that...

    "iossimulator64-xcrun" => {
        inherit_from     => [ "darwin-common" ],
        CC               => "xcrun -sdk iphonesimulator cc",
        cflags           => add("-arch x86_64"),
        sys_id           => "iOS",
        disable          => [ "engine" ],
    },

**Comment by dot-asm** [comment]
Well, if I `xcrun -sdk iphonesimulator cc hello_world.c` on my "reference" system, the binary comes out x86_64 without any additional flags. In other words I see no evidence that separate target would actually be needed. It does seem that it generates code that is "right" for current simulator, and it seems appropriate to just leave it to xcrun's discretion. Besides, you can pass additional flag at config time and choose explicitly. You can even choose to generate fat code by passing both, as in `./Configure iossimulator-xcrun -arch i386 -arch x86_64`. In other words current iossimulator-xcrun seems to be versatile enough...

**Comment by seifeet** [comment]
@dot-asm xcode can have more than one simulator.It is just that x86_64 is the default one. And you can generate a fat library but there is no way to generate i386 only library. Thanks!
