### ISSUE TITLE
Re-enable linux-ppc64le support for travis job

### ISSUE THREAD

**Issue by ghatwala** [openssl/openssl#7016]
Hi All,

Had noticed that the power support was removed as per this merge - https://github.com/openssl/openssl/blob/275bfc56a6c4efa7e80c8cbb11fda0c3f9be818d/.travis.yml  , I have tested and found power support is indeed up and running now - https://travis-ci.org/ghatwala/openssl/jobs/413545508 .

Requesting to re-enable "linux-ppc64le" support for travis.yml.

Regards,
Amit

**Comment by ghatwala** [comment]
@dot-asm - Could you please check above and revert ?

**Comment by gerrith3** [comment]
@dot-asm thanks for your input here, and our apologies for the apparent unreliability in our pre-beta of the Travis-CI service on POWER.  We unfortunately had a lightning storm in Poughkeepsie take out our entire data center there and it took a few days to get everything back up and running.  Your job was impacted by that outage.  And our backup site at University of Oregon's OSL was not yet fully operational, although it is now.  IBM has worked to make 1,000 VMs available for open source use between these two data centers and has been working with the leads at Travis-CI to bring this service to a production level.  We have had a couple of issues shaken out because of new workloads as well and are addressing those as they become clear to us.  Again, we apologies for the outage of several days that occurred as a result of a site outage from a lighting storm - that is something beyond our abilities to control.  However, we do intent to address any functional issues with the service as proactively as possible.  We would love to have your continued usage of the Travis-CI systems as we gear up for full production.  Thank you!  --gerrit - IBM POWER Open Source Ecosystem Lead.

**Comment by dot-asm** [comment]
> We unfortunately had a lightning storm in Poughkeepsie take out our entire data center there and it took a few days to get everything back up and running.

It wouldn't actually be a problem if jobs simply timed out and fail in reasonable time, say a minute. Real problem was that it was queuing without failing for long enough to become bottle-neck.

> we do intent to address any functional issues with the service as proactively as possible. ...  IBM POWER Open Source Ecosystem Lead.

All right, Let's see how #7069 goes...
