### ISSUE TITLE
TLS 1.3

### ISSUE THREAD

**Issue by pinkladywithcoco** [openssl/openssl#7063]
I have downloaded OpenSSL ( 1.1.1-pre9 ) from: https://github.com/openssl/openssl

And builded it on Mac with zlib support as no-shared. The idea is to use OpenSSL for "Https" web server. Everything worked, but when i use Firefox web browser to visit my website to see what tls version is used. It says 1.2 and not 1.3.

shouldn't this line code " ctx = SSL_CTX_new(TLS_server_method()); " prefer the highest TLS version during handshake?

I have visited Facebook webpage to compare and it says the connection used TLS 1.3, so this have to be something with OpenSSL. I'm very new to OpenSSL can someone please show me in C++ how to enable OpenSSL to use TLS 1.3?? the correct steps.

**Comment by mattcaswell** [comment]
> shouldn't this line code " ctx = SSL_CTX_new(TLS_server_method()); " prefer the highest TLS version during handshake?

It prefers the highest TLS version that *both* sides support. 1.1.1-pre9 implements the final RFC version of TLSv1.3. It does not inter-operate with earlier draft versions of the spec. If your browser implements a draft version of TLSv1.3 (as is likely) then the highest version that they both support is TLSv1.2. You will need to wait for your browser to be updated to the new version of the standard in order to be able to inter-operate with 1.1.1-pre9.
