### ISSUE TITLE
Problem in Building openssl_1.0.2p in Visual Studio 2015

### ISSUE THREAD

**Issue by SiddalingaSwamy12** [openssl/openssl#7078]
Am building new release of openssl_1.0.2p using Visual Studio 2015 Command Prompts. I have installed perl and sed. I have written some batch files to build x86 and x64 libraries. When I built same openssl version in VS 2013 and VS 2017 am not facing any issue.

But while building in VS 2015 am unable to build. When I build x86 library in “VS2015 x86 Native Tools Command Prompt” then its building fine and resulting in generating include and lib folder. But when I try to build DLL library then am getting fatal error which says

rc /fo"tmp32dll\libeay32.res" /d CRYPTO ms\version32.rc

‘rc’ is not recognized as an internal or external command, operable program or batch file.

NMAKE : fatal error V1077: ‘rc’ : return code ‘0x1’ Stop. 1 dir(s) moved. 1 dir(s) moved.”

I have attached screenshot too
![vs 2015](https://user-images.githubusercontent.com/37105160/44850615-70e7e280-ac7b-11e8-8b62-8bcd85adbb35.png)

**Comment by dot-asm** [comment]
It should be noted that this project's constant integration with Visual Studio (by courtesy of appveyor.com) does use version 2015. And there are no problems observed. There is no other conclusion to draw but that this is your local environment problem. And these are not something we can't help with. While we do stand for code and build system, it's still user's responsibility to make toolchain work.

**Comment by mspncp** [comment]
@SiddalingaSwamy12 the error message is very clear: you need to find out why `rc.exe` is not found in the PATH.
```
'rc' is not recognized as an internal or external command.
```

**Comment by t-j-h** [comment]
A **correctly** installed VS2015 does include the Windows Kits location in the path in the x86 native command tool.

**Comment by SiddalingaSwamy12** [comment]
Problem is Solved. Windows and Web Development package was not installed in VS 2015. I installed it and now openssl is building fine. 

If anyone wants to install these packages then goto control panel-> programs and features -> VS 2015
Right Click on VS 2015 -> change -> Modify -> select Windows and Web Development - > install

**Comment by gregbown** [comment]
Posting here because I seem to run into this occasionally, since I only build open ssl at most once a year and invariably open the wrong command prompt like the one in Visual Studio C++. Using the wrong command prompts will typically throw a build error like "'rc' is not recognized as an internal or external command." because they  were created for other purposes and so the required binaries are not available.

My experience has been that the command prompt in Visual Studio 2017, specifically "Developer Command Prompt for VS 2017" or "x64 Native Tools Command Prompt for VS 2017" work every time.
