### ISSUE TITLE
SSL_client_version with TLSv1.3

### ISSUE THREAD

**Issue by h-vn** [openssl/openssl#7079]
While working on tests for Perl's Net::SSLeay, I noticed that SSL_client_version returns 771 (TLSv1.2) for a TLSv1.3 connection. If SSL_version or SSL_get_version is called for the same SSL, they return 772 and 'TLSv1.3', respectively. This was observed with the current OpenSSL master branch as of today.

SSL object was created from a SSL_CTX for which SSL_CTX_set_min/max_proto_version(TLS1_3_VERSION) was set.

The manual page indicates that TLS1_3_VERSION is possible for SSL_client_version
https://www.openssl.org/docs/manmaster/man3/SSL_client_version.html

TLS 1.3 RFC specifies using TLS 1.2 in various fields for interoperability purposes when really wanting TLS 1.3, but could someone clarify if SSL_client_version behaviour is correct. If it is, could the manual be clarified to say that TLS1_2_VERSION is the expected value even if TLS1_3_VERSION is returned by the other functions and TLSv1.3 was the only allowed option, for example, when forced with SSL_CTX_set_min/max_proto_version.

**Comment by kaduk** [comment]
It looks like ```ssl_choose_server_version``` just assigns the ```hello->legacy_version``` to ```s->client_version``` at the start and it doesn't really change from that.
That said, I think there's a fairly strong case to be made here that there's "not a bug", in that "there is no single sane conception of what the expected behavior should be" -- the documentation says that:

> SSL_client_version() returns the protocol version used by the client when
initiating the connection.

but there is not a protocol concept of "version used by the client when initiating the connection".  Certainly not in TLS 1.3, but IIUC not even since TLS 1.0.  This seems like a legacy API that we're stuck with exporting but for which there's not a clear meaning to its output.

**Comment by h-vn** [comment]
Thanks for clarifying this. It's now clearer about what to expect from this API call.
