### ISSUE TITLE
Remove the NULL checks of function parameters

### ISSUE THREAD

**Issue by InfoHunter** [openssl/openssl#7130]
This issue is derived from this comment: https://github.com/openssl/openssl/pull/7113#discussion_r215185781

The main idea here is the NULL-checks for parameters should not be done as what the functions do in current code.

This is not addressed in PR #7113 , but it should be done later after 1.1.1 has been released.

**Comment by InfoHunter** [comment]
Should we push this a little further now? What is the opinion from @openssl/committers ?

**Comment by t-j-h** [comment]
-1 in general to removing any parameter checks for NULLs

**Comment by t-j-h** [comment]
I too would add them to all public APIs as it makes the error handling logic cleaner and clearer. 

However some others have expressed that the C runtime library doesn't so why should we. I don't support that argument as we are not the C runtime library and crashing due to missing error checks isn't a good state in my view.

A simply null parameter check leads to better code overall in my experience.

Adding is safer than removing and being consistent also makes a good argument for add null checks on all public APIs.

**Comment by paulidale** [comment]
I concur, a program that crashes in the C runtime library doesn't often generate a request to the library provider asking them to debug the issue.  A crash in a crypto library does in my experience -- it dumped core in your code, it must be your problem and we're going to keep saying this loudly until you prove otherwise.

**Comment by levitte** [comment]
It seems that we need to have that discussion yet again within the team.  Last time this was discussed in depth, it seemed that not checking NULL was favored, because it would immediately show the problem and where it occurs instead of happening *somewhere else* because the caller never bothered to check for errors.

What has always struck me as curious is that, as a team at that time, we also discussed assertions, and most were against using them...  however, not checking for NULL is kinda sorta an implicit assertion, so we're not entirely consistent.

Me, I'm rather ambivalent on the issue.  Checking for NULL and returning with an error relies on the user checking for the error condition, *and we haven't been entirely dilligent in our own code*...  as a matter of fact, not checking for NULL has helped finding faults in our code much faster than anything else.  So yeah, pros and cons in both ends of the question.

**Comment by stevelinsell** [comment]
> This could be a way to address that particular concern:
> 
>     if (ossl_assert(arg != NULL))
>         return 0;
> As long as you build with debug on (which I do by default) then you will still get the immediate feedback.

Shouldn't that be:

```
if (!ossl_assert(arg != NULL))
    return 0;
```

Obviously I'm not a committer but for what it's worth as a user of the library I think it's an argument you'll never satisfy everyone with. People will always argue that as a library you shouldn't just assert and should fail gracefully and other people don't want errors that are hard to debug in users code. For me Matt's suggestion looks like a reasonable compromise. At least I could turn on debug to help root cause those kind of issues but the parameter is being checked and dealt with gracefully in a release build.

**Comment by vdukhovni** [comment]
> @stevelinsell Shouldn't that be: `if (!ossl_assert(arg != NULL))`

Yes.  And I also find this approach appealing. If passing null is an error on the caller's part, then this avoids crashing in the library, and yet gives callers the opportunity to test with a library that will assert in that case.

**Comment by mspncp** [comment]
I like the dual approach, too. However, the if condition  with the double negation is not very intuitive. I would suggest adding a new macro 

```C
#define ossl_is_null(arg) !oss_assert((arg) != NULL)
```
such that one can replace the above check by  

```C
if (ossl_is_null(arg))
    return 0;
```

**Comment by mspncp** [comment]
The following variant would even give a more precise error message:

```diff
diff --git a/include/internal/cryptlib.h b/include/internal/cryptlib.h
index a608735187..460e4be247 100644
--- a/include/internal/cryptlib.h
+++ b/include/internal/cryptlib.h
@@ -27,6 +27,7 @@

 #ifdef NDEBUG
 # define ossl_assert(x) ((x) != 0)
+# define ossl_is_null(x) ((x) == NULL)
 #else
 __owur static ossl_inline int ossl_assert_int(int expr, const char *exprstr,
                                               const char *file, int line)
@@ -39,7 +40,8 @@ __owur static ossl_inline int ossl_assert_int(int expr, const char *exprstr,

 # define ossl_assert(x) ossl_assert_int((x) != 0, "Assertion failed: "#x, \
                                          __FILE__, __LINE__)
-
+# define ossl_is_null(x) ossl_assert_int((x) != NULL, "Invalid NULL pointer: "#x, \
+                                         __FILE__, __LINE__)
 #endif

 typedef struct ex_callback_st EX_CALLBACK;
```

**Comment by mspncp** [comment]
I just noticed: Things are bit more tricky, because in the NDEBUG case an error should be pushed on the stack.

**Comment by mspncp** [comment]
BTW: shouldn't also `ossl_assert()` push an error in the NDEBUG case, instead of failing silently?

**Comment by t-j-h** [comment]
It isn't failing silently - it is returning an error code. That is the point. Not all error returns push to the error stack. Pushing to the error stack for this sort of thing would be over-the-counter habdling IMHO.

**Comment by t-j-h** [comment]
You can also go further and place the if and return into the macro and add an extra argument to be the return value as it does vary depending on the function. That would also provide a simple way to compile that code out completely if someone objects to having it. Then you get three choices. Personally I don't see the need for a debug assert approach as this isn't something I would want to see asserts used on - it should have to be explicitly enabled - as passing in null would be legitimate API usage and having asserts defeats some of the purpose of cleaner and clearer error handling as you would still have to handle API usage to avoid calling with null so that debug builds work too. That to me is the wrong approach. 

A set of compile time options to allow testing the behaviour doesn't hurt though - I just would not include it in a debug build.

**Comment by mspncp** [comment]
What do you think about #7218?

**Comment by richsalz** [comment]
I would like to see a build flag that let me disable NULL checks without turning on NDEBUG.

**Comment by mspncp** [comment]
The votes in this issue were _against_ removing NULL checks. Instead, they were _pro_ adding an abort in addition to the NULL check in the debug version.

**Comment by richsalz** [comment]
If you're going to convert all  NULL checks to a macro -- which is a good idea -- please make it easy to turn that into a no-op in production builds.

**Comment by t-j-h** [comment]
What I was suggesting was putting the if statement and return into the macro and allowing additional control at compile time.

So those who want a no-null-check-production build could have that and those that want a debug build without null-check asserts could also have that. 

I.e. four options
- compile in null checks in production (default)
- compile in null checks in debug (default)
- compile out null checks in production (extra flag to enable)
- compile in null checks asserts in debug (extra flag to enable)

That would allow all options discussed.

But for code usage inside the library only the first two would be checked - as we with have null checks and the corresponding safety and cleanup and use those or we don't in my view. It makes the other two compile options useful for others application code mostly.

**Comment by mspncp** [comment]
> four options

Isn't that a bit overengineered? Or asking differntly: does it mean that since we don't manage to get to an agreement, we leave the agony of choice to the user?  ;-)

**Comment by t-j-h** [comment]
Keeping everyone happy comes at a cost.
And having debug builds assert but default defeats the point of the NULL checks allowing for cleaner error handling.

I.e. no more if (x!=NULL) {X_free(x); x=NULL; } or the non-null setting version which can lead to free memory reference. Or the missed cleanups will gotos.

**Comment by mspncp** [comment]
> What I was suggesting was putting the if statement and return into the macro

this variant is less readable. Also, there are more usages than just

```C
    if (!ossl_assert(p != NULL))
        return 0;
```
I also saw

```C
    if (!ossl_assert(p != NULL))
        goto error;
```
and
```C
    if (!ossl_assert(p != NULL)) {
        /* do some error handling */
     }
```

**Comment by mspncp** [comment]
> I.e. no more if (x!=NULL) {X_free(x); x=NULL; } 

If passing a  NULL pointer is expected usage, then there it is not a location where an assertion would be used. If not, then one still could have an assertion in debug code combined with cleanup in release code:

```C
    if (ossl_is_null(x) {
        X_free(x);
        x=NULL;
    }
```

**Comment by t-j-h** [comment]
And the point of this change and the view on it is that **passing NULL is permitted and allowed** (we have it for some functions but not for all functions already). Once we make a decision on that it will be permitted API usage and some cleanup of error handling can be done.

That would mean no assert usage ever on the null checks - but there are some people that want to be able to check for that when working through error paths and trap it. I don't see the need for it myself - but I was noting there are actually four options - if we wanted to cover them all. 

You would need multiple macros to cover the range of input parameter checking handling as you note - and I would also tend to move the input parameter checking around to get it up front and cleaner - and then there would be less variation if that was done.

**Comment by levitte** [comment]
@t-j-h said thusly re `ossl_abort`:
> It isn't failing silently - it is returning an error code.

No.  It returns the inverted boolean result of the expression it's given.  That's not an error code.

**Comment by vdukhovni** [comment]
Let's not get carried away, we're just contemplating a convenience macro for existing functions that tolerate but error-out on a NULL argument. If this gets much fancier, we're doing too much...
Tim's four options are perhaps one or two too many, but at they do seem to cover all the bases.

**Comment by t-j-h** [comment]
I would be okay with just always compiled in checks. Adding assert options defeats the purpose given code must be tested with the checks in place and will take advantage of those checks otherwise they serve little point. 

But I did want everyone to see that there are actually four options not two and the assert-in-debug is the wrong approach.

**Comment by bernd-edlinger** [comment]
My preference would be to have full checks on **exported** interfaces,
and **if** the interface pushes error codes on some error conditions, these
null-parameter checks should also do so.
What I don't like is debug-code behave nice, and report an error, via
an assertion, and the release code have a run-away recursion.

**Comment by mspncp** [comment]
@t-j-h in my opinion Matts proposal boils down to a compromise between two opposing philosophies:

- Never check NULL pointers: It's better to crash immediately instead of relying on the user to handle the returned error properly.
- Always check NULL pointers and fail gracefully: Although there is a risk of undefined behaviour, it is better than being blamed for the users errors, just because we appear in the call stack of the crash dump.

The compromise is to crash in debug version (only), but handle the error gracefully in the release build. So it picks the best of both ways. And it is not like @bernd-edlinger fears that the error condition is unhandled in release builds.

**Comment by bernd-edlinger** [comment]
> And it is not like @bernd-edlinger fears that the error condition is unhandled in release builds.

I am referring to 6839a7a7f4973a3fc2f87b12664c26d524bef1f4
where an assertion stopped the recursion from happening in in debug builds.
So if we the debug build aborts in an assertion we have basically a completely
untested error handling after the assertion.

**Comment by mspncp** [comment]
> I am referring to 6839a7a

Ok, I see. But in that case the original version had only the assert() and not the regular error return. That's why the release version could crash with a stack overflow.

**Comment by mattcaswell** [comment]
OMC: Referring to this OTC

**Comment by t8m** [comment]
**OTC Decision: The NULL checks should be kept**
