### ISSUE TITLE
Strange path choice for engines-1.1/ on Windows

### ISSUE THREAD

**Issue by wrowe** [openssl/openssl#7185]
On Windows, binaries including shared dynamic object libraries live in bin/, while the lib/ directory
consists only of build-time artifacts, including non-executable link libraries.

In the Windows master build, lib/ includes;
engines-1_1   libssl.lib  libcrypto.lib

while bin/ includes
c_rehash.pl  libcrypto-1_1.dll  libssl-1_1.dll  openssl.exe  libcrypto-1_1.pdb  libssl-1_1.pdb  openssl.pdb

I would suggest Windows conventions suggest deploying to bin/engines-1_1/ and not lib/engines-1_1/
capi.dll  padlock.dll  capi.pdb  padlock.pdb

**Comment by levitte** [comment]
Well, errr, not quite.  The convention is to have shared libraries in the same spot as the programs that are linked with them, while there is no real convention for the location of dynamically loadable modules (which the engines are).

On *Unix*, it's not unusual to have dynamically loadable modules in a subdirectory of `lib`, and since all this `bin`, `lib` and so on business isn't really a Windows convention, but rather a direct copy of Unix layouts, I think it's appropriate to have engines in the same spot on both.
