### ISSUE TITLE
SSL_CB_HANDSHAKE_START/DONE in HelloRequest of TLS1.2

### ISSUE THREAD

**Issue by shigeki** [openssl/openssl#7199]
I'm now working upgrading to OpenSSL-1.1.1 from 1.1.0 in Node.js.

In 1.1.1, one of our tests of renegotiation with client auth in TLS1.2 was failed because `SSL_CB_HANDSHAKE_START` and `SSL_CB_HANDSHAKE_DONE` are called before/after sending HelloRequest in a tls server.

Here is my debug output with ssl-trace.
```
SSL_CB_HANDSHAKE_START in state_machine
Sent Record
Header:
  Version = TLS 1.2 (0x303)
  Content Type = Handshake (22)
  Length = 28
    HelloRequest, Length=0
      Unsupported, hex dump follows:

SSL_CB_HANDSHAKE_DONE in tls_finish_handshake
```
This is an issue for us because we make TLS connection established at the time when `SSL_CB_HANDSHAKE_DONE` is called in TLS1.2. 
Fortunately, we can have its workaround by checking`SSL_renegotiate_pending()` .

I would like to know if this is an intentional change in 1.1.1 or an issue to be fixed.

**Comment by mattcaswell** [comment]
Hmmm. I don't think this is intentional. There was some work done to try and get some kind of consistent info callbacks when TLSv1.3 is in use. Possibly this has had the unintended consequence of changing TLSv1.2 behaviour.

**Comment by shigeki** [comment]
This also affects for me to work on adopting TLS1.3 in Node.js for they are called in post-handshake.
As `bbio` is not cleared until all NewSessionTickets sent, we have to wait for `SSL_CB_HANDSHAKE_DONE ` in 1 + `SSL_get_num_tickets()` times to make a new TLS connection established and 2 times in resumption of TLSv1.3.

**Comment by mattcaswell** [comment]
In 1.1.1 the description of `SSL_CB_HANDSHAKE_START` and `SSL_CB_HANDSHAKE_DONE` was changed to read as follows:

````
=item SSL_CB_HANDSHAKE_START

Callback has been called because a new handshake is started. In TLSv1.3 this is
also used for the start of post-handshake message exchanges such as for the
exchange of session tickets, or for key updates. It also occurs when resuming a
handshake following a pause to handle early data.

=item SSL_CB_HANDSHAKE_DONE           0x20

Callback has been called because a handshake is finished. In TLSv1.3 this is
also used at the end of an exchange of post-handshake messages such as for
session tickets or key updates. It also occurs if the handshake is paused to
allow the exchange of early data.
````

So, we always enclose post-handshake messages in TLSv1.3 with START/DONE - that is intentional. 

In TLSv1.2 the only post-handshake messages we have are a ClientHello (which should initiate a new handshake that should also be enclosed in START/DONE) and HelloRequest where (apparently) we never used to do that. That leaves us with a bit of a dilemma. For consistency it really ought to be enclosed in START/DONE too - but that seems like a breaking change. Probably we need to make an exception for that case.

**Comment by mattcaswell** [comment]
> This also affects for me to work on adopting TLS1.3 in Node.js for they are called in post-handshake.
As bbio is not cleared until all NewSessionTickets sent, we have to wait for SSL_CB_HANDSHAKE_DONE in 1 + SSL_get_num_tickets() times to make a new TLS connection established and 2 times in resumption of TLSv1.3.

I'm not sure I understand the issue here.

**Comment by shigeki** [comment]
We have own bio for Node.js and have to wait for `wbio` to be cleared with `clearbufs:1` of `tls_finish_handshake()`  at `TLS_ST_OK`  in order to use `SSL_write()`.

We can not know if `SSL_CB_HANDSHAKE_DONE` is called either in `TLS_ST_OK` or `TLS_ST_SW_SESSION_TICKET` unless we count the number of tickets. 
It would be helpful for me if we can distinguish them.

**Comment by mattcaswell** [comment]
I've done a bit more investigation of this issue, and things are a bit more complicated than I thought.

The 1.1.0 behaviour on HelloRequest seems to be this:
Client side:
HANDSHAKE_START on receipt of HelloRequest
HANDSHAKE_DONE at the end of the following handshake

Server side:
HANDSHAKE_START on sending the HelloRequest
HANDSHAKE_START again on receipt of the ClientHello
HANDSHAKE_DONE at the end of the following handshake

In 1.1.1 the behaviour is this:
Client side:
HANDSHAKE_START on receipt of HelloRequest
HANDSHAKE_DONE at the end of the following handshake

Server side:
HANDSHAKE_START on sending the HelloRequest
HANDSHAKE_DONE at the end of sending the HelloRequest
HANDSHAKE_START again on receipt of the ClientHello
HANDSHAKE_DONE at the end of the following handshake

It makes sense to me that there would be two HANDSHAKE_STARTs on the server side since the sending of the HelloRequest and the subsequent receipt of the ClientHello are completely distinct transactions (which could have application data between them). On the client side it also makes sense that the whole thing (receipt of HelloRequest and subsequent handshake) is all enclosed between a single HANDSHAKE_START/HANDSHAKE_DONE.

What is interesting is that in 1.1.0 there are two HANDSHAKE_START events but only one HANDSHAKE_DONE. This does not look right to me - these should always be matched. Therefore this actually looks like a bug that was in 1.1.0 but has subsequently been fixed in 1.1.1.

**Comment by shigeki** [comment]
@mattcaswell Thanks for clarification. It means that we were lucky not to have this issue in 1.1.0. 
Are you going to fix this in 1.1.0?  We need to add `SSL_renegotiate_pending()` check if the fix is made before moving 1.1.1.

**Comment by mattcaswell** [comment]
1.1.0 has now moved to security fix only mode. Since this isn't a security issue it wouldn't qualify for receiving a fix. So I'm minded to leave this alone in 1.1.0.

**Comment by mattcaswell** [comment]
> We have own bio for Node.js and have to wait for wbio to be cleared with clearbufs:1 of tls_finish_handshake() at TLS_ST_OK in order to use SSL_write().

Detecting the end of the handshake via the info callback isn't really the way you are supposed to do things. That requires you to build in knowledge about the internal state machine into your application - which is fragile and liable to change (as you have discovered with the TLSv1.3 changes). New extensions etc, that might be introduced in the future could also change this. You're supposed to wait until `SSL_accept` or `SSL_connect` have returned 1. The info callback is more of a debug and tracing tool.

**Comment by sam-github** [comment]
@mattcaswell I have been looking into this, and I believe the reason we are using the info callback (and "transparent" handshake) is that we want to know when `SSL_renegotiate()` completes on both the initiating side and the receiving side. Waiting for `SSL_connnect()` and `SSL_accept()` won't help with this.

Can you suggest a more robust way to do this? Are there some callbacks I haven't found that will tell us this?

Reminder, this is node.js, so we are doing async I/O.

For now, this what I'm trying to do.

I found that I can skip SSL_CB_HANDSHAKE_START if `SSL_get_state() == TLS_ST_SW_SESSION_TICKET` and  SSL_CB_HANDSHAKE_DONE if `SSL_get_state() != TLS_ST_OK`. This works around many of the duplicate (from our point of view) callbacks.

This appears to work on the server (so far) for TLS 1.2 & 1.3.

On the client, though, its more complex.

For TLS1.3, I get a pair of SSL_CB_HANDSHAKE_START/_DONE for every NewSessionTicket with a state of `SSLOK`. But TLS1.3 doesn't support `SSL_renegotiate()`, so perhaps the _accept/_connect approach will work for it.

TLS1.2 does support renegotiation, but I don't get the multiple ticket callbacks there.

I'm considering trying a hybrid approach, where the intial handshake uses SSL_connect/_accept as you suggest, and then I use the info callbacks for TLS 1.2 to detect renegotiation, but it will take some effort to see if this catches all the corner cases.

I've also considered using SSL_set_msg_callback() to detect the type of record being processed, and filter info callbacks based on that... It looks like I could use it to ignore NewSessionTicket info callbacks, but that might be an even more fragile dependence on TLS internal state.

If you have any suggestions, I'd appreciate hearing them.

@shigeki I'm working on this now, just a dozen tests left that fail with TLS1.3 and this might be the last big issue, so if you came to any conclusions about the best approach for Node.js, I'd appreciate any of your suggestions, too.

**Comment by mattcaswell** [comment]
>  But TLS1.3 doesn't support SSL_renegotiate(), so perhaps the _accept/_connect approach will work for it.

If the purpose is to detect renegs then surely you don't have to do anything in TLSv1.3 since they will never happen?

> I'm considering trying a hybrid approach, where the intial handshake uses SSL_connect/_accept as you suggest, and then I use the info callbacks for TLS 1.2 to detect renegotiation, but it will take some effort to see if this catches all the corner cases.

That sounds reasonable to me.

**Comment by sam-github** [comment]
> If the purpose is to detect renegs then surely you don't have to do anything in TLSv1.3 since they will never happen?

Not for SSL_renegotiation(), but its is partially replaced by two new APIs, SSL_key_update() and SSL_verify_client_post_handshake(), and I have not done POC code for them yet.

Key update should trigger callbacks for new tickets in the same way that the new tickets sent have the initial connection do, that should not require info callbacks.

For SSL_verify_client_post_handshake() I am somewhat concerned that we'll need to detect the reception of the certificate, and that I will not find an SSL callback for that specific event, so that even for TLS1.3 we'll need to be watching the info callback to detect when the requested cert has arrived.

**Comment by davidben** [comment]
TLS 1.3 key update does not cause new tickets to be sent. It's just a symmetric key ratchet and doesn't affect the resumption secret or logical state of the connection. (However, tickets may be sent at arbitrary points after the handshake so the callback may be called whenever.)
