### ISSUE TITLE
ssltest doesn't work for OpenSSL 1.1.1 

### ISSUE THREAD

**Issue by looklook888** [openssl/openssl#7202]
We used to use ssltest to verify a cert and a key are compatible. With the new OpenSSL 1.1.1, it doesn't work any more. The command we use is:
ssltest -cert a.crt -key b.key  -bio_pair

Is ssltest replaced by something else? Or it is broken? Thanks.

**Comment by mattcaswell** [comment]
`ssltest` is an internal test application that is used in 1.0.2. Since this is internal its usage and even whether it appears in the distribution could change at any time. There are no stability guarantees regarding the presence or otherwise or the usage of test applications. You shouldn't be using it.

That said, it does still exist in the distribution - just under a different name. It is now called `ssltest_old`. Its parameters have also changed. What used to be called `cert` is now called `s_cert` and what used to be called `key` is now called `s_key`.
