### ISSUE TITLE
Extended Master Secret is sent unconditionally

### ISSUE THREAD

**Issue by indutny** [openssl/openssl#7246]
When a client establishes a connection using an existing session that doesn't support "extended master secret", the "extended master secret" extension is added to the ClientHello and sent to the server. Upon receiving this, the server discards session and generates a new one.

I believe that it would be best for client to not advertise an extension in such case.

Kindly requesting a feedback on this issue before I'll implement the proposed fix myself.

Thank you!

**Comment by davidben** [comment]
I believe this is the correct behavior. This is what Chrome does as well.

While, yes, during the immediate transition the client will miss one resumption, the new session will negotiate EMS and resumption will return. It's the same as, say, enabling TLS 1.3. The first connection on the transition will miss resumption (since TLS 1.2 sessions cannot be used at TLS 1.3), but subsequent connections will have 1.3 sessions available.

**Comment by indutny** [comment]
While I wouldn't argue about usefulness/security of such transitions. Having a way to disable automatic-EMS would certainly help my use case.

**Comment by davidben** [comment]
What is the use case?

Changing client advertisements based on session state is generally a bad idea. It usually causes "stickiness" problems. Indeed you yourself ran into and fixed such a problem in issue #852. :-)

**Comment by kaduk** [comment]
> Having a way to disable automatic-EMS

Does this differ from #3910?

**Comment by davidben** [comment]
This was asking for the *client* to disable EMS *based on a previous session*, which seems highly problematic. Though yeah I suppose it could be done with a combination of `SSL_OP_NO_EXTENDED_MASTER_SECRET` and querying the `SSL_SESSION`.

**Comment by indutny** [comment]
I think #3910 would suffice for my use case. I wasn't sure whether the current behavior was intentional, or accidental. Thanks!

**Comment by dwmw2** [comment]
RFC7627 says:
```
   o  If the original session did not use the "extended_master_secret"
      extension but the new ClientHello contains the extension, then the
      server MUST NOT perform the abbreviated handshake.  Instead, it
      SHOULD continue with a full handshake (as described in
      Section 5.2) to negotiate a new session.
```
If OpenSSL unconditionally sends this option even when resuming a session which didn't use it in the first place, then resumption of such a session MUST NOT succeed. That seems suboptimal.

In my case it is particularly suboptimal because the Cisco AnyConnect VPN DTLS support works by "resuming" a session that never really previously existed, using a master secret and session ID which are generated and exchanged through other means.

There is no "full handshake" option for when OpenSSL includes the extended_master_secret extension and the server MUST NOT resume the session. There is only a connection failure.

**Comment by tmshort** [comment]
>In my case it is particularly suboptimal because the Cisco AnyConnect VPN DTLS support works by "resuming" a session that never really previously existed, using a master secret and session ID which are generated and exchanged through other means.

Yup, I wrote the server-side ASA code, and resumption is used not just to speed up the DTLS connection establishment, but to link the DTLS connection with the initial TLS login connection.

**Comment by davidben** [comment]
Session resumption is typically treated as a cache. It is actually a rather critical part of its semantics that it is always declinable for any reason. OpenSSL's entire TLS 1.3 strategy depended on this fact, otherwise post-handshake tickets would have mean 1.3 was unimplementable with OpenSSL's API. That text was also written with this assumption in mind.

If your protocol is doing a non-standard thing with sessions where they are undeclinable, I'm afraid weird behaviors are just going to have to be expected.

**Comment by tmshort** [comment]
In the case of AnyConnect, the DTLS connection **must** be resumed, a full handshake will never occur, as the session ID is required to tie the DTLS connection to the TLS connection. 

The RFC7627 quote above seems to indicate that if a prior session did not have EMS, but the client hello includes one, then a full handshake must occur. But then, what's the point of attempting to resume in this case? The client must match the EMS extension to the session, otherwise a full handshake occurs. It is detrimental for the client to not have these match; why would the client send a session ID if it knows it's going to get a full handshake in return, because it erroneously included the EMS extension?

**Comment by tmshort** [comment]
While I completely understand the reasoning you state @davidben (I was commenting on the client behavior being disruptive to itself, which is self-detremental, regardless of increased security), in @dwmw2's use case, his client must not chance breaking resumption, so he must not include the option to not have EMS present. This leads to an option as presented in PR #3910.

**Comment by davidben** [comment]
I don't follow why the client is disruptive to itself. As I said, there *is* a point to offering the EMS + non-EMS session, contrary to what you wrote in https://github.com/openssl/openssl/issues/7246#issuecomment-452356915. A client does that if it intends to stay compatible with non-EMS servers. The resumption rate is the same as before, but for one miss (over the lifetime of client and server) to switch from new to old parameters. This is how it works for every other TLS change. Adding TLS 1.3 did *exactly* this.

But, yes, like I said, PR #3910 is fine, though @dwmw2's use of session resumption is incompatible with common practice. It's https://github.com/openssl/openssl/pull/3910#issuecomment-452350120 that's not okay.

**Comment by tmshort** [comment]
It's disruptive in that it's attempting to do a resumption, but may not due to the server behavior of handling the EMS extension. Optimally, from the client's _greedy performance_ point of view, always resuming is better than having to do a second (or more) full handshake. That one miss is detrimental to the client. (Sorry, too much Ayn Rand...)

**Comment by tmshort** [comment]
@davidben, I think we're in violent agreement that an option to disable the normally-on EMS extension is appropriate.

**Comment by davidben** [comment]
Yup. Well, I don't care a whole lot for flag as a whole, but I agree that it is a plausible patch for this (questionably valid) scenario. :-P

(Fair enough. Although presumably any client using TLS includes security as part of its fitness function *somewhere*—the one I work on certainly does!—in which case, losing globally one resumption so that protocol improvements get deployed at all seems a pretty great deal no matter how you slice it. Especially consider that servers already may evict session cache entries or rotate keys, so resumption was already not guaranteed.)

**Comment by kaduk** [comment]
#3910 was committed (some time ago!), and if I am reading correctly, everyone agrees that the option it provides suffices to get the desired behavior for the scenarios under discussion.
So, closing, but I'm happy to reopen if I missed something.
