### ISSUE TITLE
blake2 missing from openssl speed output

### ISSUE THREAD

**Issue by fgsch** [openssl/openssl#7278]
SSIA

**Comment by InfoHunter** [comment]
As @tomato42 indicated, this can be done by using `-evp` option. Closing the issue...

**Comment by fgsch** [comment]
While it's possible to get this information using -evp as @tomato42 pointed out, it does not change the fact that the output is not available via `openssl speed`.

What's the criteria here to include (or not) a given algorithm?

**Comment by richsalz** [comment]
IT's just a matter of resources and priorities; there is no policy to keep anything "out"

**Comment by fgsch** [comment]
ok, in that case can you reopen it? I will try to submit a PR (that was my original intention with this issue).

**Comment by mspncp** [comment]
Sure... but can‘t you as the creator of this issue reopen it?

**Comment by fgsch** [comment]
@mspncp I didn't have the option, no.

**Comment by mspncp** [comment]
Well then, go ahead. Pull requests are always welcome...  :-)

**Comment by InfoHunter** [comment]
> it does not change the fact that the output is not available via openssl speed.

I don't quite understand this. Do you mean the 'raw' algorithm should be supported by `openssl speed` outside the `evp` interface?

**Comment by paulidale** [comment]
My understanding is that the -evp option is to be used for new algorithms in speed rather than including them directly.

**Comment by t-j-h** [comment]
And we are likely to split speed into two parts - internal testing in a separate program - and performance measurement via the interface for users (i.e. evp). Previous discussions on this have occurred.

**Comment by InfoHunter** [comment]
> And we are likely to split speed into two parts

I would say I agree with this, so if the 'external tool' is still called `openssl speed`, then no need to add 'raw' algorithm since it's already supported by `-evp` interface.

**Comment by mspncp** [comment]
Sorry, I was not aware that there has been a discussion previously and a clear policy against adding non-evp benchmarks. I did not have the intention to oppose against the consensus and restart unnecessary discussions.

I reopened the issue as an act of politeness to fulfil a request of @blake2 who expressed the desire for further discussion. (GitHub does not give the original reporter the opportunity to reopen an issue. This is rather ridiculous, because it forces people to open duplicates, see e.g. [this thread](https://github.com/isaacs/github/issues/583)).

Of course it does not make sense to encourage people to submit futile pull requests which won't be accepted anyway. So it was premature to do it, but I didn't know it better and I didn't mean to offend anybody, in particular not Paul. Maybe I also interpreted Rich's comment in the wrong direction. Sorry for the intervention.

**Comment by mspncp** [comment]
Ups, I meant to write @fgsch , not @blake2!

**Comment by InfoHunter** [comment]
@mspncp , no worries, it's not offending at all ;-)

Actually if the split happens to `apps/speed.c`, I think we still need the implementation of raw blake2. So I guess a PR containing the raw blake2 implementation in a new 'internal' tool, would be very appreciated in this context - which could be a good start of splitting the original `apps/speed`...

Any thought? @fgsch

**Comment by fgsch** [comment]
@InfoHunter I'm happy to do the work but I'm not entirely sure what the desired outcome is.
If anyone minds clarifying it I'll take it and open the PR.

**Comment by romen** [comment]
I guess that to act on what's going to happen to speed, we have to understand what is the next target for the library. Is the next one going to be a major release that can break backwards compatibility (in this case on usage of the speed app) or for the time being master should not include breaking changes of any sort?

**Comment by InfoHunter** [comment]
From my understandings, the next release is going to be a major one so we can break backwards compatibility. But still needs confirmation from @openssl/omc 

If so, it *might* be feasible to create a new *internal only* benchmark tool first, which contains the raw callings to the algorithms (Note: some algorithms can only be called by including some internal header files, so this is the reason why this *raw* tool can only be *internal*). This tool is more like a *testing* utility like other test case from my opinion. When you are doing this, you can reference the current `speed` code as a 'counter example' - which means not to just copy the `raw` part of `speed` - the new internal tool should be more careful when organizing the code...

Then the second step of this would be to remove all `raw` related code in `apps/speed` and make it pure `evp` based. But there is still more work to do with the `evp` part since not all algorithms can be used with `apps/speed` via evp - for instance EdDSA ;-). So refactoring of `apps/speed` is necessary (to support all algorithms via evp...)

Makes sense, @fgsch ? @romen Hope this matches what we have discussed earlier.

**Comment by romen** [comment]
Well yes, @InfoHunter , starting to create the internal testing speed (`test_speed`?) is definitely within the scope of any decision the OMC takes on the next release, as it does not break anything per se.

I don't know, though, if we want the new `test_speed` to have an architecture/style similar to current `speed` (which is quite messy, obscure and spaghetti-code) or to write it from scratch with a more consistent and maintainable code base.

Some things worth discussing in case of a start from scratch:
- do we want to keep the current "number of operations completed in a fixed time window" metric, or do we want to switch to a "elapsed time for a fixed amount of operations" metric? *(the latter, in my experience, provides better support for comparisons between profiling data)*
- how to unify access to internal functions for cryptosystems in the same "class" of operations to make sure that such measurements are compatible?
- should we have an abstract concept of *operation* supporting a way to categorize/group similar ops, providing an unified interface with hooks to `setup` (do all the sanity checks to make sure cmdline options for a given operation make sense), `init` (once all options have been parsed and general stuff setup, actually proceed to initialize the operation, allocate required memory, precompute inputs, etc.), `run` (minimal footprint overhead encapsulating only what is going to be actually benchmarked), `post_run` (if there is anything that needs to be freed/cleared after each `run`), `cleanup` (clean anything that was allocated in the `init` step)? *(this would help maximizing reuse of similar code for different but related operations across cryptosystems and also making sure that the critical code in the `run` hook is actually comparable across related operations)*
- other desirables that I am sure I am forgetting right now!

**Comment by fgsch** [comment]
@InfoHunter Thanks, that makes sense. I will start working on it as soon as I have some time.

**Comment by fgsch** [comment]
I haven't had time in the last 2+ years and I'm not sure when I'd have time to work on this so closing for now.
