### ISSUE TITLE
Why does GENERAL_NAME_print insert a newline character only for IPv6 records?

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#7284]
https://github.com/openssl/openssl/blob/32f803d88ec3df7f95dfbf840c271f7438ce3357/crypto/x509v3/v3_alt.c#L180-L186

This seems rather strange and caused a weird bug for us because we assumed it wouldn't insert newline characters. It's also odd because it inserts it directly at the end, after everything has been printed. I see other uses of the function where such newline printing would cause double newlines, for example here:

https://github.com/openssl/openssl/blob/32f803d88ec3df7f95dfbf840c271f7438ce3357/crypto/x509v3/v3_crld.c#L412-L416

**Comment by RameshwarapuSanthosh** [comment]
Hello mlindner,

The code base on which the issue was raised seems to be quite old. The new line inserts[BIO_puts(out, "\n"); ] seen in the code snippets shared were not present in latest[which possibly could be the printing new lines]. When tested the latest source on X86, couldn't reproduce the issue. Can you please cross-check and close the issue? 

Thanks,
Santhosh Kumar R,
Intel India

**Comment by mlindner** [comment]
Yes this seems to only be relevant for older versions. Closing.

**Comment by mlindner** [comment]
Fixed by https://github.com/openssl/openssl/pull/6226
