### ISSUE TITLE
ec_asn1.c#i2o_ECPublicKey

### ISSUE THREAD

**Issue by Yifei0727** [openssl/openssl#7330]
Hi  , when I recode a EVP_PKEY object (real is EC_KEY)
the `pkey` bellow is an EVP_PKEY 
```c
 int pkLen = 0;
 unsigned char * pkOcts = NULL; 
 pkLen = i2d_PublicKey(pkey, NULL);
  if (NULL == (pkOcts = malloc(pkLen))) {
    //ERROR;
  } 
  memset(pkOcts, 0, pkLen);
 
  if (pkLen != i2d_PublicKey(pkey, &pkOcts)) {
    fprintf(stderr, "%s\n", "ASN.1 PK transform error");
     // ERR
  }
  if (pkOcts[0] != 0x04) {
    fprintf(stderr, "%s\n", "PK MUST BE 04");
     // ERR
  }
  free(pkOcts); // cause MEMORY ERROR
```
then I trace my code & openssl code
I found that `ec_asn1.c#i2o_ECPublicKey` function
do something I could't understand (the code exists over 15 years)
see line 1136 lastest version
```c
1135     if (!new_buffer)
1136         *out += buf_len;
1137     return buf_len;
```
This cause my var `pkOcts` 'pointer offset incorrect. and  cause MEMORY ERROR when `free`
Please Help Me and Tell me:
> What is the intention to modify the pointer? Is there any special effect?

Thanks A Lot!

**Comment by mattcaswell** [comment]
This is documented behaviour. See:

https://www.openssl.org/docs/man1.1.1/man3/d2i_X509.html

Specifically:
"i2d_TYPE() encodes the structure pointed to by a into DER format. If ppout is not NULL, it writes the DER encoded data to the buffer at *ppout, and increments it to point after the data just written. If the return value is negative an error occurred, otherwise it returns the length of the encoded data."

> What is the intention to modify the pointer? Is there any special effect?

This catches a lot of people out, and probably if we were to design the API today we wouldn't do it like that. Unfortunately its been that way for a long time and we can't change it for backwards compatibility reasons. The reason behind it is probably lost in the mists of time - but my guess is so that you can read multiple DER objects out of the same buffer one after the other.
