### ISSUE TITLE
Fail to build for android NDK r16b

### ISSUE THREAD

**Issue by karma-sun** [openssl/openssl#7372]
I use android NDK r16b to cross-compile in linux,follow the NOTES.ANDROID to build and got errors below when make:

/usr/local/andk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -ldl
apps/ca.o:ca.c:function ca_main: error: undefined reference to 'stdin'
apps/ca.o:ca.c:function do_body.isra.3: error: undefined reference to 'stdin'
apps/dgst.o:dgst.c:function dgst_main: error: undefined reference to 'stdin'
apps/engine.o:engine.c:function engine_main: error: undefined reference to 'stdout'
apps/openssl.o:openssl.c:function main: error: undefined reference to 'stdin'
apps/openssl.o:openssl.c:function main: error: undefined reference to 'stdout'
apps/req.o:req.c:function req_main: error: undefined reference to 'stdout'
apps/s_time.o:s_time.c:function s_time_main: error: undefined reference to 'stdout'
./libcrypto.a(c_zlib.o):c_zlib.c:function zlib_stateful_expand_block: error: undefined reference to 'inflate'
./libcrypto.a(c_zlib.o):c_zlib.c:function zlib_stateful_compress_block: error: undefined reference to 'deflate'
./libcrypto.a(c_zlib.o):c_zlib.c:function zlib_stateful_finish: error: undefined reference to 'inflateEnd'
./libcrypto.a(c_zlib.o):c_zlib.c:function zlib_stateful_finish: error: undefined reference to 'deflateEnd'
./libcrypto.a(c_zlib.o):c_zlib.c:function zlib_stateful_init: error: undefined reference to 'inflateInit_'
./libcrypto.a(c_zlib.o):c_zlib.c:function zlib_stateful_init: error: undefined reference to 'deflateInit_'
./libcrypto.a(c_zlib.o):c_zlib.c:function bio_zlib_free: error: undefined reference to 'inflateEnd'
./libcrypto.a(c_zlib.o):c_zlib.c:function bio_zlib_free: error: undefined reference to 'deflateEnd'
./libcrypto.a(c_zlib.o):c_zlib.c:function bio_zlib_ctrl: error: undefined reference to 'deflate'
./libcrypto.a(c_zlib.o):c_zlib.c:function bio_zlib_ctrl: error: undefined reference to 'zError'
./libcrypto.a(c_zlib.o):c_zlib.c:function bio_zlib_write: error: undefined reference to 'deflate'
./libcrypto.a(c_zlib.o):c_zlib.c:function bio_zlib_write: error: undefined reference to 'zError'
./libcrypto.a(c_zlib.o):c_zlib.c:function bio_zlib_write: error: undefined reference to 'deflateInit_'
./libcrypto.a(c_zlib.o):c_zlib.c:function bio_zlib_read: error: undefined reference to 'inflate'
./libcrypto.a(c_zlib.o):c_zlib.c:function bio_zlib_read: error: undefined reference to 'zError'
./libcrypto.a(c_zlib.o):c_zlib.c:function bio_zlib_read: error: undefined reference to 'inflateInit_'
collect2: error: ld returned 1 exit status
make[1]: *** [apps/openssl] Error 1
make[1]: Leaving directory `/usr/local/anative/src/openssl-1.1.1'

**Comment by dot-asm** [comment]
One can find impossible flag combination for any given platform. And when one does, it doesn't actually mean that it's OpenSSL problem. Especially when one starts passing contradicting options. I mean what's up for example with -fPIC no-shared? Well, it's not actually so that they are problem here, -static is. And it is mentioned in NOTES.ANDROID. That one needs to modify Makefile, and that it takes an API version that is known to come with usable static libraries. In the essence it means that no guarantee can be left that -static actually works. In fact it applies to -static in general, it's viewed as debugging non-production option. To summarize, don't use -static. As for other options, give closer consideration...
