### ISSUE TITLE
Configure  android-arm does not find clang

### ISSUE THREAD

**Issue by juha-h** [openssl/openssl#7398]
I'm trying to build openssl 1.1.1 for android-arm on Linux using clang, but Configure fails like this:
```
cd openssl && \
	CC=clang RANLIB=/usr/src/baresip-android.r18/toolchain/bin/arm-linux-androideabi-ranlib AR=/usr/src/baresip-android.r18/toolchain/bin/arm-linux-androideabi-ar \
	ANDROID_NDK=/usr/local/android-ndk-r18 \
	PATH=/usr/src/baresip-android.r18/toolchain/bin:/usr/bin \
	./Configure android-arm no-shared -D__ANDROID_API__=21 -I/usr/local/android-ndk-r18/sysroot/usr/include -I/usr/local/android-ndk-r18/sysroot/usr/include/arm-linux-androideabi && \
	make build_libs
Configuring OpenSSL version 1.1.1 (0x1010100fL) for android-arm
Using os-specific seed configuration
no NDK clang on $PATH at (eval 7) line 87.
Makefile:180: recipe for target 'openssl' failed
```
PATH directory /usr/src/baresip-android.r18/toolchain/bin does include clang:
```
$ ls -ls /usr/src/baresip-android.r18/toolchain/bin/clang
4 -rwxr-xr-x 1 jh jh 223 Oct 14 08:14 /usr/src/baresip-android.r18/toolchain/bin/clang*
```
Why is clang no found?

**Comment by levitte** [comment]
The way you wrote that line, only `./Configure` can see your setting of PATH.  `make` won't see it, so you need to write your line a bit differently.

```
( PATH=/usr/src/baresip-android.r18/toolchain/bin:/usr/bin
  cd openssl && \
	CC=clang RANLIB=/usr/src/baresip-android.r18/toolchain/bin/arm-linux-androideabi-ranlib AR=/usr/src/baresip-android.r18/toolchain/bin/arm-linux-androideabi-ar \
	ANDROID_NDK=/usr/local/android-ndk-r18 \
	./Configure android-arm no-shared -D__ANDROID_API__=21 -I/usr/local/android-ndk-r18/sysroot/usr/include -I/usr/local/android-ndk-r18/sysroot/usr/include/arm-linux-androideabi && \
	make build_libs )
```

**Comment by dot-asm** [comment]
> a bit differently.

Well, Configure insists on observing $ANDROID_NDK value in `which clang` output. Even though one can make a case that any clang should fly, the question would still be if it's sensible to support *arbitrary* combination. And the answer is "not really", it's only appropriate to rely on **single** bundle from 3rd party, than allow free mix-n-match among multiple ones. Note that it's possible to "cheat" by showing clang with $ANDROID_NDK to Configure and then arranging things so that make would call different clang. But we don't have to support it.

Oh! ANDROID_NDK environment variable should be treated the same way as PATH. Is sense that it should be available to both Configure and make.

**Comment by levitte** [comment]
That might be worth a few lines in `NOTES.ANDROID`, i.e. actually spell out that the setting of those two environment variables is important both for Configure and for make.

**Comment by juha-h** [comment]
Richard Levitte writes:

> The way you wrote that line, only `./Configure` can see your setting
> of PATH.  `make` won't see it, so you need to write your line a bit
> differently.

Thanks Richard for your reply.  I think that the failure to find clang
happens already during Configure.  I made the test simpler by omitting
make so that there is only ./Configure left and I still get the error:
```
$ make openssl
cd openssl && \
	CC=clang RANLIB=/usr/src/baresip-android.r18/toolchain/bin/arm-linux-androideabi-ranlib AR=/usr/src/baresip-android.r18/toolchain/bin/arm-linux-androideabi-ar \
	ANDROID_NDK=/usr/local/android-ndk-r18 \
	PATH=/usr/src/baresip-android.r18/toolchain/bin:/usr/bin \
	./Configure android-arm no-shared -D__ANDROID_API__=21 -I/usr/local/android-ndk-r18/sysroot/usr/include -I/usr/local/android-ndk-r18/sysroot/usr/include/arm-linux-androideabi
Configuring OpenSSL version 1.1.1 (0x1010100fL) for android-arm
Using os-specific seed configuration
no NDK clang on $PATH at (eval 7) line 87.
Makefile:180: recipe for target 'openssl' failed
```
./Configure does see PATH, since if I omit /usr/bin from it, ./Configure
complains about perl missing.

**Comment by juha-h** [comment]
Thanks for the clarifications.  I'll try to make the build work.

**Comment by dot-asm** [comment]
> In android-ndk-r18 there is no clang in $ANDROID_NDK/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin.

Who said that clang is supposed to be there? NOTES.ANDROID says "adjust PATH to cover NDK's clang".

> Why [this-or-that]

As already said, because it's deemed unreliable to freely mix-n-match clangs and NDK. I mean rationale is "here is NDK, there is clang, we support *that* [and disclaim support for anything else]."

> https://developer.android.com/ndk/guides/standalone_toolchain

You have to recognize following. None of us is Android expert and development is driven by requests and feedback. We have been approached by Android users, did what we did and got thumbs up for what we did. Nobody brought up standalone toolchain. And as result it's obviously not supported. One can surely add support for it, but as far as I can see it won't look anything like for current "all-inclusive" NDK. At least standalone toolchain appears to be bound to chosen API, so that -D__ANDROID_API__=N looses all meaning, and it would be even inappropriate to suggest it as option. To summarize, for the moment of this writing answer to all question is stick with "all-inclusive" NDK, forget about standalone for now.

**Comment by juha-h** [comment]
I'm not an Android expert either. android-ndk-r18b has gcc here:
```
 ./toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
```
but that bin dir does not have clang.  There is clang here:
```
./toolchains/llvm/prebuilt/linux-x86_64/bin/clang
```
I'll try with that.

**Comment by juha-h** [comment]
Just to conclude this issue, I was able to build openssl static libs using android-ndk-r18b as shown below.  Thanks for your help.
```
cd openssl && \
	CC=clang RANLIB=/usr/local/android-ndk-r18b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ranlib AR=/usr/local/android-ndk-r18b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar \
	ANDROID_NDK=/usr/local/android-ndk-r18b \
	PATH=/usr/local/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin:/usr/local/android-ndk-r18b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin:/usr/bin:/bin \
	./Configure android-arm no-shared -D__ANDROID_API__=21 -I/usr/local/android-ndk-r18b/sysroot/usr/include -I/usr/local/android-ndk-r18b/sysroot/usr/include/arm-linux-androideabi && \
	CC=clang RANLIB=/usr/local/android-ndk-r18b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ranlib AR=/usr/local/android-ndk-r18b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar \
	ANDROID_NDK=/usr/local/android-ndk-r18b \
	PATH=/usr/local/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin:/usr/local/android-ndk-r18b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin:/usr/bin:/bin \
	make build_libs
Configuring OpenSSL version 1.1.1 (0x1010100fL) for android-arm
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

**********************************************************************
***                                                                ***
***   If you want to report a building issue, please include the   ***
***   output from this command:                                    ***
***                                                                ***
***     perl configdata.pm --dump                                  ***
***                                                                ***
**********************************************************************
make[1]: Entering directory '/usr/src/baresip-android.r18/openssl-1.1.1'
...
```

**Comment by petrovr** [comment]
juha-h wrote:
> After some studies, I'm returning to this issue. In android-ndk-r18 there is no clang in $ANDROID_NDK/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin.

It is in ..../toolchains/llvm/prebuilt/linux-x86_64/bin/clang , i.e. 
"llvm" instead of "<host-triplet>-<gcc-version>". Try to use this path.
This case definitely is supported by OpenSSL build scripts.

>   Page
> ```
> https://developer.android.com/ndk/guides/standalone_toolchain
> ```
> tells how to build a toolchain that includes clang and how to use the toolchain to build a project.
OpenSSL build script search for clang in path that match */prebuilt/* . 
Standalone may not have binaries in "expected" location.
[SNIP]

Perhaps absolute path to clang is work-around in case of "standalone" 
toolchain.


Regards,
Roumen Petrov

**Comment by dot-asm** [comment]
Support for standalone toolchain is added in #7400.

**Comment by juha-h** [comment]
Andy Polyakov writes:

> Support for standalone toolchain is added in #7400.

Great news.  I'll give it a try.

**Comment by juha-h** [comment]
Andy Polyakov writes:

> Support for standalone toolchain is added in #7400.

It worked fine and was much easier to use than without toolchain. Below
find extracts from my Makefile as an example.
```
PATH	  := $(TOOLCHAIN)/bin:/usr/bin:/bin

toolchain:
	rm -rf $(TOOLCHAIN) && \
	$(NDK_PATH)/build/tools/make_standalone_toolchain.py --arch arm \
		--api $(API_LEVEL) --install-dir $(TOOLCHAIN)

openssl:
	cd openssl && \
		CC=clang ANDROID_NDK=$(TOOLCHAIN) PATH=$(PATH) \
		./Configure android-arm no-shared && \
		CC=clang ANDROID_NDK=$(TOOLCHAIN) PATH=$(PATH) \
		make build_libs
```
