### ISSUE TITLE
No extended master secret for TLS 1.3?

### ISSUE THREAD

**Issue by zeno-endemann-kdab** [openssl/openssl#7421]
When running the example s_server (openssl 1.1.1) and then connecting via s_client it says "Extended master secret: no" on the TLS 1.3 connection. When forcing s_client to use TLS 1.2 it does use extended master secret however.
Is that right? Why is it not using it for TLS 1.3? Or is it not needed anymore for TLS 1.3, in which case I guess it would be better if the s_client output would say "not needed" instead of "no".

**Comment by mattcaswell** [comment]
Extended Master Secret is not relevant to TLSv1.3

**Comment by zeno-endemann-kdab** [comment]
Ok, thanks. It appears that the output of s_client is different for 1.3 connections anyway, I'd suggest just removing that line there.

**Comment by kaduk** [comment]
Note also the last paragraph of https://tools.ietf.org/html/rfc8446#appendix-D:

```
   TLS 1.2 and prior supported an "Extended Master Secret" [RFC7627]
   extension which digested large parts of the handshake transcript into
   the master secret.  Because TLS 1.3 always hashes in the transcript
   up to the server Finished, implementations which support both TLS 1.3
   and earlier versions SHOULD indicate the use of the Extended Master
   Secret extension in their APIs whenever TLS 1.3 is used.
```

**Comment by davidben** [comment]
BoringSSL reports both EMS and RI as always enabled in TLS 1.3. This is the backwards-compatible change because these are both "bugfix" extensions to TLS. A caller querying EMS vs RI support isn't asking whether some particular extension was physically negotiated on the wire. It is asking whether the relevant bugs have been patched, as a precondition for doing, say, some kind of channel-binding.

**Comment by kaduk** [comment]
@zeno-endemann-kdab my apologies; my remark was directed to Matt and not to you.  (And David's explanation is spot-on.)
