### ISSUE TITLE
Sign/Encrypt fails with openssl (cms) if certfile contains duplicate entry

### ISSUE THREAD

**Issue by chirag7888** [openssl/openssl#7457]
I am using openssl to encrypt file and I am getting malloc error as shown below.

```
openssl version
OpenSSL 1.0.2j-fips  26 Sep 2016

openssl command
openssl cms -sign -in infile -signer file.crt.pem -inkey file.key.pem -CAfile CAfile -out outfile -keyopt rsa_padding_mode:pss -certfile by_hash/81908841

Errors
1435735688:error:2E0A40AF:CMS routines:CMS_add0_cert:certificate already present:cms_lib.c:462:
1435735688:error:2E094041:CMS routines:CMS_sign:malloc failure:cms_smime.c:461:

```
Please note that in the command last option (-certfile by_hash/81908841) certfile has duplicate entry of certificate with same fingerprint and because of that signing is failing with CMS but somehow it works properly with SMIME.

Thanks in advance.

**Comment by mspncp** [comment]
_(@chirag7888  I reposted a part of comment https://github.com/openssl/openssl/issues/7418#issuecomment-431743310 here, because it was probably intended for this issue)_ 

Reproducible steps:
1. Get all correct/proper files mentioned in the subject/body
2. Run the command mentioned in body (Which should be passed/should be signed properly)
3. Edit certfile (last option file), duplicate the certificate and put it in same file.
4. Run step #2, which should throw errors mentioned in body, (Note: With S/Mime this is working, but with CMS its throwing error)

**Comment by mspncp** [comment]
I'm not sure whether this is really an OpenSSL error or just a usage error.

**Comment by chirag7888** [comment]
@mspncp What do you mean by usage error?
Is my command incorrect?

**Comment by chirag7888** [comment]
Ok, Thanks for your valuable time.

**Comment by t8m** [comment]
1.0.2 is unsupported version. Please open a new issue if you can reproduce the problem with 1.1.1 or 3.0 versions.
