### ISSUE TITLE
ECPrivateKey: Leading zeros should not be trimmed (PKCS#8 violation)

### ISSUE THREAD

**Issue by flurbi** [openssl/openssl#7461]
According to RFC 5915, 3. Elliptic Curve Private Key Format: The private key is an octet string of length ceiling (log2(n)/8) (where n is the order of the curve).

The order of the curve sect571r1 has 570 bits (thus 72 bytes). However, the following commando generates a variable length octet string (relatively often 71 bytes instead of 72):
openssl ecparam -name sect571r1 -genkey -noout

The following commando propagates the inaccuracy:
openssl pkcs8 -topk8 -nocrypt

Affected version: 1.0.2o

**Comment by richsalz** [comment]
Are you sure this is a bug, and not a case of leading zero's being omitted (per the DER encoding)?

**Comment by MartinBonner** [comment]
It is a bug.  It is an octet string, not a big (unsigned) integer.

The RFC is at https://tools.ietf.org/html/rfc5915.  "octet string [...] obtained from the unsigned integer via the Integer-to-Octet-String-Primitive (I2OSP) defined in [[RFC3447](https://tools.ietf.org/html/rfc3447)]."

The definition of I2OSP specifically says "(note that one or more leading digits will be zero if x is less than 256^(xLen-1))"

**Comment by davidben** [comment]
@richsalz Leading zeros get trimmed from `INTEGER`s. ECPrivateKey does not use an `INTEGER` for the private key. It uses a fixed-width `OCTET STRING`. (As it should. RSAPrivateKey's use of `INTEGER` was incorrect and causes the serialization to unavoidably leak a bit of secret information about the private key.)

It's also true that OpenSSL got it wrong at one point. Indeed BoringSSL has to accept non-standard encodings to workaround this. But it was largely fixed a while ago in 3d5bb773ecd78f75984fb096bb0be7808d3dc18d, which should be included in 1.0.2o. The fix wasn't quite right (see fe56d8e8a3665dc7e6784e0c170f790e6df8153f), but I don't believe that detail affects sect571r1.

Are you sure you are running 1.0.2o? The fix was in 1.0.2b.

**Comment by flurbi** [comment]
Sorry, I saw the bug with 1.0.1f, not 1.0.2o, indeed.

**Comment by mattcaswell** [comment]
Based on @davidben's comments above it sounds like this has already been fixed from 1.0.2b and above. Closing.
