### ISSUE TITLE
v1.1.1 compile option `no-stdio` on android cause `SSL_CTX_load_verify_locations` failure

### ISSUE THREAD

**Issue by PatriceJiang** [openssl/openssl#7536]
I compile v1.1.1 with `no-stdio` option on android which leads to `SSL_CTX_load_verify_locations` failure. 
```
./Configure $ARG_SSL_ARCH --prefix=$INSTALL_PREFIX no-shared no-unit-test no-tests  no-stdio -D__ANDROID_API__=$API_LEVEL
```
It works well once I remove the `no-stdio` option.

**Comment by levitte** [comment]
Yes, that is correct.  The underlying mechanism to access the certificate files uses stdio to do so, when no other lookup mechanism is in place.  If you have disabled stdio, then you have disabled access to those files.

This shouldn't be specific to Android, as far as I know.  If it is, then I'll start wondering.

**Comment by levitte** [comment]
> My understanding is that this would not stop any API from accessing the filesystem, and stdio is not the only way do that.

Your understanding is correct.  However, the *default* X509_STORE file lookup functionality uses stdio (via `BIO_s_file`), that's where the issue is.

You do make a good point, that we could document this a bit better...  I'm not exactly sure how yet, I would rather not have to enumerate every affected interface in `INSTALL`, that's just a maintenance problem waiting to happen.  Let me think on this for a bit.

**Comment by PatriceJiang** [comment]
Thanks for your explanation.
