### ISSUE TITLE
dll can't be free after it call bio_new and bio_free APIs in windows platform

### ISSUE THREAD

**Issue by forston** [openssl/openssl#7598]
Hi Team
I meet a strange problem when i use Openssl library.

Background
My project need to upgrade a DLL dynamically, so in application, it will load the DLL first and free it after application get a new version DLL. Then application will load the new DLL and run by new DLL.
But now, **my application can't free the DLL after it call bio_new and bio_free APIs. It's still in loading modules.**
If i don't call bio_new and bio_free，my application can free the DLL success.

Openssl is complied to a static library and linked in this DLL.
**I want to know if bio_new will use some system resource (file handle/network/memory) which will not be freed by bio_free.**
I doubt those resources block application to free DLL.

My Openssl version is openssl-1.1.0h.
Thanks
Forston

**Comment by mattcaswell** [comment]
This is due OpenSSL's use of `atexit()` to automatically clean itself up. In order to avoid problems if a dll gets unloaded before the process exits the DLL is "pinned" via `GET_MODULE_HANDLE_EX_FLAG_PIN`. See:

https://docs.microsoft.com/en-us/windows/desktop/api/libloaderapi/nf-libloaderapi-getmodulehandleexa

PR #7388 has a possible workaround but it needs rework based on the comments received.

**Comment by forston** [comment]
Hi mattcaswell
I tried your suggestion, it can unload now.
When will you release new version with this fixed?
Best regards
forston

**Comment by mattcaswell** [comment]
Unknown at this stage. Firstly I have to rework the PR based on the comments received (it's on my TODO list - but hasn't yet made it to the top) and then a decision has to be made whether to backport it.

**Comment by forston** [comment]
hi mattcaswell
Got it. Thank you
forston

**Comment by mattcaswell** [comment]
See #7647.
