### ISSUE TITLE
Why does ssl3_record.c check for HTTP verbs?

### ISSUE THREAD

**Issue by pdb2000** [openssl/openssl#7603]
ssl3_record.c line 317 - 320 checks for HTTP verbs GET / POST / HEAD / PUT.

Isn't that completely wrong from the conceptual point of view?

**Comment by mattcaswell** [comment]
It is a common error to attempt to point an HTTP client at a TLS server. These checks occur when we have received an invalid TLS record and it is an attempt to give back a helpful error message which might indicate what the problem might be.

**Comment by levitte** [comment]
It is to detect if someone mistakenly tries to send plaintext on a SSL-enabled channel.  So for example, if someone does the stoopid `echo HEAD / HTTP/1.0 | nc www.example.com 443`.  It enables us to deliver an appropriate error message, that's all, instead of just complaining about wrong TLS version number.
