### ISSUE TITLE
API support for Key Encapsulation Mechanisms

### ISSUE THREAD

**Issue by thomwiggers** [openssl/openssl#7616]
The EVP API has support for encrypting, signing and deriving keys, depending on what a certain primitive supports. I would like to discuss extending this API to expose the Key-encapsulation mechanism primitives `encapsulate` and `decapsulate`.

In recent years, under the influence of the development of new post-quantum schemes, we have seen many new proposals of **key-encapsulation mechanisms** (KEMs). KEMs are not necessarily new (encrypting a symmetric key to an RSA public key can very well be specified as a KEM), but since most PQ schemes are non-interactive (unlike (EC)DH), this method of specifying key agreement protocols has become much more popular in the (post-quantum) literature.

In the [NIST post-quantum standardization effort][nist-pq], over 30 KEMs have been proposed (see also the [pq lounge][pq lounge]). While I'm not saying any of these schemes should be integrated into OpenSSL today, there [have been efforts](https://open-quantum-safe.org) to experiment with the NIST proposals in OpenSSL.

The existence of an KEM API would be useful to those experimental efforts, and it could help users that want to switch to KEM-based algorithms in the future. It is possible to specify the current key agreement methods (e.g. RSA, (EC)DH) as KEMs. When post-quantum algorithms would be made available in OpenSSL, these users could then easily switch over.

I'm proposing adding methods such as `EVP_PKEY_encapsulate` and `EVP_PKEY_decapsulate`. Implementations could then be added for the current primitives in OpenSSL. I'm probably going to hack it in anyway, for my own experimental methods. I am looking if there would be interest for OpenSSL proper, and if there is, if I could then have some guidance how to implement this in such a way it can be merged.

[nist-pq]: https://csrc.nist.gov/projects/post-quantum-cryptography 
[pq lounge]: https://www.safecrypto.eu/pqclounge/

**Comment by levitte** [comment]
I assume you've read [rfc5990](https://tools.ietf.org/html/rfc5990) -- thank you btw, that was a new read for me.

Top of my head, I'm unsure if a totally new API is the better way, or if retrofitting KEM as a "padding mode" (apart from the fact that it's not actual padding as we usually think about it) would be the way to take this.

Either way, you have at least gotten me curious, and since you're going to hack at this anyway, I'm interested in following your progress.

**Comment by thomwiggers** [comment]
> I assume you've read rfc5990

I had not, but I also don't think it's that relevant.

> ... if retrofitting KEM as a "padding mode" (apart from the fact that it's not actual padding as we usually think about it) would be the way to take this.

I would call for a more general API, to support adding algorithms such as [CRYSTALS-Kyber][kyber] or [NewHope][nh]. These algorithms often only specify KEMs, to be used for example as illustrated in this picture from the Kyber paper. In the KEM specification they don't specify encryption and padding or hashing separately. These details are often part of the security analysis and the scheme should not be considered complete without them.

![KEM description from Kyber paper](https://user-images.githubusercontent.com/974662/48355546-9722f900-e694-11e8-8822-2a060d3ed402.png)

The pictured protocol is not dissimilar from DH key agreement, and in fact, DH key agreement can be specified as such: `ct` would simply be the $P_2$'s DH keyshare.

I'm not interested in RSA or adding some specific padding scheme. My end goal is being able to specify protocols in terms of KEMs, in which I then drop in various post-quantum schemes added through open-quantum-safe.

[kyber]: https://pq-crystals.org/kyber/
[nh]: https://newhopecrypto.org/

**Comment by thomwiggers** [comment]
I hacked together an `EVP_PKEY_*` api for KEMs, with support for DH-based KEMs based on the functionality for `EVP_PKEY_derive`. It's as of right now completely untested aside from compilation, but perhaps this gets you an idea of what it could look like.

```patch
diff --git a/crypto/dh/dh_pmeth.c b/crypto/dh/dh_pmeth.c
index cce2d9e26e..1785a95476 100644
--- a/crypto/dh/dh_pmeth.c
+++ b/crypto/dh/dh_pmeth.c
@@ -478,6 +478,46 @@ static int pkey_dh_derive(EVP_PKEY_CTX *ctx, unsigned char *key,
     return 0;
 }
 
+static int pkey_dh_encapsulate(EVP_PKEY_CTX *ctx, unsigned char *key, unsigned char *ciphertext, size_t *keylen, size_t *ctlen) {
+    BIGNUM *dhpub = ctx->pkey->pkey.dh->pub_key;
+    int ret = pkey_dh_derive(ctx, key, keylen);
+    *ctlen = BN_num_bytes(dhpub);
+
+    if (ret && key != NULL) {
+        BN_copy((BIGNUM*)ciphertext, dhpub);
+    }
+    return ret;
+}
+
+static int pkey_dh_decapsulate(EVP_PKEY_CTX *ctx, unsigned char *key, const unsigned char *ciphertext, size_t *keylen) {
+    // FIXME(Thom): implement derive
+    //
+    int ret = 0;
+    DH *dh;
+    BIGNUM *dhpub = (BIGNUM*)ciphertext;
+    DH_PKEY_CTX *dctx = ctx->data;
+    if (!ctx->pkey) {
+        DHerr(DH_F_PKEY_DH_DERIVE, DH_R_KEYS_NOT_SET); // FIXME(Thom): Correct errors
+        return 0;
+    }
+
+    dh = ctx->pkey->pkey.dh;
+
+    if (key == NULL) {
+        *keylen = DH_size(dh);
+        return 1;
+    }
+    if (dctx->pad)
+        ret = DH_compute_key_padded(key, dhpub, dh);
+    else
+        ret = DH_compute_key(key, dhpub, dh);
+    if (ret < 0)
+        return ret;
+    *keylen = ret;
+    return 1;
+}
+
+
 const EVP_PKEY_METHOD dh_pkey_meth = {
     EVP_PKEY_DH,
     0,
@@ -509,7 +549,12 @@ const EVP_PKEY_METHOD dh_pkey_meth = {
     pkey_dh_derive,
 
     pkey_dh_ctrl,
-    pkey_dh_ctrl_str
+    pkey_dh_ctrl_str,
+    0, 0, 0, 0, 0, 0,
+    0,
+    pkey_dh_encapsulate,
+    0,
+    pkey_dh_decapsulate,
 };
 
 const EVP_PKEY_METHOD dhx_pkey_meth = {
diff --git a/crypto/evp/pmeth_fn.c b/crypto/evp/pmeth_fn.c
index de1c07e171..72388278ea 100644
--- a/crypto/evp/pmeth_fn.c
+++ b/crypto/evp/pmeth_fn.c
@@ -229,6 +229,7 @@ int EVP_PKEY_derive_set_peer(EVP_PKEY_CTX *ctx, EVP_PKEY *peer)
         return -2;
     }
     if (ctx->operation != EVP_PKEY_OP_DERIVE
+        && ctx->operation != EVP_PKEY_OP_ENCAPSULATE
         && ctx->operation != EVP_PKEY_OP_ENCRYPT
         && ctx->operation != EVP_PKEY_OP_DECRYPT) {
         EVPerr(EVP_F_EVP_PKEY_DERIVE_SET_PEER,
@@ -281,6 +282,10 @@ int EVP_PKEY_derive_set_peer(EVP_PKEY_CTX *ctx, EVP_PKEY *peer)
     return 1;
 }
 
+int EVP_PKEY_encapsulate_set_peer(EVP_PKEY_CTX *ctx, EVP_PKEY *peer) {
+    return EVP_PKEY_derive_set_peer(ctx, peer);
+}
+
 int EVP_PKEY_derive(EVP_PKEY_CTX *ctx, unsigned char *key, size_t *pkeylen)
 {
     if (!ctx || !ctx->pmeth || !ctx->pmeth->derive) {
@@ -295,3 +300,51 @@ int EVP_PKEY_derive(EVP_PKEY_CTX *ctx, unsigned char *key, size_t *pkeylen)
     M_check_autoarg(ctx, key, pkeylen, EVP_F_EVP_PKEY_DERIVE)
         return ctx->pmeth->derive(ctx, key, pkeylen);
 }
+
+int EVP_PKEY_encapsulate_init(EVP_PKEY_CTX *ctx) {
+    // FIXME(Thom) Call any initialisation functions.
+    ctx->operation = EVP_PKEY_OP_ENCAPSULATE;
+    return 1;
+}
+
+int EVP_PKEY_encapsulate(EVP_PKEY_CTX *ctx, unsigned char *key, unsigned char *ciphertext, size_t *keylen, size_t *ctlen) {
+    if (!ctx || !ctx->pmeth || !ctx->pmeth->decapsulate) {
+        EVPerr(EVP_F_EVP_PKEY_DERIVE, // FIXME(Thom): Get specific errors
+               EVP_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE);
+        return -2;
+    }
+    if (ctx->operation != EVP_PKEY_OP_ENCAPSULATE) {
+        // FIXME(Thom): Get specific error
+        EVPerr(EVP_F_EVP_PKEY_DERIVE, EVP_R_OPERATON_NOT_INITIALIZED);
+        return -1;
+    }
+
+    // FIXME(Thom): Needed? What does this do?
+    M_check_autoarg(ctx, key, keylen, EVP_F_EVP_PKEY_DERIVE) // FIXME(Thom): Get specific error
+    
+    return ctx->pmeth->encapsulate(ctx, key, ciphertext, keylen, ctlen);
+}
+
+int EVP_PKEY_decapsulate_init(EVP_PKEY_CTX *ctx) {
+    // FIXME(Thom) Call any initialisation functions.
+    ctx->operation = EVP_PKEY_OP_DECAPSULATE;
+
+    return 1;
+}
+
+int EVP_PKEY_decapsulate(EVP_PKEY_CTX *ctx, unsigned char *key, const unsigned char *ciphertext, size_t *keylen) {
+    if (!ctx || !ctx->pmeth || !ctx->pmeth->decapsulate) {
+        EVPerr(EVP_F_EVP_PKEY_DERIVE, // FIXME(Thom): Get specific errors
+               EVP_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE);
+        return -2;
+    }
+    if (ctx->operation != EVP_PKEY_OP_DECAPSULATE) {
+        EVPerr(EVP_F_EVP_PKEY_DERIVE, EVP_R_OPERATON_NOT_INITIALIZED); // FIXME(Thom): Get specific error
+        return -1;
+    }
+
+    // FIXME(Thom): Needed? What does this do?
+    M_check_autoarg(ctx, key, keylen, EVP_F_EVP_PKEY_DERIVE) // FIXME(Thom): Get specific error
+    
+    return ctx->pmeth->decapsulate(ctx, key, ciphertext, keylen);
+}
diff --git a/crypto/include/internal/evp_int.h b/crypto/include/internal/evp_int.h
index 86f75ab601..015daab761 100644
--- a/crypto/include/internal/evp_int.h
+++ b/crypto/include/internal/evp_int.h
@@ -88,6 +88,12 @@ struct evp_pkey_method_st {
     int (*param_check) (EVP_PKEY *pkey);
 
     int (*digest_custom) (EVP_PKEY_CTX *ctx, EVP_MD_CTX *mctx);
+
+    // KEM methods
+    int (*encapsulate_init) (EVP_PKEY_CTX *ctx);
+    int (*encapsulate) (EVP_PKEY_CTX *ctx, unsigned char *key, unsigned char *ciphertext, size_t *keylen, size_t *ctlen);
+    int (*decapsulate_init) (EVP_PKEY_CTX *ctx);
+    int (*decapsulate) (EVP_PKEY_CTX *ctx, const unsigned char *ciphertext, unsigned char *key, size_t *keylen);
 } /* EVP_PKEY_METHOD */ ;
 
 DEFINE_STACK_OF_CONST(EVP_PKEY_METHOD)
diff --git a/include/openssl/evp.h b/include/openssl/evp.h
index b100248711..705f62395d 100644
--- a/include/openssl/evp.h
+++ b/include/openssl/evp.h
@@ -1277,6 +1277,8 @@ void EVP_PKEY_asn1_set_security_bits(EVP_PKEY_ASN1_METHOD *ameth,
 # define EVP_PKEY_OP_ENCRYPT             (1<<8)
 # define EVP_PKEY_OP_DECRYPT             (1<<9)
 # define EVP_PKEY_OP_DERIVE              (1<<10)
+# define EVP_PKEY_OP_ENCAPSULATE         (1<<11)
+# define EVP_PKEY_OP_DECAPSULATE         (1<<12)
 
 # define EVP_PKEY_OP_TYPE_SIG    \
         (EVP_PKEY_OP_SIGN | EVP_PKEY_OP_VERIFY | EVP_PKEY_OP_VERIFYRECOVER \
@@ -1417,6 +1419,12 @@ int EVP_PKEY_derive_init(EVP_PKEY_CTX *ctx);
 int EVP_PKEY_derive_set_peer(EVP_PKEY_CTX *ctx, EVP_PKEY *peer);
 int EVP_PKEY_derive(EVP_PKEY_CTX *ctx, unsigned char *key, size_t *keylen);
 
+int EVP_PKEY_encapsulate_init(EVP_PKEY_CTX *ctx);
+int EVP_PKEY_encapsulate_set_peer(EVP_PKEY_CTX *ctx, EVP_PKEY *peer);
+int EVP_PKEY_encapsulate(EVP_PKEY_CTX *ctx, unsigned char *key, unsigned char *ciphertext, size_t *keylen, size_t *ctlen);
+int EVP_PKEY_decapsulate_init(EVP_PKEY_CTX *ctx);
+int EVP_PKEY_decapsulate(EVP_PKEY_CTX *ctx, unsigned char *key, const unsigned char *ciphertext, size_t *keylen);
+
 typedef int EVP_PKEY_gen_cb(EVP_PKEY_CTX *ctx);
 
 int EVP_PKEY_paramgen_init(EVP_PKEY_CTX *ctx);
```

**Comment by levitte** [comment]
I'm not sure how rfc5990 is irrelevant, as it's an actual use case...  if *happens* to be for RSA, but as you noted, KEM can be used with other algos as well, or are quasi built in already.

The thing that got me looking around and stumbling upon RFC 5990 is that I'm pretty sure KEM would have to become some kind of parameter key parameter, for example in the case of CMS.

I'm just unsure how useful it is for the users to deal with a separate API specifically for this...

**Comment by richsalz** [comment]
Which standards use this kind of thing?

**Comment by paulidale** [comment]
If a new API is introduced for this, I'd prefer to see it not being added to EVP_PKEY.  KEM ought to include e.g. AES key wrap in addition to the asymmetric algorithms.

I'm not yet convinced that a new API is required.

**Comment by slontis** [comment]
CMS itself isnt dead - I recently saw a draft adding KMAC support to CMS.

**Comment by richsalz** [comment]
I didn't say or imply CMS is dead.  I said adding RSA KMAC seems dead.

**Comment by thomwiggers** [comment]
I'll admit that I don't know of any current standards that rely on the KEM api. However, that does not mean that this will not change, **especially** under the influence of post-quantum cryptography getting standardized by NIST and others. I am currently working on options for a post-quantum TLS, where e.g. Kyber could definitely play a role.

Post-quantum encryption and signing schemes are often quite painful in terms of resources and message sizes, and usually we only need key exchange. KEMs have been proposed to offer key exchange, while also making sure that the result has the proper security level.

> KEM ought to include e.g. AES key wrap in addition to the asymmetric algorithms.

These new proposals derive some shared secret that could for example be used to derive an AES key. They however **do not** *wrap* keys as such, the shared secret is generated as part of the specification of the KEM's `encapsulate` function.

Until I googled "OpenSSL CMS" just now I did not know what that was. I'm not really interested in hacking stuff such that one thing works, I want to be able to add 30+ post-quantum algorithms to [OQS](https://open-quantum-safe.org) and allow that work to eventually flow back to OpenSSL.

**Comment by henrydcase** [comment]
Hey, as last update was done 2 years ago I wonder - is there any plan to add KEM API to OpenSSL? In case there is - is it going to be near future or undefined at the moment?
Additionally, I've noticed that 3.0 implements "providers" (ex-ENGINE). One could imagine the implementation of PQ-crypto as a provider but in order to use it in the TLS, some adaptation to TLS layer is required (correct me if I'm wrong). Would openssl team be willing to accept such adaptation?

**Comment by mattcaswell** [comment]
> Hey, as last update was done 2 years ago I wonder - is there any plan to add KEM API to OpenSSL? In case there is - is it going to be near future or undefined at the moment? I'm thinking only about EVP_* API.

There are no current plans because we have no current algorithms available that need it. It's possible it could be fitted into the provider based key exchange operation at some point in the future.

> Also, If one would like to use PQ schemes in the TLS layer, then TLS layer needs to be modified to support KEM (correct me if I'm wrong). But as TLS protocol doesn't support KEM at the moment any modifications to TLS layer in OpenSSL make little sense, isn't?

Right. We are standards led - so if something needs protocol spec changes then we won't implement it yet. I recently put together a patch for pluggable TLSv1.3 key exchange support. So if a PQ scheme can be made to fit into the existing TLSv1.3 approach for key exchange then you could add that support to OpenSSL via that mechanism. See #11914.

**Comment by kaduk** [comment]
There could be other motivators to add KEM support to libcrypto; for example, the IETF MLS working group/protocol (https://datatracker.ietf.org/wg/mls/about) is currently working on a scheme that uses KEMs.

**Comment by romen** [comment]
I am updating this thread with 2 items.

## Issue might be closed

I believe #12750 effectively solved this issue, introducing a `EVP` layer API for KEM.

Please @thomwiggers, consider if you agree with this assessment and feel free to close the issue or provide more feedback on this.

## Integration with `libssl`

PR #13018 is extending the work done in #11914 (that allows providers to plug their own groups, even custom ones, into `libssl`) to
- add an extra capability to allow providers to optionally signal that a "plugged-in" group behaves as a KEM (_key encapsulation method_),
- include minimal changes in `libssl` to act on this optional capability:
  - handling of the `Key Share` extension on the client and the server checks the new capability so that, if set to true, the API introduced in #12750 is called, _as an alternative to the traditional "DH-like scheme", that remains unchanged_.

The combination of these 2 items would allow OpenSSL Providers to model the "plugged-in" groups either under the _key exchange_ scheme (both sides do a Diffie-Hellman_-like_ exchange) or the _key encapsulation method_ scheme (client sends KEM pubkey in `Key Share`, server encapsulates under given pubkey and send back the ciphertext as its `Key Share`, client decapsulates the received ciphertext using the paired privkey).
Given that a _key exchange_ scheme can trivially be described as a KEM scheme, this also allows the authors of OpenSSL Providers to optionally describe DH-like primitives in terms of KEM, which also simplifies the design and deployment of [hybrid schemes][id/tls-hybrid] composing _traditional-computing-resistant_ and _quantum-computing-resistant_ primitives.


PR #13018 is currently held back, because it is coming quite late in the development cycle of the 3.0 release and because we all want to avoid "feature creep".

I presented [my argument for inclusion][pro-inclusion] nonetheless and I am [looking for endorsement][call-for-comments] by members of the community to build support for it: please, @thomwiggers and @henrydcase or anyone else interested in this issue, consider participating in the #13018 discussion if you want to show your support on the matter, caution against inclusion, or share any relevant feedback.

[pro-inclusion]: https://github.com/openssl/openssl/pull/13018#issuecomment-700978207
[call-for-comments]: https://github.com/openssl/openssl/pull/13018#issuecomment-700979119
[id/tls-hybrid]: https://github.com/dstebila/draft-ietf-tls-hybrid-design

**Comment by thomwiggers** [comment]
Indeed seems like #12750 solves this issue. I'm not sure if I'll have time to weigh in on integration into the OpenSSL TLS 1.3 implementation.

**Comment by leontiad** [comment]
What is the difference with the `EVP Seal` functionality API?

**Comment by henrydcase** [comment]
it doesn't output ciphertext and shared secret, which is what you need for kem

**Comment by leontiad** [comment]
According to that [API](https://wiki.openssl.org/index.php/EVP_Asymmetric_Encryption_and_Decryption_of_an_Envelope), it outputs a ciphertext which encrypts a symmetric key. On a high level with both functionalities you want to send a symmetric key to the receiver using receiver's public key. So when at an application level you need to send a symmetric key over PKE it seems that the library gives you two options:other sealed envelope or encapsulation. Is the difference only on the KDF which is applied to compute the final symmetric key?
