### ISSUE TITLE
pkeyutl input restricted to (arbitrary?) 10x signature maxsize

### ISSUE THREAD

**Issue by Voker57** [openssl/openssl#7617]
https://github.com/openssl/openssl/blob/master/apps/pkeyutl.c#L282

Only 10 * EVP_PKEY_size() (which according to docs is maximum signature size) input bytes are read, not only for signing but encryption too. It's not enough for my purposes and I'm thinking of increasing it, but don't understand the rationale for such limits.

**Comment by levitte** [comment]
You have misunderstood the utility, or possibly what encryption / signing actually does.

This utility performs the private/public key operation *only*, i.e. it doesn't process the input through a digest (for signing) or a symmetric crypto (for encryption).  Because input size for pure private/public key operations is limited in relation to the size of the key, there's no point in reading more input than we already do (which already gives quite a lot of margin).

So, for signatures, the input you give `openssl pkeyutl` should be the digest of whatever input you probably intended.

If you want to produce a signature for any arbitrary input without having to run it through a digest step yourself, you should look more closely at `openssl dgst`, which can take a pkey and thereby produce a signature.

**Comment by Voker57** [comment]
Still, relying on signature size does not make sense, I'm implementing a method that does not include signatures at all. I think it should get size hints elsewhere.

Also, I'm using symmetric crypto inside implemented PKEY method, so it could operate on inputs of arbitrary length, but I'm not sure if it's the proper way of doing things.
