### ISSUE TITLE
TLS 1.2 backward compatibility

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#7618]
Hi,

This is more of a doubt than an issue.
I upgraded my server to support TLS 1.2 recently.
All functionalities are working perfect with new set of keys that I generated.
But when using an older set of certificates and keys, I get the below error:
> DUL secure transport layer : digest too big for RSA key

Is this (**digest too big for RSA key**) due to some backward compatibility issue for TLS 1.2.
Any help or info will be of great help.

Thanks in advance.

Regards,
Amal

**Comment by mattcaswell** [comment]
How big is the RSA key in question?

**Comment by amaljesudas** [comment]
It is a 512-bit key.

**Comment by mattcaswell** [comment]
That is a dangerously small RSA key and should be retired from use immediately IMO. Most modern clients will refuse to talk to such a server these days. I would recommend using at least 2048 bits.

That said I can't actually recreate the problem you report even when I attempt to use a 512 bit RSA key like you have. I suspect some combination of the OpenSSL version and the negotiated ciphersuite combined with the short RSA key length means that the RSA signature operation is failing.

**Comment by amaljesudas** [comment]
@mattcaswell 
I totally agree with the use of using higher key size. In-fact with the newly generated keys that have larger sizes, the system works perfectly.

To add some more details, our application can act both as a client and a server.
Using a legacy server emulator, that does not supports TLS 1.2, the application was able to communicate without issue using the older keys (512-bit).
But, when we attempt communication between two different instances of our application, using 512-bit keys, the above issue is observed.
What confuses me is the above scenario. I am not able to logically arrive at a conclusion.

Regards,
Amal

**Comment by mattcaswell** [comment]
So do you see the error above on the client or on the server? What OpenSSL version is being used? Do you know what ciphersuite is negotiated - or at least what ciphers are configured?

**Comment by amaljesudas** [comment]
Hi @mattcaswell 
The above error was obtained at the client side application.
Open ssl version is 1.0.2n.
Both client and server are configured to negotiate TLS_RSA_WITH_AES_128_CBC_SHA.

**Comment by mattcaswell** [comment]
I managed to recreate this issue. I assume that you are using client-auth right? I was able to get this problem to occur when the client certificate is 512 bit RSA and TLSv1.2 has been negotiated. The problem occurs when the client attempts to write out it's CertificateVerify message. First it selects its preferred signature algorithm based on the list sent to it by the server. This is new in TLSv1.2. By default it will choose RSA (because it has to - it has an RSA certificate) with the SHA512 digest (because that's the highest priority shared sigalg). Unfortunately a SHA512 digest produces output longer than a 512 bit RSA cert can sign - and hence you get this error. In my tests it also fails with SHA-384, but SHA-256 was ok.

You can configure this on the client side by modifying the `ClientSignatureAlgorithms` config parameter, or by simply calling the `SSL_CTX_set1_client_sigalgs_list()` or `SSL_set1_client_sigalgs_list()` API calls, e.g. something like the following should work:

````
SSL_CTX_set1_client_sigalgs_list(ctx, "RSA+SHA256");
````

Really OpenSSL shouldn't select a digest that is going to fail - but since this only happens with very small RSA keys that you really shouldn't be using I'm not sure that's going to be a high priority to fix.

**Comment by amaljesudas** [comment]
Hi @mattcaswell 

Thanks for the update.
Sorry for the delay as I could verify your update only yesterday.

> I assume that you are using client-auth right? 
Yes, right.

I got your point and could verify the same in my scenario.
Just to clarify, _"...output longer than a 512 bit RSA cert can sign"_ - this refers to the private key of client, right? I mean, you use the client's private key to sign the digest.
Please correct me if I am wrong.

Regards,
Amal

**Comment by mattcaswell** [comment]
> Just to clarify, "...output longer than a 512 bit RSA cert can sign" - this refers to the private key of client, right? I mean, you use the client's private key to sign the digest.

Right. Sorry, I was being sloppy with my wording. Obviously its the private key that does the actual signing.

**Comment by amaljesudas** [comment]
Hi @mattcaswell 

Thanks for your inputs.
I tried the work around that you suggested and could see it working.
Will check with client if a work around has to be applied or if we can treat 512bit length as obsolete.
Your analysis was really helpful, thank you again.

Regards,
Amal
