### ISSUE TITLE
Uninit read in siphash_internal_test

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#7641]
Travis is currently failing due to an uninit read in siphash_internal_test. The problem occurs in `test_siphash_basic` which calls `SipHash_set_hash_size()` with an uninitialised `SIPHASH` object.

PR #7613 recently changed that function to attempt a read from the `SIPHASH` first before updating it. This change therefore requires the `SIPHASH` to have been initialised. It's not clear to me whether it is supposed to be allowed to attempt this operation with an uninitialised SIPHASH or not. `SipHash_set_hash_size()` can be invoked from `EVP_MAC_ctrl` using `EVP_MAC_CTRL_SET_SIZE`. The documentation for `EVP_MAC_ctrl` says:

```
EVP_MAC_ctrl() can be called both before and after EVP_MAC_init(), but
the effect will depend on what control is being use.
See </CONTROLS> below for a description of standard controls.
````
But the documentation for the ctrl in question is silent on what happens if it is called before `EVP_MAC_init()`

**Comment by levitte** [comment]
There are two possible answers here:

1. revert the change from #7613, and thereby require that the hash size only be set before `SipHash_Init` is called, never after.  That will require the EVP_MAC siphash implementation to do a little bit of caching, which is workable although annoying.
2. change `test/siphash_internal_test.c` to initialize its local `siphash`...  that's quite trivial.  Since the low level SipHash functions are internal only anyway and the SIPHASH type as well, the requirement to initialize only falls on OpenSSL developers.

Personally, I'd go with 2.
