### ISSUE TITLE
Missing check?

### ISSUE THREAD

**Issue by ManSoSec** [openssl/openssl#7650]
Hi,

https://github.com/openssl/openssl/blob/master/crypto/rsa/rsa_x931g.c#L111
Return value of BN_mod_inverse is checked at line 112:
``` C
    rsa->d = BN_mod_inverse(NULL, rsa->e, r0, ctx2); /* d */
    if (rsa->d == NULL)
        goto err;
```

But it is not checked here:
https://github.com/openssl/openssl/blob/master/crypto/rsa/rsa_x931g.c#L130
``` C
    rsa->iqmp = BN_mod_inverse(NULL, rsa->q, rsa->p, ctx2);
```

I can provide a pull request if this is the case.

Thanks!

**Comment by agnosticdev** [comment]
The return value of `rsa->d` looks like it is checked on line 112 because it is used again on 119 and 126 during that function.

```c
rsa->d = BN_mod_inverse(NULL, rsa->e, r0, ctx2); /* d */
if (rsa->d == NULL)
    goto err;

/* calculate d mod (p-1) */
rsa->dmp1 = BN_new();
if (rsa->dmp1 == NULL)
    goto err;
if (!BN_mod(rsa->dmp1, rsa->d, r1, ctx))
    goto err;

/* calculate d mod (q-1) */
rsa->dmq1 = BN_new();
if (rsa->dmq1 == NULL)
    goto err;
if (!BN_mod(rsa->dmq1, rsa->d, r2, ctx))
    goto err;

/* calculate inverse of q mod p */
rsa->iqmp = BN_mod_inverse(NULL, rsa->q, rsa->p, ctx2);

ret = 1;
```

The `rsa->iqmp` value is not used during the rest of the `RSA_X931_derive_ex()` or `RSA_X931_generate_key_ex()` function.  That is why it looks like this value is not checked.

**Comment by InfoHunter** [comment]
From my limit understandings of ANSI X9.31 RSA, I think that has different defines on key derivation/generation and signature paddings against what is defined for RSA in PKCS#1.

If so, the `iqmp` could still be used when calculating via CRT. And `BN_mod_inverse` could fail due to reasons as memory allocation failure. So I think this field should be checked since non-X931 key generation function also checks this value.

(Please correct me if I didn't understand this right, thanks!)

**Comment by InfoHunter** [comment]
> Thanks @InfoHunter! Shall I send a pull request containing the check?

Hi @ManSoSec , I guess so ;-)

**Comment by agnosticdev** [comment]
>  So I think this field should be checked since non-X931 key generation function also checks this value.

After reviewing other uses of `BN_mod_inverse`, yes this does make sense @InfoHunter.
