### ISSUE TITLE
ability to disable authentication algorithms

### ISSUE THREAD

**Issue by YuDudysheva** [openssl/openssl#7684]
I'm using openssl1.1.0i and I want to disable aGost2001. Since Gost2012-Gost89120Gost8912 ciphercuite provides 2 algorithms for authentication, it's also disabled.

````
diff -u -N -r openssl-1.1.0i_orig/ssl/ssl_ciph.c openssl-1.1.0i_gost/ssl/ssl_ciph.c
--- openssl-1.1.0i_orig/ssl/ssl_ciph.c	2018-08-14 15:45:09.000000000 +0300
+++ openssl-1.1.0i_gost/ssl/ssl_ciph.c	2018-11-22 11:19:12.970986866 +0300
@@ -687,7 +724,7 @@
         if (FIPS_mode() && (c->algo_strength & SSL_FIPS))
             continue;
         if ((c->algorithm_mkey & disabled_mkey) ||
-            (c->algorithm_auth & disabled_auth) ||
+            ((c->algorithm_auth & disabled_auth) == c->algorithm_auth) ||
             (c->algorithm_enc & disabled_enc) ||
             (c->algorithm_mac & disabled_mac))
             continue;
````

**Comment by mattcaswell** [comment]
Ping @beldmit.

**Comment by beldmit** [comment]
Looks reasonable, but I need a closer look.

**Comment by beldmit** [comment]
Do you want to disable only aGOST01?

**Comment by YuDudysheva** [comment]
Yes.

**Comment by beldmit** [comment]
[7684_fix.txt](https://github.com/openssl/openssl/files/2611560/7684_fix.txt)
Try the attached patch (against master). It partially fixes the problem.

The fix you proposed does not do what you want because of manipulating bits related to algorithms available at build time or (in case of GOST algorithms) at initialization time. You need to fix it at the stage of filtering ciphersuites. 

BTW, it may be still not enough because it filters out the ciphersuites but does not filter out the methods (and corresponding certificates) during the handshake. 
@mattcaswell, am I right?

**Comment by t8m** [comment]
1.1.0 is out of support. Closing. If you still see the problem with 1.1.1 or 3.0 versions, please open a new issue.
