### ISSUE TITLE
DTLS 1.2 strictly support

### ISSUE THREAD

**Issue by getsoubl** [openssl/openssl#7694]
Hello,
How   the openssl must be configured in order to support strictly DTLS 1.2?
Not include DTLS 1.0 chiphers 

I just configure the SSL_ctx using the  DTLSv1_2_server_method and 
DTLSv1_2_client_method respectively

Βut analyzing  th wiresharks I detect that in the client hello dtls 1.0
chiphes are included as well.
Is this right?

Morever, how we can configure  the openssl to support fallback to lower
version if the server does not support 1.2

Thank you
George

**Comment by mattcaswell** [comment]
> Morever, how we can configure the openssl to support fallback to lower
version if the server does not support 1.2

Use `DTLS_server_method` and `DTLS_client_method` instead. These are the preferred "version flexible" methods that will negotiate the highest version available on both client and server.

> How the openssl must be configured in order to support strictly DTLS 1.2?
Not include DTLS 1.0 chiphers

Probably you don't really want to do this. If you only configure DTLSv1.2 ciphers then you lose all the benefits of version flexibility since DTLSv1.0 will not work.

Nevertheless, the ciphersuites can be configured using `SSL_CTX_set_cipher_list` or `SSL_set_cipher_list`:

https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_cipher_list.html

**Comment by getsoubl** [comment]
Thank you for your answer
