### ISSUE TITLE
Add all wycheproof's tests

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#7714]
We should add all tests from https://github.com/google/wycheproof in our test suite.

**Comment by mattcaswell** [comment]
Is there a licence issue? The license seems to be Apache 2 - not sure we can just incorporate them without  asking to relicence them underly OpenSSL licence.

**Comment by richsalz** [comment]
Can't you just reference it as a submodule, as done with the python and boring tests?

**Comment by kroeckx** [comment]
boringssl also has a copy of the tests vectors, which is probably in a more useful format for us.

**Comment by reaperhulk** [comment]
One potential option here would be to just update the pyca-cryptography submodule. We add wycheproof tests every time we add support for a new OpenSSL feature. (This is how we found the X25519 issue and the ed25519 issue, but not the ed448 issue since wycheproof has not released vectors for that yet). That would minimize your effort, but the disadvantage is that you won't catch things before release unless we test against master rather than a release (which we do on occasion: see x25519 bug).

**Comment by richsalz** [comment]
Is what pyca-cryptography does good enough to close this?

**Comment by t8m** [comment]
> Is what pyca-cryptography does good enough to close this?

IMO it is good enough given the limited amount of resources the project has. Closing.
