### ISSUE TITLE
9 Lives of Bleichenbacher's CAT - vulnerability

### ISSUE THREAD

**Issue by attritionorg** [openssl/openssl#7739]
Regarding this recent disclosure: http://cat.eyalro.net/

They say they contacted the affected vendors, which include OpenSSL. Do you have a fixing commit or any references for this attack?

Thank you!

**Comment by kroeckx** [comment]
It mentions 3 things it attacked in OpenSSL:
- BN2binpad, this was fixed in #5254 and #6915, which was fixed in:
  - master
    - PR #5254: commit 89d8aade5f4011ddeea7827f08ec544c914f275a and 582ad5d4d9b7703eb089016935133e3a18ea8205 (part of 1.1.1 release)
    - PR #6915: commit fcc4ee09473cac511eca90faa003661c7786e4f9, 41bfd5e7c8ac3a0874a94e4d15c006ad5eb48e59, e02c519cd32a55e6ad39a0cfbeeda775f9115f28, and 324b95605225410763fe63f7cff36eb46ca54ee9 (part of 1.1.1 release)
  - 1.1.0: 
    - PR #5254: commit 75a67a036a041d9fdac0fd7fd5a461f48709a3d3 and 0b139e41b4ca03c1d36f4c93c6e9147e497029ca (part of 1.1.0i release)
    - PR #6915: commit a6d8fe92a601728138e645302fa8bab7ca54fb58, db09fdc1a675bde167001a4f68e0f1e595e96dee, c5c6915fba3f1becfd78ed2be032caa38ecadef3 and 73bebc17a14da5278b01416b39e5c28a7d0c1861 (part of 1.1.0j release)
  - 1.0.2:
    -  PR #6889, commit 6412738be390dd9bf680cef89f22e4c810ab065f, df6b67becc1f41c2eeee7e20ff10b5ec42ced58b and ec3f996b3066ecaaec87ba5ad29c606aeac0740d (part of 1.0.2p releasse)
    - PR #6942: commit 387d170b32ceeac450bfa50b81db9db9179dc880, f9381fd323303316282331a8cced6e030e809794, b6f773b8d6c41e86c107b57dabc637c91884150e and bc251459adc14a1a56d0cbe2d372f3d6ffd20cf8 (part of 1.0.2q release)
- RSA_padding_check_PKCS1_type_2
  - master: commit f658a3b64d8750642f4975090740865f770c2a1b, 89072e0c2a483f2ad678e723e112712567b0ceb1, e875b0cf2f10bf2adf73e0c2ec81428290f4660c, 75f5e944be97f28867e7c489823c889d89d0bd06 and 603221407ddc6404f8c417c6beadebf84449074c
  - 1.1.1: commit d2cd28b99efa65dbd39cb8db0f2ad992be1aab00, 382448f33757d96a65207c8e9b55fadf45517e57, db1b63f45c8585c9c7741e0540c01baad22aa190, f5ebe54c00128d5ee0a28ba7f822a8d1b07e71e5, f1d91b89701627cc39e98987bc344aaae64f64fb (will be part of the 1.1.1b release)
  - 1.1.0: PR #7735, not merged yet, will be part of 1.1.0k
  - 1.0.2: PR #7737, not merged yet, will be part of 1.0.2r
- RSA_padding_check_none memset call: Unfixed at this time

**Comment by kroeckx** [comment]
@dot-asm: It seems we somehow missed the memset call that's mentioned in the paper, is this something you can look at?

**Comment by dot-asm** [comment]
> RSA_padding_check_none memset call: Unfixed at this time

Keyword here is that it's not called from anywhere (anymore). But even if it was called, one has to recognize following. There is certain ambiguity in claim that "BN2binpad was fixed in commit x." Because solution is not in this modification by itself, but in combination with another modification, namely switch from BN_bn2bin to BN_bn2binpad in rsa/rsa_ossl.c. Do note that after this switch call to RSA_padding_check_none (even in its current state!) would *not* give away the to-be-protected information. In case the call was preserved that is. In other words security rests not only in each function, but even in how they interact with each other. And it's even possible to interact with "insecure" functions in secure manner, like in just mentioned if-the-call-was-preserved example.

Well, one can still argue that RSA_padding_check_none deserves to be adjusted, just because it happens to be exported and hypothetically there might be an application that calls it explicitly (as opposite to implicitly not calling it by passing specific `padding` value to RSA_private_decrypt). At the same time one can only wonder how the said application would look like and if it would be actually secure even if RSA_padding_check_none is "fixed". Again, it's even about how caller interacts with it, and thing is that "fixed" version wouldn't actually solve the problem, only make attacks harder. Which is why "fixed" is in quotes in last sentences. In other words one can't actually fix RSA_padding_check_none in real meaning of the term, it's the caller that needs to be fixed in either case...

**Comment by kroeckx** [comment]
So the internal calls from the TLS library to RSA_padding_check_none() are done in such a way that memset() and memcpy() are always called with the same parameters and so everything is ok.

So in summary:
- The OpenSSL TLS implementation was already fixed in released versions.
- External users of RSA decryption need the RSA_padding_check_PKCS1_type_2 and related changes

**Comment by dot-asm** [comment]
> So the internal calls from the TLS library to RSA_padding_check_none() are done in such a way that memset() and memcpy() are always called with the same parameters and so everything is ok.

The internal calls from the TLS library to RSA_padding_check_none() **would** be done in the said way. If the call was preserved. But it's not preserved, it's gone, the function in question is not called from anywhere in OpenSSL. And everything is OK and more...

**Comment by kroeckx** [comment]
So I'm just going to close this issue.

**Comment by attritionorg** [comment]
Thanks for the links and insight here @kroeckx and @dot-asm, much appreciated.

**Comment by msmeissn** [comment]
will the openssl team assign CVEs?

**Comment by mspncp** [comment]
> will the openssl team assign CVEs?

ping @openssl

**Comment by mattcaswell** [comment]
There are no plans to assign CVEs for this.
