### ISSUE TITLE
Double free bug in execute_test_large_message

### ISSUE THREAD

**Issue by BianPan** [openssl/openssl#7844]
File: test/sslapitest.c
Function: execute_test_large_message
Issue details: 

The function execute_test_large_message releases  chaincert via X509_free(chaincert) when SSL_CTX_add_extra_chain_cert returns 0. After that, the control flow jumps to label "end", where X509_free(chaincert) is executed again, resulting in a double free bug.

For your convenience, I copy-and-paste related source code as follows.

````
static int execute_test_large_message(const SSL_METHOD *smeth,
                                      const SSL_METHOD *cmeth,
                                      int min_version, int max_version,
                                      int read_ahead)
{
    ...
    X509 *chaincert = NULL;
    ...
    chaincert = PEM_read_bio_X509(certbio, NULL, NULL, NULL);
    ...
    for (i = 0; i < NUM_EXTRA_CERTS; i++) {
        if (!X509_up_ref(chaincert))
            goto end; 
        if (!SSL_CTX_add_extra_chain_cert(sctx, chaincert)) {
            X509_free(chaincert);
            goto end;
        }
    }
    ...
 end:
    X509_free(chaincert);
    SSL_free(serverssl);
    SSL_free(clientssl);
    SSL_CTX_free(sctx);
    SSL_CTX_free(cctx);

    return testresult;
}
````

Best regards,
Pan Bian

**Comment by mattcaswell** [comment]
This code is in fact correct. X509 objects are reference counted:

````
    chaincert = PEM_read_bio_X509(certbio, NULL, NULL, NULL);
````
After the above line is executed `chaincert` has 1 ref.
````
        if (!X509_up_ref(chaincert))
            goto end; 
````
After this line `chaincert` has 2 refs.
````
        if (!SSL_CTX_add_extra_chain_cert(sctx, chaincert)) {
````
On success of this line ownership of one of the `chaincert` refs is passed to `sctx`. If it fails nothing happens.
````
            X509_free(chaincert);
            goto end;
````
This is the failure path. After these lines the number of refs to `chaincert` is decremented. So `chaincert` still has 1 ref left before we go to the `end` label. Since there is still a ref left the X509 object is not actually freed at this point.
````
 end:
    X509_free(chaincert);
````
This decrements the final ref. Since the ref count gets to zero the object is freed for real this time.
