### ISSUE TITLE
Many calls to getenv remain after the changes to use ossl_safe_getenv instead

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#7917]
Recently in pull request #7047, @paulidale made changes to swap usage of getenv to ossl_safe_getenv. However, many calls to getenv remain, notably in engines like ccgost that get linked in. Can we not change all calls to getenv to ossl_safe_getenv?

**Comment by mlindner** [comment]
Additionally the comments say that it changes all entries in libcrypto, however that's not true and several locations remain even in libcrypto.

```
$ grep -RI '[^_]getenv(' crypto
crypto/armcap.c:    if ((e = getenv("OPENSSL_armcap"))) {
crypto/ecdsa/ecdsatest.c:    if (!((getenv("OPENSSL_DEBUG_MEMORY") != NULL) &&
crypto/ecdsa/ecdsatest.c:          (0 == strcmp(getenv("OPENSSL_DEBUG_MEMORY"), "off")))) {
crypto/ppccap.c:    if ((e = getenv("OPENSSL_ppccap"))) {
crypto/cryptlib.c:    if ((env = getenv("OPENSSL_ia32cap"))) {
crypto/ec/ectest.c:    if (!((getenv("OPENSSL_DEBUG_MEMORY") != NULL)
crypto/ec/ectest.c:          && (0 == strcmp(getenv("OPENSSL_DEBUG_MEMORY"), "off")))) {
crypto/getenv.c:    return getenv(name);
crypto/threads/mttest.c:        cipher = getenv("SSL_CIPHER");
crypto/sparcv9cap.c:    if ((e = getenv("OPENSSL_sparcv9cap"))) {
crypto/sparcv9cap.c:    if ((e = getenv("OPENSSL_sparcv9cap"))) {
crypto/sha/sha512t.c:        if ((env = getenv("OPENSSL_ia32cap")))
crypto/engine/enginetest.c:    if (!((getenv("OPENSSL_DEBUG_MEMORY") != NULL)
crypto/engine/enginetest.c:          && (0 == strcmp(getenv("OPENSSL_DEBUG_MEMORY"), "off")))) {
crypto/whrlpool/wp_test.c:        if ((env = getenv("OPENSSL_ia32cap")))
```

**Comment by paulidale** [comment]
There was some discussion about what should use the safe call and what shouldn't.  The raw getenv calls that remain are the processor capabilities flags and some debug options.

As for engines, they are not part of the main code base and it would be up to the individual maintainers to update to using the safe getenv call.

**Comment by mlindner** [comment]
The code in the engine directory has separate maintainers that are not part of OpenSSL project?

**Comment by richsalz** [comment]
No.  Everything in the OpenSSL release is maintained by the team (with help of course).  There are other engines, such as GOST, that are external.

**Comment by paulidale** [comment]
As @richsalz wrote.  The engine directory from the distribution contains no calls to `getenv(3)`.

**Comment by mlindner** [comment]
> As @richsalz wrote. The engine directory from the distribution contains no calls to `getenv(3)`.

That's false. https://github.com/openssl/openssl/tree/OpenSSL_1_0_2-stable/engines The engines in 1.0.2 are not the same as the engines in 1.1.1.

**Comment by paulidale** [comment]
[I'm on vacation so I'll be brief]

The listing is from 1.0.2q not master and it doesn't match the listing I get from 1.0.2q.  This release is in security fix only mode at present: only security fixes can be committed.  Would these changes be security fixes?  I've got an opinion for each, I'd like to hear others' risk analyses.

The debug and processor feature selectors were deliberately left in place.  That leaves two that might be worth changing: `getenv(name)` and `getenv(SSL_CIPHER)`.  The former is likely best left alone (as in I can't find it in the source code).  The latter is guarded by an issetugid so should be safe but could be changed to the new scheme.

The SSL directory has one case (the `getenv("SSL_CIPHER")` in ssl_task.c) which is VMS exclusive.  The rest are definitely ignorable.  This executable looks old and seems like it would always be started in a controlled fashion @levitte ?

I'm not sure what the status of the GOST engine is.  It isn't part of the distro in 3.0.0 (but should be).

When the original work was done, the apps were specifically excluded from consideration because they should be run in a controlled manner.  So all the instances in apps are bogus from this viewpoint.

So, at most a couple of cases to consider if they are security programs and then rectify the ones that are.

**Comment by paulidale** [comment]
Closing this because it mostly is about 1.0.2 that is well beyond end of support now.
