### ISSUE TITLE
Incorrect alert message for malformed ClientHello

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#7940]
openssl version baba1545105131fa34068f62928322e99d695ab1

When OpenSSL receives a ClientHello message that does not list CompressionMethod.null method it aborts with a decode_error Alert.

RFC 8446 states:
```
      For every TLS 1.3 ClientHello, this vector
      MUST contain exactly one byte, set to zero, which corresponds to
      the "null" compression method in prior versions of TLS.  If a
      TLS 1.3 ClientHello is received with any other value in this
      field, the server MUST abort the handshake with an
      "illegal_parameter" alert.
```

while RFC 5246 states:
```
      This vector MUST contain,
      and all implementations MUST support, CompressionMethod.null.
```

so the correct value would be illegal_parameter

Reproducer: https://github.com/tomato42/tlsfuzzer/pull/489

**Comment by erbsland-dev** [comment]
@t8m @tomato42 This issue seems to be fixed in the latest version of the library.

https://github.com/openssl/openssl/blob/9884568569feb559cea2496a3326259a53db0860/ssl/statem/statem_clnt.c#L1550-L1554

**Comment by tomato42** [comment]
@erbsland-dev that code is older (dec 2017) than this issue (dec 2018)... have you _tested_ that it's fixed?

**Comment by erbsland-dev** [comment]
I just realised, I actually got decode error when I recreated my test.

**Comment by tomato42** [comment]
> Could you please share the test code you used for this case?

it's linked from the original description: https://github.com/tlsfuzzer/tlsfuzzer/pull/489...
it's the [/test-invalid-compression-methods.py](https://github.com/tlsfuzzer/tlsfuzzer/pull/489/files#diff-99279c0be1503c4c99263c445e2663b5a51a3efc9c3df2cd710c7bbaff0117f2) script

**Comment by erbsland-dev** [comment]
It's embarrassing: I can confirm the bug is indeed still open in openssl. It seems, when I did the test back then, I accidentally tested against a different SSL implementation, as I had a company server in the host parameter, instead of localhost.

I created the following PR to resolve this issue: https://github.com/openssl/openssl/pull/25255

**Comment by erbsland-dev** [comment]
It’s important not to rush these things.

With some additional time to review, I revisited the tests I conducted in July. They were indeed correct, but I mistakenly referenced the wrong code snippet in my previous comment. The issue was only resolved for TLSv1.3. When I re-ran the tests using an unaltered version of OpenSSL, I had mistakenly tested against TLSv1.2, which indeed incorrectly returns `SSL_AD_DECODE_ERROR` when the NULL compression method is absent.

I’ve since updated my PR to address this issue for TLSv1.2 and included more comprehensive tests to ensure the correct alert messages are returned for both TLSv1.2 and TLSv1.3.
