### ISSUE TITLE
RAND_DRBG: Improve randomness generation for Windows

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#7945]
This issue has been braught up in the recent [OSTIF Security Audit of the OpenSSL 1.1.1 Random Number Generation](https://ostif.org/our-review-of-the-openssl-1-1-1-random-number-generation-update) and still needs to be addressed. 

The following text is a minimally redacted excerpt from [opensslrng-audit-report.pdf](https://ostif.org/wp-content/uploads/2018/09/opensslrng-audit-report.pdf):

### F. Windows randomness generation

On pre-Windows 7 platforms, three calls to the CryptoAPI are used:

https://github.com/openssl/openssl/blob/23d221b771348e3e3ee316cd1190a4a344d145fc/crypto/rand/rand_win.c#L84-L90

On Windows XP or above, the CryptoAPI can be bypassed in favor of RtlGenRandom(), which is for example
used by BoringSSL, Chromium, Ring, Firefox. BoringSSL does the following in [crypto/rand_extra/windows.c](https://github.com/google/boringssl/blob/2d98d49cf712ca7dc6f4b23b9c5f5542385d8dbe/crypto/rand_extra/windows.c#L26-L51):
```C
// #define needed to link in RtlGenRandom(), a.k.a. SystemFunction036.  See the
// "Community Additions" comment on MSDN here:
// http://msdn.microsoft.com/en-us/library/windows/desktop/aa387694.aspx
#define SystemFunction036 NTAPI SystemFunction036
#include <ntsecapi.h>
#undef SystemFunction036

OPENSSL_MSVC_PRAGMA(warning(pop))

#include "../fipsmodule/rand/internal.h"


void CRYPTO_sysrand(uint8_t *out, size_t requested) {
  while (requested > 0) {
    ULONG output_bytes_this_pass = ULONG_MAX;
    if (requested < output_bytes_this_pass) {
      output_bytes_this_pass = (ULONG)requested;
    }
    if (RtlGenRandom(out, output_bytes_this_pass) == FALSE) {
      abort();
    }
    requested -= output_bytes_this_pass;
    out += output_bytes_this_pass;
  }
  return;
}
```

Related to: #7944 #7946

**Comment by mspncp** [comment]
cc @veorq

**Comment by paulidale** [comment]
My understanding is that RtlGenRandom calls CryptGenRandom for its randomness.  The reason to make this change would be to make the code simpler by avoiding the context creation.  If we need this for backward compatibility, it makes the code more complex.

I.e. I don't believe we need to address this because it isn't a real problem.

Any additional comments or a reference @davidmakepeace ?

**Comment by davidben** [comment]
@paulidale I believe it's the other way around. CryptAcquireContext + CryptGenRandon ultimately calls RtlGenRandom, but it also initializes a bunch of other stuff. We use RtlGenRandom because we need to be sandbox-friendly.

**Comment by paulidale** [comment]
@davidben hanks for the clarification.

**Comment by davidmakepeace** [comment]
CryptGenRandom calls RtlGenRandom.

I would prefer to use RtlGenRandom because it is not part of CAPI and doesn’t require a context.

 

David

--

David Makepeace | Consulting Member of Technical Staff | Network Security & Encryption

Ph: +61 7 3031 7047 | Oracle Australia | Level 16, 340 Adelaide Street, Brisbane QLD 4000

**Comment by mspncp** [comment]
Cleaning up old neglected issues...
