### ISSUE TITLE
A potential NPD bug

### ISSUE THREAD

**Issue by wurongxin1987** [openssl/openssl#7950]
In openssl 1.1.0, in the source file engines/e_dasync.c, there is a potential NPD bug. 
![image](https://user-images.githubusercontent.com/4220002/50390282-4e209300-0770-11e9-8c4f-1b15b7c11361.png)

In Line 757, EVP_aes_128_cbc_hmac_sha1() function may return null, and then is passed to the function call to dasync_cipher_init_key_helper as the fifth parameter. Later, it will be dereferenced in the source file engines/e_dasync.c at Line 638. 

![image](https://user-images.githubusercontent.com/4220002/50390340-1e25bf80-0771-11e9-8127-b5f933b9fb16.png)

![image](https://user-images.githubusercontent.com/4220002/50390317-d2731600-0770-11e9-8ac9-366740ae7d68.png)
![image](https://user-images.githubusercontent.com/4220002/50390325-def76e80-0770-11e9-9beb-06bc90e3396e.png)

Would you help to confirm whether this is a true bug? Thanks.

**Comment by richsalz** [comment]
It's not really a bug, since the function returns one of two global variables, and can never return NULL. The real issue is that openssl is not consistent about checking the return value against NULL.

**Comment by wurongxin1987** [comment]
Thanks for your prompt reply. I notice that, there is another implementation of the function EVP_aes_128_cbc_hmac_sha1 with a different macro definition. I wonder whether this is also possible.

![image](https://user-images.githubusercontent.com/4220002/50390976-f20e3c80-0778-11e9-800d-301562b30ff3.png)

**Comment by richsalz** [comment]
Why don't you look at how that code gets compiled (check the ifndef), and then look at the other places and see.

**Comment by wurongxin1987** [comment]
Thanks for your last reply. Sorry for my late reply. I still have some problems in understanding why the following function will return one of two global variables. 

![image](https://user-images.githubusercontent.com/4220002/51183210-864c6900-190b-11e9-83da-758f7fd12050.png)

Do you mean the variable **AESNI_CAPABLE** will never be NULL?

**Comment by richsalz** [comment]
Look at what AESNI_CAPABLE is.  (It's a number, testing a bit)

**Comment by mspncp** [comment]
@richsalz I think @wurongxin1987's analysis is correct and it's a real issue.

The `AESNI_CAPABLE` is only a bit mask, that's right. But this flag is used for testing the AES-NI capability in the [OPENSSL_ia32cap](https://www.openssl.org/docs/man1.1.0/crypto/OPENSSL_ia32cap.html) processor capabilities vector. And if the capability is not present, the conditional expression will evaluate to `NULL`:

https://github.com/openssl/openssl/blob/47c55f881ffef8aa5fafcb88d4230700bb279449/crypto/evp/e_aes_cbc_hmac_sha1.c#L943-L947

The other function always returns NULL, ...

https://github.com/openssl/openssl/blob/47c55f881ffef8aa5fafcb88d4230700bb279449/crypto/evp/e_aes_cbc_hmac_sha1.c#L955-L958

... it is compiled if the following preprocessor condition is false:

https://github.com/openssl/openssl/blob/47c55f881ffef8aa5fafcb88d4230700bb279449/crypto/evp/e_aes_cbc_hmac_sha1.c#L36-L38

The NULL return value of `EVP_aes_128_cbc_hmac_sha1()` is passed to `dasync_cipher_init_key_helper()` as parameter `cipher` ...

https://github.com/openssl/openssl/blob/47c55f881ffef8aa5fafcb88d4230700bb279449/engines/e_dasync.c#L628-L646

... and from there to `EVP_CIPHER_impl_ctx_size()`, where it is derererenced unconditionally:

https://github.com/openssl/openssl/blob/47c55f881ffef8aa5fafcb88d4230700bb279449/crypto/evp/evp_lib.c#L175-L178


Maybe @mattcaswell can tell us more, because the `cipher` parameter was added in https://github.com/openssl/openssl/commit/e38c2e8535bec4660c00c8394ff181d622bd41bd#diff-3d89738286f065b19ae6d2e0957ad2a0R666.

**Comment by mspncp** [comment]
I made one more mysterious observation: there are three definitions of `AESNI_CAPABLE`

```
crypto/evp/e_aes.c:180:# define AESNI_CAPABLE   (OPENSSL_ia32cap_P[1]&(1<<(57-32)))
crypto/evp/e_aes_cbc_hmac_sha1.c:41:# define AESNI_CAPABLE   (1<<(57-32))
crypto/evp/e_aes_cbc_hmac_sha256.c:42:# define AESNI_CAPABLE   (1<<(57-32))
```

and the one in `e_aes.c` is different from the others: it's used like a boolean (meaning: AES-NI is present) and not like a bit mask, see

https://github.com/openssl/openssl/blob/47c55f881ffef8aa5fafcb88d4230700bb279449/crypto/evp/e_aes.c#L180

and

https://github.com/openssl/openssl/blob/47c55f881ffef8aa5fafcb88d4230700bb279449/crypto/evp/e_aes.c#L520-L521

**Comment by mspncp** [comment]
Formally, it's not a mistake to have different definitions of `AESNI_CAPABLE`, since they are visible only in their respective modules, but it's confusing for anyone who (re-)views the code.

**Comment by mspncp** [comment]
> It's not really a bug, since the function returns one of two global variables, and can never return NULL. 

@richsalz when you wrote "the function", can it be that you had the `EVP_aes_128_cbc ()` function in mind?

Indeed, the implementation of `EVP_aes_128_cbc ()` can be found at

https://github.com/openssl/openssl/blob/47c55f881ffef8aa5fafcb88d4230700bb279449/crypto/evp/e_aes.c#L1266

after expanding the macro

https://github.com/openssl/openssl/blob/47c55f881ffef8aa5fafcb88d4230700bb279449/crypto/evp/e_aes.c#L520-L521

so `EVP_aes_128_cbc ()` can never return a NULL cipher, contrary to the `EVP_aes_128_cbc_hmac_sha1()` function.

**Comment by wurongxin1987** [comment]
Thank Matthias St. Pierre very much for the very detailed comments and clarification. It is really helpful for me to understand the code.

**Comment by wurongxin1987** [comment]
The tool name is Sourcebrella Pinpoint (https://www.sourcebrella.com/). This bug is detected by our new experimental version (under the development in the Cybersecurity Lab, the Hong Kong University of Science and Technology ). This version is still under the test. We are willing to share the bugs detected by it. Hope this will also help you guys.

**Comment by richsalz** [comment]
impressive work, @mspncp

**Comment by mspncp** [comment]
> impressive work, @mspncp

Oh, thanks for the complement! By the way, you remind me that I wanted to ask you a question: Is it possible that you had `EVP_aes_128_cbc()` in mind when you wrote the following in https://github.com/openssl/openssl/issues/7950#issuecomment-449682354?

> ... the function returns one of two global variables, and can never return NULL.

Because `EVP_aes_128_cbc()` indeed returns one of two non-null pointers:

https://github.com/openssl/openssl/blob/47c55f881ffef8aa5fafcb88d4230700bb279449/crypto/evp/e_aes.c#L520-L521

In that respect, `EVP_aes_128_cbc_hmac_sha1()` obviously behaves different.

I wonder whether the proper solution for this issue might be to return a non-null fallback instead of NULL, when AES-NI is not available. What do you think?

**Comment by iamihalcea** [comment]
@mspncp @richsalz - do you reckon `AESNI_CAPABLE` should be renamed in `e_aes.c` to avoid any future confusion?

**Comment by levitte** [comment]
I'm looking at this, and from the first posts, it seems obvious to me that `e_dasync.c` should check that `EVP_aes_128_cbc_hmac_sha1()` returned a non-NULL pointer before using it.  *This is, after all, what we're asking others to do*

**Comment by mspncp** [comment]
@wurongxin1987 thank you again for reporting this issue. Although it was finally classified as a non-issue, I would like to emphasize that I do _not_ consider it a false positive of your static analyzer. It was correct to point out the issue and my attempt to understand the issue was very enlightening for me. We even found and fixed another bug on the fly (695dd3a332fdd54b873fd0d08f9ae720141f24cd).

For that reason I gave credits to you and Sourcebrella in 4a81b8b6e8b908ff70d675c7173ad4923f3dc659 resp. a4a0a1eb43cfccd128d085932a567e0482fbfe47. Looking forward to your next issue reports ;-).

**Comment by wurongxin1987** [comment]
> @wurongxin1987 thank you again for reporting this issue. Although it was finally classified as a non-issue, I would like to emphasize that I do _not_ consider it a false positive of your static analyzer. It was correct to point out the issue and my attempt to understand the issue was very enlightening for me. We even found and fixed another bug on the fly ([695dd3a](https://github.com/openssl/openssl/commit/695dd3a332fdd54b873fd0d08f9ae720141f24cd)).
> 
> For that reason I gave credits to you and Sourcebrella in [4a81b8b](https://github.com/openssl/openssl/commit/4a81b8b6e8b908ff70d675c7173ad4923f3dc659) resp. [a4a0a1e](https://github.com/openssl/openssl/commit/a4a0a1eb43cfccd128d085932a567e0482fbfe47). Looking forward to your next issue reports ;-).

Thanks for your encouraging. We will try to find more issues.

**Comment by bernd-edlinger** [comment]
Actually I don't think this is a false positive.
This test case caues a SEGFAULT when run with OPENSSL_ia32cap=0:
```C
#include <openssl/engine.h>
#include <openssl/evp.h>

int main()
{
  ENGINE *e;
  const EVP_CIPHER * cipher;
  EVP_CIPHER_CTX *ctx;

  OPENSSL_init_crypto(OPENSSL_INIT_ENGINE_DYNAMIC, NULL);
  e = ENGINE_by_id("dasync");
  if (e == NULL)
    return 1;
  ENGINE_init(e);
  cipher = ENGINE_get_cipher(e, NID_aes_128_cbc_hmac_sha1);
  ctx = EVP_CIPHER_CTX_new();
  if (cipher != NULL && ctx != NULL)
    {
       int rv = EVP_EncryptInit_ex(ctx, cipher, e, NULL, NULL);
       printf("EncryptInit=%d\n", rv);
    }
  EVP_CIPHER_CTX_free(ctx);
  ENGINE_finish(e);
  ENGINE_remove(e);
  ENGINE_free(e);
  return 0;
}
```

**Comment by t8m** [comment]
Closing. If this is still an issue with currently supported releases, please open a new issue.
