### ISSUE TITLE
Confuse description in SSL_str_reasons

### ISSUE THREAD

**Issue by KanPlus** [openssl/openssl#7953]
The common error description in SSL and  TLS  was defined begin with sslv3, and SSL3.0 was disable default from the security consider, and the string reason that begin with sslv3 will confuse that sslv3 was still used.

Example:
sslv3 alert bad certificate

Will it better that update to begin with SSL/TLS or remove the sslv3?

**Comment by richsalz** [comment]
The alert is actually defined in the SSLv3 protocol and the later versions use the same alert.

**Comment by MagicC1** [comment]
Yes, define in SSLv3 original, and now these will present even disable SSLv3. :-)

**Comment by richsalz** [comment]
Yes, it is defined in SSLv3 and even tho the protocol is enabled, the alert still has the same name and value with later versions of the protocol.

**Comment by MagicC1** [comment]
This seems result from protocol Inheritance, this will confuse the user which have no deep understanding of the history of SSL and TLS , especially when SSL3.0 was regarding not safe in some scenario. Maybe update to SSL/TLS could be more clear.

**Comment by levitte** [comment]
@richsalz, I will have to contradict you in a way.  There's nothing in any of the alerts that imply a certain version.  Here's a direct quote from the TLSv1.0 RFC (2246):

> ```
> A.3. Alert messages
> 
>     enum { warning(1), fatal(2), (255) } AlertLevel;
> 
>         enum {
>             close_notify(0),
>             unexpected_message(10),
>             bad_record_mac(20),
>             decryption_failed(21),
>             record_overflow(22),
>             decompression_failure(30),
>             handshake_failure(40),
>             bad_certificate(42),
>             unsupported_certificate(43),
>             certificate_revoked(44),
>             certificate_expired(45),
>             certificate_unknown(46),
>             illegal_parameter(47),
>             unknown_ca(48),
>             access_denied(49),
>             decode_error(50),
>             decrypt_error(51),
>             export_restriction(60),
>             protocol_version(70),
>             insufficient_security(71),
>             internal_error(80),
>             user_canceled(90),
>             no_renegotiation(100),
>             (255)
>         } AlertDescription;
> 
>     struct {
>         AlertLevel level;
>         AlertDescription description;
>     } Alert;
> ```

For some reason, *we* have hooked on the originating protocol version onto those messages, but I would agree that it's at least questionable.  There's nothing inherent in those alerts that should make them bound to a particular protocol version.

Now, this is our error messages, i.e. error macros (this particular one is `SSL_R_SSLV3_ALERT_BAD_CERTIFICATE`), and while it may have seemed like a good idea at the time, it doesn't look like such a good idea in retrospect.

A simple solution to the issue is to change the text in `ssl/ssl_err.c`.

**Comment by richsalz** [comment]
You convinced me, @levitte

**Comment by DDvO** [comment]
Closed manually via #17161 - thanks for bringing this up and the discussion here.
