### ISSUE TITLE
Failed to decrypt packet with DTLS 1.0 

### ISSUE THREAD

**Issue by getsoubl** [openssl/openssl#7977]
Hello
I use DTLS 1.0 to decrypt a RTP packet. 
We use opensll 1,0,2

I get the following error
**Failed to decrypt RTP Packet from 192.168.180.16:60438 seq:2049 ssrc:(13285e77) errno:172**
Searchng in the openssl ernno code I found the following I found that the 172 errno matches to CMS_R_MSGSIGDIGEST_ERROR. Is this right?

Do you have any idea why this happens?

George

**Comment by mattcaswell** [comment]
No - that isn't correct. `CMS_R_MSGSIGDIGEST_ERROR` is specific to CMS processing and has nothing to do with DTLS. The error message given above does not seem to come from OpenSSL and the error numbers given do not seem to correlate to OpenSSL errors.

**Comment by getsoubl** [comment]
Hello
This an erno message that is generated when the try to unprotect packages. Is this errno matches to SSL_R_MISSING_TMP_RSA_KEY?
Thank you

**Comment by mattcaswell** [comment]
The number matches but you are unlikely to hit that error unless you are using export grade ciphersuites (which no one should be these days).

**Comment by getsoubl** [comment]
Thank you for the comment
What do you mean with export grade ciphersuites?
How can I check this?

**Comment by getsoubl** [comment]
I   printed the ernno and  the followign description is received
Resource temporarily unavailable

**Comment by mattcaswell** [comment]
> What do you mean with export grade ciphersuites?

These are very old ciphersuites that are low strength - originally introduced due to US crypto export rules. Support for them has been completely removed from OpenSSL 1.1.x but still exists in 1.0.2. It's very unlikely that you would be using them without knowing it because support for them is not built by default. You have to explicitly ask for support to be built at OpenSSL compile team. Even then they aren't included in the default ciphersuites, so you have to configure your application to use them at runtime too.

What component is producing the error message you provided above? That isn't an OpenSSL format error message so it must be coming from somewhere else. You should investigate that component first. So far there is nothing in this issue report that suggests a problem with OpenSSL itself
