### ISSUE TITLE
openssl 1.1.1a array initialization

### ISSUE THREAD

**Issue by YuDudysheva** [openssl/openssl#8005]
In ssl_ciph.c:
static int ssl_mac_pkey_id[SSL_MD_NUM_IDX] = {
    /* MD5, SHA, GOST94, MAC89 */
    EVP_PKEY_HMAC, EVP_PKEY_HMAC, EVP_PKEY_HMAC, NID_undef,
    /* SHA256, SHA384, GOST2012_256, MAC89-12 */
    EVP_PKEY_HMAC, EVP_PKEY_HMAC, EVP_PKEY_HMAC, NID_undef,
    /* GOST2012_512 */
    EVP_PKEY_HMAC,
};

There are 9 out of 12 array numbers initialized, because:

# define SSL_MAX_DIGEST 12

and 

#define SSL_MD_NUM_IDX  SSL_MAX_DIGEST

**Comment by richsalz** [comment]
Why is this an issue?  Three extra int's unused and initialized to zero :)

**Comment by kaduk** [comment]
It sure looks like they're supposed to be ```EVP_PKEY_HMAC``` and were missed in 7afd231275a6841556dd674ac0df471d0b7bcf33.

Most uses in tree don't use this output from ssl_cipher_get_evp() (interestingly, tls13_setup_key_block() fetches it but never uses it), just tls1_setup_key_block().

IIUC, this ends up not actually causing us problems, because the cipher's mac_type is only used for non-AEAD ciphers, and there are no non-AEAD ciphers specified that use SHA224 or SHA512 (actually, no ciphers at all), and the MD5/SHA1 hybrid is only used for signatures and not the symmetric record-protection MAC.

But code cleanliness suggests to add the missing initializers, as I understand it.
