### ISSUE TITLE
Session params output fails via cron for TLS1.3

### ISSUE THREAD

**Issue by neilstuartcraig** [openssl/openssl#8018]
WRT OpenSSL users thread: https://mta.openssl.org/pipermail/openssl-users/2019-January/009595.html

OpenSSL silently fails to output TLS session parameters when run non-interactively (via cron) using TLS1.3 (1.2- work fine). I wrote this up, hopefully correctly, at https://www.thedotproduct.org/posts/openssl-session-parameters-output-fails-when-run-via-cron-for-tls13.html.

tl;dr:
```
/path/to/openssl s_client -connect <server address>:443 -tls1_3 -sess_out /path/to/tls_session_params_file 
```
fails, whereas:
```
/path/to/openssl s_client -connect <server address>:443 -tls1_3 -sess_out /path/to/tls_session_params_file -ign_eof </dev/null
```
works.

AFAIK, the two most pertinent suggestions from the mailing list are:
Matt Caswell:
> My guess is that s_client is closing the connection before the server has had a chance to send its new session tickets. You might want to experiment with the -ign_eof option to s_client. This will keep s_client running even after having hit EOF from stdin.

Jakob Bohm:
> Maybe cron jobs are run without a valid stdin handle (rather than a readable handle at EOF), in which case explicitly adding "</dev/null" may be a fix.

Which i think explain the issue, from what I gather (i'm not an openssl source code expert by any means).

Cheers

**Comment by levitte** [comment]
This should be handled with improved `openssl-s_client` documentation.  After all, this comment is primarily an interactive command, so the lack of a valid stdin *is* surprising for it.

**Comment by levitte** [comment]
Fix PR welcome!

**Comment by erbsland-dev** [comment]
@levitte With PR #25311, I've added a section to the documentation of the `s_client` command, specifically addressing its behavior in non-interactive scenarios.

I was able to reproduce the issue in various non-interactive environments. Notably, it does not require an invalid `stdin`; even an empty input file results in the same behavior. The root cause appears to be that `s_client` processes input and output in an internal loop, but with TLSv1.3, it seems the session data is received delayed. This leads to the loop exiting prematurely, before the session data can be processed.

Relevant code section:
https://github.com/openssl/openssl/blob/6dacee485fad2c4d334e08af48891636205ddb6b/apps/s_client.c#L3270-L3274

Changing this behavior would require special handling of zero-length input, perhaps by enforcing a minimum duration for the internal loop to run before it is allowed to exit, even when no input data is provided. However, since there are already existing workarounds, I believe documenting this somewhat unexpected behavior will help users understand and address the issue more effectively.
