### ISSUE TITLE
ECDSA doesn't work with TLS v1.3

### ISSUE THREAD

**Issue by thangktran** [openssl/openssl#8039]
Hello everyone,

## Info

I built openssl 1.1.1 from source
```bash
ttran@ttran-PCS:~$ openssl version
OpenSSL 1.1.1a  20 Nov 2018
```
generate key and certificate with the following command
```bash
openssl ecparam -name brainpoolP384r1 -genkey -check -out brainpoolP384r1.key
openssl req -new -key brainpoolP384r1.key -x509 -nodes -days 365 -out brainpoolP384r1.crt
```

## Step to reproduce

Run server restricted to tls v1.3 only with -ciphersuites given.
```bash
ttran@ttran-PCS:~$ openssl s_server -key brainpoolP384r1.key -cert brainpoolP384r1.crt -tls1_3 -ciphersuites "TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_AES_128_CCM_SHA256:TLS_AES_128_CCM_8_SHA256"
```
Run client restricted to tlsv1.3 only and with ciphersuites given.
```bash
ttran@ttran-PCS:~/GitRepo/TLSPerformanceTest$ openssl s_client -connect localhost:4433 -tls1_3 -ciphersuites "TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_AES_128_CCM_SHA256:TLS_AES_128_CCM_8_SHA256"
```
## Expected result
Connection established.

## Received result
Run server
```bash
ttran@ttran-PCS:~$ openssl s_server -key brainpoolP384r1.key -cert brainpoolP384r1.crt -tls1_3 -ciphersuites "TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_AES_128_CCM_SHA256:TLS_AES_128_CCM_8_SHA256"
Using default temp DH parameters
ACCEPT
ERROR
140283842814400:error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:ssl/statem/statem_srvr.c:1657:
shutting down SSL
CONNECTION CLOSED
```
Run client
```bash
ttran@ttran-PCS:~$ openssl s_client -connect localhost:4433 -tls1_3 -ciphersuites "TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_AES_128_CCM_SHA256:TLS_AES_128_CCM_8_SHA256"
CONNECTED(00000003)
139941583753664:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:ssl/record/rec_layer_s3.c:1528:SSL alert number 70
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 235 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

---
If you need any further information, please let me know.

Thank you.

**Comment by mattcaswell** [comment]
TLSv1.3 uses the SignatureScheme to determine the algorithm and curve to be used for signing. RFC8446 (TLSv1.3) only specifies a limited set of ECDSA curves to be used. Namely P-256, P-384 and P-521 (see section 4.2.3 of RFC8446). There is no support for brainpool curves.

There is a draft to add additional SignatureSchemes for brainpool:
https://datatracker.ietf.org/doc/draft-bruckert-brainpool-for-tls13/

However this has yet to be approved and there is as yet no support for it in OpenSSL. If you swap the cert you are using to one of the supported curves then it should work. Normally OpenSSL will fallback to TLSv1.2 if it detects it only has a brainpool curve available - but since you have explicitly disabled that protocol version the connection fails.

**Comment by thangktran** [comment]
@mattcaswell Thank you for your fast response. This is indeed the problem.
