### ISSUE TITLE
openssl dll need vcruntime140.dll ?

### ISSUE THREAD

**Issue by liangruxing** [openssl/openssl#8040]
hello.
I run the rsa_test.exe on windows (openssl 1.1.1a), and it is failed and system need vcruntime140.dll
![image](https://user-images.githubusercontent.com/22595929/51294495-290d0080-1a4e-11e9-8310-07fc720660dc.png)

**Comment by kroeckx** [comment]
Please see https://stackoverflow.com/questions/32998902/msvcp140-dll-missing

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.

**Comment by ideafarm** [comment]
This is still a problem.  OpenSSL, when built using Visual Studio, will not run on a "virgin" Windows 10 computer.  As built, it dynamically links to this dll, which is not guaranteed to exist.  I am opening a new issue to bring this back to life so that we can discuss whether to change the tree so that static linking is used for this dll.
