### ISSUE TITLE
Early Data not allowed with EPSKs (Openssl 1.1.1a)?

### ISSUE THREAD

**Issue by karlmhenderson** [openssl/openssl#8046]
RFC 8446, page 17, section 2.3, paragraph 1 says:
```
When clients and servers share a PSK (either obtained externally or via a previous handshake), TLS 1.3 allows clients to send data on the first flight ("early data").
```
However, man page for SSL_write_early_data says:
```
Early data can only be sent if a session has previously been established with the server, and the server is known to support it.
```
Furthermore, the code appears to support the man page text - ssl/ssl_lib.c, function SSL_write_early_data:
```
int SSL_write_early_data(SSL *s, const void *buf, size_t num, size_t *written)
{
    int ret, early_data_state;
    size_t writtmp;
    uint32_t partialwrite;

    switch (s->early_data_state) {
    case SSL_EARLY_DATA_NONE:
        if (s->server
                || !SSL_in_before(s)
                || ((s->session == NULL || s->session->ext.max_early_data == 0)
                     && (s->psk_use_session_cb == NULL))) {
            SSLerr(SSL_F_SSL_WRITE_EARLY_DATA,
                   ERR_R_SHOULD_NOT_HAVE_BEEN_CALLED);
            return 0;
        }
```
I'd like to send early data with EPSKs - is this a bug or am I missing something?

**Comment by mattcaswell** [comment]
Probably the man page text is a little misleading. It is not intended to preclude the use of PSKs. However in order to use early data with a PSK then you must use the new TLSv1.3 PSK API functions (and not the old ones present in 1.1.0 and earlier), i.e. you need to use `SSL_CTX_set_psk_use_session_callback` or `SSL_set_psk_use_session_callback`. Note this sentence on the man page for those functions:

````
Additionally the maximum early data value should be set via a call to
L<SSL_SESSION_set_max_early_data(3)> if the PSK will be used for sending early
data.
````

Similarly the server will need to be configured to allow early data for that PSK. If the server is OpenSSL then that will mean using `SSL_CTX_set_psk_find_session_callback` or `SSL_set_psk_find_session_callback` and ensuring the `max_early_data` value has been set.

**Comment by karlmhenderson** [comment]
Thanks - I was indeed using the old SSL_set_psk_client_callback function.
