### ISSUE TITLE
TLS 1.3 post-handshake messages trigger SSL_CB_HANDSHAKE_START

### ISSUE THREAD

**Issue by agl** [openssl/openssl#8069]
Several applications (including, at least, NGINX and HAProxy) blocked renegotiation by using the info callback and watching for `SSL_CB_HANDSHAKE_START` messages after the handshake was completed.

However, with OpenSSL 1.1.1, post-handshake messages such as KeyUpdate also trigger that event meaning that these applications interpret a TLS 1.3 KeyUpdate as a TLS 1.2 (or lower) renegotiation and drop the connection.

NGINX fixed this [here](https://trac.nginx.org/nginx/changeset/e3ba4026c02d2c1810fd6f2cecf499fc39dde5ee/nginx/src/event/ngx_event_openssl.c) and HAProxy will likely do something similar soon. Eyeballing Node.js, it appears to trigger callbacks into the Javascript code when `SSL_CB_HANDSHAKE_START` is seen.

Thus, given the prevalence of this pattern, and the fact that `SSL_CB_HANDSHAKE_START` does not make inherent sense for things like KeyUpdate, it might be better if OpenSSL triggered a different event for TLS 1.3 post-handshake messages.

**Comment by sam-github** [comment]
Yes, its a big deal for Node.js, I'm in the midst of some fairly horrendous and not yet sucessful refactors in attempt to work around this. See https://github.com/openssl/openssl/issues/7199 for more info.

**Comment by sam-github** [comment]
I'm not an OMC member, so I'm posting this email here. /to @vdukhovni @agl 

On Tue, Jan 22, 2019 at 11:48 AM Viktor Dukhovni
<openssl-users@dukhovni.org> wrote:
> As for applications mishandling "SSL_CB_HANDSHAKE_START", not quite sure
> what to do there, but perhaps we could define a new even for keyUpdates
> that does not mislead applications into assuming a new "handshake".

I would love that. It would clear the biggest and last remaining
obstacle for TLS1.3 in Node.js.

I thought Node.js was the only one using/abusing
SSL_CB_HANDSHAKE_START and SSL_CB_HANDSHAKE_DONE, but if it is not,
making them clearly indicate when handshakes start and stop,
particularly with "transparent" handshakes, starts to make sense.

Also, OpenSSL has no API to detect renegotiation, other than these
info callbacks, so its not possible to replace them with other APIs
(though only TLS1.2 supports SSL_renegotiate). Maybe formalizing that
the info callbacks are supported for this purpose would make sense.

Another difficulty lies around assumptions in our unit tests about
when handshake is complete on server vs client, which I belive to be
related to the above. With 1.3, client handshake is done before the
tickets arrive (this is reasonable), but on the server, its not done
until the tickets are sent, so client will complete the handshake
before  the client, and in TLS1.2 it was the opposite. I believe this
to be a bug in our tests since they are assuming something about
inter-process ordering that is not guaranteed, but it breaks lots of
tests, and I've had to go through and fix them.

The remaining notable issue is that we aren't using the
SSL_CTX_sess_set_new_cb on the client side ATM, and are instead
assuming the session is available after handshake. This isn't a
blocker. I plan to add a new CB-based session/ticket API for the
client side, and it will work both for TLS1.2 and TLS1.3, with the
legacy API working only for TLS1.2.

There are a few other TLS1.3 specific APIs that need adding, but they
too are not blockers. The info callbacks are the real obstacle.

Is there a time estimate for 1.1.1b?

@davidben 
> Prior to SSL_OP_NO_RENEGOTIATION (new in the same release that added 1.3), this was the only way to disable renegotiations. I've seen a lot of codebases do this.

Node.js uses the API that way, both to disable, and also to check how long a renegotiation is taking, and destroy the connection if its an unreasonable amount of time (to prevent renegotiation DoS).

**Comment by sam-github** [comment]
I did post, and got bounced with

> Only OMC members and committers may post directly to this list.

Are you sure moderation is enabled?  That seemed pretty definite.

I don't see my message in the thread: https://mta.openssl.org/pipermail/openssl-project/2019-January/thread.html#1204, perhaps its still awaiting moderation.

**Comment by mattcaswell** [comment]
Oops. I just checked the configuration and apparently it was configured to reject non OMC/committer posts. Both I and @levitte (the other sys admin) both thought those posts were supposed to be being held for moderation, so I updated the config. Hopefully it should work now.

**Comment by mattcaswell** [comment]
(You'll have to resend anything you want to post to that list)

**Comment by mattcaswell** [comment]
Fix in #8096
