### ISSUE TITLE
OpenSSL can't read PKCS12 files it creates with -nomac

### ISSUE THREAD

**Issue by jack-fortanix** [openssl/openssl#8106]
Passing the `-nomac` option to `pkcs12` seems to result in PKCS12 files that `pkcs12` itself cannot parse. First seen with OpenSSL 1.1.0g reconfirmed with latest master:

```
$ openssl version -a
OpenSSL 3.0.0-dev xx XXX xxxx
built on: Mon Jan 28 21:20:17 2019 UTC
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DNDEBUG
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/lib/engines-"
Seeding source: os-specific
$ openssl pkcs12 -export -inkey rsa.key -in rsa.crt  -name Bongo -nomac -out nomac.pfx -passin pass:xyzzy -passout pass:xyzzy
$ openssl pkcs12 -in nomac.pfx  -passin pass:xyzzy
Mac verify error: invalid password?
139663882801600:error:2307E06C:PKCS12 routines:PKCS12_verify_mac:mac absent:crypto/pkcs12/p12_mutl.c:157:
139663882801600:error:2307E06C:PKCS12 routines:PKCS12_verify_mac:mac absent:crypto/pkcs12/p12_mutl.c:157:
```

I don't think this is a problem with my usage as if you replace `-nomac` with `-nomaciter` everything works.

I also tried passing `-nomac` to the reader `pkcs12` but that seems to make no difference.

**Comment by mattcaswell** [comment]
This looks to me like correct behaviour. The pkcs12 application will always by default attempt to verify the MAC on the incoming file. It will also always by default create files with MACs. Since you've explicitly asked it to create a file without a MAC, it complains when you try to read it again. As mentioned in the man page there is an option to skip mac verification when reading in the file, i.e. `-nomacver`. I just tried your commands and adding that option to the second one made it work.

Note: `-nomaciter` is not the same thing as `-nomac`. In the former case a MAC is still generated (but with reduced security). In the latter case there is no MAC at all.

**Comment by jack-fortanix** [comment]
"Mac verify error: invalid password?" is a funny way to say "there is no MAC"

**Comment by mattcaswell** [comment]
The pkcs12 app just knows the mac verification failed (which it did). 99% of the time that's because of an invalid password. The detailed error below (which comes out of libcrypto) gives the further hint: "mac absent".

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
