### ISSUE TITLE
A potential NPD bug

### ISSUE THREAD

**Issue by wurongxin1987** [openssl/openssl#8110]
The source file s3_cbc.c may include NPD bug. 
![image](https://user-images.githubusercontent.com/4220002/51905595-97fa3a00-23fc-11e9-8e6b-83d21fb9a45b.png)

In Line 498, the macro EVP_MD_CTX_block_size can be expanded as following:
![image](https://user-images.githubusercontent.com/4220002/51905637-b3654500-23fc-11e9-8237-b1dc233987ec.png)

The function call to **EVP_MD_CTX_md** may be return NULL as followings. 

![image](https://user-images.githubusercontent.com/4220002/51905655-c11aca80-23fc-11e9-8887-2e77154bca86.png)

After that, if this return value is as the parameter of the function **EVP_MD_block_size**, it will dereference NULL pointer. 
![image](https://user-images.githubusercontent.com/4220002/51905719-f3c4c300-23fc-11e9-8d59-ff509e419169.png)

There is a similar bug in the same file. 

![image](https://user-images.githubusercontent.com/4220002/51905752-1656dc00-23fd-11e9-9a5c-bab290903e2e.png)

In Line 94, the macro definition EVP_MD_CTX_type(ctx) can be expanded as followings:
![image](https://user-images.githubusercontent.com/4220002/51905791-2e2e6000-23fd-11e9-9795-db9a72accb6e.png)
![image](https://user-images.githubusercontent.com/4220002/51905803-37b7c800-23fd-11e9-81f0-741d996d4150.png)
![image](https://user-images.githubusercontent.com/4220002/51905815-40a89980-23fd-11e9-9ed6-b2e6c58e6059.png)

Similarly, it may cause a NPD bug. 

Would you help to confirm whether this is possible? Thanks very much.

**Comment by mattcaswell** [comment]
You don't say what version of OpenSSL you are looking at, but I assume it is 1.0.2 since some of this code does not exist in later versions (or it exists in different places). I'd point out that 1.0.2 is in security-fix only mode at the moment so only security issues will be fixed.

Note that these uses are in entirely internal functions. A function like EVP_MD_CTX_md() will only return NULL if ctx is NULL or if ctx->digest is NULL. If either of those things were the case then it would be the result of a bug in earlier code. In these functions we assume that the ctx has been set up correctly. You could argue that an assert might be appropriate to confirm it - but it is certainly not required and wouldn't be classed as a bug if asserts are absent. In any case it is generally not the style in OpenSSL to use extensive NULL checking in all functions in cases where we never expect the input to be NULL. In that spirit I would not classify your findings as a bug. If you could force a situation where an actual NULL deref actually occurred in a real scenario then *that* would be an issue.

**Comment by wurongxin1987** [comment]
> You don't say what version of OpenSSL you are looking at, but I assume it is 1.0.2 since some of this code does not exist in later versions (or it exists in different places). I'd point out that 1.0.2 is in security-fix only mode at the moment so only security issues will be fixed.
> 
> Note that these uses are in entirely internal functions. A function like EVP_MD_CTX_md() will only return NULL if ctx is NULL or if ctx->digest is NULL. If either of those things were the case then it would be the result of a bug in earlier code. In these functions we assume that the ctx has been set up correctly. You could argue that an assert might be appropriate to confirm it - but it is certainly not required and wouldn't be classed as a bug if asserts are absent. In any case it is generally not the style in OpenSSL to use extensive NULL checking in all functions in cases where we never expect the input to be NULL. In that spirit I would not classify your findings as a bug. If you could force a situation where an actual NULL deref actually occurred in a real scenario then _that_ would be an issue.

The version I looked at is 1.1.0, which is the default version in Ubuntu 18.04. I understood that, it would be not a bug if the parameter ctx is never to be NULL. However, I consider that, this piece of code is in a macro definition, and anyone who used this may not realise the assumption about ctx. Moreover, **EVP_MD_CTX_md** will check ctx is a Null pointer or not, and it seems you realised that it is likely to be NULL at the time of using **EVP_MD_CTX_md**. If ** EVP_MD_block_size** will not check it, it sounds like a little bit dangerous in the future.  Why not add a Null check in ** EVP_MD_block_size** and **EVP_MD_type&** to play safe?
