### ISSUE TITLE
coredump in SSL_dup

### ISSUE THREAD

**Issue by HeYoushang** [openssl/openssl#8138]
We got a coredump issue when using SSL_dup, the test code is primarily as follows:
`ctx = SSL_CTX_new(TLS_client_method());`
`ssl = SSL_new(ctx);`
`tcp connect...`
`SSL_set_fd(ssl, fd);`
`ssl_dup = SSL_dup(ssl);`
all the previous operations are ok, but we got :
![image](https://user-images.githubusercontent.com/46014603/52111624-26f69480-263f-11e9-951a-b0d361b65f14.png)
the input of BIO_up_ref is a NULL pointer, corresponding code is , 
https://github.com/openssl/openssl/blob/a28e4890eed847e6122a1c4d50653566e0813f45/ssl/ssl_lib.c#L3841
now s->rbio and s->wbio are the same and not NULL (set by SSL_set_fd). and the following code tries to duplicate rbio from s->rbio, but we find that `BIO_dup_state` does nothing for option `BIO_CTRL_DUP`, 
https://github.com/openssl/openssl/blob/a28e4890eed847e6122a1c4d50653566e0813f45/ssl/ssl_lib.c#L3833
https://github.com/openssl/openssl/blob/a28e4890eed847e6122a1c4d50653566e0813f45/crypto/bio/bss_sock.c#L175
so ret->rbio keeps NULL, causing Segmentation fault when passed to BIO_up_ref.

**Comment by mattcaswell** [comment]
Congratulations! AFAICT you seem to have run into a bug that is over 20 years old and predates OpenSSL itself (it comes from its predecessor SSLeay)! It amazes me that no one has encountered and fixed this before now.

It looks to me like you only run into this bug if you attempt an `SSL_dup()` on an SSL object that hasn't yet been used to attempt a connection, but *after* the BIOs have been set.

`BIO_dup_state` is supposed to duplicate the state from one BIO object to another. However it assumes that the destination BIO has already been created. Looking at the `SSL_dup` code it doesn't attempt to create new BIOs at all! It just goes straight into `BIO_dup_state()` - which as you note is unimplemented for a socket BIO. If it had been implemented it probably would have crashed there since the destination BIO is NULL at this point.

I guess the fix would be to just use BIO_up_ref instead and copy the BIO pointers in the source SSL to the destination SSL directly without calling `BIO_dup_state()` at all.

**Comment by mattcaswell** [comment]
Fix in #8161

**Comment by nhorman** [comment]
Issue seems fixed
