### ISSUE TITLE
Using SSL with embedded systems with limited RAM and Flash ROM

### ISSUE THREAD

**Issue by dodge55** [openssl/openssl#8179]
Not sure where to post this, but:

I've been given the task of researching how to send a 'secure' email using SSL on an embedded system with very limited RAM and Flash ROM.  The email is very vague in nature, so security is not really needed at all.  We have it working great with a non secured port (like 25 or 26).  So, I've been asked to investigate if this is possible on our system.  Many servers are not allowing unsecured port emails any longer, which has led me to this research.

There are several 3rd party vendors that offer SSL libraries, but the code space and RAM required is much larger than we can handle.  Their code handles the multitude of cipher suites, which we don't necessarily need, and probably a lot of other stuff that we don't need either.

I don't know how minimal you can get as far as what is needed to send a 'secure email'.  So, my initial questions are:

1.  Do you have to use any ciphers at all and do you have to receive certificates whether you validate them or not.
2.  If you do have to use a cipher, is there a universal cipher that all servers must support?
3.  How do you know which ciphers require minimum overhead?
4.  Are there mechanisms to tell the server to use a secure port (like 587), but I don't need all the security overhead?  Or does that defeat the purpose and ciphers are just needed?

Any other feedback would be appreciated, as I'm sure there are other factors I may need to consider.

Thanks.

**Comment by mattcaswell** [comment]
This question is off-topic because it isn't specific to OpenSSL. Perhaps information security stack exchange might be a better forum:

https://security.stackexchange.com/

I'll attempt to answer the questions as best I can anyway:

> Do you have to use any ciphers at all and do you have to receive certificates whether you validate them or not.

You always need to use a ciphersuite. NULL encryption cipheruites do exist which only provide integrity checking on application data - not privacy. However both the client and server need to support them - and they are not widely supported.

It is possible to use Pre Shared Keys (PSKs) instead of using certificates - but both the client and server need to be configured to use them. Otherwise you will always receive a certificate from the server.

> If you do have to use a cipher, is there a universal cipher that all servers must support?

No. The supported ciphersuites may vary by protocol version too. Up until TLSv1.2 ciphersuites were forward compatible, e.g. ciphersuites defined in TLSv1.0 still work in TLSv1.2. However the opposite is not always true. For example there are TLSv1.2 ciphersuites that only work in TLSv1.2. TLSv1.3 is completely different. TLSv1.3 ciphersuites do not work in TLSv1.2 or below, and ciphersuites for TLSv1.2 and below do not work in TLSv1.3.

> How do you know which ciphers require minimum overhead?

A ciphersuite is comprised of multiple components, e.g. the encryption cipher, the authentication mechanism in use, the mac etc. You'd need to analyse each individual component and consider the overhead of each one. Obviously this could also vary by implementation depending on how efficiently it has been coded.

> Are there mechanisms to tell the server to use a secure port (like 587), but I don't need all the security overhead?  Or does that defeat the purpose and ciphers are just needed?

Once you start the TLS protocol the only control you have is what parameters are negotiated (e.g. ciphersuites etc) as discussed above. Whether you enter TLS at all would be specific to the application protocol you use.
