### ISSUE TITLE
req (default_)days not working from config file (self Signing)

### ISSUE THREAD

**Issue by MasterJames** [openssl/openssl#8245]
Well it seems currently on Ubuntu Server this is the current version of openssl
OpenSSL 1.1.0g  2 Nov 2017

With this version calling openssl req -x509 -new -config etc... with a config file fails to pick up and use the 'default_days' property/value, (same with 'days' it does nothing in the config file but makes sense it should).
[I tried using the ca_default syntax, no spaces, moved the value to the top of the list etc. it simply will not override a default of 30 days.]

Yes you can from the command line add '-days ####' to get it to generate a self signing CA

This problem I've seem reported way back in 2006 so it seems from my perspective it has not worked in over a decade if ever.

This is with a self signed CA. Maybe I'm missing something or it's fixed in 1.1.1?

Maybe you need a different config with 'req' section. It's not clear. Maybe explain if I've become confused, thanks.

**Comment by kaduk** [comment]
Basically, this is because the ca(1) app is the only one that reads that part of the config file.  (It's the only one documented to do so, too, not that the lack of documentation is a historically reliable indicator.)

Unfortunately, this gets into the unholy mess of the various apps, overlap of functionality, and non-modular design, so making any changes in this space is pretty messy and prone to bugs.  It's occasionally tempting to freeze the existing stuff for "bug-for-bug compatibility" and move to new tools for  future-looking functionality, but it's unclear how realistic that would be.

**Comment by MasterJames** [comment]
Thanks for your comments it does seem maybe some rethinking is needed there then.

**Comment by levitte** [comment]
General comment, not specifically tied to this issue: the config file is really messy, and the relationship between different sections isn't at all intuitively clear.  We may have to investigate a different format that would group things together in a better manner.  I'm partial to YAML, but others may have other ideas.  Perhaps we should create an issue regarding future config file formats?

**Comment by mattcaswell** [comment]
Looks like no further work will be done on this specific issue. Marked as "answered" and scheduling for later closure.
