### ISSUE TITLE
AES_cbc_encrypt with AES_ENCRYPT output wrong encrypted string in g++ -m32 with asm

### ISSUE THREAD

**Issue by vaynezhang** [openssl/openssl#8374]
There is a compatibility issue with  g++ -m32 in linux x86_64 with openssl>=1.0.0，0.9.8zh or  g++ -m64  is correct.

if openssl compiled with: setarch i386 ./config -m32 no-asm, there is no problem. 

if openssl compiled with: setarch i386 ./config -m32, the encrypted string can't correct decrypt .

wrong result:
gcc:4.1.2 compiled:Mar  1 2019 00:41:28

test:this is test string
urlencode:this+is+test+string
HEX=746869732B69732B746573742B737472696E67

AES_cbc_encrypt AES_ENCRYPT:
HEX=E8FFBB2BA2144162430EA6D0962672C9BD65F7

base64encode:6P+7K6IUQWJDDqbQliZyyb1l96QF1K0nbFMPMCkRlBQ=

AES_cbc_encrypt AES_DECRYPT:
HEX=746869732B69732B746573742B7374728091DC2BA2144162430EA6D0962672C9

decrypt:this is test str€戃 �AbCπ�&r�

right result:
gcc:4.1.2 compiled:Mar  1 2019 01:03:19

test:this is test string
urlencode:this+is+test+string
HEX=746869732B69732B746573742B737472696E67

AES_cbc_encrypt AES_ENCRYPT:
HEX=E8FFBB2BA2144162430EA6D0962672C945AC62

base64encode:6P+7K6IUQWJDDqbQliZyyUWsYu4xBE8ZsxzGoDm4aas=

AES_cbc_encrypt AES_DECRYPT:
HEX=746869732B69732B746573742B737472696E6700000000000000000000000000

decrypt:this is test string

I guess the problem is in the openssl-1.1.1a\crypto\aes\asm\aes-586.pl

**Comment by vaynezhang** [comment]
int main(int argc, char* argv[])
{
    show_banner();
    string test = "this is test string";
    cout<<"test:"<<test<<endl;

    string urlenc = url_encode(test.c_str());
    cout<<"urlencode:"<<urlenc<<endl;
    string enc = get_encode(urlenc);
    cout<<endl<<"base64encode:"<<enc<<endl;
    urlenc = get_decode(enc);
    string dec = url_decode(urlenc);
    cout<<endl<<"decrypt:"<<dec<<endl;

    return 0;
}

**Comment by mattcaswell** [comment]
AES_cbc_encrypt() is a very low-level function that operates on complete AES blocks in one go (i.e. multiples of 16 bytes). It's not exactly clear from your description what you are passing to that function but if it is the 19 bytes of "this is a test string" (20 including the NUL terminator) then you are going to get undefined and strange results since this is not a multiple of 16. This seems likely because the corrupted string that you are seeing has 16 bytes of correctly decrypted data (corresponding to a full AES block), and only then does it go wrong.

You really should avoid calling  AES_cbc_encrypt() directly. You are supposed to use the EVP_Encrypt*() functions instead:

https://www.openssl.org/docs/man1.1.1/man3/EVP_EncryptInit.html

**Comment by vaynezhang** [comment]
> AES_cbc_encrypt() is a very low-level function that operates on complete AES blocks in one go (i.e. multiples of 16 bytes). It's not exactly clear from your description what you are passing to that function but if it is the 19 bytes of "this is a test string" (20 including the NUL terminator) then you are going to get undefined and strange results since this is not a multiple of 16. This seems likely because the corrupted string that you are seeing has 16 bytes of correctly decrypted data (corresponding to a full AES block), and only then does it go wrong.
> 
> You really should avoid calling AES_cbc_encrypt() directly. You are supposed to use the EVP_Encrypt*() functions instead:
> 
> https://www.openssl.org/docs/man1.1.1/man3/EVP_EncryptInit.html

Thanks for reply, you can test it use these codes.

#include <map>
#include <string>
#include <vector>
#include <iostream>
#include <algorithm>
#include <sstream>

#include <openssl/des.h>
#include <openssl/aes.h>
#include <openssl/md5.h>

#include <cstring>

using namespace std;

static void show_banner()
{
    cout<<"gcc:"<<__GNUC__<<"."<<__GNUC_MINOR__<<"."<<__GNUC_PATCHLEVEL__<<" compiled:"<<__DATE__<<" "<<__TIME__<<endl<<endl;
}

static string m_jobs_appid = "ba1f2511fc30423bdbb183fe33f3dd0f";
static string m_jobs_appkey = "ThisIsTest";

static inline unsigned char tohex(unsigned char x)
{ 
    return  x > 9 ? x + 55 : x + 48; 
}

static inline unsigned char fromhex(unsigned char x) 
{ 
    unsigned char y = 0x00;
    if (x >= 'A' && x <= 'Z') y = x - 'A' + 10;
    else if (x >= 'a' && x <= 'z') y = x - 'a' + 10;
    else if (x >= '0' && x <= '9') y = x - '0';
    return y;
}

static inline string url_encode(const string& src_str)
{
    string str_dst = "";
    size_t length = src_str.length();
    for (size_t i = 0; i < length; i++)
    {
        if (isalnum((unsigned char)src_str[i]) || 
            (src_str[i] == '-') ||
            (src_str[i] == '_') || 
            (src_str[i] == '.') || 
            (src_str[i] == '~'))
        {
            str_dst += src_str[i];
        }
        else if (src_str[i] == ' ')
        {
            str_dst += "+";
        }
        else
        {
            str_dst += '%';
            str_dst += tohex((unsigned char)src_str[i] >> 4);
            str_dst += tohex((unsigned char)src_str[i] % 16);
        }
    }
    return str_dst;
}

static inline string url_decode(const string& str)
{
    string str_dst = "";
    size_t length = str.length();
    for (size_t i = 0; i < length; i++)
    {
        if (str[i] == '+')
        {
            str_dst += ' ';
        }
        else if (str[i] == '%')
        {
            unsigned char high = fromhex((unsigned char)str[++i]);
            unsigned char low = fromhex((unsigned char)str[++i]);
            str_dst += high*16 + low;
        }
        else
        {
            str_dst += str[i];
        }
    }
    return str_dst;
}

static const std::string base64_chars =  
         "ABCDEFGHIJKLMNOPQRSTUVWXYZ"  
         "abcdefghijklmnopqrstuvwxyz"  
         "0123456789+/";

static inline string base64_encode(const unsigned char *src_str, unsigned int in_len)
{
    std::string ret;
    int i = 0;
    int j = 0;
    unsigned char char_array_3[3];
    unsigned char char_array_4[4];

    while (in_len--) {
        char_array_3[i++] = *(src_str++);
        if (i == 3) {
            char_array_4[0] = (char_array_3[0] & 0xfc) >> 2;
            char_array_4[1] = ((char_array_3[0] & 0x03) << 4) + ((char_array_3[1] & 0xf0) >> 4);
            char_array_4[2] = ((char_array_3[1] & 0x0f) << 2) + ((char_array_3[2] & 0xc0) >> 6);
            char_array_4[3] = char_array_3[2] & 0x3f;

            for(i = 0; (i <4) ; i++)
                ret += base64_chars[char_array_4[i]];
            i = 0;
        }
    }

    if (i)
    {
        for(j = i; j < 3; j++)
            char_array_3[j] = '\0';

        char_array_4[0] = (char_array_3[0] & 0xfc) >> 2;
        char_array_4[1] = ((char_array_3[0] & 0x03) << 4) + ((char_array_3[1] & 0xf0) >> 4);
        char_array_4[2] = ((char_array_3[1] & 0x0f) << 2) + ((char_array_3[2] & 0xc0) >> 6);
        char_array_4[3] = char_array_3[2] & 0x3f;

        for (j = 0; (j < i + 1); j++)
        ret += base64_chars[char_array_4[j]];

        while((i++ < 3))
            ret += '=';
    }

    return ret;
}

static inline bool is_base64(unsigned char c)
{  
    return (isalnum(c) || (c == '+') || (c == '/'));  
}

static inline string base64_decode(const unsigned char *src_str, unsigned int in_len, int &out_len)
{
    int i = 0;
    int j = 0;
    int in_ = 0;
    unsigned char char_array_4[4], char_array_3[3];
    std::vector<unsigned char> vecchar;
  
    while (in_len-- && ( src_str[in_] != '=') && is_base64(src_str[in_])) {
        char_array_4[i++] = src_str[in_]; in_++;
        if (i ==4) {
            for (i = 0; i <4; i++)
                char_array_4[i] = base64_chars.find(char_array_4[i]);
      
            char_array_3[0] = (char_array_4[0] << 2) + ((char_array_4[1] & 0x30) >> 4);
            char_array_3[1] = ((char_array_4[1] & 0xf) << 4) + ((char_array_4[2] & 0x3c) >> 2);
            char_array_3[2] = ((char_array_4[2] & 0x3) << 6) + char_array_4[3];
      
            for (i = 0; (i < 3); i++)
                vecchar.push_back(char_array_3[i]);
            i = 0;
        }
    }
  
    if (i) {
        for (j = i; j <4; j++)
            char_array_4[j] = 0;
  
        for (j = 0; j <4; j++)
            char_array_4[j] = base64_chars.find(char_array_4[j]);
  
        char_array_3[0] = (char_array_4[0] << 2) + ((char_array_4[1] & 0x30) >> 4);
        char_array_3[1] = ((char_array_4[1] & 0xf) << 4) + ((char_array_4[2] & 0x3c) >> 2);
        char_array_3[2] = ((char_array_4[2] & 0x3) << 6) + char_array_4[3];
  
        for (j = 0; (j < i - 1); j++)
        {
            vecchar.push_back(char_array_3[j]);
        }
    }

    out_len = vecchar.size();
    std::string ret(vecchar.begin(), vecchar.end());
    return ret;
}

static inline  void AES_cbc_encrypt1(const unsigned char *in, unsigned char *out,
     const unsigned long length, const AES_KEY *key,
     unsigned char *ivec, const int enc) {

    unsigned long n;
    unsigned long len = length;
    const unsigned char *iv = ivec;

    while (len >= 16) {
        for(n=0; n < 16; ++n)
            out[n] = in[n] ^ iv[n];
        AES_encrypt(out, out, key);
        iv = out;
        len -= 16;
        in += 16;
        out += 16;
    }

    if (len) {
        for(n=0; n < len; ++n)
            out[n] = in[n] ^ iv[n];
        for(n=len; n < 16; ++n)
            out[n] = iv[n];
        AES_encrypt(out, out, key);
        iv = out;
    }
    memcpy(ivec,iv,16);
}

static inline  void AES_cbc_encrypt2(const unsigned char *in, unsigned char *out,
     size_t len, const AES_KEY *key,
     unsigned char ivec[16], const int enc) {

    size_t n;
    const unsigned char *iv = ivec;

    while (len >= 16) {
        for (n = 0; n < 16; n += sizeof(size_t))
            *(size_t *)(out + n) =
                *(size_t *)(in + n) ^ *(size_t *)(iv + n);
        AES_encrypt(out, out, key);
        iv = out;
        len -= 16;
        in += 16;
        out += 16;
    }

    while (len) {
        for (n = 0; n < 16 && n < len; ++n)
            out[n] = in[n] ^ iv[n];
        for (; n < 16; ++n)
            out[n] = iv[n];
        AES_encrypt(out, out, key);
        iv = out;
        if (len <= 16)
            break;
        len -= 16;
        in += 16;
        out += 16;
    }
    memcpy(ivec,iv,16);
}

static inline  void AES_cbc_encrypt3(const unsigned char *in, unsigned char *out,
     size_t len, const AES_KEY *key,
     unsigned char ivec[16], const int enc) {

    size_t n;
    const unsigned char *iv = ivec;

    while (len >= 16) {
        for (n = 0; n < 16; ++n)
            out[n] = in[n] ^ iv[n];
        AES_encrypt(out, out, key);
        iv = out;
        len -= 16;
        in += 16;
        out += 16;
    }

    while (len) {
        for (n = 0; n < 16 && n < len; ++n)
            out[n] = in[n] ^ iv[n];
        for (; n < 16; ++n)
            out[n] = iv[n];
        AES_encrypt(out, out, key);
        iv = out;
        if (len <= 16)
            break;
        len -= 16;
        in += 16;
        out += 16;
    }
    memcpy(ivec,iv,16);
}

static inline string aes_encode(const char *src_str, char *key)
{
    int len = strlen(src_str);
    printf("HEX=");
    for (int i = 0; i < len; i++)
    {
        printf("%02X", src_str[i]);
    }
    printf("\n");
    unsigned char iv[16] = {1};
    AES_KEY aes;
    if (AES_set_encrypt_key((unsigned char*)key, 128, &aes) < 0) return "";

    unsigned char dst_str[100*1024] = {0};
    AES_cbc_encrypt((unsigned char *)src_str, dst_str, len, &aes, iv, AES_ENCRYPT);
    printf("\nAES_cbc_encrypt AES_ENCRYPT:\n");
	printf("HEX=");
    for (int i = 0; i < len; i++)
    {
        printf("%02X", dst_str[i]);
    }
    printf("\n");
    unsigned int size = (len%16 == 0) ? len : (len + 16 - (len%16));

    return base64_encode(dst_str, size);
}

static inline string aes_decode(const char *src_str, char *key)
{
    int len = 0;
    unsigned char iv[16] = {1};

    std::string dec_str = base64_decode((unsigned char*)src_str, strlen(src_str), len);

    AES_KEY aes;
    if (AES_set_decrypt_key((unsigned char*)key, 128, &aes) < 0) return "";

    unsigned char dst_str[100*1024] = {0};
    AES_cbc_encrypt((unsigned char *)dec_str.c_str(), dst_str, len, &aes, iv, AES_DECRYPT);
    printf("\nAES_cbc_encrypt AES_DECRYPT:\n");
	printf("HEX=");
    for (int i = 0; i < len; i++)
    {
        printf("%02X", dst_str[i]);
    }
    printf("\n");
    std::string ret((char *)dst_str);
    return ret;
}

static inline string get_decode(const string src_str)
{
    char szkey[64] = {0};

    snprintf(szkey, sizeof(szkey), "%s%s", m_jobs_appid.c_str(), m_jobs_appkey.c_str());

    MD5_CTX ctx;
    unsigned char digest[16] = {1};

    MD5_Init(&ctx); 
    MD5_Update(&ctx, szkey, strlen(szkey));
    MD5_Final (digest, &ctx);

    string dec_str = aes_decode(src_str.c_str(), (char *)digest);

    return dec_str;
}

static inline string get_encode(const string src_str)
{
    char szkey[64] = {0};

    snprintf(szkey, sizeof(szkey), "%s%s", m_jobs_appid.c_str(), m_jobs_appkey.c_str());

    MD5_CTX ctx;
    unsigned char digest[16] = {1};

    MD5_Init(&ctx); 
    MD5_Update(&ctx, szkey, strlen(szkey));
    MD5_Final (digest, &ctx);

    string dec_str = aes_encode(src_str.c_str(), (char *)digest);
    return dec_str;
}

int main(int argc, char* argv[])
{
    show_banner();
    string test = "this is test string";
    cout<<"test:"<<test<<endl;

    string urlenc = url_encode(test.c_str());
    cout<<"urlencode:"<<urlenc<<endl;
    string enc = get_encode(urlenc);
    cout<<endl<<"base64encode:"<<enc<<endl;
    urlenc = get_decode(enc);
    string dec = url_decode(urlenc);
    cout<<endl<<"decrypt:"<<dec<<endl;

    return 0;
}

**Comment by mattcaswell** [comment]
This code confirms the issue as I described above. You are not correctly using the AES_cbc_encrypt() function. You are taking the original string and URL encoding it to "this+is+test+string". Then you use strlen to find its length (19 bytes). This is the length that you pass to AES_cbc_encrypt(). That function only accepts multiples of 16 bytes for the length. Since 19 is not a multiple of 16 it fails to encrypt/decrypt correctly.

The answer is: do not use that function at all! This is a very low level function and not intended for this kind of use. Use the EVP_Encrypt* functions instead:

https://www.openssl.org/docs/man1.1.1/man3/EVP_EncryptInit_ex.html

**Comment by vaynezhang** [comment]
> This code confirms the issue as I described above. You are not correctly using the AES_cbc_encrypt() function. You are taking the original string and URL encoding it to "this+is+test+string". Then you use strlen to find its length (19 bytes). This is the length that you pass to AES_cbc_encrypt(). That function only accepts multiples of 16 bytes for the length. Since 19 is not a multiple of 16 it fails to encrypt/decrypt correctly.
> 
> The answer is: do not use that function at all! This is a very low level function and not intended for this kind of use. Use the EVP_Encrypt* functions instead:
> 
> https://www.openssl.org/docs/man1.1.1/man3/EVP_EncryptInit_ex.html

tks

**Comment by Snake1204** [comment]
> There is a compatibility issue with g++ -m32 in linux x86_64 with openssl>=1.0.0，0.9.8zh or g++ -m64 is correct.
> 
> if openssl compiled with: setarch i386 ./config -m32 no-asm, there is no problem.
> 
> if openssl compiled with: setarch i386 ./config -m32, the encrypted string can't correct decrypt .
> 
> wrong result:
> gcc:4.1.2 compiled:Mar 1 2019 00:41:28
> 
> test:this is test string
> urlencode:this+is+test+string
> HEX=746869732B69732B746573742B737472696E67
> 
> AES_cbc_encrypt AES_ENCRYPT:
> HEX=E8FFBB2BA2144162430EA6D0962672C9BD65F7
> 
> base64encode:6P+7K6IUQWJDDqbQliZyyb1l96QF1K0nbFMPMCkRlBQ=
> 
> AES_cbc_encrypt AES_DECRYPT:
> HEX=746869732B69732B746573742B7374728091DC2BA2144162430EA6D0962672C9
> 
> decrypt:this is test str€戃 �AbCπ�&r�
> 
> right result:
> gcc:4.1.2 compiled:Mar 1 2019 01:03:19
> 
> test:this is test string
> urlencode:this+is+test+string
> HEX=746869732B69732B746573742B737472696E67
> 
> AES_cbc_encrypt AES_ENCRYPT:
> HEX=E8FFBB2BA2144162430EA6D0962672C945AC62
> 
> base64encode:6P+7K6IUQWJDDqbQliZyyUWsYu4xBE8ZsxzGoDm4aas=
> 
> AES_cbc_encrypt AES_DECRYPT:
> HEX=746869732B69732B746573742B737472696E6700000000000000000000000000
> 
> decrypt:this is test string
> 
> I guess the problem is in the openssl-1.1.1a\crypto\aes\asm\aes-586.pl

**Comment by Snake1204** [comment]
There is a compatibility issue with g++ -m32 in linux x86_64 with openssl>=1.0.0，0.9.8zh or g++ -m64 is correct.

if openssl compiled with: setarch i386 ./config -m32 no-asm, there is no problem.

if openssl compiled with: setarch i386 ./config -m32, the encrypted string can't correct decrypt .

wrong result:
gcc:4.1.2 compiled:Mar 1 2019 00:41:28

test:this is test string
urlencode:this+is+test+string
HEX=746869732B69732B746573742B737472696E67

AES_cbc_encrypt AES_ENCRYPT:
HEX=E8FFBB2BA2144162430EA6D0962672C9BD65F7

base64encode:6P+7K6IUQWJDDqbQliZyyb1l96QF1K0nbFMPMCkRlBQ=

AES_cbc_encrypt AES_DECRYPT:
HEX=746869732B69732B746573742B7374728091DC2BA2144162430EA6D0962672C9

decrypt:this is test str€戃 �AbCπ�&r�

right result:
gcc:4.1.2 compiled:Mar 1 2019 01:03:19

test:this is test string
urlencode:this+is+test+string
HEX=746869732B69732B746573742B737472696E67

AES_cbc_encrypt AES_ENCRYPT:
HEX=E8FFBB2BA2144162430EA6D0962672C945AC62

base64encode:6P+7K6IUQWJDDqbQliZyyUWsYu4xBE8ZsxzGoDm4aas=

AES_cbc_encrypt AES_DECRYPT:
HEX=746869732B69732B746573742B737472696E6700000000000000000000000000

decrypt:this is test string

I guess the problem is in the openssl-1.1.1a\crypto\aes\asm\aes-586.pl

—

**Comment by Snake1204** [comment]
I guess the problem is in the openssl-1.1.1a\crypto\aes\asm\aes-8374.pl

**Comment by Snake1204** [comment]
There is a compatibility issue with g++ -m32 in linux x86_64 with openssl>=1.0.0，0.9.8zh or g++ -m64 is correct.

if openssl compiled with: setarch i386 ./config -m32 no-asm, there is no problem.

if openssl compiled with: setarch i386 ./config -m32, the encrypted string can't correct decrypt .

wrong result:
gcc:4.1.2 compiled:Mar 1 2019 00:41:28

test:this is test string
urlencode:this+is+test+string
HEX=746869732B69732B746573742B737472696E67

AES_cbc_encrypt AES_ENCRYPT:
HEX=E8FFBB2BA2144162430EA6D0962672C9BD65F7

base64encode:6P+7K6IUQWJDDqbQliZyyb1l96QF1K0nbFMPMCkRlBQ=

AES_cbc_encrypt AES_DECRYPT:
HEX=746869732B69732B746573742B7374728091DC2BA2144162430EA6D0962672C9

decrypt:this is test str€戃 �AbCπ�&r�

right result:
gcc:4.1.2 compiled:Mar 1 2019 01:03:19

test:this is test string
urlencode:this+is+test+string
HEX=746869732B69732B746573742B737472696E67

AES_cbc_encrypt AES_ENCRYPT:
HEX=E8FFBB2BA2144162430EA6D0962672C945AC62

base64encode:6P+7K6IUQWJDDqbQliZyyUWsYu4xBE8ZsxzGoDm4aas=

AES_cbc_encrypt AES_DECRYPT:
HEX=746869732B69732B746573742B737472696E6700000000000000000000000000

decrypt:this is test string

I guess the problem is in the openssl-1.1.1a\crypto\aes\asm\#8374
