### ISSUE TITLE
Why does RedHat have so many patches on OpenSSL?

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#8388]
This question is possibly better for the users list but asking it here. If it's inappropriate for this location please let me know.

Fedora keeps accumulating patches and now is somewhere around 20+ patches that it applies to OpenSSL. https://src.fedoraproject.org/rpms/openssl/tree/f30 I believe RHEL has even more.

Is there some standing reason that these patches don't/can't get submitted to OpenSSL mainline?

**Comment by mattcaswell** [comment]
I guess this question is better directed at RedHat, although there are some RedHat people that hang out around here who may know.

**Comment by t8m** [comment]
I'll try to submit some of the patches upstream eventually, but most of the downstream patches are related to the FIPS support that cannot be upstreamed (the "philosophy" of the upstream FIPS support is completely different) and also to the fact that we cannot ship some algorithms (currently EC related only) due to legal reasons. Some of the patches are just integration with the rest of the OS which also does not make sense upstream. And the recent patches are just backport of EVP-KDF and SSHKDF patches from upstream master because we need it sooner than when 3.0.0 will be available.

In general the situation is much much better than it was in 1.0.x days. The number of the downstream patches is now much smaller.

**Comment by t8m** [comment]
Just look at Fedora 19 for example for comparison: https://src.fedoraproject.org/rpms/openssl/tree/f19

**Comment by mlindner** [comment]
The reason I ask this is these changes cause ABI/API compatibility between RedHat packages that expect RedHat OpenSSL and using stock OpenSSL. It's, in effect, no longer OpenSSL and instead actually a RedHat fork of OpenSSL.

> we cannot ship some algorithms (currently EC related only) due to legal reasons.

There's command line options to disable EC when building it though. The RPMs that would be produced would not contain EC in those cases. I'm not sure what patching it out actually achieves here as the EC code is still being stored in the "inverse patch" that patches out the EC code.

**Comment by FdaSilvaYY** [comment]
@mlindner : this [patch ](https://src.fedoraproject.org/rpms/openssl/blob/f30/f/openssl-1.1.1-ec-curves.patch)disable a large part of EC curves ( only 6 remains) but not all, AFAIS.

**Comment by FdaSilvaYY** [comment]
This [openssl-1.1.1-version-add-engines.patch](https://src.fedoraproject.org/rpms/openssl/blob/f30/f/openssl-1.1.1-version-add-engines.patch) is smart.
Display all the active engines is a pertinent info to add to `openssl version -a` command .

**Comment by t8m** [comment]
Yes, that one is definite candidate for PR. I'll do it.

**Comment by t8m** [comment]
There is nothing to do here on the OpenSSL side anymore.
