### ISSUE TITLE
APP may crash in load_pkcs12

### ISSUE THREAD

**Issue by HeYoushang** [openssl/openssl#8441]
the following code indicates that `len` may be >= `PEM_BUFSIZE`, if so, the `tpass` will not be ended with null-terminator, finally probably leads to crash when calling strlen in `PKCS5_PBKDF2_HMAC` ( <--pkcs12_gen_gost_mac_key <-- pkcs12_gen_mac <-- PKCS12_verify_mac <-- PKCS12_parse <-- load_pkcs12 )
https://github.com/openssl/openssl/blob/f0e4a860d0b350e10a1ee3898445cac85af8ea16/apps/apps.c#L398-L399
https://github.com/openssl/openssl/blob/f0e4a860d0b350e10a1ee3898445cac85af8ea16/crypto/evp/p5_crpt2.c#L30-L35
I think the description of `pem_password_cb` is not so clear, app may fill the whole `buf` regardless of null-terminator, app has not been informed that the `size` includes length of null-terminator.
or else if the `buf` implicitly requires a null-terminator when it is defined as type of `char *`, why do we still judge `len < PEM_BUFSIZE` but not write directly as follows:
`len = (len > (PEM_BUFSIZE - 1)) ? (PEM_BUFSIZE - 1) : len;`
`tpass[len] = 0;`
![image](https://user-images.githubusercontent.com/46014603/54020792-9543ef00-41c9-11e9-9a02-e3ca07433b04.png)

**Comment by levitte** [comment]
Actually, if `len >= PEM_BUFSIZE`, it should be an error.

**Comment by HeYoushang** [comment]
So do you have any suggestion about this, I think there may be two ways to improve the code, 
1. assign tpass[min(len, PEM_BUFSIZE - 1)] = 0 directly
`len = (len > (PEM_BUFSIZE - 1)) ? (PEM_BUFSIZE - 1) : len;`
`tpass[len] = 0;`
2. return error when `len >= PEM_BUFSIZE`
and we may need to improve the description about the `size` parameter in `pem_password_cb`

**Comment by HeYoushang** [comment]
hello, @levitte , any advice ?

**Comment by erbsland-dev** [comment]
@mattcaswell While the functionality discussed in this issue was removed from OpenSSL, it seems the underlying problem still persists. The OpenSSL library is currently too trusting of the data returned by the password callback and does not handle edge cases gracefully.

I've submitted a PR with an additional test to demonstrate this issue. The test, as expected, fails — often resulting in a crash. For instance, when a valid password of the maximum buffer length is supplied, OpenSSL writes a null byte past the end of the password buffer, which is incorrect behavior.

I would suggest the following improvements:
- Pass `buffer_size - 1` to the callback to ensure there is always room for a terminating null byte.
- Validate the callback's return value, checking that `size <= (buffer_size - 1)`, and handle any out-of-bounds scenarios gracefully.

**Comment by erbsland-dev** [comment]
@mattcaswell After analyzing the code and extending the tests to cover both PEM and DER encoded keys, I implemented the necessary fixes to enhance the robustness of handling password callback returns. These changes ensure more reliable processing of edge cases across different key formats.
