### ISSUE TITLE
X25519/X448 implementation question

### ISSUE THREAD

**Issue by p-steuer** [openssl/openssl#8452]
(No bug-report, feature request or question how to use OpenSSL, so not sure where to put this ..)

For X25519/X448, the naive way to derive public from private key would be scalar multiplication (private key * base point (u=9/u=5)) on montgomery curve, see diff below.

However, for X25519 scalar * base point is implemented as being done on the edwards curve. Afterwards the birational map is evaluated to get u coordinate on montgomery curve. X448 also implements a special algorithm for public key derivation.

Is there more documentation regarding these implementation aspects (paper) ? Or can somebody comment on this ?

```
diff --git a/crypto/ec/curve25519.c b/crypto/ec/curve25519.c
index 7d12c5d..2eea069 100644
--- a/crypto/ec/curve25519.c
+++ b/crypto/ec/curve25519.c
@@ -5570,27 +5570,8 @@ int X25519(uint8_t out_shared_key[32], const uint8_t private_key[32],
 void X25519_public_from_private(uint8_t out_public_value[32],
                                 const uint8_t private_key[32])
 {
-    uint8_t e[32];
-    ge_p3 A;
-    fe zplusy, zminusy, zminusy_inv;
-
-    memcpy(e, private_key, 32);
-    e[0] &= 248;
-    e[31] &= 127;
-    e[31] |= 64;
-
-    ge_scalarmult_base(&A, e);
-
-    /*
-     * We only need the u-coordinate of the curve25519 point.
-     * The map is u=(y+1)/(1-y). Since y=Y/Z, this gives
-     * u=(Z+Y)/(Z-Y).
-     */
-    fe_add(zplusy, A.Z, A.Y);
-    fe_sub(zminusy, A.Z, A.Y);
-    fe_invert(zminusy_inv, zminusy);
-    fe_mul(zplusy, zplusy, zminusy_inv);
-    fe_tobytes(out_public_value, zplusy);
-
-    OPENSSL_cleanse(e, sizeof(e));
+    unsigned char base[32];
+    memset(base, 0, sizeof(base));
+    base[0]=9;
+    x25519_scalar_mult(out_public_value, private_key, base);
 }
diff --git a/crypto/ec/curve448/curve448.c b/crypto/ec/curve448/curve448.c
index b06aa58..c304ad4 100644
--- a/crypto/ec/curve448/curve448.c
+++ b/crypto/ec/curve448/curve448.c
@@ -723,5 +723,8 @@ int X448(uint8_t out_shared_key[56], const uint8_t private_key[56],
 void X448_public_from_private(uint8_t out_public_value[56],
                               const uint8_t private_key[56])
 {
-    x448_derive_public_key(out_public_value, private_key);
+    unsigned char base[56];
+    memset(base, 0, sizeof(base));
+    base[0]=5;
+    x448_int(out_public_value, base, private_key);
 }
```

**Comment by romen** [comment]
My 2 cents on this:

The "fixed point" scalar multiplication (multiplications by the agreed upon generator point) are generally a very good candidate for optimizations, as they are used frequently as part of keygen and as a preliminary step of other crypto operations (e.g. setting up each signature generation both in ECDSA and EdDSA) and because the "fixed point" aspect allows for considerable performance gains.

Given that they are compatible and that the conversion between Twisted Edwards and Montgomery/short-Weierstrass is generally cheap compared to the actual scalar multiplication cost, it makes sense to have only one implementation to optimize and harden, rather than maintaining two separate optimized implementations across different platforms:

- less code => potentially less bugs
- less duplication => easier to maintain
- often part of the optimization come from precomputed values in huge tables, so less duplication => smaller binaries

**Comment by p-steuer** [comment]
I thought in the direction of scalar * arbitrary point vs scalar * fixed point performance but couldnt see why one wouldnt implement the latter for montgomery curves to save to conversion costs.

However, if conversion cost is really that low, the advantages mentioned are certainly worth it.

Thanks.

**Comment by bbbrumley** [comment]
> if conversion cost is really that low

There are many aspects to consider in implementation. But to keep the inversions low, the approach in this code depends on combining the final conversion from projective to affine with the birational map to switch curves, so still only one inversion needed in the end.

Some [further reading](https://tools.ietf.org/html/draft-struik-lwip-curve-representations-00).

**Comment by p-steuer** [comment]
Thanks for answering this one. Closing.
