### ISSUE TITLE
Missing struct field access or object access methods 

### ISSUE THREAD

**Issue by hlsantos** [openssl/openssl#8562]
Porting my v1.0.x OpenSSL code to v1.1.x,  I was able to replace most ssl or ctx pointer field access with the new available functions, methods or "accessors."

However, when it came to X509_LOOKUP_METHOD,  I had to create an internal header similar to what was done for "include\internal\bio.h"   So now I have a "include\internal\x509_lookup.h" header.

I have a set of virtual BIO I/O methods for our RPC client/server platform.    The RPC clients can access the "wc:\ssl" files.  Our "wcBIO" functions will use our wcSDK/API if a file has a "wc:\" prefix and so on.    I was able to recompile the BIO_METHOD by reference "internal\bio.h" in my code.

Well, I needed to repeat this with the X509_LOOKUP_METHOD struct using the wcBIO functions by creating include\internal\x509_lookup.h:

```
// Created SSI.HLS 03/23/19 11:44 am
// Support wcBIO/wcX509 functions

#include <openssl/x509.h>

struct x509_lookup_method_st {
    char *name;
    int (*new_item) (X509_LOOKUP *ctx);
    void (*free) (X509_LOOKUP *ctx);
    int (*init) (X509_LOOKUP *ctx);
    int (*shutdown) (X509_LOOKUP *ctx);
    int (*ctrl) (X509_LOOKUP *ctx, int cmd, const char *argc, long argl,
                 char **ret);
    int (*get_by_subject) (X509_LOOKUP *ctx, X509_LOOKUP_TYPE type,
                           X509_NAME *name, X509_OBJECT *ret);
    int (*get_by_issuer_serial) (X509_LOOKUP *ctx, X509_LOOKUP_TYPE type,
                                 X509_NAME *name, ASN1_INTEGER *serial,
                                 X509_OBJECT *ret);
    int (*get_by_fingerprint) (X509_LOOKUP *ctx, X509_LOOKUP_TYPE type,
                               const unsigned char *bytes, int len,
                               X509_OBJECT *ret);
    int (*get_by_alias) (X509_LOOKUP *ctx, X509_LOOKUP_TYPE type,
                         const char *str, int len, X509_OBJECT *ret);
};

/* This is the functions plus an instance of the local variables. */
struct x509_lookup_st {
    int init;                   /* have we been started */
    int skip;                   /* don't use us. */
    X509_LOOKUP_METHOD *method; /* the functions */
    void *method_data;          /* method data */
    X509_STORE *store_ctx;      /* who owns us */
};

```
And this worked to get pass the initial X509_LOOKUP_METHOD setup compilation, but moving along, I now come across the need to access the SSL_CTX to access the "ctx->cert_store"  field.

Before creating a "include\internal\ssl.h", I decided to stop here because I have to be missing something.   Did this fall under the proverbial crack?   It is hard to imagine that such 1.0.x compatibility has been lost and the need to add "internal" headers to fix "things."   Its getting kind of "kludgy" even with the new Openssl v1.1 model.

I must be missing something with the BIO_METHOD and X509_LOOKUP_METHOD functionality to create your own private set of BIO/X509 I/O virtual functions.

Thanks for any input you can provide

**Comment by hlsantos** [comment]
I am looking at issues #7923 and #6505. 

Yes, as someone pointed out, this needs to better documented, in particular if a "new" function needs to be used.

**Comment by petrovr** [comment]
hlsantos wrote:
> I am looking at issues #7923 and #6505.
>
> Yes, as someone pointed out, this needs to better documented, in particular if a "new" function needs to be used.

x509 lookup api is not usable - see  #6970

**Comment by hlsantos** [comment]
Thanks for the link.  I have to study what you mean as "not usable."   I am now comparing the v1.02 examples with the v1.1.1, examples,  specifically test\ssltestlib.c and other ported examples using BIO_METHOD and X509_LOOKUP_METHOD.  But I am going to to try using/creating the internal headers functions.  I hope this does't become a show stopper.

**Comment by petrovr** [comment]
hlsantos wrote:
> Thanks for the link.  I have to study what you mean as "not usable."   I am now comparing the v1.02 examples with the v1.1.1, examples,  specifically test\ssltestlib.c and other ported examples using BIO_METHOD and X509_LOOKUP_METHOD.  But I am going to to try using/creating the internal headers functions.  I hope this does't become a show stopper.
> 

Second point of issue : result value, i.e. argument "X509_OBJECT *ret" 
of lookup method . OpenSSL API provides  *get0*, *get1*, *dup* methods 
but case is exceptional - it requires "move".
Another point is why in external code to manage "X.509 store" cache, 
"X.509 store" items and fetch of data.

Whole management of  "X.509 store" could be keep internal to OpenSSL and 
third party code to  take responsibility only to supply required by 
<name> and <type> (cert. or crl). This is goal of #8442 .

**Comment by hlsantos** [comment]
In my product/platform case,  we created long ago a "wcSSL.DLL" dynamically linked OpenSSL multi-threaded wrapper for loading/starting our SSL servers; wcWeb, wcFTP, wcTelnet, wcPOP3, wcSMTP, etc.   Since the platform is an RPC client/server system, a major part is a virtualized file I/O system isolated to the server and accessed via a proprietary file name nomenclature.  So we used the BIO_METHOD to prepare the virtualized file I/O and the X509_LOOKUP_METHOD load the certs both by file and by file spec.

I got this now recompiled under v1.1.1.  It took rolling up my sleeves to dig deep into the B4 (v1.02g) and AD (v1.1.1) to compare what has changed and to "accessors."   The migration/port doc specifics are lacking.   The only thing I had to do beyond is what is provided for accessors, was to create a "internal\x509_lookup.h"  header file:

```
// Created SSI.HLS 03/23/19 11:44 am
// Support wcX509 functions

#include <openssl/x509.h>

struct x509_lookup_method_st {
    char *name;
    int (*new_item) (X509_LOOKUP *ctx);
    void (*free) (X509_LOOKUP *ctx);
    int (*init) (X509_LOOKUP *ctx);
    int (*shutdown) (X509_LOOKUP *ctx);
    int (*ctrl) (X509_LOOKUP *ctx, int cmd, const char *argc, long argl,
                 char **ret);
    int (*get_by_subject) (X509_LOOKUP *ctx, X509_LOOKUP_TYPE type,
                           X509_NAME *name, X509_OBJECT *ret);
    int (*get_by_issuer_serial) (X509_LOOKUP *ctx, X509_LOOKUP_TYPE type,
                                 X509_NAME *name, ASN1_INTEGER *serial,
                                 X509_OBJECT *ret);
    int (*get_by_fingerprint) (X509_LOOKUP *ctx, X509_LOOKUP_TYPE type,
                               const unsigned char *bytes, int len,
                               X509_OBJECT *ret);
    int (*get_by_alias) (X509_LOOKUP *ctx, X509_LOOKUP_TYPE type,
                         const char *str, int len, X509_OBJECT *ret);
};

/* This is the functions plus an instance of the local variables. */
struct x509_lookup_st {
    int init;                   /* have we been started */
    int skip;                   /* don't use us. */
    X509_LOOKUP_METHOD *method; /* the functions */
    void *method_data;          /* method data */
    X509_STORE *store_ctx;      /* who owns us */
};

```
Now I did this before seeing what levitt did with #8442,   I suppose, in the name of keeping on par with the distribution, I can go back and remove this internal header and try the new accessors, or stay with the internal header and suggest it be added to the distribution.  After all, its working and its unfortunate that we even need an 'Internal\" set of headers to resolve compatibility problems. 

Overall, IMO, the goal should be compatibility with a clean port, no need for kludges, etc.  I will venture the OpenSSL has not even touch based with the majority of legacy and established OpenSSL implementors who are not keen with a major change idea when there was really no need for it for a stable production system .  TLS v1.3 is the most important only real business reason.  But with a major API change, Open v1.1.1 need to be stabilized for portability asap.  Implementors only have 5-6 months for conversion and foremost, testing.  Openssl may have a conflict holding to its EOL 2019 goal for v1.0.x.

Thanks

**Comment by mspncp** [comment]
> Overall, IMO, the goal should be compatibility with a clean port, no need for kludges, etc. I will venture OpenSSL has not even touch based with the majority of legacy and established OpenSSL implementors who are not keen with a major change idea when there was really no need for it for a stable production system . TLS v1.3 is the most important only real business reason. But with a major API change, Open v1.1.1 need to be stabilized for portability asap.

I can understand your frustration seeing how you are struggling with the conversion from 1.0.2 to 1.1.1, (#8551, #8556, #8575, #8577). But this does not justify your ranting against the community, here in this thread and in https://github.com/openssl/openssl/issues/8577#issuecomment-476445280. 

After all, that's what Open Source is about: You are free to take it and use it, and nobody requires you to pay money for it. But you can't just use it for 20+ years without participating or contributing anything to the community and then demand that the software meets all your requirements and needs. And with "contributing" I don't even mean writing some code, but just to speak up and share your needs and opinions. Why doesn't OpenSSL have these compatibility wrappers for 1.0.2 you are missing? Because nobody took the time and went through the effort to implement and share them. Where were _you_ when the job needed to be done? Whom do intend to blame?

> Implementors only have 5-6 months for conversion and foremost, testing. Openssl may have a conflict holding to its EOL 2019 goal for v1.0.x.

Sorry to say it, but you are _very_ late to the game. OpenSSL 1.1.0, which introduced the opaque structures, was [released in August 2016](https://www.openssl.org/source/old/1.1.0) which is a lot more than 5-6 months ago. If you are now running out of time because of the EOL for 1.0.2 you should probably blame yourself.


And finally, in reply to https://github.com/openssl/openssl/issues/8577#issuecomment-476445280:

> 20 years? Openssl is about that old.
>
> It was used to import IIS Cert/Keys when customers (of all scales; hobbyist, small biz to enterprise) switch from IIS to our Wildcat! platform
> ...
> You can't make decisions like this for folks like this by pulling stuff out especially after 20 years without a workaround or perhaps by moving the code to a legacy set of API that is still part of the package. Something, you just don't pull code like this.. That's not cool.


Sometimes it is necessary to cut off old braids, because a lot of the 20+ year old cryptography (not everything, fortunately) has become hopelessly insecure. Reading the Wikipedia article pointed out by @mlindner I see that SGC became obsolete at the beginning of the millennium. 

> Internet Explorer supported SGC starting with patched versions of Internet Explorer 3. SGC became obsolete when Internet Explorer 5.01 SP1 and Internet Explorer 5.5 started supporting strong encryption without the need for a separate high encryption pack (except on Windows 2000, which needs its own high encryption pack that was included in Service Pack 2 and later).[3]

The support for RSA_NET was removed in commit 0bc2f365558ed5980ce87d6b2704ca8649ca2a4a in 2015. Where were you in all these years to report it missing? Everybody would have told you that it does not make sense to support obsolete and insecure cryptography forever. You shouldn't add it back into the upcoming release of your software. (After all, it's Open Source; nobody prevents you from adding it back in from 1.0.2.) Everybody still using IE 5 will probably also be still using a 20+ year old version of your Wildcat software, so he won't be affected by this incompatibility anyway. But he will certainly have severe security issues.

**Comment by paulidale** [comment]
Well said @mspncp 

People have had over two years to port to the current APIs.  If they haven't yet, they've only themselves to blame.  Users of FIPS have had half an excuse since they won't have a replacement until 3.0 is done but the necessary changes haven't been hidden since before 1.1.0 was released.  The intention is for 3.0 to be compatible with 1.1.1 as far as possible -- we really are trying hard on this front despite the difficulties.

The 1.1 changes were required by the project in order to move into the future.  Yes, they hurt our consumers.  That was regrettable but unavoidable.  Opaque structures mean the project can move forwards.  Without them, we were stuck in the past.

For people who think moving forward is too difficult or too soon, [premium support](https://www.openssl.org/support/contracts.html#premium) covers 1.0.2 for a while longer.

**Comment by mattcaswell** [comment]
> However, when it came to X509_LOOKUP_METHOD, I had to create an internal header similar to what was done for "include\internal\bio.h" So now I have a "include\internal\x509_lookup.h" header.

> I have a set of virtual BIO I/O methods for our RPC client/server platform. The RPC clients can access the "wc:\ssl" files. Our "wcBIO" functions will use our wcSDK/API if a file has a "wc:" prefix and so on. I was able to recompile the BIO_METHOD by reference "internal\bio.h" in my code.

I'm not sure I understand why it was necessary to do this. In both the BIO_METHOD and X509_LOOKUP_METHOD cases it is perfectly possible to create custom METHODs in 1.1.1 without importing internal headers.

For BIO you need to use this set of functions:

https://www.openssl.org/docs/man1.1.1/man3/BIO_meth_new.html

For X509_LOOKUP_METHOD you use these ones:

https://www.openssl.org/docs/man1.1.1/man3/X509_LOOKUP_meth_new.html

> And this worked to get pass the initial X509_LOOKUP_METHOD setup compilation, but moving along, I now come across the need to access the SSL_CTX to access the "ctx->cert_store" field.

For `cert_store` use `SSL_CTX_get_cert_store`, documented here:

https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_get_cert_store.html

**Comment by levitte** [comment]
There is a tangible problem with the way the X509_LOOKUP_METHOD lookup funktions are used. [`X509_STORE_CTX_get_by_subject`](https://github.com/openssl/openssl/blob/master/crypto/x509/x509_lu.c#L289) expects the returned object to have a reference count 0. However, many public object creation functions return an object with reference count 1... but most APIs don't have a public down_ref function, and expect users to be freed to do so, and we all know what happens when the ref count drops down to zero.

The solution is *not* to provide a public down_ref function, the solution is to fix X509_STORE to be more consistent with the rest of libcrypto, let alone itself...

**Comment by kroeckx** [comment]
Adding an internal header to your own project is likely going to cause you problems in the future. Since those structures are no longer public, we can modify them without problems, and we did modify various of those structures that used to be public but no longer are.

**Comment by hlsantos** [comment]
Reqarding @mspncp comments.....

Fair points.  Where was I?  Well, I was an a health sabbatical for 5+ years (2012-mid 2018) and within the last year or so, slowly started to get back into the game.  In the 12-15+ years before v1.1.0, OpenSSL was fine.  It didn't need my technical input.  There was times via the pre-github mailing list, I might have tried to do get involved.  Nonetheless, I knew changes were coming in 2016 and as my nature, unfortunately, I wait for stability, I plan and I did expect "common sense engineering" would prevail as I always do with almost of the well founded open source projects and open standards groups, i.e. IETF,  a migration compatibility path would be a major consideration  And there was/is, albeit, it difficult one and continuing process.  But you are right,  this Openssl remodeling project needs more input from established systems who would go through this process.  It probably explains what you are seeing now.   Before GitHub, it was more difficult to do this, to participate in it and it was the mailing list. I used it for announcements.   GitHub will make it easier to participate moving forward.

In regards to #8577,  of course, none of our customers with PCI needs supports outdated stuff.  SSLLabs made sure of that into order to get A+ rating.   The  d2i_RSA_NET() function per the example in load_netscape_key() was used to a CheckRSAKey() function used in our wcSSL Setup/Configuration tool allowing a customer two options to import II4/II5 certs and keys,    Here is my thought process on that:

1) Remove the options in the next v1.1 ready update,
2) Create a custom Openssl v1.1 build to add parts back,  share it if people interested,
3) Keep OpenSSL 1.02 for the wcSSL Configuration/Setup tool and use Openssl V1.1 for the clients and servers.

#3 is silly.  But its keeps floating in my mind.  I don't want to get into customization with #2 but I can at least explore it the isolation and add it to the build with subsequent Openssl v1.1.1+ updates.   For now, as the conversion continues, go with #1 and see what happens.   After all,  the v1.0.x openssl.exe CLI tool can be used to convert IIS cert keys, I believe.  Give them a "How to" if anyone wants to reuse their IIS cert/keys.

@mattcaswell I will be checking your comments to see if I still need to use a custom internal headers for the X509 lookup. 

Thanks

**Comment by hlsantos** [comment]
> Adding an internal header to your own project is likely going to cause you problems in the future. Since those structures are no longer public, we can modify them without problems, and we did modify various of those structures that used to be public but no longer are.

@kroeckx,  I agree, thus why its not a good idea to get into this internal headers and code "kludging" game, especially so soon with a new API model.  But hopefully, they can be used to learn what needs to be done so they can be eliminated.  

Suggestion:  Most people (application developers, not crypto experts, the not the system/api developers),  learn how to apply OpenSSL via the examples provided.   So you should expect pieces of code of what was done in the pre-v1.1 versions used in applications.   These examples have to be matched in v1.1 and when parts are changed show how to replace them in its entirety or its parts.   In most cases, you don't pull, you stub it, make use of compiler macros warnings/errors, and most certainly you document it, not just say in Changes, XYZ was removed with no further information.   In fact, I suggest a check list of considerations to be reviewed for feature removals and replacement;  Is it is important?  Is it in use? Is it insecure?   Is it a client feature, server feature or configuration features?  and so on.  Sure, I wish I was around 2016 to assist, but I wasn't.  Now I am.  Hope I can help.

**Comment by kroeckx** [comment]
All the new function in 1.1 have been documented, all the examples
in the manpages have been updated to use the new APIs. We have
even provided stub functions so you can write code against the 1.1
API and still build it against 1.0.2.

I have actually ported many of the applications to use
the new API, which in almost all cases is very simple.

If I know we want to remove something, I check all sources in
Debian that they use that or not, and how hard it would be to
replace it. This is a very large amount of code, and if it's not
in use in any of them, it's not that important to keep it.

Getting all the code to use OpenSSL 1.1 in Debian takes a very
long time and that has already happened.

**Comment by mspncp** [comment]
> We have even provided stub functions so you can write code against the 1.1
> API and still build it against 1.0.2.

Kurt, when you say "we", do you mean Debian or OpenSSL? Where are these stub functions you are talking about? Would you mind providing a link to them?

**Comment by hlsantos** [comment]
@mattcaswell.  I was finally able to get the BIO_METHOD and X509_LOOKUP_METHOD code working using the new v1.1 setup without the internal headers.     Pending ssl client/server testing (those have not been converted set, don't expect much change since its already virtualized),  it appears to be ok with a SSL cert loading and initialization testing tool I have.

If anything to add ...

There is a good example in apps\s_server.c  for preparing a BIO_METHOD using the new callback setup functions.   There is not an "apps" level example for setup X509_LOOKUP_METHOD.  There is the crypto\x509\by_file.c and crypto\x509\by_dir.c  which are more raw (and v1.02 like) -- not "opaque."   I followed the BIO_METHOD layout model to do  X509_LOOKUP_METHOD in a similar manner.  A "apps" level example would be useful.   

Finally, the BIO_method example added a static const to the BIO_METHOD *BIO_s_xxxxx() initializer function.  If you follow this in your code, I got a linker problem with an undefined symbol when referenced outside the same file source.  I had to remove the static.. 

Thanks.

**Comment by hlsantos** [comment]
I am going to close this.  The only thing to add here is perhaps added an v1.1 example for X509_LOOKUP_METHOD callback setup, and I just confirmed the compiler link issue which I will post a new issue. 

Thanks

**Comment by kroeckx** [comment]
The stub functions are on the wiki

**Comment by mspncp** [comment]
> The stub functions are on the wiki

For convenience here is the link: I assume that @kroeckx was referring to the [OpenSSL 1.1.0 Changes](https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes) page, in particular the [Compatibility Layer](https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes#Compatibility_Layer) section.

It contains some examples, but is far from complete. My personal solution was simply to have a separate copy of the 1.1.1 source tree lying around and make heavy use of the grep&copy method. Since the accessors mostly follow a consistent naming convention, it's straightforward most of the times to find the correct accessors. And the simplest of them can be implemented as header-only preprocessor macros (or alternatively, inline functions if you are using C++).
