### ISSUE TITLE
[Crash] RAND_load_file()

### ISSUE THREAD

**Issue by thamht4190** [openssl/openssl#8702]
I'm using arrow/parquet to write encrypted parquet file. that RAND_load_file() is used in [this PR](https://github.com/apache/arrow/pull/3520/files). Actually my crypto.cc is a little different: 
https://gist.github.com/thamht4190/b9fab0a7bd98d75eddaaca24382bd310.

Sometimes I got a crash at RAND_load_file. This is the stacktrace from dump file: 
[trace_rand_load_file.txt](https://github.com/openssl/openssl/files/3057052/trace_rand_load_file.txt)

I'm using OpenSSL version 1.1.1b. I got the issue on both MacOS X 10.14 and 10.13.

Can anyone have ideas about this issue? Thanks!

**Comment by thamht4190** [comment]
I have a more clear stacktrace now:
[trace_rand_load_file_2.txt](https://github.com/openssl/openssl/files/3063006/trace_rand_load_file_2.txt)
```
Thread 4 (crashed)
 0  libsystem_pthread.dylib!pthread_rwlock_wrlock + 0x0
    rax = 0x0000000000000001   rdx = 0x0000000000000000
    rcx = 0x0000000000000001   rbx = 0x0000000000000000
    rsi = 0x00000001083fc150   rdi = 0x0000000000000000
    rbp = 0x000070000f9f1c00   rsp = 0x000070000f9f1bf8
     r8 = 0x00000000000130a8    r9 = 0x0000000000000000
    r10 = 0x00007fff96afb288   r11 = 0x00007fff96afb280
    r12 = 0x0000000000000000   r13 = 0x000070000f9f1d00
    r14 = 0x0000000000000020   r15 = 0x0000000000000020
    rip = 0x00007fff63effe14
    Found by: given as instruction pointer in context
 1  CortexSync!CRYPTO_THREAD_write_lock + 0x9
    rbx = 0x0000000000000000   rbp = 0x000070000f9f1c00
    rsp = 0x000070000f9f1c00   r12 = 0x0000000000000000
    r13 = 0x000070000f9f1d00   r14 = 0x0000000000000020
    r15 = 0x0000000000000020   rip = 0x0000000108428999
    Found by: call frame info
 2  CortexSync!RAND_get_rand_method + 0x36
    rbx = 0x0000000000000000   rbp = 0x000070000f9f1c20
    rsp = 0x000070000f9f1c10   r12 = 0x0000000000000000
    r13 = 0x000070000f9f1d00   r14 = 0x0000000000000020
    r15 = 0x0000000000000020   rip = 0x00000001083fc3d6
    Found by: call frame info
 3  CortexSync!RAND_add + 0x1b
    rbx = 0x000070000f9f1d00   rbp = 0x000070000f9f1c50
    rsp = 0x000070000f9f1c30   r12 = 0x0000000000000000
    r13 = 0x000070000f9f1d00   r14 = 0x0000000000000020
    r15 = 0x0000000000000020   rip = 0x00000001083fc65b
    Found by: call frame info
 4  CortexSync!RAND_load_file + 0x1c3
    rbx = 0x00007fff96afc030   rbp = 0x000070000f9f2230
    rsp = 0x000070000f9f1c60   r12 = 0x0000000000000000
    r13 = 0x000070000f9f1d00   r14 = 0x0000000000000020
    r15 = 0x0000000000000020   rip = 0x00000001083fd043
```
Any idea?

**Comment by mattcaswell** [comment]
Well, its quite odd. The crash suggests that the `rand_meth_lock` is somehow not initialised or is otherwise invalid. Here is the code that crashes:

https://github.com/openssl/openssl/blob/130b7df2db7d35af75ddf56046afdd1a57a2aea8/crypto/rand/rand_lib.c#L737-L745

But we can see that immediately prior to aquiring the lock we do a "RUN_ONCE" call (which is just pthread_once) and call `do_rand_init` which initialises the `rand_meth_lock`. So I can't currently see how that lock could be invalid.

> We are running multi threads that may call RAND_load_file() at the same. Is it allowed to do so?

Yes, this should be ok.

OTOH, I note that you are effectively calling RAND_load_file() to seed the DRBG with data from `/dev/urandom'. This should be totally unnecessary. The DRBG will automatically seed itself as required with no explicit action needed. So, while it doesn't explain the crash, one simple solution for you would be to remove the RAND_load_file() calls.

**Comment by thamht4190** [comment]
Thanks for your reply. If you need any more information, please let me know. I'll also try to debug on my side.
For RAND_load_file() use case, this is the answer from parquet crypto developer:
> we need not just random, but a stronger version called "secure random" to prevent nonce repetition that breaks AES-CTR (and GCM) algorithms.
> Loading the /dev/urandom is a standard way to do that, but I'll check for workarounds.
Any suggestion?

**Comment by ggershinsky** [comment]
@mattcaswell Thanks for your input. What we are looking for, is a C++ (openSSL) version of Java's
https://docs.oracle.com/javase/8/docs/api/java/security/SecureRandom.html

Any suggestions would be appreciated.

**Comment by mattcaswell** [comment]
> we need not just random, but a stronger version called "secure random" to prevent nonce repetition that breaks AES-CTR (and GCM) algorithms.
Loading the /dev/urandom is a standard way to do that, but I'll check for workarounds.

The OpenSSL RAND implementation provides a secure random source. It must be properly seeded in order to work. One place it could get its random seed data from is "/dev/urandom". OpenSSL will do this seeding automatically (obtaining data from "/dev/urandom" if appropriate for the platform) and 99% of the time there is no need to seed manually using RAND_load_file() or similar calls. In very rare circumstances (such as an obscure platform that OpenSSL doesn't know how to or can't seed automatically on) then it may be necessary to manually seed. You'll know if that's the case because the OpenSSL RAND_bytes() call will fail. Doing that seeding from "/dev/urandom" is pointless because OpenSSL will already have tried that.

You almost certainly don't need to worry about any of that. Just call RAND_bytes() and forget about RAND_load_file().

**Comment by ggershinsky** [comment]
Cool, thanks.

**Comment by thamht4190** [comment]
After getting some crash stack traces, I see almost the same stack that it's doing the cleanup step at a main thread:
```
Thread 0
 0  CortexSync!engine_cleanup_int + 0x0
    rax = 0x00000000ffffffff   rdx = 0x0000000000000307
    rcx = 0x0000000000000001   rbx = 0x0000000000000000
    rsi = 0x0000000000000307   rdi = 0x0000000000000000
    rbp = 0x00007ffee8c2ad00   rsp = 0x00007ffee8c2acd8
     r8 = 0x0000000000000021    r9 = 0x00007fe69ae60fd0
    r10 = 0x0000000000000022   r11 = 0x0000000000000022
    r12 = 0x00007fe69b017200   r13 = 0x0000000000000001
    r14 = 0x000000010894f260   r15 = 0x00000000000001c0
    rip = 0x00000001083b12a0
    Found by: given as instruction pointer in context
 1  CortexSync!OPENSSL_cleanup + 0x13b
    rbx = 0x0000000000000000   rbp = 0x00007ffee8c2ad00
    rsp = 0x00007ffee8c2ace0   r12 = 0x00007fe69b017200
    r13 = 0x0000000000000001   r14 = 0x000000010894f260
    r15 = 0x00000000000001c0   rip = 0x00000001083d7eeb
    Found by: call frame info
 2  libsystem_c.dylib + 0x5cef9
    rbx = 0x0000000000000000   rbp = 0x00007ffee8c2ad50
    rsp = 0x00007ffee8c2ad10   r12 = 0x00007fe69b017200
    r13 = 0x0000000000000001   r14 = 0x000000000000000f
    r15 = 0x00000000000001c0   rip = 0x00007fff63db5ef9
    Found by: call frame info
 3  libsystem_c.dylib + 0x5d1de
    rbp = 0x00007ffee8c2ad70   rsp = 0x00007ffee8c2ad60
    rip = 0x00007fff63db61de
    Found by: previous frame's frame pointer
 4  CortexSync!start + 0x3b
    rbp = 0x00007ffee8c2ad80   rsp = 0x00007ffee8c2ad80
    rip = 0x0000000106fd603b
    Found by: previous frame's frame pointer
```
I realize that I don't stop the thread where RAND_load_file() is called while the application is killed. But I'm not sure if this can cause crashes at RAND_load_file(). Can you help? @mattcaswell

**Comment by mattcaswell** [comment]
The cleanup routines assume that there are no other threads doing OpenSSL stuff (if there are why are you trying to cleanup?). Are you explicitly calling `OPENSSL_cleanup`? Normally there is no reason to do this - it should happen automatically.

**Comment by thamht4190** [comment]
No, I don't call `OPENSSL_cleanup` explicitly. It's called automatically when my application is killed.

**Comment by mattcaswell** [comment]
I'd suggest stopping all threads explicitly before closing the application and see if that helps.

**Comment by YanAnzouyijun** [comment]
@mattcaswell  
i also encounter similar problem like  @thamht4190 , but i have encounter this problem only one time.
it has never happen again........
i called the func:RAND_bytes.
First, my platform is non-preemptive system.Only one task can be performed at the same time.
but i know  that rand_meth_lock can not be null while RAND_get_rand_method be called in one task.  because Only one task can be performed at the same time in my system .
if OPENSSL_cleanup was executed before the task, the var (rand_inited) will be set to zero(OPENSSL_cleanup() -> rand_cleanup_int() -> CRYPTO_THREAD_lock_free(rand_meth_lock)).
`void rand_cleanup_int(void)
{
    const RAND_METHOD *meth = default_RAND_meth;

    if (!rand_inited)
        return;

    if (meth != NULL && meth->cleanup != NULL)
        meth->cleanup();
    RAND_set_rand_method(NULL);
    rand_pool_cleanup();
#ifndef OPENSSL_NO_ENGINE
    CRYPTO_THREAD_lock_free(rand_engine_lock);
    rand_engine_lock = NULL;
#endif
    CRYPTO_THREAD_lock_free(rand_meth_lock);
    rand_meth_lock = NULL;
    CRYPTO_THREAD_lock_free(rand_nonce_lock);
    rand_nonce_lock = NULL;
    rand_inited = 0;
}
`
then in the func(RAND_get_rand_method) will execute RUN_ONCE to new the lock.
so i cannot understand why the lock can be null ??
is there any probability that the func(OPENSSL_cleanup) and the func (RAND_get_rand_method) was called in one time ?(but i have said that my system is Only one task can be performed at the same time). so i was confused .

is there any probability that the func(OPENSSL_cleanup)  executed fail then the func (RAND_get_rand_method) was called after?
such as 
`void rand_cleanup_int(void)
{
    const RAND_METHOD *meth = default_RAND_meth;

    if (!rand_inited)
        return;

    if (meth != NULL && meth->cleanup != NULL)
        meth->cleanup();
    RAND_set_rand_method(NULL);
    rand_pool_cleanup();
#ifndef OPENSSL_NO_ENGINE
    CRYPTO_THREAD_lock_free(rand_engine_lock);
    rand_engine_lock = NULL;
#endif
    CRYPTO_THREAD_lock_free(rand_meth_lock);
    rand_meth_lock = NULL;      ----exit(fail )????   is there any probability(this is my guess.....)
    CRYPTO_THREAD_lock_free(rand_nonce_lock);
    rand_nonce_lock = NULL;
    rand_inited = 0;
}`
can you help? 
thanks!

**Comment by YanAnzouyijun** [comment]
@mattcaswell  i know  you have add a OPENSSL_INIT_NO_ATEXIT 
https://github.com/openssl/openssl/commit/8f6a5c56c17aa89b80fef73875beec53aef1f2c8#diff-a88baedd3b3f460db4620f1794f6ef48

**Comment by YanAnzouyijun** [comment]
@mattcaswell  ,i know  openssl has add a

**Comment by YanAnzouyijun** [comment]
@mattcaswell ,i know openssl has add OPENSSL_INIT_NO_ATEXIT  avoid atexit .the link is 
https://github.com/openssl/openssl/commit/8f6a5c56c17aa89b80fef73875beec53aef1f2c8#diff-a88baedd3b3f460db4620f1794f6ef48

**Comment by YanAnzouyijun** [comment]
@mattcaswell ,hello，i know openssl has add OPENSSL_INIT_NO_ATEXIT avoid atexit .the link is
8f6a5c5#diff-a88baedd3b3f460db4620f1794f6ef48
but i wonder know that if  i do not OPENSSL_cleanup() while the system is reboot , What will happen?
and how can i stopping all threads explicitly before closing the application ?Do you have any ideas?
thanks~

**Comment by YanAnzouyijun** [comment]
@mattcaswell ,hello，I know openssl has add OPENSSL_INIT_NO_ATEXIT avoid atexit .the link is
https://github.com/openssl/openssl/commit/8f6a5c56c17aa89b80fef73875beec53aef1f2c8#diff-a88baedd3b3f460db4620f1794f6ef48
but i wonder know that if I do not OPENSSL_cleanup() while the system is reboot , What will happen?
and how can i stopping all threads explicitly before closing the application ?Do you have any ideas?
thanks~

**Comment by YanAnzouyijun** [comment]
@mattcaswell ,hello，I know openssl has add OPENSSL_INIT_NO_ATEXIT avoid atexit .the link is
8f6a5c5#diff-a88baedd3b3f460db4620f1794f6ef48
but i wonder know that if I do not OPENSSL_cleanup() while the system is reboot , What will happen?
and how can i stopping all threads explicitly before closing the application ?Do you have any ideas?
thanks~

**Comment by mattcaswell** [comment]
> but i wonder know that if I do not OPENSSL_cleanup() while the system is reboot , What will happen?

It really doesn't matter. OPENSSL_cleanup() explicitly frees some global memory and possibly other global resources. Those things will get freed anyway by the OS if the application aborts or for some reason OPENSSL_cleanup() is suppressed. The only reason we need OPENSSL_cleanup() at all is that many people run tools like valgrind to check for memory "leaks" - which they will see if OPENSSL_cleanup() hasn't been called. They're not true leaks in the sense that they don't grow with time - but it doesn't stop people from seeing them and believing them to be leaks.

**Comment by YanAnzouyijun** [comment]
thank you for your reply~thanks~~~

**Comment by YanAnzouyijun** [comment]
thank you for your reply~thanks~~~

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
