### ISSUE TITLE
 error C2027: use of undefined type 'ssl_st' , while integrating openssl1.1.1b in C++ project for TLS1.3 support

### ISSUE THREAD

**Issue by kyadav78** [openssl/openssl#8705]
Hi,
   I have compiled my C++ project with openssl 1.1.1b libraries to support TLS1.3. But it is throwing below errors: 
 error C2027: use of undefined type 'ssl_st'
..openssl-1.1.1b\include\openssl/ssl.h(209): note: see declaration of 'ssl_st'
 error C2227: left of '->session' must point to class/struct/union/generic type 
could you please suggest how to fix this issue.
Regards
Kunal

**Comment by levitte** [comment]
Duplicate of #4344

**Comment by mattcaswell** [comment]
The SSL type was made opaque from OpenSSL 1.1.0+. 

https://www.openssl.org/docs/faq.html#PROG2

This means you cannot directly access members of the structure, e.g. `ssl->session` is not allowed. Instead you must use accessor functions such as `SSL_get_session`. So instead of `ssl->session` you can use `SSL_get_session(ssl)`.
