### ISSUE TITLE
Implement PKCS#11 support for 'openss cms' commands

### ISSUE THREAD

**Issue by hardfalcon** [openssl/openssl#8712]
Currently, the `openssl cms` command does not support PKCS#11, which prevents using smart cards for signing or decrypting CMS files.

**Comment by levitte** [comment]
Currently, OpenSSL has no direct support for PKCS#11 whatsoever.  There is an external PKCS#11 engine provided by the [OpenSC project's libp11](https://github.com/OpenSC/libp11), and the `openssl cms` command does support using engines with the `-engine` flag.

**Comment by mattcaswell** [comment]
As per @levitte's response there does appear to be a way to do this, so closing.

**Comment by jursed** [comment]
Found a mailing list [thread from 2016](https://mta.openssl.org/pipermail/openssl-dev/2016-March/006088.html) about incorporating PKCS#11 support natively, but apparently the idea went nowhere. It's a pity, because I don't know of any other Linux tool to sign content with (when the privkey resides on a crypto token).

**Comment by FdaSilvaYY** [comment]
some people are giving a try on this , see #8200
