### ISSUE TITLE
Add exdata to FIPS (etc) crypto objects?

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#8863]
There are a number of ways to use ex_data (as in `CRYPTO_get_ex_new_index.pod`) to cryptographic keys including the generic method using the `CRYPTO_EX_INDEX_xxx` values in `crypto.h`, and key-specific methods such as `RSA_set_ex_data()`, `EVP_MD_meth_set_app_datasize()` (sic), `EVP_PKEY_CTX_set_app_data()` and so on.

Some of those will not be available, of course, as `RSA` type isn't part of the EVP interface (via `EVP_PKEY_keygen()`), but some should still work, right?

Does the "index" value used to store type-specific exdata now vary depending on which provider or core is used?  That seems yucky, and is kind of an ABI break, since applications which used to init and have a single exdata index, now have to have more than one and know when to use each.

My suggestion is to make exdata index and instance pointer lists be a core service, but some disagree.  This discussion has wandered over multiple PR's, and @levitte rightfully suggested opening a new issue.

**Comment by mattcaswell** [comment]
> Does the "index" value used to store type-specific exdata now vary depending on which provider or core is used?

Nope. This remains exactly as it is now.

**Comment by richsalz** [comment]
> Nope. This remains exactly as it is now.

If ```CRYPTO_get_ex_new_index``` is inside the module, then this seems incorrect but maybe because that function isn't module-aware yet.  And looking at that code, since it only has the *class* index there seems to be no way to make it provider-aware.

Since the type-specific functions get a type object (e.g., ```RSA_[sg]et_ex_data``` to use our favorite example) I see how those can be module aware and dispatch to the right ```CRYPTO_[sg]et_ex_data``` but I still dont see how to set the index and callback functions done by ```CRYPTO_get_ex_new_index```

**Comment by levitte** [comment]
A side note: `EVP_MD_meth_set_app_datasize()` and `EVP_PKEY_CTX_set_app_data()` have absolutely nothing to do with exdata.

**Comment by richsalz** [comment]
You're right, I was confused by the similar names. I should have known better :)

**Comment by levitte** [comment]
> And looking at that code, since it only has the class index there seems to be no way to make it provider-aware.

@mattcaswell is making it library context aware in #8857, so if such context is allocated in the provider, it automatically becomes provider aware

**Comment by levitte** [comment]
Regarding `RSA_set_ex_data`, there are *no plans* to transfer those data to the provider, i.e. they will only be relevant within the application and the libcrypto it's linked with.

**Comment by richsalz** [comment]
So the answer is there's a new function, ```CRYPTO_get_ex_new_index_ex``` to call.  I think making the exdata a service provided by the core is simpler and requires no user code changes. But the other parts of this issue seem to still be valid anyway.

**Comment by mattcaswell** [comment]
> If CRYPTO_get_ex_new_index is inside the module, then this seems incorrect but maybe because that function isn't module-aware yet

No. It makes no difference.

Applications add ex_data to objects created in libcrypto. Those objects may themselves have references (void *) to objects held in the provider. The provider may use ex_data to store stuff in its own objects. This is entirely separate and completely distinct to the ex_data in libcrypto. Any usage of ex_data in the FIPS provider is purely *internal* only. It has nothing to do with application ex_data. libcrypto has no visibility of FIPS provider usage of ex_data, and the FIPS provider has no visibility of ex_data used in libcrypto. libcrypto can't see and doesn't about the indexes the FIPS provider creates. And the FIPS provider can't see and doesn't know about the indexes that libcrypto creates.

Most providers won't know anything at *all* about ex_data. This doesn't impact the application's ability to use it since application usage of ex_data is a libcrypto thing not a provider thing. The *only* reason we are having this discussion at all is that the FIPS module needs to use ex_data for its own internal purposes completely unrelated to application ex_data.

Application ex_data never goes anywhere near the provider. If a libcrypto side object has exdata associated with it and the libcrypto object swaps to using a different provider - it makes no difference. 

> So the answer is there's a new function, CRYPTO_get_ex_new_index_ex to call. I think making the exdata a service provided by the core is simpler and requires no user code changes. But the other parts of this issue seem to still be valid anyway.

No. This is a "red herring". `CRYPTO_get_ex_new_index_ex` is an OPENSSL_CTX aware version of `CRYPTO_get_ex_new_index`. That might be useful in libcrypto in the future but is primarily there for FIPS module usage at the moment. Actually in the latest incarnation of the #8857 PR I made it an internal function only instead of public. I do expect it to eventually become public but there is no pressing need at the moment. Existing applications that just the default OPENSSL_CTX can continue to use `CRYPTO_get_ex_new_index` with no impact.

**Comment by richsalz** [comment]
Thanks for the detailed explanation. So the plan is to add a new class index for EVP_PKEY to the public API and then providers will re-use a class index for their own internal void* objects?

**Comment by mattcaswell** [comment]
> So the plan is to add a new class index for EVP_PKEY to the public API 

If we decide to extend the ex_data capability to the EVP_PKEY API then that's the way we would do it.

> then providers will re-use a class index for their own internal void* objects?

*Only* the FIPS provider needs to do this. But yes.

**Comment by richsalz** [comment]
> If we decide to extend the ex_data capability to the EVP_PKEY API then that's the way we would do it.

Losing the ability to add exdata to key material seems like a step backwards.

**Comment by levitte** [comment]
> Losing the ability to add exdata to key material seems like a step backwards.

`EVP_PKEY` will be your application / libcrypto representative for the key material.  If you can add your ex_data to the `EVP_PKEY`, what have you lost?

**Comment by richsalz** [comment]
You can't add exdata to EVP_PKEY and Matt's comment says "maybe" about adding it.

**Comment by levitte** [comment]
I actually think we should extend the `EVP_PKEY` API to allow attached ex_data.  That, or deprecate the ex_data functionality, but I don't see that happening.

**Comment by levitte** [comment]
> and then providers will re-use a class index for their own internal void* objects?

I don't see why they would need to do that.  Provider objects will just be their blobs of data, structured in whatever way the provider authors desire, and `EVP_PKEY` will hold a pointer to such objects.  As a matter of fact, such a pointer already exists, it's called `pkey` and is currently this union:

``` C
    union {
        void *ptr;
# ifndef OPENSSL_NO_RSA
        struct rsa_st *rsa;     /* RSA */
# endif
# ifndef OPENSSL_NO_DSA
        struct dsa_st *dsa;     /* DSA */
# endif
# ifndef OPENSSL_NO_DH
        struct dh_st *dh;       /* DH */
# endif
# ifndef OPENSSL_NO_EC
        struct ec_key_st *ec;   /* ECC */
        ECX_KEY *ecx;           /* X25519, X448, Ed25519, Ed448 */
# endif
    } pkey;
```

In a provider-powered OpenSSL, I expect that union to become something like this:

``` C
    void *provider_data;
```

(although I would prefer another type than void)

**Comment by richsalz** [comment]
exdata allows arbitrary index/value sets and limiting to a single void* also seems needlessly limiting.

**Comment by levitte** [comment]
Uhmmm, the provider data pointer and the ex_data would be two different attributes in `EVP_PKEY`.

**Comment by richsalz** [comment]
much discussion, sentiment is strongly no, closing.

**Comment by levitte** [comment]
Not sure which "no" you mean.
If you mean magicking ex_data stuff all the way to the providers, then no.
If you mean adding an ex_data attribute to EVP_PKEY, I don't think we said squarely no to that, did we? That would require someone that's interested enough putting together a PR, though.

**Comment by richsalz** [comment]
#12059 covers the non-fips aspect.

**Comment by levitte** [comment]
Okie
