### ISSUE TITLE
Output argument policy on error

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#8935]
Short discussion in #8733 about the status of output arguments when a function is returning an error.  It boils down to:

1. leave them untouched
1. initialise them to something sensible

Both styles and more likely exist in the code currently.

The rationale behind the second is to be nicer to applications that don't check return codes properly.

**Comment by mattcaswell** [comment]
IMO our default position should be to leave them untouched. This might not always be feasible but should be our preferred approach.

**Comment by levitte** [comment]
Does the rest of @openssl have an opinion on this?
(I agree with @mattcaswell)

**Comment by t-j-h** [comment]
I disagree. Output arguments should always be able to be set by a function at any point. Because they can be set at any point it make sense to start with sane default values at the commencement of the function as a workable pattern.

Requiring that all functions leave output arguments unchanged on error buys you nothing in terms of caller behaviour and requires structuring all functions in a manner that holds copies of what will end up in the output arguments always and only sets the actual output arguments once the function is complete. 

I've worked in code bases with both approaches and one is clearly less error prone with respect to caller usage (sane early initialisation keeps things in a well defined state always independent of call usage).

**Comment by levitte** [comment]
Do we have any functions that regard output arguments as input arguments as well, i.e. that *modify* it?  I think it would be quite unexpected for that to happen if there was an error.

**Comment by mspncp** [comment]
It seems like we should distinguish two cases, and it is my impression that @mattcaswell, @levitte, and I had the first case in mind, while @t-j-h was thinking of the second:


The function fails because...


- ...the verification of the input parameters fails
- ...some unexpected error occurs during the function's operation


In the first case, it _makes perfect sense_ to leave the output parameters untouched. Initializing output values to some reasonable (?) value is just a waste of time with the questionable benefit that it aids the sloppy programmer who does not check his return values.

In the second case I agree with @t-j-h that it _does not make sense_ to demand unchanged output parameters. Because this would force the implementer to store the return values temporarily on the stack until he is sure that the function succeeded, or to restore the original content on error.


So neither policy is optimal. The optimal policy should be a compromise. Something like

> If the function fails, the content of the output parameters is _undefined_.

Then the implementer can choose whatever is more appropriate for his situation.

**Comment by mspncp** [comment]
> If the function fails, the content of the output parameters is _undefined_.

That said, there is one special case which should not be left undefined:

If the called function allocates one or more portions of memory on behalf of the caller, which are returned via out-pointers, then the caller should be able to expect that no memory was allocated when the function fails. This implies that if the function fails in the middle of its operation, it needs to revert all allocations made up to that point.

**Comment by richsalz** [comment]
> Do we have any functions that regard output arguments as input arguments as well, i.e. that _modify_ it? I think it would be quite unexpected for that to happen if there was an error.

all the d2i functions?

**Comment by t8m** [comment]
@mspncp summarized it quite well.

**Comment by paulidale** [comment]
Closing this since the discussion ended
