### ISSUE TITLE
Example of how to create EVP keys from ed25519 data

### ISSUE THREAD

**Issue by jeroen** [openssl/openssl#8960]
I'm trying to read ed25519 and curve25519 keys generated with ssh-keygen and sodium in openssl as EVP keys. Such public keys always consist of 32 bytes of raw data and the private key is 64 bytes for ed25519 and 32 bytes for x25519. 

Would it be possible to add a simple example to the docs how to create an `EVP_PKEY` or `EVP_KEY` from raw ed25519/x25519 data? I tried feeding the 64 bytes to `EVP_PKEY_new_raw_private_key()` but that gives an openssl error `ecx_key_op: invalid encoding`.

The other way around is also unclear to me. The [Ed25519 manual page](https://www.openssl.org/docs/manmaster/man7/Ed25519.html) does have a EVP_PKEY keygen example. However the DER serialized private key is 48 bytes (instead of 64) and the public key is 44 bytes. Is this another format?

**Comment by mattcaswell** [comment]
> I'm trying to read ed25519 and curve25519 keys generated with ssh-keygen and sodium in openssl as EVP keys. The public keys always consist of 32 bytes of data; the private key is 64 bytes for ed25519 and 32 bytes for curve25519.

"Raw" Ed25519 private and public keys are both 32 bytes in length. I'm not sure what format you have for your private key but it isn't a simple "raw" Ed25519 private key. *Possibly* it is a raw private key and public key concatenated together. Or possibly it isn't a private key at all and is an Ed25519 signature (which *is* 64 bytes in length).

> Would it be possible to add a simple example to the docs how to create an EVP_PKEY or EVP_KEY from raw ed25519/x25519 data?

You can create an EVP_PKEY from raw ed25519 key data using `EVP_PKEY_new_raw_private_key` or `EVP_PKEY_new_raw_public_key`. Both expect a key length of 32 bytes for Ed25519. See the man page here:

https://www.openssl.org/docs/man1.1.1/man3/EVP_PKEY_new_raw_private_key.html

> The other way around is also unclear to me

You can use `EVP_PKEY_get_raw_private_key` or `EVP_PKEY_get_raw_public_key` as appropriate to get hold of the raw key data (documented on the same man page as above).

> The Ed25519 manual page does have a EVP_PKEY keygen example. However the DER serialized private key is 48 bytes (instead of 64) and the public key is 44 bytes. Is this another format?

The private key is in PKCS8 format. The public key is in "SubjectPublicKeyInfo" format. There are detailed examples of the format for Ed25519 here:

https://tools.ietf.org/html/rfc8410#section-10

**Comment by jeroen** [comment]
Thanks for the clarification. I made some progress and was able to parse and import/export the openssh 32 byte public keys using `EVP_PKEY_get_raw_public_key` and `EVP_PKEY_new_raw_public_key`. 

Now I just need to find out how to convert the PKCS8 private keys into the 64 byte format from openssh / libsodium, and vice versa. I'm [not the only one ](https://github.com/openssl/openssl/issues/6357) that was expecting 64 bytes for ed25519 private keys. Perhaps the openssl/sodium format includes some additional pubkey attributes are included indeed, but I have a hard time reverse engineering their the format.

**Comment by mattcaswell** [comment]
Ah! Issue #6357 that you linked to, has a link to this blog post:

https://blog.mozilla.org/warner/2011/11/29/ed25519-keys/

At the end of that blog there is quite a useful diagram which describes the format of 64-bit NaCl ed25519 private keys. It's quite an old article so whether this is the same as the format used today in libsodium is unclear - but it seems likely.

If so it seems that the 64-bit private key is the "seed" (i.e. the OpenSSL 32-bit private key) after being run through SHA-512 and then various bits are set/cleared, i.e. these steps that are done internally in OpenSSL:

https://github.com/openssl/openssl/blob/9830e7ea42b9c0f95ea1f4b09aa2e60fa7d3115f/crypto/ec/curve25519.c#L5435-L5447
 
So, if the above is correct, then to convert an OpenSSL private key to a libsodium private key, generate the SHA-512 hash and then perform the same bitwise operations as in the above code snippet.

Unfortunately that means you won't be able to go in the other direction, i.e. convert a libsodium private key into an OpenSSL private key. This is because libsodium does not provide you with access to the 32-bit "seed", and OpenSSL does not provide a mechanism for importing the pre-processed libsodium private key. It is also impossible to reverse the 32-bit to 64-bit process manually, because of the irreversible sha512 hash that is used.

(As an aside if you re-implement the expansion shown in the above code snippet, I recommend against calling the SHA512 routines directly as is done internally. Instead you should use the EVP_Digest* functions to do the SHA512 step)

**Comment by jeroen** [comment]
Hmm not sure if that is still the case. Maybe openssh uses yet another format than nacl then. I had just discovered (by pure guessing) that I can read the private key from the initial 32 bytes of the 64 blob in the ssh private key. I have no idea what is in the remaining 32 bytes.

I checked the checksum of the private key and it matches that of the public key. However I am unable to verify if I can actually sign/verify with this keypair because `EVP_PKEY_sign_init` gives an error: ___operation not supported for this keytype___.

**Comment by mattcaswell** [comment]
> However unfortunately I am unable to test if I can actually sign/verify with this keypair because EVP_PKEY_sign_init gives an error: operation not supported for this keytype.

EVP_PKEY_sign* is intended for signing pre-hashed data. It does not support Ed25519 because we only support the "pure" variant (which doesn't allow pre-hashing). As mentioned on the Ed25519 man page you should call EVP_DigestSignInit()  with the "digest" parameter set to NULL, and then call the one-shot EVP_DigestSign() function.

**Comment by jeroen** [comment]
> EVP_PKEY_sign* is intended for signing pre-hashed data. It does not support Ed25519 because we only support the "pure" variant (which doesn't allow pre-hashing). 

Oh I wasn't aware of this limitation. So suppose we have a large file (say 10gb a linux iso) and we have the sha256 checksum, we cannot sign the checksum with ed25519? We need to read the entire iso in memory and pass it to `EVP_DigestSign()`?

**Comment by jeroen** [comment]
Actually scratch my last comment which I deleted. 

I was able to sign and verify a payload using `EVP_DigestSign` using my openssh keys. So this resolves the issue for me. It is still a mystery what is in the remaining 32 bytes of the 64 bytes openssh ed25519 private key, but afaict, everything works fine by reading the private key using only the initial 32 bytes.

**Comment by davidben** [comment]
The `crypto_sign_seed_keypair` function looks like the right one for converting from OpenSSL to libsodium.
https://libsodium.gitbook.io/doc/public-key_cryptography/public-key_signatures#key-pair-generation

For the other direction, I believe you just take the first 32 bytes.

**Comment by davidben** [comment]
(Oops. Forgot to refresh the page or something and missed this was already resolved.)
