### ISSUE TITLE
Make Makefile output more readable

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#8961]
Doing something like
```
awk '{print length;}' < Makefile | sort -nr
```
show many lines that are hundreds or thousands of characters long. This might cause problems on some sytems.  But more importantly, it is very hard on users trying to debug make/makefile issues.  It would be nice if Configure was smart about word-wrapping lines.

**Comment by levitte** [comment]
The "intelligence" sits in the build file (Makefile) templates.  The VMS `descrip.mms.tmpl` already does what you're asking for, because there are line length limitations there.  This can be done on the other templates as well...  it shouldn't even be hard.

What I've done on VMS is line breaking on per item basis.  It shouldn't be very hard to make the line breaks on 80 column basis instead, I assume that's what's desired...

**Comment by richsalz** [comment]
Slight preference for word-wrapping at 78 (80) cols, but even one item/line is better than a single 64000-character line. :)

**Comment by levitte** [comment]
Sure.  Do you dare provide a PR?  I can do that otherwise, but it'll take a few days before I get to it.

**Comment by richsalz** [comment]
I looked and I dare not touch that code, sir. :)
