### ISSUE TITLE
GENERAL_NAME_get0_value function's first parameter is not const but should be const

### ISSUE THREAD

**Issue by mlindner** [openssl/openssl#8973]
https://github.com/openssl/openssl/blob/9fdcc21fdc9d148f78d9cd5be34030f38cc45812/crypto/x509v3/v3_genn.c#L146

The function does not modify the passed in GENERAL_NAME but it is not const. Additionally, the return type is void* when in reality all of the returned types are some form of ASN1_STRING* (I believe).

**Comment by mspncp** [comment]
> The function does not modify the passed in GENERAL_NAME but it is not const.

Sounds reasonable. Would you like to create a pull request for it? Improving the const-correctness of function arguments is usually considered a non-breaking bugfix which can be cherry-picked to the 1.1.1 stable branch (see e.g. #8945).

> Additionally, the return type is void* when in reality all of the returned types are some form of ASN1_STRING* (I believe).

This is almost true, but not entirely: for example, a pointer to an `OTHERNAME` can be returned:

https://github.com/openssl/openssl/blob/9fdcc21fdc9d148f78d9cd5be34030f38cc45812/crypto/x509v3/v3_genn.c#L155-L156

https://github.com/openssl/openssl/blob/9fdcc21fdc9d148f78d9cd5be34030f38cc45812/include/openssl/x509v3.h#L113-L116

Apart from that, changing the return type of a public API function is a breaking change. It might not break C programs, but C++ programs for sure (because a void pointer can't be assigned to a pointer to a specific type without a cast).

**Comment by levitte** [comment]
> Apart from that, changing the return type of a public API function is a breaking change.

... but wasn't this about constifying *the input parameter* `a`?

**Comment by mspncp** [comment]
> ... but wasn't this about constifying _the input parameter_ `a`?

https://github.com/openssl/openssl/issues/8973#issue-446851496 consisted of two parts. I agree w.r.t part 1, but disagree w.r.t. part 2, see my response https://github.com/openssl/openssl/issues/8973#issuecomment-494775799.

1)

> The function does not modify the passed in GENERAL_NAME but it is not const.

2)

> Additionally, the return type is void* when in reality all of the returned types are some form of ASN1_STRING* (I believe).

**Comment by levitte** [comment]
Heh, I guess I zeroed in on the title a bit much...

**Comment by mspncp** [comment]
> > The function does not modify the passed in GENERAL_NAME but it is not const.
> 
> Sounds reasonable. Would you like to create a pull request for it? Improving the const-correctness of

@mlindner I added two labels as teaser for you ;-)

**Comment by mlindner** [comment]
I'm prevented from creating a pull request at the moment so I won't be able to.

**Comment by mspncp** [comment]
> I'm prevented from creating a pull request at the moment so I won't be able to.

Doesn't matter. If nobody else picks the low hanging fruit, I'll do it sometimes in the next few days.

**Comment by agnosticdev** [comment]
Pull request has been opened.
