### ISSUE TITLE
TLS 1.3 disabling ciphers and sign algos failed

### ISSUE THREAD

**Issue by wolftobias** [openssl/openssl#9025]
I want to disable TLS 1.3 to get the behavior back to act only as TLS 1.2.
I use: 
```
    SSL_CTX_set_min_proto_version(ctx, TLS1_VERSION);
    SSL_CTX_set_max_proto_version(ctx, TLS1_2_VERSION);
```

But still the TLS 1.3 sign algos are listed during handshake in 'Certificate Request'.

bad:
![image](https://user-images.githubusercontent.com/2248920/58468102-372a0680-813d-11e9-9f04-f1585de413c5.png)

good:
![image](https://user-images.githubusercontent.com/2248920/58468142-4b6e0380-813d-11e9-9987-00d9f646a78c.png)

Also disabling does`nt work, the TLS 1.3 algo always appears:
```
	SSL_set1_sigalgs_list(ssl, "DSA+SHA512:RSA+SHA512:ECDSA+SHA512:!ecdsa_secp256r1_sha256:ecdsa_secp384r1_sha384:!ecdsa_secp521r1_sha512:!ed25519:!ed448");
```

**Comment by wolftobias** [comment]
@levitte 
@richsalz 
I have a urgent customer issue here, could you please be so kind to give a first comment or opinion?!

**Comment by mattcaswell** [comment]
> But still the TLS 1.3 sign algos are listed during handshake in 'Certificate Request'.

Although these additional signature algorithms were introduced by the TLSv1.3 RFC they are backwards compatible and specified for use in TLSv1.2 as well so there is no need to suppress them in a TLSv1.2 handshake.

> Also disabling does`nt work, the TLS 1.3 algo always appears:

Did you check the return code of `SSL_set1_sigalgs_list` here? Most likely the reason you saw no difference was because this call failed. The sigalgs list is *NOT* a ciphersuite list. You cannot use the "!" character in this list. I assume libssl rejected the list because of this.

**Comment by balazskvr** [comment]
> > But still the TLS 1.3 sign algos are listed during handshake in 'Certificate Request'.
> 
> Although these additional signature algorithms were introduced by the TLSv1.3 RFC they are backwards compatible and specified for use in TLSv1.2 as well so there is no need to suppress them in a TLSv1.2 handshake.

In my understanding the backward compatibility means in this case is that the newly introduced SignatureScheme by TLS 1.3 can be mapped to the SignatureAndHashAlgorithm structure added in TLS 1.2. 
On the other sending these new schemes in a CertificateRequest (when the negotiated version is TLS 1.2) might cause issues in a client, because some of the new schemes are not defined in RFC 5246 (and enumerateds can only assume the values declared in the definition).
Is there something else described somewhere which permits the use of these in TLS 1.2?

**Comment by mattcaswell** [comment]
> Is there something else described somewhere which permits the use of these in TLS 1.2?

RFC8446 contains guidance on how to interpret these values in a TLSv1.2 context:

https://tools.ietf.org/html/rfc8446#section-4.2.3

> might cause issues in a client, because some of the new schemes are not defined in RFC 5246 

The whole point of having these things in an extension is that different implementation may support different subsets, and we have the flexibility to add new extension values at any time in the future. Any implementation that doesn't just silently ignore extension values it does not recognise is fundamentally broken IMO.

**Comment by balazskvr** [comment]
> The whole point of having these things in an extension is that different implementation may support different subsets, and we have the flexibility to add new extension values at any time in the future. Any implementation that doesn't just silently ignore extension values it does not recognise is fundamentally broken IMO.

It makes sense, thanks for clarifying how extensions should (must) be handle!

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
