### ISSUE TITLE
TLSv12 client (openssl 1.1.1) doesn't validate the TLS record layer version from server ?

### ISSUE THREAD

**Issue by hareesh-d** [openssl/openssl#9073]
1. TLSv12 Client Hello was sent using openssl 1.1.1 (TLSv13 explicitly disabled, record version is 0x0301 & Message version is 0x0303)
2. Consider a TLSv12 Server Hello received with a record version as 0x0306 (wrong minor version) and message version as 0x0303.

This case used to fail with openssl 1.0.2 branch libs due to explicit check in ssl3_get_record() function. But no failure with 1.1.1 version libs. Looks like the similar check is available in 1.1.1 also but debug flow didn't enter that part may be due to value of "s->first_packet" is 1.

Is this behavior change intentional? Can you please map it to corresponding RFC point if done due to TLSv13 implementation changes.

Thanks !!

**Comment by mattcaswell** [comment]
This change was actually implemented in OpenSSL 1.1.0 as part of the state machine rewrite (commit f8e0a557). Since this predates the TLSv1.3 implementation it is not related to the TLSv1.3 changes in 1.1.1.

I don't now recall whether this change in behaviour was intentional or not, but I suspect it was just a side effect of the state machine refactoring (and no mention of the change in behaviour is noted in the commit log or in code comments).

I can't find anything in any of the RFCs which requires us to validate this field. In the TLSv1.3 RFC it is a requirement for the sender to set it to TLSv1.2, but no requirement for the receiver to do anything with it (and in fact there is requirement that it MUST be ignored for all purposes).

So, while the change in behaviour is a little unexpected, I think it is still operating within the specification. Since its been that way for some while (since 1.1.0), I don't see any need to change it now.

**Comment by mattcaswell** [comment]
This question seems to have been answered. Closing.
