### ISSUE TITLE
Tests broken in master with enable-ec_nistp_64_gcc_128

### ISSUE THREAD

**Issue by romen** [openssl/openssl#9251]
I just noticed that with PR #9081 we introduced a regression in `ectest.c`.

This is related to #8615 which details the same failing backtrace, but was not triggered by the tests until PR #9081 was merged.

Until #8615 is addressed, my opinion is that the test here is asserting on something that we have not guaranteed in practice for a long time now:

https://github.com/openssl/openssl/blob/10c25644e362381844e0089504f0db42f029d855/test/ectest.c#L1823-L1827

Before #9081 It used to start with:
https://github.com/openssl/openssl/blob/be1dc984e1a5938170188cbdb6e536f1e7ac1656/test/ectest.c#L1823

and the only reason it was working was that there aren't multiple `EC_METHOD`s defined for `secp112r1`.

NIST P-224, P-256 and P-521 differ because on supporting 64-bit platforms the optimized `ec_nistp_64_gcc_128` can be enabled at compile time (and for `P-256` we also have the `nistz256` implementation on several platforms).

When the library is compiled with `enable-ec_nistp_64_gcc_128`, `make test` will fail at line https://github.com/openssl/openssl/blob/10c25644e362381844e0089504f0db42f029d855/test/ectest.c#L1826

this happens because, on https://github.com/openssl/openssl/blob/be1dc984e1a5938170188cbdb6e536f1e7ac1656/test/ectest.c#L1823 by default the optimized `EC_METHOD` will be used to create the returned `EC_GROUP`, but on line https://github.com/openssl/openssl/blob/be1dc984e1a5938170188cbdb6e536f1e7ac1656/test/ectest.c#L1825 the groups is created using the raw parameter values, not by name, resulting in an `EC_GROUP` associated with the generic `EC_METHOD` for prime fields.

https://github.com/openssl/openssl/blob/10c25644e362381844e0089504f0db42f029d855/test/ectest.c#L1826 will internally call https://github.com/openssl/openssl/blob/10c25644e362381844e0089504f0db42f029d855/crypto/ec/ec_lib.c#L539-L543

which in turn will call

https://github.com/openssl/openssl/blob/10c25644e362381844e0089504f0db42f029d855/crypto/ec/ec_lib.c#L882-L894

and subsequently

https://github.com/openssl/openssl/blob/10c25644e362381844e0089504f0db42f029d855/crypto/ec/ec_lcl.h#L309-L316

which fails as `group->meth` and `point->meth` differ.

**Comment by t8m** [comment]
Using secp384r1 instead should fix this, shouldn't it?

**Comment by romen** [comment]
@t8m It would hide the fact that that test fails because clearly `EC_GROUP_cmp()` has not been working as that test assumes.

When I read that test I expect that it has been written with the intent of verifying that two given `EC_GROUP` objects compare to equality when one is instantiated by name and the other is instantiated from explicit parameters (for that same name). This is simply false in OpenSSL right now.

**Comment by romen** [comment]
I mean, they compare to equality for some named curves (the majority of curves actually, because we only have alternative `EC_METHOD`s for some of the curves), but not for the most common ones: if an application had that same code to externally test in the same way that it work for NIST P-256 it would get the same failure we are seeing there even on other platforms and without passing that `enable-ec_nistp_64_gcc_128` because on arm32, arm64, x86, x86-64, sparc and many others we have `nistz256` asm methods!

So either that test is checking something abusing the public API of `EC_GROUP_cmp()` by assuming something not clearly defined about its behaviour or `EC_GROUP_cmp()` is broken because it is expected to return equality when comparing "equivalent" curves even if they internally use different methods (which is what is raised in #8615 )

**Comment by slontis** [comment]
I see this as 2 problems..
1) EC_GROUP_new_by_curve_name() and EC_GROUP_new_from_ecparameters() are selecting different methods.  I assume this is because EC_GROUP_new_from_ecparameters is using a method that has extra functions for loading. When ec_nistp_64_gcc_128 is enabled shouldnt it end up using the same method? This may not be that simple.

2) It doesnt seem logical to compare methods to see if 2 points are equal (especially for groups).
@paulidale pointed out that this could potentially become even more of an issue when ec is moved to providers.

**Comment by romen** [comment]
> 1. EC_GROUP_new_by_curve_name() and EC_GROUP_new_from_ecparameters() are selecting different methods.  I assume this is because EC_GROUP_new_from_ecparameters is using a method that has extra functions for loading. When ec_nistp_64_gcc_128 is enabled shouldnt it end up using the same method? This may not be that simple.

Until very recently (#8555) we did not have a "lookup by parameters" function, only by NID. Actually even now the lookup functionality is not entirely there, but can be implemented with wrappers around `EC_GROUP_check_named_curve()`.

Still there are 2 problems left with this:
1. this lookup is a very expensive operation in memory and operations that could open serious DoS consequences if it was done by default whenever a client sends points encoded with explicit parameters rather than named curve. A generic `EC_GROUP` must be created in `EC_GROUP_new_from_ecparameters()`, then `EC_GROUP_check_named_curve()` must be called on it to get the NID for that curve if it is one of the supported named curves doing a lot of `BN_bn2hex()` conversions and string comparisons, then an entirely new `EC_GROUP` must be created to replace the generic one if an NID is returned;
2. there are curves with same parameters but different names (aliases), so even doing what detailed above you could end up with 2 different `EC_GROUP`s, one created using a name and the other using an alias, that will have 2 different `EC_GROUP->curve_name` values and fail the comparison.

> 2. It doesnt seem logical to compare methods to see if 2 points are equal (especially for groups).

It makes sense because how to compare 2 points belonging to the same `EC_GROUP` object is defined in the associated `EC_METHOD`: https://github.com/openssl/openssl/blob/10c25644e362381844e0089504f0db42f029d855/crypto/ec/ec_lib.c#L893

Different `EC_METHOD`s may store point coordinates in different forms (e.g. affine coordinates in simple methods, different flavours of projective in specialized methods) so only the `EC_METHOD` that created an `EC_POINT` knows how to read its coordinates.

Comparing 2 `EC_POINT`s from the same `EC_GROUP` and `EC_METHOD` is in general a relatively inexpensive operation, and in general in most places our code seems to assume it is a programmer's error to create an `EC_POINT` from a `EC_GROUP`/`EC_METHOD` and then use functions from another `EC_GROUP`/`EC_METHOD` to manipulate it.

If we decide that `EC_POINT_cmp()` has to support mixing-and-matching for `EC_POINT` objects and `EC_GROUP`/`EC_METHOD` objects, then we need the `EC_POINT_cmp()` wrapper to actually take on that job, convert both points to a canonical form (e.g. affine coordinates) and compare the canonical representations instead.
But then we have a catch-22 paradox, because to compare 2 `EC_GROUP`s we need to eventually compare the 2 generators, but evaluating `EC_POINT_cmp()` on 2 `EC_POINT`s created from 2 _non-trivially-identical_ `EC_GROUP`/`EC_METHOD`s  generally should require, in addition to comparing their canonical representations, that they belong to the same _elliptic curve group_ (as in the same equation with the same parameters and the same generator, rather than the same `EC_GROUP` programming object).
When calling `EC_POINT_cmp()` from within `EC_GROUP_cmp()` the paradox is trivially solved because `EC_GROUP_cmp()` checks all the other parameters before comparing the generators, so what `EC_GROUP_cmp()` should probably do is never call `EC_POINT_cmp()` but locally do conversion to affine coordinates and compare the resulting `BIGNUM`s.
This comes at the cost of 4 extra `BIGNUM` allocations, 2 potentially computationally expensive conversions from projective to affine, and probably more computationally expensive `BN_cmp()` in affine form than in projective form.

Still I believe it's a reasonable change, but it can happen only after we solve #8615 (potentailly a behavioural change in the public API) and the ambiguity of what exactly `EC_GROUP_cmp()` should return: are two `EC_GROUP` objects identical if they represent the same identical mathematical abstraction or if they are compatible from a programming perspective?

In the latter case the programmer can reasonably assume that `EC_POINT` objects belonging to `EC_GROUP` objects for which `EC_GROUP_cmp() == true` are interoperable from a programming perspecitve.
In the first case a programmer can only assume that they belong to the same mathematical abstraction, but nothing more, so he still needs to make sure to never mix `EC_POINT`s belonging (as in _created by_) to different `EC_GROUP`s and to do conversions (`EC_POINT_get_affine(group_a, point, x, y)` + `equivalent_point_in_group_b=EC_POINT_new(group_b)` + `EC_POINT_set_affine(group_b, equivalent_point_in_group_b, x, y)`) before comparing points that belong to the same mathematical abstraction but to non-identical `EC_GROUP` objects.

All of this has implications for internal use in `libcrypto`, `libssl` and `apps/*`, and for external applications as well, because it directly affects key comparisons, which can have unexpected consequences in PKI evaluation (either through dedicated libcrypto functions or through direct manipulation at the `EC` layer) or on the state machine for handling protocols.

>    @paulidale pointed out that this could potentially become even more of an issue when ec is moved to providers.

The behaviour of `EC_GROUP_cmp()` is not clearly defined (#8615): until that is clarified it's really difficult to understand what needs to be fixed: documentation, implementations or tests?
Currently (1.02, 1.1.0, 1.1.1) the `EC` subsystem is not directly manipulated by `ENGINES`, which can at most define an alternative `EC(DSA|DH)_KEY_METHOD` to implement alternative keygen/derive/sign/verify methods but either implement their internal `EC` stack or reuse the unmodified OpenSSL one (without much flexibility in expanding it as there is no `EC_METHOD_new()` nor setters no access to inject entries in the lookup tables, OID/ASN1 details, etc.
If this is going to change with the transition to providers then yes, we need to clarify all the issues related to this and other documentation problems of EC to make sure we are internally consistent and have a clear contract for external implementations.

**Comment by slontis** [comment]
> Using secp384r1 instead should fix this, shouldn't it?

@romen Do you have any objections to me adding a PR to do this for now? - just so the build is not broken. I think we are aware of the issue.

**Comment by davidben** [comment]
We'd thought about similar issues in BoringSSL when revamping our EC code. The behavior we've settled on is:

* `EC_POINT`s remember their `EC_GROUP`s and reject operations that don't use a matching `EC_GROUP`. This avoids needing to worry about mismatched `EC_POINT` representations or things changing as we add tuned implementations for curves. We instantiate built-in curves' `EC_GROUP`s statically and ref-count custom ones, so `EC_GROUP_free` and `EC_GROUP_dup` are efficient. Note this requires making `EC_GROUP`s immutable, which is a good idea regardless. OpenSSL has a few APIs that reuse the `EC_GROUP` for configuration flags, so you'd need to ref-count some immutable core or remove those APIs. Additionally, we have an internal stack-allocatable `EC_RAW_POINT` (our EC code largely does not use `BIGNUM`) which keeps this out of point multiplication internals.
* We do not support parsing explicit EC parameters in public keys. RFC 5480 [forbids](https://tools.ietf.org/html/rfc5480#section-2.1.1) them in public keys and, in practice, no other implementation we tested allows them. Public key parsing is also security-sensitive since one parses them out of trust assertions, so it's desirable to limit supported forms. And, of course, [usual considerations](https://tools.ietf.org/html/draft-iab-protocol-maintenance-03) apply.
* However, while we don't have `EC_GROUP_new_from_ecparameters`, we *do* regretfully support the explicit ECParameters form of EC keys when parsing private keys. This is because older OpenSSLs defaulted to that form. When doing so, we [match our built-in curves](https://boringssl.googlesource.com/boringssl/+/d6f9c359d219055a89c676cb8886421b145a08da/crypto/ec_extra/ec_asn1.c#386) and instantiate the appropriate dedicated implementation. I don't think there's any reason that has to be inefficient.
* If the caller makes a custom `EC_GROUP` (please don't) out of `EC_GROUP_new_curve_GFp` and `EC_GROUP_set_generator` that happens to match a standard one, `EC_GROUP_cmp` does *not* report it as equal. OpenSSL's custom groups API splits the curve and the generator bit (another example of why #5158 is important), so trying to recognize the standard group is messy. We neither want to mix `EC_POINT`s with different representations, nor make the tuned implementations worry about incorrect base points. (Though I suppose one could transparently treat wrong bases as arbitrary points. Seems not worth it.)
* We do not support serialization of custom `EC_GROUP`s in any form. We only support such groups for a handful of legacy scenarios, which allows some simplifications.

**Comment by romen** [comment]
> > Using secp384r1 instead should fix this, shouldn't it?
> 
> @romen Do you have any objections to me adding a PR to do this for now? - just so the build is not broken. I think we are aware of the issue.

My objections would be that there is a serious risk that hiding the failure that way remove priority to fix this and especially #8615 .

That said I am not in the OMC and probably would not raise a - 1 anyway!
So please go ahead, and I will try to be more annoying in keeping up the awareness for these 2 issues until we agree on a proper solution!

**Comment by mouse07410** [comment]
@slontis Unbreaking the build is important - but why not unbreak it by fixing the problem the right way?

This
> `group->meth == point->meth`

is a distinctly weird way of comparing two EC points. I won't ask who came up with this idea - I'm asking why it's still in the code.

**Comment by slontis** [comment]
> I won't ask who came up with this idea - I'm asking why it's still in the code.
Please read all the above comments and #8615. There is more than one problem that needs to be solved the right way.

**Comment by mouse07410** [comment]
I read all of those mentioned. Yeah, I hear you - there is more than one problem...

**Comment by mattcaswell** [comment]
So the build is still broken and we need to find a way forward with this.

Does this problem only come about because of support for loading explicit curve params?

> this lookup is a very expensive operation in memory and operations that could open serious DoS consequences if it was done by default whenever a client sends points encoded with explicit parameters rather than named curve

Other than in the EC library itself do we ever internally use explicit params? I think they are rarely used in practice? In which case perhaps we should just caveat the functions in the docs with suitable warnings that they might be slow (and take the hit to convert them on load)

OR

Another thought would be to caveat those functions by saying that groups loaded that way will fail to match "standard" built in curves with the same params. We could also provide a function to "convert" a group built from explicit params to an equivalent built-in group.

**Comment by romen** [comment]
The build being broken actually is entirely because the test as it is written matches one interpretation of the doc of EC_GROUP_cmp() but does not match how the library actually behaves internally: comparing a builtin named group against a builtin group defined by explicit parameters does not work if the builtin group supports a specialized method. 

This is true also in 1.1.1, 1.1.0 and 1.0.2.

This test has not failed before just because it has been written to only test a single specific curve for which we only have the generic method.

So, to move forward and fix the build, we could recreate what is tested in the other releases and pick a FIPS supported curve for which there is no specialized method as suggested.

Removing support for explicit parameters is quite a breaking change for existing users (also because in 1.0.2 the default is to encode with explicit params on keygen).

Regarding usage in situations different from key loading, technically in TLS the use of EC explicit parameters is now deprecated at the standardization level, but I don't know what we would break for legacy applications disabling it.

**Comment by mattcaswell** [comment]
>The build being broken actually is entirely because the test as it is written matches one interpretation of the doc of EC_GROUP_cmp() but does not match how the library actually behaves internally: 

So we should fix the documentation to match what is actually implemented?

> So, to move forward and fix the build, we could recreate what is tested in the other releases and pick a FIPS supported curve for which there is no specialized method as suggested.

If we fix the documentation to match what is actually implemented that seems reasonable,.

**Comment by romen** [comment]
Opened #9474 to temporarily work around the problem as suggested by @t8m and @slontis , until we address #8615.

 

> > The build being broken actually is entirely because the test as it is written matches one interpretation of the doc of EC_GROUP_cmp() but does not match how the library actually behaves internally:
> 
> So we should fix the documentation to match what is actually implemented?
> 

I would like to have an OMC opinion about this to address #8615 (but it's better to discuss it over there). The reason why I need directions from the OMC is that either way we end up breaking something:

- fixing documentation is a breaking change as that documentation is currently wrong also for 1.0.2, 1.1.0, 1.1.1
- clarifying the documentation and ensuring that `EC_GROUP_cmp()` returns true for `EC_GROUP`s that are mathematically identical but programmatically incompatible should as well go back to all active branches

**Comment by kroeckx** [comment]
Is this still an issue?

**Comment by t8m** [comment]
The tests work correctly due to #9474 although the original issue #8615 is unfixed. I am closing this one as the #8615 is sufficient to track the EC_GROUP comparison problem.
