### ISSUE TITLE
avoid requirement for complete OSSL_PARAM structure declaration

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#9525]
avoid requirement for complete OSSL_PARAM structure declaration

After compare of current (2019-08-03) master code with previous installation I note that header "evp.h" includes in addition "params.h". As result indirectly is available declaration of all structures.

Side effect of such modification as that now all OpenSSL public structures are declared even for code never use them.

It seems to me params.h is added as is used construction 'OSSL_PARAM params[]' (1). From language point of view it is same as 'OSSL_PARAM *params' (2). The main difference is that first require qualified parameter.

In both cases function argument is read is "many parameters".

After review of implementation I note that parameter is similar to use of "string" - "(null)" terminated array of elements. String function uses '*var' notation even the fact that type is qualified because is base type. Use of non usual construction reduces readability of code.

Also as second construction hides implementation details this is more in unison with OpenSSL 1.1+ rules.
Today is array but tomorrow it could be changed. First construction will require changes in function declaration! Second is just fine.

What about to use only 'type *foo' construction everywhere?

**Comment by paulidale** [comment]
One of the intentions of OSSL_PARAM is for it to be a public structure.  The rationale is that third parties will be writing providers and there needs to be a standard way to communicate with the provider.  Because providers are intended to work with multiple versions of OpenSSL, the mechanism used cannot easily be changed -- it needs to be stable from an ABI viewpoint.
