### ISSUE TITLE
test failures with no-pic

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#9568]
when configuring master @ 1a2a3a420609c2d540b544e5ae829a3cb468a6e3
with `./config no-pic` some test cases fail:
```
Test Summary Report
-------------------
../test/recipes/30-test_evp.t                    (Wstat: 2816 Tests: 14 Failed: 11)
  Failed tests:  1-2, 4, 6-13
```
lots of ciphers like AES-128-CBC and so on fail to load.
That is a no-go for me.

**Comment by kroeckx** [comment]
It works if you combine it with no-shared.

**Comment by bernd-edlinger** [comment]
Some of our travis build specs are affected by this.

**Comment by kroeckx** [comment]
They seem to be mingw builds. I didn't expect to need to pass
no-pic for them. I don't know enough about Windows dlls, but I
maybe we should just not pass -fPIC to gcc when building for
Windows. At least NOTES.WIN doesn't say that we need to pass
no-pic. I have no idea about the assembler, I suspect that on
Windows we want the non-PIC code, so that might make sense to
enable non-pic for Windows builds. But if Windows needs that,
it should be the default.

I don't understand why no-pic no-shared works. From my
understanding, no-pic should automatically do no-shared
no-modules, and no-modules should do no-fips no-legacy.
And `perl configdata.pm --dump` seems to suggest that that is what
happened. But the backtrace is from the fips module, so clearly
something related to this is broken.

**Comment by levitte** [comment]
I suspect it's this:

https://github.com/openssl/openssl/blob/c04a9916d4443a805d11a467d69585e514b50296/test/recipes/30-test_evp.t#L17

We're not looking at all if there's anything in the build that might make some of those configs impossible.  Fix coming up.

**Comment by levitte** [comment]
This should be possible to verify on any platform, really.

**Comment by kroeckx** [comment]
I still think there is something else wrong. no-pic, which should
imply no-shared and no-fips, created a fips.so, it shouldn't.

**Comment by levitte** [comment]
That's weird...  I did try a `./config no-pic` and looked in the resulting Makefile, and could find no such thing...

**Comment by bernd-edlinger** [comment]
does this imply that no-pic does not have legacy support?

**Comment by levitte** [comment]
> does this imply that no-pic does not have legacy support?

Yes

**Comment by bernd-edlinger** [comment]
There are lots of embedded targets which are statically linked.

**Comment by levitte** [comment]
Do they normally use legacy algorithms?  Note that the legacy algorithms are those that we have disabled by default anyway...

**Comment by kroeckx** [comment]
On Sun, Aug 11, 2019 at 11:56:31PM -0700, Richard Levitte wrote:
> > does this imply that no-pic does not have legacy support?
> 
> Yes

That seems to be yet an other reason why nothing should move to
the legacy provider at this time.

**Comment by mattcaswell** [comment]
>> does this imply that no-pic does not have legacy support?
>
> Yes

There seems no reason why we couldn't make the legacy provider (optionally) built-in, which would mean no-pic should work.

**Comment by levitte** [comment]
> (optionally)

Does that mean doing a bit like we do with the engines in `engines`, i.e. make them built-in if modules aren't supported by configuration, or do you intend the "option" to be more explicit?

**Comment by mattcaswell** [comment]
> Does that mean doing a bit like we do with the engines in engines, i.e. make them built-in if modules aren't supported by configuration, or do you intend the "option" to be more explicit?

Perhaps both, i.e. make it an explicit option that becomes automatically set on no-pic.
