### ISSUE TITLE
Replace "period space space" with "period space"

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#9593]
There are many places where we use two spaces after a period:
```
; g grep --fixed '.  '|grep -v -i license | wc
    582    6479   54832
```
(The second grep is to remove the license text)

There are many more that have a single space:
```
; g grep '\. [^ ]' | wc
   5874   66390  563070
```

Do we want to fix these to use a single space?  And update doc-nits to prevent backsliding? :)

I'm willing to do the PR if there's interest.

**Comment by levitte** [comment]
In the case of PODs, we should really standardise on breaking the lines after each such period instead of fighting over the amount of spaces.  That leaves it to local standards to decide how many spaces should follow each period (and other sentence endings, but we only use periods, don't we?)

**Comment by kaduk** [comment]
> we only use periods, don't we?

‽

**Comment by levitte** [comment]
[g] I would so love to see the interrobang in a manual somewhere

**Comment by richsalz** [comment]
I am willing to do that (break lines at each sentence-end) if the team wants.

**Comment by levitte** [comment]
I was planning on doing something like that, but haven't hurried. If you're willing to take that bit, that would be awesome.

Be careful with code blocks, yeah?

**Comment by bernd-edlinger** [comment]
BTW: the habit with period + 2 spaces is from GNU, GCC has that all over.
once you write code for both code bases that might introduce those in the wrong way.

So apologies.

**Comment by levitte** [comment]
Heh...  if I'm not mistaken (this is my admittedly blurry recollection from some time in the early 90's), the GNU folks drew their inspiration from TeX / LaTeX, which adds extra space after sentence endings, and decided on a standard that emulates the same thing with monospace fonts.  Hence, two spaces.

I habitually did this already then, and have consistently written my texts in OpenSSL source that way since very early on.  So, er, while apologies are appreciated, they are really not necessary :wink:

**Comment by richsalz** [comment]
After discussion in #9606, the project doesn't consider this an issue to be addressed.  Closing.
