### ISSUE TITLE
TLS 1.3 support

### ISSUE THREAD

**Issue by stas730** [openssl/openssl#963]
I need TLS 1.3 for more security. Why it not supported in OpenSSL? Or I can create TLS 1.3-compatible certificate?

**Comment by ghedo** [comment]
> Why it not supported in OpenSSL?

I would imagine it's because TLS 1.3 is still a draft.

While I'm not an OpenSSL developer, I have been looking into implementing parts of  TLS 1.3 (e.g. 1-RTT handshake and HKDF-based key schedule) as a hobby project, but I haven't gotten very far (mostly due to lack of time).

> Or I can create TLS 1.3-compatible certificate?

No idea what a TLS 1.3-compatible certificate is....

**Comment by mattcaswell** [comment]
The standard for TLS1.3 has not yet been finalised. A future version of OpenSSL will support it.

**Comment by stas730** [comment]
Future version?
TLS 1.3 will be new version or TLS 1.2 with some restrictions?

**Comment by mattcaswell** [comment]
TLS1.3 is significantly different to TLS1.2 (they could have called it TLS2.0!!). We will add support in a future version.

**Comment by J0WI** [comment]
@mattcaswell asking for reopen since first implementations are available (e.g. Firefox/NSS).
https://github.com/tlswg/tls13-spec/wiki/Implementations
https://twitter.com/dougturner/status/739867613451280384

**Comment by mattcaswell** [comment]
Re-opened against the "Post 1.1.0" milestone.

**Comment by ddillard** [comment]
Will TLSv1.3 be added to 1.0.2?  1.1.0?  Both?

**Comment by levitte** [comment]
The closest possible openssl version where it would appear is 1.1.1.  We'll see where it'll end up, it depends on what API changes are needed. Worst case scenario is 1.2.0

**Comment by richsalz** [comment]
It's a new feature.  It will not be in an existing release.

**Comment by noloader** [comment]
Please forgive my ignorance... How do we enable TLS1.3?

Working from Master:

```
$ ./config shared tls13
Operating system: x86_64-whatever-linux2
Configuring OpenSSL version 1.1.1-dev (0x10101000L)
target already defined - linux-x86_64 (offending arg: tls13)
$ ./config shared tls1.3
Operating system: x86_64-whatever-linux2
Configuring OpenSSL version 1.1.1-dev (0x10101000L)
target already defined - linux-x86_64 (offending arg: tls1.3)
$ ./config shared tls2
Operating system: x86_64-whatever-linux2
Configuring OpenSSL version 1.1.1-dev (0x10101000L)
target already defined - linux-x86_64 (offending arg: tls2)
```

From above it sounds like TLS1.3 is enabled. However, running the self tests indicate its not enabled:

```
../test/recipes/70-test_clienthello.t ...... ok
../test/recipes/70-test_key_share.t ........ skipped: test_key_share needs TLS1.3 enabled
../test/recipes/70-test_packet.t ........... ok  
...
```

**Comment by welwood08** [comment]
@noloader `enable-tls1_3`

**Comment by richsalz** [comment]
And FYI, it's not complete, doesn't work, is a WIP, etc. :)

**Comment by TerraX-net** [comment]
nginx tested with enable-tls1_3:
Please don't miss to make TLSv1.3-only possible, altough it's negotiated someway inside TLS 1.2.
ssl_protocols TLSv1.2; --> will have TLS1.2 + 1.3 enabled.
ssl_protocols TLSv1.3; --> nginx: [emerg] invalid value "TLSv1.3"
Off topic: ssl_ecdh_curve secp521r1:**x**25519:secp384r1; -> error. You have to write **X**25519. (Still hoping for X448 for the first place)

**Comment by mattcaswell** [comment]
> nginx tested with enable-tls1_3:
> Please don't miss to make TLSv1.3-only possible, altough it's negotiated someway inside TLS 1.2.
> ssl_protocols TLSv1.2; --> will have TLS1.2 + 1.3 enabled.
> ssl_protocols TLSv1.3; --> nginx: [emerg] invalid value "TLSv1.3"
> To just use TLS13-* ciphers feels dirty.

This is an nginx issue. nginx will need to be updated to know about TLSv1.3. Looking at the code they are using the "old" way of doing this using the SSL_OP_NO_TLS* options. They need to update to use SSL_CTX_set_max_proto_version() and SSL_CTX_set_min_proto_version().

This works at the moment because the protocols are all on. The absence of a protocol from the "ssl_protocols" directive has the effect of asking nginx to switch that protocol off. Because nginx doesn't know about TLSv1.3 it never asks to turn that one off. I wonder what happens if you don't specify any "ssl_protocols"??

> I tested a little bit: even if I have secp521r1:secp384r1:X25519 chrome dev 58 and openssl itself are using X25519. if I remove X25519 from the list, no client (nightly 54/chrome58/openssl master from today) can't connect.

Not sure what groups chrome supports. OpenSSL supports all of the above but chrome may not. However chrome always sends an X25519 key_share. If OpenSSL is configured without X25519 support and it encounters a client that sends X25519 key_shares it is going to fail until !2341 is merged (HelloRetryRequest). Without HelloRetryRequest support the server cannot ask for a different key_share that it does support.

**Comment by noloader** [comment]
@mattcaswell, 

> They need to update to use SSL_CTX_set_max_proto_version() and SSL_CTX_set_min_proto_version().

It looks like the [SSL_CTX_set_min_proto_version/SSL_CTX_set_max_proto_version man page](https://www.openssl.org/docs/man1.1.0/ssl/SSL_CTX_set_max_proto_version.html) is maxed at `TLS1_2_VERSION`.

**Comment by davidben** [comment]
(Chrome supports X25519, P-256, and, P-384. Anything other than X25519 needs HelloRetryRequest.)

**Comment by mattcaswell** [comment]
@noloader,
>It looks like the SSL_CTX_set_min_proto_version/SSL_CTX_set_max_proto_version man page is maxed at TLS1_2_VERSION.

Not in the master version of these man pages (which is where the TLSv1.3 support is):
https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_min_proto_version.html

**Comment by TerraX-net** [comment]
> I tested a little bit: even if I have secp521r1:secp384r1:X25519 chrome dev 58 and openssl itself are using X25519. if I remove X25519 from the list, no client (nightly 54/chrome58/openssl master from today) can't connect.

Now, I had to remove legacy code in nginx to let it only pass a curve list to openssl to be still able to use X25519.
If my (bad) curve list is secp521r1:**prime256v1**:secp384r1:X25519 (prefer server ciphers), chrome dev 58.0.3013.3 on linux64 will use X25519, **but it should use P-256**.
After I removed X25519 from the list, P-256 is used as expected (so the new HelloRetryRequest works to override chrome's x25519 keyshare :thumbsup:). 9 days ago (without HelloRetryRequest) I got an error here.
Preferring the server cipherlist works as expected, but not with the curves.

**Comment by mattcaswell** [comment]
> If my (bad) curve list is secp521r1:prime256v1:secp384r1:X25519 (prefer server ciphers), chrome dev 58.0.3013.3 on linux64 will use X25519, but it should use P-256.
After I removed X25519 from the list, P-256 is used as expected (so the new HelloRetryRequest to override chrome's x25519 keyshare works :+1:). 9 days ago (without HelloRetryRequest) I got an error here. A P-384 ECDSA certificate is used.

What you are describing is correct and expected behaviour. TLSv1.3 works quite differently to <= TLSv1.2 in this respect. In TLSv1.3 the *client* chooses the curve. In chrome's case it *always* chooses X25519. Only if the client's choice is not acceptable to the server does the server then have a go. In that case it sends a HelloRetryRequest back to the client stating its preferred curve and the client has to send a new ClientHello, this time with the new curve selection. If you remove X25519 from the list of curves acceptable to the server then you are forcing the HelloRetryRequest route - which is expensive because it requires an additional round trip.

**Comment by TerraX-net** [comment]
My plan was to set X448:secp521r1:secp384r1:X25519 as curve list for confidential contents some day.
So now there would be a need to remove X25519 from the list (wouldn't work if P-384 would be preferred from the client), to hack the protocol (is this even possible in this case) or to have browser vendors preferring X448 over X25519 and hoping that no server is offering X448 without a need (but then it would be impossible as client to really choose the safest option in a particular case because no one had X448 in the list).
I don't think browsers will show the users a dropdown to select the strongest curve for a particular site, like financial transactions or sensible work.
Oh my god. There would be no longer an option to provide something like a fallback. Only something like example.com has a javascript making connection tests and redirects to the subdomain with the strongest curve, like x448-only.example.com. That would be horrible.
Then it would be more efficent to keep using TLS 1.2? I was happy about the improvements with client certificates in 1.3. I can't believe this. I expected TLS 1.3 to have the same capabilities as 1.2 with the same count of roundtrips as 1.2 has.

**Comment by davidben** [comment]
The exact server selection algorithm isn't quite specified. A server which wishes to use its preference would simply select the curve without reference to key_shares and then decide whether or not to send HelloRetryRequest based on that. That's what BoringSSL does since it's easier to reason about than a mixed client/server preference algorithm, and it didn't seem we needed anything more complex yet. I believe NSS will enforce its preference but also has some equipreference notion between, say P-256 and X25519?

**Comment by mattcaswell** [comment]
> I expected TLS 1.3 to have the same capabilities as 1.2 with the same count of roundtrips as 1.2 has.

Well, TLS 1.3 has less round trips than TLS1.2 to start with, so even if there is an additional HelloRetryRequest round trip then its no worse than TLS1.2.

>  That's what BoringSSL does since it's easier to reason about than a mixed client/server preference algorithm, and it didn't seem we needed anything more complex yet.

Hmmm. @davidben, so does this mean that Boring may issue an HRR even if the offered key_share is for an acceptable curve? i.e. if there is a different curve that both client and server supports and that curve is preferred by the server to the one provided in the key_share? That seems quite surprising to me. I suppose OpenSSL could offer that behaviour as an option if there was demand for it.

**Comment by TerraX-net** [comment]
A server admin could benefit from less round trips, if he doesn't enforce the server preference, leaves the default curve list (or set auto), or if he would set a realistic curve list with x25519 at the beginning (so knowing what browsers do), otherwise it's his decision to not benefit from less rounds trips, but to have the other benefits from 1.3 with then the same count of round trips as 1.2 has.
So I didn't understand OpenSSL's behavior here to ignore the exact curve list although there are tree options to gain more speed. I don't think somebody with a custom curve list only wanted to reduce the quantity of curves, but also to intentional set another order.

**Comment by davidben** [comment]
@mattcaswell With our current behavior, that's right. Our servers only accept X25519 and P-256, so this would only come up if a client supports both curves but only predicts P-256 for some bizarre reason.

I figured we'd just do the simplest option (keep the selection algorithm same as before) and, if the ecosystem evolves such that something else is preferable, we'll go implement it then. But I actually expect this algorithm will work just fine.

**Comment by richsalz** [comment]
"If the ecosystem evolves"  Unh huh.

**Comment by davidben** [comment]
@richsalz I don't catch your meaning there. (I meant the TLS 1.3 ecosystem doesn't exist yet, and such things change over time gradually, so one cannot easily predict things with certainty yet.)

**Comment by istandready** [comment]
I read the OpenSSL blog https://www.openssl.org/blog/blog/2016/10/24/f2f-roadmap/, it shows that the TLS 1.3 will be implemented by OpenSSL 1.1.1. 

Does anyone know
1) When the OpenSSL 1.1.1 will be released? April 5th 2017? 
2) Will TLSv1.3 be added to 1.0.2? 

Thanks a lot!

**Comment by mattcaswell** [comment]
> When the OpenSSL 1.1.1 will be released? April 5th 2017?

We are aiming to have the core TLSv1.3 support in place in master by 5th April. We have not as yet announced a release date for OpenSSL 1.1.1. Note that TLSv1.3 has not yet been finalised by IETF.

> Will TLSv1.3 be added to 1.0.2?

No. 1.0.2 is a stable branch and doesn't receive new features.

**Comment by Henrocker** [comment]
Hi,

when I compile nginx against the current master (compiled today), and add the option `--with-openssl-opt=enable-tls1_3` when configuring nginx, I am still not able to use TLS 1.3.

`nginx -V` gives me: 

```
nginx version: nginx/1.11.10
built by gcc 6.3.0 20170316 (Debian 6.3.0-9)
built with OpenSSL 1.1.1-dev  xx XXX xxxx
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=www-data --group=www-data --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-file-aio --with-threads --with-http_v2_module --with-ld-opt=-lrt --add-module=/root/my-nginx/ngx_brotli --add-module=/root/my-nginx/nginx-module-vts --add-module=/root/my-nginx/headers-more-nginx-module --with-openssl=/root/my-nginx/openssl --with-openssl-opt=enable-tls1_3
```

And I use the following Ciphersuites:

```
TLS13-AES-128-GCM-SHA256
TLS13-AES-256-GCM-SHA384
TLS13-CHACHA20-POLY1305-SHA256
```

Any idea?
Thanks

**Comment by mattcaswell** [comment]
So what makes you think TLSv1.3 is not working?
Most likely you are hitting problems because of this:

https://mta.openssl.org/pipermail/openssl-dev/2017-March/009146.html

**Comment by Henrocker** [comment]
@mattcaswell Thank you for your quick response. I do think that is causing the problem indeed, as even the current latest Chrome Canary does not support TLSv1.3 yet. 
Thanks

**Comment by Night1** [comment]
@mattcaswell I was hitting same issue, thank you for clarification

**Comment by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [comment]
is tlsv1.3 support in master now since it is after april 5?

**Comment by mattcaswell** [comment]
TLSv1.3 draft-19 support is in master if you "config" with "enable-tls1_3". Note that draft-19 is not compatible with draft-18 which is still be used by some other libraries. Our draft-18 version is in the tls1.3-draft-18 branch.

**Comment by Henrocker** [comment]
So no official OpenSSLv1.1.1 release in the near future, until TLS is no longer in draft-state, right?

**Comment by mattcaswell** [comment]
Right - although hopefully it won't be too much longer until they take it out of draft!!

**Comment by peterkahl** [comment]
Yesterday/today the nginx version 1.13.0 was released, advertising support for TLSv1.3.

I have compiled the nginx 1.13.0 with OpenSSL 1.1.1-dev and the nginx option `--with-openssl-opt=enable-tls1_3`.

Using Firefox and Chrome I am unable to verify TLSv1.3 operation.

**Comment by richsalz** [comment]
You need to use the "draft-18" branch of openssl as those browsers are on draft-18 and openssl master is on draft-19.

**Comment by peterkahl** [comment]
@richsalz Thanks!

**Comment by peterkahl** [comment]
@richsalz Works! 😎

**Comment by jauderho** [comment]
This is odd. I can't seem to checkout or see the draft-18 branch.

git branch -v -a only shows master as the available branch even though I can clearly see it in the github interface. Halp?

**Comment by CHERTS** [comment]
to @jauderho 
git clone https://github.com/openssl/openssl.git -b tls1.3-draft-18 openssl-1.1.1-tls1.3-draft-18

**Comment by Henrocker** [comment]
git clone -b tls1.3-draft-18 --single-branch https://github.com/openssl/openssl.git openssl

**Comment by peterkahl** [comment]
What I did was git clone the specific branch. 
Perhaps you could try googling 'git clone GitHub branch'.
You will need to specify that exact branch name.
Then compile.

**Comment by jauderho** [comment]
Thanks, that worked! Compiling now...

**Comment by Henrocker** [comment]
You need to specify TLS 1.3 Ciphers. Not just enable TLS 1.3

**Comment by noloader** [comment]
> Well, that was interesting. Trying to connect with openssl s_client returns:

Please show the actual command you used.

**Comment by Night1** [comment]
With nginx 1.13.0 you need to also add TLSv1.3 in protocol just like with TLSv1.2 for TLSv1.3 to work.
"ssl_protocols TLSv1.2 TLSv1.3;"

New, TLSv1.3, Cipher is TLS13-CHACHA20-POLY1305-SHA256
Server public key is 384 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS13-CHACHA20-POLY1305-SHA256
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: ----- snip -----
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1493194404
    Timeout   : 7200 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
    Extended master secret: no

**Comment by redhell** [comment]
openssl s_client -connect 127.0.0.1:443 
https://wiki.openssl.org/index.php/Manual:S_client(1)

**Comment by Night1** [comment]
@redhell try

openssl s_client -connect 127.0.0.1:443 -tls1_3

**Comment by mattcaswell** [comment]
> openssl s_client -connect 127.0.0.1:443 -tls1_3

That forces *only* TLSv1.3 which shouldn't be necessary: s_client should negotiate TLSv1.3 anyway as long as it has been enabled in the OpenSSL build and the server supports it.

**Comment by Night1** [comment]
You are right mattcaswell, I would expect an error there, as I belive error is in his nginx config.

**Comment by jauderho** [comment]
Looks like that is the case. I was not aware that I had to put in TLSv1.3 specific ciphers.

Previously,
`    ssl_ciphers 'EECDH+CHACHA20:EECDH+AESGCM:EECDH+AES:!SSLv3:!AESCCM';`

Now,
`    ssl_ciphers 'TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-256-GCM-SHA384:TLS13-AES-128-GCM-SHA256:EECDH+CHACHA20:EECDH+AESGCM:EECDH+AES:!SSLv3:!AESCCM';`

Seems to work now.

**Comment by mattcaswell** [comment]
> Looks like that is the case. I was not aware that I had to put in TLSv1.3 specific ciphers.

Yes, unfortunately I expect that will be a common misconfiguration issue. I have committed today to the master branch some sanity checks that will abort early on with an error message which will hopefully give a better clue as to the issue.

**Comment by Henrocker** [comment]
@mattcaswell Would you mind merging sanity checks into tls1.3-draft-18, too? As this branch currently is de facto most spreaded for at least web servers.

**Comment by mattcaswell** [comment]
> Would you mind merging sanity checks into tls1.3-draft-18, too? As this branch currently is de facto most spreaded for at least web servers.

I actually already have a WIP cherry-pick of those checks to the draft-18 branch. Unfortunately the tests seem to be failing on that branch at the moment for unknown reasons. I'll try and figure it out tomorrow.

**Comment by Henrocker** [comment]
@mattcaswell Does master now deliver draft-20 already? As I've seen Commits that change version to draft-20.

**Comment by mattcaswell** [comment]
Yes, master is now at draft-20:

https://mta.openssl.org/pipermail/openssl-dev/2017-May/009319.html

There is also a draft-19 branch in addition to the draft-18 branch if you want to stick with those older versions.

**Comment by Henrocker** [comment]
@mattcaswell Perfect! Should have a look at your MTA more often :)!

Cheers

**Comment by mattcaswell** [comment]
> I actually already have a WIP cherry-pick of those checks to the draft-18 branch. Unfortunately the tests seem to be failing on that branch at the moment for unknown reasons. I'll try and figure it out tomorrow.

I fixed those test issues but I just realised that I forgot to actually push the commits to the draft-18 branch. I have done so now.

**Comment by Henrocker** [comment]
Very attentive. Thanks

**Comment by mattcaswell** [comment]
Please see this blog post for some info on the issues you need to keep in mind when using TLSv1.3 with OpenSSL (for both application developers and application deployers).

https://www.openssl.org/blog/blog/2017/05/04/tlsv1.3/

**Comment by iz8mbw** [comment]
What is the "most appropriate" command (Linux) to download the last version of OpenSSL tls1.3-draft-18?

**Comment by Henrocker** [comment]
git clone -b tls1.3-draft-18 --single-branch https://github.com/openssl/openssl.git openssl

**Comment by noloader** [comment]
> What is the "most appropriate" command (Linux) to download the last version of OpenSSL tls1.3-draft-18?

More generally:

```
$ git clone https://github.com/openssl/openssl
$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/OpenSSL-engine-0_9_6-stable
  remotes/origin/OpenSSL-fips-0_9_7-stable
  remotes/origin/OpenSSL-fips-0_9_8-stable
  remotes/origin/OpenSSL-fips-1_2-stable
  remotes/origin/OpenSSL-fips-2_0-dev
  remotes/origin/OpenSSL-fips-2_0-stable
  remotes/origin/OpenSSL-fips2-0_9_7-stable
  remotes/origin/OpenSSL_0_9_6-stable
  remotes/origin/OpenSSL_0_9_7-stable
  remotes/origin/OpenSSL_0_9_8-stable
  remotes/origin/OpenSSL_0_9_8fg-stable
  remotes/origin/OpenSSL_1_0_0-stable
  remotes/origin/OpenSSL_1_0_1-stable
  remotes/origin/OpenSSL_1_0_2-stable
  remotes/origin/OpenSSL_1_1_0-stable
  remotes/origin/SSLeay
  remotes/origin/master
  remotes/origin/tls1.3-draft-18
  remotes/origin/tls1.3-draft-19
```

**Comment by iz8mbw** [comment]
Thank you!

**Comment by Night1** [comment]
@nolander git checkout tls1.3-draft-19

**Comment by NeetishPathak** [comment]
Is session resumption functional in tls1.3-draft-20. I am building independent client server application to do latency experiments for handshake. I observer the connection getting successful but new_session_cb is never getting invoked on the client side which is a problem if I need to make use of resumptions. With the same implementation, as soon as I switch to TLS 1.2, bo works like a charm. Anyone has used TLS1.3 for session resumption here? Thanks

**Comment by mattcaswell** [comment]
See my response to your question on openssl-users. (summary: you need to make sure you are reading application data from the client, otherwise it won't see the post-handshake session information from the server).
