### ISSUE TITLE
Fail to compile on Windows x64 MSVC 2015: error in crypto\chacha\chacha-x86_64.asm

### ISSUE THREAD

**Issue by rustyx** [openssl/openssl#967]
Checkout current master branch, open `VS2015 x64 Native Tools Command Prompt`,

```
perl Configure VC-WIN64A
nmake
```

Results in

```
        cl -DOPENSSL_USE_APPLINK -DDSO_WIN32 -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM "-DENGINESDIR=\"%ProgramW6432%\\OpenSSL\\lib\\engines\"" "-DOPENSSLDIR=\"%CommonProgramW6432%\\SSL\"" -W3 -wd4090 -Gs0 -GF -Gy -nologo -DOPENSSL_SYS_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DUNICODE -D_UNICODE /MD /Ox /O2 /Ob2 /Zi /Fdlib /I include /I . /I crypto\include -c /Focrypto\cast\c_enc.obj crypto\cast\c_enc.c
c_enc.c
        cl -DOPENSSL_USE_APPLINK -DDSO_WIN32 -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM "-DENGINESDIR=\"%ProgramW6432%\\OpenSSL\\lib\\engines\"" "-DOPENSSLDIR=\"%CommonProgramW6432%\\SSL\"" -W3 -wd4090 -Gs0 -GF -Gy -nologo -DOPENSSL_SYS_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DUNICODE -D_UNICODE /MD /Ox /O2 /Ob2 /Zi /Fdlib /I include /I . /I crypto\include -c /Focrypto\cast\c_ofb64.obj crypto\cast\c_ofb64.c
c_ofb64.c
        cl -DOPENSSL_USE_APPLINK -DDSO_WIN32 -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM "-DENGINESDIR=\"%ProgramW6432%\\OpenSSL\\lib\\engines\"" "-DOPENSSLDIR=\"%CommonProgramW6432%\\SSL\"" -W3 -wd4090 -Gs0 -GF -Gy -nologo -DOPENSSL_SYS_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DUNICODE -D_UNICODE /MD /Ox /O2 /Ob2 /Zi /Fdlib /I include /I . /I crypto\include -c /Focrypto\cast\c_skey.obj crypto\cast\c_skey.c
c_skey.c
        set ASM=ml64
        set CC=cl
        C:\Perl64\bin\perl.exe crypto\chacha\asm\chacha-x86_64.pl auto crypto\chacha\chacha-x86_64.asm
        ml64 /c /Cp /Cx /Zi /Focrypto\chacha\chacha-x86_64.obj crypto\chacha\chacha-x86_64.asm
Microsoft (R) Macro Assembler (x64) Version 14.00.23506.0
Copyright (C) Microsoft Corporation.  All rights reserved.

 Assembling: crypto\chacha\chacha-x86_64.asm
crypto\chacha\chacha-x86_64.asm(1540)ed size
crypto\chacha\chacha-x86_64.asm(1540) : error A2070:invalid instruction o˔crypto\chacha\chacha-x86_64.asm(1541)ed size
crypto\chacha\chacha-x86_64.asm(1541) : error A2070:invalid instruction o˔crypto\chacha\chacha-x86_64.asm(1542)ed size
crypto\chacha\chacha-x86_64.asm(1542) : error A2070:invalid instruction o˔crypto\chacha\chacha-x86_64.asm(1543)ed size
crypto\chacha\chacha-x86_64.asm(1543) : error A2070:invalid instruction ocrypto\chacha\chacha-x86_64.asm(1610)ed size
crypto\chacha\chacha-x86_64.asm(1610) : error A2070:invalid instruction ocrypto\chacha\chacha-x86_64.asm(1628)ed size
crypto\chacha\chacha-x86_64.asm(1628) : error A2070:invalid instruction ocrypto\chacha\chacha-x86_64.asm(1645)ed size
crypto\chacha\chacha-x86_64.asm(1645) : error A2070:invalid instruction ocrypto\chacha\chacha-x86_64.asm(1666)ed size
crypto\chacha\chacha-x86_64.asm(1666) : error A2070:invalid instruction ocrypto\chacha\chacha-x86_64.asm(1683)ed size
crypto\chacha\chacha-x86_64.asm(1683) : error A2070:invalid instruction ocrypto\chacha\chacha-x86_64.asm(1700)ed size
crypto\chacha\chacha-x86_64.asm(1700) : error A2070:invalid instruction ocrypto\chacha\chacha-x86_64.asm(1717)ed size
crypto\chacha\chacha-x86_64.asm(1717) : error A2070:invalid instruction ocrypto\chacha\chacha-x86_64.asm(1738)ed size
crypto\chacha\chacha-x86_64.asm(1738) : error A2070:invalid instruction ocrypto\chacha\chacha-x86_64.asm(1755)ed size
crypto\chacha\chacha-x86_64.asm(1755) : error A2070:invalid instruction oNMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\ml64.EXE"' : return code '0x1'
Stop.
```

Every line where compilation fails contains the `vbroadcasti128` instruction:

``` asm
	vbroadcasti128	ymm11,YMMWORD PTR[$L$sigma]
	vbroadcasti128	ymm3,YMMWORD PTR[rcx]
	vbroadcasti128	ymm15,YMMWORD PTR[16+rcx]
	vbroadcasti128	ymm7,YMMWORD PTR[r8]
```

**Comment by x64architecture** [comment]
OpenSSL requires nasm see [here](https://github.com/openssl/openssl/blob/master/NOTES.WIN).

**Comment by willie3535** [comment]
No thanks

**Comment by richsalz** [comment]
Then configure with no-asm.  That's it.

**Comment by willie3535** [comment]
Lol

**Comment by levitte** [comment]
Uhmmm, our current config for VC-WIN64A enables the possibility to use ml64, so @rustyx has good reason to raise the issue and shouldn't be so easily dismissed. Reopening, therefore.

**Comment by willie3535** [comment]
My bad didn't know! What the site for thnks bye

**Comment by levitte** [comment]
@dot-asm, do you have some insight about this issue?  Should we keep ml64 support?

@rustyx, have you tried installing nasm?

**Comment by willie3535** [comment]
What is that website about anyway

**Comment by rustyx** [comment]
With `nasm` on the PATH it works :)
But I followed the "new" instructions from [here](https://github.com/openssl/openssl/blob/master/INSTALL#L44).

```
  on Windows (only pick one of the targets for configuration):

    $ perl Configure { VC-WIN32 | VC-WIN64A | VC-WIN64I | VC-CE }
    $ nmake
    $ nmake test
    $ nmake install
```

`nasm` is not mentioned there.

**Comment by dot-asm** [comment]
> I found it weird that ml64 almost worked, except for that one instruction (vbroadcasti128)

But what makes you think that vbroadcasti128 is the *only* problem and the rest would work? It's surely *first*, but it's not the only... Anyway, nasm is mentioned in NOTES.WIN as the only supported option. The fact that you can find masm artefacts anyway means that it's not *guaranteed* to work. It might, or it might not, and when it doesn't, you are expected to opt for the *supported* option. Problem with masm is that if we wanted to actually support it, we would have to verify every visual studio version there is. We don't have such possibility (not to mention that some versions weren't even equipped with assembler), and hence chosen to support solely nasm. Incidentally it also allows to detach hardware support from visual studio version, so that you can enjoy newer processors' capabilities even if you compile with older visual studio compiler. So that it benefits even users. In either case, even if problems with masm can and are likely to be addressed, it won't make it supported. Once again, there is difference between "[happens to] work" and "*guaranteed* to work". Keep in mind that "work" doesn't only mean "compiles" but even "generated code is verified to work on target processor".

**Comment by rustyx** [comment]
OK that's fine, nasm is required (or configure with no-asm), but then shouldn't Windows instructions in INSTALL be updated to mention that? Because as they are now, it results in a compilation error.

**Comment by madduci** [comment]
Here I've wrapped the Windows installation in a CMake script and it builds on both Windows and Linux (AppVeyor is integrated) [https://github.com/madduci/CppDevLibs](https://github.com/madduci/CppDevLibs)

**Comment by dot-asm** [comment]
> Should we keep ml64 support?

There is one thing that is actually guaranteed to work with ml64, and that is applink compilation with no-asm option. I mean 'no-asm' doesn't actually mean "don't you use assembler", but rather "I have reasons to believe that one of those overly *complex* assembly modules is screwed up and I have to test letting the compiler take a crack at the problem". I mean 'no-asm' is not about using the assembler, but about using assembly modules in ./crypto/. Anyway, as for omitting ml64 support outside applink, as in "removing supporting bits in x86_64-xlate.pl". Well, it's an option... I'd be reluctant arguing that we don't know what future holds, and masm "quantum support" as in "state is not known unless measured" is the kind of flexibility that might become handy.

**Comment by levitte** [comment]
@rustyx, you might want to take not of what's written [in the beginning of INSTALL](https://github.com/openssl/openssl/blob/master/INSTALL#L20-L24) as well ;-)  
It could be argued that we should be a bit more pushy there, though.

That being said, @dot-asm, is there any reason to keep the pretence of supporting masm (because we do in `Configurations/10-main.conf`), or should we simply remove that?

**Comment by levitte** [comment]
Heh, ok, you wrote the reason while I asked the question...

**Comment by levitte** [comment]
> Anyway, as for omitting ml64 support outside applink, as in "removing supporting bits in x86_64-xlate.pl". Well, it's an option... I'd be reluctant arguing that we don't know what future holds, and masm "quantum support" as in "state is not known unless measured" is the kind of flexibility that might become handy.

I'm starting to think we should make that an option for now, rather than something that happens just because nasm is missing.

**Comment by dot-asm** [comment]
> (or configure with no-asm)

Assembly support is kind of approaching equivalence with security. In sense that there are things implemented only in assembly that make implementations secure, not only faster. So that one can argue that 'no-asm' should be referred to rather as *debugging* option [as in "report if problem persists with no-asm"] than a viable option for *production* build.

**Comment by dot-asm** [comment]
> we should make that an option for now

As already said, there is difference between "works" and "guaranteed to work/supported". So what is the suggestion more specifically? Former or latter? Keep in mind that one wouldn't have the luxury to say "update your assembler" or "switch to another visual studio", because masm is not really interchangeable option and people tend to have reasons to stick with specific visual studio version. So that at the end of the day we end up working around problems in specific [outdated] versions. Usch... As already said, masm problems can and are likely to be addressed, but I still argue that it shouldn't be interpreted as fully fledged support. Even if we fix them up now and remove no-asm from x64 builds in appveyor, I'd still advocate for "when in doubt, opt for actually supported nasm."

**Comment by levitte** [comment]
I'm thinking *some* kind of thing that lets the user explicitely say that it's ok to try using masm, be it with an environment variable `TRYMASM` or a configuration option `try-masm`.

On the other hand, INSTALL should be a bit more explicit about more requirement existining in the NOTES files.  Would that be enough, @rustyx?

**Comment by rustyx** [comment]
@levitte The instructions in the INSTALL quick-start section suggest (to me) that Visual Studio is sufficient to build under Windows. Anything that would tell me otherwise would be enough. That could be an explicit compile error saying "nasm is required or Configure with no-asm or try-masm", a warning during Configure that nasm is not found, or of course just a mention in INSTALL near the Windows build steps.

**Comment by dot-asm** [comment]
> TRYMASM or try-masm.

Oh! You mean override nasm *if* it's present on %PATH%. Yeah, it's an option... Though I'd argue that those who would have to remember to use it are in perfect ability to manipulate %PATH% to achieve the desired goal :-) At least I do at those rare occasions I turn to visual studio. But don't let this remark stop you...

**Comment by levitte** [comment]
#970 is an attempt at making it more explicit that further requirements can be found in the `NOTES` files.  Is that acceptable to you, @rustyx?  I certainly hope that you at least check for requirements before jumping ahead to the config + build commands.

**Comment by levitte** [comment]
That being said, I'm taking back the `TRYMASM` idea.  Not very good...  BUT, we could have `Configure` give off an appropriate warning if it didn't find `nasm`

**Comment by rustyx** [comment]
@levitte yes that's OK but I think if masm is not officially supported, it should not be used as the default fallback for nasm because someone is going to be unknowingly building an experimental/unsupported configuration, which can lead to more bug reports in the future, should it somehow compile but fail to work properly. So I kinda like the `try-masm` option, as the only way to build with masm for those who know what they're doing.

**Comment by dot-asm** [comment]
The problem I have with things like try-masm is that it's too specific. I mean we support a very wide range of OSes, so why does *one* deserve *that* special and specific treatment? If [fatal] warnings path is taken, maybe it would be more appropriate to generalize and introduce generic-looking --force option to bypass the [fatal] warnings...

**Comment by levitte** [comment]
I'll have you note that I never talked about *fatal* warnings...

**Comment by kaduk** [comment]
> Assembly support is kind of approaching equivalence with security. In sense that there are things implemented only in assembly that make implementations secure, not only faster. So that one can argue that 'no-asm' should be referred to rather as debugging option [as in "report if problem persists with no-asm"] than a viable option for production build.

Given the highly opaque and uncommented nature of much of the assembly modules, as well as the apparent lack of complete test coverage (witness the recent reports from @davidben and @hannob), I would be reluctant to give my support to such a proposal at present.  (Which is not particularly meaningful, of course, since I'm not on the dev team, but it would be nice if there could be improvements in these areas.)

**Comment by x64architecture** [comment]
> Given the highly opaque and uncommented nature of much of the assembly modules, as well as the apparent lack of complete test coverage (witness the recent reports from @davidben and @hannob), I would be reluctant to give my support to such a proposal at present. (Which is not particularly meaningful, of course, since I'm not on the dev team, but it would be nice if there could be improvements in these areas.)

Andy (I think) was referring to timing, side-channel and other attacks of many protocols and algorithms that can only be fixed / ensured when assembly is used. But your right the assembly needs some more comments and test coverage but that's the cost of highly optimized code and (IMHO) the ugly perlasm scripts.

**Comment by richsalz** [comment]
There is nothing intrinsic about the OpenSSL assembler stuff that prevents good comments explaining what is going on ☺

**Comment by mattcaswell** [comment]
Can this be closed now? I think we now fail with a more helpful error message if nasm is not on the PATH, and we now have a prominent reference to NOTES.WIN in INSTALL.

**Comment by rustyx** [comment]
Looks good, thanks!

```
C:\openssl>perl Configure VC-WIN64A
Configuring OpenSSL version 1.1.0-pre6-dev (0x0x10100006L)
. . .
Configuring for VC-WIN64A
NASM not found - please read INSTALL and NOTES.WIN for further details
```
:+1:
