### ISSUE TITLE
DESX incorrect output

### ISSUE THREAD

**Issue by guidovranken** [openssl/openssl#9703]
Inputs:

cleartext: {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xde, 0x7f, 0x00,
0x00, 0x00, 0x00, 0xff, 0xe0, 0x10, 0x00} (16 bytes)
cipher iv: {0x11, 0x01, 0xee, 0x42, 0x08, 0x00, 0x00, 0x10} (8 bytes)
cipher key: {0x00, 0x14, 0x64, 0x00, 0x00, 0x00, 0xfb, 0xf7, 0x00,
0x00, 0x00, 0x14, 0x13, 0x00, 0x00, 0x00,
 0x06, 0x05, 0x00, 0x01, 0x00, 0x00, 0x1e, 0x00} (24 bytes)
cipher: DESX_CBC

OpenSSL (all versions) produce:

ciphertext = {0xdb, 0x21, 0xb3, 0xb3, 0xbe, 0xc5, 0x56, 0x3e, 0xe9,
0x94, 0xbc, 0xc3, 0xfa, 0xac, 0x03, 0xeb,
              0xb8, 0x72, 0x23, 0x21, 0xd1, 0x62, 0xc8, 0xe8} (24 bytes)

but both Botan and Crypto++ produce:

ciphertext = {0xae, 0x62, 0x4c, 0xc9, 0x56, 0xab, 0x18, 0xc9, 0xa4,
0xe1, 0xdf, 0x8a, 0x00, 0x11, 0x4e, 0x27,
              0xec, 0x98, 0x06, 0xf7, 0x01, 0x7e, 0x87, 0x86} (24 bytes)

making it likely that OpenSSL gets it wrong.

**Comment by slontis** [comment]
Least I didnt break this one :)

**Comment by levitte** [comment]
> Least I didnt break this one :)

... yet :laughing:

**Comment by mattcaswell** [comment]
I think this is a problem of lack of standards. I could not find a definitive standard to describe DESX and most importantly how keys are represented. This wikipedia article gives a good overview of how it works:

https://en.wikipedia.org/wiki/DES-X

Essentially in DESX there are 3 keys, which I will call key0, key1 and key2. Each key is 8 bytes long. A DESX operation on an 8 byte plaintext is:

XOR(key2, DESX(key0, XOR(key1, plaintext)))

So key1 is xor'd with the plaintext first. Then key0 is used as a standard DES key to encrypt the output of the XOR operation. Finally the output is XORd again using key2.

However, from an API perspective we (and presumably other libraries) represent these 3 keys as a single 24 byte key. But since there doesn't seem to be a standard behind this, I can't find a definitive reference to how those 3 keys should be combined together to form that 24 byte key.

OpenSSL assumes that the 3 keys are concatenated together in the order key0, key1, key2. However if I take your key and reorder it so that it becomes key1, key0, key2 then I get the same output from OpenSSL that you do for Botan and Crypto++.

Therefore I conclude that OpenSSL is acting correctly and the difference is due to a different interpretation of how keys should be represented.

**Comment by guidovranken** [comment]
Thanks for researching this Matt! I will make a subdivision into DESX_A and DESX_B in Cryptofuzz so this discrepancy doesn't show up.
