### ISSUE TITLE
QNetworkAccessManager::get crash on Mac OS when update openssl1.0.2 to 1.1.1

### ISSUE THREAD

**Issue by timeforasong** [openssl/openssl#9711]
Before I updated OpenSSL everything was ok.But when I update openssl1.0.2 to openssl1.1.1,the client crashed when QNetworkAccessManager::get on Mac OS.The same error on Windows is "Error creating SSL context".
When using the network module, we should call libeay32.dll and ssleay32.dll, open the DEBUG runtime program, and I found that these two DLL files were not called. The reason for the error was that the executable files could not find the two files, but they did exist in the QT installation directory, so we copied C:\\\Qt\Qt5.5.1\Tools\\\\\\QtCreator\\\\bin\\libeay32.dll and ssleay32.dll into the same directory as the QT5Network.dll to solve the problem.
However.the problem on Mac OS is still exists,i do not know how to resolve it? Pls help me

**Comment by levitte** [comment]
With 1.1.x, the libraries on Windows were renamed, because they are not API or ABI compatible with libeay32 and ssleay32.  As a matter of fact, we established a library name standard that made them more similar in name across all platforms we support.

So for 1.1.x, the libraries are called libcrypto-1_1.dll and libsssl-1_1.dll for the 32-bit versions, and libcrypto-1_1-x64.dll and libsssl-1_1-x64.dll for the 64-bit versions.

For the upcoming 3.x versions, the libraries will be called libcrypto-3.dll, libssl-3.dll, etc...

This means that if you upgrade OpenSSL to this new major release, the other libraries that depend on OpenSSL will have to be upgraded as well to stay compatible.
