### ISSUE TITLE
PSK Usage

### ISSUE THREAD

**Issue by jaimesaez97** [openssl/openssl#9714]
Hello there.

I am trying to add the use of post-quantum cryptographic keys in the library.
Is it posible to use Pre Shared Keys for the key exchange in your library? Where are the PSK KEX implemented in your code?
I am trying to integrate them on ARIA cipher suite due to ease reasons, so I wonder if it is possible to execute *TLS_PSK_WITH_ARIA_128_GCM_SHA256* cipher suite through the library.

I have also another questing about the usage of OpenSSL in public projects.
Could you tell me some web browser which uses OpenSSL library?

Thank you very much,
Jaime.

**Comment by mattcaswell** [comment]
> Is it posible to use Pre Shared Keys for the key exchange in your library?

Yes, PSK is supported. From your description it sounds like you are interested in TLSv1.2 (and below) PSKs, rather than TLSv1.3 PSKs. These two work quite differently to each other.

You can read about the various PSK related APIs available to applications here:

https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_psk_client_callback.html

> Where are the PSK KEX implemented in your code?

For TLSv1.2 (and below), on the client side it is here:

https://github.com/openssl/openssl/blob/18d307e98ebfe6d376ab039a73dc285190b717a0/ssl/statem/statem_clnt.c#L2875-L2957

And on the server side it is here:

https://github.com/openssl/openssl/blob/18d307e98ebfe6d376ab039a73dc285190b717a0/ssl/statem/statem_srvr.c#L2899-L2964

> Could you tell me some web browser which uses OpenSSL library?

I don't know the answer to that.

**Comment by jaimesaez97** [comment]
Thank you very much.

Would you know a way to test PSKs inside the library? Like some command or communication between two machines.

I am trying to run the cipher suite *TLS_PSK_WITH_ARIA_128_GCM_SHA256* but I am not able to find a way to test PSKs with ARIA on Galois/Counter Mode (I just find the way to execute aria-128-ctr on the simple way `# openssl enc -aria-128-ctr ...`).

**Comment by mattcaswell** [comment]
Yes. For the server do this:

````
openssl s_server -psk 0f0e0d0c0b0a09080706050403020100 -no_tls1_3 -nocert -cipher PSK-ARIA128-GCM-SHA256
````

For the client do this:
````
openssl s_client -psk 0f0e0d0c0b0a09080706050403020100 -cipher PSK-ARIA128-GCM-SHA256
````

**Comment by jaimesaez97** [comment]
Than you very much for all.
