### ISSUE TITLE
FIPS mode not supported in OpenSSL 1.0.2g

### ISSUE THREAD

**Issue by RohanKurane** [openssl/openssl#9743]
Hi - I tried to turn on the FIPS mode in openssl 1.0.2g but for the following error 
```error:0F06D065:lib(15):func(109):reason(101)```

which is
```
openssl errstr f06d065
error:0F06D065:common libcrypto routines:FIPS_mode_set:fips mode not supported
```

How can I enable fips mode for 1.0.2g ? 
I am running on Ubuntu 16.04LTS if it matters.

**Comment by RohanKurane** [comment]
Is there a link (I tried - https://docs.ubuntu.com/security-certs/en/fips-16.html but failed to install correctly) to enable and install openssl 1.0.2 fips on Ubuntu 16.04 ?

**Comment by mspncp** [comment]
The link you posted says that Ubuntu’s FIPS certified modules are available only for customers who have purchased them:

> 140-2 Certified Modules Canonical’s FIPS 140-2 Certified Modules are available to customers who have purchased qualifying Ubuntu Advantage products.

**Comment by RohanKurane** [comment]
@mspncp - Is there a link for someone who hasnt purchased and just wants to try it out ?

**Comment by mspncp** [comment]
The Ubuntu FIPS certification is a private certification of Canonical, and although it includes a FIPS enabled OpenSSL module, the certificate is distinct form the official OpenSSL FIPS certificate.

You don't need the Ubuntu FIPS certified version if you just want to try it out. Everybody can build a FIPS enabled (also called "FIPS capable") OpenSSL. Roughly speaking, the OpenSSL library (libcrypto.so) becomes FIPS enabled by linking the so-called FIPS Objecte Module linked in, which contains the FIPS certified algorithms. Only if this is the case, enabling the FIPS mode will succeed.

Everything you need to know to build your own FIPS Object Module and FIPS enabled OpenSSL can be found in the [OpenSSL FIPS 2.0 User Guide](https://www.openssl.org/docs/fips/UserGuide.pdf).  It's not difficult, but it needs some patience to follow the guide if it's your first time.

But please be careful: it is not a good idea to replace your distributors OpenSSL installation by your own version. Install your self-built version to your home directory or to a non-default system location. (You will have to set PATH and LD_LIBRARY_PATH explicitly to test it).

**Comment by mspncp** [comment]
Sorry, wrong link: the direct link to the OpenSSL FIPS 2.0 User Guide is

https://www.openssl.org/docs/fips/UserGuide-2.0.pdf

**Comment by RohanKurane** [comment]
Thanks @mspncp ! I'll take a look and let you know how it goes.

**Comment by RohanKurane** [comment]
@mspncp  I was able to install the fips-version but when I called FIPS_mode_set(1) from the application, I still got the same error.
```
OpenSSL 1.0.1e-fips 11 Feb 2013
```

I followed the following steps to do - 
```
  78  wget http://www.openssl.org/source/openssl-1.0.1e.tar.gz
   79  wget http://www.openssl.org/source/openssl-fips-2.0.5.tar.gz
   80  tar -xzvf openssl-fips-2.0.5.tar.gz
   81  cd openssl-fips-2.0.5
   82  ./config
   83  make
   85  sudo make install
   86  cd
   87  tar -xzvf openssl-1.0.1e.tar.gz
   88  cd openssl-1.0.1e
   89  ./config fips
   90  make depend
   91  make
   92  sudo make install   
```

What am I missing here ? I followed the guide you had as well and the steps match I believe.

**Comment by mspncp** [comment]
Not sure. Maybe your application is picking up the wrong shared library? Did you check the output of `ldd your-app`? Maybe you need to set the LD_LIBRARY_PATH environment variable?

**Comment by mspncp** [comment]
Why did you switch to 1.0.1e?

**Comment by RohanKurane** [comment]
No real reason to switch to 1.0.1e.  Whats the best version ? 1.0.2g ?
```
LD_LIBRARY_PATH="/home/ubuntu/::/usr/lib/x86_64-linux-gnu::/usr/local/lib"
```

ldd app
```
	linux-vdso.so.1 =>  (0x00007ffd0c3a2000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fe7f8b9c000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe7f897f000)
	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007fe7f8749000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe7f8545000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe7f833d000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fe7f80d4000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fe7f7c8f000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fe7f790d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe7f76f7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe7f732d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe7f8da1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe7f7024000)
```

**Comment by mspncp** [comment]
The 1.0.1 series is out of support since Jan 2017. The last official release was 1.0.1u in September 2016, your version is from February 2013.

The 1.0.2 LTS series is the only one which currently has FIPS support. Since the letter releases (1.0.2a, 1.0.2b, ...) are bugfixes, it is best to choose the most current version, which is OpenSSL 1.0.2s. https://www.openssl.org/source


Can you please also post the output of the following commands:

```
which openssl
ldd `which openssl`
openssl version
```

**Comment by RohanKurane** [comment]
@mspncp 
I can change it to use 1.0.2s  

Here are the results you asked for 
```
which openssl
/usr/bin/openssl

ldd `which openssl`
	linux-vdso.so.1 =>  (0x00007ffc6ff6e000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f86f5175000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f86f4dab000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f86f5379000)

openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013
```

**Comment by RohanKurane** [comment]
I also wrote a simple C pgm and compiled it and ran it but still got the same FIPS not supported error

fips.c 

```
        int bRet = FIPS_mode();
        if(bRet)
            printf("Already in fips mode");
        else 
        {
        bRet = FIPS_mode_set(1);
        if(bRet)
            printf("Set fips mode");
        else
        {
            unsigned long err = ERR_get_error();
            printf("Cannot set fips mode %lx\n", err);
            const char* error_str = ERR_error_string(err, NULL);
            printf("Cannot set fips mode %s\n", error_str);
        }
        }
```

`gcc fips.c -L/home/ubuntu/openssl-1.0.1e -lcrypto -o fips`
`./fips.o`

**Comment by RohanKurane** [comment]
@mspncp - Same thing with 1.0.2s. So there appears to be something wrong with the linkage. 
Did you notice anything wrong above ?

**Comment by mspncp** [comment]
@RohanKurane sorry that I'm short on time. I'll try to give you a detailed reply this evening.

For the moment: your fips testapp  does not work as expected, because you built a static, not a shared version of OpenSSL. This can be inferred from your output of 
```
ldd `which openssl`
```

But this might also be your luck, because contrary to my recommendation, you did a `sudo install`. If you had done this with a shared build, you might have replaced the distributor's shared openssl libraries, which could possibly break some of you applications. (I don't know whether Ubuntu installs them in the default locatation)

So once again: please **do not  `sudo install` your test copy!**. I'll give you an example how you can do it better as soon as I find the time.

**Comment by RohanKurane** [comment]
@mspncp  Great! I look forward to your example and steps!

**Comment by mspncp** [comment]
The following procedure describes how you can test your application. I tested every step below (using gcc 8.3.0), using the following toy program, so hopefully everything should work without errors.

**test.c**

```C
#include <stdlib.h>
#include <stdio.h>

#include <openssl/evp.h>
#include <openssl/rand.h>

int main(void)
{
    if (!FIPS_mode_set(1)) {
        fprintf(stderr, "FIPS mode intialization failed!\n");
        return 1;
    }
    fprintf(stderr, "FIPS mode intialization succeeded.\n");
   
    OpenSSL_add_all_algorithms();

    unsigned char buf[32];
    if (!RAND_bytes(buf, sizeof(buf))) {
        fprintf(stderr, "RAND_bytes() failed!\n");
        return 1;
    }
    fprintf(stderr, "RAND_bytes() succeeded\n");
    return 0;
}
```


### Step 1: Install the OpenSSL FIPS Object module to the standard location

Configure, build and install the FIPS Object Module (FOM) to its default location (using sudo), following the FIPS User Guide. This step has to be done only once.


### Step 2: Build and Install OpenSSL to a non-standard location

Having an installed copy is convenient, in particular for developers who frequently make changes in their source directory, but not necessary. Testing is also possible without installing, see Step 3b below.

#### Create the installation directory (first time only)

Create a directory in a non-default location, which is owned by you (using sudo). 

```
sudo mkdir -p /opt/openssl-1.0.2-dev
sudo chown yourusername:yourusername /opt/openssl-1.0.2-dev
```

_Don't add the path to your `PATH` or `LD_LIBRARY_PATH` environment variable in your .bashrc._


#### Configure, build (and install) OpenSSL

The configure option below builds a FIPS enabled OpenSSL library with debugging information, using the FOM from Step 1. If you installed the FOM to it's default location, you only need to specify the `fips` option. Otherwise, you will also need `--with-fipsdir=<location of FOM>`.

```
perl Configure debug-linux-x86_64 fips shared --strict-warnings --prefix=/opt/openssl-1.0.2-dev
```

Now build and install OpenSSL. Since you own the installation directory, no sudo is necessary

```
make depend
make
make install
```

### Step 3: Build and test your application


#### Variant a: Using the installed version

The magic trick which enables your application to find the correct libraries even without setting `LD_LIBRARY_PATH` is to set the so-called 'rpath' correctly. This is done by specifying a linker option. The most elegant way to add it is to create a little Makefile in your application's source directory with the following content:

```make
OPENSSL_PREFIX=/opt/openssl-1.0.2-dev
OPENSSL_LIB=${OPENSSL_PREFIX}/lib
CFLAGS=-g -O0 -I${OPENSSL_PREFIX}/include
LDFLAGS=-L${OPENSSL_LIB} -lcrypto -Wl,--enable-new-dtags,-rpath,${OPENSSL_LIB}

all: test

clean:
	rm -f test *~
```

_Note: the `rm -f test *~` line at the end needs to be indented using a tab, not spaces_


Now building (resp. cleaning) your application is as simple as invoking `make` (resp. `make clean`).

```
~/src/yourapp$ make
cc -g -O0 -I/opt/openssl-1.0.2-dev/include  -L/opt/openssl-1.0.2-dev/lib -lcrypto -Wl,--enable-new-dtags,-rpath,/opt/openssl-1.0.2-dev/lib  test.c   -o test
```

After your application is built, you can verify that it picks up the correct shared library using `ldd`:

```
~/src/yourapp$ ldd test
	linux-vdso.so.1 (0x00007ffe647ef000)
	libcrypto.so.1.0.0 => /opt/openssl-1.0.2-dev/lib/libcrypto.so.1.0.0 (0x00007f2b19d58000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f2b19b5e000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f2b19b58000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2b1a089000)
```

##### Testing and Debugging

E voila, you are ready to go.


```
~/src/your/app$ ./test
FIPS mode intialization succeeded.
RAND_bytes() succeeded
```

You can even run it in the debugger

```
~/src/your/app$ gdb --args ./test
```

_Since the code in the FOM was built without debug information, you won't be able to debug into the FIPS code, unless you build a special debug build of the FOM (not approved; for testing only)._

_Note also that all breakpoints inside the FOM must be disabled until `FIPS_mode_set(1)` has finished, because debugger breakpoints change the incore fingerprint, causing `FIPS_mod_set(1)` to fail!_


#### Variant b: Using the shared libraries from the source directory

A slight change in the Makefile enables you to test directly with the shared librares from the source directory. The example assumes that the source code is in `~/src/openssl-1.0.2`:


```make
OPENSSL_SOURCE=${HOME}/src/openssl-1.0.2
CFLAGS=-g -O0 -I${OPENSSL_SOURCE}/include
LDFLAGS=-L${OPENSSL_SOURCE} -lcrypto -Wl,--enable-new-dtags,-rpath,${OPENSSL_SOURCE}

all: test

clean:
	rm -f test *~
```


```
~/src/yourapp$ make
cc -g -O0 -I/home/msp/src/openssl-1.0.2/include  -L/home/msp/src/openssl-1.0.2 -lcrypto -Wl,--enable-new-dtags,-rpath,/home/msp/src/openssl-1.0.2  test.c   -o test
```

Again, verify that your app picks up the correct shared library using `ldd`:

```
~/src/yourapp$ ldd test
	linux-vdso.so.1 (0x00007ffe4a7f3000)
	libcrypto.so.1.0.0 => /home/msp/src/openssl-1.0.2/libcrypto.so.1.0.0 (0x00007fbf59979000)    <=== now libcrypto is loaded from your source directory
	libc.so.6 => /lib64/libc.so.6 (0x00007fbf5977f000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fbf59779000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fbf59caa000)
```

**Comment by RohanKurane** [comment]
Thanks @mspncp . I am going to try these steps and I'll let you know.

**Comment by RohanKurane** [comment]
@mspncp : Everything went great till the last step where I did a `make` of `test.c` :-)

This is basically what I did - 
```
1. Install openssl FOM in home dir
2. Install openSSL 1.0.2s : 
    sudo mkdir -p /opt/openssl-1.0.2-dev
    sudo chown ubuntu:ubuntu /opt/openssl-1.0.2-dev
    cd /opt/openssl-1.0.2-dev
    wget http://www.openssl.org/source/openssl-1.0.2s.tar.gz
    tar -xzvf openssl-1.0.2s.tar.gz
    cd openssl-1.0.2s
    perl Configure debug-linux-x86_64 fips shared --strict-warnings --prefix=/opt/openssl-1.0.2-dev
    make depend
    make 
    make install
    cd /opt/openssl-1.0.2-dev
    compile test.c  --> This failed with errors - 
    make
    cc -g -O0 -I/opt/openssl-1.0.2-dev/include  -L/opt/openssl-1.0.2-dev/lib -lcrypto -Wl,--enable-new-   dtags,-rpath,/opt/openssl-1.0.2-dev/lib  test.c   -o test
    /tmp/ccmellt2.o: In function `main':
   /opt/openssl-1.0.2-dev/test.c:9: undefined reference to `FIPS_mode_set'
    /opt/openssl-1.0.2-dev/test.c:15: undefined reference to `OPENSSL_add_all_algorithms_noconf'
    /opt/openssl-1.0.2-dev/test.c:18: undefined reference to `RAND_bytes'
    collect2: error: ld returned 1 exit status
    <builtin>: recipe for target 'test' failed
    make: *** [test] Error 1
```

All the libraries (libcrypto) and include paths look good and point to the right places. 

openssl version shows 
`OpenSSL 1.0.2s-fips  28 May 2019`

This has to be something really small that I am missing. Battled for 30 mins and thought I'd ask your opinion.

**Comment by mspncp** [comment]
> /opt/openssl-1.0.2-dev/test.c

It's not a good idea to place your testprogram inside the openssl-1.0.2 installation directory. Keep the source (and Makefile) in your home directory where you had it before (say, `~/src/test`).


> Install openssl FOM in home dir

So you _installed_ the FOM in your home dir? Which command did you use for installation?. Or did you just _build_ it there? Note that you are not allowed to add `--prefix=` to the configure command. However, the user guide allows to set the `FIPSDIR` environment variable _before_ issuing the configure command to change it:

> The environment variable FIPSDIR, if present, points to the pathname of the location where the
> validated module will be installed. This location defaults to /usr/local/ssl/fips­2.0.
[FUG, Section 4.2.1]

If you did install the FOM to a non-default location, then your configure command for openssl-1.0.2 is missing a `--with-fipsdir` option. (Again, you can set the `FIPSDIR` variable before configuring instead.)
 
> files. The FIPSDIR environment variable or the --with­fipsdir command line option can
> be used to explicitly reference the location of the FIPS Object Module (fipscanister.o).
[FUG, Section 4.2.3] 


Although I am wandering why you did not get a configuration or compiler error, only a linker error. Do you alreedy have some files in `/usr/local/ssl/fips­2.0`? If yes, this is what it's content should look like:

```
$ tree /usr/local/ssl/fips-2.0/
/usr/local/ssl/fips-2.0/
├── bin
│   ├── fips_standalone_sha1
│   └── fipsld
├── include
│   └── openssl
│       ├── aes.h
│       ├── bn.h
│       ├── buffer.h
│       ├── cmac.h
│       ├── crypto.h
│       ├── des.h
│       ├── des_old.h
│       ├── dh.h
│       ├── dsa.h
│       ├── e_os2.h
│       ├── ebcdic.h
│       ├── ec.h
│       ├── ecdh.h
│       ├── ecdsa.h
│       ├── evp.h
│       ├── fips.h
│       ├── fips_rand.h
│       ├── fipssyms.h
│       ├── hmac.h
│       ├── modes.h
│       ├── opensslconf.h
│       ├── opensslv.h
│       ├── ossl_typ.h
│       ├── rsa.h
│       ├── sha.h
│       └── symhacks.h
└── lib
    ├── fips_premain.c
    ├── fips_premain.c.sha1
    ├── fipscanister.o
    └── fipscanister.o.sha1

4 directories, 32 files
```

**Comment by mspncp** [comment]
The compiler command you posted shows spaces in the middle of the `--enable-new-dtags` options? Is this only a pasting error to GitHub, or an error in your Makefile?

```
-Wl,--enable-new-   dtags,-rpath,/opt/openssl-1.0.2-dev/lib
```

**Comment by RohanKurane** [comment]
Its a pasting error. 
`LDFLAGS=-L${OPENSSL_LIB} -lcrypto -Wl,--enable-new-dtags,-rpath,${OPENSSL_LIB}`

**Comment by RohanKurane** [comment]
@mspncp 
Here are my exact steps. Maybe you can try this on your system and let me know where I went wrong ? 
```
sudo apt-get update
sudo apt-get install build-essential

cd ~

wget http://www.openssl.org/source/openssl-fips-2.0.5.tar.gz
tar -xzvf openssl-fips-2.0.5.tar.gz
cd openssl-fips-2.0.5
./config
make
sudo make install
sudo mkdir -p /opt/openssl-1.0.2-dev
sudo chown ubuntu:ubuntu /opt/openssl-1.0.2-dev
cd /opt/openssl-1.0.2-dev
wget http://www.openssl.org/source/openssl-1.0.2s.tar.gz
tar -xzvf openssl-1.0.2s.tar.gz
cd openssl-1.0.2
perl Configure debug-linux-x86_64 fips shared --strict-warnings --prefix=/opt/openssl-1.0.2-dev
make depend
make
make install
cd /opt/openssl-1.0.2-dev
make    (to compile test.c)  Fails with below errors -

    cc -g -O0 -I/opt/openssl-1.0.2-dev/include  -L/opt/openssl-1.0.2-dev/lib -lcrypto -Wl,--enable-new-   dtags,-rpath,/opt/openssl-1.0.2-dev/lib  test.c   -o test
    /tmp/ccmellt2.o: In function `main':
   /opt/openssl-1.0.2-dev/test.c:9: undefined reference to `FIPS_mode_set'
    /opt/openssl-1.0.2-dev/test.c:15: undefined reference to `OPENSSL_add_all_algorithms_noconf'
    /opt/openssl-1.0.2-dev/test.c:18: undefined reference to `RAND_bytes'
    collect2: error: ld returned 1 exit status
    <builtin>: recipe for target 'test' failed
    make: *** [test] Error 1
```

I then moved both the `test.c` and the new `Makefile` over to `~/src/test` and the `make` still failed with the same errors. 

My FOM is at the default location I believe so I do not set the FIPSDIR env variable 
```
ls /usr/local/ssl/fips-2.0/lib/
fipscanister.o  fipscanister.o.sha1  fips_premain.c  fips_premain.c.sha1
```

I do have /usr/local/ssl/fips-2.0
```
tree /usr/local/ssl/fips-2.0
/usr/local/ssl/fips-2.0
├── bin
│   ├── fipsld
│   └── fips_standalone_sha1
├── include
│   └── openssl
│       ├── aes.h
│       ├── bn.h
│       ├── buffer.h
│       ├── cmac.h
│       ├── crypto.h
│       ├── des.h
│       ├── des_old.h
│       ├── dh.h
│       ├── dsa.h
│       ├── ebcdic.h
│       ├── ecdh.h
│       ├── ecdsa.h
│       ├── ec.h
│       ├── e_os2.h
│       ├── evp.h
│       ├── fips.h
│       ├── fips_rand.h
│       ├── fipssyms.h
│       ├── hmac.h
│       ├── modes.h
│       ├── opensslconf.h
│       ├── opensslv.h
│       ├── ossl_typ.h
│       ├── rsa.h
│       ├── sha.h
│       └── symhacks.h
└── lib
    ├── fipscanister.o
    ├── fipscanister.o.sha1
    ├── fips_premain.c
    └── fips_premain.c.sha1

4 directories, 32 files
```

**Comment by mspncp** [comment]
```
sudo mkdir -p /opt/openssl-1.0.2-dev
sudo chown ubuntu:ubuntu /opt/openssl-1.0.2-dev
cd /opt/openssl-1.0.2-dev
wget http://www.openssl.org/source/openssl-1.0.2s.tar.gz


tar -xzvf openssl-1.0.2s.tar.gz     <== WHY source directory /opt/openssl-1.0.2-dev/openssl-1.0.2s?

cd openssl-1.0.2   <== TYPO?


perl Configure debug-linux-x86_64 fips shared --strict-warnings --prefix=/opt/openssl-1.0.2-dev
make depend
make
make install
```

What you sent me looks ok, except for `cd openssl-1.0.2`. This is probably a typo and in reality you did `cd openssl-1.0.2s`? Also, it was not intended that you place the _source_ directory inside the _installation_ directory. Why didn't you unpack the source to `~/src/openssl-1.0.2s`?  (But this is not the root cause of your problem.)

Apart from that your log looks ok. However, I see only your commands and nothing of the compiler and linker output, which might contain some error that was ignored. Also, I can't inspect the binaries. So I can only guess what your problem is. It won't help if I try reproduce your steps here, because I don't have exactly the same setup as you do.

So I only have three more suggestions:

1. Use `nm` to find out whether the unresolved symbols are present in your libcrypto

```
$ nm -g libcrypto.so.1.0.0 | grep OPENSSL_add_all_algorithms_noconf
00000000001d3a2f T OPENSSL_add_all_algorithms_noconf
```

2. Use `strace` to find out what the compiler and linker are doing, in particular, which libcrypto library they access.

```
strace -f make  |&  tee make.log
```

3. Ask a friend who is familiar with compiling and linking on Linux an let him help you figure out what the precise problem is.


Sorry, that's all help I can give.

**Comment by RohanKurane** [comment]
@mspncp Turns out it was a linkage issue. I forgot to update you last evening. 
I tried again on a fresh system today and it didnt work. But calling it a Victory nonetheless! 
If I run into anything, I'll reach out for help. Thanks for your help.
