### ISSUE TITLE
hmac engine does not allow to 'enginize' key operations

### ISSUE THREAD

**Issue by boos** [openssl/openssl#977]
Hmac engine can only replace functions related to digest but not on padding. 
Using an hmac engine must allow to specify how to deal with padding and consequently with the key. 

I have a crypto accelerator module with mini HSM storage and I cannot fully execute the HMAC implementation fully on the crypto accelerator module as the key should leave the HSM as the padding functionalities are not "enginizeable". 

See hmac.c file while using an engine (reset = 1)

**Comment by kaduk** [comment]
It seems that someone would need to create a new ENGINE method for HMAC (or HMAC padding) in order to effect this proposal.  That feels like a rather specific use case, and since I don't see much evidence of there being either interest from the team in implementing or a contributd implementation, I'll move this to the post-1.1.1 milestone.  But perhaps we should consider just closing it, if there is no sign of an implementation appearing.

**Comment by t8m** [comment]
Engines are deprecated in master in favor of providers. I do not think we are going to change this.
