### ISSUE TITLE
Fips self test is being triggered multiple times..

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#9909]
The fipsprov.c entry point OSSL_provider_init calls SELF_TEST_post() which then does a EVP_fetch (it will do more once the KATS are added) .. As the provider has not yet activated the fetch causes some fallback setup to be called which then calls  OSSL_provider_init() a second time..

The dummy_evp_call() will be suffering from the same issues..

**Comment by levitte** [comment]
The FIPS module re-uses the libcrypto library context, doesn't it?  i don't quite recall the mechanism, and that part is a bit of black magic to me at this point...  but this shows that we probably need a clear separation, 'cause an internal FIPS module fetch should affect *its own internal* "provider" and library context, not the library context of the caller...

**Comment by slontis** [comment]
It is definitely not clear how this will work nicely at the moment. The services need to not be available till after the entry point init returns. But we need to be able to setup internaly so the fetch doesnt need to call itself in order to retrieve EVP_XXX objects before the init method returns.

**Comment by mattcaswell** [comment]
I assume you are seeing this behaviour in the newly added evp_fetch_prov_test?

That test seems to be doing this:
1) Setting up a config file to automatically load providers for the default context
2) Explicitly creating its own OPENSSL_CTX and then also loading providers into that

Therefore the FIPS provider is being loaded twice quite correctly. Once for the default context and once for the explicit context. If you don't want it to be loaded twice then don't ask it to be!

**Comment by slontis** [comment]
By newly added - you mean it does the same thing as the the old evp_test was doing before I moved it :)
Having the potential to load it twice sounds like a very bad idea to me..
So If I use the default_and_fips.cnf file I would not expect it to call the self test twice in this case, It would also be bad if it fetched the default providers algorithm inside the self test..

**Comment by mattcaswell** [comment]
> By newly added - you mean it does the same thing as the the old evp_test was doing before I moved it :)

The old one did not load a provider into the default context via config file so it did not have this issue. In this new test you are explicitly setting up a config file to do this.

> Having the potential to load it twice sounds like a very bad idea to me..

This was explicitly how we designed it! It was exactly the idea that different components of an application may want to use different providers, and load/unload them independently of each other. This is why we have OPENSSL_CTX.

> So If I use the default_and_fips.cnf file I would not expect it to call the self test twice in this case, It would also be bad if it fetched the default providers algorithm inside the self test..

The FIPS provider will never fetch algorithms from the default provider. That just can't happen.

If we don't want something the self-test to occur twice, even if the FIPS provider is loaded twice into two different components of an application then once possible answer is to use RUN_ONCE (although that would have to be brought inside the module boundary in order to do that).

**Comment by slontis** [comment]
I will have to trace into it to see what you are saying tomorrow.. When I traced into it beforehand it was reaching the init entry point from the int entry point - that seems like it should never be something that should never happen.
The test only creates a default context if a command line option is specified. If I use the default_and_fips.cnf file which are loaded using a created lib_ctx (which it does) I would not expect it to call the fips init twice.

**Comment by mattcaswell** [comment]
> The test only creates a default context if a command line option is specified.

No it doesn't. A default context is *always* created. If you have supplied a config file then the providers specified in it will be loaded into that default context. The command line option only specifies if the default context is *used*.

**Comment by slontis** [comment]
Considering that the fips module needs a config currently in order to work this sounds like a problem to me :).

**Comment by slontis** [comment]
We are working from different designs at the moment :)

**Comment by mattcaswell** [comment]
> Considering that the fips module needs a config currently in order to work this sounds like a problem to me :).

The config file is not the problem. If you only use the default context then the FIPS Provider will only be loaded once. The problem is loading a default context *and* an explicit context. That loads the provider twice - once for each context. That is exactly the intended behaviour. The issue we have to resolve is ensuring that that the self test only happens once per physical DSO load (as opposed to provider load). A DSO gets loaded into memory once - but the provider inside it can be loaded multiple times (depending on how many contexts you are using).

**Comment by richsalz** [comment]
Perhaps leave the config file stuff out of the boundary, and the self-test only gets the parameters it needs: a couple of HMACs and file paths.

**Comment by mattcaswell** [comment]
> Considering that the fips module needs a config currently in order to work this sounds like a problem to me :).

Although that does spark another thought. I think there *is* a potential problem in the way the module configuration files currently work where explicit OPENSSL_CTX's are in use, i.e. if you load a provider explicitly I don't think it ever gets config file parameters passed to it.

@levitte can you confirm?

**Comment by mattcaswell** [comment]
> Perhaps leave the config file stuff out of the boundary, and the self-test only gets the parameters it needs: a couple of HMACs and file paths.

The config file stuff *is* outside the boundary. It's all loaded and handled by libcrypto. Libcrypto then just passes to the provider a set of OSSL_PARAMs that it read from the config file.

**Comment by richsalz** [comment]
I was responding to the last line of https://github.com/openssl/openssl/issues/9909#issuecomment-531747288 apparently mistakenly.  Thanks for the correction.

**Comment by levitte** [comment]
> Although that does spark another thought. I think there is a potential problem in the way the module configuration files currently work where explicit OPENSSL_CTX's are in use, i.e. if you load a provider explicitly I don't think it ever gets config file parameters passed to it.
> 
> @levitte can you confirm?

Yes I can. The current config module model only works with the default context, 'cause there is no way to pass down extre data to the module processors. This needs a serious bit of refactoring, which has been on my mind but hasn't come any further than that.

**Comment by mattcaswell** [comment]
> Yes I can. The current config module model only works with the default context, 'cause there is no way to pass down extre data to the module processors. This needs a serious bit of refactoring, which has been on my mind but hasn't come any further than that.

Right. Which effectively means that the FIPS provider can't be used (properly) by an explicit OPENSSL_CTX because you need config files for the FIPS provider to work, but there is no way to associate config files with an OPENSSL_CTX. We'll definitely need to fix that (for example I can easily see a situation where the FIPS provider is not in the system default config file and most of an application doesn't care about it - but one component *does* care about FIPS and wants to use an explicit OPENSSL_CTX and just load the FIPS provider for what that one component wants to do)

**Comment by richsalz** [comment]
I totally agree with https://github.com/openssl/openssl/issues/9909#issuecomment-531761783 which is why I think that we should be passing around PARAMS stuff for explicit loading of the FIPS module.  We can make the limitation be auto-loading FIPS only works for the default context, and if someone wants it another way, they parse the files (wherever they are) and then calls a FIPS_enable() API with the params and path to the library.

**Comment by mattcaswell** [comment]
> I totally agree with #9909 (comment) which is why I think that we should be passing around PARAMS stuff for explicit loading of the FIPS module. We can make the limitation be auto-loading FIPS only works for the default context, and if someone wants it another way, they parse the files (wherever they are) and then calls a FIPS_enable() API with the params and path to the library.

In my mind the simplest solution is to just make it possible to load a config file with an associated OPENSSL_CTX. The application would have to explicitly request the loading of the config file and pass in the OPENSSL_CTX to use. After that everything else works as it does now - including auto-loading of providers.

**Comment by almajedy** [comment]
openssl req -newkey rsa:2048 -sha256 -nodes -keyout YOURPRIVATE.key -x509 -days 365 -out YOURPUBLIC.pem -subj "/C=US/ST=New York/L=Brooklyn/O=Example Brooklyn Company/CN=YOURDOMAIN.EXAMPLE"

**Comment by slontis** [comment]
Running with
export OPENSSL_CONF=test/fips.cnf
export OPENSSL_MODULES=providers
export OPENSSL_CONF_INCLUDE=providers

running openssl/test/evp_fetch_prov_test -defaultctx -property fips=yes

The SELF_TEST_post is only being run once as you expected..

**Comment by slontis** [comment]
Running the following (which creates a libctx and explicitly loading the fips provider) runs the self test twice (and verifies - meaning the config data has been passed correctly).
and the test passes (meaning the fetch worked)...
openssl/test/evp_fetch_prov_test -property fips=yes fips

The first call happens via the run_once ossl_init_config when OSSL_PROVIDER_load is called explicitly from the test.. i.e: the config gets the fips_sect and actives the module..
Ok this was very confusing with all the lazy inits going on:
OSSL_PROVIDER_load 
calls 
provider_conf_init (this uses the default_ctx to load the config values globally once)
  provider_conf_load
    ossl_provider_activate
      provider_activate(prov)
         prov->init_function
            SELF_TEST_post
               verify_integrity
                  EVP_MAC_fetch (it uses the libctx here)
                       //The tangled web for fetch does a provider_activate (but this uses the internal init)
                     evp_generic_fetch
                        ossl_method_construct () //"HMAC", 
                           ossl_algorithm_do_all () //fn=ossl_method_construct_this>
                              ossl_provider_forall_loaded ()
                                  provider_activate_fallbacks()
                                     provider_activate() //prov->libctx=explict_ctx, prov->name="fips"
then it calls
provider_activate(prov) : for the explicit libctx..

The loaded config values are correct on the first call (for default) and they are stored into  a static struct
static SELF_TEST_POST_PARAMS selftest_params; Which can then be used by the on demand test if needed.
They are so not passed by the explicit load at all (it just remembers)..
This is by accident rather than by design.

The second


So on the second call to the self test the values are all already copied into the static struct. They are not passed into the

**Comment by mattcaswell** [comment]
IMO, the solution to this issue is as follows:

- We fix config params so that you can associate a config file with an explicit OPENSSL_CTX. Possibly this could be done on construction of the OPENSSL_CTX itself, e.g.

OPENSSL_CTX *ctx = OPENSSL_CTX_new("/path/to/default/config/file");

Or possibly as some additional calls after the OPENSSL_CTX has been constructed.

- We implement a ".ini" section and a ".fini" in the fips provider
1) the ".ini" creates a self-test lock and initialises a status flag to "self-test not run"
2) On a call to OSSL_init_provider inside the FIPS module we acquire the lock and check the status flag. If the status flag is "self-test not run" then we run the self tests, update the status flag and release the lock. If the status flag is "self-tests failed" then we release the lock and fail the call to OSSL_init_provider. If the status flag is "self-tests succeeded" then we release the lock and continue.
3) In the ".fini" section we free the lock

The above solution assumes all interesting platforms can support .ini and .fini sections. Is this the case? Possible alternatives could be:
1) Use a RUN_ONCE function to run the self-tests, This might work, but has some issues:
- You can't allocate any resources inside the RUN_ONCE (e.g. locks etc) that are shared between multiple OPENSSL_CTXs because you have no way of releasing them (without using a ".fini" section).
- It's difficult to pass parameters (e.g. the config file parameters) to the RUN_ONCE function in a thread-safe way
2) Always run the self-tests every time the provider is loaded. This would probably work well if an application has a small number of long running OPENSSL_CTX objects - but not so well if it is frequently loading/unloading the FIPS module or has many concurrent OPENSSL_CTXs.

**Comment by levitte** [comment]
> The above solution assumes all interesting platforms can support .ini and .fini sections.

Yes for Windows (we already have that in `crypto/dllmain.c`.
Yes for VMS (we haven't needed that so far, but still, yes, and I'm happy to deal with that).

**Comment by mattcaswell** [comment]
Can android support this?

**Comment by levitte** [comment]
I would be surprised if Android didn't...  bottom line, Android is Linux, and if it wouldn't support .ini/.fini, that would probably be quite troublesome, as much of the GNU toolchains uses that as a very basic component...
That being said, *I do not know for sure*, this remains to be verified

**Comment by mattcaswell** [comment]
Possibly we can go for the ".ini"/".fini" solution but fallback to the run-the-tests-on-every-load solution for any platforms where this is not possible (or just using an unknown compiler where we don't know how to do it).

**Comment by levitte** [comment]
Please remind me what it is that makes it impossible to create a local refcount (with lock if necessary) with a local RUN_ONCE in the provider module?

**Comment by mattcaswell** [comment]
> Please remind me what it is that makes it impossible to create a local refcount (with lock if necessary) with a local RUN_ONCE in the provider module?

I'm not entirely sure what you're proposing. RUN_ONCE and refcounting are dealing with different issues.

The main problem I see with RUN_ONCE (which you can do without a lock) is how can you pass parameters to it in a thread safe manner. To do *that* you would need a lock.

Once you have a lock, the problem is knowing when to allocate/free it. I suspect that is where you see ref counting coming in, i.e. every time you have a "load" increment the ref count. Every time you have an "unload" decrement the ref count.

So, when do you allocate the lock? Presumably when the ref count is at zero and you get a load. But what happens if you get a concurrent load on a different OPENSSL_CTX from a different thread? They both read the ref count as zero at the same time, so they both create a lock.

When do you deallocate the lock? Presumably when the ref count drops to zero during an unload. But again what happens if you get a concurrent load from a different thread?

**Comment by levitte** [comment]
-   In `OSSL_provider_init`:

    1.  RUN_ONCE the refcount initializer (which sets the count to zero) and associated lock creator
    2.  increment the refcount.
    3.  if the refcount's pre-increment value was 0 (or its post-increment value is 1), run the tests.

-   in the `teardown` function:

    1.  decrement the refcount.
    2.  if the refcount's pre-decrement value was 1 (or its post-increment value is 0), destroy the lock.

This *should* make it all correspond to when we dlopen() and dlclose() the module.  If not, we've done something deeply wrong in our core provider code and need to review that mechanism.

**Comment by mattcaswell** [comment]
I don't think you can guarantee when the OS physically unloads the module in response to a dlclose. If the OS has not yet unloaded the module and a new load occurs (or even if a load occurs while an unload is still being processed) then the RUNONCE will not run again (its already been run) and the lock won't get recreated == BOOM.

**Comment by levitte** [comment]
dlopen() / dlclose() is reference counted, that's true, so if you have done multiple dlopen(), the module has been physically loaded only once.  So your question is really, what happens when dlclose() has counted down its reference count to zero?

I have a counter question: what does dlopen() do with .bss and .data (or whatever they are named) sections, especially when its pre-increment reference count is zero?  Should it not properly initialize those memory sections (especially the .data ones), i.e. reload them from file or something similar?  Like, if I'm a library writer, and have `int foo = 123` somewhere in my code, *why should I expect it do be initialized differently depending on if it was loaded before or not?*

**Comment by levitte** [comment]
From [dlopen(3)](http://man7.org/linux/man-pages/man3/dlopen.3.html):

> If the same shared object is opened again with dlopen(), the same object handle is returned.  The dynamic linker maintains reference counts for object handles, so a dynamically loaded shared object is not deallocated until dlclose() has been called on it as many times as dlopen() has succeeded on it.  Constructors (see below) are called only when the object is actually loaded into memory (i.e., **when the reference count increases to 1**).

(emphasis mine)

**Comment by levitte** [comment]
From the [LoadLibraryA manual](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibrarya):

> The system maintains a per-process reference count on all loaded modules. Calling LoadLibrary increments the reference count. Calling the FreeLibrary or FreeLibraryAndExitThread function decrements the reference count. *The system unloads a module when its reference count reaches zero* or when the process terminates (regardless of the reference count).

**Comment by levitte** [comment]
The only case I can see where we might need to be careful is if the module is somehow treated as a `nodelete` module.  This is the case for VMS (there, modules are only unloaded at program exit).  The solution is quite easy, though...  simply never deallocate the lock in that case.

**Comment by mattcaswell** [comment]
I don't think either of those references tell us whether an OS unloads a library immediately, or whether it may defer it for a short while. In any case, even if it doesn't, it still doesn't solve the problem of what happens if a load occurs while an unload is still being processed.

**Comment by mattcaswell** [comment]
> Possibly we can go for the ".ini"/".fini" solution but fallback to the run-the-tests-on-every-load solution for any platforms where this is not possible (or just using an unknown compiler where we don't know how to do it).

Another option I just thought of which might be preferable is to use RUN_ONCE to initialise a lock. The lock is then freed in a ".fini" section - or if the platform doesn't support that then we just simply leak the lock.

**Comment by richsalz** [comment]
One thing that might help is to keep in mind the target platforms.  First, obviously, the platforms that the project and sponsors picked, which are basically Linux Windows iOS, right?  Probably need to check if iOS supports the ini/fini approach.  If you want to do more than that, a good place to look is the list of platforms in the 1747 NIST certificate (and the follow-ons maybe), which at a rough glance seem to be all Linux.

**Comment by levitte** [comment]
> I don't think either of those references tell us whether an OS unloads a library immediately, or whether it may defer it for a short while. In any case, even if it doesn't, it still doesn't solve the problem of what happens if a load occurs while an unload is still being processed.

It doesn't really matter if the OS defers physical unload or not when its refcount drops below 1, what matters is its behaviour when loading it again.  The result of an OS *load* of a module should be consistent in this regard.  If not, you've found a race condition that I would regard as a bug in the OS.

As for the load while an unload is in progress, are you talking about OS code or our code?  I just looked at `ossl_provider_free()`, and it does appear we may need to add a bit of locking there that we didn't think of...

**Comment by mattcaswell** [comment]
> It doesn't really matter if the OS defers physical unload or not when its refcount drops below 1, what matters is its behaviour when loading it again. The result of an OS load of a module should be consistent in this regard. If not, you've found a race condition that I would regard as a bug in the OS.

There is no requirement for dlclose to unload a module when its refcnt drops to 0:

https://pubs.opengroup.org/onlinepubs/007904975/functions/dlclose.html

"The use of dlclose() reflects a statement of intent on the part of the process, but does not create any requirement upon the implementation, such as removal of the code or symbols referenced by handle. "

**Comment by levitte** [comment]
> There is no requirement for dlclose to unload a module when its refcnt drops to 0:

Please re-read what I wrote.  I'm trying to have us explore about what dlopen() or corresponding does or doesn't...

**Comment by mattcaswell** [comment]
I re-read what you wrote. My understanding is that you get no guarantee from dlopen about static variables being reset etc if the refcnt is 0.

E.g. See:
https://stackoverflow.com/questions/24467404/dlclose-doesnt-really-unload-shared-object-no-matter-how-many-times-it-is-call

**Comment by levitte** [comment]
This is an interesting piece from the dlopen(3) manual:

> **RTLD_NODELETE** (since glibc 2.2)
> Do not unload the shared object during **dlclose()**.  Consequently, the object's static and global variables are  not  reinitialized if the object is reloaded with **dlopen()** at a later time.

Does that mean that they are otherwise initialized?

**Comment by mattcaswell** [comment]
Some C libraries behave differently to glibc and provide no guarantee of static data being reset:

https://wiki.musl-libc.org/functional-differences-from-glibc.html#Unloading-libraries

**Comment by richsalz** [comment]
>Some C libraries behave differently to glibc and provide no guarantee of static data being reset:

Consider not supporting those libraries and making those platforms do some work in order to get their own validation.

**Comment by levitte** [comment]
So musl implies mandatory `nodelete`? Is it possible to ensure we know this (through configuration), i.e have a flag macro for it (such as `OPENSSL_USE_NODELETE`)? In that, we should be able to deal with it, no?

**Comment by mattcaswell** [comment]
If we go with my suggestion of RUN_ONCE to init a lock, and free the lock in the ".fini" if we are able, then none of the above makes any difference. It works in all scenarios.

**Comment by levitte** [comment]
True. OK, sounds like a plan (and let's not forget dllmain)
