### ISSUE TITLE
Header file conflict code bug in windows

### ISSUE THREAD

**Issue by HeMinzhang** [openssl/openssl#9981]
```c++
//reappear bug
#include <openssl/sha.h>
#include <openssl/aes.h>
#include <openssl/evp.h>
#ifndef CPPHTTPLIB_OPENSSL_SUPPORT
#define CPPHTTPLIB_OPENSSL_SUPPORT
#endif
#include <httplib.h>
```

the conflict between the above code and the [httplib project](https://github.com/yhirose/cpp-httplib)
[reappear bug example](https://github.com/HeMinzhang/opensslbug/blob/master/src/makeBug/main.cpp)

[openssl github issue](https://github.com/openssl/openssl/issues/9981)

[httplib github issue](https://github.com/yhirose/cpp-httplib/issues/220)

[Previous discussion in qt bugreport](https://bugreports.qt.io/browse/QTBUG-78642)

**Comment by HeMinzhang** [comment]
[vs2019 c++  bug demo](https://github.com/HeMinzhang/opensslbug/blob/master/vs_src/ConsoleApplication1/ConsoleApplication1/ConsoleApplication1.cpp) 

When the project references both the openssl and httplib codebases, the following code will cause an error.

```c++
//reappear bug
#include <openssl/sha.h>
#include <openssl/aes.h>
#include <openssl/evp.h>
#ifndef CPPHTTPLIB_OPENSSL_SUPPORT
#define CPPHTTPLIB_OPENSSL_SUPPORT
#endif
#include <httplib.h>
```

![QQ截图20190923213700](https://user-images.githubusercontent.com/2683269/65430330-52d2be80-de4a-11e9-9c79-04a42c2a1bc3.jpg)

**Comment by HeMinzhang** [comment]
Operating System:windows 10 x64

openssl version: 1.1.1d, 1.1.1b, 1.1.0 k, 1.1.1 c

**Comment by HeMinzhang** [comment]
@HeMinzhang, I confirmed that it doesn't happen on Mac OS, and looked into the OpenSSL header files. It turns out that the following Windows specific code causes the compile errors.

https://github.com/openssl/openssl/blob/7c2a981ff7ca721a85687dcd972d54361434806f/include/openssl/ossl_typ.h#L68-L75

So I cannot do anything on my side. As @PixlRainbow mentioned, only thing you could do is not to include any OpenSSl headers before httplib.h. Sorry about that. Hope it helps.

https://github.com/yhirose/cpp-httplib/issues/220#issuecomment-534677935

**Comment by HeMinzhang** [comment]
I have found a solution before. For c++ projects, avoid putting openssl and httplib into the class header file (.h, .hpp) to avoid this bug.

**Comment by PixlRainbow** [comment]
@HeMinZhang you do not need to copy and paste all comments made on the other issue into this issue. You can simply ask people to refer to yhirose/cpp-httplib#220

**Comment by levitte** [comment]
Does this mean this issue should be closed?

**Comment by PixlRainbow** [comment]
@levitte no, this is an existing bug that has been isolated to a few lines in OpenSSL code. I was just telling them they did not need to go through the trouble of manually copying comment history to give people background context.

**Comment by levitte** [comment]
The bug is that there's a naming conflict between something (presumably Windows) and OpenSSL, as I understand it. They use some macro names that we use as type names. From the looks of it, it seems that more conflicting macros have been added to "something" (still presumably Windows), that we need a few more undefs. Could that be it? If that is the case, would anyone be willing to point out what macros it is this time?

**Comment by PixlRainbow** [comment]
It's more that if OpenSSL gets referenced twice in two different dependencies of a project, there will be an issue with repeat definition.

**Comment by levitte** [comment]
How do you mean that these redefinitions would happen?  Our public headers are wrapped with guards that should protect against exactly that...  like this (from the 1.0.2 ossl_typ.h):

https://github.com/openssl/openssl/blob/1c10029a68e910d936f9bf011f8c3bb18a05ff8b/crypto/ossl_typ.h#L55-L57

**Comment by levitte** [comment]
Also, from the image above, you can see that `LPCSTR` is involved somehow.  That's a Windows (VS?) type which we don't use in OpenSSL's public definitions.  I can only conclude that there is, in fact, a clash of some sort with something defined elsewhere.

**Comment by slontis** [comment]
@levitte: This seemed a bit strange to me: line 75 of x509.h.
But it also seems there are 2 files with this name..
include/crypto/x509.h &
include/openssl/x509.h

Which is probably not a good idea. I suspect it is pulling in the internal one somehow which is not guarded.

**Comment by mspncp** [comment]
> @levitte: This seemed a bit strange to me: line 75 of x509.h.
> But it also seems there are 2 files with this name..
> include/crypto/x509.h &
> include/openssl/x509.h
> 

openssl/x509.h is the public include file and crypto/x509.h is an internal one, which was moved and renamed from internal/x509_int.h during the reorganization of the header files (#9333) if I recall correctly.

> Which is probably not a good idea. I suspect it is pulling in the internal one somehow which is not guarded.

 I disagree, naturally. There is no ambiguity between these two files, because the include search path is setup in such a way that it is necessary to specify the directory prefix. The prefix acts like a namespace. See for  example:

https://github.com/openssl/openssl/blob/f6dead1b72a04b113b4b198ac98a8b9b994ad86f/crypto/asn1/x_sig.c#L13-L14

**Comment by mspncp** [comment]
Apart from that, the code block quoted in https://github.com/openssl/openssl/issues/9981#issuecomment-534822041 is from commit 7c2a981ff7ca721a85687dcd972d54361434806f, which precedes the include header changes.

**Comment by samuel-lee-msft** [comment]
I was looking for a good issue to start contributing to OpenSSL with and came across this one.

A recent change to httplib actually resolves the reported issue by undef-ing some windows symbols that are already undef-ed in openssl/ossl_typ.h (https://github.com/yhirose/cpp-httplib/pull/1148)

However the underlying problem is still there, and I minimized the failure to the following:
```
#include <openssl/ossl_typ.h>
// this #undef-s X509_NAME, etc. before typedef-ing them

#include <windows.h>
// includes wincrypt.h which #define-s X509_NAME, etc. to special LPCSTR constants

#include <openssl/x509.h>
// includes openssl/ossl_typ.h and uses X509_NAME, etc. typedefs
// ossl_typ.h has already been included above, so the guard prevents a second inclusion
// the Windows #define-s stay in place
```

The team I am a part of in Microsoft actually owns wincrypt.h, so it is possible that we could coordinate better here. I have a few thoughts on possible paths:
1. Short-term ossl_typ.h could _always_ undef the conflicting symbols when _WIN32 is defined. Moving the #undef-s out of the guarded region of ossl_typ.h would mean the second include in the minimized example above would not cause errors. Callers who want to be able to make use of both OpenSSL and Windows symbols in their code will have to make their own copies of the Windows #define-s with a different name (same as today)
If windows.h is included last and the application code relies on the OpenSSL typedefs directly then this approach would not help.
2. Longer term it would make sense for the wincrypt.h #define-s to have a prefix which makes this kind of conflict less likely. To avoid app-compatibility issues we could make the prefix opt-in to begin with. This could be achieved by wincrypt.h adding a prefix to the #define-s if a symbol (say WINCRYPT_OPENSSL_SYMBOL_COMPAT) is defined (we could use HEADER_OPENSSL_TYPES_H directly, but that seems a bit fragile to OpenSSL code changes). Whatever the symbol is, we could #define it in ossl_typ.h alongside the existing #undef-s to automatically avoid the conflict. 

In general going forward it would be great to have reasonable prefixes on both sides to minimize the likelihood of conflict. I think probably the biggest take-away from this is we want to avoid creating _more_ conflicts between OpenSSL and other projects, once there is potential for external code to rely on ambiguous symbols it's messy to fix. It certainly seems sensible to have an OSSL_ prefix on any new types.

Any thoughts?

**Comment by mattcaswell** [comment]
The short term solution seems like a reasonable approach. At least for now. I'm not sure if that would qualify as a bug fix eligible for backport to 3.0/1.1.1 (we normally try to avoid messing with the header files in a stable release)...I'm trying to think if there is any situation where doing that could break something

(2) sounds ideal if it can be arranged...but probably doesn't help for quite a long time down the road when everyone has the new version of wincrypt.h.

> In general going forward it would be great to have reasonable prefixes on both sides to minimize the likelihood of conflict. 

Yes. From OpenSSL's side we are trying to move to using the `OSSL_` prefix for all new features - but we don't do that if we're just adding new things into a namespace we've already "claimed". So, for example, new functions for doing X509 related things will start with `X509_`. Moving away from doing that would be *very* disruptive unfortunately :-(

**Comment by mspncp** [comment]
My recent (user) experience is a different one (see also https://github.com/openssl/openssl/pull/18079#pullrequestreview-938593167): I believe that you need to include the `<windows.h>` header first, with `WIN32_LEAN_AND_MEAN` defined, and afterwards include OpenSSL headers. Then OpenSSL will undefine the colliding symbols automatically.

```C
#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#include <openssl/headers.h>
```

Defining `WIN32_LEAN_AND_MEAN` has two important effects, namely it prevents implicit inclusion of `<wincrypt.h>` and of `<winsock.h>` by `<windows.h>`. In most cases this is sufficient to fix the problem (For applications that not only use OpenSSL but also Winsock2, the `WIN32_LEAN_AND_MEAN` define prevents nasty collisions between the incompatible headers  `<winsock.h>` and  `<winsock2.h>`.)

**Comment by mspncp** [comment]
@samuel-lee-msft since you are a Microsoft employee, could you please ask your colleagues why `<winsock.h>` is still included from `<windows.h>` by default, even though it is obsolete and incompatible to `<winsock2.h>`?

**Comment by mspncp** [comment]
See https://docs.microsoft.com/en-us/windows/win32/winsock/creating-a-basic-winsock-application

![grafik](https://user-images.githubusercontent.com/11467854/162837184-cc6755ad-1bc6-4582-b9cc-e490176f3a42.png)

**Comment by samuel-lee-msft** [comment]
It seems likely that winsock.h is included in windows.h for backwards compatibility - in general we do not want to break code which is compiling today by header file changes, and there are presumably (old) applications that include windows.h and use winsock.h functionality.

I will ask around to see if there are any plans to remove winsock.h from windows.h

**Comment by samuel-lee-msft** [comment]
@mspncp FYI including <winsock2.h> _before_ <windows.h> also avoids the conflict with <winsock.h>, without the need for defining WIN32_LEAN_AND_MEAN. This is at least a little bit less hairy - I can look to get the documentation updated to also include this option.
The consensus from my conversations is that the removal of <winsock.h> from <windows.h> by default is unlikely as it will undoubtedly cause compatibility problems with existing code.

W.r.t. the issue at hand of OpenSSL vs. wincrypt.h conflicts.
The httplib scenario that started this thread was directly including wincrypt.h - not windows.h, so WIN32_LEAN_AND_MEAN is not applicable.
If there are applications that need (some of) the symbols in wincrypt.h and OpenSSL symbols, then I think the PR I have is a step in the right direction.

If we are happy to say that wincrypt.h must always be included before any OpenSSL headers, then we can maybe close this issue with some documentation update instead.

**Comment by mspncp** [comment]
> The httplib scenario that started this thread was directly including wincrypt.h - not windows.h, so WIN32_LEAN_AND_MEAN is not applicable.

I think that httplib is an untypical case, because it has a header-only implemtation which is intended to be included into a single C-module. For a general purpose HTTP library, I would consider it bad style or at least lack of abstraction to include implementation-specific headers like wincrypt.h or the openssl header. If at all, it should use forward declarations.

> If we are happy to say that wincrypt.h must always be included before any OpenSSL headers, then we can maybe close this issue with some documentation update instead.

As soon as two third party libraries include mixed Wincrypt and OpenSSL headers, than it's impossible to follow that guide. But as I said, it's the third party library headers that need to be fixed imho.

> If there are applications that need (some of) the symbols in wincrypt.h and OpenSSL symbols, then I think the PR I have is a step in the right direction.

It may help, or maybe not. I'm not sure whether it will work in all constellations. In any case, I am opposed to the name `WINCRYPT_OPENSSL_SYMBOL_COMPAT`, it should be a more generic name like `WINCRYPT_[USE_]SYMBOL_NAMESPACE` or something like that. You can mention OpenSSL as an example in the preceding comment, but please don't make it part of the \#define's name.

**Comment by samuel-lee-msft** [comment]
Sounds good. Tomorrow I will close and reopen the PR to clear the need CLA tag, and change the #define name.

**Comment by mspncp** [comment]
I think your pull request should be amended by build tests checking different possible include orderings of Wincrypt and OpenSSL headers. You can find examples of such build tests here: 

https://github.com/openssl/openssl/blob/02119faee397565525151eb2ce39c424d129d287/test/generate_buildtest.pl#L17-L34

This code snippet from the `generate_buildtest.pl` script is actually a template from which the source code files are auto-generated, one for each public header file, with some exceptions (see also issue #18108):


https://github.com/openssl/openssl/blob/02119faee397565525151eb2ce39c424d129d287/test/build.info#L930-L949


In your case, a single example for every interesting permutation of `<wincrypt.h>` with a fixed choice of OpenSSL headers might be sufficient, like for example:

```C
/*
 * Check for symbol collisions between Wincrypt and OpenSSL headers 
 */
 
 
#ifdef _WIN32
# include <wincrypt.h>
#endif

#include <openssl/opensslconf.h>
#ifndef OPENSSL_NO_STDIO
# include <stdio.h>
#endif

#include <openssl/aes.h>
#include <openssl/evp.h>
#include <openssl/x509.h>
#include <openssl/x509v.h>

int main(void)
{
    return 0;
}
```
So you might not need to auto-generate it, just add these build tests explicitly.

The build tests should run on all platforms, with `<wincrypt.h>` guarded by `_WIN32` or whatever is most suitable. _(Note that I did not add `#ifndef OPENSSL_NO_FOO` guards around the `#include <openssl/foo.h>` statements, because none of those headers can be disabled by configuration (anymore).)_

@levitte might be able to give you more advice on the best way how to add those tests.

**Comment by mspncp** [comment]
You could also add tests to demonstrate the use of your new `WINCRYPT_[USE_]SYMBOL_NAMESPACE` define. Either right away, or later, when it's available. Ideally, those tests should seed for old and new versions of `wincrypt.h`.

**Comment by mspncp** [comment]
Sorry, my last two comments should better have been posted in pull request #18079, not here. I will repost them there.
