### ISSUE TITLE
openssl 1.1.1d breaks openssh login

### ISSUE THREAD

**Issue by z3ntu** [openssl/openssl#9984]
Hi, I've noticed that openssl 1.1.1d breaks openssh sshd by not being able to log in anymore. On the `ssh` side, you get the message `client_loop: send disconnect: Broken pipe` and on the `sshd` side, you there is `fatal: privsep_preauth: preauth child terminated by signal 31` in the log.

I've traced this back to the upgrade of openssl from 1.1.1c to 1.1.1d and a git bisect resulted in commit 3ff98f558157ada23a3527d82793a524eb8263ec ("Start up DEVRANDOM entropy improvement for older Linux devices.") breaking it.

This problem was observed on ARM with kernel 3.4 and kernel 3.10 on postmarketOS (based on Alpine Linux)

Unfortunately I don't have a "minimal sample" for reproducing because I'm not really sure what code in openssl is called by this procedure in openssh (I've put a bunch of printfs into openssh but I didn't find out anything useful)

**Comment by abelbeck** [comment]
I have seen this issue as well on x86, glibc 2.18 and kernel 3.16.69 using openssh 8.0p1.

It seems this issue is related to openssh-portable and the default build option:
```
--with-sandbox=seccomp_filter
```
Recompiling openssh 8.0p1 with:
```
--with-sandbox=rlimit
```
works around the problem.

So to my eye it looks like with OpenSSL 1.1.1d additional calls need to be allowed in here:

https://github.com/openssh/openssh-portable/blob/master/sandbox-seccomp-filter.c

in order for the seccomp_filter sandbox to work.

**Comment by petrovr** [comment]
Luca Weiss wrote:
> Hi, I've noticed that openssl 1.1.1d breaks openssh sshd by not being able to log in anymore. On the `ssh` side, you get the message `client_loop: send disconnect: Broken pipe` and on the `sshd` side, you there is `fatal: privsep_preauth: preauth child terminated by signal 31` in the log.
>
> I've traced this back to the upgrade of openssl from 1.1.1c to 1.1.1d and a git bisect resulted in commit 3ff98f558157ada23a3527d82793a524eb8263ec ("Start up DEVRANDOM entropy improvement for older Linux devices.") breaking it.
>
> This problem was observed on ARM with kernel 3.4 and kernel 3.10 on postmarketOS (based on Alpine Linux)
>
> Unfortunately I don't have a "minimal sample" for reproducing because I'm not really sure what code in openssl is called by this procedure in openssh (I've put a bunch of printfs into openssh but I didn't find out anything useful)

One is test for "syscall(__NR_getrandom, buf, buflen, 0);" for insatnce :

#include <stdio.h>

#define _GNU_SOURCE
#include <unistd.h>
#include <sys/syscall.h>

int
main() {
   long r;
   unsigned char buf[64];
   size_t buflen;

   buflen = sizeof buf;
   r = syscall(__NR_getrandom, buf, buflen, 0);
   if (r < 0) {
     perror("syscall(__NR_getrandom, ...) fail");
     return 1;
   }
   printf("syscall(__NR_getrandom, ...) return %ld\n", r);

   return 0;
}


Another one is to test if system support getentropy.

**Comment by z3ntu** [comment]
```
syscall(__NR_getrandom, ...) fail: Function not implemented
```
And getentropy is available in musl libc but it's just a wrapper around getrandom so it fails also because the syscall is not implemented in the kernel.

**Comment by petrovr** [comment]
Luca Weiss wrote:
> ```
> syscall(__NR_getrandom, ...) fail: Function not implemented
> ```
> And getentropy is available in musl libc but it's just a wrapper around getrandom so it fails also because the syscall is not implemented in the kernel.
> 

So if getrandom does not work (#ifdef OPENSSL_RAND_SEED_GETRANDOM) code 
will use block in #ifdef OPENSSL_RAND_SEED_DEVRANDOM ) - see rand_unix.c.

As configuration allows us to specify seed source reported case could be 
reproduced on new linux if OpenSSL is build with flag 
--with-rand-seed=devrandom.

Test with pkix-ssh code shows :
...
debug3: mm_send_keystate: Finished sending state [preauth]
debug1: monitor_read_log: child log fd closed
privsep_preauth: preauth child terminated by signal 31
...
It is important to look into errors before '...terminated...' . This 
mean that authentication process succeed and unapproved system call is 
"at exit".


Quick look into Alpine Linux (as reported postmarketOS is based on it) 
shows use of openrc system where is used file /var/lib/misc/random-seed 
to initialize random generator.
Perhaps reporter could confirm.


I guess that OpenSSL problem code is not needed on all those Linuxes 
that use OpenRC init program and so issue could be avoided when openssl 
is build with -DOPENSSL_RAND_SEED_DEVRANDOM_SHM_ID=-1 .



Regards,
Roumen Petrov

**Comment by z3ntu** [comment]
Even though I didn't really understand half of your comment, I built openssl with the `-DOPENSSL_RAND_SEED_DEVRANDOM_SHM_ID=-1` flag, installed it and openssh works properly with OpenSSL 1.1.1d

As for `/var/lib/misc/random-seed` , this file does not exist on my installation

**Comment by abelbeck** [comment]
Looking at `crypto/rand/rand_unix.c` (openssl 1.1.1d) function `wait_random_seeded()`

If `OPENSSL_RAND_SEED_DEVRANDOM_SHM_ID >= 0` (by default it is `114` unless built with `-DOPENSSL_RAND_SEED_DEVRANDOM_SHM_ID=-1`)

The following functions are called:
```
shmget(...)
open(DEVRANDOM_WAIT, O_RDONLY)
shmat(...)
```
Then, looking at openssh's `sandbox-seccomp-filter.c`

https://github.com/openssh/openssh-portable/blob/master/sandbox-seccomp-filter.c

The `open` is among the "Syscalls to non-fatally deny" and any shared memory calls will exit the sandbox (as we see with "preauth child terminated").

It appears, until this is fixed in openssh-portable, either build openssh with `--with-sandbox=rlimit` or build openssl 1.1.1d with `-DOPENSSL_RAND_SEED_DEVRANDOM_SHM_ID=-1`.

Which is least worse ?  Possibly openssh `--with-sandbox=rlimit` and not messing with openssl.

**Comment by z3ntu** [comment]
@abelbeck So this is not really an openssl issue then but the new syscall has to be allowed in sandbox-seccomp-filter.c in openssh?

**Comment by abelbeck** [comment]
@z3ntu Yes, that is how I see it.  The openssh-portable configure will default to `--with-sandbox=seccomp_filter` if the kernel supports it, building openssh with `--with-sandbox=rlimit` uses a simpler sandbox.

**Comment by petrovr** [comment]
Luca Weiss wrote:
> @abelbeck So this is not really an openssl issue then but the new syscall has to be allowed in sandbox-seccomp-filter.c in openssh?
> 

I cannot see why to allow one more syscall.
On fork child inherit shared memory.
I'm not familiar enough with shared memory management but according 
documentation all segments are detached automatically "at exit".
Child "Termination" is "at exit".


Regards,
Roumen Petrov

**Comment by petrovr** [comment]
Hi Luca,

Luca Weiss wrote:
> Even though I didn't really understand half of your comment, I built openssl with the `-DOPENSSL_RAND_SEED_DEVRANDOM_SHM_ID=-1` flag, installed it and openssh works properly with OpenSSL 1.1.1d
> 
> As for `/var/lib/misc/random-seed` , this file does not exist on my installation
> 

I don't know you OSes.

AlpineLinux documentation point to openrc as "init system" and following 
link
https://raw.githubusercontent.com/OpenRC/openrc/72df51e17ba0e1a0f94451b4bbfb338288c4625c/init.d/urandom.in 
do seed tricks.

Package for instance 
https://pkgs.alpinelinux.org/packages?name=openrc&branch=edge

postmarketOS is announced as alpha . may be is defect.


Regards,
Roumen Petrov

**Comment by abelbeck** [comment]
I created a PR over at openssh-portable
https://github.com/openssh/openssh-portable/pull/148

Works in my testing.

**Comment by djmdjm** [comment]
OpenSSH takes care to explicitly seed OpenSSL's PRNG after the unprivileged process is forked but before applying the seccomp sandbox by RAND_seed()-ing a seed and calling RAND_bytes() to read a value back. It's therefore surprising that OpenSSL is making syscalls to determine its seeded state. 

sshd won't allow the shm* syscalls in its sandbox as they could be used to interact with SHM segments outside the sandbox. Our inclination is to have the sandbox make these syscalls unconditionally fail with errno=EACCESS, but we want to be confident that OpenSSL will do the right thing in this case.

BTW OpenSSH isn't the only program to run libcrypto in a strict syscall sandbox, so IMO you should take care to ensure this case works properly.

**Comment by abelbeck** [comment]
@djmdjm : With more testing, at least for my case with OpenSSH_8.0p1 and Linux 3.16.74, the `shmget` and `shmat` calls succeed before the sandbox and only the `shmdt` call occurs within the sandbox via the `OPENSSL_atexit(&cleanup_shm)` call.

Reference for OpenSSL `wait_random_seeded()` function:
https://github.com/openssl/openssl/blob/OpenSSL_1_1_1d/crypto/rand/rand_unix.c#L373

It was bugging me if `shmget` failed then `uname` would need to be allowed, but that did not  seem to happen.

So as the onion is peeled here, with `shmget` and `shmat` calls succeeding, should the corresponding `shmdt` be allowed to also succeed in the sandbox ? What would be the effect if `shmdt` always failed, a memory leak ?

**Comment by paulidale** [comment]
There is no harm if the `shmdt` call fails.  The segment will be detached on process exit, this is more for neatness than anything else.

**Comment by petrovr** [comment]
> ... The segment will be detached on process exit, this is more for neatness than anything else.

This was my point 7 day ago - https://github.com/openssl/openssl/issues/9984#issuecomment-535097914 .
Any chance to remove "extra" clean-up?

**Comment by abelbeck** [comment]
Agreed, removing this "extra" `shmdt` clean-up would indirectly add security for the x86_32 case with OpenSSH and older kernels (3.16.x).

Using `__i386__` the include `asm/unistd_32.h` does not support `__NR_shmdt`. As such, at least for 32-bit Linux 3.16.x  `--with-sandbox=rlimit` is needed to work with the new `wait_random_seeded()` OpenSSL 1.1.1d feature.

**Comment by kroeckx** [comment]
@bernd-edlinger: Since #10044 we now always use getrandom on kernels >= 3.19, and on older kernels we now read 1 byte from /dev/random and then switch to /dev/urandom. But I understand that reading of 1 byte was only needed for kernels > 3.19, but I don't know which version. Do you think it's possible to switch to poll() for kernels were we don't need this 1 byte read and avoid the shm* calls?

**Comment by bernd-edlinger** [comment]
The original implementation did always do a poll, before using /dev/urandom.
That is in itself non-destructive to the entropy pool.
The only caveat is that there might be other processes reading from /dev/random
which would make the poll block (that is IMHO a purely theoretical objection).
The implicit assumption was that the linux version is not >= 4.8, because
it was already known from the beginning, that the CRNG implementation pulls
all available entropy from the input pool every 5 minutes.  So the poll
starts to hang.  And also reading 1 byte proves nothing on v4.8 and newer,
in contrary it can delay the initial seeeding of the CRNG.

**Comment by z3ntu** [comment]
Closing as https://github.com/openssh/openssh-portable/pull/149 fixes this issue. Special thanks to @abelbeck for creating a fix! :)

**Comment by paulidale** [comment]
There were problems with always using `select(2)` and I assume `poll(2)`:

- As @bernd-edlinger noted: using `select(2)` opens up a denial of service attack whereby an attacker can force newly started OpenSSL instances to block forever.  The shared memory segment is acting as a flag indicating that at some time in the past `/dev/urandom` was known good.
- The `poll(2)` system call might not be available on some older kernels (some small embedded devices do still use 2.0 kernels).

The single byte read will only happen if the file descriptor for `/dev/random` is too large for an `fd_set`, otherwise `select(2)` is used and zero bytes are read.  I expect that the latter will almost always be the case.

**Comment by abelbeck** [comment]
@paulidale : Just curious, could the `/proc/sys/kernel/random/entropy_avail` value be used instead of `select(2)` readability of `/dev/random` ?
